### ISSUE TITLE
`getAddLiquidity` estimate fails

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10007]
UI is calling `getAddLiquidity` to get add additional liquidity to an existing AMM, the estimates the call fails. 

```
...    
const lpTokens = await amm.callStatic.addLiquidity(cash.toFixed(), recipient);`
...
```

this call fails in `packages/augur-sdk-lite/src/api/AMM.ts`

User has been approved and has added liquidity before in prototype.

example is:
getAddAmmLiquidity 0x5FAD85B1e89d6a482705a7D04c0bEE70b6D227A5 
amm address 0x8fc4a6b8a995930574c17da7c685de13766111b4 
use eth: true 
marketId 0x0599f7e51b41673ec1cea31e088c2ee041d22fbb 
sharetoken 0x76eCfb6d07DF1A1bD31f485D7160b201C64f878E 
0 1000000000000000000 No 0.51 Yes 0.49

**Comment by robert-e-davidson3** [comment]
FYI this call will only work if the AMM already has liquidity. The call for estimating initial liquidity is callStatic.addInitialLiquidity.

**Comment by robert-e-davidson3** [comment]
```
  async getAddLiquidity(
    recipient: string,
    existingAmmAddress: string,
    hasLiquidity: boolean,
    market: string,
    paraShareToken: string,
    fee: BigNumber,
    cash: BigNumber = new BigNumber(0),
    longPercent = new BigNumber(50),
    shortPercent = new BigNumber(50)
  ): Promise<BigNumber> {```

The middleware depends on the UI to tell it if the AMM has liquidity or not using the `hasLiquidity` parameter. This was in the original API so I kept it but the middleware could do a call to verify for itself.

**Comment by bthaile** [comment]
tested and works, there were a few issues with passing in parameters depending on if amm existed or not and if there is no liquidity.

pushing to done
