### ISSUE TITLE
Reporting dispute link from market page

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#1001]
Should be able to click on a button on the market page that links to the dispute page for that market, would help when linking things + for user convenience

**Comment by phoebemirman** [comment]
there is a button on the market page for disputing. can this be closed?

<img width="1440" alt="screen shot 2019-02-12 at 10 31 20 am" src="https://user-images.githubusercontent.com/6775839/52659070-62038e00-2eb1-11e9-9c22-cd9eb3e9df44.png">

**Comment by joeykrug** [comment]
yes
