### ISSUE TITLE
Primary Button disabled doesn't look correct in trade form

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10025]
![image](https://user-images.githubusercontent.com/3970376/104046772-345f1680-51a6-11eb-8c86-a3dca98c6d29.png)

**Comment by bconfortin** [comment]
The layout for the PrimaryButton is correct, it should look faded green.
We introduced a BuySellButton which is styled like the designs, with faded gray being the disabled state.
Closing.
