### ISSUE TITLE
tooltip drop shadow

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#10028]
- add drop shadow to tooltip arrow for place top, place bottom etc

For tooltip styling and drop shadow please see the design at the bottom of this frame https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Simplified-UI?node-id=309%3A2852

**Comment by bconfortin** [comment]
Can't add borders AND shadows because the tooltip's arrow itself is a border. I can, however, use a solid shadow filter to mimic a border.

Talked to Matt and he prefers to have borders instead of shadows, so I'm closing this ticket.
