### ISSUE TITLE
User accounts stats component is jumping up and down a few pixels when switching between markets and portfolio

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#10031]

**Comment by JohnDanz** [comment]
We have disabled portfolio if you aren't logged in which should sidestep this issue for MVP. still something we should work out eventually just so we better understand how we got this issue. the key to getting it is being not-logged-in and attempting to navigate To or From the Portfolio view. you will see an obvious screen jump/draw issue.
