### ISSUE TITLE
Update Favicon

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#10048]
If you need a different size or format to the png below, let me know.

![Augur_Favicon](https://user-images.githubusercontent.com/39496225/104229165-2cc09b80-544c-11eb-9309-9ea0618631bf.png)

**Comment by JohnDanz** [comment]
pretty sure this is done now. closing.

**Comment by matt-bullock** [comment]
@JohnDanz reopening because I unless you have the PNG above (logo in white circle) it's not correct. We need it in white to show up on both light and dark mode browsers
