### ISSUE TITLE
Full breakdown needed from getAddLiquidity

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10061]
currently `getAddLiquidity` returns a BigNumber. it actually has a weird data structure that needs to be reshaped. 

I'd like a similar breakdown as `getRemoveLiquidity` basically what is needed 

```
export interface AddLiquidityRate {
  short: BigNumber
  long: BigNumber
  cash: BigNumber
  lpTokens: BigNumber
}

```

**Comment by justinbarry** [comment]
Also going to move the calculation entirely to the middleware.
