### ISSUE TITLE
Mobile Only: maket page tags and icons fix

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#10067]
These are designed to be smaller on mobile than on desktop

- Height for all should be 32px
- font size for all should be 12px Reg

Design: https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Simplified-UI?node-id=1024%3A1045

![image](https://user-images.githubusercontent.com/39496225/104296655-34bb2280-54c2-11eb-9e46-7f1e12bf74fa.png)

**Comment by JohnDanz** [comment]
I did this as part of another pr, closing
