### ISSUE TITLE
Add resolved and in settlement tags to market page

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#10094]
Desktop (sits 12px to the left of market currency)

Designs: https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Simplified-UI?node-id=319%3A3202

![image](https://user-images.githubusercontent.com/39496225/104344341-51288080-54fd-11eb-9430-80ab329d8681.png)

---

For mobile it's tighter for space so this tag will need to sit above the other tags.

Note that mobile tags are different (smaller font size and overall size) https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Simplified-UI?node-id=319%3A3202

![image](https://user-images.githubusercontent.com/39496225/104344711-cb590500-54fd-11eb-8c26-4e21baf48356.png)

16px space top and bottom (between header bar and category tags)

![image](https://user-images.githubusercontent.com/39496225/104344841-f2afd200-54fd-11eb-8ba2-04dc5b582c12.png)

**Comment by JohnDanz** [comment]
I merged in a slightly modified change to what is described here, take a look and see if it's good enough for MVP -- if not we can revisit and I can adjust it.

**Comment by matt-bullock** [comment]
tag is showing as 14px on desktop; should be 16px. Rest looks good

![image](https://user-images.githubusercontent.com/39496225/104759533-56d1d080-5760-11eb-989a-881e8cab3fd4.png)

**Comment by matt-bullock** [comment]
@JohnDanz can you update the background colour of these from 5% to 10%. 5% looks a bit weak on chrome
