### ISSUE TITLE
Settings menu additional requirements

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#10106]
Design: https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Simplified-UI?node-id=309%3A80

![image](https://user-images.githubusercontent.com/39496225/104449096-5be72200-559e-11eb-9582-1a762659602e.png)

Slippage tolerance needs tooltip @Chwy5  to supply copy

Show invalid markets filter toggle @Chwy5 to supply copy for tooltip

Ignore dark mode for now.. this can be added to a  future release when ready

**Comment by Chwy5** [comment]
Add this for the tooltip:

The maximum percentage allowed for the price change between the market price and the estimated price.

**Comment by Chwy5** [comment]
Slippage tooltip:

The maximum percentage the price can change and still have your transaction succeed

**Comment by Chwy5** [comment]
Invalid Tooltip:

Filters out markets which are likely to resolve to "Invalid" based upon the current trading price of the "Invalid" outcome.
