### ISSUE TITLE
user ETH balance bleeding over currency

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10102]
![image](https://user-images.githubusercontent.com/3970376/104380656-f4bf6400-54f0-11eb-95bc-9b43e91b335c.png)

**Comment by matt-bullock** [comment]
Better to cut it 8px before the currency icon rather than half way across the input

![image](https://user-images.githubusercontent.com/39496225/104761197-d3fe4500-5762-11eb-9d53-41cca9a5fef2.png)
