### ISSUE TITLE
Problems in the Order ticket

### ISSUE THREAD

**Issue by bconfortin** [AugurProject/augur#10149]
I've spotted a few errors in the Order ticket

1. When logged out, I can still write in the "Amount" input.
- When I'm buying, it doesn't crash but it show a few error messages in the console. Not sure if the error section should be displayed but it currently says "Insufficent Liquidity". If anything, it should say something like "Please login".
- When I switch to the sell view and I have a value written in the input, it crashes right away.
- Just came to mind: if you logout and you are in that screen, maybe erase the input instead of just disabling it?
![Captura de Tela 2021-01-14 às 19 50 54](https://user-images.githubusercontent.com/10351013/104659558-97b7df80-56a3-11eb-93bf-190176e249b9.png)
2. When logged in, I see a few `NaN` when trying to sell.
![Captura de Tela 2021-01-14 às 20 04 14](https://user-images.githubusercontent.com/10351013/104659644-c33aca00-56a3-11eb-8348-8745c2fe6b8c.png)
![Captura de Tela 2021-01-14 às 20 04 19](https://user-images.githubusercontent.com/10351013/104659648-c5048d80-56a3-11eb-89b9-717681e75b0a.png)

**Comment by JohnDanz** [comment]
theses are fixed and the concept of disabling the input is up for debate for mvp. closing
