### ISSUE TITLE
pool percentage calc off, rounding of lp token estimate

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10146]
![Screen Shot 2021-01-14 at 16 18 59](https://user-images.githubusercontent.com/3970376/104656146-709de580-5684-11eb-821e-94ffe5c25cc8.png)

- calc for user's percentage of pool needs to add to totalSupply to get correct percentage when user would be adding more liquidity than exists in current amm.
- round lp tokens from middleware

**Comment by Chwy5** [comment]
fixed closing
