### ISSUE TITLE
Can't add liquidity to existing ETH amm when the amm has no liquidity

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10158]
![image](https://user-images.githubusercontent.com/3970376/104668323-7bb13f80-569d-11eb-8b7a-1b9a0f406aea.png)

2 issues:
1. estimate add liquidity call fails
2. the call to middleware never returns and no meta mask pop up.

**Comment by Chwy5** [comment]
still not working

**Comment by Chwy5** [comment]
fixed closing
