### ISSUE TITLE
conversion issue with balance passed into remove liquidity

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10160]
![image](https://user-images.githubusercontent.com/3970376/104670074-cb453a80-56a0-11eb-9e6c-dc0502971d78.png)

1. Issue is USDC value gets passed into get Remove liquidity estimate that causes to fail, since user has less lp tokens than USDC amount.

2. When estimation does succeed the MM doesn't pop up so user can't sign transaction. Saw on USDC amm.

typing in a lower amount will allow the user to remove liquidity

The amount typed in to remove was 100 and 500 lp tokens. The values below are wrong compared to what the user typed in. Need to check values on graph transactions to see if there is a conversion error when displaying.

![image](https://user-images.githubusercontent.com/3970376/104670495-8ec60e80-56a1-11eb-8600-497683d83a21.png)

**Comment by bthaile** [comment]
Issue here was min amount was calculated incorrectly because of rounding up error. fixed

**Comment by Chwy5** [comment]
closing
