### ISSUE TITLE
Failing remove liquidity scenario

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10174]
Multiple users add liquidity on 50/50 amm.
user A adds 10 cash
user B adds 5 cash

user B tries to remove all lp token with alsoSell set true.
getRemoveLiquidity estimation fails

**Comment by robert-e-davidson3** [comment]
I wrote a contract-level test but it does not replicate the behavior you see. The middleware is just calling the contract method and it's one that doesn't require approvals.

I don't see how but perhaps the LP token calculation fix also fixed this. Try to repro to verify?
