### ISSUE TITLE
lack of liquidity trading form output should show dashes

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10198]
![image](https://user-images.githubusercontent.com/3970376/104946593-f28d5780-597f-11eb-8f00-53f61e9e2bc1.png)

![image](https://user-images.githubusercontent.com/3970376/104946757-3b451080-5980-11eb-8b8a-f5777e7ce999.png)

button should say insufficient liquidity

**Comment by Chwy5** [comment]
fixed - closing
