### ISSUE TITLE
Implement market creation block (date)

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur#102]
createMarket contract has implemented a very terse log/event that effectively gives us a lookup for a particular markets creation block.  implemented this in market loading so we can sort on it.

**Comment by scottzer0** [comment]
This is proving difficult.  In my experiments with `createMarketContract.createDate({ market: [marketId]}).watch(function(err, result) { console.log( result ) });`
i found the response to be really slow.  it's unclear what the issue is here, as i have found that other event/log fetching to be fast.

tabling this for now.

**Comment by tinybike** [comment]
It might make sense to just add the creation block number as contract data for now, since implementing this as a log/event has been tricky.  It is a small extra cost, but in my view we shouldn't "let the perfect be the enemy of the good".

**Comment by tinybike** [comment]
Implemented `creationBlock` event bindings in AugurProject/augur.js@8c84eac44cf24c046b1fddb21f602cc0f47cc8ed.  Full support in the client added in 4645ee0b77ad57bb2edbdbf184f431fa8c863de8; market cache support added in AugurProject/marketeer@010ce77638718f32c0c8b9abca69823001fafedb.
