### ISSUE TITLE
filled orders

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1020]
<img width="695" alt="screen shot 2019-02-12 at 9 40 33 am" src="https://user-images.githubusercontent.com/6775839/52656063-6c6e5980-2eaa-11e9-87da-7a941fbeaafc.png">

To do:

- [ ] don't show filled orders for resolved markets in the filled orders quad.
- [ ] change dropdown to say `View By Most Recently Traded Market` and `View By Most Recently Traded Outcome`

**Comment by bthaile** [comment]
After conversation we're going to change dropdown wording, see description

this is the first release. We've discussed next step, which would be to add a sub sort bar.

Primary bar will be market specific sorting, will sort by "end time", "creation time", "last traded"
Sub bar would allow user to change view by "market" or by "time"

**Comment by bthaile** [comment]
don't filled open orders for resolved markets in the filled orders quad.
