### ISSUE TITLE
Amount Input user inputted amount not passed to trade

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10206]
![Screen Shot 2021-01-18 at 12 56 44](https://user-images.githubusercontent.com/3970376/104953901-eeb40200-598c-11eb-8096-d3f39abffcd0.png)

user amount typed into input doesn't get passed to trade method, the user's balance gets passed in.

**Comment by JohnDanz** [comment]
Having trouble reproducing this, will keep an eye out.
