### ISSUE TITLE
open orders table

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1021]
<img width="701" alt="screen shot 2019-02-12 at 9 40 28 am" src="https://user-images.githubusercontent.com/6775839/52656093-7b550c00-2eaa-11e9-8bba-3b6f04fcd25f.png">

- [ ] don't show open orders for resolved markets in the filled orders quad.
- [ ] change dropdown to say `View By Most Recently Traded Market` and `View By Most Recently Traded Outcome`

**Comment by bthaile** [comment]
After conversation we're going to change drop down wording see description.

this is the first release. We've discussed next step, which would be to add a sub sort bar.

Primary bar will be market specific sorting, will sort by "end time", "creation time", "last traded"
Sub bar would allow user to change view by "market" or by "time"

**Comment by bthaile** [comment]
don't show open orders for resolved markets in the filled orders quad.
