### ISSUE TITLE
display decimal consistently

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10226]
comprehensive list
- price: 2 decimals
- USDC values 2 decimals
- ETH values 4 decimals
- Share values 4 decimals

**Comment by JohnDanz** [comment]
should update formatPrice/formatShares/formatEth/formatUSDC in simplified to default to these -- then make sure whenever we display one of the above values we always put it through one of these on render.

Ideally we just come up with a formatCash that takes in (value, cashName, options) where value and cashName are required and options are optional override for the default options (like ever other formatNumber)

**Comment by JohnDanz** [comment]
going to close this, any individual examples we find going forward should just get it's own ticket.
