### ISSUE TITLE
Average Price on Order Ticket Tooltip text

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#10250]
What do we want to put in the text here:

<img width="429" alt="Screen Shot 2021-01-20 at 10 40 14 AM" src="https://user-images.githubusercontent.com/10524630/105206425-fbab2f80-5b0b-11eb-97d2-c6dd61d9218b.png">

**Comment by Chwy5** [comment]
The difference between the market price and estimated price due to trade size
