### ISSUE TITLE
markets in reporting are showing as open

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10266]
market "0x0cc49229B93F87F97f657931b50c67Af3F9b7845" is in open reporting
but in simplified it's not labeled as in-settlement

There could be a potential graph data issue.

graph has this market's status as `"TRADING"`

![image](https://user-images.githubusercontent.com/3970376/105362937-19869c00-5bc1-11eb-8889-38323105b3ba.png)

**Comment by justinbarry** [comment]
![image](https://user-images.githubusercontent.com/328965/106532664-70378400-64a5-11eb-9a77-694c800a9f27.png)

@bthaile Please reopen if you see this again.
