### ISSUE TITLE
Liquidity confirmation screens are missing the sub headers

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#10283]
DEV:

![image](https://user-images.githubusercontent.com/39496225/105396003-ab24f680-5c1f-11eb-9263-5ce7d3bfa458.png)

DESIGN:

https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Simplified-UI?node-id=555%3A3264

![image](https://user-images.githubusercontent.com/39496225/105396069-bed05d00-5c1f-11eb-8313-06eb860adaf2.png)

**Comment by Chwy5** [comment]
added closing
