### ISSUE TITLE
make sure 24 hr volume is calc correctly

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10294]
make sure 24hr volume is calculated correctly, needed for sorting markets on market list page.

**Comment by Chwy5** [comment]
Starting 24hr volume was .01...see tx.  I then bought $10usdc worth of yes (0.55)...new 24hr volume shows  9.94

![image](https://user-images.githubusercontent.com/41301809/106816079-d4dc1580-6642-11eb-8907-f566fae5667e.png)

![image](https://user-images.githubusercontent.com/41301809/106816147-f2a97a80-6642-11eb-8e54-3cc2712157b9.png)

**Comment by Chwy5** [comment]
closing - duplicate ticket
