### ISSUE TITLE
(waiting on middleware) user adds liquidity to non 50/50 market

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10301]
user doesn't receive market shares, which was expected.

**Comment by Chwy5** [comment]
Getting wrong values...what i was expecting to get vs what I got...

![image](https://user-images.githubusercontent.com/41301809/106904634-6c844700-66c9-11eb-85a5-39975ff7d65a.png)
![image](https://user-images.githubusercontent.com/41301809/106904658-7148fb00-66c9-11eb-9f87-cef5463bcc01.png)

**Comment by Chwy5** [comment]
closing - fixed
