### ISSUE TITLE
add claim winnings to user activity

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10308]
investigate getting claims on graph, need total proceeds.
If total proceeds can get on the graph, calculate winnings, if not just add total proceeds.

add `claim` activity card. See design

**Comment by justinbarry** [comment]
Added `tradingProceedsClaimed` to the ShareToken entity.

**Comment by Chwy5** [comment]
Still missing

**Comment by bthaile** [comment]
this is working.looks good. 


![Screen Shot 2021-02-12 at 18 13 50](https://user-images.githubusercontent.com/3970376/107835196-48c2a000-6d5e-11eb-8bb2-2907d78c0bcc.png)



![Screen Shot 2021-02-12 at 18 14 40](https://user-images.githubusercontent.com/3970376/107835213-511adb00-6d5e-11eb-89ec-103e158549e3.png)
