### ISSUE TITLE
Update copy in claim winnings button on individual markets in portfolio 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#10318]
Should be worded like this

![image](https://user-images.githubusercontent.com/39496225/105522237-4334e580-5cdd-11eb-9c25-07d2c30832de.png)

---

Dev currently looks like this on desktop

Can you also check the buttons don't stack like this

![image](https://user-images.githubusercontent.com/39496225/105522357-6e1f3980-5cdd-11eb-9e21-a81aed228d6e.png)

**Comment by JohnDanz** [comment]
already fixed
