### ISSUE TITLE
Buying shares with ETH, user doesn't receive shares but sends ETH

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10338]
User tries to buy shares with ETH but user doesn't receive any shares. Here is a tx.

https://kovan.etherscan.io/tx/0x6bdd33ffe248cc0d55d50625f3c8ea5ade937bd5facdf5856dcdaa03cc3213f9

**Comment by justinbarry** [comment]
@bthaile Looks like the balances are there on contract.

**Comment by Chwy5** [comment]
fixed - closing
