### ISSUE TITLE
trading form not updating when new amm prices come in

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10363]
When new graph data is pulled AMM data changes, a populated trading form needs to re-estimate.

![image](https://user-images.githubusercontent.com/3970376/105872635-3d325380-5fc0-11eb-9e2e-42b3b59084f1.png)

**Comment by Chwy5** [comment]
still broken

**Comment by bthaile** [comment]
repro steps
Have two browser tabs open
 - start a trade to fill in estimation

second tab
 - make a trade to push the price
 
 notice that the first tab's prices changed but the trading form didn't re-estimate trade.

**Comment by Chwy5** [comment]
fixed - closing
