### ISSUE TITLE
invalid balancer pool data to be added to the copy at bottom of add liquidity modals

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#10368]
Add '$1 will be added to the invalid balancer pool.' to the end of the copy at the very bottom of these screens (shown below). The number will change dependant on the amount entered 

![image](https://user-images.githubusercontent.com/39496225/105877363-3297ae80-6000-11eb-9723-3fc9a0689ff6.png)

**Comment by phoebemirman** [comment]
@bthaile is adding real data for this
