### ISSUE TITLE
external link to etherscan tx

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10388]
This should be external link to etherscan transaction. `tx_hash` property on the transaction is the hash

![Screen Shot 2021-01-27 at 11 08 51](https://user-images.githubusercontent.com/3970376/106027015-180d1600-6090-11eb-945b-e72edcc257de.png)

**Comment by matt-bullock** [comment]
@JohnDanz as this is now a link can you change it to the secondary text colour and make it semi bold

On hover it should change to the primary text colour

![image](https://user-images.githubusercontent.com/39496225/106936787-4b4d4600-671d-11eb-99f1-8bd1e21f1956.png)

**Comment by matt-bullock** [comment]
@JohnDanz can you make it semi bold so it has more standout
