### ISSUE TITLE
UI Needs To Know Fees

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#10424]
When getting the rate for exit position where fees are counted, you need the market creation and reporting fees. These can be grabbed from contract calls but that's inefficient so they should be gathered from the graph.

The market creation fee is constant per-market.
The reporting fee is dynamic. It comes from OINexus but is cached in each ParaUniverse.

Blocked by #10423

**Comment by robert-e-davidson3** [comment]
Currently these values are hardcoded based on the values set in the tests.

**Comment by Chwy5** [comment]
@bthaile is this an issue?

**Comment by bthaile** [comment]
we get reporting fee from the graph. closing this
