### ISSUE TITLE
avg price in position is wrong for LP added non 50/50

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10437]
price is Yes/No 75/25 but avg price for "Yes" Shares is .26

![image](https://user-images.githubusercontent.com/3970376/106341602-750cf580-6263-11eb-883a-b6276de7166d.png)

I think there is graph data issues. In the add liquidity tx it has yes and no share cost the same but user gets back "Yes" shares, I'm not able to determine the average price of the shares the user gets back.

![image](https://user-images.githubusercontent.com/3970376/106365851-ded9dd80-62fd-11eb-8e14-85a58fae4fbb.png)

In the above example adding up `yesShareCashValue` and `noShareCashValue` doesn't equal `cashValue`
I think the issue is these values are the same

**Comment by Chwy5** [comment]
This is what I see:
![image](https://user-images.githubusercontent.com/41301809/106341882-d5546500-626c-11eb-9a7b-c7ba4a04aac2.png)

![image](https://user-images.githubusercontent.com/41301809/106341838-b6ee6980-626c-11eb-8b2c-6e98ca98c89f.png)

**Comment by justinbarry** [comment]
```solidity
  // Will be zero if ratio is 50-50.
  let netShares = addLiquidity.noShares.minus(addLiquidity.yesShares).abs();
  let noShares = addLiquidity.noShares.toBigDecimal();
  let yesShares = addLiquidity.yesShares.toBigDecimal();
  let totalShares = noShares.plus(yesShares);
  let priceOfNoShares = yesShares.div(totalShares);
  let priceOfYesShares = noShares.div(totalShares);

  let priceOfGainedShares: BigDecimal;
  if(yesShares.gt(noShares)) {
    priceOfGainedShares = priceOfYesShares;
  } else {
    priceOfGainedShares = priceOfNoShares;
  }

  // Cash value is the cost of the lp tokens received accounting for shares returned to user.
  addLiquidity.cashValue = addLiquidity.cash.toBigDecimal().minus(priceOfGainedShares.times(netShares.toBigDecimal())).truncate(0);

  addLiquidity.noShareCashValue = priceOfNoShares.times(noShares);
  addLiquidity.yesShareCashValue = priceOfYesShares.times(yesShares);
```

**Comment by pgebheim** [comment]
@bthaile -- Is this still an issue?

**Comment by Chwy5** [comment]
closing
