### ISSUE TITLE
bottom button bar isn't showing on filter menu on android mobile

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#10431]
![image](https://user-images.githubusercontent.com/6775839/106316095-0dce5180-6221-11eb-9318-6c0fe97f5633.png)

**Comment by matt-bullock** [comment]
@phoebemirman Still having this issue

**Comment by matt-bullock** [comment]
@phoebemirman content getting cut off at the bottom (above bottom bar)

![image](https://user-images.githubusercontent.com/39496225/107651211-869cc700-6c7f-11eb-829e-a6e5ff87cd36.png)

**Comment by matt-bullock** [comment]
@phoebemirman I'm still seeing the above issue

**Comment by phoebemirman** [comment]
matt check again and it is looking fixed
