### ISSUE TITLE
Notifications Modals

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1043]
When user clicks `view` the correct modal comes up for the user to preform the correct action.

Modals include:

- [ ] Unsigned orders, market liquidity
- [ ] cancel orders, cancel all orders in resolved market
- [x] sell complete sets
- [ ] claim winning proceeds
- [x] finalize market
- [ ] claim reporting fees and staked REP 
- [ ] Orphaned Orders

**Comment by pgebheim** [comment]
@bthaile -- Is this duped with the transaction work the @andrewdamelio did?

**Comment by bthaile** [comment]
This task is specifically for modals. The notifications have a ‘view’ button that brings up modals. This is a list of the individual modals. @johndanz can you check off the ones done

**Comment by bthaile** [comment]
@JohnDanz this tix was meant as a high level checklist. I ended up creating individual tix thinking each modal can be hooked up to notifications and tested. 

When you think you have all the modals done check them off.

**Comment by Chwy5** [comment]
all in individual tickets - closing this
