### ISSUE TITLE
empty trading proceeds claimed data

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10460]
added ShareTokens property on Market:

graph data
![image](https://user-images.githubusercontent.com/3970376/106509191-e7175180-6492-11eb-9c8a-3bcece055938.png)

query

![image](https://user-images.githubusercontent.com/3970376/106509423-39f10900-6493-11eb-93d2-141895a1769a.png)

**Comment by justinbarry** [comment]
moved `tradingProceedsClaimed` from shareToken entity to market entity.
