### ISSUE TITLE
remove liquidity showing NaN for tokenAmount

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10480]
amm `0x73196d9f1cb89f1f1874a8335316f1cdf7e08542`
remove liquidity showing NaN in transactions

![Screen Shot 2021-02-02 at 09 22 41](https://user-images.githubusercontent.com/3970376/106621682-6a3eb300-6538-11eb-88c0-8f018e9b968b.png)

**Comment by Chwy5** [comment]
fixed -closing
