### ISSUE TITLE
LP shows loss after one trade

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10491]
User adds $8,000 in liquidity. Second user makes trade to push prices. LP shows a loss.

![image](https://user-images.githubusercontent.com/3970376/106640334-89930b80-654b-11eb-8092-3f44095c8453.png)

Is there a better way to tell LP what fees they have earned. Currently the UI does a calc (Current Value - Initial Value) which included unrealized loss/gain.

**Comment by Chwy5** [comment]
We removed Fees earned for now....Moving this ticket to on hold for now...see if we can figure out to show fees only and no IL

**Comment by Chwy5** [comment]
no longer showing pnl for lp
