### ISSUE TITLE
multi-winnings calc is incorrect

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10504]
user's winnings calc is incorrect

![image](https://user-images.githubusercontent.com/3970376/106657298-768b3600-6561-11eb-98e9-399de8d98e7b.png)

**Comment by bthaile** [comment]
USDC is calc correctly. Have to test ETH winnings

![image](https://user-images.githubusercontent.com/3970376/106782361-b01a7a80-660f-11eb-846a-ac882e5d95e8.png)

**Comment by Chwy5** [comment]
fixed - closing
