### ISSUE TITLE
When creating the initial AMM the user will need to give a custom token name (ui part added, waiting on middleware)

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#10534]
We need an input which displays the token names below with 'y', 'n' and 'i' as default at the start of the names.

The token names will then be displayed on the confirmation screen

![image](https://user-images.githubusercontent.com/39496225/106911395-63fc3280-6702-11eb-97aa-1fe2569b7254.png)

Link to entire flow: https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Simplified-UI?node-id=555%3A3269

![image](https://user-images.githubusercontent.com/39496225/106911355-5646ad00-6702-11eb-9d6d-914d14a4d24e.png)

**Comment by matt-bullock** [comment]
@phoebemirman Can you reduce the font size in the input to 16px Bold

**Comment by Chwy5** [comment]
added - closing
