### ISSUE TITLE
LP token amount different than estimate

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10553]
creating a new ETH/USDC AMM, the estimate and actual are correct. 

More liquidity user adds to existing AMM more the estimate is wrong. estimate looks to be 1% too low when user adds equal amount of liquidity that exists in the pool. If user adds way more liquidity than is in the pool the estimate is correct. 

Also "no/yes" shares estimation to the user are off when AMM is non 50/50. User receives a different amount than estimated.

Calls to middleware, same values passed to estimation as to middleware tx call.
![image](https://user-images.githubusercontent.com/3970376/107051035-92751e80-6791-11eb-8e85-ddeb8467ff7b.png)

add additional liquidity to existing amm

![Screen Shot 2021-02-05 at 09 04 56](https://user-images.githubusercontent.com/3970376/107050962-7bcec780-6791-11eb-80a7-6226c8438a4e.png)

User's actual LP token balance:

![image](https://user-images.githubusercontent.com/3970376/107050925-71143280-6791-11eb-9cf8-089137baeec6.png)

**Comment by Chwy5** [comment]
being replaced - closing
