### ISSUE TITLE
eth amm buy No shares, curr value incorrect

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10552]
current value incorrect for ETH amm buying "No" shares. current value should be (current NO price 0.32) 
0.3147 * 0.32 * 1300 = `$130.9152`

note: verify that values are not rounded in calc user's position, only on display. init value should should be consistent with current value

![image](https://user-images.githubusercontent.com/3970376/107048784-f1856400-678e-11eb-9280-19c4f7f0e246.png)

**Comment by Chwy5** [comment]
Current value looks slightly off, might be from rounding somewhere

**Comment by Chwy5** [comment]
closing
