### ISSUE TITLE
24 hr volume isn't updated on market page.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10563]
There have been multiple trades but 24 hr volume is showing 0.00.

![image](https://user-images.githubusercontent.com/3970376/107121182-a9317900-6856-11eb-8148-96edc9cb3e7a.png)

**Comment by bthaile** [comment]
tested this again. Seems to be working as expected for newly created AMM and for existing USDC amms. 

It's only an issue with existing ETH AMMs. Newly created ETH AMMs shows 24hr volume

example: `0x74564be8f78a3189365dfe30f4f630fbb69d6525` amm doesn't show up in past graph query


<http://simplified.augur.sh/#!/market?id=0xde99d48d36b7f2b920048b7abc69dceb12860214-0x74564be8f78a3189365dfe30f4f630fbb69d6525>

![image](https://user-images.githubusercontent.com/3970376/107302243-b01cdf00-6a42-11eb-9ed0-1d6e5bcf2cdd.png)

**Comment by Chwy5** [comment]
duplicate - clsoing
