### ISSUE TITLE
USDC cost issue when creating AMM

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#10561]
This issue stems from the changes made here: #10422

Problem
===

Assuming the token we are dealing with has only 6 decimal places. The balancer pool requires a minimum of `10**6` of each token represented in the pool. Complete sets are calculated `cash.div(numTicks)`. To have at least the the minimum number of sets cash must be at least `10**6 * numTicks`. In the case of USCD this is 1000.

Solution
===

Create a version of the the ERC20Proxy1155 which will multiple/divide all amounts incoming and outgoing by numticks.

**Comment by pgebheim** [comment]
First cut at solution here: d8f0fd1b4e57e3588e0f5605f392f4f9ffb7ea31

Scaling the precision of the ERC20 to always go to 10**18

@justinbarry to add tests

**Comment by justinbarry** [comment]
Still need to add tests. The work is done.
