### ISSUE TITLE
volume goes to zero when liquidity is pulled on the market

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10572]
volume is correct until liquidity is pulled from AMM then graph shows zero. This isn't correct. volume should never go down. 

to repro:
create AMM, add liquidity
do some trades, verify volume is correct
remove liquidity
notice that volume is zero.

**Comment by Chwy5** [comment]
Both 24hr and total volume changed after i remoevd liquidity....need to figure out how to get the lat prices, right before liquidity totally removed

**Comment by Chwy5** [comment]
closing
