### ISSUE TITLE
User doesn't receive ETH when claiming

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10594]
seems a decimal is off. my account doesn't receive the ETH. Seems only gas is taken out. 

![image](https://user-images.githubusercontent.com/3970376/107402596-c0c46800-6ac9-11eb-9ec2-413d85ab7de6.png)

![image](https://user-images.githubusercontent.com/3970376/107402923-23b5ff00-6aca-11eb-81ed-db168a3f20fe.png)
https://kovan.etherscan.io/tx/0x5b889f01052a5d59645fa44e4af3f8453d24c26088d993448ee00260cdf46ce1

**Comment by Chwy5** [comment]
recieved eth - gas costs....closing
