### ISSUE TITLE
user selling shares, estimate average price incorrect.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10590]
User is selling more shares than liquidity in AMM. 
estimate for what cash user will receive is correct. The average price is incorrect. 

Average price estimate was 0.73 but after user sold shares the amm price for "Yes" shares was 0.97.

example of liquidity and trading form breakdown for USDC AMM

![Screen Shot 2021-02-09 at 09 11 43](https://user-images.githubusercontent.com/3970376/107384521-ac776f80-6ab7-11eb-810b-bdb3e6db1dfc.png)

**Comment by Chwy5** [comment]
closing
