### ISSUE TITLE
Client doesn't load, throws net_version error

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#106]
Running on localhost.  Error is `TypeError: exists is not a function` from app.js:9992:
```
    if (exists(join(dir, 'package.json')) || exists(join(dir, 'node_modules'))) {
```

**Comment by carver** [comment]
Yup, the augur-js update broke the build for me, too. :disappointed:

It looks like the bcrypt import here isn't going to work with browserify: https://github.com/AugurProject/augur.js/blob/6a37363598cc5cb4f15822510e590a1e53cbb6c9/augur.js#L1343

The usage looks unnecessary to me, anyway.  You should be able to decrypt using aes (like you're already doing) with the entered password, and catch errors to find out if it was incorrect.

**Comment by tinybike** [comment]
Oops, used bcrypt instead of bcryptjs -- fixed in 5cd12b9dff5e023b496648ad813b25c0d2985794.

Client still doesn't load for me, though; now I'm getting what looks like a web3 error:
```
Uncaught Error: net_version method not implemented [app.js:109556]
```

Good point, re: using decryption errors instead of storing the hash!  Also, now that I think of it, the plaintext password is not a good AES secret key -- sha256(password) would be better.

**Comment by scottzer0** [comment]
fixed earlier today

**Comment by tinybike** [comment]
Removed bcrypt in AugurProject/augur.js@73d1cc403ceb46d7db28b5af5a3c57918207010f.  Thanks for the suggestion!
