### ISSUE TITLE
disable trading form if no liquidity

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#10605]
if a market has no liquidity disable the trading form/ticket. 

Add language to the disabled buy/sell button to indicate that the market has no liquidity.

"Liquidity Depleted" is what the button text should read. all inputs should be disabled.

**Comment by matt-bullock** [comment]
@JohnDanz can you add the 'no entry sign' to the cursor on hover over the input. Is it possible to add text to that no entry sign that says liquidity depleted?

**Comment by Chwy5** [comment]
added - closing
