### ISSUE TITLE
Getting nonce error with Wallet Connect

### ISSUE THREAD

**Issue by bconfortin** [AugurProject/augur#10613]
Not sure how but I started to get nonce errors with WalletConnect (using MM).
When I switched to MM extension, instead of MM via WalletConnect, it worked fine and signed the transaction.

Since I'm not sure how to reproduce, maybe check if there's something off with the nonce (assuming we have control over that).

![IMG_8312](https://user-images.githubusercontent.com/10351013/107557725-ba60e980-6bb8-11eb-8b27-ec53fac0101f.PNG)

**Comment by Chwy5** [comment]
@andrewdamelio can you jump on with @bconfortin

**Comment by bconfortin** [comment]
Just retested this and it seems to have sorted itself out.

I didn't reset my MM account.

I'll keep testing WalletConnect to see if I can trigger this error.
My guess is: I was using WalletConnect with Wallet A, switched to WalletConnect with Wallet B and got the nonce from Wallet A.

**Comment by andrewdamelio** [comment]
@bconfortin closing -- Not a Augur Simp issues This is a issue with MM when using walletConnect.  I'm able to reproduce using MM + WC without using Augur
