### ISSUE TITLE
Create ERC20 Wrapper Factory and Wrappers for ParaAugurs

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#10618]
In order to have a consistent set of cost effective ERC20s for use in various pools we are going to add the machinery all ParaDeploys to be able to consistently create share tokens.

1. [x] Create WrappedShareToken that is simple ERC20
    a. [x] wrap
    b. [x] unwrap
    c. [x] claim proceeds
2. [x] Create WrappedShareTokenFactory for creating ERC20s associated with a particular ParaDeploy
    a. create WrappedShareTokens (for a tokenID/symbol pair)
    b. wrap / unwrap / etc
    c. helper functions for: publicBuyCompleteSet, publicSellCompleteSet that works on all the ERC20s?
    c. Is trusted by WrappedSharedToken
3. [x] Integrate with AMM Factory
4. [ ] Update all the tests

**Comment by Chwy5** [comment]
closing
