### ISSUE TITLE
Portis is not working, even via HTTPS

### ISSUE THREAD

**Issue by bconfortin** [AugurProject/augur#10614]
[Safari] Portis doesn't seem to be working, either via local using Kovan or via https staging url

On local: keeps popping back, asking me to login in an infinite loop
On https: opens the popup with an infinite load animation and the error shown below:

![Captura de Tela 2021-02-10 às 16 18 15](https://user-images.githubusercontent.com/10351013/107560064-a79be400-6bbb-11eb-9d4e-a2fae69bdee2.png)

**Comment by Chwy5** [comment]
@andrewdamelio can you jump on with bruno

**Comment by andrewdamelio** [comment]
closing -- Portis is just broken with safari currently when used by the connect libraries we are using.

This should fix itself when wallet-connect npm package updates to use latest SDK version --- until then i've hide Portis in safari.
