### ISSUE TITLE
Issues with Coinbase wallet

### ISSUE THREAD

**Issue by bconfortin** [AugurProject/augur#10612]
- When you are logged in with Coinbase wallet there is no "Sign Out" button, just "Switch Wallets".
- It's currently not working with Kovan, even if Coinbase is set to Kovan in the ETH network settings.

**Comment by andrewdamelio** [comment]
@bconfortin testnet isn't supported with WalletLink at this time. https://github.com/walletlink/walletlink/issues/41#issue-656016136

Noticed another issues though with CoinbaseWallet, i have a PR to address that here
