### ISSUE TITLE
init value for ETH position wrong

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10620]
User has claimed winnings before,
average price paid is wrong and init value:

user buys "No" shares on expired market and init value/cost is incorrect.

![image](https://user-images.githubusercontent.com/3970376/107652399-276e9080-6c46-11eb-8344-de9d06998cb3.png)

![image](https://user-images.githubusercontent.com/3970376/107652586-5d137980-6c46-11eb-863b-a61d6dbea2c6.png)

**Comment by Chwy5** [comment]
fixed - closing
