### ISSUE TITLE
Run augur-ui from npm package

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1066]
Would it be worth the effort to figure out why user can't just pull down augur-ui npm package and run from node_modules directory.

simple commands would be 
>npm i augur-ui
>node node_modules/augur-ui/server.js

this would host augur-ui using express. Here is the result.

![screen shot 2019-02-18 at 11 12 59 am](https://user-images.githubusercontent.com/3970376/52967390-907cdf80-336f-11e9-8cb9-a0f51226e2a4.png)

this works if users want to pull down source and run augur-ui, but there is a few extra commands
>git clone ....
>yarn
>yarn dev

**Comment by pgebheim** [comment]
This should work but is kinda a low priority it's from my perspective.

Was someone asking about it?

**Comment by bthaile** [comment]
I just thought it would be super convenient for a power user to run augur-ui. There was recently a change added to augur-ui that fallbacks to using augur casino's augur-node and alchemy's ethereum node.
