### ISSUE TITLE
missing a `claim proceeds` in activity 

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10678]
user claims multiple winning positions on ETH amm and only sees one `claim proceeds` in user activity.
All winnings do get claimed, verified in etherscan.

![image](https://user-images.githubusercontent.com/3970376/108382350-5b116380-71ce-11eb-82f4-5c49471496c2.png)

Tested claim 3 eth winning positions, only one `Claim Proceeds` doesn't show up in user activity

**Comment by pgebheim** [comment]
@bthaile @JohnDanz Updates?

**Comment by bthaile** [comment]
this has been addressed, moving to review

**Comment by Chwy5** [comment]
Closing- will retest with new contracts
