### ISSUE TITLE
Mobile Design for transactions and notification Modals

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1070]

**Comment by pgebheim** [comment]
@matt-bullock @bthaile @andrewdamelio - I think this design task is also done...

**Comment by bthaile** [comment]
I agree, not sure there is any tweaks. We only have the notifications up on sneakpeak

**Comment by Chwy5** [comment]
@matt-bullock plz review this ticket and close if done

**Comment by matt-bullock** [comment]
@cillianhunter0 think you finished all these up. Can you confirm and close
