### ISSUE TITLE
missing eth from account

### ISSUE THREAD

**Issue by nfrancois99** [AugurProject/augur#10719]
I sent ETH to my account (the REP UI) and it is not there - been a few days...
https://etherscan.io/tx/0x15ea5caaa469cb3233908a09bbb48da6eea292870e8d366642822684ee476b0f
Also, I just am trying to convert my REP old to REPv2.  The instructions say to add/transfer my REP to my address.  Is this my same ETH address?  Or, is there a separate REPold address?
Thanks

**Comment by pgebheim** [comment]
The account you transferred to now has both ETH and REP.

Sign in to the v2 ui with that account and there will be a button on the header bar prompting you to migrate from REPv1 to REPv2.

**Comment by nfrancois99** [comment]
Thanks.  I had to log out and log back in.  I just transferred over more
REP old, but I don't see it in my account.  How do I know when it gets
there so I can migrate it all at one time?
Thanks!

**Comment by pgebheim** [comment]
The REP is there.

https://etherscan.io/address/0x714a49d9662432bd71f7891aa72ea4aff2a8ac44#tokentxns

I'm confused as to what issue you're having.

Are you saying that the UI you navigate to from augur.net is not showing you the REP migration button when you log on with account: 0x714a49d9662432bd71f7891aa72ea4aff2a8ac44 ?

What version is the Ui you're using? This is available in the bottom left corner.

**Comment by nfrancois99** [comment]
No, what I was saying is that under the list of account balances, there is
only USDC, DAI and REPv2 options so although my REPold was there, it was
not listed in my account.  Thus, there was no way for me to verify when the
REP old made it to my account.
Regardless, I migrated the full 180 REP several hours ago, and the REPv2 is
still not in my account.  I have logged out and back in several times.
How long does this process take?  Can you track down my funds and provide
the status?
Thank you,
Nicole

**Comment by pgebheim** [comment]
I believe this may a bug with syncing the balances. I just found a case where we will fail to sync new balances into the UI.

You should be able to verify your REP balance by visiting your account on etherscan (in the link above.

It currently shows ~180 REPv1, these haven't yet been converted to v2.

**Comment by nfrancois99** [comment]
How should I convert them?  When using the migrate tool, I received a
countdown that confirmed they were migrated.
Thanks, 👍
Nicole

**Comment by Chwy5** [comment]
Can you email at team@augur.net to verify issues.

Thank you

**Comment by nfrancois99** [comment]
I was able to migrate them just now, but how do I withdraw them now?  The
help menu covers adding funds, but not withdrawing.
Thank you,
Nicole

**Comment by nfrancois99** [comment]
I managed to migrate from repold to repv2.  How do I withdraw funds/assets
from augur.io?
Thank you,
Nicole

**Comment by pgebheim** [comment]
Once you've migrated, those funds are now controlled by your wallet. There's no need to further withdraw / transfer them unless you want to move them. In the latter case you can do a standard token transfer from your wallet to whichever address you would like.
________________________________
