### ISSUE TITLE
Add chart scroll wheel events

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1071]
Making specific task for hooking up mouse scroll wheel events to the trading charts.

Candlestick: 
scroll x: go forward and back on timeline
scroll y: change candlestick size and range

Need more thought into the behavior of candlestick.

Depth Chart:

scroll y: zoom in/out the midpoint gap

**Comment by pgebheim** [comment]
@bthaile -- I think this is done too. I was filtering by Sprint 1 today and didn't notice this...

**Comment by bthaile** [comment]
Not done, prob do this after inital release of redesign release. Low’ish pri currently

**Comment by pgebheim** [comment]
@joeykrug @chwy -- y'all ok with leaving this for a functionality improvement after initial release?

**Comment by bthaile** [comment]
This task needs to be done but can be addressed after initial UI redesign release.

**Comment by pgebheim** [comment]
I'm gonna move this out of this Sprint since it won't be done right now.

**Comment by bthaile** [comment]
It can be pushed to the sprint after the next sprint.

**Comment by joeykrug** [comment]
can do if massive user demand, otherwise ko'd
