### ISSUE TITLE
REP Migration: Add approval button and remove message telling the user they need to sign multiple transactions

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#10721]
- Add approval button
- Remove transaction message
- Add REP v2 Balance
- Add pending states for buttons & disable when confirmed - see designs
- Add migration successful message and tick when migration is confirmed
- Add failed transaction state

https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Simplified-UI?node-id=2094%3A0

![image](https://user-images.githubusercontent.com/39496225/109324999-b5a56200-7855-11eb-948e-b7a8b9885f3a.png)

Notes:
- check if user is approved if so disable approval button
- When user sends tx for approval or migrate, store the tx hash in local storage
- Monitor the status of transaction hashes. 
- If approval or migrate tx is pending show wait indicator on button.
- migrate button only gets enabled if user is approved. If migrate transaction has confirmed show "migration successful" message and remove tx hash from local storage
  
summary of on-chain data to get when form is loaded, for simplicity make calls per block:
1. is user approved
2. user's REP and REPv2 balances
3. get tx hashes status (pending, failed or confirmed) check with @matt-bullock  on transaction failure notices

**Comment by pgebheim** [comment]
@matt-bullock Is this the design for the augur simplified version or is this referring ot the version that's in the trading ui right now?

**Comment by matt-bullock** [comment]
@pgebheim It's an adaption of the version that's in the trading UI right now. We need to separate it out onto it's own page and link to from augur.net. See https://github.com/AugurProject/augur/issues/10705

**Comment by matt-bullock** [comment]
Closing. Compiled all info into ticket #10705
