### ISSUE TITLE
When creating initial liquidity we need to display the amount that will be added to the invalid balancer pool

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#10751]
Example - at the end of the bottom copy.

The amount will be in ether Ξ or $

![image](https://user-images.githubusercontent.com/39496225/109832643-d6e4c480-7c40-11eb-9b90-037e24e8edc8.png)

**Comment by Chwy5** [comment]
Not seeing the number filter in

![image](https://user-images.githubusercontent.com/41301809/111802461-637bbd80-88a4-11eb-9946-65b2222b608a.png)

**Comment by bthaile** [comment]
import of PORTION_OF_CASH_INVALID_POOL is undefined. not sure why

**Comment by Chwy5** [comment]
fixed - closing
