### ISSUE TITLE
no explicit license?

### ISSUE THREAD

**Issue by ycdk** [AugurProject/augur#1075]
**Problem**: No LICENSE file provided in this repository

**Analysis**: -node is MIT, -core is GPLv3, but `package.json` says AAL (http://www.augur.net/license.txt?)  

**Solution**: can we please add LICENSE file for this project so users know how they can collaborate?  if AAL, can we include `license.txt` file in repository?

**Comment by stephensprinkle** [comment]
@ycdk — Thanks for the feedback!  

I’m in agreement that a more explicit agreement is advantageous for quick reference.  
I’ll add this in shortly.

**Comment by stephensprinkle** [comment]
ff348fadddefaf00d49bd66a4de0bd0a23d9a560

**Comment by ycdk** [comment]
thank you @stephensprinkle !
