### ISSUE TITLE
Architect gas handling for TypeChain and L1/L2

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#10802]
Our current gas estimation and pricing strategy is a bit of a kludge. We had to work around a third party bug and meet a deadline. It also doesn't quite seem to work right for Arbitrum. On the `robert/arbitrum` branch, I use TypeChain instead of our custom contract api solution. This makes gas overrides easy but lacks some of the features we need.

We need to manage state for all contract calls on a particular chain:
- One provider/signer per chain (L1 and each L2).
  - Each provider needs to point to the right RPC URL and have the right Chain ID.
  - I believe nonces are separately tracked per chain. If not then they need to be synced between providers.
- Each chain will have its own gas estimation and pricing rules/values. This can differ per class of tx as well.
  Specifically, Arbitrum is finicky about gas price. For deploy it doesn't matter. For txs it must be >0. For callStatic is must be 0.

This will affect flash as well as the middleware.

**Comment by pgebheim** [comment]
Can we talk to offchain labs about this gas must be === 0 for calls situation?

**Comment by robert-e-davidson3** [comment]
> Can we talk to offchain labs about this gas must be === 0 for calls situation?

Good idea. It seems like a bug since they should just ignore that value completely for calls.

**Comment by robert-e-davidson3** [comment]
The solution here is to switch to industry standard (hardhat etc) since the industry standard now works.
