### ISSUE TITLE
new trading page Chart Issues

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1082]
- [x] chart label text seems fuzzy or too thick.

~~- [ ] refresh issue on price history chart, sometimes it doesn't take up the full parent div.~~
moved to https://github.com/AugurProject/augur/issues/1152

~~- [ ] Chart section gets bigger when user zooms and out. Need to resize full layout when~~
moved to this issue: https://github.com/AugurProject/augur/issues/1271

- [x] smaller candlestick charts might need more price y axis, need to show first and last price

- [x] add padding to top of candlestick chart so top price isn't trimmed off

- [x] add padding to top of price history chart so top price isn't trimmed off

- [x] add price to both sides of depth chart

~~- [ ] when user loads directly to trading page the history price chart stays on `no completed trades`, null state.~~ moved https://github.com/AugurProject/augur/issues/1152

~~- [ ] Market depth chart needs to be able to be zoomed in and out~~
moved to: https://github.com/AugurProject/augur/issues/2748

- [  ] ~~Price history Chart Vertical axis - have price y axis on the right side like candlestick.~~ 

- [x] add dots where trades are in price history chart, helps user to see single trade on market.

~~- [  ] Add the vertical lines to the candlestick chart~~ not going to do

**Comment by pgebheim** [comment]
Please attach the correct Epic and Release and add to the backlog. If this is already slotted for one of the sprints, please select that as well.

**Comment by bthaile** [comment]
@pgebheim  how to add to >add to the backlog, I don't see it as a milestone or label

**Comment by bthaile** [comment]
All these will not hold up initial release. agree @Chwy5

**Comment by Chwy5** [comment]
Yup Agree

**Comment by Chwy5** [comment]
Would recommend trying to get this finished before launch......
when user loads directly to trading page the history price chart stays on `no completed trades`, null state.

**Comment by bthaile** [comment]
I agree, moved that issue to own tix, https://github.com/AugurProject/augur/issues/1152

**Comment by joeykrug** [comment]
Should fix the depth chart before release

**Comment by bthaile** [comment]
@joeykrug which depth chart issue, price on both sides of y-axis or zoom in/out?

Both are nice-to-have tasks. 

Or the chart section gets bigger when user manually zooms in (browser zoom)

**Comment by Chwy5** [comment]
remainder to be completed for 1.14
