### ISSUE TITLE
can not add additional liquidity to this amm

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10827]
`Will Bob dance the polka` USDC
<https://simplified.augur.sh/#!/market?id=0xff20e909af63694e9e1fb7331092661244a3a1da-0x59d60600984220e040d078270d1698eaf9ac01ce>

marketId: 0xff20e909af63694e9e1fb7331092661244a3a1da
amm: 0x59d60600984220e040d078270d1698eaf9ac01ce

MM estimate gas fails.

**Comment by Chwy5** [comment]
not needed to be fixed- will be fixed with new stuff
