### ISSUE TITLE
UI is stuck at 50 shares when I try to sell

### ISSUE THREAD

**Issue by bconfortin** [AugurProject/augur#10843]
The UI shows that I have 50 shares of "No" but they seem stuck, even after I try selling them.
![Screenshot at Mar 11 18-31-04](https://user-images.githubusercontent.com/10351013/110857917-2f970b80-8298-11eb-8e18-5ee0a761d532.png)

When I press "Sell" and confirm the transaction, it shows I sold 0 shares of "No" for $0.
![Captura de Tela 2021-03-11 às 18 28 50](https://user-images.githubusercontent.com/10351013/110857909-2d34b180-8298-11eb-98fd-337857fbcfb3.png)

Tx:
https://kovan.etherscan.io/tx/0x9ec47ae6bf9207d68ef13aabed3766b915b3841b1f9043bcb550a29836aaad46

**Comment by JohnDanz** [comment]
while looking into this, we are passing a negative number to `doExitPosition` for min amount. This should be no lower than 0 according to tom.

**Comment by Chwy5** [comment]
fixed - closing
