### ISSUE TITLE
slippage updates - slippage custom input doesn't let you delete the value when it has a single digit

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#10850]

**Comment by matt-bullock** [comment]
@phoebemirman  Slippage looks good. Just two small things:

- can you make the hand tool appear when hovering the entire clickable area
- Can you change the hover state on the default number to this

![image](https://user-images.githubusercontent.com/39496225/111500099-eafdeb00-8743-11eb-8a7b-0c09dcd5dc86.png)
