### ISSUE TITLE
Update to Buy Sell toggle on order ticker to make it clearer

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#10866]
https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Simplified-UI?node-id=319%3A4398

Please add animation to toggle (same as settings)

And hover state:
![image](https://user-images.githubusercontent.com/39496225/111684870-8b790b80-8827-11eb-976c-c4cfd1d3c18f.png)

![image](https://user-images.githubusercontent.com/39496225/111336310-693f8c00-8675-11eb-9764-ae86c7a5fc2c.png)

**Comment by matt-bullock** [comment]
@phoebemirman can you check the corner radius on both the button and surrounding outline is 8px


![image](https://user-images.githubusercontent.com/39496225/111981797-71ca1380-8b08-11eb-8ec5-8a0692ee2285.png)

Currently it looks a bit off (below) but I'm unsure if this is just the way it's being rendered 
![image](https://user-images.githubusercontent.com/39496225/111982056-ca011580-8b08-11eb-8392-110e9a256625.png)

**Comment by phoebemirman** [comment]
they both have 8px rounding @matt-bullock

**Comment by matt-bullock** [comment]
@phoebemirman can you try a way to match it up better with what you see in the design. I think you just need to increase the rounding of the black rectangle by a couple of pixels

**Comment by Chwy5** [comment]
closing
