### ISSUE TITLE
Remove slippage from settings and add to betslip

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#10863]
https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Simplified-UI?node-id=319%3A4398

**States:**
![image](https://user-images.githubusercontent.com/39496225/111215730-c125b680-85d3-11eb-8c5a-e96339805375.png)

Sits 8px below amount input
![image](https://user-images.githubusercontent.com/39496225/111215829-e4506600-85d3-11eb-867a-7b26556799e5.png)

Clicking the entire slippage area (24px in height) will open the slippage to edit

![image](https://user-images.githubusercontent.com/39496225/111216068-398c7780-85d4-11eb-98e8-243040207f47.png)

**Comment by matt-bullock** [comment]
@phoebemirman  Slippage looks good. Just two small things:

- can you make the hand tool appear when hovering the entire clickable area
- Can you change the hover state on the default numbers to this

![image](https://user-images.githubusercontent.com/39496225/111500099-eafdeb00-8743-11eb-8a7b-0c09dcd5dc86.png)

**Comment by matt-bullock** [comment]
@phoebemirman can you do these changes after clearing out the other tickets

- make the hand tool appear when hovering the entire clickable area

- animate the toggle like it does in settings

**Comment by phoebemirman** [comment]
the cursor looks right to me

**Comment by Chwy5** [comment]
its in closing
