### ISSUE TITLE
When clicking the floating Buy/Sell button to launch the betslip, please stop the market page from scrolling up

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#10877]
The replicate, scroll to the bottom of the market page and click the Buy/Sell button. You'll see the market page auto scrolls up as the betslip in launching. When I close the betslip I would expect the scroll position of the market page to be where I left it

**Comment by Chwy5** [comment]
@phoebemirman Is this still an issue?

**Comment by phoebemirman** [comment]
yes

**Comment by matt-bullock** [comment]
loads better
