### ISSUE TITLE
Changes to the available balances to make clearer

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#10870]
**Desktop** 

Home page https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Simplified-UI?node-id=93%3A17627

![image](https://user-images.githubusercontent.com/39496225/111359262-9434da80-868b-11eb-90fe-22ca6055502f.png)

Portfolio https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Simplified-UI?node-id=93%3A17690

![image](https://user-images.githubusercontent.com/39496225/111359349-af9fe580-868b-11eb-9a20-1c54d2fd06dc.png)

---

**Mobile**

https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Simplified-UI?node-id=292%3A5590

![image](https://user-images.githubusercontent.com/39496225/111359526-e5dd6500-868b-11eb-817c-d4b39a9a79de.png)

**Comment by matt-bullock** [comment]
Try removing currency icons to fit (on mobile only).

Mobile component should be the same on markets and portfolio - currently the fonts look different

**Comment by matt-bullock** [comment]
@phoebemirman on mobile, the markets page balance summary isn't fitting. Can you reduce the spacing to try to fit.

Looks like you're using a different font weight for the numbers on the markets page to the portfolio page (600 & 700). Can use either size but just need to be consistent.

Can you reduce the corner rounding to 8px

![image](https://user-images.githubusercontent.com/39496225/111984706-02562300-8b0c-11eb-8870-9da47f85378c.png)

---

On desktop - portfolio page the height of this component needs reducing. Overall height is designed to be ~102px

Just on the portfolio page the space between the label and number can be reduced to 8px. See below
![image](https://user-images.githubusercontent.com/39496225/111985649-29612480-8b0d-11eb-94f0-2e44aa079e7a.png)

Can you change 'Total Account Value' to 'Total Acc Value' to stop the label taking up so much space

**Comment by matt-bullock** [comment]
@phoebemirman See DM regarding mobile

**Comment by Chwy5** [comment]
closing-done
