### ISSUE TITLE
Add disabled button state between user clicking claim and waiting for signature

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#10883]
https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Simplified-UI?node-id=2290%3A54

![image](https://user-images.githubusercontent.com/39496225/111505915-6746fd00-8749-11eb-9bee-cb182cda5e11.png)

**Comment by Chwy5** [comment]
Still not seeing this
