### ISSUE TITLE
stuck approving

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#10895]
approving button stuck cuz of error

![image](https://user-images.githubusercontent.com/3970376/111666170-77aab680-87e1-11eb-956d-991d6225e94a.png)

![image](https://user-images.githubusercontent.com/3970376/111666200-7d080100-87e1-11eb-8b3f-69f4909cdcf7.png)

**Comment by bthaile** [comment]
got BUFFER_OVERRUN after creating USDC AMM
![image](https://user-images.githubusercontent.com/3970376/111711521-e9065b80-8819-11eb-893f-ea821914f9d4.png)

**Comment by Chwy5** [comment]
@JohnDanz is this fixed with your recent pr
