### ISSUE TITLE
MarketPane.shouldComponentUpdate returns undefined on account page

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#109]
When I go to the [account page](http://demo.augur.net/account) on the demo, this warning appears thousands of times in chrome's console:
```
[app.js:106707] Warning: MarketPane.shouldComponentUpdate(): Returned undefined instead of a boolean value. Make sure to return true or false.
1718 console messages are not shown.
```
Waiting on my local chain to sync so I can see if this is happening on the downloaded client; will update this issue once it's caught up.

**Comment by tinybike** [comment]
Confirmed that this happens on localhost, as well.

**Comment by carver** [comment]
If #111 doesn't fix it, I'll dive deeper when I get back to my dev machine.
