### ISSUE TITLE
dropdown active selection issues

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1091]
active color does not stay on dropdown selector when the cursor moves off of it.
also the active color takes a few seconds to go away after selecting

<img width="329" alt="screen shot 2019-02-20 at 6 11 58 pm" src="https://user-images.githubusercontent.com/6775839/53138421-15682480-353b-11e9-921a-0e10b6dadeb7.png">

**Comment by pgebheim** [comment]
Is this one of the small issues?

Also I assume this is used in other places than just the trading page?

**Comment by andrewdamelio** [comment]
My bad, this isn't fixed yet

**Comment by phoebemirman** [comment]
@matt-bullock thinks "the active colour should show as long as the dropdown is active"

**Comment by Chwy5** [comment]
resolved - closing
