### ISSUE TITLE
The current validity bond is less than half of the previous validity bond.

### ISSUE THREAD

**Issue by CrystalBallBe** [AugurProject/augur#1093]
From my understanding, the current validity bond will not be less than half of the previous one.
But It seems to me that it has decreased by about `62.4%`.

- The previous validity bond is that:
validityBond [InAttoEth]: `26994944668340618`
blockNumber: [7246596](https://etherscan.io/block/7246596)
timestamp(UTC datetime): `1550707195(2019-02-20 23:59:55)`

- The current validity bond is that:
validityBond [InAttoEth]: `10154469944833033`
blockNumber: [7246597](https://etherscan.io/block/7246597)
timestamp(UTC datetime): `1550707220(2019-02-21 00:00:20)`

I got these values by calling the contract function `getOrCacheValidityBond` using Web3.js.
```javascript
'use strict';
const Web3 = require('web3');
main();

async function main(){
  const web3 = new Web3('https://eth-mainnet.alchemyapi.io/jsonrpc/7sE1TzCIRIQA3NJPD5wg7YRiVjhxuWAE');
  const abi = getAbi();
  const universeAddress = '0xe991247b78f937d7b69cfc00f1a487a293557677';
  const contract = new web3.eth.Contract(abi.Universe,universeAddress);
  
  let blockNumber = 0;
  let validityBondInAttoEth =0;
  
  //"blockNumber": 7246596, "timeUtc": "2019-02-20 23:59:55", "timestamp": 1550707195,
  blockNumber = 7246596;
  validityBondInAttoEth = await contract.methods.getOrCacheValidityBond().call(undefined,blockNumber);
  console.log('blockNumber:'+blockNumber+'\n'+'validityBondInAttoEth:'+validityBondInAttoEth+'\n');
  
  //"blockNumber": 7246597, "timeUtc": "2019-02-21 00:00:20",  "timestamp": 1550707220, 
  blockNumber += 1;
  validityBondInAttoEth = await contract.methods.getOrCacheValidityBond().call(undefined,blockNumber);
  console.log('blockNumber:'+blockNumber+'\n'+'validityBondInAttoEth:'+validityBondInAttoEth+'\n');
  
}
function getAbi(){
  return     {
    "Universe": [
    {
      "constant": false,
      "inputs": [],
      "name": "getOrCacheValidityBond",
      "outputs": [
        {
          "name": "",
          "type": "uint256"
        }
      ],
      "payable": false,
      "stateMutability": "nonpayable",
      "type": "function"
    }
    ]
  }
}
```

The result is that:
```
blockNumber:7246596
validityBondInAttoEth:26994944668340618

blockNumber:7246597
validityBondInAttoEth:10154469944833033
```
For your reference, the whitepaper says as follow:
![201922101](https://user-images.githubusercontent.com/38453357/53139568-6163a980-35cd-11e9-9327-12986d8b0098.png)

**Comment by nuevoalex** [comment]
This is a bug in the v1 contracts where if no markets resolve in a given week the bond will return to its original default value. It should instead stay the same as it was previously.

**Comment by pgebheim** [comment]
Ah yes, there's nothing we can do about this for v1 but it has been fixed in the v2 code already iirc.

We don't have a ticket for that because it was in Clubhouse -- but @nuevoalex I think we should basically mark this as a dupe.

Can you add a link to the fixed code for perpetuity and we can dupe this?

@CrystalBallBe -- Thanks for investigating this!

**Comment by pgebheim** [comment]
I'm wrong about that above feedback.

@nuevoalex Did you schedule fixing this?

**Comment by nuevoalex** [comment]
Yup! There's a task in the backlog
