### ISSUE TITLE
Market appears undefined

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#110]
Occasionally after making a purchase in UI, market shares and price all go to 0 and then going to markets page the market is now "Invalid."  Refreshing the page fixes all this; I suspect it's some issue w/ dynamic updates

**Comment by carver** [comment]
Yeah, presumably related to #108 .  I'm out until at least tomorrow night, maybe all weekend.  I'll announce in #dev and/or zenhub when I start working on it.

**Comment by scottzer0** [comment]
i actualy think it's fallout from a hack i did due to inconsistent marketIds between augur.js and web3 (le sigh).

regardless, i'll take this on carver.

**Comment by joeykrug** [comment]
Still happens 
![screen shot 2015-07-27 at 8 56 42 pm](https://cloud.githubusercontent.com/assets/5925937/8921951/30db0bb2-34a2-11e5-9f96-917030ca7a71.png)
![screen shot 2015-07-27 at 8 58 04 pm](https://cloud.githubusercontent.com/assets/5925937/8921952/323bddba-34a2-11e5-8106-2bdb62b76571.png)

**Comment by scottzer0** [comment]
so after digging down into this and investigating the responses i'm getting back from my market calls, it looks like getMarketInfo is returning 0 for number of outcomes sometimes and, for me, apparently always after the buy/sell shares update.

i've checked that the market ids are identical from the original loaded market to the one that's detected changed on chain due to buy/sell outcome.

@joeykrug i suspect there may be some odd behavior with that forth property (number of outcomes) being returned by getMarketInfo.

**Comment by scottzer0** [comment]
@tinybike perhaps this kind of stuff can be caught in your test suite.  i think if any market returns zero outcomes via getMarketInfo, something a miss or it's some weird bad record that needs special blacklist treatment (or removal by other means).

**Comment by joeykrug** [comment]
So I just tested this again (funnily enough with another Rand Paul market) and got the zeroed out UI thing.  Then I did Augur.getMarketInfo('-5bfeea0efc754add5e4d11d8a57666f5210a7f5d46437e406b127971b28ac381') and it returns the number of outcomes properly (2).  It isn't returning 0 for getMarketInfo for me with a direct API call to augur.js.

**Comment by scottzer0** [comment]
#@$%@#$

**Comment by scottzer0** [comment]
indeed.  i'm examining what i'm getting back in context (two batched rpc calls getting all market data of the recent price changed market detected on chain) and it's zero number of outcomes.  however when i do it manually as above and even near the exact same time (checking for some race condition), i still get 2.

the only conditions that are different from initial market loading here are:
- the batched rpc calls are in a single market context (not a sea of them)
- the market's price has just changed and is being updated in state machine (race condition?)

le sigh

**Comment by tinybike** [comment]
> @tinybike perhaps this kind of stuff can be caught in your test suite. i think if any market returns zero outcomes via getMarketInfo, something's a miss or it's some weird bad record that needs special blacklist treatment (or removal by other means).

Right now, the augur.js test suite's `test/create/createMarket.js` file creates [4 test markets](https://github.com/AugurProject/augur.js/blob/master/test/create/createMarket.js#L21-L33), each with a single event.  After event and market creation, it then verifies that `getCreator`, `getDescription`, and `getMarketEvents` all [return the expected values](https://github.com/AugurProject/augur.js/blob/master/test/create/createMarket.js#L78-L117).  I can add an explicit check of `getMarketInfo` to this, too, if that would be helpful.

In an effort to avoid spamming our client with test markets, I do most testing on a separate test chain (network 10101).  So, augur.js does not currently have tests that loop through all markets on network 7 to verify that their stored contract data (and/or getter functions) are sane.  But if bad markets are slipping through the cracks, I can set this up.

**Comment by tinybike** [comment]
> i'm examining what i'm getting back in context (two batched rpc calls getting all market data of the recent price changed market detected on chain) and it's zero number of outcomes.

The existing batch RPC tests were not very thorough, so I added batched async versions of all test cases in augur.js's `test/markets/markets.js`, `test/markets/events.js`, `test/markets/info.js`, `test/markets/branches.js` and `test/markets/reporting.js` in AugurProject/augur.js@ded6fc978c438db1ad0ddd0ffeaab4f3786e779f.  All tests complete successfully on network 10101, so I think the underlying issue is likely not augur.js's batch RPC implementation.

**Comment by tinybike** [comment]
This *should* be fixed by 29fdcd82c18a58038ad1dacddb0c725dfa61b737.  If it happens again, please re-open this issue and I'll troubleshoot further!
