### ISSUE TITLE
portfolio quad burndown

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1101]
Data:

- [x] Make sure sorting is correct for quads

- [ ] Need to search by outcome and market for open orders and filled orders

- [x] Add filled quantity/quantity to filled orders

- [x] Add market description and timestamps to open orders @phoebemirman #1150
 
- [x] Add market descriptions to filled orders @phoebemirman 

- [x] Add correct data to positions expanded content @bthaile 

- [x] Need to see about sorting/filtering when new data comes in

- [x] Filter resolved markets from orders lists

Features:

- [x] Add switching row content component to switch positions table from current value to total returns @phoebemirman 

- [x] Add switching row content component for positions total returns from percent to ETH @phoebemirman 

- [x] Add count next to search

- [x] Show no data message when quad has no data

- [x] Add market names to single order filled/open order views @phoebemirman 

- [ ] Add pending orders from local storage to list

Styles:

- [x] Replace chevrons with right arrow design

- [x] Style quads top bar with Search component 

- [x] Change padding for single vs group order views

- [x] Work on centering for market rows

- [x] Long/Short Colors for Type (in Positions/My Created Markets) needs to be changed (Green for Long/Red for Short)

- [x] Finish styling the rows for orders (open and filled)
*  - [x] do colors for buy/sell
*  - [x] make cancel button styled 
*  - [x] pending thing
*  - [x] make sure long outcome names have ellipsis

Done:

- [x] Add/make all expanded contents @phoebemirman https://github.com/AugurProject/augur/issues/1104
* - [x] Filled Orders
* - [x] My created markets
* - [x] Open Orders 
* - [x] Positions and Positions inner expanded content 

- [x] Make market titles clickable

- [x] Portfolio page seems to have a lot of lag

- [x] Fix tab count number bug

**Comment by phoebemirman** [comment]
moved last two to separate issues:
https://github.com/AugurProject/augur/issues/1199
https://github.com/AugurProject/augur/issues/1198
