### ISSUE TITLE
Augur State Testing: Crash Recovery

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#1108]
- [ ]  Process restarts after crashing in the middle of syncing
- [ ]  Process restarts after crashing in the middle of adding new block from blockstream
- [ ]  Process restarts after crashing in the middle of a rollback

**Comment by pgebheim** [comment]
@robert-e-davidson3 -- I'm removing this from the larger epic so I can close it.

Do you still wanna build crash recovery tests?

**Comment by robert-e-davidson3** [comment]
I'm fine with this being closed. They'd be good tests but we won't get to
them

**Comment by pgebheim** [comment]
Closing, perhaps this will be done at a later date!
