### ISSUE TITLE
Augur State Testing: Full Text Search

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#1110]

**Comment by pgebheim** [comment]
@brianosaurus -- Gonna move this issue back into backlog and remove the Milestone. Recommend doing it ASAP if @robert-e-davidson3 has the structure all set for testing from logs through Ganache.

**Comment by robert-e-davidson3** [comment]
I added this test. It's in augur-test under Controller.test.ts since the FTS code is in Controller.ts.
