### ISSUE TITLE
Fix augur-core unit tests

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#1119]
Mock contracts are generated as of #1005 but the unit tests need to be updated to match the current solidity codebase. This very likely requires adding more specific mocked functions as well.

Also contract registration must be overhauled.

**Comment by joeykrug** [comment]
Should do this asap, contract tests are important!!

**Comment by nuevoalex** [comment]
We have 97% coverage roughly of the contracts as is. I think the relative value from the mock-based unit tests probably isn't as pressing as some other issues we're working through at the moment.

**Comment by pgebheim** [comment]
(Can open this or a new issue if this strategy finds its way back into vogue)
