### ISSUE TITLE
Add 24 hour volume to marketInfo

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1123]
Currently augur-node only provides current volume on markets, need to also add 24 hour volume to be congruent with mocks.

Until this is done, the UI `My Created Markets` will show over all volume.

![image](https://user-images.githubusercontent.com/3970376/55803082-42e34000-5a9f-11e9-9327-036d4d24e07d.png)

**Comment by ryanberckmans** [comment]
![image](https://user-images.githubusercontent.com/299324/55803171-702fee00-5a9f-11e9-9ae9-5a8da9548756.png)

This ticket populates data for "24H volume" in this screenshot from latest Figma designs

**Comment by ryanberckmans** [comment]
Spoke with chwy and Matt... design would like regular volume here, not 24h volume-- no need here.
