### ISSUE TITLE
Ballot status display should distinguish whether attention is required

### ISSUE THREAD

**Issue by evand** [AugurProject/augur#113]
After submitting a ballot, the status display on the left pane is unchanged; that indicator should make it clear whether my attention is still required. It should at least distinguish between no action available (no ballots available to submit / edit), a ballot needs my attention (no version has been submitted), and actions available but not required (I have successfully submitted a ballot, but it can still be re-submitted).

**Comment by tinybike** [comment]
Rolling this into #259.
