### ISSUE TITLE
Yes market has long and short position 

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1136]
related to user seeing incorrect Profit and Loss in order form confirmation https://github.com/AugurProject/augur/issues/1137

filled orders

![screen shot 2019-02-26 at 8 34 53 am](https://user-images.githubusercontent.com/3970376/53420442-6d6eb300-39a1-11e9-873c-5a0a25469ebb.png)

When long then short then long. User has complete sets.  

![screen shot 2019-02-26 at 8 33 48 am](https://user-images.githubusercontent.com/3970376/53420370-4b753080-39a1-11e9-88a8-ae2b9b107f39.png)

Selling complete sets gits rid of `Yes` with 0 for all properties. need to not show `Yes` when user has complete sets to sell, looks weird.

**Comment by pgebheim** [comment]
@bthaile I'll move this into backlog or this being actively worked?

**Comment by bthaile** [comment]
This is being worked.

**Comment by Chwy5** [comment]
addressed -closing
