### ISSUE TITLE
Cover short position has incorrect math

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1137]
related to user having completeSets: https://github.com/AugurProject/augur/issues/1136

User has short position on YesNo market. 

short 3.5 @ .7429, 

User is covering short to buy 1 @ .7

Order tix confirmation should say. profit of 0.0429. instead order confirmation says loss of ...

**Comment by pgebheim** [comment]
@bthaile I'll move this into backlog or this being actively worked?

**Comment by bthaile** [comment]
This is being worked. Will update sneakpeak,Needs to be tested

**Comment by Chwy5** [comment]
Still not showing correct Pnl....
Shows Negative PnL (in red) when I start with a short position and buy it back cheaper.....PnL should be positive

**Comment by joeykrug** [comment]
Should fix this before release

**Comment by bthaile** [comment]
@chwy5 is this still an issue, with latest update to sneakpeak?

**Comment by Chwy5** [comment]
tested - and fixed closing ticket
