### ISSUE TITLE
Getting error message while trying to make a trade when I own every outcome in Cat 3

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1147]
I am long 1 share of every outcome in a Cat 3 market.  Every time I try to buy an additional share of Outcome B from this point I get a blank screen with the message "Sorry, something went wrong, try reloading this pg or return home"

See attached screenshot for message i get in the console

![2-26er](https://user-images.githubusercontent.com/41301809/53436794-fac5fd80-39c9-11e9-93e6-bdf7dd4a7faf.jpg)

**Comment by bthaile** [comment]
@Chwy5 can you retest and close if everything is good.

**Comment by Chwy5** [comment]
looks good, closing
