### ISSUE TITLE
price history chart doesn't populate initially

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1152]
User refreshes on trading page, the price history chart doesn't draw.

![screen shot 2019-02-26 at 5 16 47 pm](https://user-images.githubusercontent.com/3970376/53453633-53a58e00-39ea-11e9-9173-62267aab21c2.png)

related issue is the price history chart doesn't take up whole div.

![screen shot 2019-02-26 at 7 28 21 pm](https://user-images.githubusercontent.com/3970376/53458675-b0aa3f80-39fc-11e9-90cf-5e11810bd435.png)

**Comment by Chwy5** [comment]
looks good. loading up quickly
