### ISSUE TITLE
Order Form confirmation word change

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1156]
![screen shot 2019-02-27 at 9 39 44 am](https://user-images.githubusercontent.com/3970376/53502425-a11a0d80-3a73-11e9-9ca8-0b4b05f9430a.png)

flipping a short position:
closing position
`Buying Back` 

New position
`Buying` Green, instead of long and short

Flipping a long position:
closing position
`Selling Out` Red

new position
`Selling` Red

![screen shot 2019-02-27 at 10 42 34 am](https://user-images.githubusercontent.com/3970376/53506859-6a94c080-3a7c-11e9-87c1-1f7330a99369.png)

**Comment by Chwy5** [comment]
working correctly in snpk
