### ISSUE TITLE
only show google translate for non english regions

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1157]
We don't need the google translation bar around for everyone. Should detect if needed and only show then.

**Comment by pgebheim** [comment]
Gonna backlog this!

**Comment by cillianhunter0** [comment]
Can we get this in for v1.14 @pgebheim @bthaile ?

It's quite annoying/takes up screen real estate, seems pointless for anyone who has english as their default.

**Comment by pgebheim** [comment]
We could hide it by default and shoe a flag in the me I bar:
https://stackoverflow.com/users/1527562/mogelbrod

Paul
paul@augur.net

________________________________

**Comment by cillianhunter0** [comment]
Could be a nice solution 👌will switch this to a design task for now.

**Comment by joeykrug** [comment]
only hide if user browser is English

**Comment by pgebheim** [comment]
Google Translate currently doesn't appear for me... though we do have it on the page. Perhaps its because of the cross site browser settings I have?

@bthaile @joeykrug do you ever see the google translate bar?
