### ISSUE TITLE
Use correct cancel buttons in trading form

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1158]
![screen shot 2019-02-27 at 10 31 00 am](https://user-images.githubusercontent.com/3970376/53506059-d0804880-3a7a-11e9-9fe7-f6d3a0350738.png)

use new cancel button

![screen shot 2019-02-27 at 10 31 27 am](https://user-images.githubusercontent.com/3970376/53506095-e261eb80-3a7a-11e9-9abf-7ddb4b9c8cc1.png)

Also add cancel all button

**Comment by pgebheim** [comment]
@phoebemirman -- Is this still blocked? If so, could you attach the blocker issue as a related issue?

**Comment by phoebemirman** [comment]
blocked by https://github.com/AugurProject/augur/issues/1124 and https://github.com/AugurProject/augur/issues/1068
