### ISSUE TITLE
price history chart has incorrect x axis labels

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1159]
![screen shot 2019-02-27 at 10 36 23 am](https://user-images.githubusercontent.com/3970376/53506418-8a77b480-3a7b-11e9-950b-5e1cbb21f81e.png)

market?id=0xeac824bea3cf45f34fc4bec7485eef41c79e3cc4

for markets older than 3 months go to showing one day a week. That will clean up the x axis.

**Comment by joeykrug** [comment]
We should fix this one before release

**Comment by bthaile** [comment]
this has been addressed, we show xaxis time labels based on length of market, 
less than 3 days old, label every 3 hours
less than 1 month old, label are daily
over 1 month old, labels are weekly

@Chwy5 can you confirm on price history charts

**Comment by Chwy5** [comment]
X axis looks fixed....Did find one small issue of the dots (for the trade in price history) don't line up with the dates, for daily....will close this ticket and create a new one for this new issue
