### ISSUE TITLE
Market Flagging

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#116]
Would be cool to eventually be able to flag markets as "likely indeterminate."  This would basically serve as an ability to filter out all of these grey certainty markets for people buying/selling shares in markets.  It'd be helpful for people who don't understand the indeterminate reporting / 50 cent payout structure and are just regular users, and by default these flagged markets should probably be filtered out, with the ability to (and a caution notice) to make them appear.

**Comment by tinybike** [comment]
I like this idea in principle.  May be tricky to implement in a user-friendly way though.  Two basic ways to implement it that I can see:

1. Bundle it with the other market metadata and store in IPFS.  Upside: easy and free.  Downside: abusable, e.g. sibyl attack competing markets.
2. Rep weight the flagging and store them on-chain.  Upside: secure.  Downside: spendy.

Hmm...

**Comment by joeykrug** [comment]
3. Rep weight the flagging and store them off-chain using signed messages by reporters ??? profit

**Comment by joeykrug** [comment]
meh, too complicated and comments allow this in practice
