### ISSUE TITLE
Using <MarketLink> should update NAV state

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#1161]
To reproduce:
1) Go to the Portfolio screen and click on a Market Name within a marketRow
2) You should be routed to the market page for the selected market
3) The NAV will not be updated to reflect the Market route

![screen shot 2019-02-27 at 12 36 44 pm](https://user-images.githubusercontent.com/3970376/53514027-5d7fcd80-3a8c-11e9-9cc9-5bae1b5390fc.png)

**Comment by joeykrug** [comment]
fixed now
