### ISSUE TITLE
update open orders collection after market creation with liquidity.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1163]
![screen shot 2019-02-27 at 12 44 20 pm](https://user-images.githubusercontent.com/3970376/53514606-b4d26d80-3a8d-11e9-9394-9af2bacd649f.png)

After market creation with liquidity transactions confirmed, the count for market with open orders is correct, but the market with open orders didn't populate in the collection.

to repro:

create market with liquidity, after clicking the `submit` button user is redirected to portfolio page.
after signing each order tx, notice that the orders don't show up in the `Open Orders` quad.

**Comment by phoebemirman** [comment]
this is working on the new-trading-page-layout branch
