### ISSUE TITLE
order confirmation is confusing for categorical markets

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1164]
![screen shot 2019-02-27 at 2 02 44 pm](https://user-images.githubusercontent.com/3970376/53519224-6eced700-3a98-11e9-8e80-f9ee88497afb.png)

Issue is when user is reversing Long position when they also have a Short position:

order confirmation says user is closing out 4.5 shares when the positions says user is long 4 shares.
reason is user is also short `C` 0.5 so actual position on `A` is 4.5.

Issue also occurs when user wants to reverse Short position when they have long positions.

Scenario:

What to do? scenario,

Categorical market, 3 outcomes
User get short  position 1 share @ .5, outcome 1 
- users shares array is [1, 0, 1]
(in UI user shows position Short outcome 1)

User wants to go long  1 share on outcome 2
- users shares array is [1, 0, 2]
(in UI user shows user is 
Short outcome 1
Long outcome 2)

User wants to take an existing order to add 1 share to their Short position, outcome 1.
(order form says closing position and sell 2 shares,  and add to Short position)

Reason is user has 2 shares of outcome 2 but doesn't know it.

Process results from augur.trading.simulateTrade to make the order form conform to synthetics.

**Comment by bthaile** [comment]
@Chwy5 Is order form confirmation correct when user is reversing a position, when they don't have complete sets?

**Comment by Chwy5** [comment]
Yes, it is correct now
