### ISSUE TITLE
profit and loss chart

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1168]
![Screen Shot 2019-02-28 at 8.22.16 AM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/8fe6f803-ca25-4c5e-9db7-0a0da3a185f7)
![image](https://user-images.githubusercontent.com/3970376/54372235-ebd97f00-4648-11e9-849d-300637510e43.png)

needs to change based on user selection of time range.

- [x] show no trades when user hasn't made any trades
- [x] try to smooth out the line
- [x] add the gradient to shading

**Comment by bthaile** [comment]
waiting on https://github.com/AugurProject/augur/issues/1187

to add PnL percentage change over time range.

**Comment by bthaile** [comment]
need to only show 4 price lines on the chart. 
verify price changes are correct.

**Comment by Chwy5** [comment]
closing
