### ISSUE TITLE
UI doesn't load on the best web browser of all time (Internet Explorer)

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#117]
Can only see feedback button

**Comment by scottzer0** [comment]
i only have access to Windows 10 and Edge 20.1 currently and it work splendidly.

Can you do a run through on any version of IE you have again?  use http://client.augur.net

If you do have an issue, please note the platform and browser version.

**Comment by joeykrug** [comment]
IE 10 windows 8 was what the complaint said
