### ISSUE TITLE
Active Markets, user position 24 hour change

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1173]
open markets

Market row: sum user's `position percentage change` in 24 hour period. 

Math:
calculate `total value` per existing user's positions.

If user's position is less than 24 hours old use the positions `totalCost` as old totalValue.
If user's position is 24 hours or more old use market trade history to get the outcome's last price 24 hours ago to calculate `total value`. 

position percentage change = (Current totalValue - Old totalValue) / Current totalValue * 100

**Comment by Chwy5** [comment]
initial work done...math updates being worked - closing
