### ISSUE TITLE
REP faucet

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1176]
Create modal for REP faucet, use existing form, no mock will be created.

Only add REP faucet on hosted like dev.augur.net and sneakpeak and for local dev.

not for production.

![screen shot 2019-02-28 at 9 36 20 am](https://user-images.githubusercontent.com/3970376/53578014-5c0dde00-3b3c-11e9-884e-274034c1a125.png)

**Comment by JohnDanz** [comment]
The buttons shown in the above screenshot are now components in `new-trading-page-layout` They all require an `action` prop, but nothing else. They can be found in `common-elements/buttons` and are `DepositButton`, `WithdrawButton`, `ViewTransactionsButton`, and `REPFaucetButton` respectively.
