### ISSUE TITLE
Syncing market data

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1177]
Block syncing data

`learn more about syncing`   link to augur doc, `https://docs.augur.net/#augur-node-functions`

there is a method `getSyncData` that we get the sync data from. We don't have a nice friendly write up of syncing market data. use tech doc for now.

Show red when synced percentage is less than 99.00%
Show yellow when syncing percentage is less than 99.90%
Show green when syncing percentage is 99.99% or above.

This this is only for syncing market data section, there is another task for the augur stats.

**Comment by Chwy5** [comment]
Mine is green and synced at 99.99%, not sure how to get the other states to test

**Comment by bthaile** [comment]
I’ve tested the behind too many blocks and it shows red. 

We could use augur-app and reset the database and watch the block processing to verify red goes to yellow to green. 

Syncing agains kovan or rinkeby would be quick.

**Comment by andrewdamelio** [comment]
@bthaile we good to close this now?

**Comment by bthaile** [comment]
Tested using Rinkeby and Kovan, didn't get yellow augur-node doesn't respond very well when in bulk sync mode. Did see red and green. 

I think the tix is finished, moving to closed.
