### ISSUE TITLE
update date to last filed order creation time

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1179]
![screen shot 2019-02-28 at 10 52 51 am](https://user-images.githubusercontent.com/3970376/53583510-536ed500-3b47-11e9-9e6e-f326814ed0aa.png)

In Filled Orders update the order date based on the last filled order timestamp.

**Comment by phoebemirman** [comment]
this is done already 

<img width="750" alt="screen shot 2019-02-28 at 1 47 24 pm" src="https://user-images.githubusercontent.com/6775839/53600869-858c3100-3b5f-11e9-8b75-6af3e612b6e0.png">
