### ISSUE TITLE
total returns incorrect in portfolio positions

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1184]
Total Returns, percentage is incorrect for categorical positions where user has more than once position in the market.

total returns is (realized + unrealized, comes from augur-node) 
Percentage should be calculated:
(Total Returns / purchase Price) * 100

**Comment by bthaile** [comment]
Fixed and pushed up to sneakpeak.

**Comment by Chwy5** [comment]
Total Returns Percentage is still not working correctly

**Comment by bthaile** [comment]
This is addressed by augur-node task, fixed by https://github.com/AugurProject/augur/issues/1187

**Comment by bthaile** [comment]
blocked by augur-node changes for percentage.

**Comment by bthaile** [comment]
Sounds like this task is done, UI is already wired up. closing
