### ISSUE TITLE
Add per-market positions and new fields to getUserTradingPositions()

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1187]
In this screenshot, it shows user's market total returns percentage and total returns in ETH.
![screen shot 2019-03-04 at 5 12 43 pm](https://user-images.githubusercontent.com/3970376/53769203-cdcd8b00-3ea0-11e9-8ca7-c0bb03f9fb62.png)

In this screenshoot, it show unrealized percent, realized percent per outcome position and the overall outcome position total returns percentage.
![screen shot 2019-03-04 at 5 12 50 pm](https://user-images.githubusercontent.com/3970376/53769201-ca3a0400-3ea0-11e9-9581-81d2122386b1.png)

```

export interface GetUserTradingPositionsResponse {
  tradingPositions: Array<TradingPosition>;
  frozenFundsTotal: FrozenFunds;
 marketTotals: MarketTotals; 
}
```

```
export interface MarketTotals {
  marketId: string
}
```

```
export interface marketTotal {
currentValue: string,
  totalReturns: string,
  totalReturnsPercentage
}
```

augur-node needs to calculate all percentages used in the UI for positions

Need: added fields, so backward compatible. 

Total market position percentage is a weighted average of all outcome position percentages:
- Summation of all outcomes total returns percentage - see below -
(total position quantity / total market positions quantity * position total returns percentage)

Position total returns percentage is a weighted average of realized and unrealized percentages: 
- ((realized quantity / total quantity) * realized percentage) + ((unrealized quantity / total quantity) * unrealized percentage)

Unrealized percentage calculation:
- (last outcome price - average position price) / average position price * 100

Realized percentage calculation:
- (closing price - average position price) / average position price * 100

for these calculations: average price for short is (max price - average price) this normalizes the price.

**Comment by ryanberckmans** [comment]
**Proposed public API change**
```typescript
export interface GetUserTradingPositionsResponse {
  tradingPositions: Array<TradingPosition>;
  NEW tradingPositionsPerMarket: {
    [Address]: TradingPosition // but fields like `TradingPosition.outcome` won't apply
  }
  frozenFundsTotal: FrozenFunds;
}

export interface TradingPosition {
  // fields apply only outcomes
  outcome: number;
  position: string;
  averagePrice: BigNumber;
  netPosition: BigNumber;

  // fields apply to outcomes and market aggregation
  marketId: Address;
  realized: BigNumber; // realized profit as of my last trade
  unrealized: BigNumber; // unrealized profit as of last price
  total: BigNumber; // total = realized + unrealized
  frozenFunds: BigNumber;
  NEW currentValue: BigNumber; // currentValue = unrealized - frozenFunds
  MAYBE NEW totalCost: BigNumber; // TODO how do we define totalCost?
  NEW realizedPercent: BigNumber; // realizedPercent = realized / totalCost
  NEW unrealizedPercent: BigNumber; // unrealizedPercent = unrealized / totalCost
  NEW totalPercent: BigNumber; // totalPercent = total / totalCost
}
```

**Comment by ryanberckmans** [comment]
Public API is updated with mock data https://github.com/AugurProject/augur-node/compare/master...1187-get-user-trading-positions-enhance
