### ISSUE TITLE
empty default price history doesn't fill 

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1189]
![screen shot 2019-02-28 at 5 51 49 pm](https://user-images.githubusercontent.com/3970376/53606742-88981900-3b81-11e9-8e79-07af8780c579.png)

There is no trigger for highchart to fill the div. Need to figure out how to fill area.

**Comment by bthaile** [comment]
this has been fixed. Need to update sneakpeak for testing.

**Comment by Chwy5** [comment]
fixed
