### ISSUE TITLE
augur-node: Augur platform Activity Stats

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1192]
Need a new endpoint to get platform stats to be displayed in the UI. 

These activities are to give the user some metadata about the platform. They've are guesses of what people are interested in. If we can't easily get the information then punt on it.

new endpoint takes in 
universe
endTime

UI Time ranges are 
24 hour
1 week
1 month
All Time `here endTime will be null`

stats are:
Active Users
number of Trades
Open Interest: `augur.api.Universe.getOpenInterestInAttoEth(...`
Markets Created
Volume
Money at Stake

Prob need to get @nuevoalex involved to get an approach.

User will be able to click on time range and the stats would reflect the time period. For example if user clicks 1 month. Stats would answer the question of how many active users on Augur for the past month. What was total volume over 1 month period. ...

UI ticket: https://github.com/AugurProject/augur/issues/1193

![Screen Shot 2019-03-12 at 3 42 53 PM](https://user-images.githubusercontent.com/3970376/54234787-d431b780-44dd-11e9-8275-e4f31e49081c.png)

**Comment by bthaile** [comment]
Start time is earliest block
End time is most recent time

Other augur-node time range endpoints do this. 

StartTime: translate the timestamp to the corresponding block to get the start block.

EndTime: translate this timestamp to most recent block. 

Use queries to grab information between these two blocks. 

If startTime and endTime are 0 then grab the earliest and most recent blocks to get data from the database.

**Comment by bthaile** [comment]
Additional query

`Markets in Dispute`

given the time range return the number of markets currently in dispute.
not the markets awaiting next dispute round.

**Comment by brianosaurus** [comment]
Added disputedMarkets as another stat.
