### ISSUE TITLE
UI: Augur platform Activity Stats

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1193]
![screen shot 2019-03-01 at 7 28 17 am](https://user-images.githubusercontent.com/3970376/53641105-97b7af00-3bf3-11e9-898b-da8b8469dd98.png)

We'll get another augur-node endpoint for user stats to populate this section. augur-node tix: https://github.com/AugurProject/augur/issues/1192

**Comment by bthaile** [comment]
moved this to in progress, augur-node endpoint is ready

**Comment by pgebheim** [comment]
@bthaile -- Awesome, gonna move this into this sprint.

**Comment by bthaile** [comment]
"ready" meaning that the stubbed out endpoint is on master. not that we are getting real data.

**Comment by bthaile** [comment]
wired up, so we don't get console errors when trying to connect to augur-node platform stats endpoint.

**Comment by Chwy5** [comment]
no console errors - closing
