### ISSUE TITLE
scalar denomination is null

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1194]
need to be consistent what is displayed for scalar denomination when it is null.

![screen shot 2019-03-01 at 8 01 35 am](https://user-images.githubusercontent.com/3970376/53642833-44942b00-3bf8-11e9-8e2b-82cdbe0fd785.png)

![screen shot 2019-03-01 at 8 01 56 am](https://user-images.githubusercontent.com/3970376/53642861-5544a100-3bf8-11e9-94a2-f3e5a95dbe42.png)

I like displaying `null` when scalar denomination is null.  add this logic to getOutcomeName(...) so we can keep consistent in market selector. Also update code to use this method that isn't. Might need to pull this out into a helper method.

**Comment by JohnDanz** [comment]
Scalar Denomination shouldn't ever be null, it's required and it's required to be a non empty string in market creation -- or should be, now. I guess the contracts allow it to be null? We should make it required in v2
