### ISSUE TITLE
deposit and withdraw type button

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1196]
![screen shot 2019-03-01 at 12 01 03 pm](https://user-images.githubusercontent.com/3970376/53656703-b630a100-3c19-11e9-9c02-e7975255f139.png)

create style button

**Comment by JohnDanz** [comment]
Made all 4 buttons that are on summary page, they all take an `Action` prop.

no hover:
<img width="603" alt="screen shot 2019-03-01 at 8 17 14 pm" src="https://user-images.githubusercontent.com/10524630/53675767-7ab8c580-3c5f-11e9-9d8a-a8fd31203dc1.png">

hover:
<img width="609" alt="screen shot 2019-03-01 at 8 17 32 pm" src="https://user-images.githubusercontent.com/10524630/53675773-860bf100-3c5f-11e9-8285-4c93e3b1b298.png">

disabled:
<img width="609" alt="screen shot 2019-03-01 at 8 16 55 pm" src="https://user-images.githubusercontent.com/10524630/53675775-8d32ff00-3c5f-11e9-9fa4-eccf72b23c0e.png">

merged into `new-trading-page-layout`
