### ISSUE TITLE
Order Form Confirmation for synthetics

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1197]
No change for Binary and Scalar markets, order form confirmation isn't confusing. 

Categorical scenarios that can confuse the trader.

For these examples I'm using a categorical with 3 outcomes, the scenarios also apply to categorical market with 4, 5, 6, 7, 8 outcomes.

user shares array is the share tokens in display format (10**18) in an array location set by outcome id, synthetics array is using netPosition in array by outcome id. see examples below.

## User is long all but one outcome and wants to long last outcomes:
initial state:
user shares array [1, 1, 0]
synthetics array [1, 1, 0]

user share array result of trade:
user share array [0, 0, 0]

order form confirmation says `closing position` ...

System thinks that if user is buying shares on all outcomes they want to convert shares to ETH therefore sell their existing shares. 

approach:
When existing user share array and synthetics array are the same and order type is buy,
leave Total Order Value same
Max cost of ETH will be escrowed is 0 
Show new Position quantity @ price ...
Show same Max profit and Max loss as though they are opening up new position.

Here is an example of user going long on all 3 outcomes in categorical market with different quantities

![screen shot 2019-03-01 at 4 22 25 pm](https://user-images.githubusercontent.com/3970376/53671088-877af080-3c42-11e9-8859-e5645e841e40.png)

## User is long one outcome and wants to short same outcome:

> (no modifications needed in this scenario) order form confirmation says user is opening a new long position outcome

## User is long in multiple outcomes and wants to short different outcome
> (no modifications needed in this scenario) order form confirmation says user is opening new short position on outcome

## User is short one outcome and wants to long another
> (no modifications needed in this scenario) order form confirmation says user is opening new short position on outcome

## User is short one outcome and wants to short another
initial state:
user shares array [1, 1, 0]
synthetics array [0, 0, -1]

user share array result of trade:
user share array [1, 0, 0]

order form confirmation says `closing position` ...
initially last outcome was shorted, result is user owns shares of first and second outcomes. When user wants to short second outcome all existing shares on other outcomes (first and last) are sold to give user short on last outcome. 

approach:

Show user is opening up new Short position with same Max profit and loss as though they are creating their first short position.

Here is what it looks like as though user wanted to short every outcome. User shorts 0.1 on each outcome in 5 outcome categorical.

![screen shot 2019-03-01 at 4 50 57 pm](https://user-images.githubusercontent.com/3970376/53671055-703c0300-3c42-11e9-85ca-e30a0c53673d.png)

**Comment by pgebheim** [comment]
@bthaile -- was this supposed to be closed with #2712?

**Comment by bthaile** [comment]
Yes, this can be closed, I'd like @Chwy5 to verify and close

**Comment by Chwy5** [comment]
fixed closing
