### ISSUE TITLE
I'd like to contribute, but there are no issues listed. 

### ISSUE THREAD

**Issue by jackson-sandland** [AugurProject/augur#1199]
I saw this quote on http://commonapp.proofofwork.news/:

The front end team is working on building out the screens for reporting during dispute resolution and open reporting. They received some new mocks back from IDEO regarding the forking screens, and are beginning those shortly.

I would like to contribute :)

**Comment by tinybike** [comment]
We use Clubhouse.io for our issue tracker!  I'm sending you an invite to our Clubhouse now.  Anyone else reading this who is interested in chipping in, just reply here (with your email, if it's not visible on GitHub) and I'll give you access to our Clubhouse.

**Comment by tinybike** [comment]
Also, most of our discussion takes place on Discord, to join us just click this invite link: https://discord.gg/JwEtX9P

**Comment by jackson-sandland** [comment]
@tinybike Awesome. Thanks! Not sure if someone else got that invite, but it's expired. 
Would be helpful to be able to chat in there.

**Comment by brresnic** [comment]
I'm interested!

**Comment by adrake33** [comment]
Closing this issue, as info on requesting access to Clubhouse has now been added to https://github.com/AugurProject/augur/blob/master/README.md#contributing.
