### ISSUE TITLE
Style windows scroll bars to look like mac

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1207]
On windows the white scroll bars take away from the design. Need to style them to look darker and not distracting

**Comment by cillianhunter0** [comment]
Potential solution for this: 
https://grsmto.github.io/simplebar/

See figma for styling: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=2454%3A1097

**Comment by andrewdamelio** [comment]
I wonder if this request is as easy as ...

```
html {
  -ms-overflow-style: -ms-autohiding-scrollbar;
}
```

**Comment by Chwy5** [comment]
Looks good - closing this
