### ISSUE TITLE
Wrong Message displayed in order ticket for Categorical Markets when user is  long all outcomes but 1 and enters order to buy the last

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1209]
For Cat3 Market, I am long 1 share of A, 1 share of B and I am placing an order to buy 2 (or more)shares of C (message is correct for buying 1 share).....It is showing Closing Position (even though I have no Net position on C)....should just show New Position in the order ticket with the Max profit/loss on that new position total

![3-3message](https://user-images.githubusercontent.com/41301809/53702629-eec9a980-3dd6-11e9-99ed-381f4ead2197.jpg)

**Comment by bthaile** [comment]
I have a fix, issue what I didn't take min of numShares and 1, augur.js would subtract shares amount owned by other outcomes from 1 whole share, I was subtracting from numShares which is over 1, so my math was off. updating sneakpeak.

**Comment by Chwy5** [comment]
Tested and fixed
