### ISSUE TITLE
Faucets unreliable

### ISSUE THREAD

**Issue by evand** [AugurProject/augur#121]
Clicking on the faucets doesn't always produce the desired result. Sometimes I get cash / rep, sometimes not. They get greyed out, but there's no confirmation as to whether it is actually pending vs failed for some unclear reason.

**Comment by tinybike** [comment]
Faucets seem to be working smoothly as of e6f19bb6d601ccc3319f324749d4e2c5bed141bc, but please re-open this issue if this problem re-surfaces.
