### ISSUE TITLE
Portfolio pg/Position Section - Total Returns % needs to be spaced out from Last Price

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1210]
Currently the Total Returns (%) is right up against the Last price # and looks to be a percentage of that number....See screenshot
Total Returns % needs to be moved over the right

![3-4](https://user-images.githubusercontent.com/41301809/53744851-d8b9f880-3e6b-11e9-83cf-3e908dc282c4.jpg)

**Comment by pgebheim** [comment]
@bthaile -- I'll let you organize :-D

**Comment by bthaile** [comment]
We'll need to add padding around percentages, also there will be percentages to the right of realized P/L and unrealized P/L which will need formatting.

**Comment by phoebemirman** [comment]
this has been fixed on new-trading-page-layout
