### ISSUE TITLE
UI: Transactions Modal

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1211]
UI task for creating transaction modal to consume augur-node endpoint.

augur node task: https://github.com/AugurProject/augur/issues/1221

See mocks, 

transactions has gone through a few iterations, will need to translate outcome names from payout numerators in some cases.

**Comment by JohnDanz** [comment]
Going to start building out the component so i moved this to in progress. I know the end point is almost ready (will probably need some edits along the way anyway) so i want to get going so we can iterate faster on those little edits that might be needed.

**Comment by bthaile** [comment]
this can be closed, we have individual tix to track transaction modal stuff.
