### ISSUE TITLE
Price display

### ISSUE THREAD

**Issue by evand** [AugurProject/augur#122]
When I hold 'No' shares in a market, my holdings on the account page report the price of the 'No' shares; this is backwards from what I'm used to / expected, and I think backwards from the desired behavior.

This adds a lot of mental strain for the user; I have to mentally negate the prices on only some of the lines in order to come up with probabilities that can be applied to the text next to them. Basically, I should be able to parse the display as "Event X is 80% likely to happen; I hold 5 'No' shares.". Instead it's showing me "Event X (in which I hold 5 'No' shares) is 20% likely to not happen", which is a lot more work to interpret.

**Comment by scottzer0** [comment]
true.  this was a mistake and good catch.  the percentage/price of a binary market should always be the likely hood of the affirming outcome.  at least that's my understanding and is less cognitive load on the user.
