### ISSUE TITLE
Implement getAccountTransactionHistory getter

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1221]
Currently in the UI, we are collecting user transactions over 4-5 endpoints, we need to consolidate this data into one new augur-node endpoint. This will allow Ui to clean up a lot of logic.

Input params:
* `universe` - universe in which to query for transactions
* `account` - user account address for which to find transactions
* `earliestTransactionTime` - earliest timestamp to filter by
* `latestTransactionTime` -latest  timestamp to filter by
* `coin` - currency used in transactions (can be "ETH", "REP", or "ALL")
* `action` - type of transactions to get (can be "BUY", "SELL", "CANCEL", "CLAIM_MARKET_CREATOR_FEES", "CLAIM_PARTICIPATION_TOKENS", "CLAIM_TRADING_PROCEEDS", "CLAIM_WINNING_CROWDSOURCERS", "DISPUTE", INITIAL_REPORT", "MARKET_CREATION", "COMPLETE_SETS", or "ALL")
* standard sort parameters, such as `sortBy`, `isSortDescending`, `limit`, & `offset`

Output params:
* `action`: string
* `coin`: string
* `details`: string
* `fee`: string
* `marketDescription`: string
* `outcome`: number
* `outcomeDescription`: string
* `price`: string
* `quantity`: string
* `timestamp`: number
* `total`: string
* `transactionHash`: string

### Transaction types:

**Action: Buy** - queries the trades table for orders where the user created a buy order that got filled.
	* **Price**: trades.price
	* **Quantity**: trades.amount
	* **Fees**: trades.reporterFees + trades.marketCreatorFees
	* **Total Revenue**: trades.amount * (markets.maxPrice - trades.price)

**Action: Sell** - queries the trades table for orders where the user created a sell order that got filled.
	* **Price**: trades.price
	* **Quantity**: trades.amount
	* **Fees**: trades.reporterFees + trades.marketCreatorFees
	* **Total Revenue**: trades.amount * trades.price

**Action: Canceled** - queries the orders_canceled table for the user's canceled orders.
	* **Price**: orders.price
	* **Quantity**: orders.amount
	* **Fees**: 0
	* **Total Revenue**: 0

**Action: Claim** - queries crowdsourcer_redeemed, participation_token_redeemed, & trading proceeds tables. (Queries for claiming from market creator mailbox will be done in a separate ticket since this requires new AN code.)
**Crowdsourcer (REP)**: 
	* **Price**: 0
	* **Quantity**: 0
	* **Fees**: 0
	* **Total Revenue**: crowdsourcer_redeemed.repReceived
**Crowdsourcer (ETH)**: 
	* **Price**: 0
	* **Quantity**: 0
	* **Fees**: 0
	* **Total Revenue**: crowdsourcer_redeemed.reportingFeesReceived
**Participation Token**: 
	* **Price**: 0
	* **Quantity**: 0
	* **Fees**: 0
	* **Total Revenue**: participation_token_redeemed.reportingFeesReceived
**Trading Proceeds**: 
	* **Price**: outcomes.price
	* **Quantity**: trading_proceeds.numShares
	* **Fees**: (trading_proceeds.numShares * outcomes.price) - trading_proceeds.numPayoutTokens
	* **Total Revenue**: trading_proceeds.numPayoutTokens
Do we also need to show the REP amount redeemed for crowdsourcers & participation tokens, or just the profits?

**Action: Dispute** - queries disputes table for any dispute transactions where user is the reporter.
	* **Price**: 0
	* **Quantity**: disputes.amountStaked
	* **Fees**: 0
	* **Total Revenue**: 0

**Action: Initial Report** - queries initial_reports table for any initial reports where user is the reporter.
	* **Price**: 0
	* **Quantity**: initial_reports.amountStaked
	* **Fees**: 0
	* **Total Revenue**: 0

**Action: Market Finalization** - would require additional AN code. Not a high priority, so probably will be done only for v2.

**Action: Market Creation** - queries markets table for all markets where user is marketCreator. (Only returns ETH validity bond txs; does not return no-show REP bond txs since this info is not in the logs.)
	* **Price**: 0
	* **Quantity**: 0
	* **Fees**: markets.creationFee
	* **Total Revenue**: 0

**Action: Complete Sets** - queries completeSets table where account is user.
**Buying**: 
	* **Price**: markets.numTicks
	* **Quantity**: completeSets.numCompleteSets
	* **Fees**: 0
	* **Total Revenue**: 0
**Selling**: 
	* **Price**: markets.numTicks
	* **Quantity**: completeSets.numCompleteSets
	* **Fees**: (reporting fee rate * price * quantity) + (creator fee rate * price * quantity)
	* **Total Revenue**: (completeSets.numCompleteSets * markets.numTicks) - fees

We also need pagination like the other getters. This response from this getter will populate this transactions modal:

![unknown.png](https://images.zenhubusercontent.com/5bff29dc5cb43a45a18add9f/96db3232-5593-43b3-9fb4-19eeaf9a5ee7)

**Comment by pgebheim** [comment]
I'll tackle this this week!

**Comment by adrake33** [comment]
@chwy Since we are displaying both bought & sold complete sets, should those just be listed under the Buy/Sell actions instead of as their own action?

**Comment by Chwy5** [comment]
Complete sets- No I would have them under their own Action, b/c if they were listed as individual txs how do we know which one gets the fee tied with it?

Claim (settled winning shares): outcome {winning outcome}, cost basis: {should this be initial cost + winnings?}, coin: ETH, fee: {creator fee + reporting fee}, total: {should this be initial cost + winnings - creator fee - reporting fee?} - I think we, this needs to be a separate transaction. I For example, I if I buy 10 shares at .4 of outcome A and Outcome A settles at 1.0 ( i will have a tx for outcome A with a cost basis of 4 eth)....this may actually need to be a sell at 1.0 (so cost basis of the sale would be the 10 shares at 1.0 for a cost basis on the sale of 10 eth ( my releazed would be (10eth-4eth ) for + 6eth winnings

Claim (participation token): outcome: none, cost basis: {amount user paid}, coin: REP, fee: {should this be the amount of reporting fees received?}, total: {amount user paid + reporting fees redeemed}- @joeykrug how should this be calculated

**Comment by Chwy5** [comment]
Wherever we are claiming...it can just be a Value...doesnt need to be cost basis

**Comment by adrake33** [comment]
@Chwy5 I may be misunderstanding what you're saying, but wouldn't the fee always be associated with the selling of the complete set, not the buying? Do you have an example of what you mean?

And for the claiming of settled winning shares, are you saying to show one transaction for when the shares were acquired, and one transaction for when they were settled, like this:

Shares acquired info: outcome {outcome}, cost basis: {price * quantity}, coin: ETH, fee: 0, total: {same as cost basis}
Shares settled info: outcome {winning outcome}, cost basis: {settled price * quantity}, coin: ETH, fee: {creator fee + reporting fee}, total: {(settled price * quantity) - (creator fee + reporting fee)}

**Comment by adrake33** [comment]
@Chwy5 I discussed the participation token txs with Alex, and he said we don't have a good way to get the buy participation token txs from the DB right now, and they aren't necessary for tax purposes anyway, so I'll leave those out. For the claim participation token txs, he said the cost basis should be 0, and the total should just be the reporting fees the user got.
