### ISSUE TITLE
dropdown width

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1224]
@matt-bullock  wants us to increase the width of the dropdown to accommodate the largest menu item 

examples: 

![image](https://user-images.githubusercontent.com/6775839/53758218-49fcaa00-3e72-11e9-8b70-5b1d702384d8.png)

![image](https://user-images.githubusercontent.com/6775839/53758249-597bf300-3e72-11e9-8593-8d1e2af1450d.png)

talk to matt for more details if needed

**Comment by Chwy5** [comment]
addressed - closing
