### ISSUE TITLE
trading complete sets, user cover short, order confirmation is wrong

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1225]
This is only an issue if user has existing complete sets.

If a user has a short position, and goes to cover their short position, adding a buy order to the order ticket, the order ticket only displays "New Position" info and is not displaying the "Closing Position"info

**Comment by bthaile** [comment]
Complete sets, have market maker create liquidity.
Have second user take all orders. market maker should be left with complete sets.

**Comment by nuevoalex** [comment]
You can also get complete sets by making orders for each outcome (in binaries and scalars they must not cross)

**Comment by bthaile** [comment]
That was easy, worked like a charm!

**Comment by bthaile** [comment]
Things look good with small change

Scenario: User has complete sets but order form confirmation looks correct.
User can buy/sell and the order form confirmation says user is opening new position.

Issue come in with synthetics when user buys/sells shares when they have complete sets. 
There is a netPosition of 0 on `No` with no realized/unrealized it shows up as a `Yes` long position with zeros. UI can filter that position out.

With this change the user can create new positions and close position and not get mixed up.

See what you think @Chwy5 updating sneakpeak,

confirm positions with all zeros are filtered out.

**Comment by Chwy5** [comment]
Makes sense to me when there is ranges between dates....Like Sept 8, Sept 12, Sept 16th etc, Little bit weird to me for daily dates though when the dot doesnt match up with the coordinating date.

**Comment by Chwy5** [comment]
tested and fixed
