### ISSUE TITLE
layout for account page needs adjustment

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1229]
layout should be more similar to portfolio so you see the header of Open Markets at the bottom of your screen

notifications, watchlist and open markets should all have a taller max height
 
talk to matt 

--consolidating conv--
remove Account Summary header to create more room for columns.

**Comment by pgebheim** [comment]
@phoebemirman @bthaile -- Do we have the info needed to get this adjusted?

**Comment by matt-bullock** [comment]
We can remove the header 'Account Summary' and tighten up space in that area. Same as what we do on Portfolio

**Comment by Chwy5** [comment]
Looks better with out the Account Summary Header in

The Max height of the quadrants seems a little too long still....right now I still cant tell that there is another quadrant underneath them....I can only see the top of the lower quadrant shading....Need to be able to see the quadrant Title (like Open Markets, Status or Transactions)

**Comment by bthaile** [comment]
@Chwy5 can you add a screenshot?

**Comment by Chwy5** [comment]
![3-21as1](https://user-images.githubusercontent.com/41301809/54771780-5a37b780-4bdc-11e9-8a5f-814aae73bff0.jpg)

**Comment by phoebemirman** [comment]
the middle column is designed as a fixed height. it can not grow or shrink.

**Comment by Chwy5** [comment]
@matt-bullock anyway to shrink the height of the center column so it doesnt go to the bottom of the screen...so we can see there is a header of additional info underneath that quadrant

**Comment by Chwy5** [comment]
@matt-bullock please respond - need height of middle column shorter for standard desktop resolution. Reason is son user can see their are more boxes underneath...similar to portfolio pg

**Comment by matt-bullock** [comment]
The spacing in the build can be tightened up to better match the design. That will save a good amount of space. See below: left is build, right is design:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/b7702862-7ad4-42b3-8c55-68368dffac4a).

Try this first to see if it's enough

**Comment by Chwy5** [comment]
The readjustment or shrinking of your overview, caused the column widths to go out of wack again...they are no longer close to being even

**Comment by phoebemirman** [comment]
those definitely are not related. the last two columns o nthis page don't stay at an even width with the first column because they can only get so small. we probably need another breakpoint for smaller screens.

the 24hr pill selector and all/in-reporting tabs can only get so narrow by design. 
<img width="863" alt="Screen Shot 2019-04-08 at 5 17 27 PM" src="https://user-images.githubusercontent.com/6775839/55764907-35d43b80-5a22-11e9-9e34-cc778a682a53.png">

**Comment by bthaile** [comment]
Design also indicated the `Your Overview` is a fixed height but the other quads min-height can be shorter.
The min-height for Notifications and Watchlist needs to be the same as the portfolio quads.

**Comment by matt-bullock** [comment]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/3413ff6e-41a1-4072-973d-537f8354138d)

This is what Chwy can currently see in his monitor. We would want My active markets to be visible in the same way that Transactions is (the header and some content is visble at the bottom of the users screen). Should use the same responsive rules as the portfolio and adapt to the screen size

The dead space in Watchlist shouldn't be visible. This should apply to all sections here.

**Comment by phoebemirman** [comment]
dupe of https://github.com/AugurProject/augur/issues/1521
