### ISSUE TITLE
augur-node user's 24hr Profit and Loss percentage change

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1231]
![screen shot 2019-03-04 at 5 44 11 pm](https://user-images.githubusercontent.com/3970376/53770554-21da6e80-3ea5-11e9-9101-bbf1620d9c04.png)

summary: 

For the account summary, Need past 24 hour percentage change in user's position for each outcome. Also need 24 hour percentage change for the market. Similar to what now exists, just in the 24 hour time frame.

It might be easier to add to getUserTradingPositions.

**Comment by bthaile** [comment]
https://docs.google.com/spreadsheets/d/1ZxP0WS6_gRyjJgiVzZIKb5Tkxghd0av_rsuIoAyHkJg/edit#gid=1950036041

**Comment by ryanberckmans** [comment]
Updated design... the % change shown here is the **24-hour percent change to a user's unrealized revenue**.

The algorithm is

1. given a user's open position (even if it was opened only 30 seconds ago)
2. given unrealizedRevenue for that position
3. calculate unrealizedRevenue24HoursAgo based on trade price 24 hours ago
4. 24H% change = `unrealizedRevenue/unrealizedRevenue24HoursAgo - 1`
