### ISSUE TITLE
Trading pg fills show 0 - hover

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1235]
When doing a tiny sized trade(smaller than 4 decimal places) on the trading pg, both the trade history, positions and My fills shows 0.0000....we should probably allow a user to hover over that number and see the true decimal amount (at least for desktop)...@matt need a solution for mobile

![3-5fills](https://user-images.githubusercontent.com/41301809/53836691-9f15ea00-3f5e-11e9-9e82-e3caeabaeb9c.jpg)

We need a new QuantityLabel that will show `0.000...` and allow the user to hover over it to get the full precision value.

if quantity has more sig decimals than 4 and value is `0.0000xxx` display `0.0000...` then user can hover over to get full value.

if quantity is greater than zero and has more sig decimals than 4, display whole number value and`...` example is 1234567.000344567 display `123456...` and full precision value on hover.

~~(verifying this approach with design)~~ Chwy agrees

MOVED Order Book specific changes to the issue: https://github.com/AugurProject/augur/issues/1291

This task is for the hover for row values that don't fit.

**Comment by bthaile** [comment]
I'll wait to see what @matt-bullock says, 

We could detect this sit. and display last 4 significant digits. This is only an issue on v1, v2 will go to 2 decimals.

**Comment by matt-bullock** [comment]
Add ellipsis to any number that is smaller than 0.0001. So 0.0000...

Order book and trade history share the same pattern. Full decimal value is displayed when you hover over the number. Shouldn't cover the price so needs to come out the side.
![image](https://user-images.githubusercontent.com/39496225/53894149-e15b2c00-402f-11e9-9502-110dbc036ca6.png)

Orders and positions:
![image](https://user-images.githubusercontent.com/39496225/53894294-25e6c780-4030-11e9-9c2e-cfc298c1829a.png)

**Comment by JohnDanz** [comment]
Examples of the baseline component piece, is this what you are looking for @Chwy5  (using eth in this example even though this really applies more to quantity for now.

<img width="377" alt="Screen Shot 2019-03-11 at 6 50 36 PM" src="https://user-images.githubusercontent.com/10524630/54165437-ae010e80-442e-11e9-90d9-643b9eec8fb0.png">
<img width="433" alt="Screen Shot 2019-03-11 at 6 50 41 PM" src="https://user-images.githubusercontent.com/10524630/54165440-b1949580-442e-11e9-99a3-93dc9b2dad59.png">
<img width="406" alt="Screen Shot 2019-03-11 at 6 50 45 PM" src="https://user-images.githubusercontent.com/10524630/54165446-b48f8600-442e-11e9-90ce-84506d2a778f.png">
<img width="439" alt="Screen Shot 2019-03-11 at 6 50 48 PM" src="https://user-images.githubusercontent.com/10524630/54165449-b6f1e000-442e-11e9-9afd-a1f4911d5ed3.png">

**Comment by bthaile** [comment]
Only need the hover effect for values that are not totally visible. 

Also I think we want to slim up the hover

**Comment by JohnDanz** [comment]
updated styling example based on mocks:

<img width="308" alt="Screen Shot 2019-03-12 at 11 32 46 AM" src="https://user-images.githubusercontent.com/10524630/54217961-98d1c180-44ba-11e9-8944-c1f25160c83b.png">

**Comment by matt-bullock** [comment]
![image](https://user-images.githubusercontent.com/39496225/54221884-9db36700-44f4-11e9-9d01-4dbb51ae0ae4.png)

cursor demonstrates hover on a dust order (0.0000…) to expand to show the full 8 decimlas (0.00000001)

**Comment by bthaile** [comment]
looks good we just need to use the correct mono font for numbers.

**Comment by pgebheim** [comment]
Changing this to be a #feature and removing myself :-D

Pretty hovers btw!

**Comment by bthaile** [comment]
Created separate dev task issue, not going to continue with this for development. closing this one
