### ISSUE TITLE
Volume metric is misnamed

### ISSUE THREAD

**Issue by evand** [AugurProject/augur#124]
In normal markets, "volume" refers to trading volume. The number displayed next to volume is the number of shares outstanding, which is not the same thing. That number is closer to "open interest", though it doesn't quite exactly match that term either, since "open interest" ought to include the shares "held" by the market maker.

Consider the following example:

A buys 1000 YES
B buys 1000 NO
A sells 500 YES

The trading volume is 2500 shares. The open interest is 1000 shares (or 2000, if you enjoy double counting): B holds 1000 NO, A holds 500 YES and MM holds 500 YES. The number displayed by the current software is 1500, which is an interesting number, but probably shouldn't be called either volume or open interest.

**Comment by joeykrug** [comment]
The number does include shares held by the market maker.  It should be renamed to open interest or perhaps shares outstanding

**Comment by evand** [comment]
It doesn't seem to. This screenshot shows 825.49 NO, 2490.49 YES, and "volume" of 3315.98 (= 825.49 + 2490.49). The open interest should be 2490.49 (or 4980.98 if you like double counting).

![augur-volume](https://cloud.githubusercontent.com/assets/118926/8688970/37261264-2a70-11e5-9a1f-c8c54382e485.png)

**Comment by joeykrug** [comment]
How are you calculating open interest?

**Comment by joeykrug** [comment]
I guess open interest isn't a good term either, since there's not always a direct counterparty for a trade.  It's "outstanding shares" (that haven't been sold) atm, and includes the shares a market maker holds.  Could keep it that way or change it to actual volume traded.

**Comment by evand** [comment]
Max(outstanding yes, outstanding no). Equivalently, the maximum amount paid out by the market maker to shareholders. Also equivalently, the number of pairs of shares in existence, assuming that shares must always exist as pairs and that the market maker holds any unpaired shares (which is the framing that captures the fact that the market creator is on the hook for paying for them at judgment time, and therefore can be treated as "owning" them).

**Comment by evand** [comment]
In what sense do you mean "shares a market maker holds"?

Open interest (or outstanding shares, they're really pretty similar...) and volume are both interesting metrics, as is the graph of those things over time. I wouldn't worry too much about how to display the more detailed info, provided the trade history is readily available via API so some interested 3rd party dev can make a nifty viewer.

**Comment by joeykrug** [comment]
When a market maker provides initial liquidity, they essentially hold shares on both sides in proportion to how they set the initial odds.  Trade history will be available by js api

**Comment by scottzer0** [comment]
this "volume" metric has to go for now.  it's was mis-named from the beginning.  i don't think total shares purchased (which is what this actually is) is very useful and i think we even have an issue to drop it.

i ask you, evan, what are some useful metrics you'd like to see at a glance (market pane briefs) and also in detail (market page)?

joey and i can evaluate how realistic they are to implement.   due to ethereum data stores and decentralization, not all metrics are that trivial.

**Comment by evand** [comment]
A quick stab at what I (think I) want:

How's the liquidity? The market maker parameter matters, but so does my best guess about the actual user-generated liquidity I can't see. Good proxies for that probably include open interest or shares outstanding, and recent time-averaged trading volume (eg volume in the past day or week or whatever; lifetime volume is less interesting). The tricky question I actually want the answer to is if I can't take a large enough position to be interesting just against the market maker liquidity, can I (likely) take one against limit orders I can't see?

What's the trading history? The chart should include at least price and trading volume, and open interest or shares outstanding as well would be nice.

In general, I can't think of anything that isn't computable locally from the current order book (which I can't get...) and the ticker. So if the ticker is available via API, some 3rd party can make a nifty order book widget, so anything beyond the crudest of charts should be low priority (IMO).

Given the hidden order books, I'm not really sure what the best at a glance summary is. I think price, fees, and open interest is probably a fine start. Plus closing date. If you have those, you've at least feature-matched Foresight Exchange from the late 1990s.
