### ISSUE TITLE
Price History Chart - Dots (representing trade) don't line up one x axis displays daily

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1243]
![3-6xaxis](https://user-images.githubusercontent.com/41301809/53885928-e1860800-3fec-11e9-9a00-8cdaabb151fe.jpg)

**Comment by bthaile** [comment]
Are you saying the dates dont line up with trades?

The xaxis dates dont know about the trades, some times it lines up some times it doesnt. 

We aren’t going to line up. When markets get older we only show xaxis every week. So the labels dont crowd.

**Comment by bthaile** [comment]
The hover/crosshairs should always line up

**Comment by Chwy5** [comment]
So the daily x axis line up with trades on Categorical markets (i get when we have longer time frame in x axis like 2 week intervals, they wont align), but for scalars...like in the above example...the trade on Feb 22 is off line...the date in the x axis to the dot

**Comment by bthaile** [comment]
I've got a change, will inform when we push up to sneakpeak

**Comment by bthaile** [comment]
Same issue as noticed on tix: https://github.com/AugurProject/augur/issues/1256

I think this is accurate and the chart is correct. What do you think @Chwy5

**Comment by Chwy5** [comment]
Isnt it a bucket for the day?   (even if there is only one trade on that day) If that is the case I think it should match up with the date....

If it isnt a bucket for the day, then based off of time it traded makes sense

**Comment by bthaile** [comment]
The trades are bucketed, meaning we just take the last trade of the day. We keep the trades traded timestamp and chart spreads the days across the width of the chart so the day is contained within each day tick. 

So trades early in the day are closer to the left tick and trades at the end of the day are closer to next day tick. 

If this is confusing I can move the trade to midnight of the trade day so trades show up on the tick. 

Let me know

**Comment by Chwy5** [comment]
Yeah that would work better

**Comment by bthaile** [comment]
Ok, I can make that change

**Comment by bthaile** [comment]
There are the scenerios where the trade is in the correct day but there isnt a tick b/c we are only showing weekly because the market is older than 3 months. After I make the above change

Just fyi

**Comment by bthaile** [comment]
Made change, pushed to sneakpeak.

**Comment by Chwy5** [comment]
Yeah looks good, that's better for me...closing this and 1256
