### ISSUE TITLE
Sell Complete Sets button isn't visible generally

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1248]
<img width="1920" alt="screen shot 2019-03-06 at 10 54 56 am" src="https://user-images.githubusercontent.com/3970376/53898900-a1c81c00-3ffe-11e9-928b-a733928c4168.png">

The could be more visible in a different location.  User would have to collapse the header to show

**Comment by Chwy5** [comment]
This wont be needed for V2
