### ISSUE TITLE
Selling Shares Causes UI to Zero Out in Demo

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#125]
It does seem to correct upon a refresh though.

**Comment by joeykrug** [comment]
Still happens
![screen shot 2015-07-27 at 8 56 42 pm](https://cloud.githubusercontent.com/assets/5925937/8921932/04992b74-34a2-11e5-8ecc-59de573df3f6.png)

**Comment by scottzer0** [comment]
duplicate of #110
