### ISSUE TITLE
Verify: Short position correct when shorting and own complete sets

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1251]
This is only an issue if the user is taking their own orders. I think this is a super edge case.

User's position is short 0.1 but the sum of filled orders is 0.0 shares. User has 0.2 complete sets.

<img width="1597" alt="screen shot 2019-03-06 at 1 30 43 pm" src="https://user-images.githubusercontent.com/3970376/53908086-38530800-4014-11e9-9695-3a49a7c0d74d.png">

<img width="1558" alt="screen shot 2019-03-06 at 1 30 39 pm" src="https://user-images.githubusercontent.com/3970376/53908095-3b4df880-4014-11e9-9b74-1ee8a2f47e0d.png">

This is actual shares owned by user:
<img width="1173" alt="screen shot 2019-03-06 at 1 30 52 pm" src="https://user-images.githubusercontent.com/3970376/53908075-31c49080-4014-11e9-82c5-2128adda9661.png">

To create scenario:

Create market with liquidity
Second user takes a bid and ask on one outcome
Market creator gets complete sets.

If user with complete sets is taking other user's orders then the synthetics are correct.
I think the correct way to address this is through documentation or educating the user in the UI. I don't think we need to make augur-node changes.

putting this in backlog. I'd like to get @Chwy5 input on this issue.

**Comment by pgebheim** [comment]
@bthaile -- Was this on Rinkeby or a local net, and do you happen to have a market ID that alex can poke at?

**Comment by bthaile** [comment]
I was local. Doesnt matter. 

User creates a market with liquidity. Second user takes order on each side of the book. 

Then market creater has complete sets and takes his own original liqidity orders. 

I think its an edge case for our users unless market maker is wash trading with complete sets. They will get confused because their position wont make sense as they take orders.

**Comment by Chwy5** [comment]
This is an uncommon edge case, but is a huge issue imo if it occurs...we need to figure out the math/balances to make sure they are always correct

**Comment by Chwy5** [comment]
@ryanberckmans plz speak with @bthaile prior to working

**Comment by joeykrug** [comment]
Tested, non issue anymore
