### ISSUE TITLE
PouchDB wrapper should not create directories for memory adapter

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#1254]
When creating a pouchdb wrapper via its factory, a directory is created to store the database. This is unnecessary when the pouchdb adapter is in-memory, as it is during testing.

This is low priority because the only side-effect is extra directories being created.

See this PR for specifics: https://github.com/AugurProject/augur/pull/1252/files#diff-0e459113e2991685a25ab67b41642104R90

**Comment by pgebheim** [comment]
Not worth the time to investigate.
