### ISSUE TITLE
bucket data is incorrect 

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1256]
notice that for day buckets there is multiple trades for one day, the chart is too jagged.

<img width="1494" alt="screen shot 2019-03-06 at 2 21 57 pm" src="https://user-images.githubusercontent.com/3970376/53911131-3771a480-401b-11e9-8810-5a4769837dbc.png">

**Comment by bthaile** [comment]
using 0x75ec1f1a3356517908eccb5f6e4fac619c68ba99 to see, the trades don't line up with market trade history. last trade of the day needs to be represented on the multiple day chart.

**Comment by bthaile** [comment]
sorting by trade timestamp and logIndex smoothed out the graph. Also verify that the dot on price history is the last trade of the day in week+ long markets. @Chwy5 give it a look

**Comment by Chwy5** [comment]
Price History chart still looks jagged to me

The dots on the price history chart still dont match up with the dashes for that date.....see
market?id=0xece19690ac910cc9b7a4dc669d1c5e2ee93daa44

**Comment by bthaile** [comment]
I think it's correct. Like the hash line is the start of that day, the trade is during the day so it won't be on the day. Like the prior day is before.

For instance on the market mentioned above. 

Feb 07 has a trade, which is at the end of Feb 07, almost Feb 08 and the chart reflects that. Where as Feb 11 trade is at 1am very close to midnight and is really close to the Feb 11 hash mark.

I think this is accurate and the chart is correct. What do you think @Chwy5

**Comment by Chwy5** [comment]
Makes sense to me when there is ranges between dates....Like Sept 8, Sept 12, Sept 16th etc, Little bit weird to me for daily dates though when the dot doesnt match up with the coordinating date.

**Comment by Chwy5** [comment]
Isnt it a bucket for the day?   (even if there is only one trade on that day) If that is the case I think it should match up with the date....

If it isnt a bucket for the day, then based off of time it traded makes sense

**Comment by Chwy5** [comment]
Charts look good, dots matching up with dates...closing issue
