### ISSUE TITLE
Make bulk sync more efficient

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#1259]
~~We should be making single calls to the Ethereum node that return logs for all event types, rather than multiple calls for each event type. This will require changing the sync logic as well as the logic for parsing the logs and sending the data to each DB.~~

Move async queue to EthersProvider.

**Comment by pgebheim** [comment]
@adrake33 -- Is this issue still supposed to be in Review/QA?

**Comment by adrake33** [comment]
@pg I created a PR that gets multiple events in a single request for each chunk. However, Alchemy takes a significantly long time to send a response when requesting multiple events if the number of results is high (e.g. 1500+). I'd also like to get the async queue issue figure out before attempting to merge this since the tests take a long time to run. Will move this to the next sprint.
