### ISSUE TITLE
[Community Bounty] Augur.wiki

### ISSUE THREAD

**Issue by Anish-Agnihotri** [AugurProject/augur#1267]
<img src='https://cdn.worldvectorlogo.com/logos/augur.svg' width="200"/>

# Augur.wiki
Open-sourced, community-funded analytics, historical database, and developer platform built for Augur. Built to be a unified service enabling easy statistics-backed analytics for the average user.

[Link to original application](https://github.com/AugurProject/augur/issues/1116#issuecomment-467693731)

### The problem
As a relatively early-stage platform, Augur has garnered enthusiast usage and is beginning to approach a more user-centric environment through platforms like [Veil](https://veil.co) and [Reporters.Chat](https://reporters.chat/), which aim to simplify the process of using the platform, for the average user.

As it grows though, there are limited expansive analytics resources. While there are niche tools and other web platforms offering specific services (think [Predictions.Global](https://predictions.global/), [Crystal Ball Be](http://crystalball.be/stats/), etc.), there are currently no open-source platforms for analytics, statistics, historical reporting, etc.

### The solution
Augur.wiki is an open-source initative funded through the support of The Forecast Foundation (this grant), which aims to build a unified platform for Augur statictics and analytics. In specific, the current plan of action is focused around building:

1. Simple analysis dashboards which display specific network statistics (things like sync data, unique addresses, open interest, finalized markets, etc.)
2. Reporting dashboards which show the latest trades to happen on the platform in live-time.
3. Historical dashboards which allow users to search through past markets with simple keywords, view historical decisions made by other users, and analyze the specific hour-by-hour analysis of each market.
4. GraphQL API to allow developers to easily integrate platform data into their own applications.
5. A clean, easy-to-use User Interface so that the average user is able to easily access the data they need.
6. Plus, a few other small features I'm currently experimenting with (things like cross-platform alerts that you can setup to trigger when market actions occur, etc). More on this in the upcoming weeks, as I work out platform specifics.

### Proposed Milestones
Since payment is going to be handled in two seperate parts, I'll be breaking my work into two specific milestones. Of course, this is still a very brief spec., and as I begin working, I'll be adding on and checking off items on these lists.

#### First milestone
Estimated date of completion (including testing): April 1st, 2019

Description of tasks to complete by this date, in order to qualify for 50% payment:

1. [X] Procure domain name, hosting.
2. [X] Configure server architecture, load-balancing, auto-deployment, CI, and setup repository with contributing guidelines, and front-end + back-end starting points.
3. [ ] Finish building front-end; up until further back-end integration is required.
4. [X] Have Express server running and pushing out simple analysis dashboard views.
5. [ ] Have search functionality for historical markets live.
6. [X] Have minimal viable API functionality working.

#### Second milestone
Estimated date of completion (excluding final testing): April 22nd, 2019

Description of tasks to complete by this date, in order to qualify for remaining 50% payment:

1. [ ] Have GraphQL outgoing API fully functional.
2. [ ] Have historical reporting (non-search) built and ready-to-go.
3. [ ] Have livetime reporting dashboards be live-time instead of the WIP synchronous as in the first milestone.
4. [ ] Have developer documentation built and ready to go.
5. [ ] Be ready to go live.
6. [ ] Deploy to IPFS and be running a node to interact with the network in a more decentralized fashion (reducing reliance on third-party API's).
6. [ ] **Begin working on Augur.wiki link**. Let users easily sign a nonce with their frequently used Augur addresses and populate a personal dashboard with their market information, markets they've participated in, statistics, and setup alerts, etc.

For payments, my ETH wallet address is: `0x016C8780e5ccB32E5CAA342a926794cE64d9C364`.

Tying into development, each of these tasks will be a major issue on the the platforms Github organization project board with multiple sub-tasks for my codesprints. Once those are live, I will drop a message which will further elaborate on the basic guidelines outlined here. As always, though, happy to answer any and all questions regarding these milestones, and the bounty in general.

### Development
I'll be developing everything completely transparently. All development work will be taking place on the [Augur.wiki](https://github.com/augur-wiki) organization. If you're looking to stay up to date with development specifically, star and watch the [web repository](https://github.com/augur-wiki/web), since that is where I will be posting a majority of the updates regarding the platform and check-ins. After each one, I'll cross-reference here, to make sure that this ticket history is up to date.

In addition, I will be dropping live links here once this bounty is complete for future reference.

### Additional Information

Cheers, looking forward to seeing more amazing community bounties bringing innovation to Augur. Honored to be a part of it.

`Anish`

**Comment by petervecchiarelli** [comment]
@Anish-Agnihotri Hey, just checking in. Ping me on discord (can find me in Admins) and we can discuss progress/roadblocks.
