### ISSUE TITLE
Ether units are really jargony

### ISSUE THREAD

**Issue by evand** [AugurProject/augur#127]
Displaying units of ether with specialized units is really jargony, and makes things harder to understand for people not in the know about Ether. What's an Ether, a Szabo, or a Wei? What's the conversion ratio? Why am I thinking in these terms instead of just normal numbers?

**Comment by tinybike** [comment]
Agree 100% with this.  I don't understand why Ethereum uses so many different unit names, when they're just power-of-ten multiples of one another.  I think we should *only* use plain the plain Ether unit.  (Tricky enough to explain what CASH and Rep are, without also dragging in 15 redundant Ether designations...)

**Comment by evand** [comment]
Or, if 'Ether' is a really big or small unit in context, use an SI prefix. But use it consistently.

**Comment by tinybike** [comment]
The strange thing is, it isn't -- the way we have it set up, invoking contract methods requires about 30 Ether, which is a pleasantly boring number.  (Usually you get almost all this back immediately -- implementing a good estimation of contract gas use is definitely on the to do list...)

**Comment by theletterx** [comment]
I second the use of SI prefixes.  Ethereum's denominations are unintuitive and idol worship.

**Comment by scottzer0** [comment]
okay.  so i prefer this as well.  the base unit we're going for is 'ether' with SI prefixes.

**Comment by tinybike** [comment]
Removed confusing extra units in d6a285e2b632c37d4150ff3c15e760e74f626bd5.  The two units everyone seems to know are ether and wei -- so, ether is now shown as "ether" (if 1 ether or above) or "wei" (otherwise).  Will add in SI prefixes later if ether/wei are insufficient.
