### ISSUE TITLE
Candlestick mobile label position

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1272]
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/560c109b-e01d-4a71-8d2f-006deb23e007)

Need to stack dropdowns under open close high low labels for candlestick mobile.

~~Also, the crosshairs are reversed, xaxis should be hidden and yaxis visible, need to check highcharts css classes.~~ moved to another issue: 
https://app.zenhub.com/workspaces/augur-5bfed3424b5806bc2bf8d173/issues/augurproject/augur/1289

**Comment by bthaile** [comment]
stack 2 rows
first row is for O C H L
then the dropdowns on a second row.

**Comment by Chwy5** [comment]
On chrome/Windows the candlestick chart fluctuates it's size and when it expands and contracts the hover disappears.....

Also my hover gets cutoff at the top of the candlestick chart range

**Comment by bthaile** [comment]
I'll address the disappearing in other tix. @Chwy5 not sure what you mean by "Also my hover gets cutoff at the top of the candlestick chart range"

I'd like to see a picture or do you have a specific market?

**Comment by Chwy5** [comment]
spacing is better
