### ISSUE TITLE
null state alignment in my create markets

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1273]
![image](https://user-images.githubusercontent.com/3970376/54040884-04025780-418c-11e9-8ddb-ed2909a67115.png)

need to put null state label in middle center of quad.

**Comment by phoebemirman** [comment]
<img width="1505" alt="screen shot 2019-03-08 at 9 17 08 am" src="https://user-images.githubusercontent.com/6775839/54044103-f8f6f980-4182-11e9-9155-35448855bcc4.png">
this was fixed

**Comment by Chwy5** [comment]
Fixed
