### ISSUE TITLE
Portfolio Quads data fill/empty behavior

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1274]
![image](https://user-images.githubusercontent.com/3970376/54041654-de764d80-418d-11e9-9b63-7aaf1ca0da86.png)

Need to organized quads into columns so that if the quad above doesn't have data it shrinks to min height. It will allow the quad below to take up more room in the upper part of the page.

The quads might will look weird because they are accordaning. 

![image](https://user-images.githubusercontent.com/3970376/54042559-0b2b6480-4190-11e9-9752-0d614ab2d4ee.png)

**Comment by phoebemirman** [comment]
updated on new-trading-page-layout
