### ISSUE TITLE
Total Account Value portion of `Your Overview`

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1276]
![Screen Shot 2019-03-08 at 11.37.15 AM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/b1d5ff81-e2d5-4064-8a52-f2070f8afda8)

The green total portfolio percentage is still to be added from augur-node, just mock that out with `000.0000` will update when we get the data.

When user clicks time range, only Profit and Loss percentage changes

**Comment by bthaile** [comment]
More portfolio stuff popped up, moving this to Andy.

**Comment by Chwy5** [comment]
Only the % of Total Acct Value Changes:

Total Acct Value, Available Trading balance, FF and the Rep balance/staked remain the same (when toggling between time lengths)

**Comment by bthaile** [comment]
Yes, that is our understanding as well. 👍 
I updated the tix to be more clear.

**Comment by bthaile** [comment]
@andrewdamelio format frozen funds use formatEther `utils/format-number` 

![Screen Shot 2019-03-16 at 4 28 05 PM](https://user-images.githubusercontent.com/3970376/54481874-88964b00-4808-11e9-950f-2a33ab943830.png)

**Comment by bthaile** [comment]
Added blocking tix for augur-node work, need to get percentage change in user's Total Account Value.

**Comment by Chwy5** [comment]
ticket is redundant - works been done - closing
