### ISSUE TITLE
augur-node User Time Ranged User Stats

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1277]
Need time bound user's stats

Needs to be time ranged based 
24 hours, 1 week, 1 month, all time

stats are:

Positions
markets created
number of trades
successful disputes
markets traded
redeemed positions

![Screen Shot 2019-03-12 at 3 42 12 PM](https://user-images.githubusercontent.com/3970376/54234891-0d6a2780-44de-11e9-958b-adee1212714f.png)

I'm thinking the new getter will take:
`universe`
`account`
`endTime`

fyi: `all time` endTime will be null

endTime will need to be translated to block (being the earliest block to get information) Since augur-node db is block centric.

Where's the information: 

*markets created*: look in `markets` table, marketCreator field, for the give block range.

*positions* info, just unique market outcome share tokens the user owns in the given time range. example: If user owns Yes shares on market A and blahBlahBlah share tokens on categorical market, then user has 2 positions.

*number of trades* look in trades table for number of records where user is `filler` or `creator`

*markets traded* like number of trades but unique markets

*successful disputes* needs a bit more research, my initial thought is look in `crowdsourcers` table for user's (`reporter` field) contributions on payoutId. Need to cross reference to see if the payoutId was  the  winner when the market(s) resolved (market reporting state is `awaiting_finalization` or `finalized`). We don't want to get current disputing markets only those that have resolved.
Look in `get-dispute-info` getter for existing queries. FYI, don't need to look in `initial_reports` table that is first reporter not disputer. Look in `payouts` table for markets that have resolved and their winning payout, more info in `get-markets-info` getter for `winningPayoutRows`

*redeemed positions* look in trading_proceeds table for account is account field, use blockNumber to make sure it's in the time range

**Comment by bthaile** [comment]
Start time is earliest block
End time is most recent time

Other augur-node time range endpoints do this. 

StartTime: translate the timestamp to the corresponding block to get the start block.

EndTime: translate this timestamp to most recent block. 

Use queries to grab information between these two blocks. 

If startTime and endTime are 0 then grab the earliest and most recent blocks to get data from the database.

**Comment by pgebheim** [comment]
@brianosaurus Does that last PR close this issue as well or is this still in review?

**Comment by pgebheim** [comment]
Was closed with #2813
