### ISSUE TITLE
If a user trades vs themselves - both trades need to show in My Fills/filled orders

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1279]
In the event that a user trades with themselves, only one side of the trade shows up in the Filled/My fills sections...both need to show (1 a buy at xyz price and 1 a sell at xyz price)....both should have the same timestamp

UI gets this information from augur-node. `getTradingHistory` passing in user's account

**Comment by bthaile** [comment]
@Chwy5 can you confirm the self trading? moving this tix over to design review.

**Comment by Chwy5** [comment]
works better - closing
