### ISSUE TITLE
onboarding new user

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1283]
See blocknative.com for some ideas on onboarding new users. 
https://demo.blocknative.com/demo-page.html

--- 

Onboarding new users can be difficult, it depends on their understanding of the ethereum ecosystem and crypto currencies in general. This task is an effort to understand user flow. 

List of types of Crypto users:

1. New to crypto, owns zero crypto (Does not understand Gas, or Crypto Wallets)
2. Crypto Neophyte - follows BTC/Eth - has made small trades on CEX (like Gdax or Polo) - uses Coinbase (may have knowledge of MM or MEW), probably doesn't know what a Dex is, or its benefits
3. Power user - knowledge of Hard/soft wallets - makes multiple trades/tx/ and transfers

Types of Users and styles:

1.  Traders:
     A)  Buy and hold Traders (trader who trades equities, basic knowledge of retirement plan) casual user who may want to place a bet rather then sit and trade an event - most likely to use mobile
     B)  Day Traders (market makers) - this is a user who will most likely be sitting on a desktop, trading live events. Usually has finance/trading or sports betting background
     C)  Arbitrage Trader - spread trader, some manual trading, probably running a bot, might be on daily to weekly depending on risk parameters or frequency of events

2. Bettors:
      A)  Match bettor can either be a day trader or more casual user.  Will usually have an opinion on an event and look to take one side of it.  Most likely will come on the computer or check their phones once a day and place a bet
      B)  Betting exchange Bettor can be a day trader or arb trader - understands backing and laying bets.  This user is a liquidity provider and spends most of their time trading

New to crypto, has no ETH. We are assuming user does have access to already hosted augur-ui:

1. augur.net (or other entry point)
2. web app
3. scroll thru terms
4. check checkbox
5. click accept
6. click trade on market
7. sign in to trade
8. edge
9. create account
10. username
11. pin
12. password
13. finish
14. add funds
15. 8 steps on coinbase or wyre
16. Navigate back to augur
17. Navigate back to landing page
18. Navigate to market page again (need a back button)
19. Enter quantity
20. Enter Price
21. Review
22. Confirm buy
steps to do a trade on augur ^
Add 14 steps if you use metamask

**Comment by Chwy5** [comment]
I tweaked list of types of "Crypto" users and added types of users and styles

**Comment by joeykrug** [comment]
@cillianhunter0 re onboarding flow

**Comment by pgebheim** [comment]
no longer relevant
