### ISSUE TITLE
Initial loading of augur-ui when user is logged in has slowed down

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1284]
Investigate the initial loading difference between when user is logged in or not logged in.

Identify and delete calls to get data that isn't needed on load.

There is a lag between when the UI connects and when we send a request. Need to look for any timeouts or something.

**Comment by bthaile** [comment]
investigations, using local augur-ui connecting with Rinkeby augur-node:
start time: 1553121502758
call augur.connect: 1553121502758
return augur.connect: 1553121504192
call augur-node: 1553121504296
return augur-node: 1553121504365

total time to get augur-node data: ~1.6 seconds
augur.js connection: ~1.4 seconds
augur-node initial call response: 0.067 seconds

**Comment by bthaile** [comment]
total time to get augur-node data: ~1.6 seconds
augur.js connection: ~1.4 seconds
augur-node initial call response: 0.067 seconds

**Comment by Chwy5** [comment]
Night and Day improvement - closing
