### ISSUE TITLE
Show `Closed` if position has been closed

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1287]
If user closes position show `Closed` in portfolio sections in the UI. `Closed` should be default table label color, not green and not red. Changes are needed in both trading page position section and in portfolio positions quad.

![Screen Shot 2019-03-11 at 2 13 03 PM](https://user-images.githubusercontent.com/3970376/54151189-3b7d3800-4408-11e9-8a34-b0bb97ef5b03.png)

**Comment by phoebemirman** [comment]
this has been implemented on the portfolio page for the new order and position rows. 

we are waiting on the trading page to be updated with these rows. https://github.com/AugurProject/augur/issues/1124
