### ISSUE TITLE
mobile candlestick crosshairs are styled incorrectly

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1289]
![Screen Shot 2019-03-11 at 4.22.05 PM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/1c191f07-1ef1-4284-97a2-fe4871f49ffc)

**Comment by Chwy5** [comment]
When I go to view on mobile I dont even see the buttons for Price History, Candlestick and Market depth.  Preset is to Price History...so I cant view Candlestick in mobile version.  See attached screenshot.

Side note...you can see the issues w/ the Price history Chart x axis (also Yaxis on Mobile needs to be smaller)
![3-15-mob-candle.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/e5cdfcd3-550c-49c3-8188-f44ecc5299de)

**Comment by Chwy5** [comment]
ok I was able to get into candlestick on mobile - still no horizontal cross hairs on candlestick

**Comment by bthaile** [comment]
There is a chance css selector hides the wrong crosshair, highcharts crosshair drawing order is indeterminate on mobile.

will address with: https://github.com/AugurProject/augur/issues/1240

**Comment by pgebheim** [comment]
@JohnDanz -- Is this closable?
