### ISSUE TITLE
misalignment on page 3 of markets

### ISSUE THREAD

**Issue by pqdeep** [AugurProject/augur#129]
table misalignment on page 3 of markets (desktop view, mobile's fine):
http://demo.augur.net/markets/3

**Comment by scottzer0** [comment]
i'm not seeing anything misaligned.   i'm looking at all 4 responsive treatments on firefox and chrome on mac os.

can you tell me your platform and send a screenshot?

**Comment by pqdeep** [comment]
Firefox 39.0 - screenshot attached. Not sure what the deal is. Could be my
system, but I changed zoom levels - no effect. Should I check something
else? Maybe it has something to do with that invalid spam market.

**Comment by pqdeep** [comment]
![fireshot screen capture 022 - augur - demo_augur_net_markets_3](https://cloud.githubusercontent.com/assets/13311619/8762376/9d439d96-2d77-11e5-87e7-5402f39376ff.png)
