### ISSUE TITLE
Order Book changes

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1291]
1. Quantity right align text
2. padding decimals to be 4
3. leave enough room to allow for additional 4 characters to the right (8 total)
3. if more sig decimals past 4 add ellipse (...) to tell user they can hover to expand to show all 8 decimals.
4. allow 5 digits to left of decimal.

Market trading history task is here: https://github.com/AugurProject/augur/issues/1302

22222 (normal) just needs 4 decima padding.
22222.000009 (need hover expansion) `22222.0000...`
0.000009 (need hover expansion) in order book shows `0.0000...`
123456 (need hover expansion) in order book shows `12345...`

show ellipse when order book/market trade history quantity is 
greater than 99,9999 (whole number)
less than 0.0001

![Screen Shot 2019-03-13 at 12 04 42 PM](https://user-images.githubusercontent.com/3970376/54299135-3941e780-4588-11e9-96f9-a48ce09ced8a.png)

**Comment by matt-bullock** [comment]
![image](https://user-images.githubusercontent.com/39496225/54222176-2af6bb80-44f5-11e9-8d32-2202f5dfcd18.png)

cursor demonstrates hover on a dust order (0.0000…) to expand to show the full 8 decimlas (0.00000001)

**Comment by Chwy5** [comment]
I created an order to 8 decimal places and worked perfectly

I created another order out to 13 decimals and it gets messed up....The decimal place is no longer aligned and it cuts off the 0 on the left side of the decimal and the 13th decimal place on the right

it is in market?id=0x75ec1f1a3356517908eccb5f6e4fac619c68ba99

it is currently the 6th bid down on the order book, has a price of .1851

The Price in both the Bids and Offers section doesnt align (this might have something to do with it)...Looks Like Offer side of the book is right aligned and Bid Section is left aligned

**Comment by bthaile** [comment]
That was a decision we made. What should the order book quantity look like if the sig decimal is 13 or past the viewable 8 decimal places.

**Comment by Chwy5** [comment]
I am not sure that its working properly.....
b/c in the Market Trade History I can have one of the filled trades out to 14 decimal places and it fits

**Comment by bthaile** [comment]
We allocate space for 8 decimals in the order book so the width doesnt get too wide. 

I think we allocate more space in the market trade history. I’ll check out the difference in terms of 14 decimal places.

**Comment by bthaile** [comment]
![Screen Shot 2019-03-16 at 4 01 11 PM](https://user-images.githubusercontent.com/3970376/54481598-c1342580-4804-11e9-8e3f-0deeca8fba8a.png)

![Screen Shot 2019-03-16 at 4 01 17 PM](https://user-images.githubusercontent.com/3970376/54481600-c4c7ac80-4804-11e9-93d3-84ff8f6c2bf9.png)


I see the case you are talking about.

I think we need to round to 8 decimals.

**Comment by Chwy5** [comment]
Yup agree let show to 8 decimals on the right side of the decimal in expanded only

**Comment by Chwy5** [comment]
Looks good - closing ticket
