### ISSUE TITLE
Remove lodash in augur-state and augur-ui

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1298]
replace all lodash instances and remove from package.json.

**Comment by justinbarry** [comment]
This tool purports to remove the array methods (forEach, map, etc....) from the codebase.

https://github.com/cpojer/js-codemod#underscore-to-lodash-native

**Comment by pgebheim** [comment]
In UI or everywhere?

**Comment by justinbarry** [comment]
Looks like there is some use in augur-state. Presumably it should go there as well.

**Comment by pgebheim** [comment]
Dup for for UI work, not a priority for augur-sdk.
