### ISSUE TITLE
latency - link responsiveness

### ISSUE THREAD

**Issue by pqdeep** [AugurProject/augur#130]
latency / lags (react.js?) - I frequently have to click links more than once (like the Market link to get from the Overview page to the Markets section) to get them to work

**Comment by scottzer0** [comment]
agreed, very annoying and not unknown.   with the initial load of markets and all the requests needed to fetch their data from ethereum contracts (and the subsequent react rendering) there's been many passes at optimizations and there will be more.

i'll leave this here as a placeholder for optimizing the initial loading experience.

**Comment by pqdeep** [comment]
I've gotten used to it, but yeah it can get annoying at times, especially
for a newcomers, I'm guessing. Yep, it's a secondary issue - just wanted to
know if you were aware of it.

**Comment by tinybike** [comment]
I believe this has been resolved via [marketeer](https://github.com/AugurProject/marketeer) -- latency/responsiveness issues were due to excessive amounts of network traffic bogging down the browser.
