### ISSUE TITLE
Market Trade History number format issues

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1302]
This task is to format market history trades like order book and have the same behavior for long numbers like order book quantity. See: https://github.com/AugurProject/augur/issues/1291
for details.

![Screen Shot 2019-03-12 at 2 07 38 PM](https://user-images.githubusercontent.com/3970376/54228549-6337d300-44d0-11e9-8443-21bdf8cbec25.png)

**Comment by Chwy5** [comment]
When Testing...I created an order out to 8 decimal places and this worked perfectly.

Works to 14 decimal places

How many decimal places are we showing to?  When we get past 8 the decimal doesnt align

**Comment by Chwy5** [comment]
looks like it is adjusting to 8- closing ticket
