### ISSUE TITLE
Mobile: Candlestick chart dropdowns miss placed 

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1303]
different than mobile style chrome on desktop, but on chrome iPhone, dropdown buttons are not on candlestick header with ochl values.

![image](https://user-images.githubusercontent.com/3970376/54229210-d3932400-44d1-11e9-842f-56091c065414.png)

**Comment by Chwy5** [comment]
The dropdowns appear over the candlestick chart, but the OCHL is missing and only appears after I hover the mouse over the  chart and the chart expands
![3-16mob.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/2fd96f47-96ef-4510-ba95-c9e611437660)

**Comment by bthaile** [comment]
That was by design for desktop, we carried that behavior over to mobile. 

On mobile we can make the ohlc labels stick around. Which I prefer for desktop as well. I"ll make the change.

**Comment by bthaile** [comment]
un-disappear ohcl when user isn't hovering over candlestick.

**Comment by Chwy5** [comment]
OCHL look good, I am not sure the weekly candlestick is working correctly on mobile

Also the Volume in Eth or shares drop down should be right aligned imo....see screenshot
![3-18c.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/7fa12b39-55a3-4b90-8c8f-2eb11bc8442d)

**Comment by bthaile** [comment]
Interesting there is a space between the dropdowns on mac chrome. 

I’ll create a separate tix anf get some design input on it, just to be sure. 

This one can be closed, if you think the main issue has been fixed.

**Comment by Chwy5** [comment]
Original Issue is fixed, closing this issue....Tom is making a ticket for spacing issue of dropdowns on chrome
