### ISSUE TITLE
login dropdown doesn't hide when you click off of it

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1309]
<img width="515" alt="Screen Shot 2019-03-13 at 11 06 07 AM" src="https://user-images.githubusercontent.com/6775839/54303354-0ac00e80-4580-11e9-93f1-3f4551373cbc.png">
<img width="542" alt="Screen Shot 2019-03-13 at 11 06 01 AM" src="https://user-images.githubusercontent.com/6775839/54303355-0ac00e80-4580-11e9-9a1d-21acdb67b2bf.png">

login dropdown doesn't hide when you click off of it

**Comment by Chwy5** [comment]
Works when ui doesnt freeze -  appears to be freezing issue

**Comment by phoebemirman** [comment]
i mean clicking on other parts of the screen, for example, the notifications dropdown.

it does work when clicking the original dropdown button.

**Comment by pgebheim** [comment]
@bthaile @andrewdamelio -- small one for next sprint!

**Comment by bthaile** [comment]
Yes good place for it.

**Comment by pgebheim** [comment]
Actually should probably wait for the Onboarding UX epic since this all may change -- realizing we don't have a follow-on epic for that yet, will make

**Comment by andrewdamelio** [comment]
closing - doesn't apply anymore
