### ISSUE TITLE
jumping tabs on trading page.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1312]
tabs on trading page jump when user has open order

![Screen Shot 2019-03-13 at 8 39 08 PM](https://user-images.githubusercontent.com/3970376/54325421-16d3bc80-45d0-11e9-88f1-fbe8e3e14c1a.png)

![Screen Shot 2019-03-13 at 8 39 12 PM](https://user-images.githubusercontent.com/3970376/54325422-1804e980-45d0-11e9-927a-f9bc667ef9ae.png)

Need to allocate space so that tabs don't resize when user has open order

**Comment by phoebemirman** [comment]
all the tables are supposed to have a lighter colored bottom bar

**Comment by phoebemirman** [comment]
fixed on new-trading-page-layout
