### ISSUE TITLE
Open order quantity is 0

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1313]
Not sure the scenario where open order amount is zero. Testing on Rinkeby, binary market. Had a long position and created new open order.

![Screen Shot 2019-03-13 at 8 23 18 PM](https://user-images.githubusercontent.com/3970376/54325565-f6f0c880-45d0-11e9-8266-84c915b8d4ba.png)

The full precision amount is correct.
I created open orders escrowing ETH and escrowing Shares and both had amount values.

![Screen Shot 2019-03-13 at 8 08 59 PM](https://user-images.githubusercontent.com/3970376/54325624-41724500-45d1-11e9-8207-464c3bdca513.png)

This issue needs more investigation.

**Comment by joeykrug** [comment]
will be diff w/ 0x anyway
