### ISSUE TITLE
Two ways to Sell complete sets, standardize

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1314]
Use modal to sell complete sets when user clicks on `Sell Complete Sets` button at bottom of positions page on market trading page.

Currently sell complete sets modal is used from notifications on account summary.

**Comment by Chwy5** [comment]
Wont be needed for V2.....selling complete sets will occur Automatically

**Comment by Chwy5** [comment]
adding modal for new notifications - closing
