### ISSUE TITLE
for market-rows, clamp market titles at longer than 3 lines with an ellipsis 

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1315]

**Comment by Chwy5** [comment]
@phoebemirman - what do you mean?

**Comment by phoebemirman** [comment]
<img width="505" alt="Screen Shot 2019-04-05 at 12 13 14 PM" src="https://user-images.githubusercontent.com/6775839/55651039-365ba080-579c-11e9-8893-8617663f6930.png">


limit the length of the market titles in these market cards (also in portfolio, positions, my markets, active markets)

**Comment by phoebemirman** [comment]
cut off with an ellipsis.

**Comment by Chwy5** [comment]
Ok gotchya...do we need design on that?

**Comment by phoebemirman** [comment]
no, @matt-bullock requested this a while ago.

**Comment by Chwy5** [comment]
Ok agree...moving this backed to be worked

**Comment by pgebheim** [comment]
@phoebemirman @bthaile -- Do the new market cards / portfolio cards do this now?

adding to bugs/misc for sprint 14

**Comment by Chwy5** [comment]
Currently does not cut off w/ an ellipse on the trading pg or in additional details, as well as the portfolio pg.  still needs to be worked on.
![8-11](https://user-images.githubusercontent.com/41301809/62833587-52ba8e80-bc0f-11e9-90c8-ad4f4cccebec.jpg)
