### ISSUE TITLE
Automate Finalization of All markets for V2

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1316]
Can we add the cost of finalizing a market into the market creation, so all markets can be finalized automatically, after a certain point in the process?

- How much additional cost would this incur?

**Comment by nuevoalex** [comment]
Is the idea that we would estimate the gas cost of finalizing the market and include that as a bond that is paid to whoever finalizes the market?

Not sure exactly what is proposed here if not.

**Comment by Chwy5** [comment]
Yeah or does that leave us with too much risk, bc we cant foresee the cost at time of finalization

**Comment by nuevoalex** [comment]
It would be fine I think if we provided it as an optional bond that would just be awarded to whoever finalizes the market where the creator can specify the amount they wish to award them. Then market creators have freedom and flexibility for that option since just compensating the gas cost even (if we could accurately get it every time) may not be enough to incentivize someone to do the tx.

**Comment by Chwy5** [comment]
I was just thinking more of an automated thing.....so markets (ones that never trade) dont get stuck in that limbo state of not finalized

**Comment by nuevoalex** [comment]
How would we automate it?Any state change on chain needs to occur as part of a tx so we either need to include the finalization as part of another transaction (Currently we do this for traded on markets when shares are claimed) or do pseudo-automation by paying someone to do the tx (This is how cryptokitties "automates" cat births for example)

**Comment by Chwy5** [comment]
Not really sure....I was thinking something along the lines of how orders can be given a time range to be cancelled.  Like I place an order on the book today, and it cancels in 2 weeks at 12 pm utc

**Comment by nuevoalex** [comment]
That's also not really implementable though. You could have it take an expiration date after which point it could not be taken for example but to return the escrowed funds someone would have to actually make a tx which specifically does that.

**Comment by Chwy5** [comment]
Kind of thought that, but thought it was at least worth exploring the idea...k thanks I'll close
