### ISSUE TITLE
Augur is vulnerable to clickjacking

### ISSUE THREAD

**Issue by sirdarckcat** [AugurProject/augur#1316]
I think you want to avoid being iframed:
http://evilwebsite.com/xss.php?frame_xss=https://dev.augur.net

This can be done in javascript, by checking that top==self or by adding an HTTP header that says [x-frame-options: deny](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options).

Risk of this is low, but you still probably should fix it.

**Comment by tomkysar** [comment]
cc @stephensprinkle @tinybike

**Comment by justinbarry** [comment]
@sirdarckcat Good catch and thank you for the report! I have moved this to our internal issue tracker.
