### ISSUE TITLE
add 3 day count down timer to claim proceeds notification

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1317]
![Screen Shot 2019-03-14 at 10 57 39 AM](https://user-images.githubusercontent.com/3970376/54371806-0ceda000-4648-11e9-92ea-426c36545443.png)

Mocks are in figma. When market is finalized and user has winning shares, show notification with count down timer from 3 days of market finalization.

The `view` button in the top mock needs to be greyed out.

When 3 day timer is out activate the notification like it's new and the `view` button is active.

**Comment by Chwy5** [comment]
I am not sure we need the "View" button on the one with the countdown clock.  Clicking it wont do anything ...i cant take the action of claiming until that clock expires

**Comment by bthaile** [comment]
It can be disabled or removed. Def not active.

I think the mocks have a button. Create an issue we can remove it.

**Comment by andrewdamelio** [comment]
The VIEW button for this card will appear disabled and unclickable in the UI.

**Comment by Chwy5** [comment]
Im closing this ticket and making a new one to remove the view button when claim proceeds is in countdown
