### ISSUE TITLE
Implement new flash scripts

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#1327]
Some of the flash scripts have been updated. Ideally these should be transitioned to typescript.

**Comment by robert-e-davidson3** [comment]
I started on the flash scripts but ran into a pretty big snag: they heavily depend on augur-node but augur-state isn't yet ready to step in. Once it is, this unblocks.

**Comment by pgebheim** [comment]
So I believe this has been started by the work on order creation.

Is this right?

@justinbarry should this be closed in lieu of the flash epic?

**Comment by justinbarry** [comment]
Yes.

**Comment by pgebheim** [comment]
Closing for the epic #1881 that expands all this into sub tickets.
