### ISSUE TITLE
Augur State Bulk Sync Chunking / Parallel Request Optimization

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#1328]
Currently, Augur State syncs each DB's block chunks sequentially from lowest block to highest. We should optimize it to retrieve all the block chunks in parallel and then queue the DB writes.

**Comment by pgebheim** [comment]
Currently this kinda already happens because we request all log types separately.

I think the real task here is to decide which log types to group and fetch all at once so that we can minimize the number of log range requests.
