### ISSUE TITLE
Implement Account getters with tests

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#1335]
- [x] getAccountTransactionHistory
- [x] getAllOrders
- [ ] getAccountTransferHistory
~~- [ ] getUserShareBalances~~ // not needed anymore, it was used for sim trade
- [ ] getWinningBalance
~~- [ ] getCompleteSets~~ // V2 contracts cash out completesets automatically as part of trading
- [ ] getAccountTimeRangedStats

**Comment by justinbarry** [comment]
Moved remaining sub-tasks to the deliverable epic.
