### ISSUE TITLE
Updates to "transaction history" modal 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1341]
Figma link: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=2725%3A135772

Updates: 
- addition of outcome column
- reduced "market name" column width 
- tweaked the spacing between each column (24px) 
- sort by column (only on cost basis and qty for now)
- tooltip for truncated text
- left aligned "action" column
- changed a value in the "action" column, "market finalisation" to "Finalised"

**Comment by Chwy5** [comment]
Finalized s/b spelled with a "Z" in it

**Comment by JohnDanz** [comment]
> Finalized s/b spelled with a "Z" in it

Don't worry chwy, I always Americanize the text ;)

**Comment by Chwy5** [comment]
@cillianhunter0 plz review design on this and make sure you are satisfied - do not close as i need to test functionality

**Comment by Chwy5** [comment]
at first glance...it has the old scroll bars vs horizontal and vertical on the pg

**Comment by cillianhunter0** [comment]
Looking good, couple of issues to fix up: 

- Max height is 100% of browser window
   - Can you change this so there is padding at the top and bottom of approx 80px
- The following labels and values are not right aligned 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/77f76b14-1961-4d5a-9db4-c6cdf7c8a5ed)
- Pagination isn't centered horizontally in the modal 
- Pagination component should be flexi width based on the number of pages, for example in this screenshot (build is top, design is bottom), the build has 2 pages, but it doesn't reduce in width so there is a large gap between the '1' and the '2'. The padding should be the same between pages as it is in the bottom version. 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/a84857da-f8bb-48f7-8e52-8faaad0684ce)
- Design change request: Column sort icon (triangles) were too small in design, I have updated these to be larger
- Design change request: space between the filters and the table, reduce from 40px to 24px to free up a little more space

**Comment by Chwy5** [comment]
@adrake33 plz rvw

**Comment by adrake33** [comment]
Ryan and I created https://github.com/AugurProject/augur-node/pull/846 to fix the totals calculation for buy/sell actions.

**Comment by bthaile** [comment]
looks like code was merged. moving this to UI dev Outgoing. 

@adrake33 can this go to @Chwy5 for testing?

**Comment by adrake33** [comment]
Yes, the AN changes are ready for testing now.

**Comment by bthaile** [comment]
ok, moving to `Design Review` for @Chwy5 to test.

**Comment by Chwy5** [comment]
@adrake33 @bthaile Its not displaying any information....says NO Transactions....though i have over 240 trades in this acct

**Comment by adrake33** [comment]
This was occurring due to an error in the query for sell txs (but not buy txs). The fix has been merged: https://github.com/AugurProject/augur-node/pull/847.

**Comment by Chwy5** [comment]
looks better - closing
