### ISSUE TITLE
Claim proceeds notification 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1342]
Figma: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=2662%3A904

Notes
- There are two states for the 'Claim proceeds' notification 
 - A) claim proceeds when waiting period ends (includes countdown timer) 
 - B) claim proceeds now 
- Strings have been updated

**Comment by bthaile** [comment]
@andrewdamelio Take a look at this and see if there are any questions before dev.
