### ISSUE TITLE
"Receive funds" modal 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1343]
Figma: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=6939%3A265238

Notes
- Strings updated
- New address component with micro interaction when user copies the address
- - Check mark appears for 3 seconds and then returns to copy icon
- - Tooltip appears for 3 seconds and then disappears

**Comment by bthaile** [comment]
@JohnDanz see if this tix has everything needed to start the task.

**Comment by cillianhunter0** [comment]
@bthaile what's the new copy you mentioned on this?

**Comment by bthaile** [comment]
It was on the REP faucet. Check out sneakpreview if the account summary loads for you. There could be a loading issue between inital load and nav to acct sum straight away. It should load if there is web console errors that would be helpful.

**Comment by cillianhunter0** [comment]
Issues
- QR code should have a 4px white border (left is correct)

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/17b89585-987f-46ee-999e-0661261a3365)

**Comment by joeykrug** [comment]
this is missing a lot of data
go to the current augur site now and account page and deposit to see how it looks now
copy could be improved on that version

but this one has no deposit info

also on the wyre link it should go to https://dash.sendwyre.com/sign-up not just sendwyre.com

**Comment by bthaile** [comment]
Created a specific design tix to track this.  https://github.com/AugurProject/augur/issues/new

**Comment by bthaile** [comment]
@Chwy5 this is polish since we moved the missing items to another tix. recommend v1.14
