### ISSUE TITLE
"REP faucet" modal 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1344]
Figma:
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=6939%3A265203

Note:

A 'processing transaction' state was included in the flow to provide feedback immediately after user taps "send rep", thoughts here? Do we expect each wallet will prompt the user immediately after the tap 'send rep' so we don't need to provide feedback etc?

**Comment by bthaile** [comment]
Don't add the "feedback" wait modal. The tx is sent and that is it. It's free testnet REP, don't need multiple modal workflow.

@JohnDanz see if this makes sense.
