### ISSUE TITLE
Chart shading for profit and loss and scalar/binary price history

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1345]
wrong area on profit loss chart is shaded when user has negative profit

![Screen Shot 2019-03-15 at 1 48 48 PM](https://user-images.githubusercontent.com/3970376/54455145-1569d780-4729-11e9-8d8e-3dd05631a49a.png)

Shading was reversed with negative chart values. I removed the shading, this tix is to add it back in and verify shading is correct for positive and negative `realized` values. 

Same issue in trading price history chart:

![Screen Shot 2019-03-18 at 12 00 43 PM](https://user-images.githubusercontent.com/3970376/54548981-0d9f7280-4977-11e9-92cf-0005a951ce74.png)

**Comment by bthaile** [comment]
added up totals for the user's portfolio change. Still need percentages.

Need tix: https://github.com/AugurProject/augur/issues/1187

**Comment by Chwy5** [comment]
The profit an loss chart doesnt look correct.
If All time is selected, it needs to show the ebbs and flows of the changes over that time period
It is supposed to show the life cycle of the PnL over the time period selected, not just a final number

**Comment by Chwy5** [comment]
Shading looks good for scalars

**Comment by bthaile** [comment]
Do you have a screenshot of what your talking about?  It should look the same as the old portfolio chart.

**Comment by Chwy5** [comment]
![3-19pnlchart.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/4116324b-7a2b-4e6b-a617-b8a8fef6fdba)

This acct shows all time Pnl form nov 20th to now....I should have many peaks and valleys in it, as some days I added to my Pnl total and others my total decreased

**Comment by bthaile** [comment]
moving this tix to closed, creating a tix specifically for profit and loss chart data.

new issue: https://github.com/AugurProject/augur/issues/1418
