### ISSUE TITLE
Wire up profit and loss totals

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1346]
Currently profit and loss values are stubbed out, need to get from augur-node.
![Screen Shot 2019-03-15 at 1 48 48 PM](https://user-images.githubusercontent.com/3970376/54455332-89a47b00-4729-11e9-9815-5e9304cf3a7e.png)

added  Realized for ETH value and percentage change in profit and loss.
hoping augur-node changes to user position will add realized percentage to get-profit-loss.

**Comment by bthaile** [comment]
This tix isn't blocked, not sure how to remove the dep.

**Comment by bthaile** [comment]
UI is already wired up and gets the realized percentage.

**Comment by Chwy5** [comment]
Looks to be working correctly now - closing
