### ISSUE TITLE
"Transactions" card on the account summary page

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1347]
Figma:
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=2704%3A981

Notes: 
- Button paddings standardised
- New strings (Send, Receive, Your Wallet, Your Transaction History)
- New icons for send and receive buttons

**Comment by cillianhunter0** [comment]
Test net version with REP Faucet:  

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/ce011e2d-b9ca-46fc-a794-575fafb78f0b)

**Comment by bthaile** [comment]
Obvious but just making a note that `REP Faucet` is only for non-mainnet.

**Comment by cillianhunter0** [comment]
Padding issues in the build: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/31af915d-ab73-479c-935b-c9a48d0fdad3)

Should be: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/2b028366-d547-434e-a951-8c0c9713df0a)

**Comment by bthaile** [comment]
@Chwy5 can you put a priority on this one.  then move to our incoming.

**Comment by bthaile** [comment]
close this b/c https://github.com/AugurProject/augur/issues/1526 covers these changes.
