### ISSUE TITLE
Holdings Clarity Issue

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#135]
![screen shot 2015-07-28 at 12 37 57 pm](https://cloud.githubusercontent.com/assets/5925937/8938784/4e67f242-3526-11e5-94f2-8361ba7eeabc.png)

Someone pointed out that it's not super clear that the % on the left side is odds/likelihood percent

**Comment by scottzer0** [comment]
yes, this is a general UX issue across the site where ever we we what to summarize the current state of a market.  we use the 'YES' outcome in the market pane as well.  although here, it's closely associated with a particular outcome holding and that could be more confusing if it's the 'NO' holding.

**Comment by tinybike** [comment]
No longer relevant; closing.
