### ISSUE TITLE
Limit number of decimal Places in the order ticket to match what is displayed in the extended states

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1353]
The order ticket allows user to input up huge numbers of decimals...more than our expanded states display.  Should limit it to match the expanded states

**Comment by Chwy5** [comment]
want to allow user to take existing dust orders off the book, but when creating new orders create quantity to max decimal limit of 8.....

v2 make min trade amt

**Comment by bthaile** [comment]
@Chwy5 can this be closed?
