### ISSUE TITLE
order book/ market trade history expansion value is more than 8 decimals.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1354]
![Screen Shot 2019-03-16 at 4.01.11 PM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/65893016-e827-4ac9-ad18-bea1c0d164b2)

![Screen Shot 2019-03-16 at 4.01.17 PM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/6d35b3f4-a4cf-4df7-8804-8fc037c463ad)

In the above example, the value can be rounded to 8 decimals. 
`5.19010595772242`
would show `5.1901` and `5.19010596` on expansion. Is that correct?

@Chwy5  What if the order book quantity is `5.00000000772242` or 5.00000000002242 ?
What would be shown? in Order book and on expansion?

After discussion with @Chwy5 
round decimal places to 8 decimals if all 8 decimals are zeros then just show `x.0000` in the order book.

**Comment by bthaile** [comment]
@phoebemirman this is good to go. check it out. see if you have any questions.

**Comment by Chwy5** [comment]
Looks good - closing
