### ISSUE TITLE
Fix history object deprecated method

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1355]
![E27EBBF5-515E-4F8D-96C5-AC65FF45F1E3](https://user-images.githubusercontent.com/3970376/54484915-85698200-483d-11e9-9db6-d377d9cb2ed4.jpeg)

Find and fix deprecated place with history object. Might be browser specicif. Needs investigation

**Comment by Chwy5** [comment]
I havent gotten the error this morning while testing since the last update- will keep an eye out for it- closing ticket for now
