### ISSUE TITLE
Limit quantity to 8 decimal places

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1357]
Since we only have room to show 8 decimals in order book and market trading page, lets be consistent and only allow 8 decimals in quantity.

![Screen Shot 2019-03-17 at 1 52 24 PM](https://user-images.githubusercontent.com/3970376/54496329-01a2aa80-48bc-11e9-956f-44eb025e9cc9.png)

**Comment by Chwy5** [comment]
This is still not fixed....It allows me to add more than 8 decimals into quantity

**Comment by Chwy5** [comment]
looks good - closing
