### ISSUE TITLE
candlestick chart crosshair price cuts off at top

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1358]
![Screen Shot 2019-03-17 at 1 59 31 PM](https://user-images.githubusercontent.com/3970376/54496404-ebe1b500-48bc-11e9-8e63-e038326c57c5.png)

price cuts off at the top need to add top padding.

**Comment by bthaile** [comment]
fixed for mobile

![image](https://user-images.githubusercontent.com/3970376/56070818-d6db3300-5d4f-11e9-85bf-514bd1cd3f1f.png)

**Comment by Chwy5** [comment]
Bo longer getting cut off but not seeing the dotted crosshair line

**Comment by bthaile** [comment]
Theres an existing tix for the dotted line missing on mobile. Recommend closing this one.

**Comment by bthaile** [comment]
@Chwy5 I think we can close this one.
