### ISSUE TITLE
Need to disable ‘view’ button after running action

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1359]
In the notifications is possible for the user to click ‘view’ button and send transaction then click ‘view’ again to bring up the modal again and send the transaction again. 

Notifications need to know the transaction has been sent and disable the ‘view’ button. 

Lets just disable the ‘view’ button.

**Comment by bthaile** [comment]
This should be in ‘UI Dev Incoming’ on mobile, dont have the option. Does this task make sense?

**Comment by Chwy5** [comment]
Perfect....looks much better....closing
