### ISSUE TITLE
Need to tell user they are not connected to augur-node

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1362]
There's a possibility that user losses connection to augur-node and doesn't know it. The block processing won't tell them since all block processing numbers come from augur-node.

User could be in a state where data isn't updating and they are making trades and not seeing the result. 

I recommend some indication where `Blocks Behind` is that informs the user.

**Comment by cillianhunter0** [comment]
How does this issue get resolved for users?

**Comment by bthaile** [comment]
Actually the UI should show the Not currently connected modal. That might be the real issue.

**Comment by bthaile** [comment]
just tested and UI does show `Reconnecting to Augur Node` and if fails shows correct connection Modal. I'll close this. 

What I saw was UI connecting to a augur-node that isn't fully synced. I think that is a rare edge case. closing
