### ISSUE TITLE
Trading page errors

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1363]
In mobile view, navigate to trading order form.

![Screen Shot 2019-03-18 at 10 40 12 AM](https://user-images.githubusercontent.com/3970376/54542677-4258fd00-496a-11e9-9f8b-730be925a755.png)

**Comment by pgebheim** [comment]
@phoebemirman Is this issue fixed by #2760? If so can you move this into Closed?

**Comment by phoebemirman** [comment]
chwy is testing this

**Comment by bthaile** [comment]
Chwy you can just test this one on desktop.

**Comment by Chwy5** [comment]
didnt see this error message-closing ticket
