### ISSUE TITLE
Too many clicks for mobile user to get out of trading page

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1364]
User has to click 3 times to get you of trading page once on order form. Recommend moving <- arrow to go back to market list to same level as `Market Info`, `Trade` and `Orders`

![Screen Shot 2019-03-18 at 10.42.07 AM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/2d77ccab-acbe-415c-8282-02d1a68db3f9)

![Screen Shot 2019-03-18 at 10.43.00 AM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/2a63206e-06d1-4cf0-9946-61b7d670576c)

![Screen Shot 2019-03-18 at 10.43.33 AM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/91ea908f-734e-40d0-9afd-ce1462b164b1)

**Comment by cillianhunter0** [comment]
@matt-bullock are you looking at this? 

If we don't have a clear solution right now I suggest we come back to this issue later.

**Comment by bthaile** [comment]
It looked like Matt had a solution for this based on the mobile designs we talked about. He was goimg to move the back arrow to the same level as ‘Market Info’ ‘trade’ and ‘orders’ at the top of the mobile trading page

**Comment by matt-bullock** [comment]
Solution for this is in the latest trading page mobile mocks

**Comment by matt-bullock** [comment]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/c504b01c-d6c4-40f6-90df-7d21bb355d0f)

can we use the correct size arrow. It's the same arrow we use to expand the tables

**Comment by bthaile** [comment]
Andy can you update the arrow size?

**Comment by andrewdamelio** [comment]
@bthaile 💯

**Comment by andrewdamelio** [comment]
this appears to be fixed, agree @matt-bullock

**Comment by matt-bullock** [comment]
Looks good
