### ISSUE TITLE
augur-node, user's account total account value change over time range

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1365]
![Screen Shot 2019-03-18 at 10.53.49 AM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/122050c7-4fd1-4bc7-bfab-ee1f6a282722)

Need realized P/L for time range.

options:
1 ) Currently we aren't using `getProfitLossSummary` maybe we can use it for this functionality or we can 

2 ) Add a new property to existing `getUserPositions` 
that adds realized p/l for {day: ###, week: ###, month: ###, allTime: ###}

ONE is the Realized P/L in ETH

these items we already have:
TWO is user's account current balance
THREE is the user's current frozen funds.

I need value ONE, given the Time range (24 hour, 1 week, 1 month, all time) how to calculate:

parameters:
universe,
account,
startTime
endTime

**Comment by Chwy5** [comment]
Not changing those values with time range change - moved time change button below to avoid concussion
