### ISSUE TITLE
formatting frozen funds.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1366]
Need to hook up loginAccount eth balance to Available Trading Balance and sum frozen funds with available to get the total (bold number with ether symbol)

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/dafff1ef-ba4f-4d88-a948-f969904f489c)

format frozen funds use formatEther utils/format-number

**Comment by Chwy5** [comment]
Looks gd...closing
