### ISSUE TITLE
Fix the wording in the REP faucet

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1369]
![Screen Shot 2019-03-18 at 12 42 24 PM](https://user-images.githubusercontent.com/3970376/54551088-4fcab300-497b-11e9-8824-00144836a77f.png)

super minor, new wording is

`Get test net REP, it will be sent to your connected wallet`

the button `Send REP` should say `Get REP`

**Comment by bthaile** [comment]
@JohnDanz do you agree with this change, ran it by design. Currently it's confusing.

**Comment by Chwy5** [comment]
fixed
