### ISSUE TITLE
numeric tooltip shows when no decimal value

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1370]
![Screen Shot 2019-03-18 at 1 10 39 PM](https://user-images.githubusercontent.com/3970376/54553150-94584d80-497f-11e9-903c-c8d57aba21bc.png)

values from augur-node for position are all whole numbers
![Screen Shot 2019-03-18 at 1 11 43 PM](https://user-images.githubusercontent.com/3970376/54553171-9e7a4c00-497f-11e9-90a6-aa85af7f387d.png)

if no decimal values in number don't show tooltip

![Screen Shot 2019-03-18 at 1 12 31 PM](https://user-images.githubusercontent.com/3970376/54553178-a0dca600-497f-11e9-8433-8fb8a559aa0f.png)

**Comment by Chwy5** [comment]
fixed
