### ISSUE TITLE
2 digit days in date format in portfolio page

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1371]
dates on market trading page and portfolio page `filled orders` as an example, need to use two digit day. 

![Screen Shot 2019-03-18 at 1 19 58 PM](https://user-images.githubusercontent.com/3970376/54553628-a4bcf800-4980-11e9-8a77-8cc9e4a19c46.png)

![Screen Shot 2019-03-18 at 1 21 15 PM](https://user-images.githubusercontent.com/3970376/54553677-bf8f6c80-4980-11e9-90a6-8027751d7581.png)

**Comment by phoebemirman** [comment]
there is no space in the mocks 
![Screen Shot 2019-03-18 at 11.25.35 AM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/ec21f22e-ea5e-4007-8ab5-633dd930f2c2)

**Comment by bthaile** [comment]
I'm a bit confused, what do you mean no space in the mocks?

**Comment by phoebemirman** [comment]
never mind actually. i thought you were saying to add a space between the date and month

**Comment by bthaile** [comment]
This tix is just for the date format. Theres another one specifically for the space. Only happems when the width gets squashed.

**Comment by Chwy5** [comment]
Does the Timestamp in the extended version - should this match the fill date like 23Jan 2019, instead of Jan 23, 2019

**Comment by phoebemirman** [comment]
it should. i'll add that

**Comment by Chwy5** [comment]
It shows  Jan 23, 2019 style in the extended states of Filled and open orders as well.....I think Tom and I just made a ticket for that a few hrs ago

**Comment by Chwy5** [comment]
fixed - closing
