### ISSUE TITLE
squashed values in portfolio filled orders 

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1372]
![Screen Shot 2019-03-18 at 1 22 57 PM](https://user-images.githubusercontent.com/3970376/54553823-109f6080-4981-11e9-9178-5aaef3b63dfe.png)

issue in from @Chwy5, give a bit more space between Price and Fill Date. there is room on the right side of Fill Date, see image above.

**Comment by phoebemirman** [comment]
there isn't really space on the right side of fill date because the headers (Fill Date and No. of Fills) need some space between them. It looks weird if they are too close.

**Comment by bthaile** [comment]
The headers are spaced correctly, it's the data that gets messed up.

**Comment by phoebemirman** [comment]
The headers need to have the same width as the data to be aligned with
them.

**Comment by Chwy5** [comment]
Looks better - closing
