### ISSUE TITLE
tokenEscrowed is undefined.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1373]
![Screen Shot 2019-03-18 at 1 43 00 PM](https://user-images.githubusercontent.com/3970376/54555028-dc796f00-4983-11e9-80c3-dbe0c42ec9fd.png)

Issue happened on open-orders.tsx, happened as order was pending.

repro:

on market trading page take an order sign tx,
navigate to portfolio.

I had an existing position and was partially closing it out.

**Comment by pgebheim** [comment]
@phoebemirman Was this fixed along with Squashed Headers?

If so we should move the issue to closed.

**Comment by bthaile** [comment]
It needs to be tested. I would like Chwy to test it on sneakpreview.

**Comment by Chwy5** [comment]
I havent been able to reproduce this error - closing ticket
