### ISSUE TITLE
Order book Price Column Bids and Offers are not aligned

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1374]
see screenshot
![3-18price.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/e5a19978-7dd7-4ff0-b4d0-75c0e40ba0e2)

Create various sized orders in bid side of the book and a few regular ask orders and see if ask side doesn't align correctly.

**Comment by Chwy5** [comment]
Still not lining up sometimes....see sceenshot:

Either being caused by ellipse on offer side order or being caused by ugly scroll bar pushing in on bid side

**Comment by phoebemirman** [comment]
@Chwy5 do you have a sceenshot? that link is not one.

**Comment by Chwy5** [comment]
![3-22A](https://user-images.githubusercontent.com/41301809/54839793-01325700-4ca2-11e9-9c67-70983c932dd7.jpg)

**Comment by phoebemirman** [comment]
@Chwy5 do you have a screenshot with the headers in them?

i also don't see the issue where the ellipse makes them misaligned?

**Comment by Chwy5** [comment]
![3-22e](https://user-images.githubusercontent.com/41301809/54841828-99323f80-4ca6-11e9-8b33-9980ceab1b3d.jpg)

**Comment by Chwy5** [comment]
better - closing
