### ISSUE TITLE
Quadrants on Acct Summary pg, can extend too long

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1378]
Notifications section extends like 3 pages long.  Needs some type of end bound

**Comment by bthaile** [comment]
Is there a max-height on the account-summay? @andrewdamelio

**Comment by andrewdamelio** [comment]
@bthaile currently no max-height is set on any of the quads on the account-summary.

**Comment by bthaile** [comment]
Needs to be the same as portfolio. I think thats 50%

**Comment by andrewdamelio** [comment]
confirmed ```max-height: 65vh;```
