### ISSUE TITLE
Mobile candlestick range dropdown and volume dropdown placement/style

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1379]
![Screen Shot 2019-03-18 at 4.09.50 PM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/3285b79a-ff24-4640-8ee0-c349cc6c6f33)

We stacked the ochl above the dropdowns b/c there wasn't any room to have them in a line.

Design have any thoughts?

**Comment by matt-bullock** [comment]
placing below the buttons makes it more connected to the chart. Saves jumping over an obstacle.
Please see the figma mobile designs for guidance 

![image](https://user-images.githubusercontent.com/39496225/54605004-76a2eb00-4a48-11e9-8b18-d7342bc03e18.png)

**Comment by bthaile** [comment]
taking this tix for development. @phoebemirman see design for mobile candlestick dropdowns.

**Comment by Chwy5** [comment]
box location looks fixed - closing ticket
