### ISSUE TITLE
Need copy for trading page report indicator

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1381]
![Screen Shot 2019-03-18 at 3.38.43 PM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/139dd8fa-9bff-414a-9b7b-5823cade3030)

need copy for this: "Go to the reporting form to decide on an outcome"

**Comment by bthaile** [comment]
Having better verbiage would give the user/trader a better idea of the reason for the `Report` button. I agree.

**Comment by cillianhunter0** [comment]
"Reporting is open
 Submit the winning outcome to begin the disputing process" 

This could be better, but is this an accurate description?

**Comment by Chwy5** [comment]
I dont like this sentence....Submit the winning outcome to begin the disputing process"(its confusing to a new user- actually its confusing to me and I know whats going on)
They are together, but almost think of them a separate actions....1) Reporting process and 2) dispute process
I think we need better wording for that

**Comment by bthaile** [comment]
As I understand Augur, the wisdom of the crowd, aka oracle... 
We could use terms like the Truth, actual outcome of the event. 

Mainly it comes down to the event result as defined by the resolution source.

**Comment by cillianhunter0** [comment]
"Reporting is open: submit the winning outcome of the event" (?) --> tooltip that briefly explains what this means. 

Why a tooltip? Because it's a new, unfamiliar concept, it's a one of the few times it makes sense to use helper text to explain things to people. 

e.g. "Augur's community of users determine the winning outcome of all events, using a process known as "disputing", that ensures the correct outcome is reached each time. Read more."

**Comment by bthaile** [comment]
@Chwy5 thoughts on the above verbiage?
@matt-bullock are you working on verbiage for trading page?

just to give a list, not sure if all reporting states need detailed explanation. 
- designated reporting
- open reporting
- dispute
- finalize
- waiting period
- claim proceeds
- migrate (after fork is successful)

**Comment by Chwy5** [comment]
I actually think just saying "Submit the winning outcome" explains everything that is needed at that stage

**Comment by Chwy5** [comment]
@matt-bullock whats the status on this

**Comment by matt-bullock** [comment]
We have all the copy for these on the market page headers section of the trading page desktop design. Tom and Chwy have reviewed all these and I believe they're good to go but if not can you guys sign off on the copy in the figma design
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/1d000af6-ec76-44d3-a11b-ca0a45120256)

**Comment by Chwy5** [comment]
yeah they are good to go

**Comment by Chwy5** [comment]
closing
