### ISSUE TITLE
numeric tooltip shown when it doesn't need to

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1386]
don't need ellipse/tooltip when the value can be rounded to nearest 4 decimal places. 
value below can be represented as 0.8993

![Screen Shot 2019-03-19 at 9.54.26 AM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/efd8df80-2a35-45a8-bf63-f563a849e296)

**Comment by JohnDanz** [comment]
<img width="313" alt="Screen Shot 2019-03-19 at 12 34 30 PM" src="https://user-images.githubusercontent.com/10524630/54628365-650b1480-4a43-11e9-8ecc-8a73a350c084.png">
<img width="294" alt="Screen Shot 2019-03-19 at 12 34 27 PM" src="https://user-images.githubusercontent.com/10524630/54628366-650b1480-4a43-11e9-828b-bc392e0e0706.png">
<img width="230" alt="Screen Shot 2019-03-19 at 12 34 04 PM" src="https://user-images.githubusercontent.com/10524630/54628367-650b1480-4a43-11e9-880e-ea244bdab31e.png">
<img width="239" alt="Screen Shot 2019-03-19 at 12 33 57 PM" src="https://user-images.githubusercontent.com/10524630/54628369-650b1480-4a43-11e9-877f-a64552bc8aef.png">
<img width="205" alt="Screen Shot 2019-03-19 at 12 33 55 PM" src="https://user-images.githubusercontent.com/10524630/54628371-650b1480-4a43-11e9-8f82-652c77e5a8de.png">
<img width="344" alt="Screen Shot 2019-03-19 at 12 35 45 PM" src="https://user-images.githubusercontent.com/10524630/54628441-8c61e180-4a43-11e9-80f2-fcd8d437ee8b.png">

**Comment by Chwy5** [comment]
looks to be fixed - closing
