### ISSUE TITLE
orphan order needs to match new row styles

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1388]
<img width="1217" alt="Screen Shot 2019-03-19 at 11 17 11 AM" src="https://user-images.githubusercontent.com/6775839/54631145-a1854300-4a38-11e9-870b-2a8725a2ee72.png">

**Comment by Chwy5** [comment]
@matt please rvw

**Comment by matt-bullock** [comment]
looks good. We have recently restyled this but implementing that is lo priority. Will create a new ticket for it
