### ISSUE TITLE
trading page outcome labels misaligned

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1389]
Outcomes table - all values are out of alignment except for the 'last' value 

![Screen Shot 2019-03-19 at 1.31.12 PM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/921d79a1-4906-434c-8013-b09f8f05ed4b)

**Comment by phoebemirman** [comment]
this is the same as this https://github.com/AugurProject/augur/issues/1380

**Comment by Chwy5** [comment]
Looks better - closing
