### ISSUE TITLE
Order ticket: never show scientific notation

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1390]
Order ticket - never show scientific notation in total order value field (or anywhere!)

**Comment by Chwy5** [comment]
Still seeing this in the messaging for opening/closing a position

see screenshot![3-21scnot.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/dcb5b741-e6ad-427b-a318-27c91a2b43d9)

**Comment by bthaile** [comment]
@Chwy5 not sure what "Still seeing this" is referring to.

**Comment by Chwy5** [comment]
I am still seeing scientific notation....if you look in the above screenshot under closing position...it says Buying Back 1.2552585e-10

**Comment by bthaile** [comment]
aaaahhhh, I see the scientific notation, I missed it.

**Comment by bthaile** [comment]
Accidently put `Needs Approval` on this tix.

**Comment by Chwy5** [comment]
looks fixed - closing ticket
