### ISSUE TITLE
My fills: transaction details data should be approx a third of the width of the whole row 

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1393]
My fills - when i expand a row, the columns should be approx a third of the width of the whole row 

![Screen Shot 2019-03-19 at 2 58 15 PM](https://user-images.githubusercontent.com/3970376/54637807-8a098280-4a57-11e9-9fa3-d198c747fc34.png)

**Comment by phoebemirman** [comment]
is this for both trading page and portfolio page?

the mocks look like the screenshot
<img width="351" alt="Screen Shot 2019-03-19 at 1 17 43 PM" src="https://user-images.githubusercontent.com/6775839/54638952-7b1bd380-4a49-11e9-83a4-31e47e366096.png">
<img width="544" alt="Screen Shot 2019-03-19 at 1 17 23 PM" src="https://user-images.githubusercontent.com/6775839/54638953-7b1bd380-4a49-11e9-9cf8-95173d5f797f.png">

**Comment by bthaile** [comment]
we use the same Filled Orders component for trading page and portfolio page.

**Comment by phoebemirman** [comment]
should the middle column be center aligned? (the data and the header)

**Comment by bthaile** [comment]
@Chwy5 @matt-bullock 

What should the view transactions details look like in portfolio filled orders and trading page filled orders. We are using the same component. 

So we need direction on how existing needs to change?

existing:
![image](https://user-images.githubusercontent.com/3970376/54641032-2a16da00-4a5f-11e9-8dfc-914bd54c10d9.png)

![image](https://user-images.githubusercontent.com/3970376/54641066-40bd3100-4a5f-11e9-85e5-38efa09e94c4.png)

**Comment by matt-bullock** [comment]
![image](https://user-images.githubusercontent.com/39496225/54773852-b9acbc00-4c0a-11e9-91c0-56a9bebb1351.png)

These are fixed width and set to the right. Please see filled orders components on Portfolio - Desktop page for exact measurements.

**Comment by bthaile** [comment]
Notice the date time format has changed, @phoebemirman

**Comment by matt-bullock** [comment]
looks good. Can you give the headers' filled', 'timestamp' and 'TX details' the same styling as the other column headers. Mono Caps and grey - see above screenshot

**Comment by Chwy5** [comment]
@matt-bullock please review design changes look correct now

**Comment by Chwy5** [comment]
fixed - closing
