### ISSUE TITLE
remove price next to scalar denomination.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1394]
Outcome table - scalar markets - in the outcome column, only show the outcome name, not the current outcome price  

![Screen Shot 2019-03-19 at 3 09 11 PM](https://user-images.githubusercontent.com/3970376/54638408-fafd6a00-4a58-11e9-984e-f2875d6d92c2.png)

since we show denomination and last price in the outcome row.

**Comment by Chwy5** [comment]
fixed - closing
