### ISSUE TITLE
dropdown formatting fixes

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1395]
dropdown formatting:

dropdown width is determined by the widest item in the list.
![image](https://user-images.githubusercontent.com/3970376/54638927-3187b480-4a5a-11e9-8659-581562434af6.png)

dropdown items height is determined by the standard height of the dropdown button

![Screen Shot 2019-03-19 at 3 15 47 PM](https://user-images.githubusercontent.com/3970376/54638902-23399880-4a5a-11e9-9d66-ed8d171c5c9e.png)

**Comment by Chwy5** [comment]
looks good- closing
