### ISSUE TITLE
outcome name is too long - show tooltip

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1396]
Positions - if outcome name is too long - show tooltip - design need to create rules for the tooltip, max width etc 

Need design for tooltip for outcome name, .... whenever there is content too long for space.

**Comment by cillianhunter0** [comment]
Figma: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7181%3A15

Rules: 
- Displays at the centre point of the truncated name
- Min width 248px
- Max width 320px 
- Responsive height

**Comment by cillianhunter0** [comment]
Tooltip isn't working for me. Have tried outcome strings on: 
- trading page
- portfolio page
- account summary page

when i hover over the string nothing appears. 

![tooltip.gif](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/615aade4-528f-4431-b05a-724e72cf2d87)

**Comment by cillianhunter0** [comment]
Tooltip still isn't working for me. Tried on portfolio > open orders and on the trading page

**Comment by Chwy5** [comment]
works now - closing

**Comment by cillianhunter0** [comment]
Still not working for me
