### ISSUE TITLE
My Created Markets sort order

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1397]
My created markets - all filter - set 'sort by expiring soonest' as the default 

sort by endTime that is coming soonest. The markets that have already ended will be at the bottom.

**Comment by phoebemirman** [comment]
should this be the same for all tables with an end time sort? or just my created markets?

**Comment by bthaile** [comment]
It was only discussed for my created markets. I suggest just putting it there for now.

**Comment by Chwy5** [comment]
Cool this is fixed, much better this way imo - closing ticket
