### ISSUE TITLE
Scale candlestick chart 

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1403]
Scale candlestick chart to be 10% greater and less than price avg

![3-19ochl.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/1741752f-8703-42df-b76b-785c0892857e)

**Comment by Chwy5** [comment]
Show market range...currently not showing bottom line number  so categorical are not showing 0.000

If we have enough room to add a 3rd line, show middle value of market range

**Comment by bthaile** [comment]
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/a7a8cd14-84c8-43a1-ba8b-e88562679e32)

**Comment by Chwy5** [comment]
scale is showing better -closing
