### ISSUE TITLE
crash after typing really small numbers in order form

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1404]
typed .00000000...1 in both fields then crash
also maybe switched buy/sell tabs
<img width="727" alt="Screen Shot 2019-03-19 at 7 29 29 PM" src="https://user-images.githubusercontent.com/6775839/54655166-162ea080-4a7e-11e9-95c3-2cc36b535dbe.png">

**Comment by Chwy5** [comment]
Just got this again...slightly different message but putting in really long decimals triggered it

![3-21bignumb.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/425e9ee5-4957-498a-818a-da83a9c8aab6)

**Comment by Chwy5** [comment]
fixed - closing
