### ISSUE TITLE
Send funds modal 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1405]
Figma: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7110%3A254322

Notes: 
- Mobile and desktop designs are on the same page, on the link above 👆
- Currency chosen will update the 'available' funds shown below 
- Amount entered will update the 'overview' of the transaction below
- If user taps 'max', input the max available funds in the 'amount' input
 - In the overview, 'send' will display the max amount
 - 'Gas cost' will be caluclated and displayed
 - 'Total' = [send] - [gas cost] 
- Validation errors for 'invalid address' and 'insufficient funds'

**Comment by cillianhunter0** [comment]
Issues: 
- If I enter number into "amount" e.g. "200", I cannot delete the first digit of the number, so I'll be stuck with "2" in this example. 
- When using "max" amount, it always tells me i have insufficient funds, the idea here was to subtract the gas cost the users 'max', and show the 'total' that the user could send, i.e. so they don't get an error if they use the feature, they can send 'max', we subtract the gas cost for them. 
- First letter of copy in the two buttons is not a capital letter, should read "Send" etc

**Comment by Chwy5** [comment]
only styling is left - moving that to 1.14

**Comment by JohnDanz** [comment]
What still needs to be done for this ticket? @Chwy5 @matt-bullock

**Comment by cillianhunter0** [comment]
Most of this is done, some styling issues remain, have created a ticket specific for them: #1949
