### ISSUE TITLE
Max Profit/Loss values are zeros

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1408]
![Screen Shot 2019-03-20 at 3 54 57 PM](https://user-images.githubusercontent.com/3970376/54718455-8db90a00-4b28-11e9-9e85-ba4ef99e4178.png)

What do you want to display for Max profit and Loss?

we have plenty of room to show 9 decimal places
we could use the numeric tooltip

**Comment by Chwy5** [comment]
WE can either show up to 9 decimals or do something like this:
Max Profit ................  0.000.. Eth
Max Loss ..................  0.9999 Eth

**Comment by bthaile** [comment]
Lets show upto 8 decimals since we have room. Also with the quantity. I made these changes already because there was scentific notation showing. You can test that tix and see what you think. We can also use the ellipse if we want to go that direction. It would add some complexity because of all the variations we have, like coloring red if max profit is negative.

**Comment by Chwy5** [comment]
Just confirming we would only show up to 8 decimal if it was a tiny number with many zeros in the decimal....like 0.00000007

If not we display 4 decimals

**Comment by bthaile** [comment]
True, is that the behavior you are currently seeing on sneakpreview? 

I made the changes witht the scenific notation issue.

**Comment by Chwy5** [comment]
Yes...currently shows 4 for everything unless its a tiny number with many zeros in front then it shows up to 8......Which is what I want it to do

This looks to be working correctly so I am closing
