### ISSUE TITLE
not enough space in outcome dropdown

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1410]
![image](https://user-images.githubusercontent.com/3970376/54718567-c822a700-4b28-11e9-9613-577d22bdf9d5.png)

Need to fix the width of the outcome dropdown so that the arrows don't overflow outside of the input. 

need to include the arrows when centering the content.

**Comment by andrewdamelio** [comment]
I could not reproduce this. 
<img width="343" alt="Screen Shot 2019-03-21 at 4 39 42 PM" src="https://user-images.githubusercontent.com/1683736/54785166-e5747580-4bfb-11e9-8382-133f7a32cf17.png">

@bthaile would it be possible to retest and let me know if you still see an issue?

**Comment by bthaile** [comment]
Since you are running same res as chwy, lets close this.
