### ISSUE TITLE
React warning about highchart usage

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1414]
![image](https://user-images.githubusercontent.com/3970376/54752779-42950a80-4bad-11e9-8d5e-6b3d9d17e44c.png)

Fix warning, not sure the exactly the scenario it occurs.

**Comment by Chwy5** [comment]
I believe this message came up when trying to go to the Acct Summary pg from the markets pg

**Comment by Chwy5** [comment]
havent been able to reproduce....closing
