### ISSUE TITLE
Candlestick Chart changes

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1415]
Design has made tweaks to charts. 

move ETH label to top to reduce redundancy

![image](https://user-images.githubusercontent.com/3970376/54753753-cd770480-4baf-11e9-90fd-4926fd2872fb.png)

**Comment by Chwy5** [comment]
@matt-bullock plz rvw and close if complete

**Comment by matt-bullock** [comment]
Label is in but needs correct type size and spacing. Closing for now as this can be addressed in ticket 1602
