### ISSUE TITLE
Categorical Market Price history chart changes

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1416]
Move ETH label
change date time and price crosshair label color to match line color

![image](https://user-images.githubusercontent.com/3970376/54786536-1e5e1b80-4bf7-11e9-9951-ff2b441688a4.png)

**Comment by Chwy5** [comment]
approved - moving to ui incoming

**Comment by bthaile** [comment]
@Chwy5 how about moving this to 1.14?

**Comment by Chwy5** [comment]
Yeah - not priority for 1.13...moved to 1.14
