### ISSUE TITLE
Market creation time and market end time should be shown in UTC

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1417]
Market created and market expires should show UTC not local time.

![image](https://user-images.githubusercontent.com/3970376/54759481-2cdb1180-4bbc-11e9-9f64-bc367af86e6f.png)

direction from design
![image](https://user-images.githubusercontent.com/3970376/54760572-55fca180-4bbe-11e9-9efb-be2f271db2a7.png)

**Comment by bthaile** [comment]
Need to get feedback from @Chwy5 @matt-bullock @cillianhunter0 
to make sure design and product are on board.

**Comment by Chwy5** [comment]
Yes I think we should do that for now....everything set to UTC....Down the road when we add user preferences will give user ability to show all dates in local time

**Comment by cillianhunter0** [comment]
Yep agree

**Comment by pgebheim** [comment]
@bthaile -- Will this be affected by the newest changes?

**Comment by bthaile** [comment]
Nope, we’ll show UTC and the new timezone stuff we are adding both in specific locations like market trading market info and in market creation.

**Comment by pgebheim** [comment]
@bthaile -- Putting together a release for these timezone improvements. Re-read this, and confirming that this isn't a part of those changes but will be just related to the redesign.

Yes?

If so, perhaps we remove Blocked from this?

**Comment by Chwy5** [comment]
will be addressed w/ timezone changes-closing
