### ISSUE TITLE
profit and loss chart data looks incorrect.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1418]
![image](https://user-images.githubusercontent.com/3970376/54765384-66fde080-4bc7-11e9-87bc-b61286423984.png)

message from chwy

"This acct shows all time Pnl form nov 20th to now....I should have many peaks and valleys in it, as some days I added to my Pnl total and others my total decreased"

**Comment by Chwy5** [comment]
Data looks to be displaying correctly - closing

**Comment by Chwy5** [comment]
Found  a chart that doesnt look correct   see attached screenshot....have -Pnl of 12.6472...it doesnt start at the zero line and go down...just goes straight across....looks like to me that i started with a negative balance and just maintained it...this chart is being viewed on All-time

![4-11pnl.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/e757c7d4-3af7-493f-b01a-5af1698a8683)

**Comment by Chwy5** [comment]
we need to start All - time PnL at 0

**Comment by Chwy5** [comment]
closing...we have individual tickets for styling tweaks
