### ISSUE TITLE
Labels are uppercase

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1419]
format for Label ....... value has changed, now LABEL is all caps. Same font size and color, from what I can see in the mocks.

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/bec9a156-e1eb-4208-93da-183e38a0b924)

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/4a079685-4b38-449d-9da3-94ec92404880)

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/811b67ad-f6c8-4d91-ae6d-2f6b9ba73da7)

![image](https://user-images.githubusercontent.com/3970376/54775034-12fcf700-4bdb-11e9-9f7e-be023390564f.png)

also trading type filled order type labels are also uppercased

**Comment by matt-bullock** [comment]
let's review this when it's updated across the app.

**Comment by bthaile** [comment]
Using this tix as a dev review for all labels

**Comment by phoebemirman** [comment]
all the stuffs in the screenshots are uppercase

**Comment by cillianhunter0** [comment]
@phoebemirman spotted two labels on the account summary, the 'blocks behind' and 'blocks processed': 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/6149b6b1-94b8-4370-8f71-cd30e91f95af)

The rest of portfolio and account summary look good. 

@matt-bullock can you check the same for trading page?

**Comment by pgebheim** [comment]
@matt-bullock @cillianhunter0 -- Commenting as to what we should do here?

Gonna move it to next sprint with the goal of getting it sorted Monday.

**Comment by cillianhunter0** [comment]
We have an issue in that specifies a consistent approach: 
https://app.zenhub.com/workspaces/augur-5bfed3424b5806bc2bf8d173/issues/augurproject/augur/1573

**Comment by andrewdamelio** [comment]
closing - I checked and this work appears to be done.
