### ISSUE TITLE
UI doesn't load on Safari

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#142]
See Title.  Sits at the screen w/ Augur logo on Safari 8.0.7
works on Safari 8.1

**Comment by marksmeets** [comment]
Same problem here, but no matter what browser I use. Tried firefox and chrome. This is on an ubuntu system.

I started the server according to instructions with
geth --datadir "~/gethTest" --rpc --rpccorsdomain "http://client.augur.net http://localhost:8080" --rpcapi "db,eth,net,web3" --shh --networkid "007" --port "30303" --genesis genesis_block.json --autodag --mine --minerthreads "1" --unlock "0" console

(yes, created a datadir 'gethTest')
In the terminal I see that it has generated "DAG", then pops up messages about "commit new work on block.." and "Mined block ...". 

but the website keeps saying 'loading'...

**Comment by scottzer0** [comment]
mark,  if you use the legacy "proceed in demo mode", does the UI load?

i just want to separate the browser claim here with the UI not handling you local geth node's state gracefully (which I'm guessing is the case).  the UI has gone through iterations to handle various failures, but it's by no means as robust as i'd like it.

also, if your geth instance isn't actually downloading groups of blocks and "catching up"  then you might have to wait longer or just nuke from orbit.

**Comment by tinybike** [comment]
@marksmeets just realized I forgot to add our bootnodes to the instructions on docs.augur.net!  Try adding this flag to your geth command:
```
--bootnodes "enode://70eb80f63946c2b3f65e68311b4419a80c78271c099a7d1f3d8df8cdd8e374934c795d8bc9f204dda21eb9a318d30197ba7593494eb27ceb52663c8339e9cb70@[::]:30303,enode://405e781c84b570f02cb2e4ebb18c60528aba5a08ccd72d4ebd7aeabc09208ef24fa54e20ff3b10e478c203dd481f3820242e51fe72770a207a798eadfe8e7e6e@[::]:30303,enode://d4f4e7fd3954718562544dbf322c0c84d2c87f154dd66a39ea0787a6f74930c42f5d13ba2cfef481b66a6f002bc3915f94964f67251524696a448ba40d1e2b12@[::]:30303,enode://8f3c33294774dc266446e9c8483fa1a21a49b157d2066717fd52e76d00fb4ed771ad215631f9306db2e5a711884fe436bc0ca082684067836b3b54730a6c3995@[::]:30303,enode://4f23a991ea8739bcc5ab52625407fcfddb03ac31a36141184cf9072ff8bf399954bb94ec47e1f653a0b0fea8d88a67fa3147dbe5c56067f39e0bd5125ae0d1f1@[::]:30303,enode://bafc7bbaebf6452dcbf9522a2af30f586b38c72c84922616eacad686ab6aaed2b50f808b3f91dba6a546474fe96b5bff97d51c9b062b4a2e8bc9339d9bb8e186@[::]:30303"
```
(These are needed -- temporarily -- because we're on a private chain.)

**Comment by scottzer0** [comment]
also, @joeykrug,  if it works on 8.1, i say good riddance safari 8.0.7.  i hardly knew ye...

**Comment by scottzer0** [comment]
i cringe at our current private chain install instructions.  i would just use a big font and say, "use our hosted solution and play with your kids more!"

**Comment by tinybike** [comment]
>i cringe at our current private chain install instructions. i would just use a big font and say, "use our hosted solution and play with your kids more!"

While I can't bring myself to disagree with this, since we've got run-your-own-geth instructions on docs.augur.net anyway, I'm gonna update them to at least be correct!

**Comment by marksmeets** [comment]
Hi guys,

yes, demo mode works. Also, adding --bootnodes definetly does something. I can now proceed past the 'loading' screen, but am left with an empty, green screen. 

This is my script:
mark@fasterix:~/augur$ cat augur.sh 
geth --datadir "~/gethTest" --rpc \
	--rpccorsdomain "http://client.augur.net http://localhost:8080" \
	--rpcapi "db,eth,net,web3" --shh --networkid "007" --port "30303" \
	--mine --minerthreads "1" \
        --autodag \
	--unlock "0" \
	--bootnodes "enode://70eb80f63946c2b3f65e68311b4419a80c78271c099a7d1f3d8df8cdd8e374934c795d8bc9f204dda21eb9a318d30197ba7593494eb27ceb52663c8339e9cb70@[::]:30303,enode://405e781c84b570f02cb2e4ebb18c60528aba5a08ccd72d4ebd7aeabc09208ef24fa54e20ff3b10e478c203dd481f3820242e51fe72770a207a798eadfe8e7e6e@[::]:30303,enode://d4f4e7fd3954718562544dbf322c0c84d2c87f154dd66a39ea0787a6f74930c42f5d13ba2cfef481b66a6f002bc3915f94964f67251524696a448ba40d1e2b12@[::]:30303,enode://8f3c33294774dc266446e9c8483fa1a21a49b157d2066717fd52e76d00fb4ed771ad215631f9306db2e5a711884fe436bc0ca082684067836b3b54730a6c3995@[::]:30303,enode://4f23a991ea8739bcc5ab52625407fcfddb03ac31a36141184cf9072ff8bf399954bb94ec47e1f653a0b0fea8d88a67fa3147dbe5c56067f39e0bd5125ae0d1f1@[::]:30303,enode://bafc7bbaebf6452dcbf9522a2af30f586b38c72c84922616eacad686ab6aaed2b50f808b3f91dba6a546474fe96b5bff97d51c9b062b4a2e8bc9339d9bb8e186@[::]:30303" \
	console

(I've removed --genesis , I think that would overwrite my current data and mining efforts)

After entering the password (for which I'm only prompted after I press return in the console btw) I add the 4 peers in the instructions. Then the screen in the browser goes green.

After reloading the web page I'm stuck at 'loading' again though...
Hmm. After restarting the script I'm back to 'loading' for good

Thanks for the response so far.

**Comment by marksmeets** [comment]
Tried again, but now 'proceed in demo mode' gets stuck at loading as well. Both on chrome and firefox.

Also tried on a clean computer (never ran geth there). Here I can't get the demo mode up as well. This is on an ubuntu 15.04 with chromium.

**Comment by scottzer0** [comment]
i can't find this version of safari and given the weak circumstances of this bug, closing
