### ISSUE TITLE
uppercase table headers

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1425]
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/acb7ea8f-5d77-4460-a948-fce26d40378f)

look at design to get all the places where table headers are uppercased and match the color.

**Comment by phoebemirman** [comment]
@matt-bullock are the headers for the portfolio and trading page supposed to have different colors? i saw the mock has it that way. seems inconsistent.

**Comment by matt-bullock** [comment]
@phoebemirman They should be the same. I've updated across the design. Only difference between mobile and desktop is font size

MOBILE:
font-family: Roboto Mono;
font-style: normal;
font-weight: normal;
font-size: 9px;
line-height: normal;
text-transform: uppercase;

color: #76737E;

DESKTOP:
font-family: Roboto Mono;
font-style: normal;
font-weight: normal;
font-size: 10px;
line-height: normal;
text-align: right;
text-transform: uppercase;

color: #76737E;

**Comment by Chwy5** [comment]
@matt-bullock please review this looks correct....

Is All, Open, In Reporting, Resolved in Positions and My Created markets supposed to have all caps as well?
