### ISSUE TITLE
Mobile version console errors

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1428]
When shrinking my desktop display down to mobile size i got these errors in my console.  When clicking around i continued to get them

![3-21unc.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/8896a390-4803-4462-8071-bc6f60b36480)

**Comment by Chwy5** [comment]
When trying to expand back out to full screen version for desktop....the view stays as mobile just stretched out to full screen size (doesnt revert back)

**Comment by bthaile** [comment]
@JohnDanz can you give this a look, I'd like to make sure it's not breaking anything. And see if you can fix to clean up web console.

**Comment by JohnDanz** [comment]
I'll take a look first thing in the morning

**Comment by JohnDanz** [comment]
I was unable to reproduce this error however I did notice some pretty significant hang on resize. I think we need to take a look at fixing the lag to redraw/adjust to a window resize -- i suspect we are doing to much on a resize event or we aren't properly cleaning up those event handlers. 

see this https://github.com/AugurProject/augur/issues/1392

**Comment by bthaile** [comment]
@Chwy5 verify you no longer get these errors.

**Comment by Chwy5** [comment]
not seeing them - closing for now
