### ISSUE TITLE
Re-add old PL code for deriving a cost basis for shares owned in a synthetic short

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#1431]
From Alex on Discord:

"essentially we'll need to recreate the data that was in the moneySpent column there
and for any sale transaction the cost basis will be amount of position sold * moneySpent / amount owned before trade
using actual on chain owned shares.. hm so we'll need that data too
oh we should have that though, just their share balance
for the issue btw its not just specific to synthetic shorts but its mostly relevant for them since I think if all we had was longs things would just work
I'm wondering about my previous comment too about the share balances being available. This is for historical data so I dont think it is
so we'll need the numOwned data from the old PL to come back as well
actually I think we may still calc that one sec
nah we dont store historical amounts. We'll need that as well
cost basis for longs that are selling synthetic shorts is gonna be fun
just a sum of the cost basis for each outcome"

**Comment by Chwy5** [comment]
@adrake33 is this for the transaction pg

**Comment by adrake33** [comment]
@Chwy5 Yeah, I believe this was referring to the cost basis on the tx page. Since we removed that from v1, this would need to be done for v2.

**Comment by pgebheim** [comment]
@nuevoalex -- This looks to be a ticket related to what we were talking about last week re: netPosition and actual position.

I can't recall if that still needs to happen,

**Comment by nuevoalex** [comment]
I vaguely recall this not being an issue in V2 though I think I'd need the context of the actual feature desire again

**Comment by pgebheim** [comment]
I have a feeling we don't actually want to do this and we really just want to simplify the data export so that its easily importable by any of the crypto tax packages.

Meaning, we just export raw values and don't try to continually calculate the basis in terms of the export.

**Comment by pgebheim** [comment]
Closing as irrelevent in V2
