### ISSUE TITLE
Simplify Ledger login

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1434]
After discussion in #Issues channel:

1. Add new ledger live default address to derivation path array that we scan and iterate on. Derivation path:
`m/44'/60'/x'/0/0`

Will need to change up derivation path iterator, it currently increments on last character. 

2. In advanced option only show the single address that corresponds to the user inputted derivation path. Dont need to iterator through many paths.

**Comment by pgebheim** [comment]
All this worked is tracked in #3997 / hardware wallets.
