### ISSUE TITLE
Account summary page is not loading on sneak build 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1436]
I'm seeing this error when I open the page: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/432c42b6-9ce6-4248-9aea-20e0797f2d5b)

Account summary URL is loading as: 
https://sneakpreview.augur.net/#!/deposit-funds

Console errors:
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/5b19d07a-02ee-4538-8bc2-bcf068ade3ea)
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/cf89d5ef-51f1-48fc-8f53-f284d532232d)

**Comment by bthaile** [comment]
Update made and pushed to sneakpreview.

**Comment by Chwy5** [comment]
Fixed-closing
