### ISSUE TITLE
claim proceeds: Need to disable button when tx is sent

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1437]
![Screen Shot 2019-03-22 at 7 26 58 AM](https://user-images.githubusercontent.com/3970376/54822849-eb0da200-4c73-11e9-84ac-bbdce16d33b8.png)

If the user chooses to claim one by one, the `claim proceeds` button needs to disabled so the user doesn't accidently click on the button again.

This needs to be the approach for all modals where the modal can stay visible after a click to send tx.

**Comment by Chwy5** [comment]
this is updated closing ticket
