### ISSUE TITLE
Order Ticket empty state placeholder numbers need to be adjusted

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1438]
Order ticket has gray numbers for place holders when the order ticket is empty. In its current form it is confusing and looks like there might be an order in the ticket already: 
2 Changes we need to do:
1) Lighten up the Gray placeholder numbers 
2) We should display: (Quantity and Limit Price to 2 decimal places and Total Order Value to 8 dec places)

Quantity:
0.00
Limit Price
0.00 
Total Order Value
0.00000000

**Comment by bthaile** [comment]
after discussion we are going with "0.00" for Total Order Value as well.

**Comment by Chwy5** [comment]
yup confirmed

**Comment by Chwy5** [comment]
looks good - closing
