### ISSUE TITLE
Mobile: market trading page "Open Orders"

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1440]
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/106a3d31-43c2-4a65-a630-83c4ca9d96c2)

Look at the `Orders` section in the `Trading Page - Mobile` tab.

**Comment by cillianhunter0** [comment]
Ignore this comment. 

~~Has open orders been updated in the build?~~ 

~~I'm still seeing the old version, where cancel is in the row rather than revealed when the row is expanded.~~

**Comment by bthaile** [comment]
This issue is for market trading open orders. 

If you are pointing out something for portfolio open orders, that is a different thing.

**Comment by bthaile** [comment]
@phoebemirman There are some changes needed for market trading page. look at design

**Comment by phoebemirman** [comment]
which are the changes? the rows look the same to me.

**Comment by phoebemirman** [comment]
the pr for this hasn't been merged yet. 

https://github.com/AugurProject/augur-ui/pull/2815

**Comment by matt-bullock** [comment]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/3c891dcc-ae0a-489a-b9ad-721168dd2d19)

Top is design, bottom is dev. Can you do do a quick scan through to check type size, colour and spacing with design. 

We're using the off-white for most whites other than the market title. 

The arrow should be the grey for default state

Total cost(ETH) etc lables should be 10pt Mono #76737E.

Check top and bottom spacing around cancel button.

Type, Quantity, Price needs to line up with their column content. Left align  for Type, Right align for all others.

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/2b17965e-31ad-470e-935e-1f28bc7f8cfa)
Corner notches shouldn't be visible here.

The expand and close transitions could be smoother and snappier. this applies across the whole product. Speeding the transitions up would help.

**Comment by Chwy5** [comment]
@matt-bullock please review latest changes

**Comment by matt-bullock** [comment]
Can you make the market title medium weight (500) then we should be good

**Comment by Chwy5** [comment]
@matt-bullock confirm this has been fixed and then close
