### ISSUE TITLE
New styling for Bell item indicator

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1441]
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/4150e02c-bbd5-472b-a81e-411b0b77ba7c)

new Bell item indicator

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/f70329d3-3f96-451e-aa79-69f20dc03cdf)

**Comment by Chwy5** [comment]
Approved

**Comment by bthaile** [comment]
this is a dup of https://github.com/AugurProject/augur/issues/1463
closing
