### ISSUE TITLE
user can't clear Amount in withdraw modal 

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1443]
accidently created this in augur-ui, creating here.

Input doesn't allow the user to backspace value from modal.

to repro,

type in 1 in Amount then backspace, the 1 doesn't get removed.

![image](https://user-images.githubusercontent.com/3970376/54849978-cdf8c380-4cb3-11e9-8d03-8f6fb98f18a5.png)

**Comment by cillianhunter0** [comment]
This is still not working.

**Comment by Chwy5** [comment]
fixed - closing
