### ISSUE TITLE
withdraw modal allows user to put in negative amount

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1445]
User sends MAX ETH, and is left with dust because we estimate gas fee, so there can be dust left.

Second time user transfers ETH and clicks MAX a negative value shows in Amount and Send tooltip displays same negative balance.

Need to say error message of Not enough ETH available to pya gas cost. message if available balance is less than estimated gas cost.
![image](https://user-images.githubusercontent.com/3970376/54850090-26c85c00-4cb4-11e9-9f24-4f7f0f01a50c.png)

**Comment by cillianhunter0** [comment]
@bthaile how about: 

- user taps max (with dust amount)
- amount appears in the 'amount' input
- validation error shows not enough eth to cover gas 
- total number is highlighted as red when negative 
- send button is disabled 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/53f1216b-a306-4b68-8133-461f18296f27)

**Comment by Chwy5** [comment]
fixed - closing
