### ISSUE TITLE
Add more logs to Augur contracts

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#1446]
Some of the logs we will want to add include:
* ~~Fees when claiming trading proceeds~~
* ~~Fees when selling a complete set~~
* ~~Start & end dates for market creation events (needed for full-text search)~~
* ~~Forking market to `UniverseForked`~~
* ~~price to `OrderFilled`~~
* ~~Event logging for when a market has begun normal dispute pacing (possibly as a new param in DisputeCrowdsourcerCompleted)~~
* No-show bond amount
* Market info: ~~finalizationTime~~, ~~consensus~~, ~~endTime~~, ~~numTicks~~: https://gist.github.com/adrake33/c4b671181a1b4fb350b5dc6f18d11570
* Market price history (should use finalization payout amount): https://gist.github.com/adrake33/f7e71594182020a585ccf71306b83e31
* Market outcome price change (payout for that outcome should be used): https://gist.github.com/adrake33/d192651a004684cfcd8d347bc5a9bff6
* Market creator has unclaimed fees & market creator claimed fees: https://gist.github.com/adrake33/10c16da8ac291ef392cc6844a741b888

And more to come

**Comment by joeykrug** [comment]
@nuevoalex status?

**Comment by nuevoalex** [comment]
Closing this in favor of just using new issues to handle any additional logs we may need.
