### ISSUE TITLE
Need design for cancel orphan orders notification

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1447]
Need a notification for user when they have orphan orders.

Currently there is only one place the user is informed they have orphan orders, that is the market trading page in Open Orders section.

The order is filtered out of the portfolio Open Orders quad. A notification would be beneficial to prompt the user to free up their locked up capitol.

prob need to add a modal as well, it will prob be same as cancel open orders when market is finalized modal.

moved this over from augur-ui repo, I created it there by mistake.

**Comment by bthaile** [comment]
old augur-ui tix, https://github.com/AugurProject/augur-ui/issues/2789

@Chwy5 you said in the old tix for @matt-bullock to look at this after mobile is done

**Comment by Chwy5** [comment]
@matt-bullock Once mobile design is complete we need a design for this

**Comment by Chwy5** [comment]
design is created - closing
