### ISSUE TITLE
Need design for Claim Stake and Fees notification modal

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1451]
associated notification

![image](https://user-images.githubusercontent.com/3970376/54851572-6b55f680-4cb8-11e9-9cc7-d76c3604d813.png)

This modal is for:

1. all the disputes the user has won.
2. redeeming participation tokens
3. redeeming any initial reporting through open reporting.

**Comment by Chwy5** [comment]
@matt-bullock High priority after finishing mobile

**Comment by Chwy5** [comment]
Design is created and added to ticket 1485 - closing this
