### ISSUE TITLE
In Reporting component

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1453]
We need a new atomic component for showing more detail for in-reporting.

designated reporter state.
![image](https://user-images.githubusercontent.com/3970376/54936569-b8241200-4ef0-11e9-85d8-d99d333e3503.png)

![image](https://user-images.githubusercontent.com/3970376/54851785-08189400-4cb9-11e9-8af5-fd769cc21050.png)

![image](https://user-images.githubusercontent.com/3970376/54851789-0e0e7500-4cb9-11e9-8f4a-b7c0a23ee5ca.png)

![image](https://user-images.githubusercontent.com/3970376/54851801-149cec80-4cb9-11e9-8f4a-0186c7f373c4.png)

**Comment by cillianhunter0** [comment]
One of the in-reporting tag states is called "waiting on reporter", the idea was to display that when the market is in the state "designated reporter", as a more understandable  term, thoughts?

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/95171911-93e6-4f24-8424-1a7fe5b7c164)

**Comment by bthaile** [comment]
Using this tix for development
