### ISSUE TITLE
Mobile - Account summary - notifications view 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1460]
Figma:  
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7187%3A250630

*NB* review with Cillian before building. 

Notes: 
- Notifications are accessed using the tabs at the top of the page
- IF there are new notifications, show red dot (beside tab link). IF there are no new notifications, hide red dot
- Tapping a notification opens a modal (a separate ticket will be created for these) 
   - Except for reporting/disputing notifications, which will link directly to the relevant page for the moment

**Comment by cillianhunter0** [comment]
@andrewdamelio is there any dev wallet we use that will allow me to see all the notifs?

**Comment by andrewdamelio** [comment]
@cillianhunter0 i'll msg you some accounts on discord
