### ISSUE TITLE
Order book - padding and alignment 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1461]
Change to the alignment of the price column label and data, change from center, to right aligned to keep things consistent. 

Order book spacing between column data should be even. 
E.g. on desktop: 
48px spacing between each column factors in 8 digits and one decimal point for each column 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/b03e58b4-8c73-431e-a41a-4a9b58e6a59a)

**Comment by phoebemirman** [comment]
@cillianhunter0 is there a mock in figma for this?

**Comment by phoebemirman** [comment]
@cillianhunter0 said to close this
