### ISSUE TITLE
Notification bubble - color change 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1463]
Applies to desktop and mobile. 

The notification 'bubble' that appears in the header when user receives a new notification. Change of colour to: #FD6266

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/d600f7f6-5006-4499-b0eb-277ad393dc06)

**Comment by bthaile** [comment]
dup of https://github.com/AugurProject/augur/issues/1495

**Comment by Chwy5** [comment]
changed- closed
