### ISSUE TITLE
Orphan order format is inconsistent.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1464]
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/d2c54542-26b7-4ca6-8265-c884d92ee74b)

Orphan Order row, Needs correct cancel button style.  Also price isn't aligning up correctly.

**Comment by phoebemirman** [comment]
this is a dupe https://github.com/AugurProject/augur/issues/1388
