### ISSUE TITLE
style updates to market trading page mobile tables

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1466]
![Screen Shot 2019-03-25 at 10.41.25 AM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/f6f66660-aa48-4c88-8ad8-a1cd64289677)

**Comment by Chwy5** [comment]
@matt-bullock please review

**Comment by matt-bullock** [comment]
More of a global update but all text items in the tabs should be 14px not 16px - Open Order, My FIlls, Positions etc
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/aea11cb1-4056-4c15-9323-f3efc1c00a7b)

Arrows are #999999 for default state, white for hover
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/ae0b6dc8-7365-44a2-a52c-9a3625096ce6)

Numbers are 10px and #CED7D8. BUY, SELL remains 11px and green/red
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/9afe89e4-c923-435a-938d-8a583a805820)

Market should be medium weight. Looks bold currently
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/7cd53c08-985c-4b21-a06f-bc4ea1584fb9)

Visible indent on border should be removed when expanded
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/00193812-632a-4a55-aaa4-47cff0a6f2af)

Should be mono 10px, #76737E
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/47641642-b9d0-4a68-91eb-47904fac1ffc)

Should be 10px, #CED7D8
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/626ae1d0-e208-491e-a6ec-d6987ac7a5b0)

Vertical spacing should be 16px top and bottom
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/5ae687a3-34d0-40b9-bf75-bbd1af65b0da)

**Comment by matt-bullock** [comment]
My fills looks like an older design

**Comment by phoebemirman** [comment]
most of that was addressed here: https://github.com/AugurProject/augur/issues/1440

this ticket is just for the size of open orders table. there isn't a ticket for filled orders yet that i'm aware.
