### ISSUE TITLE
Create webworker that can call Augur API (to make use of augur.js/augur node)

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#1469]

**Comment by pgebheim** [comment]
@brianosaurus -- anything 8 points or higher should be broken up into an epic.

Also, what's the idea of this? Why would we need Augur.js to be called from a web worker?

The idea Alex and I discussed in the channel was to make an interface library that sits on the UI side and can call the augur-state API, and potentially also call Augur.js during the transition.

The web worker would be on the other side of a boundary.

Correct me if I'm wrong of course, but if I am can you describe this task on the ticket?

**Comment by brianosaurus** [comment]
Agreed this should be broken up into an epic @pgebheim 

The tasks would be:

1. Ge augur state running in the browser
1. Move augur state into a web worker, shared worker, or service worker with reference counting. Requires a little research.
1. Build a mechanism to route requests to the worker that also enables standalone node.js operation with WS and JSON-RPC endpoints.
