### ISSUE TITLE
Assist User in Zero or Low Balance of Cash and Ether

### ISSUE THREAD

**Issue by pqdeep** [AugurProject/augur#147]
"Submit a Market" form could use some text prompt, above the liquidity field or something, telling people their balance is empty. Otherwise, there's no indication for the uninitiated (besides the empty balance) of why a market submission isn't getting through.

**Comment by scottzer0** [comment]
Yes, this is actually related to the larger issue of UX patterns and actions that require resources you don't have and how to handle this.  

While I could start pasting more words around explaining stuff. I'm aiming for something less noisy, more intuitive and higher order.  Such as not allowing the action in the first place or an initial hand-holding for users with no cash or ether.

As I need to track this, going to hijack this issue and change it's title.  Thanks Perry.

**Comment by pqdeep** [comment]
Just catching up - very cool. I hadn't reviewed the demo since before the individual accounts were introduced so I've really picked up on all the big and subtle changes. Everything - features, loading time, responsiveness, overall flow, etc. -- everything is much, much better. This is a big help for future demo presentations. Many, many thanks, Scott.

**Comment by tinybike** [comment]
Rolling this into #277.
