### ISSUE TITLE
Claim Available Stake And Reporting Fees bug

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#1470]
I was able to click on View for Claim Available Stake And Reporting Fees more than once.

- also check all the other notifications for correct behavior

**Comment by Chwy5** [comment]
So this is the error a user gets when they claim on an individual market and while it i processing they hit claim all....simplest solution is to gray out all additional claim buttons...individual and claim all, until the first transaction confirms

![4-17errormodals.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/72e02acb-8c6d-4548-94c6-16e07b1b315d)

**Comment by Chwy5** [comment]
simplest solution is to gray out all additional claim buttons...individual and claim all, until the first transaction confirms

But I am not sure if these txs are done individually where they shouldnt be effected

**Comment by andrewdamelio** [comment]
@Chwy5 
This addresses the issue with the modal/notifications for Claim Proceeds and Claim Reporting Stake/Fees.

To reproduce:
1) Open either modal via notification
2) Click the CLAIM ALL button
3) Don't accept the TX, close the modal
4) You shouldn't be able to reopen the modal until you cancel the 'claim all' TX

**Comment by Chwy5** [comment]
looks good closing
