### ISSUE TITLE
mobile, market info trading page

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1477]
Market Info part of mobile trading page.

![Screen Shot 2019-03-26 at 10 00 34 AM](https://user-images.githubusercontent.com/3970376/55008853-a48bb080-4faf-11e9-8a38-f2169a1ec1a6.png)

1. move market type label up
2. restyle all hint svg (this new style should be default for UI)
3. remove `Add to watchlist` 
4. DON'T add new 3 vertical dots (design hasn't finished the full behavior)
5. add new In-reporting with reporting state styling

~~I'll get more information on the 3 vertical dots pop up thing.~~ not adding 3 vert dots.

**Comment by Chwy5** [comment]
@matt-bullock please rvw

**Comment by matt-bullock** [comment]
Circled updates look good. The (i) icon can go down to 12px in size.

Rest of that page is still awaiting update

**Comment by andrewdamelio** [comment]
@matt-bullock FYI this has been updated, please review once it gets pushed to sneakpeak.

**Comment by matt-bullock** [comment]
icon looks good. closing this now
