### ISSUE TITLE
new core stats header

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1478]
The core stats balances will use 3 of the same balances as account summary. so you can get them from the same place. The different value `Realized P/L` is for `All Time` and doesn't change with user selecting Time Range in account summary. We don't want to call a different endpoint to get all time realized p/l, it should be added on to user positions, since we are calling that endpoint frequently
augur-node task for that: 

example of the three values

![Screen Shot 2019-03-26 at 10 16 31 AM](https://user-images.githubusercontent.com/3970376/55009989-727b4e00-4fb1-11e9-86f2-3bc4ee07dfe8.png)

new look for mobile
![Screen Shot 2019-03-26 at 10 13 20 AM](https://user-images.githubusercontent.com/3970376/55009022-e61c5b80-4faf-11e9-8369-de0a80945979.png)

desktop design
![Screen Shot 2019-03-26 at 11 07 38 AM](https://user-images.githubusercontent.com/3970376/55013578-61cdd680-4fb7-11e9-8700-0db71c735e17.png)

notice the red circle on the bell, task for that:  https://github.com/AugurProject/augur/issues/1441

For the time being use `src/modules/positions/actions/update-top-bar-pl.js` instead of calling `getProfitLossSummary` call `getProfitLoss` and pass in startTime: null and endTime: null and grab the last item in the array. set it to new property on login account.

**Comment by phoebemirman** [comment]
@matt-bullock what would the mobile side bar look like now that p/l is in the top bar?

![Screen Shot 2019-03-26 at 1.53.58 PM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/29cf6915-599f-4830-ba87-e2165bc4a397)

**Comment by bthaile** [comment]
Are we getting rid of the 1 and 30 day P/L

**Comment by Chwy5** [comment]
yes...can be seen in the AS pg

**Comment by Chwy5** [comment]
Closing ticket
