### ISSUE TITLE
Remove startup violations

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1479]
![Screen Shot 2019-03-26 at 12.34.47 PM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/936e233d-bc8b-4b5a-b5f5-4ac6db377b71)

this is from sneakpreview

from local pointing at Rinkeby

![Screen Shot 2019-03-26 at 12 41 08 PM](https://user-images.githubusercontent.com/3970376/55020268-7ebcd680-4fc4-11e9-962d-4bb0a879cbf1.png)

**Comment by bthaile** [comment]
Was able to remove all but chrome-extension setTimeout errors.

**Comment by Chwy5** [comment]
tested - i dont see any error messages currently - closing for now
