### ISSUE TITLE
Implement Market Metadata Store

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur#148]
Using some centralized service (or IPFS/Swarm if ready and fast enough), implement a stor that can be looked up by market hash to get any extra data that we deem delicious for markets:

- longer description and details
- images (url or blob)
- external resources

**Comment by tinybike** [comment]
Hmm, the easiest implementation (for now) is probably to just attach this stuff to the market docs we're already caching via marketeer -- what other metadata do we want to store, besides the three things mentioned here?

**Comment by tinybike** [comment]
Oh hi IPFS

**Comment by tinybike** [comment]
Combining with #218: add a separate (longer) description field, and store that in the metadata store.  The (shorter) title remains on-chain.

**Comment by tinybike** [comment]
Combining with #244, filtering based on metadata / category.

**Comment by tinybike** [comment]
Added in c15e28a551d01ac2b76e648fa209654bda47b32b.
