### ISSUE TITLE
Tooltips with large amounts of text should be standardized

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1481]
these tooltips placement is off, they are not near the info icon.

and the market resolution source one's font color is white and unreadable

![Screen Shot 2019-03-26 at 1.16.50 PM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/9030e752-af8d-47f7-a203-4296024ffb20)![Screen Shot 2019-03-26 at 1.15.17 PM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/95510523-11b4-4708-9a85-0df35712689d)

**Comment by bthaile** [comment]
Need to standardize tooltips for mass text.

**Comment by bthaile** [comment]
closing this, redesign removes this very large tooltip
