### ISSUE TITLE
the content of these buttons is not aligned in the middle 

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1482]
looks really distracting that they don't have equal left and right padding.

 ![Screen Shot 2019-03-26 at 2.15.02 PM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/a8f69835-42b8-4e32-9343-66ed5b838ee9)

**Comment by bthaile** [comment]
There is an existing tix for formating the Transaction section. https://github.com/AugurProject/augur/issues/1347

closing this one
