### ISSUE TITLE
Notifications (mobile and desktop) 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1484]
Figma: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7268%3A27729
(side by side of mobile vs desktop notifications)

Notes:
- The only change between the notifications on mobile and desktop are width and text styles, title and body is 10px on mobile and 11px on desktop
- Otherwise we can treat notifications as a responsive component 
- <s>States</s> (moving to another issue --> https://github.com/AugurProject/augur/issues/1517)

  - <s>New = any new notification since the user last logged in (gets the purple new tag)</s>
  - <s>Unread = any notification that hasn't been interacted with by user yet </s>
  - <s>Read = any notification that has been interacted with (but not actioned or resolved) </s>

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/44acaf35-5829-4b1d-ad55-bb8fffa6dbf1)

**Comment by andrewdamelio** [comment]
@cillianhunter0 moving the states stuff to a separate issue to break up the work since its a little more effort than the design changes on their own.

**Comment by cillianhunter0** [comment]
🤘
