### ISSUE TITLE
Notification modals (mobile and desktop) 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1485]
Figma: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7228%3A28619

Modals: 
1. Unsigned orders
2. Open orders in resolved market [**modal not ready - temporary links to market page**]
3. Sell complete sets
4. Claim proceeds (individual market)
5. Claim proceeds (multiple markets) 
6. Finalize markets 
7. Orphaned orders [**modal not ready - temporary links to market page**]
8. Claim stake and fees [**modal not ready - using lagacy for now**]

**Comment by cillianhunter0** [comment]
Claim stake and fees added to figma

**Comment by Chwy5** [comment]
@andrewdamelio Open Order Notification - when i click on view in "New" state the modal does NOT open and the notification goes to the bottom of the (viewed) list

**Comment by andrewdamelio** [comment]
@Chwy5 after https://github.com/AugurProject/augur-ui/pull/2858 gets merged, clicking on VIEW will instead link to the market page.

Of course, once that modal is complete, it will open the modal instead of linking to the market page.

**Comment by pgebheim** [comment]
This is ancient, combining with #1716
