### ISSUE TITLE
timezone: market trading page messaging 

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1486]
https://www.figma.com/file/csVtbWhGCAYe3nVe2LI1UEPM/Timezone-issue?node-id=15%3A0

Yellow messaging above market properties with tooltip.

this banner is dismissible and shows up for each market.

**Comment by bthaile** [comment]
There is still one item to do, need to add the extra UTC timestamp and timezone to exiting date time

**Comment by Chwy5** [comment]
looks good - closing
