### ISSUE TITLE
timezone: new verification modal

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1487]
https://www.figma.com/file/csVtbWhGCAYe3nVe2LI1UEPM/Timezone-issue?node-id=15%3A0

Modal comes up on first trade (they click confirm in order form) for every market unless user clicks `Don't show this message on any more markets`

**Comment by bthaile** [comment]
Checkout dev.augur.net

**Comment by Chwy5** [comment]
looks good - closing
