### ISSUE TITLE
Categorical Markets

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur#149]
Implement a new market type that allows for categories such as horse races.

**Comment by tinybike** [comment]
Added to create market modal (and confirmed working) in bad716a1db4559adc5ae34eca6a5da0c05e2c497.  Market + reporting pages still need prettying up, so leaving this open for now.

**Comment by tinybike** [comment]
Usable/not-too-shabby as of 273a335900a761853169b6d71db8ef5b7db32302; closing.
