### ISSUE TITLE
Mobile - Account Summary - Account overview 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1494]
Figma: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7245%3A0

**Comment by Chwy5** [comment]
@cillianhunter0 plz rvw

**Comment by cillianhunter0** [comment]
Couple of small issues: 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/682be100-f114-4642-ada6-bc6cb0dd8082)

**Comment by phoebemirman** [comment]
@bthaile is adding the chart scale to his list.

**Comment by Chwy5** [comment]
@cillianhunter0 plz rvw this has been updated

**Comment by cillianhunter0** [comment]
@phoebemirman could you remove the bottom padding on: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/76976b0e-ccbb-406d-b9b9-b17c6be59c4c)

Other padding looks good.

**Comment by phoebemirman** [comment]
dupe of https://github.com/AugurProject/augur/issues/1534
