### ISSUE TITLE
Mobile - Account Summary - Tabbed navigation  

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1495]
Figma: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7245%3A0

Notes: 
- Horizontal scrolling tabbed navigation
- Each 'card' from the desktop version is it's tab on mobile
- Note: 'Notifications' displays a red dot when there are any new notifications 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/c4a733c5-c045-40c1-b22f-1ac233596ce6)

**Comment by phoebemirman** [comment]
is there no terms and conditions footer on this page for mobile?

<img width="745" alt="Screen Shot 2019-03-28 at 11 19 53 AM" src="https://user-images.githubusercontent.com/6775839/55183156-7d1e1a80-514c-11e9-9d60-a5e8da0ced54.png">
<img width="1348" alt="Screen Shot 2019-03-28 at 11 19 40 AM" src="https://user-images.githubusercontent.com/6775839/55183157-7d1e1a80-514c-11e9-9cc5-33f7596fe535.png">

**Comment by Chwy5** [comment]
@cillianhunter0 please rvw

**Comment by cillianhunter0** [comment]
Couple of padding issues and note on the styling underline of the active page. Details: 

Build on left, design spec on right 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/834c8eda-d9be-491d-8dad-281d4acf49a0)

**Comment by cillianhunter0** [comment]
Red dot for notification doesn't seem to be appearing either, but not sure if that's because I've already 'viewed' the notification?

**Comment by phoebemirman** [comment]
the red dot hasn't been added. thought that would go in with the mobile notification view tickets.

**Comment by phoebemirman** [comment]
moved the red dot for new notifications here https://github.com/AugurProject/augur/issues/1510
