### ISSUE TITLE
Mobile - Account Summary - Active markets

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1496]
Figma: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=6626%3A193084

**Comment by cillianhunter0** [comment]
Percentage change:
- Have we implemented the colors for increase/decrease along with icons (See design)
   - I haven't seen them in my build yet but likely because they just haven't triggered, possible to get a screen shot of that? 
- IF 0, format as 0.00% 

Design on the left, build on the right: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/0fc69f71-888e-4f8b-af6c-e3ed4d34da7b)

**Comment by phoebemirman** [comment]
dupe https://github.com/AugurProject/augur/issues/1524
