### ISSUE TITLE
Mobile - Account Summary - Augur status  

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1499]
Figma: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7245%3A187

**Comment by Chwy5** [comment]
@cillianhunter0 please review status of this

**Comment by cillianhunter0** [comment]
Small padding issue: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/ecc929a0-737a-4328-9789-f23084dfa6ca)
