### ISSUE TITLE
Update to notifications copy 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1501]
Figma: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7268%3A27729

Notes: 
- Copy has been updated on notification, titles, body and buttons
- tl;dr everything has been trimmed down to focus the message and save space

**Comment by cillianhunter0** [comment]
Is there a full list of the copy i can read through? (I only have a few notifs on my account at the min)

**Comment by andrewdamelio** [comment]
@cillianhunter0 See https://github.com/AugurProject/augur-ui/blob/1955482eab97c201f4e725d9a1759e437bbcfe78/src/modules/account/components/notifications/notifications-templates.tsx#L146-L272
