### ISSUE TITLE
quantity too long out of line in order book

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1502]
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/6872ee1e-980b-451f-93c5-cb5c1d3e4d2d)

Rinkeby:
http://localhost:8080/#!/market?id=0x75ec1f1a3356517908eccb5f6e4fac619c68ba99

What should we do, we've chatted about this but haven't landed on a specific soluiton.

1. Could trim off to 8 decimals so it would be `0.00000000` 
2. Just round up to `0.00000001` tell a bit of a fib?

@Chwy5 thoughts

Investigate ability to display `0.00000001` but when user clicks on value in orderbook the actual order quantity is inputted in the order form.

**Comment by Chwy5** [comment]
I like option 2...shows there is something in there...if it gets clicked on, the true value will show in the order ticket

**Comment by Chwy5** [comment]
approved

**Comment by Chwy5** [comment]
tested but cant tell if it works properly when i click on the order....When clicking on the .00000001 order I expect to see the true value in the order ticket....I keep getting scientific notation.  

Will need to retest after scientific notation is fixed

**Comment by Chwy5** [comment]
the order book part is fixed....still cant tell by clicking on the .00000001 if the real value shows in the order ticket - still getting scientific notation....closing this ticket since we have an issue for the scientific notation

**Comment by bthaile** [comment]
Theres another tix specifically for scientific notation from orderbook value
