### ISSUE TITLE
Mobile: trading page Trade section

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1504]
Changes to Trade section of trading page. 

- [x] The Buy / Sell button is gone
- [x] The outcome selector for categorical markets is sticky
- [x]  Order book / trade history is moved up
- [x] order form is next
- [x] then candlestick / depth chart
- [x] User can click on outcome in `Market Info` and navigate to the order form, if categorical the outcome selector will be on the correct outcome.

See `Trading Page - Mobile` section in the design
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/754bfc20-5653-4488-bad9-6ac3a2ab1aed)

**Comment by Chwy5** [comment]
@matt-bullock plz review

**Comment by Chwy5** [comment]
visually looks updated - closing will reassess functionality in mobile q/a
