### ISSUE TITLE
Partial Short Fill Only orders

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1505]
Community member mentioned that they had an issue taking partial short orders when `Fill Orders Only` checkbox is checked. 

Need to test this and other variations of `Fill Orders Only` when eth or shares are used to make sure there isn't existing issues. 

@Chwy5 can you run through some scenarios to verify everything is working correctly?

**Comment by Chwy5** [comment]
What does that mean exactly taking partial short orders.....Are they trying to hit the existing bids to get short (selling into bids)?...b/c if they are **taking** that is buying  and lifting offers off the book and wouldnt make them short

**Comment by Chwy5** [comment]
User hit bid to get short

**Comment by Chwy5** [comment]
Tested....did a bunch of successful trades in binary and scalar...
Did 6 successful trades in a cat 3 market....7th trade after selling  outcomes a and c...i tried to sell a partial of outcome B and the ui didnt update....In the bell my message got stuck in pending state, but when I went and clicked on the etherscan tx...it shows trade confimed.  I then tried the exact trade on snkpk and then 2 more times back agaon on augur app and the trade worked correctly and went through

**Comment by pgebheim** [comment]
@bthaile -- Set this to Needs Info until you move it to where you want it.

**Comment by bthaile** [comment]
not repro on v1, closing
