### ISSUE TITLE
Scalar Markets

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur#151]
Implement scalar market type

**Comment by tinybike** [comment]
Added to create market modal (and confirmed working) in bad716a1db4559adc5ae34eca6a5da0c05e2c497.  Market + reporting pages still need prettying up, so leaving this open for now.

**Comment by tinybike** [comment]
Prettying up is ongoing, but has reached a sane and more-or-less usable form as of 0547dcf55211b51dd6214bccd679aff3abaa38dd.
