### ISSUE TITLE
Change invalid share value message

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1512]
“I think the text on the new warning has a slight flaw. "each share will be refunded to traders in equal amounts"
This can give traders the impression that their trades will be refunded back to what they originally paid”

“Yeah it should be each share will be valued or worth, not refunded”

Make changes on master

**Comment by cillianhunter0** [comment]
Update to sentence: 
"If a market resolves as invalid, each share will be valued equally, based on the number of outcomes.  For example, if a market has 4 outcomes, each share will be valued at 0.25"
@Chwy5 can you confirm ?

**Comment by Chwy5** [comment]
@cillianhunter0 Use this instead...."If a market resolves as invalid, each share is worth equal amounts at resolution."

**Comment by cillianhunter0** [comment]
The new sentence: 

"If a market resolves as invalid, each share is worth equal amounts at resolution."

**Comment by Chwy5** [comment]
Approved

**Comment by Chwy5** [comment]
confirmed on dev - closing
