### ISSUE TITLE
timezone: market creation and form changes

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1516]
Text formatting and styling for 
- [x] Reporting form
- [x] Dispute form

Changes to market creation
- [x] remove header
- [x] condense multiple forms into one
- [x] add more properties to confirmation page

**Comment by Chwy5** [comment]
approved

**Comment by bthaile** [comment]
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/c28ba59b-47c8-4f2c-8b1f-7d679814b066)

**Comment by cillianhunter0** [comment]
Looking good. 

Some small things: 

Copy on the date/time labels (to keep consistent):
- "REPORTING STARTS DATE" -> "REPORTING START DATE"
- "REPORTING STARTS TIME" -> "REPORTING START TIME" 

Tooltip beside "official start time": 
- Hard to see this:
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/06e61633-6271-46e0-aa8d-d31923118eaa)
- Can we use the icon in figma 

Date input looks disabled: 
- Change font weight from 200 to 400 and colour to ##372e4b to match the other inputs

When I'm on the liquidity step and tap next, I'm at the bottom of the 'review' page, have to scroll back up to see the content.

**Comment by cillianhunter0** [comment]
Also, we've decided to remove the 'delay reporting' input as it creates confusion now that we've renamed 'event end time' to 'reporting start time'. 

We need to update the copy on the right as a result.

figma: 
https://www.figma.com/file/csVtbWhGCAYe3nVe2LI1UEPM/Timezone-issue?node-id=163%3A113

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/72f58721-3b0a-4134-83ea-a434098b5d80)

**Comment by Chwy5** [comment]
Market creation is updated, waiting on reporting/dispute updates
