### ISSUE TITLE
Deprecate Faucets in Favor of an Artificial Economy

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur#152]
For beta release, we would like to create an artificial system supported by the core to  create some scarcity and incentives for making good and prudent decision on augur.

**Comment by tinybike** [comment]
Replaced cash faucet with deposit / withdraw ether methods: AugurProject/augur-core@78e0d79e44a40f4a095caccf6249999f59dc5391 & AugurProject/augur.js@06072cd230053854d918a78bf595909758d6e28c.
