### ISSUE TITLE
Account summary - claim stake & fees modal

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1522]
Does not match with design for this modal. 

Build
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/b943c316-a118-4c62-896e-6c6ea7cfd460)

Design
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/9b0b9051-e20b-4a1b-b9b6-bf2b920339d6)

**Comment by cillianhunter0** [comment]
One tweak needed: 
- Small separation between the REP amount and the ETH amounts 
- Update label from "total", to "Total ETH" for clarity 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/16ad5d4e-59df-4305-a013-608839197f1e)

**Comment by Chwy5** [comment]
@cillianhunter0 plz rvw and close if it looks better to you

**Comment by cillianhunter0** [comment]
Previous points are fixed. 

Seeing an issue with the update to the new scrollable modal. See my comment on ticket below. If it will be fixed in that ticket then we can close this one out. 
https://app.zenhub.com/workspaces/augur-5bfed3424b5806bc2bf8d173/issues/augurproject/augur/1601

cc: @phoebemirman

**Comment by phoebemirman** [comment]
that should be fixed there
