### ISSUE TITLE
Account summary - active markets 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1524]
- Update to copy, 'open markets' to 'active markets' 
- Can remove the copy next to the search icon 
- Update to column label copy
- Update to the format of the % values in rows 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/590eb093-7fa0-4abe-99b4-7d51db99548e)

**Comment by phoebemirman** [comment]
most of this was updated, maybe it isn't on sneakpreview yet. Ryan is working in getting the backend numbers for those so everything is zero as a placeholder.

do we want all places where 0% is shown to be 0.00%? like here:
<img width="675" alt="Screen Shot 2019-04-02 at 9 34 36 AM" src="https://user-images.githubusercontent.com/6775839/55419872-8f240280-552a-11e9-8b3e-e416ea70b56d.png">

**Comment by phoebemirman** [comment]
make mobile and desktop match as so:
![image](https://user-images.githubusercontent.com/6775839/55422869-8aaf1800-5531-11e9-9894-0f285d656e18.png)
