### ISSUE TITLE
Account summary - Augur Status 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1525]
Small padding issue 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/057bbbae-1cb8-4f4a-bc46-0ac00145f6f0)

**Comment by phoebemirman** [comment]
<img width="488" alt="Screen Shot 2019-04-02 at 9 41 43 AM" src="https://user-images.githubusercontent.com/6775839/55420305-8d0e7380-552b-11e9-91da-31488b915b37.png">

fixed on sneakpreview
