### ISSUE TITLE
Account summary - notifications - unsigned orders modal 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1527]
- There is no feedback after tapping 'claim', we can use the 'pending' tag here 
- Market title isn't clickable through the market page
- Total gas is showing as zero 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/327b4973-aa30-4df9-bfaf-dbedc53d5dd4)

**Comment by bthaile** [comment]
@cillianhunter0 what should the feedback when user clicks `submit`?

**Comment by bthaile** [comment]
We'll work the user feedback mech when design is worked out.

**Comment by bthaile** [comment]
putting this back in feedback until we get the design worked out for handling user feedback.

**Comment by Chwy5** [comment]
@cillianhunter0 please review
