### ISSUE TITLE
Account summary - layout 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1530]
There are a few issues with the layouts responsiveness to different resolutions. 
- Column widths don't remain even 
- At smaller resolutions UI elements start to run out of the screen 

Design and dev teams to discuss this and update this ticket with solution. 

Examples: 

Column widths are not even: from below 1920 down to 1320
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/9ef818af-f0e3-4aa2-ad8d-11b12857fab2)

Column widths are not even: 1440 width
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/c31e52b8-528e-40f9-a852-2dbdc84e0a28)

Column widths are not even and start to run off the screen: From 1320 down
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/52eb71c3-dfa7-4c37-9b48-e9049d11a4fc)

Column widths are not even and start to run off the screen: Another example at 1280
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/59d310fd-e270-4299-9c3e-cf77140f7aeb)

**Comment by phoebemirman** [comment]
dupe https://github.com/AugurProject/augur-ui/issues/2778

**Comment by phoebemirman** [comment]
need additional breakpoints

**Comment by Chwy5** [comment]
need to address when breakpoints are figured out

**Comment by pgebheim** [comment]
Moving this into backlog but leaving this as blocked by the other issue.

**Comment by pgebheim** [comment]
Done
