### ISSUE TITLE
Remove market title from expanded state of Open Orders and My Fills on mobile trading page and add market title to top of this section

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1531]
Note this is only a change to expanded states on the trading page, not the portfolio.

Market title should be scrollable with the rest of the page. See design file for size and positioning.

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/61bfe180-5fe1-4d18-b4c9-a9f7cf3954c7)
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/22ee3cb6-a648-4da2-b3f1-46245cfbd525)

**Comment by Chwy5** [comment]
looks good closing

**Comment by matt-bullock** [comment]
Can we check the spacing here
![image](https://user-images.githubusercontent.com/39496225/56045074-c8d1e600-5d40-11e9-8028-f8140fc2854f.png)

**Comment by matt-bullock** [comment]
closing
