### ISSUE TITLE
New styling for Orphaned Order messaging on the Trading Page

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1533]
Low Priority styling changes for standout and consistency with our other messaging

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/bb8404be-5021-468f-82b2-162bb63823ba)

**Comment by Chwy5** [comment]
I only want to update Orphaned orders...we should leave complete sets the way they are....some users will trade in and out of complete sets (shouldnt look like a warning message)....Also complete sets will occur automatically for v2... dont wast dev time on this update....

only want to update orphaned orders

**Comment by bthaile** [comment]
updated title to remove `sell complete sets`

**Comment by Chwy5** [comment]
works -looks gd...closing
