### ISSUE TITLE
Update trading page header section - Desktop

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1535]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/5043a40f-9fd1-4d59-ae41-b305dfc0cb3b)

All states can be found within the trading page design here:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/269e395a-6227-4653-9def-6288153740be)

**Comment by bthaile** [comment]
look on `Trading page - desktop` section of Augur Redesign design

**Comment by andrewdamelio** [comment]
To help with QA

### Testing
```
LOG IN AS
0xbd355A7e5a7ADb23b51F54027E624BfE0e238DF6
```

**In reporting viewed by designated reporter**
0xddf472617f4103b0025fb1e320e37de55391e201

**In reporting - open reporting**
0x78c67b0b1ec71d2daa5fc20dbdc7981a050db0a2

**In reporting - in dispute window**
0x461fc817fb2cdc1b89fe2072a7166d706b397c2e

**In reporting -awaiting next dispute window**
0x513088c059411248ad68c710c083a52da2a771ce

**Resolved - awaiting market finalization**
0xf5d13f3eede50c0f9ad322b9c9971e2d47ce61a2

**Resolved - market finalized and moved into 3 day waiting period**
0xc82661ee0ce5f8b5668421e19694d0d439a25c2c

**Resolved - 3 day waiting period ended seen by users with proceeds to claim**
0x900adfa9d44c4fcfa4f13609d7440b97ed559af7

**Resolved - 3 day waiting period ended seen by users with no proceeds to claim**
0x879f55cbe5b34c6ec9548055523ebf088a6b9aec

**Comment by Chwy5** [comment]
@matt-bullock plz rvw

**Comment by matt-bullock** [comment]
Check alignment of right section. See guide:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/d99c95e1-7f19-4184-bb27-9fe6da9e87b0)

Check grid. Left and right sections should be split 50/50
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/33132a48-2cc1-4d51-98ce-377d321c1209)

Purple divide should be #211A32
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/43390414-ef55-4c9d-a781-985419f90d3c)

ETH values are getting broken onto two lines. Making this section 50% of the header width should help fix this but we'll need to test and possibly knock the text size down at smaller break points
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e10d290b-0773-435d-b0b1-fb4e81cf66b0)

Timeframe component can be nudged up  a pixel or two to align with other labels

Estimated Fee isn't horizontally aligned with 24hr volume

Tooltip should be using Roboto 10px, not Roboto Mono. Bold for title, Regular for body copy. (sorry zenhub won't allow me to post images anymore).

Can we add some line height to the additional details copy. I have 140% in the figma file. This should be standard for 12px Roboto paragraph text. Lets it breathe and is easier to read

Remove gradient fade on additional details and instead follow design and add an ellipsis 

Smooth out transition of showing more/less of additional details. Message me if you need any guidance on this but you can see the action is clunky. Would be good to add some easing to it

Centre the arrow to 'LESS'. It moves up a few pixels

**Comment by matt-bullock** [comment]
market status shouldn't wrap here. Countdown timer should allow the market status to fit on one line
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/7d33458e-8fd6-4be6-8860-bf3f9604b188)

Clicking menu button a second time should close the menu.
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/a1407c96-17ae-4b52-b527-e4b650c7508b)

Coundown timer label should be 10px. Currently it's showing up as 11px
Left Align this the label and time. Currently it's right aligned
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/8e52a97c-58c3-403e-bd51-5f62a9ae648b)

Align Top these component
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/02cd60d1-0b32-4b2d-b5cf-7e1bccaeb14a)

Can we switch from centre alining the countdown element to top alignment. It looks odd it the message in that box goes onto multiple lines
Also increase the spacing between countdown as the messages to 40px. See below:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f4af0693-a222-4f98-b961-f804cfaff67d)

**Comment by matt-bullock** [comment]
Update 'Reporting Began' to 'Reporting Started'
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/cf4e6ed6-5378-4c0d-912a-733918dfa198)

**Comment by matt-bullock** [comment]
Looks good. There are few things that still need addressing. Nothing major but would be good to get these in.

- [x] update this arrow to the arrow we're using across the designs
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/b9d33cb7-7589-41cf-9b20-7b477c414335)

- [x] Nudge up roughly 2px the Estimated fee figure - so it lines up with 24hr volume figure
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/6d5d1d49-5b6a-4371-8c35-e74f55a29d0e)


- [x] Can we add some line height to the additional details copy. I have 140% in the figma file. This should be standard for 12px Roboto paragraph text. Lets it breathe and is easier to read
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/1ee8cdce-f0e3-4c95-a6a6-def569166b31)

- [x]  update 'More' button - see design 

- [x] hidden text should end with ellipses and shouldn't cut through a line of text. This is what I'm seeing on the build. Is it possible for it to work like the screenshot above?
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/6f2ad365-6e22-4449-9e79-efaf7e6194ae)

- [ ] animation to show less/more could be smoothed out. When I click 'less' it pushes the content below down before pulling it back up. Should be a smooth eased transition with no jerkiness.

- [x] default state for menu button should be #76737E. White on hover/active
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/11afda9e-6a4f-434b-bdb1-79ad87ccfb38)

- [x] change timeframe line background colour to #76737E
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/957ce3f0-3a66-4acd-866e-5d3e3cc8e1d3)

**Comment by andrewdamelio** [comment]
@matt-bullock for sure! will do

**Comment by matt-bullock** [comment]
Looks good closing for now.

Couple of issues i've created separate tickets for in v1.14
