### ISSUE TITLE
2 boxes selected on menu bar

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1538]
When a user creates a market and submits their transactions for market creation (and pre/liquidity) we currently take them to the Portfolio pg....But both menu boxes are highlighted... if we are taking them to portfolio only portfolio should be highlighted when they get there...See screenshot

![4-2menu.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/8533d097-5663-4440-92d3-bb770f74013c)

**Comment by bthaile** [comment]
There is a similar tix about having the correct primary nav highlighted/active. I suggested removing/disabling the active highlighting.

**Comment by Chwy5** [comment]
I was thinking about this more....we should try to fix instead of making all the same color.   We removed the headers of location on the pg to provide additional room....Highlighting the nav menu box shows a user where they are.

**Comment by bthaile** [comment]
When we change ip the nav to new look we will definitely fix. 

We’ll see if there is a quick fix for the active highlight issue first, we need to totally refactor how routing works. It was over engineered.

**Comment by andrewdamelio** [comment]
closing -- will be addressed with the new nav to be created
