### ISSUE TITLE
Look into the upsert module for PouchDB

### ISSUE THREAD

**Issue by brianosaurus** [AugurProject/augur#1540]
We have to set retries for PouchDBs bulk insert to 10 to get around 409 db document conflict errors. If that fails we get an unhandled promise exception. There is probably a better way to deal with this.

Look into this plugin for PouchDB (which handles retries for us): https://github.com/pouchdb/upsert

See if we can make it retry less and/or handle the retries for us. It would be better to not throw an unhandled Promise exception on failure.

**Comment by pgebheim** [comment]
Adding to next Milestone.

**Comment by pgebheim** [comment]
@justinbarry -- This was done right?

**Comment by justinbarry** [comment]
@pgebheim yes.
