### ISSUE TITLE
The Invalid outcome needs special treatment in the Reporting and Dispute UI

### ISSUE THREAD

**Issue by nuevoalex** [AugurProject/augur#1548]
Currently if someone makes an outcome with the text "Market is Invalid" it will be indistinguishable from the _actual_ Invalid outcome in the reporting and disputing UI.

It should have special visual treatment such as being a different color and ideally with a help tooltip explaining it is the real invalid outcome.

**Comment by Chwy5** [comment]
@cillianhunter0 lets discuss and add to next sprints tasks...will need design mock up for this

**Comment by Chwy5** [comment]
Closing quick change done
