### ISSUE TITLE
DR reporting when market in open reporting

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1549]
Need to show `repAmount` to user when they are open reporting and are designated reporter.

user being designated reporter take precedence over market being in open reporting. 

to repro:

create a market where the DR and market creator is the same.
let market go to open reporting
when the DR reports they need to have REP there needs to be a REP amount shown

**Comment by Chwy5** [comment]
@bthaile can you update the word change for clarity and correct value to be displayed. We shoudl remove the negative value for returned rep.
@cillianhunter0 we need to think about possibly adding a (i) - a descriptive sentence

**Comment by Chwy5** [comment]
confirmed changes - closing ticket
