### ISSUE TITLE
Portfolio - open orders - sorting bug 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1552]
When I filter the open orders panel by "view by most recently traded outcome" on the portofolio page, the list of orders disappear. See gif of the behaviour: 

![portfolio - open orderes - bug.gif](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/5fc11e9a-295b-45c4-b1b4-746229ec0695)

**Comment by bthaile** [comment]
not able to reproduce this issue. @cillianhunter0 ping me and we can walk through this issue. If you can still repro.

**Comment by cillianhunter0** [comment]
Fixed.
