### ISSUE TITLE
Account summary - label styling

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1554]
Some labels in the 'your overview' and 'augur status' panels are white. We need to update to light gray #76737E

Build on left with labels highlighted, design on right: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/7a3af74c-3d6f-4faf-b4fb-18ccde9cf328)

**Comment by phoebemirman** [comment]
dupe https://github.com/AugurProject/augur/issues/1573
