### ISSUE TITLE
(Desktop) Portfolio - positions - % change 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1555]
We show 4 characters after decimal point in some instances of the % change, let’s update this to only show 2. 

Rules for this: 
- IF % change => 0.005 THEN show change of 0.01 (in green/red depending) 
- IF % change <0.005 THEN show no change (i.e. 0.00% in grey)

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/cc321327-2c29-4986-91a2-02244f019e44)

**Comment by Chwy5** [comment]
looks good - closing
