### ISSUE TITLE
(Desktop) Portfolio - positions - % change alignment issue

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1556]
% change values are being pushed out of place

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/2b31c3d6-d5f1-4044-9319-6d274a32cf06)

**Comment by cillianhunter0** [comment]
The percentage change values seem to be fixed but the label are now out of alignment: 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/b1a45a4c-31c8-45e6-b8f4-95f391ca4643)

**Comment by Chwy5** [comment]
looks better - closing
