### ISSUE TITLE
(Desktop) Portfolio - positions - color of rows 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1557]
When a row is exapnded, any of it's sub rows should have the same background color: #2B2438

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/4378b010-0e83-43fb-b202-85964d2ec743)

**Comment by bthaile** [comment]
keep a look out for a similar tix having to do with sub-rows color same as parent row when expanded.
