### ISSUE TITLE
(Desktop) Portfolio - my created markets - countdown timer

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1559]
Component needs to be updated to have 1 consistent pattern for the countdown timers across the app. 

Cillian is working on this today. Will update here when done. 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/024a9696-7769-4d86-8dfc-f9907088b2c3)

**Comment by bthaile** [comment]
this tix might get fixed indirectly when the other tix to standardize all countdown timers gets worked.

**Comment by cillianhunter0** [comment]
Do you want to close this one in favour of the other?

**Comment by bthaile** [comment]
Yes, closing this in fav of other tix
