### ISSUE TITLE
There are randomly "invalid" markets strewn about for no apparent reason

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#156]

**Comment by scottzer0** [comment]
this i believe is related to the zero'd out state after buying shares, which the market also goes invalid.  at some point, something changed and now the async market loading doesn't always fetch the needed data to complete the market and it's marked as invalid.

this is my current focus.  not easy to debug though.

**Comment by scottzer0** [comment]
@joeykrug does this happen when using a local geth node?

just fyi, it looks like jack's changes might have created two places where that host is set and i'm still trying to audit his changes to see where augur.js is setting the host.

**Comment by joeykrug** [comment]
yeah happens both w/ local and with hosted client in the sky

**Comment by scottzer0** [comment]
fixed by migrating to augur.js filters.  huzzah!
