### ISSUE TITLE
(Desktop) Portfolio - filled orders - padding and truncation 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1560]
Three things here: 
1. 'no of fills' label is very tight to the label on the left, let's move that right
2. Outcomes should be indented by 8px to help see parent/child relationship with market etc
3. Where we have truncation on a value, it would be great to use alt text to show the full value on hover

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/6fc30a28-0669-4db7-aa5b-9033275c0188)

**Comment by Chwy5** [comment]
@cillianhunter0 plz review...the no of fills in the top right of filled orders still doesnt look right on mine

**Comment by cillianhunter0** [comment]
Looks better for me, @Chwy5 can you add a screenshot?

**Comment by Chwy5** [comment]
@cillianhunter0 

![4-9.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/99e3c742-b914-43c1-9b45-324ae5d42afd)

**Comment by cillianhunter0** [comment]
Can we move the "no of fills" column 8px to the right

**Comment by Chwy5** [comment]
@cillianhunter0 plz rvw and close if you think this is fixed
