### ISSUE TITLE
(Desktop) primary navigation 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1564]
If I click a market link listed on the Portfolio page, when the market opens, the primary navigation still has portfolio highlighted. 

Logically the primary nav should highlight the 'markets' link as it's where the market 'lives'.

**Comment by bthaile** [comment]
I think we need to get rid of the highlighting of the primary nav. We'll be readdressing nav later down the road when reporting redesign starts.

**Comment by cillianhunter0** [comment]
So for now we only highlight the nav when a user is in one of the primary pages?

**Comment by bthaile** [comment]
We’ll investigate having the correct primary nav highlighted, if its not a simple change, we’ll simply not highlight the nav button.

**Comment by andrewdamelio** [comment]
Closing -- will address in #2861 (if it's applicable) when we create the new v2 navigation.
@pgebheim
