### ISSUE TITLE
Says I own 47 rep immediately after creating an account before i have any ether and before i even use the faucet

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#157]
![screen shot 2015-09-13 at 8 50 30 pm](https://cloud.githubusercontent.com/assets/5925937/9840519/20096bb2-5a59-11e5-986c-177ac3da7f63.png)

**Comment by joeykrug** [comment]
issue is fixed now

**Comment by joeykrug** [comment]
nvm, is back

**Comment by tinybike** [comment]
>:(

**Comment by tinybike** [comment]
I'm not seeing this any more on the latest divshot push.  Tested by registering a new account, and for me 50 (then 100) ether appeared in the account, and cash/rep were both zero.  Closing for now; as always don't hesitate to re-open if this issue appears again...
