### ISSUE TITLE
Total Cost column needs to display unrealized cost

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1570]
steps to reproduce....buy 3 shares of an outcome at one price...sell 1 share higher to get a realized and unrealized pnl.  Then sell another 1 share at a different price.   Total cost is still displaying on the original purchase amount and not on the remaining open balance.

**Comment by bthaile** [comment]
need to use unrealized cost for position total cost.

**Comment by Chwy5** [comment]
look to be fixed - closing
