### ISSUE TITLE
Transaction history - update to the 'action' input 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1572]
Figma: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7452%3A17292

"Claim" to be split out into 4 options: 
- Claim market creator fees
- Claim participation tokens
- Claim staked REP & reporting fees
- Claim trading proceeds 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/345c6251-3603-4101-b0d6-c409747572c1)

**Comment by Chwy5** [comment]
@cillianhunter0 plz review design on this

**Comment by cillianhunter0** [comment]
One issue: 
- Font should be Roboto regular in the 'action' and 'coin' inputs and dropdowns 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/2aa1e7c6-7370-4a70-be52-5c8abd20d2b8)

**Comment by JohnDanz** [comment]
Fixed this and pushed the fix to `new-trading-page-layout`
