### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jessepollak** [AugurProject/augur#1574]
Hey all -- wasn't sure where the best place to put this was, so figured I'd just open up an issue!

I spent 30 minutes playing around with Augur today and wanted to share some high level feedback from a first time user. First thing I want to say is: wow! This has come a long way. The UI is beautiful, the sections make sense, the interface feels snappy and exciting. Amazing work!

Some smaller nits:

* They distinction between Buy/Sell is _confusing_. On [this trade page](https://dev.augur.net/#/market?description=will_the_golden_state_warriors_win_the_2019_nba_championship&id=0x6abb420dff196253b3946b649ed39b13678fb6b0), I am very confused about how to bet "No", I do not think they will win the championship. I executed a "Sell" (though I don't think I owned anything?) and it seems to have executed. Does this mean I bet against it? I also issue a "Buy" and the order is still pending? I'm pretty confused by what's going on here. It would be amazing if in the UI there was some Augur 101 stuff that walked me through the basics of how I invest on either side of a prediction.
* I am confused by [this market](https://dev.augur.net/#/market?description=high_temperature_in_degrees_fahrenheit_on_wed_may_02_2018_at_the_san_francisco_international_airport_as_reported_by&id=0x9c0d56766ddf313bcd519666b0af3b8d51f27f79). How do I actually pick a degree that I think it will be? I can place a "Buy" or a "Sell", but I can't figure out what this actually means. This is similar feedback to above, but since it's not a binary prediction, I think I require even more UI / UX help.
* When I place an order, there's not status or indicator that my transaction is pending. It would be amazing if the little prompt that shows up bottom right also included a link to something like Etherscan where I could track status. Also, it would be great if pending transactions could show up in the My Positions section with a pending status.
* On the Porfolio page, I'm not sure what [this chart is](https://www.dropbox.com/s/yunyby3o0ijaikm/Screenshot%202018-05-12%2012.59.28.png?dl=0). It was there before I had an positions, is it the entire market? Fake data?

Anyways, just wanted to dump out thoughts in case they were useful. Really excited to see this continuing to mature 👏 🎉 💛 

cc @joeykrug

**Comment by joeykrug** [comment]
Thanks! This is [one of] the right place[s]!

- Yep it means you short sold / bet against it. It is kinda confusing, there'll be a tutorial walkthough explaining it all in the UI eventually. Essentially it's a trading platform first, then there'll be a simpler UI skin that makes it easier / simpler to use for betting, which should also help with this issue. Did your buy order ever finish pending? Or does it instead say "open order" [this is like an open unfilled order on gdax if that's what it says]
- Ah yeah, so you don't actually pick an exact degree it'll be, what you do is buy / sell or go long / short the market at a given price. So for instance, say the current prediction is 0.27 degrees and you think it'll get up to 20 degrees, just how if in a binary market you would buy up to say 60% odds or a price of 0.60 and you'd enter in 0.60 for your price in the buy box, here you'd enter in 20 and the amount you want to buy as well.
- I agree, good call x2
- Yeah, that's a bug I've reported as well, it's fake data haha

**Comment by jessepollak** [comment]
🙏
