### ISSUE TITLE
Sort disputing market cards by highest market outcome stake

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1574]
Since users can stake more than maximum on initial reporter contract, a bug discovered a while ago.

Sorting by dispute market cards by round isn't accurate representation of which market is closest to forking.

Sort dispute market cards by markets highest staked outcome.

**Comment by Chwy5** [comment]
approved, will be included when we start work on the reporting pg redesign

**Comment by matt-bullock** [comment]
If I'm understanding this correctly, we don't want to sort by the 'total amount of REP staked' in a market but instead by the 'market with the highest staked outcome'?

If we have a sort by dropdown, is there anything else we would want to sort the markets by in reporting? @bthaile

**Comment by bthaile** [comment]
We want to sort by total REP staked, which I think you have added to the dropdown.

**Comment by matt-bullock** [comment]
Yeah we have that in the wireframe. Can you think of anything else it would be useful to sort by?

**Comment by bthaile** [comment]
Add all the same sorting options we have in market listing.

**Comment by matt-bullock** [comment]
Not sure how useful those other options would be. What reason would users have here to sort by OI, Vol etc?

**Comment by bthaile** [comment]
Consistency in the UI with sorting market cards list.

**Comment by Chwy5** [comment]
Different sorting....

We should Sort by:
Amount of Rep Staked 
Dispute Round
Ending Soonest

**Comment by pgebheim** [comment]
Designed:

![image](https://user-images.githubusercontent.com/86010/64465051-67c7f780-d0bf-11e9-8f18-55cf94437785.png)

#3195 for dev
