### ISSUE TITLE
new claim stake and fees notification doesn't show up until you click "my reporting"

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1588]
probably not likely to occur because only happens when on localchain.

need to be on the app when the fees become claimable. meaning notification isn't updating based on new data.

**Comment by andrewdamelio** [comment]
@phoebemirman I have a fix for this - feel free to assign this to me after approval

**Comment by Chwy5** [comment]
approved

**Comment by andrewdamelio** [comment]
@Chwy5 v 1.13 or 1.14?

**Comment by Chwy5** [comment]
1.14

**Comment by pgebheim** [comment]
I'm moving this into Reporting for someone to take a look at and understand if it's still an issue with the new designs.

@andrewdamelio

**Comment by bthaile** [comment]
closing this since we are totally redoing reporting / disputing and there is no "my reporting" section in the new design
