### ISSUE TITLE
Trading Page: Outcomes Table

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1589]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/0ed98f36-3336-41fe-89bf-7de21f4df593)
- [x]  last price arrow looks slightly bigger than design
- [x]  Maker sure numbers are 11px and #CED7D8
- [x]  Outcome should also be 11px font size - check styling against design
- [x]  Remove background colour on non-categorical markets
- [x]  Outcome shouldn't be selectable on non-categorical markets  (there is currently an interaction state on the build that does nothing)
- [x]  reduce row height to 32px
- [ ] Find a solution so that the space sits on the line below on all the header labels to the right
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/66dda9a9-e798-4042-bfc8-97ba45a9f7dd)
- [ ] Give the outcome name more space - allow 16px or a suitable percentage of padding between the outcome name and Bid Quantity column. See below ![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/70325e36-c3e0-4fb7-9463-8002ba28be07)

**Comment by Chwy5** [comment]
@matt-bullock plz rvw and close if completed

**Comment by matt-bullock** [comment]
It looks like we can give the outcome names more space by decreasing the space between the other columns:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/11ed6896-7148-4b7f-aa2e-c8dea6a03715)

All labels need to wrap onto 2 lines when required or we have this issue. Is this an issue that can only be fixed by adding more responsive design breakpoint? (Trading page designs are on their way)
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/39885308-ea79-4872-b69c-08cedda8de0a)

**Comment by phoebemirman** [comment]
i think we need another breakpoint for that.

**Comment by Chwy5** [comment]
@matt-bullock plz rvw

**Comment by matt-bullock** [comment]
![image](https://user-images.githubusercontent.com/39496225/56038975-848c1900-5d33-11e9-8d4b-83038e29d98a.png)

Seems the only way to solve this issue is to add more breakpoints. Rest looks good.

Can you close up the spacing between the number and arrow in last price. About half the existing gap.  Design has 4px

**Comment by matt-bullock** [comment]
fixed. Closing
