### ISSUE TITLE
Verify market data via sha256

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#159]
Verify the given market data by marketeer hashes up to the same hash as it gives (so it's not spoofing fake data)

that'd be sha3 cost * numMarkets addl computation, but should be essentially negligable

**Comment by tinybike** [comment]
But this will foil all my evil plans D:

**Comment by robertmccone** [comment]
Looking into this one. It looks like the Marketeer does not currently store all the information needed to recreate the hash. Specifically it is not storing (grabbed from createMarket.se):

MARKET
tx.origin
initialLiquidity
cumulativeScale

I think all the rest exist or can be derived from what Marketeer is storing. Is adding these fields currently in the works? If not, who should I coordinate with as it will involve deploying new marketeers?

**Comment by tinybike** [comment]
Added in AugurProject/augur.js@3b7ec7492a0f0111dadc01176b4e6f5195140810.
