### ISSUE TITLE
Desktop Trading Page: Open Orders

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1590]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f05c55fe-345b-44c8-a893-b1e5c905990b)
- [x]  increase padding around column heading labels so they are forced to go onto two lines if the space is too tight. You can see from the above that labels are pushed together causing confusion.
- [x]  make sure labels stay lined up with content (I think more responsive breaks will help this)
- [x]  Update label colours to #76737E. This should be a global change
- [x]  gap between total cost shared column and the cancel button can be one third tighter to close up the space here.
- [x]  Reduce down the size of the bottom bar (holds cancel all button) to 32px. Do the same for My Fills and Positions

**Comment by Chwy5** [comment]
@matt-bullock please review...at least at first glance on mine the total cost eth and shares have not been updated.

**Comment by phoebemirman** [comment]
only condenses on 
<img width="743" alt="Screen Shot 2019-04-08 at 5 14 56 PM" src="https://user-images.githubusercontent.com/6775839/55764783-e261ed80-5a21-11e9-8c1b-1964eb1b57cc.png">
smaller screens

**Comment by matt-bullock** [comment]
Can we always have Total Cost (ETH) and Total Cost (Shares) go onto two lines - like how they sit on smaller screen sizes. Request from Chwy and Joey.

**Comment by Chwy5** [comment]
Looks good - closing
