### ISSUE TITLE
Desktop Trading Page: Order Ticket

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1593]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/9d065f02-4746-4f96-9add-0606544cb597)
Design       |         Build

- [x]  Update Tab Styling. Headers on desktop are 48px now.
- [x]  make Outcome text 14px Medium Weight. Required for more space
- [x]  Update input label styling - make mono caps and update colour
- [x]  Update type style of denominations (SHARES,ETH,ETH)
- [x]  Update type and spacing within this area:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/82167a3c-efdb-45c3-a411-1f37d6370f7d)

- [x]  change type style of button
- [x]  check "Place Buy/Sell Order" button color - design looks a lot more vibrant
 - [x]  Update outcome display/input - see below
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/08756e95-b7f3-4869-b66e-2faa68263e92)
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/a3df412c-d33a-4748-9f52-d00ca9c22f2c)

-[ ] Update scalar input to better fit the denominations. Text showing the denomination can drop down to 9px. See below
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/8f1ee6e9-d61d-4bc1-8012-f7fad9d4e3e1)

**Comment by Chwy5** [comment]
outcome/denomination for scalar markets only make 50% each side

**Comment by Chwy5** [comment]
closing
