### ISSUE TITLE
Desktop Trading Page: Order Book

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1594]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/39ab3571-d4e3-45d2-ba5f-50087c1da875)
Left: Design | Right: Build

- [x]  Make Quantity and My Quantity numbers #CED7D8
- [x]  Update Spread Typography and design including background colour
- [ ] Update quantity bars so max width is right of Quantity column. See image below
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e754db53-3271-426f-80e2-8b3d85ec3f13)

**Comment by Chwy5** [comment]
prioritize shading s/b based off of total eth amount not just shares (quantity * price)
