### ISSUE TITLE
View by most recently traded Market does not update 

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1596]
View by most recently traded Market does not update in portfolio pg, filled orders quad.

I have tested multiple times and sometimes it updates and sometimes nothing updates even being both maker and taker in 2 separate accts.

I Created a market in acct A and added preliquidity...Acct be trade vs acct A (both were on the trading pg)...then went to portfolio pg for both accts....My Market and and My filled order should be displayed at the top but neither accts show it.  I even tried going back into the trading pg and back to portfolio pg and still doesnt update it.....Only refreshing the pg works

**Comment by cillianhunter0** [comment]
@Chwy5 can you check this one

**Comment by Chwy5** [comment]
Just tested...still didnt update automatically....I needed to refresh the pg and then it updates

**Comment by phoebemirman** [comment]
this is working for me. it takes a while to show up though. are you the filler in this scenario? 

also, if you are filling on the same order it could have shown up under "no. of fills"

**Comment by Chwy5** [comment]
So I am trading with myself in different accts( acct 1 is the maker - adding orders in preliquidity, and acct 2 is the taker of orders)....the taker shows up quickly, but the maker at least when i create in pre markets liquidity, doesnt show up until i refresh

**Comment by phoebemirman** [comment]
i tested this scenario and it worked for me.

**Comment by Chwy5** [comment]
ill test further

**Comment by Chwy5** [comment]
closing for now...will reopen if issue happens again
