### ISSUE TITLE
make market categories case insensitive

### ISSUE THREAD

**Issue by reductionista** [AugurProject/augur#1597]
I created a market today on test.augur.net, just to get more of a sense for how the UI works.  I intended to add it under the category POLITICS, which already existed... but instead it created a new category and now both of them show up exactly the same on the panel that lists all categories.

Only by clicking on each and comparing the url can you see what happened.. one of them is capitalized while the other is not:

https://test.augur.net/#/markets?category=Politics
https://test.augur.net/#/markets?category=politics

Ideally, I think there should be a dropdown menu of categories, so you can pick from existing ones instead of having to enter it in as a text string.  But either way, it should be case insensitive so this kind of thing can't happen.  (The display is already case insensitive, just need to make the rest consistent with that.)

**Comment by bthaile** [comment]
Thanks for the heads up,

This will be fixed as soon as the PRs are merged. It ended up being both the UI and augur-node use case sensitive category searches. 

[https://github.com/AugurProject/augur-node/pull/374](https://github.com/AugurProject/augur-node/pull/374)

**Comment by justinbarry** [comment]
Merged. Thank you for the issue report!
