### ISSUE TITLE
Desktop Trading Page: Price History Graph

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1597]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/be1294d4-7d89-483b-ab16-962bf17d0cf1)

- [x]  Check colour value of pink. Build looks lighter
- [ ]  ~~Add vertical lines~~
- [x]  Remove circles on line
- [x]  Change 'ETH' on y axis to 10pt
- [x]  Make Y axis numbers 10pt
- [x]  Make x axis number 9pt
- [ ]  ~~Can we remove the diagonal x axis labels, it breaks the flow of the page. If tight for space I suggest stacking the number on top of the month like so. But only when extra space is required~~
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/c0e91624-6d46-4ebe-880b-e71b2c6c5f2e)

- [x]  markers shouldn't overlap because of opacity
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/6200a2d3-6234-4177-aa5f-d9bd24fb0917)

- [x] spacing here
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/6fe8bf97-f0c8-4aba-9aeb-c5fa8bb2a1fc)

- [ ]  Match hover states. Can remain the white outline but overlay should line up with the numbers below
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e0da2036-2128-4982-9d09-517f06bbfb7b)

- [x]  Horizontal lines and X axis should go all the way to the edge
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/298337c3-3fac-4175-afbb-adda012b16e5)

- [x]  Y axis markers should sit 2px below lines, not above. Not need to show the value at 0
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/5b830188-4cf9-4ae0-b26e-2de082624bc1)

- [x]  remove border on left and bottom around graph component (dark area)
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e0a3d39d-a3d0-49b6-b5df-85ba62764235)

- [x]  Check padding
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/6fb78945-e0f0-4b0d-9b8a-de55a62e98bd)

- [x] Update the right hand side of the graph to match design. There should be 8px spacing between graph line and y axis labels.
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/a6c856bf-0210-466c-8270-f58b325fc0a7)

- [x] Remove the draw in feature or if it needs to stay only have it draw in the first time the page loads, not every time you switch between graphs

**Comment by Chwy5** [comment]
Weekly displayed bucket is displaying daily pts represented by dots...needs to be weekly bucket

**Comment by pgebheim** [comment]
@JohnDanz This is done now yeah?
