### ISSUE TITLE
Closing a short position on scalar markets returning wrong value

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1598]
Scalar market with min 0/ max 10

Short 3 shares at avg price of 5 (Sold 1 at 4, 1 at 5 and 1 at 6).
I go to cover 1 share at 6 (on my 4th trade) s/b a losing trade ( i should be losing 1 eth + est fee)
Order ticket in closing positions shows Buying back 1 share @6, est fee 0.001 but profit of 3.499

**Comment by bthaile** [comment]
figured out issue, incorrect calculation for normalizing price for scalar, wasn't noticeable for yesNo or categoricals since it was dividing by max - min which is 1.

**Comment by Chwy5** [comment]
looks better - closing
