### ISSUE TITLE
Disable Review button after confirming an order

### ISSUE THREAD

**Issue by reductionista** [AugurProject/augur#1598]
When submitting a Buy or Sell order in the market module, there's a bug which makes it very easy for the user to accidentally submit the same order more than once (I did this myself the first time, or maybe even the first couple times, I tried it out--have been meaning to report this for months).

The bug is that after you click Review and then Confirm, it briefly flashes a message saying the order has been submitted, but then goes back to a page where the Review button is still active.  If you click on that, then it goes to the next page where the Confirm button is also still active.  The first couple times I saw this, I assumed it meant that something had gone wrong and the order hadn't been submitted, since usually on most web interfaces once you confirm an order or transaction it no longer asks you to confirm again--at least one of those buttons (Review or Confirm) should be grayed out.

Interestingly, if you click on Review, then Confirm, then Review again, then Back (without hitting Confirm the second time)... _then_ the Review button will become disabled.  So my guess is that after the order is submitted the Review button is attempted to be disabled, but it fails to take effect until the frame is reloaded.  If that's the case, I think the fix would just involve making sure the button gets automatically re-rendered as soon as the order is submitted, instead of waiting for a frame reload. (Or perhaps it's easier to just force the whole frame to reload, I have no idea how this UI is implemented, have only played around with it as a user.)

**Comment by JohnDanz** [comment]
https://github.com/AugurProject/augur/pull/1801 PR for the fix is here, once reviewed/tested/merged it should be fixed.

**Comment by JohnDanz** [comment]
Update: this should be no longer an issue in Master :)
