### ISSUE TITLE
scrolling within a scrollable Modal 

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1601]
this is how design wants scrolling to work on modals: 

<img width="661" alt="Screen Shot 2019-04-05 at 8 53 14 AM" src="https://user-images.githubusercontent.com/6775839/55640409-5f6e3800-5780-11e9-9735-420efb370106.png">

**Comment by Chwy5** [comment]
approved

**Comment by cillianhunter0** [comment]
I'm seeing an issue on one of the notification modals.

The scroll view doesn't reach the lines that separate the body from the header of the modal, and the footer of the modal. See: 

![scrolling.gif](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/9dddab3a-4d53-4255-9536-0ce96164ce1f)

**Comment by Chwy5** [comment]
still seeing the chrome/windows old scroll bars in the claim stake and fees modal and open orders in resolved markets...

see screenshot

![4-15clm.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/e5cf6f2e-c74e-4026-8ca5-a7b539d22bea)

**Comment by Chwy5** [comment]
Change title of ticket - see cillians scrollable issue above

**Comment by cillianhunter0** [comment]
Previous comment was: 
> The scroll view doesn't reach the lines that separate the body from the header of the modal, and the footer of the modal. 

The scroll view now reaches to line that separates the header from the body, but need to get the same thing done for the bottom, so the scroll view reaches the line the separates the footer from the body.

**Comment by cillianhunter0** [comment]
This is fixed on desktop, but still seeing issues on tablet breakpoint and smaller. 

![scroll.gif](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/e61f2943-b0ba-4267-ac13-91e7b1f22edb)

**Comment by matt-bullock** [comment]
Can someone test on a mobile device who has enough stake and fees to claim on their mobile account

**Comment by andrewdamelio** [comment]
@matt-bullock i can test this -- will report back

**Comment by andrewdamelio** [comment]
@matt-bullock looks good to me now, footer and header seem to be scrolling fine.

I noticed the buttons are a little squished though, not sure if this is a new issue or something we are aware of.

**Comment by Chwy5** [comment]
@andrewdamelio whats going on with the close and claim all button in that screenshot?

**Comment by andrewdamelio** [comment]
@Chwy5 mentioned in above comment ```I noticed the buttons are a little squished though, not sure if this is a new issue or something we are aware of.```

![image](https://user-images.githubusercontent.com/1683736/57153588-b168a480-6da4-11e9-9379-0496d2f1c72b.png)

**Comment by matt-bullock** [comment]
Thanks for checking this on mobile. So the scroll seems fine but we still have the gap here that shouldn't be

![image](https://user-images.githubusercontent.com/39496225/57146540-d7eb0780-6dc5-11e9-950d-6fe7ef35cc19.png)

@andrewdamelio any idea why the buttons are doing that? They look ok to me when testing on decore but can't test on coinbase wallet

**Comment by cillianhunter0** [comment]
Seeing an issues with Open orders in resolved market, it's scrolling the table not the modal content view (on desktop and mobile)

mobile for example:
![scrolling modal mobile.gif](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/5a89942c-4b98-437c-ba9f-c986b9504dc6).

**Comment by cillianhunter0** [comment]
Also still seeing issue with the top of the scroll view not reaching the header on mobile, stake and fees example: 
[Uploading... modal scrolling3.gif ]

**Comment by pgebheim** [comment]
@JohnDanz Is this still an issue? @bthaile?
