### ISSUE TITLE
Add in token exchange widgets

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1606]
On dev.augur.net deposit there is two ways users can get REP by exchanging ETH. 

Joey mentions here:

this is missing a lot of data
go to the current augur site now and account page and deposit to see how it looks now
copy could be improved on that version

but this one has no deposit info

also on the wyre link it should go to https://dash.sendwyre.com/sign-up not just sendwyre.com

In. https://github.com/AugurProject/augur/issues/1343#issuecomment-480437368

Tix

**Comment by bthaile** [comment]
@Chwy5 this needs to get worked as part of release 1.13. If I’m understanding @joeykrug

**Comment by Chwy5** [comment]
@cillianhunter0 needs design...we can add to Transactions box in AS

**Comment by Chwy5** [comment]
we will need both of these

![4-6](https://user-images.githubusercontent.com/41301809/55669568-e84fa700-5846-11e9-892d-1c437a29a97f.jpg)

**Comment by cillianhunter0** [comment]
Updated "receive funds" modal to include 'how to' content and links to buy ETH/REP. 

@bthaile are there any help articles on the topic of buying ETH/REP hosted on Augur anywhere? If not, would adding a page to augur.net similar to the FAQ be the easiest option? We can push the 'help' link and content to v1.14 

Figma: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7699%3A1012

**Comment by JohnDanz** [comment]
Didn't add the scrolling element or the how to because it doesn't exist, but made these updates in a PR will add the scrolling in another issue and will update the text to add how to when we make docs for it.

**Comment by Chwy5** [comment]
I dont see this added

**Comment by bthaile** [comment]
Only mainnet shows the token swap/buying REP. Those aren’t available on testnets.

**Comment by Chwy5** [comment]
@tom...plz verify

**Comment by bthaile** [comment]
tested redesign dev branch against mainnet. @Chwy5 @cillianhunter0 I think this is good to go.

![image](https://user-images.githubusercontent.com/3970376/56155896-99f68280-5f81-11e9-93f3-796975cd8c26.png)

**Comment by cillianhunter0** [comment]
looks good
