### ISSUE TITLE
Add Orphaned Orders modal

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1612]
When user clicks on view orders in notifications - the orphaned orders modal should pop up (currently doesnt do that

**Comment by Chwy5** [comment]
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7110%3A283094

**Comment by Chwy5** [comment]
Need to add for 1.14

**Comment by bthaile** [comment]
no longer needed, closing
