### ISSUE TITLE
Change of secondary button color

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1615]
We are changing the all caps text button color, from white to blue. 

It's currently blending in with the surrounding text too much and as a result it's not easy to spot the actions on any given page. 

The updated color is: #09CFE1

Examples: 
'Clear' button in the order ticket
![Screenshot 2019-04-09 at 11.42.26.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/ef26e161-4fc2-4188-a2b9-459a656519c2)

Actions in modals such as 'SUBMIT' OR 'CLAIM' 
![Screenshot 2019-04-09 at 11.44.01.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/921a65fd-d6ae-4161-937c-a321033a79c1)

Notification actions
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/38628b28-ea83-48fe-9778-baa7a3421454)

**Comment by cillianhunter0** [comment]
@andrewdamelio I'm seeing a different hover state for these buttons, are these updated from our chat yesterday?

**Comment by andrewdamelio** [comment]
@cillianhunter0 correct, I only updated the color. I thought this issue was only to address the color.

Should we update this issue to also aligned all the states (hover, focused, disabled, etc) for all the text buttons mentioned above (i notice a lot of them are missing these)?

**Comment by cillianhunter0** [comment]
Correct, this ticket was only to change the color. Shall we create a new ticket for the other changes we've been discussing? @andrewdamelio

**Comment by andrewdamelio** [comment]
@cillianhunter0 Yes we should -- assuming a v1.14 task?

**Comment by cillianhunter0** [comment]
ok, i'll create a separate ticket for button updates.
