### ISSUE TITLE
Update collapsed header state on Desktop Trading Page

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1616]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/8239622e-4694-4474-9a50-7f05b0650cbc)

All collapsed states can be found next to the open states in the Trading Page Design 
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/1723aa8a-e282-4993-b46b-ad52f73bbfc8)

Animation should be smooth, quick with subtle ease. Message me if you have questions regarding the transition.

**Comment by andrewdamelio** [comment]
I believe @matt-bullock has already reviewed this

**Comment by matt-bullock** [comment]
Waiting for the update to be pushed so I can test

**Comment by matt-bullock** [comment]
Looks good. One request is if the rotation of the arrow could finish at the same time the open/close transition finishes. When closing the header the arrow is still moving after the header closed which is a little distracting.

**Comment by Chwy5** [comment]
pushing this last part to 1.14
