### ISSUE TITLE
copy market ID and copy market creator ID

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1617]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e128213d-a987-45f7-ab2a-5e6db42ebfd2)

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/1dfd76bd-8ce0-470d-9f7f-df5fda17bc2c)

Location:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e6033e51-9ad1-4d20-8515-664f3ac0f435)

**Comment by matt-bullock** [comment]
@bthaile can you add the exact details that will be copied in these 2 instances.

**Comment by bthaile** [comment]
we can copy the marketId which is a string like "0x10e8fddabe2c5be2d1297459c7976a82b51ffe35" 
the market creator address is a similar string.

users can use these strings to paste into 3rd party sites for analysis.

**Comment by Chwy5** [comment]
looks good - closing

**Comment by matt-bullock** [comment]
Can you create a larger hit area for this on mobile. I'm struggling to press it. Should have an area of 32px x32px
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/d8bd8891-73a5-409d-8388-7b68c3c12fef)

**Comment by matt-bullock** [comment]
fixed. Closing
