### ISSUE TITLE
creating a new market issue

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#162]
When making a new market --- it never appears as pending, and eventually it fails in console with createMarket failed: Object {error: BigNumber, message: "bad input or parent doesn't exist"}

**Comment by tinybike** [comment]
Just tried create market on development.augur.divshot.io and it went through the whole createEvent -> createMarket -> market created successfully! thing just fine.  The new market isn't being picked up immediately by marketeer for some reason -- possibly it isn't hitting the contracts filter? -- but it's definitely there.  (I've previously experienced this bug, but it seems it was solved unintentionally, through other fixes...?  Not sure, but closing this for now.)

Oddly, while pending, the new market shows up as the first market on the last page of the UI.  When it is successfully created, it then shows up as the last market on the last page of the UI.  Creating a separate issue for this.

**Comment by tinybike** [comment]
This error is back, not sure why.

**Comment by tinybike** [comment]
Fixed (...for real this time!) in 4645ee0b77ad57bb2edbdbf184f431fa8c863de8.
