### ISSUE TITLE
Transaction feedback component / pattern 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1622]
Wherever there is a transaction that is triggered from a secondary button, we will use this pattern to give users immediate feedback on the interaction. 

Rules: 
- When a button is triggered, it becomes disabled and the 'processing' tag is shown 
- If user hovers (desktop) or taps (mobile) the processing tag, tooltip is displayed
- When transaction is processed confirmed tag appears, Two variations of this:
   - IF transaction is triggered from a modal, the ‘confirmed’ tag doesn’t disappear
   - IF transaction is trigged anywhere else, i.e. on a page, ‘confirmed’ tag appears for 3 seconds and then disappears
- 'Processing' tag is removed after 3 confirmations (cc: @Chwy5 )

Figma: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7776%3A4212

**Comment by bthaile** [comment]
design is coming up with different approach for V2, there is existing tix for this effort, closing
