### ISSUE TITLE
Claim stake and fees 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1623]
Figma: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7365%3A251125

Notes: 
- IF multiple markets THEN show totals at the bottom 
- IF user claims fees from an individual market, THEN subtract these from the totals at the bottom and remove this market from the list that 'claim all' affects  
- IF user clicks 'claim all' THEN modal will close and user receives a notification of transaction processing 

For details on the transaction feedback component, see: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7776%3A4212

**Comment by bthaile** [comment]
@phoebemirman are all the above already covered?

**Comment by phoebemirman** [comment]
i just have to hide the totals when there is just one market, add the tooltip, switch the word pending to processing, and fix a bug for the totals when eth fees are zero.

**Comment by Chwy5** [comment]
@cillianhunter0 plz rvw and close if complete

**Comment by cillianhunter0** [comment]
>IF user claims fees from an individual market, THEN subtract these from the totals at the bottom and remove this market from the list that 'claim all' affects

When I claim an individual markets stake/fees, and the tx is confirmed in the dialog, that markets figures are not subtracted from the total figures at the bottom.

**Comment by cillianhunter0** [comment]
Issue with subtraction from totals is fixed for me. 

There's a new issue at the totals, we are displaying a double crypto abbreviation after the figures for 'total rep' and 'total fees' 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/cc7dfd08-1784-4cac-9cfe-f0f78c3ec313)
