### ISSUE TITLE
Mobile Menu Design update

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1624]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/882aa713-fdf6-41fd-b2ec-43c3e262595a)

Prototype - see for transition behaviour 
https://www.figma.com/proto/JsliY6ONwB3N5aoRm0UTGzHj/Mobile-Trading-Page-Prototype?node-id=104%3A23673&viewport=895%2C429%2C1&scaling=min-zoom

Design can be found here:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/09f62ef6-5f76-4492-b947-18563cc9efd6)

Overlay background: #000 25% opacity

Transition: Ease In and Out 200ms

**Comment by phoebemirman** [comment]
what does the sub nav look like?

<img width="431" alt="Screen Shot 2019-04-15 at 12 32 47 PM" src="https://user-images.githubusercontent.com/6775839/56159870-9d3a4000-5f7a-11e9-8bef-852a88843baf.png">

**Comment by matt-bullock** [comment]
@cillianhunter0 is working on the sub nav

**Comment by phoebemirman** [comment]
reporting has one as well <img width="464" alt="Screen Shot 2019-04-16 at 1 03 54 PM" src="https://user-images.githubusercontent.com/6775839/56240423-5c106180-6048-11e9-8ce4-3e06ddaf8fca.png">

**Comment by cillianhunter0** [comment]
@phoebemirman I created a separate ticket for the sub nav here: 
https://app.zenhub.com/workspaces/augur-5bfed3424b5806bc2bf8d173/issues/augurproject/augur/1691

**Comment by cillianhunter0** [comment]
For the reporting page, we're going to use the same tabbed navigation we're using on account summary. See: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=8005%3A0

**Comment by Chwy5** [comment]
Ticket mention above #1691 is to be worked for 1.13....

This ticket is 1.14

**Comment by andrewdamelio** [comment]
closing. This was completed with the v2 redesign of the mobile SideNav.
