### ISSUE TITLE
Add messge to the order ticket to notify user if they are going to consume their own order on the book

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1626]
Similar to how we display message for gas exceeds order value.... @matt-bullock can u design really quick

**Comment by Chwy5** [comment]
We need wording for this....something like...

You are about to trade with your own existing order.

**Comment by cillianhunter0** [comment]
We'll use the same component as the "gas higher than order" warning message. 

With the following copy: 
- CONSUMING OWN ORDER
- You are trading against one of your existing orders
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/562dc46d-a4f3-48b7-b18a-417b76357410)

**Comment by Chwy5** [comment]
@bthaile the message needs to match the design above

See picture above: 

(in red)(!) Consuming Own Order
You are trading against one of your existing orders

**Comment by bthaile** [comment]
![image](https://user-images.githubusercontent.com/3970376/56004549-95844e00-5c91-11e9-8f47-26fe06ea230c.png)


this is what we have.

**Comment by Chwy5** [comment]
Looks good - closing

**Comment by matt-bullock** [comment]
Colours look different to Cillian's Design. Check we are using the coral and not sell orange.
Background colour looks murky. Not sure if this is a colour rendering issue but can you check it's the correct colour

**Comment by bthaile** [comment]
![image](https://user-images.githubusercontent.com/3970376/61402698-4c97f300-a899-11e9-838a-77141bc2a51c.png)

it's been updated. closing
