### ISSUE TITLE
Active market, filter out closed positions.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1630]
![Screen Shot 2019-04-10 at 2.51.33 PM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/1e894fe6-ae39-4b53-8ce3-a83698a5fe11)

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/accfb740-e0fa-4582-9d16-58d3e10e64bf)

- [x] need to filter out markets in open reporting state where position has been closed. 
- [x] show all markets the user has a open position, even if the market is in reporting or resolved.

**Comment by Chwy5** [comment]
looks to be working correctly - closing

**Comment by Chwy5** [comment]
confirmed - filtering out closed positions
