### ISSUE TITLE
Portfolio > open orders > cancel transaction > pending tag 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1632]
The pending tag partially covers the 'type' value at certain resolutions. Could we place the pending tag directly over the 'type' value

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/274f75af-2af7-4b87-8b13-ae667d3663a0)

**Comment by phoebemirman** [comment]
there is a conflicting ticket for this already https://github.com/AugurProject/augur/issues/1591
