### ISSUE TITLE
Tooltip hover fix on mobile

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1633]
Problem: it's getting cut off because the tooltip is centred
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/a4893f46-0775-4417-967f-29dbdffc3b55)

Fix: Arrow remains fixed to (i) but the rectangle and content moves depending on the constraints. In this case you would probably want to allow for 16px padding from the left of the screen.
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/17a438f1-e015-4258-a5fd-93b4d8866b87)

**Comment by Chwy5** [comment]
looks better - closing
