### ISSUE TITLE
[24h%] outcome_value_timeseries can't tell which trade came first if trades are in same block

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1634]
tested unrealized price changes and closing positions and the 24 hr % doesnt update (just shows 0.00%) but specific to categorical markets....(this info does update on the portfolio pg though)

**Comment by ryanberckmans** [comment]
Fixed by https://github.com/AugurProject/augur-node/pull/843

**Comment by ryanberckmans** [comment]
Reopening this for Chwy to close after he's verified the fix

**Comment by Chwy5** [comment]
Binary markets the math is correct...but takes a refresh in order to update (i'll make separate ticket for that)....

Scalars do NOT update at all currently, even after multiple refresh attempts...

Min/Max is 1 - 2....
Trade 1)  buying 1 at 1.45
Trade 2)  buying 1 at 1.501

My 24hr % change shows -65.45%
It should be +11.33%

Categorical market....first outcome I traded (opening trade) displays old way....I sold 1 share at .65 (it is showing my 24hr% change as -65%, should be zero since it was the opening trade)

**Comment by ryanberckmans** [comment]
> Scalars do NOT update at all currently, even after multiple refresh attempts...

Will investigate.

> Categorical market....first outcome I traded (opening trade) displays old way....I sold 1 share at .65 (it is showing my 24hr% change as -65%, should be zero since it was the opening trade)

Suspect this will be fixed by our upcoming redesign to use oldestPricePaidInLast24hForOpenPosition if you opened/further opened position in last 24 hours (tracked in #1666).

-65% seems "right" for current code: with no price history it will default to 0 for lastPrice, so we're going from `0 -> 0.65` lastPrice which gives short price `1 -> 0.35` which is where the 65% loss comes from. Again should be fixed with #1666 at which point we'll see 0% change.

**Comment by bthaile** [comment]
Put in a small delay to avoid a race condition with augur-node

**Comment by ryanberckmans** [comment]
24h% should be working and updating in all cases now. @Chwy5 how does it look? If it's good then we can close this

**Comment by ryanberckmans** [comment]
Worked with chwy to isolate problem:

The DB table `outcome_value_timeseries` uses `timestamp` as the sort column, but trades in the same block may have same timestamp, preventing clients of `outcome_value_timeseries` from determining correct trade order.

Proposed solution

1. add columns blockNumber, logIndex to outcome_value_timeseries
2. update clients of outcome_value_timeseries to secondarily sort by blockNumber, logIndex. The only client is queryOutcomeValueTimeseries which will now sort by (timestamp desc, blockNumber desc, logIndex desc)

Working on solution

**Comment by ryanberckmans** [comment]
Reopening for design review

**Comment by ryanberckmans** [comment]
Fix is merged to master and will be on try.augur.net in about 20 minutes

**Comment by bthaile** [comment]
@Chwy5 kicked this to `design review` for you to test.

**Comment by Chwy5** [comment]
Looks good in testing - closing
