### ISSUE TITLE
Account summary quad boxes jumps

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1635]
![2019-04-11 09 54 00](https://user-images.githubusercontent.com/3970376/55968300-5fb77900-5c41-11e9-93a6-d622da6a19f4.gif)

with `My Active Markets` partially filled when the user expands other quad boxes jump.

**Comment by phoebemirman** [comment]
that shouldn't be an issue anymore when the account layout is updated https://github.com/AugurProject/augur/issues/1521

**Comment by bthaile** [comment]
ok, I put the other tix is blocking this one. when #1521 is fixed move this tix along with it.

**Comment by Chwy5** [comment]
looks better - closing
