### ISSUE TITLE
Move My Reporting Section from Portfolio to Reporting Section

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1636]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/dc73fb94-c854-485a-adf9-a37b626858f1)

1 px Divide : #0F0A19. 12px spacing top and bottom

- [ ] Move `My Reporting` from portfolio to reporting.
- [ ] Remove the top section of My reporting, the user now has a modal for claiming stake and fees.
- [ ] Remove the side-out/origami menu for Portfolio

**Comment by Chwy5** [comment]
closing
