### ISSUE TITLE
Profit and loss chart price range

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1638]
![image](https://user-images.githubusercontent.com/3970376/55972155-98a71c00-5c48-11e9-80eb-546a74323dc6.png)

- [x] if high is over 0, then min value used will be 0 and max will the user's max.
- [x] if low is below 0 and the max value is 0 then max is 0 and min is user's min.

![image](https://user-images.githubusercontent.com/3970376/55972367-fd627680-5c48-11e9-9a8e-7e11c7d20371.png)

data looks different.

- [ ] Always show a solid line at zero, if user's PnL crosses or is in view
- [x] if high is above zero, max is price time max
- [x] if low is below zero, min is price time min
- [x] for all time need to start with user's first realized profit trade

**Comment by bthaile** [comment]
issue with second chart is startTime is null so bucketed data comes back all the same.
Need to put in a default startTime. maybe something when Augur was put on mainnet. That will give augur-node a time range and the bucketed data will be correct.

**Comment by JohnDanz** [comment]
Getting a solid line for the 0 ytick is a bit more difficult than I anticipated. I can come up with a hacky solution most likely but we should see if it's really required.
