### ISSUE TITLE
Account summary: responsive designs 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1641]
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/05cc00c0-fb0d-4911-9ec4-6fc63c814195)

Figma: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7833%3A4694
(Zoom out for overview) 

**Notes**

MOBILE
- Mobile (min = 360)
   - Nothing changing here
- Mobile (max = 767) 
   - 24px margins on sides

TABLET
- General note
   - We'll use the mobile header bar between 768-1199px, but retain the content of the pages from desktop
- Tablet (min = 768)
   - Two column layout with 12px margins on sides, with 12px padding between cards 
- Tablet (max = 1199) 
   - Two column layout stretches to fill space, with 24px margins on sides, with 12px padding between cards
   
DESKTOP
- Desktop (min = 1200)
   - 3 column layout
   - Nothing changing from 1440 other than each card/panel is flexi width (40px margins on sides, 12px padding between cards)
   - Cards/panels have same width as tablet (min)
- Desktop (baseline = 1440 - what we've been working at to date)
   - Nothing changing here
- Desktop (max = 2064) using as an example of a large resolution, would we consider this a new breakpoint? (we can come back to this if not trivial) 
   - 40px margins on sides of screen
   - 24px padding between cards 
   - Creating a 4 column layout, with card heights expanding down to reveal their content (if nothing else is below them)

**Comment by cillianhunter0** [comment]
- I'm seeing an issue between 1201px and ~1280px. There isn't enough room for the cards. It's because the side nav is in the build and not in the designs. 
   - I suggest we change the breakpoint from 1200 to 1280 until we remove that side nav in the build. 
- At 1280px I'm also seeing a problem with uneven column widths, see: 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/3c07b808-1f39-494b-8567-90eda53b24de)

**Comment by andrewdamelio** [comment]
**At 1280px I'm also seeing a problem with uneven column widths:**
- Until we remove the side nav, to address the uneven box widths we've decided to adjust the font of the switch label component between 1281px and 1420px.
