### ISSUE TITLE
Add User's REP balance into the market creation, Reporting sections, and disputing form

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1643]
Market Creation. Across all steps
Page: Market Creation 4
https://www.figma.com/file/csVtbWhGCAYe3nVe2LI1UEPM/Timezone-issue?node-id=181%3A965
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/2ed75d74-b758-4caa-8796-cd3351ec37d6)

Use the same component across the following sections

Reporting: Dispute
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/5fef0731-85bd-4ed4-aa9f-3336d79b8565)
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e0ab614e-f086-4ce2-aa1e-dc62d4591e94)

Reporting: Markets
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/2ca4db6a-f3a2-4fe7-9fe6-2b0630dbedb2)

Reporting: Resolved
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/baf2c7b7-4a57-4459-8152-c0c823893143)

Dispute Form
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/c8aa6dff-3f5c-4c74-9e56-9323d428d41c)

Report Form
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/23fb7c60-e7bb-41f9-97ee-93632550809a)

**Comment by bthaile** [comment]
Notice that if the market is `Open Reporting` and the user isn't the Designated Reporter no need to show the user's REP balance.

**Comment by Chwy5** [comment]
@matt-bullock it's added...plz rvw make sure it matches design and close

**Comment by matt-bullock** [comment]
Can you align it to the right of that section on market creation:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/4f07eeba-6d7c-47ea-9ddd-73456545fa27)
