### ISSUE TITLE
Remove interaction prompt (mouse change to hand pointer) when there is no interaction 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1644]
Seen this in a few places and it's confusing for users

![Kapture 2019-04-11 at 20.34.40.gif](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/0be9c06d-ffff-43ae-97d7-d834041fe40d)

**Comment by JohnDanz** [comment]
I'm just going to drop the pointer all together on the hover labels, the more i think about it, even if it is hoverable the pointer doesn't need to be shown because it's not actually interactable, it's just hoverable.

**Comment by matt-bullock** [comment]
Good call. Let me know when it's done and I'll get this closed
