### ISSUE TITLE
RedeemStake estimate gas error message when user logs in

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1648]
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/afdb01ce-dc21-4097-b956-fb27090b4c12)

After talking to Alex, the issue is if there are too many crowdSourcers / feeWindows the estimate gas call will run out of gas and fail. Need to break up the call, this will also need to be done when the user actually calls redeemStake

@Chwy5 can you see if you are getting this error after redeeming reporting stake and fees? If not then we can probably move this to v1.14

**Comment by Chwy5** [comment]
tested- i didnt get this message,

but doesnt look like me eth and rep balances updated either

**Comment by bthaile** [comment]
@Chwy5 I think this one is important. I put it in v1.13, I would like to get your approval.

**Comment by Chwy5** [comment]
Approved
