### ISSUE TITLE
24hr% data is incorrect

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1651]
My active markets 24 hr % data is not showing correct....see screenshot

All non Categorical markets are showing the same value....you can see in the expanded state of both scalar and binary markets showing a different value for the outcome and the value next to the market...in those cases the numbers should always be the same

See screenshot

![4-12-24hr.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/497e5a7b-1c75-44ce-bbd5-1b11b459bb89)

**Comment by ryanberckmans** [comment]
Fixed. In "My Active Markets" the per-outcome and per-market data should now be correct. The "24HR" portfolio value at top is not yet wired in.
