### ISSUE TITLE
Current Value displaying incorrect data

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1652]
When Current Valaue toggle is pressed in positions section of portfolio....its displaying the wrong value on 59 of 61 of my markets.....

see screenshot (59 of them all show the same current value)

![4-12cv.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/709ff71a-3a89-494a-a756-bc0410ddf02f)

**Comment by ryanberckmans** [comment]
Fixed by https://github.com/AugurProject/augur-node/pull/843
