### ISSUE TITLE
Make quantity button clickable

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1657]
On trading pg in positions...we should make the quantity button clickable....so the quantity fileters into the order ticket...

If a user is Long an outcome...Sell shares should be highlighted and the quantity only fills into the order ticket

If a user is short an outcome and they click on their quantity, buy shares should be highlighted and the quantity only fills into the order ticket

**Comment by andrewdamelio** [comment]
Doable but will take more time, should move to another EPIC if its something we still want.

@pgebheim

**Comment by Chwy5** [comment]
This is a feature which we will need
