### ISSUE TITLE
New/pending markets on last page

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#166]
While it is pending, a new market shows up as the first market on the last page of the UI.  When it is successfully created, it then shows up as the last market on the last page of the UI.  Not sure if this is a bug, but I thought it was very nice to display the pending market on the first page.

**Comment by scottzer0** [comment]
i'm now storing pending markets separately since they really want to be treated different until assimilated.

**Comment by tinybike** [comment]
Storing them separately is fine, but I think it's much nicer for the user if the pending markets appear on the first page (or wherever the market will ultimately be displayed once it is created).

**Comment by tinybike** [comment]
Fixed pending market creation / removal in 04c7f54d4628b1b4dad4db445fedf001cbaeb4a3.  New markets still appear on the last page, which seems ok to me; if anyone has a strong preference otherwise, feel free to make an issue!
