### ISSUE TITLE
Duplicate transactions showing in Transaction History modal

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#1662]
Steps to repro:
1. Using account 0x913dA4198E6bE1D5f5E4a40D0667f70C0B5430Eb on Rinkeby, go to the Account page and click View Transactions. Select the action "Claim Trading Proceeds". Count the number of txs that show up.
2. Select the action "Dispute".
3. Select the action "Claim Trading Proceeds" again. Note that the number of txs has increased. This is because there are duplicate txs getting shown, and the number of them keeps increasing as you switch from Claim Trading Proceeds to another action and back.

**Comment by Chwy5** [comment]
looks better - closing
