### ISSUE TITLE
positions not showing in portfolio or market trading page.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1668]
confirming that user's position isn't showing up on both portfolio and market trading page.

users do have positions they can trade using their shares.

Specific versions of the UI the users are using. They are seeing the correct positions using augur-app. 

Maybe augur.casino has the wrong version of augur-node that has the new synthetic positions.  

Will get more information from the users, are the positions they aren't seeing the LONG positions on categorical markets? 

categorical markets are the issue.
both long and shorts are not showing up.

**Comment by Chwy5** [comment]
works fine on dev...just slow lag time, but positions appear

**Comment by Chwy5** [comment]
Categorical markets on dev when short selling do not show the synthetic longs in all other outcomes...only shows the actual net short position of the outcome sold
