### ISSUE TITLE
Mobile header doesn't match up with design

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1669]
Build on left, design on right

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/4eed18c4-88da-4af1-b3f8-5675ec3a000b)

**Comment by bthaile** [comment]
@cillianhunter0 is that for mobile or desktop?

**Comment by cillianhunter0** [comment]
Mobile

**Comment by cillianhunter0** [comment]
Looks good, just one tweak. When we increase the width the data should align right, like: 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/39bada3f-9ff4-4ffa-927a-05b1146a8fc0)
