### ISSUE TITLE
Portfolio - mobile - dropdown menu 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1672]
The height of the rows in the sort by dropdown should be the same height as the input itself. Same applies to all dropdowns across mobile. 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/63005305-d100-43f9-b2ce-65bac815d5d3)

**Comment by JohnDanz** [comment]
This is probably fixed now, I worked a similar issue before and ended up fixing an inconsistency with the common dropdown component, @phoebemirman since this is assigned to you, can you just confirm that it's fixed and close this if it is?

**Comment by JohnDanz** [comment]
It was indeed fixed in a previous update, here's a screenshot:
<img width="557" alt="Screen Shot 2019-08-08 at 10 49 38 AM" src="https://user-images.githubusercontent.com/10524630/62713167-44c7fc00-b9ca-11e9-8145-372873622bad.png">
