### ISSUE TITLE
Portfolio - mobile - cancelling an open order 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1674]
When I cancel an open order, the 'cancel' button doesn't update to its disabled state. 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/31ac607d-7dcf-4562-b914-ea48f0c2cd63)

**Comment by cillianhunter0** [comment]
I'm seeing the cancel button being hidden rather than changing to its disabled state.

**Comment by Chwy5** [comment]
looks better - closing
