### ISSUE TITLE
Portfolio - mobile - filled orders - match padding and alignment of labels

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1677]
Match padding and alignment of labels 

build on left, design on right 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/bf663ac2-cceb-4859-bc57-90f62d0f1df4)

**Comment by cillianhunter0** [comment]
Red lines show where labels and values below are not aligned
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/01ec4680-f4d4-4ca0-8ac5-93f6d1bf2784)

**Comment by bthaile** [comment]
@Chwy5 I think this one is polish and can be pushed off to v1.14

**Comment by JohnDanz** [comment]
this looks to be fixed:
<img width="587" alt="Screen Shot 2019-08-08 at 10 48 13 AM" src="https://user-images.githubusercontent.com/10524630/62713039-0e8a7c80-b9ca-11e9-8fcd-ad4c09d657cf.png">
