### ISSUE TITLE
Portfolio - my created markets - timer component

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1679]
Not using "timer" component

Build on left, design on right 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/0db03c78-998c-43ee-a2fc-96defa4926f1)

**Comment by andrewdamelio** [comment]
@bthaile new timing got pushed to v.14 https://github.com/AugurProject/augur/issues/1488 -- going to update release info

**Comment by cillianhunter0** [comment]
Clarification note: when doing this ticket, it is the timer component with right alignment.
