### ISSUE TITLE
Timezone updates carry over for market creation and reporting

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1686]
We need to carry over the updates made to market creation and reporting from v1 regarding timezone issues.

@cillianhunter0 plz comment on colors needed

**Comment by cillianhunter0** [comment]
Only two color changes: 

- Divider lines: #443B59
- Yellow info box background: #FBE9A6

(Mocks below for color change reference only)

Market creation step 1+3: 
https://www.figma.com/file/csVtbWhGCAYe3nVe2LI1UEPM/Timezone-issue?node-id=203%3A1487

Reporting: 
https://www.figma.com/file/csVtbWhGCAYe3nVe2LI1UEPM/Timezone-issue?node-id=203%3A2522

**Comment by bthaile** [comment]
mobile doesn't look very good, but we'll address that in "market creation" redesign.

**Comment by Chwy5** [comment]
Getting error - 

![4-22.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/6216f2a4-837f-45c7-ad85-84fe522fd489)

**Comment by bthaile** [comment]
fixed indirectly by Justin's fix @Chwy5 can you test again?

**Comment by Chwy5** [comment]
fixed and confirmed carry over
