### ISSUE TITLE
24 hr % change needs refresh

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1687]
24hr% change doesnt update after a trade happens....the pg needs to be refreshed

**Comment by bthaile** [comment]
This has been addressed with UI delaying getting user positions when log comes in. This will give augur-node time to process the log. That's our approach to the issue.

this could be a dub tix. https://github.com/AugurProject/augur/issues/1634

@Chwy5 can test this allow with tix above.

**Comment by ryanberckmans** [comment]
Duplicate of #1634
