### ISSUE TITLE
Review market details dialogs for trading page (1.13 release) 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1688]
Both modals can be permanently dismissed if the user checks the checkbox before tapping the "OK" or "Confirm" buttons. 

When a user visits a new market: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7981%3A253720

When a user places a trade on a new market: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7981%3A253701

**Comment by cillianhunter0** [comment]
@andrewdamelio fyi, one piece of copy was added to the second paragraph of the first modal:

"Always make sure that the Market Question, Additional Details, Reporting Start Time, Resolution Source and Outcomes are not in direct conflict with eachother. **Always make sure the market has mutually exclusive outcomes, i.e. only one outcome can occur.**"

**Comment by Chwy5** [comment]
Not seeing these appear while testing...not sure if it hasnt been pushed through yet

**Comment by bthaile** [comment]
@andrewdamelio there is a pop up modal when the user enters a market for the first time.


![image](https://user-images.githubusercontent.com/3970376/56373092-d9151580-61c5-11e9-8c52-f508d42ca6b7.png)

**Comment by Chwy5** [comment]
After clearing out local storage...seeing the modal...

still needs updated messaging

**Comment by Chwy5** [comment]
making a color tweak to message title - will be in another ticket...closing this
