### ISSUE TITLE
firefox quad boxes are off

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1689]
<img width="1479" alt="Screen Shot 2019-04-16 at 10 28 10 AM" src="https://user-images.githubusercontent.com/6775839/56231079-70e1fa80-6032-11e9-8fa4-5f8c471e121e.png">
<img width="515" alt="Screen Shot 2019-04-16 at 10 29 03 AM" src="https://user-images.githubusercontent.com/6775839/56231104-7fc8ad00-6032-11e9-8e8b-af73adc36324.png">\

trade history also has this issue

**Comment by Chwy5** [comment]
approved

**Comment by Chwy5** [comment]
no longer running over into the quads below...closing
