### ISSUE TITLE
Rep faucet broken: "not enough ether" error

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#169]
Created a new account (registered in UI), and successfully used the cash faucet.  The rep faucet doesn't work however.  I get a "not enough ether" error in the console (even though I do have enough ether).

**Comment by tinybike** [comment]
Fixed in e6f19bb6d601ccc3319f324749d4e2c5bed141bc.

**Comment by TheDeafMute** [comment]
Does this issue reference an actual Faucet (like a traditional faucet) for gathering some REP? If so how?
