### ISSUE TITLE
Market list page - mobile - adding in a 'filter list button'

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1691]
Figma: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7981%3A254261

Two changes needed for the market list page on mobile: 
1. Addition of a "Filter topics" button
2. Tweaks to the header area of the page to tidy everything up and include the new filter button

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/cd3305b0-80ee-4c4e-873c-02a1b969b23b)

Tweaks to the header area: 
- H1 header = 24px roboto bold 
   - 24px padding top and bottom
- Search input has been moved to the top
- Sort inputs sit below (16px padding top and bottom) 
- New filter button and "has open orders" checkbox sit below (24px padding bottom) 

Rules for the filter button: 
- When a user navigates to the 'markets' link in the primary navigation on mobile, we will bring them directly to the page, disabling the categories/tags component that appears from the side
- To trigger the categories/tags component, user must first tap the "Filter topics" button at the top of the page 
- This will then show the component, similar to how it works now, with one change
- Change = we have added a header area to the component
   - when user is looking at the categories (image 02 on figma), we display an "X" top right that closes the component
   - when user is looking at the topics (image 03 on figma), we display an "X" top right, and a back arrow top left (brings user back to categories) 
- Show all categories and tags using Title Case (assuming there are no issues with doing this) 

See #1624 for info on how this impacts the reporting sections sub nav (comment section).

**Comment by JohnDanz** [comment]
gonna take a semi substantial refactoring of the state/triggering method of doing the sidebar to make this happen so bumping the points to 8.

**Comment by Chwy5** [comment]
looks good - works on s6 version and higher in testing
