### ISSUE TITLE
Account summary - your overview - P&L graph 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1697]
Notes
- Padding of the copy and numbers at the top should be: 
   - Profit and loss (ETH) (padding below = 8px)
   - Green or red change number (padding below = 4px)
   - P&L number (padding below = 4px) 
- The width of the graph should run to side of the card/panel with 24px margin (same as the content above) 
- ~~There should be three dotted lines on the graph indicating range (currently only two)~~
- Line color at base of graph = #76737E 
- We need to update the colors when it’s negative. See below. (Design oversight, sorry)

Figma for chart in three states: 
- Profit only
- Loss only
- Mix of profit and loss
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=8005%3A6070

Build on left, design on right: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/674125a6-5063-45cf-a01f-1d3a1bf912f1)

**Comment by Chwy5** [comment]
Discussed with Tom....I want Line at Zero solid....

Will only show 1 dotted line for PnL wehn:  
1) high pt only - user only has positive pnl
2) low pt only - user only has negative pnl

if user has both a negative Pnl and positive Pnl, we will show 2 dotted lines 

For 1.14 we can work on adding in 2 dotted lines (high and midpts) if user only has positive pnl
