### ISSUE TITLE
Explain how fees work 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1699]
Problem: 
It's not clear to users: 
- What the fees on Augur are
- Where they go
- How they can benefit from fees

We need to better answer each of these questions so users A) understand how Augur works and are comfortable using it and B) understand and are encourage to benefit from fees through market creation and reporting.

**Comment by pgebheim** [comment]
@joeykrug @Chwy5 @cillianhunter0 -- Is this a critical thing we'll actually tackle anywhere in product?

Seems like a KC thing at most, but perhaps I'm off base.

**Comment by Chwy5** [comment]
We have a tooltip next to the fees on the trading  pg.

Also have something in the help center

**Comment by pgebheim** [comment]
Great glad it's handled.
