### ISSUE TITLE
Make Augur more human

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1700]
Problem: 
Augur today doesn't do a good job of revealing the humans that use the protocol to create, trade and report on markets. As a result it feels like an isolated and unsocial place. Humans are by nature social. In order to create a product people can form a connection with we need to introduce features that address this problem. 

Ideas: 
- Usernames
- User profiles 
- Leaderboard of top traders 
- User success stories "@Joey made 10ETH on his market 'xyz'"
- Chat/market commenting (#503)
- Reactions
- Follow users trading activity

**Comment by pgebheim** [comment]
@cillianhunter0 -- Let's move this into the product ideas list in Wrike since product is working out of that. Specific dev/design tasks for roadmap can go into issues when they're relevant.
