### ISSUE TITLE
Make whole trade button a hitzone on mobile

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1702]
Currently only the text is working as a hit zone

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/773272df-e442-45ce-96ca-605d42d00eaf)

**Comment by andrewdamelio** [comment]
@matt-bullock It appears this is fixed. When you test this next, if its still a problem, ping me.

**Comment by Chwy5** [comment]
works - closing
