### ISSUE TITLE
Copy: Claiming Modals

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1707]
for claim proceeds when a user has multiple markets to be claimed on...if they do it individually and only one is left...the modal still reads   "You have xyz amount to be claimed from multiple markets"

@cillianhunter0 @matt-bullock so when it gets down to this level do we want to just change the wording on the existing notification or do we open a new one...and If a user gets more than 1 market available to claim for again the wording changes back

**Comment by matt-bullock** [comment]
I think the wording should just change. I can't see any issue with this

**Comment by cillianhunter0** [comment]
The design has different copy that works better in that situation 
"You currently have a total of 5.0000 ETH to be claimed in the following markets:"

**Comment by pgebheim** [comment]
This still needs to be updated.

**Comment by pgebheim** [comment]
Closing for #1716
