### ISSUE TITLE
Transaction history mobile - scrolling and views

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1709]
Two scroll views: 
1. The entire body area of the modal (Scrolls vertically)
2. The transaction table (Scrolls horizontally)

For more details and mocks: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=8016%3A626

**Comment by cillianhunter0** [comment]
Chwy also pointed out that on windows the horizontal scroll view has a scroll bar on the top of the view and on the bottom. Can we eliminate the on top?

**Comment by Chwy5** [comment]
None of my transactions are showing up on this page so I cannot confirm the vertical scroll bar, but the horizontal one works better

**Comment by pgebheim** [comment]
Closing this, but leads to a new issue that the transaction history is now broken.
