### ISSUE TITLE
Add market creation time to the reporting/dispute page

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1720]
Request from discord: 
Can the "market creation time" field be added to the reporting/dispute page? It is sometimes needed information based on the market question, and it is presented on the trading page

**Comment by matt-bullock** [comment]
I feel this should go on the reporting and disputing forms along with other necessary information on that market needed when reporting/disputing such as source and additional details

**Comment by Chwy5** [comment]
Needs to be added to the modal for the market specific reporting - will go in both dispute form and reporting form

@matt-bullock need design

**Comment by pgebheim** [comment]
Handled in designs:

![image](https://user-images.githubusercontent.com/86010/64465120-b2e20a80-d0bf-11e9-9b33-aa3f1279ae08.png)
