### ISSUE TITLE
Mobile Trading Page: Price History Chart

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1723]
We need to prioritise spacing issues to better follow the design.

Spacing and sizing guidance have been created for this on the desktop designs. Same should apply for mobile. Please go through and pick out the quicker fixes for now which will push across both desktop and mobile
https://app.zenhub.com/workspaces/augur-5bfed3424b5806bc2bf8d173/issues/augurproject/augur/1597

It will be good to get the build (left) looking more like the design on the right
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/baa0f01d-ec8b-40df-925c-19d6a66a9130)

**Comment by pgebheim** [comment]
Design is done on this.
