### ISSUE TITLE
Transaction feedback - when 'processing' tag is shown 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1725]
A question has come up regarding the feedback we show when a transaction is triggered. 

For example in the claim stake and fees modal.

If I tap 'claim' the processing tag appears *before* the MM window appears. 

Is there a way for it to display *after*, and how would this work with other wallets? 

cc: @Chwy5 @bthaile

**Comment by matt-bullock** [comment]
@phoebemirman made a point about why we originally added it there: sometimes the mm window shows up behind the browser window so it can confuse people. 'Pending' worked better in this instance but it still doesn't tell the user they need to sign the transaction. 

Should the label first be telling the user to sign, then once signed this label turns into 'processing'

This also relates to this ticket https://app.zenhub.com/workspaces/augur-5bfed3424b5806bc2bf8d173/issues/augurproject/augur/1750

**Comment by Chwy5** [comment]
We either need to add a delay and wait until MM is signed to say processing or say something else like pending or pending MM signing, before showing processing....bc we are not processing anything at that moment....and the MM signing box can show up behind the browser window here as well and a user would think a transaction is being processed when nothing is happening

**Comment by bthaile** [comment]
At one time we had the button to run a transaction say ‘sign’ then change to ‘processing’ that would give the user feed back. And tell them the tx hasnt been sent. Something like that.

**Comment by cillianhunter0** [comment]
What about: 

- User taps "Claim" 
- Tag appears "Pending" (tooltip on hover says something like "waiting for you or your wallet to sign for..."
- MM window appears > user signs
- Tag updates to "Processing" 

OR Edge auto signs and it automatically goes from "pending" to "processing"

**Comment by Chwy5** [comment]
is this MM specific - if so I would say "Please sign your MetaMask transaction to proceed" or "you to sign you must sign your MetaMask transaction to proceed"

Rest works

**Comment by bthaile** [comment]
With ledger and trezor we throw up a blocking modal telling the user to sign the tx.

**Comment by pgebheim** [comment]
@bthaile @cillianhunter0 -- Were these states added in the v2 Designs?

**Comment by bthaile** [comment]
Design has the task to incorporate the new functionality in design.

**Comment by pgebheim** [comment]
Ok, I'm gonna close this ticket and this can be handled dev wise in the follow-on engineering epic to #2378
