### ISSUE TITLE
Firefox displays old scrollbars (like chrome)

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1727]
We need to update all firefox scroll bars - like we did in chrome, everywhere a scrollbar is used

**Comment by bthaile** [comment]
@Chwy5 We don't officially support Firefox. How about pushing to v1.14

**Comment by pgebheim** [comment]
Given that FF should work I think we should officially support it on Desktop for v2.

@andrewdamelio @phoebemirman @JohnDanz -- is the CSS for firefox scrollbars particularly nutty?

**Comment by pgebheim** [comment]
(Moving this into Sprint 15 misc)

**Comment by pgebheim** [comment]
Kicking this down the road a couple weeks

**Comment by joeykrug** [comment]
looks the same as chrome now
