### ISSUE TITLE
Scroll bar issue - multiple scrollbars 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1730]
@chwy gets 2 individual scrollbars show up in trade history on windows. Could you supply a screenshot

I get two types of scroll bar:

1 default:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/5b014317-9e2f-4616-81b1-c77e5dc150ba)

1 active:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/8ab7fa68-9da8-46a5-97fd-226e7e46daf7)

Can we discuss a better solution for this

**Comment by Chwy5** [comment]
![4-18sb.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/3a6e1347-03d4-439e-8b24-b753e6943c21)

**Comment by andrewdamelio** [comment]
Closing - this is the default behavior in Chrome. You get that one type of bar when scrolling BUT if you move and hold your mouse inside the SCROLL BAR path Chrome will draw the scroll bar margins.
