### ISSUE TITLE
Mobile Trading Page: Positions showing wrong data

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1732]
This is wrong:
looks to be pulling in the positions from Portfolio
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f27ea657-1b78-4208-9ea7-3946f5bbffc5)

Should be:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/3dba1150-23ed-4a4e-b9e6-806495565841)

**Comment by Chwy5** [comment]
Needs to pull in information for positions in that specific market trading pg....it is currently pulling in information from the portfolio pg which contains different information.

**Comment by matt-bullock** [comment]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/84133a64-3b38-4553-9a7f-1b7ff63d8b28)

Appears to be fixed. A couple of tweaks:

Can the 'TYPE' label line up to the left with outcome and type - 16px from left.

@Chwy5 With Unrealized P/L can this follow the same rules with hiding the full decimal value and revealing on hover? Showing 9 decimal places won't fit on mobile as can be seen above

**Comment by Chwy5** [comment]
yes

**Comment by bthaile** [comment]
@matt-bullock and @Chwy5  If this tix is fixed then close it. If there are addition changes create a different tix. 

by sending us back this tix you are saying the developer failed in addressing the issue.

**Comment by Chwy5** [comment]
Correct data - clsong this ticket  @matt-bullock plz create a new ticket for "Type"
