### ISSUE TITLE
Mobile Trading Page: Mobile Keyboard shouldn't cover order ticket inputs

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1736]
Works great when using Decore Wallet and moves the order ticket up but in Coinbase Wallet this behaviour isn't working.

Note: We need to test this in other mobile wallets

**Comment by bthaile** [comment]
@JohnDanz can we address this?

**Comment by JohnDanz** [comment]
I'm actually seeing the keyboard move the view like we would expect. you can still scroll once the keyboard is up but that's always the behavior as far as i can tell. I don't see it covering any of the inputs however unless i force it to.

**Comment by bthaile** [comment]
it's prob phone dependent. mine the order form is covered up but I can just scroll to see more of the phone. I think we are good on this, users won't get confused.

![IMG_3465](https://user-images.githubusercontent.com/3970376/56511086-522baa00-64f1-11e9-90bd-de71623befd6.jpg)

**Comment by JohnDanz** [comment]
See when i clicked it, and it pushes the whole screen -- and when i explicitly started the input at the very bottom of my phone view it moved it to the right spot. - tested on an iphone Xs

**Comment by bthaile** [comment]
@Chwy5 I don't think this is an issue and user expects the behaviors described above. Ether the content gets pushed up or the user can scroll the content. Plus I don't see how we could address the keyboard moving or not moving the content.

recommend closing

**Comment by Chwy5** [comment]
closing
