### ISSUE TITLE
Output junit files for CI to consume

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#1739]
We are already doing this for jest tests at the monorepo.

**Comment by justinbarry** [comment]
This is just a nice to have.

**Comment by robert-e-davidson3** [comment]
This can be accomplished by running all jest-compatible tests from the root. The augur-core python tests might be tricky since they aren't run with the rest of the tests. Likely the python junit output will need to be merged into the jest junit output so that CI can read them both.

**Comment by justinbarry** [comment]
ref #2265

**Comment by justinbarry** [comment]
See:  https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript?view=azure-devops#run-unit-tests

**Comment by robert-e-davidson3** [comment]
@petong we're doing this, right?
