### ISSUE TITLE
Mobile Account: Your Overview

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1741]
Left:Build — Right:Design
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/6653219f-3dcc-4fd0-969d-3fc0b922bb93)

- [x] Make 'Total Account Value' and 'Profit and Loss (ETH)' 12px Bold Mono
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/586d0908-c73c-4164-8565-0104f21da1b6)![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/dbbe1e15-5d0d-4504-abba-ca5d42ef3ef7)

- [x] Check sizing and colour of type against design
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f0583f9b-641e-43b0-bd91-97da6eb676e2) 

- [ ] centre Augur Logo
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/c334f9aa-8ef5-497c-83d9-1551c7e58af8)

- [x] check font size, weights and colour against design 
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/daa2fdbf-66f1-4992-a8da-d362e65ae680)

- [x] percentages for account value and P/L should be in brackets
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/3addc326-b2c2-476e-9e33-bf7d2ecb54a2)

- [x] Spacing
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/a0906a3f-041f-4829-953e-c9a8d0a7ea3f)

**Comment by Chwy5** [comment]
@matt-bullock  plz rvw

**Comment by matt-bullock** [comment]
Closing and creating separate tickets for remaining issues
