### ISSUE TITLE
Mobile Trading Page: Label row should always be 32px height

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1743]
Needs increasing in Open Orders and Positions
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/4fa4f27b-19c5-4237-9947-b82a2f65251c)

**Comment by Chwy5** [comment]
@matt-bullock plz confirm and close

**Comment by matt-bullock** [comment]
It still looks like they're not fixed to 32 px. The reason I ask is that it stops this component jumping up and down in size when switching between tabs. Should look like this:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/3a06e408-fcfe-4dd4-b5d0-dda85bab127c)

**Comment by matt-bullock** [comment]
It still appears to be jumping around in height between the three tabs. Can we make all the same height/positioning and text should stay vertically centred
