### ISSUE TITLE
Try Buying x shares then buying y shares immediately after while pending

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#175]

**Comment by tinybike** [comment]
The `+x shares` label is overwritten by a `+y shares` label (when they should actually be summed).  If there's more to the bug than this, please update this issue with more details.  (Both trades complete successfully, and my total shares held is updated correctly.)

**Comment by joeykrug** [comment]
That's all, they should be summed

**Comment by tinybike** [comment]
Fixed in 3717ceedc020eca039ebe255c97e4fb968c08fab.
