### ISSUE TITLE
Claim proceeds: processing appears before signing tx

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1750]
When I click the claim proceeds for an individual order, the processing label appears before I sign the MM transaction. Surely this should only appear once I've signed the transaction and it's sent to be processed ![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e270ccbf-4503-4f20-bd88-ebfeef6e6a64)

**Comment by Chwy5** [comment]
better-closing
