### ISSUE TITLE
Mobile trading pg positions fields are scrunched together

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1751]
Fields under the positions section of the trading pg on Mobil are all jumbled together....

see screenshot

https://cdn.discordapp.com/attachments/464067340015763466/568586637345423360/Screenshot_20190418-195855.jpg

**Comment by bthaile** [comment]
I think this has been addressed with recent push to sneakpeak. I'll verify.

**Comment by bthaile** [comment]
![image](https://user-images.githubusercontent.com/3970376/56519333-68dcfb80-6507-11e9-8490-6f0b57ec15a6.png)


![image](https://user-images.githubusercontent.com/3970376/56519349-72fefa00-6507-11e9-9f6f-2a9d3acd3131.png)


looks fixed, can you confirm @Chwy5

**Comment by Chwy5** [comment]
better - closing
