### ISSUE TITLE
Mobile Trading Page: My Fills component showing wrong information

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1753]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/2c9df794-0927-4edf-88d9-5c01d7699039)
Build

On mobile we had to remove the Fill Date column for the information to fit. It should be showing this information:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/ec124cc5-d75a-4821-9f28-b88795fef0f1)

**Comment by Chwy5** [comment]
Mobile trading pg My Fills appears to be pulling information from filled orders in the portfolio pg (which contains different information) than the My fills of the trading pg

**Comment by Chwy5** [comment]
It's currently not showing any data

**Comment by bthaile** [comment]
Fixed the issue where filled orders wasn't showing any info. Sending this back to you @Chwy5

**Comment by Chwy5** [comment]
fixed - closing
