### ISSUE TITLE
Review market details modal adjustment

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1757]
The modal should only pop up when a user enters a market from the markets list pg....

It should not pop up if a user enters a market through the acct sum pg or portfolio pg

If a user has an open position or open/filled orders and clicks on the market (the modal currently pops up ...if they hadnt clicked dont show this message on any more markets)

**Comment by bthaile** [comment]
This seems like a `priming the pump` issue. I agree there will be users with existing positions when they first open the UI and currently they will see the modal. 

Over a small amount of time they will nav to the market via markets list. I don't think we need to add code to cover this small gap in time where users navigate to markets they already have a position in.

**Comment by Chwy5** [comment]
lets punt to 1.14

**Comment by andrewdamelio** [comment]
@pgebheim decent amount of time needed on this. Should be broken out of this epic
