### ISSUE TITLE
Google translate bar is cut off on mobile 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1758]
Google translate bar is cut off on mobile. Visually it also looks really dated and doesn't fit in well with our UI. 

Can we customize this bar? 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/58116420-a927-443b-b635-d9f5ae0a1080)

**Comment by andrewdamelio** [comment]
@cillianhunter0 we will remove it

**Comment by andrewdamelio** [comment]
closing.

Going to remove this bar from the UI for now. 

When we are ready to tackle intl in the UI we should revisit how we would like to handle google based translations (should we allow it?) as well as designs around it.
