### ISSUE TITLE
Add ellipses to end of Resolution details when there is more to show

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1760]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/d5b575e6-9d78-4a52-a3b1-01d9b5ac5da0)

**Comment by andrewdamelio** [comment]
Closing -- doesn't apply anymore since the end of the details  is now hidden, see below
![image](https://user-images.githubusercontent.com/1683736/69999189-0b417080-1526-11ea-88a2-12c06dec5bb3.png)

**Comment by matt-bullock** [comment]
![image](https://user-images.githubusercontent.com/39496225/70270322-71d3c200-17a4-11ea-8a06-3be6ef56156f.png)

It should still apply. If there is more to show then add ellipses where the text gets cut off and add the arrow button to show more

**Comment by Chwy5** [comment]
Need to have a max length we show on the market trading pg (say 3 or 4 lines) aanything longer we show the ellipse and they would need to hit the arrow to expand down

**Comment by matt-bullock** [comment]
Not seeing the ellipses here even though there is more to show:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/fee04b2a-3091-4810-9cbe-7dd64812592c)

It's also sometimes displaying the show more arrow when there is nothing more to show. Seems to only be cutting of the descenders of the letters, which it shouldn't be doing (only hide lines of text here, not cut part way through a line) Example:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/267170d2-e6f0-41dc-875f-bad587c6ab35)

**Comment by Chwy5** [comment]
closing
