### ISSUE TITLE
Trading Page mobile update to sub nav: change Orders to Orders/Position

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1763]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/60efe4cb-7290-4933-ae03-c472528dc6f8)

**Comment by Chwy5** [comment]
Need to remove the "S"

![4-23s.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/fecb64b8-3c10-4e44-8830-9eaf8f5236a5)
