### ISSUE TITLE
Trading Page: Responsive Designs

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1764]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/620acb9e-4e10-47fe-a9e4-e4e705b9c768)

https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7945%3A268540

Notes

MOBILE

- Mobile (min = 360)
  - Nothing changing here
- Mobile (max = 767)
  - Scale content left & Right

SMALL TABLET

- General note
  - We'll use the mobile header bar between 768-1199px, but retain the content of the pages from desktop
- Small Tablet (min = 768)
  - 24px margins on sides
  - Order Book and Trade history are combined into same component
- Small Tablet (max = 1199)
24px margins on sides

See layout grid. Note how order ticket, order book and trade history all take up equal thirds
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/3015b970-7a06-4e44-b47f-54357f94e231)

LARGE TABLET
- Same as small tablet except order book and trade history become separated out into independent components - horizontally stacked with Order Ticket
- min = 992
- max = 1199

DESKTOP

- Desktop (min = 1200)
   - 40px margins on side
  - 20px padding between components (or whatever is currently used)
  - use guides. Note: order ticket, order book and trade history are 1/4 of the space. Outcomes and charts 2/4. Orders and Positions 3/4
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/d22acfba-a962-4e41-9230-adc09d5e24b7)

- Desktop (baseline = 1440 - what we've been working at to date)
  - 40px margins on side
  - 20px padding between components (or whatever is currently used)
  - use guide for proportions - following the same structure as 1200
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/23c40b86-6642-439d-8a0f-bf394beb5a74)

- Desktop (max = 2064) using as an example of a large resolution (we can come back to this if not trivial)
  - 40px margins on side
  - 20px padding between components
  - Components shift around to create the best fucntioning layout at this size to prevent components like order book stretching out and becoming too wide.
  - Design is more a guidance for layout here as gridding and spacing may not be perfect
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/591d5df2-fee9-42ae-afca-a7d477fe0990)

**Comment by JohnDanz** [comment]
We need to do some refactoring i think before this can be done effectively. We are still to tightly tied to using isMobile and isMobileSmall etc which need to come out, and we need to refactor this page to use CSS to flow it instead of variables branching what we render -- it's cumbersome for really no reason.

**Comment by bthaile** [comment]
@Chwy5 this effort will be substantial prob over a week, recommend moving this to v1.14

**Comment by Chwy5** [comment]
pushing to 1.14

**Comment by andrewdamelio** [comment]
@pgebheim this should also be moved to mobile epic

**Comment by pgebheim** [comment]
Moved!
