### ISSUE TITLE
Pagination button amend

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1767]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/9cf94cd8-ba03-4f55-9488-6ad4cb9fc6b8)

Instead of removing button, please show the disabled state of that button

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/0da61ab4-54bf-4f56-b4fc-5afe285b1f12)

Can be found here:
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=342%3A34455
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/09a5f555-0d7b-4efa-82b1-890143d35761)

**Comment by bthaile** [comment]
new pagination for market listing redesign. closing
