### ISSUE TITLE
Mobile Trading Page Outcome selection 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1768]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/19850fa6-4edf-46e7-963b-69cef1c85cfb)

Add 16 px of padding to the button of this
Add same opacity (90%) and background blur as the subnav

Should look like this when content scrolls under

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/adbee69f-29df-4b69-85ff-708fa3c002bc)

**Comment by matt-bullock** [comment]
Outcome selector there but some of the details missing:

Padding looks like 32 px. Should be 16px. Opacity still not there
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/9ae69663-bccb-4829-8e6e-c2f37d445e8a)

Moving this to 1.14 for to get the details in

**Comment by JohnDanz** [comment]
Related Ticket: https://github.com/augurproject/augur/issues/1916
