### ISSUE TITLE
Notification modals mobile (close out list) 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1770]
**Finalize market**
- Update string to "The following market is resolved and ready to be finalized so proceeds can be claimed"
- Remove string "Please finalize this market so proceeds can be claimed"
- Padding, see screenshot:
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/05ccdc30-d756-4271-93ad-73f9e3830799)

**Unsigned orders**
- Wasn't able to check this, but can you please check that if the table has a lot of unsigned orders, it doesn't create a double scroll situation inside the modal 
- Padding issues, see screenshot:  
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/9d5cd4ae-6e61-450d-a40f-4ea5ed643412)

**Open orders in a resolved market**
- String color should be #CED7D8 "You have open orders in this resolved market:" 
   - Bottom padding below the same string should be 12px not 20px 
- When I tap 'cancel' on an order, the cancel button isn't disabled (it should follow the transaction feedback pattern and disable the button)
- IF multiple open orders and user expands them so the modal increases in height, THEN the modal should only have one scroll view (currently the table scrolls as well as the modal's scroll area). This is the scroll area we should use: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/def44a05-528d-4a13-a37f-fb3b346b3044)
Padding: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/91e2070c-32b4-4751-a998-bfda9f54a7f8)

**Sell complete sets**
- Padding issues, see screenshot
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/15d01487-06ac-4512-b39c-2b574eecc374)

**Claim proceeds**
- Multiple issues, please reference design on figma for below: 
   - Padding and margins of elements is off
   - Header and footer lines don't extend to edge of modal 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/ba9c8d07-ed20-4021-98bd-5486b337baca)

**Claim stake and fees**
- Multiple issues, please reference design on figma for below: 
   - Padding and margins of elements is off
   - Button copy isn't accurate 
   - Header and footer lines don't extend to edge of modal 
Build on left, design on right 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/9f9d3126-5bd6-40ef-a13d-def2cb955d27)

**Orphaned orders**
- This doesn't exist as a modal at the moment.

**Comment by bthaile** [comment]
Finalized market
![image](https://user-images.githubusercontent.com/3970376/56595106-a6975e00-65b3-11e9-8eb4-358f1bf94dd2.png)


![image](https://user-images.githubusercontent.com/3970376/56538421-9d14e400-6528-11e9-98a4-1d696b3c5d10.png)

![image](https://user-images.githubusercontent.com/3970376/56538431-a30ac500-6528-11e9-92d7-2cbfc49ba2ec.png)


Unsigned Orders

![image](https://user-images.githubusercontent.com/3970376/56595892-1528eb80-65b5-11e9-9e31-2b4b0faa3248.png)

![image](https://user-images.githubusercontent.com/3970376/56538546-f846d680-6528-11e9-9951-b1337e7bbcf1.png)

![image](https://user-images.githubusercontent.com/3970376/56538555-ff6de480-6528-11e9-861f-6c1c43e3d0ef.png)

sell complete sets
![image](https://user-images.githubusercontent.com/3970376/56596061-705ade00-65b5-11e9-9b8a-6923605bea34.png)

![image](https://user-images.githubusercontent.com/3970376/56538674-49ef6100-6529-11e9-8d75-edf5f65cda9f.png)

![image](https://user-images.githubusercontent.com/3970376/56538684-507dd880-6529-11e9-9e02-13bf730a702a.png)


claim proceeds:

![image](https://user-images.githubusercontent.com/3970376/56596236-ce87c100-65b5-11e9-86ed-5dfa91776945.png)

![image](https://user-images.githubusercontent.com/3970376/56538591-18769580-6529-11e9-89e0-6beecdcab45d.png)

![image](https://user-images.githubusercontent.com/3970376/56538611-23c9c100-6529-11e9-8ff3-1f90dd346c6b.png)

**Comment by bthaile** [comment]
@cillianhunter0 I put screen shots for the notifications and modals you `Haven't been able to view this on test account`

I can walk you through getting each of these if the screenshots don't handle it.

**Comment by bthaile** [comment]
this tix is not clear and was used as a verification of notification modals. It can be closed. We'll end up running through all the modals as part of general testing of account summary. Plus we'll have a different list for V2.
