### ISSUE TITLE
Mobile - portfolio - positions (styling issues) 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1771]
Collapsed row
Build on left, design on right (incl notes): 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/2fbfa2dd-4757-495d-855b-2b25c38211ab)

Expanded row
Build on left, design on right (incl notes): 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/e545df72-07dd-405f-ab57-051c29903cab)

Inputs area
Build on left, design on right (incl notes)
Also note that the "cancel" button color should be blue: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/67808871-d71e-4e91-ad5f-3a4715f3ea3c)

**Comment by phoebemirman** [comment]
this is based on old design, new design changes will be addressed by other tickets
