### ISSUE TITLE
Mobile - portfolio - open orders (styling issues)

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1772]
Expanded row
Build on left, design on right (incl notes):
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/15633f0f-e85e-47a3-8edf-605aeef8673a)

Also note that all outcome strings in portfolio are updated to roboto 12 bold #ffffff

**Comment by phoebemirman** [comment]
this is based on old design, new design changes will be addressed by other tickets
