### ISSUE TITLE
Mobile - portfolio - filled orders (styling issues)

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1773]
Expanded row
Build on left, design on right (incl notes):
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/4f2e434d-5c27-42c1-b13c-bbab5bb725be)

Also note that all outcome strings in portfolio are updated to roboto 12 bold #ffffff

**Comment by phoebemirman** [comment]
this is based on old design, new design changes will be addressed by other tickets
