### ISSUE TITLE
Keep augur-artifacts up-to-date with smart contracts

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#1776]
We are going to assume augur-artifacts is updated by the core developer making the changes. The plan here will be to fail a PR if `contracts.json` is dirty (changed) after building augur-core.

**Comment by pgebheim** [comment]
@nuevoalex @justinbarry --- If the contract builder just exports these to `augur-artifacts` is it okay for you to just commit them @nuevoalex along with PRs?

In CI we actually do build them all and then deploy to make sure its all working -- but having those artifacts pre-committed would make local testing much faster since it wouldn't require that artifact to e built.

**Comment by pgebheim** [comment]
Also, @justinbarry -- Did your changes yesterday change these to output to augur-artifacts?

**Comment by nuevoalex** [comment]
Yea that's fine. Any contract changes should result in a rebuild for this anyway since you have to do that to run tests.

**Comment by justinbarry** [comment]
@robert-e-davidson3 In CI we build the artifacts and check for a dirty working copy? Is that what you are thinking?

**Comment by robert-e-davidson3** [comment]
@justinbarry I'm not sure what you mean by dirty but probably? I was thinking that when building augur-core as part of CI, check if the output files like `contracts.json` in augur-artifacts changed. Like do a hash of them before and after or ask git.

**Comment by pgebheim** [comment]
Awesome!

**Comment by justinbarry** [comment]
So implement the file change checking in ci is the real task here.

**Comment by pgebheim** [comment]
That already happens -- CI builds augur-core when that package's tree is modified.

Adding @petong to confirm that.

**Comment by justinbarry** [comment]
But now we need to fail if contract.json changes, yeah?

**Comment by pgebheim** [comment]
Hmm.

So that Alex knows he needs to commit that file? @nuevoalex – would it work if your PR would fail unless the contracts and the contracts.json were in sync?

Paul Gebheim
paul@augur.net

**Comment by pgebheim** [comment]
This is working now!
