### ISSUE TITLE
Create 2 markets issue

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#178]
Create two markets, only one will appear as a finalized market on the last page even though both succeed in console.  Not even a refresh makes it appear.

**Comment by tinybike** [comment]
Strange, doing `getMarketInfo` in the console shows that's clearly there, though.  Troubleshooting.

**Comment by tinybike** [comment]
Fixed in 46b4fe842f925c37f54f060a85e0d33bba23afb4.
