### ISSUE TITLE
Lag after a trade is made

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1781]
I created a scalar market and added 6 orders in preliquidity 3 bids/3 offers....

I hit submit....took 1 minute for first mm sign box to appear (we need to show some type of pending or action to user so they know what is happening in this downtime state).....After signing...the pg freezed for 1 - 2 mins...I cant scroll or click on anything (half the time I am getting a pg unresponsive message pop up)...after clicking wait, eventually it loads...

This occurs for each of my preliquidity orders as well...I sign 1 mm box and augur pg freezes for about 1-2 mins...unfreezes i sign the next....It has taken me 15 mins to create a basic market and sign mm tx boxes

**Comment by Chwy5** [comment]
appears better closing

**Comment by Chwy5** [comment]
getting a lag right after a trade confirms...screen freezes for a few seconds and then reengages again

**Comment by bthaile** [comment]
We need a better user flow for market liquidity. It doesn't work to chain send/sign orders after market creation tx confirms.

We do need market creation confirmation before sending orders. we don't want to send orders for a market that might have failed or has a low gasPrice and takes days to confirm.

We need to think through this process.


example, I never sent my liquidity orders. b/c of this

![image](https://user-images.githubusercontent.com/3970376/56675819-a1551480-6682-11e9-9ea7-bc4627016266.png)


MM didn't pop up. and by the time the market creation tx came in I was off doing something else.

We need to not rely on MM pop ups.

**Comment by Chwy5** [comment]
still getting the lag after a trade

**Comment by bthaile** [comment]
As bad as it was before? Is there any perceived improvement?

**Comment by Chwy5** [comment]
I just created a market and added pre-liquidity and it was the exact same

**Comment by Chwy5** [comment]
I just tried it on a regular trade (not pre-liquidity) and it was much better....so issue seems to exist in the pre-liquidity provision only now

**Comment by bthaile** [comment]
Kick this tix back to me if you haven't already and I’ll look specifically at the thread.

**Comment by Chwy5** [comment]
latest testing seemed better...got slight freeze in pre-liq of categorical, but was very short...not getting any in binary or scalar - closing this
