### ISSUE TITLE
Improved Market Filters

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#1782]
We now have an idea for a filter to filter markets by spread, the algorithm is below. This’ll filter out illiquid markets from a spread perspective but also ones that’re doing validity arbitrage at really bad prices (i.e. the markets that’re referred to on reddit as being ones to watch out for). So it solves a big problem right now for helping people avoid markets with bad prices that expire before they should.

UI wise this should be just like the fees filter where you can filter by Fee < X %, but instead Spread < X %.

So we need the:

- Design for this (simple + functional / not overthought, it’ll be redone when we do the markets listing page)
- AN endpoints for this
- UI dev for this

```
So the algo would be:

Spread = []
outcomes = 0
For outcome in market (if binary or scalar, just for yes outcome):
      10_percent_shares = max(sum(ask_quantities), sum(bid_quantities)) * 0.10
      smallest_side_amount = min(sum(ask_quantities), sum(bid_quantities))
      num_shares = min(10_percent_shares, smallest_side_amount)
      bid_value = 0
      ask_value = 0

      // the getters return a dictionary of orders w/ quantity and price, returns an empty one if num_shares is 0
      bid_quantity = 0
      quantity_gotten = 0
      for order in get_orders_up_to_num_shares_quantity(bids, num_shares):
            if(order.quantity + quantity_gotten > num_shares):
                 order.quantity = num_shares - quantity_gotten
            bid_value += order.quantity * order.price
            quantity_gotten += order.quantity
      bid_quantity = quantity_gotten
      quantity_gotten = 0
      for order in get_orders_up_to_num_shares_quantity(asks, num_shares):
            if(order.quantity + quantity_gotten > num_shares):
                 order.quantity = num_shares - quantity_gotten
            ask_value += order.quantity * order.price
            quantity_gotten += order.quantity
      ask_quantity = quantity_gotten

      if (numShares == 0) {
        // one or both sides of order book was empty; we'll pretend instead
        // it/each had 1 share to facilitate calculating spreadPercent.
        numShares = 1;
        if (totalBidQuantity == 0) {
          // bid side of order book was empty
          bidValue = minPrice
          askValue = ask_value / ask_quantity
        }
        // note this isn't an "else if" anymore so that both bid/bask set to min/max if entire book empty
        if (totalAskQuantity == 0) {
          // ask side of order book was empty
          askValue = maxPrice
          BidValue = bid_value / bid_quantity
        }
    }

      Spread[outcomes] = (ask_value - bid_value) / ((max - min)*num_shares)
      outcomes += 1

// max spread across all outcomes
spread_percent = max(Spread)

Filter out markets by spread % < x
```

This should be part of the markets listing epic (on mobile so can’t add it to it atm)

**Comment by tinybike** [comment]
Would it make sense to also include outcomes that only have bids or asks?  If missing bid, best_bid=min_bid and if missing ask, best_ask=max_ask.  This way you can't get around the algo by just adding orders to one side of the book of a bad market.

**Comment by bthaile** [comment]
I’d like to get a bit of design work for mobile. Also we need to add the algo to getMarkets augur-node endpoint.

**Comment by Chwy5** [comment]
This feature will fall into the customization search criteria I  want to have for a user to search on the market list pg.  B/c of space, especially for mobile, we plan on displaying drop downs for basic search functions (adding a new type - for Binary, categorical, and scalar) + our existing dropdowns.  I want to move any customizable ones like this and the % ones, + some others I want to add (any search feature which doesn't get changed very often), will fall into this.....We will include it when we start on the market list page next week.

**Comment by Chwy5** [comment]
Does any of the math being done come from AN? if so it may need to wait until after the switch

**Comment by pgebheim** [comment]
@chwy5 -- we got approval from @nuevoalex to do the AN work for this in v1. It doesn't require a schema change and is potentially not needed for v2 to accomplish the same result.

In any case you can schedule to move forward with it for 1.14.

**Comment by Chwy5** [comment]
adding it to 1.15 which is the market listing pg, which we are starting on - thursday

**Comment by pgebheim** [comment]
Sounds good to me.

Paul
paul@augur.net

________________________________

**Comment by matt-bullock** [comment]
Design guidance is on 'Market List' page of this doc

https://www.figma.com/file/csVtbWhGCAYe3nVe2LI1UEPM/v1-updates-to-the-UI?node-id=300%3A8313

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/eaa70cdb-bb99-4136-8746-647b26cffdb8)

**Comment by ryanberckmans** [comment]
I've been asked to implement this in augur-node

**Comment by bthaile** [comment]
@ryanberckmans yes, coordinate changes with @phoebemirman , she is running the UI portion.

**Comment by Chwy5** [comment]
@matt-bullock we still need design for v2 version of the spread....it should be located within the market lists setting feature, would also call it bid/ask spread inside there

**Comment by ryanberckmans** [comment]
Related to https://github.com/AugurProject/augur-ui/issues/3028

**Comment by pacif1c** [comment]
[This market](https://predictions.global/augur-markets/-will-eth-be-above-165-at-end-of-may-0x6b0eef4addfe1a5e3938fc4511bdb7a2c307d630) would rank high/pass the filter even though it's Invalid. 

This gets at a broader issue with binary (and scalar) markets where since the scammer gets a payout of .50, they are willing to pay anything under .50 for long *or* short shares.  

For example, a market with a ~5% spread with a bid at .51 and ask at .49 is probably *more* likely invalid than one with a 10% spread with a bid at .40 and ask at .44 — even though it has a tighter spread. 

Another way to think about this: if you take all the orders on the book would any of them come out at a loss if they were filled and the market resolved Invalid? If not then the market is suspect 

One solution is for the algo to define liquidity in a broader way where it’s not just what % you would recoup if you bought shares then sold right away but also if you bought and held shares and then the market resolved Invalid

**Comment by bthaile** [comment]
Would the settlement fee considered in the calc. The market maker might be willing to make a tighter spread (pass the filter)  if they knew they would get a “high” settlement fee. Knowing the market would resolved as invalid.

**Comment by Chwy5** [comment]
In my opinion this is a separate feature, even though related to the original spread filter.  I think simple is best....Most users if augur is successful, wont even want to get into the invalid spread, possibility.  Regular non-dev, limited crypto bettors will have no idea what that is...but still want to find markets w/ tight spreads.  I would stick with the current idea and if we want to add a more complex version like your suggesting, it would go into some "advanced settings", that some users could do if they want.

**Comment by pacif1c** [comment]
To clarify Chwy, this would be invisible in the UI, just under the hood in the algo. My concern is users falsely assuming markets with a tight spread are valid. That is a fair assumption for categorical markets with over two outcomes but otherwise (binary, scalar, or categorical market with only two outcomes) it is not necessarily the case because the highest bid and lowest ask could both be profitable in the case of Invalid but still within a 5% spread. So I’m thinking how we could alter the algo to weed these out. I am in 100% agreement to keep things as simple as possible and trying to think of a way to keep this as simple or even simpler than it already is.

**Comment by joeykrug** [comment]
Spread filter is the same as above. 

This idea would be a separate feature called the Experimental Invalid Filter (checked by default):

`if best bid <= range/num_outcomes+min + oi_fee/4 and best ask >= range/num_outcomes+min - oi_fee/4` For any of the outcomes in a market then a market is filtered out, else it appears

**Comment by pgebheim** [comment]
This whole epic is actually in progress

**Comment by cillianhunter0** [comment]
Can we add an option at the top of the filter that shows markets with any spread. 

We'll call it "Show all markets". 

Reason for this: we're going to remove the "Has open orders" filter because it's redundant due to the spread filter.

**Comment by phoebemirman** [comment]
we were planning on adding that

![image](https://user-images.githubusercontent.com/6775839/57644326-c0074680-7570-11e9-9b76-054c10a7e7bc.png)

**Comment by cillianhunter0** [comment]
OK cool, that looks good

**Comment by ryanberckmans** [comment]
Worked with Joey to tweak algorithm a bit:

1. `elif(best_ask_exists):` is no longer an "else if", just an "if", to support both sides of book being empty

2. `smallest_side_amount` dropped so that if one side of book is empty, then the other side still accrues bidValue/askValue. Now is just `num_shares = 10_percent_shares`

**Comment by ryanberckmans** [comment]
@phoebemirman we might want "All Spreads" to go at bottom of dropdown instead of top. "All spreads" is equivalent to "Spread <= 100%"

**Comment by phoebemirman** [comment]
that order is consistent with the fee dropdown
<img width="156" alt="Screen Shot 2019-05-13 at 7 04 23 PM" src="https://user-images.githubusercontent.com/6775839/57665747-05983380-75b2-11e9-9092-a1aa90816dad.png">

**Comment by ryanberckmans** [comment]
> This idea would be a separate feature called the Experimental Invalid Filter (checked by default):

Joey asks that "Experimental Invalid Filter" be included in the same release as spread filter. I told Joey I can piggy-back this pretty easily on the existing work. Tomorrow I'll create a ticket for "Experimental Invalid Filter" and get started on it.

**Comment by joeykrug** [comment]
```
So the algo would be:

Convert prices to non display prices, so a scalar from -100 to 200, -100 would be 0, 200 would be 300.

midpoint_liquidity = []
outcomes = 0
For outcome in market (if binary or scalar, just for yes outcome):
      best_bid = get_best_bid(market)
      best_ask = get_best_ask(market)
      if(no_bid_exists): best_bid = minPrice
      if(no_ask_exists): best_ask = maxPrice
      best_bid = best_bid / (1 - totalFee %)
      best_ask = best_ask / (1 + totalFee %)
      midpoint_price = (best_bid + best_ask)/2
      ask = midpoint_price + spread % * range/2
      bid = midpoint_price - spread % * range/2

      bid_quantities = 0
      // inclusive of price
      // for bids we get orders from the midpoint down to the bid price. For asks we get the orders from the midpoint *up to* the ask price. 
      for order in get_orders_down_to_price(bids, price): bid_quantities += order.quantity
      ask_quantities = 0
      for order in get_orders_up_to_price(asks, price): ask_quantities += order.quantity
      num_shares = min(ask_quantities, bid_quantities)
      num_shares_was_0 = 1 if(num_shares == 0) else 0

      bid_value = 0
      ask_value = 0
      raw_bid_value = 0
      raw_ask_value = 0
      // the getters return a dictionary of orders w/ quantity and price
      bid_quantity_gotten = 0
      for order in get_orders_down_to_price(bids, price):
            if(num_shares == 0):
              num_shares = bid_quantities
            if(order.quantity + bid_quantity_gotten > num_shares):
                 order.quantity = num_shares - quantity_gotten
            bid_value += order.quantity * order.price
            raw_bid_value += order.quantity * (order.price - min)
            bid_quantity_gotten += order.quantity
      ask_quantity_gotten = 0
      for order in get_orders_up_to_price(asks, price):
            if(num_shares == 0):
              num_shares = ask_quantities
            if(order.quantity + ask_quantity_gotten > num_shares):
                 order.quantity = num_shares - quantity_gotten
            ask_value += order.quantity * order.price
            raw_ask_value += order.quantity * (max - order.price)
            ask_quantity_gotten += order.quantity

      if (num_shares_was_0) {
        // one or both sides of order book was empty; we'll pretend instead
        // it/each had shares on the other side at the max or min to facilitate calculating.
        if (bid_quantities == 0) {
          // bid side of order book was empty
          bidValue = minPrice * ask_quantities
          num_shares = ask_quantities
        }
        // note this isn't an "else if" anymore so that both bid/ask set to min/max if entire book empty
        if (ask_quantities == 0) {
          // ask side of order book was empty
          askValue = maxPrice * bid_quantities
          num_shares = bid_quantities
        }
      }

      midpoint_liquidity[outcomes] = (raw_ask_value + raw_bid_value) / 2
     Spread[outcomes] = (ask_value - bid_value) / ((max - min)*num_shares)
     outcomes += 1

// min midpoint liquidity across all outcomes
// in v2 exclude invalid
Liquidity = min(midpoint_liquidity)
Spread = max(Spread)

Let user choose a spread % like in dropdown now, but it's a sort and it'll sort markets by liquidity within that spread % threshold, it should filter out markets that have a spread as calculated above > n%, in the example above, n is 10%.

*Or* you can use it to filter markets by a certain spread % and not sort
```

**Comment by joeykrug** [comment]
```const SELL_INCREMENT_COST = 0.1 eth;
def getLiquidityTokens(marketId, outcome, spreadPercent) {
    // we adjust for fees by ask / (1 + totalFee%) and bid / (1 - totalFee%)
    // also the share price should be converted to non display prices so a scalar from -100 to 200, -100 would be 0, 200 would be 300. 
    const orderBook = feeAdjust(sharePrice(select *
        from orders where marketId and outcome));
    // also add orders to the book for infinite liquidity (so maybe just whatever the biggest js value is) at the min and max, for bids we add it at the min, for asks we add it at the max
    let liquidityTokens = 0 eth; // ie. proceeds from selling complete sets
    let liquidityTokenCost = 0 eth; // ie. cost for complete sets
    const sellIncrementQuantity = numCompleteSetsForNEthTokens(
        SELL_INCREMENT_COST
        );; // ie. number of complete sets bought by SELL_INCREMENT_COST tokens
    let liquidityTokens = 0 eth;
    do {
        liquidityTokenCost += SELL_INCREMENT_COST;
        // sell the complete sets into the book by selling into the bid and then buying it back via the ask and seeing how much money is left over. e.g. take .1 eth worth of complete sets which is y complete sets and try to sell y shares by filling the bid side, then try to buy back y shares by filling the asks. So an example is the user buys a complete set. Then they get rid of outcome x by selling it, which gives them say 198, then they buy it back, which costs them 202. Then they close their complete set out for 300. In the transaction they made 300 + 198 - 202 which is 296. If that was a range 300 eth market with a complete set cost of 300 eth, then if they had a sell increment cost of 300, the liquidityTokens would go up to 296 and the liquidityTokenCost would be 300. 296/300. Makes sense! If the sell increment cost was a more reasonable 0.1 eth, then .1/300 = 0.0003333333333 it’d be 0.099999 + 0.065999 - 0.067333 or 0.098665. 0.098665 would be the liquidityTokens received divided by the cost of 0.099999 or  0.098665/0.099999. Note those two numbers have the same spread, just on a different size/scale, so we can see that the math works!
        tmpProceeds = orderBook.takeCompleteSets(sellIncrementQuantity);
        if (liquidityTokens / liquidityTokenCost < (1 - spreadPercent))
            break;
        liquidityTokens += tmpProceeds
    } while )
return liquidityTokens;
}

if (binary or scalar market):
    numOutcomes = 1
Liquidity = array(numOutcomes)
for outcome in marketId {
    if (binary or scalar and outcome == no):
        continue
    Liquidity[outcome] = getLiquidityTokens(marketId, outcome,
        spreadPercent)
}
Liquidity_Value = min(Liquidity)

If(best_display_ask - best_display_bid) / range < spreadPercent {
    show market
}
else {
    hide market
}

Sort visible markets by Liquidity_Value
```

ryan modified algo
