### ISSUE TITLE
Close idle websocket connections in augur-state server.

### ISSUE THREAD

**Issue by brianosaurus** [AugurProject/augur#1789]
### Idle timeout

So that they don't use resources, we should close idle webcoket connections in augur-state. By idle, I mean connections that don't send requests for a period of time (ex: 10 minutes). How long to wait needs a little research and might be best dealt with as a configuration variable in settings.json.

**Comment by pgebheim** [comment]
This is a nice to have for server mode.

**Comment by pgebheim** [comment]
Removing from #668 so that can be closed with V2 launch issues.
