### ISSUE TITLE
Implement getAccountTransferHistory getter & tests

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#1797]

**Comment by pgebheim** [comment]
@brianosaurus -- Have you had a chance to look at this at all?

@adrake33 -- is this easy now with the user tracked data?

**Comment by adrake33** [comment]
@pgebheim Should be pretty straightforward since we're already tracking the `TokensTransferred` event in its own DB.

**Comment by robert-e-davidson3** [comment]
https://github.com/AugurProject/augur-node/blob/master/src/server/getters/get-account-transfer-history.ts

**Comment by robert-e-davidson3** [comment]
Not necessary for v2.

**Comment by pgebheim** [comment]
Where is this functionality handled? Has it been wrapped up into the big user info getter?

**Comment by robert-e-davidson3** [comment]
@bthaile

**Comment by bthaile** [comment]
close this, I don't see where the ui would use this. unless I'm missing something.
