### ISSUE TITLE
Implement getAccountReportingHistory getter & tests

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#1808]
Reporting Information needed for market cards in reporting,  participation tokens and disputing form.

Input:
 - user account address
  - universe address

Outputs:
  summary: This is all user account specific information. All reporting/disputing stake information and participation information. This includes:
 - Profit and Loss percentage on reporting/disputing (REP staked / REP redeemed)
  Include REP profit in attoREP UI will format it.
 - All `IReportingParticipant` contracts and amounts the user has currently contributed to or can be redeemed. (don't include finalized markets user lost)
 - All dispute window contracts the user currently has participation tokens. This includes current disputing window and dispute windows in the past. 

* Result shape could be:
```typescript
{
  profitloss: decimal,
  profitAmount: string,
  reporting: {
    totalAmount: string;
    contracts: [{
      address: string,
      amount: string,
      marketId: string 
    }]
  },
  disputing: {
    totalAmount: string;
    contracts: [{
      address: string,
      amount: string,
      marketId: string 
    }]
  },
  participationTokens: {
    totalAmount: string;
    totalFees: string;
    contracts: [{
     address: string,
     amount: string,
   }]
 }
}
```
![image](https://user-images.githubusercontent.com/3970376/63956762-aff67280-ca4c-11e9-9471-c3844347bed7.png)

![Screen Shot 2019-08-29 at 11 07 27 AM](https://user-images.githubusercontent.com/3970376/63957108-65c1c100-ca4d-11e9-8a14-d157c65170f2.png)

**Comment by robert-e-davidson3** [comment]
Related to this: https://github.com/AugurProject/augur/issues/2946

**Comment by bthaile** [comment]
getter is giving data, this can be closed
