### ISSUE TITLE
Implement getDisputeWindow getter & tests

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#1810]
This getter is to support the UI's current dispute window component and purchasing participation tokens. 

no input parameters

returns currently active 7 day dispute window on the universe. Which following properties:
1. dispute window address
2. start timestamp
3. end timestamp
4. current amount of participation tokens purchased
5. amount of reporting fees

**Comment by justinbarry** [comment]
This info will be included in the getMarketsInfo getter. See #2946.

Should probably be implemented as a separate getter and called from the getMarketInfo getter.

**Comment by robert-e-davidson3** [comment]
kinda looks like this: https://github.com/AugurProject/augur-node/blob/master/src/server/getters/get-fee-window.ts
