### ISSUE TITLE
Implement getForkMigrationTotals getter & tests

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#1812]
this getter provides payout migration totals for a forking market in a universe

Inputs
 * universe

Outputs
```
 {
  universe: string,
  marketId: string,
  outcomes: [ {
    outcomeName: string,
    outcome: string, // non-scalar markets this is outcome id.
    amount: string,
    isMalformed: boolean,
    payoutNumerators: string[] // not needed by UI, but 3rd parties might want it
  }]
}
```

default return value when universe isn't forking
```
{}
```

this getter is different from V1. the outcomes will be resolved see disputeInfo on getMarkets info getter. 

outcome:
For YesNo and Categorical markets outcome is same as outcome id.
For Scalar markets outcome is price between minPrice and maxPrice.

isMalformed
this is possible for YesNo and Categorical markets. This occurs when a report/dispute payout numerators are not in alignment with market type. 

Example: yes no market payout numerators are ["50", "25", "25"] or ["0", "50", "50"], all numTicks should be in one index of the payout numerators like ["100", "0", "0"] for invalid. ["0", "100", "0"] for No or ["0", "0", "100"] for Yes. 

same for categorical all numTicks need to be on one single index of the array.

**Comment by robert-e-davidson3** [comment]
replicating this: https://github.com/AugurProject/augur-node/blob/master/src/server/getters/get-fork-migration-totals.ts

**Comment by robert-e-davidson3** [comment]
Awaiting fleshing-out of how UI will handle forking.
