### ISSUE TITLE
Implement getPlatformActivityStats getter & tests

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#1813]
Make a getter that returns 
```ts
export interface PlatformActivityStatsResult {
  activeUsers: number; // what defines an active user?

  // OrderEvent table for fill events (eventType == 3) where they are the orderCreator or orderFiller address
  // if multiple fills in the same tx count as one trade then also counting just the unique tradeGroupId from those
  numberOfTrades: number;

  openInterest: BigNumber; // contract call

  // MarketCreated table
  marketsCreated: number;

// from the derived market table
// since that will have the latest volume for any given market
  volume: BigNumber;
 
// disputedMarkets get unique marketIds from the DisputeCrowdsourcerCompleted table
  disputedMarkets: number;
}
```

The getter should take a startdate, enddate, and universe.

**Comment by justinbarry** [comment]
@brianosaurus Can you knock this one out alongside #1802?

**Comment by brianosaurus** [comment]
@pgebheim How are we defining activeUsers? 

DAU, WAU, MAU? Have a choice? 

Also what metric? Make a trade, market, some other combination? Obviously logins won't work...

**Comment by Chwy5** [comment]
@brianosaurus We should define active users by anyone who does any type of transaction. This can include any type of, order placement (adding bid/offer to the book), actual trade, cancel order, order adjustment(which we should have soon),market creation, Reporting, dispute, purchase of participation tokens, or redeem winnings
