### ISSUE TITLE
"Has Open Orders Box" on mobile not displaying correctly

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1822]
depending on the mobile version the checkbox for has open orders doesn't sit next the text - these need to be tied together 

see screenshot

![4-23box.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/df017a15-38f3-4af4-aa80-9fbadedf19b6)

**Comment by Chwy5** [comment]
it works correctly for s7 and higher so can be fixed in 1.14

**Comment by bthaile** [comment]
closing this, no longer have open orders checkbox
