### ISSUE TITLE
Lag when hitting portfolio

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1823]
There is a 10 second lag when pressing the portfolio button

**Comment by Chwy5** [comment]
Clicking on portfolio and away from it was much faster yesterday, when Filled orders and My fills was not displaying information....worth testing if there is a cause of the delay there

**Comment by Chwy5** [comment]
it is cut down to about 4-5 seconds...not closing this moving this to 1.14...lets see if we can get this down even further

**Comment by bthaile** [comment]
Are you seeing this lag on your large trading account? We do have another optimization we can do. It’ll take a large’ish refactor, v1.14 would be the best time to do it.

**Comment by Chwy5** [comment]
I was on a decent size one(about a third of the size the size of my biggest one)...not my biggest and had the 4-5 second lag....new acct was quick though

**Comment by andrewdamelio** [comment]
@pgebheim can we close this and move to the benchmarking and performance epic work

**Comment by bthaile** [comment]
I think we can close this. We can create a more specific v2 tix if need be.
