### ISSUE TITLE
unsigned orders modal - buttons need to be grayed out an/or show processing

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1824]
When I submit an individual transaction....the cancel, submit, and submit all button are still functioning while my transaction is being processed...we need to show the procsessing button and gray out all the other buttons until the transaction is confirmed

![4-23orph.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/ce0ccabd-e403-42d5-9f1b-6385b0d6c227)

**Comment by andrewdamelio** [comment]
Should be moved out of this epic. All transaction buttons will have to be updated once the UI wires up to the new TX queue for determining transactions states (sign, pending, confirmed, error)
