### ISSUE TITLE
Market list page 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1827]
Areas to address:
- Market cards
- Categories
- Search, sort and filters

Notes from previous ticket:
- market cards take up way too much space. More market should be visible at one time.
- revisit the way categories and tags are displayed on the market card
- address pagination styling and type (load more, pages, etc)
- add market type filter
- show the price and quantity of the best bid on the most popular
- show tentative and winning outcomes

**Comment by joeykrug** [comment]
1) UI shouldn’t show tags and categories if they don’t have any markets that fit the filters you’re looking at
4) The way sorts / filters could work imo is you have the usual open, in reporting, resolved dropdown. To the right of that you have the spread sort dropdown with the same options we have today. Then to the right of that you should have the option to filter by OI > some amount, recently traded < some time, and reporting starts < some time. Much simpler, if users clamor for more we can add more at that point.

@cillianhunter0 @matt-bullock @Chwy5

**Comment by Chwy5** [comment]
@joeykrug is this for v1 or market card redesign.....the redesign addresses all of those issues listed

**Comment by joeykrug** [comment]
Redesign. Nothing is happening on V1 besides sorts/filters now

**Comment by joeykrug** [comment]
Also, we’ll need to *sort/rank* categories and tags by the sort people are using.
Eg liquidity sort should sort all categories by sum of liquidity in each category and so on
