### ISSUE TITLE
Update OrderFilled & MarketCreated logs for use by `getMarkets` getter

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#1831]
This also entails updating the solidity-typescript generator, the FTS code & numerous tests.

**Comment by pgebheim** [comment]
@adrake33 -- Should this be in Review?

**Comment by adrake33** [comment]
@pgebheim ~~I created a PR for it, but I'm making more changes, so I'll move it back to In Progress~~
Never mind, you already did :)
