### ISSUE TITLE
Follow up candlestick chart issues

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1839]
associated with https://github.com/AugurProject/augur/issues/1602

- [ ]  add 1px rounding to candlestick bodies (not sure we can even do this, need to convert to full style mode)

- [ ] update the interaction styling showing exact date and eth - see design. These overlays should line up with the numbers behind them

- [ ] Fix spacing around top and bottom of x axis labels

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/d1b01f77-bbb8-45a3-aabf-3b34fac6b516)

left:build | Right: Design

**Comment by bthaile** [comment]
@Chwy5 these items weren't accomplished as part of the associated tix. I think this can be moved to v1.14. I'll do a style overhaul using highcharts `styleMode=true` configuration.

**Comment by Chwy5** [comment]
moving to 1.14
