### ISSUE TITLE
Use the MD5 hash of augur-state/src/contracts.json to tag docker:geth images

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#1840]
path should be augur-artifacts/src/contracts.json

Throwing in pg's notes on the issue:

  - Image tag should be based on MD5 of contracts, not the docker.json (update that tool)
  - after upload, should copy the addresses.json (scripts/copy-docker-files.sh)
  - builder, don't generate docker.json
  - builder, tag image based on md5 (use same tool as above)
  - Remove docker.json

**Comment by petong** [comment]
https://github.com/AugurProject/augur/pull/1843

**Comment by petong** [comment]
mostly done, just waiting on final PR that tags augur-core image with contract md5
