### ISSUE TITLE
cancel open order says `processing` when transaction hasn't been sent.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1841]
cancel-order needs to be smart enough to set pending tx only when tx is actually sent. 

We had the same issue in claim winning proceeds and claim fees and stake modals

example below
![2019-04-23 18 55 46](https://user-images.githubusercontent.com/3970376/56623350-812d4300-65f9-11e9-844d-a32a258a91a5.gif)

**Comment by cillianhunter0** [comment]
What was the fix for this? @bthaile

**Comment by bthaile** [comment]
there has been instances where the user thinks the tx is being processed but really the meta mask popup is hidden behind the web browser. 

So the tx isnt processing. Its only processing when it is sent. 

In two modals we changes (claim winnings and claim fees) to only say processing when the tx has actually been sent. Not just saying processing when they hit the button. Either approach doesnt really cover all cases. Probably need a “waiting” or “signing”  step.

**Comment by Chwy5** [comment]
approved

**Comment by bthaile** [comment]
this is fixed with addition of transaction lifecycle hooks.
