### ISSUE TITLE
When the docker image closes it looses contracts, logs, and markets

### ISSUE THREAD

**Issue by brianosaurus** [AugurProject/augur#1842]
The uploaded data to the chain needs to stay between sessions.

When I run a fresh docker image and call from augur-tools:
```sh
yarn dp all-logs
```

Nothing is returned. Then I have to
```
yarn dp upload
yarn dp create-markets
yarn dp all-logs
``

Then stuff comes back.

**Comment by petong** [comment]
if you run these commands from the repo it won't persist the data, those commands need to be called when the docker file is being built. try running these two commands from the top level of the monorepo:

    yarn docker:build:augur
    yarn docker:build:all

That will create the augur-build image, then augur-core, then the dev-pop-geth images (which is where the deploy happens).

it takes a bit of time for those commands to run, kick it off before you go to lunch ;)

**Comment by justinbarry** [comment]
As of now, CI seems to have all this data in place. @brianosaurus please re-open if you find the pop images lacking.
