### ISSUE TITLE
Market creation mobile 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1845]
Two issues to fix: 
- UI is displaying 2 columns on mobile, should stack elements as in design
- The reporting start time inputs - issue when touch target size it seems, if you tap around the edges of the input it doesn't open the dropdown menu 

Figma: 
(scroll to the right to see the review step mobile designs also) 
https://www.figma.com/file/csVtbWhGCAYe3nVe2LI1UEPM/Timezone-issue?node-id=181%3A1294

**Comment by JohnDanz** [comment]
I can't follow that mock in a reasonable amount of time because I would need to refactor this whole page pretty substantially to simplify the whole thing -- so refactor in 1.14 but for now ill just flow it into a column as best i can, but i some things will be grouped in a way that's not exactly as the mock has them, just a heads up @cillianhunter0

**Comment by bthaile** [comment]
@Chwy5 put this in v1.13

**Comment by cillianhunter0** [comment]
Looks better, 3 things that would help: 

Can we have all elements containers run to the green lines here:
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/7a6de929-db14-4d2d-b30d-62db1a89383f)

Can we make the text in these two inputs 2px smaller:
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/feb3bcaa-dafc-4e05-aff0-6f51be4e636b)

Can we eliminate this large gap, the same padding above the "market type" label ideally
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/85579a26-194b-400c-b9d3-e4b2c2d73ac1)

**Comment by bthaile** [comment]
Large gap is for scalar or categorical content. Removing the gap by default then the lower content will get pushed down when scalar or categorical is selected.

**Comment by cillianhunter0** [comment]
Removing the gap and pushing content down when needed is preferable

**Comment by bthaile** [comment]
@Chwy5 these tasks sound like perfect v1.14 tasks. Recommend putting in v1.14

**Comment by cillianhunter0** [comment]
agree, ok to push

**Comment by Chwy5** [comment]
Looks more than usable for 1.13 pushing tweaks to 1.14

**Comment by JohnDanz** [comment]
I can do this in a few min for 1.13, working on it now
