### ISSUE TITLE
Google Bot Follow Should Links to Market Pages

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#1847]
This is an extension of #854. Now that the page is generally crawlable we need to come up with the work items to make this actually do what we want for the market pages.

Adding this to the v1.15 Release, @bthaile -- this will perhaps convert to an epic once we can spec out the work.

**Comment by bthaile** [comment]
We need a different tix as the SEO epic and conver all bulk seo tix to smaller ones and put in the new SEO tix.

**Comment by joeykrug** [comment]
already subset of seo ticket
