### ISSUE TITLE
Implement SDAI usage

### ISSUE THREAD

**Issue by nuevoalex** [AugurProject/augur#1848]
Currently the implementation thought will be to still use DAI everywhere but while money is in escrow convert it to SDAI  and on exit send the interest accumulated to the reporting fee pool

**Comment by nuevoalex** [comment]
-Everything is denominated and done in Dai
-When Dai is escrowed into the system it goes into a funds contract
-The funds contract will convert received funds into DSR when DSR is "active"
-DSR is "active" when the rate is 1 or more maximum rate movements from 0%
-When funds are withdrawn the appropriate amount of DSR-Dai is convert back to Dai and withdrawn
-When a dispute window is created any accumulated interest in the funds contract is swept into the Reporting Fee Pool
-DSR "active" flag toggling can be triggered at any time and a successfull toggle will award X REP to the tx sender
-Toggling will succeed if:
  - The DSR is on and the rate is now < 1 maximum rate move from 0%
  - The DSR is off and the rater is >= 1 maximum rate movements from 0%

**Comment by pgebheim** [comment]
Dropping from the Milestone -- leaving this in Blocked though.
