### ISSUE TITLE
Replace "Ethereum not found" popup

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#185]
Most user-friendly replacement is to default to hosted, and have local available via a toggle switch or something.  This may be a bit contrary to our principles though; the next-most-user-friendly option is probably to have it default to localhost (if available), but seamlessly use hosted if not.

In either case, we should have an "only use local node" toggle switch on the site for people who are all about decentralizing-all-the-things.

**Comment by scottzer0** [comment]
My intention for the pop-up was to basically flip the logic and only have it popup if it detects a local node running.  The user would confirm that they wish to use the locally running instance and also if they wish to be the default in the future.  Some stats like connected peers and age of last block, current block, etc. might help the user make an informed decision.

**Comment by tinybike** [comment]
Replaced the modal with a seamless (I think...) fallback-to-hosted system in 5fe69fba5601d57564d672f0ecb49c5368bbae82.  Leaving this open if we want to expose a toggle or something to let the user manually select local/hosted.

**Comment by tinybike** [comment]
Closing this since we're going to be retiring the market caches soon.
