### ISSUE TITLE
Frozen Funds bug on self trade

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1852]
In the event a user trades with themselves....Frozen Funds is increasing. Causing Total Funds to increase as well.....I dont believe a users Frozen Funds should increase in this situation as they would have no position:

steps to take to test.

1) start with no position in categorical market.  add sell order to the order book. (only available balance and total funds should decrease at this point).  
2) Take your own offer - Frozen funds is increasing (along with total funds)

@joeykrug plz confirm expected behavior

**Comment by ryanberckmans** [comment]
First pass at thinking through how frozen funds might work when self-trading:

## self-fill to create complete sets

(after #1869 fixed)

1. start with no position in categorical market
2. add sell order to the order book
    1. frozen funds should increase by sell order escrowed ETH
    1. available balance should decrease by sell order escrowed ETH
    1. total funds should be unchanged (because total = available + frozen iirc)
3. take your own offer
    1. since we have no position in any outcome in this market, this self-filled trade will create new complete sets 
        1. Tom says v2 will change this: it's always non-preferable to make complete sets with yourself in a self-filled trade, but afiak Augur v1 has no special logic to prevent this, but v2 will just refund your ETH. So in v2 we expect different frozen funds / available / total
    1. frozen funds should increase by take order escrowed ETH. Intuitively you locked up more ETH to create the complete sets vs. just having an open order on the books
    1. available funds should decrease by take order escrowed ETH
    1. total funds should be unchanged
4. cancel the sell order on the order book
    1. frozen funds should decrease by escrowed ETH remaining based on quantity unfilled

## self-fill, sell shares to yourself for ETH (no complete set creation/destruction):

(after #1869 fixed)

1. add order to order book, escrow shares not ETH, no change to frozen funds or available funds
1. take your own offer by escrowing ETH, no change to frozen funds**[1]** or available funds
    1. because FF increases by "revenue" and decreases by "cost" but these are same number (escrowed ETH transferred to yourself). Same with available funds
    1. **[1]** in this example you start with shares, ie. position and FF start non-zero, so the self-trade will trigger a realized P&L event, so the actual frozen funds will _increase_ by the change in realized profit
1. works similarly if order on book escrowed ETH and the take escrows shares

## self-fill, destroy complete sets

(after #1869 fixed)

1. add your order to book, escrow shares, no change to FF or available funds
1. take your order by escrowing shares, frozen funds**[2]** decreases by order quantity in binary/categorical (where 1 complete set == 1 ETH in escrow); available funds increases by same amount
    1. **[2]** in this example you start with shares, ie. position and FF start non-zero, so the self-trade will trigger a realized P&L event (on both buy/sell sides), so actual frozen funds will _increase_ by the change in realized profit
