### ISSUE TITLE
Categorical outcomes are truncated to 32 chars

### ISSUE THREAD

**Issue by secret-bitcoin-login** [AugurProject/augur#1854]
Categorical outcomes are truncated to 32 characters after being submitted. They should be limited in the UI prior to submission so the market creator knows what data is actually stored. 32 characters may be a short limit for this field, it may be worthwhile to consider 64 chars.

**Comment by sharkcrayon** [comment]
@JohnDanz I'm assigning you here. This should be done post-launch. I'll create a CH ticket in v1.0.1.

**Comment by bthaile** [comment]
This is fixed, closing issue.
