### ISSUE TITLE
PnL Chart regression

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1854]
Think we fixed this and closed, looks like it went back to the old way....

0 eth needs to be solid line and dotted line needs to be the high/low or both.

****The starting pt needs to be at 0 and adjust based over time to the profit or loss...see screenshot for what it currently looks like

![4-25pnl.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/c42c4816-c9db-4787-adc7-a7ad9c07cfd4)

**Comment by bthaile** [comment]
PnL `all time` chart should start at 0. put in code for that

**Comment by Chwy5** [comment]
fixed - closing
