### ISSUE TITLE
Remove overlap on y axis chart markers

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1857]
Transparencies overlapping causing this:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f7d3e4ae-e2da-497f-b0ba-5f7b0c475083)

**Comment by Chwy5** [comment]
@matt-bullock is this ticket referring to the double dates When daily is selected?

**Comment by matt-bullock** [comment]
no it's just a very minor visual amend where the vertical lines should move down 1px so they don't overlap the horizontal line causing this:
![image](https://user-images.githubusercontent.com/39496225/57146831-9018b000-6dc6-11e9-9052-8cc3633c117e.png)
