### ISSUE TITLE
Made a market, it appears successfully, but still pending above

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#186]
![screen shot 2015-09-22 at 5 10 08 pm](https://cloud.githubusercontent.com/assets/5925937/10033089/df69c9da-614c-11e5-82aa-9fd63a0355d5.png)

**Comment by tinybike** [comment]
Does this still happen for you on http://development.augur.divshot.io/?  I made a few different market combinations and the "pending" pane always seems to get cleared ok for me.

**Comment by joeykrug** [comment]
No it seems to be fixed after latest update
