### ISSUE TITLE
augur-core, augur.js, and augur-ui don't conform to same build structure

### ISSUE THREAD

**Issue by brianosaurus** [AugurProject/augur#1865]
All packages in the monorepo should have the same structure so that commands are consistent, there is less confusion, and builds happen seamlessly.

augur-cure, augur.js, and augur-ui do not conform to the standard build structure that the other packages use. At a bare minimum, packages should build into a build directory with an index.js built there.

package.json should start with (as an example):

```json
{
  "name": "@augurproject/ethersjs-provider",
  "version": "1.0.0-0",
  "description": "Ethers.JS Provider Implementation for Augur API",
  "author": "The Augur Developers <team@augur.net>",
  "license": "MIT",
  "main": "build",
  "directories": {
    "src": "src"
  },
```

This structure will put files into the build directory. Similarly, tsconfig.json should look like:
```json
{
  "extends": "../../tsconfig-base.json",
  "compilerOptions": {
    "outDir": "build",
    "rootDir": "src"
  },
  "include": [
    "src/**/*"
  ],
  "references": [
    {
      "path": "../augur-api"
    },
    {
      "path": "../augur-artifacts"
    },
    {
      "path": "../contract-dependencies"
    },
    {
      "path": "../contract-dependencies-ethers"
    }
  ]
}
```

This structure will allow commands like 
```sh
yarn workspace @augurproject/node build
```
to build not only the named package but also packages that the named package depends upon if needed.

As an example, if I modify a file in augur-api/src and run 
```sh
yarn workspace @augurproject/node build
```
it will not only build what's needed in augur-node but also the modified file in augur-api.

**Comment by pgebheim** [comment]
For augur.js the build dir isn't necessary, as its already Javascript. The entrypoint in package.json is pointed at `src` and importing this module doesn't end up with any problems.

Both augur-core and augur-ui have `build` already, but let me point out some details:

Our goal should be to have nothing should to *remove the dependency on augur-core*. Dependencies should move somewhere else (e.g. the deployer perhaps should move into `tools`), and then all we need to do is depend on `augur-artifacts` and `augur-tools`. The augur-core build directory is called `output` which is indeed a little wonky, but again is solved by package.json pointing there. That said, if we could remove the TS dependencies from being in augur-core it would be a great help.

Augur UI does have the normal build command, and it produces minified artifacts capable of being imported from webpack... don't really see the issue there.

**Comment by pgebheim** [comment]
I'm gonna close this because while its true, I think we solve it with a few other tickets.

I'll mention them here.
