### ISSUE TITLE
Frozen funds does not update on open orders

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1869]
when placing an open order Available Funds decreases by escrowed amount + gas, Frozen Funds stays the same, and Total decreases by available amount.  FF needs to increase to offset the decrease in available, so Total should be the same as the starting amount - the gas fee.

**Comment by bthaile** [comment]
@Chwy5 moving this over to `Design Review` for testing

**Comment by Chwy5** [comment]
closing - needs to be retested from scratch for v2
