### ISSUE TITLE
portfolio blows up, when processing user positions

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1871]
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/2a2393dc-673d-4615-9b18-4167d90b351d)

caused this issue when optimizing market selector.

**Comment by Chwy5** [comment]
approved

**Comment by Chwy5** [comment]
works on dev...still not working on the other

**Comment by bthaile** [comment]
pete is looking into the issue where try.augur.net doesn't behave the same as dev.augur.net
