### ISSUE TITLE
augur-state: build market order book

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1872]
The UI spend considerable effort in building the order book. it cycles through all the orders to combine them based on price. 

This effort can be quicker if augur-state builds the order book and UI requests it, in the perfect shape, whenever there is a filled order or new/cancelled open order. 

(bonus, needs discussion)
Another approach/optimization would be augur-state sends the new order book on the log.

**Comment by bthaile** [comment]
we could prob get this done in v1.14.

**Comment by Chwy5** [comment]
approved
