### ISSUE TITLE
market creation depth chart / order not visible

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1874]
![2019-04-25 14 25 30](https://user-images.githubusercontent.com/3970376/56762694-0c2b4c00-6766-11e9-98e7-23a308e7e6e6.gif)

**Comment by bthaile** [comment]
@Chwy5  we need to fix this for v1.13

**Comment by Chwy5** [comment]
approved

**Comment by Chwy5** [comment]
better-closing
