### ISSUE TITLE
Acct Summary crash

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1877]
Steps to reproduce....

1) report on an open reporting market...after hitting submit on mm, I immediately click on the Acct sum pg (before reporting confirms) and console blows up...

see screenshot:

![4-25report.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/a7d38faa-f135-41e7-aabc-4d481ffda6cf)

**Comment by bthaile** [comment]
issue where we load reporting information before market info on markets that are initially reported or or disputed.

**Comment by Chwy5** [comment]
fixed - closing
