### ISSUE TITLE
when number of markets with orders and number of orders is equal there is a bug in the orders boxes

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1878]
it doesn't show the orders when switching to the outcome view

![Screen Shot 2019-04-25 at 1.02.59 PM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/a21dd6ed-2e2f-4f46-95f2-af7f46b0261a)

**Comment by bthaile** [comment]
@Chwy5 recommend for v1.14

**Comment by bthaile** [comment]
@Chwy5 this blocks other testing going ahead and fix it.

**Comment by Chwy5** [comment]
approved
