### ISSUE TITLE
sort by bug

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1879]
1. switch to view by outcome
2. search
3. cancel search
4. it says view by market but it is viewed by outcome

![Screen Shot 2019-04-25 at 1.25.04 PM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/9e712f85-8987-49c1-9743-c1b848b4a159)

**Comment by bthaile** [comment]
@Chwy5  recommend for v1.14

**Comment by bthaile** [comment]
@Chwy5  this blocks other testing, going ahead and fix it.

**Comment by Chwy5** [comment]
approved

**Comment by Chwy5** [comment]
fixed closing
