### ISSUE TITLE
The /markets endpoint page should only show active markets

### ISSUE THREAD

**Issue by Frankenmint** [AugurProject/augur#189]
Perhaps show all closed markets on a different endpoint like closed or past markets?

**Comment by scottzer0** [comment]
i think this would be a better experience.  the matured market really are just noise to users browsing markets.

matured markets really only need to be there to review for a while and to allow the author (and perhaps others) to close it.  an authors markets should show up on their overview page as well.

**Comment by priecint** [comment]
Closed by b60c9f178cb, there is /markets for active and /markets?expired=true
