### ISSUE TITLE
Delays/missed keystrokes when typing in modals

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#190]
Moved from AugurProject/augur.js#47, since augur.js just handles the username/password once they're submitted.  This affects the market creation modal as well.

I suspect the underlying issue here is excessive network I/O.  My reason for this is that this problem is intermittent but more-or-less regular, and seems to coincide with block arrivals (which initiate a series of direct-to-geth RPC requests).  One solution might be to just avoid sending any read operations to geth, and get everything from the cache instead.  Another solution could be to throttle network traffic: when I manually turn on throttling in Chrome's network panel, this problem seems to go away.

**Comment by scottzer0** [comment]
i think batching/trimming the onBlock update calls would probably make this a non-issue.

**Comment by thinkloop** [comment]
Hello, 

To be sure is this regarding the client at http://client.augur.net/markets?

Is an example of one of these misbehaving text modals the one that appears when clicking "Submit a Market"? 

Are there other examples?

Best,
Baz

**Comment by tinybike** [comment]
If you click "Register" or "Sign in", this happens in the username/password fields, as well.

**Comment by tinybike** [comment]
I can no longer reproduce this; guessing it was inadvertently fixed while optimizing augur and/or augur.js.
