### ISSUE TITLE
use current block as highest block in `blocks behind` calculation

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1907]
we shouldn't use highest block from augur-node we should use current block from augur.js/ethrpc. Just in case connection to augur-node stales or gets laggy.

This way user will actually know how many blocks they are behind.

added bonus, just get sync data every other block. it will cut down chatter with augur-node. the down side is the user will see 1 block behind every other block. I don't think that is a big issue for v1.

**Comment by bthaile** [comment]
changes on `issue-wrong-blocks-behind` branch.

**Comment by bthaile** [comment]
@Chwy5 we can bring this in v1.13 as a performance improvement or push to v1.14. If we all agree with the change.

**Comment by pgebheim** [comment]
I don't think this is a great plan. If the augur-node connection is screwed up then they won't be able to get any of the data for those newer blocks anyway, and although we may do some basics (e.g. show that a transaction was sealed) none of the other UI state would respond to it.

**Comment by bthaile** [comment]
At least the blocks behind will increase to give an indication something is wrong. I think its an edge case. But if augur-node is laggy user will jist get behind and not know it.

**Comment by Chwy5** [comment]
@pgebheim @bthaile putting in 1.14 for now....lets discuss before deciding on whether to move forward with this...putting in needs feedback

**Comment by bthaile** [comment]
based on current discussion in #issues I think we need to work this for v1.13. @pgebheim thoughts.
*meanwhile I'll move to v1.13*

**Comment by pgebheim** [comment]
Agreed. Get ‘er done!

Paul Gebheim
paul@augur.net

**Comment by Chwy5** [comment]
im seeing 4 blocks behind...doesnt seem right

**Comment by bthaile** [comment]
* need to take out getSyncData every other block.
* need to not let blocks behind go negative

**Comment by Chwy5** [comment]
looks good - closing
