### ISSUE TITLE
fill orders race condition

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1910]
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/7ef2ecd9-ee5d-4bbd-a97f-37ee8366016e)

If user quickly clicks on Portfolio there is a race condition where the filled orders are loaded but not all the markets info.

Need to add marketsData state selector to select-markets-filled-orders. 

A similar issue can occur, if one of your orders is filled, only that market's filled orders will show up in portfolio filled orders.

**Comment by bthaile** [comment]
@Chwy5 found an issue where filled orders can go blank or not fully get populated. I think you were seeing this.

**Comment by Chwy5** [comment]
approved

**Comment by pgebheim** [comment]
@bthaile -- I think this was supposed to go to closed?

**Comment by bthaile** [comment]
@Chwy5 can you verify. You arent seeing it.

**Comment by pgebheim** [comment]
he commented "Approved" and then moved it to incoming

**Comment by bthaile** [comment]
He approved the work to be done, not verified the work is a solution to his issue.

**Comment by Chwy5** [comment]
This was approved to be worked on....I am currently not seeing this, but this didnt have known steps to reproduce, but has happened 3 separate xs last week...needs to be investigated....this is related to the missing Filled orders/My fills

**Comment by bthaile** [comment]
We found the issue and fixed this. To confirm, have a another account take you order and confirm that all filled orders are still in the portfolio filled orders list.

**Comment by Chwy5** [comment]
closing
