### ISSUE TITLE
order book bug

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1911]
<img width="346" alt="Screen Shot 2019-04-25 at 5 02 41 PM" src="https://user-images.githubusercontent.com/6775839/56775686-19076a00-677d-11e9-8e00-1cc28840516f.png">

i think this happened when pressing backspace in the price field!!!!

valid order but the button doesn't not light up

1. clicked on order in the book (that was mine)
2. increased price
3. then switch to sell 

happened in a few different cases, not sure the other reproductions

https://try.augur.net/#!/market?id=0x599c4cdee0dc31b7c21e89c3352bc1b6afb40ed6
clicked on the order and then did backspace and typed .4

**Comment by Chwy5** [comment]
It is not doing it for me.....what it looks to me from the screenshot above is that the numbers didnt update....your total order value is still showing the same amount as if it was a sell order....
it should show .003 for a buy order

**Comment by phoebemirman** [comment]
happens to me on most markets 

this one for example:
https://try.augur.net/#!/market?id=0x75ec1f1a3356517908eccb5f6e4fac619c68ba99
1. select first offer in order book
2. backspace in limit price
3. enter valid order price
4. nothing happens
