### ISSUE TITLE
Market creation mobile - styling issues 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1914]
Fix header
Build
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/8078e5d5-93db-4fae-93c6-6610b922a808)
Design
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/766a1d09-6f47-4039-a49b-a0a4a682bf9b)

Reduce font size of radio buttons to 14px: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/78b04b81-6276-445f-9a53-252fbfdad029)

**Comment by bthaile** [comment]
closing this, market creation redesign has changed and has new responsive designs
