### ISSUE TITLE
Logout won't collapse for non MM logins 

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1915]
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/ce3ce2f9-64e7-42f2-86ae-00b0dc008c2b)

Since MM is down, I've been testing with Edge and Ledger and both the `logout` won't collapse.

**Comment by bthaile** [comment]
@Chwy5 I think we need to work this one.

**Comment by Chwy5** [comment]
approved

**Comment by Chwy5** [comment]
closing
