### ISSUE TITLE
Yes outcome on mobile disappears

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1916]
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/74ae69ef-26a6-4674-ac76-df3f187a13b8)

to repro:

1. coinbase mobile on iPhone
2. go to market trading page
3. go to trade page
4. scroll all the way down then back up
5. notice that `Yes` outcome has disappeared

**Comment by bthaile** [comment]
@Chwy5 this can be worked in v1.14, imo

**Comment by JohnDanz** [comment]
It actually hasn't disappeared, it's just not picking up styling correctly. I'm seeing it fine on local desktop/mobile responsive view but on coinbase i can see that it's still unstyled at try.augur.net. Is try up to date?

The other strange thing, if you interact with the page (like flipping between trade history and order book) it reappears. I'm going to see if i can find a way for it to be more consistent.

**Comment by bthaile** [comment]
https://github.com/AugurProject/augur/issues/1934

More screen shots in the tix above. Going to close the other tix

**Comment by Chwy5** [comment]
@bthaile noticed the gap is gone, but still seeing outcome disappear...had to scroll up and down a few x's to trigger it, but still disappeared

**Comment by bthaile** [comment]
tested on dev and try.augur.net. Still an issue. We need to figure out a better way to test before pushing up changes. @JohnDanz 
Thoughts on how to test to verify without pushing up?
Could host locally and make available over local private network and point coinbase wallet at it.

**Comment by JohnDanz** [comment]
So the real problem here is that it's still being drawn, it's just somehow not staying on top unless you take some action on the page. I think this is a safari/coinbase wallet browser issue but i'm not sure how I can force it to stay on top but i'll see if anyone else ran into this on google.

**Comment by andrewdamelio** [comment]
I don't see this issue on my iPhone 🤔 are you testing on android?

**Comment by JohnDanz** [comment]
I'm going to do the ticket to update the mobile outcome name to closer match the mock (semi-transparent background, allowing scroll to happen under the component) which hopefully will fix this issue due to a re-layout of the components that hopefully doesn't produce this drawing issue. This is the ticket I'm referencing: https://github.com/AugurProject/augur/issues/1768
