### ISSUE TITLE
trade history has no scroll cut off 

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1917]
<img width="1497" alt="Screen Shot 2019-04-26 at 9 52 31 AM" src="https://user-images.githubusercontent.com/6775839/56823545-076ba400-6809-11e9-8b12-d002ade8181d.png">

**Comment by bthaile** [comment]
@Chwy5 this is easy fix, won't break anything. dev is in the code. can we fix in v1.13

**Comment by Chwy5** [comment]
approved

**Comment by Chwy5** [comment]
Mine is contained - what are you viewing this on?

**Comment by phoebemirman** [comment]
i see it on dev and master. the market has to have lots of data in trade history

**Comment by Chwy5** [comment]
mine does...doesnt look like that

**Comment by Chwy5** [comment]
appears to be caused by chromes latest update....old versions show correctly

**Comment by Chwy5** [comment]
closing
