### ISSUE TITLE
market trade history doesn't load when refreshing when logged out.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1918]
how to repro:

nav to market trading page not logged in
refresh page, notice that market trade history doesn't load

**Comment by bthaile** [comment]
@Chwy5 need to work this in v1.13, imo

**Comment by Chwy5** [comment]
approved

**Comment by phoebemirman** [comment]
i also noticed that if i am logged in on a market trading page and then i log out, then a lot of the market info disappears https://github.com/AugurProject/augur/issues/1921

<img width="1557" alt="Screen Shot 2019-04-26 at 11 09 51 AM" src="https://user-images.githubusercontent.com/6775839/56827485-d775ce00-6813-11e9-96db-8f4edbf74065.png">

**Comment by Chwy5** [comment]
fixed - closing
