### ISSUE TITLE
Section headers are dark/unreadable

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1919]
![Screen Shot 2019-04-26 at 10.33.11 AM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/c69e4364-88c7-4b5d-9475-b183e58e259b)

<img width="1568" alt="Screen Shot 2019-04-26 at 10 33 06 AM" src="https://user-images.githubusercontent.com/6775839/56825720-d0988c80-680e-11e9-95bd-c4570544487b.png">

**Comment by Chwy5** [comment]
Mine look fine on both Windows desktop and Macbook... see screenshot

![4-27.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/20e49e2a-543b-49c4-beb5-24347672e8ab)

**Comment by cillianhunter0** [comment]
I'm seeing the same thing as Phoebe, seems like the text color is set to the same color as the background 

chrome on mac: 73.0.3683.103

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/37eaea9b-a2a9-4eb2-94f3-fa8ba4d3ad2b)

**Comment by Chwy5** [comment]
so weird...cillians looks like yours phoebes....I asked cillian to comment will make adjustments

**Comment by cillianhunter0** [comment]
Did a hard refresh and now I can see it: 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/0a524b98-d937-4f29-9c4f-d83f665d6ceb)

**Comment by phoebemirman** [comment]
i already did this

**Comment by Chwy5** [comment]
@cillianhunter0 please confirm if yours still looks like this...close if better

**Comment by cillianhunter0** [comment]
Fixed
