### ISSUE TITLE
market reporting states should be right aligned in my markets list

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1925]
![Screen Shot 2019-04-26 at 8.49.37 PM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/0b287bde-37e1-47e9-8397-0b4b8dfd4d16)

<img width="710" alt="Screen Shot 2019-04-26 at 8 49 29 PM" src="https://user-images.githubusercontent.com/6775839/56844434-eb95eb80-6864-11e9-9461-74dc72a53714.png">

**Comment by Chwy5** [comment]
@matt-bullock @cillianhunter0 plz confirm

**Comment by cillianhunter0** [comment]
Yes, should be right aligned

**Comment by matt-bullock** [comment]
Yep
