### ISSUE TITLE
Market Trading Page Sorting

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1927]
This tix will contain Open orders, Filled orders and Positions. Since there isn't any sorting options on market trading page this tix will handle all of them.

They need to be in descending order by creation date. Another way of saying it newest at the top.

Positions section sort by outcome id, so the positions are in the same order as outcomes list.

**Comment by phoebemirman** [comment]
positions- yes
filled orders- no
open orders- no

putting fix in a PR

**Comment by Chwy5** [comment]
Open orders doesnt look to be updating by newest on top....it is currently grouping each outcome in a categorical together...so in  a cat 3 market, all A's are together, all b's are together, all c's are together....If i add a c it does put the c on top of the c's....but this should go to the top of all the outcomes

**Comment by joeykrug** [comment]
status?

**Comment by joeykrug** [comment]
reping on this one

**Comment by bthaile** [comment]
We need to re-address open orders. Not sure we have the same creation time the on-chain orders had.  We can use salt for open orders, make a mod to zeroXOrdersGetter.

@phoebemirman can you verify that positions and fills are ordered correctly?

**Comment by joeykrug** [comment]
yeah should use salt
