### ISSUE TITLE
Portfolio Positions Sorting

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1928]
There are 4 sorting options:

* Sort by Most Recently Traded
  - sort by most recent trade, not user trade any trade on the market
* Sort by Current Value
  - sort by the current value, meaning current market aggregation unrealized position value
* Sort by Total Returns
  - sort by total returns, meaning user's total value, includes unrealized and realized.
* Sort by Expiring Soonest
  - sort by the market's endTime sooner it expires it's at the top, already expired markets should be at the bottom in recently expired to not recently expired. 

default is `Sort by Most Recently Traded`

**Comment by phoebemirman** [comment]
Recently traded, total returns, current value is good, Expiring soonest is wrong for positions. Putting this in a PR. 

we also don't have backup sorts for if some of these are equal, like if total returns are equal on two markets we haven't defined what order they would show in.

**Comment by Chwy5** [comment]
looks good - closing
