### ISSUE TITLE
Portfolio Open Orders Sorting

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1929]
Portfolio open orders section, it only has one sort method but two views

* Sort by most recently traded market, not by the logged in user. The most recent market that has a trade should be at the top of the list.

  - View by Most Recently Traded Market
  - View by Most Recently Traded Outcome

**Comment by phoebemirman** [comment]
added fixes to PR

**Comment by phoebemirman** [comment]
for this view:
<img width="764" alt="Screen Shot 2019-04-29 at 3 54 38 PM" src="https://user-images.githubusercontent.com/6775839/56932088-3f881680-6a97-11e9-9c92-8ecb917fcb78.png">

should individual orders still be grouped by markets?
