### ISSUE TITLE
Portfolio My Created Markets Sorting

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1930]
My Created Markets sorting in Portfolio page has three options:

* Sort by Expiring Soonest
  - Markets that will expire soonest should be at the top, markets that most recently expired should show up after. Markets that have long expired should show up at the end.
* Sort by Most Recently Traded
  - sort by most recent trade on the market, not by the user but any trade.
* Sort by Creation Time
  - sort by creation time, most recently created markets should show up at the top. Markets that were long past created should show up at the bottom.

default is `Sort by Expiring Soonest`

**Comment by phoebemirman** [comment]
this is done correctly

**Comment by Chwy5** [comment]
looks good closing
