### ISSUE TITLE
Account Summary Watchlist

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1933]
Watchlist on Account Summary has three sort options:

* Sort by Most Recently Added
  - sort by most recently added to the list, recently added are before those added in the past.
* Sort by Market Creation
  - sort by market creation time, newest markets are at the top, older markets are below.
* Sort by Expiring Soonest
  - Sort markets that are about to expire, markets that are about to expire should be at the top of the list. markets that have expired should be below markets that have not expired yet, markets that have long expired should be at the end of the list.

**Comment by phoebemirman** [comment]
recently added, creation time is good, putting expiring soonest in a PR

**Comment by cillianhunter0** [comment]
I haven't been able to properly test this, I found a bug on the watchlist, see: 
https://app.zenhub.com/workspaces/augur-5bfed3424b5806bc2bf8d173/issues/augurproject/augur/1968

**Comment by joeykrug** [comment]
Status?

**Comment by Chwy5** [comment]
this was fixed - closing
