### ISSUE TITLE
Yes Outcome creates gap on scroll

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1934]
below are examples of the gap, this effects categoricals as well. Scalar markets I've seen the denomination value disappear on scroll. i think we are trying to get too fancy and the outcome should be sticky. This might only be an issue on iPhone/safari. I think it's bad enough we need to address in v1.13 since we are making a high effort to be mobile friendly.

![IMG_3486](https://user-images.githubusercontent.com/3970376/56871195-02148200-69e0-11e9-8daf-50b32b4eca71.jpg)

![IMG_3488](https://user-images.githubusercontent.com/3970376/56871197-05a80900-69e0-11e9-8953-096355499b04.jpg)

![IMG_3487](https://user-images.githubusercontent.com/3970376/56871200-093b9000-69e0-11e9-8ad3-ef44423f6a2a.jpg)

**Comment by Chwy5** [comment]
Approved...I believe we have another ticket related to this already... @bthaile plz check ticket 1916 and close or combine

**Comment by bthaile** [comment]
Referencing other tix. Closing this one.
