### ISSUE TITLE
Account summary profit and loss chart doesn't show

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1935]
Profit and Loss chart doesn't show on coinbase wallet. Needs investigation

![IMG_3489](https://user-images.githubusercontent.com/3970376/56871315-ac40d980-69e1-11e9-8cdd-494a10dbc3c7.jpg)

**Comment by Chwy5** [comment]
approved....mine looks correct...need to investigate why yours is off

**Comment by Chwy5** [comment]
After confirming different devices...it is iphone specific

**Comment by JohnDanz** [comment]
doesnt appear to be the case anymore
