### ISSUE TITLE
Speed up communication with local geth

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#194]
**Problem:** the client uses direct-to-geth RPC requests when a user is running a geth node on localhost.  However, due to the excessive number of HTTP requests this requires, the client is essentially unusable with a local geth node (~5 minutes to fully load markets on my laptop).

**Proposed fix:** geth supports IPC (via domain sockets on *nix and named pipes on Windows), which should be much faster than HTTP RPC.  As of AugurProject/ethrpc@59af082fc4a559170b4ea95ed1fe761c775402a9, ethrpc supports IPC via Node.js's `net.Socket`.

**Caveat:** IPC is not usable from the browser, so it will require a server-side process.  This process will exist solely to get/process data from geth over IPC.  The server-side process will only exist on the desktop version.  Mobile users will not be running full ethereum nodes locally on their phones, so the mobile version will continue to be served as a purely client-side application.

**Comment by hitchcott** [comment]
Hi, just randomly read this issue and you may have already tried this but would batching the requests help? https://github.com/ethereum/wiki/wiki/JavaScript-API#batch-requests

**Comment by tinybike** [comment]
Yes, this is already implemented.  It does help, but unfortunately not enough!

**Comment by tinybike** [comment]
Implemented get-all-possible-info-about-this-market method to the markets contract (along with essentially infinite "gas") in 49988231a994f65c95a5d479f555e8dfbbd15370.  Marking this solved for now...
