### ISSUE TITLE
V2 end date cut off messaging

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1942]
When we transition to Augur v2 there will be a cutoff date where we release v2 once all markets ending before that cutoff have finalized. 

We want to prevent users from creating new markets and encourage users not to trade or report on markets that expire outside of the cutoff date. Most users and REP will migrate to Augur v2, putting any REP and ETH staked on these new markets in v1 at risk.  

**Scope of UI updates:**
Market creation
- Add messaging to Market Creation telling users what the cutoff is 
- Date Input - prevent new markets from being created post cutoff

Trading page 
- Add messaging to any markets that end post cutoff

Market list page 
- Add messaging to Market cards [current] for any markets that end post cutoff 
- A default filter which filters out any markets made past the cutoff date
   - Unless user has a position in one of these markets 

Reporting:
- Add messaging to markets that end post cutoff 

Global
- When the cutoff date hits - display global banner telling users not to trade etc

Content
- We'll need a post on Augur 
   - Should this be on docs.augur.net? a direct, clear explanation of what's going to happen / the risks involved in these markets etc 

Status: 
- [ ] **Design solution**
    - [x] Scope the solution, what’s in, what’s out
    - [ ] Design for desktop 
    - [ ] Review & iterate
    - [ ] Design for mobile 
    - [ ] Finalise 
- [ ] **Write it up**
    - [ ] Write GitHub tickets for the UI team
       - [ ] Break the piece of work down into logical groupings for dev
       - [ ] Describe behaviour  
    - [ ] Walk-through with dev

**Comment by pgebheim** [comment]
Add another UI scope PROPOSAL: Add a default filter to filter out markets from the market list that are beyond that END date, but allow that filter to be toggled off.

This is an amendment to the bits in "We won't" the we should consider.

**Comment by Chwy5** [comment]
If the filter gets toggled off a warning message should appear before proceeding
