### ISSUE TITLE
UI allows user to select date in the past when creating market.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1943]
Noticed that UI date picker and time dropdowns allows the user to pick a End Time in the past. The create market will fail.

**Comment by bthaile** [comment]
I think this is minor issue since users will create markets that end days from creation or weeks. 

We might want to help the user not create failing transactions.

**Comment by Chwy5** [comment]
@bthaile mine doesnt allow me to pick an end time in the past

**Comment by Chwy5** [comment]
approving this...maybe your seeing something i am not

**Comment by bthaile** [comment]
this has recently been fixed.

**Comment by Chwy5** [comment]
fixed-closing
