### ISSUE TITLE
Send funds styling 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1949]
Remaining issues on the send funds modal: 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/cde0308b-8f76-4be5-bb1c-2e9d0d2c30af)

**Comment by pgebheim** [comment]
@cillianhunter0 @bthaile moving this into Sprint 15 misc, should QA it then.

**Comment by bthaile** [comment]
closing since there has been more redesign work on account sum page / transaction section
