### ISSUE TITLE
A search field on the markets page that filters down the markets as you type in

### ISSUE THREAD

**Issue by Frankenmint** [AugurProject/augur#195]
Bonus feature:  give is wildcards and [mkt:closed] style capabilities longer term so that you can really pin down what you want in a landscape with 10K plus markets.  

I would create a textfield that would apply a filter based on *%sss* logic  so that typing in the first three letters would give immediate feedback in the form of filtered down results.  I would do this with something like emit.onChanged or something of that sort for the search field.

**Comment by tinybike** [comment]
Duplicate of #153.
