### ISSUE TITLE
Remove the "view details' button for claim proceeds to a market when its in the 3 day wait period- replace w (i)

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1950]
Remove the "view details' button for claim proceeds to a market when its in the 3 day wait period  and the countdown clock is present....

I found it confusing to click view details and all it does is bring me to the trading pg

We should instead add an (i) and explain what is happening as to why the countdown clock is there and they cant actually claim their proceeds at that moment

**Comment by andrewdamelio** [comment]
doesn't apply - no wait period in v2 
@pgebheim
