### ISSUE TITLE
in market creation, single category options still have a comma next to them

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1951]
![Screen Shot 2019-04-30 at 9.16.27 AM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/4fc103ff-19a1-4f7c-ba43-f1e092f5d8a1)

**Comment by andrewdamelio** [comment]
closing -- this doesn't apply in v2 -- new create designs being used.
