### ISSUE TITLE
null state not handled when nav directly to market

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1952]
![Screen Shot 2019-04-30 at 11.39.52 AM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/f9ed1214-5d6c-4bc1-95d4-e605da7633d2)

nav directly to <https://try.augur.net/#!/market?id=0x42acbee5124689be980006d89081be2dacc997f9>

**Comment by Chwy5** [comment]
approved
