### ISSUE TITLE
Seeing closed position when i have no position

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1962]
I added an open order and then cancelled the open order (nothing traded)....I am seeing a closed position showing 0.0000 in every column....

Also on the portfolio pg seeing Open position ith the same 0.0000 under every column

I should have no position at all and my positions should jsut be empty

![5-1.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/dbf822f8-c6b6-47c5-9ab0-f019c02236b5)

**Comment by bthaile** [comment]
@Chwy5  Not able to repro.  was this on a specific type of market?

**Comment by Chwy5** [comment]
I see it on 4 markets...2 binary, 1 scalar and 1 categorical....
to reproduce start with a new acct...place an open order on an existing market (I place 3 open orders on the cat 3 market, 1 on each outcome)...then cancel the orders...dont do any trading

it leaves all these closed markets that show all 0.000s except for the last trade price in the market...see screenshot..

![5-1closed](https://user-images.githubusercontent.com/41301809/57051471-a9e3b700-6c4f-11e9-8e06-2b81bca96ce8.jpg)

**Comment by bthaile** [comment]
not an issue in V2, closing
