### ISSUE TITLE
Watchlist - markets are removed 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#1968]
No markets are appearing in my watchlist. 

If I add some markets to the list using the star and navigate to account summary they will be in the watchlist panel. If I then refresh, and navigate back to the account summary, they are gone. 

I refresh at the 14 second mark: 
https://drive.google.com/open?id=1dhzMolg1y9I7xb4ESa9GIy7m7ndZUzmu

**Comment by bthaile** [comment]
not able to repro, closing
