### ISSUE TITLE
UI Integration w/ v2 API

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1969]
multiple phases to get augur UI and augur-node getters migrated to all typescript typed methods.
Removing the use of `submitRequest` to typed methods.

Phase I: get existing submitRequests working for augur UI gets data from augur-node

Phase 2: use interfaces on augur-ui side so all responses use @augurproject/node interfaces

Phase 3: all augur-node calls will be typed methods, example would be

```
  await winningBalance: WinningBalance = 
    augur.augurNode.getWinningBalance(new WinningBalanceParams(marketIds, account))
```

Phase 4: to be in different epic, switch out augur.augurNode with augur.state...

**Comment by joeykrug** [comment]
status?

**Comment by bthaile** [comment]
This epic can be closed the two remaining item can be moved off, they can be worked separately from this large effort. 

augur-node and augur.js have been removed from UI. Integration with SDK is done, backend is working on stability and getters which have their own tix and epics.
