### ISSUE TITLE
I was able to buy from a closed market after the deadline @ 0:00 on the 1st day of the new month

### ISSUE THREAD

**Issue by Frankenmint** [AugurProject/augur#197]
I saw all markets, even closed ones from before had been open on localhost, so I quickly threw in 100 cash on this bad boy and it filled! 

http://puu.sh/kutk9/4f7d23d571.png

Pretty sure I was using client.augur but I might have been using divshot - I was in the middle of testing other things and the window presented itself for me to buy so I decided to buy and see if it would throw an error, but it didnt...http://localhost:8080/market/-3c535ace746d6285fb423ed6441eca82f91013217e7baf481c66c6caccfe75e5

**Comment by Frankenmint** [comment]
Using localhost build today I've now seen the behavior a couple times and its that all markets aren't mature for a few moments then the filters are shown on them.  Seemed to allow me to purchase well expired shares though

**Comment by joeykrug** [comment]
This isn't actually a bug, markets allow trading until resolved by reporters.  UI should handle this in some more intuitive way though

**Comment by dstadulis** [comment]
@Frankenmint This behavior is intensional (though maybe warrants a warning message to the user) as it allows users to cash out before having to wait an extended period of time for the market to be settled by reporters.

**Comment by tinybike** [comment]
Closing this b/c this isn't a bug (agree there should be better UX for this though).
