### ISSUE TITLE
Start up UI dev env

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1973]
yarn commands to start up correct docker image

yarn command to start up augur-node

yarn command to build and start up augur-ui

verify that augur-ui hot loader works. Doesn't reload web browser only re-builds.

**Comment by justinbarry** [comment]
In separate terminal windows: 
```
yarn build -w

yarn workspace @augurproject/tools docker:geth:pop-15

yarn workspace @augurproject/node start

yarn workspace @augurproject/ui dev
```
