### ISSUE TITLE
Look into IPFS for market cache

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#198]
Because we're too forward-thinking to limit our filesystem to just one planet.

**Comment by jbenet** [comment]
Happy to help wherever. feel free to tag me as you figure things out, or open issues in https://github.com/ipfs/notes/ if you want to think something through.

**Comment by tinybike** [comment]
IPFS isn't quite at the point where it's useful for this; closing for now.

**Comment by jbenet** [comment]
Curious what the use case here is? What would make IPFS useful?



—

**Comment by tinybike** [comment]
Well, I was thinking of using IPFS for was storing pre-processed market data (because gathering it via many small HTTP requests to Ethereum takes too long).

The main issue with this is that the market data isn't completely static, so its hash changes.  IPNS seems like it would be the perfect solution to this (just map the market's ID to the current data hash), but for me at least `ipfs name resolve` takes 30+ seconds to complete.

The other (maybe bigger!) thing is that we discovered there's a somewhat-obvious-in-retrospect way of doing this pre-processing on Ethereum itself, essentially for free!  So, might as well keep it simple; fewer moving parts = better (even if the moving parts are otherwise very cool things).
