### ISSUE TITLE
Add a default filter which filters out any markets that end past the cutoff date - on market list page

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1980]
Filter should not be selected as default if a user holds a position in a market that expires after the cutoff

**Comment by matt-bullock** [comment]
Designs can be found on 'Market List' page of this doc

https://www.figma.com/file/csVtbWhGCAYe3nVe2LI1UEPM/v1-updates-to-the-UI?node-id=300%3A8313

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/03c84bb0-2a16-41b5-aeec-67dcc5dee102)

**Comment by andrewdamelio** [comment]
This needs augur-node changes, will update the state of this ticket once that has been completed.

**Comment by Chwy5** [comment]
added - closing
