### ISSUE TITLE
Flag on market cards

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1985]
Market list page
- Flag on the market card, on hover shows a tooltip with messaging and link to post
https://www.figma.com/file/csVtbWhGCAYe3nVe2LI1UEPM/v1---updates-to-the-UI?node-id=321%3A849
(scroll right to see more) 
- Only show on markets that expire after the cut off
- Show on the reporting and disputing pages still but hide on the disputing and reporting forms

**Comment by phoebemirman** [comment]
PR opened https://github.com/AugurProject/augur-ui/pull/3038
- need to update date to correct cutoff date in tooltip text and constant when available 
- update read more link to correct link when available

**Comment by cillianhunter0** [comment]
Looks good. Do we want to keep this open until we have date/link added? @phoebemirman

**Comment by phoebemirman** [comment]
lets close it
