### ISSUE TITLE
Market creation: add banner, disable date selection, and add message

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1986]
Market creation 
- We'll display a banner at the top of the page that alerts users to the cutoff date with a link to the post

 
- Disable selecting a date after the cutoff and add a message that explains you can't select a date after cut off
https://www.figma.com/file/csVtbWhGCAYe3nVe2LI1UEPM/v1---updates-to-the-UI?node-id=321%3A849

**Comment by cillianhunter0** [comment]
This looks good, except for the two column layout on mobile. @JohnDanz you updated this 2 weeks ago, right?

**Comment by phoebemirman** [comment]
that was added in this PR https://github.com/AugurProject/augur-ui/pull/2978 but it was for V2

**Comment by phoebemirman** [comment]
going to address the two column layout here https://github.com/AugurProject/augur/issues/2081
