### ISSUE TITLE
Post cutoff: Global banner across the app with link to post

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1987]
- Display a global banner across the app with link to post 
https://www.figma.com/file/csVtbWhGCAYe3nVe2LI1UEPM/v1-updates-to-the-UI?node-id=301%3A2551
(scroll right for more)

- have this show up only if the date is after the cutoff date so it is triggered by the time

- change forking banner to new color
- move forking banner to top of the page and the global banner shows up under it

**Comment by phoebemirman** [comment]
screenshots:

![image.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/5f5fee7a-01c6-4756-a9e0-4553d89cef4b)

![image.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/3eebd393-5869-4636-b004-d579ad31e354)


![image.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/5f30a805-21dc-4afb-a984-2ebeb4b9215f)

![image.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/45530a58-32a6-4060-9ec1-b8773e7dff76)

![image.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/3e71cdb5-c56c-46d0-adef-d4c83f19cbde)

**Comment by cillianhunter0** [comment]
Can you reduce the padding between the main copy and the read more link here, to 24px 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/b0730f33-342c-46e9-9443-ff2023e01327)

**Comment by cillianhunter0** [comment]
Let's jump on a call later to look at the mobile version before closing out

**Comment by phoebemirman** [comment]
here are some screenshots of the updated banners:

<img width="1448" alt="Screen Shot 2019-05-09 at 1 01 10 PM" src="https://user-images.githubusercontent.com/6775839/57484511-11a48e00-725e-11e9-9936-2f38071e27bf.png">
<img width="837" alt="Screen Shot 2019-05-09 at 1 00 49 PM" src="https://user-images.githubusercontent.com/6775839/57484512-11a48e00-725e-11e9-967c-4f804b485f41.png">
<img width="400" alt="Screen Shot 2019-05-09 at 1 00 38 PM" src="https://user-images.githubusercontent.com/6775839/57484514-11a48e00-725e-11e9-8772-7cb7180d08ff.png">
<img width="373" alt="Screen Shot 2019-05-09 at 1 00 18 PM" src="https://user-images.githubusercontent.com/6775839/57484515-123d2480-725e-11e9-8895-22b9ca476878.png">
<img width="806" alt="Screen Shot 2019-05-09 at 12 59 20 PM" src="https://user-images.githubusercontent.com/6775839/57484516-123d2480-725e-11e9-9509-90848cfbe387.png">
<img width="1417" alt="Screen Shot 2019-05-09 at 12 58 41 PM" src="https://user-images.githubusercontent.com/6775839/57484517-123d2480-725e-11e9-834d-8414559e3ba1.png">

**Comment by cillianhunter0** [comment]
Looks good in screenshots but i'm not seeing it on dev.augur or try.augur

**Comment by andrewdamelio** [comment]
@cillianhunter0 all these fixes from yesterday you're trying to QA haven't be built yet on try/dev yet. Not sure why looks like the pipeline failed?

We will let you know when it's been updated -- sorry about that

**Comment by cillianhunter0** [comment]
Can't view this myself as date dependant but looks good in screenshots.
