### ISSUE TITLE
Market trading page level banner

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1988]
- for markets after the cut off, get rid of the yellow text on market properties
- add market level banner to warn users
https://www.figma.com/file/csVtbWhGCAYe3nVe2LI1UEPM/v1---updates-to-the-UI?node-id=321%3A849
- post cut off, both this banner and the global banner will show up

**Comment by cillianhunter0** [comment]
Banner is showing but it's covering some of the content on the top of the page. Looks like the main scroll view hasn't defaulted to the top of its view: 

![scroll position.gif](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/b7987db0-3f84-4046-a546-febf5fdd4243)

**Comment by phoebemirman** [comment]
also fix this

![image](https://user-images.githubusercontent.com/6775839/57389513-33731780-716f-11e9-8493-07e434dbcdf7.png)

**Comment by cillianhunter0** [comment]
Fixed on desktop but still seeing it on mobile: 

![scroll position mobile.gif](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/28088620-85b0-41d5-b8cf-3a2bac94369a)

**Comment by cillianhunter0** [comment]
Not seeing this in the build.

**Comment by cillianhunter0** [comment]
Not aligned right on desktop above 1550px: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/d72f8901-3c08-4854-8c42-f59bcc0aa520)
