### ISSUE TITLE
Increase vertical hit area of text buttons on touch devices

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#1989]
Increase the vertical hit area of these buttons on touch devices to 24px . Currently, they're very small to tap

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/a2a447c2-d391-44b3-b468-97567fafcc63)

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/522f5cfa-bc58-491b-9e3c-89b159c3f830)

**Comment by andrewdamelio** [comment]
@pgebheim we can move this one to the Mobile epic

**Comment by bthaile** [comment]
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7268%3A326
in figma

**Comment by pgebheim** [comment]
🎉
