### ISSUE TITLE
Market trading page notice modal

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#1999]
- for markets after the cut off get rid of the market review confirm modal and add this new market notice modal

**Comment by cillianhunter0** [comment]
Looks good, let's just update the time to show seconds:
11:59:59 PM

**Comment by andrewdamelio** [comment]
@cillianhunter0 Can we close this issue and move the above to a new issue. (https://github.com/AugurProject/augur/issues/2050) We are using a single constant to show the time & date so it will need to be changed/tested for all messaging.
