### ISSUE TITLE
Need Specific End Time for Markets

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#200]
Alpha Improvement Request:
When creating a market the author should be required to enter an end time (default to midnight) and a time zone. This would be a simple step to reduce ambiguity in markets with inexperienced market creators.
Request support to Beta release by adding necessary fields and drop down boxes to select end time and time zone.

**Comment by thinkloop** [comment]
What time zone do contracts use, GMT? Should the time be normalized to that before submission?

**Comment by joeykrug** [comment]
Blocktime for now

The end times should display with whatever local time the user's browser is using: https://stackoverflow.com/questions/6939685/get-client-time-zone-from-browser

So if current block is block 100 and you want something to end 15 seconds from then, you make it expire in block 101.  To find the end time for a market for a user you find the difference between the current block and the expiration block, see how many hours/minutes that is, and display the end time in the user's timezone by adding that to the user's current time.

**Comment by thinkloop** [comment]
To confirm, say a user selected an end-date of `July 14, 3pm EST`, The steps would be:

1. Get current _server time_ (say `March 6, 7pm GMT`)
2. Convert server time to selected timezone: i.e. `March 6, 2pm EST`
3. Get seconds difference between user-provided end-date and current server-date: `July 14, 3pm EST` - `March 6, 2pm EST` = `8505s` (just chose any number)
4. Divide seconds difference by block duration (15s): `8505 / 15` = `567`
5. Get current block #: `9400`
6. Add previously calculated block difference: `9400` + `567` = `9967`
7. Record end-block in contract: `9967`

Correct?

**Comment by joeykrug** [comment]
Yep!

**Comment by joeykrug** [comment]
Just use epoch time for this now since everything expires using epoch time, much easier to get proper time zone and everything too

**Comment by thinkloop** [comment]
Is this important for MVP? Reporting is month-long, does it matter if markets expire at 11:59pm of their day?

**Comment by joeykrug** [comment]
It could mean the difference between getting in one or the next reporting period. Also this is probably the most trivial issue on here, JavaScript has a way to get the current epoch time and add seconds to it.  This is one line of code to get epoch time and add to it at market creation and one line of code to display time in a users client side time zone. It's probably more work to randomly generate creation times. Third, people cannot resolve a market without a specific resolution time

**Comment by thinkloop** [comment]
Understood, but it's not trivial, we need to add UI that allows user to select time (always clunky), many markets don't care about a specific time causing the user cognitive dissonance guessing a time, if there is a time (rare) user has to convert to their timezone (high likelihood of mistakes), then we have to decide when to display the date with time (certainly not always, like not on markets-list) and when not to. 

The additional ui required, high likelihood of dissonance, high probability of mistakes and the rarity of needing a time make it seem like a low-win feature.

**Comment by joeykrug** [comment]
1). UI already has time input (even for specific hour and minute unless you guys removed it)
2) it worked great, didn't have to put in time if you didn't want to
3) _they_ don't have to convert to their timezone, just let them input time and use epoch time
4). Markets _literally require_ a time. By not putting one all you do is make the system less precise

**Comment by thinkloop** [comment]
OK, but it really is non-trivial and hurts ux, to respond:

> 1). UI already has time input (even for specific hour and minute unless you guys removed it)

It was removed (in augur1) before I came on due to some compilation I don't currently recall

> 3) they don't have to convert to their timezone, just let them input time and use epoch time

They do, if I'm in California and want to put the closing time of APPL in NY, we either have to give them a timezone toggle as well, or since we default to their timezone they have to figure out that it closes 7pm PST. Going between European timezones and North America is that much more complicated and error-prone

> 4). Markets literally require a time. By not putting one all you do is make the system less precise

Yes, putting the max-time of the day they chose 11:59:59pm would cover 99% of cases while removing a large amount of complexity for the user, and extremely rarely affect reporting cycle. The only time it seems to matter is with something like your APPL example where something really different can happen within a few hours, but in that case if it's not clear in the description, reporters will almost certainly report wrong on it (not to mention they have to do their own error-prone timezone conversions).

**Comment by joeykrug** [comment]
These are market creators, not average users. Anyone putting $100 creating a market isn't a noob: they know what they're doing and want to be able to do what they want to do, not have the UI assume they're stupid. 

Max time of the day when - in what time zone lol?

**Comment by tinybike** [comment]
FWIW, a number of people have requested this feature -- I think it's something that needs to exposed in the UI.

**Comment by tinybike** [comment]
Added in AugurProject/augur-ui-react-components@6e944c94a9adfa2a5e1808cad0a9cbe1d390c3c2.
