### ISSUE TITLE
Get list of all Contract && augur-node calls in UI

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#2003]
# SubmitRequest...

"getAccountTimeRangedStats"
"getAccountTransactionHistory"
"getDisputeInfo"
"getFeeWindow"
"getFeeWindowCurrent"
"getFeeWindows"
"getForkMigrationTotals"
"getMarketPriceCandlesticks"
"getMarkets"
"getPlatformActivityStats"
"getProfitLoss"
"getReportingFees"
"getTradingHistory"
"getUniversesInfo"
"getUserShareBalances"
"getWinningBalance"

# augur.api. ...
 `Augur.isKnownUniverse`
`CancelOrder.cancelOrder`
`Cash.allowance`
`Cash.balanceOf`
`ClaimTradingProceeds.claimTradingProceeds`
`CompleteSets.publicSellCompleteSets`
`Controller.getTimestamp`
`CreateOrder.publicCreateOrder`
`FeeWindow.buy`
`FeeWindow.withdrawInEmergency`
`Mailbox.withdrawEther`
`Market.contribute`
`Market.doInitialReport`
`Market.finalize`
`Market.getMarketCreatorMailbox`
`Market.isFinalized`
`Market.migrateThroughOneFork`
`ReputationToken.balanceOf`
`ReputationToken.migrateOutByPayout`
`TestNetReputationToken.faucet`
`Universe.buyParticipationTokens`
`Universe.getDisputeRoundDurationInSeconds`
`Universe.getDisputeThresholdForFork`
`Universe.getForkEndTime`
`Universe.getForkingMarket`
`Universe.getForkReputationGoal`
`Universe.getOpenInterestInAttoEth`
`Universe.getOrCacheDesignatedReportStake`
`Universe.getParentUniverse`
`Universe.getReputationToken`
`Universe.getWinningChildUniverse`
`Universe.redeemStake`

**Comment by JohnDanz** [comment]
SubmitRequest...

"getPlatformActivityStats":

modules/account/actions/update-platform-timeframe-data.ts

"getAccountTimeRangedStats":

modules/account/actions/update-timeframe-data.ts

"getForkMigrationTotals":

modules/forking/actions/get-fork-migration-totals.js

"getMarketPriceCandlesticks":

modules/markets/actions/load-candlestick-data.js

"getTradingHistory":

modules/markets/actions/market-trading-history-management.js

"getAccountTransactionHistory":

modules/modal/containers/modal-transactions.ts

"getProfitLoss":

modules/positions/actions/get-profit-loss.js
modules/positions/actions/update-top-bar-pl.js

"getUserShareBalances":

modules/positions/actions/load-user-share-balance.js

"getDisputeInfo": 

modules/reports/actions/get-dispute-info.js

"getReportingFees":

modules/reports/actions/get-reporting-fees.js

"getWinningBalance":

modules/reports/actions/get-winning-balance.js

"getMarkets": (not sure why this isn't using the API that's there already...)

modules/reports/actions/load-disputing.js (2 spots in the file)
modules/reports/actions/load-reporting-final.js
modules/reports/actions/load-reporting.js (3 spots in the file)

"getFeeWindowCurrent":

modules/reports/actions/load-reporting-window-bounds.js

"getFeeWindow":

modules/reports/actions/load-reporting-window-bounds.js

"getFeeWindows": (note the plural)

modules/reports/actions/participation-tokens-management.js

"getUniversesInfo":

modules/universe/actions/load-universe-info.js

**Comment by JohnDanz** [comment]
augur.api. ...
(all folders are src/modules/...)

account/actions/get-rep.js:

Universe.getReputationToken
TestNetReputationToken.faucet

app/actions/init-augur.js:

Augur.isKnownUniverse

app/actions/load-universe.js:

Universe.getReputationToken
Universe.getDisputeRoundDurationInSeconds

app/actions/sync-blockchain.js:

Controller.getTimestamp

auth/actions/approve-account.js:

Cash.allowance

auth/actions/update-assets.js:

Universe.getReputationToken
ReputationToken.balanceOf

forking/actions/get-fork-migration-totals.js:

Universe.getForkingMarket

forking/actions/migrate-market-through-fork.js:

Market.migrateThroughOneFork

forking/actions/submit-migrate-rep.js:

Universe.getReputationToken
ReputationToken.migrateOutByPayout

markets/actions/finalize-market.js:

Market.finalize

markets/actions/market-creator-fees-management.js:

Market.getMarketCreatorMailbox
Cash.balanceOf
Mailbox.withdrawEther

modal/containers/modal-deposit.js:

Universe.getReputationToken

orders/actions/cancel-order.js:

CancelOrder.cancelOrder

orders/actions/liquidity-management.js:

CreateOrder.publicCreateOrder

orders/actions/orphaned-orders.js:

CancelOrder.cancelOrder

positions/actions/claim-trading-proceeds.js:

ClaimTradingProceeds.claimTradingProceeds

positions/actions/sell-complete-sets.js:

CompleteSets.publicSellCompleteSets

reporting/components/reporting-report/reporting-report.jsx (Why.... Why is this in a component....):

Universe.getOrCacheDesignatedReportStake

reports/actions/claim-reporting-fees.js:

Universe.redeemStake

reports/actions/participation-tokens-management.js:

FeeWindow.withdrawInEmergency
FeeWindow.buy
Universe.buyParticipationTokens

reports/actions/submit-initial-report.js:

Market.doInitialReport

reports/actions/submit-market-contribute.js:

Market.contribute

universe/actions/load-universe-info.js:

Market.isFinalized
Universe.getParentUniverse
Universe.getForkingMarket
Universe.getWinningChildUniverse
Universe.getOpenInterestInAttoEth
Universe.getForkEndTime
Universe.getForkReputationGoal
Universe.getDisputeThresholdForFork

**Comment by pgebheim** [comment]
Sweet, now we can use this list to start working on how the API should go together.

**Comment by bthaile** [comment]
associated UI log event processing https://github.com/augurproject/augur/issues/2058

**Comment by pgebheim** [comment]
Marking as done since we have all the info.
