### ISSUE TITLE
Post cutoff: update forking copy for post cutoff 

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#2006]
Waiting for design @cillianhunter0

**Comment by cillianhunter0** [comment]
Updated copy:
Color = EB5757 (for the first sentence only) 
"Alert: If you migrate your REP to a child universe, you will never be able to migrate your REP to Augur V2. Read more

If you want to migrate to a child universe anyway, collect any outstanding REP on the Portfolio: Reporting page. Then migrate your REP to your chosen child universe. All REP migrated during the forking period will receive a 5% bonus. The forking period will end on [DATE] or when at least [x] REP has been migrated to a single child universe. Read more about the forking process here. "

**Comment by phoebemirman** [comment]
screenshots:

![image.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/4585f8f6-cd50-4435-9dcb-79ecac09d99e)

![image.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/19cc50c3-85eb-4b4e-89b3-285541ce3626)

![image.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/1be778b6-adcd-45c5-bb40-fd72b9a46619)

**Comment by cillianhunter0** [comment]
@phoebemirman we do we remove the red "alert" copy in the second screenshot?

**Comment by phoebemirman** [comment]
that is for pre cutoff forking
