### ISSUE TITLE
Add social media widget support

### ISSUE THREAD

**Issue by TheKnowin** [AugurProject/augur#201]
Should add the social media widgets to the Beta release so people can easily send a market to Facebook, Twitter, Google+, Pinterest or email contact.

Edit: I see Twitter widget in the Alpha.  Should add others...

**Comment by tinybike** [comment]
Should re-introduce the Twitter widget also, it seems to have gotten lost in the migration to the new market page!

**Comment by tinybike** [comment]
Moved to CH
