### ISSUE TITLE
Add User Preference Settings with Global Data Format Support

### ISSUE THREAD

**Issue by TheKnowin** [AugurProject/augur#202]
Since this will be used globally I think it would be a good idea to offer support for:
- Different date formats - (MM/DD/YYYY or DD/MM/YYYY)
- Different numeral separators -  "," or "." (American style or European style)
- Preferred user time zone

The Alpha version uses US format.  I think this will have global appeal so we should support global user preferences.

**Comment by dstadulis** [comment]
Regarding date formats, other options: 

The international format defined by ISO (ISO 8601) tries to address all these problems by defining a numerical date system as follows: YYYY - MM - DD where. YYYY is the year [all the digits, i.e. 2012] MM is the month [01 (January) to 12 (December)] DD is the day [01 to 31].

**Comment by joeykrug** [comment]
Also allow choosing your own time zone

**Comment by tinybike** [comment]
Moved to CH
