### ISSUE TITLE
Betting: Account summary

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#2023]

**Comment by yanelbottini** [comment]
# Design done list

### Desktop
- [ ] Default view, including Notifications, Active markets, Balance, Augur Status, Favorites
- [ ] Alternative view, including empty states for Notifications, Active Markets & Favorites
- [ ] Transactions ¿?
- [ ] Deposit flow
- [ ] Withdrawal flow

### Responsive
- [ ] Mobile breakpoint
- [ ] Tablet breakpoint
