### ISSUE TITLE
MarketCreated

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2053]
# **MarketCreated**

market created log event comes in the UI:

* market information is fetched
* category are added to UI state if new.

### user logged in:
 * users assets balances are update 
 * if user created the market alert is updated
 * update any pending transactions // this needs to be standardized in the UI.

**Comment by pgebheim** [comment]
@bthaile -- This issue looks informational (e.g. remembering what we could do with a MC created log).

Can we close it / it doesn't seem actionable.
