### ISSUE TITLE
reflow create market page to be one column on mobile

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#2081]
this was done for V2 AugurProject/augur-ui#2978 but need to add it to this release

https://www.figma.com/file/csVtbWhGCAYe3nVe2LI1UEPM/v1---updates-to-the-UI?node-id=181%3A1294

**Comment by cillianhunter0** [comment]
The tags section is still on two column: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/a561ca64-fdd7-4cb2-9a92-3a1f683ac833)

**Comment by Chwy5** [comment]
fixed - closing
