### ISSUE TITLE
Phase 4: Make Connectors to talk to data sources 

### ISSUE THREAD

**Issue by brianosaurus** [AugurProject/augur#2086]
### Phase 4 in the epic

Make Connectors that use this interface to talk to a WS or Web worker based backend for our UI:
```json
{ subscribe, unsubscribe, send, connect, disconnect }
```

The connectors should
* abstract the communication method so the UI doesn't have to know details after instantiation
* be performant
* allow a mock connector, for testing, to be easy to construct

**Comment by justinbarry** [comment]
## Note
This is only for the request response parts of the connector. The subscriptions stuff is upcoming.

**Comment by justinbarry** [comment]
ref #1786
