### ISSUE TITLE
Buy / Sell improvements

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#210]
Users should be allowed to input:
- number of shares to buy (currently allowed)
- odds they want to set the market to
- how many shares they're willing to buy for a given price / share _or_ given total cost.
   - i.e. I wanna buy 10 at 50 cents per share or I wanna spend $5 total.

all as different ways to buy/sell shares 

UI should show potential profit if right when buying and cost per share

**Comment by joeykrug** [comment]
Should also show cost per share when buying.  It shows cost but it should also show what the cost per share would be

**Comment by priecint** [comment]
> how many shares they're willing to buy for a given price / share or given total cost

I was thinking something like this:

![order-ticket](https://cloud.githubusercontent.com/assets/5900808/13364549/b3abf530-dccf-11e5-96ad-c1bc03342558.png)

User inputs either value and the other value gets calculated and input changed accordingly.

What do you think? Thanks

**Comment by joeykrug** [comment]
Looks good, would make it say Cost (amount to spend)  for now until people get used to knowing exactly what cost means

**Comment by thinkloop** [comment]
Is "odds they want to set the market to" still relevant with orderbook?

**Comment by joeykrug** [comment]
It's just your limit price.

- given total $$$ how many shares can I buy? isn't available as a calc. but prob. should be [etrade and most stock sites have this] - or as a mouseover tooltip or something
- UI should show potential profit if right when buying

Both of those from OP still aren't in yet

**Comment by joeykrug** [comment]
Should also show fees for a trade when placing it

**Comment by joeykrug** [comment]
all done except for 1 thing which will make on clubhouse
