### ISSUE TITLE
Refactor Styles

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#2105]
We need to do a pass to refactor the style sheets that are still referencing old color values or using verbose names.

Ideally we should be trying to slim down out style code so that we have very few classes that have simple naming conventions. Use PascalCase for classes not camelCase, do not use _ or -, try to limit classes to the overall element wrapper of a component and use encapsulated element targeting within that class to style elements of the component. small modifier/conditional classes are ok, things like `.open` or `.closed` for example to toggle height or display is fine. Do not name the classes with repetitive prefix-text. Example would be something like `market-view.styles.less` having `.MarketViewContainer` then having `.MarketViewTextBox` etc. instead just make a `.Container` class, and avoid the need for a seperate class for TextBox.

**Comment by pgebheim** [comment]
@JohnDanz @bthaile Closing this major effort.
