### ISSUE TITLE
Refactor Component Elements

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#2106]
Remove unneeded element tags, aka overwrapped elements. We shouldn't have situations where for example we do something like this:

```
<div>
  <label>
    <span> some text </span>
  </label>
</div>
```

Drop the span, and consider dropping the label unless it actually is a label for an input.

Convert JSX to TSX as well and add typing.

The goal is to simplify the HTML involved in our elements so they are easier to style/position using Less.

We should also look to rename elements to remove `-` and `_` characters. Keep Things Simplified and look to merge common elements where it makes sense.

**Comment by pgebheim** [comment]
@JohnDanz Is this still a useful ticket?

**Comment by JohnDanz** [comment]
yeah, It's more of a general note on what we want to do, I could probably make more based on each section of code. I'll look to break it up and then i'll close it

**Comment by pgebheim** [comment]
@JohnDanz @bthaile Closing as a major effort is complete.
