### ISSUE TITLE
Remove Old Elements

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#2107]
Find and Remove old component code that is no longer in use. 

Part of this will also be simplifying the folder structure of our modules. Ideally we want to move to something like this:

```
modules/<module>/
  actions
  reducers
  helpers
  selectors

or modules/<module>/ (a good example of the new structure is modals, for the most part)
  containers
  someComponent.tsx (components just live in the baseline folder, ideally these are fed by containers)
  common.tsx (this includes common elements specific to this code section, see modals as an example)
  <module>.styles.less (styling for all files in this folder)

```

If there is a situation where it makes sense for a module to have actions/reducers/etc and also containers and components then consider a `component` folder to keep things a little more organized, but do not make specific folders for each component. an example of what we want to avoid would be something like this:
```
// we don't want this
modules/<module>/
  components/
    someComponent/
      someComponent.tsx
      someComponent.styles.less
 etc...
```
To many folders and it doesn't really help organize any better than just having a top level folder name on there, we end up repeating the same text over and over in our imports for no real reason. Don't need to be that verbose.

**Comment by pgebheim** [comment]
@JohnDanz Make specific tasks for this if they come up.
