### ISSUE TITLE
Add hooks to process pending transactions locally as they are sent

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#2111]
## The goal: 
We need to derive user specific notifications in the ui (or via chain query of some sort or another) for when a transaction is sent and not yet mined.

## Acceptance Criteria:
There is a middleware API endpoint which can be used to register a callback for when a transaction is submitted.

## The plan:

1. Modify the contract dependencies to have a hook for when a tx is sent. It will be provided the tx hash as well as other relevant tx data.
1. Create the appropriate hook in the Augur SDK for the UI or other consumers to react to transactions as they are sent.

### A more concrete example:

1. User clicks to submit an order 
1. Order is submitted by the ui with the following parameters:

```
function createYesNoMarket(uint256 _endTime, uint256 _feePerCashInAttoCash, uint256 _affiliateFeeDivisor, address _designatedReporterAddress, bytes32 _topic, string memory _extraInfo) public returns (IMarket _newMarket);
```

Called with...

```
createYesNoMarket(1234, 1, 1, $SOMEADDRESS$, $SOMETOPIC$, $EXTRAINFO$);
```

Note: Extra info could have details we want to display in the UI during the pending phase of a transaction.

1. This will trigger on `onSubmit` (name up for change) call in the contract dependencies
1. Augur SDK will have a callback registered for it which will itself be a location for consumers of the SDK to register their own app specific behavior. In this particular case the UI will listen for these events and insert them into the `pending_orders` redux table/key/toplevel thingy.
1. A selector will merge both the `pending_orders` and the `orders` redux tables into one for UI display.
1. UI is handed a log object on `pendingTx` (name to change) event. Values on the log are:
  * contract name
  * method name
  * transaction hash
  * timestamp submitted
  * arguments on the method in form of [{key: value}] 

The individual UI components will be responsible for understanding how to display any "pending" items.

## Open question:

* How do we handle failed transactions?
* How can we notify the user they have a pending transaction to sign someplace? (This is probably another epic but we need to think about it).

## Discoveries

1. solc outputs the hash of the abi which should be all we need to generate the reverse mapping.

**Comment by justinbarry** [comment]
ref #2183

**Comment by pgebheim** [comment]
Scheduling this Epic work into next sprint.
