### ISSUE TITLE
Investigate increasing CI capacity

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#2113]
We might benefit from setting up our own instance. See: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops#install

We might benefit from reaching out to [David Burela](https://github.com/DavidBurela) and asking him what can be done here.

**Comment by petong** [comment]
Parallel jobs have been increased to 15, hopefully this gets us through the short term.  azure runs jobs on DSv2 instances: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes

without running our own agents, we can purchase more parallel jobs here: https://marketplace.visualstudio.com/items?itemName=ms.build-release-hosted-pipelines&ssr=false#overview

work still needs to be done testing out running our own agents on better hardware
