### ISSUE TITLE
Remove Lodash

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#2115]
Remove all calls to Lodash and replace with regular old JS. Once all references to lodash are removed, remove it from package deps.

**Comment by pgebheim** [comment]
@JohnDanz Should we keep this scheduled for next sprint or should it go to backlog?

**Comment by JohnDanz** [comment]
Lets put this in the next sprint, I've been removing lodash calls when I see it but we should assign someone to handle it all at once and be done with it

**Comment by bthaile** [comment]
looks like there is still work to do here moving to backlog and out of sprint.

**Comment by pgebheim** [comment]
Good idea, but not a priority.
