### ISSUE TITLE
Registration duplication

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#212]
I can register the same exact username and password... twice.

**Comment by tinybike** [comment]
I'm trying to reproduce this.  What username / password did you use?

**Comment by Frankenmint** [comment]
what is the unique key on mongodb?  I think its using the address generated and should use the email/register handle as the unique ID.  I’ve never gotten the ‘name is taken’ validation thrown.

**Comment by joeykrug** [comment]
rogerdat
rogerdat1

On Saturday, November 7, 2015, Frankenmint <notifications@github.com> wrote:

> what is the unique key on mongodb? I think its using the address generated
> and should use the email/register handle as the unique ID. I’ve never
> gotten the ‘name is taken’ validation thrown.
>
>
> > On Nov 7, 2015, at 4:11 PM, Jack Peterson <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > I'm trying to reproduce this. What username / password did you use?
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/AugurProject/augur/issues/212#issuecomment-154766712>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AugurProject/augur/issues/212#issuecomment-154768023>.
>


-- 
Joey Krug
www.augur.net
Decentralized prediction market
A Clearer Future

**Comment by tinybike** [comment]
Account info is not stored in MongoDB.

**Comment by tinybike** [comment]
As of AugurProject/augur.js@33fe7cf841b08c2993d79e08fd8649dda553a860 accounts persist in localStorage; "handle taken" checks/tests added in AugurProject/augur.js@4d179cb51cb26a7db73bab39dd2b2bf0020844ff.
