### ISSUE TITLE
Redesign Trading Page

### ISSUE THREAD

**Issue by AugurIntegration** [AugurProject/augur#212]
This encompasses a number of changes/additions to the Trading page, including:

- Add zoom in/out to the depth chart
- Add a toggle or setting for net position vs quantity in categoricals
- Review how net position/quantity is displayed for binarys and scalars
- Show both yes and no outcomes on binarys
-  Add a setting so users can switch between seeing yes and no, and seeing long and short. 
- Add trading history
- Add filled orders (which is the user's personal trading history)
    - Columns: type (bought/sold), amount, effective price, total, fill date, link to view fills (which can be done on multiple trades)
- Add the ability to “favorite” the market from the trading page
- Combine the order form inputs and review screen
- Add max cost to the order form so the user can see how much eth will be escrowed while order is pending
- Use denomination for outcome label on scalar markets under Positions and Open Orders
-  For price, precision should be limited to the precision available on the contacts. For scalars, this depends upon what the user set when creating the market.
- Add to order form: ch1658 
-  show the market spread in the orderbook instead of the midpoint
-  show pending orders (with a pending label) in the open orders.
- Add a “cancel all” button for open orders
- market depth lines should not overlay quantity labels
- show a more detailed hover state with cumulative quantity on market depth chart
- compress/expand space for full trading page to fit on user's screen
- add ability to expand or collapse order book and trade history (vertically)

**Comment by adrake33** [comment]
Dupe of #293
