### ISSUE TITLE
Add get gas estimation functionality

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2122]
There are 3 types of getting gas estimates:

1. hard coded values
2. simple get gas estimates for contract call
3. aggregated gas estimates where contract addresses are passed in to a contract call that loops through the contracts and calls a method. There is a limit to how many contracts can be passed into these loop functions. 
a) redeemStake
b) cancelOrders.cancelOrders (pass in orderIds) is there a limit
c) claimMarketsProceeds (pass in markets) is there a limit

**Comment by joeykrug** [comment]
seems to be done

**Comment by robert-e-davidson3** [comment]
Closing because this looks done. Re-open if it isn't.
