### ISSUE TITLE
Trade info missing

### ISSUE THREAD

**Issue by AugurIntegration** [AugurProject/augur#213]
When placing a trade below total it should also take total / shares to show an average price per share [i dont wanna have to use a calculator or do it in my head]

There should also be a calculator to calculate how many shares to buy at a given price if i wanna spend y dollars.  Screenshot example attached:

![quantity.PNG](https://api.clubhouse.io/api/attachments/files/clubhouse-assets/57ba59e0-be53-4e07-8817-724a7edbc3e0/1657/quantity.PNG)

**Comment by adrake33** [comment]
Dupe of #294
