### ISSUE TITLE
Dapper doesn't work - EIP-1102

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#2137]
Looks like we need to clean up our web3 interface.

Attached are the docs for Dapper.

[https://app.zenhub.com/files/142967010/b2696c24-d185-434b-89d1-cda15b9b0323/download](https://app.zenhub.com/files/142967010/b2696c24-d185-434b-89d1-cda15b9b0323/download)

@joeykrug @chwy -- do we wanna priority high this and try to get it into 1.12.1?

**Comment by joeykrug** [comment]
Sure. Since this is the last v1 release let’s do it

**Comment by pgebheim** [comment]
It looks like it DOES work.

Closing.
