### ISSUE TITLE
Replace isMobile, isMobileSmall, and media queries with css

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#2142]
as a step one we can sub out the isMobile stuff for the react media query if we absolutely must but we should focus on  styling as much as we can then address the harder sections we used react-media-query thing

**Comment by bthaile** [comment]
@phoebemirman make sure to remove `appStatus` reducer when isMobile and isMobileSmall is no longer used. I have a PR to refactor and type reducers which slimmed down `appStatus` to only have isMobile and isMobileSmall.

**Comment by phoebemirman** [comment]
@bthaile that probably won't be for a while. don't want to get rid of isMobile for parts of the ui that are getting re-done

**Comment by bthaile** [comment]
The direction is to get rid of it, I think now is the best time, while we have time
