### ISSUE TITLE
Chunked estimate gas calls

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2144]
There are contract methods that take an array of contract address. The contract calls can't take unlimited number of contract addresses. They need to be chunked.

There is a limit to how many contracts can be passed into these loop functions.
a) redeemStake - worked
~~b) cancelOrders.cancelOrders (pass in orderIds) is there a limit (market trading page and portfolio)~~
c) claimMarketsProceeds (pass in markets) is there a limit

**Comment by pgebheim** [comment]
@bthaile -- Again this will be needed for Trading to be complete, so gonna put this into that deliverable

**Comment by pgebheim** [comment]
Cleaning up modals epic

**Comment by joeykrug** [comment]
Need to do for a and c

**Comment by Chwy5** [comment]
transaction fees displayed for bulk match the amount in Transaction payment in the console

Closing
