### ISSUE TITLE
Remove "has open orders" filter from market list page 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#2145]
We're going to remove this filter. The spread filter makes it redundant.

**Comment by phoebemirman** [comment]
is this how the filters should look? would spread go next to the other dropdowns?


<img width="654" alt="Screen Shot 2019-05-13 at 11 44 34 AM" src="https://user-images.githubusercontent.com/6775839/57646055-905a3d80-7574-11e9-92e4-c2363b09b88d.png">
<img width="1425" alt="Screen Shot 2019-05-13 at 11 44 15 AM" src="https://user-images.githubusercontent.com/6775839/57646056-905a3d80-7574-11e9-99a0-6caf141305f6.png">

**Comment by cillianhunter0** [comment]
Yeah next to the other dropdowns: 

![image](https://user-images.githubusercontent.com/48024319/57646480-98d46780-75b8-11e9-93bf-7cd93471a0f1.png)

**Comment by cillianhunter0** [comment]
On mobile the filters are behaving differently to desktop. 

Mobile, the container is a fixed width, see the distance of 'open' and the dropdown arrow icon
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/f1958ed6-a04e-489d-afba-b5be29e4fc35)

vs

Desktop, the container is fluid based on the selected option in the menu (this option is preferable for mobile) 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/6ce5af2d-9200-4df1-bf27-5822b581260a)

**Comment by cillianhunter0** [comment]
On comment above. Agree with Phoebe to keep this. It's current mobile behaviour and not a major issue.
