### ISSUE TITLE
Include info from `getDisputeInfo` in `getMarketsInfo`

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#2153]

**Comment by pgebheim** [comment]
@adrake33 -- Gonna put this sprint into backlog and not work on these in Sprint 8, since we wanna focus on the functionality to get the Markets and Trading pages working first.

So as soon as we get these two in review issues merged, this can come out of the milestone!

**Comment by adrake33** [comment]
Ok, sounds good!
