### ISSUE TITLE
remove all augur.rpc.* calls in UI

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2158]
augur.rpc.* is used for these reasons:

* get account types from augur.rpc.constants;
* get ETHER from constants `const { ETHER } = augur.rpc.constants;`
* get accounts ` augur.rpc.eth.accounts((err: any, accounts: Array<any>)`
* get gas price `augur.rpc.getGasPrice()`
* get net version `augur.rpc.net.version((err: any, netVersion: string)`
* clear tx history `augur.rpc.clear(); // clear ethrpc transaction history, registered callbacks, and alerts`
* sha3 utility `const addressHash = augur.rpc.sha3(formattedAddress.toLowerCase());`
* get block by has ` augur.rpc.eth.getTransactionByHash(...`
* get transport `augur.rpc.getTransport().getTransportName()`
* tx relay `augur.rpc.excludeFromTransactionRelay(NO_RELAY);` and `augur.rpc.registerTransactionRelay((transaction: any)`
* set debug options `augur.rpc.setDebugOptions(env.debug);`

**Comment by justinbarry** [comment]
| Old Method | New method |
| --- | --- |
| get account types from augur.rpc.constants;                           | Added here https://github.com/AugurProject/augur/pull/2159 |
| get ETHER from constants const { ETHER } = augur.rpc.constants;       | Added here https://github.com/AugurProject/augur/pull/2159 |
| get accounts augur.rpc.eth.accounts((err: any, accounts: Array<any>)  | Exists on the EthersProvider [here](https://github.com/AugurProject/augur/blob/master/packages/ethersjs-provider/src/EthersProvider.ts#L54) |
| get gas price augur.rpc.getGasPrice()                                 | This is EthRpc to be unraveled if we need it |
| get net version augur.rpc.net.version((err: any, netVersion: string)  | |
| clear tx history augur.rpc.clear(); // clear ethrpc transaction history, registered callbacks, and alerts | Will probably [this](https://gist.github.com/rsms/3744301784eb3af8ed80bc746bef5eeb) from the event emitter interface. |
| sha3 utility const addressHash = augur.rpc.sha3(formattedAddress.toLowerCase()); | Is [this](https://github.com/AugurProject/augur/blob/master/packages/augur-core/source/libraries/ContractDependenciesEthers.ts#L19) the same thing? |
| get block by has augur.rpc.eth.getTransactionByHash(... | provider.getBlock, unsure it the types actually expose it. |
| get transport augur.rpc.getTransport().getTransportName() | Unsure if needed. |
| tx relay augur.rpc.excludeFromTransactionRelay(NO_RELAY); and augur.rpc.registerTransactionRelay((transaction: any) | Unsure if needed |
| set debug options augur.rpc.setDebugOptions(env.debug); | Unsure if needed. |

**Comment by justinbarry** [comment]
The following are the only two remaining:
1. augur.rpc.excludeFromTransactionRelay(NO_RELAY);
2. augur.rpc.registerTransactionRelay((transaction: any)

**Comment by bthaile** [comment]
all `augur.rpc` calls have been removed from UI, except tests which will be fixed at a later time.
