### ISSUE TITLE
UI error when coming up (g.default.manifest is not a function)

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2171]
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/630fd742-4423-4947-9972-97ef89ce4c80)

tested Rinkeby once synced brought up the UI and get this error. dead in the water.

**Comment by bthaile** [comment]
looks like pete fixed it with new build.

**Comment by Chwy5** [comment]
fixed- closing
