### ISSUE TITLE
augur-node migration script issue

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2172]
I suspect this migraiton script
<https://github.com/AugurProject/augur-node/blob/master/src/migrations/20190205102050_rm_complete_sets_trade_group_id.ts>
is causing error in Augur App 1.13 candidate. @pg 
universe - SQLITE_CONSTRAINT: NOT NULL constraint failed: _knex_temp_alter7.numCompleteSets

<https://gist.github.com/bthaile/b4fde3e112f4730337898376d4ed2243> gist

... NULL as tradeGroupId,...`

To test:
sync mainnet with older version like 1.12.
make sure augur-app starts to sync.

**Comment by bthaile** [comment]
Ryan fixed with augur-node PR

**Comment by Chwy5** [comment]
fixed
