### ISSUE TITLE
Add a sync status getter to augur-state

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#2182]
This should be the v2 equivalent of `augur.augurNode.getSyncData`

**Comment by justinbarry** [comment]
Eventually this will probably be emitted using whatever we decide here: #2183.

**Comment by brianosaurus** [comment]
Needs this in particular lastProcessedBlock.number

**Comment by brianosaurus** [comment]
* last block processed
* last block's timestamp
* last block's hash
* blocks behind
* percentage complete in ‘##.####’ format
