### ISSUE TITLE
Closing a market

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#22]
So as a market creator (or anyone involved) I want to be able to close markets:

make this call  `tradingPeriod = MARKETS.getTradingPeriod(market)`
  
Then check in js `if(BRANCHES.getVotePeriod(branch) > tradingPeriod)`

Using both those calls if you get 1/true then a market is able to be closed.

To close the market call `def closeMarket(branch, market)`

**Comment by niran** [comment]
Why does the market creator want to close it? Is it just something has to be done once the trading period has expired?

**Comment by joeykrug** [comment]
Yeah it has to be done + he won't get his trading fees if he doesn't close it

**Comment by scottzer0** [comment]
can a market be closed prematurely?

**Comment by joeykrug** [comment]
Nah can't be closed prematurely

**Comment by Frankenmint** [comment]
I'm confused, don't markets close automatically upon exipration and isn't expiration set by block?

**Comment by tinybike** [comment]
Is this still an issue / what is the issue here?  I added basic close market support to the UI right before the alpha release.  (I haven't tested it recently, though...)

**Comment by joeykrug** [comment]
Option/button to close market in the UI never appeared when I made this issue.

**Comment by tinybike** [comment]
Combining this with #58:

After a market has matured and the event's outcome has been decided, remove the market from the markets/branch page.

Then, on the account holding page, show the user how much profit/loss they made on that market after it's closed. Once it has been closed (meaning the user has been paid out if they won) allow the user to click an x or something to remove that market from their holdings page.

**Comment by tinybike** [comment]
Fixed in 824cfe912f9a5cec8df15d11ff865750836179f9 and AugurProject/augur.js@447fcd14d8237e1df07524171c71c4552934c0ef; when #259 is complete the whole (updated) reporting sequence will work in-UI!
