### ISSUE TITLE
Price weird, don't have any idea what is going on here

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#220]
![bobissue](https://cloud.githubusercontent.com/assets/5925937/11983853/75c25f10-a97c-11e5-9842-d312eac0545c.PNG)

**Comment by tinybike** [comment]
It's a scalar market!  The prices look weird because they're displayed as percentages -- I'll fix that.

**Comment by tinybike** [comment]
Fixed in 0547dcf55211b51dd6214bccd679aff3abaa38dd.
