### ISSUE TITLE
Standalone Augur Market Odds Converter

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#2203]
It would be good to get a stateless lib to take markets and output various odds types.

Well want american, decimal, fractional odds for sure.

It is sufficient for this library to do calculations in display prices (e.g. Cash mapped to the range of the market) instead of attocash -- so it should use BigNumber.js.

**Comment by joeykrug** [comment]
https://www.oddsshark.com/tools/odds-calculator

american, decimal, fractional, implied/percentage/aka what we do now

**Comment by pgebheim** [comment]
Good call!

**Comment by pgebheim** [comment]
Stale.
