### ISSUE TITLE
Client doesn't work on iOS (Chrome/Safari)

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#225]

**Comment by priecint** [comment]
@tinybike With http://jsconsole.com I was able to find and fix errors in the code.
But suddenly
```
"[ethrpc] asynchronous RPC timed out", "https://eth1.augur.net", {"id": 2, "jsonrpc": "2.0", "method": "eth_coinbase", "params": []}
"[ethrpc] asynchronous RPC timed out", "https://eth3.augur.net", {"id": 2, "jsonrpc": "2.0", "method": "eth_coinbase", "params": []}
"[ethrpc] asynchronous RPC timed out", "https://eth4.augur.net", {"id": 2, "jsonrpc": "2.0", "method": "eth_coinbase", "params": []}
"[ethrpc] asynchronous RPC timed out", "https://eth5.augur.net", {"id": 2, "jsonrpc": "2.0", "method": "eth_coinbase", "params": []}
```
I [only found eth_coinbase](https://github.com/search?l=&q=eth_coinbase++user%3AAugurProject&ref=advsearch&type=Code&utf8=%E2%9C%93) in test files in our code.
Do you know what to do?

**Comment by tinybike** [comment]
@priecint sorry for the slow response on this.  I think those error messages are from when our hosted nodes crashed last week -- were they specific to iOS?

**Comment by priecint** [comment]
I tried it on desktop and iPad and it looks like it's iOS specific. Desktop loads ok, iPad logs
``
"local node:","http://127.0.0.1:8545"
``
and those 4 time-outs.

**Comment by tinybike** [comment]
Hm.  What else is in the console, aside from that local node message?  It should default to the hosted nodes if there isn't an eth node running on localhost.

**Comment by tinybike** [comment]
The underlying issue turned out to be a bug in [js-ipfs-api](https://github.com/ipfs/js-ipfs-api).  I made an issue for this on the js-ipfs-api Github (https://github.com/ipfs/js-ipfs-api/issues/212) and walled off the bug in AugurProject/ramble@27b6cb739b10cc98d9eb6905b3ec026841bcf111 / 09b1ab34eec6493a2fd536979c7028a881b4f4bf so that the site will now load on iOS.  The IPFS-based features (comments and metadata) will not work until this bug is fixed, but in the meantime the rest of the site should work now.
