### ISSUE TITLE
Get OrderBook getter

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2257]
UI needs to get the order per market per outcome. taking in parameters
"marketId"
"outcomeId"

This getter can consume other getters like "get orders"

Then orders will need to be aggregated based on price and sorted by price.

The data needs to be in the shape (open for discussion)
```
{
marketId: "marketId0x"
outcome: "outcomeId",
 "bids": [ Order1, order2, order3],
 "asks": [ Order1, order2, order3]
}
```

**Comment by justinbarry** [comment]
Make it look like:  packages/augur-ui/src/modules/markets/helpers/order-and-assign-cumulative-shares.ts

**Comment by justinbarry** [comment]
Will need to consider the current users cancelling orders when calculating the order book.
