### ISSUE TITLE
[Roadmap] Spike - Investigate v2 doc generation

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#2258]
Things to investigate:

* Find & try out a doc generator for Solidity (e.g., https://github.com/OpenZeppelin/solidity-docgen)
* Paul found a JS doc tool that has a plug-in where you can do in-line code samples. We would need to set up the default states to allow the docs to have a connection to Rinkeby. However, he didn't verify how it worked with TypeScript (e.g., if it would Babel the TS in the browser). If this isn't doable, the next best alternative would be to give the user a place where they have a JS editor and can enter code to run it against Rinkeby.
* May want to use a different theme, etc. for displaying docs. (Paul suggested https://jhildenbiddle.github.io/docsify-themeable/#/introduction.)

**Comment by pgebheim** [comment]
@adrake33 -- Make sure you add some sub-issues re: Fixing solidity-docs

**Comment by justinbarry** [comment]
Now that the "spike" is done.... moving to an epic with more specific tickets.
