### ISSUE TITLE
replace momentjs with luxon

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2267]
https://github.com/moment/luxon
it's a separate npm package. will be needed for timezone processing in market creation

**Comment by andrewdamelio** [comment]
@bthaile I looked into using Luxon as a drop-in replacement for moment.js but it doesn't look like we will be able to do that -- see below.


> "But Luxon doesn't quite fulfill Moment's mandate. First, it doesn't provide some of Moment's most commonly-used features, like relative date formatting. These features will soon be added to modern browsers and quickly folded into Luxon, but they aren't there yet." 
https://moment.github.io/luxon/docs/manual/why.html

We actually use moment in the UI a lot for relative date formatting. I suggest we use Luxon alongside moment, at least until Luxon adds support for relative date formatting.

Should we change the focus of his issue to be about adding Luxon and not replacing moment?

**Comment by bthaile** [comment]
We really only need it for timezones. Lets keep moment and add luxon for timezone stuff. @andrewdamelio
