### ISSUE TITLE
Add new field to markets

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#228]
Add an additional field to markets which specifies the sources to use for resolution and parameters surrounding resolution.  Good example: "Star Wars will gross what after its worldwide premier?"  This field would state the source is x and whether or not, say the China release (which releases later than the rest of the world) in Jan. is included or not.

**Comment by tinybike** [comment]
Added in cdb1f13a01d3fef3d6b418970568214681d8aee0.
