### ISSUE TITLE
go through unit tests for the UI

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2282]
delete unit tests that don't make sense. update to maintain unit tests that add benefit.

**Comment by justinbarry** [comment]
@robert-e-davidson3 This appears to be in your wheelhouse.

**Comment by robert-e-davidson3** [comment]
This is specifically for the UI. I can do it if Thom is otherwise occupied but he'll have an easier time since he knows the frontend and I don't.

**Comment by bthaile** [comment]
I might have missed deleting a unit test in the UI. they all need to be delete then turn on running them in CI. we'll start creating some.

**Comment by robert-e-davidson3** [comment]
they're all deleted but if any are added then they will block CI
