### ISSUE TITLE
Fix comments

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#229]
Comments have gone wonky sometime over the last week.

**Comment by whatSocks** [comment]
I experienced:

- create accout
- login
- there's no way for me to logout so w/e
- make a comment by typing in field then pressing return (not the "babble" button)
- i'm logged out

this doesn't happen if I make comments by typing in the comment field then pressing the "babble" button

**Comment by tinybike** [comment]
Fixed in b818ffab22bda10b02f7c810b93643cfcec3b2a9 and AugurProject/augur.js@80e323c2670618a9b23644438ab384e5e5e1d88b (as far as I can tell).
