### ISSUE TITLE
[Feature Request] UI: Display ENS name of market creator (if available)

### ISSUE THREAD

**Issue by veox** [AugurProject/augur#2300]
**Is your feature request related to a problem? Please describe.**

Market-makers wishing to build a reputation for creating well-defined markets must [compete with copycats](https://www.reddit.com/r/Augur/comments/bmzqvh/psa_here_come_copycattwin_markets_keep_an_eye_out/). There is no way for them to "brand" markets except through their address: the only thing presented in the interface that is both user-provided and unfalsifiable.

**Describe the solution you'd like**

Make a reverse ENS look-up. Legitimate market makers can now advertise themselves by a memorable name.

* `web3.js` [doesn't have reverse look-ups yet](https://github.com/ethereum/web3.js/issues/2683);
* `ethers.js` [does](https://docs.ethers.io/ethers.js/html/api-providers.html#ethereum-naming-service);
* `web3.py` [does](https://web3py.readthedocs.io/en/stable/ens.html#ens.main.ENS.name).

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by veox** [comment]
To clarify, this should make a reverse (address->name) lookup, followed by a [forward one](https://docs.ens.domains/dapp-developer-guide/resolving-names) (name->address) to validate.

(It's possible to set any name as a "canonical" one for an address, but it's impossible to set an address for a name without control of the name.)

-----

The [`Registry`'s TTL](https://docs.ens.domains/contract-api-reference/ens#get-ttl) can be used to cache the information.

**Comment by joeykrug** [comment]
@tomkysar would be a good one to gitcoin bounty

**Comment by pgebheim** [comment]
We won't be doing this but indeed a good bounty candidate!
