### ISSUE TITLE
Design a "reactive" mechanism to emit virtual events from the getters upon block chain events.

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#2305]
=== The goal
Consumers of our event emitter would like to receive "virtual/synthetic" events from the SDK in lieu of having to poll the getters.

**Comment by justinbarry** [comment]
@brianosaurus I would bet you have thought about this at some point. Please weigh in if you have any thoughts.

**Comment by brianosaurus** [comment]
@justinbarry I think a reactive system would be awesome. After I get the events happening we can add a RxJS layer to Augur that'll automatically take in events and make them a reactive stream. Should not be too hard. I'll need to coordinate with @bthaile and his team to make sure what is done works for them.

**Comment by bthaile** [comment]
Not sure what a reactive stream is. You can educate me.
