### ISSUE TITLE
[Roadmap] UI Bootstrap

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#2310]
Scenario:

User loads UI, initial activity:
UI creates SDK object and wires up events
UI processes `onNewBlock` event to call sync data getter to get sync information and store in Redux. UI components display sync information to the user.

**Comment by pgebheim** [comment]
@brianosaurus -- Are your issues for this still in progress?

**Comment by pgebheim** [comment]
@justinbarry is #2361 gonna be done for this epic?

**Comment by justinbarry** [comment]
@pgebheim Moving the non-event issues out to a future epic.

**Comment by pgebheim** [comment]
Perfect thanks.
