### ISSUE TITLE
Notification etherscan transaction has is incorrect

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2322]
Repro:
1. Place an order with more quantity than asking order on the book
2. The pending notification etherscan is correct
3. When the tx is confirmed the notification etherscan link is wrong

Issue is when the Order Filled confirmation transaction log comes in `log.orderId` is appended to the notification id. The notification id is used to construct the etherscan link url. Need to not append `log.orderId` to the notification id.

**Comment by pgebheim** [comment]
Closed with AugurProject/augur-ui#3084
