### ISSUE TITLE
[Roadmap] UI V2 prep: Typing / Refactoring

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#2325]

**Comment by pgebheim** [comment]
@andrewdamelio @bthaile -- Is this really a roadmap epic if it just has one issue in it?

Is this being worked on?

**Comment by pgebheim** [comment]
This is done for the purposes of the Roadmap, sub-issues in an ongoing epic.

**Comment by andrewdamelio** [comment]
Typing the UI has become an ongoing effort as we refactor/buildout v2. aka, "fix what you see".

Tom and I took the first pass and fixed a lot of the common issues. We should be able to tackle the rest as we remove and update old code.
