### ISSUE TITLE
Sync Backward in Time a.k.a Reverse Sync

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#2329]
We have a desired feature of doing syncing by grabbing chunk going backwards in time.

This would allow for a user to see their current positions/markets etc quickly, while still getting the full time-series information in charts and history after awaiting a full sync.

**Comment by justinbarry** [comment]
1. Do you either of you have thoughts on how this could work? 
2. What data integrity issues could we run into (and could they be mitigated)?

**Comment by nuevoalex** [comment]
Notes from our discussion:

> the biggest issue is if a user is logging in on a different platform for the first time. If the user is fresh to Augur then they will have no contextual data and so they naturally won’t have data integrity issues because all data requests stem from a market context and by the time a market log is processed we must have processed everything that came after it already
> 
> The problem case is for something like trading history
> On a new platform for an existing user
> But even then it’ll just be incomplete until they finish syncing
> 
> I think we will want to put in something UI wise to allow it to sync until it has a minimum number of markets probably
> The Augur state getters do need to always gracefully handle data not existing too even if it shouldn’t occur normally
> In the getter I wrote this can be seen when it tries to get market data
> The other aspect of that is when it can be helped we should reduce dependence on other tables

**Comment by joeykrug** [comment]
do eet

**Comment by joeykrug** [comment]
do eet

**Comment by pgebheim** [comment]
Adding this issue to the Performance Testing epic to decide if / how we need to do this.

**Comment by nuevoalex** [comment]
@pgebheim @joeykrug I think this is largely not needed now that we're developing a warp sync strategy as the primary method of reducing sync time. Thoughts?

**Comment by joeykrug** [comment]
yeah it never made sense to me to begin with

**Comment by pgebheim** [comment]
Agreed, closing.
