### ISSUE TITLE
[Roadmap] UI Deploy Improvements

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#2348]
* Allow for docker ipfs pinner to auto update
* Allow for docker augur node to auto update
* Allow for IPFS pinning within UI:

```
Means:
- Update the IPFS sha of the ui on github upon commit/release
- People could load a STABLE ipfs hash
- That would load the site from the ipfs file on the site
- It would THEN pin it
- AND it would serve it
```

* Put default augur node + eth node urls in the ui that are: a) overridden by localhost ones and b) can be overridden by a different url param

**Comment by pgebheim** [comment]
Adding to growth epic since this would be a way to simplify sharing / making sticky links
