### ISSUE TITLE
Bug: Cannot run augur-sdk tests in intellij

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#2364]
Configured as follows:
![image.png](https://images.zenhubusercontent.com/5c0090502c4f4d3a81333d42/44f6a7aa-d847-4cb0-90b7-c0de7b01e4c3)

**Comment by robert-e-davidson3** [comment]
@justinbarry: This works for me; lmk if it works for you.

<img width="1069" alt="Screenshot 2019-06-13 12 58 18" src="https://user-images.githubusercontent.com/45945043/59463503-f982da00-8dda-11e9-8b89-7ecf8926dc33.png">
