### ISSUE TITLE
Cleanup Filter Frontend

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#2366]
- [ ] 1. Use dynamic text in market creation specific to a given user's market + show ahead of time whether their market will show up with default filters
- [ ] 2. Show warnings on market pages that fail invalid filter
- [ ] 3. tooltip on filters on market page that has similar language as market creation one
- [ ] 4. Don't uncheck invalid markets box if someone owns shares of that market. What it should do is keep it filtered and if you go to the portfolio page you can see those markets because they’re in your portfolio

**Comment by pgebheim** [comment]
@cillianhunter0 @Chwy5 -- Do y'all know if we have the design done for the warning on the market pages?

**Comment by pgebheim** [comment]
@joeykrug

```
+ show ahead of time whether their market will show up with default filters
```

Need to find out if the current code supports this in any straightforward way. I'll note hat we have a ticket to support this for v2.

**Comment by bthaile** [comment]
Paul addresses the unknown with item (1.) 

(3.) (few hours) if the design is straightforward and there isn't any back-and-forth between design and dev. 

Items (2.) and (4.) can be handled with adding a flag to result of MarketInfo getter that tells the UI the market is marked as Invalid. This also fits with Paul's comment above, we need to find out if the current code can be put in a method that getMarketsInfo can call.

invalid filter is one sql stmt

```
    query.whereRaw("(CAST(markets.bestBidTakerInvalidProfitTokens as REAL) > 0 OR CAST(markets.bestAskTakerInvalidProfitTokens as REAL) > 0)");
```

If the above sql could set a boolean property `passesInvalidFilter` on getMarketInfo market data, we'd be able to handle items (2.) and (4.) easily in the UI in a 4-6 hours.

**Comment by pgebheim** [comment]
I think the major question is if we can do that filter without passing an order book through all the machinary that generates DB rows.

That would be the only way to do it before the liquidity is created.
If we need to do it just AS the liquidity is added then yeah it I think tom's right.
So with investigation, I think this takes a dev out for 2 days?

**Comment by cillianhunter0** [comment]
1. Is done in market creation with the "market visibility" panel 
2. This isn't necessary for v2 as we won't have the invalid filter, we'll have the invalid outcome, right? 
3. Does this mean a tooltip beside filters to explain what they are? 
4. Same question as 2 above

**Comment by bthaile** [comment]
verified that 
*"Don't uncheck invalid markets box if someone owns shares of that market. What it should do is keep it filtered and if you go to the portfolio page you can see those markets because they’re in your portfolio"*

The above is satisfied on master. `invalid markets checkbox` stays checked even if the user has a position in invalid marked market.

`HIDE MARKETS ENDING POST V2 CUT-OFF` checkbox will uncheck it's self if the user has positions in market past the cut off. Is that what needs to change?

**Comment by joeykrug** [comment]
Yeah, if they want to uncheck it they can manually or can go to positions to see those markets

**Comment by joeykrug** [comment]
Status of this?

**Comment by cillianhunter0** [comment]
> 2. Show warnings on market pages that fail invalid filter

We're not doing anything here outside of displaying the invalid outcome and it's data etc. 
We will be doing something like it on betting, e.g. a banner "High risk of invalid" 

@joeykrug @Chwy5 is this something we want to get in for trading?

**Comment by Chwy5** [comment]
@joeykrug, We can either do what we are currently doing, add a red flag or add same text we will use on betting "High Risk of Invalid"

**Comment by joeykrug** [comment]
Would do red flag with text

**Comment by Chwy5** [comment]
Do you want to do the text as a tooltip like we do for the Green and Yellow shields or have both flag + text visible?

**Comment by joeykrug** [comment]
visible if market has bid on invalid above ~10% imo

**Comment by Chwy5** [comment]
@cillianhunter0 can we get quick design on on this....for market cards on market list pg and in Reporting disputing

@bthaile we want this to trigger if ther is a bid on invalid above ~10%

**Comment by bthaile** [comment]
> visible if market has bid on invalid above ~10% imo

seems like a troll vector. anyone can put a invalid bid on the book.
