### ISSUE TITLE
Trading: Misc v2 features (tx feedback)

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#2374]
Smaller features 

* ~~Global settings~~ (parked for now)
  * ~~Change odds~~
  * ~~Change default timezone~~
  * ~~Change time format~~ 
  * ~~Change language~~
  * ~~Change to "max profit" or "max return"?~~ 
  * ~~Settings: ability to turn off toast~~ 
* Transaction feedback pattern
  * Talk to CHWY about this - specifically 0x mesh 
  * https://github.com/AugurProject/augur/issues/1725
  * For the order ticket we can't hide the button 
  * Explore how this pattern could be applied across the app 
  * Included in this is the unsigned orders modal for new market creation 
    * "included" was in reference to purchasing flows - kept here to work on afterward 
  * List of places this needs to work 
    * Create market
    * Reporting
    * All trading flows
    * Onboarding
    * Forking 
  * A version of this might be built in one of the transaction modals (phoebe should know which) 
* ~~Blocking modal for singing transactions~~ 
  * ~~Depends on the wallet, IF edge/portis there is no signing etc~~ 
  * ~~Do we really need this right now?~~

**Comment by pgebheim** [comment]
➤ Joey Krug commented:

Get rid of change price of open order. Not relevant with 0x

**Comment by Chwy5** [comment]
Other settings options:
Receive Notifications (possibly through an email Alert)
Approve in/out of newsletter
Hide Chat
Hide Comments
Theme?
date format setting
