### ISSUE TITLE
Trading: Auction

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#2377]
Link to Uniswap from somewhere in the UI
Buy REP 

---
If they can't do it on time, fork their code

* Becomes a part of augur
* Need to have UI for this
  * We can lean on their already existing UI, skinned for augur

**Comment by pgebheim** [comment]
➤ Joey Krug commented:

Have we made a dark mode of their UI and Pr’d it yet? We need to if we haven’t

**Comment by pgebheim** [comment]
➤ Cillian Hunter commented:

uniswap / dark mode skin is now in this ticket: Trading: DAI integration + crypto purchases
