### ISSUE TITLE
Trading: v1 to v2 REP Migration

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#2379]
Notes

* Modal on opening Augur -> do you want to migrate your v1 rep
* Message on the AS page -> you have v1 REP, do you want to migrate
* IF 2 balances, rep 1 and 2, show v2 balance, message to ask do you want to migrate

**Comment by pgebheim** [comment]
➤ Joey Krug commented:

Wrapping got cancelled, it’s just migration now

**Comment by pgebheim** [comment]
➤ Cillian Hunter commented:

Up to date product doc here: https://docs.google.com/document/d/1zzOFHqkA0BzlpqwXHj-h4SsMRXuRm0-bvGbwYKzEJzk/edit?usp=sharing
