### ISSUE TITLE
[BUG] Claiming winnings in finalised market resulted in wrong-direction realised P/L display

### ISSUE THREAD

**Issue by veox** [AugurProject/augur#2391]
**Describe the bug**

A market where I had winnings displays realised P/L as loss after claiming the winnings.

**To Reproduce**

0. Have winnings on a Yes/No market (hypothetical example: having purchased 1 "No" share at 0.6).
1. Wait for the market to be finalised (in example, to "No"). Observe "Unrealised P/L" is positive (in example, "+0.6").
2. Observe "Claim proceeds" is shown for the market in Portfolio -> Positions -> Resolved, as well as "Outstanding returns". Click on the button, wait for tx confirmed.
3. Observe "Realised P/L" as negative (in example, "-0.4" instead of approximately "+0.6"), whereas on-chain, there was an appropriate positive winnings transfer (in example, of ~1 ether).

**Expected behavior**

`augur-app` displays positive winnings instead of loss.

**Screenshots**

Can't do - see "additional context".

**Desktop (please complete the following information):**

 - OS: Arch Linux
 - Browser: Chromium
 - Version: 75.0.3770.80

**Additional context**

I'm not able to show actual trade where this happened, since am managing a portfolio on someone else's behalf, and am not allowed to disclose such information. Sorry. :(

Have not tried to reproduce on testnet yet.

I've tried resetting the database and syncing from scratch. This resulted in the same behaviour with `augur-app` version `v1.14.2`.

I've also tried with `v1.11.1` and a database backup from that era (that wouldn't break on migrations). This version does not exhibit the issue, so it's safe to say this is a regression.

In all cases, I'm syncing `augur-app` against a "Local" `geth` node, `v1.8.27`.

**Comment by veox** [comment]
Side-note: on a different market (also Yes/No) which resulted in a loss, there in no inappropriate reversal. However, there was understandably no "Claim losses" button to press, so the point is moot.

**Comment by veox** [comment]
Tried `v1.13.0` and `v1.13.1` (also with a version-specific database backup). Results in same erroneous behaviour as in OP.

EDIT: `v1.12.0` does not.

So, the regression happened between `v1.12.0` and `v1.13.0`. (There were no other point releases in `v1.12`.)

Diff: https://github.com/AugurProject/augur-app/compare/release-1.12.0...release-1.13.0

-----

Possibly fallout from upstream changes, since the diff contains:

``` diff
- "augur-node": "7.5.0",
- "augur-ui": "6.4.4",
+ "augur-node": "7.7.2",
+ "augur-ui": "6.6.4",
```

**Comment by pgebheim** [comment]
There were some PL changes in augur-node in that time period. But it doesn't look like we've been able to reproduce this exact behavior.

If you're on Discord and can PM your public address so we can take a look the database state for augur node we may be able to track this down.

Is that possible?

**Comment by veox** [comment]
> If you're on Discord and can PM your public address so we can take a look the database state for augur node we may be able to track this down.
> 
> Is that possible?

I'm afraid not.

Let's let this issue hang for a while then, see if anyone else has it happen to them. Or if it repeats for me, for that matter.

JIC, here's the [diff for `augur-node`](https://github.com/AugurProject/augur-node/compare/7.5.0...7.7.2) between the versions listed above.

-----

EDIT: Another market has finalised - also Yes/No, also with winning outcome. This time, the issue is _not_ observed. So, this appears sporadic.

**Comment by joeykrug** [comment]
Should be fixed in v2

**Comment by joeykrug** [comment]
reopening to make sure

**Comment by joeykrug** [comment]
confirmed fixed
