### ISSUE TITLE
MC: Timezone dropdown menu 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#2408]
Figma (at bottom):
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=8219%3A266057

Notes
- Users current timezone and UTC 0 are displayed at the top of the list 
- If user has entered a date, timezone list will filter to only showing DST timezones that fall on that date
   - See Tom about new date/time library to replace moment.js 

use moment and moment-timezone to create timezone list to populate filterable dropdown.

Allow user to type in string to filter the timezone list.
Seed the timezone offset with reporting begins date to show correct offsets.

**Comment by pgebheim** [comment]
@bthaile -- Does this handle the case with only showing the appropriate timezones for the time of the year? E.g. showing PST vs PDT based on the market end time?

**Comment by bthaile** [comment]
It uses timezone locations and does change the offset based on date time picker value.

**Comment by pgebheim** [comment]
@bthaile -- You're the man!
