### ISSUE TITLE
money isn't showing up upon very first login

### ISSUE THREAD

**Issue by whatSocks** [AugurProject/augur#241]
Actual:
- create a new account
- am presumably signed in
- i see this:
![screenshot 2016-01-02 12 12 04](https://cloud.githubusercontent.com/assets/2731744/12075312/2e0a4bc6-b14a-11e5-9a76-10bc54b8c63c.png)

- force logout by hitting "return" while cursor is in a comment field
- log back in
- i see this:
![screenshot 2016-01-02 12 12 32](https://cloud.githubusercontent.com/assets/2731744/12075313/41f312da-b14a-11e5-8ab9-b299ad826636.png)

Expected:
I should see 0 in my currency fields, not `-`, or at least the displays should be consistent

**Comment by whatSocks** [comment]
Maybe I'm not even logged in?

**Comment by tinybike** [comment]
Fixed in 1753133b4e5b3b17081612fbc7d84790d47e4c7e.
