### ISSUE TITLE
MC: custom market form 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#2410]
Figma (yes/no):
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=449%3A1763

Figma (multiple choice):
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=449%3A2107
 
Figma (scalar): 
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=433%3A3

Figma (mobile):
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=466%3A1136

**Global notes**
- Each section of the form has a "Learn more" link that will open a modal with help content 

**Yes/no**
- Market type
   - Uses radio button card component 
- Reporting start date and time
   - Components used
      - Uses date picker component
      - Uses time picker component
      - Uses timezone component (defaults to users current timezone) 
   - When user enters the date and time, a box will appear below showing the users time converted to UTC0 (see [here] (https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=434%3A408) for example)
- Market question
- Market category (set the dropdown input widths to 156px)
   - There are three levels of categories
      - Category
      - Sub-category
      - Sub-sub-category
   - Initially user will see one category dropdown, with a list containing
      - Sports, politics, entertainment, finance, crypto, create custom  
      - If user selects "create custom", a text input will be shown, allowing user to enter anything they want
         - In addition text inputs will be shown for sub and sub-sub category entry 
         - This text input will use typeahead (2596 = component ticket), showing results to users after they type 2 characters, the lists are in spreadsheet, ping chwy for more on where to find these and how to use them
         - The typeahead results will highlight any characters in the results the user has typed as bold
      - If user selects one of the first five in the list, another dropdown will be shown "Sub-category", with a new list related to previous selection 
      - If user had selected "Sports", the sub-category dropdown will display a list predefined sports with the last item in the list being "create custom"
      - If user selects "create custom", a text input will be shown, allowing user to enter anything they want 
      - If user selects one of the predefined options in the list, another dropdown will be shown "Sub-sub-category", with a new list related to previous selection 
         - If there is no predefined list at the sub sub level, show a text input instead (see mocks) 
      - If user had selected "Soccer", the sub-sub-category dropdown will display a list predefined categories related to soccer with the last item in the list being "create custom"
      - If user selects "create custom", a text input will be shown, allowing user to enter anything they want 
      - [See all variations on Figma] (https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=1300%3A928)
   - See this [mock] (https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=1307%3A1) for rules on duplicate category names and a specific rule for the "Sports" category 
   - [Mobile mocks] (https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=1309%3A791)
- Resolution source
      - Uses radio button 1 line component 
      - IF user selects "from public website" reveal a text input using the components "activated and expanded state" copy for the input = "Enter website"
- Resolution details
- Designated reporter 
      - Uses radio button 1 line component 
      - IF user selects "Someone else" reveal a text input using the components "activated and expanded state" copy for the input = "Enter wallet address" 

**Multiple choice**
- Same as "yes/no" except for
   - New section "Outcomes" are displayed below the market question 
   - Displays two outcomes by default
   - User can tap the "add" button to add another outcome (revealing another text input) 

**Scalar**
- Same as "yes/no" except for
   - Three new sections
      - "Unit of measurement" allows user to select from a list of common denominations
         - "Other" will be displayed at bottom of list, if user selects it reveals a text input [See for mock] (https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=896%3A100)
      - "Numeric range" with two text inputs and the users previously entered [denomination] written in read only format 
      - "Precision" single text input with the users previously entered [denomination] written in read only format

**Comment by pgebheim** [comment]
@phoebemirman --- Is this done now?
