### ISSUE TITLE
I shouldn't be able to make 2 users with same username / pw

### ISSUE THREAD

**Issue by whatSocks** [AugurProject/augur#242]
I am able to register 

```
username: ce5
password: 123456
```
I log in and see some long account number like
`0xee85ad9fe08dd20d37237de75d7f45b85ac7e9c3`

I hit hard refresh and am logged out. (this seems like a bug as well)

I register again with the same credentials

I log in and see some other account number like
`0x65dc087e4418c8b1c4fd34838706885bbc0992f8`

I'd expect to see some validation message (or at least help text) telling me that usernames are not unique in this system, or some validation message telling me that the username is already taken.

**Comment by tinybike** [comment]
Fixed in a7e984da47753b11c0451b7a29e868e8b216f71d.
