### ISSUE TITLE
Market Creation Responsive Design Review

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#2444]
Figma (landing page):
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=466%3A6040

Figma (forms):
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=466%3A4406

Figma (review):
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=466%3A9520

Scroll to the right to see min/max at each breakpoint.

**Comment by pgebheim** [comment]
@phoebemirman implemented this as responsive already, this task will be to confirm that its working right / sketch out what isn't working right.
