### ISSUE TITLE
Pipe results of `registerTransactionStatusCallback` to augur emitter to inform the UI of pending transactions

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#2454]
registerTransactionStatusCallback is here: 
https://github.com/AugurProject/augur/blob/master/packages/contract-dependencies-ethers/src/ContractDependenciesEthers.ts#L123

**Comment by bthaile** [comment]
going in different direction with pending tx. closing

**Comment by justinbarry** [comment]
Closing as a duplicate of #2635
