### ISSUE TITLE
Default price probability for Market Trading

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2458]
In v1 we had 50% probability by default for untraded markets.

Now with `Invalid` as a tradable outcome what should be the probability for newly created market?

revised: return last trade price for `price` or null if outcome hasn't been traded.

**Comment by Chwy5** [comment]
WE should show a dash instead of any probability for untraded markets.....Showing any number (even the range divisable by the total number of outcomes) is misleading

**Comment by Chwy5** [comment]
Also we may need to consider handling invalid differently as well....there is most likely never going to be a good price to sell invalid.....the bid of invalid is what is most useful imo

**Comment by pacif1c** [comment]
For untraded outcomes I think it should default to the halfway point between the best bid and best ask. If there are no bids and/or no asks, then a dash. This is what I think is most useful to users + the closest thing to what the market is saying in terms of price/probability and since markets will only be visible if they have close bids/asks, this data should usually be present.

**Comment by Chwy5** [comment]
For untraded outcomes I think it should default to the halfway point between the best bid and best ask.- No this is misleading to the user.....and showing bad information is much worse than showing no information, when there is nothing to show....As a trader showing me nothing has traded is more useful than showing me a false price pt
>this data should usually be present....that is wrong....on any centralized exchange, that data would never be present.  It is only represented by a dash (or left empty) until it does.

**Comment by cillianhunter0** [comment]
@Chwy5 @matt-bullock should we do this now and get it out of the way? Doesn't seem a big change to trading/market cards.

**Comment by pgebheim** [comment]
@cillianhunter0 moved this item into the design list in Wrike, if this gets worked now it will get added to a timeslot.
