### ISSUE TITLE
Types for subscription events

### ISSUE THREAD

**Issue by brianosaurus** [AugurProject/augur#2481]
Add types to the events system
Add tests to generate and emit each of the types

Use this pattern found in augur.js/index.d.ts +252
```ts
  public augurNode: {
    submitRequest<K extends keyof Params>(command:K, options: Params[K], callback: ApiCallback<Return[K]>) : void;
  };
```

**Comment by pgebheim** [comment]
@brianosaurus -- Is this issue in progress?

**Comment by brianosaurus** [comment]
@pgebheim oops, yes.
