### ISSUE TITLE
[Roadmap] Flash Script Coverage for Manual Testing States

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#2488]

**Comment by pgebheim** [comment]
➤ Wrike Bot commented:

Robert Davidson All the necessary task dependencies have been completed, so you can start working on it right away.

**Comment by robert-e-davidson3** [comment]
I can get some of the flash scripts into the browser but not enough of the useful ones. The groundwork for removing Ganache is up for review but untangling the rest is more work than this Epic was specced for.

The big hurdle is how deploy currently works since it relies on the node-only `fs` module. This might be a deeper problem or might not, depending on whether or not `contracts.json` is importable in the browser.
