### ISSUE TITLE
Implement Post creation flow 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#2492]
Figma: (scroll to right to see all) 
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=709%3A3702

Notes: 
- When user selects the "Create" button on the review step, a confirmation modal will be displayed
   - Content modal with two actions "cancel" and "confirm" 
   - If user is using Edge or another wallet that doesn't require them to sign transaction, then display [this modal] (https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=813%3A7065)
- IF user selects "confirm" THEN take them to the portfolio page
   - IF their wallet has a confirmation step e.g. Metamask, this will now display and require the user to sign
   - Their market will appear in the "my created markets" panel
      - Apply an animation so users eye is drawn to that area (pushes other markets down, ping Cillian when looking at this) 
      - The market listed in the panel will have a pending tag and additional copy "When the market is confirmed you can submit initial liquidity"
- WHEN market is confirmed
   - IF they had not entered any initial liquidity, THEN display market in the panel as standard "open" state
   - IF they had entered initial liquidity, THEN display market in the panel as "open" with additional copy and action, [see mock] (https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=813%3A5612)
      - AND display red dot in the primary navigation beside "account summary" to indicate they have a new notification
- Notification will appear on the account summary page, it is the same as the "unsigned orders" notification with different copy [see mock] (https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=715%3A3897)
- "Pending orders for new market" modal - this is TBD when we work on DAI integration in the UI, but it will be a copy of the "unsigned orders" modal until then

**Comment by pgebheim** [comment]
Merging with #2499
