### ISSUE TITLE
Market Creation Liquidity integration

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2498]
Here is the backend PR, it's informative <https://github.com/AugurProject/augur/pull/3575>

impl design for market creation liquidity page. This includes calling middleware for getting ranking and results of liquidity passing default spread filter.

UI knows the default liquidity spread. Market creation liquidity will inform the user about:
 * tell user if their liquidity spread won't pass default spread filter.
 * tells user they need to add a bid or ask if one doesn't exist.

Need sdk method/getters to call to get two pieces of UI data:
 * given the user's current liquidity (order book). What ranking will the market be given.

See PR linked above to exact inputs and outputs
```typescript
export interface Order {
  price: string;
  amount: string;
}

export interface OutcomeOrderBook {
  bids: Order[];
  asks: Order[];
}

export interface OrderBook {
  [outcome: number]: OutcomeOrderBook;
}

interface getMarketLiquiditySortPositionParams {
  orderBook: OrderBook;
  numTicks: BigNumber;
  marketType: MarketType;
  reportingFeeDivisor: BigNumber;
  marketFeeDivisor: BigNumber;
  numOutcomes: number;
}

result: 

export interface MarketRanking {
  marketRank: number;
  totalMarkets: number;
}
```
design area of mocks
<https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=781%3A960>

![image](https://user-images.githubusercontent.com/3970376/64392656-6214d800-d013-11e9-96fe-c0aba6ca2a63.png)

![image](https://user-images.githubusercontent.com/3970376/64392662-680ab900-d013-11e9-9f36-0c37056676ab.png)

![image](https://user-images.githubusercontent.com/3970376/64392678-70fb8a80-d013-11e9-8942-2e22f4e24e05.png)

**Comment by pacif1c** [comment]
One thing I’ve been thinking for a while would be useful, and maybe this is already the plan, is that on the market creation page you can plug in different orders with different spreads + volume and see instantly where the market would rank in the sort. 

So by default it may say something like “Currently your market will not be visible to most users. Add liquidity to make your market more prominent.” Then as soon as I add some orders it will update to say something like, “your market will now rank 5th.” Ideally it could even say “add X amount to rank 4th.” Imo we want market creators competing for the top few spots.

Another way to do this that would be a bit more technical...but I think a lot more effective… if you’re a market creator on the liquidity page you see a text input where you enter the median price and then two sliders, one for the total volume (of Dai) you’re willing to put up and one for the spread.

Let’s say you create a yes/no market and enter the price as .50. If you set the volume slider to 100 Dai and spread slider to .10 it will place a 100 Dai bid at .45 and a 100 Dai ask at .55. Then you can adjust either slider and as you do so, it shows you the new ranking of the market in the sort. You can get a higher ranking by either tightening the spread or adding more volume. 

I think this would make things more frictionless for (most) market creators while encouraging them to put up good liquidity

**Comment by justinbarry** [comment]
Will need to create another getter that accepts `getMarketLiquiditySortPositionParams`.

```typescript
export interface Order {
  price: string;
  amount: string;
}

export interface OutcomeOrderBook {
  bids: Order[];
  asks: Order[];
}

export interface OrderBook {
  [outcome: number]: OutcomeOrderBook;
}

interface getMarketLiquiditySortPositionParams {
  orderBook: OrderBook;
  numTicks: BigNumber;
  marketType: MarketType;
  reportingFeeDivisor: BigNumber;
  marketFeeDivisor: BigNumber;
  numOutcomes: number;
}

```

**Comment by bthaile** [comment]
@BenDavidow i added some screen shots of design. Creating orders is intuitive for maker creators / liquidity providers. If design and product can come up with an intuitive new design/ component for market creators to shape the order book, based on your ideas.

**Comment by pgebheim** [comment]
@JohnDanz @bthaile This was closed last month yes?
