### ISSUE TITLE
KYC Order Book

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2503]
KYC order book scenarios:

* User not logged in:
Don't show KYC orders.
* User logged in not KYC'd
Don't show KYC orders, only non-KYC orders
* User has multiple KYC tokens
Show all non-KYC orders and all KYC orders the user owns KYC token for.

Will it be possible for KYC users to take KYC orders and create non-KYC orders?

**Comment by justinbarry** [comment]
@bthaile we should set some time aside next week to talk through this.

**Comment by bthaile** [comment]
@justinbarry lets bring in @nuevoalex so he can check if the description makes sense.

**Comment by nuevoalex** [comment]
Anyone can make or take non KYC orders.

I don't believe we should do any work on this for V2 launch personally. (Can be done after)

**Comment by joeykrug** [comment]
iced
