### ISSUE TITLE
Trading: Wallet UX

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#2515]
Chat to Andy about this when picking up ticket. 

**This piece of work covers:** 

* Review and design the 'connect a wallet' UX 
  * Review new wallets and addition of Gnosis safe with Andy 
* Merge wallet, gas price & blocks behind dropdowns in the global app bar (when wallet is connected). 
  * Explore addition of send/receive fund buttons 
  * Explore addition of displaying fund balances 
  * Blocks behind is out of place, one idea is to display only when behind, outside of the dropdown

---NOTES---

**New wallets**

* Portis
* Squarelink
* Formatic

**Gnosis safe** 

* Onboarding
  * IF logged out
    * Log in button
      * Have wallet? Yes/No 
        * No -> promote Edge (but only has fiat on ramp on mobile) 
* New user flow (with wallet)
  * Has a wallet with nothing
  * Push them down the simple path 
* Existing user flow (or user that has a wallet with funds) 
  * Connect and has DAI / ETH
    * Push them down the more sophisticated path

**Comment by pgebheim** [comment]
@andrewdamelio -- What's your estimate for the remaining work on this?

**Comment by andrewdamelio** [comment]
All of this work is complete except for squarelink,  that still requires some work.  I had some initial issues getting it to play nicely with ethers so I would say another day or two of discovery work to finish this up!

**Comment by pgebheim** [comment]
Subsumed by wallet/onboarding work
