### ISSUE TITLE
gasPrice override UI

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#2519]
We need to gasPrice on the account object somewhere. We need to pull it from there if it's not set then get the gasPrice from the provider.

This is really only important on mainnet, we use eth gas station as an API to get high, standard and low gasPrices every 100 blocks. The user has ability to override the gasPrice they want to use. We need to either pass the override value or just get current standard gasPrice from the provider when sending a tx.

**Comment by pgebheim** [comment]
Implemented in modals etc.
