### ISSUE TITLE
Market creation save draft

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2532]
Give user the ability to save multiple "draft" market creations.

store a structure in localStorage that keeps track of user inputs and where they are in the market creation process. 

See design for table of draft market creations

When user clicks on an item it will hydrate the structure and put the user right where they were when they clicked "save draft" button

for the first effort:
1. keep "save drafts" button active
2. user can only save a draft if the question has been inputted
3. if user clicks drafts with no market question there will be a error message (design to provide)

**Comment by cillianhunter0** [comment]
putting question here to keep question and response together.
```
Question for design:
What is the label in the `saved drafts` scrollable component on the landing page? Looks like the market question. Just to clarify, if the user doesn't input a question they can't save a draft?

To help the user differentiate between saved drafts, allow them to put the label. Then they can save multiple versions of the market they are working on?
```

Yes it's the market question. If the user doesn't enter a question we can display a validation error that tells them what they need to do. I'll work on that tomorrow. 

For the first version of the save feature I think we should keep it simple, you can only save one version of the market you're working on. If you save multiple times it just overrides the previous save.
