### ISSUE TITLE
middleware: support for Market creation categories

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2535]
MODIFICATIONS to getter.

 * Don't include markets with reportingState of `awaiting_finalization` or `finalized`.
 * Calculate both `Volume` and `OpenInterest`
 * Return display values to 2 decimals

Market creation needs all categories and sub-categories stats so the user can pick the category to put their market. We need two metrics to help the user locate the correct category. 

They are 

1. current trading volume for all open markets given category and in their sub categories. 
2. Number of markets in the category. including all markets in sub categories

This is used to describe popularity of categories to the market creation. We can have a new getter `getCategoryStats`

input: 
categories : ["sports", "entertainment", ...]

output: 
```
{
  "entertainment": {
    "category": "entertainment",
    "numOfMarkets": 22,
    "volume": "200",
    "openInterest": "2000",
    "categories": {
      "movies": {
         "category": "movies",
        "numOfMarkets": 12,
        "volume": "100",
        "openInterest": "1000"
      },
     "theater": {
         "category": "theater",
        "numOfMarkets": 10,
        "volume": "100",
         "openInterest": "1000"
     }
  },
  "sports": {
    "category": "sports",
    "numOfMarkets": 34,
    "volume": "4000",
   "openInterest": "2020",
   "categories": {
    "soccer": {
         "category": "soccer",
        "numOfMarkets": 12,
        "volume": "900",
         "openInterest": "1000"
     },
    "american football": {
         "category": "american football",
        "numOfMarkets": 22,
        "volume": "3100",
         "openInterest": "1020"
      }
    }
  }
}
```

![image](https://user-images.githubusercontent.com/3970376/60139015-035cf380-9772-11e9-9ecb-d0fbd78b41d3.png)

**Comment by justinbarry** [comment]
@bthaile Is this handled by #2864?

**Comment by bthaile** [comment]
we don't need the market info objects just the number of markets per category and the trading volume summed up.

**Comment by robert-e-davidson3** [comment]
SCOPE UPDATE: We need to accept a list of categories and return their secondary categories as well.

**Comment by robert-e-davidson3** [comment]
This is functional now but is ripe for improvements. I put that work in this ticket: https://github.com/AugurProject/augur/issues/4352.
