### ISSUE TITLE
create component for number lists

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#2539]
![image.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/3df78658-04d8-4e75-a979-c1371e37f32f)

**Comment by cillianhunter0** [comment]
Link for the min max states of this component
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=1027%3A69449

**Comment by pgebheim** [comment]
Completed Jun 25
