### ISSUE TITLE
gasLimit issues when setting from the UI

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#2542]
Having some gasLimit issues when sending transactions using Edge/Trezor, where I have to provide a gasLimit. 

Seems like calling provider.estaimateGas(tx) doesn't return the same thing as, for example, calling ```faucet_estimateGas``` right off the contract instance.

**Comment by pgebheim** [comment]
Provider adds extra gas because gas estimates from geth/parity are wrong for varying reasons.
