### ISSUE TITLE
Fill order notification issues

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#255]
@adrake33 commented on [Thu Nov 29 2018](https://github.com/AugurProject/augur-ui/issues/2510)

Reported by @Chwy5:

I started with a short position. The best offer on the order book showed 1 share at .8 (which i clicked on, to filter into the order ticket) I then changed the order ticket quantity to 2 shares and had the fill order only button checked....So I was a buyer of 2 shares (knowing i would only be filled on one)

![11-29wrongmessage.jpg](https://images.zenhubusercontent.com/5bff29dc5cb43a45a18add9f/5b60238e-2691-4dcb-9b8e-46f8dcac9cd3)

The message is wrong...it should show buy order and not sell.

Also, checking the fill order box and  changing the quantity - which will result in a partial fill ( i was filled on 1 share and my other didnt hit the book, like expected) resulted in a pending state (even though I have an etherscan confirm)

**Comment by joeykrug** [comment]
was fixed but not closed b/c old/new issue number
