### ISSUE TITLE
Augur top left link

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#255]
Clicking on AUGUR on the top left of the site shouldn't reload the page

**Comment by tinybike** [comment]
Right now this is intended behavior.  Am open to suggestions though!

**Comment by joeykrug** [comment]
With a site that takes ~20 seconds for me to load on Windows 10 Opera having any refreshes beyond one I purposefully do by either F5 or clicking the refresh button is annoying

**Comment by tinybike** [comment]
Point taken.  I'll make it just link back to Overview instead of doing a full refresh.

**Comment by tinybike** [comment]
Added in 7f7e9549adc5d765b0848841a00901a2c12e54c7.
