### ISSUE TITLE
denomination selection component

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#2560]
the dropdown is only for templates market creation, custom market creation will just have a text input?

![Screen Shot 2019-06-24 at 9.58.34 AM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/c50940eb-a080-4ffb-b551-db570b8dd8da)

**Comment by JohnDanz** [comment]
seems as though there is a common component between this issue and this one:
https://github.com/AugurProject/augur/issues/2559
