### ISSUE TITLE
squarelink sdk issue

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#2572]
Squarelink seems to throw the error ```invalid argument 1: hex number with leading zero digits``` when trying to initialize the provider/signer with out API.

```
import { Web3Provider } from "ethers/providers";
import Squarelink from 'squarelink';

const sqlk = new Squarelink("...", { ... });
const provider = new Web3Provider(sqlk.getProvider());
// using provider.getSigner()
```

maybe related ->  https://github.com/ethers-io/ethers.js/issues/148

**Comment by pgebheim** [comment]
Closing icebox issues
