### ISSUE TITLE
Take order transaction fails on categorical market

### ISSUE THREAD

**Issue by AugurIntegration** [AugurProject/augur#259]
This issue was partly fixed by ch18028, but we still need to determine why the tx is failing.
...

This issue is now resolved, is it possible ch13352 fixed it?
 -epheph
...

Hmm, I don't think ch13352 would have fixed this. That was completed back in July, and it was for market creation. This issue was seen recently.
 -adrake33
...

You're right... I'll see what else might have fixed it, or if it was fixed
/cc @phoebemirman 
 -epheph
...

It is not fixed, i had repro case wrong. i can cause failure now
 -epheph

**Comment by adrake33** [comment]
Backlogging this since it will require other augur.js work.

**Comment by epheph** [comment]
The confusion about this being resolved earlier was that there was also a bug in the ethrpc layer related to the pre-flight transaction throwing, without being caught/calling the callback.

The underlying issue here is not resolved. I believe this call was failing deep in the transaction and not in an early modifier or check.

**Comment by joeykrug** [comment]
What's status of this?

**Comment by adrake33** [comment]
I'm not sure what the repro steps are for this. It's possible this is still a bug. 

@Chwy5 -- are you aware of any bugs with taking orders in categorical markets?

**Comment by Chwy5** [comment]
Yes...went over it with Justin, PG and Tom.  

Attempting to take an existing bid off the order book.  I clicked on the existing bid and filtered into the order ticket, then went to trade vs it.  My order hit up on the order book (but did not trade) so we were left with a crossed order book.  It did duduct from my frozen funds though.  It appears this was a ghost order.  The order apparently traded 2 days earlier, but did not get removed from the order book.

**Comment by AugurIntegration** [comment]
@chwy5 -- this ticket was referring behavior in v1. We went through v2 behavior yesterday so that wouldn't really apply here.
