### ISSUE TITLE
MC component: typeahead 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#2596]
We're using typeahead search for category selection during market creation. 
[See figma mocks] (https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=1300%3A928)

We can base this off of the "simple typeahead" component here: 
https://ng-bootstrap.github.io/#/components/typeahead/examples

Rules
- It will follow the same styling rules as a standard dropdown list. 
- When user enters two characters it triggers the typeahead list to appear below the text input
- The characters the user enters will be highlighted as bold in the results of the typeahead 
- If there are no matching results, the type ahead won't appear
- If there are matching results but the user continues to type and there are no more matches, the type ahead will be hidden

**Comment by bthaile** [comment]
Typeahead is also called auto-complete

We could use this dropdown type for all dropdowns in market creation. 
@phoebemirman @JohnDanz thoughts?
