### ISSUE TITLE
Creation date sort

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#261]
Creation date sort doesn't work [sorts by expiration date]

**Comment by tinybike** [comment]
Seems to be working for me.  Would you mind taking a screenshot of when it fails for you?

**Comment by joeykrug** [comment]
I can't get it to happen again right now, but it looks like this:
![capture](https://cloud.githubusercontent.com/assets/5925937/12602281/8ce0a5ec-c46d-11e5-974c-01df7bac0f0c.PNG)
Except creation date appears as a `-`

**Comment by joeykrug** [comment]
And so then the sort doesn't work right

**Comment by joeykrug** [comment]
This doesn't happen anymore
