### ISSUE TITLE
SSL FireFox not working (Ledger not working)

### ISSUE THREAD

**Issue by AugurIntegration** [AugurProject/augur#262]
Ledger needs SSL to work FireFox has some issues with the way we are either using self signed certificates or that we use ws://  to connect to augur-node, maybe they want wss://

Need to get ledger working in Chrome first.
...

@tomhaile What's the state of this now?
 -sharkcrayon
...

Once ch13531 is fixed then Ledger should be thoroughly tested again in FF.
 -sharkcrayon
...

even with using wss with augur-node we need real certs.

![screen shot 2018-07-17 at 10 04 33 pm](https://user-images.githubusercontent.com/11491365/49775299-950c8400-fcac-11e8-810c-67bce81942d4.png)

 -bthaile
...

ch14601  this might get fire fox happy with CORs issues and then using real certificates should get ledger working in Fire fox.
 -bthaile
...

Let’s determine the steps for allowing users to do this, and Peter can add them to the docs.
 -adrake33

**Comment by bthaile** [comment]
Need to flip a setting in Firefox

`network.websocket.allowInsecureFromHTTPS`  needs to be set to true:
https://stackoverflow.com/questions/11768221/firefox-websocket-security-issue/12042843#12042843

`security.webauth.u2f` needs to be set to true:
https://support.mozilla.org/en-US/questions/1218921


Even with these 2 settings turned on I get this popup:
Same with myCrypto.com, MEW says that Firefox doesn't support u2f and can't be used.

![screen shot 2018-12-01 at 5 21 33 pm](https://user-images.githubusercontent.com/3970376/49333920-955e9e00-f58d-11e8-9ad1-4e28aac34a36.png)



![screen shot 2018-12-01 at 5 20 08 pm](https://user-images.githubusercontent.com/3970376/49333913-72cc8500-f58d-11e8-9f77-85609bb6b3c8.png)

**Comment by bthaile** [comment]
https://blog.filippo.io/mkcert-valid-https-certificates-for-localhost/


Check this out for real certs for localhost

**Comment by bthaile** [comment]
Comments from Micah in #dev channel in discord, capturing here:

```
Internet suggests that exception is thrown when you do a cross-domain JS load.
Unfortunately, since the code is minified the error and debugging is pretty useless.
Yeah, looks like React caught the error and then rethrew it from somewhere else, so getting a breakpoint on the actual exception may prove challenging.
Separately, holy smokes you all have a lot of exceptions during your startup!
I turned on "break on all exceptions", there must be 100+ before the page finishes processing its startup scripts.
Unfortunately my debugger is not loading the .js file (I think it is too big).  However, I got a function name: initialConnect > connect is the top of the stack.
```
![image](https://user-images.githubusercontent.com/3970376/58338574-96220f80-7e0d-11e9-8b5c-591c80150eb6.png)

```
Exception is when doing:
new WebSocket("ws://127.0.0.1:9001", [], undefined, void 0, { timeout: 100 }, {})
If I navigate to google.com and paste that into my console, I get the same error.
```
![image](https://user-images.githubusercontent.com/3970376/58338596-a639ef00-7e0d-11e9-939f-3002eb209f23.png)

```
:point_up: is a FF console while looking at google.com
I just verified that I don't have any local services listening on port 9001 (though I don't think it is getting as far as attempting the connection).
I get the same error no matter the port.
```

```
The error goes away if I set the protocol to wss instead of ws.
@tomhaile I think the problem is that you are trying to open an insecure WebSocket connection from a page that was loaded with HTTPS.
Firefox is saying, "no, you cannot load any insecure resources when browsing a secure page.
I'm relatively surprised that the other browsers allow it...
```
<https://bugzilla.mozilla.org/show_bug.cgi?id=917829>
<https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications>
```
WebSockets should not be used in a mixed content environment; that is, you shouldn't open a non-secure WebSocket connection from a page loaded using HTTPS or vice-versa. In fact, some browsers explicitly forbid this, including Firefox 8 and later
```

**Comment by joeykrug** [comment]
What's status of this

**Comment by bthaile** [comment]
No status change, that I know of, no  investigation of current FF version. @andrewdamelio did you test firefox and ledger when you were making changes to wallet integration?

**Comment by andrewdamelio** [comment]
@bthaile I don't believe I did, I'll install firefox later this week and give it a test.

**Comment by joeykrug** [comment]
We use ledger thru metamask now
