### ISSUE TITLE
Trading: Loading states

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#2627]
Users may land on different pages, most important we need loading states for components on pages: 

* Landing page
* Market list page
* Trading page 

Discuss loading times with Paul/Tom 

Don't forget this state: 

![](https://storage.www.wrike.com/filemeta/thumb100/F110939577.A2810379)

┆Attachments: <a href="https://storage.www.wrike.com/attachments/110939577?accountId=2810379">image.png</a>

**Comment by pgebheim** [comment]
➤ Joey Krug commented:

If loading is a thing / takes long enough to need a loading state we’re probably fucked anyway

**Comment by pgebheim** [comment]
➤ Cillian Hunter commented:

Joey Krug i'm not sure what the loading time is going to be, need to sit down with paual/tom on this. But this ticket specifically refers to loading states of components, so for example, if it takes 0.5 seconds on load before content loads in to market cards, we'll have a loading state of the card, basically a blank card, you've prob seen this pattern on twitter/facebook.
