### ISSUE TITLE
PL for winning No Shares is incorrectly set to 0 at market finalization

### ISSUE THREAD

**Issue by AugurIntegration** [AugurProject/augur#263]
- Acquire No shares by selling Yes and matching it with another account
- Move time to end the market and go through reporting and the dispute period
- Finalize the market
- Unrealized PL will be 0
...

@achapman Is this still an issue? Can this be closed?
 -adrake33
...

Nope, still an issue. I believe @pgebheim said he had started looking at / working on this?
 -nuevoalex
...

This is the highest priority item for me to work on.
 -pgebheim
...

@achapman is going to start work on synthesizing the trades of outcomes based on the what is escrowed, and I can take it from there to do the time-series breakdown of the calculations.
 -pgebheim

**Comment by pgebheim** [comment]
Fixed with big PL merge.
