### ISSUE TITLE
UI: user needs to be able to transfer ETH, REP and DAI

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2637]
middleware tix: https://github.com/AugurProject/augur/issues/2636

UI needs to give the user ability to transfer ETH, REP and DAI in account summary page in the transfer-funds modal.

middleware to add helper methods to be called in contractCalls.ts. Currently it's stubbed out.

**Comment by pgebheim** [comment]
@bthaile - Does this still need the specific middleware support?

**Comment by bthaile** [comment]
Yes, it might be only educational, but the UI needs to know how to transfer DAI and ETH. I think REP is taken care off.
