### ISSUE TITLE
allow user to claim winning trading proceeds

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2640]
look at `augur/packages/augur-ui/src/modules/modal/containers/modal-claim-proceeds.ts`

Summary:

Add new contract calls in `ContractCalls.ts`, give user ability to claim individual winnings or batch claim multiple markets. 

Todo:

Need to add information on user's positions to indicate winnings.  Use existing modal listed above. It will need to be modified to work with V2. 

There isn't a mock to allow user to claim each market individually, need to allow. 

![Screen Shot 2019-09-10 at 3 55 43 PM](https://user-images.githubusercontent.com/3970376/64649962-a32a3500-d3e3-11e9-98de-42ca631a5932.png)

**Comment by bthaile** [comment]
this is still under development

**Comment by pgebheim** [comment]
Works
