### ISSUE TITLE
Need some way to tell if the user is on the correct network

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2641]
since we don't have augur-node to match up network ids, we need to have some configuration to tell the user they are pointing at X network.

**Comment by justinbarry** [comment]
![image.png](https://images.zenhubusercontent.com/5c0090502c4f4d3a81333d42/b9fe1e18-b7ff-4e44-b9d3-b9cb8f1e5319)

**Comment by pgebheim** [comment]
Works now:

![image](https://user-images.githubusercontent.com/86010/68192990-1923c600-ff67-11e9-8e33-608343e34c17.png)
