### ISSUE TITLE
OrderEvent events aren't coming through

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2661]
In SyncableDB.ts eventName of "OrderEvent" comes in after a trade but there are no logs.
```
    if (this.eventName === "OrderEvent") {
      this.parseLogArrays(logs);
    }
```

So the order events don't make it to the UI.

Steps to repro:

1. start UI
2. log in as contract owner 0x913..
3. go to a market and cancel order
can put console.log in wrap-log-handler.ts
```
    console.log("event name", log.eventName);
```
4. sign MM pop up
5. notice there isn't a console log for order event but there is for New Block

**Comment by brianosaurus** [comment]
For the record the code above isn't why Order events aren't coming through. It's more sinister and will require testing and simulation to figure out why. @bthaile

**Comment by brianosaurus** [comment]
Works for me!

**Comment by bthaile** [comment]
I'm not able to see Order events in the UI. I see market created and universe created. no Order events.

**Comment by bthaile** [comment]
I didn't have the OrderEvent wired up. I'm getting order events, now that I fixed that.
