### ISSUE TITLE
User-Specific Data Fetching

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#2662]

**Comment by pgebheim** [comment]
@bthaile -- I am going to move this epic off the Roadmap, since it is being use for organiational purposes not as a piece of work with and end date.

Each ticket in here should ultimately be put into some deliverable epic.

**Comment by bthaile** [comment]
I agree, if it makes sense, we prob need to focus the effort across UI and backend for some of these.

**Comment by bthaile** [comment]
closing this Epic.
