### ISSUE TITLE
Tell user number of tx needed to take order

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2663]
It's possible that the user will need to sign multiple tx to make a trade.

In order form confirmation display number of transactions needed to make trade. 

This task is waiting for design.

**Comment by bthaile** [comment]
moving this to trading, we now have the information needed from sim trade to tell the user roughly how many tx will be needed.

**Comment by Chwy5** [comment]
The box notifying number of transactions needed does appear in the order ticket.  But there is an issue with Xing out the box to see the information behind it.  When I click on the x to close the box, it returns again

**Comment by joeykrug** [comment]
done afaik
