### ISSUE TITLE
figure out UI changes for order price change

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2694]
Two impacts to the UI for new functionality that allows users to change price of existing orders.

1. Order Event log comes in for existing order price change. UI needs to handle this case.
2. User can change price of their existing open order

Need design for this feature. might be as easy as user clicking on price in `Open Orders` section of market trading page and updating the price.

**Comment by pgebheim** [comment]
Ok -- this feature is being removed since it doesn't exist on the 0x mesh.
