### ISSUE TITLE
uncaught (in promis) errors with derived db (Markets)

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2704]
![image](https://user-images.githubusercontent.com/3970376/61059352-7b582a00-a3be-11e9-96fb-0ebcdc2e6111.png)

document update conflict errors in `Markets` collection.

tried to capture stack trace in gist
<https://gist.github.com/bthaile/772c20af22d916bc427af2bae05cbada>

**Comment by justinbarry** [comment]
Addressed by UpsertPlugin
