### ISSUE TITLE
Setup mechanism to switch over to SDK integration test to use Blockstream programatically

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#2710]

**Comment by robert-e-davidson3** [comment]
Right now we test using bulk sync. We should also be able to test using blockstream sync.

**Comment by justinbarry** [comment]
^ in at least some of the integration tests.

**Comment by pgebheim** [comment]
Adding this to epics so we can think about actually doing it...

**Comment by joeykrug** [comment]
closing, open if relevant / matters
