### ISSUE TITLE
MC: Market question text input on custom form - default text 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#2711]
The default text in the input should change based on the market type selected above. 

Yes/No: 
"Example: Will [person] win the [year] [event]?"

Multiple choice: 
"Example: Which Team will win: [Team A] vs [Team B] on [date]?"

Scalar: 
"Example: How many [goals/points] will [person] score in the [year] [event]?"

**Comment by bthaile** [comment]
Is this for templates? If so the template text is set.

**Comment by phoebemirman** [comment]
Its for custom. It is also just for the placeholder text in the input
fields.
