### ISSUE TITLE
Only run tests for changed modules in CI

### ISSUE THREAD

**Issue by AugurIntegration** [AugurProject/augur#272]
This will help us conserve build resources and significantly speed up CI.
Probably involves this command:

`npx lerna ls --since $SYSTEM_PULLREQUEST_TARGETBRANCH`

Note: `$SYSTEM_PULLREQUEST_TARGETBRANCH` is provided by Azure CI pipelines.
...

I implemented a first round of this in the monorepo, will only run tests based on files changed in the last commit. Still in testing phase.
 -petong

**Comment by petong** [comment]
This is done via conditionals in the azure pipeline configuration.
