### ISSUE TITLE
Add info to whitepaper on binary, scalar, & categorical markets

### ISSUE THREAD

**Issue by AugurIntegration** [AugurProject/augur#273]
@joeykrug noticed we don't describe the different market types of Augur in the whitepaper and asked that this be added.
...

I think the whitepaper will also need to be updated to reflect some of the changes being made in v2.0. I can address this issue at the same time I update the paper to reflect the v2 changes. 
 -Austin-Williams
...

Sure, sounds good. Just wanted to make sure we have a ticket for this so we remember to add it.
 -adrake33

**Comment by pgebheim** [comment]
@Austin-Williams -- Thoughts on this?

Not sure we need to do this in the whitepaper.

**Comment by Austin-Williams** [comment]
My personal preference is to leave it out of the white paper and keep it in the docs.
