### ISSUE TITLE
Add transaction states to UI

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2747]
Currently in the UI, it only tells the user `processing` with a wait indicator. If the tx fails or gets cancelled the Ui is stuck displaying `processing`.

With new transaction lifecycle hooks available to UI we can tell the user the state their transaction is in. 

States:

awaiting signing
pending
success
failure

it's possible for the user to cancel the signing and the UI will get `Failure` message.

**Comment by Chwy5** [comment]
Yeah, Like these 4 can we show # of confirms to pending?

what else can be added?

**Comment by bthaile** [comment]
Yes we can show number of confirmations. We can show inline and in alerts. We just need ti figure out the behavior and code it up.

**Comment by pgebheim** [comment]
@bthaile -- I am closing this since I believe its been addressed in the most current designs, re-open if I'm incorrect.
