### ISSUE TITLE
Review App for Major Design Issues

### ISSUE THREAD

**Issue by AugurIntegration** [AugurProject/augur#275]
Matt will be the owner here after he's added to CH.

Explore the app. The purpose here is to get to know it, and to keep an eye out for glaring visual and usability issues. This is a first pass for the major issues that jump out at you; we can do a more fine-toothed pass later on.

Keep a list of the issues you find.  Separate them by priority: having a "high priority" and "low priority" list is probably enough granularity here, but do what you think is right.
...

@mattbullock I've added a task list within this story. I know you may have gone through a number of these views already - go ahead and check off any that you've already done.
 -sharkcrayon

**Comment by adrake33** [comment]
Closing, as this was an old ticket that got migrated from CH.
