### ISSUE TITLE
Implicitly type events on api event emitter

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#2757]
This is a nice to have. See pattern used here:

https://github.com/AugurProject/augur/blob/90eba649f77d043dcd1f52c62351abe5ad3053b8/packages/augur.js/index.d.ts#L252

and here:

https://github.com/AugurProject/augur/blob/90eba649f77d043dcd1f52c62351abe5ad3053b8/packages/augur-node/src/index.ts#L12

**Comment by pgebheim** [comment]
Agreed this is a nice to have, closing as informational.
