### ISSUE TITLE
Interactive walkthrough for new users

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#277]
A gmail-esque walkthrough for new users, so they understand what's what and basically how to use Augur.  Most shiny, service-in-the-cloud websites have these now.  Essentially it's just a series of tooltips that the user clicks on, guiding them through the site's functionality.  Augur's an involved enough site that it badly needs something like this.

**Comment by thinkloop** [comment]
Are we using the ui up on dev:

![image](https://cloud.githubusercontent.com/assets/118814/12904485/d2d15328-ce9d-11e5-8662-cb3f4f61a73a.png)

Or the one in uxpin:

![image](https://cloud.githubusercontent.com/assets/118814/12904568/3e886570-ce9e-11e5-9b98-4e23b549481f.png)

**Comment by tinybike** [comment]
Is it possible to do this on the UI as it exists on dev, with the understanding that it will be mutating underneath you until it looks like the one on uxpin?  (The one exception is that I do think there should be an Augur logo / title in the upper left, which I just noticed is absent from the uxpin...)

**Comment by tinybike** [comment]
Basic walkthrough added in 2d4981f58352cee93c4449f2483ecf3145b00c70.
