### ISSUE TITLE
wire up bell alerts to transactions lifecycle hooks

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2770]
when a tx pending comes in build the initial bell alert. Update the bell alert when the confirmation or failed tx comes in.

store alerts the same as before in localstorage. When the user logs in loop through all pending tx and look up and update the status. 

need to use `getTransactionByHash` call in contractCalls.ts to get the tx. I think ethers can be used to pull the transaction information.

**Comment by pgebheim** [comment]
@phoebemirman's work on #3858 did this

@bthaile Can you confirm? I logged in recently and got bell alerts for previous txns
