### ISSUE TITLE
Notification for when a market creators liquidity is low/depleted

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#2785]
We need to create a new notification that triggers when: 

[TBD] Joey is working the logic. 

Notification copy: 
[Heading] Market outside of spread filter 
[Body] ...

Notes 
- Modal might just display instructions, recommendation on what to do 
- Show a countdown timer (24 hour etc)

**Comment by pgebheim** [comment]
@cillianhunter0 -- Is this still in design?

**Comment by pgebheim** [comment]
@Chwy5 -- This is one we missed for the notifications -- Adding to your spreadsheet and adding to next sprint to keep track of it.
