### ISSUE TITLE
User newly created orders don't show up

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2786]
User logs in and creates a new order on market trading page. The new order doesn't show up in the `Open Orders` section of the market trading page.

![image](https://user-images.githubusercontent.com/3970376/61383194-cddc8f00-a873-11e9-8f2f-7ff934c885ac.png)

![image](https://user-images.githubusercontent.com/3970376/61383265-f06ea800-a873-11e9-837a-34eb79eef612.png)

**Comment by justinbarry** [comment]
Addressed by upsert plugin.
