### ISSUE TITLE
Registering an account freezes browser, sometimes causing crash or irrecoverable freeze

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur#279]
Similarly logging-in causes an unnerving stall, but much less severe. If the process is expensive, perhaps it can be done in a non-blocking async way?

**Comment by tinybike** [comment]
Everything should be 100% async already.  None of this stuff should be computationally intense in the front-end.  When you say an "unnerving stall", does it actually lock up the browser?  Also, what setup were you using when you observed the freeze?  Localhost?  cloud9?  augur-dev.firebaseapp.com?  app.augur.net?  Were you using a local or hosted Ethereum node?

**Comment by thinkloop** [comment]
Good questions! :-)

> When you say an "unnerving stall",  does it actually lock up the browser?

Yes, the browser fades out and freezes so it can't be interacted with and threatens a crash

> what setup were you using

This is off the development branch, watch build, on [cloud9](http://augur-client-thinkloop.c9.io/) interacting with a hosted ethereum node

**Comment by tinybike** [comment]
Hmm ok, let me get on cloud9 then, and let's see if we can get it back to unnerving stall state so I can have a look at it!

**Comment by tinybike** [comment]
Does this still happen?

**Comment by tinybike** [comment]
Was never able to reproduce this; closing.
