### ISSUE TITLE
TypeError: Cannot read property 'sync' of undefined

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2796]
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/5d479acc-edcc-4d50-a31d-94554b2340a4)

switched user from non-contract owner to contract owner.
tried to capture stack trace
<https://gist.github.com/bthaile/cd8c058c37d2fc2ab13cbc093cc4e2ec>

**Comment by justinbarry** [comment]
~~Yep. See #2697.~~

~~Closing as duplicate.~~

**Comment by justinbarry** [comment]
Yep. See

**Comment by justinbarry** [comment]
This is related but not exactly the same. Re-opening for now.
