### ISSUE TITLE
restarted UI and got rollback errors

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2797]
`DB.ts?b8fd:315 Uncaught (in promise) TypeError: Cannot read property 'rollback' of undefined`

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/7a844e55-8683-4259-9e00-1475eda220a6)

tried to capture stack trace
<https://gist.github.com/bthaile/63d3b249dafae5487ecd2061c0c7897a>

**Comment by justinbarry** [comment]
This appears to be fixed. Please re-open if it happens again.
