### ISSUE TITLE
Recommend differentiating style/look of non-interactive elements like market tags

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur#281]
![image](https://cloud.githubusercontent.com/assets/118814/12970646/750368ee-d05f-11e5-895e-41ee50d14083.png)

Referring to the uxpin for market here: https://live.uxpin.com/b6f189f8b71325ddf9ce9cd9268ab0998a7ea9b3#/pages/35153837/nosidebar

I would like to propose having a different look/feel for non-interactive elements, like the market tags circled in the image vs. the drop-down (also circled) or tab headers.

**Comment by Newportkiwi** [comment]
Yeah, that's a good call. I'll play around with the design of the tags and update on Zeplin/UXPin (probably just on the one page on UXPin though).

@tinybike What is the vision for tags - should a user be able to click to show all other markets with that tag? Kinda like a search term that displays search results?

**Comment by Newportkiwi** [comment]
We could make them plain white:

![2016-02-11_09-11-26](https://cloud.githubusercontent.com/assets/16562458/12972761/a971187a-d09f-11e5-810b-953720a7d2e2.png)

Or plain white with rounded ends (radius 10px):

![2016-02-11_09-10-49](https://cloud.githubusercontent.com/assets/16562458/12972775/bb9f21fe-d09f-11e5-9f23-9be3bfd788f7.png)

Any thoughts or preferences?

**Comment by tinybike** [comment]
I like the plain white (without the rounded ends) personally.

**Comment by Newportkiwi** [comment]
I like the same. The round corners look a little out of place with most other elements being kinda square. I'll update the style guide (but not the prototype).
