### ISSUE TITLE
Update Markets UI per uxpin

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur#282]
Make this:

![augur_markets_current](https://cloud.githubusercontent.com/assets/118814/12970731/7c045710-d060-11e5-9a02-006d53305048.PNG)

Look like this:

![image](https://cloud.githubusercontent.com/assets/118814/12970744/941638c8-d060-11e5-9cb5-9bd9b734886f.png)

Per this:

https://live.uxpin.com/b6f189f8b71325ddf9ce9cd9268ab0998a7ea9b3#/pages/35153837/nosidebar

And this:

https://app.zeplin.io/project.html#pid=56ba73076498ba9d0bea0bcb&sid=56ba7328836767f573e8878a

**Comment by thinkloop** [comment]
Hey @Newportkiwi,

I'm really enjoying working with the materials you provided, making my workflow very smooth, great job!

Quick question, they bg grey here:

![image](https://cloud.githubusercontent.com/assets/118814/12971769/af54861a-d06c-11e5-8852-4a65f1b41755.png)

Seems to be a shade in between pale-grey (#eceff4) and cloudy-blue-two (#cad3df), any idea which one it should be?

**Comment by Newportkiwi** [comment]
Hey Baz, the colours are all consistent on the style guides on Zeplin (I uploaded a second page yesterday with some spacings, headers and a few other things). So go with the elements/spacings on Zeplin and use the UXPin screens just for the layout and content.

The style guides on Zeplin also have a different design for tabs. The prototyping software didn't let me use my design without a lot of hassle, so I just used what they offered.

Any questions, give me a shout on Slack when you're up an about.

**Comment by tinybike** [comment]
Good start!  Just noticed that the text box styling has gone a bit wonky...
![create-market](https://cloud.githubusercontent.com/assets/2637020/13007491/80d6e812-d145-11e5-9975-077fe20f9c8e.png)

**Comment by tinybike** [comment]
![initial-liquidity](https://cloud.githubusercontent.com/assets/2637020/13007897/f866da34-d147-11e5-856a-5067f7841429.png)

**Comment by thinkloop** [comment]
How do you create a market? I can't seem to find that ui.

**Comment by Newportkiwi** [comment]
Right now...Markets page, blue + sign up to the right.

**Comment by thinkloop** [comment]
Ty, found it.

What about that "initial liquidity" box, know where that is?

**Comment by Newportkiwi** [comment]
It's two or three steps into the creation process.

**Comment by tinybike** [comment]
@thinkloop Please fix the text box, button, etc. displays!  Don't want to revert all the changes from pr 282, just the ones that broke the textbox/button styling.

**Comment by thinkloop** [comment]
@tinybike sent a pr that fixes text boxes in modal, verified in FF, Chrome

**Comment by thinkloop** [comment]
@Newportkiwi how do we add markets in the new design? Previously there was the plus symbol:

![image](https://cloud.githubusercontent.com/assets/118814/13047019/3be5fab0-d3aa-11e5-8e99-56f1ea3d1fa7.png)

**Comment by tinybike** [comment]
Also, I noticed this on the "My Markets" page -- the Trading Fee and other info text is offset to the right instead of below the title:
![screen-2-15-2016](https://cloud.githubusercontent.com/assets/2637020/13061812/2f3f60ea-d3ef-11e5-9801-978ee00c2f11.png)

**Comment by tinybike** [comment]
Fixed the issue mentioned in my last comment in 50384b8b9f75bb797c34714fc5128d3b3b0668c9.

**Comment by tinybike** [comment]
There are some additional minor changes to be made, but the overall Markets page now matches the uxpin damn near exactly.  Declaring victory on this one -- nice work, @thinkloop!
