### ISSUE TITLE
Attach flash scripts to browser's toplevel window object.

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#2826]
The idea is to get the flash scripts into the webapp as dev-only buttons. To do that, first the flash scripts need to be available in the browser at all. Attaching the flash scripts to `window` is good because then they are easily called from the js console as well. This works well with the other debugging tools that are also attached to the `window` object, like `state`.

The major difficulty with this issue is untangling the node dependencies that the flash scripts in augur-tools depend on. At least some are in augur-core but there may be others.

Note that the ganache-related code is entirely separated out from the rest of the flash scripts. This is because ganache is not available in the browser. Avoiding importing the ganache scripts may require non-top-level imports (like using `/build/*`).

**Comment by pgebheim** [comment]
Closing, can search and re-open if we decide to do this.
