### ISSUE TITLE
Get Flash Scripts into the Browser

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#2827]
There's a huge benefit to getting flash scripts in the browser because then they are easier to execute, especially for non-technical tests.

**Comment by pgebheim** [comment]
@robert-e-davidson3 -- Is this gonna work??

If not lets close these issues

**Comment by robert-e-davidson3** [comment]
It'll work.

**Comment by pgebheim** [comment]
Ah ok, cool -- then we should think about when in the order of operations you'll wanna tackle this.

After load testing stuffs?

**Comment by robert-e-davidson3** [comment]
Definitely after load testing. I also want to revisit the smoke test asap to get it running in our CI. Probably I can get to this ticket in mid August.

**Comment by robert-e-davidson3** [comment]
This is still a good idea but I'm closing this ticket because it's very low priority. Re-open or re-file when we have time.
