### ISSUE TITLE
Augur Node Warp Sync

### ISSUE THREAD

**Issue by AugurIntegration** [AugurProject/augur#284]
In order to reduce the startup time currently required to get an Augur Node synced we'd like to provide functionality to take and retrieve snapshots /deltas in a decentralized manner.

The basic premise would be to assume there is some external mapping of block => hash which AN can query. With this hash AN can then request a serialized DB and use that as a start point for the sync at the next block.

Current thought on the mechanism for this is to use a contract to do the block => hash lookup and to use webtorrent to seed and download the serialized DB. The contract portion can be fleshed out in more detail at a later point but will initially be manually updated.

There is apparently some support for processing deltas as well which would be extremely nice if we could also integrate that, but it isn't needed for this first iteration.
...

> The contract portion can be fleshed out in more detail at a later point but will initially be manually updated.

IMO we should just make it a thing reporters can trigger a vote on for a db snapshot as of a given block -> hash of db

> There is apparently some support for processing deltas as well which would be extremely nice if we could also integrate that, but it isn't needed for this first iteration.

I would actually support deltas in v1 of this, if we have until v2 to get it done we should go out the gate with a bang with something that's *slick*. If we can't do updates w/ deltas that's a lot less slick IMO 
 -joeykrug
...

Current thought is actually just to store a file with block -> hash data that we maintain possibly on GitHub. This is similar to how we already store chain specific data in the codebase with contract addresses or upload block numbers.

There's no real incentive for REP holders or anyone else to vote or stake on such a contract and it leaves the system open to greifing as well as adding an additional perpetual cost to the system (paying for txs to update and vote, etc).

One additional possibility is working something out with Alchemy as they seemed to think they could address this although it would need to be something decentralized as I still don't want to depend on them critically for features we develop.
 -nuevoalex

**Comment by adrake33** [comment]
Tom will work on the first cut of this.
