### ISSUE TITLE
market card timestamp display value and fast / slow dispute label

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2853]
use date time format that already exists, mocks are not consistent. 

Time left to dispute / finalization time / reporting time

 * reporting starts
https://www.figma.com/file/Do4qnkCNM8P7lwBmCdYZCS4X/Market-Cards?node-id=2086%3A12087

![image](https://user-images.githubusercontent.com/3970376/64369405-ea7a8500-cfe1-11e9-96e6-489b17b9c653.png)

 * time left to dispute
https://www.figma.com/file/Do4qnkCNM8P7lwBmCdYZCS4X/Market-Cards?node-id=2102%3A7972

![image](https://user-images.githubusercontent.com/3970376/64369969-03376a80-cfe3-11e9-88d3-ba689ffeb1d6.png)

note: time left to dispute is determined by Market's dispute window endTime

![image](https://user-images.githubusercontent.com/3970376/64374518-a5f2e780-cfe9-11e9-8822-fadb77fe1a66.png)

 - fast dispute label
on MarketsData there's `disputePacingOn` property. when this is false, fast resolution is active. 

 - slow dispute label
on MarketsData this is DisputeInfo object with `disputePacingOn` property. Slow resolution is indicated when the value is true.

 - finalization time
https://www.figma.com/file/Do4qnkCNM8P7lwBmCdYZCS4X/Market-Cards?node-id=2096%3A10

![image](https://user-images.githubusercontent.com/3970376/64374054-a2129580-cfe8-11e9-9b07-439fa31eb2be.png)

timestamp is finalizationTime on MarketData object.

**Comment by pgebheim** [comment]
Moving this into the Reporting epic so that this can be looked at again once all the data is in place to get to the different states.
