### ISSUE TITLE
modified getMarkets getter

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2864]
Market creation logs need to parse out categories from extraInfo
categories will come in as string array. order is primary, secondary and tertiary (optional).

Initial loading of market lists page. UI will call getter with default filters. 

Filters: 
market reporting states included
liquidity spread
market fee
invalid market (show | hide)
search term (optional)
category array (["primary", "secondary", "tertiary"] format)
sort by
limit: items per page
offset: page number

Sort options (should always be assumed to be descending order):

 * liquidity
 * open interest
 * volume
 * created timestamp
 * end date
 * last traded timestamp
 * last liquidity-depleted timestamp

return values:

UI needs:
 * market ids in filtered search
 * categories in filtered search (whole category tree)
 * market count in category (primary, secondary, tertiary
 ~~* market status counts (open, in reporting, resolved)~~ (no longer needed)
 * market count filtered out (only liq filter and trading fee apply)

 ```json
{
  "results": [
   ...MatchingMarketsInfo.....
  ],
  "meta": {
    "categories": [
      {
        "name": "sports",
        "count": 2,
        "children": [{
          "name": "soccer",
          "count": 2
        }]
      }
    ],
    "filteredOutCount": 10,
    "marketCount": 40,
  }
}
```

**Comment by justinbarry** [comment]
Proposed response shape: https://gist.github.com/justinbarry/a4bca96208cb8c9a61e2cca631083e06

**Comment by pgebheim** [comment]
@adrake33 -- Is this still in progress or did this get paused?

**Comment by adrake33** [comment]
@pgebheim Still working on this. I hope to have it finished today.
