### ISSUE TITLE
Automate Releases on Azure pipelines

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#2876]
Goal is to be able to trigger releases via the Azure Pipelines GUI

**Comment by petong** [comment]
* start publishing our packages as NPM packages: Artifacts, SDK, Core, Tools, UI
SDK and UI being most important

**Comment by pgebheim** [comment]
Leaving this just assigned to you @petong -- but Justin and I will get notifications. Adding this to the Wrike timeline.

**Comment by pgebheim** [comment]
Removing from wrike
