### ISSUE TITLE
Scan ledger/trezor for addresses with eth or rep balances.

### ISSUE THREAD

**Issue by AugurIntegration** [AugurProject/augur#288]
Instead of showing pages of addresses with zero balance, scan through derivation paths to find addresses with eth and/or rep.
User can still use advanced to set any cutom derivation path.
...

When looking to impl this, I wasn't sure about the UX. Here are some thoughts.

The main reason for the scan is to onboard new users easily, UI can scan their hardwallet, the process would look at the most popular 5+ derivation paths and the top 10 addresses and present addresses with balance. If there are no balances the default derivation path would be used and user can page through.
 -bthaile

**Comment by bthaile** [comment]
Settled on scanning top 5 addresses in 2 derivation paths, takes roughly 6 seconds. User can always go to `advanced` to page through derivation path of choice.

**Comment by adrake33** [comment]
Fixed by https://github.com/AugurProject/augur-ui/pull/2516
