### ISSUE TITLE
market list location query parameters

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2892]
url location query parameters will drive market list page. That way users can copy and send url to friends and share on social media. No redux stores will be needed for market list

values for these query parameters will be html encoded 

query parameters are:

`cat` : category array to indicate hierarchy, "primary", "secondary, "tertiary". 
`fee`: fee filter, only one is allowed "0-5", "0-10", ...
`liq`: liquidity spread filter, "10", "15", "20", ...
`state`: reporting state, "open", "reporting", "resolved"
`aff`: affiliate address
`term`: search term to be applied to search
`sortby`: sort, need values that are passed to getMarkets getter (TBD)
`limit`: number of markets per page (default is 10)
`offset`: page number, if 0 first page, if 1 and limit is 10 then 11 - 20 will be returned
`view`: 0, 1, 2. 0 is condensed, 2 is classic, 3 is expanded (not passed to getMarkets getter)
`etherNode` this is ignored by market list page, it's used to create SDK object.

**Comment by justinbarry** [comment]
cat will be the same array form that is stored in extra info.

**Comment by bthaile** [comment]
That is a good point. we could have category hierarchy in the url. 

I was thinking of only one category but what if they want to navigate to a specific sub cat that might be in many primary categories. I'll make change above.

**Comment by pgebheim** [comment]
@joeykrug -- Is this a priority item for sharing the market list?

**Comment by joeykrug** [comment]
Don't think so

**Comment by joeykrug** [comment]
seems to be done
