### ISSUE TITLE
Login button is missing on mobile

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#2893]

**Comment by JohnDanz** [comment]
@matt-bullock @cillianhunter0 @Chwy5 Where is this supposed to be on mobile? I don't see a mock with a login button anywhere, but i could just be looking in the wrong areas

**Comment by Chwy5** [comment]
@JohnDanz matt will send over the updated login state to you...he is updating it now

**Comment by matt-bullock** [comment]
Here:

https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=9813%3A309073
