### ISSUE TITLE
Reporting Page: Quick guide modals Needs actual text

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2907]
Reusing this Ticket, update modal when actual text is figured out by design.

Same modal is shown for these two buttons/text blocks
icon isn't included

 * `Designated Reporting Quick Guide`button
https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=630%3A7024
![image](https://user-images.githubusercontent.com/3970376/63794442-a4c60a00-c8c7-11e9-81bd-957f07ffaac0.png)

 * `Disputing Quick Guide` button
https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=218%3A10732

 * There is the text for Quick guide modal
https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=631%3A36120

 * modal view over UI
https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=631%3A36120

**Comment by bthaile** [comment]
We need text for the modals, currently mock has placeholder text.

**Comment by pgebheim** [comment]
@Chwy5 -- Can you add this to your radar?

**Comment by Chwy5** [comment]
Yup, is on the list for @BenDavidow to work on

**Comment by pgebheim** [comment]
@petervecchiarelli @Chwy5 @bthaile -- this got written but never included, yes?

**Comment by phoebemirman** [comment]
addressed here https://github.com/AugurProject/augur/issues/4848
