### ISSUE TITLE
Disputing Page: Overall layout 

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2919]
https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=492%3A33668

shows where components are going to be placed.

Logged out state and empty state
https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=2271%3A13160
![image](https://user-images.githubusercontent.com/3970376/63716668-28babc00-c80c-11e9-8eb6-09d1910e12ea.png)

![image](https://user-images.githubusercontent.com/3970376/63716682-340de780-c80c-11e9-8dee-30c1bad63758.png)

responsive, mobile:
https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=0%3A1

![image](https://user-images.githubusercontent.com/3970376/63716742-556ed380-c80c-11e9-99a8-76a9aebb493b.png)

**Comment by pgebheim** [comment]
finished.
