### ISSUE TITLE
Disputing Page: Current Dispute Window

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2922]
https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=492%3A33668

![image](https://user-images.githubusercontent.com/3970376/64190983-1e687580-ce3d-11e9-8448-30e5c6ea72a5.png)

shows progress bar to the end of the current 7 day dispute window.

There is a tix to get the current dispute windows start and end times

inputs: 
start timestamp
end timestamp
current timestamp

**Comment by pgebheim** [comment]
Done.
