### ISSUE TITLE
Reporting: Wire up log handlers

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2933]
Wire up log handlers, dispute information is on MarketInfo object. need to get latest information when reporting/disputing logs come in. Also need to update users assets. 

  
1. Disputing logs
 - [x] crowdsourcer completed
 - [x] crowdsourcer contribution
 - [x] crowdsourcer created
 - [x] crowdsourcer redeemed
2. Reporting logs
 - [x]  initial report submitted
 - [x] initial report redeemed
 - [x] initial report transferred
3. Dispute window logs
 - [x] dispute window created
4. participation tokens
 - [x] participation tokens redeemed
 
(token transferred) might get fired when user buys participation tokens (needs investigation)
markets have a dispute window associated to them. When market is in fast resolution then the dispute window will be 24 hour timeframe. When in slow resolution it's 7 day timeframe.

 - [x] remove old reporting-window-stats

**Comment by pgebheim** [comment]
WE talked today about merging all this information into the Derived DB for faster lookups @justinbarry
