### ISSUE TITLE
Trading: Onboarding (sign up / login / connect / landing page / account info)

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#2935]
Scope:
* Sign up flows
* Login flows
* Connect wallet flows 
* Onboarding modals 
   * Disclaimer modal 
   * DAI explainer modal
   * Test trade modal 
* Redesigned wallet dropdown/menu in app bar 
* App landing page 
* How to trade (dummy trade)

**Comment by pgebheim** [comment]
➤ Joey Krug commented:

Do with wallet at same time imo

**Comment by pgebheim** [comment]
➤ Cillian Hunter commented:

Agree

**Comment by pgebheim** [comment]
Closing design task in favor of #3191
