### ISSUE TITLE
Trading: Help center (theming the tool + any screenshots)

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#2939]
Knowledge center

* Onboarding help 
* Wallet help 
* Add funds help 
* Trading help
* MC help
* Reporting help 
* etc

FAQ/glossary section

**Comment by pgebheim** [comment]
➤ Joey Krug commented:

This should just send people to discord imo

**Comment by pgebheim** [comment]
➤ Cillian Hunter commented:

Agree, I think that's the sane thing to do for v2 launch. We can get a basic FAQ/HELP page in, and include "for more help visit discord" etc

Post v2, there's been some discussion about a help center as a tool for user education on prediction markets/trading/augur. Hosting articles like "how trading works", "how to create  markets", "how to add and maintain good market liquidity", "how reporting works" etc.

**Comment by pgebheim** [comment]
➤ Cillian Hunter commented:

I imagine using a 3rd party tool to host this, something like zendesk/intercom help center for example

**Comment by joeykrug** [comment]
status of this?

**Comment by cillianhunter0** [comment]
@petervecchiarelli has been running this, he has an initial theme applied in gitbook. We'll need to update the theme and get any screenshots sorted for launch. 

Let's close this, i'm keeping track of it as a GTM task.
