### ISSUE TITLE
Trade info missing

### ISSUE THREAD

**Issue by AugurIntegration** [AugurProject/augur#294]
When placing a trade below total it should also take total / shares to show an average price per share [i dont wanna have to use a calculator or do it in my head]

There should also be a calculator to calculate how many shares to buy at a given price if i wanna spend y dollars.  Screenshot example attached:

![quantity](https://user-images.githubusercontent.com/11491365/49775242-5f679b00-fcac-11e8-8bc8-3c5b2159ba0a.PNG)
...

@sprinkle I'm going to archive this task because it looks relevant to the old UI. Please unarchive and comment about priority if otherwise.
 -sharkcrayon
...

I think the current UI is still missing this. Users should be able to click on quantity and calculate how many shares they can buy at a given price per share. It's basic functionality that almost all trading UIs have [like Etrade, IB, and Robinhood]
 -joeykrug
...

@joeykrug — Does having market order functionality not solve this?

The order summary will display the total shares and we can derive the average price as well.

...

It doesn't solve it. 

Basically when you're placing an order there should be a calculator like the pic above where you should be able to input say $100 or 10 ETH and have it calculate how many shares you can buy at the current market price or at the limit price you enter given that amount of capital. It basically just keeps people in the UI and not having to whip out a separate calculator. Both Robinhood and ETrade have it
 -joeykrug
...

OK, I’ll unarchive this and slate it for review for inclusion in peccary.

...

Assigning over to @serena for review.  

...

Sounds good to me. I'll work on getting a design for this/thinking through it a bit more for Peccary.
 -sharkcrayon
...

:thumbsup::skin-tone-2: 

...

@chwy Is this something we need to do?
 -bthaile
...

Yes, I think it would be helpful, especially b/c if a user tries to use the order ticket now to figure it out, it can be confusing if they have an open position already(because of shares vs eth)...adding this helps solve the confusion.

It also keeps the user on the page, rather than leaving to calculate it themselves

 -Chwy5
...

A better way of doing this than E*TRADE is just have on the order entry ticket have a way to enter number or shares or amount to bet. Have them horizontal next to each other. If you enter one it’ll automatically populate the other based on the price. Lemme know if you don’t get what I mean 
 -joeykrug
...

@serena @mattbullock Is this something that can go into the redesign?
 -adrake33
...

Yes, I’ll link it to that ticket.
 -sharkcrayon
...

@joeykrug We're going to move away from showing shares in the interface and denominating everything in ETH instead. So, instead of seeing that you have "X shares at Y price", you'll just see that you have "X ETH" on an outcome.

I'm guessing that with this change we'll no longer need a calculator or to show the average price per share. Does that sound good to you?
 -sharkcrayon
...

[   shares    ] <>  [     cost      ]
[  price        ]

Is how I would do this. Enter cost or shares and it'll calculate the other for you based on your price. Veil is kinda doing this.
 -joeykrug
...

@joeykrug We have a couple questions on this.

Since we’re dealing with a decentralized system, we sometimes have to escrow more than the estimated order cost. This happens when the user is trying to fill an order on the books for less than the limit price they have set, but we have to escrow the total cost for creating the order just in case the order they want gets taken.

Should the cost the user enters be interpreted as the est. cost (if they are able to fill orders that are currently on the books) or the max cost (how much money is needed to add the order to the books if the cheaper orders get taken before their order is placed)? I’m leaning toward the max, but curious what you think.

2nd question:

We currently express things in both ETH and shares. So, if a user is holding 10 shares and is trying to sell 30, the cost will be a combination of X ETH and 10 shares.

How does the cost field factor into that? If we use it to represent only the ETH portion of the cost, the user would then enter in 0 for cost and be shown anything from 0 to 10 for quantity, which is kind of a weird user experience (we don’t know how many of those shares they’d actually like to sell). The alternative is to represent shares in ETH for the purpose of this equation, but that’s inconsistent with how we’re displaying everything else, and the value in the cost field will not match the numbers shown in est. or max cost.

3rd question:

What is the point of showing price per share? Isn’t that just the limit price the user has entered?
 -sharkcrayon
...

1. That's the same IRL too, not special with decentralized systems. Max. 
2. Cost shouldn't be shares, should be eth. The way we display it other places is a bit weird as well, e.g. should show them the price + cost in eth, and say that we're using their shares to fill the order.
3. Unclear on this question, to recap:

[ shares ] <> [ cost ]
[ price ]

Is how I would do this. Enter cost or shares and it'll calculate the other for you based on your price. Veil is kinda doing this

Only shows limit price / price per share once and it's in that price field above [ price ] 
 -joeykrug
...

@joeykrug 

2. "should show them the price + cost in eth, and say that we're using their shares to fill the order."

Do you have an example of this being done in a trading interface? I'm curious what language they use and how they format things.

3. "Only shows limit price / price per share once and it's in that price field above [ price ]"

We already show limit price, which is the price per share. What are you saying needs to be added in your original description for this task?
 -sharkcrayon
...

Robinhood is a good example when you sell shares
 -joeykrug
...

I’m just going to make a mock-up... haha
 -joeykrug
...

<img width="310" alt="screen shot 2018-11-08 at 2 50 32 pm" src="https://user-images.githubusercontent.com/11491365/49775255-6bebf380-fcac-11e8-9974-1b1b2072d9ba.png">

 -joeykrug
...

^ an idea, if it doesn't make sense, I'll explain on next weekly call [this issue is 2 years old so it can wait a few days haha!]
 -joeykrug

**Comment by mattbullock** [comment]
Hi - just an fyi, the wrong Matt Bullock (me) has been tagged in a few issues on this project. Looks like there's the difference of a hyphen in our usernames.

**Comment by sharkcrayon-augur** [comment]
@joeykrug 

Does this satisfy the need for allowing the user to enter/edit the total amount of ETH they'd like to spend? See "Total Order Value" field:

![image.png](https://images.zenhubusercontent.com/5c2d32db5bb3566961516bae/e35efa5b-c4a4-473c-b2a1-137a56e4176a)

**Comment by joeykrug** [comment]
yeah, saw this in the mocks, it's good.
