### ISSUE TITLE
Market list: middleware support full text search

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2943]
give user ability to search on all market fields, 
categories
market creator, designated reporter, market id, outcomes, description, resolution source, ....

This feeds UI search on market list page.

**Comment by pgebheim** [comment]
@adrake33 -- This was finished last week with the FTS change, yes?

Closing -- repopen if I'm missing something!

**Comment by adrake33** [comment]
Yep, this is implemented now.
