### ISSUE TITLE
Disputing: middleware, REP usage breakdown (User and Current window)

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2946]
UI needs current REP usage for user totals and current dispute window. 

1. User (totals) across dispute windows
 * current total REP in initial reports (DR and open reporting)
 * current total REP stake to disputes
 * current total REP used to buy participation tokens
 * User's reporting/disputing P/L given in a decimal or percentage format. 
Example: user disputes 1 market with 10 REP and wins 40% of 10, then their P/L 40%

Participation tokens
 * All dispute windows user has participation tokens that can be redeemed
 * current total User's Reporting fees balance outstanding

 - Note, values above would reduce if user redeems participation token or dispute winnings

The above will feed the design
![image](https://user-images.githubusercontent.com/3970376/61911972-95395700-aefe-11e9-88c1-0a35192e9e21.png)

![image](https://user-images.githubusercontent.com/3970376/61911946-82bf1d80-aefe-11e9-92bc-ca983a54a130.png)

2. Current slow dispute window (7 days)
 * start time
 * end time
 * total REP used for participation tokens
 * total DAI fees on current fee window
 * User's REP on participations tokens 

Universe.sol `getCurrentDisputeWindow(false)`

The above will feed the design
![image](https://user-images.githubusercontent.com/3970376/61911954-894d9500-aefe-11e9-820e-6694392f2383.png)

**Comment by robert-e-davidson3** [comment]
has been split into tickets
