### ISSUE TITLE
Typo on the last tutorial page.

### ISSUE THREAD

**Issue by cjphilpot** [AugurProject/augur#295]
On the last welcome tutorial page both the Yes and No bets are displayed as having the same odds. This is just a typo on the tutorial as the market is displaying correctly.

Do you think the odds of Yes should be higher than 23.55%?
If so, click Buy to place a bet on the Yes outcome.
Do you think the odds of No should be higher than 23.55%?
If so, click Buy to place a bet on the No outcome.
(You will need to sign in or run a local Ethereum node to place a bet!)

**Comment by tinybike** [comment]
Fixed in 13279a1f0e702b607e9f1d74b1228567004247e6.
