### ISSUE TITLE
Redesign Sidebar Menu

### ISSUE THREAD

**Issue by AugurIntegration** [AugurProject/augur#295]
Ideally, we move the menu to the top bar. This also involves re-doing the category and tag filters on the market list page. 

-  consider how to order categories and tags. Possibly alphabetical or by open interest or volume. 

Revisit this story when the filters are redone: ch14840
...

UX for this is done. This is currently in the visual design phase.

https://overflow.io/s/0KOB3I/
 -sharkcrayon

**Comment by joeykrug** [comment]
done in latest mocks
