### ISSUE TITLE
Remove all width/height settings for common elements

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#2955]
Common elements with set `min-width` for example are breaking previously made pages because those pages don't have the same dropdowns (Transactions History modal for example). We should avoid setting height/width on common elements and it should be done from the parent class that's going to hold the common elements. If we end up using the same height/width very often we can make a helper class to handle the common cases. (so for example, most dropdowns have a min-width of 210px, this could be a class we just add to the container) Example:

```
.someCompositionComponent {

> div {
// this div is a dropdown in this component
.RegularDropdown; 
// the .RegularDropdown helper class could just include something like:
// height: 40px;
// max-height: 40px;
// min-width: 210px;
// width: 100%;
}
}
```

Giving this an initial estimate of 13, because in order to do this we will need to walk through the UI and update container classes to correct the width/height from there instead of relying on the common component.

**Comment by pgebheim** [comment]
@JohnDanz Closing, re-open if you think this is still an effort we need to do and we'll add it somewhere
