### ISSUE TITLE
simplify creation and use of user balances

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2964]
keep eth, rep and dai properties on loginAccount. remove all usages of these.

create selector to format user's balances for ETH, REP and DAI. On `loginAccount` create new `balances` property that has 3 number formatted properties.

EthFormatted
RepFormatted
DaiFormatted

Update code base to use new selector.

**Comment by pgebheim** [comment]
@bthaile Still wanna do this? If it's not a priority, just an idea, close it.

**Comment by bthaile** [comment]
This was a refactor ticket. Not a priority
