### ISSUE TITLE
Fix "feedback" button being to large on safari

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur#297]
![2016-02-17_15-16-57 1](https://cloud.githubusercontent.com/assets/118814/13114258/c7781bf0-d560-11e5-9a46-2348daa3328a.png)

**Comment by tinybike** [comment]
Should the feedback button be changed to just be a text link in the footer?  It's a bit big/obtrusive for what it is.

**Comment by priecint** [comment]
Does it provide useful insights? If not let's move it to footer
