### ISSUE TITLE
[Dev] 0x Trading Spike

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#2971]

**Comment by pgebheim** [comment]
@nuevoalex -- Mind filling in some information here about what needs to be accomplished next?

Is it that we need to implement 1155 a-la: https://github.com/0xProject/ZEIPs/issues/24 ??

**Comment by nuevoalex** [comment]
Will give more detail after we get sorted out with their team. Basic idea currently is creating a custom ERC1155 that is essentially a message passing mechanism to be used to faciliate 0x signed order format and fulfilment but actual asset fulfilment will happen within our contracts.

The work on our side for this would consist of making this custom token and providing the additional contract fillable liquidity methods to be used by 0x so we can do our fill logic then have them exchange the ERC1155 token to update order state.
