### ISSUE TITLE
Guided Tour: Add ui element to restart tour at any time

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur#298]

**Comment by thinkloop** [comment]
@tinybike I moved this to In The Hole, but just saw that you had put it in progress - is this something we want for beta? Perhaps lowest priority if-we-have-time kinda thing?

**Comment by tinybike** [comment]
Yeah, I'd say lowest-priority-if-we-have-time is right!

**Comment by tinybike** [comment]
No longer relevant.
