### ISSUE TITLE
fix currency display mobile

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#2982]
<img width="232" alt="Screen Shot 2019-07-30 at 10 15 12 AM" src="https://user-images.githubusercontent.com/10524630/62137036-464f4100-b2b3-11e9-81b8-257c4a56f5f0.png">
<img width="245" alt="Screen Shot 2019-07-30 at 10 15 06 AM" src="https://user-images.githubusercontent.com/10524630/62137038-464f4100-b2b3-11e9-9e93-aaab197907da.png">

we need to find a better way to handle large numbers/ensure the currency is displayed in a readable/clear way on mobile. @Chwy5 @cillianhunter0 @matt-bullock

**Comment by Chwy5** [comment]
@matt-bullock

**Comment by matt-bullock** [comment]
Should be fine if we can accommodate up to 100000000.00
We can remove the commas
With that, there should be enough room:

![image](https://user-images.githubusercontent.com/39496225/62248928-93353380-b3e9-11e9-8427-84891d12119c.png)
