### ISSUE TITLE
Trading order form flickers

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2986]
Trading order form changes from logged in to logged out and back to logged in.

Look in either sign in with MM code or in init-augur. There is code that auto logs out the user.

**Comment by bthaile** [comment]
I see the order form flicker when navigating to the first market trading page after logging in. Doesn't happen every time.  The UI doesn't "logout".

Another reason the form might flicker is if  availableEth updates and has 0 for a value for split seconds.

I'll keep an eye out.

**Comment by bthaile** [comment]
noticed the flicker is still happening. easier to see on local chain. reopening

**Comment by justinbarry** [comment]
LGTM

**Comment by Chwy5** [comment]
Have Not seen it flicker in the last few days....closing
