### ISSUE TITLE
[Dev] Trading critical

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#2994]
bugs to clean up for trading. Some of these might be issues from Kovan being on fake time.

**Comment by joeykrug** [comment]
also pending orders / trades aren't showing up anywhere and they're supposed to in v2 (even before a transaction is confirmed)

**Comment by joeykrug** [comment]
cc @Chwy5

**Comment by Chwy5** [comment]
https://docs.google.com/spreadsheets/d/148PxribIRkdrpC0wWncM3xydl7L-mwim8Ag4UtuytVk/edit#gid=0

**Comment by bthaile** [comment]
I’ve seen that when the middleware fails to process new block event. There is an existing error for this issue. https://github.com/AugurProject/augur/issues/2702

**Comment by bthaile** [comment]
We'll have fixes for most of the issues. Main one was in the UI. the events didn't get re-wired up when the user logged in or switched accounts.

**Comment by bthaile** [comment]
this Epic is done, closing
