### ISSUE TITLE
Store hourly snapshots of MarketDB in new RankingMarketDB

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#2997]
The `getMarkets` getter needs to be able to sort markets by last liquidity-depleted. 

Discord conversation starts at https://discordapp.com/channels/378030344374583298/557226630293225472/605822297659408385

As per Alex on Discord: "Since this is naively a recalc required on every daily load for all markets regardless of changes having occurred I think some care should go into only recalcing what is needed"

**Comment by justinbarry** [comment]
https://gist.github.com/joeykrug/f61596d7b51cf66252c01b599bc3f0f6
