### ISSUE TITLE
Market cards hook up icons to data

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#3002]
![Screen Shot 2019-07-30 at 3.34.23 PM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/ce973a9f-e734-42e5-9985-1eceedbf7a8d)

Market creator and designated reporter information is on marketData object from market selector.

DAI icon data comes from user's positions. 

reporting/disputing info will be from a new reporting getter. user reporting information won't be on MarketInfo from getMarketsInfo getter. 
use flash scripts to report and dispute to get an idea of disputeInfo object shape.

**Comment by pgebheim** [comment]
This depends on Dispute and Stakes data being available for the market, which will come with Reporting.

**Comment by bthaile** [comment]
waiting for get account reporting history getter to be finished

**Comment by bthaile** [comment]
now we have data this can be closed
