### ISSUE TITLE
invalid address from AddressFormatReviver.ts

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3038]
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/eb6fbad3-b6ac-47a6-a243-13c0c2e279b7)

*"it is triggered after i hit connect wallet"* 
error when @Chwy5  was testing. 

Do you have more information?

**Comment by Chwy5** [comment]
Not really....I go to the site...it shows me markets listing pg, with no markets I hit connect a wallet and get this error, after i connect my wallet.....My acct shows up but no markets load.

**Comment by pgebheim** [comment]
Address is undefined as it gets passed in.

That's using metamask? Also is this still happening?

**Comment by pgebheim** [comment]
Stale
