### ISSUE TITLE
Global Design Tweaks

### ISSUE THREAD

**Issue by Newportkiwi** [AugurProject/augur#305]
A few tweaks and improvements to the overall design. Some of these have also been added to the style guide document for future reference. I may add to this list as we go along.

- [x] Add 500 weight to the Roboto font on the main stylesheet

- [x] Add antialiasing to all fonts on the website: -webkit-font-smoothing: antialiased;

- [x] Ensure the H1-H4 headings on website match the style guide - which I have updated with some new sizes (for example: H1 on the Markets page is 36px, not 32px as specced in the style guide)

- [x] Remove the 1px shadow effect from search boxes: box-shadow: inset 0 0px 0px rgba(0, 0, 0, .075);

- [x] Reformat the drop-down menus to match the style guide. Looking at the Bootstrap components, this should be possible.

- [x] Drop the font used in buttons down to 13px (currently 14px) and make sure there is 18px padding at the left/right end of all buttons (for example: the buttons on the Markets page have only 12px padding)

**Comment by priecint** [comment]
Will probably use http://jedwatson.github.io/react-select/
