### ISSUE TITLE
Trading: Add post only to order ticket

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#3055]
Remove "fill only" checkbox, add "post only" checkbox to order ticket.
Advanced menu

* time in force (tooltip) 
  * good til cancelled (default)
  * order expiration (date and time) 
    * fyi: 0x mesh, every order has an expiration date of 1 month 
      * if you connect wallet before expiration date, it is possible for us to refresh 
  * fill or kill

**Comment by matt-bullock** [comment]
Closing as this has been moved to 4476
