### ISSUE TITLE
Migrate Performance chart on Portfolio page to D3

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#307]
@adrake33 commented on [Thu Nov 29 2018](https://github.com/AugurProject/augur-ui/issues/2511)

(Copying from CH.)

Joey requested that we add timestamps to the chart when hovering. This should be done across all of the charts. John said this should be pretty straightforward to do in D3.

---

@JohnDanz commented on [Fri Nov 30 2018](https://github.com/AugurProject/augur-ui/issues/2511#issuecomment-443217090)

https://github.com/AugurProject/augur-ui/pull/2500

**Comment by JohnDanz** [comment]
this was merged into master augur-ui, going to close this issue.
