### ISSUE TITLE
Flashing "Not enough funds" warning on market creation confirmation screen

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#3072]
Seeing this:
![image.png](https://images.zenhubusercontent.com/5c0090502c4f4d3a81333d42/518ae30e-0053-46b2-8557-04c1876ef150)

Then this:
![image.png](https://images.zenhubusercontent.com/5c0090502c4f4d3a81333d42/45af59b8-3fde-40a9-8a8d-891762063cfd)

**Comment by bthaile** [comment]
Ive not seen this behavior. I think old ticket can be closed
