### ISSUE TITLE
Suggestion: resolved markets should show resolution timestamp

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#308]
@veox commented on [Tue Oct 02 2018](https://github.com/AugurProject/augur-ui/issues/2358)

I'd like to create a new market `Mnew` on whether an existing market `Mdisp` will resolve (be finalised) by date `D`.

Since this info is not displayed in the UI, it would be hard for future reporters on market `Mnew` to make a determination whether `Mdisp` indeed closed before `D` or after.

A work-around is possible, using the `augur.markets.getMarketsInfo(...)` API call for a specific market, then checking `reportingState` and `finalizationTime`.

However, this is best IMO integrated into the UI, rather than provided by a third-party tool.

-----

EDIT: Is this better suited for `AugurProject/augur-app`?.. I can "move" it there.

---

@bthaile commented on [Tue Oct 02 2018](https://github.com/AugurProject/augur-ui/issues/2358#issuecomment-426272538)

https://app.clubhouse.io/augur/story/17153

**Comment by matt-bullock** [comment]
@Chwy5 @cillianhunter0 do you have any thoughts on adding the resolution timestamp to markets.  it should be easy enough to add to the resolved market cards and trading pages.

**Comment by Chwy5** [comment]
Not sure how this would work?  Market goest through disputing, but still needs finalization.

Not needed imo, can be implemented later if needed

**Comment by matt-bullock** [comment]
Would this the timestamp at the end of the market's successfully undisputed window? Or would this be the moment the market is finalised? @adrake33

**Comment by adrake33** [comment]
@matt-bullock I suspect it's the former, but I'm not entirely sure. 

@veox From the perspective of Augur's smart contracts, a market is finalized when the `finalize` function is called on the Market.sol contract. (This happens when funds are redeemed on an initial report or dispute crowdsourcer, or if the function is called directly.)  However, this will typically occur *after* the market's dispute window has passed without the tentative outcome getting successfully disputed. When you said you want to create a market on when another market is finalized, did you mean the time at which the market's dispute window has elapsed without the tentative outcome being disputed?

**Comment by matt-bullock** [comment]
We can add this in but need to decide whether we show the date from the end of that markets final dispute window or the time the market was finalized. I'm really not sure. @joeykrug what do you reckon?

**Comment by veox** [comment]
Note:

* finalisation can be indexed by the emitted on-chain event - rather easily: there can only be one for a given market;
* "last dispute" is a bit more difficult, as it's not unique (must be tracked continuously) - but that's something that has to be done anyway;
* "last dispute opportunity" must be computed from the latter - but that's simple date-time arithmetic, delegatable to a lib.

-----

Is the question here which of the three to display to the user?..

If so, I'd say the easiest to implement and ~~understand~~ _describe succinctly_, and the rest in a pop-up.

> Market finalised: `<date-time>` (`<timezone>`) (`?`)

with `?` being a pop-up saying:

> At this moment, market outcome was declared final by ~~The Oracle~~ reporters.
>
> Last dispute contribution was on `<date-time>` (`<timezone>`). Last dispute opportunity was `<24-hours>` later, on `<date-time>` (`<timezone>`). After that, disputing was no longer possible.

`<24-hours>` being a stand-in for whatever is the dispute window duration.

**Comment by bthaile** [comment]
The timestamp of finalization is the same timestamp of the ethereum block the market’s finalized method is called. There is not arguing it, as far as I understand it. The finalizationTime is set on the market. We can get that info as a property of the market. Easy to get.

**Comment by cillianhunter0** [comment]
It does seem a good piece of data to include on all markets for transparency / clarity of the key dates of the market. Re: chwy's point on priority though, we should park it if it's a non trivial addition

**Comment by bthaile** [comment]
I think its important, it also rounds out the market cycle.

**Comment by matt-bullock** [comment]
We would simply change the Reporting Started label to Market Finalized and pull in that date. Makes sense to do this anyway

**Comment by Chwy5** [comment]
We can add it, but will only occur if a market gets finalized

**Comment by joeykrug** [comment]
Was it added? Close if so

**Comment by matt-bullock** [comment]
We've added in the Market Finalization date on the resolved cards. Closing
