### ISSUE TITLE
Make deposit/withdraw more clear to novice users.

### ISSUE THREAD

**Issue by Zoltu** [AugurProject/augur#308]
Currently, the UI for transferring money from Ethereum to Cash is a little confusing for novice users.  It uses terminology like "withdraw" without having a clear indication of which is the source and which is the destination.

My recommendation (without much thought) is to instead change the wording to something like "Cash to Ether" and "Ether to Cash".

**Comment by tinybike** [comment]
The whole withdraw/deposit scheme has been more-or-less replaced by the simple(r) faucet; closing.
