### ISSUE TITLE
Need error when there's a affiliate fee but no creator fee

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3080]
![image](https://user-images.githubusercontent.com/3970376/62559638-e91e3700-b840-11e9-8343-555dec59e744.png)

need design?

**Comment by Chwy5** [comment]
@cillianhunter0

**Comment by cillianhunter0** [comment]
Added to spreadsheet: 
https://docs.google.com/spreadsheets/d/1TqZ0ePiJKn3F8wYh8WRJ139vSIRpgZzfz6RboW44zxM/edit?usp=sharing

Errors tab, row 26

Error appears on the creator fee input
