### ISSUE TITLE
button colors are off.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3088]
button color is wrong, see design below
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/1e894287-5a30-4019-9356-af9a6b9f993d)

button design:
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7833%3A196490

**Comment by pgebheim** [comment]
@JohnDanz  Close this along with the other colors please.

**Comment by JohnDanz** [comment]
This looks like it was fixed already, closing
