### ISSUE TITLE
Add support for multiple Ether addresses attached to a profile.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#309]
Right now one ether address can be attached to a profile which is managed by the application.  It would be nice if users could add secondary addresses that could be referenced in the UI in places like transferring Cash to Ether.  For example, a user could add several addresses to their profile and then instead of asking the user for a address to transfer their cash to, you could give them a drop-down list of addresses that they have added to their profile (with a name provided by the user).  This sort of interface is very familiar to novice cryptocurrency users who are used to traditional financial systems where you add a bank account/credit card to an account and then when buying something you can reference which card to use.  The mechanic is reversed in the cryptocurrency world (an application can only receive money) but I think the paradigm can still be useful in reverse.

**Comment by tinybike** [comment]
Moved to CH
