### ISSUE TITLE
Add buttons to Errors for user to get REP / ETH / DAI

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3092]
add buttons to individual insufficient error messages
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=714%3A1975

design to provide modals or behavior for when user clicks on `Get REP`, `Get ETH`, `Get $ (DAI)` buttons

**Comment by pgebheim** [comment]
@bthaile -- Is this issue blocked on design / is there something needed to make it go?

@Chwy5 @joeykrug -- This wasn't marked as priority so I'll kick it out of the release if neither of you wanna press it.

**Comment by joeykrug** [comment]
get dai / add dai should pop up the add funds modal imo.

**Comment by Chwy5** [comment]
We either need the errors or need to have a direct link to get dai/Eth and Rep as all are required to make a market.....If you are in market creation and just created a market and added pre-liquididty, It would be really bad to have to leave and go get what is needed to create it, only to come back....Agree with Joey, should just pop up the add funds modal.

**Comment by Chwy5** [comment]
@bthaile what is the status of this?

**Comment by bthaile** [comment]
We have a button to add funds. I think this can be closed. @Chwy5 can you confirm

**Comment by pgebheim** [comment]
![image](https://user-images.githubusercontent.com/86010/75364986-665ad900-5871-11ea-9a7d-30c552a806fa.png)
confirmed!
