### ISSUE TITLE
Headers being Cut Off

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#3097]
Portfolio pg, in the Positions section, when a market is expanded, the headers are being cut in half...

see screenshot![8-7a.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/74ee9547-c7c1-4d4b-93af-add735a71b28)

**Comment by pgebheim** [comment]
Working since Portfolio responsive work. Can't make it cut off.
