### ISSUE TITLE
error when insufficient balance in trade

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3100]
![image](https://user-images.githubusercontent.com/3970376/62637506-2fd36600-b901-11e9-9b68-536518ab915b.png)

In trade.ts there is an error when `placeOnChainTrade` when this.checkIfTradeValid. need to catch error. and tell user insufficient balance

**Comment by phoebemirman** [comment]
this was a design decision to let the user still try to place a trade even if they don't have enough funds.
