### ISSUE TITLE
Order book doesn't update after doing trade

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#3103]
I did an opening trade, buying 10 at .55 (offer was already on the order book).  I got my fill, it showed up in my Positions and in the market trade history....but the order book quantity did not update.  (original order was 1000 offered at .55 and I bought 10)....I tried refreshing and the order book still shows the wrong quantity, but now my position and the trade history disappeared as well.  This is the console error I see after doing the trade (prior to the refresh)

**Comment by Chwy5** [comment]
![8-7b.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/c7db5bc1-a5d0-4224-8893-b59ea4ab09e6)

Was seeing this error in the console after executing the trade

**Comment by bthaile** [comment]
this might be associated with backend sending too many requests to eth node. @justinbarry thoughts?

**Comment by justinbarry** [comment]
I think that is the case. Will close this for now.
