### ISSUE TITLE
candlestick chart crashes UI

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3105]
nav to market with trading history
nav to market trading page candlestick chart
click to change between Shares and DAI in dropdown in top right of candlestick chart.
Wasn't able to repro very time.

![image](https://user-images.githubusercontent.com/3970376/62646174-500c2080-b913-11e9-85cb-b52c9c638f01.png)

**Comment by bthaile** [comment]
not able to repro.

**Comment by phoebemirman** [comment]
got this error 
<img width="689" alt="Screen Shot 2019-08-23 at 9 59 12 AM" src="https://user-images.githubusercontent.com/6775839/63609775-aff9fc80-c58c-11e9-9c73-398d4650c26c.png">

it was on a yes_no market i created, no trading history, only an open order

**Comment by bthaile** [comment]
Ok, we need to fix this
