### ISSUE TITLE
Frozen Funds Values not Always Updating Correctly

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3106]
Frozen Funds isn't correct.

Scenario:

1. create order and check that frozen funds updates correct when order is created
2. create order that take a trade and verify that frozen funds updates correctly

verified that situation 1. (create order) works fine.
2., when user closes a position frozen funds doesn't update from Users.ts `getProfitLossSummary` getter.

**Comment by pgebheim** [comment]
Will re-visit during next QA phase.

**Comment by pgebheim** [comment]
@Chwy5 -- Joey said you just had an example here,

mind putting it here?

**Comment by pgebheim** [comment]
need to know which cases they aren't updating correctly, and are all of these listed on that P/L spreadsheet?

**Comment by bthaile** [comment]
updated the description of ticket with more information

**Comment by Chwy5** [comment]
Testing with Tom....when user has a position and closes it out and reverses a position the FF doesnt update...

Example Buying 1 share at 0.25

Sell 2 shares at .15

My FF should increase by 0.7...i get this b/c Selling out my 1 long at .15 ( I would get back .15) and opening a new position of selling 1 at .15 (FF would be .85)= (.85+.15)= .7

**Comment by joeykrug** [comment]
fixed
