### ISSUE TITLE
Initial liquidity causes market preview to throw

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3108]
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/d4838b73-82f4-4b7c-a9e6-bc9ed3d24177)

create market with liquidity and go to market preview. UI throws

**Comment by phoebemirman** [comment]
can't reproduce @bthaile

**Comment by bthaile** [comment]
Still an issue,

In market creation, created scalar market with price range of -10 to -100 with a bid and an ask order then nav to market preview and it exploded.

![image](https://user-images.githubusercontent.com/3970376/62948827-b75e2080-bdaa-11e9-9071-18861d311d08.png)
