### ISSUE TITLE
remove Augur logo for mobile

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#3116]
We need to decide how to represent larger values on mobile that will allow us to conserve space while still conveying an accurate value for a users funds. Particularly for the header funds display on mobile as it currently doesn't work well with larger values.

To allow more space for mobile remove Augur logo on mobile.

also change decimals to only 2 for DAI. this call is in contractCalls.ts, just change 4 to 2 for DAI.

**Comment by andrewdamelio** [comment]
closing. This was addressed with the newest designs around the mobile header.
