### ISSUE TITLE
Update Get Started page & IPFS redirect page on augur.net

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#312]
@adrake33 commented on [Wed Nov 28 2018](https://github.com/AugurProject/landing-page/issues/8)

(Copying this over from Clubhouse.)

Matt will provide the spec (https://github.com/AugurProject/landing-page/issues/7) for the Redirect page, which will include:
- Disclaimer blurb
- Button or link for canceling / going back
- Button or link for continuing
- Info that there's an auto-redirection and a countdown

Disclaimer should say:
```
You are now leaving Augur.net and entering a website with no affiliation, support, or relationship to the Forecast Foundation. 

The Forecast Foundation does not endorse this website, its sponsor, or any policies, activities, products, or services offered on the site by any any advertiser or service provider on this site. The Forecast Foundation cannot attest to the accuracy of the information provided by this link. You will be subject to the destination site's privacy policy when you follow the link. Services offered when following the link have no affiliation to the Forecast Foundation, and the Forecast Foundation makes no claims in relation to the following link. 

Thanks again for visiting Augur.net.
```

Get Started page: https://github.com/AugurProject/landing-page/blob/gh-pages/get-started/index.html
Redirect page: https://github.com/AugurProject/landing-page/blob/gh-pages/ipfs-redirect.html

**Comment by phoebemirman** [comment]
blocked by https://github.com/AugurProject/augur/issues/313

**Comment by joeykrug** [comment]
Tom already implemented this a while back, since then it has been made clearer and now 90% of users of that page convert once they land on it. Prior to that it was only 55%
