### ISSUE TITLE
MC: dates not displaying correctly when user selects timezone

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3120]
timezone date time is getting changes instead of UTC time. 

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/2bf10b16-0042-4a06-a0f4-abff8343a43a)

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/d73d14de-4343-4c5e-9f89-a4b29a3cdda3)

the timezone'd time should be what the user selected and UTC time should change to reflect that.

**Comment by Chwy5** [comment]
better...shows both dates/time in market creation
