### ISSUE TITLE
Update Get Started page of augur.net

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#313]
@adrake33 commented on [Wed Nov 28 2018](https://github.com/AugurProject/landing-page/issues/7)

(Copying this over from Clubhouse.)

Ideally, we should display some text on the Get Started page describing differences between Augur App and the Web Version/IPFS gateway.

Joey suggested calling Augur App "Downloadable Version". If we do call it this on augur.net, some of the other text on the Get Started page should be reviewed and updated.

**Comment by joeykrug** [comment]
Tk is handling
