### ISSUE TITLE
Once Supported by Gnosis Safe Relay API provide additional safe creation params

### ISSUE THREAD

**Issue by nuevoalex** [AugurProject/augur#3130]
Currently the Gnosis Safe Relay API doesn't allow you to specify a payment parameter. Instead it fills this in and provides you with the address it generated using that payment. This won't work as well for us since we'd like to have a very limited set of payments to iterate when checking if a user has a generated safe.

Gnosis says they would be willing to adjust the API to take a payment and validate the payment is acceptable. Once this is possible we can adjust our use of the API and add tests to confirm we get the same address using the relay API as we do when calculating an address offline.

**Comment by pgebheim** [comment]
This won't need to happen because we're going to be hardcoding the gas cost instead of asking for more info.
