### ISSUE TITLE
Add local Gnosis Relay to local dev setup

### ISSUE THREAD

**Issue by nuevoalex** [AugurProject/augur#3132]
We'll need https://github.com/gnosis/safe-relay-service running as part of our dev spinup when developing the UI locally.

**Comment by justinbarry** [comment]
@petong once https://github.com/AugurProject/augur/pull/4259 is merged we need to populate the contract addresses when the relayer is run locally. Right now they are hard coded.

The initial cut of getting this working locally is done but the addresses are hard coded.

**Comment by pgebheim** [comment]
Exists in docker:all
