### ISSUE TITLE
Map of markets

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#314]
https://www.finviz.com/map.ashx?t=sec

This is a ways off, but it'd be cool to have something like the above where the rectangles were augur markets sized by volume and sorted by the first category tag

**Comment by tinybike** [comment]
This would be very cool!  Agree that this is a ways down the road though.  When the time rolls around this feels like a @thinkloop kind of problem... :)

**Comment by joeykrug** [comment]
unnecessary for now
