### ISSUE TITLE
Pizzazify

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur#315]
There have been requests to add some pizzaz to the augur beta. Suggestions of using more/brighter colors, a hero image, branding/logo elements have been made. 

(see slack conference-room conversation at Feb 22, 5:56pm EST if possible)

![image](https://cloud.githubusercontent.com/assets/118814/13236205/fd2e497a-d990-11e5-8b19-3deaf76da909.png)

![image](https://cloud.githubusercontent.com/assets/118814/13236216/107dd054-d991-11e5-913b-f784087f424a.png)

![image](https://cloud.githubusercontent.com/assets/118814/13236228/22a5950a-d991-11e5-81d9-b6a83c7bf18b.png)

![image](https://cloud.githubusercontent.com/assets/118814/13236242/2dc8f530-d991-11e5-9a0f-67880424e03d.png)

![image](https://cloud.githubusercontent.com/assets/118814/13236249/405d2d56-d991-11e5-9de1-46c40a5100ac.png)

![image](https://cloud.githubusercontent.com/assets/118814/13236255/48223ee6-d991-11e5-9f29-03e0774a260c.png)

**Comment by Newportkiwi** [comment]
Okay, never seen that original colour palette before. Thanks.

I'm fine with jazzing things up a little. I've deliberately kept things a little low-key to focus more on the UX and making sure users can get their business done as quickly and simply as possible (i.e. scannable lists, easy to read data, options easy to find and select).

Branding will definitely go in the header - that should be done ASAP, I'll add a ticket to the board today for that. 

A hero image is great for the homepage but they shouldn't be used elsewhere.

**Comment by Newportkiwi** [comment]
Pizzazify complete - style guides updated.
