### ISSUE TITLE
Tutorial Issue w/ Text Clarity/Sharpness

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#316]
Text looks crisp - good
![good.PNG](https://files.zenhub.io/56cbd10720a8f1497d72cf5a)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

Text looks blurry
![bad](https://cloud.githubusercontent.com/assets/5925937/13240750/be97198e-d9aa-11e5-830b-7bc941fd242d.PNG)

**Comment by joeykrug** [comment]
![good](https://cloud.githubusercontent.com/assets/5925937/13258227/f33946cc-da17-11e5-87b6-a104b79a4060.PNG)

good image didn't upload the first time

**Comment by thinkloop** [comment]
@joeykrug do you think it's the font color? It seems ok to me, but its not black-on-white - is it more blurry than the rest of the site? What browser/os btw

**Comment by joeykrug** [comment]
Yes it is more blurry, the only part of the site that is blurry for me.  Firefox / W10

The "Welcome to Augur" image looks fine, but the "this event has two possible... etc" looks blurry.  I don't think it's the color since these two images have the same font color, but only one is blurry.  Let me try another browser

**Comment by joeykrug** [comment]
Ok, it's only firefox.  Can someone try firefox on a different OS?  If it's not blurry on other OSs too I'd leave this as fairly low priority but it is an issue on FF/W10

**Comment by thinkloop** [comment]
@joeykrug is this still happening? Do you have windows cleartype type turned on by chance?

**Comment by joeykrug** [comment]
Oh, it was windows cleartype
