### ISSUE TITLE
Spike: Use ganache w/ flash forking to generate seeds from existing non-ganache chains

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#3169]
It *should* be as easy as forking from the block Augur was uploaded to (or zero if you have a lot of spare time) then building a seed off of the fork.

https://github.com/trufflesuite/ganache-cli/blob/686e5db39789e0357ddf8140bae23204d5f9e6d5/README.md

https://ethereum.stackexchange.com/questions/45709/want-to-run-a-local-fork-of-ropsten

**Comment by bthaile** [comment]
@Justbeingjustin  is this ticket a priority? I pushed it to next sprint.

**Comment by justinbarry** [comment]
@robert-e-davidson3 This is a spike, yeah?

**Comment by justinbarry** [comment]
This is a nice to have to test more “real world” scenarios.
