### ISSUE TITLE
Layout here needs work

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#317]
Looks messy imo

**Comment by joeykrug** [comment]
![capture (2).PNG](https://files.zenhub.io/56cbd1ac20a8f1497d72cf69)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by joeykrug** [comment]
![hmm](https://cloud.githubusercontent.com/assets/5925937/13240802/2613f3ca-d9ab-11e5-9dee-9ee635e4a888.PNG)

**Comment by tinybike** [comment]
On the upside, metadata details are showing up!

**Comment by tinybike** [comment]
Details hidden:
![marketpage-2-22-2016-1](https://cloud.githubusercontent.com/assets/2637020/13243462/d5b6087e-d9b3-11e5-9c80-cea18cbe35ae.png)
Details showing:
![marketpage-2-22-2016-2](https://cloud.githubusercontent.com/assets/2637020/13243470/e7379338-d9b3-11e5-8b42-ce16730bd644.png)
Thoughts?

**Comment by Newportkiwi** [comment]
We should limit the amount someone can enter here. Most of the SpaceX stuff in that description is copied/pasted from a webpage - they should just link to that page.

**Comment by joeykrug** [comment]
Ok looking much better.  
![pic](https://cloud.githubusercontent.com/assets/5925937/13257990/c880508e-da16-11e5-97ad-2ae809f81df8.PNG)
^ Looks tacky though

Posting a couple screenshots from etrade which look nicer, unable to pinpoint exactly why but could serve as inspiration for market metadata

![etrade1](https://cloud.githubusercontent.com/assets/5925937/13258064/31ae4282-da17-11e5-92ac-a8327b09d321.PNG)

![etrade2](https://cloud.githubusercontent.com/assets/5925937/13258072/35b4241e-da17-11e5-8c2a-512e47bc8687.PNG)

**Comment by joeykrug** [comment]
Particularly their data section with open, prev. close, etc. etc. looks better

**Comment by Newportkiwi** [comment]
Yep, this whole page needs to be redesigned. It's on the list.

**Comment by tinybike** [comment]
Combining this with #319.
