### ISSUE TITLE
Account creation error

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#318]
Do not close this window or browse to another page until your account registration is complete!
Creating new account joejoe...
Received 100 Ether.
Resetting blockchain listeners...
Exchanging 50 Ether for CASH...
Blockchain listeners reset.
Details

{
  "account": {
    "error": -32603,
    "message": "could not unlock signer account"
  }
}

**Comment by tinybike** [comment]
Can you re-try this, now that the funding sequence is (I think...) fixed up?

**Comment by joeykrug** [comment]
works now
