### ISSUE TITLE
Trade page needs some design lovin' before beta launch

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur#319]
![image](https://cloud.githubusercontent.com/assets/118814/13259950/8b5961b2-da27-11e5-99cc-ad8d391246b4.png)

![image](https://cloud.githubusercontent.com/assets/118814/13259969/9e2f0ac6-da27-11e5-81ac-62397873d396.png)

**Comment by thinkloop** [comment]
I'm going to move the possible positions/outcomes horizontally to the top until further guidance

**Comment by Newportkiwi** [comment]
I'll be working on this when I can this week

**Comment by tinybike** [comment]
Rebuilt in 59f966ae8b6d24f221fec1ec166e75a53216429e (might still need some design lovin', but this issue is ovah).
