### ISSUE TITLE
Scalar Market not displaying Denominated in on trading pg

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#3192]
On the trading pg, both in the header area and on the order ticket the denomination is not displaying.....see screenshots

![8-12a.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/84672e9b-6bca-4c3a-80b9-400ac527b8bb)

![8-12b.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/8b652220-e520-4a8a-b6a2-c598ae1637ba)

**Comment by Chwy5** [comment]
Not displaying in the OUTCOME chart either, shows N/a there as well

**Comment by bthaile** [comment]
What market are you seeing this on? it could be a market where scalar denomination wasn't provided. We should still display `N/A` for scalar denomination or different text. 


![image](https://user-images.githubusercontent.com/3970376/62879499-de581c00-bcf0-11e9-87cf-216f4e060422.png)

![image](https://user-images.githubusercontent.com/3970376/62879513-e57f2a00-bcf0-11e9-8d45-2e9dd8d2db93.png)

**Comment by Chwy5** [comment]
not seeing this anymore - closing
