### ISSUE TITLE
Scalar Market on trading pg displaying Scientific Notation

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#3193]
Under the Outcome section the Max of the range is being displayed as scientific notation

the range I used to create this market is 0-50

![8-12c.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/249e5e6f-1ee4-4474-9a4f-29902b3b92a7)

**Comment by bthaile** [comment]
issues found while creating scalar market.

"maxPrice":"0.00000000000000005",
"cumulativeScale":"0.00000000000000005",
"settlementFee":"0.1000000000000001",
"reportingFeeRate":"0.0000000000000001",
tickSize":"0.00000000000000000001"

**Comment by Chwy5** [comment]
fixed - closing
