### ISSUE TITLE
Mist compatibility

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#320]
Check if Augur works in [Mist](https://github.com/ethereum/mist) out-of-the-box, and if it doesn't, figured out how to make it work.

**Comment by joeykrug** [comment]
I looked into this --- Mist doesn't support other applications/dapps or javascript anymore.  Looks like it hasn't been added in yet.  Only way to do things atm is using electron per my other issue using https://github.com/ethereum/ethereumjs-lib which would be a pain and be a multi month project i think [if you actually ran a node in it --- not running a node it's easy].  Gonna close the other issue too b/c can just wait until mist is out w/ a working setup for dapp javascript, still too early atm tho
