### ISSUE TITLE
Current Value in the Positions section of the Portfolio pg not working

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#3210]
displaying only 0.000s

Both for long and short positions

**Comment by Chwy5** [comment]
@bthaile still showing me 0.000s

**Comment by Chwy5** [comment]
after the last fix no longer showing me zeros, but showing me incorrect value.

I sold 11 at .27 and last trade price was .28, my current value s/b 7.92= (1-.28)*11
it currently shows me with -7.02 value which is incorrect

**Comment by phoebemirman** [comment]
seems like getUserTradingPositions is sending back the wrong currentValue

**Comment by bthaile** [comment]
This might have been addressed with newest change to currentValue

**Comment by Chwy5** [comment]
this is working correctly now...closing
