### ISSUE TITLE
market creation needs to handle not valid numbers getting through in validations

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#3225]
![image.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/ab677b39-e334-4c9d-b7d6-a6c02c17f18d)

**Comment by phoebemirman** [comment]
@cillianhunter0 what should we do in this case? should "-0" throw an error or be turned to zero without telling the user? also consider "0.000" or "1.000"

**Comment by bthaile** [comment]
FYI, the market gets created with values of 0. it's a UI display bug.

**Comment by joeykrug** [comment]
is this fixed?

**Comment by phoebemirman** [comment]
no. but seems like a minor issue.

**Comment by cillianhunter0** [comment]
@phoebemirman missed your ping on this. 

Can we just limit the input to numbers and "." ?

**Comment by phoebemirman** [comment]
negative numbers should be allowed

**Comment by cillianhunter0** [comment]
We don't allow negative numbers here though? 
![image](https://user-images.githubusercontent.com/48024319/73450611-a5266d80-435d-11ea-9618-b59b3bcfa5bb.png)
If someone enters "-0" and we show it as "0" on the review step seems fine to me if a quick fix.

**Comment by Chwy5** [comment]
There is no reason to allow negative numbers - keep the error we have if someone does 

xyz fee must be more than 0.....

Close and move on

**Comment by phoebemirman** [comment]
Sorry this happens for all market creation inputs including min/max range.
Fees was just an example.

**Comment by Chwy5** [comment]
ok gotchya....all numbers should be positive with the exception of scalar markets Min/Max....those could be negative ( as rare as that would be)

**Comment by phoebemirman** [comment]
ok. thats how the form works already. closing
