### ISSUE TITLE
Cutoff/spacing issues w/ ether send

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#323]
text box is too close to button
![tooclose](https://cloud.githubusercontent.com/assets/5925937/13296999/d231cca4-daf5-11e5-8168-3089953f2fa0.PNG)
text is cutoff & button again
![cutoff2](https://cloud.githubusercontent.com/assets/5925937/13297001/d274b690-daf5-11e5-8705-7207b7a85a9b.PNG)
text is cutoff & button again
![cutoff](https://cloud.githubusercontent.com/assets/5925937/13297000/d27361fa-daf5-11e5-89b2-3b9bb517cb4b.PNG)

**Comment by tinybike** [comment]
Widened the send modals in 7b9efaba6c17377f4cd080346aef9de9d12218b1.
