### ISSUE TITLE
User doesn't know diff. between cap and price

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#324]
![needs tutorial or exp](https://cloud.githubusercontent.com/assets/5925937/13297093/2fc747ea-daf6-11e5-8281-7f35a2a46aa9.PNG)

**Comment by joeykrug** [comment]
needs tutorial or explanation

**Comment by tinybike** [comment]
Maybe "maximum price" and "minimum price" would be better?

**Comment by joeykrug** [comment]
Yeah

**Comment by tinybike** [comment]
Fixed in 4576d9ac51cf800b40966d16344b858a5a46c2e7.
