### ISSUE TITLE
Open orders doesn't work

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#326]
![doesntwork](https://cloud.githubusercontent.com/assets/5925937/13297209/c5b723f6-daf6-11e5-8567-c1c2312df6a5.PNG)

Trump cost to buy 10 shares is .39 .39/10 is 3.9 cents / share, this order should execute, but it isn't

**Comment by joeykrug** [comment]
looking at console it doesn't appear to be doing anything whatsoever btw

**Comment by tinybike** [comment]
It's expecting cap > price (if you enter a cap).  It should show an error though rather than just entering an unfillable order onto the book.

**Comment by tinybike** [comment]
Fixed in c0bfe147065c619bba6e36cc63148ca1f0d140ca / AugurProject/augur.js@e1f6b17cad41a4939075b3dd5ce55ba7440ecdd3.  (If it still fails on Win10, re-open and I'll troubleshoot further.)
