### ISSUE TITLE
Market creation issue

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#328]
Made a market.

Made a trade in it.

Refreshed / logged out while trade in progress

Logged back in

Won't let me create new markets anymore.. nothing happens

**Comment by joeykrug** [comment]
then my rep/cash/eth just all zeroed out

**Comment by tinybike** [comment]
I'm unable to reproduce this.  (Which is good, since this sounds bizarre and horrible.)  This maybe was a byproduct of the progress modal not being properly reset?  That doesn't explain your assets getting zeroed out though.  Can you check to see if you can reproduce this?

**Comment by joeykrug** [comment]
still happens

**Comment by joeykrug** [comment]
if i do a second refresh and login and make a market it works

**Comment by tinybike** [comment]
When you say "nothing happens", what do you mean?  When you click on " new
market " nothing at all happens? The modal appears but won't let you
progress?  You can get thru the modal but it won't submit?  You click
submit but nothing happens?  You submit but the progress modal fails?
Please be specific!

**Comment by joeykrug** [comment]
Nothing occurs of consequence upon filling out a market creation modal.  Nothing is happening in the console, i.e. it's not doing anything at all.  Fill out everything in the modal, click submit market, then it proclaims to be putting something on chain but in the console it's actually doing nothing.  Not a single transaction nor a single log nor a single call

**Comment by tinybike** [comment]
What do you mean "proclaims to be putting something on chain"?  Do you mean the progress modal appears and seems to be progressing normally?  If so, can you take screenshots of this?  What you're describing should not be possible: the progress modal for add market cannot advance without there also being stuff logged to the console (https://github.com/AugurProject/augur/blob/develop/app/components/AddMarketModal.jsx#L259-L336).

**Comment by joeykrug** [comment]
Yeah that's exactly what happened haha. Gimme a min

**Comment by joeykrug** [comment]
Sent a new video recording of this

**Comment by tinybike** [comment]
@thinkloop Are you able to reproduce this?

**Comment by thinkloop** [comment]
I tried serveral different subtle variations and am not able to repro

**Comment by thinkloop** [comment]
Obsolete
