### ISSUE TITLE
Display orphaned orders message on trading page

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#332]
From chwy: "Went to sell 5 of outcome "MY" (which consisted of 2 orders (see messaging in Bell)....the first order traded and the second order ended up in open orders in my position (at the bottom of the page)....resulted in a crossed order book (see 2nd screenshot)"

"Yeah I have an orphaned orders message....we may need to move that to the trading pg when it happens....I only  see it in the portfolio pg under my markets....most users wont know to check there"

![clipboard 2018-20-11 at 12 12 16 pm](https://user-images.githubusercontent.com/11491365/49392880-96eeaa00-f6e4-11e8-982e-ce4e5136249a.png)
![clipboard 2018-20-11 at 12 12 27 pm](https://user-images.githubusercontent.com/11491365/49392886-9bb35e00-f6e4-11e8-8a09-abce46161641.png)

**Comment by bthaile** [comment]
trades on this market by user
[
  {
    "amount": "2",
    "logIndex": 27,
    "maker": false,
    "marketCreatorFees": "0",
    "marketId": "0x25032153f97825ffd332d2e6f6ee4566b7696f1e",
    "orderId": "0x1513e54d71b77dc015f5d30b884e3a1e116b36d1466219d89724e552bf93b100",
    "outcome": 2,
    "price": "0.15",
    "reporterFees": "0",
    "selfFilled": false,
    "settlementFees": "0",
    "shareToken": "0x3700f2befd2156c496adb5cfb64385759e9ed838",
    "timestamp": 1542740657,
    "tradeGroupId": "0x87c418034383309ad90c01468e666897ddb06d7e3b9bbf3cec5f78de6e9181a0",
    "transactionHash": "0x35570f5d79430027f94cf086190bc05d5240cbb5cffc17c7bf30bea394f8a62f",
    "type": "sell"
  },
  {
    "amount": "2",
    "logIndex": 40,
    "maker": false,
    "marketCreatorFees": "0",
    "marketId": "0x25032153f97825ffd332d2e6f6ee4566b7696f1e",
    "orderId": "0xeb6c2b461e5a8eb55f80fd53a42a5437f4855235fec1e576e8919480e4a14704",
    "outcome": 1,
    "price": "0.1",
    "reporterFees": "0",
    "selfFilled": false,
    "settlementFees": "0",
    "shareToken": "0x008ccebe607026313a9ab26491a1651cd4427b83",
    "timestamp": 1542740582,
    "tradeGroupId": "0x69084ce9a724a528242ccefe7321109284a43cbd6933b4b9cf1d5928bbc2e1ac",
    "transactionHash": "0x6fe02f14e8f09b50c9339fd6a270a0e7a8b496bd43cef0cd60dfc407b8ca3f7b",
    "type": "sell"
  },
  {
    "amount": "1",
    "logIndex": 47,
    "maker": false,
    "marketCreatorFees": "0",
    "marketId": "0x25032153f97825ffd332d2e6f6ee4566b7696f1e",
    "orderId": "0xbd859db81343e6c00902ea671991c3a729a7013fa4ff5768e362a652d505189e",
    "outcome": 1,
    "price": "0.15",
    "reporterFees": "0",
    "selfFilled": false,
    "settlementFees": "0",
    "shareToken": "0x008ccebe607026313a9ab26491a1651cd4427b83",
    "timestamp": 1542740537,
    "tradeGroupId": "0x69084ce9a724a528242ccefe7321109284a43cbd6933b4b9cf1d5928bbc2e1ac",
    "transactionHash": "0xbf11466a6f80d17e667d4dd5e42b9b023333531df5e88d12c8e526e5bac8ed20",
    "type": "sell"
  },
  {
    "amount": "1.5",
    "logIndex": 49,
    "maker": false,
    "marketCreatorFees": "0",
    "marketId": "0x25032153f97825ffd332d2e6f6ee4566b7696f1e",
    "orderId": "0x87c808113c81add43de63e7bda13cc438621ef1f69e9c88f6c06ef9f59184b50",
    "outcome": 1,
    "price": "0.2",
    "reporterFees": "0",
    "selfFilled": false,
    "settlementFees": "0",
    "shareToken": "0x008ccebe607026313a9ab26491a1651cd4427b83",
    "timestamp": 1542740477,
    "tradeGroupId": "0x5cfa6e1ccc117800f646cc70eaca41c848fce18c03a2457d32d8b33f6e5ec41d",
    "transactionHash": "0x8e97bc635aab65c4a019783d7c680bfaaac923fcfb4b0aa905335e8347341be4",
    "type": "sell"
  },
  {
    "amount": "1",
    "logIndex": 18,
    "maker": false,
    "marketCreatorFees": "0",
    "marketId": "0x25032153f97825ffd332d2e6f6ee4566b7696f1e",
    "orderId": "0xa78f1a8d1cb8f198ae24b5e6990b895c703a29844e9583ba9f9880d2bf9a5935",
    "outcome": 1,
    "price": "0.25",
    "reporterFees": "0",
    "selfFilled": false,
    "settlementFees": "0",
    "shareToken": "0x008ccebe607026313a9ab26491a1651cd4427b83",
    "timestamp": 1542740447,
    "tradeGroupId": "0x5cfa6e1ccc117800f646cc70eaca41c848fce18c03a2457d32d8b33f6e5ec41d",
    "transactionHash": "0xf1f83fbd18218956d93ee15582f1d4621494bc5c40a273bd09285fb0fe79af96",
    "type": "sell"
  },
  {
    "amount": "0.12",
    "logIndex": 36,
    "maker": false,
    "marketCreatorFees": "0",
    "marketId": "0x25032153f97825ffd332d2e6f6ee4566b7696f1e",
    "orderId": "0x890d6579247e6258242fb76568a9aeb14e6c7bd8d5f655ae15f333b973580576",
    "outcome": 0,
    "price": "0.1",
    "reporterFees": "0",
    "selfFilled": false,
    "settlementFees": "0",
    "shareToken": "0xde6585a4164c569c154663b1e0ee15b0181c1c1c",
    "timestamp": 1542740312,
    "tradeGroupId": "0x728d2b25d1e13e2cae6c87b7219ddebe439faed06ad4a472aef75ef6c1564898",
    "transactionHash": "0x038357fbdd428866f22bd297277f7a0507dab444a2d58656741adf5f7cf9dc2c",
    "type": "sell"
  },
  {
    "amount": "0.11",
    "logIndex": 42,
    "maker": false,
    "marketCreatorFees": "0",
    "marketId": "0x25032153f97825ffd332d2e6f6ee4566b7696f1e",
    "orderId": "0xfa264c4c4f906d83875b8135a6d9c52ff8875348f295116f0830b7453890b414",
    "outcome": 0,
    "price": "0.125",
    "reporterFees": "0",
    "selfFilled": false,
    "settlementFees": "0",
    "shareToken": "0xde6585a4164c569c154663b1e0ee15b0181c1c1c",
    "timestamp": 1542740282,
    "tradeGroupId": "0x728d2b25d1e13e2cae6c87b7219ddebe439faed06ad4a472aef75ef6c1564898",
    "transactionHash": "0x1bf90f1fd91d5402f27e4efccf6c67cd7fbe4089f61aabaed4e2b436bcea5fff",
    "type": "sell"
  },
  {
    "amount": "0.1",
    "logIndex": 70,
    "maker": false,
    "marketCreatorFees": "0",
    "marketId": "0x25032153f97825ffd332d2e6f6ee4566b7696f1e",
    "orderId": "0x45dc097f2db30e92ab5659f070f190cc3972fd2475246881a1352c22fb20a825",
    "outcome": 0,
    "price": "0.15",
    "reporterFees": "0",
    "selfFilled": false,
    "settlementFees": "0",
    "shareToken": "0xde6585a4164c569c154663b1e0ee15b0181c1c1c",
    "timestamp": 1542740237,
    "tradeGroupId": "0x728d2b25d1e13e2cae6c87b7219ddebe439faed06ad4a472aef75ef6c1564898",
    "transactionHash": "0x824715407daa8a7e07f0592aa03a5f953bf2cad33debb8cb85a0b310ce3cb9b6",
    "type": "sell"
  },
  {
    "amount": "1",
    "logIndex": 42,
    "maker": false,
    "marketCreatorFees": "0",
    "marketId": "0x25032153f97825ffd332d2e6f6ee4566b7696f1e",
    "orderId": "0xbdfc987aa228cb51049f19539134138ca8f5704a67fd4dfe9251eb45c6e9f60e",
    "outcome": 0,
    "price": "0.2",
    "reporterFees": "0",
    "selfFilled": false,
    "settlementFees": "0",
    "shareToken": "0xde6585a4164c569c154663b1e0ee15b0181c1c1c",
    "timestamp": 1542739817,
    "tradeGroupId": "0x9e2fcc2433dc5725b88ae8a7a7d0aa6c2390a82c7b475ba5a85b777abbd7c8a2",
    "transactionHash": "0x51a8f27b897aad43631d44527664cc62d4741cb0cf49eb80bad3ac33ed7af7c1",
    "type": "sell"
  }
]

**Comment by bthaile** [comment]
Also looks like the market creator sold 3.3 Complete sets before the Last 5 share order was made. Not able to recreate on local chain. Able to reproduce most of the same numbers.


![screen shot 2018-12-03 at 5 37 16 pm](https://user-images.githubusercontent.com/3970376/49408798-7db91e00-f723-11e8-9c2e-32d3f34a3e78.png)
![screen shot 2018-12-03 at 5 41 19 pm](https://user-images.githubusercontent.com/3970376/49408803-827dd200-f723-11e8-8605-ab1d5df6be68.png)

**Comment by bthaile** [comment]
I really don't trust position data, P/L is currently being worked on. Not able to repro the cross order book issue.

**Comment by bthaile** [comment]
Not able to recreate on Rinkeby through augur-app.

![screen shot 2018-12-03 at 6 28 08 pm](https://user-images.githubusercontent.com/3970376/49410151-32a20980-f729-11e8-8402-0001b57bdd76.png)
