### ISSUE TITLE
Register modal goes in unexpected state when handle is already taken

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur#333]
When registering a handle that is already taken, the modal with the progress bar displays, doesn't finish but also shows the close button. If you click close and try to register again, u can see the error msg on the form about the handle being taken. When you do try and register again with a new handle, you get the same odd state:

![image](https://cloud.githubusercontent.com/assets/118814/13312085/c8c92664-db61-11e5-997e-2071c04ade6d.png)

**Comment by Newportkiwi** [comment]
Lets turn the registration process into a page rather than a modal - that way the user is less inclined to close the window by accident (or on purpose). And pages work better on mobile than modals.

**Comment by tinybike** [comment]
Just pushed a new on-contract function that will speed up the registration process about 3x.  This should also make the process short/simple enough that there's no need for a separate page.

**Comment by Newportkiwi** [comment]
I disagree - I think pages work so much better than modals for logging in and signing up. It's not a high priority but something for the final design.

**Comment by tinybike** [comment]
Are you talking about the progress modal (the one in Baz's screenshot that is behaving strangely), or the modal where you enter an account + password?  I think the account + password entry would be fine as a separate page.

**Comment by Newportkiwi** [comment]
I'm thinking something like this...

https://login.mailchimp.com/signup
http://getbootstrapadmin.com/remark/base/pages/login.html
http://getbootstrapadmin.com/remark/base/pages/register-v3.html

**Comment by tinybike** [comment]
I like http://getbootstrapadmin.com/remark/base/pages/login.html a lot -- very tasteful!

**Comment by Newportkiwi** [comment]
Yeah, me too. Think I'll adapt that page for Augur. They have a nice alternate design as well:

http://getbootstrapadmin.com/remark/base/pages/register-v2.html

**Comment by tinybike** [comment]
This issue was resolved by 853d1598966187c920f9000be700a5233301811d; creating a new issue for converting the register/login modals to pages.
