### ISSUE TITLE
Trading bug- multiple trades hitting up - incorrect position

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#3336]
Steps to reproduce:
Go to Binary market with existing order book: 
1) buy 5 of "yes" (take 5 from existing offer)
2) Sell out 15 down to the 2nd price of the existing bids (for example if the order book is .28 bid for 10 and .25 bid for 20, add an order to sell 15 at .25
Expected behavior would be to sell 10 at .28 and 5 at .25

what is happening is I am getting 10 at .28, 5 at .25 and 10 at .25

The trade history shows the extra 10 and my position reflects this as well

**Comment by bthaile** [comment]
user traded default canned YesNo market

buy 5 Yes shares at 0.31
sell 15 shares of yes at .25

user signs 1-2 transactions

in Filled tab in market trade page, there is 3 entries when only 2 TX got signed. (in this instance the user got prompted to signed twice)

**Comment by Chwy5** [comment]
closing, not seeing this
