### ISSUE TITLE
Problems with compilation from source "Cannot GET /"

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#335]
@blacktemplar commented on [Sun Oct 28 2018](https://github.com/AugurProject/augur-app/issues/396)

Since multiple Augur versions my Arch Linux Package which packages Augur doesn't work anymore (https://aur.archlinux.org/packages/augur-git/). The Augur-App starts up and synchronizes normally but when one opens the UI the only html-response is an Error "Cannot GET /".

Steps to reproduce the problem:
```
git clone https://github.com/AugurProject/augur-app.git
cd augur-app
npm install
npm run make-linux dir --dir
cd dist/linux-unpacked/resources
electron app.asar
"Connect in Augur-App and then click Open in Browser (after syncing)"
```

The weird thing is that if we are calling the executable `../augur` everything works fine. But I would prefer to don't use the executable in my package since I don't know all the dependencies of the executable. I followed the packaging of another well known electron app in arch linux for my build script, see https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=signal.

---

@petong commented on [Thu Nov 08 2018](https://github.com/AugurProject/augur-app/issues/396#issuecomment-437105051)

The problem seems to come from the command you are using to start the app, it does not start the UI server which is why the GET request isn't handled. You can also see this by running `lsof -i :8080` after you start the app via your electron command vs running the binary. Is there a reason you prefer `electron app.asar` rather than the binary itself?

---

@petong commented on [Thu Nov 08 2018](https://github.com/AugurProject/augur-app/issues/396#issuecomment-437220336)

the app uses `electron-is-dev` to determine the env that is being run. If the app isn't started via the binary then the library assumes that the env is dev:

```function getUIClientBuildPath() {
  if(isDevelopment) {
    return path.join(__dirname, '../../node_modules/augur-ui/build')
  } else {
    return path.join(process.resourcesPath, 'ui-client')
  }

}
```

since the ui-path has to be accessed by a browser it can't live within the asar packed app. 

Currently looking to see if there is a way around this problem.

**Comment by petong** [comment]
@blacktemplar Are you still interested in getting this working? You most likely will have to call the augur binary itself rather that electron.

**Comment by adrake33** [comment]
Closing this for now. 

@blacktemplar if you'd still like to get this working, feel free to reopen this ticket.

**Comment by blacktemplar** [comment]
I changed the package to use the binary, so I don't need this anymore.
