### ISSUE TITLE
When i refresh the ui screen it logs me out (using trezor)

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#336]
@Chehands commented on [Fri Jul 13 2018](https://github.com/AugurProject/augur-app/issues/157)

---

@petervecchiarelli commented on [Mon Jul 23 2018](https://github.com/AugurProject/augur-app/issues/157#issuecomment-405613404)

https://app.clubhouse.io/augur/story/14232/keep-user-logged-in-after-browser-refresh

---

@sharkcrayon commented on [Mon Jul 23 2018](https://github.com/AugurProject/augur-app/issues/157#issuecomment-407008318)

@Chehands This is expected behavior at the moment, though we are discussing changing this. I'll post an update here when I have one.

---

@CptanPanic commented on [Thu Jul 26 2018](https://github.com/AugurProject/augur-app/issues/157#issuecomment-408258628)

Yes I am struggling with this issue also.  I would like to use the improved search/sort at predictions.global but am not able to actually bring up markets that I find because it then logs me out of wallet.  

---

@bthaile commented on [Sat Sep 08 2018](https://github.com/AugurProject/augur-app/issues/157#issuecomment-419689135)

We'll be working on an auto-login and manual logout feature.

**Comment by adrake33** [comment]
We have decided to hold off on implementing this for the time being: https://app.clubhouse.io/augur/story/16818/keep-user-logged-in-on-refresh-for-edge-trezor-ledger

**Comment by joeykrug** [comment]
For things that have been decided not to be done, let's just close them --- dead issues are like commented code imo, let's keep it clean
