### ISSUE TITLE
Order ticket displaying wrong closing Values

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#3363]
Wehn I have an existing long position and I go to sell out my long position and more, the order ticket closing position displays wrong amount of shares and the profit is incorrect as well

Steps to reproduce:

Go to Yes/No market with no current position
Trade 1) buy 5 shares at .31 (new position I am long 5 shares at .31)
Order book has .25 bid for 5.02 and .19 bid for 30.03
Trade 2) enter selling 10 shares at .19

Closing position in the order book should say Selling out 5 shares (mine shows 9.98) and new position should show selling out 5 shares (mine shows .02)

Also my profit on the closing position shows positive number should be negative (bought .31s selling out .25s)

**Comment by Chwy5** [comment]
This happens with starting with a short position as well.

The key to reproducing this is to reverse and do more than the starting position...

So If I bought 5 shares on the first trade and go to sell out my 5 shares, it works correctly, but If i bought 5 shares on the first trade and go to sell 10 shares, the numbers get screwed up

**Comment by pgebheim** [comment]
@Chwy5 -- Is this still an issue?

If it works now can you close it.
