### ISSUE TITLE
frozen funds is off when shorting

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3369]
these are prob related. 

short YesNo market. User shorted 5 at 0.25 and current value is -3.75. 
frozen funds was current before trade, after frozen funds goes to 56.6514. 

(new ff value) 341.569 - (previous ff value) 294.3953 + (short trade) 3.6 + (recent short trade) 0.81 = 51.5837 off

**Comment by pgebheim** [comment]
Closed with #3376
