### ISSUE TITLE
UI not resetting issue

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#337]
- Make a trade to buy
- Sell a few shares after
- Get this:

![uinotreset](https://cloud.githubusercontent.com/assets/5925937/13329456/95a88a42-dbb9-11e5-84b5-20c2c4c7c4b6.PNG)

It's just doing the trade in the same window as the trade that just finished w/o starting the progress and info over again

**Comment by tinybike** [comment]
Fixed in 853d1598966187c920f9000be700a5233301811d.
