### ISSUE TITLE
Feature: Auto connect

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#338]
@page1 commented on [Mon Jul 23 2018](https://github.com/AugurProject/augur-app/issues/227)

I'm betting most users are not going to change these settings. And even those that do will probably always want to connect to the same endpoints. Adding a little "remember my selection", or "connect automatically next time?" check box would reduce the complexity of this app.

<img width="557" alt="screen shot 2018-07-23 at 12 00 34 pm" src="https://user-images.githubusercontent.com/6609556/43094439-1af0b114-8e70-11e8-9b45-764159630115.png">

Obviously with this change some way to go back and make changes in the future would be needed.(Possibly part of the "settings" dropdown

---

@joeykrug commented on [Mon Jul 23 2018](https://github.com/AugurProject/augur-app/issues/227#issuecomment-407252945)

Yeah I like this idea

---

@bthaile commented on [Mon Jul 23 2018](https://github.com/AugurProject/augur-app/issues/227#issuecomment-407261665)

https://app.clubhouse.io/augur/story/14414

I like this idea also. It was a feature initially but has gotten lost through the many revisions.

**Comment by sharkcrayon** [comment]
@adrake33 I think this should be closed. It seems relevant to the old Augur App design, not the most recent one.

**Comment by adrake33** [comment]
Yeah, this can be closed. I had copied over some of the remaining issues from the augur-app repo when Pete and I were migrating everything to this repo and hadn't re-looked at them very closely yet.
