### ISSUE TITLE
Problem with numbers

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#338]
![problemwnumbers](https://cloud.githubusercontent.com/assets/5925937/13329512/e58ab030-dbb9-11e5-8cba-a569b00876c5.PNG)

**Comment by tinybike** [comment]
Is the issue here the blank text for one of the outcomes, or something else?  Right now if you input a space for the outcome text it will accept that as valid text; I can change that if that's not what we want.

**Comment by Newportkiwi** [comment]
They should have to enter something IMO. Shouldn't be able to leave the outcome field blank when creating a new market.

**Comment by tinybike** [comment]
Fixed in 2e345e7bdabebad2aceaa62715cb070a4ade0275.
