### ISSUE TITLE
wire up `cancel all` button on market trading page

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3384]
Currently nothing happens when user clicks `cancel all` button at the bottom of open orders.

**Comment by bconfortin** [comment]
The button is disabled whenever there is something pending (hasPending).
When enabled and clicked, I get the following error:

```javascript
AwaitingSigning Transaction cancelOrders

inpage.js:1 MetaMask - RPC Error: Internal JSON-RPC error. 
{code: -32603, message: "Internal JSON-RPC error.", data: {…}, stack: "Error: "message" must be a nonempty string.↵    at…eogaeaoehlefnkodbefgpgknn/background.js:1:1207421"}

wrap-log-handler.ts?7035:14 event name Failure

log-handlers.ts?1ac7:111 TxFailure Transaction cancelOrders
:8080/#!/market?id=0…5e01C4bC8AbDDFB23:1 Uncaught (in promise) 
code: -32603
message: "Internal JSON-RPC error."
```

**Comment by bthaile** [comment]
That means the contract call failed. This can happen if too many order ids were sent to the cancel multiple order contract call


issue was resolved, MM pop was being manually cancelled

**Comment by bthaile** [comment]
fixed by PR, closing
