### ISSUE TITLE
open order shows processing even though user canceled the `cancel order` transaction

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3385]
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/7500c9c9-4120-4be4-b068-c6983e9084f0)

UI needs to remove pending when cancel order fails.

**Comment by joeykrug** [comment]
does this still happen @bthaile?

**Comment by bthaile** [comment]
We added a failed handler so the cancelled order doesnt just spin
