### ISSUE TITLE
Date issue

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#339]
![needfulldate](https://cloud.githubusercontent.com/assets/5925937/13329602/6da245a0-dbba-11e5-8fd9-1bdf7c7323d9.PNG)

**Comment by tinybike** [comment]
Is the issue here that the DD is cut off?

**Comment by joeykrug** [comment]
Yes

**Comment by tinybike** [comment]
Fixed in 9283c6571fad363080709594acdccf5ebc3d30d1.
