### ISSUE TITLE
Trading: Bell alert copy 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#3403]
Alert content (chat to chwy about this) 
General idea here: 
More useful strings, e.g. has market name and link 
IF partial - context of parent transaction e.g. "filled [2 of 10] on [market name]"
Or can partials just update one alert for example 
Settings: ability to turn off toast 

--- notes --- 

Transaction states 
Awaiting signature
Contract method and params 
Pending
Confirmed
We can now tell how many blocks are confirmed after transaction confirmation
Question of whether we would want to do anything here 
Failed

**Comment by phoebemirman** [comment]
copy was updated when alerts work was done
