### ISSUE TITLE
Market list page Categorical Market type blends with the Tags

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#3416]
See screenshot:

![8-30.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/bc2f6c53-636c-4052-b1c7-960b97228205)

**Comment by andrewdamelio** [comment]
@Chwy5 I believe this has been fixed - please confirm

**Comment by Chwy5** [comment]
Fixed - closing
