### ISSUE TITLE
Convert Register and Login modals to pages

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#343]
Moved from #333.  @newportkiwi says:

I'm thinking something like this...

https://login.mailchimp.com/signup
http://getbootstrapadmin.com/remark/base/pages/login.html
http://getbootstrapadmin.com/remark/base/pages/register-v3.html

**Comment by Newportkiwi** [comment]
@tinybike Something these...

![sign up page](https://cloud.githubusercontent.com/assets/16562458/13351811/37641c58-dc81-11e5-88b7-38fa520b91f5.png)
![login page](https://cloud.githubusercontent.com/assets/16562458/13351810/374fc3fc-dc81-11e5-8303-9fb28f442368.png)


(made with royalty free images from: https://pixabay.com/)

**Comment by tinybike** [comment]
Converted in 59f966ae8b6d24f221fec1ec166e75a53216429e.  Still needs to be re-skinned (to match those screenshots!) though.
