### ISSUE TITLE
[Dev] Product Analytics

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#3431]
## Goal

To improve the experience for users of Augur the UI needs to be instrumented to track events in scenarios where users actions are not recorded on chain. In a traditional web app, a service such as Google Analytics or Mixpanel would be used to gather and report on this data. This isn't an option for Augur, since third party tracking services cannot be shipped with the UI.

The goal, then, is to create a usable and publically accessible event stream which allows anyone to understand the activity on Augur simply by subsribing to an IPFS pub/sub channel.

Using the events off this channel, data can be analyzed to understand user behavior by subsequently using off the shelf analytics tools. Anyone subscribing to this channels has the opportunity to understand Augur user behavior, just as anyone analyzing the blockchain has the opportunity to understand user behavior.

## Considerations

- User privacy -- what data gets published and is there any information available to publish that would not already be available via the blockchain

  - e.g. When a user connects with the Tor.us wallet they can optionally transmit their email to the dapp, allowing it to display their logged in email instead of their Account address. This data should not be logged as its not otherwise available on chain.

- Trading data / front-running -- The application should not log information related to trades the user may want to make but has yet put on the order book, or at least should delay these events enough that they're not actionable for front running purposes beyond what is already possible for either 0x-based trades or on-chain trading.

- IPFS data usage -- chattering messages through the pub/sub network isn't costless for people accessing Augur and participating in ipfs and the application should strive to limit it's data transfer to actionable, non redundant data.

  - e.g. logging steps of a users sign-up process allows understanding what prevents users from accessing Augur, vs logging the whole order book on every trading page load demand that all clients send the same information through the ipfs network.

- How do we prevent tampering / otherwise reduce the amount of crappy data showing on the pub sub channel that may screw up stats? Perhaps we do nothing...

## Implementation:

The implementation needs to be broken into two halves.

   1) A layer which tracks events within the react app / js in general and submits them to the pub sub network.

   2) A layer to connect to the IPFS pubsub network, handles publishing messages.

For (1) -- begin by evaluating https://getanalytics.io -- It looks like it will be perfect for what we want! Using it page views and events can all be tracked without significant effort.

For (2) -- Implement a plugin for the Analytics that tracks events through the IPFS pubsub. This plugin will need to create an IPFS node in our app and then use that to send messages via pubsub.

Example code for doing this:

https://gist.github.com/joeykrug/3b8d86e30813ea8fc4a947b64188010a

https://gist.github.com/joeykrug/87498d3765814c6adb38d072e3f898c2

https://gist.github.com/joeykrug/99f30c738813d0d7c4c6c0737b1ec54f

This pubsub code should be instiated by the middleware and should be share-able by other components of the application. For instance well want to use the ipfs node to also pin the Augur UI allowing the current browser to serve UI resources to clients.

Questions)

  - Can we use this one instance with Orbit.chat?

What to track:
  - All page transitions -- analytics.page()
  - All steps of onboarding
  - When a user has started funding
  - When a users funds are detected after they began funding 
  - All trading actions (filled ticket, submitted order)
  - ???

**Comment by pgebheim** [comment]
This issue should track the sum of work, we can break this into 3+ tickets:

1. Create plugin for Analytics.js that can send events to IPFS pub/sub
2. Integrate that into the Augur UI in one spot and make sure it works
3. Instrument various actions with it.

**Comment by gitstart-augur** [comment]
- Can we use this one instance with Orbit.chat?
@pgebheim 

1. We will use the browser version of ipfs
2. Create a node on browser.
3. And connect to OrbitIO node via swarm.
4. Each channel on Orbit has a separate db, we can get it on console log.

Basically this is very possible and we should give it a shot.

**Comment by pgebheim** [comment]
That is true -- but currently we are iframing the orbit chat so that if there's an XSS or injection in the chat it doesn't infect the whole app.

So given that we either need to connect to the ipfs service in both, or start to do something more complex like share that connection with a serviceworker.

For the scope of this let's start by adding the ipfs connection to the SDK (on the worker side) and go from there. Incidentally I am going to try to do something similar tomorrow to support another feature.

Paul
paul@augur.net

________________________________

**Comment by gitstart-augur** [comment]
Estimated Credit Cost: 150

**Comment by gitstart-augur** [comment]
Final credit cost: 300
