### ISSUE TITLE
Finish remaining issues with syncing tracked users

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#3436]
TODO: 
- Replace Sync.createAPIAndController function with a better solution
- Make other endpoints (HTTP, WS, etc) respond to UserDataSynced event
- Enforce mixed case addresses

**Comment by pgebheim** [comment]
@adrake33 Removing this from market list as its not necessary, but putting it in the general Sprint 16 bucket.

**Comment by pgebheim** [comment]
We've removed `tracked users`
