### ISSUE TITLE
Create bot for math for PnL

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#3438]
We need to create a bot to confirm math is always correct on each entry:

Adding open orders(both long and short),
Trading (both long and short), this include multiple trades-book sweeping
Holding Multiple positions in the same market
Reversing open position
Cancelling orders

**Comment by Chwy5** [comment]
Need to confirm PnL after a market is finalized as well

**Comment by pgebheim** [comment]
This is a nice to have -- idea here for perpetuity
