### ISSUE TITLE
Create bot for Math of Frozen Funds

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#3439]
We need to create a bot to confirm math is always correct on FF after each entry:

Adding open orders(both long and short),
Trading (both long and short), this include multiple trades-book sweeping
Cancelling orders

**Comment by pgebheim** [comment]
I think this is less of a bit and more of a script that can dump trades into a spreadsheet format so it's easy to follow

**Comment by pgebheim** [comment]
@Chwy5 -- Gonna close this as a ticket until we're actually gonna schedule it out -- its easy to regenerate.
