### ISSUE TITLE
Fix Gnosis Test

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#3445]
We're getting a nonce error in the Gnosis test when creating a market. However, when the contract is edited to make that call do nothing, the nonce error goes away. Thus the error is with ganache, not the contract nor how we're calling it.

This ticket is for figuring out a solution. Ideally ganache is fixed but it's also viable to use a different evm for this test.

**Comment by robert-e-davidson3** [comment]
Upgrading to ganache 2.7.0 did not help.

**Comment by bthaile** [comment]
based on what Alex said this is done, closing
