### ISSUE TITLE
Current Value not displaying value

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#3446]
On the portfolio pg in the positions section the Total Returns/Current Value toggle button....when changed to Current Value, Value still shows 0.000 even though there is a current value for an open position...

see screenshot:

![9-3.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/37e93096-db8a-418e-adb3-c9a13b42ec2f)

**Comment by bthaile** [comment]
market currentValue should be total value of all positions.
