### ISSUE TITLE
Switching accounts using Metamask

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#3447]
created 1 market w on MM acct, when to trade vs it in another MM acct and getting this message....I have logged out and back in with the new acct and the addresses changed but still getting this pop up...

![9-3a.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/a514bf44-0b9e-4139-8203-0fb9627a6fc9)

Steps to recreate:
1) using a Metamask acct sign on and create a market with adding liquidity in market creation
2) approve your market and the liquidity so the orders are on the order book
3) log out
4) log in with a different metamask acct.
5) click on one of the orders on the order book so the info filters into the order ticket
***Message appears in the order ticket for me

**Comment by bthaile** [comment]
I might need some SDK support on this ticket. Will need to research it. We recently made some changes to login to sdk process. 

Need backend support for this @justinbarry 
seems once `ContractDependenciesEthers` address has been set it can't be changed. I think I'm missing something. 

Tried when user switched accounts, setting account property on `contractDependencies` through Augur.ts. That worked fine except that orderbook getter got the old one. It behaves like there are 2 separate instances of contractDependencies.

**Comment by pgebheim** [comment]
@andrewdamelio Can you check on this one?

**Comment by andrewdamelio** [comment]
@pgebheim tested on v2.augur.net. I was unable to reproduce the issue described in the initial issue.

**Comment by Chwy5** [comment]
Hey I Just tried to reproduce even trading with myself consuming my own order in the same Acct) and I am not seeing that popup message appear (which would be a bug)...

**Comment by pgebheim** [comment]
Oh! Does that not happen only of you switch accounts?
