### ISSUE TITLE
Multiple transaction popup keeps returning after (x) it out to close

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#3448]
![9-3mb.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/c5352629-9b57-46e4-ae77-99afe504384d)

To recreate:
try sweeping an orderbook (take multiple trades at once) to trigger the notification pop-up in the order ticket.  Click the (x) in the top right of the message (DONT do the trade yet), wait 5 seconds and it returns

**Comment by bthaile** [comment]
component doesn't rem that the user dismissed it. the component refreshes and loses all state. 
That is current behavior. We'll need to hold state outside of component and reset when either trade is executed or form is cleared. 

this will still be an issue with 0x trading since fills are on-chain.

**Comment by Chwy5** [comment]
fixed-closing
