### ISSUE TITLE
Closing position doesnt match my current position

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#3449]
Steps to recreate:

1) The example above was in a yes/no market....first trade I bought 5 shares that were offered on the order book....after executing the trade current position s/b long 5 shares (which is what is shown under positions)
2)  Next I went to sell out 6 shares that were bid on the order book
Closing Position says selling 6 shares:
Closing Position s/b selling 5 shares 
and Opening a new position
of 1 share

![9-3b.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/86d9be8e-273c-4878-acc4-ebde5a8d65af)

**Comment by bthaile** [comment]
testing binary market:

user is short 17.01 shares

simulate trade, buy 32.05 at 0.40:
simulate trade says shares depleted is 19.03, but positions getter says user is short 17.01

inputs
```
{
  "affiliateAddress": "0x0000000000000000000000000000000000000000",
  "amount": "320500000000000000",
  "direction": 0,
  "displayAmount": "32.05",
  "displayMaxPrice": "1",
  "displayMinPrice": "0",
  "displayPrice": "0.4",
  "displayShares": "0",
  "doNotCreateOrders": false,
  "kycToken": "0x0000000000000000000000000000000000000000",
  "market": "0x0A2603aa7DF52Df509D822a8f931173484Bf2aC1",
  "numOutcomes": 3,
  "numTicks": "100",
  "outcome": 2,
  "price": "40",
  "shares": "0",
  "tradeGroupId": "0x393864653761302d623335312d343361652d383062392d363061373035366600"
}
```
results:
`["320500000000000000","5208000000000000000","190300000000000000","0","2"]`
```
{
  "displaySettlementFees": "0",
  "displaySharesDepleted": "19.03",
  "displaySharesFilled": "32.05",
  "displayTokensDepleted": "5.208",
  "numFills": "2"
}
```

also odd is when user wants to buy 300 shares, simulate trade says user depletes 36.04 shares

inputs:
```
{
  "affiliateAddress": "0x0000000000000000000000000000000000000000",
  "amount": "3000000000000000000",
  "direction": 0,
  "displayAmount": "300",
  "displayMaxPrice": "1",
  "displayMinPrice": "0",
  "displayPrice": "0.4",
  "displayShares": "0",
  "doNotCreateOrders": false,
  "kycToken": "0x0000000000000000000000000000000000000000",
  "market": "0x0A2603aa7DF52Df509D822a8f931173484Bf2aC1",
  "numOutcomes": 3,
  "numTicks": "100",
  "outcome": 2,
  "price": "40",
  "shares": "0",
  "tradeGroupId": "0x666139386233302d336236622d343739372d623062332d333335373939623900"
}

result:
```
["320500000000000000","105584000000000000000","360400000000000000","0","2"]
```
{
  "displaySettlementFees": "0",
  "displaySharesDepleted": "36.04",
  "displaySharesFilled": "32.05",
  "displayTokensDepleted": "105.584",
  "numFills": "2"
}
```

**Comment by Chwy5** [comment]
This is fixed...closing
