### ISSUE TITLE
Open market showing as expired

### ISSUE THREAD

**Issue by Sput** [AugurProject/augur#346]
On the expired markets tab is a market not set to close until Feb 29 (screenshot taken on Feb 27th). Also not shown in the picture, but there are three markets listed as expired, but the page reads "1-2 of 2"
![2016-02-27](https://cloud.githubusercontent.com/assets/1197741/13374777/09606092-dd43-11e5-811c-524e2f7e68e0.png)

**Comment by tinybike** [comment]
Fixed in 77dd2ed19b3d38e0d610b3756f2b2914ad1561ca.
