### ISSUE TITLE
Register not working on iOS 9.3 + Safari

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#347]
When I try and register, the page just auto-reloads, with the message "a problem occurred with this webpage so it was reloaded" displayed at the top.  Possibly chunking the work required for key creation would fix this?

**Comment by tinybike** [comment]
Looks like a Safari-specific issue -- register works okay on iOS 9.3 + Chrome.

**Comment by thinkloop** [comment]
Updated keythereum and augur.js with chunked scrypt-based auth. This will make logging in and registering much better in general, and hopefully resolve this issue.

498f2a486e52137c3d6b2b82f4a1359bc74ff46a
c49225645da210bf08aa75f1e450c525ee614fd5
