### ISSUE TITLE
V1 augur-node: error getting initial reporter balance

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3476]
started up UI with `ETHEREUM_NETWORK=rinkeby yarn dev`

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/05334c8f-3a23-465f-9fb2-89192af5652e)

steps:

 * created a market
 * navigated to My-markets in portfolio to get Initial reporter address from market card.
 * transferred REP to initial reporter contract. 
 * refreshed UI

**Comment by pgebheim** [comment]
Done
