### ISSUE TITLE
Market Sort Options pending Backend Support

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#3480]
Market sort options don't work for the below sort options. 
```
GetMarketsSortBy.marketOI
GetMarketsSortBy.volume
```

**Comment by adrake33** [comment]
Dupe of #3023. I'll add a note to it to look into marketOI/volume sorting

**Comment by adrake33** [comment]
Reopening and removing parts about liquidity sorting, since those are in #3023.
