### ISSUE TITLE
Add market depleted filter to getMarkets getter

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#3490]
from Joey in Discord:

That sort should show markets that don't appear in the current hourly liquidity ranking but did in the average one
// rerun this hourly
// will need to store in local storage or w/e

if(time.now() - last_updated >= 1 hr ago):
    hourly_rankings[current hour day year] = do_liquidity_calcs()
    last_updated = time.now()

ranking = sum(hourly_rankings.trailing24hr.only_nonempty) / len(hourly_rankings.trailing24hr.only_nonempty)
https://gist.github.com/joeykrug/f61596d7b51cf66252c01b599bc3f0f6

Gist
Liquidity ranking
Liquidity ranking. GitHub Gist: instantly share code, notes, and snippets.

from ^
so take ranking above and hourly_rankings[current hour day year], remove any duplicates in ranking by removing ones that are also in hourly_ranking Whatever is remaining in the ranking list is therefore markets that were liquid > 1 hr ago but aren't now, and thus need liquidity replenished and should appear under the "needs liquidity" filter
no timestamp imo, it's just a filter
cc @achapman if any algorithms questions

This also needs to update the liquidity snapshot DB to save liquidity per market for each liquidity spread in the UI.

**Comment by bthaile** [comment]
@joeykrug we need a little clarity on this feature. @adrake33 

Is what is proposed a filter in the UI where there's an option in the liquidity spread filter, and only markets that have had liquidity recently depleted? like within the last hour, day, week?

add new `recently depleted` option here
![image](https://user-images.githubusercontent.com/3970376/64455996-ba4fe680-d0b4-11e9-8b34-fe67f19a4d7e.png)
