### ISSUE TITLE
Mobile Menu Updates

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#3503]
SideNav Updates
- ~~The Routing menu~~ [Done]
- The Filter/Sort/Search menu
https://www.figma.com/file/GKhft5ZOwuH3ANrupGNCLHUU/Market-list-page?node-id=225%3A0
  - Clicking Search (on markets list page) will open the Mobile Side Nav with  *new* search
  - Clicking Market Title (on markets list page) will open the Mobile Side Nav with categories options
  - Clicking Filter button(on markets list page) will open the Mobile Side Nav with filters/sort options

Categories:
![image](https://user-images.githubusercontent.com/1683736/64862890-a3a01700-d601-11e9-995c-dc4d49a7a641.png)

Filters/Sort:
![image](https://user-images.githubusercontent.com/1683736/64862869-96832800-d601-11e9-8bf2-12a0e49b3462.png)

Search:
![image](https://user-images.githubusercontent.com/1683736/64862590-ea414180-d600-11e9-86b6-f6675775cffe.png)
  - Show Markets and Cateogires that match the search

**Comment by pgebheim** [comment]
Adding to Sprint 16 Misc / Bugs and we can go through and decide when this effort will happen.

**Comment by pgebheim** [comment]
@andrewdamelio Closing this, re-open if its still needed.
