### ISSUE TITLE
Remove body styles

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#3504]
Investigate why the below styles are being placed on body (and from where).

![image](https://user-images.githubusercontent.com/1683736/64465886-df584f80-d0dc-11e9-9698-4ce785ed2745.png)

**Comment by pgebheim** [comment]
@andrewdamelio Are you gonna prioritize this?

**Comment by joeykrug** [comment]
status / does this matter?

**Comment by andrewdamelio** [comment]
not a big deal IMO @joeykrug

**Comment by andrewdamelio** [comment]
@JohnDanz did you make any progress on this? Can we close this issue
