### ISSUE TITLE
JS error when signing in to MM

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#352]
chwy said he is seeing the following JS error appear in the console when he logs in:

![clipboard 2018-20-11 at 12 19 41 pm](https://user-images.githubusercontent.com/11491365/49481504-144b1500-f7e0-11e8-9eb4-0c4b1db99330.png)

**Comment by bthaile** [comment]
fixed by https://github.com/AugurProject/augur-ui/pull/2519
