### ISSUE TITLE
Stable IPFS Loader

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#3525]
## Description

A stand-alone, self-contained web page used to load the Augur UI based upon the current release in Github.

## Motivation

For SEO and Sharing having a stable URL for web pages is highly advantageous. In order to do this in a censorship resistant manner, Augur cannot rely upon existing DNS systems to resolve the current version of the Augur UI. As a solution, we propose creating a loader which once deployed will keep a stable IPFS hash -- but be able to dynamically look up the current release of the Augur UI from Github, load that release off of IPFS, and then display the app in the frame.

## Requirements
- Must be able to quickly resolve the Github release, and iniate loading the content seamlessly -- adding unnoticable latency to the page load.
- Strategy must be SEO friendly, so that Google etc can index the pages.
- Routes specified in the Loader URL should reflect in app on load: Example. if a user goes to /ipfs/QmUZ.../#market/0x3980c89aab1f6cd864f48e2746d504706bc44955 -- the loader should load the UI and drop the user onto the market page for that market immediately.

## Strategies
- Option 1: Load the page using normal HTTP calls, and swap out the body of the html. This is simple but may requre some trickery with paths. I got it working in a basic form (with a hardcoded IPFS path): https://gist.github.com/pgebheim/1d94a29e54b5f13476333a1a07b24174

- Option 2: Make a service worker that proxies all calls to load from the determined current release IPFS path. This could still load the data over HTTP using the same HTTP endpoint as the loader exists on. e.g. if the user loads the IPFS hash from cloudflare-ipfs.com/ipfs/<loader hash> -- then the content would all be loaded directyly from cloudflare-ipfs.com and cached in the service worker.

- Option 3: Load the data off of IPFS using js-ipfs and serve it via a service worker.

Of all the options we need to determine what works and still keeps SEO capability. I believe that google doesn't run service workers during its indexing, but does run Web Workers -- so option (2) and (3) may not work when being hit by the goog.

## Current Release Fetching

Each tagged release of the Augur UI will be available via the releases at https://github.com/AugurProject/augur/releases.

Each tagged release will contain a file (ipfs-hash.txt, or if needed ipfs-hash.json) that contains the current IPFS hash for the bundled assets.

**Comment by pgebheim** [comment]
Another option here is that the javascript that is used to load the site is served directly from GitHub.

In this model the loader would just find the current release and load the JS for loading the site.

**Comment by pgebheim** [comment]
Hey @gitstart-augur -- This is another one that I think could be a good task since although it fits in with IPFS it is mostly just loading a URL off of github releases and then doing some fancy javascript to load that inline

We can break this up into tasks if need be.

**Comment by gitstart-augur** [comment]
Initial Credit Estimate: 100
