### ISSUE TITLE
"Report" or "Dispute" buttons not dynamically showing in Child Universe

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#353]
Fork and go to a child universe.
Create a Market.
While viewing the Reporting: Reporting page move time forward to DR or Open Report period.
The market card moves to the correct location but the button says "Trade"
Refreshing the page makes it correctly display "Report"
Do an initial report and move time forward to a dispute window
Again the button on the market card says "Trade" when it should be "Dispute"
Refreshing the page also fixes this
...

This seems to just be for Child Universes so pushing out of this deadline
 -nuevoalex
...

@phoebemirman can you test this scenario to see if it's still an issue?
 -bthaile
...

@tomhaile this is still happening
 -phoebemirman
...

Moving to Ready for Development since this is still occurring.
 -adrake33
...

i am not seeing the MarketState/handleMarketStateLog log being called for child universes
 -phoebemirman
...

Assigning to Scott since this sounds like an AN issue, as Phoebe mentioned.
 -adrake33

**Comment by epheph** [comment]
@phoebemirman didn't we fix this a while back, the `MarketState` log being emitted? Or was this issue specific to child universes and in addition to the other MarketState log issues we had in the past?

**Comment by phoebemirman** [comment]
i think it is specific to child universes.

**Comment by epheph** [comment]
There is no logic in the update/emit that is specific to universe and subscription is not per-universe either; is it possible the UI is filtering universe websocket subscriptions locally?

**Comment by phoebemirman** [comment]
ill check that out

**Comment by phoebemirman** [comment]
i see the MarketState log coming through in the network tab

**Comment by epheph** [comment]
OK, so not an augur-node issue then? Must be something in augur.js or UI?

**Comment by phoebemirman** [comment]
Yea

**Comment by pgebheim** [comment]
Won't do V1 Fix.
