### ISSUE TITLE
when using the markets "search" functionality, should be intuitive way to clear search terms to quickly display all markets again

### ISSUE THREAD

**Issue by RonB7139** [AugurProject/augur#354]
can be a clear button, or the search field can auto-clear on next click of "open markets" or....

**Comment by joeykrug** [comment]
![image](https://cloud.githubusercontent.com/assets/5925937/13381206/aa88f41a-de1b-11e5-8a18-3cb4be0cd2a1.jpeg)

Maybe something like that

**Comment by Newportkiwi** [comment]
Like the search box in my last set of mock ups for the Markets pages. Which I will be adding to the style guide later tonight.
![stripes-colours-arrow](https://cloud.githubusercontent.com/assets/16562458/13381245/3f4537f2-de4f-11e5-97c7-9ecbf15e1ec5.png)

**Comment by RonB7139** [comment]
...great minds...

**Comment by thinkloop** [comment]
Enhanced in 4e3bfcd0038d7619c67008c106631a3461366aa5
