### ISSUE TITLE
Errors aren't propagated to the user.

### ISSUE THREAD

**Issue by Zoltu** [AugurProject/augur#355]
Errors from the jsonrpc calls aren't propagated to the user.  For example, try to place a bet with account balance too low.  The window will show you a progress bar but if you look at your network tab in chrome debugging tools you'll see that there was a jsonrpc error about balance too low.  This error should be surfaced to the user in some way, even if it is a generic, "Something went wrong".  Since the RPC is giving an error message it seems like it would be best to display that message to the user as well.

Note: I am not talking about a specific error message here, I am talking about the general case where the UI receives a jsonrpc error that it doesn't yet handle.  There should be a fallback error handling for unexpected errors.

**Comment by tinybike** [comment]
Error handling is now confined to the transactions screen (as of 59f966ae8b6d24f221fec1ec166e75a53216429e).  We may need to make the error reporting more verbose; we'll play that by ear.
