### ISSUE TITLE
Augur UI retries jsonrpc errors forever.

### ISSUE THREAD

**Issue by Zoltu** [AugurProject/augur#356]
When there is an unexpected jsonrpc error, the UI will retry over and over forever.

It appears to retry as fast as it can.  There should be some limits unless the error is on that is expected to eventually succeed.

**Comment by tinybike** [comment]
@Zoltu There was a bug in ethrpc's check-for-duplicate-nonces code that was causing this which I fixed a few days ago.  Just want to verify that this is still happening.  What are the steps to reproduce it, if so?

**Comment by Zoltu** [comment]
Repro steps:

1. Create an account.
2. Don't put any Ether in it.
3. Select a market.
4. Buy 10 shares.
--> Notice dialog just sits forever and notice that the request to Ethereum is repeated over and over again forever.

**Comment by tinybike** [comment]
Fixed in 4dd41daf7510950654e8f398f6abea63372ef6d2.
