### ISSUE TITLE
8080 redirects to 8443 when ssl is enabled but query parameters are lost.

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#357]
start augur-app and enable ssl.
`open in browser`
change the url from https://127.0.0.1;8443....
to http://127.0.0.1:8080... to mimic the user having an old browser session up.

notice that the user's browser redirects to https:.....8443 correctly but the query parameters are lost.

edge case but could cause the user confusion.

**Comment by bthaile** [comment]
Not sure we need to do this, the electron app is going to go away. recommend closing @adrake33

**Comment by adrake33** [comment]
Sure, sounds good, I'll go ahead and close this.
