### ISSUE TITLE
Expired markets page shows 5 markets, says showing 1-4

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#357]
![image](https://cloud.githubusercontent.com/assets/5925937/13381434/d7a28596-de21-11e5-819e-fc9f5f0065be.png)
![image](https://cloud.githubusercontent.com/assets/5925937/13381435/d7b4a3d4-de21-11e5-9710-9efcc98e3053.png)
![image](https://cloud.githubusercontent.com/assets/5925937/13381436/d7b64e28-de21-11e5-9adc-fc5e2bfcf372.png)

**Comment by tinybike** [comment]
That first market is not expired!  I think the "tour" market is just being shown under the expired tab when it shouldn't be.

**Comment by joeykrug** [comment]
I bet that's it

**Comment by tinybike** [comment]
Fixed in 77dd2ed19b3d38e0d610b3756f2b2914ad1561ca.
