### ISSUE TITLE
toast/alert component

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3571]
![image](https://user-images.githubusercontent.com/3970376/64651257-abd03a80-d3e6-11e9-8f94-f0e2876ba42e.png)

![image](https://user-images.githubusercontent.com/3970376/64723722-adf1d200-d496-11e9-9034-234373b826e4.png)

https://www.figma.com/file/20glBimYoPKAALucbh0tXP/Toast-and-Bell-Messages?node-id=2%3A25497

component that houses:
 * human readable transaction type
 * human readable transaction text
 * close button
 * etherscan link (all toasts should have a etherscan link)
 * date time 

states/modes:
 * read
 * unread (fyi, toast are always unread)

Can prob just reuse/restyle old alert component.

**Comment by pgebheim** [comment]
@phoebe @tomhaile -- is this one in progress yet?

**Comment by bthaile** [comment]
Not yet, just created it. To be worked after some reporting form tweaks.
