### ISSUE TITLE
Augur State: Sync with existing web3 provider.

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#3579]
Right now the UI passes an Alchemy URL to the SDK for making contract calls and populating the SDK's database of blockchain logs. We need to support more kinds of web3 providers, including MetaMask, which doesn't have a URL. We want to support anything that injects the typical web3 object into the UI thread.

Few kinds of object can be passed into a web worker because postMessage only clones its messages: it does not pass by reference except in a few irrelevant cases. Right now the SDK builds an EthersProvider out of the URL passed to it via postMessage. That EthersProvider wraps a JsonRpcProvider. We want to also support the SDK building an EthersProvider that instead sends and receives messages with the UI thread. So when we tell the SDK thread how to talk to the blockchain, the message we pass will potentially include message routing information - both what to send and what to listen for.

A new object will live in the UI thread that routes these messages to and from the SDK and web3 provider. Let's call it Web3Router.

---

MetaMask potential example:

Logs are received in the MetaMask plugin thread. This will trigger changes in the UI thread's web3 object that will call the Web3Router's hook. That hook will send the logs as a message to the SDK thread. The SDK will process the logs exactly as it does right now, using its EthersProvider. (Note: I'm speculating as to how web3 is updated and if it even has hooks. Polling may be necessary.)

The SDK makes contract calls. It will pass the call to its EthersProvider which will send a message to the UI thread. The UI thread has its Web3Router object route that message to the web3 provider aka MetaMask. This routing is likely just a call to the web3 object.

---

When there's a choice of where to put extra complexity, the first choice is the new EthersProvider implementation. Specifically, the message routing to/from web3 should be as simple as possible because it's difficult to test relative to testing within the SDK.

---

Relevant docs:
* https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage

**Comment by pgebheim** [comment]
This currently happens when using the SingleThreadConnector -- Since that model appears to be working, e.g. not needing WW since we switched to dexie, I think we consider this closed.
