### ISSUE TITLE
More Info on "Details" displayed on the "Revealing Trade" Window

### ISSUE THREAD

**Issue by tonysakich** [AugurProject/augur#358]
When a trade is in progress and the "Details" is selected, the information displayed has no context in regards to "what it is" and would definitely provide confusion to newer/less tech savvy users. Would it be possible to include a more specific description of what the information is regarding? Upon launch I have a feeling users would select "Details" and it will not show specific information they may be seeking. Image showing this window is here: http://imgur.com/yUnm5Ig

**Comment by tinybike** [comment]
"Details" is whatever the market creator typed into the details box when they created the market.  I don't see how it's possible to be more specific, since it'll be different for every market.  Am I misunderstanding your question?

**Comment by joeykrug** [comment]
Look at hit image

**Comment by joeykrug** [comment]
His*

**Comment by tinybike** [comment]
The link doesn't work for me -- if you can see it, mind pasting it here?

**Comment by joeykrug** [comment]
![capture](https://cloud.githubusercontent.com/assets/5925937/14219353/6be26a66-f81f-11e5-8539-ec941357cd28.PNG)

there ^

**Comment by tinybike** [comment]
Obsoleted by 59f966ae8b6d24f221fec1ec166e75a53216429e.
