### ISSUE TITLE
Browser Crashes / Memory issues

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#3582]
Desktop:
If I leave the window open for a while I'll sometimes come back to the below.
![image](https://user-images.githubusercontent.com/1683736/64661085-3c237500-d411-11e9-9ebc-b43cf2aac836.png)

Mobile:
Joey noticed some mobile issues - "Reloading bug. The page reloads and says an error happened with maybe 1/3 of UI interactions"

I've also noticed mobile safari/chrome will sometimes just spontaneous crash.

**Comment by pgebheim** [comment]
Well that's a bummer.

@justinbarry @achapman add to the list to look at with profiling.

**Comment by andrewdamelio** [comment]
![image](https://user-images.githubusercontent.com/1683736/64725936-95d47f80-d4a3-11e9-9d87-9b9fa5a2d86c.png)

**Comment by pgebheim** [comment]
oh lordy, a pouchdb crash with OOM.

Wondering if this is happening during indexing because of the index algo or if things are bloated elsewhere and this just happens to be where it exploded.

**Comment by joeykrug** [comment]
dont see this anymore
