### ISSUE TITLE
Suggestion to place the price chart to the right of market data instead of below

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#359]
A la
![image](https://cloud.githubusercontent.com/assets/5925937/13387299/d6bb3ec6-de7a-11e5-97d4-80ae97c38c53.png)

Instead of vertical (could be vertical on mobile though)

**Comment by tinybike** [comment]
That's not a bad idea.  And maybe below instead we could have a "passive updates" window -- instead of the modal progress window, you could have a minimizable terminal-like window that just shows you updates as they arrive.

**Comment by Newportkiwi** [comment]
I would put the chart on a separate Stats & Charts tab.
