### ISSUE TITLE
docs.augur.net crashes in Chrome on Android

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#360]

**Comment by joeykrug** [comment]
Tested + works on Chrome on Galaxy S7

**Comment by adrake33** [comment]
@pgebheim was the one who reported this using his S9+ with the latest version of Chrome. We haven't tested it on any other Android devices yet.

@tinybike Can you try loading docs.augur.net on your Pixel2 to see if Chrome hangs for you?

**Comment by joeykrug** [comment]
Works on Nexus 6 as well

**Comment by adrake33** [comment]
Ok, that's good to know. Maybe it's specific to @pgebheim's setup. If Jack is able to load it without problems as well, we can probably just close this.

**Comment by adrake33** [comment]
@Chwy5 tried this on his Galaxy S6, and he said "it loaded, but seems to be stuck....I see overview and all the writing, but cant scroll down and the 3 lines with nav wont open"

**Comment by joeykrug** [comment]
Have him try again, it works in browserstack now on G S6

**Comment by adrake33** [comment]
@joeykrug Paul tried it this morning and said it's still broken for him when he loads the page & clicks on the menu. Also it's broken in Brave too for him.

**Comment by Chwy5** [comment]
Pg only load 5/6th of the way and then the loading bar gets stuck.   I can scroll up and down, but cant open the 3lines nav button
