### ISSUE TITLE
Market List Changes - top area

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#3607]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/1171fad4-5d65-47a3-bd5c-e13371d4d2bb)

Reference Frame
https://www.figma.com/file/GKhft5ZOwuH3ANrupGNCLHUU/Market-list-page?node-id=968%3A12572

Ignore color change for now

Shrink up search bar height to 44px

Page Header (All Markets) make 24px

Move down dropdown and view market card type buttons to sit 16px above cards or fee message.

Decrease vertical spacing between all these elements to 16px

**Comment by matt-bullock** [comment]
Should the search say 'Search markets and categories' ? @Chwy5 

Can you make the number next to Open, in-reporting, resolved bold text
Underline for these should be corresponding colour when active. Green for open, yellow for in reporting, red for resolved

**Comment by Chwy5** [comment]
Should say 'Search markets and categories'
