### ISSUE TITLE
js error when registering an account

### ISSUE THREAD

**Issue by pqdeep** [AugurProject/augur#361]
might have to do with limitations of system I'm using -- had a few browser tabs opened in Firefox (current version / Windows 10) -- but js should be lightweight enough for broad array of configs to be able to handle it. I was allowed to go to the next step after clicking the "continue' button twice.

https://drive.google.com/open?id=0Bx8T_M1UUwjQMTFXbHZMNnNzR2c

**Comment by tinybike** [comment]
This is actually just a warning (not an error).  You're getting this message because the private key encryption step requires quite a few hashing rounds for security.  I could make it lighter weight -- 1 hash round and it would finish instantly -- but it would be at the cost of security.

**Comment by pqdeep** [comment]
Rather not compromise security (certainly not for live version). I dont suppose there's a way to keep browsers from generating this error - maybe something that could "ping" to the browser the equivalent of a "hey, don't worry, it's coming"?

**Comment by tinybike** [comment]
I'm not sure -- @thinkloop, would chunking the work the way you suggested help with this?

**Comment by joeykrug** [comment]
I'm on a 2014 thinkpad and it happens on my machine too

**Comment by thinkloop** [comment]
@tinybike if the smallest atomic operation works well and fits nicely in a frame, then chunking should work

**Comment by thinkloop** [comment]
I found a solution to upgrade the hashing algorithm to scrypt while also removing browser lockup:

```
var scryptAsync = require('scrypt-async');

var password = 'aaaa';
var salt = 'bbbb';
var N = Math.pow(2, 17);
var r = 8;
var finalHashLength = 32;
var chunkSize = 100;

console.time('time-scrypt');
scryptAsync(password, salt, Math.log2(N), r, finalHashLength, chunkSize, (derivedKey) => {
  console.log('---->', derivedKey);
  console.timeEnd('time-scrypt')
}, 'hex');
```

**Comment by thinkloop** [comment]
Updated keythereum, updated augur.js with chunked scrypt auth. This will make registering/logging cleaner, and hopefully solve this issue
