### ISSUE TITLE
Make market indicator easier to see when close to extreme ends of scalar markets

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#361]
Currently, the market indicator is barely visible for scalar markets when at the extreme left/right of the range:

<img width="449" alt="screen shot 2018-09-25 at 4 35 22 pm" src="https://user-images.githubusercontent.com/11491365/49775141-06980280-fcac-11e8-8380-9925fa7d1b4d.png">
...

@juliyasmith I think the easiest way to fix this might be to set a maximum for how close it can be to the ends. Does that seem reasonable?
 -adrake33
...

@adrake just in terms of display? Ya that sounds good
 -unparalleled-js
...

Tho when I first brought this up, I meant the red / green triangle indicator that appears to the right of the outcome

<img width="737" alt="screen shot 2018-09-25 at 4 30 22 pm" src="https://user-images.githubusercontent.com/11491365/49775155-0e57a700-fcac-11e8-86bc-eda2f6d7035b.png">

 -unparalleled-js
...

Ok, sorry for the misunderstanding.  I'll create a separate ticket for that and  move this one to the backlog for now since it's not a huge problem, and it may change in the redesign anyway.
 -adrake33

**Comment by antazoey** [comment]
https://github.com/AugurProject/augur-ui/pull/2549

**Comment by antazoey** [comment]
https://github.com/AugurProject/augur/pull/651

**Comment by bthaile** [comment]
This can be closed @Chwy5
