### ISSUE TITLE
JS error while awaiting trade confirmation (typically before Close button appears)

### ISSUE THREAD

**Issue by pqdeep** [AugurProject/augur#362]
https://drive.google.com/open?id=0Bx8T_M1UUwjQNVJoeGZKc0FJdEk

**Comment by tinybike** [comment]
That link is behind a permission barrier, and has some kind of download protection (I can't download the image).  Can you post it here?

**Comment by pqdeep** [comment]
checking
![index](https://cloud.githubusercontent.com/assets/13311619/13599937/12d27c4c-e526-11e5-803f-fc07cdc96ee7.jpg)

**Comment by joeykrug** [comment]
I used to get this, don't anymore, closing for now
