### ISSUE TITLE
Disputing Page: add text to Quick guide

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3624]
Text for disputing Quick Guide:
<https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=598%3A174459>

![image](https://user-images.githubusercontent.com/3970376/64829347-91869000-d591-11e9-8ffb-6bb095bbbe34.png)

**Comment by pgebheim** [comment]
Closed with #4662
