### ISSUE TITLE
Market List Filters - Copy Needed

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#3626]
Filter tooltips (Fees, Liquidity Spread, Invalid Markets) needs copy.
![image](https://user-images.githubusercontent.com/1683736/64869090-a81efc80-d60e-11e9-9d69-ad6aed8f5d34.png)

![image](https://user-images.githubusercontent.com/1683736/64869064-9b9aa400-d60e-11e9-9590-1789d94f9198.png)

**Comment by phoebemirman** [comment]
this has been done
