### ISSUE TITLE
Adjust notifications design for mobile

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#363]
https://app.zeplin.io/project/5b4e35b558ed7df75165a52e/screen/5ba01ff54799c73235e8b600

@tomhaile almost the same as the web version. Less padding between content and edges of the screen (left and right). Increase the area containing dimissAll/ Clear all" to 40x

Will optimize this better for mobile when more of the desktop design is done
...

maybe related to this https://app.clubhouse.io/augur/story/10652/android-firefox-initial-screen-is-pushed-down
 -phoebemirman
...

Not going to worry about this for MVP.
 -sharkcrayon
...

@serena  I didn't find mobile design for notifications. Need design or guidance. 
 -bthaile
...

@mattbullock  can you mock this up real quick? 
 -sharkcrayon
...

https://app.zeplin.io/project/5b4e35b558ed7df75165a52e/screen/5ba01ff54799c73235e8b600

@tomhaile almost the same as the web version. Less padding between content and edges of the screen (left and right). Increase the area containing dimissAll/ Clear all" to 40x

Will optimize this better for mobile when more of the desktop design is done
 -matt-bullock
...

@mattbullock are these mobile notification designs the most current? Any tweaks needed? This tix is a bit old. If all it good, move to `Frontend` project.
 -bthaile
...

these are the latest for the current design. They'll get adapted in the future for the new design that's in the works
 -matt-bullock

**Comment by joeykrug** [comment]
part of notifications reskin
