### ISSUE TITLE
Participation tokens redeem and buy alert

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#3638]
- Participation tokens redeem and buy

**Comment by joeykrug** [comment]
Status?

**Comment by phoebemirman** [comment]
should be ready for dev

**Comment by Chwy5** [comment]
i dont see an alert saying i bought PT after i purchase them

**Comment by phoebemirman** [comment]
<img width="399" alt="Screen Shot 2020-02-10 at 12 26 32 PM" src="https://user-images.githubusercontent.com/6775839/74187026-9adb5d80-4c00-11ea-86d8-065dd5281403.png">
are you sure the order went through? @Chwy5

**Comment by Chwy5** [comment]
this is fixed - closing
