### ISSUE TITLE
Turn on failed CI build notifications

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#3644]
See: https://docs.microsoft.com/en-us/azure/devops/notifications/howto-manage-team-notifications?view=azure-devops

Setting appears to be here: https://dev.azure.com/augurproject/augur/_settings/notifications?view=contents

**Comment by petong** [comment]
enabled, notifications should go to the following roles:

last changed by
requested by
requested for
deleted by 

will close when I can verify that they work
