### ISSUE TITLE
condensed: theme color changes

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3649]
update and condense the colors into one file and get parity with design. 

<https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=10970%3A308625>

![image](https://user-images.githubusercontent.com/3970376/65156666-17bd2f00-d9f5-11e9-8a1f-8cbacc85fcd9.png)

**Comment by JohnDanz** [comment]
https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-%26-Disputing?node-id=492%3A33668 --- dispute

https://www.figma.com/file/GKhft5ZOwuH3ANrupGNCLHUU/Market-list-page?node-id=968%3A12572 --- market list

https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=2704%3A981 -- accounts

https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7110%3A244314 -- portfolio

https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=453%3A59625 -- updated trading

commenting this for easier access to the newer mocks so I can walk through easier and replace colors

**Comment by pgebheim** [comment]
closed
