### ISSUE TITLE
categorical market created: previously created and then erased some options. but they're retained in title

### ISSUE THREAD

**Issue by pqdeep** [AugurProject/augur#365]
when I added and then erased entries of categorical options to the new market "Who will be the next signatory to the Schengen Agreeement to formally introuce border controls.." 
it didn't fully reflect the content changes. Items previously added stayed in the field. Autofill script needs to be checked

https://drive.google.com/open?id=0Bx8T_M1UUwjQQ3RuWk0zOGF6c3M

**Comment by pqdeep** [comment]
ah, just tried it again - happens when you insert the cursor back into the field and type anything (even just an empty space). Disrupts the autofill script.

**Comment by tinybike** [comment]
Fixed in 8f2fa8bfc0b65e6efe5d479659a8a49f000adc3c.
