### ISSUE TITLE
Open Orders has different headers.

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#365]
@serena What should the headers be in Potfolio Positoins for open orders. Are these correct? They are different from Market Trading view.

Porfolio Positions view
![screen shot 2018-06-04 at 2 27 11 pm](https://user-images.githubusercontent.com/11491365/49775002-87a2ca00-fcab-11e8-8ec4-15045329dd0d.png)

Market Trading view
![screen shot 2018-06-04 at 2 27 29 pm](https://user-images.githubusercontent.com/11491365/49775014-91c4c880-fcab-11e8-83d9-226bc10787f9.png)
...

@tomhaile This is how IDEO has it in the mocks. I think the difference comes from which headings are toggle-able on each page.  Open Orders is treated as a subsection of the toggle-able My Positions section on the Trading page, while it is its own toggle-able section on the Portfolio page.

This is good enough for now. Closing as won't fix.
 -sharkcrayon
...

Ok, we might want to fill in last price in the open orders section of portfolio positions then. 
 -bthaile
...

Actually I'm going to leave this open for a design revisit and move it to Peccary.
 -sharkcrayon
...

moving to `design`
 -bthaile

**Comment by joeykrug** [comment]
Resolved in new ui
