### ISSUE TITLE
display animated loading gif during process delays?

### ISSUE THREAD

**Issue by pqdeep** [AugurProject/augur#366]
there tends to be a protracted delay between the last modal status update and when the close button appears and also between when a comment is submitted and displayed.

In the case of the modal status pop-up, some people might interpret that as the app having stalled and close/reopen the tab/window. 

In the case of comments, it could lead to a lot of duplicate comments. Suggest adding an animated loading gif or something that assures people the request is in process.

**Comment by RonB7139** [comment]
agree, the wait times for various completions have been variable in length.....

**Comment by tinybike** [comment]
The transaction window added in 59f966ae8b6d24f221fec1ec166e75a53216429e is sort of a catch-all loading display; closing.
