### ISSUE TITLE
Research FAQ bot for discord

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#3669]
Problem
=

Many questions are repeated by the general public in various discord channels. Why create bespoke answers when we can not do that?

Current State
=

1. Member/Prospective member of the community will pose a question to our team. e.g. "Why is the dispute window 7 days?"
2. Member of community responds with answer.
3. Repeat without any knowledge of previous interaction

Solution
=

A robot friend who can take care of this. 

It should do the following things:

Upon addition to FAQ:
====
1. Monitor discord for mentions of a handle like "@domoarigato".
2. Clip the conversation around the mention to capture the original question along with permalinks.
3. File a PR of above contents against an FAQ (To be created) repo.

Upon a repeated question posed by community:
====

1. A mention that will tell the bot to post a link to the FAQ into the current channel.

Potential Problems
===
1. This isn't an entirely automatic process requiring humans to review generated PRs
2. Multiple PRs might be filed for same question in several channels

Improvements
===
1. Automate answering of questions. This might require Sentiment analysis but we might be able to get away with keyword matching
2. Provide a format to community member who answer many questions to simplify formatting concerns

**Comment by pgebheim** [comment]
https://discordbots.org/bot/441430430403526657
