### ISSUE TITLE
Open orders entry "processing" doesnt get removed after a transaction is finished

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#3672]
sell 1 share from existing order on the order book.  Order appears under position, but if i go to open orders it appears there as well, with the processing button spinning.![9-17d.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/e36ceddf-a597-44b0-8db0-91e6a80bf00f)

**Comment by joeykrug** [comment]
fixed
