### ISSUE TITLE
Trading on categorial markets processing forever

### ISSUE THREAD

**Issue by bconfortin** [AugurProject/augur#3673]
When trading on categorical markets, the trade remains "Processing..." forever. It seems to follow through (even with errors) when the page is refreshed.

The problem happens on these lines of code. The .find() method finds nothing, so it returns undefined.

get-outcome.ts

```javascript
case CATEGORICAL: {
  outcome.description = market.outcomes.find(mOutcome => mOutcome.id === outcome.id).description; // find isn't finding anything, so it returns undefined
  return outcome.description || "N/A";
}
```

[.find() documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)

> Return value:
> The value of the first element in the array that satisfies the provided testing function. Otherwise, undefined is returned.

**Comment by bthaile** [comment]
refreshed web browser and get these errors
![image](https://user-images.githubusercontent.com/3970376/65049904-2b509300-d92c-11e9-9e0a-caa4b17b97e8.png)

**Comment by bthaile** [comment]
refreshed again
![image](https://user-images.githubusercontent.com/3970376/65050036-60f57c00-d92c-11e9-8072-55f0fb3f14d4.png)

**Comment by Chwy5** [comment]
Not seeing this closing
