### ISSUE TITLE
Add indexes to getters to optimize queries

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#3686]
Steps required
===
1. Identify commonly used params or groups of params for given a pouchdB instance.
2. Add indexes to DB definition.

Note, this might require an expansion of the current index definition mechanism.

As a simple example in derived MarketDB given:

```typescript
    const request = {
      selector: {
        amount: { $gt: '0x00' },
        orderCreator: params.account
      },
    };
```

Will require indexes ['amount', 'orderCreator'].

**Comment by pgebheim** [comment]
This has been happening
