### ISSUE TITLE
Scalar market UI improvement

### ISSUE THREAD

**Issue by pqdeep** [AugurProject/augur#369]

**Comment by tinybike** [comment]
I'm not crazy about the current interface, either.  Am open to suggestions for improvement!

**Comment by Newportkiwi** [comment]
I'm working on some new concepts for the trading page. Sketches at this stage, but should have something to show this week (depending on baby situation).

**Comment by tinybike** [comment]
Not sure what @newportkiwi has in mind, but here's my sketch of a possible trading interface:
![img_20160423_151109](https://cloud.githubusercontent.com/assets/2637020/14771117/e8762b6c-0a35-11e6-89ae-10bb70e78378.jpg)

The accompanying order book would look something like this:
![img_20160423_151741](https://cloud.githubusercontent.com/assets/2637020/14771118/0b0dac18-0a36-11e6-8d0e-6d9e868c9b03.jpg)
