### ISSUE TITLE
market list: dropdown for market count is mis-styled

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3695]
this style needs to be fixed

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/7be8ef1e-73cd-44e3-8c8d-18cb1acfc231)

should look like
![image](https://user-images.githubusercontent.com/3970376/65148557-0ddfff80-d9e6-11e9-941a-932bf7854b85.png)

styles are in pagination.styles.less file

**Comment by bconfortin** [comment]
This is already fixed.
