### ISSUE TITLE
Server Error: error creating table

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#370]
![screen shot 2018-09-05 at 10 32 50 am](https://user-images.githubusercontent.com/11491365/49775564-78248080-fcad-11e8-9b78-e58aef32d647.png)

wellspenttimeToday at 3:15 AM
reported this screen shot,
OS: Windows 10
version: 1.4
...

Huh.... That doesn't make much sense!!
 -pgebheim
...

@tomhaile  -- this was reported in #issues correct?

I haven't seen any else report this, but it would be an error during migration -- seems like we'd get this a lot if it was gonna happen at all.
 -pgebheim
...

Yes, that was reported in #issues channel. 
 -bthaile
...

I only saw this reported once, no more instances of it have popped up. We might just need to keep an eye out.
 -bthaile
...

Ok, I'll set it to Unreproducible Bugs so we can still track it.
 -adrake33

**Comment by epheph** [comment]
@petong that image doesn't work for me?
