### ISSUE TITLE
AN failing with error: "market and outcome not found for shareToken"

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#371]
"market and outcome not found for shareToken 0x113e21c8f602a03218f9dc3dbe574f4893fa759a (0x2e3637153e3f5a906af750135b375f87847232de30c48bd89770327384b0b0aa"

is the exact error being seen. This could potentially be related to the problem being fixed by upgrading our blockstream version
...

Moving this to "Unreproducible Bugs" for now. Might be fixed by Scott's change, but we can keep an eye out for it.
 -adrake33

**Comment by epheph** [comment]
this just means data, somewhere, went missing. We now have a new table called "transaction_hashes", which might be interesting to see where/when the data went missing.
