### ISSUE TITLE
buy/sell order box dimensions shouldn't change as you submit an order

### ISSUE THREAD

**Issue by pqdeep** [AugurProject/augur#371]

**Comment by tinybike** [comment]
Can you elaborate?

**Comment by pqdeep** [comment]
When I entered a quantity to buy, or at some point after that, the box height and/or width changed in a way that looked clunky. I can redo the action and send a vid capture when either app.augur. or augur-dev.firebaseapp is back up. Can't access them at the moment.

**Comment by pqdeep** [comment]
This is what I'm referring to (happens as I start to input order quantity)

![1](https://cloud.githubusercontent.com/assets/13311619/13697138/b2ba4bb2-e76b-11e5-8afa-24b7de677d56.jpg)

**Comment by pqdeep** [comment]
Realize why it's being done (to accommodate additional content/fields), but think it could be more graceful and that either the length or width should stay fixed.

**Comment by tinybike** [comment]
Obsoleted by 59f966ae8b6d24f221fec1ec166e75a53216429e.
