### ISSUE TITLE
Disputing: disputeInfo has no tentative winning outcome identified

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3714]
categorical market with 8 outcomes, initially reported on but values are incorrect, no tentative winner and staking values are negative

```json
{
  "bondSizeOfNewStake": "699361165364583334",
  "disputePacingOn": false,
  "disputeWindow": {
    "disputeRound": "1",
    "endTime": 1574902800,
    "startTime": 1574816400
  },
  "stakeCompletedTotal": "349680582682291667",
  "stakes": [
    {
      "bondSizeCurrent": "-349680582682291667",
      "outcome": "1",
      "stakeCurrent": "0",
      "stakeRemaining": "-349680582682291667",
      "tentativeWinning": false
    }
  ]
}
```

**Comment by adrake33** [comment]
I tried submitting initial reports for all markets on docker:geth:pop, and I was unable to repro this issue. There were no negative numbers, and `tentativeWinning` was true for all of them, so closing this ticket.
