### ISSUE TITLE
clarify that this is play-money -- test ether and reputation (test) tokens

### ISSUE THREAD

**Issue by pqdeep** [AugurProject/augur#372]
https://drive.google.com/open?id=0Bx8T_M1UUwjQTUVRVXQzUVFMeEU

we've already received at least one inquiry from someone who thought it was a giveaway and asked how he could transfer it to his live eth address

account registration status update should say "received 5 test ether...*test* or *play* cash and Reputation *tokens*" for people who are completely new to all this

Very nice how hash details are hidden from view by default

**Comment by tinybike** [comment]
Added in 198fcfab0ffeb1aa4de24c9d629502a00be27a1d.
