### ISSUE TITLE
alerts: remove Order Placed alert when filled

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3730]
minor issue, when the order place by user fills an existing order (they match up) remove the `order placed` alert. We don't want to flood the user with a `Order Placed` alert for every `Filled` they get.

example of what we don't want:
![image](https://user-images.githubusercontent.com/3970376/65253782-dabe6e80-dac0-11e9-932a-870d34f92324.png)

need to differentiate by order details because these have the same id/txHash

**Comment by joeykrug** [comment]
fixed
