### ISSUE TITLE
condensed: market trading page Header

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3733]
Market Trading Page Header:

Designs in figma
<https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=194%3A2121> 

![image](https://user-images.githubusercontent.com/3970376/65272658-179c5c80-dae5-11e9-853a-0fb686c95465.png)

**Comment by JohnDanz** [comment]
copy icon is no longer a dropdown and it just copies a link to `cloudflare-ipfs.com/ipfs/xF......./#markets/?id=0xffff` (example)

**Comment by bthaile** [comment]
LOOK AT THIS!!

<https://www.figma.com/proto/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=218%3A23083&viewport=310%2C385%2C0.0645487979054451&scaling=min-zoom>

mocks for trading header

<https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=864%3A107092>
Design

**Comment by bthaile** [comment]
notes from John:

my plan was to make the properties into a more robust component, refactor the whole header to just use like properties reportingbar(think it's called headerbar atm)there's a div that can probably be a more robust component that can morph for reporting that does the creation and reporting time, it's just in market-header atm. then the action bar is the social sharing and back button,  that should also just live in that market title/details component section. Use grid, have the grid styles shift based on reporting state/market type to add scalar or not, etc keep ti as simple as possible in market-header imo


we need something similar to toggle-height classes for the drop downs imo, we can use display: relative to put it on top -- z-index needs to be adjusted for the overall header piece. just double hcekc that it doesn't block dropdowns from top bar and such
```
