### ISSUE TITLE
suggestion: add "average cost per share" below "order quantity" field and "cost" calculation

### ISSUE THREAD

**Issue by pqdeep** [AugurProject/augur#374]
below "order quantity" field and "total cost" calculation add a dynamic "average cost per share" calculation that also responds "live" to user input -- along with an explanatory tooltip as a pre-beta "band aid" before an order book chart is introduced post-beta. Head off confusion about the pricing process.

**Comment by RonB7139** [comment]
along these lines: although my "shares held" is displayed for (each) outcome, it's not clear what I paid for them and how much I stand to lose or gain from any result; therefore it is hard to understand my risk vs reward (which is the language of trading and betting...)

also, especially for more than 2 outcomes, it would be useful to know whether or not and how many complete sets I am long or short (is it a user action to B/S complete sets or are they automatically transacted when the set becomes complete; in which case is P&L clear related to that clear?)

**Comment by tinybike** [comment]
Included w/ new trading system.
