### ISSUE TITLE
markets that were in dispute when a fork happened don't show dispute info correctly

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#375]
<img width="974" alt="screen shot 2018-10-23 at 9 14 59 am" src="https://user-images.githubusercontent.com/11491365/49775505-49a6a580-fcad-11e8-8704-f032f19b332a.png">
...

@johndanz When a fork occurs, all non-forked markets have their tentative outcome reset to the outcome submitted in the initial report. Phoebe mentioned this might be happening due to the console errors we were seeing when a fork occurs (ch17599). Can you please work on fixing that issue and then see if this is still happening?
 -adrake33
...

or just related, i saw that disputeInfo doesn't have bondSizeCurrent set and maybe missing some other values. 
 -phoebemirman
...

@serena @mattbullock When a fork occurs, all disputed non-forked markets have their tentative outcome reset to the outcome submitted in the initial report. 

Currently, these disputed non-forked markets are not showing a dispute round, nor are they showing any outcomes. Should we still be displaying this information, even though the dispute round will never advance and the tentative outcome will never change in the current universe?
 -adrake33

**Comment by sharkcrayon** [comment]
We should show the information that will be relevant once disputing resumes in the winning child universe.

Whatever information is normally shown when markets have received an initial report and are waiting for their first dispute round should be shown at this point: the tentative winning outcome, Round 1, the dispute bond amounts for the other possible outcomes, etc.
