### ISSUE TITLE
mainnet: user @eeksskee doesn't get `claim` button on winning position

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#376]
User has winning position, owns winning NO shares in `0xd01ef4c1006deff19c20bafbb6cb7657ff160b0f` market.

Position says they have NO shares.

![screen shot 2018-10-08 at 10 02 45 am](https://user-images.githubusercontent.com/11491365/49774863-fa5f7580-fcaa-11e8-825b-f814662f15e7.png)

The positions back from augur-node look weird.

![screen shot 2018-10-08 at 9 43 27 am](https://user-images.githubusercontent.com/11491365/49774890-195e0780-fcab-11e8-93ff-b88daa631097.png)

transaction history for the market looks correct:

![screen shot 2018-10-08 at 9 48 14 am](https://user-images.githubusercontent.com/11491365/49774894-1fec7f00-fcab-11e8-90d6-2bbf834b7537.png)

user wants to keep public address private. contact me to get it.
...

After talking to Scott, user has already claimed, issues

Etherscan doesn't recognize SHARE token burns so tokens still show up in user wallets.

UI doesn't update correctly sometimes after claiming. Still confused about `numSharesAdjustedForUserIntention` and how to display them, see above user's position based on data coming back from augur-node.

This might it handled as a side-effect of working PL stuff. Is this true @pgebheim ?
 -bthaile
...

This will be fixed with Alex's changes since we will be basing all these token balances off of the actual balance tables which are affected by burns/transfers/etc.

This looks to be an artifact of the bug where the positions aren't tracked properly when you receive a share by creating a sell order for another share which you don't own and escrowing CASH.
 -pgebheim
...

@achapman -- Should work with the new code yah?
 -pgebheim
...

We could probably use the new tables for this data yea. In general I think we should get rid of the concept of `numSharesAdjustedForUserIntention` entirely. For now in the current UI for Binary/Scalar we could just check for No/Short shares and display them as negative and in categorical just show what people have.

The net qty for binary/scalar is redundant anyway and for categoricals it breaks (logically) as soon as someone makes a trade on an outcome they received shares of from shorting.
 -nuevoalex
...

I agree on that -- and was thinking of the same solution.

From getPL we can return the NO shares and the UI can look them up for the negative share values, or I can add that as a case to the getter for binary markets.
 -pgebheim

**Comment by adrake33** [comment]
Blocked by https://github.com/AugurProject/augur/issues/263

**Comment by Shrey33** [comment]
@petong can you tell me the reproduction steps ?

**Comment by bthaile** [comment]
User buys 1 no share in Yes/No market. The market ends and the No outcome is reported on then market finalizes. 

User doesnt see claim footer on market card. So user can’t claim their winnings. 

We have made small changes to hopefully address a few underlining issues. This issue is block waiting for another change.

**Comment by Shrey33** [comment]
@bthaile can you tell the impact ?

**Comment by bthaile** [comment]
Depends on if user was ever able to claim winnings. I’ve not heard of this issue being common. Because if this, I’d say medium.

**Comment by adrake33** [comment]
This should be working now that #263 has been fixed.

@bthaile Can you please confirm if this is fixed and close this ticket if that's the case?

**Comment by bthaile** [comment]
Ive not seen this issue since this issue. I’d say this is fixed.
