### ISSUE TITLE
Show better ui if trying to register a duplicate/existing username

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur#376]
Right now the progress bar hangs and no msg is shown.

Jack feel free to assign to me if you like - I put it in your queue just because you've been in and out of there recently.

**Comment by tinybike** [comment]
Assigned to you :)

**Comment by Newportkiwi** [comment]
I'll add some error messaging into the final design for the new sign-up and login pages (the ones with the pretty pictures)

**Comment by tinybike** [comment]
Don't you have something more important to do today, @Newportkiwi?  Whatcha doin on Github at a time like this??

**Comment by Newportkiwi** [comment]
Just taking a break outside, we're a few hours yet from any action.

**Comment by thinkloop** [comment]
Hey @tinybike, given that we are overhauling the login flow post launch, I aimed to solve this as simply as possible to get the job done. That said I had a rough time with it, and spent more time on it than I had hoped, mainly reverse engineering logic and how/when it effected state. At the end I couldn't escape all the side-effects, my solution works, but I'm not happy with how it's implemented: 338a8702f858e8a315903ca1e9945db04b4f4f1c

Would you mind verifying that it does not cause unintended behavior I did not account for. 

Also, this makes a great example relating back to our discussion the other day about component-state, would be great to chat about it again post-launch.

All the best.
