### ISSUE TITLE
Publish all NPM modules to NPM with Release Versions

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#3767]
**Is your feature request related to a problem? Please describe.**
I want to build something on the Augur SDK, but I don't want to or can't build from source.  I would like to just do `npm install @augurproject/sdk` and hit the ground running.

**Describe the solution you'd like**
```
cd packages/augur-sdk && npm publish --access public
```

**Describe alternatives you've considered**
None.  I **demand** NPM packages!

**Additional context**
I'm _really_ lazy.

**Comment by pgebheim** [comment]
I feel yah micah!

We'll publish the whole monorepo as things come to launch.

**Comment by pgebheim** [comment]
Re-opening 'cause Micah convinced me to start an epic for Launch Planning.

**Comment by pgebheim** [comment]
We'll use `lerna publish` to publish all the parts of the mono-repo for this.

**Comment by justinbarry** [comment]
In preparation we need to merge multiple modules together and put them all under the `@augurproject` org namespace.

Prospective package list:
===

@augurproject/artifacts
@augurproject/core
@augurproject/sdk
@augurproject/tools
@augurproject/types
@augurproject/utils
@augurproject/ethersjs-provider

These need to be moved/merged.
===
@augurproject/logger
blockstream-adapters

These can be merged together and then into the sdk module.
===

contract-dependencies-ethers
contract-dependencies-gsn
contract-dependencies

These should NOT be published
===
@augurproject/test 
@augurproject/ui
