### ISSUE TITLE
windows auto update doesn't update percentage.

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#377]
![screen shot 2018-08-20 at 9 39 29 pm](https://user-images.githubusercontent.com/11491365/49774791-cdab5e00-fcaa-11e8-81af-bf0592f9bc90.png)

this screen sits there for a while the disappears then a message box pops up saying it's installing.

The progress bar never moves past 0.
...

@justinbarry Can you confirm if this is fixed?
 -adrake33
...

Marking as Ready for Development. @justinbarry If this is no longer an issue, feel free to close.
 -adrake33
...

Looks like this is a known issue. Will need to decide how to handle this. 

See: https://github.com/electron-userland/electron-builder/issues/3264
 -justinbarry
...

Maybe for windows just have an animation of downloading and down show percentage. 
 -bthaile
...

@tomhaile What about https://www.npmjs.com/package/electron-progressbar#indeterminate-progress-bar?
 -justinbarry
...

Yea, that sounds good to me. 
 -bthaile
...

FYI, just upgraded augur-app from 1.6.0 to 1.6.1 and there was percentages and the progress bar updated correctly. looks good.
 -bthaile
...

This needs to be tested on a Windows machine with Docker before it can be released.
 -adrake33

**Comment by justinbarry** [comment]
Code is here:

https://github.com/AugurProject/augur-app/tree/justinbarry/ch15634/windows-auto-update-doesn-t-update-percentage

I cannot test because I do not have a windows machine that I can run docker on.

**Comment by Romain-P** [comment]
@nuevoalex ? I still have this issue
