### ISSUE TITLE
Adjust Order Books for Canned Markets to Pass Filter

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#3771]
The order books for the canned markets currently wont pass the liquidity filters because the orders are too small, so any profits would be offset by TVOM (time-value of money) and gas fees.

To make markets show in the UI we need to adjust the order books in the canned markets, by multiplying the share values of all trades by 100.

We wanna do this for 2/3 of the markets in the canned data set:
https://github.com/AugurProject/augur/blob/9b0a5eafca2bd8c6f9efc5efd245d5c92b3ebc6e/packages/augur-tools/src/flash/data/canned-markets.ts

**Comment by bthaile** [comment]
this ticket has been addressed closing
