### ISSUE TITLE
Collapse Market trading page: collapse/expand center column

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3789]
2 configurations for middle column of market trading page

### 4 or less outcomes (invalid is last): 
show up to 4 outcomes in the outcome list. 
scalar markets displays 2
binary markets displays 3
 * categorical markets with over 3 display 4 total. Invalid being the last. 
 * charts are shown and open/filled/positions are shown
 * no expandable/collapsible arrows for charts or outcomes
 * open/filled/positions section does have expandable/collapsible arrows. Charts gets covered if open/filled/positions section is expanded.

### 5 or more outcomes
 * on load categorical market with 5 or more outcomes. Outcomes list is expanded to show all outcomes with Invalid being last. 
 * chart section is closed
 * open/filled/positions section is open
 * user expands charts, outcomes list collapses to show 4 outcomes (invalid is last) and outcomes list is scrollable. 
 * when outcomes list is collapsed and scrollable the page behaves like  a categorical market with 4 or less outcomes.

**Comment by Chwy5** [comment]
For Binary, scalar, and category 4 or less....
We show the outcome section, the chart and the open/filled/position section
the outcome and chart should not have the expandable/contrasting arrows....Only the Open/filled/positions section should have expandable arrows (to make bigger), this should cover the chart, if applied.  If hit again goes back to normal size

For Category 5 or greater....When a user first opens to that market (should happen everytime going to that market) we show every outcome, and the Open/filled/Positions section...(the chart section is closed up.  If the user expands the charts, the chart should open up (so we would still display 4 outcomes), and also the Open/filled/positions section is still visible. The outcome section, at this point should become scrollable.....So at this point it looks like a cat4 or binary market described above, except the outcome section is scrollable

**Comment by Chwy5** [comment]
open/filled/positions would be scrollable as well
