### ISSUE TITLE
Bookie SDK

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#379]
As a market maker, I want to make a profit by giving bettors a better experience and consistent liquidity.

As a bettor, I want quick, cheap fee, well priced options available to take a position in a market.

This ticket is just a placeholder for now. If we decide to do this, we'll need to break this into lots of smaller tasks. Micah created a Google Doc for what needs to be done for the Bookie SDK: https://docs.google.com/document/d/1yzR2rMSRT6VW7si-STOYfdMQz268Uae_0qfF6EkAfNw/edit
...

This should really be called like a bookie SDK imo, it's far more [reading the spec above] than an AMM
 -joeykrug

**Comment by justinbarry** [comment]
@pgebheim Should this be a "[ROADMAP]"?

**Comment by joeykrug** [comment]
Also should have option to show markets created only by a certain creator

**Comment by pgebheim** [comment]
Taking a simpler path on this one.

1) Ship betting UI
2) Make sure dev experience for all the Augur core functionality is good
