### ISSUE TITLE
Toast / Bell Alerts: Verification

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3792]
list all toasts and verifications here so we can check them off.

### toast
 - [x] Migrate V1 rep to V2
 - [x] Trading: Filling existing order: Filled
 - [x] Trading: Open order getting filled: Filled

### bell alerts
 - [x] Migrate V1 rep to V2
 - [x] Trading: Adding Pre-Liquidity: Order Placed
 - [x] Trading: Adding Open Order: Order Placed 
 - [x] Trading: Filling existing order: Filled
 - [x] Trading: Open order getting filled: Filled
 - [ ] Gnosis Safe: Dai Account Set-up 
 ~- [ ] Approval: Dai Approval~
 - [x] Market Creation: Market Created
 - [x] Trading: Cancel Order: Order Cancelled
 - [x] Reporting: Designated Reporting: Market Reported
 - [x] Reporting: Adding prefilled stake: Pre-Filled Stake Added
 - [x] Reporting: Disputing: Market Disputed
 - [x] Reporting: Open Reporting: Market Reported
 - [x] Reporting: Participation Tokens: Buy Participation tokens
 - [x] Reporting: Participation Tokens: Redeem Participation tokens
 - [x] Trading: Claiming Proceeds: Claim Winnings
 - [x] Reporting: Redeeming REP: Redeem REP staked

**Comment by cillianhunter0** [comment]
@bthaile there is no toast for REP migration

**Comment by matt-bullock** [comment]
Closing this. Created a separate ticket for the one that is remaining
