### ISSUE TITLE
implement insufficient ether user messaging

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur#38]
this may take several forms (modal, form validation, etc.) but for the alpha, we should have some basic user messaging for actions that require ether (add market, sending assets, buy/sell shares, etc.)

a modal could also have help text for mining or requesting it.

**Comment by carver** [comment]
Since we want a no-account mode, this seems a good place to check if there is an account at all.

**Comment by scottzer0** [comment]
yea.  i was about to augment this issue with that. 

there really is a slightly larger and very related issue of components knowing if there is an unlocked, account credential available for sendTx actions (buy/sell, faucets, add markets, etc.) and the low ether state.

**Comment by scottzer0** [comment]
duplicate of #38
