### ISSUE TITLE
Canceling open orders does not clear open orders in state

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#3807]
Steps to reproduce:

1. Report on a market where the current user has open orders, push time to end of dispute window. Market should now be in Awaiting Finalization reporting state
2. Go to Account Summary page, find the notification that says the resolved market has open orders
3. Click the View Orders button and click Cancel All in the modal that pops up.
4. Go to the market's trading page and note that the order book is now clear, but the Open Orders section still shows the orders

Expected behavior: The Open Orders section should not show any orders

**Comment by bthaile** [comment]
this has been addressed. 

issue was user open orders state wasn't updated. The reducer lacked the logic to remove orders only add them.
