### ISSUE TITLE
Use undefined to indicate value hasnt been set

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#381]
Null is a value in the UI, undefined is easier to work with. Use undefined for all augur packages to indicate no value has been set.

**Comment by phoebemirman** [comment]
i talked to @epheph about this ticket and he said this wouldn't work because undefined is not valid json so can't use that in augur-node

@bthaile was original creator of this. was there something else you were thinking of with this?

**Comment by bthaile** [comment]
well, if it's not valid json then it can't be sent over the wire. so this wouldn't be a good path forward for v1. v2 we can keep in mind the differences between null and undefined, but no systemic change is needed at this time, closing this task
