### ISSUE TITLE
Suggestion: add market statistics

### ISSUE THREAD

**Issue by btcre** [AugurProject/augur#381]
Suggestion: Place the "sign out" on the right corner, so you won't always accidentally click it.
and also add Market statistics page (total markets, volume, fees, etc)
Cheers :)

**Comment by tinybike** [comment]
Sign out moved in 0ef1f0d3bdaed45185c096ed7c465ca3b1a11d82.

**Comment by priecint** [comment]
What statistics we want to / can display?

I'd suggest:
- open interest,
- last trade price,
- price change since yesterday (absolute and percentage),
- lifetime and today volume (shares traded),
- lifetime and today price extremes (min/max),
- number of participants (traders)

**Comment by joeykrug** [comment]
Interesting, so there are two types of statistics here:

1) Statistics on a per market basis:
```- open interest,
- last trade price,
- price change since yesterday (absolute and percentage),
- lifetime and today volume (shares traded),
- lifetime and today price extremes (min/max),
- number of participants (traders)``` as suggested above sounds good

2) Statistics for the entire system:
  - total markets created
  - total volume
  - total value of shares traded: shareValue

Both are useful

**Comment by tinybike** [comment]
Moved to CH
