### ISSUE TITLE
Suggestion: Add Similar Markets and Other Author's markets 

### ISSUE THREAD

**Issue by btcre** [AugurProject/augur#382]
Just like in Android app, once you select the market, at the bottom list some of "Similar markets" and if the Author has other markets it should have the "Other Author's Markets"
This way the markets are promoting each others.

**Comment by joeykrug** [comment]
tags now allows this --- click on tag at top of a market page and you see similar markets, other author's markets is cool

**Comment by tinybike** [comment]
Moved other author's markets issue to CH
