### ISSUE TITLE
fix inefficient load market info call (for volume and placing new order, for example)

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#383]
...

added related tix ch6815 this tix would get fixed indirectly, leaving open until that happens.
 -bthaile
...

@johndanz Just a reminder for when you start working on this ticket -- please try to break it up into smaller tasks once you get more info from Paul/Scott.
 -adrake33

**Comment by bthaile** [comment]
this isn't needed anymore because of new SDK structure. closing
