### ISSUE TITLE
suggestion: leaderboard

### ISSUE THREAD

**Issue by pqdeep** [AugurProject/augur#383]
user performance rankings by adjustable criteria (volume, gains, etc.) over adjustable time horizons.
Make it easy for everyone (including lurkers) to find the hidden sages.

**Comment by joeykrug** [comment]
I don't think this is actually possible to do in a decentralized manner in any fashion where it doesn't take hours to load.  Should be a separate thing from main ui and main ui could display it or something if someone makes one
