### ISSUE TITLE
update create-market to remove extraInfo

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#384]
Extra info is going away because it's a relic that we don't need now with augurnode. @epheph is updating the augur-node to help processes this better in his work with adding `scalarDenomination`.
...

To be clear, extraInfo can go away from the perspective of the UI, augur.js will be the packager, and augur-node will be the unpacker. 
 -epheph
...

Not sure if i should do this? The PR in augur.js makes me think this is on hold based on @tinybike's statement, @epheph @sprinkle Post MVP or no? https://github.com/AugurProject/augur.js/pull/284
 -JohnDanz
...

Moving to Peccary for now; maybe good to do but don't want to get into this kind of reorganization for MVP.

...

:thumbsup: 
 -sharkcrayon
...

@epheph Is this done?
 -bthaile
...

My understanding of this ticket is that nothing changes in augur-node, extraInfo is still passed along. It was just that the UI was doing a bunch of stuff in the UI code that was more appropriate for augur.js to deal with. This ticket is not done, we decided to punt for MVP
 -epheph

**Comment by bthaile** [comment]
closing
