### ISSUE TITLE
Review Mobile Functionality

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#385]
Go through the Augur UI, testing various bits of functionality and making issues in CH for design or function problems that arise:

 - Viewing / Searching Markets
 - Market Display
 - Trading
 - Universe selection
 - Viewing Reporting pages
 - Disputing
 - Viewing Portfolio Pages
 - Claiming market proceeds
 - Claiming reporting proceeds
...

 We should wait to do this until we get through a lot of the redesign. 
 -sharkcrayon

**Comment by joeykrug** [comment]
dupe of mobile cleanup epic
