### ISSUE TITLE
Additional Details should be auto-expanded

### ISSUE THREAD

**Issue by housemobile** [AugurProject/augur#386]
Often could contain important information regarding the bet and people shouldn't miss it because they don't expand it manually

**Comment by tinybike** [comment]
Resolution field should be shown prominently.  Tags are in a breadcrumb style (i.e., quite prominent) on augur-dev.  IMO it's best for extraInfo to be hidden at first (or, if displayed, shown in some non-obtrusive way).

**Comment by tinybike** [comment]
No longer relevant.
