### ISSUE TITLE
Notifications:  dispute notification card for dispute market

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3880]
Notification Card
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/b096d63e-6215-4d3c-a475-0604b9740666)

opens disputing form but market is in Open Reporting.
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/222e62e3-8b2c-49bb-b2bc-b600df32edd0)

**Comment by pgebheim** [comment]
@bthaile Is this still in progress or done?

**Comment by Chwy5** [comment]
What is that message? Is that something we are using?

Dispute round 0 for the market xyz is ending soon?

**Comment by bconfortin** [comment]
> What is that message? Is that something we are using?
> 
> Dispute round 0 for the market xyz is ending soon?

@Chwy5 I believe so. Have you seen it anywhere? Should appear only for the market creator when a dispute is near its end, from what I can gather.

**Comment by Chwy5** [comment]
I have never seen that message before...at least about dispute rd 0

**Comment by bconfortin** [comment]
@Chwy5 Do you think that's an interesting message to show?

**Comment by Chwy5** [comment]
No I think it is confusing....

I think what happened on this is the Designated reporter, received that message (that they needed to report) and that the time for him to report was about to expire.  Then he didnt report and the market went into Open reporting.

I think the user should have gotten an initial message that they need to report with a countdown timer.  If that timer runs out we can gray out the notification and if they hit view we can tell them time has expired and the market has moved into Open Reporting to be reported on.
