### ISSUE TITLE
P/L display does not make sense (see attached image)

### ISSUE THREAD

**Issue by RonB7139** [AugurProject/augur#391]
![pl issue](https://cloud.githubusercontent.com/assets/16419551/13543861/75fd68e0-e23d-11e5-832f-8bc364581cf1.png)

**Comment by tinybike** [comment]
Maybe I'm mis-using the terms.  What the terms in the display mean are: "Profit/Loss" = total amount made or lost in this market.  Since you've only bought shares, you're at -100% because you haven't cashed any of them out yet.  "Unrealized P/L" = total amount made or lost in this market + the amount of cash you'd get if you sold all your shares right now at market price.

**Comment by RonB7139** [comment]
Unrealised PL may make sense (can't do the math easily) as I should have substantial profit based upon buying at ~17 and current price of ~97 but the term Profit/Loss when used in conjunction with "Unrealised P/L indicates the former is displaying either only Realised P/L, which in this case should be 0 or sum of realised and unrealised which in this case should be identical...so depending on how you are calc'ing PL i.e. only realised or as sum, then "Profit/Loss" should be better explained ("Total Profit/Loss" or "Realised Profit/Loss" accordingly).

It would not be conventional to describe Profit/Loss as you've suggested

And, should not be quoted as percentage which is way less useful than the nominal amount of profit/loss...i.e. I dont care if I am up 100% if its only $1 (and if we know the percentage then we know the dollar amount)

**Comment by tinybike** [comment]
So, what is the definition of "Realized P/L" then?  I'm just using the sum of inputs and outputs.  (In this case, 2 inputs and 0 outputs = 100% loss.)  If this is incorrect, how should I calculate Realized P/L?

**Comment by tinybike** [comment]
I can change it to an absolute amount display instead of a percentage!  I assumed (incorrectly I guess) that percentage would be more useful but amount is actually easier :)

**Comment by RonB7139** [comment]
realised PL is the result of only netted buys and sells i.e. in the same amount of buys and sells which cannot be impacted by future changes in the market price or settlement, unrealised PL is the amount of PL that would become realised if the open positions were closed at the current market price...total PL (sum of the two) can change obviously until the market is resolved

example: if I buy 20 shares at 40, and sell 12 shares at 60 (and the last trade is 60) and the maket isnt resolved yet, I would expect a realised PL of 240 (I made 20 points on 12 shares) AND an unrealised profit of 160 (8 shares not yet closed but "in the good" by 20 points x 8 shares)

**Comment by tinybike** [comment]
Makes sense; fixed in a3c5bb696a8ea39fbfcd081f9e2ddf8a4dd4b4ca.
