### ISSUE TITLE
log removals for market state changes

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#392]
marketState: awaiting_net_window
if it is rolled back
should be
marketState: awiating_designated_report, removed: true (more like, this is the new state, due to a removal)
...

@epheph is this task still needed or desired?
 -bthaile
...

Technically, yes. It's a very subtle issue that could happen under rare circumstances: If a new fee window happens on a block that gets re-org'd. we will move the things too soon to their new state, and the block that is re-org'd to might not have a timestamp that moves the fee window forward until the NEXT block. The impact is minor and unlikely, but still is a flaw
 -epheph
...

Look into if this is still true.
 -epheph

**Comment by epheph** [comment]
New Augur-node rollback strategy might avoid this issue altogether.

**Comment by adrake33** [comment]
Closing this since it's a very small edge case and Alex said it doesn't need to be done.
