### ISSUE TITLE
Onboarding - getMarkets getter should also provide category OI totals on meta object

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#3924]
![image](https://user-images.githubusercontent.com/1683736/65887719-69a67300-e36c-11e9-8584-f5164ae55788.png)

Landing page needs to show Market Counts AND OI for all primary categories.

Update LandingPage to use the ```getCategoryStats``` getter.

**Comment by pgebheim** [comment]
@nuevoalex Thoughts on how to do this? This is across all the markets so we either need to load them all and accumulate or do a derived db sorta thing where we keep category info accumulated.

**Comment by nuevoalex** [comment]
Yea another derived DB is probably the right way to do this.

**Comment by andrewdamelio** [comment]
#3971 will address this
