### ISSUE TITLE
Move shared tools (eslint, babel, tslint, prettier) and base configs into tools package

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#393]
This was originally a task in story #8185.

**Comment by pgebheim** [comment]
@justinbarry -- I think this problem was solved in a different way.

Re-open and lets schedule outside of this epic if you disagree.

**Comment by justinbarry** [comment]
@andrewdamelio It is possible that this can be done by moving the eslit/prettier rc files to the root on the mono repo.

**Comment by pgebheim** [comment]
Totally
