### ISSUE TITLE
Market Card changes

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3935]
Market Card changes:

1. on market listing page: Viz changes only. market cards remove market state 
market types are `open`, `in reporting` and `resolved`

2 Market listing page remove market type:
`YesNo`, `Categorical` and `Resolved`

3. Disputing page, leave market card state `In-reporting`

stuff to remove on market card:

![Screen Shot 2019-09-30 at 1.22.30 PM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/c5a66027-4e52-4521-a6b8-0fc5c071cec3)

![Screen Shot 2019-09-30 at 1.23.29 PM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/a47a098e-280a-43cd-b116-d6b9c2dbc7d2)

![Screen Shot 2019-09-30 at 1.25.13 PM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/3881fcea-435f-4807-9d07-396c19bce294)

example of disputing page:

![Screen Shot 2019-09-30 at 1.25.39 PM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/9dc7dacb-8208-4408-8a9e-8e287eb8faf1)![Screen Shot 2019-09-30 at 1.22.30 PM.png]

**Comment by gitstart-augur** [comment]
@bthaile we think changes for this issue has been added in on master already:

https://github.com/AugurProject/augur/blob/4b06e4074dbd2022936cf9f746bb2487c3964d21/packages/augur-ui/src/modules/market-cards/market-card.tsx#L213

**Comment by bthaile** [comment]
This ticket has been finished in another effort.
