### ISSUE TITLE
Replace the progress panel/modal with a "pending transactions" page

### ISSUE THREAD

**Issue by RonB7139** [AugurProject/augur#396]
perhaps use typical default "show last 10 transactions" with a clickable link to "show more"

**Comment by tinybike** [comment]
I think @thinkloop's "Pending transactions" implementation (https://augur2-thinkloop.c9users.io/) is the way to go here -- also can replace the widely-hated progress panel/modal!  Double win.

**Comment by RonB7139** [comment]
ticket really refers to archive i.e. most recent/last 24 hours/last
week/last month and also archive of deposits/withdrawals

also love the pending  re-work of pending transactions

**Comment by tinybike** [comment]
I think we'll have to add an extra event log to the deposit/withdrawal contract to get the history for those.  However we have a full record of trades (since those are already recorded in the `updatePrice` log) so that should be straightforward to add!

**Comment by tinybike** [comment]
Replaced in 59f966ae8b6d24f221fec1ec166e75a53216429e.
