### ISSUE TITLE
awaiting finalization markets need to show under resolved in portfolio and account

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#3966]
<img width="855" alt="Screen Shot 2019-10-01 at 1 10 37 PM" src="https://user-images.githubusercontent.com/6775839/65996763-ec066400-e44c-11e9-96d8-b9929b543029.png">

**Comment by bthaile** [comment]
Prob nust need to add awaiting_finalized to same conditional as check for finalized
