### ISSUE TITLE
Reporting a second market causes problems

### ISSUE THREAD

**Issue by housemobile** [AugurProject/augur#399]
I am trying to report on the 5 markets currently available to report on.

Process as follows:

1) report on event 1. hit submit. 

2) click on reporting tab at top.

3) click report on event 2.

4) site either does nothing or entire app.augur.net pages refreshes

**Comment by tinybike** [comment]
I haven't been able to reproduce this specific bug, but I pushed a few reporting-on-more-than-one-market fixes in 4a92472458ef1232ed5e9ba74b53cf25f5419ca2.  Would you mind re-trying this?

**Comment by housemobile** [comment]
it seems to be fixed now. problem was happening yesterday.

**Comment by tinybike** [comment]
Okay, closing for now.  Feel free to re-open if this happens again.
