### ISSUE TITLE
Onboarding - Connect / Hardware Wallets

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#3997]
- Add Edge, Ledger and Trezor to the new Connet modal

**Comment by pgebheim** [comment]
As per #1434 -- We also need to make sure that we can auto-detect the various derivation paths people may have used when setting up their Ledger.

**Comment by pgebheim** [comment]
And re: #817 may need to handle difficulties with using the trezor interfaces

**Comment by joeykrug** [comment]
Do we even need this? Can't ledger and trezor users just use metamask?

**Comment by MicahZoltu** [comment]
I have run into many users that don't like using their hardware wallet through MetaMask.  Not sure if they make up a significant portion of potential users though.  Also, historically there have been a _ton_ of bugs with hardware wallets and MM to the point where I have given up on trying to get my Ledger to work with MM.  So while _technically_ they may be supported, I don't know that they are pragmatically supported.

**Comment by joeykrug** [comment]
really re MM? I've used ledger w/ mm a ton recently and 0 issues

**Comment by MicahZoltu** [comment]
https://github.com/MetaMask/metamask-extension/issues?q=is%3Aissue+ledger+is%3Aopen

I have had no end of issues, and it appears I'm not alone.

**Comment by Chwy5** [comment]
User will need to use MM
