### ISSUE TITLE
Tour text is blurry (sometimes)

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#400]

**Comment by thinkloop** [comment]
I'm not able to repro - any hints on how often, or if anything possibly triggers it? Which browser/OS? @joeykrug have you seen blurriness since you disabled cleartype?

**Comment by joeykrug** [comment]
Nah I haven't

**Comment by tinybike** [comment]
Chrome/Ubuntu.  It seems to only happen when I'm zoomed out 2x (i.e., ctrl+0, ctrl+-, ctrl+-) -- if I'm at normal zoom it doesn't happen.
![tour-blurry-3-9-2016](https://cloud.githubusercontent.com/assets/2637020/13633929/1df96e38-e5a7-11e5-8f9f-c05666ec4aa0.png)

**Comment by tinybike** [comment]
Follow-up thought: if this is now only happening for me, and only at a weird zoom, this may not be too important to fix.  Downgrading this to "In the Hole" unless others start complaining about this...
