### ISSUE TITLE
Market Creation: issue creating markets with long titles and additional details

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4003]
add a long title and additional details see if review form renders correctly

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/6af8acac-5ec0-4412-9175-ecce066c4ab7)

**Comment by phoebemirman** [comment]
review step looks fine with long title and details
<img width="959" alt="Screen Shot 2019-10-24 at 12 42 50 PM" src="https://user-images.githubusercontent.com/6775839/67519534-e111ae80-f65b-11e9-87af-4ee7d614afe5.png">
<img width="915" alt="Screen Shot 2019-10-24 at 12 42 45 PM" src="https://user-images.githubusercontent.com/6775839/67519536-e111ae80-f65b-11e9-94ed-fadb69f3fca7.png">
