### ISSUE TITLE
Document augur.rpc properties on docs.augur.net

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#401]
The following augur.rpc properties should be documented on docs.augur.net:

augur.rpc.constants
augur.rpc.errors
augur.rpc.eth
augur.rpc.clear
augur.rpc.startBlockStream
augur.rpc.getBlockStream
augur.rpc.getCoinbase
augur.rpc.getCurrentBlock
augur.rpc.getGasPrice
augur.rpc.getNetworkID
augur.rpc.getLogs
augur.rpc.getTransactionReceipt
augur.rpc.isUnlocked
augur.rpc.sendEther
augur.rpc.packageAndSubmitRawTransaction
augur.rpc.callContractFunction
augur.rpc.transact
augur.rpc.excludeFromTransactionRelay
augur.rpc.registerTransactionRelay
augur.rpc.setDebugOptions
augur.rpc.WsTransport
augur.rpc.publish
augur.rpc.sha3

**Comment by bthaile** [comment]
not needed for v2
