### ISSUE TITLE
Tour should fail gracefully

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#401]
If the tour tries to load when you're on "expired markets" (so that the tour element isn't on the page), the UI throws this error:
```
The element for this Shepherd step was not found .market-row .description
```
crashing the page.

**Comment by thinkloop** [comment]
Factored out tours into their own files, added var checks for existence of dependent vars, added try/catch to fail gracefully in unforseen circumstances:  9e6eda758e4a387b741c7e08281dd883abcc3c2f

**Comment by tinybike** [comment]
This still happens:
![reporting-tour-error-3-8-2016](https://cloud.githubusercontent.com/assets/2637020/13627629/8c1b2be4-e580-11e5-9d7c-66eae3f380fe.png)

**Comment by thinkloop** [comment]
@tinybike have any repro tips? I tried a bunch of things to get into that state but wasn't able to.

**Comment by tinybike** [comment]
Does not seem to be happening any more.
