### ISSUE TITLE
Market Creation Failure

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#4023]
Create a custom market. I was doing a cat 4 market ( 3 outcomes + invalid), used 1 for fee.  after signing MM boxes market creation says failed.

![10-3c.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/1b678941-40dd-487f-8fa6-acdc79928c8f)

![10-3d.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/ea9bad1f-2bdb-4206-941e-0655ab7a8fa8)

![10-3e.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/ddff6708-e07d-4f24-97a9-95a28d9a9a44)

Etherscan link says sorry unable to locate this tx hash....and failure onportfolio pg happens immediately...also retry fails again

**Comment by joeykrug** [comment]
fixed
