### ISSUE TITLE
Reporting selection issue

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#403]
1) Select one of the possible answers, i.e. no, yes, indeterminate
2) Wait a second or two
3) It's now unselected and must be reselected before you can submit your report

This is an intermittent bug, it only happens every so often on my machine, however, another person has reported the same issue on reddit.

**Comment by tinybike** [comment]
Fixed in 1abeee2d151fb0ccc7f561bd282e405f8cc66a3f.
