### ISSUE TITLE
Notifications Verification List

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4038]
Notifications:

 ### Report On Markets,
 - [x] notification if user is designated reporter

 ### Resolved Markets Open Orders,
 - [x] notification if user has open orders in resolved market

 ### Finalize Markets,
 - [x] notification if user's market needs to be finalized

 ### Markets In Dispute,
 - [x] notification if market they have interacted with is in dispute

 ### Claim REP from Reporting/Disputing and Participation Tokens with fees,
 - [x] notification if user has REP to claim (includes participation tokens and fees)

 ### Unsigned Orders,
 - [x] user has pre-liquidity orders

**Comment by JohnDanz** [comment]
Found an issue with finalize, looks like it's filtering the notification by markets that are already finalized, not awaiting finalization -- Another odd thing was seeing the finalize notification with a 2nd account that hadn't interacted with the market in question at all. 

also it appears unsigned Orders is not creating a notification

I don't see a notification if I'm the DR on a market that is in DR.
