### ISSUE TITLE
other account reports show up on same computer

### ISSUE THREAD

**Issue by housemobile** [AugurProject/augur#404]
I made my reports with one account. I logged out.

I signed in to another account.

The reports I made with the first account were there. I changed the reports. I logged out.

I signed back in to the first account. I could now see the changes.

**Comment by housemobile** [comment]
Cash, rep, ether, and the Portfolio and My Markets tabs remain different between accounts, but the Reporting tab is linked.

**Comment by tinybike** [comment]
Fixed in 4858d66287acf94dd8c2f5e8727d50824ce49591.
