### ISSUE TITLE
Disputing: Event emitter issue (in slow disputing)

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4043]
Here is the scenario, for disputed market doesn't update reportingState:

1. market is in CrowdsourcingDispute
2. dispute to fill the dispute bond in slow disputing
3. UI requests the market and gets CrowdsourcingDispute as reportingState
4. Switch tabs in disputing, just to make sure and a new getMarkets request is made for markets in CrowdsourcingDispute and the disputed market is returned
5. Switching tabs to request markets in AwaitingNextWindow and no markets come back.
6. refresh UI
7. disputed market has the correct reportingState.

**Comment by robert-e-davidson3** [comment]
It's a race condition.

I added a bunch of logging. When the race condition manifests itself, here's the order of execution:

1. Derived DisputeDB begins upserting its docs into the database.
2. The processing of the relevant log, DisputeCrowdsourcerCompleted, is executed in its entirety and returns a log to be bulk-upserted into the derived MarketDB. The method is called `processDisputeCrowdsourcerCompleted`.
3. Derived MarketDB begins upserting its docs into the database.
4. The processing of the timestamp from the new block* is executed up until it begins upserting docs. The execution at this point includes a database query of the Market logs. The method is called `processTimestamp`.
5. The bulk upserts for DisputeDB and MarketDB finish processing.
6. The timestamp upsert finishes processing.

Explanation:

The `processTimestamp` method depends on changes made in `processDisputeCrowdsourcerCompleted`, specifically the update to `nextWindowStartTime`. That update isn't made until `processTimestamp` has begun executing, specifically after it makes a database query.

When the race condition manifests, `processTimestamp` finishes upserting *after* `processDisputeCrowdsourcerCompleted` finishes upserting, thereby overwriting the correct `reportingState` that was derived from the DisputeCrowdsourcerCompleted log.

When the race condition does **not** manifest, this is the order of events:

1. Derived DisputeDB begins upserting its docs into the database.
2. The processing of the relevant log, DisputeCrowdsourcerCompleted, is executed in its entirety and returns a log to be bulk-upserted into the derived MarketDB.
3. Derived MarketDB begins upserting its docs into the database.
4. The processing of the timestamp from the new block begins execution. It doesn't yet get to the database query, let alone upserting.
5. The bulk upserts for DisputeDB and MarketDB finish processing.
6. The timestamp processing does the database query and fully upserts without interruption.

We definitely shouldn't be processing the timestamp until the logs have finished processing. It looks like we just get lucky that usually we begin upserting the log changes before querying for them in the block processor.

\* I didn't verify that it's from the new block but the timing is right. I definitely didn't push time and the timestamp it reports is the same as the previous block's.

**Comment by bthaile** [comment]
this ticket should have been closed when code was merged. closing
