### ISSUE TITLE
SDK Performance Notes

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#4047]
Observations on performance
==

Running things in the same thread as the UI on mobile safari seems to increase speed significantly.

Index creation is slow
====
1. Need to reduce the number of indexes and/or delay index creation.
2. Possible we only use indexes on derived dbs and use map/reduce for all 

Intial Sync is slow
===
1. Check block numbers before rolling back on bulk sync (I cannot find the ticket I filed for this).
2. Need to use gang'ed up requests for bulk sync. We are making a request per per event per chunk.

Connectors
===

Not strictly a performance issue but we do need to figure out how to use the metamask connection in the ui. If for some reason we decide to go single threaded then this becomes trivial.

**Comment by justinbarry** [comment]
Actual data is forthcoming.

**Comment by pgebheim** [comment]
Questions:
 - Can you point to anything that says making a LOT of new indices is worse than just indexing more data?
 - Is there evidence that this makes syncing faster for everything?
 - Is the solution with replicating to disk still viable?

**Comment by justinbarry** [comment]
Filed this with pouch: https://github.com/pouchdb/pouchdb/issues/7928

**Comment by justinbarry** [comment]
@pgebheim For items 1 & 2 see: https://augurproject.github.io/pouchdb-perf/

**Comment by pgebheim** [comment]
This isn't an actionable ticket so we should turn it into one.

**Comment by pgebheim** [comment]
Major thoughts with this have been fixed with Dexie Re-write and #4245  -- closing issue.
