### ISSUE TITLE
Go to a different page, pending transaction window [say for a trade] disappears

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#406]
Instead of disappearing perhaps it should persist.  Or as another person suggested, perhaps there should be a whole pending transactions tab for all pending tx at the top or maybe even as a dropdown that you can click at the top in the white space at the right side of the screen that'd slide down a few inches from the top-right hand side of the screen.

**Comment by bp360** [comment]
Came here to log this issue - glad its in the hole! - i agree it should be persistent across page navigation - I like the idea of a log off-screen - where the most recent status is up top (just like it appears now) but I could expand it up to see a log of all past transaction summaries.

**Comment by tinybike** [comment]
Fixed in 59f966ae8b6d24f221fec1ec166e75a53216429e.
