### ISSUE TITLE
Onboarding: migrate V1 REP to V2

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4061]
Need modal design

<https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=2342%3A542>

![image](https://user-images.githubusercontent.com/3970376/66273912-687ab780-e83e-11e9-9e5d-a2806c695345.png)

**Comment by cillianhunter0** [comment]
You'll find that here @bthaile (visual design updated): 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=9706%3A6055
