### ISSUE TITLE
Forking: contract call failures

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4066]
Need to investigate, seems there is conditions not met so user can't perform these actions:

### issue 1
forking has already started, user needs to release their REP so they can migrate:
 * Can't release REP staked on market. markets are non-forking market
```typescript
    contracts.redeemStake.redeemStake(
      reportingParticipantsContracts,
      disputeWindows
    );
```

Note: `disavowCrowdsourcers()` needs to be called on all market before user can release all their REP. It would be advantageous if MarketsInfo had a property to indicate if the market's crowdsourcers have been disavowed already. Then the UI would know if 2 transactions are needed or just one per market.

### issue 2
fork has resolved there is a winning universe, market that haven't expired can't be migrated:
 * Can't migrate markets where their endTime hasn't passed.
```typescript
    market.migrateThroughOneFork(payoutNumerators, description);
```

### ~~issue 3~~ 
(has been addressed)
not forking related, but on the way to a fork, more info on ticket
 * Once markets move to slow disputing their reportingState doesn't update
<https://github.com/AugurProject/augur/issues/4043> existing ticket

**Comment by nuevoalex** [comment]
Were we ever able to find any exact repro steps for 2? I have yet to be able to actually repro a tx failure for market migration based on endTime alone.

**Comment by nuevoalex** [comment]
Also for issue 1, what method is being called? `disavowCrowdsourcers` I assume? If so is there nay other information or does this seem to fail for all markets?

Is it the gas estimation that fails or the actual transaction? On Kovan or local or both?

@bthaile

**Comment by nuevoalex** [comment]
@bthaile I really need something more for issue 2. I've tried to repro this in automated testing through a large set of scenarios and never been able to produce a failure as long as the migrating user has new universe REP.

Can you provide either more detail about the market, account, and universe(s) OR exact minimum repro steps?
