### ISSUE TITLE
Says no trades on my pnl page

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#407]
![hmmm](https://cloud.githubusercontent.com/assets/5925937/13624868/91b29910-e577-11e5-858b-b11ffa1c64a7.PNG)

Shouldn't it say trades 1 since i've traded once?

**Comment by tinybike** [comment]
The trading info lags the other stuff in the UI -- it's stored in logs, which are loaded after all the on-contract market data is loaded.  If you wait 10-20 seconds, the trading info should appear -- but if you waited a while and it never showed up then that's a 'nother story and I'll get to debugging it...

**Comment by joeykrug** [comment]
Ok so it still does this no matter what

**Comment by joeykrug** [comment]
Even if i do a second trade it still stays that way

**Comment by joeykrug** [comment]
did a third trade and now it says trades 1

**Comment by tinybike** [comment]
Fixed in 18c0abbcba27f506210475af61b621474847b1ca.
