### ISSUE TITLE
Gnosis Safe - SDK hookup

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#4073]
![image](https://user-images.githubusercontent.com/328965/66953966-55bd6b00-f014-11e9-8e74-fba7445edc89.png)

###  SDK (plugging the bits)
SDK should be able to detect, on userSync(?), if the provided address has any ETH/DAI.

  - [ ] IF YES:  SDK should either CREATE or RESTORE the user's Gnosis wallet and return this wallet address to the UI.*
  - [ ] IF NO: SDK should continue along with the provided wallet.

*The gnosis safe relayer polls and will create the safe once funds are at the address. New gnosis safe accounts with no funds won't be deployed, so the SDK should return the future deployed safe address.

**Comment by andrewdamelio** [comment]
Related: https://github.com/AugurProject/augur/pull/4125

**Comment by justinbarry** [comment]
```
- on login check if there is a safe associated with the account in our safe registry
- if not request safe
- get back safe address
- sign safe address
- stored safe address and corresponding sig in localstorage
- ask user to fund address
- once address is funded the safe is created by the relay and will be auto-registered in our safe registry contract
- on login check if there is a safe associated with the account in our safe registry
- returns safe, use safe
```
