### ISSUE TITLE
Add data for outstanding shares to Markets page and as Markets sort option

### ISSUE THREAD

**Issue by RonB7139** [AugurProject/augur#408]
current system makes "shares outstanding" a key indicator of "tradability"...meaning how much liquidity a market has and how much any share purchase will move the current price...markets with greater shares outstanding offer better opportunity for trades at reasonable prices and is a very useful criteria to determine which markets to trade.  Save me a click.

**Comment by tinybike** [comment]
"Volume" is displayed as part of the general markets display now.  (Sorting UI isn't live in 2.0 yet, but volume is one of the options there, as in the 1.x UI!)
