### ISSUE TITLE
cant login from different computer

### ISSUE THREAD

**Issue by housemobile** [AugurProject/augur#409]

**Comment by tinybike** [comment]
This is a fundamental limitation of storing the accounts in localStorage, unfortunately.  There are a couple ways to make accounts more portable -- beyond simply exporting to a json file, then importing on your other computer -- and those are on the to-do list: https://github.com/AugurProject/augur.js/issues/48

**Comment by tinybike** [comment]
This is a fundamental limitation of storing the accounts in localStorage, unfortunately.  There are a couple ways to make accounts more portable -- beyond simply exporting to a json file, then importing on your other computer -- and those are on the to-do list: https://github.com/AugurProject/augur.js/issues/48
