### ISSUE TITLE
Move all icons to discrete files

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#409]
Split the icons out into separate files that are imported into an `index.js` file.
...

De-prioritized this.

...

Also would like to request that all icons also be functions so that their inclusion is `<Icon />` rather than `{Icon}` (assuming that isn’t already done prior to this task’s work)

**Comment by JohnDanz** [comment]
we are moving away from this idea as it's easier to put all the icons in one spot and have only one import in the common folder.
