### ISSUE TITLE
Market Cards: Styling and spacing changes

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4093]
Changes to tighten up classic view. need to maintain market cards looking "good" at least "decent" on condensed and expanded.

![Screen Shot 2019-10-08 at 11.00.46 AM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/b3ba72d8-fa60-4894-b937-18f7ff3c3ae4)
1 spacing see last description in tix description
2 spacing see last description in tix description
6 remove market reporting state and market type. leaving in-reporting sub state

![Screen Shot 2019-10-08 at 11.03.38 AM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/16972d85-343d-45a5-9851-496d0755b15d)

3 tighten up so that the component that has total volume and open interest is 96 px should leave about 12px from `interest` to the dividing line.
4 spacing see last description in tix description
5 align outcomes so they line up with market title. they are fine on mobile. desktop needs to be fixed they were recently changed to go to the edge. 

7 outcome hover outline color should be `#3C3B43`
![image](https://user-images.githubusercontent.com/3970376/66414713-8facc280-e9bf-11e9-9344-7cc3e3ca7222.png)

spacing :
![image](https://user-images.githubusercontent.com/3970376/66414113-62abe000-e9be-11e9-97d5-61f3f57dc4af.png)

make minor adjustments to make the spacing consistent between elements on the card.

**Comment by pgebheim** [comment]
Was merged
