### ISSUE TITLE
add svgs next to reporting phase

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#410]
https://app.zeplin.io/project/5b4e35b558ed7df75165a52e/screen/5b900736180c125baa49dcb8

need svgs from @mattbullock
...

[reportingIcon.svg](https://api.clubhouse.io/api/attachments/files/clubhouse-assets/57ba59e0-be53-4e07-8817-724a7edbc3e0/5bb3ba7d-8bdb-4e43-b1b2-9422951f180c/reportingIcon.svg)
 -phoebemirman
...

[openIcon.svg](https://api.clubhouse.io/api/attachments/files/clubhouse-assets/57ba59e0-be53-4e07-8817-724a7edbc3e0/5bb3ba83-e4af-4976-8c5b-3a47ef95d06f/openIcon.svg)
 -phoebemirman
...

[closedIcon.svg](https://api.clubhouse.io/api/attachments/files/clubhouse-assets/57ba59e0-be53-4e07-8817-724a7edbc3e0/5bb3ba88-201f-4087-8fef-ba8673b92109/closedIcon.svg)
 -phoebemirman
...

@mattbullock I talked to @phoebemirman more about this, and she said you think it makes sense to just wait for the redesign and not bother with these current SVGs.

If you want to close this ticket since it's part of the new redesign, feel free.
 -adrake33

**Comment by joeykrug** [comment]
closing per OP
