### ISSUE TITLE
Add positions / open orders section

### ISSUE THREAD

**Issue by housemobile** [AugurProject/augur#410]
helpful to know which of my portfolio predictions are ending soon. may want to hedge or double down.

**Comment by housemobile** [comment]
probably would be helpful to allow for sort of My Markets in same way to so mass market creators can sort all their markets as they see fit.

**Comment by tinybike** [comment]
Sharing @thinkloop's AURC screenshot here to show how this page will be laid out:

![pasted image at 2016_07_11 02_37 am](https://cloud.githubusercontent.com/assets/2637020/16722909/c2679f72-46fe-11e6-80e2-5f5e7ae51b5a.png)

**Comment by tinybike** [comment]
Combined with #643
