### ISSUE TITLE
Market Creation, Information added/changes

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4102]
https://docs.google.com/spreadsheets/d/1TqZ0ePiJKn3F8wYh8WRJ139vSIRpgZzfz6RboW44zxM/edit?usp=sharing

Text for market creation. This ticket is to go through the document and update market creation text. 

See the mocks for locations of external links
<https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=419%3A952>

**Comment by phoebemirman** [comment]
this has been completed
