### ISSUE TITLE
Dev Text: Learn More links

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4103]
Figure out what is needed for the `Learn More` 
 - [ ] for reporting form Invalid outcome
 - [ ] participation token section
 - [x] market creation
 - [ ] forking banner

searching the code base for `learn more` will give you the places some just link to docs.augur.net. 
Is that correct?

**Comment by phoebemirman** [comment]
addressed here https://github.com/AugurProject/augur/issues/4846 and https://github.com/AugurProject/augur/issues/4848
