### ISSUE TITLE
Have (i) for each of items in create market

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#411]
Have information popups / mouse overs for headers in the create market forms.

outcome
Resolution Source
Designated Reporter
Expiration Date
no show bond
validity bond
Settlement Fee
Initial Liquidity
denomination
...
...

This is a good idea, but punting it to Peccary for now to minimize scope creep...

...

:thumbsup:  Totally agree!
 -sharkcrayon
...

@serena I'd like to get design for tooltip or description of the create market fields.
 -bthaile

**Comment by joeykrug** [comment]
Should do this for trading too

**Comment by pgebheim** [comment]
@matt-bullock @cillianhunter0 @Chwy5 -- Do you believe the new market creation designs approach the problem of communicating whats happening enough that this ticket is closable?

**Comment by Chwy5** [comment]
I believe it does, there might be 1 or 2 random spots that need an (i) but we can close this ticket

**Comment by joeykrug** [comment]
Is this done for trading?

**Comment by Chwy5** [comment]
I believe so... @matt-bullock please confirm
 only thing i think still needs to be completed with them is changing eth to dai for Total amount escrowed in the order ticket and Total Cost (shares) in Open Orders
