### ISSUE TITLE
Global Chat: orbits in-browser chat server

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4113]
<https://github.com/orbitdb/orbit> 
<https://github.com/orbitdb/orbit-web> 

Figure out where the orbits core/web stuff needs to be set up. Can it be in SDK or does it have to be on the UI side. This will spin up orbit-db and set up orbit-core for the UI.

**Comment by robert-e-davidson3** [comment]
A little concerning, from the repo: 

> Status: Hold. Work on Orbit Chat is largely in other repositories, at the moment. This may change in the future.

> NOTE! Orbit is still more or less experimental. It means Orbit is currently not secure, APIs will change and clients can break over time. If you come across problems, it would help greatly to open issues so that we can fix them as quickly as possible.

**Comment by bthaile** [comment]
closing this ticket we are going with external hosted orbits and using iframe
