### ISSUE TITLE
Error when creating markets and adding market liquidity - changing Total order value when all 3 fields are populated

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#4124]
**Describe the bug**
Changing the value `total order value` causes an error of 

```TypeError: Cannot read property 'maxPrice' of undefined```

**To Reproduce**
1. Create binary market
2. set quantity to 10, press tab
3. set limit price to .5, press tab
4. change the value of `total order value`

results in an error page

**Comment by Chwy5** [comment]
I just retested this:  

Add Quantity 10
Add Price .5>>>>makes total order value 5.0
Then manually change Total Order Value to 4.0 and hit trade.....I get filled at 5.0 (this is not correct)

Price should remain constant in this scenario.....If a user changes the total order value (when all fields are populated) the quantity should adjust

**Comment by Chwy5** [comment]
So when changing the total order value in my example above....or starting with total order value first....we should change the quantity and then trigger the error (about quantity)...so would look like this....

![2-19orderticket](https://user-images.githubusercontent.com/41301809/74862330-f2bd4700-5319-11ea-9e83-f27d657bd1e1.jpg)

**Comment by Chwy5** [comment]
fixed - closing
