### ISSUE TITLE
Categories should be normalized in the derived dB 

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#4146]
Category case shouldn't matter when requesting category stats, Sports and sports should return merged data.

Category case also shouldn't matter when returning cateogry related data. A request for sports markets should return both Sports and sports.

![image](https://user-images.githubusercontent.com/1683736/66661751-89178880-ec15-11e9-804e-7c95244a8571.png)

**Comment by tinybike** [comment]
Is changing this in the [getter](https://github.com/AugurProject/augur/blob/master/packages/augur-sdk/src/state/getter/Markets.ts#L765) sufficient, or is it better for everything to be lowercased when the logs are read in (i.e., in state/db/MarketDB.ts)?

**Comment by nuevoalex** [comment]
It should be done in the market DB processing of the log so the data in the DB is normalized
