### ISSUE TITLE
Dispute tabs not updating the quantity

### ISSUE THREAD

**Issue by bconfortin** [AugurProject/augur#4149]
At the disputing page

I had 4 markets in dispute and one of them moved to "awaiting next dispute". The tab numbers (quantity) didn't update.

`Currently disputing (4) | Awaiting next dispute (0)` should be `Currently disputing (3) | Awaiting next dispute (1)`.

However, when you change tabs or refresh the page, these numbers are updated accordingly.

![Tabs not updating](https://user-images.githubusercontent.com/10351013/66667599-c6861100-ec29-11e9-98db-558582943f5d.png)

**Comment by bthaile** [comment]
old ticket, looks to have been fixed
![2020-04-11 08 41 56](https://user-images.githubusercontent.com/3970376/79045417-9c111280-7bd0-11ea-9c8e-b9d8d6719cc3.gif)

**Comment by matt-bullock** [comment]
yeah not seeing this. closing
