### ISSUE TITLE
Can't backspace after typing non-numbers into buy/sell form

### ISSUE THREAD

**Issue by housemobile** [AugurProject/augur#415]
Sometimes you can but more often than not it locks up. 10-- causes it to lock up and you have to highlight all and delete. Letters, symbols cause problems.

**Comment by priecint** [comment]
Can't reproduce

**Comment by housemobile** [comment]
It's happening again on a scalar market. 
What will be the ETH price in USD by March 31st end-of-day?

I typed `0  on the under 35.11 

It wont let me backspace. Need to highlight all and delete.

**Comment by tinybike** [comment]
Does this happen for you on https://augur-dev.firebaseapp.com as well as https://augur.net?  Asking b/c the most recent changes have only been pushed to augur-dev so far!

**Comment by housemobile** [comment]
Was using augur.net
