### ISSUE TITLE
Alert bar from filters settings at the top of the market list pg needs an (x) to be closed added

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#4159]
![Screen Shot 2019-10-12 at 11.55.34 AM.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/55d26a1e-a756-4c01-8198-979c7b33c75d)

Need to add an (x) in the top right of this bar...so user can dismiss it if they choose

------------------------------------------
tasks:
1. add X so user can dismiss the alert
2. store in state (on loginAccount on new `settings` property) that the user dismiss this alert.
3. check loginAccount state before showing this alert

**Comment by bthaile** [comment]
@Chwy5 

an X wasn't in the original design we can make the bar dismissible. What is the behavior you want?
1. dismiss forever?
2. dismiss only for the user's session
3. dismiss only for that search  (it would come back every time they nav away and back to market list page)

#2 is the direction

**Comment by bconfortin** [comment]
Have to add the button for another banner as well.
