### ISSUE TITLE
Implement Accessibility Guidelines

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#416]
Figure out what the UI is going to do about accessibility throughout the app.
...

Design is needed to make sure accessibility guidelines are baked in.
 -bthaile

**Comment by joeykrug** [comment]
This is mostly an ongoing thing, doesn't really fit anywhere / should be considered *as* the designs are being done. Fwiw, I tested the UI in greyscale and it looks + feels pretty good, nothing out of place atm [for colorblind]
