### ISSUE TITLE
Review: Forking Sequence for Traders

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#417]
I want to check whether traders are given clear enough direction when it comes to universe selection after a fork has been initiated.
...

seems to be a design research task.
 -bthaile

**Comment by Chwy5** [comment]
@joeykrug does this need to be its own epic

**Comment by pgebheim** [comment]
@cillianhunter0 @Chwy5 -- Closing this as a specific task, but recommend adding this to any user testing we do with the new forking flows.
