### ISSUE TITLE
React Refactor: UNSAFE methods `alerts-view.tsx`

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4172]
convert `UNSAFE_` methods and use `useState` and `useEffect` and `useRef` and convert to functional component

`augur/packages/augur-ui/src/modules/alerts/components/alerts-view.tsx`

```typescript
  UNSAFE_componentWillUpdate(nextProps: AlertsViewProps) {
    if (this.props.alertsVisible && !nextProps.alertsVisible) {
      const { updateExistingAlert, alerts } = this.props;
      alerts.forEach(alert => {
        updateExistingAlert(alert.uniqueId, { ...alert, seen: true });
      });
    }
  }
```

**Comment by gitstart-augur** [comment]
@bthaile I want to use Alert interface on modules/types for typing "alerts" prop, but currently Alert interface contains only "id" prop and doesn't contain "uniqueId" prop. Walking through alert reducers/actions, I can see that we only use "uniqueId" for checking for existing alert and in most cases there's same value for both props. Could you please recheck and confirm that, so we can remove the "id" prop.

**Comment by gitstart-augur** [comment]
Total Cost for PR: **50** Credits
