### ISSUE TITLE
React Refactoring: convert `error-container.tsx`

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4174]
convert UNSAFE_ methods and use useState and useEffect and useRef and convert to functional component.

`augur/packages/augur-ui/src/modules/auth/components/common/error-container.tsx`

```
  UNSAFE_componentWillUpdate(nextProps, nextState) { 
...
}
```

**Comment by gitstart-augur** [comment]
Total Credit Cost: 50
