### ISSUE TITLE
add copy user feedback

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4179]
need user feedback when they click the copy icon. Use the same tooltip popup that on-boarding uses.

<https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=394%3A2380>

![image](https://user-images.githubusercontent.com/3970376/66723962-6a67ec00-ede5-11e9-8da0-e28444ba8c90.png)

![image](https://user-images.githubusercontent.com/3970376/66723981-bc107680-ede5-11e9-8ee5-d22578b7f918.png)

**Comment by joeykrug** [comment]
done
