### ISSUE TITLE
Reporting/disputing: initial report on market,  but doesn't update reporting state

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4180]
on kovan:

1. market in open reporting
2. initially report (with pre-filled and without pre-filled)
3. transaction is successful. 
4. no markets in disputing page
5. no market on in-reporting market listing page that are in `crowdsource disputing)

successful initial reporting transaction on kovan:
<https://kovan.etherscan.io/tx/0xcd1265fbc57f573ee87c7587be1c444edff0937d238607c5f6492e501549aad8> 

initial report transaction but market still shows open reporting. Even after refresh

**Comment by nuevoalex** [comment]
What reporting state does the market have when this occurs?

**Comment by bthaile** [comment]
Initially reported on markets in “Open reporting”.
Also reported on a designated_reporting state.

Each had the same issue, of not updating reporting state

**Comment by nuevoalex** [comment]
Is that where it appears in the UI or is that the reporting state returned by the SDK for the market info?

**Comment by bthaile** [comment]
The reporting state from sdk, UI. I checked in web console, UI stores the MarketsInfo in redux. state.MarketInfos[“marketId”]

**Comment by nuevoalex** [comment]
This is likely the same issue we had with similar problems where the timestamp handling function has a race condition with the generic even handler and the initial report reporting state gets overwritten. We should make the lock for updating occur in the `handleMergeEvent` function so that no such overwriting can occur.

**Comment by robert-e-davidson3** [comment]
I wasn't able to repro with an automated test.

Here's the code, which passes:
```
  test.only(':getMarkets : reporting', async () => {
    const universe = john.augur.contracts.universe;
    const actualDB = await db;

    const marketContract: Market = john.augur.contracts.marketFromAddress(markets['yesNoMarket1']);

    await actualDB.sync(john.augur, CHUNK_SIZE, 0);
    let market: MarketInfo = (await api.route('getMarkets', {
      universe: universe.address,
    })).markets.filter((marketInfo) => marketInfo.id === marketContract.address)[0];
    expect(market.reportingState).toEqual(MarketReportingState.PreReporting);

    // Get past the market time, into when we can accept the initial report.
    await john.setTimestamp(new BigNumber(market.endTime + 1));

    await actualDB.sync(john.augur, CHUNK_SIZE, 0);
    market = (await api.route('getMarkets', {
      universe: universe.address,
    })).markets.filter((marketInfo) => marketInfo.id === marketContract.address)[0];
    expect(market.reportingState).toEqual(MarketReportingState.DesignatedReporting);

    // Now go forward a day, into Open Reporting.
    const currentTime = await john.getTimestamp();
    await john.setTimestamp(currentTime.plus(1 * 60 * 60 * 25));

    await actualDB.sync(john.augur, CHUNK_SIZE, 0);
    market = (await api.route('getMarkets', {
      universe: universe.address,
    })).markets.filter((marketInfo) => marketInfo.id === marketContract.address)[0];
    expect(market.reportingState).toEqual(MarketReportingState.OpenReporting);

    const SOME_REP = new BigNumber(6e25);
    await john.repFaucet(SOME_REP);

    // Do the initial report, creating the first dispute window.
    const payoutNumerators = getPayoutNumerators(market, 'invalid');
    await john.doInitialReport(marketContract, payoutNumerators, '', SOME_REP.toString());

    await actualDB.sync(john.augur, CHUNK_SIZE, 0);
    market = (await api.route('getMarkets', {
      universe: universe.address,
    })).markets.filter((marketInfo) => marketInfo.id === marketContract.address)[0];
    console.log(market);
    expect(market.reportingState).toEqual(MarketReportingState.CrowdsourcingDispute);
  });
```

**Comment by nuevoalex** [comment]
The issue with the automated tests is that the update is occurring via a sync, so `processTimestamp` isnt even being called and there is no code path where a race could occur. Instead the test would need to be operating in blockstream mode if it were to attempt and repro this.

**Comment by robert-e-davidson3** [comment]
Kovan hasn't been deployed since the first fix got into master so it's likely that there is no longer a bug. This is supported by my inability to repro locally. When possible, we'll redeploy to kovan and retest.

**Comment by robert-e-davidson3** [comment]
Verified fixed on new Kovan deploy.

Before reporting:
```
state.marketInfos["0x8aacbE11Eaed9e4922fDC58A26A6e7DcAA1d3Ac8"].reportingState
"DesignatedReporting"
```

After reporting:
```
state.marketInfos["0x8aacbE11Eaed9e4922fDC58A26A6e7DcAA1d3Ac8"].reportingState
"CrowdsourcingDispute"
```

(Tom verified that the original issue also happened in DesignatedReporting state.)
