### ISSUE TITLE
Current Wallet SDK issues

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#4181]
```
AS OF~~~
"fortmatic": "1.0.0",
"@portis/web3": "2.0.0-beta.53",
"@toruslabs/torus-embed": "0.2.6",
```

- Chrome ✅
- Opera: ✅
- Safari (13)  ✅
- Firefox ✅
- Brave ⚠️*

*Portis/Torus require the user to accept cookies on Brave
**Torus has pop-ups issues, pop-ups may need approval

### Tor.us
- OAuth pop-ups getting blocked
- Permissions menu doesn't save user state, asks for permissions every time
- Session cookies don't persist in all cases (tab closed)
- ~~On Brave, getting the below errors in regards to localStorage~~
- ~~On Brave, getting the below errors in regards to sessionStorage~~
- On Signup flow, we shouldn't load the previous session 
- ~~On Safari (Mobile/Desktop) had to disable the permissions modal since its getting blocked on Safari.~~

- iOS 12 Error 

### Portis

- <s>Permission window doesn't block/wait for users' selection </s>

- <s>On Portis login, the wallet remains open until the user closes it</s>

- On Portis load we get ```https://api.portis.io/auth/is-dapp-authorized 401```

- <s>On Brave, getting the below errors in regards to localStorage</s>

- On Signup flow, we shouldn't load the previous session

- ~~On desktop Safari getting the following errors on login~~

- iOS 12 Error

**Comment by joeykrug** [comment]
Status of this?

**Comment by andrewdamelio** [comment]
In progress. Wallets have been updated. Next step is to re-test above scenario and bring up issues.

**Comment by joeykrug** [comment]
bump

**Comment by andrewdamelio** [comment]
Closing this issue. #6389, #6700 are still open and relate.
