### ISSUE TITLE
Make the Close Market process less bad

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#419]
![close-market-button-ugly-3-9-2016](https://cloud.githubusercontent.com/assets/2637020/13658005/7bc53b10-e628-11e5-82bf-a37e3062928b.png)
Sweet mother of god...!

**Comment by thinkloop** [comment]
We can easily make the button smaller and give it more spacing, but do we want to rethink how this whole part works? There is no messaging on what it means to close a market, no lead-up that this eventually needs to be done, no communication of costs, no placement in a continuous work-flow, etc.

Is all that part of this issue, or for after beta?

**Comment by tinybike** [comment]
I agree re: this workflow needing to be improved.  Updated this issue's wording.  Any suggestion on how to do this?  It's mostly jarring right now b/c you have to navigate to the markets to close them.  Maybe there should be prompts on the reporting page for this?

(Doesn't have to be done for beta, but definitely would be a welcome improvement.)

**Comment by tinybike** [comment]
Update: closeMarket can be made totally passive (b/c of refund).  Hurrah!

**Comment by tinybike** [comment]
Badness removed in 02ade0e01241a1689f6ac68214ed21f7e61b71a6.
