### ISSUE TITLE
Synchronize Gnosis Ganache container accounts with our tool defaults

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#4197]
We need to provide our default addresses some of that sweet sweet ether inside the container when run. Can be done by passing in the account and a balance to the cli.

See: 
https://ethereum.stackexchange.com/questions/38738/setting-the-initial-balance-of-an-account-in-ganache-cli
https://github.com/gnosis/safe-relay-service/blob/master/docker/ganache/Dockerfile

**Comment by petong** [comment]
done
