### ISSUE TITLE
Forking: SDK allow UI to change universe 

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4205]
There are issues where getters assume universe based on contract addresses like ` const universe = augur.addresses.Universe; `

need to add method to Augur.ts so the UI can set the universe address.

**Comment by pgebheim** [comment]
It doens't look like we have the problem described above, but there are still issues switching forks. Closing this in lieu of #7110 (moved into RC1 epic/milestone)

**Comment by pgebheim** [comment]
This is the real issue, #7110 is no longer a problem.

**Comment by pgebheim** [comment]
Closing!

UI is passing in universe everywhere. There was a getter bug fixed in #7207
