### ISSUE TITLE
Top Predictions = All Predictions

### ISSUE THREAD

**Issue by housemobile** [AugurProject/augur#421]
Unclear why it says Top Predictions. It shows all the predictions available for that particular market. Perhaps remove 'Top' or only show top 2 predicted options.

**Comment by tyche78** [comment]
Yes, this one always bothered me a bit. I suggest showing only the top two in multi-choice markets, and only the top one in binary markets (with "predictions" gone singular).

_Leading _prediction(s), rather than top prediction(s), also appears slightly cooler to me.
