### ISSUE TITLE
Proxy eth/augur connections via localhost

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#421]
To minimize the amount of configuration the UI must do at run time we will serve traffic vis a local proxy.

Using a package like this https://github.com/nodejitsu/node-http-proxy

And code like this:
```
const proxy = new HttpProxy({ws: true});
this.app.use('/augur-node', (req, res) => { proxy.web(req, res, {target: 'http://localhost:9001'}); });
this.app.use('/ethereum-ws', (req, res) => { proxy.web(req, res, {target: config.ethereum_http}); });
```
...

This could be an easy win to support Safari, Brave and Fire fox. These web browsers have stricter CORS requirement than Chrome.
 -bthaile
...

I'll setup proxies for these endpoints
/augur-node
/ethereum-http
/ethereum-ws

that means we we will pass http://127.0.0.1:<port>/<above endpoint> to UI.

 -bthaile
...

@tomhaile Can we talk about this when you get back?
 -justinbarry
...

Yes we can, this origianlly was your idea. I just agreed. 
 -bthaile

**Comment by adrake33** [comment]
Closing since this won't be useful for v2 anyway.
