### ISSUE TITLE
split out local addresses and local upload-block files from addresses.json and upload-block file

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4221]
create local-addresses.json that gets merged in to addresses when SDK spins up. 

.gitignore local-addresses.json
.gitignore local-upload-block....

this way only deployed testnet addresses are in addresses.json

**Comment by robert-e-davidson3** [comment]
We may be better off doing https://github.com/augurproject/augur/issues/2978 instead. Then we can get rid of `addresses.json` and also unblock the smoke test. That doesn't help us with `upload-block-numbers.json` however our local testing just uses `0` anyway so it doesn't make changed to that file.

**Comment by robert-e-davidson3** [comment]
I went ahead with this strategy instead of using CREATE2 because this can be done much faster.
