### ISSUE TITLE
NSFW Prevention

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#423]
Add a custom search to search google images:
https://developers.google.com/custom-search/docs/tutorial/introduction

Only allow market images from there 

Per https://developers.google.com/custom-search/docs/structured_search#overview have safesearch strict and rights reuse as qualifications

Per https://developers.google.com/custom-search/docs/xml_results#filtering-results and https://developers.google.com/custom-search/docs/element#supported_attributes, image_filter should be 1

This google image search thing allows api calls to make it so you can only get images free to use - so that should be on 100% of the time to prevent dmca issues

In addition to that the ui would have an option to toggle sfw off if you wanted
Market creators when making a market would by default have safesearch on, and they could turn it off if they wanted but it'd tell them "only users with sfw turned off will be able to see your image"

It's not 100% ideal to have to use google as the image source but allowing people to upload their own doesn't prevent illegal things like child porn or dmca violations [whereas google w/ free use on does by default prevent both those issues] 

And there's also no sfw filters as in javascript libraries [and google w/ safesearch on does this, probably better than any 3rd party filters if any did exist anyway]

Market creators should be encouraged to not use images for actual speculation/questions but rather as an enhancement to the market.  Image hashes should be stored somewhere, if the hash doesn't match the image, display something to the user letting them know that the image has changed.

**Comment by RonB7139** [comment]
Add this guideline/policy/procedure to FAQ's

**Comment by joeykrug** [comment]
Actually, could just use this: https://thenounproject.com/
100x simpler, cohesive ui as opposed to images

**Comment by tinybike** [comment]
Closing this (and other image-related issues) for now; can re-open if/when we decide to re-introduce images.
