### ISSUE TITLE
Market description is missing on MarketsInfo object

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4233]
not seeing markets description in the UI. only a few markets have their title, they are PRE-REPORTING.

![image](https://user-images.githubusercontent.com/3970376/66885292-801e1280-ef99-11e9-9d24-be4ab11a4e6c.png)

![Screen Shot 2019-10-15 at 10 15 25 PM](https://user-images.githubusercontent.com/3970376/66885294-82806c80-ef99-11e9-831e-0fa82af7e0e3.png)

**Comment by bthaile** [comment]
cleared application data and market titles showed up. Something to keep an eye on.

**Comment by nuevoalex** [comment]
@bthaile Can we icebox this till theres repro steps?

**Comment by bthaile** [comment]
I've not seen this issue since initial time, closing
