### ISSUE TITLE
Option to have gas price adjust if not entered manually

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#427]
When a user selects one of the preset gas options we should provide an option to continue to adjust the price as that setting would adjust.

For example if a user checks this option then selects "Standard" when it is 3 gwei and the "Standard" gas price changes to be 10 gwei, their transactions should go in at 10 gwei. If they did not select the option to track they should still just use 3 gwei.
...

Allowing the user to clear their manually created gasPrice will allow the gasPrice to float each time they open the UI (this is different than the title of the CH task). This is the behavior before we added manually setting gasPrice. 

Currently the UI doesn't allow the user to clear their gasPrice. We can track the `standard` value if the user hasn't inputted a gasPrice or if they cleared it. We update the gasPrice values from API every 100 blocks, I think that would be ok for the user to peg their gasPrice to low/standard/high.

We'd need to change the form to allow the user to select which value they want to Peg to.
 -bthaile

**Comment by pgebheim** [comment]
This has been implemented differently.
