### ISSUE TITLE
Bug w/ charts and scroll

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#428]
Ok so chart bug - no chart, dunno why

Scrolling bug - scroll down to the bottom, wait a bit, it jumps up.  Confirmed it's not my trackpad or anything like that.  Also not b/c console is open

Attached a video

Change extension to .webm to view
[ice_video_20160311-000047.pdf](https://github.com/AugurProject/augur/files/168549/ice_video_20160311-000047.pdf)

**Comment by joeykrug** [comment]
these bugs seem to appear after being on a market page for ~20 sec or so.  Sometimes they're there straight off

**Comment by housemobile** [comment]
This happens with chrome on windows as well

**Comment by thinkloop** [comment]
We'll see with next charts implementation
