### ISSUE TITLE
Market cards for template formatting is currently off

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#4290]
For All sport templates that are using the Estimated scheduled start time, Formatting needs to be on 2 lines(even if the Font size needs to be shrunk on the 2nd line):

Needs to look like this:
yes/no
Will the NY Giants win vs. the New England Patriots by 3 or more points
Estimated schedule start time: Sept 19, 2019 1:00 pm EST

Categorical
Which NFL Team will win:  NY GIants vs New England Patriots
Estimated schedule start time: Sept 19, 2019 1:00 pm EST

**Comment by bthaile** [comment]
don't have control over the formatting of the market title string. it's just a string.

recommend closing

**Comment by bthaile** [comment]
we recently removed the market type from the market cards. Is this ticket to add them back for templates created markets?

**Comment by Chwy5** [comment]
NO...was just showing the templated market under each market type

**Comment by joeykrug** [comment]
did we get fixed?

**Comment by bthaile** [comment]
this has been done, templates with estimated scheduled date time is formatted in 2 lines
