### ISSUE TITLE
Market Creation Template Fixes - American Football

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#4291]
Need to add NFL and NCAA template seperation, see attached figma file
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=2629%3A185

![10-18fb.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/e42a0031-f0d7-47dc-95b1-564291137d29)

This can be removed from the template, b/c we have the boxes underneath it with the same info.  Still needs to show up in that formatting on the market cards and market trading pg

Yes/No
Will the [Team A] win vs the [Team B], Estimated schedule start time: [Date time]?
[ ] Change Suggested resolution rules to Include resolution rules, 
[ ] Remove the checkboxes on the current 2 rules and make them automatically included in resolution details

Will the [Team A] win vs the [Team B] by [Whole #] or more points, Estimated schedule start time: [Date time]?
[ ] shrink up # box
[ ] only allow whole # to be entered, not decimal or fractional or negatives 
[ ] Change Suggested resolution rules to Include resolution rules, 
[ ] Remove the checkboxes on the current rules and make first rule automatically included in resolution details
[ ] Remove rule If the game ends in a tie, the market should resolve as "NO' as Team A did NOT win vs team B

Will the [Team A] & [Team B] score [Whole #] or more combined points, Estimated schedule start time: [Date time]?
[ ]Market Question shrink up the Whole # box and 
[ ] only allow user to enter whole number no fractional or decimals
[ ]Same formatting needed, mentioned above for Estimated scheduled start time
[ ] Change Suggested resolution rules to Include resolution rules, 
[ ] Remove the checkboxes on the current rule 1 and make tit automatically included in resolution details
[ ] remove rule 2 - doesnt go with this market (If the game ends in a tie....)

Will the [Team] have [Whole #] or more regular season wins in [Year]?
[ ] Change Suggested resolution rules to Include resolution rules, 
[ ] Remove the checkboxes on the current rule 1 and make tit automatically included in resolution details

Will the [Team] win SuperBowl [Roman Num]?
[ ] make num into numeral 

Will [Player] win the [Years] [Award] award?
Example: Will Patrick Mahones win the 2019-20 MVP award?? - Change Mahones to Mahomes (has an m not an n)
award picker dropdown should say select award

Categorical
Same formatting changes needed for the estimated scheduled start time- where applicable

Which NFL Team will win: [Team A] vs [Team B], Estimated schedule start time [Date time]?
Outcome 3 needs to be Tie/No Winner (not draw)
[ ] Change Suggested resolution rules to Include resolution rules, 
[ ] Remove the checkboxes on the current rules and make rules automatically included in resolution details....for second rule need to make it Tie/No Winner from No Winner

Which College Football Team will win: [Team A] vs [Team B], Estimated schedule start time [Date time]?
For outcome number 3 needs to be No Winner (there are no ties/draws in college football)
[ ] Change Suggested resolution rules to Include resolution rules, 
[ ] Remove the checkboxes on the current rules and make rules automatically included in resolution details....for second rule If the game is not played or is NOT completed for any reason, or ends in a tie, the market should resolve as "No Winner". - need to remove "or ends in a tie"

[Team A] vs [Team B]: Total goals scored; Over/Under [Whole #].5, Estimated schedule start time: [Date time]?
[ ] needs to be Total points scored (not goals)
[ ] est sch start time formatting in market question
[ ] needs to be enter # in market question + same rules must be whole number entered, no decimal, fractional or negative
Outcomes
[ ] No winner outcome needs to be the 3rd outcome not the 1st
[ ] Change Suggested resolution rules to Include resolution rules, 
[ ] Remove the checkboxes on the current rules and make rules automatically included in resolution details....rule If the game is not played or is NOT completed for any reason, the market should resolve as "No Winner

Which NFL team will win the [Year] [Event]?
Market question can shrink up the year picker box
Other (field) needs to be an outcome if there are more than 7 possible outcomes

Scalar
Unit of measurement wins needs to stand out more and should probably remove choose denomination for the range (bc user cant change it in the template)

Precision s/b set to 1

Need to add Include Resolution Rules and add: Regular Season win totals are for regular season games ONLY and will not include any play-in, playoffs, or championship games

**Comment by Chwy5** [comment]
Will the [Team A] win vs the [Team B] by [Whole #] or more points, Estimated schedule start time: [Date time]?

[ ] only allow whole # to be entered, not decimal or fractional or negatives

Will the [Team A] & [Team B] score [Whole #] or more combined points, Estimated schedule start time: [Date time]?
[ ] only allow user to enter whole number no fractional or decimals

These are still allowing me to enter negative numbers

**Comment by bthaile** [comment]
user gets informed about the whole number error when they try to proceed to the next screen
![image](https://user-images.githubusercontent.com/3970376/68532878-5205c700-02e8-11ea-9525-33c1b01645f3.png)

**Comment by Chwy5** [comment]
It still was allowing me to enter a negative number here and we cant allow them to do that
In betting -1.5 means something.....we only want them for the templates in this input to enter a positive number
