### ISSUE TITLE
Market Creation Template - Discarding draft

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#4294]
If I am in the market creation process and I wish to discard my draft, after doing so, I need to be redirected to the, beginning step which would be the Category (which is step 1 of the template sequence).

Currently directs me back to the template step (which is step 4 in the template sequence)

**Comment by bthaile** [comment]
I'm not sure that is an intuitive flow. I would want to go back to the previous screen not back 3 screens. I think the user would get confused. 

I'd like to keep the screens in the same order moving forward as backwards.

**Comment by Chwy5** [comment]
I think if i discard my draft, I either want to choose a different template, market type or just start from scratch.  It is a little weird If I want to start from scratch (confirm discarding the draft) takes me to the middle point and I still have to hit back multiple xs to start over.

I think most likely scenerio is user will want a different market type (switch from Yes/NO template to categorical for example), but again...I still feel it should take you to the beginning if you chose to discard

**Comment by bthaile** [comment]
The template and custom market creation uses a page flipping nav approach or linear. I'd like to maintain that. We could have a button that would take the user back to the start, kinda like a `Start Over` button.

**Comment by phoebemirman** [comment]
lets make this button go back to landing page

<img width="735" alt="Screen Shot 2019-10-22 at 10 06 33 AM" src="https://user-images.githubusercontent.com/6775839/67311036-aa009900-f4b3-11e9-9284-6e7b0443112c.png">

**Comment by bthaile** [comment]
`create market` button navigates user back to landing page will be addressed in a different ticket. closing
