### ISSUE TITLE
Market Creation Template Fixes - Basketball

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#4296]
Need to add in separation between NBA and NCAA Templates...see figma attachment for design
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=2629%3A185

Formatting for any market with Estimated schedule start time needs to be fixed (2 lines)

![10-18rm.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/76b21398-8ece-4dc4-a5d3-fe39323c9a58)
remove this from the market question step from all templates since it is in the picker underneath.  This is only removed here....still needs to be seen and formatted correctly on Market card and market trading pg

First 3 yes/no templates have Las Angeles Lakers needs to be changed to "Los" 

Yes/No
Will the [Team A] win vs the [Team B], Estimated schedule start time: [Date time]?
[ ] Change Suggested resolution rules to Included resolution rules
[ ] Remove checkbox and include the current rule to be added into the resolution details automatically

Will the [Team A] win vs the [Team B] by [Whole #] or more points, Estimated schedule start time: [Date time]?
[ ] Make Whole # box smaller and change whole to enter
[ ] only allow for whole numbers, no decimals or fractions or negative #s
[ ] Change Suggested resolution rules to Included resolution rules
[ ] Remove checkbox and include the current rule to be added into the resolution details automatically

Will the [Team A] & [Team B] score [Whole #] or more combined points, Estimated schedule start time: [Date time]?
[ ] Make Whole # box smaller and change whole to enter
[ ] only allow for whole numbers, no decimals or fractions or negative #s
[ ] Change Suggested resolution rules to Included resolution rules
[ ] Remove checkbox and include the current rule to be added into the resolution details automatically
[ ] Remove the rule, If the game ends in a tie, the market should resolve as "NO' as Team A did NOT win vs team B (does not go with this market)

Will the [Team] have [Whole #] or more regular season wins in [Year Range]?
[ ] Make Whole # box smaller and change whole to enter
[ ] only allow for whole numbers, no decimals or fractions or negative #s
[ ] Change Suggested resolution rules to Included resolution rules
[ ] Remove checkbox and include the current rule to be added into the resolution details automatically

Will the [Team] win the [Year Range] NBA Championship?? 
[ ] remove 1 of the ? (currently 2)

Categorical
Which team will win: [Team A] vs [Team B], Estimated schedule start time: [Date time]?
Outcomes
[ ] remove Draw/No winner as an outcome
[ ] Change Suggested resolution rules to Included resolution rules
[ ] current rule is incorrect
[ ] Remove checkbox and change current rule to Include Regulation and Overtime, so it will appear in the resolution details automatically

[Team A] vs [Team B]: Total Points scored; Over/Under [Whole #].5, Estimated schedule start time: [Date time]?
Formatting changes for estimated scheduled start time in Market question[ ] 
[ ] Outcome 1) No winner needs to be removed (not for this market)
[ ] Make Whole # box smaller and change whole to enter
[ ] only allow for whole numbers, no decimals or fractions or negative #s
[ ] Change Suggested resolution rules to Included resolution rules
[ ] current rule is incorrect
[ ] Remove checkbox and change current rule to Include Regulation and Overtime, so it will appear in the resolution details automatically

Which college basketball team will win the [Men's/Women's] [Year] [Conference] tournament?
[ ] Outcome 1) Other s/b be Other (Field), s/b last option displayed before invalid
[ ] Change Suggested resolution rules to Included resolution rules
[ ] Remove checkbox

Which [League] player will win the [Year Range] [Award] award?
Since we are separating NCAA form NBA now, this one needs some changing...remove picker league and One Market will say "Which NBA player will win the {Year range} {picker award}award
The other one will say which NCAA player will win the.... 

Which Player will have the most [Action] at the end of the the [Year Range] regular season?
Outcomes must Include Other (field) as the last outcome before invalid

Scalar
Total number of wins [Team] will finish [Year Range] regular season with?
Unit of measure "Wins needs to stand out more" need to remove the choose denomination as it is preselected and cant be chosen
Precision s/b set to win

Tertiary Category for Basketball markets:

NBA ones should only show NBA or WNBA and custom (remove all others), NCAA should only show NCAA, March Madness, Tournament, and custom (remove all others)

**Comment by bthaile** [comment]
last item on the list:
we dont separate out Basketball categories in the tertiary category picklist. 

we would have to create sub-categories like `NBA Basketball` and `NCAA Basketball` it's possible but would be weird in the categories navigation.

**Comment by Chwy5** [comment]
Will the [Team A] win vs the [Team B] by [Whole #] or more points, Estimated schedule start time: [Date time]?

[ ] only allow for whole numbers, no decimals or fractions or negative #s....
it is still allowing me to enter a negative number for this market and fractions

**Comment by bthaile** [comment]
not following 

Tertiary Category for Basketball markets:

NBA ones should only show NBA or WNBA and custom (remove all others), NCAA should only show NCAA, March Madness, Tournament, and custom (remove all others)

here is the category picker

![image](https://user-images.githubusercontent.com/3970376/68532979-bb3a0a00-02e9-11ea-90cd-cc1ea4891cf3.png)

**Comment by Chwy5** [comment]
we would have to create sub-categories like NBA Basketball and NCAA Basketball it's possible but would be weird in the categories navigation. ---- Don't do this!!!

The way they are in the templates is fine...So If I am under WNBA pick my template, My Category sequencing Will be:
1) Sports
2) Basketball
3) WNBA
This is good
