### ISSUE TITLE
Verify or fix that Augur Node blockstream restarts on Ethereum node websocket ECONNRESET

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#431]
# Background

Ryan accumulated a list of errors when experimenting with local light node + augur node. Ryan emailed these errors to Paul, Scott, and Alex on 2018/11/19. Paul followed up and suggested that the most egregious of these was failure to restart blockstream. This ticket is for me to verify how this works and fix it if necessary.

# Error to investigate

```
Error: blockstream doesn't restart
  websocket wss://gethnode.com/ws closed: 1006 Socket Error: read ECONNRESET
  Disconnected from Ethereum node Socket Error: read ECONNRESET
  // using gethnode.com, after bulk sync finishes, AN doesn't automatically restart the blockstream on ECONNRESET.
  //   --> might be fixed by Scott's recent work to de-singleton blockstream
```

**Comment by ryanberckmans** [comment]
Seems fixed. Tested by manually inserting errors at ethrpc level:

```
during blockstream
    HTTP
        unretryable error --> OK
        retryable error --> OK
    WS
        unexpected close() --> OK
        retryable error --> OK
        unretryable error --> OK
```
