### ISSUE TITLE
mobile: hamburger menu shows up incorrectly

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4317]
![IMG_4095.jpg](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/8b66f150-61ce-4376-a99d-b43cee06bacd)

![IMG_4096](https://user-images.githubusercontent.com/3970376/67223933-d05fff00-f3f5-11e9-9576-75edb2527bb4.jpg)

**Comment by phoebemirman** [comment]
not reproducible
