### ISSUE TITLE
Auto-sell complete sets

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#432]
Auto sell complete sets when a user ends up getting them
...

@chwy Just to clarify, are are you saying that whenever the user makes a trade, the contracts should automatically sell any complete sets after the trade is completed and then notify the user?
 -adrake33
...

When a user acquires a complete set through trading...it should automatically sell those complete sets
 -Chwy5
...

It sounds like this would be 2 separate tickets: one for changes to the contracts, and one for changes to the frontend.

@achapman Should we add an option to the trading functions to allow auto-selling of complete sets?
 -adrake33
...

I'm on the fence about this. Users have expressed a desire to keep complete sets and doing things automatically for them when they may not want to take that action is really bad.

This is especially bad because it incurs settlement fees when the intention of the trader may have been to sell the respective shares separately on the market and avoid some portion of those fees and more importantly make money off of a spread.

In general this should only happen when someone is a liquidity provider (which to me means they absolutely do not want us to auto-sell complete sets) or they are explicitly choosing to use the API and not use owned shares in trades (which means they've explicitly indicated they want to gain new shares).

Is there a common case we're seeing from normal trading where people end up with unwanted complete sets?
 -nuevoalex
...

This was user feedback added from Joey....I am also on the fence about this and had made an argument to not automatically trigger complete sets in the past, especially for categorical markets...which allows the user to "leg" trades...After trading on the platform for months, I believe complete sets are confusing to most users and probably should be done behind the seens.
 -Chwy5

**Comment by adrake33** [comment]
Fixed by https://github.com/AugurProject/augur/pull/788
