### ISSUE TITLE
Remove dashes next to Outcome on trading pg

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#4326]
![10-21.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/007d8188-5119-4805-9ebd-216d7825e7a7)

These dashes need to be removed

**Comment by phoebemirman** [comment]
are we also removing last price? those are for when last price is empty

**Comment by Chwy5** [comment]
Yes only in that spot....no need to have it in two locations....still will be under the last column
