### ISSUE TITLE
Await all promises

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#4332]
We currently do not wait for all promises resolve or reject. It is very likely that at least one of these unawaited promises is causing testing to fail to resolve in a timely fashion and therefore breaking the CI flow.

Most of the unawaited promises, and by far the most difficult to fix, are when we create new database indexes. We create them in their constructors but constructors cannot be async. We need to either use static creation methods or have a separate init() method.

The testing issue with awaits can be reproduced by running the `:getAccountTimeRangedStats` test like `yarn -t :getAccountTimeRangedStats`.

**Comment by MicahZoltu** [comment]
Async constructor pattern:
```typescript
export class MyClass {
    private constructor(
        private readonly apple: string,
        private readonly banana: number,
        private readonly cherry: boolean
    ) {}
    public static async create(applePromise: Promise<string>, banana: number, durian: Thing): MyClass {
        const apple = await applePromise
        const cherry = await getCherry(durian)
        return new MyClass(apple, banana, cherry)
    }
}
const newMyClass = await MyClass.create(applePromise, banana, durian)
```

**Comment by MicahZoltu** [comment]
The above pattern also makes it so you don't have to deal with classes in a not-yet-ready-to-use state where their promises haven't fulfilled yet.  The class always starts fully constructed and ready to go.

**Comment by pgebheim** [comment]
Yeah! We use that internally in a number of places (see Augur.ts) -- but yeah should do this for all the DBs as well.

**Comment by pgebheim** [comment]
Not actionable
