### ISSUE TITLE
Unsafe: refactor UNSAFE_ method in market-charts

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4339]
for these refactor, only refactor out the unsafe methods, minimize changes.

./packages/augur-ui/src/modules/market-charts/components/market-outcome-charts--depth/market-outcome-charts--depth.tsx:  `UNSAFE_componentWillUpdate(nextProps) {`

./packages/augur-ui/src/modules/market-charts/components/market-outcomes-chart/market-outcome-chart-highchart.tsx:  `UNSAFE_componentWillUpdate(nextProps) {`

./packages/augur-ui/src/modules/market-charts/components/market-outcome-charts--candlestick/market-outcome-charts-candlestick-highchart.tsx:  `UNSAFE_componentWillReceiveProps(nextProps) {`

./packages/augur-ui/src/modules/market-charts/components/market-outcome-charts--candlestick/market-outcome-charts--candlestick.tsx:  `UNSAFE_componentWillReceiveProps(nextProps) {`

**Comment by gitstart-augur** [comment]
Final Credit cost: 50

**Comment by joeykrug** [comment]
status / does this matter? what is this issue

**Comment by pgebheim** [comment]
Already addresses.
