### ISSUE TITLE
Augur Node Sync Time

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#434]
Takes me 20 min. to sync 10%, still think it's way too slow
...

I think we should have a product-level conversation about what is required here. Without distributing pre-sync'd snapshots, I think it would be a bit of engineering to get it significantly lower. It's making significant quanitites of eth calls and has to operate linearly (to match the linear nature of the blockchain). There is perhaps more parallelism we could get by pre-fetching eth_calls' before we are in the linear portion of the code.
 -epheph
...

Why is it operating linearly? Why not fetch multiple block ranges worth of logs at the same time _then_ process them all
 -joeykrug
...

@joeykrug we do, we fetch very large quantities of logs and block details in one go. however, inside the block processing, there is data we need to get via off-chain calls, that isn't present in the logs. Those slow down the batch-mechanisms we have in place for the other things. As an example, a market's outcome tokens are not in the event logs, we need to make calls for it, and cannot finish that one createMarket until they are done.

We could pre-request those and have them available as an injected promise, but that just requires more engineering. would probably cut time in half or so? Haven't profiled it, though
 -epheph
...

If it cuts time in half I'd recommend doing it but not super high priority
 -joeykrug

**Comment by joeykrug** [comment]
part of an v2
