### ISSUE TITLE
Unsafe: refactor UNSAFE_ methods from /market/ and others 

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4342]
for these refactor, only refactor out the unsafe methods, minimize changes.

./packages/augur-ui/src/modules/portfolio/components/common/filter-switch-box.tsx:  `UNSAFE_componentWillUpdate(`
./packages/augur-ui/src/modules/filter-sort/components/filter-search.tsx:  `UNSAFE_componentWillMount() {`
./packages/augur-ui/src/modules/filter-sort/components/filter-search.tsx:  `UNSAFE_componentWillUpdate(nextProps, nextState) {`
./packages/augur-ui/src/modules/market/components/market-view/market-view.tsx:  `UNSAFE_componentWillMount() {`
./packages/augur-ui/src/modules/market/components/market-view/market-view.tsx:  `UNSAFE_componentWillUpdate(nextProps) {`
./packages/augur-ui/src/modules/market/components/trading-form/trading-form.tsx:  `UNSAFE_componentWillReceiveProps(nextProps: TradingFormProps) {`

**Comment by gitstart-augur** [comment]
Final Credit cost: 70
