### ISSUE TITLE
Unsafe: refactor UNSAFE_ methods from /create-market/ /trading/ and others

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4343]
for these refactor, only refactor out the unsafe methods, minimize changes.

./packages/augur-ui/src/modules/account/components/profit-loss-chart.tsx:  `UNSAFE_componentWillUpdate(nextProps: ChartProps) {`
./packages/augur-ui/src/modules/modal/transactions.tsx:  `UNSAFE_componentWillMount = () => {`
./packages/augur-ui/src/modules/create-market/components/review.tsx:  `UNSAFE_componentWillMount() {`
./packages/augur-ui/src/modules/create-market/components/review.tsx:  `UNSAFE_componentWillReceiveProps(nextProps, nextState) {`
./packages/augur-ui/src/modules/create-market/components/common.tsx:  `UNSAFE_componentWillReceiveProps(nextProps) {`
./packages/augur-ui/src/modules/trading/components/form/form.tsx:  `UNSAFE_componentWillReceiveProps(nextProps) {`
./packages/augur-ui/src/modules/trading/components/wrapper/wrapper.tsx:  `UNSAFE_componentWillUpdate(nextProps) {`
./packages/augur-ui/src/modules/trading/components/confirm/confirm.tsx:  `UNSAFE_componentWillReceiveProps(nextProps) {`

**Comment by gitstart-augur** [comment]
Final Credit cost: 50
