### ISSUE TITLE
Augur.js Session Settings

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#435]
It would be a nice feature for development if Augur.js had support for additional stored user settings during a session. Namely if you could specify:

- meta
- gas price

and for the duration of your session it would use those in every tx which is made.

Currently these have to be specified manually which has bitten us a few times for "meta" when it's been forgotten.

Being able to specify and change a session gas price will be very useful when implementing specifying gas price for hardware wallets.
...

@achapman Can you please add a Priority label to this issue?
 -adrake33

**Comment by pgebheim** [comment]
This has been handled for gasPrice for augur.js.

Converting this into an Augur State issue.
