### ISSUE TITLE
Support for Market creation categories round 3/3

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#4352]
The previous two rounds made the `getCategoryStats` getter work but leaves some room for improvement:

1. Refactor the Markets getters to use the same MetaCategories code.
2. Make and use a derived categories DB.

The refactor helps with maintainability. The derived DB helps with speed.

**Comment by joeykrug** [comment]
status of this?

**Comment by robert-e-davidson3** [comment]
This is for speed improvements.

> 1. Refactor the Markets getters to use the same MetaCategories code.

This might not still be relevant since we've gone through at least one major change in the interim (move to Dexie)

> 2. Make and use a derived categories DB.

This is probably still a good idea.
