### ISSUE TITLE
Upgrade to Typescript 3

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#436]
Augur Core wont build with Typescript 3 currently, but it may not be too bad.
...

Scratch that, it doesn't even work in 2.9.2 which is the version we use in Augur Node.

Fixing the issues.
 -pgebheim
...

@pgebheim what's the status on this one? Should this be in 'ready for dev' since there are still issues you need to fix? Or have they been fixed already?
 -sharkcrayon
...

Sorry, I just handled the upgrade to 2.9.2 within my mono-repo update.

Still haven't done v3.
 -pgebheim
...

@achapman Is this something that we should still do?
 -adrake33
...

Yea this would still be nice to do. Not high priority but still relevant
 -nuevoalex

**Comment by justinbarry** [comment]
Already done.
