### ISSUE TITLE
Use seed forking to fix tests

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#4366]
We have some tests that fail when run in parallel but not in serial.  Justin's ganache seed forking work will likely fix them. Even if it doesn't fix them, it will make them run faster and more resilient to changes in other tests.

The main test file to fix is Users.test.ts.

**Comment by pgebheim** [comment]
@robert-e-davidson3 Does the PR for #4725 close this issue or is that just a part of it?

**Comment by robert-e-davidson3** [comment]
It does! These are the last tests that needed the seed forking to work.

**Comment by pgebheim** [comment]
Closing, then.
