### ISSUE TITLE
Combine recheck sealed block requests

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#437]
Should just do 1 per block hash; currently a separate recheck is done for every transaction.
...

@epheph is it clear what this issue refers to / what needs to be done here?  TLDR is, the re-checking to see if a block has been sealed (mined) yet in ethrpc currently is done once per transaction, even if the transactions were part of the same block.  To avoid doing a bunch of extra RPC requests, it'd be better to just do a single lookup per block.

**Comment by epheph** [comment]
In V2, ethrpc will not be used and likely will be abandoned. Let's not put engineering effort into optimizing it.
