### ISSUE TITLE
Open orders PNL bug

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#438]
1) Pick a market with 100 - 0 odds
2) Buy the 0 side
3) starting price .50
4) max price .80
5) buy 1000 or some high # of shares
6) it buys nothing

It should buy shares up until the cost is .80/share

**Comment by joeykrug** [comment]
Edit, no it did!  It just took a long time

**Comment by joeykrug** [comment]
Reopening for a bug here still.
replace 6) with "it buys the proper # of shares"

7) it says i have realized profit/loss --- should all be unrealized, second, it says i have loss, and i shouldn't have any loss if no one else has changed the price, unrealized or not

![capture](https://cloud.githubusercontent.com/assets/5925937/13712234/160e6736-e788-11e5-85bc-b36db11dd162.PNG)

**Comment by tinybike** [comment]
Fixed in 18c0abbcba27f506210475af61b621474847b1ca (as far as I can tell...)
