### ISSUE TITLE
Failed to buy Shares

### ISSUE THREAD

**Issue by gabbello** [AugurProject/augur#4381]
**Describe the bug**

I tried to place a bet for the brexit market via Guesser, transaction went through (https://etherscan.io/tx/0x34a783c68d9ff09a7fd2db489e33901160ff61133ceddd271babc83696ccd367) but for some reason doesn't appear under "my predictions" section, also I can not see in on augur.casino and it's quite clear it didn't work as expected.

Also, when I check it on etherscan I only see some CASH token, but not any SHARES token transactions. Any idea what went wrong?

**Additional context**
I'm using an imported wallet on mobile MetaMask (which is beta) so that might be the reason.

**Comment by nuevoalex** [comment]
Hey @gabbello ,

The TX succeeded but there was no matching order on the orderbook so it simply returned your ETH.

**Comment by gabbello** [comment]
Thanks for quick feedback. Since I don't know what was the balance before buying the shares I couldn't notice that it was returned, I was just fooled that it only appears as an OUT transaction for my account (https://etherscan.io/address/0x64ecb3a56ea6cd5bf0d8f52c8f5907e4b2976260) without any IN.

On the other side, it would be nice for the (new) UI to list such "unmatched" orders somewhere on the order/market list.
