### ISSUE TITLE
Update gas price copy

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#4384]
Gas price will be updated from: 

"Gas cost/price" or "Estimated gas cost" 
to
 "Transaction fee" 
throughout the UI. 

Locations: 
- [x] Withdraw funds modal 
- [x] Market creation - review step (x3) 
- [x] Market creation - review step tooltips (x3)
- [x] Initial reporting form
- [x] Disputing form 

If I've missed any area change that too :)

**Comment by pgebheim** [comment]
@andrewdamelio -- This should probably be on your plate with fees
