### ISSUE TITLE
Create env with weeks of trade history

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#4388]
We need at least weeks of trade history in an environment so that design/ux can test the charts.

The candlestick/pop flash script can be used but first needs to be edited to use a wider range of prices. It may need time-related tweaks as well.

Getting an environment up is the tricky part. We have a few options:

1. Deploy to Kovan with TimeControlled but leave our current deploy alone. Once <https://github.com/AugurProject/augur/pull/4371> gets merged in, it will be easy to point to the alternate Kovan while leaving the regular one undisturbed.
2. Someone runs a local ganache node and exposes the port. Other people point to it. Major downside is that waking someone through connecting is not easy and home routers can be a pain.
3. We put a local ganache node into an EC2 or similar container (or aws manage blockchain?). We can actually do this in two parts, where first we locally create the data, save the seed, then load the seed in the remote container etc. Or we can run flash locally against the remote blockchain.

**Comment by joeykrug** [comment]
status/?

**Comment by pgebheim** [comment]
Closing specific task since we're doing this with Chaos monkey -- we've got deterministic accounts etc.
