### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#439]
EDIT: This is the result of all of the conversation below:

The loading animation will consist of a progress bar at the top of the screen (see attachment). It should be implemented site wide.

![clipboard 2018-06-09 at 7 27 22 pm](https://user-images.githubusercontent.com/11491365/49621396-fca79400-f979-11e8-9023-c0ab8af06234.png)

@justinbarry Aaron would like you to do some research on what implementing this would entail and then give an estimate for it.
...

Need to create list of views & locations where this is needed, and then get clarity from IDEO if necessary.
 -sharkcrayon
...

@sprinkle This is ready for assignment. Feel free to add technical details to the task description.
 -sharkcrayon
...

:thumbsup: 

...

Moving this back to "Waiting on Designs". Tara wants to spend more time thinking about our options here and doesn't think the progress bar is the right solution.
 -sharkcrayon
...

@sprinkle This is ready for development. See screenshots above and updated task description.

I'd like to review the PR to double check the visual effect after you're done with development.
 -sharkcrayon
...

:thumbsup::skin-tone-2: 

...

Moving to post-MVP.
 -sharkcrayon
...

I want Matt to review this before we implement
 -sharkcrayon
...

This task could add the loading progress bar at top and also replace the loading logo. 
I think this is a good time to do this. What do you say @mattbullock 
 -bthaile
...

@tomhaile @serena as we're adding more functionality to the core stats bar we need to give it more real estate. I suggest removing the awkward polygons and making use of the full height. 

I don't think the progress bar should cover the core stats as it's hiding vital info. I suggest a bright colour of 4px height that sits directly below the core stats.

Any preference?

![clipboard 2018-06-09 at 6 46 01 pm](https://user-images.githubusercontent.com/11491365/49621481-6758cf80-f97a-11e8-8968-e4984c8d23af.png)

![clipboard 2018-06-09 at 6 46 29 pm](https://user-images.githubusercontent.com/11491365/49621482-6a53c000-f97a-11e8-8c99-e6cf32179102.png)

 -matt-bullock
...

The green is always used as a positive colour in the UI which is why it might be well suited
 -matt-bullock
...

loading bar could be above the core stats and be 4px

 -bthaile
...

![clipboard 2018-06-09 at 7 27 22 pm](https://user-images.githubusercontent.com/11491365/49621454-41cbc600-f97a-11e8-988a-1148b29422ce.png)

yeah I like that
 -matt-bullock
...

I like those screenshots. What do you think about gray to that light purple? To me the green grabs too much attention while the purple grabs just enough.
 -sharkcrayon
...

Ok let's just use the purple. there's no gradient or colour change to indicate it's complete. Progress complete is indicated by the bar disappearing. 

Why do you think below the core stats bar is appropriate - because it only indicates things are loading under the bar as opposed to it indicating loading of data within the core stats?
 -matt-bullock
...

if building it now, put it at the top because the polygons will be covering part of it. We can shift below when we remove the polygons and update the core stats bar
 -matt-bullock
...

I like that idea.
 -bthaile
...

Green looks the best imo
 -joeykrug
...

@justinbarry Can you do some research on this to see what this would entail code-wise, and give an estimate?
 -adrake33
...

@serena 
1. What events are we going to use the loader for? 
2. Is it possible we have multiple on going "loading" event?
3. If so, should we accommodate that.
 -justinbarry
...

 It may be more useful for you to ask me specifics, because I don’t know how data is loaded into each section, but here’s the general outline of what I’m picturing: 

 The progress bar should begin when the page is first viewed and end when all data for that page has finished loading. If the user takes an action that’s localized to a specific part of the page (like changing the period or range on a graph)  a local spinner should be used instead of the progress bar.  

 We should also use the progress bar for pagination. This is certainly the case on the market list page when the user changes what pagination-page they are viewing, and we probably want to use it as well for when pagination is specific to a section (like on portfolio or reporting).

 Does that help at all? I suspect you may need to ask me questions page by page as you implement.

@justinbarry 
 -sharkcrayon
...

The UI itself is probably a 2. The rest is unknown. 

@johndanz given you just went through all the code while refactoring is there an easy place to hook a progress indicator?
 -justinbarry
...

I'm not sure what this bar is for, i guess loading markets? we can just put it on the `top-bar` component most likely (see how the new connect account dropdown was added). I imagine the state management around it will relate to the markets.
 -JohnDanz
...

@johndanz  The description says it should be implemented site-wide. I believe the idea is that it would replace the animated Augur logo.  Is that correct @serena ?
 -adrake33
...

@adrake @johndanz Yes, that is correct. 
 -sharkcrayon
...

@justinbarry Marking this as Ready for Development. If more internal feedback is still needed, please let me know.
 -adrake33

**Comment by joeykrug** [comment]
Is this happening? Noticed sprinkle is tagged in it which means it's old as heck

**Comment by bthaile** [comment]
Design needs to weigh in on this. Taking my name off. Puttin on chwy.

**Comment by Chwy5** [comment]
My opinion is, if we are doing Augur correctly we wouldn't need the progress bar.  I rather spend the time fixing the lag instead of masking the slowness with a progress bar.

I also think it is a little more complicated adding it than it appears with the new redesign.  Currently depending which OS a user has, the google translate bar would cover it, as it currently covers the header....making it fixed is not an option either especially b/c we are limited with space on mobile up top, with multiple fixed components there already.

Lets fix the current lag issue and only come back to this if needed

**Comment by joeykrug** [comment]
Yeah I think this is unnecessary, let’s just close
