### ISSUE TITLE
Allow a report to be edited in the first half of the voting period

### ISSUE THREAD

**Issue by niran** [AugurProject/augur#44]
When a user navigates to their ballot after the hash has been submitted, we should add a link or button to the messaging in #42 that lets the user edit their ballot and submit again.

**Comment by joeykrug** [comment]
They can't edit their ballot (otherwise hashes won't match) (unless this is still in the hash submission period)

**Comment by niran** [comment]
Yeah, only in the hash submission period. This is a low priority since reporters should rarely need to edit their ballot, but definitely necessary before Homestead so reporters have a way to fix mistakes that will cause them to lose assets.

**Comment by tinybike** [comment]
Folded into #259.
