### ISSUE TITLE
FAQ's will help users understand things, FAQ's need beta testing too!

### ISSUE THREAD

**Issue by RonB7139** [AugurProject/augur#441]

**Comment by tinybike** [comment]
Right now we have the [Zendesk FAQ](https://augur.zendesk.com/hc/en-us), the [technical documentation](http://docs.augur.net), as well as the in-app tour.  Did you have something in mind apart from these?

**Comment by RonB7139** [comment]
glossary of terms for sure, perhaps a more visible placement for the FAQ's

**Comment by tinybike** [comment]
Added links to the FAQ on both augur.net (landing page) and augur-dev.firebaseapp.com.  The FAQ now has a (reasonably in-depth) glossary of terms, too.
