### ISSUE TITLE
open orders and comments overlap after expanding market header

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#4416]
expanding this part:

<img width="775" alt="Screen Shot 2019-10-25 at 8 29 49 AM" src="https://user-images.githubusercontent.com/6775839/67584081-bc701200-f701-11e9-8f3f-e54625f88bb3.png">

overlap:
<img width="1266" alt="Screen Shot 2019-10-25 at 8 28 17 AM" src="https://user-images.githubusercontent.com/6775839/67584166-e0cbee80-f701-11e9-9cba-bfdfecf5e090.png">

**Comment by bthaile** [comment]
I'm not able to repro
