### ISSUE TITLE
Stop orders are confusing to most people, should at least have an info modal or FAQ explaining

### ISSUE THREAD

**Issue by RonB7139** [AugurProject/augur#442]
(I think Carl has a template for "helper modals")

**Comment by joeykrug** [comment]
Good idea, maybe something like a helper modal first time you try to use it then tooltips in the future: https://www.google.com/design/spec/components/tooltips.html#

**Comment by joeykrug** [comment]
should just get rid of stop orders - they won't be persistent anyway so will just confuse users --- limit and market orders only
