### ISSUE TITLE
Automate Chwy's Tests Where possible

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#443]
Augur Trading Test Script
 1. Ability to make orders and trades in Binary (long vs short markets), categorical, and scalar markets: (These tests need to be performed individual, simultaneous trading of 2 users, and eventually with multiple parties)
    - Place limit buy order
    - Place limit sell order
    - Buy at the best available price – consuming entire order
    - Sell at the best available price – consuming entire order
    - Buy at the best available price – partially filling the order
    - Sell at the best available price- partially filling the order
    - Buy at best available price consume entire order and be bid over for more at that price
    - Sell at best available price hitting the entire order (initiating a short sell) and be offered over for more at that price
    - Consume multiple levels of an order (sweeping the book) both for bid and offer side (as well as bid/offered over)
        1. Are we getting filled at best price
        2. Rebate?
        3. If not being filled at best price what happens to that money
 2. For Binary Markets: tests need to be done having:
    - No starting position in a market (new to market),
    - Starting w/ a long position,
    - Starting w/ a short position
 3. For Categorical Markets: tests need to be done having:
    - No starting position in a market (new to market),
    - Starting w/ a long position,
    - Starting w/ a short position
    - Starting with Multiple Long outcomes
    - Starting with Multiple short outcomes
    - Combination of long and short
    - Will complete sets occur automatically? If so need clear path and notification of change in position and money to user
 4. Money Management
    - ETH starting balance is correct
    - Confirm balance is the same when I leave the site and come back – if not what changed (notification)
    - When placing bid or ask, confirm correct amount is being frozen and follow clear path to where it is being deducted from (money needs to be to the penny)
    - When Starting w/ a short position and buying a portion of it back – need to confirm margin isn't being taken on the new buy order and instead should decrease due to closing out a portion of original position
    - Confirm Estimated costs match Eth deduction
    - Confirm fees are being calculated and deducted correctly (especially in settlement and complete sets)
    - Confirm Gas costs being deducted and compare to Etherscan TX
    - After user has an open position and that position PnL changes how is that being tracked? Is it included in ETH total? 30-day? 1-day?
    - How does system treat realized profits and remaining open positions?
    - Confirm realized and unrealized PnL updating correctly (will need to confirm on market settlement as well)
    - Ability to see how money changes based on orders or trades user makes
    - As price of an outcome in one of my open positions change does my PnL (total eth, 30-day, 1-day) change as well
    - When cancelling an open order confirm Eth balance corrects what was being held
 5. Risk & Position Management
    - What are my open positions (in a specific market)
    - What was my opening price (in the event of multiple trade prices the avg price of all the trades – weighted)
    - Realized P&L (difference from opened position and closed position)
    - Unrealized P&L (difference from opened position starting price to open position last trade price)
    - Confirm last trade price updating correctly
    - When a book is swept, confirm last trade price updates correctly.
    - What is my true Eth balance vs my available ETH balance for trading (frozen funds)
    - Track all open positions and PnL at once (total PnL)
    - Ability to sort not just by individual market but have total frozen risk with ability to cancel open orders (cancel individual markets and cancel All)
    - Ability to sort closed trades (filled orders by market and/or date or time frame)
 6. Order Book
    - Make sure it is displaying correctly
        1. Best bid and best offer should display closest to midpt
        2. Put in multiple bids and offers – see how many orders (both Bids and Offers) book can support
    - When clicking on order from the order book, make sure correct information filters into order ticket (confirm price and quantity) do initial trade test from above including taking multiple orders on the book at once)
    - Confirm order book updates correctly to show book reducing by the amount traded on order ticket submission
 7. Market depth
    - Confirm displaying properly
    - Confirm # of steps
    - Confirm when clicking on a step proper filtering in of the order ticket both price and quantity
Additional UX test script
 1. Ability to make an Account
 2. Ability to add funds to an Account (Purchase Eth if necessary)
 3. Ability to find a market
    - Search and/or sort
    - Favorites
    - Find it again after returning another time – easily (w/out searching through 10k markets)
 4. Ability to understand Rules of a Market
 5. Market Price charts displaying correctly w/ proper labels
 6. Order book to display properly and update correctly
 7. Order ticket
    - Easy to use
    - Arrows updating properly to correct decimal place
 8. Ability to easily see what my position and PnL did by signing on again
    - See my old trades and account Tx. especially if I had not been on in a while…i.e. Long term contest …who will win the World Series?
 9. User has to understand Risk, account status and how money changed at all times
    - Confirm consistency of market data (last price when price changes) markets page, market info (outcomes, my position), portfolio pg.
    - Confirm consistency of PnL (when last price change) in my positions, markets pg, Eth balance and portfolio
 10. How to create a market
    - Market Types (binary, categorical, scalar)
    - Fees being paid
    - When a market expires vs when it is settled
    - Specific Language used
    - Specific Rules and settlement sources
 11. Trade Notification
 12. How to settle a Market (market reporting)
    - Reporting obligation
 13. Ability to withdraw money
...

Talked to @chwy about this. He said he would work on updating it, but recommended waiting to do so until after the new trading page is out.
 -adrake33

**Comment by pgebheim** [comment]
@robert-e-davidson3 --- Could you take a look at this and add thoughts / see if there's anything that you know we have tests for?

**Comment by robert-e-davidson3** [comment]
Some of these tests can't be automated because they're tests of how people interpret Augur (like #11). Many others are UI tests so we won't be automating them.

A lot of the tests here can have their variations pared down through automation. I'm not sure if any of our existing tests are sufficient but we have the pieces in place to cover many more of these cases than we currently cover.

Some of the UI tests, essentially those involving the word "correctly", can be automated as backend tests as well as having a manual frontend test. This will reduce the number of manual test runs needed that fail due to backend issues instead of actual UI issues with display or updating.

Also some tests aren't really Augur-related (#8 and #9) since they involve Ethereum account creation and funding. They're prerequisites to interacting with Augur but shouldn't be run if we can use existing accounts.
