### ISSUE TITLE
Blocks/period in hex

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#443]
![hex](https://cloud.githubusercontent.com/assets/5925937/13712891/ad97a83a-e78b-11e5-8b83-afd2604b6792.PNG)

I'm not that 539 at hex to do the conversion in my head

**Comment by joeykrug** [comment]
Wait a minute --- 0xf69b5 is 1010101 the branch ID

Blocks / period isn't showing up at all!

**Comment by tinybike** [comment]
blocks/period is supposed to be in base 10!  it's just not showing up there for some reason -- the 0xf69b5 is the branch ID ( == the infamous 1010101)

**Comment by tinybike** [comment]
...............thunder stolen

**Comment by tinybike** [comment]
Fixed in b63b7643c0f5a18dd8d077b45b775169eb784cb3.
