### ISSUE TITLE
MC Templates - Market Validation Proposal

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#4441]
Proposal for template validation:

Pre Create Market: fields added to extraInfo to be passed to market creation onChain.
market description still exists as `Will Green Bay Packers beat Chicago Bears on October 31, 2019 4:00 AM (UTC 0)`

added extraInfo:
```
export interface ExtraInfoTemplateInput {
  id: number;
  value: string;
}
export interface ExtraInfoTemplate {
  hash: string;
  question: string;
  inputs: ExtraInfoTemplateInput[]
}

```
example:
```
{
  "template": {
    "hash": "QmcitCLDk6Q4xwNe3ZkV4CHsV4ot1SPMKc9xjErzVzFKx1",
    "question": "Will [0] beat [1] on [2]?",
    "inputs": [
      {
        "id": 0,
        "value": "Green Bay Packers",
        "list": "NFL_TEAMS"
      },
      {
        "id": 1,
        "value": "Chicago Bears",
        "list": "NFL_TEAMS"
      },
      {
        "id": 2,
        "value": "October 31, 2019 4:00 AM (UTC 0)"
      }
    ]
  }
}
```
other example:
```
{
  "template": {
    "hash": "Lki4X...",
    "question": "Will [0] make the [1] [2] [3]?",
    "inputs": [
      {
        "id": 0,
        "value": "Ohio Bobcats",
      },
      {
        "id": 1,
        "value": "2020",
        "list": "YEARS"
      },
      {
        "id": 2,
        "value": "Men's"
        "list": "MENS_WOMENS"
      },
      {
        "id": 3,
        "value": "NCAA Tournament"
        "list": "NCAA_BASKETBALL_EVENTS"
      }
    ]
  }
}
```
Each template consists of a few parts:
(1) An overall template substitution string which when evaluated, produces the Title of a market.
(2) Parameters which can be filled in with certain values to be substituted into (1).

We propose a method a building these templates such that a market can be validated to match a defined template.

#### Defining Templates
All parts of the template must be verifiable by a defined regular expression, and the template string is in full defined by one large regular expression containing these sub expressions.

For example:
```
NFLTeams = "(Green Bay Packers|Chicago Bears|Oakland Raiders)"
DateFormat = "(0[0-9]|1[0-2])/([0-1][0-9]|3[0-2])/(19|20)[0-9]{2}"
Template = "Will $(NFLTeam) beat $(NFLTeam) on $(Date)"
FullyExpanded = "Will (Green Bay Packers|Chicago Bears|Oakland Raiders) beat (Green Bay Packers|Chicago Bears|Oakland Raiders) on  (0[0-9]|1[0-2])/([0-1][0-9]|3[0-2])/(19|20)[0-9]{2}"
```

For each template in the system, we can generate this full expanded regular expression. Then, for each of those regular expressions generate a hash (I recommend using a multi-hash for this) and generate single JSON file the maps a hash to a particular template string:

For example, if the only template in the system was the one defined above, we'd have a file like so.

example-templates.json
```json
{
    "QmcitCLDk6Q4xwNe3ZkV4CHsV4ot1SPMKc9xjErzVzFKx1": {
        "template":  "Will $(NFLTeam) beat $(NFLTeam) on $(Date)",
        "parameters": {
            "NFLTeam": ["Green Bay Packers", "Chicago Bears", "Oakland Raiders"],
            "Date":  "(0[0-9]|1[0-2])/([0-1][0-9]|3[0-2])/(19|20)[0-9]{2}"
        },
        "validator": "Will (Green Bay Packers|Chicago Bears|Oakland Raiders) beat (Green Bay Packers|Chicago Bears|Oakland Raiders) on  (0[0-9]|1[0-2])/([0-1][0-9]|3[0-2])/(19|20)[0-9]{2}"
    }
}
```
#### Creating a market with a template

When a market is created with a template 3 things should occur:

1. The user should choose a template that they want to use, and we should look up the template string, the parameters, and the hash.
2. The UI should gather the input parameters from the user, making sure they pass the rules for those parameters.
3. The UI should substitute them into the template, and then use the validator regular expression to validate that the whole title is correct.
4. When submitting the market, the parameters used for substitution, as well as the template HASH should be included on extraInfo.

#### Validating Templates

When displaying markets, the UI can validate templates by repeating the actions above in a different order.

1. Look up the template used to generate this market based on the hash. IF the hash doesn't map to a known template -- it will not get the badge.
2. Validate that the template TITLE matches the validator regular expression.
3. Expand the template string with the parameters, and validate that it matches exactly the TITLE string.

If all 3 of the above conditions are met, the market should get the "Created from template" shield.

**Comment by pgebheim** [comment]
This proposal currrently doesn't correctly spot tampering with additional details.

In order.for those to be included in the template hash the resolution details will need to be added to the big regex so that the ID of the template includes all the title details as well.

Perhaps there's something slightly cleaner here?

Eg perhaps we hash a JSON structure:

```
{
    validator,
    details
}
```

And that becomes the ID of the market.

**Comment by bthaile** [comment]
All choice resolution rules got removed in templates. we have an array of resolution rules that are added to longDescription.

example for 3 resolution rules concat and sent in extraInfo
```
"longDescription":"Include Regulation and Overtime\nIf the game ends in a tie, the market should resolve as \"NO' as Team A did NOT win vs team B\nAt least 55 minutes of play must have elapsed for the game to be deemed official.  If less than 55 minutes of play have been completed, there is no official winner of the game and the market should resolve as \"No\""

```
on market object, `details` property has
```
"Include Regulation and Overtime
If the game ends in a tie, the market should resolve as "NO' as Team A did NOT win vs team B
At least 55 minutes of play must have elapsed for the game to be deemed official.  If less than 55 minutes of play have been completed, there is no official winner of the game and the market should resolve as "No""
```
it's possible to pre-hash the resolution rules and compare to hash on market.details.

**Comment by bthaile** [comment]
closing this. validation and templates have been done
