### ISSUE TITLE
Account summary Pg Issues

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#4443]
A few issues i see with Acct Sum pg:
1)We are missing the "NEW" pop up in purple box on the Acct summary pg
~~2) the "View" box looks a little small on desktop~~
~~3) after viewing the message the message turns from white to gray - the gray is too dark, I cant really read it on my screen~~

Tom: (crossing out 2 and 3, "little small" isn't clear enough and colors will be worked as a larger effort)

4) The center section - is missing the PnL chart to start (just big empty space, though one s/b there)...if I switch from Your overview and back to augur status and then back to Your overview the Pnl chart appears.  But when I do this the 2 toggles circled above disappear (no longer see the tabs Your overview or Augur Status)

![10-28as.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/64842ff8-e28e-4c3f-8eb7-e2001445bf3c)

![10-28as2.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/f375fb80-1a3d-4bba-bd3c-61782d8aa791)

looks like this:
![10-28as3.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/ccc9207b-f75d-484d-9c05-e58c7527ab89)

**Comment by bconfortin** [comment]
> 1) We are missing the "NEW" pop up in purple box on the Acct summary pg

That is actually there. It's just not purple anymore and it is aligned to the right instead of left. You probably have missed it, which might indicate we should give it a little more **contrast**.

![Desktop](https://user-images.githubusercontent.com/10351013/68338110-8f880b80-00c0-11ea-9ad2-c85647d3ea7d.png)
