### ISSUE TITLE
Prediction market ontology

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#445]
This idea seems very useful to me, although it'll probably not make it into v1.0 of augur: https://github.com/joeykrug/essays/blob/master/ontopreds.md
...

@tinybike what action needs to be taken?
 -Chwy5
...

Closing since the link is broken and the purpose of this ticket is unclear.
 -adrake33
...

Reopening this ticket since @tomhaile sent me an updated link.
 -adrake33
...

Main time this becomes useful is if we do the first dispute api stuff I’ve been talking about in discord --- can discuss further whenever you guys want

 

 -joeykrug
...

Assigning this to Alex/Austin for further consideration.
 -adrake33
...

What work for this would actually be something we would do? I'm not sure exactly how contracts would come into play here specifically since this is labeled as a backend issue.
 -nuevoalex
...

Yeah, this ticket doesn't really seem like it should have been set as Backend. It sounds more like an Augur Node/frontend issue.  If you think this is something you'd prefer to postpone, I'll just move it to the backlog.
 -adrake33
...

Actually, I suppose it could potentially affect the contracts if we wanted certain elements of the market description to be stored in a certain way on the blockchain, and then those elements could be passed by Augur Node to the frontend so that multiple languages could be supported. I'm not entirely sure what Jack had in mind here, though.
 -adrake33
...

The extraInfo field of the market could already support storing this information.
 -nuevoalex
...

Yeah, true. In that case, this wouldn't require contract changes. I'll change this to a Frontend issue.
 -adrake33

**Comment by bthaile** [comment]
@joeykrug @pgebheim can this be closed?
