### ISSUE TITLE
volume, default format for big numbers?

### ISSUE THREAD

**Issue by RonB7139** [AugurProject/augur#445]
![shares](https://cloud.githubusercontent.com/assets/16419551/13718253/5866c9f6-e7b6-11e5-98cf-42602d6b4387.png)
![shares2](https://cloud.githubusercontent.com/assets/16419551/13718255/59e8c900-e7b6-11e5-98d2-2513e8dab3f4.png)

**Comment by joeykrug** [comment]
How many shares did you try to buy?

**Comment by RonB7139** [comment]
***I think .ooo1***

**Comment by joeykrug** [comment]
Then the UI is wrong entirely there, it says you bought ~0.00000001

**Comment by RonB7139** [comment]
tried to repro the issue but cannot buy another share

**Comment by tinybike** [comment]
I think this is fixed in 6f6a433a276e1e250538f79274cd9c714a6e5d13.  Re-open this if this re-surfaces...
