### ISSUE TITLE
Trading pg order ticket displaying wrong info to user

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#4450]
To reproduce cat 2 market + invalid
sell 100 of outcome A (trade it not place open order)
then go sell 600 of outcome B

Order ticket shows closing a 100 share position in outcome B and opening a new selling position of 500 in outcome B
This should only display opening a position for short 600 in outcome B

***The max cost of XXX dai will be escrowed (under the total order value)  should account for the shares being used

**Comment by bthaile** [comment]
I tested on cat 6 market. 
sold 10 @ .3 of outcome A.
in order form short 60 @ .3 of outcome B. 

confirmation says
`Max cost of 42.00 will be escrowed.`
New Position
Selling 60 shares @ 0.3

Is the issue that max cost should say 35,  (42 - 7 shares cost from first shorting)

I see the issue, UI doesn't know the user's share balances, only the synthetics.

**Comment by Chwy5** [comment]
working better- closing
