### ISSUE TITLE
Frozen Funds missing 

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#4452]
I had an open position that is now resolved.

My Frozen funds had been displayed for a few days no longer appears.  MY availabale balance and total balance are visable (minus the missing frozen funds).  The market i hold an open position in, is now resolved.  The amount I am missing is the FF from that market.  I still have not claimed my winnings yet.

Refreshing does not make the FF return

-- further investigation
User's frozen funds doesn't update unless they have a position. Open orders doesn't contribute to FF. seems to be a bug in SDK.

**Comment by Chwy5** [comment]
Still missing for me...see screenshot attached.  They were there yesterday and now disappeared again.

I have 2 open positions....so should have Funds frozen against it...see screenshot

[Uploading... 11-8ff.jpg ]

**Comment by bthaile** [comment]
does this ticket still need to be worked @Chwy5
