### ISSUE TITLE
Togglable odds

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#447]
Someone requested a toggle between standard PM odds (e.g. 50%) and standard wagering odds (e.g. http://www.wikihow.com/Read-Odds) (e.g. 2-1)

...

can also add UK, decimal, US style odds too
 -joeykrug
...

@sprinkle Is this still something we want to consider doing in the future?

Archiving for now, please unarchive if we want to keep and let me know.
 -sharkcrayon
...

Why would we archive one of the most requested features?
 -joeykrug
...

Unarchiving and placing in peccary for review during the next release planning.

...

Right, this is definitely something we want to include -- as Joey says, it's a request we've gotten consistently since the earliest alpha release -- although it won't be until after MVP.

Re: different types of odds, I'd keep this simple to start with, just use the common "2:1" odds format.  If there are a lot of requests for alternative displays we can address those then.

...

:thumbsup: 

...

@chwy Is this something we need to do?
 -bthaile
...

This should be part of a new epic for the betting style interface that’s enable/disableable via a settings page in the account section. I wouldn’t implement it separately apart from that. When we’re ready for this I have a bunch of ideas for how the UI should look and can sketch it out when we’re ready 
 -joeykrug
...

Closing for now. Feel free to reopen if necessary, @joeykrug.
 -adrake33
...

Just gonna put in backlog so we don't forget about it
 -joeykrug

**Comment by joeykrug** [comment]
It's in the exchange UI mocks
