### ISSUE TITLE
Modify PriceTime Data

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#4479]
<img width="1244" alt="Screen Shot 2019-10-29 at 12 01 10 PM" src="https://user-images.githubusercontent.com/10524630/67790554-f6b01b00-fa43-11e9-95fb-979348a2766b.png">

So the issue here is on this market there was a bunch of trades for no (pink) then a bunch of trades for Yes (green). We have gaps in our price time data however, time passed but there was no change on these outcome lines. Because of this, we have gaps. We want to have a straight line in this case that just maintains the previous price. We need to devise a proper way to indicate that no price has changed but still add data to the chart basically showing 0 change in price.

**Comment by JohnDanz** [comment]
Best way to go about this is to modify the select-bucketed-price-time-series.ts selector it looks like. Basically we need to make sure that each outcome has a value for every timestamp we have. it should use the previous price data if there is no data for that outcome. All outcomes should start at 0.

example:
Yes/No market:

Let's say that hour 1 has YES trade that completes at .6
then hour 2 has YES trade that completes at .8

then hour 3 has NO trade that completes at .2

then hour 4 has a NO trade that completes at .3

then hour 5 we have an invalid trade at .5

current implementation would return:

YES: would have 2 data points for hour 1 and 2 respectively and that's it.
NO: would have 2 data points, hour 3  and 4 respectively and that's it.
Invalid: would have 1 data point, hour 5.

What we would need is all 5 of these outcomes having 5 data points.

YES would need to be .6, .8, .8, .8, .8 (since there was no change since hour 2)
NO would need to be 0, 0, .2, .3, .3 (0 is what you get prior to any action, then by hour 5 there was no change from hour 4)
Invalid would need to be 0, 0, 0, 0, .5 (again, 0 prior to any trades then by hour 5 we get a new value)

**Comment by bthaile** [comment]
can you just remove the buckets that don't have a trade price? note: can't have zero to represent not trades b/c of scalars, zero might be a valid price.

**Comment by JohnDanz** [comment]
The buckets already don't exist if they have no price, that's kinda what I wanna fix so that the lines are always shown and not just starting somewhere on the chart and potentially stopping before the end of the chart. If we don't care about that I can just close this then. What we would need to do if we do want to always show lines is just use `minPrice` instead of 0, the 0 was just a yes/no example
