### ISSUE TITLE
Market refreshes with answer #'s instead of the actual answers

### ISSUE THREAD

**Issue by housemobile** [AugurProject/augur#448]
Sometimes after placing a bid, when the market refreshes, instead of seeing the actual answer choices, it shows 1, 2, 3, 4...

http://i.imgur.com/ZZ0GIE7.png

![marketrefresh](https://cloud.githubusercontent.com/assets/17286590/13723583/84af55d8-e837-11e5-9855-0e746815a6f4.png)

**Comment by tinybike** [comment]
Fixed in 997ff90f1945709c162e364e136162e2a0dac26e.
