### ISSUE TITLE
Consider adding Markdown support for Additional Details

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#448]
User request from aaaaaaaaaa:

Oh, hey, kind of on a tangent. But if we're thinking of asking for more comprehensive additional details, is there any way we can get markdown formatting or something? Plaintext is not super great sometimes

Micah’s comments:

Markdown would be cool, but we have to be careful about people creating market descriptions that can be rendered in multiple ways.

e.g., if one browser or viewer or client renders the text in one way and another renders it a different way and the differences are enough to change the description then someone can attack reporters that way.

This is _already_ a problem with Unicode support, since there are a ton of non-printing characters, and characters that look like other characters across the space and they render differently depending on font used.

————-

To-do’s for this task:

- research whether the attack Micah brought up can be done with Markdown
- if you’re reasonably confident that it can’t, discuss with the team what Markdown rules we want to allow in the Additional Details
- implement those rules

**Comment by phoebemirman** [comment]
I tested a few different browsers and os, as well as researched online a bit and have not seen any differences in markdown rendering. Especially for the more basic ones that I think people would actually want to use for additional details. 

So, I was thinking we could start with these basics like bold, italic, and underline. Are there others that we think could be useful? Another popular one is strikethrough but that seems like it could cause confusion, not sure if it has a use case. 

Other possibilities that I could see being useful are block-quotes, tables, and code snippets. These are more likely to have some slight variation between browsers but just in terms of spacing really. For example, tables has slightly different margins looking at internet explorer. 

@serena @matt-bullock

**Comment by bthaile** [comment]
https://css-tricks.com/choosing-right-markdown-parser/

here are some markdown parsers we could consider. That way we don't have to write our own.

**Comment by phoebemirman** [comment]
i was looking at this https://github.com/rexxars/react-markdown

**Comment by sharkcrayon** [comment]
Bold, italic, and underline seem like a good start. 

Here are my thoughts on what to include and not include:

Include:
- bold, italic, and underline
- ordered and unordered lists
- linebreaks
- horizontal rules (maybe)
- headings (maybe - and if so, we have to decide how they should be styled)

Don't Allow:
- block-quotes
- tables
- code snippets/html
- links (they could use trustworthy looking text like [www.cnn.com](www.fake-malicious-site-wfnjwnedf.com) and then link somewhere malicious)
- videos
- images

**Comment by bthaile** [comment]
React-markdown looks like it would work. I agree with not allowing images and video, good call on not allowing links. 

I like block quotes and embedded html and tables, no javascript code execution of course. 

Second thought, seems the more options we allow the harder the problem making sure there is no malicious attack vectors. 

Also we’d have to make sure UI can show only part and allow user to “read more” so the text/markdown doesnt flood the UI.

**Comment by sharkcrayon** [comment]
Tables would get in the way of that, and I can't see a situation in which a market creator would need to quote something in a special format. They're not writing an article, after all. Embedded HTML seems unnecessary to me - why would this be useful when describing the constraints of a market?

**Comment by phoebemirman** [comment]
I agree with Serena and think that bold, italic, and underline, ordered and unordered lists, and linebreaks (we already have). Don't really see uses for the others mentioned. 

Another thing to mention is that markdown is interpreted different by different parsers so ours will look the same on browsers still but some people might be used to writing it a certain way and ours might treat that differently. this shows those differences https://babelmark.github.io/. React-markdown uses Github Flavored Markdown.   

We might also want to add a preview of the details on the page where they are being added, here:

<img width="1518" alt="screen shot 2018-12-12 at 3 32 03 pm" src="https://user-images.githubusercontent.com/6775839/49905604-3a496880-fe23-11e8-855c-9297600a5c05.png">

**Comment by bthaile** [comment]
I definitely advocate having a market preview before the user creates the market. The preview should show market trading page header and market card. So user isn’t surprised after they create their market.

**Comment by phoebemirman** [comment]
there is one on the review screen, but having one, in addition to this, next to where you write out the details would be helpful.

**Comment by phoebemirman** [comment]
> Also we’d have to make sure UI can show only part and allow user to “read more” so the text/markdown doesnt flood the UI.

that shouldn't be a concern because "read more" cuts off the div overflow so things are already rendered, not the actual/raw text

**Comment by sharkcrayon** [comment]
I agree we should have a preview of the Additional Details. A preview of the entire Trading page header is overkill.

@phoebemirman Can you put the preview to the right of the Additional Details input box, splitting that space similar to how Categories and Suggested Categories is currently split? The heading for right side can be "Additional Details (Preview)".

Let me know if that makes sense or if you want a mock. If it's clear enough you can do it and then post a screenshot here.

**Comment by phoebemirman** [comment]
that makes sense to me

**Comment by phoebemirman** [comment]
<img width="1222" alt="screen shot 2018-12-13 at 3 34 31 pm" src="https://user-images.githubusercontent.com/6775839/49974094-9d530200-feec-11e8-840d-09f2bb2703e5.png">

here is a screenshot

**Comment by bthaile** [comment]
I recommend using the same component to preview user's `additional details` that the market header uses. that way the user gets an accurate preview and we save coding.

Also, I think it's important the market creator sees where the <read more> cuts off their additional details. This will allow them to make sure important information is "above the fold". Which can be important to sell/promote their market to traders browsing.
