### ISSUE TITLE
change up login dropdown animation slightly

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#449]
https://framer.cloud/WAdpj/

animation notes:

<img width="485" alt="screen shot 2018-10-01 at 8 53 08 am" src="https://user-images.githubusercontent.com/11491365/49621367-cff37c80-f979-11e8-91b7-39b7aec3c940.png">

**Comment by phoebemirman** [comment]
@matt-bullock 
should this be implemented still? wanted to check because it is a bit old

**Comment by matt-bullock** [comment]
Can leave this for now as it may change slightly with the redesign. I'd like us to refine the interactions when we implement the new design
