### ISSUE TITLE
Analyze blocking requests in the UI and create issues as appropriate for any methods causing delays in rendering

### ISSUE THREAD

**Issue by nuevoalex** [AugurProject/augur#4495]

**Comment by bthaile** [comment]
todo: 
1. create a specific load testing flash script that creates as many zeroX orders as fast as possible. add a throttle param to limit X number of orders per second. 

2. create script that creates X number of trades for specific user. 

3. create script to add X number of open orders for a specific user.

**Comment by bthaile** [comment]
Currently there are these scripts
1. `simple-orderbook-shaper`
Runs continuously creating orders on each side until required amount of orders is met. Will maintain orderbook if order(s) have been take or if existing order falls below quantity of 100. 

2. `create-yesno-zerox-orders`
`create-cat-zerox-orders`
`create-scalar-zerox-orders`
Creates 3 orders on each side of book and exits.

3. `take-orderbook-side`
takes best order of a side every second. Its configurable to increase delay between trade. Or limit number of trades it makes. Or can take continuously until killed.

**Comment by pgebheim** [comment]
Closing as not particularly actionable. We've been testing and investigating issues as they occur.
