### ISSUE TITLE
Change canned markets to use relative time

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#450]
So things don't change depending on when dev-pop-geth is deployed

/cc @justinbarry @tomhaile
...

@tomhaile What does relative time mean here? Is this the user's timezone?  Also, what priority would you give this?
 -adrake33
...

oops, this is devOps, when canned markets are created when contracts are deployed we need to make sure we are creating markets in the future. 

@adrake 
 -bthaile
...

@tomhaile Ok, thanks for clarifying.
 -adrake33

**Comment by bthaile** [comment]
done closing
