### ISSUE TITLE
disputing form errors

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#4500]
'null' is showing up in the text input when typing. 

doing ".1" which should result in an error because it is not in tick size range. the error does not show up but the confirm is disabled. 

also clearing the ".1" for the outcome clears the rep amount as well. 

seeing these on scalars

**Comment by pgebheim** [comment]
@phoebemirman -- can you confirm if this is still happening?

**Comment by phoebemirman** [comment]
not happening
