### ISSUE TITLE
 not send referrer to external destination

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#4504]
this for links in Augur that are external. 
and to not send the Augur web location to the external destination

https://stackoverflow.com/questions/5033300/stop-link-from-sending-referrer-to-destination

**Comment by bthaile** [comment]
@bconfortin  can you add the needed tags.

**Comment by bconfortin** [comment]
Yeah, I can @bthaile

**Comment by joeykrug** [comment]
status?

**Comment by bconfortin** [comment]
This is done @joeykrug

**Comment by Chwy5** [comment]
closing
