### ISSUE TITLE
Market creation: (additional rule) Updated rules section on top of form 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#4510]
The rules section has two updates: 
1. New copy that lists out the rules [the copy](https://docs.google.com/document/d/1lLi6BxdhITvrpTgkz9t4ZJRTzeGpL31J-zH5_MkJj-w/edit?usp=sharing)
2. Styling has been updated 

To be applied on both custom/template flows. 

Custom: 
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=2788%3A3

Template: 
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=2771%3A9222

```
A market is invalid if: 
The market question is subjective in nature.
The result of the event was known at market creation time.
The outcome was not known at event expiration time.
The title, details and outcomes are in direct conflict with each other.
There are strong arguments for the market resolving as multiple outcomes, unless it is explicitly stated how the market should be resolved in resolution details.
If using a resolution source (a source is a noun that reports on or decides the result of a market), the source's URL or full name is NOT in the Market Question, regardless of it being in the resolution details.
If using a resolution source, it is not referenced consistently between the Market Question and Resolution Details e.g. as either a URL or its full name
If it’s a stock, currency or cryptocurrency and its ticker is not used in the market question.
If it’s an index and the indexes full name is not in the market question.
A market only covers events that occur after market creation time and on or before reporting start time. If the event occurs outside of these bounds it has a high probability as resolving as invalid. 

At market creation time, it was known that one or more of the outcomes can't win
The market question can still finalise…
If you make a market that’s not in the correct league for team/players at market creation time then the market is invalid 
If there is 1 or more outcomes that can’t win, if a winner can be determined from the remaining outcomes, should it resolve invalid? 

```

**Comment by bthaile** [comment]
moving this to blocked until ready.

**Comment by cillianhunter0** [comment]
The copy: 
* The market question is subjective in nature.
* The result of the event was known at market creation time.
* The outcome was not known at event expiration time.
* The title, details and outcomes are in direct conflict with each other.
* There are strong arguments for the market resolving as multiple outcomes.
* If you’re using a resolution source and its full name or URL is not in the market question or, it's not in the market question but is in the resolution details.
* If it’s a stock, currency or cryptocurrency and its ticker is not used in the market question.
* If a market falsely claims to be a template somehow but isn't a template.
* A market only covers events that occur after market creation time and on or before reporting start time. If the event occurs outside of these bounds it has a high probability as resolving as invalid.

**Comment by Chwy5** [comment]
Please add an additional rule:

For any sports market that lists a player or team not in the correct league, division or conference, at the time the market was created, the market should resolve as invalid.
