### ISSUE TITLE
Market creation: styling+copy tweak to any template that has preset rules 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#4515]
Figma: 
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=2771%3A9222

If a template has any preset / unchangeable rules. I have tweaked the styling so it doesn't appear like you can uncheck that rule. It's read only etc.

The heading "Added resolution rules" -> "Template resolution rules" 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/2ccc969b-70b5-43ed-b229-fb5489eda22e)

**Comment by bthaile** [comment]
this ticket will address <https://github.com/augurproject/augur/issues/4568> this issue
