### ISSUE TITLE
Market creation: remove "resolution details" from template markets 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#4516]
We're removing the "resolution details" section from all template markets. 

IF there are predefined rules on a market template, a new section appears called "Template resolution rules". 

IF there are no predefined rules, no new section appears. 

Figma: 
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=2771%3A9222

**Comment by bthaile** [comment]
redundant ticket, closing
