### ISSUE TITLE
Add settlement/clearing time comparison to traditional markets after a trade succeeds

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#452]
Something like: "Your trade just settled [3 days in seconds / seconds trade took to be confirmed] times faster than it would've on Wall St."

**Comment by tinybike** [comment]
"Your trade just settled 100,000x slower than it would've if we were using a regular database."

**Comment by joeykrug** [comment]
Sounds like a slow db

**Comment by tinybike** [comment]
@priecint IMO the way to do this is just to calculate the time it took to execute the trade (`new Date().getTime()` before and after the trade sequence is probably the easiest way), then express 3 days as a multiple of whatever that duration is.

**Comment by joeykrug** [comment]
meh - superfluous ;)
