### ISSUE TITLE
Implement universal redemption

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#453]
Right now the way we redeem stake is by redeeming on a per token basis. This takes a lot of tx signing.

There is actually a method exposed which lets us redeem multiple ReportingParticipant contract's stake in one tx: https://github.com/AugurProject/augur-core/blob/master/source/contracts/reporting/Universe.sol#L461

The real complication here is that because of gas limit constraints we only want to do a certain batch size per tx still. The likely best way to do this is to start off redeeming some base (like 3) number of items then iteratively add and estimate the gas that will cost and if it surpasses a threshold use the last number and then begin a new tx with another batch.

In many cases this will reduce the number of total txs to one but we'll still have to do multiple for users with a ton of varied stake across many markets.

This task is for both middleware & UI changes. There shouldn't be much input needed from Design on this, but if there are questions, please check with Serena/Matt.

**Comment by bthaile** [comment]
We could have a list of all the contracts the user can redeem.
v1 they can redeem participation tokens as well as dispute/initial reporter contracts.
v2 only dispute/initial reporter contracts.

We already have market cards on the portfolio:reporting page. It would be better to replace those with a list of contracts they can redeem against.

I see two options:

Group/Batch:
Showing a list, each list item would have; market title, amount of REP staked and what type of contract (initial report, dispute, participation [v1]) and at what time or block the REP was staked and the amount of ETH they get when they redeem. Amount of ETH is only know when the associated market has settled or the FeeWindow has ended. If those events haven't happen then the list item isn't redeemable (button is greyed out) and the ETH balance can't be shown.

The user could select all contracts they want to group redeem, then go to a confirmation screen, there the estimated gas would be displayed with their totals of REP and ETH. That way the user can decide if the transaction is worth the cost. As a side note the user can adjust their global gasPrice to tweak time/cost ratio.


One at a time:
There would be a redeem button for each item in the list. The user can just redeem one contracts at a time or only the profitable ones based on current gasPrice or user urgency.

**Comment by matt-bullock** [comment]
Is this now covered in the new claim stake and fees modal?

**Comment by pgebheim** [comment]
@Chwy5 @justinbarry @nuevoalex 

I'm not sure if this is handled for v2 or relevant anymore? Anyone shed some light on this?

**Comment by nuevoalex** [comment]
The contract portion is implemented

**Comment by joeykrug** [comment]
So what's the next step then?

**Comment by bthaile** [comment]
this batch strategy has been impl for order liquidity (which isn't needed with 0x trading) but we have the pattern. 

Claiming winnings modal needs to be hooked up to call SDK to claim winnings (which is just a pass through to contract call). We have a path forward and I don't see any blockers.

**Comment by pgebheim** [comment]
@bthaile - is this accounted for in the work breakdowns for the specific pages?

If so we can close this as a design task

**Comment by bthaile** [comment]
As a design ticket, its done.
