### ISSUE TITLE
Implement Use-or-Lose

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#454]
We need to change the forking UI to indicate that the user _must_ migrate their REP or they will be locked out of migration entirely. We also need to remove the stuff about receiving a 5% bonus as that is not longer the case.

**Comment by adrake33** [comment]
@JohnDanz FYI, there is an issue for creating a design spec for use-or-lose: https://github.com/AugurProject/augur/issues/491. Alex didn't think this would require much input from Design, but if you do have questions about this, please check with @sharkcrayon and @matt-bullock. You can also start on any middleware changes in the meantime.

**Comment by sharkcrayon** [comment]
I agree that this should just be a text change.

**Comment by JohnDanz** [comment]
@matt-bullock Can you provide me with the updated text that I'll need to make for this change?

**Comment by adrake33** [comment]
@JohnDanz I talked with @matt-bullock some more on this, and we decided it would make more sense to make the UI changes for this once the forking UI has been redesigned. I'll move this to the backlog for now. Please feel free to choose a different task to assign yourself for next week.

**Comment by pgebheim** [comment]
Design implemented 

![image](https://user-images.githubusercontent.com/86010/64464168-d5722480-d0bb-11e9-857a-78ccccb3f80c.png)

Will be implemented in dev along with #2967
