### ISSUE TITLE
depth chart crashes

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#4540]
![Screen Shot 2019-10-31 at 4.05.22 PM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/933e8f91-151d-4df0-8300-33ff78dbfb53)

got this when on depth chart tab and resized the window to be larger. there is no error msg above

**Comment by pgebheim** [comment]
@JohnDanz fixed this today.
