### ISSUE TITLE
Add sharing to market cards

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#4547]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/672bb20c-4eef-4bd0-88ec-f2d8025a000d)

Design:
https://www.figma.com/file/Do4qnkCNM8P7lwBmCdYZCS4X/Market-Cards?node-id=3026%3A1210

Replace the 3 dots menu with the share button.

Clicking this share icon brings up an item list menu
Ignore all other styling that is in the item list design until finalised (grey colour etc)

Use same icons from market list page. Icons are 16px x 16px

**Comment by joeykrug** [comment]
@andrewdamelio wanna do this one?
