### ISSUE TITLE
Trading on expired/matured markets

### ISSUE THREAD

**Issue by housemobile** [AugurProject/augur#455]
All markets should be tradeable until it enters the reporting phase

**Comment by thinkloop** [comment]
Are markets allowed to be traded during reporting, so people can liquidate for a small spread, without waiting for full report?

**Comment by joeykrug** [comment]
Markets are tradable 24/7 no matter what

**Comment by tinybike** [comment]
Added in 250a316794b0d60b4297639b2d76dcb892c8fa6a
