### ISSUE TITLE
Market-View-Resizing

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#4572]
If you try and shrink the window on the trading page, without hitting a breakpoint to switch the view to a different size (desktop to tablet for example) the left side of the page doesn't shrink and the right column overflows off screen. Things should shrink back down to min size if we resize the window.

Example, say your width is 1920px, and you try and shrink the window to say 1500, the page doesn't shrink responsively as you might expect.

Before (1920 width):
<img width="1920" alt="Screen Shot 2019-11-04 at 12 53 02 PM" src="https://user-images.githubusercontent.com/10524630/68148688-19d64100-ff02-11e9-8ec5-8d435cf1828c.png">

After (1403 width):
<img width="1403" alt="Screen Shot 2019-11-04 at 12 53 09 PM" src="https://user-images.githubusercontent.com/10524630/68148715-2490d600-ff02-11e9-8ad3-f38565256e3c.png">

**Comment by pgebheim** [comment]
@JohnDanz Added to the charts epic so that can be the main place to look for charts issues.

**Comment by joeykrug** [comment]
status?

**Comment by JohnDanz** [comment]
https://github.com/AugurProject/augur/issues/5620

**Comment by JohnDanz** [comment]
Done.

**Comment by matt-bullock** [comment]
looks good. closing
