### ISSUE TITLE
Feature: Reliable Log Fetching in the Face of Lying Nodes

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#4577]

**Comment by pgebheim** [comment]
In block streaming mode the algorithm needs to work like this:

We keep track of the last block we encountered an augur log: L
We get notified of a new block B

We turn around and request logs for blocks (L, B] matching our filters.

One of two cases occurs:
  - we get logs returned, in which case we know the node we spoke to has logs for that block and would have any known logs for blocks before B. 

So we then take all logs from that range, and write them. We know any blocks with no logs do indeed have no data for augur.

We then update L to be B.

  - we get [], which means either no logs matched the filter, or the block didn't exist on that node.  In this cAse we don't commit the empty block, nor tell the UI a change was made.

**Comment by justinbarry** [comment]
![image](https://user-images.githubusercontent.com/328965/69100493-2a161200-0a12-11ea-82ed-574d7307d6cd.png)

**Comment by pgebheim** [comment]
Looks right
