### ISSUE TITLE
Doesn't load on the latest [old] windows version of safari

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#459]
From 2013, but should still work on a multitude of browsers

**Comment by joeykrug** [comment]
TypeError: 'undefined' is not a function (evaluating 'p.sortOptions.find(function (opt) {
                            return opt.value === p.selectedSort.prop;
                        })') 

is the error

**Comment by tinybike** [comment]
Is Safari on Windows maintained?  From the first few Google links it looks like it was abandoned by Apple a while ago.  If that's the case, I'm not sure this is worth supporting on our end.

**Comment by joeykrug** [comment]
Per OP it's not maintained
