### ISSUE TITLE
Hotloading categorical market

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4596]
getting this error when hotloading categorical market

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/088abee0-0287-4d49-b618-1e48a08b7db4)

weird because the outcomes are there

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/e4032504-6fc9-45b1-9c1a-5d244579c038)

**Comment by nuevoalex** [comment]
Guessing numOutcomes is incorrect then
