### ISSUE TITLE
adjust spacing trading page mobile

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#4598]
<img width="375" alt="Screen_Shot_2019-11-05_at_3 12 29_PM" src="https://user-images.githubusercontent.com/10524630/68247704-fcc46f80-ffe0-11e9-9a55-84618d6edc40.png">
This should be adjusted to have a bit less padding on the outsides of the text and add a small amount of padding to the middle section between the 2 columns of values. maybe something like this:
<img width="334" alt="Screen_Shot_2019-11-05_at_3 14 03_PM" src="https://user-images.githubusercontent.com/10524630/68247759-182f7a80-ffe1-11e9-9016-294391870f72.png">

**Comment by matt-bullock** [comment]
It should look like this for mobile. This should remove any of those issues

Design:
https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=449%3A925

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/a67233f7-adbc-454e-a3c0-dc46f0ecc592)

**Comment by matt-bullock** [comment]
closing as there's a new ticket for handling this
