### ISSUE TITLE
Disclaimer: scroll bar on mobile

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#4608]
Testing mobile in chrome on OSX. The scroll bar is huge. Not sure if this is the same on actual mobile as build was having issues, couldn't access it. 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/2ce6e43d-7a9e-483a-8fa7-712892b36eb7)

**Comment by andrewdamelio** [comment]
@cillianhunter0 try again on your device - should be 👍 
(try chrome private tab)
