### ISSUE TITLE
Augur doesn't load when emulating mobile.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4627]
This seems weird, but I see the same behavior when testing from mobile device. UI doesn't load when chrome is in mobile emulation. When chrome is in regular desktop mode the UI runs fine.

Looks like loading just stops with `Syncing user-specific log DBs`

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/81e1fa31-5e00-43f1-bfb6-b99dbae08f12)

Issue is SEOConnector is loaded when UI is in mobile mode running on mac. `isMobileSafari()` returns true in augursdk.ts

**Comment by bconfortin** [comment]
I believe this was fixed after removing an "await" on SEOConnector.
