### ISSUE TITLE
ML: add "template" filter 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#4631]
Figma: 
https://www.figma.com/file/GKhft5ZOwuH3ANrupGNCLHUU/Market-list-page?node-id=1331%3A1474

Add a new filter to the top of the filters section. 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/d2030de4-b9a6-4768-82e5-672a4010fcde)

Label: 
Markets

Tooltip: 
There are two forms of market on Augur:

**Augur templates** provide market creators with a set structure for popular markets that reduce the potential for error during market creation.
 
**Custom markets** are fully open and don't follow a set pattern/structure, as a result they are more likely to contain potential issues and should be examined carefully before betting.

Option 1: 
Show all 

Option 2: 
Augur templates

Option 3: 
Custom markets

**Comment by pgebheim** [comment]
@bthaile -- Will you do this or should it go to Phoebe for the market list page?
