### ISSUE TITLE
ML: Category issues - desktop 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#4632]
CATEGORIES 
- [x] On a large monitor the bottom of the panel is a different colour, needs to match up, example from build: **HIGH**
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/233104a1-8e08-4461-a62e-bb4873bd43a0)

- [ ] Categories/filters panel should not scroll by itself, it should just scroll with the page @phoebemirman is this something we can quickly switch on/off? **HIGH**
- [x] Top 5 category icons, crypto, sports and politics are not correct [Figma](https://www.figma.com/file/GKhft5ZOwuH3ANrupGNCLHUU/Market-list-page?node-id=1342%3A6) **HIGH**
- [x] Categories have no hover states, see text link states here [Figma](https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=8219%3A265631) **LOW**
- [ ] Style updates to category items: [See states in Figma] (https://www.figma.com/file/GKhft5ZOwuH3ANrupGNCLHUU/Market-list-page?node-id=1343%3A1618) **HIGH**
   - [ ] See panel 1 on figma - category text style in the default state are bold 
   - [ ] See panel 1 on figma - styling to the default state of the count for each category has been updated (new text colour, fill colour and border added) 
   - [ ] See panel 2 on figma - styling to the active state of the count for each category has been updated (same as above with new text colour) 
   - [ ] See panel 2 on figma - when a category has been selected, only the active category text is bold, all other categories use regular text style 
- [ ] When I select a category, it should be left aligned with "category" text above, currently it's indented slightly, example of this in the build: **HIGH**
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/18acd92d-c847-46e1-84f2-e6cfb26f11d5)
- [ ] When I select a category, the alignment of the categories doesn't match the alignment from the default state, and the back arrow icon should be centre aligned with the category icons, see example of this in the build: **LOW**
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/173dc31a-4723-494b-9658-3c88c0ff6f1f)
- [ ] When I select a category, the counts are not the same distance from the right side of the column, they have moved in a few pixels, they should be the same **HIGH** Example from build: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/5da62331-ef81-4952-b3fc-b54a55f4d942)
- [ ] The "+ Show more (2)" link colour needs to be changed to "text primary" or E0DFDF **HIGH**
- [ ] The "+ Show more (2)" link is missing a hover state **LOW**
- [ ] When I click the  "+ Show more (2)" link, the link disappears, it needs to update to "- Show less" which then collapses the list back up **HIGH**

**Comment by cillianhunter0** [comment]
The first 3 issues mentioned here are not fixed. Any update on these 3 @phoebemirman ?

Everything else are styling related and have been replaced by another ticket.

**Comment by phoebemirman** [comment]
ill check out the first one and the others we can keep in backlog
