### ISSUE TITLE
ML: mobile - can't scroll to bottom of the filter menu 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#4636]
The 'invalid' filter is getting cut off, tested on safari on ios and chrome on mac OS: 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/c68bc968-49da-451a-8f33-2b36004aa620)

**Comment by cillianhunter0** [comment]
Still not working for me on iOS mobile

**Comment by matt-bullock** [comment]
Filter menu is now scrolling off the screen. It should be fixed to the mobile screen height.

**Comment by cillianhunter0** [comment]
Looks fixed when testing using inspector on chrome. But can't check the build at the moment on my phone, keeps crashing.

**Comment by matt-bullock** [comment]
When the menu is open I'm able to scroll the page behind the the menu. We should disable this from happening
