### ISSUE TITLE
ML: Mobile - top section of page  

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#4638]
TOP SECTION OF PAGE ON MOBILE:
Search input, filter button, views button, filter tags etc 
[Figma](https://www.figma.com/file/GKhft5ZOwuH3ANrupGNCLHUU/Market-list-page?node-id=1331%3A3936)
- [x] Update search box style / size to match figma **HIGH**
- [x] Update filter button to match component on figma **HIGH**
- [x] Update page title to match figma style/color **HIGH**
- [x] Update view buttons to match figma **HIGH**
- [x] Update market status tabs to match figma **HIGH**
- [x] Update applied filter tags to match figma **HIGH**
- [x] Vertical spacing between elements to match figma **HIGH**

Comparison: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/5629ca5c-1ecd-42b5-ad67-516b2a737743)

**Comment by JohnDanz** [comment]
@rubyweb3 when you are working a ticket like this make sure to move it to the `in progress` pipeline. Also when you make a PR that is related to this ticket please place the URL for this issue as a link inside the PR description so we can quickly link back to the issue if need be.

oh and try and provide an estimate value -- this is a personal interpretation of how hard/long you think the ticket will take you to complete fully. the more work the higher the number should be assigned. This is just for our internal burn down charts and to have a general idea at a glance to how much work still remains overall and how quickly we are finishing it. I think most people go by the rule of if something is going to take a full work day, it should be a ~8 point estimate, but the estimate is up to you in the end.

**Comment by rubyweb3** [comment]
Build on branch ruby/trading-page-input
![Screen Shot 2020-01-30 at 6 36 00 PM](https://user-images.githubusercontent.com/58647954/73442452-d324a580-438f-11ea-8a35-bb5cccfd07bd.png)

Design:

There is an additional help icon when the web app is loading. How are we going to handle it?

**Comment by rubyweb3** [comment]
If we hide the help icon even when the web app is loading:
![Screen Shot 2020-01-30 at 6 43 19 PM](https://user-images.githubusercontent.com/58647954/73442811-74136080-4390-11ea-9607-d1e65ed3547b.png)

**Comment by cillianhunter0** [comment]
you can hide the help icon when logged in, it appears in the slide out menu

**Comment by JohnDanz** [comment]
if we aren't logged in and it's finished loading, will it look crappy? we need to make sure nothing overflows in general 

Ideally that link to betting ui coming soon should also push down content a slight bit to leave space so it isn't bleeding above the search bar

**Comment by cillianhunter0** [comment]
> if we aren't logged in and it's finished loading

i don't follow, how does loading make a difference? if not logged in there should be a help icon, if logged in there shouldn't be one etc

**Comment by matt-bullock** [comment]
Help icon should appear only on the menu when logged in 

But when logged out the help icon should appear on both the menu and top bar. This is so it's more visible to first time users

![image](https://user-images.githubusercontent.com/39496225/73471621-f187a280-4389-11ea-87fc-6708fd01377e.png)

![image](https://user-images.githubusercontent.com/39496225/73471815-43302d00-438a-11ea-9cad-44b3b88dd26b.png)

**Comment by matt-bullock** [comment]
looks done. closing
