### ISSUE TITLE
Good example of pnl issues

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#464]
https://www.dropbox.com/s/aabmxh5mfouhvrb/do%20these%20numbers%20add%20up.jpg?dl=0

**Comment by joeykrug** [comment]
another example, bought 6k shares of trump and that's all, realized should be 0
![capture](https://cloud.githubusercontent.com/assets/5925937/13757394/381a470c-e9f2-11e5-86f9-46980f729313.PNG)

**Comment by tinybike** [comment]
Fixed in a3c5bb696a8ea39fbfcd081f9e2ddf8a4dd4b4ca.
