### ISSUE TITLE
Creating a market and providing pre-liquidity my orders do not appear in the market or in the portfolio under open orders

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#4641]
1. Used horse racing template created a multiple choice market, and added liquidity to a few of the outcomes.
2. market gets created
3. portfolio: My created markets,  don't get`view orders` button to create market liquidity

Only the market creation processes, but my orders do not show up on the market and open orders is empty as well in portfolio....(looks like my available funds only updated for the market creation.

I am using portis

not getting pre-liquidity button:
![image](https://user-images.githubusercontent.com/3970376/68418761-7b92e700-015e-11ea-8ff7-0896041f0380.png)

**Comment by bthaile** [comment]
this should be working, last I checked.

just checked against kovan. It's working

**Comment by Chwy5** [comment]
fixed - closing
