### ISSUE TITLE
ML: banner issues 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#4647]
Figma: 
https://www.figma.com/file/GKhft5ZOwuH3ANrupGNCLHUU/Market-list-page?node-id=1355%3A118917

- [x] Banner missing icon that appears below markets: "There are 21 additional markets outside of the current filters applied. Edit filters to view all markets" **HIGH**

- [ ] The padding around the same banner is too big. Needs to be reduced to be 24px from the cards. Also there's a large gap after it to reach the bottom of the page that can be reduced to 48px. This applies to desktop and mobile. **LOW**

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/b70d7908-f690-407a-b753-5b96dc3021a7)

~~- [ ] Remove "x" icon to close warning banner for desktop/mobile. Applies to desktop and mobile. **LOW**~~

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/f7d1d00a-ce02-4dcc-876b-00fd4771a686)

**Comment by cillianhunter0** [comment]
Banner still has large padding above it

Still seeing the x icon on the banner - is this non trivial to remove?

**Comment by phoebemirman** [comment]
Chwy wanted the x to stay there.

**Comment by Chwy5** [comment]
Need to keep the x so user can dismiss this message

**Comment by cillianhunter0** [comment]
@phoebemirman 
cool re: keeping the 'x' in the banner.

Can you replace it with the 'x' icon (it's way too small as is, can barely make it out) we're using with you can see in the liquidity tag above in this screenshot. And just make sure it's aligned centre vertically:

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/532112b2-d5ba-4985-8db8-5777ba344d8c)
