### ISSUE TITLE
Bug where outcome names disappear

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#465]
https://www.dropbox.com/sh/7nwn74p3rjshgg0/AAD3cuk7ZEdvXtSaEnIlGZ8Pa?dl=0&preview=Bitfinex+changes+to+1.jpg

**Comment by KenKappler** [comment]
I also get this.

**Comment by tyche78** [comment]
Ditto. It happened to me on the presidential election market after completing a trade.

http://imgur.com/4YexFVU

**Comment by tinybike** [comment]
Fixed in 997ff90f1945709c162e364e136162e2a0dac26e.
