### ISSUE TITLE
Registration improvements

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#466]
Registration should tell you how to move accounts across browsers / let the user know about that

**Comment by JohnDanz** [comment]
How should this be done? Right now when you register a new account it brings you to the login form with your secure id already in place. It also gives you the following message: 

"Success! Your account has been generated locally. We do not retain a copy. *It is critical that you save this information in a safe place.*" 

Should we change this to something about using the secureLoginID anywhere to login? That should be all that is required now. You can download the account keystore but you don't need to do that anymore to use your account anywhere. If you can remember or copy and paste your secureLoginID to any other device, enter your password and assuming you are using a hosted node then it should log you into the correct account. 

As a reminder the secureLoginID is simply an object containing the keystore and the name of the account that has been encrypted into a string.

**Comment by tinybike** [comment]
Hm, I see your point.  I think a prompt to download the keystore file would be good, along with a (short) explanation of what the file is (your encrypted key + decryption info) and a note that, if you need to use it, you can do so using our import account feature.

(Moving this off the MVP milestone.)

**Comment by joeykrug** [comment]
done
