### ISSUE TITLE
Breaking Changes to the MetaMask Inpage Provider

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#4664]
https://medium.com/metamask/breaking-changes-to-the-metamask-inpage-provider-b4dde069dd0a

**Comment by pgebheim** [comment]
Done for V1

**Comment by joeykrug** [comment]
is this done for v2?

**Comment by andrewdamelio** [comment]
To be done still - shouldn't be a big effort though

**Comment by joeykrug** [comment]
let's get it done
