### ISSUE TITLE
Implement DAI changes in Augur UI

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#467]

**Comment by epheph** [comment]
I am making these changes in two parts. The first is to treat cash as a standard ERC20 (without deposit/withdraw (which DAI doesn't support, of course)). Next step would be to actually change it into DAI.

These contract changes are sitting in a PR, but should not be merged until the UI is ready. No contract functions are payable any more, this includes:
- createMarket*
- createOrder
- publicBuyCompleteSets
- publicCreateOrder[s]
- publicFillOrder
- publicTrade
- publicTradeWithTotalCost
- publicFillBestOrderWithTotalCost

Additionally, some non-payable functions used to convertToAndFrom cash, such as cancelOrder, so you won't end up with eth back any more. everything stays in Cash.

The real bit here is that the UI will need to acquire or ensure the proper quantity of Cash prior to making the contract call. Where createMarket would forward along the `getOrCacheDesignatedReportNoShowBond` as eth, it instead needs to ensure that balance of Cash and not forward as msg.value
