### ISSUE TITLE
Positions disappearing

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#4670]
Yesterday I traded on 2 separate markets and had 2 positions (filled orders).

My Frozen Funds had shown up as well.  Today when I got back on, My FF was missing, but my 2 positions were both there.  I refreshed the pg, to see if my FF would return, but instead one of my positions disappeared.  (FF didnt return).  Tried refreshing again and the missing position didnt reappear

**Comment by bthaile** [comment]
I'm hoping that Alex's refactor of getters fixes this intermittent issue.

**Comment by Chwy5** [comment]
Not seeing this happen
