### ISSUE TITLE
Templates: NHL picklist dependency 

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4671]
`Which NHL team will win the [Year] [Event]?` template

<https://www.lineups.com/articles/plain-text-lists-of-professional-college-sports-teams-nfl-nba-mlb-nhl-soccer/>

If Eastern Conference Finals is selected (only teams in the eastern conference can be selected from the outcome list
If Western Conference Finals is selected (only teams in the western conference can be selected from the outcome list
If Stanley Cup is selected Both Eastern and Western Conference teams can be selected

 * add eastern and western conferences, stanley cup
 * add picklists per conference

 * use team picker for `NHL: Will the [Team] win the [Year Range] Stanley Cup?` template

**Comment by Chwy5** [comment]
looks good
