### ISSUE TITLE
Templates: auto-complete picklist

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4672]
horse racing template `Which horse will win the [0] [1]?` for event add auto-complete picklist

dropdown for Event
Here is a list of all the big betting races to do auto-pop search
**** https://extra.betamerica.com/racing/major-horse-races/

not just for horse racing.

prob should make all template dropdowns that have more than 10 values be auto-complete.

**Comment by phoebemirman** [comment]
UI is compliant with design

**Comment by joeykrug** [comment]
status?

**Comment by bthaile** [comment]
I don't think we need to do this. dropdowns perform and all styles are up to date. closing
