### ISSUE TITLE
Design QA: Trading Page - Market Details

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#4674]
Design:
https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=453%3A59625

- [x] Shield for templated market: add a tooltip on hover:
Template markets have pre-defined terms and a greater chance of validly resolving than custom markets

- [x] Market type label -Update styling. See design

- [x] Categories - update styling. See design

- [x] Copy button - fade in tooltip for 2 seconds saying 'Copied' above button after user clicks

- [x] Market status - update text styling. See design

- [x] Market data - update the text and colour styles on both labels and numbers. See design

- [x] Estimated fee and event expiration should be using the (?) for tooltip hover not (i). Should be replaced globally 

- [x] When collapsed, clicking the whole bar (other than the back button) should open it
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/a8d055f7-3de5-4e56-97ab-7dc9c28b6b51)

- [x] Expanding resolution details should look like this
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/54d7ed12-7fdc-48b7-a12a-e41352e4c058)
https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=2101%3A216

- [x] Ellipsis market title after 3 lines
Designs:
https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=1913%3A3099

Ellipsis
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/2086fb46-cf06-4243-8ed8-9f44e3e0ed7a)

Hover
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/29f44a60-b1a0-4ee8-bdfb-f96dc56c14e1)

- [x] Change 'Additional Details' to 'Resolution Details'

- [x] Resolution details to be place at the bottom of that component like image below. Currently it sits too high

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/072b9fc2-0913-420c-8d70-41106365aecb)

- [x] Update back to market list button - see design

**Comment by JohnDanz** [comment]
`Template markets have pre-defined terms and a greater chance of validly resolving than custom markets` <- template tooltip

**Comment by joeykrug** [comment]
Seems done?
