### ISSUE TITLE
Order ticket displaying incorrect info when having a position

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#4686]
Here shows my current position....long 2350 SF at avg price of .58
![11-9.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/7cf8abf0-2b33-484c-a4a9-90507b5a9541)

Here shows the order ticket, trying to sell out 100 shares at .6....Says New position and is giving me info as if it is a new position....it should say closing position and show my my potential PnL

![11-9a.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/f2ec63b5-9874-4af1-bf37-aa9d79998be6)

**Comment by bthaile** [comment]
tried to mimic the description. @Chwy5 can you try this scenario again? I wasn't able to repro

![Screen Shot 2019-11-29 at 2 18 22 PM](https://user-images.githubusercontent.com/3970376/69888750-22c4f300-12b3-11ea-8761-872af9f0fe9c.png)

**Comment by Chwy5** [comment]
works
