### ISSUE TITLE
Limit order issue

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#470]
Make an order like that, submit it, it'll just buy indiscriminately even though it shouldn't due to your cap on the price.  

![augur](https://cloud.githubusercontent.com/assets/5925937/13760146/a3787908-e9ff-11e5-94f1-a8c63b938ddc.JPG)

**Comment by tinybike** [comment]
Hmm, it's not supposed to accept a cap without a price.

**Comment by joeykrug** [comment]
It should - that's a standard limit order

**Comment by tinybike** [comment]
The price is when the order starts to be filled.  The cap is when the order stops being filled.  These aren't "real" limit orders -- they're just stop orders with a cap.

**Comment by joeykrug** [comment]
I don't see your point. Why can't I submit an order with a cap and that's it?  The backend supports it

**Comment by joeykrug** [comment]
All it is is - buy shares automatically at this price - this price being 0, highest price is my limit

**Comment by tinybike** [comment]
Obsoleted by 59f966ae8b6d24f221fec1ec166e75a53216429e.
