### ISSUE TITLE
Firefox error - can't load markets

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#4700]
<img width="1440" alt="Screen Shot 2019-11-11 at 10 58 49 AM" src="https://user-images.githubusercontent.com/1683736/68607960-d2aafb80-047f-11ea-9804-3b266ff4cd32.png">

@bconfortin looks like it may have to do with chat-based on the error above?

**Comment by bconfortin** [comment]
@andrewdamelio That shouldn't be halting markets from loading. Could you be so kind and test that again?

It loads for me both on local and v2.

**Comment by andrewdamelio** [comment]
same issue for me @bconfortin - very stange 

What version of firefox are you running?

**Comment by bconfortin** [comment]
@andrewdamelio 70.0.1 (64-bits) on Mojave

It took 1 min or 2, but it loaded. From what I researched, that error is from specifying an address like 192.168.etc without the scheme, like ws:// or http://

Will have to take a better look

**Comment by andrewdamelio** [comment]
Gotcha so it loads for you 👍 

Out of curiosity, do you also see the error I posted above?

**Comment by bconfortin** [comment]
I do, that's why I asked you to retest it. It didn't halt the market load for me, which is really weird. I'm just finishing a task here and then I'll see what could be the problem.

Are you on Kovan or local? I was on local, with flash run fake-all, btw

**Comment by andrewdamelio** [comment]
I noticed on kovan when I was testing v2.augur.net

**Comment by bconfortin** [comment]
Seems to be working after the switch from PouchDB to DexieDB.
