### ISSUE TITLE
Design QA: Trading Page - Order Book

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#4703]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/c6bee0e2-894f-4bc6-90b0-04eb577b92ca)

Design:
https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=134%3A37268

- [x] Heading (ORDER BOOK). Update text style. Make primary text colour

- [x] Labels. Update text style. Make primary text colour.

- [x] Label area background: check size - looks smaller than design

- [x] Add 1px dark grey line to bottom of labels bar

- [x] Quantity bars should not overlap number with 8 digits (1000.0000). Anymore digits and it can overlap. See design

- [x] Make sure quantity bar lines up with the green or orange vertical line to the far left

- [x] Numbers: update text styling

- [x] Spread: update text styling

- [x] Spread: add 1px dark grey line to top and bottom of bar

- [x] Check quantity bar is 50% opacity. Currently looks faded but might be the way the browser renders is 

- [x] Check 1px line to the far left of each row is 100% opacity

**Comment by joeykrug** [comment]
seems done?
