### ISSUE TITLE
Design QA: Trading Page - Trade History

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#4707]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e4ccc2cd-6ce5-4d1e-996f-afa35309cece)

- [x] 'Trade History' header - update style and colour

- [x] Header - add 1 px dark grey line to the bottom

- [x] Labels (quantity, price etc) - update style and colour

- [x] Label area background: check size - looks smaller than design

- [x] Add 2px dark grey line between daily groupings - see design

#### Daily share amount ####
- [x] text aligned 8px from left
- [x] text: check styles
- [x] Make text 50% opacity

#### Order Row ####

- [x] Update text style and colours
- [x] Price arrow should be text/secondary at 50% opacity.

**Comment by joeykrug** [comment]
seems done?
