### ISSUE TITLE
Design QA: Trading Page - Outcomes

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#4708]
Design: https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=209%3A915

- [x] Outcomes header: update text style

- [x] Labels: update styles

#### Outcome Rows ####

- [x] Active outcome row should be highlighted with the hover state colour. See design
- [x] Outcome name now has a different text styling. Please update
- [x] Update number stylings
- [x] Dark grey divider lines shouldn't go full width. see design
- [x] Add tooltip next to invalid. Copy: "A market may resolve as Invalid if its details or outcome are ambiguous, subjective or unknown. Because Invalid is a resolvable outcome, traders may buy/sell shares in it."

**Comment by joeykrug** [comment]
seems done?
