### ISSUE TITLE
Loading endlessly

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#471]
So this was happening to me last night, so it's not a load/beta issue imo.  It happens to other people too occasionally [like on reddit].  It doesn't matter what browser or os, has happened to me on firefox and opera, happened to people on reddit with chrome.

It'll just load forever.

Refresh and it still loads forever

Open a new tab and sometimes it loads.

Attached a video link:
https://dyffy.slack.com/files/joeykrug/F0SM6LLT0/ice_video_20160314-160118.webm

**Comment by tinybike** [comment]
Does this still happen for you, after the most recent round of updates?

**Comment by joeykrug** [comment]
Fixed for me now on all browsers

**Comment by joeykrug** [comment]
still fixed, even on a super slow connection, closing
