### ISSUE TITLE
Design QA: Test Trade Tutorial

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#4722]
- [x]  Add more orders to part fill order book
- [x] Add more trades to fill trade history
- [x] Hide facebook comments

- [ ] Check the type style and type colours update when masters have been updated 

- [ ] Disable all interactions across the top bar and navigation

- [ ] Only show error message for quantity if they click next after entering a wrong amount. Currently it shows as soon as I start entering an amount.

- [ ] Total Order Value input number should appear after adding the limit price. But should remain non-interactive

- [ ] Order book: Spelling mistake - change edition to addition (2nd word)

- [ ] Order book tooltip: Is it possible to make this so it doesn't appear partly under the nav bar if the user scrolls? I don't think the user should be able to scroll this page anyway (there seems to be a section of empty space at the bottom of the  page which is causing the scroll. This is the issue ![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/063f2611-a501-48bc-a917-fd11fbd77c51)

- [ ] Check when the update to the order ticket happens (Buy/Sell button should be dynamically fixed to the top - under advanced button or new position info) that the tool tip moves with it. This will stop the tooltip sitting off the bottom

- [ ] Open Orders: Change the last paragraph to say: 'Click next to see what happens when your order is filled. Check design for text styling

- [ ] My fills. Can the user expand their fill

- [ ] Positions: change the Next button to say Finish

- [ ] Congratulations screen: Knowledge Centre should become a link when it's ready to link to.

- [ ] Close test trade button: it's been mentioned that this doesn't get noticed so can we change it to the button - see the design

**Comment by bthaile** [comment]
I think the trading tutorial is done. @Chwy5  moving this to Product Review

**Comment by matt-bullock** [comment]
@Chwy5 can you put this into design review after you've checked. This is mostly design stuff to review

**Comment by Chwy5** [comment]
The external links in the messages dont load....like the community guidelines, guide, learn more

**Comment by Chwy5** [comment]
Also the information box (Box 10) which points to Open orders and say you can view your open orders here...covers up Open orders

**Comment by Chwy5** [comment]
fixed -closing
