### ISSUE TITLE
Design QA: Trading Page - Order Ticket

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#4731]
Designs:
https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=102%3A3991

### Header (Buy Shares, Sell Shares) ###
- [x] Check type sizes
- [x] Make hover states green for buy, orange for sell

### Outcome Select ###
- [x] Update states to match design
https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=1957%3A727
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f5ff7fb7-3312-4592-8503-41548dcce4f5)
- [x] update dropdown menu style if not already done in the app

### Inputs ###
- [x] make 32px height - same as the outcome selector
- [x] Update label styles
- [x] Update text styles of labels within inputs
- [x] Update input text style
- [x] Update states. Design for orderform input states: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=8219%3A266044
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/81f7fabb-6bea-4fd9-af55-19f69d8dc349)

### percentage and clear button ###
- [x] give hover state design: https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=1774%3A9278
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/cb9c8b2c-66b7-40ee-b90e-130196fccac2)

### Max cost of... ###
- [x] update text styling

### Advanced button ###
- [x] make arrow animation instant
- [x] Give hover state: https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=1774%3A3055

### Advanced order dropdown ###
- [x] Fix the width to the largest text size (good till cancelled). It shouldn't decrease in width for the other items
- [x] give correct hover and active style: https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=1950%3A38
- [x] Update dropdown menu style

### Order Expiration ###
- [x] Input should follow the same state rules (active, hover etc) as the other inputs in the order form. Only difference is it's smaller and less padding  around text
- [x] Date and time buttons should have hover states
- [x] Timezone picker button needs be wider to show full text
- [x] Date, time and timezone button should all be the same button style:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/c23da248-bf0d-4d81-a405-768427175c96)
- [ ] Date, time and timezone pickers should appear above the button so they don't get cut off the bottom of the screen

### BUY/ SELL Button ###
- [x] Dynamically move up and down 16px from the nearest above element:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/7b2d5ad9-5585-47a6-a001-24baab7ea2bd)
- [x] Update text styles
- [x] Update opacity for states: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=8223%3A4544
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/0e9afe7c-d3d1-47b0-937f-4b911989cc78)
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/de3dd9e8-bdff-409d-98be-34acdbc65a47)

**Comment by Chwy5** [comment]
Moving ticket back into ui dev incoming....remaining items are lower priority then current needs....this can be finished working on after higher priority issues are done

**Comment by rubyweb3** [comment]
I haven't figured out how to 
- Date, time and timezone pickers should appear above the button so they don't get cut off the bottom of the screen

@bthaile Could you help this item?

**Comment by Chwy5** [comment]
This is low priority, not needed right now, We should only be working Med tickets or higher

**Comment by matt-bullock** [comment]
@rubyweb3 

Everything in the form looks good thanks, only suggestion is creating enough room for the time to sit on one line. See image from build:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/09f66436-2cf4-465d-af1a-41a1c17ddda8)

**Comment by matt-bullock** [comment]
all good. closing
