### ISSUE TITLE
Sort bug

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#474]
"When I sort the markets, the first one is always the same for me (Right now: Will ETH/USD price crash on April 1, 2016?). "

**Comment by tinybike** [comment]
Right now, if you haven't taken the tour yet, the tour market always gets
placed at the top -- if this is not the behavior we want, should be easy to
change!

**Comment by joeykrug** [comment]
It should probably tour based on just picking the first binary market in the sort or something, idk, doesn't make sense to hard code it to one market
