### ISSUE TITLE
UX Improvements to newly created markets

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#4743]
Steps to reproduce:
Create  a new market ( ihave been using the NFL Football template Team a vs Team b) Add liquidity to all the possible outcomes hit the button to create the market.  Model pops up telling me what next steps will be and I hit ok to proceed and sign my Tx.  I see my market processing under My creaed markets in the portfolio pg and that is it.....No other popups to sign, no notifiactions in the Acct Summary that I have open orders to sign

**Comment by Chwy5** [comment]
Still not getting the little red circle (dot) indicator on the acct Summary pg telling me I have a new notification...

Showing me I have a view orders on the portfolio pg under My created Markets is easy to miss, bc it goes to the bottom of the list and I have 10 other markets already created

**Comment by cillianhunter0** [comment]
AS - notification should appear at _top_ of the notification list (currently appearing in what seems a random order) 
AS - red dot on account summary in navigation is not appearing when user has a new notification 

(Will look at improvements to the flow tomorrow and update here)

**Comment by cillianhunter0** [comment]
**Improvements for post creation UX**

Improve visibility in the my created market list:
1. Display the new market at the bottom of the my created market list on porfolio page, automatically scroll the user to the end of the list so they can see it
2. Have the background colour of the new market pulse twice to draw attention to that part of the screen, that and the pending tag should do enough to get users eyes down there (see figma link for states) 

As soon as the market is created:
1. Display a modal that tells the user their market has been created (this would be a new modal that provides a link to the market and if they had entered pre-liquidity it allows them to start that process) 
2. if they entered pre-liquidity - display red dot beside account summary in navigation to get their attention on the notification section where they can submit that liquidity etc

Portfolio page and market row states: 
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=3202%3A562

Modals when user entered pre-liquidity:
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=3211%3A5767

Modal when user didn't enter pre-liquidity:
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=3211%3A3984

Red dot appearing in nav bar beside account summary: 
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=3210%3A2

**Comment by bthaile** [comment]
@Chwy5  anything on this ticket need to be worked?

**Comment by Chwy5** [comment]
No, the new changes should cover it for now...closing this
