### ISSUE TITLE
Market date off

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#475]
There are markets that don't expire until the 19th in the expired markets section --- calculation here is wrong somehow

**Comment by housemobile** [comment]
https://github.com/AugurProject/augur/issues/436

**Comment by thinkloop** [comment]
I am not able to repro, but perhaps it got fixed in recent commits - do u guys still see unexpired markets while the 'recently expired' checkmark is checked alone?

**Comment by joeykrug** [comment]
I don't

**Comment by thinkloop** [comment]
OK closing for now, pls feel to re-open if it pops up again @housemobile
