### ISSUE TITLE
Design QA: Portfolio - Open Orders

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#4758]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/236908c4-335c-448a-ba3f-55e449f51601)

Designs:
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=2629%3A4491

HEADER COPMPONENT:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/d1c6a2d5-902f-4d19-9629-18b31c69460a)
- [x] Check header component is up to date

LABELS COMPONENT
- [x] Check this is up to date
- [x] Line up Outcome label 16px from left

MARKET TITLE COMPONENT
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=2599%3A866
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/0b3075fd-8d04-4ce0-94c5-9719815bfcff)
- [x] Check text style is up to date

ORDER DETAILS COMPONENT:
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=2599%3A1314
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/86418cae-9d84-4306-afe8-6452f7af2f4c)
- [x] Check all text styles are up to date

ORDER DETAILS COMPONENT - EXPANDED STATES

- [x] Check styles and colours and spacing for sort by recently traded outcome 
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/2f85a09f-9d78-4589-89c2-63e65e99fc85)
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=10719%3A7986
- [x] Remove indent on market title
- [x] Update background colours

- [x] Check updates are applied when most recently traded market is selected
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/6c93a660-1b6b-4344-9897-ca8f677cd8f7)![image.png]
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=10718%3A4468
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/0124e71f-14ec-4c0f-9fb6-e480b4a9e393)

DIVIDERS:
- [x] When sorting by most recently traded outcome 1px dark grey divide is 16 px from left and right edges. See image:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/20b10eae-2e69-4ec6-abac-c491cf56c420)

- [x] When sorting by market keep the 1px dark grey divide 16 px from left and right between outcomes but between markets use a full width 2px dark grey divide. See image:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/8480dbbf-abe1-4e1c-8987-f7de6e831210)

**Comment by pgebheim** [comment]
@Chwy5 @matt-bullock @cillianhunter0 

Is this up to design review snuff?

**Comment by Chwy5** [comment]
Yes, but those guys have not been able to get on to v2 to test this and about 14 other tickets
