### ISSUE TITLE
Using MM entering an order into the book but cancelling it on MM make the order stuck in open orders

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#4760]
To reproduce (Use a MM acct)....

Enter an order into the order ticket: (ie sell 10 at .55) and hit place sell order, when the MM sign box appears, hit cancel....this leads to the order on the trading pg and portfolio pg in Open Orders stuck spinning in a processing state...

Only refreshing the pg fixes it

**Comment by joeykrug** [comment]
fixed
