### ISSUE TITLE
Special Behavior for Event Picker in Market creation and Outcomes for Multiple Choice Markets

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#4764]
For the multiple choice market type (for all sports not just Football, just using it as an example)The teams being used in the outcome picker associated to the Event can only be used once....so in the example
Which NFL team will win the [Year] [Event]? and Event is AFC Championship, the outcomes should only allw AFC teams to be selected,
****But once a team is selected it needs to be grayed out and cant be added to the list again

we cant allow them to pick the same team more than once....So for who will win the AFC Championship:
1) Field
2) Chiefs
3) Raiders
4) Chargers
5) Chiefs
6) Broncos
7) Invalid
So in this example outcome #2 and #5 are the same...can't allow that

**Comment by bthaile** [comment]
market creation form won't allow user to proceed if outcomes has duplicates. closing
