### ISSUE TITLE
Design QA: Portfolio - Filled orders

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#4768]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/371953c7-3dbb-4109-ab62-581c4c1b477b)

Designs: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7110%3A244694

HEADER COMPONENT
- [x] Check it's up to date

LABELS COMPONENT
- [x] Check it's up to date

ORDER COMPONENT
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=2599%3A44117
- [x] Check up to date

MARKET TITLE COMPONENT
- [x] Check it's up to date

EXPANDED STATES
- [x] Check most recently traded market expanded state components are up to date
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7110%3A244694

- [x] Check most recently traded outcome expanded state components are up to date
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7110%3A244737

**Comment by joeykrug** [comment]
where is PR for this?

**Comment by phoebemirman** [comment]
there were a few. this was one of them https://github.com/AugurProject/augur/pull/5270

**Comment by matt-bullock** [comment]
If it's a quick job please line up the lines and elements to the left and right in the expanded states. Currently looks like this:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/1103c565-6857-4bdc-bf78-549a5bba4ed8)

Should ideally look like this:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/760a1238-60e7-4016-8e26-9d7df23a78e0)

**Comment by matt-bullock** [comment]
@phoebemirman was that request looked at before you closed the ticket? I'm still seeing this on local which doesn't look great. If not let me know before closing so we know what's been skipped and have a record of it for later.
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/ecfb3c2b-ec3d-439e-b823-999c308c2ecf)

**Comment by phoebemirman** [comment]
so filled orders expanded details should align with the arrow? and thats all? i thought you meant something about the inner columns was off.

**Comment by matt-bullock** [comment]
yes, and on the left side the divide shown when expanding details should line up with the other elements
