### ISSUE TITLE
Market link doesn't work

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#477]
go to market link like https://augur.net/markets/-adffbf20f2c1cd157d6e04bc20dc04cf4cbb91e4c81abd71ba71d4f825846702 and it a) loads all the market first [not needed when i'm going to a specific market, load them after loading this specific one, or load them once i go to the generic markets page] before finally loading the market i need
b) sometimes never loads and just says no market found

**Comment by tinybike** [comment]
997ff90f1945709c162e364e136162e2a0dac26e changed it so if you're on an individual market page it'll load the market first, then go on to the full market load.  This will fix slow loading but I don't think it'll fix it if it never loads.  I can't get "never loads" to happen though, so I'm closing this for now -- if this happens again, please re-open and paste the url for which it does not load!
