### ISSUE TITLE
Design QA: Account Summary - Your Overview

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#4774]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/ea5dd664-f0a2-42c6-918e-144a3e432ce6)

Design: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=2694%3A127

HEADER:
- [x] Check background colour
- [x] Check text style

TEXT ACROSS WHOLE COMPONENT:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/26f1ac7a-d603-4bd7-8e0b-4265c520ecf6)
- [x] Update any text styles and colours that are incorrect
- [x] Remove DAI symbol and use $ instead

REP SECTION
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/58ce0a0b-837c-4baa-a5a8-2ddb3f5e1452)
- [x] Remove outline in background and add background colour
- [x]  Correct type sizes and colours

TOGGLE
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/b9bdefe4-3f15-4b4c-b6f0-d0de29b208c4)
- [x] Update text style
- [x] Update button style
- [x] Update hover and active styles. Hover should be same style as active

PROFIT AND LOSS GRAPH
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/bb0cc246-2dee-467b-b2d4-8b1ca94498aa)
- [x] Add background grey
- [x] Make dates all caps
- [x] Update horizontal axis colour
- [x] Add horizontal lines

**Comment by JohnDanz** [comment]
bumping to an 8 est because this is going to take a bit of refactoring as well as just style updates

**Comment by matt-bullock** [comment]
You Overview header text looks more over to the left than other sections.
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/b4094b1e-b11a-4ed5-b5a6-faafdce8548a)

Rest looks good

**Comment by matt-bullock** [comment]
closing
