### ISSUE TITLE
Design QA: Account Summary - Footer

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#4778]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/ecdafad5-caaf-47bc-af7f-0e7d9ef88312)

https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=12103%3A283122

- [x] Update footer style
- [x] Update text styles
- [x] Keep below the fold of the page

**Comment by JohnDanz** [comment]
Do we need version on here? we don't currently store it anywhere, might need a new ticket to add that.

**Comment by matt-bullock** [comment]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/14951cb8-8d1f-451d-a822-b153fe1878b4)I forgot to account for the global chat button here.

Can you shift the content over to account for this. To look like:![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/7424af42-529f-450c-8723-91c179176575)

**Comment by matt-bullock** [comment]
@chwy would you know if we want to show the Augur Version number?

**Comment by Chwy5** [comment]
No we dont need it
