### ISSUE TITLE
Design QA: Account Summary - Notifications

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#4789]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/5e11b9ed-b920-4d87-a4c6-90262d389f97)

Design: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7268%3A30399

HEADER
- [x] Check text style is up to date
- [x] Update label indicating new message

NOTIFICATION COMPONENT 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7272%3A212

- [x] Update header text
- [x] Update paragraph text
- [x] Paragraph text doesn't go full width - see design
- [x] 2 lines max before text is cut off by ellipses 
- [x] Update VIEW button
- [x] Update colour of read and unread states![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/7fd3719f-c428-4127-81d9-2429eccfabf6)
- [x] Update new notification tag/label
- [x] 12px space between component top edge and top of content
- [x] 12px space between component bottom edge and bottom of content
- [x] 12px space between paragraph text and top of countdown timer label
- [x] Divides between notifications shouldn't go full width

**Comment by JohnDanz** [comment]
all of this is related to these two:

https://github.com/AugurProject/augur/issues/5370
https://github.com/AugurProject/augur/issues/5371

**Comment by cillianhunter0** [comment]
Open orders, claim proceeds, claim stake and feeds look good. 

There are issues with: 
- Finalize market
- You need to report
- Dispute

See comments in the screenshot: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/c6107b85-7aae-4beb-8579-3a1e4d43a5cb)

**Comment by Chwy5** [comment]
closing
