### ISSUE TITLE
Investigate keeping a separate KYC orderbook on contracts

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#479]

**Comment by joeykrug** [comment]
I think this should be pretty easy, all the trading functions add a parameter for the kyc token (an erc 721 address) and if a user has that token, it lets them place an order, all those orders are stored with a mapping. Like set of order books equals mapping 721 address -> the book for a market. To place or take an order a user needs that token. For non kyc token books it’d just be the 0 address or something. Does that make sense @nuevoalex?

**Comment by nuevoalex** [comment]
Yea the contract portion sounds relatively simple. Keeping Augur Node functionality for v2 is probably relatively easy as well, it just implies any relevant getters also need to specify what orderbook token they want to use for context.

Would this proposal also involve building something into the client UI?

**Comment by joeykrug** [comment]
I figure UI could be done on a later date, one route is to have it as a url param (maybe a simple UI mvp for it) another is to have people enter it in the UI globally or on a per market basis

**Comment by pgebheim** [comment]
@nuevoalex -- When this is done we should fill out an issue that describes how to implement in Augur State.

**Comment by pgebheim** [comment]
@nuevoalex -- Again, was there a PR associated this moving into Review/QA?

**Comment by nuevoalex** [comment]
Yea, connected now
