### ISSUE TITLE
Design QA: Chat - Chat screen

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#4797]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/22a9fdeb-00f7-4f9e-a88b-fc4402afff2a)

Design: https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=194%3A3832

 - [x] Centre align text for '205 Online'

- [x] Adjust height of chat input box to match design. Currently it looks small leaving a large gap at the bottom

- [x] Update username text style

- [x] Check user's messages are using colour text/primary

- [x] 'Type your message' text. Make colour text/secondary at 75% opacity

- [x] Active input text should be colour text/primary at 100% opacity

- [x] Check types style for input - might need updating to larger font size

**Comment by bconfortin** [comment]
Oops. Miss clicked.
