### ISSUE TITLE
Gnosis class weirdness around onNewBlock events

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#4809]
Notice a strange issue within the UI while I was QA-ing Gnosis safe.

There seems to be two instances of the Gnosis class. Inside Gnosis.ts, the private method **onNewBlock** which is called on each new block seems to be only being caught on one of the two instances, the instance that also doesn't contain any of the relevant Gnosis data we need to listen to.

Not sure if it's related, or another issue, but furthermore, the UI will sometimes just stop receiving **onNewBlock** events - which causes balances and gnosis states to freeze until the page is refreshed or another TX is triggered.

**Comment by justinbarry** [comment]
@andrewdamelio The two instance thing is expected. There will be one on each side of the webworker boundary. One is tied into blockstream and the other is not which should account for what you are seeing.

**Comment by andrewdamelio** [comment]
So a fix is required @justinbarry? To allow the UI to get these events?
