### ISSUE TITLE
Get rid of numticks

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#481]
Everything can just be in terms of DAI to Complete Sets. For Scalar it would be display range * DAI

**Comment by joeykrug** [comment]
What feedback is needed?

**Comment by nuevoalex** [comment]
Whether this is worth the time potentially spent reworking anything that deals with trades or trade data to no longer consider numTicks. It probably is but its going to be a fair bit of work and want to be explicit about the decision.

**Comment by nuevoalex** [comment]
We decided against this in the end as its nice having the value of complete sets be as small as possible to allow fractional shares and minimal required assets to trade in a market.
