### ISSUE TITLE
Local Gnosis relayer issues

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#4811]
It seems like when running ```docker:gnosis``` I'm seeing the below issues with the relayer.

1) Safes get stuck in CREATED state. It seems like the relayer status never shows these safes with a block hash (only a TX) so they never move into an AVAILABLE state

<img width="444" src="https://user-images.githubusercontent.com/1683736/69065645-15278780-09ee-11ea-916f-f23d2b436e04.png">

2) Seems like running ```calculateGnosisSafeAddress``` on the creation params doesn't return the same address -- This DOES work on kovan not sure why locally i would be getting different results
<img width="444" src="https://user-images.githubusercontent.com/1683736/69065646-15278780-09ee-11ea-8d45-68ac4f38a25b.png">

**Comment by joeykrug** [comment]
status of this?

**Comment by justinbarry** [comment]
@andrewdamelio We solved this one, yeah? Please reopen if I'm wrong.
