### ISSUE TITLE
Template: outcome dropdown adds extra outcome

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4815]
New Template, where outcome dropdown and text input then another other dropdown. There seems to be a bug when the second dropdown value is selected.

initial view
![image](https://user-images.githubusercontent.com/3970376/69074140-6b97c480-09f4-11ea-8b5b-8ac79badba76.png)

after selecting Team B
![image](https://user-images.githubusercontent.com/3970376/69073958-0348e300-09f4-11ea-9d14-5997d071adbb.png)

**Comment by phoebemirman** [comment]
need to try switching ids for 1 and 2 in the template
