### ISSUE TITLE
Add option for a area graph in markets with multiple options

### ISSUE THREAD

**Issue by alexvandesande** [AugurProject/augur#482]
It's very hard to make sense of this graph:

<img width="1190" alt="captura de tela 2016-03-15 as 11 54 43 am" src="https://cloud.githubusercontent.com/assets/112898/13782171/d9b37270-eaa4-11e5-9558-2bc353431cb1.png">

A much better option, in my opinion since all markets have a constant sum, would be a total area graph:

<img width="1190" alt="captura de tela 2016-03-15 as 11 54 43 am" src="https://upload.wikimedia.org/wikipedia/en/archive/8/81/20130817230447!USRD_area_graph.svg">

**Comment by pqdeep** [comment]
Might be better to break up the catch-all chart into individual charts -- give the top three options their own line chart.

**Comment by tinybike** [comment]
Moved to CH
