### ISSUE TITLE
Walkthough of UX issues so far

### ISSUE THREAD

**Issue by jackwinters** [AugurProject/augur#483]
Some initial comments (just thinking aloud as I use the site) I did not try actually buying any shares since registering means agreeing to terms and conditions including indemnifying you and I'm wary of doing this just to contribute to beta testing.

- Landing page is boring as hell no images, just bad purple design choices.
- If I were a newbie who did not know what Augur is nothing tells me what I'm looking at or what this site is.
- First time I tried the site contents did not load and no markets are shown just endless beep bloop beeps. Some hours later it worked.
- Search box would be better with autocomplete.
- Sort by categories don't match consumer needs: What about sorting or filtering by category e.g. sports, politics, hot, closing soon or best odds.
- Tags exist but are not clickable
- Bottom banner is Slack | Documentation | Blog | About | Github | REP Login | FAQ | Terms of Service
 -     Is slack really the first thing a consumer is looking for?
 -     Documentation takes you to developer & API documentation which while good is not what I want as a consumer looking for help.
 -     The FAQ link does not work (No help desk at augur.zendesk.com)
 -     There is no help link 
- Not exactly clear what my expected return is for each market does 50% 50% mean 1:1 odds in betting terms? Does the market pay out 1 of some currency per share if the prediction is correct?
- You can filter by volume (e.g. 612092.61 shares) is this 24 hr trading volume or total number of shares on the market. This needs to be explained.
- What currency are the prices in?
- Looking at the US Presidential candidate No images of the candidates, themes or other information - not fun.
- Why are there different amounts of shares outstanding for each of the candidates what does this mean?
- Why do I care that the Author is 7f605b7d61a38738048c3bd63ee94be7a8094b15 ?
- The graph is ugly, jumps up and down like crazy and there is no legend. Consider other ways of visualising time variation of predictions. (candlesticks, area, moving average with error bars ect)
- What is the bottom graph? Is it volume if so say.

**Comment by pqdeep** [comment]
We appreciate the feedback, and we'll weigh it carefully as we continue to improve the interface. The helpdesk was temporarily down earlier today, but it's back up now.

**Comment by tyche78** [comment]
I agree that image thumbnails in listings are a big design priority, but there is an unsolved NSFW problem: https://github.com/AugurProject/augur/issues/378

**Comment by joeykrug** [comment]
i made the unresolved / still relevant issues as other issues on clubhouse
