### ISSUE TITLE
market creation form validation error rewording

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#4835]
we need to change that error msg "You must complete all required fields highlighted above before you can continue"

save draft uses it too

**Comment by bthaile** [comment]
change `You must complete all required fields highlighted above before you can continue` to what?

**Comment by phoebemirman** [comment]
the wording doesnt apply for the validations where they did enter values but they arent valid ones

**Comment by bthaile** [comment]
@petervecchiarelli thoughts on this?
maybe something like:
All validation errors must be fixed before continuing with market creation
