### ISSUE TITLE
[design] Do we really need so much spacing between elements?

### ISSUE THREAD

**Issue by tyche78** [AugurProject/augur#484]
Margins between elements (h1, search box, etc) at the top of the UI are all above >20px. This is unconventional, unattractive and becomes an annoyance on mobile.

Compare these two screenshots and tell me that huge margins are necessary: http://imgur.com/a/G185p

I personally much prefer with reduced margins.

**Comment by tinybike** [comment]
@Newportkiwi's call

**Comment by tinybike** [comment]
Obsoleted in 59f966ae8b6d24f221fec1ec166e75a53216429e; reskin pending.
