### ISSUE TITLE
Make all ERC20s ERC777

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#485]
...

Preserving backward compatibility as ERC20 too
 -nuevoalex

**Comment by nuevoalex** [comment]
After a lengthy discussion something that we would like to change with the existing implementation on the https://github.com/AugurProject/augur/tree/erc777 branch is to be less strict implementing the 777 spec.

In particular we should change the implementation such that the ERC20 interface does not wrap the 777 implementation, and instead simply provides the ERC20 functionality.

This will allow us to provide the 777 functionality that third parties will likely enjoy (being able to avoid approvals) while also maintaining the protection that ERC20 affords from malicious token recipients which prevents us from having to build a withdraw pattern into the UI.

**Comment by nuevoalex** [comment]
Alternatively we could simply make an addition to the ERC777 interface to allow a send that does not trigger the sender and receiver hooks as normal. Our contracts would use these hooks and avoid any potential malicious user issues.
