### ISSUE TITLE
Anayltics: Should generate session ID not tied to users ETH address.

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#4853]

**Comment by pgebheim** [comment]
Its possible that Analytics.js does this automatically, in which case we'll want to not call `idenfity` with their address.

https://github.com/AugurProject/augur/blob/4f8dd3d432e414ed5f69913f38f368dbe2834798/packages/augur-ui/src/services/augursdk.ts#L126

**Comment by phoebemirman** [comment]
No longer applicable
