### ISSUE TITLE
Analytics: Add 30s Delay to All Logging

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#4855]

**Comment by bthaile** [comment]
all analytics need to be delayed by 30 seconds. or does trading need to be delayed by more?

Also, is it ok to post user's analytics when they login next session or should all analytics be posted when they close their browser?

**Comment by pgebheim** [comment]
That's fine -- analytics calls just need to be sent with the timestamp from when they're generated which I believe happens automatically when we hook into the transport layer.

**Comment by bthaile** [comment]
~~if we delay 30s then the `timestamp` will be delayed. I don't see where timestamp is set in augur-ui. if it's set when sent to `Analytics` then the timestamp won't be correct.~~

I see where timestamp is being added on new PR.

**Comment by pgebheim** [comment]
The delay needs to happen in the IPFS plugin for analytics, which is just at the transport level.

**Comment by pgebheim** [comment]
https://github.com/AugurProject/augur/blob/master/packages/augur-ui/src/services/analytics/plugin-ipfs.ts
