### ISSUE TITLE
Analytics: Investigate how to instrument flows

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#4856]
Look into how to architecturally track things in the UI. @bthaile wants it to not infect the UI with tracking code if possible.

- [ ] Onboarding
- [ ] Test Trade
- [ ] Trading
- [ ] Add Funds
- [ ] Market Create
- [ ] Anything interesting about market list?
- [ ] Reporting

The analytics library already tracks a unique ID per person (Anonymous ID) that is valid until the `identify` call.

I think we need more details on which events/data to track, here is a start.

In general, events should be named in a "Noun Past Tense Verb" Style. Here is a list to start with, though they may need some adjustment. We need to do a similar breakdown for onboarding flows + Test trade.

## Page Views
- This is a built in event for `analytics` as well as most services. Use the `page` event type whenever the route changes.

## Modal Events
  - Modal Viewed
    - Type -- The Modal Type
    - From -- The Page / Description Location they opened this modal from
    - Automatic -- True if this modal was shown automatically
  - Modal Closed

## Market List Events
  - Market List Viewed
    - Active Filters  -- the Active Filters
    - Search Terms -- Any search terms used
    - Result Count -- The number of results on this page
    - Page Number -- The Page Number of viewed
  - Market Shared
    - Source - "Market List Card"
    - Title of the Market
    - Service Market Was Shared To
    - Market ID
  - Market Link Copied
    - Source - "Market List Card"
    - Market ID

## Market Page Events
  - Market Shared
    - Source - "Market Page"
    - Title of the Market
    - Service Market Was Shared To
    - Market ID
  - Market Link Copied
    - Source - "Market Page"
    - Market ID

## Order Events
  - _NB: All Order events must be delayed by N seconds before being published_
  - Order Amount Entered
    - Type: Buy | Sell
    - Market ID
  - Order Price Entered
     - Type: Buy | Sell
     - Market ID
  - Order Submitted
     - Type: Buy | Sell
     - Market ID
  - Order Created
     - Type: Buy | Sell
     - Market ID
     - All Order Details
  - Order Filled
     - Perspective - Creator | Filler
     - Type: Buy | Sell
     - all other order details

## Market creation
 - Market Creation Started
   - DATA `template (what template) or custom`
 - Market Creation Saved
   - DATA `template (what template) or custom`
 - Market Creation Created
   - _NB: Emitted when the created market has been mined_
   - Type -- Template or Custom
   - Template ID -- The Template ID used
   - Template Name --T he Template Name used
   - Market ID -- The resulting market id

Notes from @bthaile 
Maybe you can make a custom react hook for very detailed component specific events like in modal-view to capture modal opening / closing.

**Comment by andrewdamelio** [comment]
@pgebheim @phoebemirman 
```

Onboarding Steps -- Analytics

// payload to be defined
const payload = {
  address,
  userAgent,
  ...{otherDataWeCareAbout}
}

// STEP 1 - modal-account-created.ts
augurAnalytics.fireTracking('Onboarding::AccountCreated', { ...payload });

// STEP 2 - modal-augur-uses-dai.ts
augurAnalytics.fireTracking('Onboarding::AugurUsesDai', { ...payload });

// STEP 3 - modal-buy-dai.ts
augurAnalytics.fireTracking('Onboarding::BuyDai', { ...payload });

// STEP 4 - modal-add-funds.ts [optional - user can skip this step]
augurAnalytics.fireTracking('AddFunds', { ...payload });

// STEP 5 - modal-test-bet.ts
augurAnalytics.fireTracking('Onboarding::DoATestBet', { ...payload });

// STEP 6 - Test Trade
augurAnalytics.fireTracking('Onboarding::StartTestTrade', { ...payload });
AND/OR
augurAnalytics.fireTracking('Onboarding::FinishedTestTrade', { ...payload });
AND/OR
augurAnalytics.fireTracking('Onboarding::SkippedTestTrade', { ...payload });

// STEP 7 - User Added Funds
* Fire when we detect DAI coming into the users wallet
augurAnalytics.fireTracking('AddedDai', { ...payload });


With the above, we can create the below two funnels
- Onboarding (Steps 1 - 6)
- Onboarding with Funds (Steps 1 - 6 AND Added Funds)
```

**Comment by pgebheim** [comment]
@phoebemirman can you update those to use the more natural English way of writing the events?

The strings can have spaces and they show much better in the analytics interfaces.

eg.
Onboarding - Test Trade Started

**Comment by phoebemirman** [comment]
Haven't added:
- Reporting events
- Automatic -- True if this modal was shown automatically piece of data for modal showing
- Market card sharing (social buttons aren't added to these yet)
