### ISSUE TITLE
suggestion - embolden "REP Login" link in the footer

### ISSUE THREAD

**Issue by pqdeep** [AugurProject/augur#486]
Keep getting inquiries from people worried they can't access their crowdsale REP accounts through the beta login. Maybe highlight/embolden "REP Login" in the footer?

**Comment by tinybike** [comment]
I don't think having a single bolded link would be great visually.

**Comment by pqdeep** [comment]
Maybe moving the "REP Login" link close to the beta app login up top? We're getting multiple inquiries about this daily.
