### ISSUE TITLE
Affiliate Market fees

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#486]
Market creators should be able to specify an affiliate fee which will be taken from trading proceeds and given to a referral address specified at the settlement levels of contracts.

**Comment by joeykrug** [comment]
Users could share these via a url parameter. Then when they trade it uses that referral address from the url as a parameter. That way market creators can have multiple referrals ^^

**Comment by joeykrug** [comment]
Thinking on this more there should really be two types of referral fees, market creator can choose how  much to devote to either (default 50-50). One is referral to that direct market, the other is referral to using augur in general. Both should be incentivizable.

**Comment by nuevoalex** [comment]
For the Augur in general portion where would the money be sourced from? The original idea I was that this is a new fee taken from market proceeds so its essentially an addition to the market creator fee.

**Comment by joeykrug** [comment]
yeah good point, maybe just creator ones are poss. then
