### ISSUE TITLE
Transaction History Conversions

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#4871]
The Outcome for a scalar market comes back as an on contract style value and we need to make sure it's converted to a display value. An example would be a scalar where `3,000` is the value we expect as an outcome name but instead we receive `3000000000000000000`. Alternatively we could just use the scalar description (`Degrees` etc).

We also get on Contract values back for share amounts and totals, very similar to the above issue.

Finally we are seeing a lot of these tagged as `ETH` but they should probably be looking at DAI values now or sending labels for DAI instead of ETH at the very least if the values are accurate to DAI already.

**Comment by bthaile** [comment]
I can look at scalars.

**Comment by joeykrug** [comment]
status?

**Comment by Chwy5** [comment]
Looks like scalars and Dai show correctly now....

Looks like their are 3 issues we have: 
1) We are with showing a number in Outcome for Initial Report
2) In the Total column for Claim Stake and Fees we show a long string (I think we are missing the decimal place)
3) Doesnt look like we show the trading Fee

![4-7ir.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/596fb684-b6df-4de0-b403-c1c4a6c8f815)

![4-7claimstakeandfees.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/816c4c2a-5348-428b-a11b-83f49c612f3e)

**Comment by Chwy5** [comment]
fixed closing
