### ISSUE TITLE
Market Maker Fees should depend on Market validity

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#488]
Market maker fees should be kept by the market or mailbox until a market resolves as a valid outcome.

If a market resolves as invalid the market maker fees should be taken as reporting fees.

**Comment by joeykrug** [comment]
> If a market resolves as valid the market maker fees should be taken as reporting fees.

Shouldn't this be invalid?

**Comment by nuevoalex** [comment]
> > If a market resolves as valid the market maker fees should be taken as reporting fees.
> 
> Shouldn't this be invalid?

Yup!

**Comment by epheph** [comment]
This was fixed as a side-effect of #767
