### ISSUE TITLE
Design QA: Market List Page- Cards - Condensed View - Desktop

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#4880]
Design: https://www.figma.com/file/Do4qnkCNM8P7lwBmCdYZCS4X/Market-Cards?node-id=186%3A262

 - [x] Update Label Style: Total Volume and event expiration. All should be the same label style

- [ ] Update number and date style: number for total vol and date should all be the same style

- [ ] Check share icon button is in with correct share menu - See this ticket: https://app.zenhub.com/workspaces/augur-5bfed3424b5806bc2bf8d173/issues/augurproject/augur/4547

- [x] Move up Total Volume so Total Vol label is in line with categories. Should also be in line with event expiration

- [x] Reduce text size of Market title on condensed cards - see design

- [x] Add dollar sign to start of Total Volume

- [ ] Move icons indicating if user has a position in dai, a stake in rep, MC or DR to the bottom left: 8px from bottom, 12px from left - see designs

#### Interactions ####

- [x] Make interactions the same as classic view

**Comment by matt-bullock** [comment]
Update volume number to 12px (same as the date)

**Comment by matt-bullock** [comment]
Can you update the icons to sit 8px from the bottom so there is a space between icon and volume amount when the cards have a single line market title. this is what's happening in build:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/b9a9839b-6ce6-4306-b924-982accb78f1c)

**Comment by phoebemirman** [comment]
ok im only seeing this for the condensed view

**Comment by matt-bullock** [comment]
yeah that's ok, the classic view has enough space
