### ISSUE TITLE
Add help icon (?) to top bar when logged out

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#4881]
Desktop: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=9597%3A277770

Mobile: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=11719%3A90

**Comment by Chwy5** [comment]
this is done - closing
