### ISSUE TITLE
Login or signup issue for MM users

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#4892]
Problem: 
- Users who are familiar with crypto that will use MM (or another wallet), may click on the 'login' button when first using Augur v2, currently this means they would not see the onboarding modals. 
- We want them to see 'account created' for every new wallet they connect - because they will have created a new 'augur account' for each address they connect (new gnosis safe).  
- We want them to see the 'add funds' modal. 

Possible solution: 
- We could trigger the onboarding modals if a user clicks login and they appear to have never used augur before
   - Can we check this based on their wallet address? or using local storage? 
   - Note: re: local storage - this could work but if the user then uses a different device to login, from what I understand this would trigger the onboarding modals again, which would be odd, e.g. they would see "account created" again.

**Comment by cillianhunter0** [comment]
@andrewdamelio @pgebheim @joeykrug 
Are there any solutions that would enable us to avoid showing the onboarding modals if a user logs in on another device with a wallet address they've previously used?

**Comment by joeykrug** [comment]
afaik no
