### ISSUE TITLE
Loading modal 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#4893]
Update copy to: 
- "Connecting to our partners at [wallet provider] to create your secure account."
- When Torus is the wallet provider copy should be 'Torus', not 'Tor.us' 

Add learn more link. 

Figma: 
https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=1588%3A415

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/f46f0558-5b3d-4edb-aaad-5211655ddda6)

**Comment by cillianhunter0** [comment]
@andrewdamelio  i'm not seeing this update on v2.augur. Have only just cleared my cache as well, should it be up?

**Comment by joeykrug** [comment]
afaik this is in

**Comment by cillianhunter0** [comment]
I thought I had seen this in as well, but it seems to have reverted, now i'm seeing: 

![image](https://user-images.githubusercontent.com/48024319/72153076-c3273080-33a4-11ea-9c89-350ef3b6bd80.png)
