### ISSUE TITLE
Trade Failed: your trade commitment could not be completed

### ISSUE THREAD

**Issue by gmdeo** [AugurProject/augur#490]
Has happened on every trade I have tried to make. Windows 10, Chrome.

Trade commitment hash:
-0x69efec897b07e7074b9b56304347cfa9ac2e40bad4ac3bd412d492df1fa2ddd8
Your trade commitment could not be completed.
 Details
{
  "error": 500,
  "message": "transaction failed"
}

**Comment by joeykrug** [comment]
I got this too today

**Comment by tinybike** [comment]
I'm trying various OS/browser combos and am so far unable to reproduce this bug.  Are there certain markets where this happens, or are you guys experiencing this for all markets, or at random?  When it happens, what (if anything) appears in the browser console -- if you could paste that here that would help me track this down!

**Comment by joeykrug** [comment]
I tried it on the presidential market. It only happens some of the time

**Comment by LeonardoLeonardo** [comment]
Same issue.

**Comment by DanielCarlyleEvans** [comment]
Same issue.  Not every time and I am not sure I can find a pattern.  I have also noticed that  I can often place a stop order when this occurs.  But while that order is created, it does not fill, even when it looks like it should fill.

**Comment by DanielCarlyleEvans** [comment]
I am having this problem often (almost every time) using Windows 10, Chrome, with other browser windows open (with bitcoinwisdom and it's streaming charts for example).

If I refresh the page, I am able to place the trade.  Seems to work every time if I refresh and place the trade immediately.  I then move to other markets and can't place a trade without the refresh.

**Comment by housemobile** [comment]
Happens to me all the time too. Windows XP/chrome

Trade commitment hash:
-0x78db2498ac8873016d9614e13d53755984d287ab2eb0baedebd460238aab809b
Your trade commitment could not be completed.

**Comment by tinybike** [comment]
Combined with #615
