### ISSUE TITLE
Create Design Spec for v2 Use-or-Lose

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#491]
I believe this is just changing some wording in the forking UI since we no longer have a 5% bonus and users must migrate or be locked out forever.

**Comment by pgebheim** [comment]
@matt-bullock @Chwy5 -- We explain use it or lose it in the new flows, yes?

If so can you mark this closed?

**Comment by matt-bullock** [comment]
Yeah, plan is to explain this in the new flows. Closing
