### ISSUE TITLE
Add 'add funds' button to app bar 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#4911]
Figma: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=635%3A30189

Add 'add funds' button to app bar. Opens the add funds modal.

**Comment by matt-bullock** [comment]
Done but we want to be using the new brand colour green here. It looks slightly more vibrant than the buy green. Please update
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/45c788c3-c365-42aa-9d59-26bb0365749e)

**Comment by JohnDanz** [comment]
This is using brand green now `#2AE7A8` for border. it has a 20% opacity version of `#2AE7A8` for the background. text color: `#D7DDE0` and then the circle/plus signs are both using `#2AE7A8`

**Comment by matt-bullock** [comment]
Ah ok, the this green appears to render slightly less vibrant in the browser than figma I so thought it was the wrong green. Closing this
