### ISSUE TITLE
ML: Desktop - category and filter panel 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#4916]
LEFT SIDE PANEL:
Categories and filters
[Figma](https://www.figma.com/file/GKhft5ZOwuH3ANrupGNCLHUU/Market-list-page?node-id=1342%3A6)
- [x] Update all text styles to match figma (labels, category text, filter text etc) **HIGH**
   - Styling/spacing on different states of category menu [Figma](https://www.figma.com/file/GKhft5ZOwuH3ANrupGNCLHUU/Market-list-page?node-id=1343%3A1618)
- [x] Update spacing between labels, categories and radio buttons to match figma **HIGH**
- [x] Update category icons to match figma **HIGH**
- [x] Update category count component **HIGH**
- [x] Update the tooltip icon (and color) to match figma **HIGH**
- [x] Update the 'show more' button to match figma **HIGH**
- [x] Update radio button styling to match figma **HIGH**

Hover states
[Figma](https://www.figma.com/file/GKhft5ZOwuH3ANrupGNCLHUU/Market-list-page?node-id=1722%3A481)
- [x] Update hover states to match figma **HIGH**

Comparison:
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/c964ea7a-c556-4eba-8a90-bc36c752ba23)

**Comment by Chwy5** [comment]
@rubyweb3 

The "Sort By" is  hardly visible on mobile

This is what I see on my phone:
https://cdn.discordapp.com/attachments/378030793899114516/675671604390526984/Screenshot_20200208-115643_Chrome.jpg
