### ISSUE TITLE
ML: Mobile - filter menu (styling)

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#4917]
MOBILE FILTER MENU:
Categories, sorts and filters
[Figma](https://www.figma.com/file/GKhft5ZOwuH3ANrupGNCLHUU/Market-list-page?node-id=1677%3A53834)

**Note** the majority of styling updates from #4916 will carry over to mobile. With the exception of 2 px increase in font sizes for labels, counts and category/radio button text on mobile. As well as increased spacing between rows for better touch targets. 

- [x] Update all text styles to match figma (labels, category text, filter text etc) **HIGH**
- [x] Update spacing between labels, categories and radio buttons to match figma **HIGH**
- [x] Update category icons to match figma **HIGH**
- [x] Update category count component **HIGH**
- [x] Update the tooltip icon (and color) to match figma **HIGH**
- [x] Update the 'show more' button to match figma **HIGH**
- [x] Update radio button styling to match figma **HIGH**
- [x] Update the header area background color to match figma **HIGH**

When a user has selected a category: 
- [x] Update spacing/styling of the category rows to match **HIGH** [Figma](https://www.figma.com/file/GKhft5ZOwuH3ANrupGNCLHUU/Market-list-page?node-id=1677%3A57837) (scroll right to see all states) 
- [x] Also note that when you select a category the label updates to say "categories" and the categories shown are the same height as they were before selecting one. this makes the transition after selecting one flow well. 

Comparison shots: 
Overview of all elements: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/8a0ad39d-a1a7-42ea-84bb-37925b5a6d92)

Sub-category state: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/c830568a-6f4a-46cb-bcf7-63267dceea1c)

**Comment by cillianhunter0** [comment]
I can't review this at the minute, markets are not loading on iOS or Android.

**Comment by matt-bullock** [comment]
Can you add more spacing between the filters header and markets sub header here. Looks too tight. Refer to design

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/b73d2d1d-8e8e-46c2-8aab-2a1fccce42b8)

@cillianhunter0 everything else visually looks good here but I want you to check the behaviour of drilling down the category selection to check it matches with the intended design

**Comment by rubyweb3** [comment]
> Can you add more spacing between the filters header and markets sub header here. Looks too tight. Refer to design
> 
> ![image.png](https://camo.githubusercontent.com/14cada5e478414fb1f5e870b699634af33f8778d/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563303761663437303335383935333038393131633463352f62373364326431642d386538652d343663322d386161622d326131666363636534326238)
> 
> @cillianhunter0 everything else visually looks good here but I want you to check the behaviour of drilling down the category selection to check it matches with the intended design

@matt-bullock  Updated

![Screen Shot 2020-02-13 at 4 33 40 PM](https://user-images.githubusercontent.com/58647954/74415958-4e518580-4e7f-11ea-83fa-366885b862f6.png)

**Comment by matt-bullock** [comment]
Thanks. I'm closing this as the styling all looks done. Will create separate tickets for any functionality issues
