### ISSUE TITLE
Create Design Spec for v2 Auction

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#492]
For more information on how the the auction actually functions talk to @achapman .

As a brief summary:

 - 2 ETH and 2 REP auctions per week
 - Auction starts off offering the assets at 4x the final price of the previous auction and decreases in price until the end (day long) where it would be worth nothing.
 - Users may commit any amount of the counter asset to purchasing the asset (ex. I will pay 1 ETH. At the time of commit that may entitle me to 10 REP, though unless the auction ends there I will receive more)
 - Once the auction has ended either by hitting the 1 day time limit or by the assets all being sold off the participants may redeem tokens they received for the asset they committed to buying.

**Comment by pgebheim** [comment]
Auction is gone.
