### ISSUE TITLE
Create Design Spec for v2 Continuous Dispute Rounds

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#493]
Since dispute rounds can occur on an immediate sequence with no time delay this means the UI as is may be a little unclear as to whats going on.

At a minimum we need to distinguish disputes that are in immediate mode from disputes that have returned to the normal spaced out cadence

**Comment by matt-bullock** [comment]
I suggest adding an icon to the markets which symbolise continuous dispute

**Comment by pgebheim** [comment]
This has been handled in the new reporting/dispute flows and market cards
