### ISSUE TITLE
Please make it possible to remove choices (Multiple Choice)

### ISSUE THREAD

**Issue by Augurtester** [AugurProject/augur#493]
I noted that it's possible to add more choices ("Add another answer") but not to remove them once you have done so (and changed your mind) Please fix this, much appreciated.

**Comment by housemobile** [comment]
Also m/c should by default be 2 answers, not 3.

**Comment by priecint** [comment]
@Augurtester When #377 is deployed, this is fixed.
@housemobile What do you mean by m/c?

**Comment by tinybike** [comment]
Added in 60255ce97b03441adf8c6d66aa6c11fec4369630. (Nice job, @priecint!)
