### ISSUE TITLE
Gnosis Relayer Issues

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#4932]
### Issue to hold the current main issues with the Gnosis Relayer.

<s>1) Gnosis Relayer doesn't seem to be using the provided gasPrice.

See below, sent TX with gasPrice of 1 but the relayer used 3. Even if i set the gasPrice to 22 or 100, 3 is still used by the relayer. It does appear like the relayer does take extra DAI when i use a higher gasPrice so it seems to be fulfilling half of that deal.

<img src="https://user-images.githubusercontent.com/1683736/69687678-d058bc00-1091-11ea-8b7c-dc2284a659b2.png" width="333" /></s>

2) Gnosis Relayer doesn't seem to be using the correct ETH to DAI (cash) rate. This should be a mocked value for now similar to the current price of ETH. i.e, 1 DAI = 148.46 DAI.

See below, these TX's fees should be way higher than 0.0000000035 DAI - expecting ~0.1DAI

![image](https://user-images.githubusercontent.com/1683736/69687550-4dcffc80-1091-11ea-887c-b54ef465fbea.png)

**Comment by justinbarry** [comment]
Addressing the second item. The value is currently hard coded here: https://github.com/AugurProject/safe-relay-service/commit/2d8dc18ad7db4d2ec4d06ffb017056dcc50b6c74

**Comment by joeykrug** [comment]
did 2nd ever get addressed?

**Comment by justinbarry** [comment]
We put it behind a env flag. "It" being the automatic token addition logic we hacked in.
