### ISSUE TITLE
When user has no funds, replace the buy/sell button on order ticket with 'Add Funds to Place Order' blue button

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#4938]
Clicking this will launch the Add Funds modal

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/95c8b07a-2c55-49df-8f5b-e9bdb262e904)

Design: https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=2108%3A17100

**Comment by JohnDanz** [comment]
This seems unneeded as we already show an overlay that says "No Funds" with an Add Funds button.

as shown here:

<img width="385" alt="Screen Shot 2019-11-27 at 1 24 08 PM" src="https://user-images.githubusercontent.com/10524630/69753451-42281880-1119-11ea-8321-768d4f22ab2d.png">

**Comment by matt-bullock** [comment]
The idea is to replace this overlay with the button. That way new users can see and interact with the order ticket before adding funds. Same for the logged out state: https://app.zenhub.com/workspaces/augur-5bfed3424b5806bc2bf8d173/issues/augurproject/augur/4937
