### ISSUE TITLE
show the "average price paid per share" for each position where shares are held

### ISSUE THREAD

**Issue by hyperanthropos** [AugurProject/augur#495]
this issue was created by @joeykrug, included in the beta milestone and has been closed. #56
however, the functionality is not implemented in the current live version. i think this is one of the most important information traders want to see (even more important then overall profit/loss) and should be included as initially planed.

edit: this could be shown just below the number of shares held within each outcome option

**Comment by tinybike** [comment]
Added in 59f966ae8b6d24f221fec1ec166e75a53216429e.
