### ISSUE TITLE
Consider napkin math comment for approximate Augur Ice Age

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#4961]
https://github.com/AugurProject/augur/blob/c1973d49be54288cce7d1b5d0c021ce22a8092ed/packages/augur-core/source/contracts/Augur.sol#L221-L223

I suspect that Augur can go for many upgradeCadence intervals before it stops working so this probably isn't an issue... but I think it would be valuable to add a comment with some napkin math on how many cadences before some contracts will stop working.

**Comment by nuevoalex** [comment]
Do you mean like when factoring in a hypothetical state rent?

**Comment by MicahZoltu** [comment]
Ah, nevermind.  I misread this code the first time around.  I thought this was an unbounded loop (which it technically is) but it is only actually a loop at all if no one creates a market for an entire upgrade cadence.
