### ISSUE TITLE
Make all private variables public, or ensure there are getters for each.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#4963]
https://github.com/AugurProject/augur/blob/c1973d49be54288cce7d1b5d0c021ce22a8092ed/packages/augur-core/source/contracts/Augur.sol#L72-L92

When auditing a deployed contract, it is important to be able to know what the current internal state of the contract is.  This is incredibly difficult when there are private members with no getters available.  You can sometimes derive answers to questions of "is this private variable set" by calling functions that will switch on that, but this is not ideal.

Easy solution is to just make all of those variables public (assuming no naming conflicts).  Alternative solution would be to add getters for any that are missing one (e.g., `shareTokens` doesn't appear to have a getter).

**Comment by epheph** [comment]
Are you suggesting to change the actual production contracts that get deployed to open up all private variables?

**Comment by MicahZoltu** [comment]
Yeah.  Having tried to audit production contracts with private variables, I can say that it is a huge PITA.  This is especially true when the private variables contain potentially security sensitive information like "who has admin access".  Private variables forces the auditor to try to derive current state by tracking all transactions sent to the contract over time, or using things like `getStorageAt` (which can be quite difficult to use).

**Comment by MicahZoltu** [comment]
For example, if you have an `owner` variable and it is private, auditing to ensure that the owner has correctly been cleared may prove difficult, especially if there are multiple potential owner variables that can set each other.
