### ISSUE TITLE
Consider using targeted import statements.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#4965]
https://github.com/AugurProject/augur/blob/c1973d49be54288cce7d1b5d0c021ce22a8092ed/packages/augur-core/source/contracts/Augur.sol#L4-L21

Consider using either namespaced imports or explicit imports.  This makes it much easier to identify where all variables in a file are coming from, and thus easier to audit.  This is especially true when looking at the source code without a build system setup (e.g., pulling contracts from Etherscan).

```solidity
import { IAugur } from 'ROOT/IAugur.sol'; // Usage: IAugur
import 'ROOT/IAugur.sol' as Augur; // Usage: Augur.IAugur
```

https://solidity.readthedocs.io/en/v0.5.10/layout-of-source-files.html#importing-other-source-files

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nuevoalex** [comment]
Gonna wont-fix this. All our imports pull in one contract of the filename.
