### ISSUE TITLE
market info, volume isn't getting updated

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4966]
volume isn't getting updated on market info from getter, even though there has been trading.
volume is 0.00 DAI in market trading header

![image](https://user-images.githubusercontent.com/3970376/69984038-b984f000-14fd-11ea-8012-e115a12c3744.png)

`volume` is "0"
![image](https://user-images.githubusercontent.com/3970376/69984090-e6390780-14fd-11ea-8ec5-9991864dccdd.png)

**Comment by bthaile** [comment]
waiting to see if Alex's rewrite fixes this issue.

**Comment by pgebheim** [comment]
![image](https://user-images.githubusercontent.com/86010/71737208-e59ad600-2e07-11ea-9a78-0ea24bb4cac8.png)

Works now.
