### ISSUE TITLE
Improve naming of `log` methods.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#4967]
https://github.com/AugurProject/augur/blob/c1973d49be54288cce7d1b5d0c021ce22a8092ed/packages/augur-core/source/contracts/Augur.sol#L258-L260

This method, and others, are named `log*` but the also set security critical state (such as trusted markets).  To avoid accidentally introducing or overlooking security bugs, these methods should be renamed to make it clearer that they do more than just log data.

**Comment by MicahZoltu** [comment]
Maybe `notice*MarketCreated`?

**Comment by MicahZoltu** [comment]
`recordAndLog*MarketCreated`?
`noteAndLog*MarketCreated`?

**Comment by MicahZoltu** [comment]
Same issue with `logUniverseForked`.  I don't see any others in that contract, but someone else should double check.

**Comment by epheph** [comment]
`onMarketCreated` ?
