### ISSUE TITLE
Odds-and-Ends-QA

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#4968]
- [x] Market cards - invalid tooltip on card (Matt to add this) 
- [x] Market cards - change dashes "-%" -> "0%" and gray https://www.figma.com/file/Do4qnkCNM8P7lwBmCdYZCS4X/Market-Cards?node-id=2664%3A34553

- [x] Market page - invalid tooltip on outcome (Matt has a ticket for this) 
- [x] Market page - place order button is below fold 
- [ ] Market page - font fixes for legibility + colors (Matt has a ticket for this) 
Detailed tickets for each component here: https://app.zenhub.com/workspaces/augur-5bfed3424b5806bc2bf8d173/issues/augurproject/augur/4461
Suggest for speed doing a visual comparison for fonts and colours using the figma file: https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=453%3A59625
- [x] Market page - order ticket - if entering two of the inputs it should work 
- [x] Market page - order ticket - if value in quantity, and another input, delete all characters in QTY, there's some weird behaviours in here 
- [x] Market page - estimated fee - copy in tooltip is not correct - doesn't match the figure 
- [x] Market page - scalars - "outcome" -> "Limit price" 
- [x] Market page - scalars - right side of the limit price input should have denomination

- [x] Alert menu - should close when click away anywhere 
- [x] Alert toast - apply a max width and truncate if title is huge 

- [ ] Portfolio - text style and color updates (Matt has a ticket for this)
This ticket contains all the detailed QA for Portfolio (https://app.zenhub.com/workspaces/augur-5bfed3424b5806bc2bf8d173/issues/augurproject/augur/4463) but I suggest for for speed, doing a visual matchup of type sizes and colours using the figma file: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7110%3A244314

- [x] Change Last to Last Price on the Outcomes Table

- [x] Order ticket - add 'tip' banner at the bottom of order ticket that explains that users can place a "Sell" order. It will disappear if a user enters info into the order ticket. It will disappear whenever a user makes their first trade, on a per market basis. If I go to another market it will reappear 
https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=102%3A3991

- [x] Scalar markets - add modal when you enter a scalar market that explains what a scalar market is 
https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=2613%3A0

- [x] Change 'Number of Fills' to just 'Fills' on My Fills section of market page and portfolio
----------------------------------------------------------------------------------------------------
- [x] Update main nav text size and underline. Make sure markets is active when on market pages
https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=453%3A59625

- [x] Check all headers/tabs on market page are same text size/style. Only have coloured underline on buy shares/sell shares. Remove underlines from charts and orders/positions
See https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=453%3A59625

**Comment by JohnDanz** [comment]
The last 2 bullet points above that are unchecked relate to a bunch of tickets, I don't want to leave this open just because we haven't finished the 20+ issues related to this when they are all assigned and in queue to be worked on.

**Comment by joeykrug** [comment]
status of last 2 bullets?
