### ISSUE TITLE
Create design doc for Augur State

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#497]
Located at https://docs.google.com/document/d/1IyAGC11daIhrhkfyTaN2Khn0QOXPKsoZZbu0mtyV6HI/

**Comment by justinbarry** [comment]
How does this relate to #765?

**Comment by adrake33** [comment]
Closing this as a dupe of https://github.com/AugurProject/augur/issues/765. (Info from https://docs.google.com/document/d/1IyAGC11daIhrhkfyTaN2Khn0QOXPKsoZZbu0mtyV6HI will be moved to https://docs.google.com/document/d/1ug5EU_yZjF126XOZNT3xSAe4IS5E4zPTasm5M4FY7D0.)
