### ISSUE TITLE
Basic comment anti-spam measures

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#497]
- have to buy in the market before you can comment on it
- later on when leaderboards exist, rank comments by users w/ a high leaderboards ranking first as a quality metric

**Comment by ChrisCalderon** [comment]
Just use PoW /sarcasm

**Comment by tinybike** [comment]
Changed to "Implement comments" and assigned @stephensprinkle.

**Comment by joeykrug** [comment]
This feature isn't relevant now using the new Facebook comments schema which has sorting options built in - so all that matters is the other implement comments issue referenced above
