### ISSUE TITLE
Portfolio/Account Summary Navigation is confused

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#4978]
sub-navigation is confused between portfolio and account summary

![image](https://user-images.githubusercontent.com/3970376/70006039-6036b400-1531-11ea-922c-ebe666035d04.png)

![image](https://user-images.githubusercontent.com/3970376/70006026-557c1f00-1531-11ea-9bc7-06af2cb32a3d.png)

**Comment by matt-bullock** [comment]
looks fixed
