### ISSUE TITLE
settings: show x markets per page

### ISSUE THREAD

**Issue by housemobile** [AugurProject/augur#498]
If this is not possible, 15 is too few to show per page. 25 or so is preferable.

**Comment by tinybike** [comment]
It's possible!  Just not coded yet.

**Comment by joeykrug** [comment]
Still not done

**Comment by tinybike** [comment]
I closed this because after discussing, @thinkloop and I concluded there's no need to expose this.  Why is this needed / desirable?

**Comment by joeykrug** [comment]
So if a user is on mobile they can basically infinitely scroll

**Comment by tyche78** [comment]
Intruding. Congratulations on the ui progress so far. Convinced like Joey that without some form of unlimited loading or autoscrolling, using the ui would be a pain, especially on smartphone. I favor automatic loading when bottom of page is reached. Is it technically feasible? That would be so cool.

**Comment by thinkloop** [comment]
Infinite scroll is cool, very different from what this feature describes, created new issue: https://github.com/AugurProject/augur/issues/640
