### ISSUE TITLE
Anyone can take tokens from GnosisSafeRegistry

### ISSUE THREAD

**Issue by epheph** [AugurProject/augur#4987]
There is no workflow that causes anything of value to end up on the GnosisSafeRegistry, so this is minor, but this can/does happen in the wild so it's worth mentioning

https://github.com/AugurProject/augur/blob/67c0fec95e65fca8d27751f28a6c06e5247978c6/packages/augur-core/source/contracts/GnosisSafeRegistry.sol#L33

The callRegister, while intended to be delegatedTo from a GnosisSafe, can be executed from the GnosisSafeRegistry itself. Since all actions are taken from parameters, this means you can ask the GnosisSafeRegistry to call the following functions on any contract you want, with any parameters you want (such as your own address).

- approve
- setApprovalForAll
- register
- setFingerprint
- setReferrer

**Comment by nuevoalex** [comment]
Gonna wont-fix this. No funds should ever be in this contract.
