### ISSUE TITLE
Categorical selection doesn't update correctly

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#4989]
**Issue**
Categorial selection doesn't update options for the next selection when switching choice properly.

**To Reproduce**
Go to market creation, choose custom, go to the category selection.

Change primary category to something (lets use sports in the example)

Then click on secondary category dropdown that appears and note the list is correctly showing relevant options for the primary selection (baseball, golf, boxing, etc)

Change primary category selection to a different option (example: crypto)

Click on secondary category dropdown and notice that it's still showing the previous primary category selection's relevant options (baseball, golf, boxing, etc)

Change primary category selection again to anything else (can reuse sports or something else, doesn't matter)

Click on secondary category dropdown and notice that now the dropdown shows the 2nd primary category selection (we are now on our 3rd selection for primary) in our example that would be BTC, REP, etc because it's showing crypto options now.

**Expected Behavior**
this should update based on the currently selected primary category selection.

**Screenshots**
here are some example screenshots:

<img width="327" alt="Screen Shot 2019-12-03 at 1 32 54 PM" src="https://user-images.githubusercontent.com/10524630/70083129-74ca8900-15d1-11ea-9e28-9ebddb441af0.png">

<img width="327" alt="Screen Shot 2019-12-03 at 1 33 11 PM" src="https://user-images.githubusercontent.com/10524630/70083148-7eec8780-15d1-11ea-9d77-5fb5fc8879b9.png">

<img width="325" alt="Screen Shot 2019-12-03 at 1 33 33 PM" src="https://user-images.githubusercontent.com/10524630/70083181-8c097680-15d1-11ea-99e1-e5d49b401160.png">

**Comment by phoebemirman** [comment]
fixed - not reproducible anymore
