### ISSUE TITLE
Import account successful, status bar only 60%

### ISSUE THREAD

**Issue by housemobile** [AugurProject/augur#499]
Just imported my account. Seems to have worked, but status bar does not complete.

http://i.imgur.com/aJ6wEXA.png

**Comment by martijnvanrooij** [comment]
Same issue.
Google Chrome Version 49.0.2623.87 (64-bit) on OS X El Capitan 10.11.3

QUOTE
Creating new account xxxxxxx@gmail.com...
Received 5 test Ether.
UNQUOTE
