### ISSUE TITLE
Free extra tokens when _longOutcome >= numOutcomes in  buyCompleteSetsForTrade

### ISSUE THREAD

**Issue by epheph** [AugurProject/augur#4993]
https://github.com/AugurProject/augur/blob/67c0fec95e65fca8d27751f28a6c06e5247978c6/packages/augur-core/source/contracts/reporting/ShareToken.sol#L152

When _longOutcome exceeds numOutcomes, the shortRecipient receives a full CompleteSet, and the longRecipient receives an _amount of tokens for an invalid outcomeId .

However, because _longOutcome is a uint256 that gets truncated to a uint8 here:
```
    function getTokenId(IMarket _market, uint256 _outcome) public pure returns (uint256 _tokenId) {
        bytes memory _tokenIdBytes = abi.encodePacked(_market, uint8(_outcome));
        assembly {
            _tokenId := mload(add(_tokenIdBytes, add(0x20, 0)))
        }
    }
```

If you picked a special value for _longOutcome , like 257, you would end up with an _amount of extra tokens!
the tokenId would be exactly the same as _outcome=1, so outcome 1 would mint twice as many tokens as it was supposed to (which are not backed by CASH). One set goes to short recipient (along with all other outcomes), one set goes to long recipient.

**Comment by nuevoalex** [comment]
Nice find!
