### ISSUE TITLE
MC: Mobile - landing page

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5008]
Figma link
[Figma](https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=3139%3A1534)

General
- [x] Update spacing/padding at top of the page and between the main divs to match figma **HIGH**
- [x] Check that all text styles (size + color + weight) on this page match figma **HIGH**

Saved drafts
- [x] Fix the header and footer of this div to match figma **HIGH**
- [x] Update the 'delete' button to match figma 

Use a market template
- [x] Match the spacing between elements in this div to sync up with figma 
- [x] Update 'don't see your category?' to be centre aligned and match figma **HIGH**

Start from scratch
- [x] Update spacing of elements inside this div to match figma  **HIGH**

Comparison:
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/c590b3a5-c2cf-4174-962f-94dc912aea20)

**Comment by cillianhunter0** [comment]
Two issues. 

1: 
The spacing between the category cards should be 8px, currently 6px. 


2:
Something odd is happening with some of the icons on the home screen. Lines are heavier and lighter. 

I've exported the 5 main category icons for you here to fix that. The sub cats look ok. 

Icons @40px
[https://app.zenhub.com/files/142967010/cc7f47d4-19c0-46d7-8301-0a8584f3b6eb/download](https://app.zenhub.com/files/142967010/cc7f47d4-19c0-46d7-8301-0a8584f3b6eb/download)

**Comment by cillianhunter0** [comment]
Also, can you sort them the same we have done on the ML page: 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/f3323a38-c5f9-433d-909d-5b617962d0e1)

**Comment by phoebemirman** [comment]
i have it as 8px

**Comment by phoebemirman** [comment]
the categories on the market list are sorted by the number of markets with that category based on the filters.
so the order of those will change. should the template categories be sorted by total number of markets they have (the number that is shown)? i don't think it makes sense to follow the market list sorting

**Comment by phoebemirman** [comment]
or just keep the same non-sorted order? dont think people will want to see categories changing order when they go to market creation @cillianhunter0

**Comment by bthaile** [comment]
Template landing page should be alpha order imo. Or same as default categories like filters but not based on num of markets. I think they need to be consistent. 
Since the are sorted alpha, we might as well leave market creation landing page the way they are.

**Comment by bthaile** [comment]
Fix spacing and icons then call it done and close the ticket.
