### ISSUE TITLE
Design QA: Trading Page - Order ticket outcome dropdown interaction states

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5009]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/4c679a22-a51f-4df5-bf22-f14d417b55f9)

Design: https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=1957%3A734

**Comment by matt-bullock** [comment]
Once the opening on hover is turned off we can close this

**Comment by rubyweb3** [comment]
I think https://github.com/AugurProject/augur/pull/5642 also fixes this issue

**Comment by matt-bullock** [comment]
looks good. closing
