### ISSUE TITLE
MC: Mobile - templates - market type 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5011]
Figma link
[Figma](https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=3146%3A2176)

- [x] Update spacing/padding at top of the page and between the main divs to match figma **HIGH**
- [x] Check that all text styles (size + color) on this page match figma **HIGH**
- [x] Update icons to match **HIGH**
- [ ] Check that component styling and states match figma **HIGH**
- [ ] Update spacing in main div to match figma 

Change request - tom, if this is not trivial ignore it 
- [ ] Remove the 'next' button from this step, allow user to just tap a market type to move to next step

Comparison:
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/3b4b65ea-dfd3-40ef-ab7d-da129548af56)

Check w/John about any font changes

**Comment by cillianhunter0** [comment]
- Icons are too small or are not the right icons (you can grab them here [link](https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=3146%3A2176))
- Spacing between the radio button cards is 6px should be 8px

Comparison: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/7ab2e7b9-90be-4493-aeac-1223f1b9f706)

**Comment by phoebemirman** [comment]
i have it as 8px
