### ISSUE TITLE
MC: Mobile - templates - choose a template 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5012]
Figma link
[Figma](https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=3146%3A2550)

- [x] Update spacing/padding at top of the page and between the main divs to match figma **HIGH**
- [x] Check that all text styles (size + color) on this page match figma **HIGH**
- [ ] Check that component styling and states match figma **HIGH**

Comparison:
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/da974abc-6888-4127-8f19-5495bdb80c0c)

**Comment by cillianhunter0** [comment]
There are two spacing/padding issues: 
- Within the radio button card, the padding around the content should be 16px, the right padding is 2px on some (see screenshot)
- The padding to the left and right of the radio button cards themselves should be 16px, it's 26px on the right (see screenshot)  

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/26ad69e5-a790-49d6-bf22-3b55067ff3fd)

**Comment by matt-bullock** [comment]
looks ok to me. closing
