### ISSUE TITLE
MC: Mobile - review 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5015]
Figma link
[Figma](https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=3151%3A9719)

- [x] Update spacing/padding at top of the page and between the main divs to match figma **HIGH**
- [x] Centre align the heading and preview button on top of page 
- [x] Check that all text styles (size + color) on this page match figma **HIGH**
- [x] Add the notes for invalid markets at the top of the page, see figma **HIGH**
- [x] Check that the spacing between elements in the market details div match figma 
- [x] Update tooltips to match figma 
- [ ] Update 'not enough REP/DAI' banner to match the banner component here: 
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=3052%3A94

Comparison:
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/b3bcea86-c5e9-4eee-bd14-c141a248a587)

**Comment by matt-bullock** [comment]
Image is from build
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/39b4df4a-9bdb-4bd2-9dbb-04f551abb8c6)

Move third category onto line below.
Secondary category label keep on 1 line
Secondary category and affiliate fee should should start at 50% of the page
Design:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/43885049-e2a8-48a3-aafc-610b03761864)
___

Labels should be 10px medium 9599A5
Numbers should be 12px medium

Build is showing
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/4cede30a-1b96-44bb-a30f-a362b97b9012)

________________________________________________

It's still showing the old tooltip icon.

___

**Comment by matt-bullock** [comment]
looks good. closing
