### ISSUE TITLE
Design QA: Trading Page - small dropdowns updates (candlesticks but also used in other places like portfolio)

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5016]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/84c951aa-10e1-401b-a38e-14e1ca96eca4)

Design: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=8219%3A266057

- [x] Type size and style
- [x] arrow style
- [x] hover style
- [x] Update menu items style
- [x] Update menu items hover style

**Comment by rubyweb3** [comment]
Update order expiration dropdown. However, it also cause other issues. For example:
![Screen Shot 2020-01-15 at 2 01 47 AM](https://user-images.githubusercontent.com/58647954/72424666-34673a80-373b-11ea-96c7-7039b5bd077a.png)

**Comment by rubyweb3** [comment]
Fixed the issue 
![Screen Shot 2020-01-15 at 2 39 58 AM](https://user-images.githubusercontent.com/58647954/72427433-95ddd800-3740-11ea-8a4b-b96d1f297f76.png)

**Comment by matt-bullock** [comment]
This looks good. Only thing is that it's showing up as regular rather than semi-bold. Could you please update to Semi-bold as regular looks too weak. thanks

Could you also make it so that mouse over on the button triggers the hover state. I've updated  the screenshot to show what I mean. Sorry I don't think this was clear before
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/c83f3e5c-df88-4f22-a2b8-7119fe9d5efa)

**Comment by rubyweb3** [comment]
@matt-bullock "mouse over on the button triggers the hover state"

Does it apply to all dropdown, or just small dropdown?

**Comment by matt-bullock** [comment]
@rubyweb3 this would apply to all, unless you see any issues?

**Comment by rubyweb3** [comment]
> @rubyweb3 this would apply to all, unless you see any issues?

Mobile doesn't have hover state. I will add hover state in desktop version

**Comment by matt-bullock** [comment]
Looks good. closing
