### ISSUE TITLE
MC: Mobile - custom form 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5017]
Figma link
[Figma](https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=2968%3A29468). Scroll to the right for the other variants of the form. 

- [x] Update spacing/padding at top of the page and between the main divs to match figma **HIGH**
- [x] Check that all text styles (size + color) on this page match figma **HIGH**
- [x] Check that component styling and states match figma **HIGH**
   - [x] Text input component
   - [x] Select menu / dropdown / picker component
   - [x] Radio button component
   - [x] Card radio button component 
- [x] Reduce the huge gap between 'resolution info' and 'resolution details' - should match spacing between 'market details' and 'market type' 

Multiple choice form - outcomes input
- [x] Reference [figma link](https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=3151%3A1228). Scroll to the right for other states. 

Scalar form - denom, range, precision input 
- [x] Reference [figma link](https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=3151%3A2647). 

Comparison:
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/de22cb4f-231f-4724-90a7-6fa2493ee890)

**Comment by cillianhunter0** [comment]
- [ ] When clicking into create custom it's jumping down the page, i'm seeing: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/7c38e167-aad2-4c4b-8259-e87d7cc103ac)
- [ ] Same issue as in template market ticket, when selecting a tertiary category the 'x' appears off screen
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/754450db-92b6-44d9-a50d-64ef25f5a599)

**Comment by matt-bullock** [comment]
closing. created a new ticket as there's still an issue for the last point
