### ISSUE TITLE
Design QA: Trading Page Mobile - Outcome selector

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5018]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/9deee33e-c8f4-4db9-80d8-ec7d2bbe4299)
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/7c521d81-58e4-48cd-915a-4cd244b54565)

Design: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=12661%3A2062

- [x] Dropdown selector is 40px height on mobile
- [x] Update text size and style
- [x] Update arrow style
- [x] Menu items are 48px height for mobile
- [x] check colours and interactions are in sync with the design
- [x] BG shadow when dropdown is active

**Comment by rubyweb3** [comment]
@JohnDanz @matt-bullock https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=12661%3A2062 returns 404

**Comment by rubyweb3** [comment]
> @JohnDanz @matt-bullock https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=12661%3A2062 returns 404

I have access to the file now.
