### ISSUE TITLE
Design QA: Trading Page - Order Book MOBILE

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5020]
Design: https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=184%3A3613

- [x] Reference desktop ticket for majority of changes that should get pushed through to mobile 4703

- [x] Increase row height to 24px. Lets test this but may need to go even bigger to easily select a row

**Comment by matt-bullock** [comment]
Looks weird that the price isn't visually centred in the screen and qty is far over to the right. This is also apparent on desktop but less so

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/ec325898-cbd7-44ab-8feb-7677adfc335b)

Can we get it more like the design:
@chwy can you make a call on this and prioritise or close
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/cde47d24-4ee4-4aa7-8f10-17e87a6c43fe)

**Comment by Chwy5** [comment]
Need to fix centering issues

**Comment by matt-bullock** [comment]
looks good. closing
