### ISSUE TITLE
Comments covering content on mobile when scrolling

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5021]
Happens when scrolling down then scrolling back up

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/202b8e9a-19a9-4c2d-809c-ca92e3a73695)

- [x] Fix the above issue

- [x] Remove dead space at the bottom of comments section. Should be 16px of spacing between bottom of comments section and bottom of screen

**Comment by matt-bullock** [comment]
I'm still seeing the comments covering content. To replicate issue: scroll to very bottom of page then scroll up by touching anywhere other than the comments section and the comments section will stick to the bottom of the screen whilst everything else scrolls under it

**Comment by Chwy5** [comment]
I want to remove the comments section from this screen only.....No reason to make a comment as you are entering an order
