### ISSUE TITLE
Closing the number pad on mobile often makes the page jump around

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5032]
Page shouldn't move when closing keypad

**Comment by JohnDanz** [comment]
I'm not seeing this on my iPhone as far as I can tell. after the below PR is merged can you double check this still happens? @matt-bullock 
https://github.com/AugurProject/augur/pull/5373

**Comment by matt-bullock** [comment]
I'm not seeing this anymore. Closing
