### ISSUE TITLE
User-provided IExchange isn't required to validate 0x signature

### ISSUE THREAD

**Issue by epheph** [AugurProject/augur#5033]
https://github.com/AugurProject/augur/blob/67c0fec95e65fca8d27751f28a6c06e5247978c6/packages/augur-core/source/contracts/trading/ZeroXTrade.sol#L215

The _exchange being called is provided by calldata, and while the intention is that they will provide a 0x exchange, the user can provide anything they want, including their own contract which never performs the signature check.

Once they pass that line, they have specified an order for a creator that is not themselves that they are can take at whatever price they want.

**Comment by nuevoalex** [comment]
This is basically intentional. The Exchange is being provided in the signed order so that the system can handle upgrades to the exchange contract if they occur in the future. The expectation is that order validation off chain ensures the specified exchange is valid.

**Comment by nuevoalex** [comment]
Talked about this more. The issue is that a malicious user can do this directly to force a trade from another account which did not sign anything.

**Comment by epheph** [comment]
Additionally, there is no market validity check in the 0x trade code path, it is checked on every other entry into the order book
