### ISSUE TITLE
Make Quantity display max to 2 decimal places for Binary and Categorical markets

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#5035]
We need to limit the quantity 2 decimal places for order ticket for Binary and cat markets

**Comment by Chwy5** [comment]
@JohnDanz

**Comment by JohnDanz** [comment]
after talking to chwy this sound like a site wide change more than just order ticket, in other words order book/trade history etc should always show 2 decimals for shares etc when binary/cat but up to 4 with scalar.

**Comment by matt-bullock** [comment]
Needs updating:

### Maket Page: ###
Estimated Fee
Trade History - price
Open orders - quantity
My Fills- quantity filled
Position - quantity 

### Account Summary ###
Your Overview - Total account value and breakdown of funds

### Portfolio ###
Positions - quantity
Open Orders - quantity, total cost shares
Filled Orders - quantity, quantity filled, price, filled when expanded to show fills

**Comment by JohnDanz** [comment]
Is this only for cat/binary markets? The Market Page and Portfolio parts anyway.

**Comment by Chwy5** [comment]
Yes for Cat/Binary

For Market pg, /Portfolio/ and Acct Summary
