### ISSUE TITLE
MOBILE - selecting order from orderbook will scroll up the ticket into view

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5037]
Current issue is that the user can't see their order selection filtering into the ticket. Example: ![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/0960f2e6-61e2-48f0-85e0-4b090acc6b1e)

Fix is to scroll the screen up to show populated order ticket when user taps on order on book:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f67c5eb9-34d0-4b4b-b107-6a94a4931537)

Whilst this approach works for smaller dpi devices, we may have to adapt for larger DPI as device may be large enough to show both order book and ticket, in which case there's no need for it to scroll up.

**Comment by matt-bullock** [comment]
order ticket isn't scrolling into view when I select an order from the order book

**Comment by Chwy5** [comment]
Confirmed this still needs to be fixed for v2

**Comment by matt-bullock** [comment]
working now
