### ISSUE TITLE
Dynamically resize order book dependant on mobile device height

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5039]
Is it possible to make the order book dynamically resize depending on the mobile device screen size. That way you always maximise the order book height whilst still showing some of the ticket below.

Ideal scenario is that larger devices see all the order book and the top half of ticket. Smaller devices order book and quantity and limit price inputs.

Lets explore this when there is time

**Comment by Chwy5** [comment]
****This is for the lower end of medium, don't work on this until last for medium issues

**Comment by JohnDanz** [comment]
@Chwy5 @matt-bullock can we move this to post v2?

**Comment by Chwy5** [comment]
yeah moving
