### ISSUE TITLE
MC: Mobile - market preview 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5049]
Figma link
[Figma](https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=3198%3A4747)

**Note** the build seems to be broken in how it loads the preview in on mobile. Close button is broken, elements are cut off and overlapping etc. 

- [ ] To simplify this and hopefully fix all of these issues, let's add the 'close preview' button and background div to top of the page (remove the title your market preview), then just let the market flow down below with no side borders. This should be full screen and should not show the nav bar of app. **HIGH**

Comparison:
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/596ae790-f389-4661-b495-8de48ac6ac07)

**Comment by cillianhunter0** [comment]
I wasn't able to test this on iOS but looking at it in inspector on chrome I'm seeing some issues: 
- The hamburger icon is still visible
- There is what looks like an extra border on both sides of the page

screengrab: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/363b80ca-655d-486b-b095-65f710218417)

when I scroll the hamburger icon follows me down the page: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/16eed5a6-efc3-4d4f-acae-a49178ef0d82)

**Comment by matt-bullock** [comment]
looks fixed. closing
