### ISSUE TITLE
MC: Template - added resolution rule issue

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5055]
Update title copy: 
From "Added resolution rules" 
To "Preset resolution rules" 

Update description copy:
From: "Rules for this template that will be included in your market"
To: "Rules for this template that will be included in your market and cannot be changed"

Remove the duplicate copy below that says "Added resolution rules" again. 

So we'll end up with: 
![image](https://user-images.githubusercontent.com/3970376/70546006-1dc63600-1b34-11ea-9ab8-469f40b40e4d.png)

Sceenshot of build: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/6d4bf3be-7b1d-4dcb-9e4f-d1bbe8117429)

**Comment by joeykrug** [comment]
if that unimportant, cut it
