### ISSUE TITLE
Design QA: Portfolio - Positions MOBILE

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5057]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/fd859d83-3507-4632-b336-123b37687561)

https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=6564%3A189279

 - [x] Check desktop ticket is done and that changes have pushed through to mobile

- [ ] Check Total returns/current value button up to date

- [ ] Market status tabs component should sit above the search and dropdown

- [ ] Market status tabs component is 40px height

- [ ] Market status tabs - check text styles and colours

- [ ] Update divides between rows

- [ ] Update background colour of expanded row

**Comment by matt-bullock** [comment]
Add 8px space under buttons and left align dropdown

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/1d0a84e5-0f5e-4a1f-9183-412a8828e250)

**Comment by matt-bullock** [comment]
Build is missing outline

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e0ff96dc-1baa-4781-9e47-4df9e3ddb291)

**Comment by phoebemirman** [comment]
which outline?
