### ISSUE TITLE
Relayer Fallback Work

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#5059]
Tasks:

- [x] Add Modals to the UI to explain to the user how to proceed with trading when relayer is down
- Wire up the UI Modals to show. Should show when 
  - [x] 1) TX fails due to relayer down
  - [x] 2) Safe Creation fails due to relayer being down
- [x] Add a new TX Event in the middleware (RELAYER_DOWN)
- [x] Set ```useRelayer``` to false when the relayer isn't working
- [x] Provide a means to gauge the health status of the relayer (before TX or react to TX errors)

**Comment by joeykrug** [comment]
status?

**Comment by andrewdamelio** [comment]
completed

**Comment by joeykrug** [comment]
yay!
