### ISSUE TITLE
User is seeing very large P/L

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#506]
We are not sure of the exact steps to reproduce this, but it has been raised in Discord several times.
![12-4](https://user-images.githubusercontent.com/11491365/49457006-ec878d00-f79e-11e8-9af9-1b51bd38108e.jpg)

**Comment by bthaile** [comment]
helpfully this gets cleared up with new P/L changes. Adding Paul to this tix

**Comment by adrake33** [comment]
Closing this for now. If it gets reported again, we can reopen it.
