### ISSUE TITLE
Cant Allow Event Resolution time to occur before estimated scheduled start time on any template 

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#5062]
Any Template which has an estimated scheduled start time...the event resolution can not occur before the start time

**Comment by joeykrug** [comment]
did this get done

**Comment by bthaile** [comment]
Yes, this got done

**Comment by Chwy5** [comment]
reopening until i can confirm on v2

**Comment by Chwy5** [comment]
closing
