### ISSUE TITLE
Categories on Market trading pg are not displaying correctly

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#5072]
On V2 finance shows 0 markets, but if i click it....

![12-5o.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/dc8f3513-cf2d-47b2-a354-030ce6fdb554)

but if i click it, i see this...

![12-5o1.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/b600f8f2-9520-4864-b222-ac85230e7d0f)

same for crypto categories

**Comment by Chwy5** [comment]
Still appears to do it with the current Science Category under All Categories....shows 1, when I click on it, there are 2 markets in there

**Comment by bconfortin** [comment]
Fixed, most likely by @andrewdamelio

**Comment by bthaile** [comment]
@andrewdamelio can you see if your recent changes fixed this issue

**Comment by andrewdamelio** [comment]
@bthaile looks like it working - not sure what recently changes i made though that fixed this 🤔

**Comment by Chwy5** [comment]
@andrewdamelio this issue is occurring again (it was fixed for a while) can u please take a look....see joey's comments below:
WebSocket network error: OSStatus Error -9807: Invalid certificate chain 
2augur.781eb2eafdf97b31883c.js:2:11686932
getting this in console on safari
also categories don't seem to work?
if i change spread from all to 10%
and back to all
then they show up
then Politics shows 1 market
I click on it
then 2 actually appear
and the politics counter updates to 2
if i go back to all categories
politics then updates to 1
this is a new regression in past few days, did not occur previously for me
afaik
yeah there's a big list of ui/ux issues on github @tinybike
ui code wise, designs are done
