### ISSUE TITLE
No incentive to call Universe.sweepInterest()

### ISSUE THREAD

**Issue by epheph** [AugurProject/augur#5078]
https://github.com/AugurProject/augur/blob/67c0fec95e65fca8d27751f28a6c06e5247978c6/packages/augur-core/source/contracts/reporting/Universe.sol#L700

It seems this should be called automatically when the next disputeWindow is created?

**Comment by nuevoalex** [comment]
We could add that. Some thoughts on that though:

- If we _depend_ on that someone can troll it by preemptively creating dispute windows in the future which we allow.
- If there _is_ some critical MKR related DSR bug that emerges in the future this would result in a total system shutdown whereas currently it would just stop sweeping interest.
