### ISSUE TITLE
Need a way for user to easily assess risk

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#508]
User signs on and sees 1-day or 30 day PnL changed...need an easy way for the user to access where the change is coming from, not clicking open every market and going through each open position, to compare quantity and avg price to last price.....

I currently have 7 open markets with multiple open positions and it just took me 40 mins to figure out where my PnL change came from
...

I'll slate this for soon after MVP.
 -sharkcrayon
...

@chwy  what can we add to help the user understand this?
 -sharkcrayon
...

getting rid of shares should help a little, but a redo of teh users portfolio so they can easily see what is changing in the positions
 -Chwy5
...

We don’t show a user pnl per position in their portfolio? We should. Do we show total pnl and also 24 hr and 30 day pnl too? If not, of course we should add that which is why it’s confusing right now!

 -joeykrug

**Comment by joeykrug** [comment]
in pnl changes chwy is organizing
