### ISSUE TITLE
WarpSync market text should not say "end of market".

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#5082]
https://github.com/AugurProject/augur/blob/21f4286e1fab3e3f3b3bb31048e849a381317103/packages/augur-core/source/contracts/WarpSync.sol#L25

There have been problems in the past with reporting on markets that use the terminology "end time" as that isn't a technical term in the Augur reporting world.  A more correct term would be "reporting start time".

**Comment by MicahZoltu** [comment]
Separately: I recommend you run the text by #reporting to get additional feedback.  This market needs to be ultra-clear, since invalid is _really bad_.

**Comment by MicahZoltu** [comment]
Perhaps, "...for the last block with a timestamp less than the reporting start timestamp for this market?"  I don't think there is additional value in including "equal to", and it has potential to cause unnecessary ruckus of the "you cannot know the answer at reporting start time!" variety.

**Comment by pgebheim** [comment]
I actually would prefer this market define specific block heights somehow, though I'm not certain we can do that in a particularly good way.

**Comment by epheph** [comment]
> I actually would prefer this market define specific block heights somehow, though I'm not certain we can do that in a particularly good way.

I smell some awful Solidity assembly brewing

**Comment by pgebheim** [comment]
Joey points out this is a bad idea because the block time will likely decrease in the future as an in place upgrade.
