### ISSUE TITLE
Reporting ease of use improvements

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#509]
From Reddit:

Can you make it so that after submitting a report I am redirected not just back to the reporting page but to the point where I left off? I have to keep scrolling down to try to find where I left off. 

You could also include a "show reported markets" checkbox that shows (and importantly, removes when unchecked) the markets that I have submitted a report on. This would make navigating the reporting page a lot easier. 

At this moment, it is difficult. So difficult that I gave up after reporting on "enough" markets. If it were easy to navigate and tell which markets I had already reported on an which I had not, I would have continued.

**Comment by housemobile** [comment]
This needs to be done. Came to make similar issue. At present, way too much scrolling is required.

Checkbox would work well.

**Comment by tinybike** [comment]
Old UI issue.
