### ISSUE TITLE
Add reporting and dispute history to market page

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#509]
From Discord:

Design Feedback (@Serena @MattB): When I look at a market that is currently in reporting, along with trading I should also see details about the current state of reporting.  Round number, tentative outcome, etc.  I should also see a button to dispute the market if it is up for dispute, and if I am the designated reporter I should see a button to submit designated report.
At the moment, if someone links me (a reporter) to a market I have to then go manually locate that market in the reporting list in order to report on it.  As more and more markets make it into that list, this becomes more and more of a difficult task.
🙏
2
This is particularly important for giving people a way to gather capital for disputes.  If you see a market that should be disputed but don't have capital to do it yourself, you need to be able to link people to the market to get their support.
tomhaileToday at 3:56 PM
And having a reporting history on the market would be nice, it would tell nee reporter whats been going on.
...

@serena Is the first item done with addition of the `Report` button on the Market Trading page?

And is adding report history on the `todo` list? We can use this tix for adding reporting history (will need design).
 -bthaile
...

 I agree with the need to add reporting and dispute history to the market page. Good idea, let’s use this ticket for that. I’ll adjust the title.

And yes, the first issues mentioned are taken care of now. 
 -sharkcrayon

**Comment by joeykrug** [comment]
Done
