### ISSUE TITLE
Only one thing to report on

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#510]
I only see one thing to report on, should I be seeing more?

**Comment by joeykrug** [comment]
Now I see 0

**Comment by tinybike** [comment]
Have all markets loaded when you see 1 or 0 to report on?  (In the console,
is there a "all markets and logs successfully loaded" message?)

**Comment by joeykrug** [comment]
Yes they have.  After waiting on the reporting page for ~30 sec. they appeared
