### ISSUE TITLE
Need to add TOTAL or Total ETH

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#510]
I thought this from the first day i tried this and still as a trader am not comfortable not seeing Total Eth per open order and Filled order.

As a trader I want to know how much total eth is tied up in each open order (quantity x price), so if i need to free up eth I can cancel very quickly...Same for filled orders...I want to know the total eth consumed in a trade...in case I want to replicate or partial the trade again.  A user does not want to have to plug numbers into the order ticket to see and Est Cost (if they already have an open position or filled trade)

Also, (already brought up in another ticket) but the est cost does not work properly in my opinion as if a user has an open position,  it shows the user the est cost taking into account the open position....a user wants to see what the true est cost would be without the open position.
...

> Also, (already brought up in another ticket) but the est cost does not work properly in my opinion as if a user has an open position, it shows the user the est cost taking into account the open position....a user wants to see what the true est cost would be without the open position.

@chwy Are you talking about how we show the cost of an order in both ETH and shares? For example if you are holding 10 shares, and you go to place in a sell order of 20 shares, that will show you an estimated cost of X ETH and 10 shares?

> As a trader I want to know how much total eth is tied up in each open order (quantity x price), so if i need to free up eth I can cancel very quickly...Same for filled orders...I want to know the total eth consumed in a trade...in case I want to replicate or partial the trade again. A user does not want to have to plug numbers into the order ticket to see and Est Cost (if they already have an open position or filled trade)

Are you saying we should have a total cost column in the Open Orders section here on the Trading page as well as on the Portfolio page:

![clipboard 2018-22-06 at 4 56 06 pm](https://user-images.githubusercontent.com/11491365/49621339-af2b2700-f979-11e8-9707-22ef5da60e75.png)

What if part of the order cost is in shares?  For example, if you were holding 10 shares and then you placed a sell order for ten shares?
 -sharkcrayon
...

It might just be a terminology issue.....To me est cost (is trade based) is (what i explained above), what Augur calculates for est cost (if you have an open position) is the estimated change in position for that trade.

what most betters and traders will be familiar with (imo) should be similar to centralized exchanges.....On a CEX when you input your amount and price it shows the amount to be traded.  For example, If i was long 10 eth on Gdax and entered to sell 2 lots at $500...it will show my total (Est cost) as $1000
 -Chwy5
...

Sorry back to the original question...Are you saying we should have a total cost column in the Open Orders section here on the Trading page as well as on the Portfolio page:

Yes i do
 -Chwy5
...

@serena what additional info is needed here? What do we want to do here, let me know design wise and ill start on it 
 -JohnDanz
...

I think this is a v101 issue, since it is a functionality change/improvement. Moving to v101  for further consideration.
 -sharkcrayon
...

@serena Do you know if there is another ticket for this? Chwy thinks maybe this is a duplicate.
 -adrake33
...

@chwy  this is partly addressed by the escrow columns we now have for open orders, right? 

 The other issue (of what “total” means)  is similar to another discussion we were having (the need to show max cost for an order), but is not the exact same. I think we should keep the ticket open. 
 -sharkcrayon
...

Yup escrowed Eth in the my positions  part of open orders addresses total eth.....Still needs to be added for filled orders imo.
 -Chwy5

**Comment by joeykrug** [comment]
duplicate
