### ISSUE TITLE
"The outcome you have reported is: _none_" display error.

### ISSUE THREAD

**Issue by jreale** [AugurProject/augur#511]
When reporting on a market, no matter what outcome I choose, the modal shows
"You have reported the outcome of this market!
The outcome you have reported is: _none_"
The correct report value does show up in the list, however.

**Comment by housemobile** [comment]
same issue. when the pop-up first comes up it shows your answer, then it changes to none

**Comment by tinybike** [comment]
Obsoleted by 59f966ae8b6d24f221fec1ec166e75a53216429e.
