### ISSUE TITLE
Make `masterCopy` in ProxyFactory public.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#5115]
https://github.com/AugurProject/augur/blob/7b9c2675588ac9a7f0b3a9dd740a37366953272f/packages/augur-core/source/contracts/ProxyFactory.sol#L6-L8

While I understand the cost issue mentioned in the ProxyFactory comment, I don't think this is worth it.  The primary reason is that without exposing `masterCopy` tooling will not be able to identify what the proxy is proxying to.  The number one place that this is useful is when looking at a Proxy on EtherScan.  As currently written, it will not be possible for anyone other than an expert user to look at a Proxy instance on EtherScan and identify what it is proxying too.

It is worth noting that `CloneFactory` has this same problem, but at least it is using a standard proxy and there is hope that EtherScan will add native support for standard proxies in the future.  It is unlikely that EtherScan will add native support for this custom proxy though.

On a related note, why is the Gnosis stuff using `Proxy` instead of the standardized `Clone` that is used everywhere else?

**Comment by nuevoalex** [comment]
These aren’t our contracts. They are in our codebase for testing but are created and deployed by Gnosis
