### ISSUE TITLE
Malicious relayer or MitM can give user a bad safe, or no safe and just pocket the fee.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#5116]
https://github.com/AugurProject/augur/blob/7b9c2675588ac9a7f0b3a9dd740a37366953272f/packages/augur-sdk/src/api/Gnosis.ts#L299-L314

When creating a safe via a relayer, the UI will send a request to the relayer to create a safe and the relayer will respond with an address.  The UI currently doesn't validate the address before putting it into the "safesToCheck" queue.

A malicious relayer or man in the middle could return any address they want from that request, and the user would then send assets there.  Worse, the relayer could create an actual safe at that address but where the initializer is their own, rather than the expected initializer.  This would make it so the user sees an otherwise functioning safe that even matches the expected code, but the relayer could later steal any funds the user deposits during this session.

The fix for this is easy (once #4975 is resolved): Call `this.calculateGnosisSafeAddress` and compare it against `response.safe`.

**Comment by nuevoalex** [comment]
This will likely end up on someone other than me. It's a piece of the Gnosis integration we've known we have to do though I'm not sure why it's been left out.

**Comment by MicahZoltu** [comment]
The code already exists to check/validate the address.  It just isn't called in this specific code path.  I'm guessing an oversight.
