### ISSUE TITLE
All markets to be reported on show Share Volume of 0.0

### ISSUE THREAD

**Issue by jreale** [AugurProject/augur#512]
There were 75 markets to be reported on in my console, and in the spirit of the beta, I figured I'd give it a shot, but my patience quickly ran out after 7 or 8.  So I thought I'd at least report on any that had shares on the line.  But every single one showed a Volume of 0.0 shares.  Could that be true?  Also, I'd hate to think that any of our actual REP will be at stake for null markets :-)

**Comment by tinybike** [comment]
Old UI issue.
