### ISSUE TITLE
Design QA: Account Summary - Notifications - MOBILE

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5126]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/6309726d-9619-4cb2-b3ff-07287ceb70b4)

Design: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7266%3A247595

- [x] Apply desktop fixes
- [x] Make VIEW button mobile friendly

**Comment by cillianhunter0** [comment]
Closing this and adding comments to 5371
