### ISSUE TITLE
Design QA: Account Summary - My Active Markets - MOBILE

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5127]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/34058def-449f-4fe6-9975-ca455e7b2fcf)

- [x] Desktop ticket done #4771

- [x] Area with search and 24hr change looks broken

- [x] Fix divides between markets

**Comment by JohnDanz** [comment]
where's the figma link for this on mobile?

**Comment by matt-bullock** [comment]
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=6626%3A193084

https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=6653%3A1108

**Comment by pgebheim** [comment]
@JohnDanz -- is this done or is there more to do here (seeing open check boxes above)

**Comment by JohnDanz** [comment]
It's in QA Review -- I just forgot to check boxes -- waiting on matt to confirm

**Comment by matt-bullock** [comment]
closing
