### ISSUE TITLE
Design QA: Account Summary - Watchlist - MOBILE

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5128]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/05262bc1-a97d-4d68-a0fd-4e3c4e6d6d1c)

Design: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=6626%3A192340

- [ ] Desktop fixes

- [ ] Dividers between markets

**Comment by JohnDanz** [comment]
is this accurate? I can't find the figma designs don't seem to match the screenshots? maybe I'm looking at the wrong place

**Comment by matt-bullock** [comment]
The above link sends me here. Looks correct 
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/ef88fbf7-aa9f-49dd-b6ac-01abfa602751)

**Comment by matt-bullock** [comment]
looks good. closing
