### ISSUE TITLE
Warn users when fees are high

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#513]
Suggested changes:

The UI should prevent, or at least heavily discourage, a user from making a trade with a guaranteed loss. In this case buying at over 50% should be prevented or strongly warned.

~~Additionally, the potential profit display should probably also factor in fees. In this case potential profit would have been negative after accounting for fees.~~ (moved to ch17355)
...

I’m in favor of immediately moving forward with the PL update, no design work needed for that.

@achapman If you’re in favor of that, can you make a new ticket for just that part and assign it appropriately? I’m not sure if John or Paul/Scott is the right person for that.
 -sharkcrayon
...

Out of curiosity, how does the PL take into account that the fee is only charged when users convert a complete set back into ETH?
 -sharkcrayon
...

@pgebheim  and @johndanz have worked the most on PL. They can probably answer.
 -adrake33
...

It would have to factor that into the potential profit as though they were going to do settlement with Augur instead of selling the share to someone else.
 -nuevoalex
...

Sounds good regarding the PL change. I believe this instance of PL is entirely UI / Augurjs side so I'll put it in frontend.
 -nuevoalex
...

https://app.clubhouse.io/augur/story/17355/order-form-pl-should-factor-in-fees
 -nuevoalex

**Comment by joeykrug** [comment]
UI has fee filter now
