### ISSUE TITLE
Alignments of positions, M Fills/Filled Orders on trading pg and AS pg are off

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#5131]
The Positions section of the AS pg and Filled orders are not alligned:

![12-9a.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/1f82430f-79af-4e65-a717-e65410d2bd07)

My Fills on the trading pg is not aligned:

![12-9.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/aea4ae3a-a936-4813-99aa-77a6385cccad)

**Comment by matt-bullock** [comment]
Looks fixed. closing
