### ISSUE TITLE
Need to portray Complete sets to the user better

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#514]
Users have a hard time knowing when they have a complete set to redeem.

Currently a message is at the bottom of the trading pg, under outcomes, under positions, under open orders....

there should be a message to the user when they sign on that they have compete sets to sell.

Also imo should have a message on the top of the trading pg where the compete sets are on.

I also think we should have a user settings, which we can allow users to select if they wish to receive notification messages, such as sell complete sets,

see attached screenshot
...

@serena @mattbullock Please take this into consideration as part of the Trading Page redesign.
 -adrake33

**Comment by joeykrug** [comment]
Users should never end up with unwanted complete sets due to #788
