### ISSUE TITLE
Account creation stalls

### ISSUE THREAD

**Issue by tyche78** [AugurProject/augur#514]
Tried to create account _kal-el_ on augur.net, the process stalled. _kalel_ went through with no problem at nearly the same time.

**Comment by tyche78** [comment]
Nevermind, _kalel_ has stalled too, just a bit further in the process. Overloaded nodes?

**Comment by tyche78** [comment]
Both accounts exist and I can connect but they both hold no cash/rep and one of them holds nothing at all

**Comment by tinybike** [comment]
I think so!  We're switching from our hosted nodes to etherscan's API
shortly, which should resolve several problems that pop up when our nodes'
RPC servers are overloaded.

**Comment by tyche78** [comment]
That explains all.

**Comment by tinybike** [comment]
This should be fixed with the latest account / faucet updates.  Will re-open if The Stall occurs again.
