### ISSUE TITLE
Display message when Cancel Order button is disabled

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#515]
When the user cancels an order and the transaction signing window pops up, we were not disabling the Cancel button, so the order could be canceled twice. 

Phoebe is fixing this as part of https://app.clubhouse.io/augur/story/17871/orders-can-be-canceled-multiple-times by disabling the Cancel button in this scenario. However, we may want to display a message informing the user why it's disabled (similar to how we do when the user creates a market & then signs the tx).

**Comment by joeykrug** [comment]
This seems obvious, if end up getting user complaints can do it but for now, not do it
