### ISSUE TITLE
Faucet to gnosis safe relayer address in dev/test deploys

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#5155]
When we deploy to kovan or other test networks, we need to faucet Cash to the relayer's address so it can Robinhood that cash to users.

**Comment by justinbarry** [comment]
@petong This needs to be done after every kovan deploy.

`ETHEREUM_HTTP=https://eth-kovan.alchemyapi.io/jsonrpc/1FomA6seLdWDvpIRvL9J5NhwPHLIGbWA ETHEREUM_PRIVATE_KEY=<KEY_WITH_ETH> yarn flash run faucet -a 100000 -t <RELAY_PUBLIC_KEY>`

**Comment by robert-e-davidson3** [comment]
Done.
