### ISSUE TITLE
Withdrawing on the account page gives zero confirmation

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#516]
Withdrawing using the UI in the account pages gives you zero confirmation of the withdraw, in-progress, anything. If you're not using MM, you can't even look at the TX. No notification. (example report was w/ Ledger).
...

@mattbullock We should talk about what should be shown here.
 -sharkcrayon
...

![screen shot 2018-09-10 at 5 45 53 pm](https://user-images.githubusercontent.com/11491365/49621305-8440d300-f979-11e8-8d2d-eda679061d3b.png)

There is a notification with etherscan link now, I think we are good.

@serena agree or do we need to add something?
 -bthaile

**Comment by joeykrug** [comment]
There's no notification for this still.. on sneakpeak

**Comment by Chwy5** [comment]
@cillian is this fixed now? close if it is

**Comment by cillianhunter0** [comment]
Fixed
