### ISSUE TITLE
Question not clearly resolved by time of expiration

### ISSUE THREAD

**Issue by DanielCarlyleEvans** [AugurProject/augur#516]
Here is the example:

Will Republicans host hearings for Merrick Garland?

Matured: Mar 20, 2016

So.... they haven't held hearings by the maturity date.  Should it be assumed that the original question means has this happened by the maturity date?  It would obviously be better if it were worded that way.  There certainly is still a chance the Republicans will host hearings and it is somewhat unresolved.  I'm not sure whether to call this a "No" or "Indeterminate".  I am going to mark indeterminate because I tend to be literal and want the questions worded clearly, but this issue will probably come up often and perhaps guidance should be given as to how to handle it.

**Comment by joeykrug** [comment]
"Should it be assumed that the original question means has this happened by the maturity date?"
I'd say yes --- we'll write up a set of "reporting guidelines" and then the community can edit them
