### ISSUE TITLE
Gnosis safe - relayer down for existing users 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5162]
If relayers go down for a user who tries to make a transaction:

- [x] Modal appears whenever a user tries to make a transaction that explains the situation and provides a link to add ETH:
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/71632f29-e36e-4d2a-8643-757fadbe52fd)
https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=1783%3A125283

- [x] Add ETH modal - the same as the add funds modal with changes to all of the copy, switching 'dai' to 'eth'
   - The 'need help' on the bottom left has been removed and tooltips have been removed 
   - Instruction copy on Coinbase and transfer options updated
   - 'Augur account address' label copy updated on Coinbase and transfer options 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/55383b0e-238b-477b-90f2-5701f9a70184)
https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=1773%3A28

**Comment by joeykrug** [comment]
after 0x stuff can you do this next Andy?

**Comment by andrewdamelio** [comment]
@joeykrug yup
