### ISSUE TITLE
Reporting page shows initial odds, not final odds

### ISSUE THREAD

**Issue by DanielCarlyleEvans** [AugurProject/augur#517]
In the FAQ about rep it states that much of the reporting will be fairly trivial as the final odds (share price) will make it clear how the question was resolved.  As I am doing the reporting, everything seems set to the initial equally distributed model (50/50 for example).  Either the FAQ should be changed, or the final info needs to pull through to the reporting page.

**Comment by maveric** [comment]
I noticed that every single report I was asked to find info on had 0 trade volume. If your set was the same, then initial was final. Already posted an issue about reporting on 0 volume markets.

**Comment by thinkloop** [comment]
Should reporting page show any odds?

**Comment by joeykrug** [comment]
If event only has 1 market should show that market's final odds

**Comment by tinybike** [comment]
Old UI issue.
