### ISSUE TITLE
Add "extra" metadata to reporting page

### ISSUE THREAD

**Issue by DanielCarlyleEvans** [AugurProject/augur#518]
It could be that no one included these (I did when I set up a market).

It is really helpful to have a link there to find the information (for example to an exchange which provides the quotes).  Either these aren't pulling through  to the reporting page in the beta or no one is using these fields when they set up the market.

Some of the reporting is actually quite difficult to determine and very time consuming.  Thought should be given on how to motivate the market makers to include information helpful to the reporters on the back end.

**Comment by martijnvanrooij** [comment]
Same Description and Resources information is blank on the Markets page (clicking on a specific market) as well. I tested with a very comprehensive market I created myself with lots of additional details ... no luck.

**Comment by joeykrug** [comment]
fixed in latest version
