### ISSUE TITLE
Malicious ABI encoding of 0x order AssetData causes incorrect parsing of order details

### ISSUE THREAD

**Issue by epheph** [AugurProject/augur#5181]
The code here:

https://github.com/AugurProject/augur/blob/153f5d2b0a328727beec4ddba72fe02e85be2f86/packages/augur-sdk/src/state/db/ZeroXOrders.ts#L115-L118

directly indexes into the AssetData of 0x orders using fixed offsets in order to extract the market, outcome, price, and type of an order. However, this code does not take into consideration the multiple ways the exact same data could be ABI encoded. When dealing with variable-length ABI encoded items, the fixed offset does not represent where the data lives, but an offset to where the data lives (relative to the beginning of the entire abi encoded message). Just because one ABI encode put the marketData at point 456, does not mean the next has to put it in the same place. Take the following as offsets from the end of the 4-byte function signature. The AssetData is commonly encoded this way (note that Exchange is no longer encoded, that needs to be fixed as well. See #5146  ):

```
0  : tokenAddress
64 : offset for tokenIds (->320)
128: offset for token Values (->448)
192: callback data (->576)
256: kyctoken
320: length of tokenIds array (1)
384: tokenIds data
448: length of tokenValues array (1)
512: tokenValues
576: length of callbackData (1)
640: callbackData
```
Here, the marketId, outcome,price, and type data begin at offset `384`

Now imagine that a malicious user encoded their order this way instead:
```
0: tokenAddress
64: offset for tokenIds (->576)
128 offset for token Values (->448)
192 callback data (->256) (We just repurpose the 0-data in kyctoken to imply 0-length bytes)
256 kyctoken
320 EMPTY VALUE
384 REALLY GOOD OFFER
448 length of tokenValues array (1)
512 tokenValues
576 length of tokenIds (1)
640 REALLY BAD OFFER
```

When the parseAssetData takes this data (from offset `384`) it will believe this is REALLY GOOD OFFER for matching/display to user. However, when this data is brought to the chain, it is correctly parsed and tokenIds = `[REALLY BAD OFFER]`.

`REALLY GOOD OFFER` is not a part of the ABI Decoded data structure at all.

The solution here is to first read the offset at 64 (or wherever tokenIds lives) and read from THAT offset +64 ( so long as value at offset 64 is 1)

**Comment by pgebheim** [comment]
Merged changes into zeroX branch

**Comment by epheph** [comment]
@pgebheim I don't see this fixed in master or in any of the PRs:

https://github.com/AugurProject/augur/blob/master/packages/augur-sdk/src/state/db/ZeroXOrders.ts#L130

**Comment by epheph** [comment]
@pgebheim pointed me to the code he was talking about, it it does resolve this issue.
