### ISSUE TITLE
Group reports intelligently (by tag?) to make it easier for reporters to report

### ISSUE THREAD

**Issue by DanielCarlyleEvans** [AugurProject/augur#519]
For example, there are a ton of S&P will close... type of questions but they are scattered all over the reporting page.  It would be really nice to see these grouped up so that they could all be dealt with at once.  Similarly, sports scores and politics are easiest dealt with at the same time.

I would think the tags would help with this.

General categories would also be helpful for this (Sports, Politics, Pop Culture, Crypto, Economics, Other, etc.).

Overall I find the reporting to be pretty laborious right now.  I know it will be very important to see this done well, so whatever can be done to ease the pain will be important.  Also, I know that people owning more rep will receive more reward.  Will people with more rep also do a larger share of the reporting?  It would be onerous for someone with a small amount of rep to do this much reporting in my opinion and I would expect that to lead to only a few large rep holders meaning too much centralization.

Thank you for your work on this.  It is an exciting project.  I know that it is a lot of work.

**Comment by joeykrug** [comment]
Yes they will do more reporting.  Good idea to group similar markets
