### ISSUE TITLE
Submit Multiple transactions in bulk and not individually

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#519]
Not sure Augur can do this?  Paradex was set up for bulk transactions.  When a user has multiple orders submit them all at once instead of individually.
...

@achapman I don't believe the smart contracts currently allow this, do they?  Would this be possible to add? It seems like it would require passing in an array of order objects to a function, which I don't think can be done in Solidity.
 -adrake33
...

This is something we can add fairly easily to the contracts. Lets make a contract task for this for v2 to go with this.
 -nuevoalex
...

Ok, I created a separate ticket for the backend task and linked it.
 -adrake33
...

 Do we still need this ticket open? What would change in the UI?
 -sharkcrayon
...

If I'm understanding correctly, it sounds like this would require a UI on the trading page for allowing the user to specify multiple orders that could then be submitted in bulk. Can you let @serena know what you had in mind for this UI-wise, @chwy? Would there be design changes needed?
 -adrake33
...

The first change would be on the contract level (i believe it is being added for v2).  The UI change would possibly need to include a Submit All button in market creation....where the user doesnt have to sign a ton of MM signing boxes if they place multiple orders in pre-liquidity.

 -Chwy5
...

@chwy Ok, so this would only affect the market creation flow, not on the trading page, correct?
 -adrake33
...

Yes
 -Chwy5

**Comment by pgebheim** [comment]
Closing as Feature Request (can be resurrected later if it makes sense)
