### ISSUE TITLE
Missing Trades

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#5192]
Cleared out cache and had blank acct on V2 No Gnosis safe version:

First trade I tried failed:

Second trade in Yes/No Market worked...I sold 20 shares of Yes at 75 (frozen Funds worked correctly)
 3rd trade I tried to enter an open order to place on the order book....sell 10 shares of No at .3

Trade can be seen in bell message but does not in my Open orders, My Fills, or Positions and FF doesnt update...trade does not appear on the order book either

![12-11mo.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/f544ecf6-6f6e-476d-bdae-d335f2a6773b)

Refreshing made the trade appear on the book and in my open orders

**Comment by joeykrug** [comment]
fixed
