### ISSUE TITLE
TP: Responsive design (Breakpoints)

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5196]
Trading page responsive designs (at all breakpoints):
https://www.figma.com/file/og1llFtTU9l5F2hk5tKMxc/Responsive-Layouts?node-id=0%3A1
Scroll left to right to see mobile up to x-large desktop. 

- [ ] Check that the build matches the breakpoints and layout at breakpoints in figma

### Mobile 
looks good and doesn't need work

### Tablet
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/b486d2bf-0a5f-45b2-a3d3-3fc4780d67ce)

https://www.figma.com/file/og1llFtTU9l5F2hk5tKMxc/Responsive-Layouts?node-id=1%3A23302

** Changes: **

- [  ] Stack market info: See mocks
- [  ] Order ticket, order book and trade history are sat next to each other in 3 columns. All at equal height - I suggest matching the height of the order ticket and review how this works

### Regular Desktop
Looks good - doesn't require changes

### Wide Desktop
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/634cd012-da9e-4953-8cad-951d6f57bc85)

https://www.figma.com/file/og1llFtTU9l5F2hk5tKMxc/Responsive-Layouts?node-id=1%3A23493

** Changes **

- [ ] Move order book next to order ticket
- [ ] Move trade history to the far right - see mock

### Ultrawide Desktop

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e7ea5f27-6319-4430-8da8-cb363ab1785d)

https://www.figma.com/file/og1llFtTU9l5F2hk5tKMxc/Responsive-Layouts?node-id=1%3A23455

** Changes **

- [ ] Move order book next to order ticket
- [ ] Move trade history to the far right - see mock
- [ ] Separate out charts - see mock

**Comment by Chwy5** [comment]
@cillianhunter0 please add more info

**Comment by Chwy5** [comment]
Closing this ticket....We need to make to make sure breakpoints for tablet display like desktop and not like mobile
