### ISSUE TITLE
Portfolio: Responsive design

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5197]
See this figma link for design at all breakpoints: 
https://www.figma.com/file/og1llFtTU9l5F2hk5tKMxc/Responsive-Layouts?node-id=0%3A1

Scroll left to right to see mobile up to x-large desktop. 

**Note for dev:** Arrange call with Matt to chat through this ticket. 

- [ ] Check that the build matches the breakpoints and layout at breakpoints in figma

**Comment by cillianhunter0** [comment]
@phoebemirman i wasn't able to check with content in each box but the layout looks good. Just spotted three issues:

Mobile
- [ ] Tabs should be above the dropdown/search inputs on Positions tab (same applies to the My Created Markets tab)
- [ ] Remove the word 'display' from the display total returns button 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/f255ce1e-9fc2-4b24-aa8e-8e3315e2402d)

Tablet
- [ ] Sort by dropdown should be right aligned 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/2bcb2cf0-01af-410f-a5ad-ba3135b0006d)

**Comment by matt-bullock** [comment]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/560a9256-035f-4350-9289-09700e585f17)

Is it much work to left align the dropdown on mobile and tablet? Would be good to get in as it helps balance out that area - as shown in the screenshot above. If too much work, can pass

**Comment by Matts** [comment]
@phoebemirman wrong poke. Have a nice day
