### ISSUE TITLE
Account Summary: Responsive design (Breakpoints) 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5198]
See this figma link for design at all breakpoints: 
https://www.figma.com/file/og1llFtTU9l5F2hk5tKMxc/Responsive-Layouts?node-id=0%3A1

Scroll left to right to see mobile up to x-large desktop. 

**Note for dev:** Arrange call with Matt to chat through this ticket. 

- [ ] Check that the build matches the breakpoints and layout at breakpoints in figma

**Comment by matt-bullock** [comment]
Account summary breakpoints is very straight forward. Just refer to the mocks and give me a shout if anything needs clarity

**Comment by matt-bullock** [comment]
looks to be working. closing
