### ISSUE TITLE
Allow the user to choose the end date timezone in Create Market

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#520]
See Joey‘s comments below.
...

This'd be nice
 -joeykrug
...

@mattbullock this could also be added to the core stats, so use could change their timezone.
 -bthaile
...

@chwy Is this something that we want to do?
 -bthaile
...

Definitely makes this a much better experience for the user....allowing them to create markets in their own time zone

Issue that it may cause though, is confusion in contests...especially if there are multiple contests on the  same event, with different time zone expiration times.  IMO i think it is a helpful feature to have.
 -Chwy5
...

I'd just make everything appear in whatever  the time zone  a _user_  selects is.

A market shouldn't be like "Bla blah blah at 5:00 PST?" It should  just have  an expiration time which the user enters which is in their own time zone [that they chose in settings],  and if I view that market, the expiration time should show what it is in my time zone. That way people dont have to do a ton of googling for time zones.

"especially if there are multiple contests on the same event, with different time zone expiration times" is something that should *never* happen if this  is designed properly.  
 -joeykrug
...

This time zone should exist in a settings page / account page imo
 -joeykrug

**Comment by joeykrug** [comment]
closing to consolidate into micah's issue
