### ISSUE TITLE
Disputing: Responsive design (Breakpoints)

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5200]
See this figma link for design at all breakpoints: 
https://www.figma.com/file/og1llFtTU9l5F2hk5tKMxc/Responsive-Layouts?node-id=0%3A1

Scroll left to right to see mobile up to x-large desktop. 

**Note for dev:** Arrange call with Matt to chat through this ticket. 

- [ ] Check that the build matches the breakpoints and layout at breakpoints in figma

**Comment by matt-bullock** [comment]
This isn't working as it needs to use the tablet breakpoint design here.

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/12e0693c-e5b9-4ac5-96dd-a7ccef781b6d)

This is the design for tablet sizes:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f22f80bf-c976-4b9d-a672-dbf6d8d69ffe)

**Comment by phoebemirman** [comment]
i don't think we can get to that too easily because that is a shared component and i don't want it to not follow the patterns set for it

**Comment by phoebemirman** [comment]
plan is to: make tables 2/3 and side components 1/3. switch checkbox font to mono semi bold 10 and tighten margin between check and words.

**Comment by matt-bullock** [comment]
This  looks to be working a lot better. Only issues I can see is the check box for showing only markets in the users portfolio moves over to the left at a smaller break point. It should stick to the right
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/dfcb06bf-a953-499b-a65e-b3e7e94d6b26)

Also the checkbox should be centred and closer to the text (Only markets in my portfolio). 8px space rather than 16px

**Comment by matt-bullock** [comment]
Still breaking at smaller size before mobile.

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/d1812c8b-42d0-493a-b8bb-9fb43ba8f4ed)

keep Only market in my portfolio right aligned if it goes onto 2 lines


Tab underline is breaking away
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/969351fc-f70b-4400-99be-abd0f2da8eaa)

Change quick guide button to say: Need Help? Disputing Quick Guide
That way it should fit

**Comment by matt-bullock** [comment]
Those other issues appear fixed now but can the only markets in my portfolio stay to the right? Currently it looks like this on the build: ![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/19a56c56-5ac8-4df9-b270-904e424de1f5)
