### ISSUE TITLE
App/Nav: Desktop - logged out 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5201]
- [x] Add the help menu when logged out **HIGH**
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=9597%3A277770
- [x] Fix the spacing in the nav bar, it should be an even 12px above and below the nav links **HIGH** 
- [x] When hovering on links in the nav bar, the text is the only area that allows me to click, increase the size of the click area **HIGH** 

Comparison: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/c7bfdc52-ee15-49e5-8602-2fda5f42a783)

Nav screenshot from build, it's not 12px above and below:
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/edcc1130-ff6d-48e4-b7a2-c7796751d5e7)

**Comment by JohnDanz** [comment]
Design actually has 11 px above and below text and v2 matches design exactly right now for the nav.
