### ISSUE TITLE
App/Nav: Desktop - logged in 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5202]
Figma: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=635%3A30189

Left side:
- [ ] Match the test styles used in figma **HIGH**
- [ ] Match the alignment and spacing used in figma **HIGH**

Right side: 
- [ ] Change the 'help' and 'bell' icons to match figma (24px icons with color D7DDE0) **HIGH**
- [ ] Move the account menu to the right side, so the order is 'help', 'alerts' & 'account' **HIGH** 
- [ ] When the alerts menu has the red count, match the spacing to figma (currently it has a lot of room around the number in the build + match the text style of the number **HIGH** 
- [ ] Add the 'add funds' button **HIGH** (Note: this will be removed at tablet breakpoint)
- [ ] Match the test styles used in figma **HIGH**

Comparison: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/14c003eb-67f7-4ea7-964c-76e25b3f1ef1)

Nav bar: 
- [ ] Match the create market button styling to figma button 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/8985e64a-83d6-41fe-a902-25a18eaae056)

**Comment by Chwy5** [comment]
closing
