### ISSUE TITLE
App/Nav: Desktop - help menu 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5203]
Figma: 
https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=718%3A30

The links in the help menu have changed for some reason. 

- [ ] Change the links in the help menu back to the text only links (see screenshot) **HIGH**
- [ ] Copy update "Make a test trade" -> "Trading tutorial" + move this to the top of the list (this link does not have an icon) **HIGH**

Comparison: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/d9be6ece-164c-45da-af94-a4f8e62870ad)

**Comment by matt-bullock** [comment]
looks done. closing
