### ISSUE TITLE
App/Nav: Desktop - account menu 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5204]
Figma: 
https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=455%3A7639

- [ ] Match text styles used in figma **HIGH**
- [ ] Replace the (?) the tooltip icon **Low**
- [ ] For transaction fee row - remove the 'average fee' copy beside label and replace the value below label with the string format on figma **HIGH**
- [ ] Match button component with same as on figma **Low** 
- [ ] Fix the padding to the sides of the avatar / right side of the menu button (should be 16px) **HIGH**

Comparison: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/efc50f46-6fbf-4564-9e09-a1f031b12132)

**Comment by fedakova** [comment]
myslím  je to moc nějaké problemi  vznikají  v účtu

**Comment by pgebheim** [comment]
Desktop looks good
