### ISSUE TITLE
App/Nav: Transaction fee modal 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5205]
Figma: 
https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=1232%3A144048

- [ ] Match text styles to figma **LOW** 
- [ ] Centre the modal heading **LOW** 
- [ ] Add tooltip beside gwei when advanced is open **LOW** 
- [ ] Centre the buttons **LOW** 

Comparison: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/fb20fe8d-7378-47af-9868-2d56ed5df6a0)

**Comment by joeykrug** [comment]
meh
