### ISSUE TITLE
App/Nav: Mobile - logged out 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5206]
App bar: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=11719%3A90
- [x] Add in the help menu button **HIGH**

Comparison: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/8ea0b251-09c8-41f9-834a-3766943a4536)

Hamburger menu: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=12854%3A300448

- [ ] Update color of top row of the hamburger menu to match figma **HIGH**
- [ ] Add in the help button and login/signup buttons to the top row **HIGH**
- [ ] Add in logo with divider line below **Medium**
- [ ] Match the colour of the bottom row with the global chat button to figma **LOW** 

Comparison: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/ee079d00-8c60-43ae-92f9-3585404879b7)

**Comment by Chwy5** [comment]
moving to post launch for remainder
