### ISSUE TITLE
App/Nav: Mobile - logged in -See Chwy's comments below

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5207]
App bar: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=425%3A51

- [ ] Match text styles to figma **HIGH**
- [ ] Match text spacing to figma **HIGH**
- [ ] Change the bell icon and color (same as desktop ticket)

Comparison: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/f1c17160-81fc-4306-8daa-fb90893324c0)

Hamburger menu logged in: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=12854%3A298319

- [ ] Update top row background color to match figma (same as logged out ticket) **HIGH**
- [ ] Replace the 'X' icon with the one used in figma + match color **HIGH**
- [ ] Update the (?) help icon to match figma **HIGH**
- [ ] Update text styles to match figma **Medium** 
- [ ] Add in logo and divider line below **HIGH**
- [ ] Add in the 'add funds' button **HIGH** 
- [ ] Match the color of the inactive navigation link to figma **HIGH** 
- [ ] Add in the create market button and divider line above **Low** if non trivial change the text from 'create' to 'create market'
- [ ] Match 'logout' text + icon style and color with figma **Low** 
- [ ] Match 'global chat' button component with figma **Low**  

Comparison
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/219f9407-aa29-49a0-834b-12b9b328173f)

**Comment by Chwy5** [comment]
All I need done from this ticket for Launch is:
1) Add in Funds Button
2) Make font color match so the choices are easier to read
3) Add In create Market button

**Comment by matt-bullock** [comment]
The add funds button should be green. looks like an old mock in the ticket above.

https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=2138%3A8445

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/1b007dbf-4d9c-4363-bd1b-b9462ffe1e5c)

For some reason the create market button was changed to a text button style. This wasn't a design request but it actually works fine now we have the add funds button and I suspect this was done to create space. If we do this on desktop we should carry through to mobile

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/95461473-765b-4718-b712-65491377a2a4)

**Comment by Chwy5** [comment]
Please make add funds button green

**Comment by Chwy5** [comment]
closing
