### ISSUE TITLE
App/Nav: Mobile - account menu 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5208]
Figma: 
https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=1819%3A1348

- [x] Update background color of the menu that appears to one color 1B1A1E - this will also be the background color of the menu button above **HIGH** 
- [x] Match text styles to figma **HIGH**
- [x] Update the transaction fee row to a simple string (remove the 'average...' copy beside the label)  (same as desktop ticket) **HIGH** 
- [x] Update buttons and button icons to match figma **Low** 

Comparison:
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/a29756af-4a4d-4e34-8157-d403b57bf6f5)

**Comment by rubyweb3** [comment]
The current implementation is

![Screen Shot 2020-02-06 at 4 39 19 PM](https://user-images.githubusercontent.com/58647954/73919830-446bd780-48ff-11ea-9272-1d8ab698afda.png)

@Chwy5 
Should we update the header to the design?

**Comment by Chwy5** [comment]
it needs to match what matt has in the design at the top

**Comment by cillianhunter0** [comment]
Issues: 

- [x] When I open the hamburger menu, the account menu inactive state should have the same background color as the darker gray on the left 
- [x] When I expand the account menu the background color should be: 1B1A1E
   - [x] This is different from the background color of the rest of the hamburger menu, e.g. behind the navigation links the color should be: 222124
- [x] The tooltips should be positioned 4px from the labels 
- [x] The add funds button should be larger in terms of width, with 16px padding on the sides

See design vs build:
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/166657cb-aaa2-4b7a-a61a-b1594bb0dbb0)

**Comment by bthaile** [comment]
@Chwy5  I think this ticket is done for launch.

**Comment by Chwy5** [comment]
I am unable to get mobile to load to test

**Comment by rubyweb3** [comment]
> Issues:
> 
> * [x]  When I open the hamburger menu, the account menu inactive state should have the same background color as the darker gray on the left
> * [x]  When I expand the account menu the background color should be: 1B1A1E
>   
>   * [x]  This is different from the background color of the rest of the hamburger menu, e.g. behind the navigation links the color should be: 222124
> * [x]  The tooltips should be positioned 4px from the labels
> * [x]  The add funds button should be larger in terms of width, with 16px padding on the sides
> 
> See design vs build:
> ![image.png](https://camo.githubusercontent.com/cfb5ef4f909159521d5ec00df652353a68354d48/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563373539316437656563313537343566666165393962312f31363636353763622d616161322d346237612d613631612d623135393462623064626230)

updated

**Comment by Chwy5** [comment]
Why are there 2 add funds buttons? ! in green and 1 in black....seems weird....Can come back to post launch and fix

**Comment by cillianhunter0** [comment]
Yeah it is a bit strange, it was initially a blue button that you see in the account dropdown, then we added the green button to the nav bar on desktop, on mobile that sits in the slide out menu.  

Agree we should improve that, either all green buttons or remove the extra button.
