### ISSUE TITLE
pending label not showing up for initial liquidity

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#5209]
similar design 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign

**Comment by Chwy5** [comment]
@phoebemirman what is this? when I go to figma I dont see anything so not sure what the fix is, that I am looking for

**Comment by phoebemirman** [comment]
just the pending label on initial liquidity orders was not showing up previousy
