### ISSUE TITLE
Market creator fee not initially visible when on creation pg

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#521]
A user must scroll up to find the Market creator fee box (while on the liquidity prevision pg)...not all users will know to do that when creating a market.

Fonts size should be made smaller to fit everything on one pg.
...

When going through the market creation process....once getting to the liquidity provision page.....a user can NOT see the Market creator fee box (without scrolling up) - new  users will not  know to do this.
 -Chwy5

**Comment by joeykrug** [comment]
fixed in sneakpeek
