### ISSUE TITLE
Move reported on items to the end

### ISSUE THREAD

**Issue by DanielCarlyleEvans** [AugurProject/augur#521]
Each time you report on a market, the screen reloads and you have to scroll down to find the next item needing to be reported on.  With a long list like we have now, this is laborious.  I have been working on the reporting for a few hours now and I find myself getting tired and clicking on items I have already answered.  Really should just move from one to the next as you report without needing to rescroll each time.

**Comment by joeykrug** [comment]
agree, duplicate issue but plan to implement this feature :)
