### ISSUE TITLE
App/Nav: Mobile - help menu 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5210]
Figma: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=12854%3A298479

- [ ] This menu should replicate the behaviour of the account menu, pushing down the navigation links
- [ ] Match the styling of the help menu to match figma
- [ ] Update the links so they match figma and see the desktop ticket for notes on copy changes 

Comparison: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/d07e664b-2b0c-4d31-9365-85a58dbf5837)

**Comment by matt-bullock** [comment]
help menu looks done. closing
