### ISSUE TITLE
overflowing open orders table does not line up when scroll bar isn't visible

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#5214]
<img width="1049" alt="Screen Shot 2019-12-12 at 9 38 51 AM" src="https://user-images.githubusercontent.com/6775839/70735506-3d3f9900-1cc3-11ea-9104-f5505472ac4c.png">

**Comment by andrewdamelio** [comment]
@Chwy5 i think removing cancel text has fixed this issue.
![image](https://user-images.githubusercontent.com/1683736/76460019-abbff000-63b3-11ea-8ca0-f94cb1eef368.png)

**Comment by Chwy5** [comment]
closing
