### ISSUE TITLE
Input validation regex too loose

### ISSUE THREAD

**Issue by epheph** [AugurProject/augur#5223]
```
export const ValidationTemplateInputType = {
  [TemplateInputType.TEXT]: `(.*)`,
  [ValidationType.WHOLE_NUMBER]: `[0-9]*`,
  [ValidationType.NUMBER]: `[0-9]+\.*[0-9]*`,
  [TemplateInputType.USER_DESCRIPTION_OUTCOME]: `(.*)`,
  [TemplateInputType.SUBSTITUTE_USER_OUTCOME]: `[0-9]*`,
  [TemplateInputType.DATETIME]: `(January|February|March|April|May|June|July|August|September|October|November|December) ([0-9]){2}, 20|([0-9]{2}) \d\d:\d\d (AM|PM) \\(UTC 0\\)`,
  [TemplateInputType.DATEYEAR]: `(January|February|March|April|May|June|July|August|September|October|November|December) ([0-9]){2}, 20|([0-9]{2})`,
};
```

These regex's are too loose. I was able to create a bunch fo markets that showed up as "Augur Templates", with strange values that get inserted. Here's some below

![Screen Shot 2019-12-12 at 4 04 17 PM](https://user-images.githubusercontent.com/361654/70758874-32076000-1cf9-11ea-87fb-4cf79e8c41ef.png)

It seems the regex's aren't always working correctly?  How did `4..1a` get through? Regardless of that, I think these would be better values:

```
  [ValidationType.NUMBER]: `[0-9]+(\.[0-9]+)?`,
  [TemplateInputType.SUBSTITUTE_USER_OUTCOME]: `[0-9]+`,

```

**Comment by MicahZoltu** [comment]
`TemplateInputType.TEXT` is going to be particularly problematic.  Anywhere there is an opportunity for free form text the user can put in additional market conditions.  For example, `LPGA: Will [0] make the cut at the [1] [2]?` would match:
> LPGA: Will Dwayne Johnson die and Tiger Woods make the cut at the 2020 Kia Classic?

I bumped the priority on this issue up since there is a whole swath of scam vectors available with free form text input.

**Comment by MicahZoltu** [comment]
Same general problem for `TemplateInputType.USER_DESCRIPTION_OUTCOME`.

**Comment by MicahZoltu** [comment]
@bthaile Reading the PR description on #5338 it doesn't appear to address the issues brought up in this issue.  Did you mean to close this when that was merged (perhaps there are more fixes in the PR that weren't in the PR description), or was the idea just that that PR worked on addressing this issue, but wasn't meant as a complete solution (and so this shouldn't be closed)?

**Comment by bthaile** [comment]
Yes, meant to close this ticket:

Addressed the issue where multiple periods are allowed in numbers, also addresses the issue where multiple picklist values were allowed. 

Did not address any free-hand text issues. 
Which were not pointed out in the original ticket description.
