### ISSUE TITLE
MC: category - validation state missing 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5229]
If I enter a custom category as my primary category and _don't_ enter a secondary category (which is a required field), then click next, the main validation message appears telling me i need to complete all fields, but the secondary category input is not showing in it's error state. 

It looks like this: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/dc9fe1f8-f766-4477-a7bd-04ad26bc3977)

It should be displayed as: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/2c2fa337-754e-462e-aa75-f9c2eafa3704)

**Comment by Chwy5** [comment]
this shows now - closing
