### ISSUE TITLE
MC: No max character count set on outcome input

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5230]
User can enter as many characters as they want into the field, we can apply a max character count of 32 to that input so we avoid the need to display this validation error: 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/5bbb1587-520b-4353-ba0b-9a43e8f9d478)

**Comment by jfarid27** [comment]
@bthaile Could this be closed as a wontfix then? I actually don't think it's a huge bug.

**Comment by joeykrug** [comment]
Sounds like we should either close this or merge #5398 or both
