### ISSUE TITLE
Migrate REP button and tooltip 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5234]
Desktop: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=12885%3A588
- [ ] Change the button type (blue button is too big for the new nav bar) **HIGH**
- [ ] Switch out the tooltip icon (new icon being used everywhere) **LOW**

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/0bdab0f1-8fa0-43ae-9533-4078b8a88566)

Mobile: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=12888%3A934
- [ ] Change the button type (blue button is too big for the new nav bar) **HIGH**
- [ ] Add the tooltip **HIGH**

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/fce5cf7c-0949-4660-9e38-13780e918d1f)

**Comment by jfarid27** [comment]
So I pushed up #5411, but I would recommend punting on adding the new styling for the tooltips icons. It's definitely not a priority.

**Comment by joeykrug** [comment]
tooltip in build looks better anyway imo

**Comment by cillianhunter0** [comment]
Closing as not priority.
