### ISSUE TITLE
Migrate REP modal 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5237]
Desktop: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=12884%3A109

Mobile: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=12888%3A2312

For both desktop and mobile: 
- [x] Update the description copy "Migrate your V1 REP to V2 REP to use it in Augur V2. The quantity of V1 REP shown below will migrate to an equal amount of V2 REP. For example 100 V1 REP will migrate to 100 V2 REP." **HIGH**
- [x] Update the learn more button, it should just be text and icon **Low - but do it if quick!**
- [x] Remove the 'V2 REP balance' box **HIGH**
- [x] Centre the 'v1 rep' box **HIGH**
- [x] Update the copy in the 'v1 rep' box -> "V1 REP to migrate" **HIGH**
- [x] Update transaction fee color **HIGH**
- [x] Centre the transaction info message below and update the copy **Low - but do if quick!" 
- [x] Update the 'convert' button copy to 'migrate' **HIGH**
- [x] Check that text styles and colors match figma **Low - but do if quick!" 

Desktop
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/42379466-f397-4603-b45e-fa376fff1804)

Mobile
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/2dd1766d-429c-4f3b-9852-3a63354a843d)

**Comment by Chwy5** [comment]
modals look correct and updated - closing
