### ISSUE TITLE
No alerts confirming REP migration  

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5238]
There's currently no confirmation alert when the REP is migrated to V2. Nothing happens...

Ran it by @Chwy5  show same spinner proposed for notifications when transaction is being processed. 

![image](https://user-images.githubusercontent.com/3970376/75048037-806d7380-548d-11ea-8c5d-44f0952aedd8.png)

show spinning icon when migration transaction is being processed.

**Comment by matt-bullock** [comment]
Shows up in the bell dropdown but not as a toast. Is toast required?

**Comment by cillianhunter0** [comment]
I'm not seeing this in the bell dropdown. 

We should also enable the toast for this, it's an important transaction, we should make the confirmation state as visible as possible.

The button state should also update using the new transaction feedback pattern (processing, confirmed etc)

**Comment by matt-bullock** [comment]
toast and bell now there
