### ISSUE TITLE
UI forces you to report on everything atm [even though some will get rejected b/c you weren't selected to report on them

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#524]
Also, reporters are selected to report on ~2x what they actually have to, UI should let reporter know how many things they have report on at a min [getNumEventsToReport(branch, votePeriod)]

To see whether a user has to report on event x:
```y = array(1)```

	y[0] = tx.origin + eventID

	shaHash = sha3(y, items=1)/2**64

If `shaHash < calculateReportingThreshold(branch, x, votePeriod)` then that event is one a user can report on.

So show user all the events that meet that ^ --- then they only have to report on getNumEventsToReport(branch, votePeriod) (but can do more if they like)

**Comment by tinybike** [comment]
Added in ef0ec5b1963dc7d55484307643a8679c6e14fffa.
