### ISSUE TITLE
Report reveal data migration

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#525]
Should be a way to migrate this across browsers [maybe dropbox]

**Comment by joeykrug** [comment]
see #557

**Comment by tinybike** [comment]
Probably needs to be part of the Airbitz integration.

**Comment by joeykrug** [comment]
There needs to be a way to do it without airbitz.  Community cache nodes and just allowing people to import their data into another browser are two ways as well

**Comment by joeykrug** [comment]
This is definitely not a bell.  If I cannot do this augur isn't worth launching yet.  We're dealing with money here, people should be able to do things as basic as this

**Comment by tinybike** [comment]
> Community cache nodes and just allowing people to import their data into another browser are two ways as well, the former isn't too difficult.

IMO reports should be handled the same way as accounts: there should be a browser import/export option, and Airbitz integration if you don't want the hassle of moving files around locally / between browsers.

I don't think cache nodes are a good way of handling reports for three reasons.  One, it's an extra burden on people running the nodes (of potentially unboundedly large size, depending on the number of reports they're asked to store).  Two, unless cache nodes have perfect replication for non-blockchain data, you're relying on the same cache nodes being available when you write and read your reports.  Third, the cache nodes don't exist yet; IMO it's better not to plan features around them until they do.

Agree that this isn't a "Bells" feature though.  Moving to "MVP" for the browser import/export, which should be very straightforward and use the same logic as account import/export; Airbitz integration should be part of the Launch milestone.

**Comment by joeykrug** [comment]
1) No it's not [I can provide a proof if you like]
2) If they used the IPFS persistence lib they would
3) Yes they do
4) It doesn't exist on airbitz yet either

**Comment by tinybike** [comment]
1) Sure, please do.  Isn't the size of the reports unbounded, since the number of events is unbounded?
2) Cache nodes should not have IPFS as a dependency; we've rejected solutions that require IPFS installations previously and I think that was the correct decision.
3) How can cache nodes exist already, when Kevin is not done coding them?
4) As I understand it, there's no question that Airbitz can be used to do this.  With cache nodes this is not clear (to me at least; see 1-3).

**Comment by joeykrug** [comment]
3) Try using one!  You can already get the getmarketsinfo data from them which is the first thing they're supposed to be used for.  You cannot add features to a computer program without coding them naturally :P

**Comment by joeykrug** [comment]
1. [512 bits per report * 30 reports/event given a high appeal rate * 10000 events/2 months = 19MB at any given time, instantly prunable every 2 months]
4. There's no question that Airbitz cannot be used to do this

**Comment by joeykrug** [comment]
Additionally you'll kill adoption by forcing $12/yr on users to have a usable app that doesn't suck

**Comment by tinybike** [comment]
Why 10000 events every two months?  Why not a million events?

Re: Airbitz, per my conversation with Paul, Edge Security's intended use is storing data precisely like this.  What's your reason for thinking this isn't possible?

**Comment by joeykrug** [comment]
"Additional Clauses

16. The Provider will not provide block­chain functionality, will not secure arbitrary user

data, and will not provide access to encrypted user data without proper authentication."

**Comment by tinybike** [comment]
Yes, it clearly would not be covered by our existing contract with them.  But they do have the capability to do this, and they've indicated an interest in doing so.

Moving this conversation offline.

**Comment by joeykrug** [comment]
> Why 10000 events every two months? Why not a million events?

Premature optimization?  I've heard you mention it, there's _no way_ the UI can handle a million events, cross that bridge when we get there because we'll have so many tx fees + resources it'll be easy?

**Comment by tinybike** [comment]
Moved on-contract.
