### ISSUE TITLE
Use strict type checking.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#5251]
Type checking for the various augur packages currently is set to be quite loose, including `strict: false`, `strictNullChecks: false`, and `noImplicitAny: false`.  This means that the project is currently configured to ignore compile time errors that would alert you of problems before releasing into production.  For a project that has a high level of security needed, running with the most strict type checking is recommended to minimize the chances of introducing obscure JS bugs that could lead to various attacks against the UI.

**Comment by pgebheim** [comment]
Thanks for the suggestion -- right now this is just a practical consideration that we can revisit during a refactor phase.
