### ISSUE TITLE
Use seconds since unix epoch or ISO8601 date/time stamps in templates.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#5254]
The current regex for template dates is:
```
(January|February|March|April|May|June|July|August|September|October|November|December) ([0-9]){2}, 20|([0-9]{2})
```
The problem with this is that one can create invalid dates like January 42nd.  Similarly with the timestamp entry one can create timestamps like 70:70 AM
```
(January|February|March|April|May|June|July|August|September|October|November|December) ([0-9]){2}, 20|([0-9]{2}) \d\d:\d\d (AM|PM) \\(UTC 0\\)
```

Rather than trying to manually create a regex that can detect and match dates correctly, instead store the dates in the template in a standardized format like ISO8601 or seconds since unix epoch and then humanize that timestamp at render time if desired.  This will allow you to use standardized tooling for validation of the timestamp (in the case of ISO8601) rather than attempting to roll your own time validation (which is a _really hard problem_).

**Comment by pgebheim** [comment]
I'm generally a fan of using ISO8601 -- since as you mentioned times are *really hard* to get right.

@bthaile -- thoughts on this?

**Comment by MicahZoltu** [comment]
Thinking more on this, I think seconds since epoch would be ideal, and then teach the UI how to render this (can even be localized).  Maybe put it into some structured block so non-template markets can also get the same effect?

```
Will X happen before {unixtime:1578292394}?
```

**Comment by pgebheim** [comment]
That's an interesting idea. Currently only templated markets can get the benefits of the localization. And since that's happening anyway just putting the unix timestamp in the official description is really not such a problem from a display perspective.

**Comment by bthaile** [comment]
Thanks, already addressed the regex in templates-template.ts file in augur-tools

**Comment by bthaile** [comment]
```
export const ValidationTemplateInputType = {
  [TemplateInputType.TEXT]: `(.*)`,
  [ValidationType.WHOLE_NUMBER]: `[0-9]+`,
  [ValidationType.NUMBER]: `[0-9]+(\\\.[0-9]+){0,1}`,
  [TemplateInputType.USER_DESCRIPTION_OUTCOME]: `(.*)`,
  [TemplateInputType.SUBSTITUTE_USER_OUTCOME]: `[0-9]+`,
  [TemplateInputType.DATETIME]: `(January|February|March|April|May|June|July|August|September|October|November|December){1} ([1-9]|[1-2][0-9]|3[0-1]), 20[0-9]{2} \d\d:\d\d (AM|PM) \\(UTC 0\\)`,
  [TemplateInputType.DATEYEAR]: `(January|February|March|April|May|June|July|August|September|October|November|December){1} ([1-9]|[1-2][0-9]|3[0-1]), 20[0-9]{2}`,
  [TemplateInputType.DATESTART]: `(January|February|March|April|May|June|July|August|September|October|November|December){1} ([1-9]|[1-2][0-9]|3[0-1]), 20[0-9]{2}`,
};
```

more strict date time and number regex

**Comment by MicahZoltu** [comment]
This still leaves February 31st, 2000, 67:89 AM.  I don't believe it is actually possible to construct a regex that ensures the timestamps are valid, which is why I think an inline unix timestamp that is resolved by the UI is a better solution.

Reopening this since the underlying issue is still not resolved, if the intent is to make this as "Won't Fix" feel free to re-close it as such.

**Comment by pgebheim** [comment]
Won't fix -- these selections create a clearly invalid market.
