### ISSUE TITLE
Order tickets act very weird

### ISSUE THREAD

**Issue by tyche78** [AugurProject/augur#526]
1- http://nimb.ws/KVx3JZ (weird amount of cash/share + erroneous order cost calculation)
2- http://nimb.ws/7qswgo (buying 1 share of donald trump is not supposed to have such a huge impact, is it?)

**Comment by hyperanthropos** [comment]
see this discussion on reddit regarding point 2:
https://www.reddit.com/r/Augur/comments/4924wo/something_is_wrong_with_the_way_shareprices_and/

**Comment by tinybike** [comment]
Can you paste the original images here?  Neither is available any longer.  Re: point 2, hopefully this was clarified in the Reddit discussion.  We're moving to an order book system anyway, so this will be a moot point shortly.
