### ISSUE TITLE
0x protocol fee.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#5260]
https://github.com/AugurProject/augur/blob/b380634f04fcf5fa18e3ae3f7739c70f1dc41026/packages/augur-core/source/contracts/trading/ZeroXTrade.sol#L215

Currently the protocol fee is hard coded in the contracts.  This means that if the fee rate changes, then Augur will stop working with 0x.

However, if a change is made to blindly fetch the fee at runtime and forward the whole thing, then the 0x Exchange owner has the opportunity to exit scam by jacking the fee way up and seeing how many users confirm the transaction without checking the fee amount (my guess is most users will fall to this scam until word gets out).

I'm not sure how to address this in a way that both protects Augur users from malicious fee changes while also allowing non-malicious fee changes through.  Best option I can think of is to ensure that the UI makes it _incredibly_ prominent how much of a fee is being charged by 0x, and to protect Augur's reputation make it clear that this portion of the fee is a 0x fee, not an Augur fee.

**Comment by MicahZoltu** [comment]
Another option would be to have the UI accept any fee changes within a range, but require a UI update to go beyond that.

**Comment by epheph** [comment]
And pass the protocol fee in as an argument in the calldata?

**Comment by MicahZoltu** [comment]
Yeah, I believe it is already part of the order.
