### ISSUE TITLE
Golf Template fix

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#5261]
WE need to remove Presidents Cup from multiple Choice dropdown for:

Which Player will win {event}

Need To add New Golf Multiple Choice Template:

Which Team will win the Presidents Cup

Outcomes are:

1) United States
2) International
3) No Winner/Event Cancelled

Added Resolution Rules:

If tournament or Match is cancelled or postponed and will not be completed before the market's Event Expiration time, the market should resolve as "No Winner/Event Cancelled".

Includes regulation, any play-offs and sudden death

**Comment by bthaile** [comment]
what about other team golf tournaments like Ryder cup?

**Comment by Chwy5** [comment]
Going to do this for the Presidents Cup and Ryder Cup only
