### ISSUE TITLE
Minimum Trade Size for 0x Orders

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#5274]
- Make a minimum trade chunk size of 10 shares for both fills and makes (helps with spam and gas cost issues), then if there’s someone who wants to buy 20 shares, that's fine b/c it's a multiple of 10, vs 25 isn't allowed. On chain this will be enforced, off chain we'll also need to enforce that orders we display are multiples of 10 shares.
- Sort the order books by size priority because larger orders are cheaper to trade

- [x] On Chain Support
- [x] Off Chain Support

**Comment by epheph** [comment]
Although, if that's enforced everywhere, why not just make 1 share more valuable and then have minimum divisible be 1?
