### ISSUE TITLE
ZeroXTrade.doTrade should return actual amount traded.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#5275]
https://github.com/AugurProject/augur/blob/057c31ddf1124acdcb200ed6ce425834fd86238c/packages/augur-core/source/contracts/trading/ZeroXTrade.sol#L255-L269

This function is expected to return the amount of the asset that was traded, but instead it returns the amount of the asset that was _requested_ to be traded.  At a glance I wasn't able to spot an immediate vulnerability from this (@epheph may have better luck) since `exchange.fillOrder(...)` _should_ make it so `_amount` is always exactly equal to the amount traded.  However, from a code health standpoint the current code is very dangerous since there is an implicit assumption in this function that the caller has already established that `_amout` is guaranteed to be exactly equal to the final amount traded.

Recommendation: Return the result of `fillOrder.fillZeroXOrder`, which does contain the amount actually traded.

**Comment by nuevoalex** [comment]
Added this to https://github.com/AugurProject/augur/pull/5272
