### ISSUE TITLE
Penalization catchup issue

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#528]
Everyone in the beta has 46.x rep now [those who had accounts from the beginning].

If there's nothing to report on in a period [and thus the user didn't report] the UI is just calling the penalization catchup function.  It should be calling the proper / normal penalization functions as if the user reported normally.  [penalize not enough, penalize wrong w/ branch 0 as params, collect fees in second half of period].  This will ensure the user doesn't lose rep in a period they didn't report in with 0 events.

**Comment by DanielCarlyleEvans** [comment]
Shouldn't that REP go somewhere too?  If nobody's REP went up that is like the destruction of REP, which I didn't think would happen.  I thought it should be redistributed.

**Comment by joeykrug** [comment]
Yes it's supposed to be redistributed.  It looks like the UI isn't calling the functions above which means it won't get redistributed, it'll just sit there until the UI does call those functions.  Since it didn't call them due to this bug, we have to wait until the end of next period before it'll get redistributed.

**Comment by joeykrug** [comment]
dup. of #574
