### ISSUE TITLE
Order ticket quantity changes - force multiples of 10

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5282]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/48b57ae9-e45c-481a-86a3-fed4e5dedb4c)

Design: https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=2733%3A146

Until Matic is introduced we need to force users to trade in multiples of 10.

- [ ] Add copy '(Must be a multiple of 10)' above quantity input - right aligned
- [ ] Quantity input needs to change in increments of 10 when using the up and down arrows
- [ ] If user clicks the buy/sell button and quantity is not a multiple of 10, error message is displayed reading 'Quantity must be a multiple of 10'. And quantity input is displayed in its error state

**Comment by Chwy5** [comment]
done - closing
