### ISSUE TITLE
Went to reports page to submit reports, got a ton of failures in console then all ui buttons stopped working

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#529]
Extension is actually .log - from opera console
[augur.net-1458760153486.txt](https://github.com/AugurProject/augur/files/186687/augur.net-1458760153486.txt)

**Comment by joeykrug** [comment]
Tried exiting / reloading in browser, and it seemed to correct

**Comment by tinybike** [comment]
Should be fixed by 59f966ae8b6d24f221fec1ec166e75a53216429e; re-open if this happens again...
