### ISSUE TITLE
scrollbar styling issues 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5293]
Yanel on a mac running chrome gets this:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f2abf184-0f9a-4307-a14e-6fee216c30ba)

I get a lighter scrollbar on categories as opposed to the scrollbar far right:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/4078a04e-f9a2-4289-9ed3-b567cd81b7c7)

They should ideally be the dark style like the scrollbar on the far right of the page

**Comment by pgebheim** [comment]
Not certain if this is still an issue, removing from epic so it can be closed, scheduling w/ proper labels.
