### ISSUE TITLE
Submitting unsigned orders is not working 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5294]
When I click 'submit all' it triggers my MM to sign for the transaction but nothing happens. The modal just remains as is. 

Note: after digging on this some more, it appears they have been submitted but there's a problem with the modal, it's still available with the same orders that have appeared on that markets order book already. So it's two problems: 
1. When you click submit all, it should close the modal and bring you to that market so you can see the orders processing
2. When they process it should remove the notification 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/3e53d7a3-a6e3-4804-b13b-5567b175c63e)

**Comment by Chwy5** [comment]
fixed
