### ISSUE TITLE
Add Scalar tag to scalar market cards

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5297]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/a01e5bbc-4b1d-47b1-a9ee-d3a082035430)

Add to all scalar card types (classic, condensed and expanded) in all market states (open, in-reporting, resolved)

Design: https://www.figma.com/file/Do4qnkCNM8P7lwBmCdYZCS4X/Market-Cards?node-id=1907%3A131086

**Comment by JohnDanz** [comment]
@matt-bullock When you are back from the holiday break we need to have a meeting to go over what the market cards. I'm seeing some inconsistencies in the mocks vs what we currently have but they are significant enough that I want to make sure im moving things around right before I do it and then its not what we actually want.
