### ISSUE TITLE
Markets  listing  improvements

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#530]
- value at stake on the markets listing per  market
- show best bid  / ask for whatever the current highest priced outcome is
...

@joeykrug Can you elaborate on what you mean for the first item here?
 -adrake33
...

You know how it says Volume: blah ETH? on the markets listings page?

Make another thing that says Open Interest [or Value at Stake]: blahh ETH
 -joeykrug
...

@joeykrug Ok, thanks for clarifying. Makes more sense now.
 -adrake33

**Comment by joeykrug** [comment]
done
