### ISSUE TITLE
App loading screen 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5306]
Note: don't put any new brand material live until launch day. If implementing this loading state for v2.augur or demo.augur just remove brand for now. 

Desktop: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=13096%3A1

Mobile: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=13096%3A16

**Comment by Chwy5** [comment]
Desktop version Looks broken

**Comment by pgebheim** [comment]
Closing as dup for #7052
