### ISSUE TITLE
Not enough room for date time

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#5308]
![404D660A-15A6-4B88-A062-0A3E4FF3EF85](https://user-images.githubusercontent.com/3970376/71287249-7912d800-232d-11ea-8a99-9c347d2a9886.jpeg)

Need to be able to see full date time in order form when user sets expiration date. Need to have 0x enabled to see. Can manually set 0x enabled.

**Comment by matt-bullock** [comment]
Looks fixed
