### ISSUE TITLE
Any calls like this in console don't work

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#531]
flux.augur.getNumEventsToReport(1010101, 13)
Object {error: 500, message: "transaction failed", bubble: TypeError: syncRequest is not a function
    at Object.call (https://augur.net/app.js:181178:23)
   …, tx: Object}

**Comment by tinybike** [comment]
Yeah I scrubbily have not added in browser synchronous request support for
etherscan yet.  If you add a callback function it should work.  Just define
a function:

function mycallback(x) { console.log(x); }

then pass mycallback as the last argument to the augur method and it should
print out the result!

**Comment by joeykrug** [comment]
etherscan gone
