### ISSUE TITLE
Confirming Report... (unclickable)

### ISSUE THREAD

**Issue by housemobile** [AugurProject/augur#532]
Under the Reporting Tab, I'm shown a ton of markets and all say Confirming Report.. when I click the button nothing happens.

In the box on the right it says REPORT NOT SUBMITTED

cliffs: have a ton of markets to report, unable to report.

Windows: using both Chrome, and Firefox (imported account)

**Comment by housemobile** [comment]
![reports](https://cloud.githubusercontent.com/assets/17286590/14022102/b4a24ecc-f1b4-11e5-85e7-4b5e8b861464.PNG)

**Comment by DanielCarlyleEvans** [comment]
I believe you have missed the reporting period by "a few seconds" according to the screenshot.  I think the bug is that the "Confirming Report" buttons don't do anything.

**Comment by joeykrug** [comment]
Agree this is an issue --- should not make things that look like buttons but actually aren't

**Comment by tinybike** [comment]
Obsoleted by 59f966ae8b6d24f221fec1ec166e75a53216429e.
