### ISSUE TITLE
The main markets listing page should have total share value outstanding in ETH as one of the things listed [our closest thing to market cap for markets]

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#532]
...

@sprinkle We already display number of shares outstanding, correct?  If share value outstanding is just number of shares outstanding * last trade price, would this be redundant?  (Although, maybe relevant enough that it should be shown anyway...?)

...

That’s correct.

It’s effectively just a user aid so they don’t have to do the math.

...

>  If share value outstanding is just number of shares outstanding * last trade price, would this be redundant? 

Not quite, it'd be shares outstanding * range, not times last trade price.
 -joeykrug

**Comment by joeykrug** [comment]
Done
