### ISSUE TITLE
Malicious 0x order signer can create un-fillable order, displayed in UI

### ISSUE THREAD

**Issue by epheph** [AugurProject/augur#5326]
The AssetData on ZeroXTrade 0x orders is encoded with a bit of vestigial data: an array of tokenValues, which are unused on the Augur-side. The default off-chain encoding value for TokenValues is [1]. However, order creators can set this value to anything them anything they want, without impacting the Augur-side of the order fill.

https://github.com/AugurProject/augur/blob/656707dd708d7cb8d1656a6994ca90cc7117637c/packages/augur-core/source/contracts/trading/ZeroXTrade.sol#L300

This value is still passed along to 0x ERC-1155 AssetProxy, and fake transfer logs are created based on this value. One could create a valid order, but set the tokenValues[0] = 2^256-1. Because this number gets safe multiplied by the "amount" of an order, any amount >1 will explode the SafeMath:

https://github.com/0xProject/0x-monorepo/blob/011ecb8f4bb9f620d0f3dbd14126de703c6c4754/contracts/asset-proxy/contracts/src/ERC1155Proxy.sol#L74

Someone could create really juicy orders in the UI, with an encoded "tokenValues" of a huge number, and the UI (and contracts) won't filter it, but when the taker brings it to the chain, the tx will revert inside the 1155 Proxy contract (unless they take just 1 amount)

https://etherscan.io/address/0x7eefbd48fd63d441ec7435d024ec7c5131019add#code

We should either enforce this value to be exactly [1], in both the UI and contracts

There are other bugs, like someone could assign that to an array > 1 in length, and that starts to get fairly awkward (as 0x will think they are filling more than one asset-type, but in reality, only one thing happens on the Augur side)

**Comment by joeykrug** [comment]
did this get fixed?

**Comment by epheph** [comment]
I don't believe so. I'm looking for a line in the UI's validate order that inspects the multi-Asset 0x encoded data, and looks into the ERC-1155 part to ensure that the "value" there is either 1 (no reason it shouldn't be 1) or at very least:
 `value * assetAmount < 2^256`

**Comment by bthaile** [comment]
I’ve not addresses this, can we filter orders out before they get into zeroXOrders collection?

**Comment by joeykrug** [comment]
static parseTradeAssetData(assetData: string): OrderData {
    // Remove the first 10 characters because assetData is prefixed in 0x, and then contains a selector.
    // Drop the selector and add back to 0x prefix so the AbiDecoder will treat it properly as hex.
    const decoded = defaultAbiCoder.decode(erc1155AssetDataAbi, `0x${assetData.slice(10)}`);
    const address = decoded[0] as string;
    const ids = decoded[1] as BigNumber[];
    const values = decoded[2] as BigNumber[];
    const callbackData = decoded[3] as string;

Which value would it be? Looks like it's an array of values

**Comment by nuevoalex** [comment]
There should only be one value of 1 in the `values` array

**Comment by joeykrug** [comment]
added a fix to paul's PR
