### ISSUE TITLE
Scalar Market add ellipse and hover 

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#5330]
In the Order Book and the open orders, my fills, positions section on the trading pg and portfolio pg, for scalar markets we need to display price and quantity in 2 decimals.  But bc these markets might have a slightly smaller precision set, it is possible to have price to require more than 2 decimals:

In this case after the 2 decimals (if there is more) we need to add an ellipse, and if the user hovers (for desktop) or clicks on it for mobile to see the expanded quantity

**Comment by Chwy5** [comment]
All these numbers are really to 4 decimal places...this is where we need to add the ellipse and hover

![4-7ell.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/24c71a83-f64e-4752-b77a-f2e204145e8b)

**Comment by Chwy5** [comment]
This seem to add it to every market....can we have this only when it is greater than 2 decimal places?

Would only need to be seen for scalar markets, when there is greater than 2 decimal places

**Comment by phoebemirman** [comment]
which market are you seeing it on? i'm only seeing it on scalars

**Comment by Chwy5** [comment]
fixed - closing
