### ISSUE TITLE
approveToTrade using gas-inefficient values for allowance

### ISSUE THREAD

**Issue by epheph** [AugurProject/augur#5334]
The function which sets the allowance of Cash(DAI) for Augur, FillOrder, and CreateOrder uses an arbitrary value:

```
  const allowance = createBigNumber(99999999999999999999).times(
    TEN_TO_THE_EIGHTEENTH_POWER
  );
```

The tools and tests do it properly, using 2^256-1:
https://github.com/AugurProject/augur/blob/1e4bc2fb846bc7fc1fcf7da91683313b62e2a3ee/packages/augur-tools/src/libs/contract-api.ts#L59-L70

but the code from the UI does not:

https://github.com/AugurProject/augur/blob/14849e933d84ddc1e99bf27693f51e3d8f61dd57/packages/augur-ui/src/modules/contracts/actions/contractCalls.ts#L666-L677

This will cause an extra SSTORE for every Dai/Cash transferFrom, due to these lines:
```
        if (src != msg.sender && allowance[src][msg.sender] != uint(-1)) {
            require(allowance[src][msg.sender] >= wad, "Dai/insufficient-allowance");
            allowance[src][msg.sender] = sub(allowance[src][msg.sender], wad);
        }
```

**Comment by joeykrug** [comment]
fixed https://github.com/AugurProject/augur/commit/a36ace7fb66f419c5a2fb2a2b41bc004011c6368
