### ISSUE TITLE
Standardize market type names in UI

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#534]
Currently we use "Multiple Choice" and "Numerical Range" in market creation, and "Categorical" and "Scalar" on the Trading page, Market List filters, and Notifications.

We should standardize on something across the interface.
...

We might not need any separation at all between Yes/No and Categorical, since those are all 3 - 8 outcomes.
 -sharkcrayon

**Comment by pgebheim** [comment]
New designs choose consistent naming
