### ISSUE TITLE
Claim stake and fees notification is not disappearing 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5347]
I opened the notification a few days back and tried to claim the fees, nothing seemed to happen. 

A few days later after clearing cache and hard refreshing the notification is still appearing but i can't open it. 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/ccc19fe8-2d84-4d7e-b752-36604e70d2fc)

**Comment by bthaile** [comment]
Note:

I've seen that claiming transactions can fail. We need to figure out why.

**Comment by bthaile** [comment]
I see that claiming was successful and the notification is removed. I think this is good. moving to Product Review

**Comment by cillianhunter0** [comment]
still seeing some issues here: 

- after claiming stake and fees
- it sits in the list (for some reason it moves to the bottom of the list of notifs, creating a separate ticket for this)
- i can't click 'view' again
- it did not disappear 
- i had to leave AS and return to the page to access 'view' button again
- after the third attempt at claiming it disappeared

**Comment by JohnDanz** [comment]
So this does disappear in my testing however, we do need to better handle the disabling of buttons -- ideally not the view button but the claim all/claim buttons if they are pending still.

The plan is to use tom's latest pattern from the PR for pending orders and extend that to claiming proceeds

**Comment by cillianhunter0** [comment]
@JohnDanz do you mean the processing tag for the the individual 'claim' buttons and the processing text with spinner in the 'claim all' button?

**Comment by bthaile** [comment]
notification disappears after claiming in my testing as well.  notification not disappearing after all claims have been made. That is the main issue of this ticket. Anything else create another ticket. @cillianhunter0 

@JohnDanz  any other issues don't work on this ticket.

**Comment by bthaile** [comment]
@cillianhunter0  does the notification disappear after claiming fees and REP? if so close this ticket. If not we need more information on how to reproduce.

**Comment by bthaile** [comment]
@cillianhunter0  
tested again with single market claiming and again with multiple markets and notification gets removed when claiming rep and fees. 

can you test again?

**Comment by matt-bullock** [comment]
Tested this and it disappears
