### ISSUE TITLE
Limit order info for users

### ISSUE THREAD

**Issue by Andrew547** [AugurProject/augur#535]
I tried experimenting with limit orders. I set up some tests but they didn't trigger before my account was disappeared. However, in a real-world situation I probably wouldn't dive in like that unless I knew what to expect. Maybe there could be or should be an explanation of the process added somewhere?

I think something basic and utilitarian would be fine. In testing I was balancing a lot of things by placing multiple limit orders in sizes I knew were too big for the current market to handle. I was totally flying blind and making assumptions.

Here's my thinking on the matter, FWIW:

In the case of multiple limit buy orders, for example, with the identical bid price - say from different users - is it first come first serve? Based on the order of submission? Will there be market depth at some point and will I see existing limit order volume and where in line mine might fall? If the next in line limit order is too large to fill because the size of it moves the market price out of range, is there a partial fill? If so, all things equal, does that limit order keep getting hit when the price falls back to the bid again, and then another partial fill and stop again when the cap is hit, and does this keep happening until the entire order is filled?

**Comment by tinybike** [comment]
Combined with #615.
