### ISSUE TITLE
UI for Market Makers/Liquidity Providers

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#535]
This may just be a matter of making the Liquidity interface of the Create Market form available outside of the create market form.

Or, maybe the main order form should be changed so that multiple orders can be added at once.

Talk to Alex, Jack, Chwy, and do some research on standard interfaces for this.
...

@achapman Just FYI, I've added this ticket to track the need. I'm not sure how highly prioritized it should be compared to all of our other priorities. We'll discuss.
 -sharkcrayon
...

This may just be a matter of making the Liquidity interface of the Create Market form available outside of the create market form. 
 -joeykrug
...

That’s what I’d do ^
 -joeykrug

**Comment by joeykrug** [comment]
Make the Liquidity interface of the Create Market form available outside of the create market form. Let's just do that

**Comment by cillianhunter0** [comment]
Do you imagine this is a feature only available to a market maker, on a market they have already created? @joeykrug

**Comment by joeykrug** [comment]
No it should be available to all users

**Comment by joeykrug** [comment]
for people who want to add a lot of orders

**Comment by cillianhunter0** [comment]
So this is something that would be triggered from the new trading page, will keep this in mind as we look at the liquidity step for market creation. cc: @Chwy5 @matt-bullock

**Comment by joeykrug** [comment]
yeah

**Comment by pgebheim** [comment]
@joeykrug @Chwy5 -- Does this still sit as a priority in the current flow of things?

If so I'll add this to the Liquidity Dev epic to make sure it can be accessed stand-alone on a market, but that may require some design.

**Comment by joeykrug** [comment]
dont think it matters, no other trading UI has this

**Comment by Chwy5** [comment]
I dont believe it is a big priority. Most users will input through the order ticket and imo anyone wanting to add multiple orders at once will do it through bot trading.

Can either close and reconsider later or just punt until later
