### ISSUE TITLE
Funds Withdrawal modal Bug

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#5354]
When going to withdraw funds, the amount box displaying Nan

![1-1.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/6c4ad9d5-f640-4610-affc-0623496b83e9)

**Comment by phoebemirman** [comment]
not seeing this. do you have repro steps?

**Comment by Chwy5** [comment]
closing for now
