### ISSUE TITLE
Some modals are missing from the new design

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#536]
Modals that are currenlty missing:

- initial terms agreement 
- initial trade authorization
...

Modals we still need to have updated mocks for by my look through:
```
Claim Reporting Fees (forked Markets)
Claim Reporting Fees (unforked Markets)
disclaimer
ledger signer
uport signer
trezor signer
networkMismatch
participationTokens buy form
participationTokens review form
market migration form
```
 -JohnDanz

**Comment by joeykrug** [comment]
these are all mentioned in other design issues
