### ISSUE TITLE
Add Summary section

### ISSUE THREAD

**Issue by RonB7139** [AugurProject/augur#536]
show how much fees have been earned for each market with standard market data (volume, charts, etc)

show how much fees earned by market as well as cumm. summary accounting to market creator in "my markets"

consider other locations i.e. "marketing" aspects of displaying total fees earned and payed by system

**Comment by tinybike** [comment]
This section should be a summary of everything, including (at a minimum) total value, net gain/loss, total fees earned, and total fees paid.  As an example, see the top section of the following [mock](http://augur.link/mocks/myreports.svg):

![myreports-bg](https://cloud.githubusercontent.com/assets/2637020/16863621/9354b450-4a09-11e6-8ab0-283253afbc24.png)

**Comment by stephensprinkle** [comment]
Closing this issue per discussion.

We're no longer employing the horizontal summary and will now be displaying contextualized data points in the sub-nav of portfolio.  These changes are built and visible in the AURC branch `204-my-markets`.
