### ISSUE TITLE
Reporting ends soon Notifications and designated reporting on reporting pg do not go away after market is reported on

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#5368]
![1-3r1.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/90f108f0-e09d-4b94-a705-5ccf05ed62bf)

![1-3r2.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/64c3d00a-729d-4932-a01a-c39619ac33f2)

I reported on this market through reporting pg.  The notification I have doesnt go away (needs to)
The "Report" button remains enabled and the countdown timer keeps showing for me on the reporting pg (makes me think I need to report again), should remove timer countdown to the DR after Designated reports and should disable the report button to the dr

**Comment by matt-bullock** [comment]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/28bdc1d1-ef80-4c78-aca2-2d3dee7fa1d1)

See design for processing feedback once a user has reported on a market

Design: https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=630%3A2854

To summarise:
After submitting the report the button is disabled and shows the status 'Processing'. Once confirmed this button changes to 'confirmed!' After a few seconds this market disappears from the DR section
