### ISSUE TITLE
Updates to the Initial reporting notification 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5369]
We need to make a few updates to the reporting notification to improve UX: 
1. Update title copy to "You need to report" 
2. Update button copy to "Report"
3. When user clicks the "report" button, open the reporting modal from the account summary page 
4. Add the countdown timer 

Comparison: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/6e84c57a-08eb-4a99-98da-5015d4e6d560)

**Comment by Chwy5** [comment]
Currently when User hits view it is taking them to the reporting pg (not the modal) should just open the modal up on the acct sum pg

**Comment by matt-bullock** [comment]
Looks good and the report button is opening the reporting form. closing
