### ISSUE TITLE
Update augur.net Getting Started design to show download options

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#537]
People are confused when they are redirected to github to download the app. Instead of doing that, let’s show download options on the getting started page itself. We should delineate between the available operating systems (showing an option for Mac, windows, and Linux) and then put the github link below for advanced users.

This ticket is just for the design. Once the design is created a new ticket should be created for development.

**Comment by joeykrug** [comment]
Already designed and developed by @tomkysar
