### ISSUE TITLE
Notifications on desktop - styling fixes 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5370]
Items below show examples from 3 notifications. These styling updates should be applied to all notifications to improve legibility. 
See examples of styling for all states of desktop notifications here: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=13208%3A739

---

Unsigned orders: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=13208%3A1374
- [x] update 'new' tag styling
- [x] match text styles to figma 
- [x] update button copy to 'view' and match the alignment and spacing 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/f00afbdd-1553-410c-a9be-88628277979b)

Reporting ends soon:  (HIGH Priority Part)
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=13208%3A1836
- [x] 'reporting ends soon for' copy should be the same line as the market, currently show as two lines
- [x] update text colors to match figma (*NB* READ STATE IS TOO DARK) 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/1b9e2264-c42e-4b80-9232-1af6a63cd122)

Dispute: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=13252%3A3
- [x] 'Dispute round [X] for the market:' and 'market_name' AND 'is ending soon' should be on one line, currently split over three lines
- [x] Update color of 'dispute ends' label above the countdown timer to match figma (TOO DARK, can't read) 
- [x] update text colors to match figma (*NB* READ STATE IS TOO DARK) 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/f1d009a8-8a34-4d51-bd01-c6a61d39a2a3)

**Comment by JohnDanz** [comment]
https://github.com/AugurProject/augur/issues/4789 related

**Comment by cillianhunter0** [comment]
Closing this and moving comments to 4789
