### ISSUE TITLE
Notifications on mobile - styling fixes

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5371]
Items below show examples from 3 notifications. These styling updates should be applied to all notifications to improve legibility.
See examples of styling for all states of mobile notifications here:
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=13208%3A740

---

Unsigned orders:
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=13258%3A288895
- [x] Button styling is wrong, it's using desktop rather than mobile button
- [x] Text styles and color need to be updated to match figma 
- [x] The copy "You have unsigned orders pending for the following market’s initial liquidity: “What will be the high temperature in Death Valley for 2019?” is split over two lines, it should be one sentence.  
Example on design side of an unread and read state: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/36445e58-4336-4b79-a984-99b7f54dd63a)

Reporting: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=13258%3A288897
- [x] Button styling is wrong, it's using desktop rather than mobile button
- [x] Text styles and color need to be updated to match figma 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/f017b836-8446-438c-a99e-a6c197a40870)

Dispute: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=13258%3A289135
- [x] Button styling is wrong, it's using desktop rather than mobile button
- [x] Text styles and color need to be updated to match figma 
- [x] The copy "Dispute round [X] for the market: “What will be the high temperature in Death Valley for 2019?” is ending soon" is split over three lines, it should be one sentence
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/de14e64e-8acd-4388-9b78-19c9478c1eaa)

**Comment by JohnDanz** [comment]
https://github.com/AugurProject/augur/issues/4789 related

**Comment by cillianhunter0** [comment]
Note the main things to fix and that apply to _all_ notifications: 
- The notification text should flow like a paragraph - there should be no line breaks
- The button should be the mobile button 

**Note - claim proceeds is not in the screenshot but please apply the same changes to it**

See all issues here: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/efc69c5b-741b-4750-9abd-1425ed85d7ce) 

Color issue with the read state: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/27644034-6766-4734-a68e-12ed7a886d01)

**Comment by Chwy5** [comment]
closing
