### ISSUE TITLE
Site-wide timezone setting

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#538]
https://github.com/AugurProject/augur-app/issues/195
...

I think the user is referring to augur-ui. @achapman you want to add a global user selected timezone option in augur-ui?

I think the effort would be biggish, not too big. We have tried to isolate date stuff to date-format.  We'd need to get design for the top core-stats timezone picker.

@serena thoughts?
 -bthaile
...

Yea this seems reasonable to me. Should still default to local since this is a power user thing and normal humans don't think in terms of UTC.

We probably need a design / UI for user session settings anyway to allow setting a manual gas price and such so this could in theory go there.
 -nuevoalex
...

 I think this is a good idea. Adding it to the design list. 
 -sharkcrayon

**Comment by joeykrug** [comment]
we have a separate epic for this
