### ISSUE TITLE
Tradingview.com templates need time zone details.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#5389]
TradingView.com supports user configurable time zone.  The market description for these templates needs to specify that the user should use UTC time zone when determining the open/close price.

**Comment by Chwy5** [comment]
addressed with resolution rule - closing

**Comment by MicahZoltu** [comment]
I don't see a resolution rule on master that addresses this.

**Comment by Chwy5** [comment]
It is in now...got pushed yesterday....2nd Added resolution rule down
