### ISSUE TITLE
Remove fallback conditions for TradingView.com template.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#5390]
Fallback conditions have caused more problems then they have solved in the past and the current templates based on TradingView.com data do not provide sufficient details to address those problems (it is unclear if there exists enough details to address the problem).  Until such time as reporters can figure out a good way to have fallback resolution sources work, the fallback conditions for tradingview.com markets should be removed.

Also, it is worth noting that there is a whole lot of text for how to execute the fallback for coinbase.com, but not for fallback to any of the other supported exchanges.  This is yet another reason to just remove the fallback entirely.

**Comment by Chwy5** [comment]
we want to have a fallback even though it may be a little complex, - closing
