### ISSUE TITLE
TradingView market validators are broken.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#5392]
I don't know the cause, but the `templateValidation` for the TradingView.com markets are broken:
> (^Will the price of (BTC\\/USD|BTC\\/USDT|BTC\\/EUR){1} open on or above [0-9]+(\\.[0-9]+){0,1} on undefined, according to TradingView.com \"(.*)\"\\?$)

Note the `on undefined` in there.

**Comment by Chwy5** [comment]
been addressed - closing
