### ISSUE TITLE
TradingView markets are confusingly worded.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#5393]
The trading view markets have a suffix like "according to TradingView.com "BTCUSD (crypto - Coinbase)".  As a user, I find this wording to be confusing and to not clearly align with the question.  Recommend changing them to read something more like:
> Will the price of BTC/USD open on or above 8000 on Coinbase on December 31, 2019, according to TradingView.com

This makes it more clear that I'm predicting the price of BTC/USD on Coinbase, not the price of BTC/USD more broadly speaking, while still telling me that I should use TradingView as the authoritative source for Coinbase's price.

The resolution rules would still have the text indicating that the market is invalid if TradingView doesn't report the Coinbase open price for the specified date (#5390).

**Comment by MicahZoltu** [comment]
Also consider changing the wording from "according to ___" to "as reported by ___" for this case, which I think is a bit more clear.

**Comment by Chwy5** [comment]
closing, discussing better way to handle these
