### ISSUE TITLE
ZeroX Trading Fees aren't reported right in Transaction History

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#5400]

**Comment by pgebheim** [comment]
The UI is kinda faking up this view at the moment with Redux state, so this is unsurprising -- it really all needs to be consolidated into a getter.

**Comment by joeykrug** [comment]
they (fees that is) aren't reported at all atm

**Comment by joeykrug** [comment]
Is this fixed?

**Comment by bthaile** [comment]
Looked like it worked the whole time. Fee is 0 until user closes position and fees are taken.
