### ISSUE TITLE
Free Shares

### ISSUE THREAD

**Issue by DanielCarlyleEvans** [AugurProject/augur#541]
I just bought 0ver 1,000 shares of "Yes" to the question

"Will the dollar price of ETH, as reported by TradeBlock, be trading below $10.82 at the expiration of this market?"

expiring March 26th.

I paid $0.000

Look, I love a freeroll, but I really don't think shares should ever go to 0.  And with only a few thousand shares total I am surprised that the price wasn't moved more with that size order.

On top of all of that, right now it looks like I have a decent chance of winning (the price is very close to that level).  I could be right but the price right now shows 100% on the other side.  What would be the check against all the reporters just checking the side that looks correct based on the betting?  When real money is on the line and events are resolved before the market closes this will probably be very rare, but it could happen, especially by someone trying to simply game the system by making the market look resolved in their favor.

These aren't the only free shares that I have bought.  Usually I can only get a very few for free though.  I can often get a lot very, very cheap.  Not sure of the formula being used, but it may need tweaking.

Also.... I typed all this while waiting for the trade to confirm and show up.... It didn't, so I refreshed the page and saw nothing had gone through.  I bought 100 and another 100 (for free).  Now it shows all of them went through...  I have over 1200 shares, with 1200 bought for $0.000.

**Comment by DanielCarlyleEvans** [comment]
The ETH price is fluctuating above and below this questions cutoff so I went to check exactly when the market expires (since the question is about the price at that time).  I don't see anywhere on the market page exactly what time it expires.  It may be somewhere (FAQs or something maybe) but it should definitely be on the page as well.  Probably a countdown clock would be best if that wouldn't make the system significantly slower.

**Comment by joeykrug** [comment]
Fixed / non-issue in new limit order system, will be in UI soon™
