### ISSUE TITLE
See Chwy's comments below - modals: unsigned orders - styling fixes _ Still broken in mobile

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5419]
****For launch update :
1) spacing elements for mobile
See last messaging and screenshot about decimal places below
-------------

Desktop
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=14842%3A9141
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/6b46ec93-3083-4454-997c-d5b576bf8426)
- [ ] Modal should have a header, body and footer, the scrollable area is in the body 
- [ ] Update modal background color to match 
- [ ] Update all font styling and color to match 
- [ ] Update table styling and colors to match 

Comparison
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/a6b5ec3c-97b4-4ef0-9273-7606925ba15c)

Mobile
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=14842%3A9142
- [ ] Modal should have a header, body and footer, the scrollable area is in the body 
- [ ] Update modal background color to match 
- [ ] Update all font styling and color to match 
- [ ] Update table styling and colors to match 
- [ ] Update spacing of elements to match 

Comparison 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/7be2bac4-1f68-46ec-96f0-84f104647008)

**Comment by Chwy5** [comment]
For launch update :
1) spacing elements for mobile
2) Color of "Type/ Quantity/ Price /and est Cost (for both desktop and mobile - currently tough to see)

**Comment by phoebemirman** [comment]
which spacing elements do we want fixed exactly? @cillianhunter0   @Chwy5

**Comment by Chwy5** [comment]
its these...see screenshot....numbers arent lined up in its rows....

![3-5spacing](https://user-images.githubusercontent.com/41301809/76026024-03fe7a00-5efc-11ea-908c-0f9bcbfd01b3.jpg)

**Comment by Chwy5** [comment]
Still looks off in mobile....see attached screenshot...

![3-12off.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/d8c4f78f-bfe0-449a-acb2-efc7eb8b1931)

**Comment by Chwy5** [comment]
The Quantity in the modal still shows to 4 decimal places instead of 2 for Yes/No and Categorical...this is what pushes the alignment off in mobile....see screenshot

Change to 2 decimals should fix

![3-17.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/a327a1e2-074c-46ca-8954-f91c7974b88e)

**Comment by Chwy5** [comment]
closing
