### ISSUE TITLE
possible addition of a hover to show full position size

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#542]
This is one of the few times i would think about adding the addition of a hover to show the full number....

Please see attached screenshot (bottom open order in My positions)...where it shows quantity 0 and escrowed eth 0
...

 If we are limiting the quantity field in the order form to 8 decimals and giving the user an option to display quantity in 8 decimals, does that suffice? @chwy 
 -sharkcrayon
...

:thumbsup: 
 -Chwy5

**Comment by joeykrug** [comment]
fixed in new trading ui afaik

**Comment by Chwy5** [comment]
added in new ui - closing
