### ISSUE TITLE
Notification modals: Claim proceeds - styling fixes

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5420]
Desktop
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=13416%3A290467
- [x] Modal should have a header, body and footer, the scrollable area is in the body 
- [x] Update modal background color to match 
- [x] Update all font styling and color to match 
- [x] Update table styling/spacing and colors to match 
- [x] IF only one market to claim THEN show transaction fee in the row and remove the totals (HIGH PRIORITY)

Comparison: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/b4ae5160-3266-4d04-b4b0-36898105adbd)

Mobile
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=13416%3A289941
- [x] Modal should have a header, body and footer, the scrollable area is in the body 
- [x] Update modal background color to match 
- [x] Update all font styling and color to match 
- [x] Update table styling/spacing and colors to match 
- [x] IF only one market to claim THEN show transaction fee in the row and remove the totals (HIGH PRIORITY)

Comparison: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/62a93286-0ebe-4a99-8c59-2db64d9670c4)

**Comment by Chwy5** [comment]
Two parts of this ticket are High priorirty

**Comment by cillianhunter0** [comment]
The transaction fee should be $x.xx, it's showing as X.XXXX. Is that only because Gnosis safe isn't enabled? 

cc: @andrewdamelio do you know if that's the case?

**Comment by andrewdamelio** [comment]
Yup -- b/c gnosis isn't enabled in that test case
