### ISSUE TITLE
Market title jumps around on hover when no hover is needed

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5422]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/6b0f1c2b-35f7-4324-b7df-85fab459032c)

Seems to only be happening when the market goes onto 3+ lines

Probably has something to do with revealing the whole market title when it is cut short

**Comment by JohnDanz** [comment]
yeah it does, it's set to activate If we get to a 3rd line, i'll adjust it

**Comment by matt-bullock** [comment]
![Kapture 2020-01-21 at 0.52.06.gif](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/0f57de5b-4f61-4af5-a382-c58bb39c411f)

It's still jumping around on hover

**Comment by matt-bullock** [comment]
closing
