### ISSUE TITLE
MC: breadcrumb issue at tablet breakpoint

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5425]
At tablet resolution, 800px for example, when i navigate through the template flow two things are happening: 
1. The breadcrumbs in the UI is sitting directly under the app bar, there should be 32px of padding between it and the app bar. 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/7843a489-99bd-467d-898a-98f387c357b5)
2. When i get to the form to enter market details, the page loads in like this (hiding the breadcrumbs until i scroll up)
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/1652d9a0-87c6-4529-9b74-ce955bcf0087)

**Comment by phoebemirman** [comment]
not seeing this issue anymore ![Screen Shot 2020-01-16 at 12.39.50 PM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/dba3c135-8d9a-46b1-9d21-9a8e22d8bc8c)
