### ISSUE TITLE
templates with TEXT (freetext)

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#5433]
[Single Player's Name], [Single Candidate's Name], [Single Person's Name], [Single Horse's Name], [Single Person, Single Group or Movie Title], [Individual Movie Title], [Individual Stock or ETF Name], [Individual Stock or ETF Ticker Symbol]

Added additional Rule to include:  
This market is intended to be about a [Single Person, Single Group or Movie Title], if this is not the case, this market should settle as invalid.

PGA: Will Tiger Woods win the 2020 PGA Championship?
PGA: Will Tiger Woods make the cut at the 2020 PGA Championship?
Euro Tour: Will Rory Mcllroy win the 2020 Omega Dubai Dessert Classic?
Euro Tour: Will Rory Mcllroy make the cut at the 2020 Omega Dubai Dessert Classic?
LPGA: Will Lexi Thompson win the 2020 U.S. Women's Open?
LPGA: Will Lexi Thompson make the cut at the 2020 U.S. Women's Open?
Will American Pharoah win the 2020 Triple Crown?
Men's Singles Tennis: Will Roger Federer win the 2020 Wimbledon?
Men's Double Tennis: Will Juan Sebastin/Robert Farah win the 2020 Wimbledon?
Men's Soccer (Point Spread): Real Madrid to win by more than 1.5 goals over Manchester United?\nEstimated schedule start time: Sept 19, 2019 1:00 pm EST
Men's Soccer (O/U): Real Madrid vs. Manchester United: Total goals scored Over/Under 4.5?\nEstimated schedule start time: Sept 19, 2019 1:00 pm EST
Women's Soccer (Point Spread): Real Madrid to win by more than 1.5 goals over Manchester United?\nEstimated schedule start time: Sept 19, 2019 1:00 pm EST
Women's Soccer (O/U): Real Madrid vs. Manchester United: Total goals scored Over/Under 4.5?\nEstimated schedule start time: Sept 19, 2019 1:00 pm EST
NBA: Will Steph Curry win the 2019-20 NBA Most Valuable Player award?
WNBA: Will Maya Moore win the 2019-20 WNBA Most Valuable Player award?
NFL: Will Patrick Mahomes win the 2019-20 MVP award?
NCAA FB: Which team will win the 2020 Cotton Bowl: Tennessee Volunteers vs. Miami Hurricanes?
Will Donald Trump win the 2020 U.S. Presidential election?
Will Elizabeth Warren win the 2020 Democratic U.S. Presidential nomination?
Will Oprah Winfrey run for U.S. President by December 31, 2019 1 pm EST
Will Donald Trump be impeached by December 31, 2019 11:59 pm EST
Will Kim Jong Un be Supreme Leader of North Korea on December 31, 2019 11:59 pm EST
Will Benjamin Netanyahu be impeached be December 31, 2019 11:59 pm EST
Will Pope Francis vacate papacy by be December 31, 2019 11:59 pm EST
Who be Supreme Leader of North Korea on December 31, 2019 11:59 pm EST
Will AAPL close on or above 200 on then Nasdaq (traded in USD) on September 1, 2020?
Will AAPL exceed 250 on the Nasdaq (traded in USD) anytime between the opening on June 1, 2020 and the close on September 1, 2020?
What will AAPL close at on the Nasdaq (traded in USD) on December 31, 2019?
Will Billy Crystal host the 2019 Academy Awards?
Will Leonardo DiCaprio win an award for Best Actor at the 2016 Academy Awards?
Will Avengers: Endgame gross $350 million USD or more in it's opening weekend in the US?
Head-to-Head: Will Avengers: Endgame gross more than Avangers: Age of Ultron on it's opening weekend in the US?

**Comment by phoebemirman** [comment]
todo: need to update placeholders for all TEXT inputs in this list and add new resolution rule for them

**Comment by bthaile** [comment]
these look to be done. @phoebemirman is there anything left?
