### ISSUE TITLE
Golf Template Fixes - Removing pro am Rule + Tournament and separating out team tournaments

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#5434]
Need to remove Pro am rule from Added Resolution Rules
 
Under PGA Remove AT&T Pebble Beach Pro Am form Event drop down list

Under PGA....Need to make an additional 2 templates using [Team] for Presidents Cup
Remove Presidents cup from current dropdown list and have it in 2 new templates

Under Euro....Need to make an additional 2 templates using [Team] for Ryders Cup
Remove Ryders cup from current dropdown list and have it in 2 new templates

**Comment by bthaile** [comment]
`Under Euro....Need to make an additional 2 templates using [Team] for Ryders Cup`
why 2 templates, not following
