### ISSUE TITLE
Transaction history modal 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5446]
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7110%3A261400

- [ ] Change "fee" label to "Tx fee" 
- [ ] Add in a "Trading fee" column 
- [ ] Change the font used for the values under "market" and "outcome" from roboto mono, to regular, check figma for exact style
- [ ] Width of columns and spacing between columns has been tightened up to fit in the new column, see figma for spacing 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/d6ed7cf0-61e3-4f77-8b30-476b7d84adb2)

**Comment by joeykrug** [comment]
" Change "fee" label to "Tx fee"
 Add in a "Trading fee" column"

Just call it trading fee, 1 column

**Comment by cillianhunter0** [comment]
@joeykrug to clarify: merge the two fees so they appear as one fee? 

Side note: could we do the same on trading page?

**Comment by joeykrug** [comment]
We can’t get the historical gas cost anyways afaik just from logs, so it should really just be trading fees

**Comment by bthaile** [comment]
currently there is only `fee`

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/7fb08c30-7fa3-4756-bb88-fbe1ecac7910)

**Comment by cillianhunter0** [comment]
so are we good to just rename "fee" to "Trading fee" as joey mentioned above?

**Comment by Chwy5** [comment]
closing
