### ISSUE TITLE
Feedback pattern for notification modals 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5448]
This is a general pattern for feedback for transactions / any action that takes time to process. 

Described here for **notification modals** that have multiple transactions that can be triggered. 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=13594%3A287953

1. User taps the action that triggers the transaction 
2. The action(s) that relate are hidden and a "Processing" tag appears 
3. If successful a "Confirmed" tag appears
3.1 The row disappears
3.2 The rows below slide up to fill its space 
4. If not successful a "Failed" tag appears and a try again action appears 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/d959a2e4-9f4b-481b-a381-f8df058dc736)

**Comment by Chwy5** [comment]
@bthaile This is related to the discussion of feedback pattern in notifications and reporting/disputing/ and PT

**Comment by bthaile** [comment]
I dont think we need the confirm right now. Maybe post launch. 

I think only need to show spinner in the notification if the notification modal gets closed as a result of modal action.

**Comment by Chwy5** [comment]
yeah agree...do u have another ticket to merge this into or leave it

**Comment by Chwy5** [comment]
closing - being worked with another ticket
