### ISSUE TITLE
New Market not showing on augur.net

### ISSUE THREAD

**Issue by Jezz81** [AugurProject/augur#545]
A new Contract "Australian NRL: Wests Tigers v. Paramatta Eels 28 March 2016" is not showing on:
https://augur.net/markets
This Contract has been created _after_ the current "most recent" listed in /markets: Currently named as "will full Disclosure of aliens be made by the usa by january 2017"
I can see the "Australian NRL: Wests Tigers v. Paramatta Eels 28 March 2016" listed in:
https://augur.net/overview

**Comment by tinybike** [comment]
As far as I can tell this works properly on https://augur-dev.firebaseapp.com (will be on augur.net soon).
