### ISSUE TITLE
Make sure resolution source is clear on Universes page

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#545]
+ think through selection flow for traders during and post fork.

**Comment by Chwy5** [comment]
What does this mean? Needs more clarity @adrake33

**Comment by adrake33** [comment]
The resolution source is the website (or whatever source) that should be used by reporters to determine the outcome.

**Comment by pgebheim** [comment]
Newest forking modal mocks show this well considered:
![image](https://user-images.githubusercontent.com/86010/64464972-06a02400-d0bf-11e9-8e17-141e66778384.png)
