### ISSUE TITLE
New account auto-reporting (kind of) 

### ISSUE THREAD

**Issue by housemobile** [AugurProject/augur#546]
I made a new account. I checked out the reporting tab and there were 2 markets I could report on. 

I reported on the first one, then I looked at the second one. It says Reported Outcome: Yes. 
I did not report on this market yet. 

![autoreport](https://cloud.githubusercontent.com/assets/17286590/14079623/25a32630-f4cd-11e5-95f8-6e8bd568c1c4.PNG)

When I click on report the radio boxes are empty. 

![radio](https://cloud.githubusercontent.com/assets/17286590/14079657/5787b65c-f4cd-11e5-9278-adc3de6177f0.PNG)

It appears the problem is with 'Reported Outcome' defaulting to Yes.

**Comment by tinybike** [comment]
Should be obviated w/ new UI.
