### ISSUE TITLE
Complete Sets & Initial Liquidity

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#546]
achapman: Someone bringing up making a market and providing liquidity in general chat revived my worry about the way our trading UI displays complete sets(edited)
Currently if you have yes and no shares they just cancel out I think and shows a position of 0.
So for market makers providing liquidity through our provided UI the UI will basically break if someone takes their orders

@Serena @tinybike how would y'all feel about adding in a step during initial liquidity purchasing where the first TX buys complete sets?
This has a few benefits
It makes it so when a liquidity providers orders are taken they just get ETH instead of shares and potentially getting complete sets
It also makes it so initial liquidity is counted for OI
tinybike - Today at 9:50 AM
I think it's generally not what they would want for binary and scalar markets tho
achapman - Today at 9:50 AM
why?
you think they want to own shares?
To be more specific about the current behavior and results:
Currently in initial liquidity they make a bunch of orders and escrow ETH. When people take these orders the market maker ends up with shares. Potentially having both Yes and No or Long and Short shares, which our UI doesnt display correctly (and which I dont think is what they actually want as liquidity providers)(edited)
If they buy complete sets first (up to the lowest number of shares of a particular outcome theyre making liquidity for) they'll instead escrow shares and be paid out ETH when people take their orders
if they have an uneven number of shares between outcomes they'll end up with positions but it wont cause the bad UI behavior and makes sense
tinybike - Today at 10:04 AM
What is it that our UI doesn't display correctly?
achapman - Today at 10:05 AM
owning Yes and No shares at the same time (or Long and Short for scalar)
which will happen as things are currently for market creators providing initial liquidity(edited)
tinybike - Today at 10:07 AM
You mean because it shows their net position?
achapman - Today at 10:08 AM
Because if they own 10 shares of Yes and 9 of No it shows they have 1 Yes share
tinybike - Today at 10:08 AM
That's intended
We can also display the raw positions of course
achapman - Today at 10:08 AM
that would be fine too. I'm saying I suspect we'll need to do something to address that
tinybike - Today at 10:08 AM
Maybe we should, idk, with categoricals it seems like we need to display both
achapman - Today at 10:09 AM
I think the complete set route might be preferable though. It depends on what liquidity providers actually want. I would think they actually want to just receive ETH
tinybike - Today at 10:09 AM
I think we can punt this to after launch, no?
You might be right, tbh I don't know
achapman - Today at 10:10 AM
We can punt anything not security related, I suspect this will become a problem pretty quick
tinybike - Today at 10:10 AM
Maybe so.  The opposite issue -- showing raw instead of net position -- is something @chwy has vocally complained about
So maybe prob just need to display both
...

@achapman Is this addressed now? I remember you guys added in some Complete Sets functionality.
 -sharkcrayon
...

We should still think about having the user buy complete sets before the initial liquidity orders go out
 -nuevoalex
...

@serena Can this be closed?  Does it need to be discussed more?
 -adrake33

**Comment by joeykrug** [comment]
so low priority & no one has asked for it, closing
