### ISSUE TITLE
Total Order Value on trading ticket is empty

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#5464]
To reproduce:

In empty order ticket:

Enter quantity field first (enter either a 1 or an 11)

Then enter price (like .2)...then go back to quantity and add a o to the end of your initial quantity to make it a quantity multiple of 10.

Total Order Value stays empty

(Another way to trigger this is to enter the Limit price first then the quantity....Total Order Value doesnt filter in

**Comment by joeykrug** [comment]
@andrewdamelio or @bthaile was working on fix for this I believe

**Comment by bthaile** [comment]
@Chwy5  can you test this one again. I got a fix in for it.

**Comment by Chwy5** [comment]
i am still seeing this happen on local

It actually does filter in but take like 7-10 seconds to do so

**Comment by bthaile** [comment]
not able to repro. it might be a function of how many open orders there are on the book and sim trade taking a long time. 
![order-form-cost](https://user-images.githubusercontent.com/3970376/74271892-48b73c80-4cd3-11ea-9bff-61f8c15e12f2.gif)

**Comment by bthaile** [comment]
@Chwy5  can you try and repro on a market that has zero open orders in the book and one that has a lot of open orders in the book. see if there is a difference in speed of total order value getting populated.

**Comment by Chwy5** [comment]
tested both, working much better - closing for now
