### ISSUE TITLE
Add Estimated transaction fee to order ticket

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5465]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/5f8f44ce-222f-45fb-99ba-581fa2d283d4)

https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=3187%3A19884

See any notes from Chwy below

**Comment by Chwy5** [comment]
Make sure Estimated fee and TX fee are not deducted from profit (currently estimated fee is deducted)

**Comment by Chwy5** [comment]
Currently discussing all fees....design might change...dont work till i ok

**Comment by bthaile** [comment]
notes:

from order form perspective, ZeroX trading Summary:

create open order (no transaction/gas fees)
make trade (0xfee/transaction fee/gas fee)
cancel open order (has transaction/gas feee)
order expiration (no transaction/gas fees)
closing a position (market settlement fee and transaction/gas fee/0x fee)


0xfee is 150kgas * gasPrice -- so our estimate can have that tacked on for display

use this gas amount for transaction fee.

**Comment by Chwy5** [comment]
@bthaile for comments or questions how this will work

**Comment by matt-bullock** [comment]
@chwy can you check the functionality here and close if good
