### ISSUE TITLE
Shield and text highlight for Templated market with MC inputted text

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5469]
Design: https://www.figma.com/file/Do4qnkCNM8P7lwBmCdYZCS4X/Market-Cards?node-id=3229%3A10948

Yellow shield acts as a caution for templated markets that have freeform TEXT inputs.

Inputed text should be highlighted in yellow in the market title across market cards, trading page and reporting and disputing forms.

When hovering (desktop) or tapping (mobile) the highlighted text will show a tooltip explainer.

Shield tooltip explainer: "Templated market question, contains market creator text. This text should match to highlighted section's tooltip."

market question: In-line text Tooltip copy determined by template input placeholder text

**Comment by Chwy5** [comment]
Desktop works....having trouble closing the tooltip after I click to open it on mobile. Do you think we need to add an (x) to close them....both for shield and in-line text tooltips?

**Comment by phoebemirman** [comment]
@Chwy5 moving your mouse away doesn't work?

**Comment by Chwy5** [comment]
on desktop yes.....but not on mobile

**Comment by matt-bullock** [comment]
can you make it so that tapping anywhere on the screen on mobile closes them, even tapping the tooltip. Can you see any issues with doing this?

**Comment by phoebemirman** [comment]
@matt-bullock it works like that for me now

**Comment by phoebemirman** [comment]
are you still seeing this? @Chwy5 
not reproducible for me

**Comment by Chwy5** [comment]
working for me now...closing
