### ISSUE TITLE
if i click a link in the footer, I get logged out (firefox, windows10)

### ISSUE THREAD

**Issue by RonB7139** [AugurProject/augur#548]
also to consider if some/all the links should open in a new window

**Comment by joeykrug** [comment]
Login issue is b/c if you don't check "remember me" navigating to another window will log you out --- this should probably be changed or allow people to enable remember me after registration

**Comment by RonB7139** [comment]
agree, you shouldnt be logged out during 1 session on same browser

**Comment by tinybike** [comment]
Obsoleted by 59f966ae8b6d24f221fec1ec166e75a53216429e.
