### ISSUE TITLE
Add google translate to UI and/or landing page

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#548]
We've discussed this at various points, and one of the old landing pages had google translate integrated.  It seems beneficial to have this in both the landing page and the UI.  Input appreciated!

Suggested by @joeykrug on Discord.

----

EDIT by Serena:

@mattbullock We should decide where the translate button should go.
...

Doesn't that count as having a third party script installed? I thought we couldn't do that.
 -sharkcrayon
...

@tomkysar is there a restriction against using third party scripts?  We already are using third-party scripts in some cases (e.g. Trezor) so it definitely isn't a blanket restriction.

...

@serena @tinybike - no restriction (legally speaking) w/ 3rd party scripts. Mindset prior to launch was always to remove as much of this as possible, from a dApp / security perspective. Foreign JS and dependence on another service _primarly_ would like to avoid, but I think Google Translate is generally OK (it's not disappearing anytime soon, and don't think Google is gonna pwn us). 

But no legal restrictions! Scripts should just be evaluated from a technical & security standpoint. 
 -tomkysar
...

Okay, so that's good to know. 

From a product standpoint though, I'm not sure this is something we want to add. If Google translate is automatically translating what's on the page,  users lose transparency between what is very specific text intended by the market creator and what is translated text. I personally wouldn't want to trade on the market if I didn't know whether the title I'm seeing is the same title other traders and reporters will see.

I could be much more intentional by using the Google translate browser plug-in or website.

@tinybike @joeykrug 
 -sharkcrayon
...

Hm, maybe I'm misunderstanding how Google translate integration works, but I think it's not fully automatic -- it asks if you want the page translated, then lets you select what language you want something translated into.

...

That's what I'm saying is the problem. It translates the entire page, so you don't know which text you're looking at is the original text or translated text (which could be incorrect, or less specific).
 -sharkcrayon
...

But you had to manually tell it to translate the page, after the page had already loaded, so you have the chance to inspect it both ways, right?

Is there a way to use Google translate in a more targeted way?  I.e. a button next to the market description that causes translated text to be displayed below it / in a pop-up or something?

...

Yeah, if people use the browser plug-in, you can hover over specific text and translate just that.
 -sharkcrayon
...

Someone who doesn’t speak English doesn’t care about the plain text, they want to see it in their language
 -joeykrug
...

People aren’t going to install a browser plugin
 -joeykrug
...

This used to be part of the UI and it was pretty great, somehow it got mysteriously removed. 
 -joeykrug
...

The special case is someone wanting to look at plain untranslated text. They can easily do that by refreshing or opening an incognito window
 -joeykrug
...

But there is a big difference in reliability between the markets that have been translated and markets that are in the user's original language. When the entire page is being translated there is no way to know the difference between two. The accuracy of the market title and additional details is extremely important. If everything is being translated then users have no way of knowing if they are looking at an accurate market title (created by someone speaking the user's language) or a market title that has been filtered through the lens of a sometimes-inaccurate translation AI.
 -sharkcrayon
...

Imagine if there was a feature on the site that, for a random sampling of markets, changed a word here and there. There is no immediately apparent indication on which markets is has been done. Would you be comfortable trading on any of the markets without first turning off the feature to know which markets had been changed?
 -sharkcrayon
...

FWIW google translate was included in the old UI (https://github.com/AugurProject/augur-ui/pull/867) but AFAIK it hasn't ever been part of the new (IDEO) UI.

@joeykrug I think what @serena is saying is, maybe people _shouldn't_ be trading or reporting/disputing on markets that aren't in a language they actually know, because something could be getting garbled by the translator and they would not realize it.

...

Yes, exactly. And I'm also saying that if the entire page is being translated, users don't know which markets might be garbled so they can't make an informed choice on what level of risk they're taking.
 -sharkcrayon
...

IDK, is it unreasonable to expect users to click the translator on-and-off if they want to see _which_ markets have text that is being translated?  That seems pretty simple to me.

...

Google translate is as accurate for humans for most languages now anyway. Hard to get much better. The feature example is not a good one because I *know* I requested translation, I didn’t request some random sampling shit, but I certainly requested the translation. I *would* already know which markets have been changed because google tells me what is translated and what was already in my native language and thus didn’t need translation. So both these arguments seem invalid to me
 -joeykrug
...

Users of chrome *already* get all this behavior out of the box, all I’m suggesting is making it so users of other browsers get the same benefits
 -joeykrug
...

Right now a huge swath of the world cannot use augur because of lack of localization. Localization that we provided with auto translate of the crowdsale site btw, let users make their own judgement calls on what to do with that information imo vs withholding it from them 
 -joeykrug
...

Also, I don’t think that’s unreasonable Jack (heck, users don’t even have to ever turn it on if they don’t want to). This is just suggesting an optional feature be added back in so that more people can use augur. Like everything else involved in using augur, they can make their own judgement calls whether they feel comfortable using it, but right now it’s not even an option (and even worse, it was an option in the past which we’ve since removed - remember the majority of repholders at the time anyway we’re actually overseas!)
 -joeykrug
...

Okay it looks like it _is_ easy for the user to check with the original text is:

![clipboard 2018-07-08 at 2 32 36 pm](https://user-images.githubusercontent.com/11491365/49620405-93be1d00-f975-11e8-8255-14c804394e13.png)

And users should see a notification along the top of page when translation has been done:

![clipboard 2018-07-08 at 2 33 28 pm](https://user-images.githubusercontent.com/11491365/49620415-9caeee80-f975-11e8-92e2-565dabdb0024.png)

So that satisfies my concerns.

Let's move forward with this :thumbsup: 
 -sharkcrayon
...

:tada: 

...

Google can autodetect if the content is not your native language and offer to translate. Including this is like one line of html or js, I dont see why an issue brought up 2 years ago is taking so long to implement / in the spirit of Nike let’s just do it!

 -joeykrug
...

(No button needed)
 -joeykrug

**Comment by joeykrug** [comment]
Done
