### ISSUE TITLE
Movie gross templates are likely to resolve as invalid.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#5483]
At the moment, it is not well specified in the templates what exactly should be measured for "weekend".  Does a weekend start midnight UTC on Thursday evening?  Midnight local timezone Thursday evening?  Midnight East coast?  West coast?  Besides that, different websites may calculate gross differently, or from different root sources.

Either the templates need to be updated with much more strict rules about how to resolve them, or they need to be changed to use a resolution source.

**Comment by MicahZoltu** [comment]
Related: https://github.com/AugurProject/augur/pull/5387

**Comment by Chwy5** [comment]
@MicahZoltu I had a feeling you were going to say that for this one... @bthaile There are way too many rules to add to what is included in domestic and international (specific countries, times, etc)....Let's add www.boxofficemojo.com into the market question as a resolution source. We still will need to add a backup source if that isn't available.

**Comment by MicahZoltu** [comment]
Backup sources have, historically, not worked well for markets.  Generally you are better off just letting the market resolve as INVALID if the primary source is unavailable.  INVALID then translates (effectively) to "probability that boxofficemojo will be down".

Something you can do to mitigate this is to encourage a longer period of time between expected announcement of gross and market resolution.  For a market to resolve as INVALID due to resolution source not available the site/data has to be unavailable for the entire period leading up to the reporting time.  If there is a 3 day window (for example) between expected publishing of results and market resolution then it is unlikely that boxofficemojo will have a 3-day outage or a 3-day delay on reporting.

**Comment by Chwy5** [comment]
added backup source and delay window (earliest it can resolve is Wed following the weekend)
