### ISSUE TITLE
WarpSync rewards go to tx relayer instead of GnosisSafe owner 

### ISSUE THREAD

**Issue by epheph** [AugurProject/augur#5489]
Now that augur supports transaction relay using GnosisSafe, we cannot rely on `tx.origin` to reward the protocol-level sender of a transaction. The line in question is here:

https://github.com/AugurProject/augur/blob/8e62ffe80226c385d01dcb0ffc9fc1d601dd7da6/packages/augur-core/source/contracts/WarpSync.sol#L88

The reason for using `tx.origin` here is likely because the calls that are awarded with minted rep come from a few places, and each would need to pass along msg.sender.

**Comment by nuevoalex** [comment]
Since it is generally thought this reward will almost always go to bots this is likely not worth adding complexity to address.
