### ISSUE TITLE
this market format is unclear, it is it a trading range between 0 and 140 or is it a "higher than/less than" prediction (he had like 300 points last year accdg to cbs)

### ISSUE THREAD

**Issue by RonB7139** [AugurProject/augur#549]
![1](https://cloud.githubusercontent.com/assets/16419551/14144818/51b30f72-f65f-11e5-978e-26371ab7a525.png)

**Comment by joeykrug** [comment]
Discussed this w/ Carl a couple weeks back, should be fixed in new UI design

**Comment by joeykrug** [comment]
dup. of new issue now
