### ISSUE TITLE
Trading needs to support vDAI

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#5498]
ZeroXTrade currently works exclusively with `cash`.  During global shutdown, anytime a complete set is sold it will generate vDAI, rather than DAI, that is transferred to the user.  This means that a trader may open a position with DAI but then close the position and walk away with vDAI that cannot be converted to DAI.  This means the user cannot then use that capital to open a new trade, they need to go somewhere else to trade vDAI for DAI before they can then open a new 0x trade.

Not only does this provide a poor user experience, over time DAI could become a scarce resource as Augur migrates DAI to vDAI with each complete set purchase/sale.  This could lead DAI to end up with a hefty price premium over the underlying claim on collateralized assets compared to vDAI.

Resolution: Add support for using vDAI in 0x trades.  I don't have a complete solution, but at the least the `cash.allowance` checks need to change to `CashSender.allowance` checks:
https://github.com/AugurProject/augur/blob/de76fd1ce689e0ec52e0bf2f07bd64d796185485/packages/augur-core/source/contracts/trading/ZeroXTrade.sol#L170

Under the hood I suspect more work will be required to make 0x work with mixed DAI/vDAI, but I'll leave that to an exercise for the reader.  😉

**Comment by nuevoalex** [comment]
I believe this is just that the ZeroXTrade balanceOf function will become inaccurate over time. Trading does work with vDai already so shouldn’t be too bad

**Comment by MicahZoltu** [comment]
"Inaccurate over time" could easily result in "unusuable over time" if DAI liquidity dries up while vDAI liquidity does not.  Since DAI => vDAI is one way during shutdown, and Augur is actively doing that one-way transition, it is very possible (I would posit even likely) that post-shutdown, Maker will end up with almost no DAI and some vDAI available.

**Comment by MicahZoltu** [comment]
It is worth noting that vDAI doesn't have an allowance function.  There is a balance function and an "authorized to send" boolean.  This means that vDAI trading is either on or off.

It is also worth noting that vDAI is not an ERC20 token... which may cause problems with 0x's trading functions (there is no `.transfer`, `.transferFrom`, etc.)

**Comment by nuevoalex** [comment]
Just noting it won’t result in direct loss of funds or anything. I agree we should make the balanceOf function handle shutdown.

CashSender handles doing the equivalent of transfer and transferFrom for vDai
