### ISSUE TITLE
Market Statistics

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#550]
Interesting, so there are two types of statistics here:

1) Statistics on a per market basis:

open interest, [available on chain]
last trade price, [available on chain]
price change since yesterday (absolute and percentage), [has to be calculated in UI]
lifetime and today volume (shares traded), [lifetime is on chain, today volume isn't]
lifetime and today price extremes (min/max), [has to be calculated: easily done by taking them from the price charts in UI (which i don't think exist yet in the new UI)
number of participants (traders) [available on chain]
as suggested above sounds good

2) Statistics for the entire system:

total markets created [available on chain]
total volume [not available on chain: sum(volume of all markets) from the initial market load data the UI has to use to sort by volume is the way to calculate it]
total value of shares traded: total shareValue is available for each period, sum them all for each branch to get total value of shares traded
Both are useful
...

@micah.zoltu @sprinkle this stuff will now be available via augur-node, if you still think it's useful to include in the UI.

...

Need design for this feature
 -Chwy5

**Comment by joeykrug** [comment]
These are all in the UI now
