### ISSUE TITLE
Movie total gross opening day validations

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#5507]
with new changes to movie total gross templates need to add validations for market creation form and shield validations.

In market creation form detect `validationType: ValidationType.EXP_DATE_TUESDAY_AFTER_MOVIE`.  and blackout all days including Tuesday after movie opening date for event expiration.

same for shield validation. if event expiration is before the start of wed after opening day don't give the shield.

**Comment by Chwy5** [comment]
looks correct -closing
