### ISSUE TITLE
template doesn't stay selected in template selector

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#5509]
navigate to Entertainment templates.
template doesn't stay selected, but the `Next` button activates.

![image](https://user-images.githubusercontent.com/3970376/72275620-e4319080-35f3-11ea-8bed-8f95656ec399.png)

![image](https://user-images.githubusercontent.com/3970376/72275640-e98edb00-35f3-11ea-95f9-77fb6cb3970e.png)

**Comment by phoebemirman** [comment]
steps to repro: click a template, then go back, then go forward, next is selectable
