### ISSUE TITLE
Category System Suggestion

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#551]
This [along with loading / slowness issues being fixed] is one of the most requested features on augur.

Simple suggestion / way to do it:
tag1 is a category
tag2 is a subcategory
tag3 [or maybe a few more past tag 3] is[are] [a] keyword[s]

Allow users to browse by category and then subcategory, when within those search would filter by keyword.  Could be a sidebar with categories or something else entirely like a dropdown.  Most popular categories and subcategories would be shown first

**Comment by joeykrug** [comment]
Should do #519 as part of this

**Comment by joeykrug** [comment]
requires collab w/ @Newportkiwi

**Comment by tinybike** [comment]
Combined with #598.
