### ISSUE TITLE
portfolio page: create templated markets

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#5510]
currently a bug, have to logout then back in for newly created markets to show in portfolio.

for portfolio, need to add template shield for both when ALL is selected or when a specific market status is selected.

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/a423c239-f8d8-4c24-b89a-9947a3aa033b)

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/485e8317-2c24-47bd-b886-3645eac9d583)

@matt-bullock  design?

**Comment by phoebemirman** [comment]
is there a design for when a specific market status is selected? not sure where the shield would show up there.

**Comment by matt-bullock** [comment]
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7110%3A244777

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/25958182-7717-45a2-addf-02d487b45653)
