### ISSUE TITLE
Help Menu Item Hyperlinks need better links

### ISSUE THREAD

**Issue by jfarid27** [AugurProject/augur#5521]
**Is your feature request related to a problem? Please describe.**
The current iteration of the help menu has items which mostly link to docs.augur.net. Should these point to something else?

![Screenshot from 2020-01-13 18-46-12](https://user-images.githubusercontent.com/1673206/72301904-4b703480-3636-11ea-8105-340684ee27a8.png)

**Describe the solution you'd like**
Possibly link to documentation that specifically describes how to trade, how to dispute, etc. I'm not sure if the content is created yet but I would even recommend removing the links from the help menu entirely if it's not available.

**Comment by joeykrug** [comment]
there's another issue to add these tagged as v2 req to launch, closing as dupe
