### ISSUE TITLE
Add red flag icon/tooltip to market cards for markets that fail the invalid filter threshold

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5526]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/a93cfe9e-87c0-42b6-bd0e-f98e5dfca00c)

Design: https://www.figma.com/file/Do4qnkCNM8P7lwBmCdYZCS4X/Market-Cards?node-id=3419%3A11110

Should sit before the templated market icons

Tooltip copy as a placeholder until a decision can be made
`"This market has a very high probability of resolving as invalid"`

**Comment by Chwy5** [comment]
For Tooltip: 

This market had failed the invalid filter and has a very high chance of resolving as Invalid

**Comment by matt-bullock** [comment]
@bconfortin The tooltip isn't showing the copy Chwy posted above. It still shows ![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/cd01eee5-af5c-4ee9-885f-ee89eabd06b1)

**Comment by bconfortin** [comment]
Will fix this asap @matt-bullock

**Comment by matt-bullock** [comment]
@Chwy5 Should the message under the market title read the same as what you posted above: 'This market had failed the invalid filter and has a very high chance of resolving as Invalid'?

Current image from build:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/1e9c493b-6672-45ad-8ff1-21889ec227aa)

**Comment by Chwy5** [comment]
looks good - closing
