### ISSUE TITLE
Post Launch we need to add hover tooltips to tutorial

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#5529]
anything we expect traders to hover over we need to add to tutorial at some point otherwise non powerusers will miss it

https://docs.google.com/spreadsheets/d/1UHaFfDF9LBNgDcQx4U9ZyQXW8F6OD0MQfnpAvt_O0JI/edit?usp=sharing

**Comment by joeykrug** [comment]
losing game UX wise imo, just need a simple UI for non power users is real soln to this
