### ISSUE TITLE
Community market storage

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#553]
Use something for market data storage so only new markets have to be fetched on UI load, not all the old ones every time.  Gist, usenet, etc. could be used for this.  New markets that the UI notices that haven't been added to the list yet would be appended to it.  If this goes down user an always load all markets, but will take longer

**Comment by joeykrug** [comment]
This should improve loading times by _a lot_, like a gazillion times

**Comment by tinybike** [comment]
Maybe not quite a gazillion

**Comment by tinybike** [comment]
@joeykrug what mechanism did you have in mind for this?  Is there a way to do a community market cache without it being easy for people to edit (mess with) the info?

**Comment by tinybike** [comment]
Combined with #554
