### ISSUE TITLE
Add expiry countdown to open orders in trading page and portfolio + change cancel button on desktop 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5531]
###  Desktop
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/2a4ed001-81cb-4dc8-869c-f30a3525f5bb)

https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=209%3A745

- [ ] Add countdown next to cancel button to orders that are set to expire
- [ ] Change text button to icon button with close icon - this gives room for the expiration countdown

### Mobile 
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/352326e8-c2cb-4e57-91f0-8f5885b47e29)

https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=480%3A9844

- [ ] Add countdown next to BUY/SELL text
- [ ] DON'T change cancel button on mobile

### Desktop

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f0606610-d7c2-40aa-a343-b64160222921)

https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=2629%3A4491

- [ ] Add countdown next to cancel button to orders that are set to expire
- [ ] Change text button to icon button with close icon - this gives room for the expiration countdown

### Mobile
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/d5ce939c-5fef-4e2e-85dc-3293dde4c0d7)

https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=6149%3A5376

- [ ] Add countdown next to BUY/SELL text
- [ ] DON'T change cancel button on mobile

**Comment by Chwy5** [comment]
added - closing
