### ISSUE TITLE
Change the yellow highlight to an underline for Templated market with MC inputted text 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5532]
2px underline

https://www.figma.com/file/Do4qnkCNM8P7lwBmCdYZCS4X/Market-Cards?node-id=3424%3A99
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/37004a91-248a-45ff-aa1b-b877b17e8d19)

Tooltip still appears above text:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/ecb7233c-34c5-4881-8e7d-6e9def9dbee3)

**Comment by Chwy5** [comment]
closing
