### ISSUE TITLE
Community Nodes

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#554]
Parity nodes run by community so avg. users don't need to download & run their own nodes.

So needs to be some way for people to add nodes to the node list & verify they're legit nodes, they need to accept rpc calls for augur.net, and there needs to be a very easy way for people to setup cloud nodes.

All is pending Parity working w/ augur of course

**Comment by tinybike** [comment]
I'm still trying to get Parity working.  geth will be switching out its leveldb for rocksdb soon as well, which should bring its performance up to acceptable levels.  Between these two things we should hopefully have our speedup soon.

**Comment by joeykrug** [comment]
done
