### ISSUE TITLE
Considered advanced search functionality / more filters

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#555]
- max fees (only show markets with fees under X)
- min open interest
- liquidity sort or filter of min liquidity available (see comments below for chat from Discord)
...

Liquidity definition suggested by burdakovd:

for liquidity you'd want to take market spread while imagining certain trade volume (e.g. 1 ETH) in both directions. If you take market spread as it is, it will be confused by dust orders.

Simple way to phrase it is "If a trader (or group of traders) came by and decided to buy each share to form N complete sets, how much would they lose as opposed to scenario where they'd just create complete sets from ETH directly". Such formulation naturally makes it work for all types of markets (binary/categorical/scalar).

Also good metric should change little if an order is split into two orders with very similar prices or two orders with similar prices are merged into one order (the one I suggested has this property, while the naive one "out of all orders with size greater than X, what is the spread between closest buy and sell order" is not stable when splitting/merging orders)

Maybe do it as a search filter, comments from aaaaaaaaaa / chwy:

In the predictions.global metric, the user can choose the X parameter. So if they want to trade 1 eth they set it to 1, if they want to trade 100 eth they set it to 100

What about giving the user the ability to search not just a distance or % away from the midpt, but also allow for a minimum amount of available market size (bid/ask quantity)

Comments from Serena:

I especially like this idea of a param the user can set in terms of ETH they want to be able to trade, bc then this will serve both the small fries and the whales.
 -sharkcrayon

**Comment by joeykrug** [comment]
A simple idea here is you should be able to filter by multiple things, so instead of just choosing one filter you can do multiple. Like markets with fees under .5% and OI over $50k and volume over $100k as an example

**Comment by joeykrug** [comment]
Closing, we have most of these except a spread filter now and making an issue for that now
