### ISSUE TITLE
App Switcher

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5551]
Note the different designs for mobile, tablet and desktop breakpoints 

https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=3342%3A1345

**Comment by Chwy5** [comment]
@pgebheim @bthaile When do we want to start work on this?  This is the swithcher on the top of the pg to change from Trading, to betting to sportsbook

**Comment by pgebheim** [comment]
Need a product decision on whether or not we want to tease the other UIs within the trading UI.

If not, I would include this work in the betting ui push,

**Comment by joeykrug** [comment]
It already says Betting Exchange App - Coming Soon! which seems sufficient to me

**Comment by pgebheim** [comment]
Adding this to the Betting UI release

**Comment by pgebheim** [comment]
First phase of this was put into betting ui branch, right @JohnDanz ?

**Comment by joeykrug** [comment]
yes
