### ISSUE TITLE
Markets should show creation date on market page and on reporting page

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#556]
For this reason https://www.reddit.com/r/Augur/comments/4d5l39/is_there_a_way_to_see_when_markets_where_created/

**Comment by tinybike** [comment]
Right now creation date requires an extra request (b/c it's in a log) so for efficiency's sake it's loaded after the other data.  If this is important, can we move creation date on-contract @joeykrug?

**Comment by joeykrug** [comment]
It's not important to load slower or not. Just important to appear in general, and it doesn't for me or the poster

**Comment by joeykrug** [comment]
ive never seen creation dates when reporting even after waiting 20 minutes well after things have loaded

**Comment by tinybike** [comment]
Creation dates aren't shown on the reporting page at the moment.  They are shown on the trading page though:
![screenshot - 04242016 - 04 29 04 pm](https://cloud.githubusercontent.com/assets/2637020/14771243/b408dc72-0a39-11e6-930a-f3e41536813f.png)

**Comment by joeykrug** [comment]
should show on reporting page too --- useful for reporting sometimes

**Comment by tinybike** [comment]
Creation date now on-contract and pulled in with getMarketInfo.
