### ISSUE TITLE
Post-launch idea: chat window

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#556]
Idea I wanted to throw out there for discussion: should we add a gitter pop-over chat window to our UI?  This would be post-launch.  I've seen chat windows like this on several sites -- EtherDelta and bounties.network both use it -- and it seems to work pretty well overall.

Possible downside: gitter is mostly used by developers, so this might not be a great solution for non-dev end-users.
...

@serena — looping you in on the discussion.

...

I'm going to throw this in our Peccary sprint, which is post-MVP. When I review our tasks for that sprint I'll think about this more closely.
 -sharkcrayon
...

Or whisper, chat doesn't need to be persistent beyond a few days
 -joeykrug
...

Non gitter / whisper trollbox better  imo
 -joeykrug

**Comment by pgebheim** [comment]
V2 - Dup#3404
