### ISSUE TITLE
Discussion: What components will be shared between Trading and Betting UI

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#5571]
This will be our pro-active discussion ticket for how to handle component usage across the UIs. Any questions, thoughts, issues should be mentioned here so we're capturing that.

Figma Betting UI Link:
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=140%3A0

Design System:
https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet---Design-System?node-id=0%3A1

**Comment by JohnDanz** [comment]
Goal:
Betting / Trading ui needs to be switchable on the fly with a button tap.

General Plan:

we can use a common ui folder to house elements shared between betting and trading.

we should be able to use the concept of `context` in react to facilitate the switch of ui styling.

Early on: 

we should create a branch to start setting up the basic structure with an aim to take a short time (less than 1 month) to have it be mergeable back into master without breaking anything. After we will make a long running betting branch that does the heavy lifting and will have master get merged back into it to ensure that the latest changes to master/common components get propagated into the betting ui.

**Comment by rubyweb3** [comment]
UI not in https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=140%3A0:

My Account in Betting UI

**Comment by rubyweb3** [comment]
Common components:
- Market List and My Bets in betting UI will share many component in trading UIs. 
- Setting, account, alert modals are same in trading and betting UIs

**Comment by pgebheim** [comment]
Closing this ticket, its being handled by John and Matt as they go through the betting ui.
