### ISSUE TITLE
shift dropdown on tables to right for mobile view

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#5574]
see original request at bottom of here (@matt-bullock  comment)

https://app.zenhub.com/workspaces/augur-5bfed3424b5806bc2bf8d173/issues/augurproject/augur/5197

<img width="675" alt="Screen Shot 2020-01-16 at 11 47 55 AM" src="https://user-images.githubusercontent.com/6775839/72557667-14786980-3856-11ea-9102-453e4b42ccbb.png">

**Comment by phoebemirman** [comment]
done ![Screen Shot 2020-01-20 at 11.57.05 AM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/e537e202-46ed-411f-889d-752f14bddc9c)

**Comment by matt-bullock** [comment]
This is meant to be left aligned like the design screenshot in original comment
