### ISSUE TITLE
Mobile menu sometimes has double scroll

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#5575]
original issue this was referenced https://app.zenhub.com/workspaces/augur-5bfed3424b5806bc2bf8d173/issues/augurproject/augur/4636

see matt's comment
![Screen Shot 2020-01-16 at 11.48.55 AM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/17790fe9-039f-4426-9d0f-aead6e349e52)

**Comment by matt-bullock** [comment]
issue appears fixed. closing
