### ISSUE TITLE
change how clearing dropdowns work

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#5576]
see original request here
https://app.zenhub.com/workspaces/augur-5bfed3424b5806bc2bf8d173/issues/augurproject/augur/5054

![Screen Shot 2020-01-16 at 12.06.05 PM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/99e45ab4-c910-41c7-ac7b-24c72fb048ec)

**Comment by Chwy5** [comment]
closing
