### ISSUE TITLE
Make colors on reporting page

### ISSUE THREAD

**Issue by housemobile** [AugurProject/augur#558]
Right now the reporting page is bland. The only way to tell if you've reported on a market or not is it says either PLEASE REPORT OUTCOME or OUTCOME REPORTED. 

It's not easy to efficiently see this when scrolling through all the markets. It would be helpful if reported markets were green and unreported markets were red, or some other color scheme.

**Comment by tinybike** [comment]
This should be solved w/ the new interface https://augur-dev.firebaseapp.com.
