### ISSUE TITLE
Add social media widget support

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#558]
Should add the social media widgets to the Beta release so people can easily send a market to Facebook, Twitter, or email contact.

Edit: I see Twitter widget in the Alpha. Should add others...
...

@mattbullock  Where should Social Media widgets be added?  Also does this require icons to be created or do we have specific ones Aaron should use?
 -Chwy5
...

@joeykrug How would this work on main net? The link wouldn't load unless the user has Augur App running.
 -adrake33
...

The same way  it works on predictions.global, it'd link  to a localhost url with the market ID in  it --- but yeah  you have to  have augur running for it to work
 -joeykrug
...

@joeykrug Actually, maybe we could make the domain be dynamic. For example, if someone on augur.casino posts a link to a market, the link would go to augur.casino.
 -adrake33
...

Good call
 -joeykrug

**Comment by matt-bullock** [comment]
![image](https://user-images.githubusercontent.com/39496225/50225728-9b33ec00-03a1-11e9-890e-ca56f8304739.png)
I included this menu icon (top right) as a way to quickly share the market and possible other actions that we can put there without cluttering the market cards. I need to think through the rest of the flow for this.

I would prefer to hide the social media icons in a similar menu on the market page, but this could be a more obvious 'share' button which then reveals the sharing options. Having too much in that heading area could make it cluttered but we should discuss this more.

**Comment by joeykrug** [comment]
it shouldnt be hidden like this. should be a copy paste button + fb + twitter + IG buttons up front / obvious

**Comment by pgebheim** [comment]
This has been handled in the V2 designs. #4099 #4094 for implementation
