### ISSUE TITLE
Let people know the average price they bought in at

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#56]
I think an additional piece of data would be useful in the holdings modal.  When you buy/sell shares, basically take the amount your cash decreased/increased by and divide by number of shares you bought/sold and that gives you the average price per share you bought/sold at.  Would be useful to have this stored in the holdings modal.

**Comment by tinybike** [comment]
Added in AugurProject/augur.js@7ca2337e6a9d940ff684e7143e92400bf0d29e07 / ccf369688980fabf7d4dff8d09419271309f6560.
