### ISSUE TITLE
Uniswap - when balance is 0, I can't only enter 0 in the input

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5606]
If my balance is zero and I try to type any number but 0 into the input, it won't work. 

We should replicate how uniswap handles this by highlighting the balance, the number being input and displaying an error message below the inputs. 

Uniswap handles the error case like this: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/302119ad-56dc-4536-9c50-f5132e254672)

**Comment by pgebheim** [comment]
Validation doesn't break at this point.
