### ISSUE TITLE
Add text 'Must be a multiple of 10' top right of quantity input

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5616]
Needed for Binary and Multiple Choice Markets

Design: https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=2733%3A0

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/7478bce0-3fc6-49f7-bea0-305e437b5a05)

**Comment by Chwy5** [comment]
@bthaile do we remove this for scalars?

**Comment by joeykrug** [comment]
Why is this ticket even needed? We already show an error message when it's off, and for scalars it needs to be dynamic - so showing the size that makes sense for the scalar, so not a constant ten.

**Comment by Chwy5** [comment]
How are users supposed to know they need to enter a multiple of 10....doesnt say it anywhere until an error is triggered

If you are ok with the error message being the first indication to the user about needed to trade in multiple of 10's close the ticket

**Comment by joeykrug** [comment]
It's not just a multiple of 10 --- needs to be a diff multiple for scalars, which we know how to calculate though

**Comment by Chwy5** [comment]
Cant we make the message disappear for scalar markets?

**Comment by bthaile** [comment]
Easily make the message disappear for scalars or for scalars change the message to tell the user the min quantity for the specific scalar market. Which would be clear and helpful.

**Comment by joeykrug** [comment]
The latter - showing the chunk value for scalars would be helpful
