### ISSUE TITLE
Outcome selector in order ticket - Should open on click, not hover + make menu same width as outcome button

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5617]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/29b495d6-54d9-445d-9e26-c5f92f76ca7a)

See guide:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/c93f52a7-2043-474e-9324-9eb39b5e5874)

**Comment by rubyweb3** [comment]
I guess it's a bug in my recent PR https://github.com/AugurProject/augur/pull/5604 I will work on it.

**Comment by rubyweb3** [comment]
I'm working on a PR to fix the issue

**Comment by rubyweb3** [comment]
@matt-bullock I have a PR to fix width in outcome selector in order ticket

 I think I misunderstanding the requirements of hover state on all dropdowns as we discussed in https://github.com/AugurProject/augur/issues/5016. 

Does "mouse over on the button triggers the hover state" to all dropdowns but exclude outcome selector in order ticket

**Comment by matt-bullock** [comment]
@rubyweb3 Mouse over simply changes the fill colour of the button to #302F36 (hover state). Then  clicking will open the menu. This should be the same behaviour for all dropdowns. It should be clear from the image I posted above but let me know if not
