### ISSUE TITLE
ORDER TICKET SUMMARY: Update typography so label styles are the same

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5618]
Image from build (settlement fees and profit less fees are in all caps whilst max profit and max loss are in lower case):
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/9e55bbd6-028e-442d-a41b-9c2a2649e48d)

Please check each typography weight and size and align with design
https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=3187%3A19884

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/2be7b483-c1fe-46c3-bb8d-8f5ac3737570)

**Comment by matt-bullock** [comment]
Settlement Fee, Est. TX Fee, Profit Less Fees are still in all caps.  Please make same case style as max profit and max loss

Image from build:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/4076cde2-d230-4310-a634-b6572a0cbe5d)

**Comment by JohnDanz** [comment]
can you adjust this @rubyweb3 as well as finish off this https://github.com/AugurProject/augur/issues/4731 ticket. I should have some betting ui tickets for you after tomorrow -- sorry taking me longer than I thought to get the colors done and I want them in place so we can start building some of the smaller components / work on updating things that are shared to use the proper style

**Comment by matt-bullock** [comment]
looks good. closing
