### ISSUE TITLE
Market Creation Prompts

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#562]
UI should probably have a bunch of "are you sure" style things and prompts to discourage creation mistakes. Otherwise they could get closed as indeterminate.

**Comment by thinkloop** [comment]
Joey any specific examples beyond checking value requirements/ranges throughout and a final confirm step at the end?

**Comment by joeykrug** [comment]
Make sure user provides a description

Make sure user is prompted are you sure if they didn't put a resolution source

When they confirm prompt them to make sure they leave no ambiguity in their description

**Comment by thinkloop** [comment]
> Make sure user provides a description

done - can't proceed without it

> Make sure user is prompted are you sure if they didn't put a resolution source

done - can't proceed without selecting generic source or providing specific source

> When they confirm prompt them to make sure they leave no ambiguity in their description

ok - maybe solved with more/better msg'ing but could look into an additional prompt to communicate the importance of it

**Comment by tinybike** [comment]
Closing this as market creation is pretty prompty now.  Feel free to re-open if more prompts are needed / desired...
