### ISSUE TITLE
Consider Moving to Infinite Scrolling & Load More

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#562]
Consider moving to infinite scrolling instead of pagination site-wide (on pages with multiple pagination, use load more button)
...

I like this
 -joeykrug

**Comment by joeykrug** [comment]
Hmm actually, I like how it is now because links work way better, can link to a specific page, not really as doable w/ infinite scroll. Google + Amazon still use pagination for a reason. Trying to get rid of issues that aren't really important / clear junk out, reopen if you feel strongly /shrug
