### ISSUE TITLE
Add copy to tooltips in market visibility section of MC

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5624]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/19a57380-af8b-4759-88b9-679b7626eefc)

**Default spread filter check copy:** Displays markets based on how much liquidity there is available under a 15% spread

**Market ranking copy:** Shows how your market will compare to all other markets

**Comment by Chwy5** [comment]
@andrewdamelio Did you add this already?  Don't see it on local

**Comment by Chwy5** [comment]
in closing
