### ISSUE TITLE
Update any URL's to link to the help centre

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5626]
@petervecchiarelli 

Currently there are 'learn more' links in the trading app that are not pointing to the right URL. When the help centre is ready to go, dev will need to update these URLs in the trading app to point to the right pages.

**Comment by petervecchiarelli** [comment]
All Learn More links and locations are in here:

https://docs.google.com/spreadsheets/d/1UHaFfDF9LBNgDcQx4U9ZyQXW8F6OD0MQfnpAvt_O0JI/edit#gid=603506167

**Comment by Chwy5** [comment]
everything looks synced up to the correct spot - closing
