### ISSUE TITLE
Betting View Changes

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#563]
<details>
 <summary>Old ticket description</summary>
![user-images.githubusercontent.com&#x2F;11491365&#x2F;49554163-d1587280-f8af-11e8-8fbf-ad915ebaf5af.png](https://)

Replace trade w/ bet and change the price to odds. Allow people to switch between American, fractional, and decimal odds.

![user-images.githubusercontent.com&#x2F;11491365&#x2F;49554176-dae1da80-f8af-11e8-8cc7-69fe7be28d2e.png](https://)

Quantity should go to amount, price should be odds.

![user-images.githubusercontent.com&#x2F;11491365&#x2F;49554204-f351f500-f8af-11e8-8a73-8f7e08fd8e56.png](https://)

There should be no order book or depth chart, just a price history line chart + the order book as we see below with bet + lay, that's what bettors expect to see.

Buy/sell is instead back / lay. The betting ticket can be used for the initial liquidity provisioning page for markets too

My open orders, transactions page, and positions page I've thought less about but transaction pages from betfair, open orders, and positions pages from betfair are below:

![user-images.githubusercontent.com&#x2F;11491365&#x2F;49554220-0bc20f80-f8b0-11e8-89cc-9427a9164ad2.png](https://)

![user-images.githubusercontent.com&#x2F;11491365&#x2F;49554228-1381b400-f8b0-11e8-850a-bed7c9f7e7da.png](https://)

![user-images.githubusercontent.com&#x2F;11491365&#x2F;49554233-1b415880-f8b0-11e8-9bf9-5ca00ed97f0b.png](https://)

https://www.youtube.com/watch?v=n36TrNC3yqs also good video if people aren't familiar with betting to learn.

</details>

**Comment by pgebheim** [comment]
Ancient
