### ISSUE TITLE
Add d(days) h(hours) m(minutes) s(seconds) to countdowns

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5631]
Currently looks like this which isn't so clear:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/0d457021-7b3d-453f-accc-d1b6df695f84)

Adding the extra info helps:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/48304b9f-609f-4f4b-a1cb-ddfcaee9a3da)

@Chwy5 to confirm whether we need to display seconds

**Comment by Chwy5** [comment]
@bthaile @joeykrug What did we decide with the countdown timer? Do we only want to show to minutes? or to seconds?

**Comment by joeykrug** [comment]
for everything except open orders, days minutes seconds
for open orders, minutes above 5 min, otherwise seconds?

**Comment by bthaile** [comment]
@Chwy5  is this absolutely needed for V2 launch?

**Comment by Chwy5** [comment]
pushing to post v2....

Should Be worked post
