### ISSUE TITLE
Filter menu changes - Desktop only

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5633]
- [ ] Hide Filters by default

- [ ] Add down/up button 8px to the right of 'Filters'. Down when closed,  up when open.

- [x] Show 8 categories under 'All Categories' - to fill the empty space

- [x] Augur Templates selected by default

Closed  (default) https://www.figma.com/file/GKhft5ZOwuH3ANrupGNCLHUU/Market-list-page?node-id=1544%3A541

Open: https://www.figma.com/file/GKhft5ZOwuH3ANrupGNCLHUU/Market-list-page?node-id=1682%3A140621

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/0627d337-dc0c-4e2e-b217-95b409036111)

**Comment by phoebemirman** [comment]
where do the sort by options go? @matt-bullock  

<img width="361" alt="Screen Shot 2020-02-11 at 4 21 07 PM" src="https://user-images.githubusercontent.com/6775839/74291690-91c6bb00-4cea-11ea-9189-2d64e929d2e3.png">

**Comment by matt-bullock** [comment]
Just to clarify this is for desktop only. It was later decided we wouldn't change mobile so it wouldn't affect the sort by options

**Comment by Chwy5** [comment]
closing
