### ISSUE TITLE
Market Template Date picker in Market Question Lets me put in a passed date

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#5646]
Today is Jan 22, 2020, when I use the templates (in the market question) the date picker allows me to select yesterdays date....Should Only allow today or in the future

**Comment by Chwy5** [comment]
Still noticing I can do the day before on some templates...this is an example of Stock in date range (2nd yes/No template)

![1-29er.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/674467a0-e891-43ba-8098-d21b631d29d1)

**Comment by phoebemirman** [comment]
not reproducing that at this time but will keep an eye out on it
