### ISSUE TITLE
No history if sell all your shares

### ISSUE THREAD

**Issue by housemobile** [AugurProject/augur#565]
I had a bunch of Villanova wins NCAA March Madness shares. After they won the price quickly shot up to 1.00. Rather than wait for reporting, I sold all my shares. 

Nowhere does it show any details of me and this market. I got the cash from the sale, but would be nice to see a record of my buy/sells.

**Comment by thinkloop** [comment]
@tinybike are there facilities to pull past closed positions atm?

**Comment by joeykrug** [comment]
You can get past trade logs

**Comment by tinybike** [comment]
@thinkloop getAccountTrades should pull all trades, whether the positions are closed or not.

**Comment by tinybike** [comment]
Fixed in AugurProject/augur.js@bb5c32b1b1984280470b78e10de03e4a8bc0fd60.
