### ISSUE TITLE
Need to only sign tx 1 time instead of multiple times (V2 improvement) when placing a trade

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#565]
When trading - the order book had:
0.3 bid for .15 shares,
0.2 bid for .1 shares
I entered an order on the order ticket to sell 1 at 0.1.  I was forced to sign 3 different txs...first sold the .15 shares, 2nd sold the .1 shares and the 3rd put an offer on the books to sell .75 at 0.1.

Users will expect to only hit the tx confirm one time.

@johndanz any comments to add.
...

Alex said there's not really anything we can do to reduce confirmations on the contract side. (The middleware already intentionally breaks this into smaller txs so miners will accept them with reasonable gas prices.) 

However, we could potentially add something to the UI when the user has a pending tx or when trading may cause multiple txs to occur.

@serena @mattbullock Can you please think about how we could improve the UX when there are multiple txs?
 -adrake33
...

:thumbsup: 
 -sharkcrayon

**Comment by joeykrug** [comment]
Subset of #592
