### ISSUE TITLE
Withdraw shares and complete sets in the UI so can use them in 0x relayers / augur relayers

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#566]
Share withdrawal should exist on the positions page
...

This seems to be something users would like to do. We have a issue/comment by one member that has already tried to transfer market share tokens.

Makes sense to add a transfer token mech. on the Portfolio Positions page. 
 -bthaile
...

@tomhaile @joeykrug  what would be needed on the UI level to make this happen? 
 -sharkcrayon
...

similar to the account ETH | REP withdraw, The user would need an easy way to withdraw market share tokens. They need to know the market share contract address. I think it's that simple, the other part would be in augur-node.

I think augur-node would need to pickup market share transfers so when the user transfers  market share the UI would show correct positions.
 -bthaile
...

 After talking with Austin, this sounds like a much more complex user experience, and I’m not sure we should be focusing on it now. 

 The steps a user would have to go through: 
-  Check that their wallet is 0x-enabled. 
-  Choose which market they want to withdraw shares for.
-  Choose which outcome they want to withdraw shares for. 
-  Withdraw the shares. 
-  View the token address for the particular outcome they withdrew shares form.
-  Load that token address into their wallet so they could see the shares.
-  Repeat this for any other outcomes they want to trade.

They would also need a way to import shares back into Augur.

 This is not a straightforward process and would need to be accompanied with a lot of explaining. Further, I suspect it’s not a common need - especially if this is what users have to go through to do it.

 Wouldn’t we just be better off building a 0x relayer into Augur? 

@achapman @chwy @joeykrug @tomhaile 

 -sharkcrayon
...

You don’t need to check that your wallet is 0x enabled - all Ethereum wallets support erc20 tokens

This would appear on the positions page

“View the token address for the particular outcome they withdrew shares form.
Load that token address into their wallet so they could see the shares.
Repeat this for any other outcomes they want to trade.”

Idk what this is all about. It’d just work without all this stuff on any relayer that supports augur markets

As far as building our own relayer, no, FF cannot operate a relayer.

I disagree that the UX is difficult here, it’s simply just adding a withdraw button next to your shares on the positions page where you can paste in an address to withdraw to, and then the shares are transferred to that address.

Additionally, if I transfer shares to my augur address, the augur UI should recognize that I have shares in a given market and display them in the UI. Whether we like it or not, users *will* do the second part of this so we need to be prepared for that at the least. Adding a withdraw button to fulfill the first part is just a simple logical next step to make things a non walled garden

We can’t simultaneously want UIs on top but also wall off our own default one imo

 -joeykrug
...

I agree with the points @joeykrug makes above.
 -nuevoalex
...

👍
 -sharkcrayon
...

We’ve already had a user transfer market tokens. 

We need augur-node to pick up these transfers and serve up the account’s positions. 
 -bthaile

**Comment by joeykrug** [comment]
Actually, user should be able to just bring their same wallet to any other relayer and use the same shares, since wallets are self custodial. So this is a non issue
