### ISSUE TITLE
MC: icon for the olympics category 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5662]
We need to add a category for olympics: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/975e8646-cb45-4c58-905f-9cf81471161e)

Icon: 
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=3392%3A0

This should be listed under Sports Category....

We can remove the Learn more section and add this

**Comment by matt-bullock** [comment]
looks good. closing
