### ISSUE TITLE
add ellipses to end of resolution details on mobile

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5665]
Currently isn't showing

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/42fdd45c-8a90-46b3-a760-05898a3ea38b)

**Comment by JohnDanz** [comment]
@Chwy5 this is harder to implement than it looks for some reason... let's push to post v2 and also we only show a dropdown arrow in this area if there is more details, which conveys there is more.

**Comment by Chwy5** [comment]
moving to post launch
