### ISSUE TITLE
Inform user their Position is Partially closed.

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#567]
The UI messaging exists for showing user a message when their Position is partially closed.  Need to re-architect.

These files need to be refactored so that state is updated correctly.
Selector:
src/modules/my-positions/selectors/close-position-status.js

Reducer:
modules/my-positions/reducers/close-position-trade-groups.js

processing file:
src/modules/my-positions/actions/close-position.js
...

@serena This might fit into your current design for Market Trading.

Need the verbiage of the message to show user when their order is partially closed.
 -bthaile

**Comment by Chwy5** [comment]
Wording for Partially filled orders should say:
For a Buy Order:  Bought (# of shares purchased) of (original order quantity) Shares of "(Outcome)" at (price)eth (eventually Dai)....... (For example)  Bought 2 of 7 Shares of "Patriots" at 0.45 ETH

For Sell Order:  Sold (# of shares Sold) of (original order quantity) Shares of "(Outcome)" at (price)ETH (eventually Dai)....... (For example)  Sold 3 of 7 Shares of "YES" at 0.53 ETH

**Comment by Chwy5** [comment]
Filled orders on the Portfolio pg will have a quantity column and a Quantity filled column to show this.  Allows user to see original order and partial fills of that order.
