### ISSUE TITLE
We don't show the total cost for each position in my positions / portfolio page

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#568]
...

@sprinkle Is it important to display this piece of info?  Is this included in the mocks?

...

I’m a little hazy on the reasoning behind this one as it was created so far back, but I _think_ the original intent here was to show the user how much ETH in total is currently locked into a position, in addition to the other metrics — currently there isn’t a simple way to see that — you have to do quantity * last price.  

This definitely falls into the ‘user aid’ category, thus eval for Peccary.

Not currently part of the mocks.

...

@serena When I talked to @chwy earlier today, he said this was something they had at Paradex.  If it's helpful, he can show you a sample of what it looked like.
 -adrake33

**Comment by Chwy5** [comment]
will be shown on portfolio pg positions section on redesign

**Comment by joeykrug** [comment]
Done
