### ISSUE TITLE
Trading pg Responsive design breakpoints

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#5692]
Need to make sure Any laptop, or tablet are displayed like Desktop version (and not mobile)

Mobile should be its own

**Comment by bthaile** [comment]
Need to have tablet use desktop view not mobile view. only mobile needs the very compressed view of market trading page.  Need to adjust breakpoints.

iPad is using mobile. it should be using desktop view.
![image](https://user-images.githubusercontent.com/3970376/73107611-dae1d700-3ec3-11ea-9b7e-cd67dabeb484.png)

example is iPad pro in landscape

![image](https://user-images.githubusercontent.com/3970376/73107649-f77e0f00-3ec3-11ea-8279-2c75bde63281.png)

**Comment by Chwy5** [comment]
The top screenshot is I pad pro in portrait and its using mobile (that needs to use desktop view as well)

**Comment by matt-bullock** [comment]
How are we going to handle **tablet portrait** if we can't stack the components which is needed to fit this view. The page won't compress down to this size and the mobile isn't suitable. If we use desktop it wouldn't be responsive and the user would have to scroll horizontally to view the page. Are there any other solutions?

**Comment by JohnDanz** [comment]
https://www.figma.com/file/og1llFtTU9l5F2hk5tKMxc/Responsive-Layouts?node-id=1%3A23005

**Comment by JohnDanz** [comment]
side note to myself: charts shouldn't minimize if we have a bunch of orders -- make sure responsive changes address this.

**Comment by matt-bullock** [comment]
iPad 768 portrait is breaking. Examples:

open orders, my fills, positions are bringing in mobile content 

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/bf896d3c-d141-4c0a-becb-89cfff3309cb)
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/0cea3097-d6b0-4f03-9345-e8a4f8829723)
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f6258ce8-1f9e-4a63-a923-42704244eb26)

Content is getting cut off on right side
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/61470e0f-21f5-4d4a-b706-eaf0fe23dcab)

**Comment by matt-bullock** [comment]
Content still getting cut off on the right  at 768. This is happening across the whole app at this size

Trading page:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/cc3062c8-876b-4292-b701-29a8e15fc9e8)

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/83c89199-3b85-4527-a104-97e21ccc24af)

**Comment by matt-bullock** [comment]
looks fixed
