### ISSUE TITLE
Show meaningful stats about REP profit loss

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#570]
I don't think this is being done currently. See ch9706 for original discussion.
...

Edit: Instead, let's focus on how we'd like to show users their "P/L" when it comes to REP.
 -sharkcrayon
...

If this is something we want to do, we'd need design.
@achapman interested in add REP P/L?
 -bthaile
...

If that's what @serena and @mattbullock think is the best way to display this sure!
 -nuevoalex
...

 I’m going to adjust the title to reflect this direction, and add it to our design to do list. 
 -sharkcrayon

**Comment by matt-bullock** [comment]
@Chwy5 whats your thoughts on this?

**Comment by joeykrug** [comment]
Rep out after a market or fork resolves minus rep in = pnl for that market. It should show cost basis (amount of rep put in), rep value at the end, and profit (value - basis) is my two cents

**Comment by Chwy5** [comment]
Yes this should be added....

It should be displayed in the reporting pg in the box w/ My Available Rep Balance (shared in both Disputing and Initial reporting pgs)

Include All-time Rep PnL
 (arrow direction) color code and % increase/decrease from previous change

**Comment by pgebheim** [comment]
This is now included on the reporting page designs

![image](https://user-images.githubusercontent.com/86010/64465387-49fb9200-d0c1-11e9-8e55-f8c1381a2e40.png)
