### ISSUE TITLE
Alert modal doesn't close when user click account button

### ISSUE THREAD

**Issue by rubyweb3** [AugurProject/augur#5705]
![Screen Shot 2020-01-27 at 12 29 22 AM](https://user-images.githubusercontent.com/58647954/73159803-3cf53480-409c-11ea-9a95-967791f98100.png)

Steps to reproduce:
1. Click alert button. Alert modal will appear.
2. Click account button, Alert modal won't disappear and account modal will appear. 

These modals are overlapped.

**Comment by JohnDanz** [comment]
@rubyweb3 feel free to fix this, we do this sort of things on other components. generally you want to attach a click handler that will see if you clicked off this menu while it's open and then force a state chance to opened: false or something along those lines.

**Comment by JohnDanz** [comment]
going to make this post v2 launch as it might have performance implications and is a minor issue in general. @Chwy5 @matt-bullock
