### ISSUE TITLE
Provide a way for users to claim REP/fees on the market cards in Portfolio:Reporting

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#572]
aaaaaaaaaaaaa requested allowing a more granular way to do claiming instead of the single Claim button on Portfolio:Reporting. He said there may be a number of reasons users might want to do this, such as wanting to claim only the biggest REP winnings as soon as possible so they can be put into another dispute as quickly as possible. (This would be for both v1 & v2.)

**Comment by matt-bullock** [comment]
I think we cater to this in the new claim modal. @Chwy5 can you close if no longer needed

**Comment by Chwy5** [comment]
added to both the reporting section and through notifications - in wireframes at the moment...

Is not being added to the actual cards

**Comment by pgebheim** [comment]
@Chwy5 -- Closing this as v2 designs do this through the notifications section and seems to be stablized.
