### ISSUE TITLE
Fix getPlatformActivityStats volume calculation

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#5731]
The current calculation is nonsensical. What we really want to calculate is the magnitude of taken orders in the given timeframe.

We can't just use the VolumeChanged logs because we only store the latest volume and growing that database would be prohibitive. So instead we will calculate the volume from the logs of taken orders. The logic is outlined in https://github.com/AugurProject/augur/blob/35a246ad2ec8b05cc9446c035653fe5358a37084/packages/augur-core/source/contracts/trading/FillOrder.sol#L579

Note the complete set value bit which means market num ticks is needed.

---

The original ticket for reference: https://github.com/AugurProject/augur/issues/1192

**Comment by pgebheim** [comment]
Wait can't we just summtbe volume changed per market? Volume changed is already stored per market.

**Comment by robert-e-davidson3** [comment]
That would work for the current but not historical stats. The API expects a time range.

The API's params:
```
  static getPlatformActivityStatsParams = t.intersection([
    t.type({
      universe: t.string,
    }),
    t.partial({
      endTime: t.number,
      startTime: t.number,
    })]);
```

If we can drop the time range then this will be very easy to calculate but I don't know how important that is.

**Comment by robert-e-davidson3** [comment]
N/A
