### ISSUE TITLE
Red Dot should disappear when notifications are read

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5734]
### Desktop:

Should only disappear when the user opens their account summary.

https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=635%3A29484

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e2432c20-5726-4b5e-9ad9-8f74b56f894b)

### Mobile:

Should only disappear when the user opens the  notification tab of account summary

**Needs to  appear in 2 places:**
** 1 - main menu**
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=12854%3A298319

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/78e33eaf-d840-4f9c-8d57-526270d66e7c)

**  2 -  sub menu**
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7404%3A275155

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/2ffcdd57-3df2-480a-8eb9-362b6798ba4d)

Details:

Circle: 4px x 4px
Color: #FD6266;
Placement: 4px to the right of Account Summary. Align top right with text. See below:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/9fa1f8fb-a529-40bd-bc00-f4425d1574d6)

**Comment by Chwy5** [comment]
looks good closing

**Comment by matt-bullock** [comment]
@Chwy5 The red dot isn't disappearing when I go to the account summary as  I would expect it to. The 'NEW' tags should should also disappear when the user leaves the account summary, even if they've not opened the notification.

For example if a user gets a notification about a dispute which they see in account summary but chose not to open, they don't want to forever see a red dot there and a NEW tag at the top of their notifications.

![Kapture 2020-02-12 at 11.42.41.gif](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/7e0c0e54-1cc0-4c92-bffd-3c9cbd180867)

**Comment by Chwy5** [comment]
main functionality is there for launch....remaining behavior fix can be don post launch
