### ISSUE TITLE
Remove DAI($) from order book spread and put dollar sign before figure

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5739]
See mock below.

Both desktop and mobile

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/05442d03-baf6-4bac-a720-f1fada1f3a5b)

**Comment by phoebemirman** [comment]
looks like this was done already
<img width="365" alt="Screen Shot 2020-02-10 at 12 07 43 PM" src="https://user-images.githubusercontent.com/6775839/74185680-f9eba300-4bfd-11ea-984d-56165bb66e3d.png">
