### ISSUE TITLE
Consider options for ordering Disputed markets

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#574]
https://github.com/AugurProject/augur-app/issues/213
...

@serena What do you think about adding different sorts in the dispute markets? The community member has some ideas.

I would like to add the same search for Market List for disputes page.
 -bthaile
...

 I like the idea of making the dispute view user-centric. I’ll revisit this when we redesign the dispute section, as well as after we redo the filters on the market list page because some of that can carryover. 
 -sharkcrayon

**Comment by Chwy5** [comment]
closing- added see ticket 1574
