### ISSUE TITLE
Charts: When hotloading if price history chart has data, the page will freeze

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#5749]
This is very consistent.

If you have a market that has any price history, and load it directly so that the hotloading code occurs,m the page gets into a nasty busy loop in high charts.

By removing the `this.buildOptions` in *either* componentDidMount or UNSAFE_componentWillMount the chart doesn't work but the page loads normally.

**Comment by Chwy5** [comment]
Not sure what I am reviewing .....Looks broken to me   Price history chart never loads

![2-11.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/c5361266-24d9-403d-b692-8a9e455d0702)

**Comment by JohnDanz** [comment]
I was able to get data -- the chart always rendered. I did discover another issue where positions/fills/trading history etc wasn't being loaded however. I don't believe the two issues are related so this particular issue can most likely be closed.

**Comment by Chwy5** [comment]
loading again...closing for now
