### ISSUE TITLE
Update icons on market cards that indicate if the user has activity on that market

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5758]
Icons appear to be old. These are the latest

https://www.figma.com/file/Do4qnkCNM8P7lwBmCdYZCS4X/Market-Cards?node-id=370%3A24

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/09b69529-341d-4ff8-bbdb-e2ce952e792d)

Need new logo for Augur icon

**Comment by Chwy5** [comment]
This needs to be added right before launch with new logo

**Comment by bthaile** [comment]
I can do this one now and we can have a rebranding ticket right before launch.

**Comment by pgebheim** [comment]
@bthaile -- Good call on pre-launch rebranding ticket

https://github.com/AugurProject/augur/issues/7052

**Comment by matt-bullock** [comment]
done. closed
