### ISSUE TITLE
Add two links to the help menu dropdown 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5763]
Four updates to the help menu
- Add "Submit feedback"
- Add "Community support" 
- Change the color of two of the dividing lines (see screenshot below) to break it up into logical groups of links that help users scan
- Update the text "Trading tutorial" to "View trading tutorial"

Desktop:
https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=689%3A329

Mobile: 
https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=1819%3A4165

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/9c977fdf-8da8-4887-945e-dcf3216a7161)

**Comment by petervecchiarelli** [comment]
Submit Feedback: https://github.com/AugurProject/augur/issues/new/choose

Community Support: https://discordapp.com/invite/STswGEF

**Comment by Chwy5** [comment]
added
