### ISSUE TITLE
Add REP info section into reporting form - My available rep balance, get rep btn and the initial reporter stake required

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5765]
https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=630%3A7049

This section is currently missing from the form

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/eeca63af-15a3-457e-a904-d27a34270957)

---

Mobile:

https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=793%3A978

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/34a08abe-95f5-49a9-a2c1-7fb780f4824f)

**Comment by bthaile** [comment]
It's there for disputing. 

Why have it there for open reporting, user doesn't need REP. 
Also 99.9% of the time user won't need REP for designating reporting. 

This isn't a high pri ticket. suggest closing it.

![image](https://user-images.githubusercontent.com/3970376/75175176-79e23480-56f7-11ea-9ac8-7c4ec63b6aa1.png)

**Comment by matt-bullock** [comment]
Yep this shouldn't be there for open reporting, it's only needed for the DR form but I'm not seeing on the DR forms - see screenshot from local below. @Chwy5 feel free to make this lower priority. User would benefit from seeing their REP balance and access to getting REP if they want to add pre-filled stake

![image](https://user-images.githubusercontent.com/39496225/75199471-7b494680-5763-11ea-94a3-9fa72ad9fcf0.png)

**Comment by Chwy5** [comment]
needed post launch
