### ISSUE TITLE
replace [insert outcome user is staking on] with the correct outcome when adding pre-filled stake

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5767]
Currently showing: [insert outcome user is staking on]

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/91ff5b16-2dfe-474a-81c3-dd541ae89b61)

**Comment by bthaile** [comment]
Component doesn't have access to selected outcome. Removing the bracketed text, don't want want to make many changes, risk averse.

**Comment by matt-bullock** [comment]
ok. Change looks good. closing.  

Created a new ticket to remove apostrophes that have made there way in since the last change 
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/4013f591-b126-491c-89b5-20bf157d2b92)
