### ISSUE TITLE
pre-filled stake input min max and clear buttons issues

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5768]
Build:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f829107a-d340-45bd-a4ee-8cb200910777)

Design:
https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=2328%3A961
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/7b116fa7-6808-48bc-b2b2-26685ec9071f)

Min button is missing

Max should say 'FILL DISPUTE BOND'

Min button and fill button left aligned. Clear button right aligned

**Comment by bthaile** [comment]
open reporting, I don't think there is a min for open reporting. I was able to open report with pre-fill REP of 0.01 and another open report with 0.0001 REP both were successful. 
![image](https://user-images.githubusercontent.com/3970376/75174391-1e637700-56f6-11ea-9125-f7b95e864e29.png)

**Comment by bthaile** [comment]
disputing looks correct as well. moving this to Feedback Needed. I think this ticket is done 

![image](https://user-images.githubusercontent.com/3970376/75174849-edd00d00-56f6-11ea-991e-aea1fca49d78.png)

**Comment by bthaile** [comment]
If you want a clear button create another Ticket. @matt-bullock

**Comment by matt-bullock** [comment]
@bthaile I'll close. If you don't think the clear button is necessary then leave it out
