### ISSUE TITLE
Reporting usability suggestions

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#577]
- Would be nice to be able to access the Claim All button from the reporting and/or dispute pages
- Would be nice for the participate button to be visible on the Reporting as well as the Dispute page
...

:thumbsup: 
 -sharkcrayon

**Comment by Chwy5** [comment]
Included in redesign

**Comment by pgebheim** [comment]
This is handled in redesigns, things appear in multiple places contextually

**Comment by pgebheim** [comment]
![image](https://user-images.githubusercontent.com/86010/64465446-9050f100-d0c1-11e9-954d-22b1277470bf.png)
