### ISSUE TITLE
clicking on username logs me out on dev site

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#577]

**Comment by tinybike** [comment]
This is intended behavior, but I think the intention should be changed...@thinkloop? :)

**Comment by thinkloop** [comment]
It's like augur1 except we display the handle instead of "logout", eventually there will be an account page linked from there, is it better for now to go back to "logout"?

**Comment by joeykrug** [comment]
I expected to go to an account page or nothing to happen, didn't expect to be logged out

**Comment by tinybike** [comment]
We're thinking of changing it to have this functionality: http://bit.ly/1SQOQG8
