### ISSUE TITLE
trading page doesn't show best ask and bid 

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#5776]
market trading outcome data not shown. 
1. bid and ask price info doesn't show
2. last traded price doesn't update if market is traded on.

![image](https://user-images.githubusercontent.com/3970376/73400960-cd579300-42af-11ea-9d72-41533b195861.png)

**Comment by bthaile** [comment]
@Chwy5  can you verify that this is fixed?

**Comment by Chwy5** [comment]
yes closing
