### ISSUE TITLE
distinguish between real contract invalid outcome and market maker's outcomes

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#578]
Add different Color and tooltip on real invalid in reporting and dispute page and market card.

Need design to contribute. We can add a quick stop gap, so users know on existing markets in dispute.
...

@serena @mattbullock Please take this into consideration when redesigning the market cards for the Reporting:Reporting/Reporting:Dispute pages.
 -adrake33

**Comment by Chwy5** [comment]
Market creators outcomes should all be displayed in one color

Augurs invalid should be displayed (everywhere) trading pg, market cards, reporting/disputing in another
