### ISSUE TITLE
Estimated gas fee missing from pre-filled stake and the total

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5784]
See screenshot:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/07e4ea90-6fa6-44a8-b4ca-1b6f81f5f200)

Design:
https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=2328%3A961

**Comment by bthaile** [comment]
@matt-bullock  adding two gas fees doesn't make sense. it's only one transaction. Can add one transaction fee. 

might as well update design.

**Comment by matt-bullock** [comment]
@bthaile ok  - when designing it I think we thought it was two transactions. Would it make sense to move the Estimated gas fee at the top to below total REP at the bottom?

**Comment by bthaile** [comment]
closing this ticket
