### ISSUE TITLE
Total rep in reporting form not calculating correctly 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5785]
Image from build:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/67008b79-9e13-409d-a312-861630d4d994)

The total at the bottom should show a combination of initial reporter rep + pre-filled stake rep. Currently it's only calculating the initial reporter rep

**Comment by bthaile** [comment]
incorrect, open reporting user doesn't pay REP. 
only need to show what pre-filled REP they are staking

**Comment by matt-bullock** [comment]
This isn't open reporting. This is from initial reporting.
It's showing 'open reporter winning stake' as an error which I've created a separate ticket for

**Comment by bthaile** [comment]
Ok, there is a terminology issue
As I understand 
Initial report is the first report on the market. It can be either designated reporter or open report.

Seems you are referring to initial report as designated reporter. Where I’m thinking that initial report is either designate or open.

**Comment by bthaile** [comment]
Also as I understand it designated reporter only needs to stake REP if they are not the market creator. If they are the market creator the no-show bond will be used as initial REP staked.

**Comment by matt-bullock** [comment]
Yes I meant to say Designated Reporter. The above screenshot is when I'm the market creator doing the initial report from designated reporting
