### ISSUE TITLE
Display REP decimals on Dispute Bond page more clearly

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#579]
The user `Diesel Augur` requested on Discord that we display the number of REP decimals more clearly on the Dispute Bond page. He gave an example of a dispute bond that appeared to be one attorep short of completion, but only shows 4 decimal places, and is unclear.

![unknown](https://user-images.githubusercontent.com/11491365/49620274-04186e80-f975-11e8-985d-dbd202559a18.png)

**Comment by adrake33** [comment]
@joeykrug suggested always rounding the first number down. We could do this, and if the user attempts to contribute more than is allowed, only contribute the max allowed. However, we would still need some way to convey to the user why the full amount they entered didn't get contributed.

Alternatively, it might be better to display how much REP is still needed to fill the bond as opposed to how much as already been contributed. We would still need a way to handle precision past 4 decimals, though.

**Comment by Chwy5** [comment]
We should round down, unttil the total bond is filled, but still provide an ellipse and hover to see full amount - so user knows exact amount needed to fill
