### ISSUE TITLE
Add footer links to beta2 UI

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#579]
![screenshot - 04162016 - 03 07 37 am](https://cloud.githubusercontent.com/assets/2637020/14580407/74f3dbb4-0380-11e6-8d82-27f71e24380c.png)

**Comment by thinkloop** [comment]
What's tomas' github username, doesn't seem to be popping up. I think he might be working on this.

**Comment by joeykrug** [comment]
@priecint is it

**Comment by priecint** [comment]
Fixed in AugurProject/augur-ui-react-components@54b53616f0e149a4651a89e8441097779f8b22db
