### ISSUE TITLE
Reporting Form - Scalar markets - Should show the min max and denomination on form

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5793]
screen shot from build:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e3e94dfd-d18e-4289-afc7-0e942ba3159d)

Design:

https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=793%3A900

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/efafba88-be15-4161-b8f4-e856e1e77b43)

Mobile

https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=793%3A978

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/06a4cc7f-5906-4c4d-b6af-b7d28f6e59d0)

**Comment by bthaile** [comment]
form does show min and max range on the outcome. I don't think this is a high pri item
![image](https://user-images.githubusercontent.com/3970376/73951944-fb4a6200-48c3-11ea-9027-0791fffd9b24.png)

**Comment by matt-bullock** [comment]
Didn't notice that. Would be good to get the details in the header but this can definitely go lower priority @Chwy5

**Comment by matt-bullock** [comment]
@bthaile If the min and max are long numbers, they're getting cut off at smaller break points and there's no way to see the full min and max values. We either need a tooltip on these or show the values at the top of the form

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/caae2c91-e21c-4edf-adbf-ee639fa263f8)

**Comment by Chwy5** [comment]
lowered priority

**Comment by matt-bullock** [comment]
closing
