### ISSUE TITLE
Pushing time doesn't trigger market reporting state change

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#5798]
on time controlled contract deploy. using pop or just uploading contracts using `docker:all false true`

pushing time so that a market reporting state transitions doesn't trigger a market updated event. so the UI has markets in wrong reporting state.

**Comment by nuevoalex** [comment]
@bthaile Is this still an issue? I recall you cleared site data and it resolved itself I think.

**Comment by nuevoalex** [comment]
@bthaile Is this still an issue?

**Comment by bthaile** [comment]
No longer an issue. Saw it work today
