### ISSUE TITLE
Redesign Transactions Page

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#580]
This encompasses a number of changes/additions to the Transactions page, including:

- Status of each transaction should be visible without having to click to open
- Github feedback: https://github.com/AugurProject/augur-app/issues/231
- Consider transactions order and sorting: ch14594

**Comment by joeykrug** [comment]
Data export should export a csv btw, atm we do a json iirc but people want csv

**Comment by Chwy5** [comment]
duplicate ticket - closing
