### ISSUE TITLE
Tooltip needed to be added next to pre-filled stake amount on dispute form

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5803]
Add tool tip and add text:
Users can add extra support for a Tentative Winning Outcome

Build:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/5bb9c018-bf6f-47a4-b734-6e28041d1904)

Design:

Add this into a tooltip:
Users can add extra support for a Tentative Winning Outcome

https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=3665%3A18348

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e39d69d1-9724-4a8f-8aea-47970c0f6c90)

**Comment by bthaile** [comment]
need tooltip text if going to add (?) next to `Pre-Filled state`

**Comment by petervecchiarelli** [comment]
"Users can add extra support for a Tentative Winning Outcome by pre-staking REP that will be used to dispute in that outcome’s favor in the event that is no longer the Tentative Winning Outcome. Pre-filling can help accelerate a market’s resolution.

Pre-filled Stake yields ROI if and only if 1) the market resolves to the staked-on outcome and 2) the pre-stake ends up being used to dispute in that outcome’s favor. If the market resolves to the staked-on outcome but the pre-stake is not used, you will receive back the pre-stake but no ROI. If the market does not resolve to the staked-on outcome, you will lose the pre-stake."

Or could just use 1st half.

**Comment by Chwy5** [comment]
1) On disputing market card, next to pre filled (?) tooltip
"Users can add extra support for a Tentative Winning Outcome"

2) We need to add text below to the disputing quick guide 

3) @petervecchiarelli we need to add this to the disputing explained section in the help center docs: 

Pre-filled Stake
"Users can add extra support for a Tentative Winning Outcome by pre-staking REP that will be used to dispute in that outcome’s favor in the event that is no longer the Tentative Winning Outcome. Pre-filling can help accelerate a market’s resolution.

Pre-filled Stake yields ROI if and only if 1) the market resolves to the staked-on outcome and 2) the pre-stake ends up being used to dispute in that outcome’s favor. If the market resolves to the staked-on outcome but the pre-stake is not used, you will receive back the pre-stake but no ROI. If the market does not resolve to the staked-on outcome, you will lose the pre-stake."

**Comment by matt-bullock** [comment]
I'm seeing the REP denomination in but shall we keep this ticket open/rename it for adding the tooltip? @Chwy5

**Comment by Chwy5** [comment]
yes I updated

**Comment by Chwy5** [comment]
added - closing
