### ISSUE TITLE
'NaN' appearing instead of 0.0000 in amount of rep staked - disputing form 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5804]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f18ae346-cbad-4249-ab57-1abc5f59aee5)

**Comment by phoebemirman** [comment]
i'm not seeing this. do you have repro steps @matt-bullock ?

**Comment by matt-bullock** [comment]
@phoebemirman Enter a REP amount then clear the input. Although previously it was showing up as NaN by default if there was 0 REP already staked.


![image](https://user-images.githubusercontent.com/39496225/74194118-f33e4980-4c58-11ea-8c3d-38c4168466ec.png)

**Comment by phoebemirman** [comment]
ok i see that now

**Comment by matt-bullock** [comment]
Not seeing this now. closing
