### ISSUE TITLE
Transaction page wording should be clarified

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#581]
I think there needs to be a differentiate between opened orders and filled order terminology.....

I would suggest when a user places an open order the words sell or buy be used: (an example) Sell 2.5 shares @ .4 or Buy .5 shares @ .15

I would suggest using the terms Sold and Bought for filled orders: (an example) Sold 2.5 shares @ .4 or Bought .5 shares @ .15

**Comment by joeykrug** [comment]
Already in redesigns
