### ISSUE TITLE
in reporting tab: warning somewhere of deadline to submit ballot. maybe here...

### ISSUE THREAD

**Issue by pqdeep** [AugurProject/augur#581]
![2](https://cloud.githubusercontent.com/assets/13311619/14580727/727ea8ee-03d7-11e6-829e-e86197d36968.jpg)

**Comment by thinkloop** [comment]
good idea

**Comment by thinkloop** [comment]
@joeykrug @tinybike reporting deadline is always at the end of the current month correct (regardless of month length, etc., if a market is supposed to be reported on)?

**Comment by joeykrug** [comment]
Commit deadline is 30 days. Reveal deadline is 28 days. 2 days to appeal a decision then it starts over again.

**Comment by joeykrug** [comment]
And not always at the end of current month

**Comment by tinybike** [comment]
Added as the "progress bar" component
