### ISSUE TITLE
Advanced Order info doesnt clear out of order ticket after placing an order/trade

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#5813]
create an open order and use the advanced order to set a time for expiration. After order goes onto the book....those filters dont clear out

**Comment by bthaile** [comment]
can wire up `clear` button to clear order form advanced section.  We'd need to refactor how trading form is organized to make this work. I don't want to put in a hack just to clear advanced section of order form. 

Will talk over with other devs.

**Comment by Chwy5** [comment]
if this isnt easy to solve we can push this to post

**Comment by bthaile** [comment]
not easy to solve, push to post. The clear button in order form will now clear Advanced section

**Comment by Chwy5** [comment]
closing - hitting clear resets it and also leaving the pg and coming back resets it....will require major refactor to do
