### ISSUE TITLE
Error message (similar to orphaned orders) should appear upon sign on _ yellow message

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#582]
In the event of pre-liquidity orders not being submitted, a yellow message (similar to orphaned orders) should appear on the top of the screen.  A user should be able to click on this link bringing them to the page to cancel or sign all the unsigned orders.  Would recommend showing this message everytime a use signs on, until orders are cancelled or signed.

@johndanz plz add any thoughts

**Comment by Chwy5** [comment]
this is changed for the redesign...will get a notification and can either be closed in the modal or on the trading pg itself
