### ISSUE TITLE
Make rows correct height in initial liquidity  so that cancel buttons don't overlap

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5825]
Build

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/851f2244-fefc-45cc-acf7-2f71a9e98a6f)

Design

https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=3050%3A915

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/1d5a8c97-69aa-43e1-a69e-c993bff3c516)

**Comment by Chwy5** [comment]
looks better closing
