### ISSUE TITLE
spacing issue on inputs when disputing scalars 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5827]
Degrees Fahrenheit denomination looks like it's  linked the REP input. Refer to design for correct spacing

Build:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/b46f2246-3bda-49c0-9689-4e92f0aafc32)

Design:

https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=536%3A4391

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/5e67ee1e-edc0-4fb1-95af-695df17c386e)

**Comment by Chwy5** [comment]
closing - fixed
