### ISSUE TITLE
Invalid Outcome bid on scalar market needs to display in red above the threshold

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#5828]
(same behavior we do for binary and multiple choice)

https://cdn.discordapp.com/attachments/464067340015763466/672833972031455232/Screen_Shot_2020-01-31_at_11.01.21_AM.png

**Comment by bthaile** [comment]
this has been fixed. created order at 15% and get the red label. tested on local evn. Kovan might need new contracts. I've not been able to create orders on scalar markets.

![image](https://user-images.githubusercontent.com/3970376/74259232-33cfae80-4cbd-11ea-9ae7-46de6f2948fd.png)

**Comment by Chwy5** [comment]
Trades are failing when I try to enter an order for invalid on scalars

**Comment by bthaile** [comment]
After talking to Alex, it seems to be a contract issue. same as my comment above. I'll see when new contracts are updated.

**Comment by Chwy5** [comment]
closing
