### ISSUE TITLE
Investigate external smoke test for dev.augur.net

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#583]
Can you investigate if site24x7 browser tests can wait until JS is loaded and check for an elements existence?

Or, perhaps our browserstack membership can provide alerts.

Ultimately we will want full integration testing re: 8527

Gave this 2pts. Adjust before beginning if you think differently
...

@pgebheim we investigated using selenium before, but came up empty handed.  Will look into other solutions
 -petong
...

I think we could do this now with the internal Jest tests -- where we prune them down enough that they operate as a smoke test.
 -pgebheim

**Comment by robert-e-davidson3** [comment]
My thought is we write the smoke test using jest and puppeteer.

For CI and local testing, we can use ganache and the SDK to setup the test environment.

For testing against other environments, we can potentially use the SDK but we may need to use different but similar smoke tests for each environment. My concerns are account specification (which private keys), fauceting, and our limitations on mainnet (read-only, right?).

This is out of scope for this ticket though.

**Comment by robert-e-davidson3** [comment]
@andrewdamelio has ghost inspector running against dev.augur.net. I think that's fine for external testing.

For CI we need to use puppeteer or similar since ghost inspector only works on constant, external endpoints.
