### ISSUE TITLE
Sort by: volume (descending order) should be default

### ISSUE THREAD

**Issue by pqdeep** [AugurProject/augur#583]
Baz says can't make it default without changing backend because markets will thrash around during load. Any way to address this? Other ways to minimize user exposure to spam markets and encourage concentration of volume?

![4](https://cloud.githubusercontent.com/assets/13311619/14580746/f30558c8-03d7-11e6-8836-55d41ba5c246.jpg)

**Comment by thinkloop** [comment]
Changed to volume for now even tho back-end not updated, see how it feels

**Comment by tyche78** [comment]
This is mildly annoying right now. Until the backend changes, I suggest reversing back to a sort by last created.
