### ISSUE TITLE
Unable to place an order on scalars

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5830]
Keep getting this message

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/a7834747-1762-4ddf-a9e0-9be43db2951b)

**Comment by bthaile** [comment]
![image](https://user-images.githubusercontent.com/3970376/74856674-1ecfcc80-5308-11ea-8d4c-c9a5037c5e03.png)

**Comment by bthaile** [comment]
![image](https://user-images.githubusercontent.com/3970376/74856785-4d4da780-5308-11ea-8495-709c1e56d464.png)

**Comment by bthaile** [comment]
made some code changes. need to re-test

**Comment by matt-bullock** [comment]
It's working for me now

**Comment by Chwy5** [comment]
closing
