### ISSUE TITLE
raise font size of ".market .outcomes .outcom" css class. 

### ISSUE THREAD

**Issue by pqdeep** [AugurProject/augur#584]
maybe to 1.4rem? maybe reduce line-height a bit as well

realize we dont want interface to look cluttered, but current font-size of probabilities might be hard to see, at least on my screen. Screenshot at resolution 1920 x 1080:

![a](https://cloud.githubusercontent.com/assets/13311619/14580757/6a201ea2-03d8-11e6-8b73-f952d35cdfaa.jpg)

**Comment by pqdeep** [comment]
font-size of ".transactions .page-content .transaction-item .description .market-description" class looks a bit small too

![5b](https://cloud.githubusercontent.com/assets/13311619/14580767/eced5584-03d8-11e6-8432-6b1f48f0a500.jpg)

**Comment by pqdeep** [comment]
font size of ".transactions .page-content .transaction-item .description .market-description" css class also a bit small

![5b](https://cloud.githubusercontent.com/assets/13311619/14580775/4cadeb3c-03d9-11e6-9f30-2db27cc2e320.jpg)

**Comment by thinkloop** [comment]
Increased size of fontts
