### ISSUE TITLE
Trading: need design for User to easily put in valid order quantity into form.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#5842]
Depending on the Scalar market min quantity varies. Need an easy way for the user to paste in a valid Quantity near the quantity they have entered already. Currently there is a error that gives the user the Quantity has to be a multiple of value and a “try” value which is the nearest valid value to what they typed in the order form.

Scalar markets might have a multiple of value of 1, .1, .01, .001, ...
Depending on the scalar market min/max price

**Comment by Chwy5** [comment]
Why does it need to be that?  That is a non doable request.....can't make a user enter some crazy quantity (like a multiple of .076).   Scalars are a new concept to most and we cant add something like that in.....Need to find a way so the user can enter some real number.

**Comment by bthaile** [comment]
@Chwy5  the above is a placeholder. We need a design that will allow the trader to understand valid quantities and allow them to easily update quantity. 

It's similar process if the user was to put in price and total order value. Except we need to give them easy valid quantities. No matter what we do currently Quantities for scalars are weird. 
Need to educate the trade, imo

Or price of google I want to buy 10 shares @ 1450...not some weird amount that i am forced to do

**Comment by Chwy5** [comment]
Educating wont solve this problem....we ahva bunch of templated markets Like Number of wins in a season, Total number of points scored in game, price of stock, etc.

IE # of wins NY Yankees will finish regular season with (min/Max 0 -162)....As a use I want to buy simple numbers....buy 1 share at 105 (105 wins)....not buy .76 of a share at 105....we need to fix this so we can use real whole numbers in quantity

**Comment by bthaile** [comment]
Going a different direction. Going to round up min quantity for scalar markets. UI will update formula after contracts are updated. Closing

**Comment by bthaile** [comment]
Reopening ticket, weird scalar quantities have been addresses but having an easy way for users to update order quantity would improve UX

**Comment by matt-bullock** [comment]
Design: https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=3516%3A695

Design showing hover state for quantity buttons in error message: https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=3530%3A1

Had to create a new white outline button for this as none of the existing buttons are designed to work on a red background 

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/7164501d-f4e9-487c-9b83-37d7b9e07b92)
