### ISSUE TITLE
ledger users should not be able to sign in when they have contract data turned off

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#585]
i think this used to work previously

saw in issues channel user bsninjagoalie was having ledger issues because of this

**Comment by bthaile** [comment]
confirmed: UI does allow user to connect even though contract data is off.

This error when trying to create and sign tx.

![screen shot 2018-12-04 at 11 34 33 am](https://user-images.githubusercontent.com/3970376/49461104-96274800-f7b8-11e8-8574-f2b80f18cff6.png)

We need to detect contract-data is off. haven't been able to find a api call to detect if contract data is on.
