### ISSUE TITLE
ZeroXTrade doesn't actually return funds

### ISSUE THREAD

**Issue by samczsun** [AugurProject/augur#5852]
https://github.com/AugurProject/augur/blob/dbcd5ea6281a5e0d9f99ad86bd1e4dc163ea5c52/packages/augur-core/source/contracts/trading/ZeroXTrade.sol#L275-L277

You probably want `msg.sender.call.value(address(this).balance)("");`

**Comment by nuevoalex** [comment]
@samczsun would you mind submitting this as a bounty using our hackerone program: https://hackerone.com/augurproject
