### ISSUE TITLE
Outcomes for Football (Both NFL and NCAA) templates with (week #) vs the spread are broken

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#5856]
See attached screenshot...

![2-2.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/8393596d-1952-486e-86e5-79788e44c9d4)

**Comment by bthaile** [comment]
looks good to me. moving to Product Review

![image](https://user-images.githubusercontent.com/3970376/74353609-c9cc0d80-4d7f-11ea-8128-5af5cadde81f.png)

**Comment by Chwy5** [comment]
looks good closing
