### ISSUE TITLE
menu doesn't close when clicked outside

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#5858]
clicking outside the `Popular Help Resources` doesn't close it.

![image](https://user-images.githubusercontent.com/3970376/73612984-98e91d00-45b6-11ea-8fbe-6b028c45463d.png)

**Comment by phoebemirman** [comment]
are we sure we want this? the account dropdown doesn't have this behavior either

**Comment by bthaile** [comment]
ok, then need to close it when user clicks on an item in the menu.
