### ISSUE TITLE
positions page: column misalignment

### ISSUE THREAD

**Issue by pqdeep** [AugurProject/augur#586]
should columns be consistently aligned? word-wrap long titles within fixed width (%?) limits. reduce width of position column to accommodate long market titles and apply fixed (%) width there too?

![8](https://cloud.githubusercontent.com/assets/13311619/14580803/478fc5b6-03da-11e6-80c6-ade0fdff651a.jpg)

**Comment by thinkloop** [comment]
In the process of being designed, otherwise absolutely yes what you said.
