### ISSUE TITLE
Initial reporter stake and pre-filled stake should be totalled up at the bottom

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5869]
Build

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/1f5d454b-1c7a-4292-b80b-258ff3e0fca5)

**Comment by bthaile** [comment]
this is incorrect. 

open reporting the user gets REP doesn't stake REP. 
they can stake pre-filled, but that shouldn't be added to REP user is going to get. 

for designated reporting the REP amounts need to be summed.

**Comment by matt-bullock** [comment]
@bthaile the above is a screenshot from designated reporting. It's saying 'open reporting winning stake' for some reason but this is an error and I've created a separate ticket for that.

I've just gone through it again to double check and this what opens from my Designated Reporting 

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/4b448c8f-bc78-41c5-b621-2dfbff2c24b1)
