### ISSUE TITLE
Support Non-Debian distributions of Linux

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#587]
https://github.com/AugurProject/augur-app/issues/234
...

@tinybike How high of a priority is it to support non-Debian distributions of Linux?
 -sharkcrayon
...

Pretty low.  IMO anyone running non-debian Linux distros is relatively likely to be comfortable building from source.  Setting up a ppa so Debian/Ubuntu users can install via apt-get is quite a bit more important IMO!

...

> Setting up a ppa so Debian/Ubuntu users can install via apt-get is quite a bit more important IMO

@tinybike Do you know if there's a ticket for that already?
 -sharkcrayon
...

No there isn't, please create one

...

:thumbsup: ch14579
 -sharkcrayon
...

:thumbsup:

**Comment by joeykrug** [comment]
Augur has appimage now
