### ISSUE TITLE
Disputing quick guide learn more button needs to link to the correct page in the help centre

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5874]
Currently doesn't go anywhere

**Comment by Chwy5** [comment]
Still going to the wrong doc

**Comment by phoebemirman** [comment]
whats the link for the right doc @Chwy5 ?

**Comment by Chwy5** [comment]
https://augur.gitbook.io/help-center/disputing-explained

To the disputing pg in this doc...this is what we will be  using for the help center

**Comment by Chwy5** [comment]
fixed - closing
