### ISSUE TITLE
Message on ROI is missing when inputting pre-filled stake

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5886]
Should appear once the user enters an amount:

Design: https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=231%3A60628

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/48caeba0-4eec-4a15-afe5-1c481e96a36f)

**Comment by Chwy5** [comment]
@matt-bullock  Need to define what ROI IS....Most people what not know what that means
