### ISSUE TITLE
Show users existing pre-filled stake contribution when a user wants to add more 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5888]
When a users adds pre-filled stake to an outcome they have previously added pre-filled stake to, their previous contribution appears to be missing

Design:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/028c7f1f-5076-4ab3-b17c-fd17801ccca7)

https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=1025%3A0

**Comment by Chwy5** [comment]
moving to post launch - we should do this

**Comment by matt-bullock** [comment]
This is in. closing
