### ISSUE TITLE
Participation tokens learn more needs a link

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5889]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/b8d05281-9427-4b8b-8191-8a29abd81f0e)

Waiting for Peter V to finish this section of the help centre first

**Comment by petervecchiarelli** [comment]
Can link here:

https://app.gitbook.com/@augur/s/help-center/reporting-or-disputing-faq#what-are-participation-tokens

**Comment by matt-bullock** [comment]
links in
