### ISSUE TITLE
Request: Fiat Prices

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#589]
https://github.com/AugurProject/augur-app/issues/86
...

Would need support for multiple different currencies.
Need live feed support
Recommend doing after V2, as (i.e eth/usd is very different from exchange to exchange).
May not be needed with creation of Dai.
 -Chwy5
...

We would need to have a site wide conversions or we could have a tooltip.

@serena What about the idea of having a hover tooltip that gives full precision and give value in currency. We'd probably only support USD initially but could add currencies as we add price feeds.
 -bthaile
...

This should be done post-v2.
 -adrake33

**Comment by joeykrug** [comment]
Not needed with Dai
