### ISSUE TITLE
When a user adds more stake to a bond that already has that users stake, their stake should be represented by a different color in the bond progress indicator 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5891]
Build:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/bad0a3b8-2994-43ad-ad42-bddde02046fd)

Design:

https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=558%3A6486

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/398472e4-6e68-4d75-9f9a-cfef16848bac)

**Comment by Chwy5** [comment]
should add post launch
