### ISSUE TITLE
Expired timestamp should show the date the market expired

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5892]
Where this needs updating: My Created Markets in Portfolio

Build:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/ca299f21-4870-4903-84b5-2959761abb92)

Design:

https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=2640%3A29211

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/a2a1762e-66b4-4f8b-9b72-b7311a7b5035)

**Comment by Chwy5** [comment]
fixed - closing
