### ISSUE TITLE
Add finalize market to market page if I'm the market creator

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5894]
Although the MC can finalise from the notification, if they decide to click on the market first it's missing the finalize button

Design:

https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=3533%3A0

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/b72ccfb6-39a1-4372-b292-73326c25376f)

**Comment by Chwy5** [comment]
closing - not needed
