### ISSUE TITLE
Add "Creation date: xx" under "Ends (date): xx" as market meta? 

### ISSUE THREAD

**Issue by pqdeep** [AugurProject/augur#590]
There's a currently expired question that highlights need for this:
"Will Bitcoin's price drop below $410 USD at any time before April 9, 2016 12:00am GMT (Coinbase)"

I didn't have a quick way of knowing what time period the market creator was referring to. Needed a start date to answer the question, ideally without leaving the tab and losing my place in the ballot (although I noticed later the UX handles this gracefully -- when you get back to the main dash and click the reporting tab, the list starts off with the last market you hadn't finished reporting on). 

Unable to click open any market after it's expired to get this additional detail.

**Comment by tinybike** [comment]
Suggestion: add this as a mouseover display.

**Comment by tinybike** [comment]
Added
