### ISSUE TITLE
Feature Request: Manually choose Data Folder

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#590]
https://github.com/AugurProject/augur-app/issues/182
...

@achapman Is setting user own data dir a feature we want to offer in augur-app?
 -bthaile
...

Seems reasonable to me as something in a hidden away setting for advanced users. Low priority though.
 -nuevoalex
...

Assigning to Serena/Matt for design consideration.
 -adrake33

**Comment by adrake33** [comment]
Original issue is #343

**Comment by joeykrug** [comment]
In v2 it'll be in the browser anyways and not choosable, I wouldn't spend time on it
