### ISSUE TITLE
reporting: all reports were "pending" for more than a half-hour after completing entire ballot

### ISSUE THREAD

**Issue by pqdeep** [AugurProject/augur#591]
#Is this supposed to be the case? I thought all committed votes were immediately sent to the blockchain after encryption for later reveal.

Edit: When I logged back in, all the reports were still listed as pending under the "Pending Reports" tab.

**Comment by tinybike** [comment]
I think this was an artifact of the node issues we had recently.  Please re-open this if this happens again.
