### ISSUE TITLE
Use Ethereum Alarm Clock to automate time-dependent actions

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#591]
Original discussion here: https://github.com/AugurProject/augur-app/issues/402.

Such actions to consider would be: 
  - Paying for transaction fees in Dai instead of ETH (requires account abstraction. Can be done using a proxy/identity wallet, so interactions with Augur and EAC are through that wallet and thus the wallet address is constant.)
  - Automating placing/canceling orders (also requires proximity/identity wallet)
  - Submitting Designated Reports (also requires proximity/identity wallet)
  - Submitting First Public Reports (requires support for EVM expressions as conditions. This has not been implemented yet, but more details can be found at: https://blog.chronologic.network/time-is-only-the-beginning-introducing-conditional-scheduling-with-chronos-protocol-76036e4daaad)

Need to discuss this more (particularly proximity/identity wallet).

**Comment by joeykrug** [comment]
closing to clean up issues unless we have a concrete use case
