### ISSUE TITLE
Design individual market display

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur#592]
A listed market has to show several pieces of information:

- description
- fee
- end date
- volume
- tags
- outcomes
- action button (trade, report, view)

Those are the base properties, additionally, markets can be related to the user in various ways that need to be reflected:

- owned positions (num shares, gain/loss, etc.)
- open orders (num shares, price, etc.)
- market was created by user (fees collected, gain/loss, etc.)
- market is pending user's report
- market reported on by user (show which outcome reported, unethhical)

**Comment by joeykrug** [comment]
done
