### ISSUE TITLE
date created showing wrong year on market trading pg

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#5922]
shows year as 4896

![Screen Shot 2020-02-05 at 11.31.02 AM.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/70216832-ca5b-4d0c-9da2-f2ed4b66a0ba)

**Comment by bthaile** [comment]
this has been fixed, moving ticket to Product Review

**Comment by Chwy5** [comment]
not seeing this anymore - closing
