### ISSUE TITLE
Logo clashing with menu button on smaller phones (iPhone 5/SE)

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5924]
Need a solution to this post launch. Could remove logo on phones this size

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/b05338af-f765-4679-beaa-00803047f372)

**Comment by joeykrug** [comment]
need before

**Comment by joeykrug** [comment]
didn't notice this was iPhone 5, closing
