### ISSUE TITLE
saved market needs to disappear in market creation

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#5925]
If I save a market I was creating in market creation.....then go back into it at a later time and finish creating it....the saved market still remains at the top of market creation...

it should disappear since i created it

**Comment by bthaile** [comment]
I disagree with auto deleting saved drafts.  I think that will confuse the user.

**Comment by Chwy5** [comment]
makes sense to keep if you want to use the same format over and over and just change date/ price or team....closing
