### ISSUE TITLE
Open orders, unsigned orders & claim proceeds modals don't have a close button

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5932]
Open orders, unsigned orders & claim proceeds modals don't have a close button.

Add a close button to each, example for claim proceeds: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=13416%3A290467

**Comment by matt-bullock** [comment]
All these should have the header panel with title and 'X' button. It's still missing from open orders in resolved market modal

This is correct.

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/ecf6f5b6-fb2e-4a6b-8e6d-399dd119344f)

This isn't

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/a6ba2f9d-b092-43d0-b7df-58188c505389)

**Comment by bconfortin** [comment]
@matt-bullock can you retest that, please? If you are using Chrome, open the developer tools in Chrome (cmd + shift + C), right click on the refresh button to the left of the address bar and choose the third option. Should be something like "Empty cache and force reload".
Here:

![Captura de Tela 2020-03-10 às 18.09.25.png](https://images.zenhubusercontent.com/5d7fcf516b3dcf00019b60cd/99ae80d4-18d9-4907-acfc-b0ca4c3695a8)

That modal actually has a header and a X/close button. What you are seeing is an overlapping table on top of everything (including the header and the X button), which would only happen using absolute positioning. We are not using that for that table, which makes me believe you have some old CSS there.

**Comment by matt-bullock** [comment]
Tested again and looks fixed. closing
