### ISSUE TITLE
Provide Guidelines for what Invalid means in UI

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#594]
Perhaps with a tooltip:

* INVALID: The market is clearly trying to subvert the reporting system or scam traders/reporters.
* INVALID: At market creation time, it was known that one or more of the outcomes will never payout.
* INVALID: The question is subjective in nature.
* INVALID: The outcome was not known at market end time.
* INVALID: The title, details and outcomes are in direct conflict with each other.
* INVALID: There are strong arguments for the market resolving as multiple outcomes.
...

@serena @mattbullock Any thoughts/suggestions on this? Does the tooltip described above sound good?
 -adrake33

**Comment by sharkcrayon** [comment]
@adrake33 Is this meant for the reporting and dispute forms?

**Comment by adrake33** [comment]
I believe that's what this issue was for. @nuevoalex originally filed this. Can you please confirm, Alex?

**Comment by adrake33** [comment]
Checked with Alex, and he said this is intended for the reporting/dispute forms in v1. For v2, it is also for the trading page.

**Comment by sharkcrayon** [comment]
This is a good idea. Here is possible text to use:

"Please choose an outcome below based on the resolution source at the time the market ended. The market should be considered invalid if it is opinion-based, unclear, has more than one valid outcome, or the outcome wasn't known when the market ended."

It should go above the Outcome list on the Reporting form and above the Tentative Winning Outcome on the Dispute form.

**Comment by adrake33** [comment]
@sharkcrayon Thanks, will reassign this to @bthaile. Can you please make a note to add this when you're breaking down Matt's trading page design into smaller dev tasks later today?

**Comment by bthaile** [comment]
Is the v1 task to add this above the outcome lists? If so there are three locations to consider:

Initial report
Dispute
Migrate REP (during fork)

For v2 we might want to condense the text/layout since the trading page will already be condensed.

**Comment by adrake33** [comment]
@bthaile Alex's original idea for this was as a tooltip. Couldn't we just add the tooltip at the end of the option that says "Market is Invalid"?

**Comment by joeykrug** [comment]
No, you'd want this at market creation, on the market page (when trading) itself, and as a tooltip for _all_ reporting flows. All as tooltips. Otherwise it wont serve the purpose of limiting invalid markets + trading on them

**Comment by adrake33** [comment]
@joeykrug For the market creation flow and trading page, where were you thinking this would go?

**Comment by joeykrug** [comment]
Market creation it'd be a tooltip when entering the question. Or just appear on the screen itself. Trading it'd appear as a tooltip next to the market title
