### ISSUE TITLE
[4.5" screen] Column display problem

### ISSUE THREAD

**Issue by tyche78** [AugurProject/augur#594]
http://i.imgur.com/OuvocB8.png

Columns are garbled on the 720x1184px screen of a Moto-G.

**Comment by thinkloop** [comment]
improved markets display on small width screens

**Comment by thinkloop** [comment]
improved markets display on small width screens, better? If so pls close.

**Comment by tyche78** [comment]
A lot better

There's one problem with excessive stemming of percentage display though. I'd also suggest further reducing margins so that more of the screen is used for information, if this is possible without breaking the design on normal screens. 

Screenshots: http://imgur.com/a/VsU9R

**Comment by tyche78** [comment]
(by excess. stemming i mean the 3 dots)

**Comment by thinkloop** [comment]
How about now

**Comment by tyche78** [comment]
Yup. Closing. But I think you should reduce margins/paddings to the bare minimum, like on predictit.
