### ISSUE TITLE
Order book should load with the spread in the centre point - MOBILE

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5941]
Currently if a book is heavier on the sell side then it loads the book at the top of the sell side. See image from build - this is what happens when I come to this market on mobile

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/b44e0420-7314-49e3-9ef0-c811820187ee)

**Comment by Chwy5** [comment]
still appears to be doing the same thing

**Comment by matt-bullock** [comment]
looks fixed now
