### ISSUE TITLE
ML: rename the filters button on mobile

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5948]
- [ ] Rename the filters button on mobile to: "Categories & Filters" 
- [ ] Reduce the size of the search input to allow for this 
- [ ] 12 px padding between the search input and the button 
- [ ] Rename the filters heading when you open the filters menu on mobile to: "Categories & Filters" 

https://www.figma.com/file/GKhft5ZOwuH3ANrupGNCLHUU/Market-list-page?node-id=1331%3A3936

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/127b303f-cc86-4b9e-bcf1-0f5a27239756)

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/fd774ee5-6514-4a31-adba-e93362a4b7bd)

**Comment by matt-bullock** [comment]
looks done. closing
