### ISSUE TITLE
Price Oracle Visual Design

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#597]
Matt will be the owner here.

**Comment by adrake33** [comment]
@sharkcrayon @matt-bullock FYI, I talked to Alex about the price oracle, and he said we're still planning to go with the double auction at the moment. However, he said we should postpone working on this task and #425 since we're trying to still trying to come up with alternatives.

**Comment by sharkcrayon** [comment]
Sounds good. We won't be able to begin it until mid-January at the earliest in any case.
