### ISSUE TITLE
UI should not cut off before bottom of device screen

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5970]
Appears to be getting cropped off before the bottom of the screen

Build:

![Kapture 2020-02-06 at 15.02.55.gif](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/a4bfb0ac-6770-4023-b401-03cf177d0b38)

**Comment by phoebemirman** [comment]
this is needed so ios bottom bar doesn't cut off content

**Comment by phoebemirman** [comment]
no content cutoff

**Comment by matt-bullock** [comment]
Yep, tested on phone and no content cut off. This was from when I was having to rely on desktop to test mobile. Closing
