### ISSUE TITLE
Mobile: Dispute form getting cut off before header section

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5971]
![Kapture 2020-02-06 at 15.09.27.gif](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/2d48ed74-6bf0-4df6-aaf0-e3e8530eec3f)

**Comment by phoebemirman** [comment]
<img width="385" alt="Screen Shot 2020-03-05 at 12 28 37 PM" src="https://user-images.githubusercontent.com/6775839/76022909-e4a42480-5edc-11ea-8567-32c3ab27bedf.png">

not seeing this

**Comment by phoebemirman** [comment]
no content is being cutoff

**Comment by matt-bullock** [comment]
Not seeing this anymore. closing
