### ISSUE TITLE
Add category (tags) sidebar

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#598]
Something like this (very rough sketch):
![mock-4-22-2016-markets](https://cloud.githubusercontent.com/assets/2637020/14771265/6e0cc99e-0a3a-11e6-8201-7765d2b17f6c.png)

**Comment by thinkloop** [comment]
Tags have been added, making them side-bar format would be part of design sprint at the very end, closing.

**Comment by joeykrug** [comment]
Do the tags now have category -> subcategory -> tag or how does it work

**Comment by thinkloop** [comment]
This issue focuses on the display/filtering of tags - was just in the process of creating an issue for the inputting of tags during the market creation process. 

The logic currently implemented is for all tags to be displayed sorted by popularity, then when a tag is selected, it shows only tags that are associated to remaining filtered markets. I haven't discounted forcing only tier 1 tags until 1 tag is selected, then tier 2, etc., but there are pros and cons for each, and I wanted to see how this plays out in practice (it's more flexible and more tolerant of user input mistakes). Updating to the other way is trivial when we need, the infrastructure is all there.

**Comment by thinkloop** [comment]
related: https://github.com/AugurProject/augur-ui-react-components/issues/22
