### ISSUE TITLE
ML: Only apply filters on mobile when user taps 'apply' button

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5989]
Currently when a user taps a category or a filter on mobile it actually applies the filter in the background. 

This creates a noticeable delay as the user taps on a filter. 

The change is to only apply the selected filter when the user taps the 'apply' button, not when the tap the filter.

**Comment by Chwy5** [comment]
what is the status of this?

**Comment by bconfortin** [comment]
That is done

**Comment by Chwy5** [comment]
closing
