### ISSUE TITLE
Can scroll the background on all modals on mobile 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#5991]
Can scroll the background on all modals on mobile . Background scrolling should be disabled. 

![Kapture 2020-02-06 at 18.58.49.gif](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/ac52cd81-fd18-4446-90af-936f4b467308)

**Comment by joeykrug** [comment]
matters a lot, scrolling sucks on mobile atm, need to fix

**Comment by matt-bullock** [comment]
I'm still seeing this on a few places like login but I don't think it's a game changer

**Comment by Chwy5** [comment]
I only see this occur on the login pg ( the background can scroll - doesnt effect login process at all....this is small issue - closing
