### ISSUE TITLE
Mobile: URL in market title form isn't flowing onto a new line correctly 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6002]
![Kapture 2020-02-07 at 11.33.57.gif](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/46f4b62f-ddd2-43a2-a3ac-f7fb388d68c0)

**Comment by bthaile** [comment]
we'd have to reduce the text size very small to fit the text in. Or break up the text into chunks. I don't think we should do anything about this.

**Comment by Chwy5** [comment]
is the whole URL visable to a user? Want to make sure there is no question about what url it is?

**Comment by bthaile** [comment]
They can scroll to see the whole url.

**Comment by Chwy5** [comment]
Can reevaluate post launch

**Comment by joeykrug** [comment]
no one right scrolls on mobile

**Comment by matt-bullock** [comment]
This looks fixed now. Just tested:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/aa00927d-9dfb-468d-921c-bbbd25def1c0)
