### ISSUE TITLE
Mobile: Account Summary and Portfolio are getting cut off before the bottom of the screen

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6008]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/0d3c5dbf-96d8-4b6a-83b8-026c0e34320c)

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/b0ddc97f-6d80-42c4-94d5-4457e4d24308)

**Comment by phoebemirman** [comment]
needed so ios bottom bar doesn't cut off content

**Comment by phoebemirman** [comment]
no content is being cutoff

**Comment by matt-bullock** [comment]
Makes sense, again this was when relying on local to test mobile on desktop. Not seeing it on my phone. closing
