### ISSUE TITLE
Reporting and disputing forms: allow user to click market title in form to go to market page

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6013]

**Comment by Chwy5** [comment]
@joeykrug Is this within the modal.....

bc on the notification section in the acct summary pg, if the user gets a notifiaction to report/dispute, they can click on the market name in the message....or through the disputing or reporting pg user can click on title....the only spot they cant is if they open the modal, they would need to (x) out and do it from one of those other spots

**Comment by matt-bullock** [comment]
@Chwy5 this is just a request to allow the user to go to the market page via the reporting or disputing forms by making the market title clickable - It's a pattern we want to make as common as possible. Very low priority but should be easy to get in

**Comment by Chwy5** [comment]
moving this to high, this can worked now

**Comment by matt-bullock** [comment]
Can this show the underline on hover like we do on market cards. This should be a common pattern on market titles, although it's not everywhere it feels like it should be here @phoebemirman

**Comment by Chwy5** [comment]
added - closing
