### ISSUE TITLE
Unlocked accounts not working

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#602]

**Comment by tinybike** [comment]
Local node connection is handled using environment variables for now; however, although connection works, positions and balance still do not display.

**Comment by thinkloop** [comment]
Shouldd this be handled in augurjs?

**Comment by tinybike** [comment]
Partially!  augur.js will return an `account` field in its connect function, which will be `null` if the node is not unlocked, and contain the account address if it is unlocked.

**Comment by thinkloop** [comment]
The ui will use this account as tho the user logged in on connect()

**Comment by thinkloop** [comment]
What are the steps to setup an unlocked account to test

**Comment by tinybike** [comment]
To test this, you'll need a local geth node running, and will need to unlock your account on it.  You can do this either using the `personal_unlockAccount` RPC request (if the `personal` suite is enabled), or you can use the `--unlock` flag when you start geth.

**Comment by tinybike** [comment]
Fixed in AugurProject/ethrpc@1d2bea3566c3f716cc5dc2f3e916afd9e2980162 and ethereumjs/ethereumjs-connect@57c46e0c8716f55cd7830ea5d268baab54fbc51b.
