### ISSUE TITLE
Movie total gross - template needs message to tell user reporting cant begin until Wed

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6026]
Right now user doesnt find out that they cant make reporting begin until they get an error message after they try to submit.  We need to add text saying "earliest reporting can begin is the Wednesday following the weekend in the market question". Needs to be added by the Resolution date and time section

![Screen Shot 2020-02-07 at 9.09.19 PM.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/2b48da4e-8890-4279-b634-6d0535a0f673)

**Comment by bthaile** [comment]
there was a design decision to show errors on submit not before. Do you want to modify `Event Expiration date and time` label to say `Earliest event expiration date time is the Wednesday following the weekend in the market question`?

**Comment by Chwy5** [comment]
Yes, but not we can change that later, moving this to post v2 launch

**Comment by joeykrug** [comment]
dont think this matters
