### ISSUE TITLE
Incorrectly getting OrderEvent type 2, `Fill`

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#6037]
When user has open order but transfer DAI out of wallet, leaving less than needed DAI. Filled Order event is emitted. 

Repro Steps:

1. create open order (example for 50 @ 0.5)
2. transfer out of wallet leaving less than 25 DAI in wallet. (use UI withdraw function on Account Summary)
3. Notice a Filled Order Event comes in log-handlers and user gets `Fill` toast pop up.

**Comment by nuevoalex** [comment]
@bthaile This sounds like something weird being done in the ZeroXOrders.ts DB layer to send fake events.

**Comment by nuevoalex** [comment]
@bthaile Is this still an issue?

**Comment by bthaile** [comment]
No longer an issue. @joeykrug fixed it.
