### ISSUE TITLE
[v2] Can't migrate REPv1->REPv2 if user changes allowance to less than their full balance

### ISSUE THREAD

**Issue by veox** [AugurProject/augur#6039]
**Describe the bug**

Using Firefox and Metamask.

Migrating REP from v1 to v2 requires setting the allowance to the migration contract via `approve(address,uint256)` (1st tx), then calling `migrateFromLegacyReputationToken()` (2nd tx) - all available in the UI, using the button in the top right corner.

The user is warned of the fact this will require 2 transactions; however, if the user _edits_ the `approve()` permission to something less than their full REPv1 balance, they'll never get the second transaction signing window in Metamask.

**To Reproduce**

0. Get REPv1 ("Account summary" tab on top -> "Legacy REP Faucet" button on bottom right).
1. Once tx is confirmed, a button will appear top-right: "Migrate V1 to V2 REP". Click it.
2. Take notice of the REPv1 balance - say it's 10. Click "Convert".
3. Click "Edit Permission" in Metamask, and set the "Custom Spend Limit" to something less than the balance above - say, 5. Confirm the tx and wait 'till it's mined.
4. Observe errors in console:

```
MetaMask - RPC Error: The execution failed due to an exception. (x5)
Error: "convertV1ToV2"
```

**Expected behavior**

At the very least, user is given the option to convert the amount they approved.

However, considering the [function's implementation](https://github.com/AugurProject/augur/blob/2f2ae74ef60d4a1a74ae4e5c1dbd54f301cb27be/packages/augur-core/source/contracts/reporting/ReputationToken.sol#L186), the simplest "solution" here is to add a note that "only your entire balance can be migrated", and passing the exact amount in tx data to Metamask (so that the user is discouraged from editing it).

**Screenshots**

None.

**Desktop (please complete the following information):**

 - OS: Arch Linux
 - Browser: Firefox 72.0.2
 - Metamask: 7.7.4
 - Augur: whatever's currently served at https://v2.augur.net/

**Comment by pgebheim** [comment]
The dialog says it will migrate N rep, and doesn't mention that will will try to only migrate your manually approved balance or anything.

Thus I don't believe this is a bug but I'm okay with a text clarification saying it will migrate your total balance.

**Comment by pgebheim** [comment]
@petervecchiarelli @Chwy5 --

Your call on words to explain things to people. Do you agree it should somehow say that it will always attempt to do the full balance or do you think this is clear enough?

**Comment by Chwy5** [comment]
@pgebheim I think he is still referring to the old migrate modal design, the new one hasnt been added yet...see ticket 5237 (let me know if this helps with the issue).  As far as I am aware the user inputs the amount of Rep they wish to migrate. 

The copy says: The quantity of V1 REP shown below will migrate to an equal amount of V2 REP
