### ISSUE TITLE
Augur icon and hamburger icons are overlapped 

### ISSUE THREAD

**Issue by rubyweb3** [AugurProject/augur#6044]
It's a regression bug. 
![Screen Shot 2020-02-10 at 12 35 39 PM](https://user-images.githubusercontent.com/58647954/74121475-a2036b00-4c02-11ea-9d5c-2997e9b6b648.png)

Previously in PR https://github.com/AugurProject/augur/pull/5859/files#diff-123e68b9f6f2a7adf18cdb6a58cc23c0L68, they are not overlapped. The code was
```
<div>
         {(!isLogged && !restoredAccount) && <HelpResources />}
         {!isLogged && !restoredAccount && (
           <SecondaryButton action={() => loginModal()} text={'Login'} />
         )}
```

The current master https://github.com/AugurProject/augur/blob/master/packages/augur-ui/src/modules/app/components/top-bar.tsx#L69 is 
```
<div>
        {((!isLogged) || !isMobile && (isLogged || restoredAccount)) && <HelpResources />}
        {!isLogged && !restoredAccount && (
          <SecondaryButton action={() => loginModal()} text={'Login'} />
        )}
        {!isLogged && !restoredAccount && (
          <PrimaryButton action={() => signupModal()} text={'Signup'} />
        )}
```

**Comment by joeykrug** [comment]
seems to have been fixed
