### ISSUE TITLE
beta2 seems stuck in initial splash screen on firefox (46.0.1)

### ISSUE THREAD

**Issue by pqdeep** [AugurProject/augur#606]
looks fine on chrome

**Comment by tinybike** [comment]
Fixed in bf8d294bb4db9f73aa34fc921e8c1715bd0a6822.

**Comment by thinkloop** [comment]
I think this might be happening again - what was the underlying issue and resolution?

**Comment by thinkloop** [comment]
looking at the commit, the current issue might be a different reason, but having trouble loading https://augur-dev.firebaseapp.com/

**Comment by joeykrug** [comment]
SSL certificate is invalid so Firefox makes you run a wrongly signed site

**Comment by tinybike** [comment]
Sorry, I forgot to push to augur-dev after making the fix.  Should be ok now.

**Comment by pqdeep** [comment]
Confirmed - it's fine now.
