### ISSUE TITLE
show dashes for user balances until they are fully logged in.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#6068]
We want to guard against giving the impression that the user is logged in and their balances is all zeros. It could freak them out. They could think all their funds have been stolen.

![Screen Shot 2020-02-10 at 8.49.55 PM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/e62e8dd8-08c1-4831-bd06-b7bdd2d2bcf3)

**Comment by joeykrug** [comment]
status?

**Comment by pgebheim** [comment]
![image.png](https://images.zenhubusercontent.com/56019653638e718c995d3fc0/e91fa0a0-17c1-420c-8535-f875ff2f5121)
