### ISSUE TITLE
cancel out of sign up

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#6071]
got this modal when cancelling out of sign up.

1. click sign up
2. click with email button
3. exit out by clicking the X

![image](https://user-images.githubusercontent.com/3970376/74213296-2505df00-4c5e-11ea-998e-bfe6ae5e2fb9.png)

**Comment by phoebemirman** [comment]
looks like this now.

<img width="967" alt="Screen Shot 2020-03-04 at 10 38 54 AM" src="https://user-images.githubusercontent.com/6775839/75911427-670ce580-5e04-11ea-9e21-72b16068c858.png">

is that good?
