### ISSUE TITLE
Categorical markets trading page: Charts are hidden by default so clicking a chart heading tab should open the charts

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6073]
Seems intuitive that clicking the headings should reveal the charts

Currently on build:

![Kapture 2020-02-11 at 12.07.37.gif](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/7d005b40-9dea-405a-97ed-6db945986698)

**Comment by bthaile** [comment]
@Chwy5  this isn't a bug. this is new functionality.

**Comment by Chwy5** [comment]
Clicking the titles of the charts seems like normal behavior

**Comment by matt-bullock** [comment]
working now
