### ISSUE TITLE
Resolution details have disappeared from reporting and disputing forms

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6074]
When I view a market that has resolution details on the trading page, they're no longer there on the reporting form.

A recent change has made these disappear as they were showing last week.

**Comment by bthaile** [comment]
added them back in.
![image](https://user-images.githubusercontent.com/3970376/74264632-95e0e180-4cc6-11ea-91cc-65eec0c7aa7d.png)

**Comment by matt-bullock** [comment]
This has also added in the volume, open interest and fee that was never originally there. Is there a reason to add that in? There's some weird spacing going on there as well - looks messy.

This is the design:

https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=3665%3A18348

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/61d2b794-7494-4c7b-88f0-657b1999da71)

**Comment by matt-bullock** [comment]
Closing and creating new lower priority tickets for the above issues
