### ISSUE TITLE
Reporting/disputing forms: Unable to press confirm on invalid - happening on scalar markets

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6076]
Now only happens if I click the max threshold button and then clear it.![Kapture 2020-02-11 at 12.44.07.gif](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/bd0c3291-b879-4a0f-a773-86cf08becbba)

**Comment by matt-bullock** [comment]
@bthaile Still seeing issue

This is open reporting 

![Kapture 2020-02-12 at 18.35.53.gif](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/c91f6a29-26da-4716-8fda-801826b4e20f)

**Comment by bthaile** [comment]
ok, I see. scalar works which I was testing. I'll fix

**Comment by matt-bullock** [comment]
Still seeing the problem on scalar

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/cba532b7-41b7-4306-a4e1-2a27e6aa4b96)

**Comment by bthaile** [comment]
If you click clear instead of clearing the input does the confirm button activate?

Just curious.

**Comment by matt-bullock** [comment]
No I was trying everything to get it to work including the clear button

**Comment by bthaile** [comment]
I have no issue, let's sync up. 

![image](https://user-images.githubusercontent.com/3970376/74895564-8feaa080-5357-11ea-9718-15d4afbd8d58.png)

or

![image](https://user-images.githubusercontent.com/3970376/74895486-57e35d80-5357-11ea-8d5f-abf3b64b8696.png)



testing errors and recovery

![image](https://user-images.githubusercontent.com/3970376/74895599-af81c900-5357-11ea-88fd-08dd9ebedf60.png)

![image](https://user-images.githubusercontent.com/3970376/74895623-c2949900-5357-11ea-9c20-a7d3dc1896af.png)

**Comment by matt-bullock** [comment]
Still seeing this issue when doing an open report on a scalar. The confirm button doesn't become active after inputting a correct amount of pre-filled stake.

Tested disputing form and it's working ok - not seeing any issues

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e1be9b5e-c07f-4b57-bb52-1e993cbcb65e)

**Comment by matt-bullock** [comment]
appears fixed now. closing
