### ISSUE TITLE
Disputing form: Showing a dash rather than the existing stake amount

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6077]
This seems to be a recent issue as it was showing last week

Also the left side of the orange bar is chopped off

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/81185c2b-035e-4c04-b592-afb60f070e3b)

**Comment by bthaile** [comment]
Need steps on how to repro this. @matt-bullock 


looks good to me. 
![image](https://user-images.githubusercontent.com/3970376/74270996-ca0dcf80-4cd1-11ea-8168-d8c9a5f021f2.png)

**Comment by bthaile** [comment]
here contributed to another outcome


![image](https://user-images.githubusercontent.com/3970376/74271125-fd505e80-4cd1-11ea-90dd-77208a9c5822.png)

**Comment by matt-bullock** [comment]
@bthaile Checked it again and it appears to be working again. I'll close this

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e0406ac3-0f73-4362-b751-e89fda16af12)
