### ISSUE TITLE
Market title becoming overlay when not required

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6081]
I thought we didn't need this functionality on mobile as we can show the full market title anyway?

Content below is shifting up and looks like it's being hidden

![Kapture 2020-02-11 at 15.07.04.gif](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/9cd2fe89-234a-47e6-869e-ffbea885178b)

**Comment by phoebemirman** [comment]
i'm not seeing this issue. all the mobile markets that expand seem to need it because titles are cut off. next time you see when please put the link here.

**Comment by Chwy5** [comment]
closing
