### ISSUE TITLE
ML: Add In the count of markets from the market status tabs 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6089]
Add in the the counts of markets from the market status tabs at the top of the page to In Reporting and Disputing. 

The goal is to reduce confusion created when we only have the # of markets on the selected tab, when in fact the other tabs e.g. 'in-reporting' will also more than likely have markets also. 

From this: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/fd1fd7e6-10d0-4389-8ba5-f02c8876c3e5)

To this: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/f777fbe1-757b-421a-8e8e-81511a20cb47)

**Comment by Chwy5** [comment]
If the numbers get large we need to round to the first decimal place...over 1000

I.E.
1k 
1.1k

22.3k

100K
