### ISSUE TITLE
Unable to trade position; Early market maturity

### ISSUE THREAD

**Issue by SpiderMunk** [AugurProject/augur#610]
Have position in market that appears in portfolio but am not able to sell position when viewing the market. Possibly related is that the market Matured date appeared in the future. Matured on the 21st but I first saw that on the 19th.
![portfolio](https://cloud.githubusercontent.com/assets/19531871/15471710/718321e4-20c5-11e6-879a-2710f4fbf5d1.PNG)
![market](https://cloud.githubusercontent.com/assets/19531871/15471714/73659f14-20c5-11e6-8dc2-7da69229882d.PNG)

**Comment by tinybike** [comment]
Should be addressed by changes in #615
