### ISSUE TITLE
Pre liquidity Order process change

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6103]
Since Open orders Can't be created before the market is actually created we should:

1. ~~Sign open orders when signing to create market transaction.~~ can't sign orders until market is created
2. when market gets created send signed open orders automatically.

Thoughts of adding `auto send pre liquidity orders when market is created` checkbox to market review when user has pre-liq.
Also add number of tx needed to sign pre-liq message above `Create` button on Review page. So user knows how many signatures they'll be prompt for.

**Comment by bthaile** [comment]
closing this ticket. we went with different approach. agree @Chwy5
