### ISSUE TITLE
Label colours on mobile too dark in some places - wrong colour

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6113]
Only appearing on mobile. Colour should be Text/Secondary #9599A5

Please update across market page and all across portfolio 

Example from build:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/2799b677-8b84-4be8-be2a-0cbf71a8341e)

**Comment by Chwy5** [comment]
This is needed for v2 launch....too hard to read

**Comment by matt-bullock** [comment]
update looks good. closing
