### ISSUE TITLE
Check colours/opacity of add funds button

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6117]
The green looks very washed out on comparison to the design. Should be more vibrant

Build:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/b1b38be7-1a4c-453b-ab14-daa756e04d98)

design:
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=635%3A29484

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/7d6fb24a-dad2-4916-9a64-a9dc56cdd34b)

**Comment by joeykrug** [comment]
looks irish to me
