### ISSUE TITLE
"Cancelling All" requires refresh to update balance when there are many orders

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6118]
I added 10 bids and 4 offers to the orderbook then hit cancel all.  Most of my balance returned but not all.  After waiting for 5 mins I hit refresh and the rest of my balance returned

![2-12bal.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/45c8a618-59d5-47f1-8949-d6eb7661e33d)

![2-12bal2.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/a2774255-ab2a-45c5-a218-e9989fb26684)

**Comment by bthaile** [comment]
I tested with creating 6 orders and cancelled all, it took two signings and the second batch took a minute but frozen funds updated correctly.

can you test again?

**Comment by Chwy5** [comment]
worked with 8 cancels...will try a bunch more

**Comment by Chwy5** [comment]
Just cancelled 26 orders and it worked

**Comment by Chwy5** [comment]
I am closing for now...will keep an eye out for this
