### ISSUE TITLE
Mobile - filter option for invalid markets is cut off

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6121]
On safari on iOS (iphone 8): 
- The categories and filters menu
- Scroll to bottom, the 'show' option is cut off and can't be pressed

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/a3b2ba9e-e612-4a5e-8d8e-59b0a1546503)

**Comment by cillianhunter0** [comment]
This original issue is fixed but if you tap on any other filter the "apply" button appears and covers off the "show" option of the invalid market filter. You can't select it.

@bconfortin quick fix might be to increase the padding below by default so there's space for the button.

**Comment by matt-bullock** [comment]
Need someone with an iphone to test this

**Comment by matt-bullock** [comment]
Looks fixed from the screenshots Bruno shared. closing
