### ISSUE TITLE
MC: Post creation - change text and size of text in my created markets for preliquidity 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6129]
Current: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/297d261d-cf7b-4e97-a216-5cae0edbfa6c)

Updated: 
[Figma](https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=3966%3A32)
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/677ae44c-ce9d-4a3f-bc77-f6b1d6e16160)

**Comment by Chwy5** [comment]
Fixed - closing
