### ISSUE TITLE
Make best bid and best ask price clickable from the outcome table

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6137]
If a user clicks on a specific best bid or best ask in the outcome table that price and quantity should filter directly into the order ticket.....This only applies to clicking on the best price for the outcome.  Clicking on the outcome name itself continues to work the way it does.

![2-12outcome.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/4ff82966-09c9-495f-986f-b9c7c2c0ce07)

clarification:
if user clicks on best bid or best ask in the outcome list. 
the order form will be populated with the price they clicked on and the associated qty.
DO update the outcome the order form has selected.

**Comment by Chwy5** [comment]
@phoebemirman they are working corectly when clicked...thanks, but the Font size looks to have shrunk....

This is what it looks like now...

![2-17font.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/1af956cc-4e70-4f57-bacb-a01e2b77392c)

Should look like the screenshot up top

**Comment by matt-bullock** [comment]
font size is now fixed. closing this
