### ISSUE TITLE
Rectangular boxes appearing next to outcomes

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6138]
Create a multiple choice market and add multiple outcomes (using add more) boxes appear next to outcomes on trading pg....

see screenshot

![2-12boxes.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/a9625317-4c7d-469c-ab28-0639d7157dbe)

**Comment by bthaile** [comment]
I dont see the squares

![image](https://user-images.githubusercontent.com/3970376/74387364-f737ac00-4dbd-11ea-9d07-4138578d5e6a.png)

**Comment by Chwy5** [comment]
Are you on V2 or local?

I see it on the market list pg for that market as well...
![2-12](https://user-images.githubusercontent.com/41301809/74390199-7f25b200-4dce-11ea-87af-dc97fda5d609.jpg)
and my whole trading pg still looks like that screenshot above

**Comment by Chwy5** [comment]
fixed - clsoing
