### ISSUE TITLE
Betting UI - Convert Categories Section to new style

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#6142]
https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet---Design-System?node-id=55%3A316

Convert the overall categories section/side bar to the new style -- this is a bigger ticket, feel free to break it up if that makes it easier.

<img width="709" alt="Screen Shot 2020-02-12 at 1 06 44 PM" src="https://user-images.githubusercontent.com/10524630/74368177-bb3e2000-4d98-11ea-97e4-3a4a82b60e2b.png">

**Comment by rubyweb3** [comment]
Hover and focus state for filter are difficult to make as the size of the circle changes.

![Screen Shot 2020-02-19 at 6 07 26 PM](https://user-images.githubusercontent.com/58647954/74824177-dc77b100-5342-11ea-89a8-821f3b8411e6.png)
