### ISSUE TITLE
Betting UI - Big Tab Labels

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#6151]
https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet---Design-System?node-id=540%3A67![Screen Shot 2020-02-12 at 1.25.10 PM.png](https://images.zenhubusercontent.com/57155267bf93871ccd99a48b/493ec303-64b6-4b98-877e-2c58ce7443ec)

new component.

**Comment by rubyweb3** [comment]
@JohnDanz Could you add a link to figma? I didn't find this component.
