### ISSUE TITLE
Betting UI - Back/Lay Switch

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#6152]
https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet---Design-System?node-id=540%3A67

![Screen Shot 2020-02-12 at 1.27.54 PM.png](https://images.zenhubusercontent.com/57155267bf93871ccd99a48b/252a40a7-4113-477b-982f-5343fa5c284e)

New Component

**Comment by pgebheim** [comment]
Closed with merge of #6969
