### ISSUE TITLE
Change to relative paths in index.html break directly loading inner pages

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur#616]
@tinybike recently the paths in index.html were changed to be relative, but this broke loading inner pages directly, like `/m/_marketid` - what was the reason for it again? Is it possible to get around it and go back to root-based paths?

**Comment by priecint** [comment]
https://dyffy.slack.com/archives/dev/p1462820989000663

**Comment by tinybike** [comment]
You can change it back.  Reason for it is so it would display over IPFS, although there may be another workaround for that.

**Comment by thinkloop** [comment]
changed back to relative
