### ISSUE TITLE
Buy participation tokens > My REP balance deducts after about a minute but my participation tokens don't show up here

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6170]
**Read to end of ticket**

Here it should show 11
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/22cefee4-9d8b-4ebb-a3d2-0e89d241becf)

it is updating in the total PT tokens purchased but not showing that I own them

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/d7814930-1821-425a-adce-dcd9d557cb46)

After pushing time forward a week it's now working correctly

**Comment by bthaile** [comment]
this has been fixed, can you retest.

**Comment by matt-bullock** [comment]
yep this is working thanks
