### ISSUE TITLE
Indeterminate auto fills in 1.5

### ISSUE THREAD

**Issue by housemobile** [AugurProject/augur#618]
When I click indeterminate on this market: https://app.augur.net/reports/-0x325ec195cecd054fee352eeb7ebc543c2d75d49aa35380ea54ead6663e52892d

Question
TheDAO0n0¯0é0¦0É0»0ü0ë0gÆ0~0ÑM0o}BN

Your answer must be at least 0, but no more than 20000000000

It fills in the event outcome box as 1.5. Unable to delete that without unselecting the indeterminate box. 

Hitting submit shows: The outcome you have reported is: 1.5

Doesn't seem to be a way to vote indeterminate here.

**Comment by tinybike** [comment]
For numerical markets, "indeterminate" should be 0.5 in fixed-point (see http://docs.augur.net/#reporting-outcomes) -- this will be fixed as part of the UI overhaul.
