### ISSUE TITLE
Create market form template: inputs need to accommodate the full instruction and not cut it off

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6191]
Example where the user can't view the  whole instructions:

Should say ETF name and ETF Ticker at the ends

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/37e354f6-e263-4065-8b83-9ccbc2b86486)

**Comment by Chwy5** [comment]
Might need to change Individual to Single

**Comment by Chwy5** [comment]
Please confirm this is an issue, bc I do not see this on mine

**Comment by matt-bullock** [comment]
Chwy isn't seeing the issue using chrome on windows but I am when using chrome on mac

**Comment by matt-bullock** [comment]
Firefox on mac is cutting ticker symbol off

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/0b970345-8b31-44f8-9c22-fd617630b5a6)

**Comment by bthaile** [comment]
I can change individual to Single

`Single Person or Single Group or Movie Title` this one is really long. mostly needed for tooltip after market is created. placeholder text is super minor thing imo.

**Comment by bthaile** [comment]
example
![image](https://user-images.githubusercontent.com/3970376/75399228-536ff500-58c1-11ea-9449-cf7f428a191c.png)

could have a hover tooltip, only good on desktop. not sure about mobile. longer text box wouldn't work on mobile. 


![image](https://user-images.githubusercontent.com/3970376/75399349-94680980-58c1-11ea-9ce1-13b62284e857.png)

but might, depends on the mobile device.

**Comment by cillianhunter0** [comment]
Solution for this. [figma](https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=4017%3A17)

- On **desktop** we increase the max width of the text-inputs so they can go full width within their div (with padding both sides)
   - additional note: if the placeholder text is very long and needs more than one line, the input can increase in height)
- On **mobile** we allow the input to increase in height.

Mobile
Build on left, design on right: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/d6189c2e-3538-4543-84b5-a795a7e3be24)

Desktop
Build on left, design on right: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/fc76b1d8-a9f0-4815-b89f-abd1b9e66417)

**Comment by Chwy5** [comment]
closing
