### ISSUE TITLE
At smaller desktop sizes in Positions tab: average price, unrealized P/L and realized P/L should go onto 2 lines

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6193]
To stop them bunching up like in the image below

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/201c5cb8-4069-46f7-807f-b568bb1129cf)

**Comment by phoebemirman** [comment]
have to do new lines for all desktop sizes. wee don't have smaller desktop breakpoints

**Comment by matt-bullock** [comment]
Could the text just naturally wrap onto 2 lines when the space gets too tight across any size?

**Comment by phoebemirman** [comment]
it wouldn't be consistent. some would wrap some wouldn't

**Comment by Chwy5** [comment]
fixed - closing
