### ISSUE TITLE
Tennis Templates displaying wrong shield and missing shield

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6197]
The who will win set # is displaying a green shield...should be Yellow, since user still needs to input Players names (also Players names are missing the underline and tooltip)

The Tennis over/under templates are not displaying any shield - s/b yellow since Market creator needs to input players names

**Comment by bthaile** [comment]
Validation only checks market question for text inputs for yellow shield. Then all categorical that have text inputs will end up with yellow shield. Which seems to be the best approach. I can make the fix.

I’ll check the O/U template some validation is failing.

**Comment by Chwy5** [comment]
The market question does have text inputs....players names (Player vs Player)

**Comment by Chwy5** [comment]
fixed - closing
