### ISSUE TITLE
Rep balance errors

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6198]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/cfa42aff-ddc3-49b5-8d06-ea9496684c48)

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/732b5d7c-c734-47b5-a205-8aecf7f2fdde)

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/544a7a02-351f-4496-87ab-aa702f5a43b8)

there's an error in rep balances when supporting an outcome:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/43affa46-3fca-4cf3-a6b0-05b81a5473d2)

similar issue happening with disputing an outcome
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f0773350-c256-455f-9e30-550046dab878)

**Comment by bthaile** [comment]
I have a PR to fix this issue of balances not updating.

**Comment by matt-bullock** [comment]
Check through and DR and OR appears to be fixed.

Disputing is still having issues with adding pre-filled stake to outcomes. Some markets are working fine but below is an example where the amount is coming out of the users available rep balance and is showing on the market card under pre-filled stake but it's not showing up in the users 'My Total REP Staked'

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/8f0120d8-e270-4f06-89fa-55bb96cf7f3e)

**Comment by bthaile** [comment]
Ok, could be UI isnt refreshing user data after a dispute or there is some error preventing the updating of user data. I can look.

**Comment by bthaile** [comment]
I'm not seeing this issue. @matt-bullock can you confirm

**Comment by matt-bullock** [comment]
Checked through all scenarios and rep balances are all being deducted/adding up correctly
