### ISSUE TITLE
Update create market form with new fields and liquidity step

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur#620]
The logic is located in `/src/modules/create-market`

Part of this issue will be to implement the new `generateOrderBook` function jack added as an action: https://github.com/AugurProject/augur.js/blob/master/src/index.js#L854 

Part will be to update the `create-market-form` selector

**Comment by stephensprinkle** [comment]
TODO:

- [ ] Update `create-market-form` selectors
- [ ] Implement `generateOrderBook`

**Comment by stephensprinkle** [comment]
PR #652 resolved this issue.
