### ISSUE TITLE
blocks behind needs mobile styling for logout 

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#620]
gets cut off for smaller widths 

<img width="426" alt="screen shot 2018-12-05 at 10 42 34 am" src="https://user-images.githubusercontent.com/6775839/49536085-8c661900-f87a-11e8-8af6-f059a92f9e05.png">

where should this dropdown go for mobile?

works in this placement when signed in but not signed out

<img width="436" alt="screen shot 2018-12-05 at 10 44 15 am" src="https://user-images.githubusercontent.com/6775839/49536186-c59e8900-f87a-11e8-9f92-2f4e3307042b.png">

**Comment by phoebemirman** [comment]
@matt-bullock said to move the blocks dropdown to the right, so that it is straight aligned on the left for mobile

**Comment by matt-bullock** [comment]
@phoebemirman only for the logged-in state - presuming it fits? Otherwise it'll need more design

**Comment by phoebemirman** [comment]
yea. should fit.
