### ISSUE TITLE
Warp Sync market design assets

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6200]
Fleshed out the basic design assets with Tom for this. 

https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=3782%3A504

todo:

1. [x] warp sync market needs to be identified, SDK to add a flag
2. reporting/disputing form, need to not show min/max prices 
3. for open reporting need to populate outcome input from sdk call to get hash
4. for disputing need to populate outcome input from sdk call, just like open reporting.
5. need to convert hash to unsigned 256 int for contract call.
6. [x] hide warp sync market on market list page. SDK needs to filter it out of `getMarkets` getter

**Comment by bthaile** [comment]
closing moved todos to <https://github.com/augurproject/augur/issues/5986>
