### ISSUE TITLE
MC: Template wrapped value formatted issues

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#6227]
Two issues.
1. the second name isn't underlined 
2. tooltip isn't lined up

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/2b6ad7ce-d892-4c99-8cf8-6484b145a427)

Issue in the second name is wrapped which is messing up the underline and tooltip location

**Comment by Chwy5** [comment]
fixed closing
