### ISSUE TITLE
Initial liquidity not displaying correctly on market preview

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6234]
My initial liquidity 

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e8551f7d-1470-4322-9b62-ea0f6ca7f618)

What I see on market preview:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/833f2989-1cd2-4434-809c-d8ac933201cb)

**Comment by Chwy5** [comment]
closing
