### ISSUE TITLE
Open / fill orders - scroll area is tiny in safari (Mac OS) 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6238]
Open / fill orders - scroll area is tiny in safari (Mac OS) and should match the implementation on Chrome.

Safari: 
![Kapture 2020-02-17 at 19.17.09.gif](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/f3616408-dceb-4496-9989-caa083ff3aca)

**Comment by Chwy5** [comment]
not seeing this....closing
