### ISSUE TITLE
Have better way to handle 0x functionality when not on mainnet/kovan

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#624]
0x transfers are only available on mainnet/kovan, so currently clicking "Buy REP using 0x instant" on Account:Deposit while using other test nets does nothing.

Need Design team to decide if we should even show this page on other test nets since it is unusable. If not we need some other way to convey this to the user.

**Comment by adrake33** [comment]
Since we decided not to hide the Deposit page (due to some users potentially wanting to use the QR code), I would recommend replacing the 0x button with a message that says "Deposits via 0x Instant are only available on the Ethereum main network and Kovan test network" instead of just removing it altogether.

**Comment by sharkcrayon** [comment]
I think we either need to go the direction where we hide the 0x column on that page altogether (leaving the public address and QR code) or disable the 0x button and put the warning text Aaron mentioned above directly below the disabled button.

The warning text without the disabled button lacks context, as some users may not know that that functionality is typically available to begin with.

@matt-bullock Any opinions?

The page as it normally is on Mainnet, with the 0x button enabled:

![image](https://user-images.githubusercontent.com/4355755/49671820-5c5b7900-fa26-11e8-98e6-bf9cf3852c45.png)

The same section on a testnet with the button removed and the disclaimer added:

![image](https://user-images.githubusercontent.com/4355755/49671852-785f1a80-fa26-11e8-8bc9-a6e9267136d0.png)

**Comment by matt-bullock** [comment]
I agree with disabling the button and having the message. I'd use an actual button rather than just the text button - this makes the disabled state more obvious.

**Comment by adrake33** [comment]
Yeah, I like the idea of an actual button when the functionality is available. Matt said we can just use the same type of button as the Trade button on the market list page.
