### ISSUE TITLE
Feature request: store a note about a market in localstorage

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#625]
Suggested by aaaaaaaaaaaaa: Could be a nice feature to be able to store a note about a market. Just something for yourself stored in local storage, not a public note. Can help to remind you why something is invalid or such. Would be helpful for when people ask about that market weeks later

**Comment by sharkcrayon** [comment]
To me this seems like really low priority, and I'm not sure it would even be useful to a large enough number of users to justify it. I'd be curious how mainstream day traders handle whatever note keeping they need.

**Comment by adrake33** [comment]
Agreed, I'll change it to low priority. It's not something we'd need to work on anytime soon, and it may not be something we decide to implement.

**Comment by joeykrug** [comment]
Gonna close, if more users ask for it could reopen
