### ISSUE TITLE
MC: MOBILE - Post creation - change text and size of text in my created markets for preliquidity

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6251]
Related to desktop ticket of same issue: #6129

The mobile view looks messy. Heres a fix for that: 
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=3976%3A344

design on left, build on right
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/ae431cc8-345a-4bfd-acbe-3a056f28bcd0)

**Comment by matt-bullock** [comment]
done. closing
