### ISSUE TITLE
Feature request: Show market creator address in trading UI

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#627]
Suggested by spiz0r: It would be great if we could see the market creator address in the UI, and  the possiblity to list the markets created by that address. It would give more information about a market, if I see the market created by a known scammer, I simply wont trade on it.

**Comment by sharkcrayon** [comment]
This is a great idea and we should definitely do it. I'd say this is about medium priority because it's more important to finish the overhaul of the UI first and then get through V2 stuff.
