### ISSUE TITLE
Move 24hr change back over to the right on my active markets

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6283]
For some reason it has shifted over to the left

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/2f04e514-4d20-4cf6-a09a-eb7351a950c9)

Design 

https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=2677%3A24673

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/6d56bf6a-13a6-4a7a-86e7-b42e73b3917c)

**Comment by Chwy5** [comment]
Ticket 5963 can be done at the same time as this ticket

**Comment by matt-bullock** [comment]
done
