### ISSUE TITLE
Profit and loss and Balances not adding up correctly after claiming proceeds- scroll to the bottom to see comments

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6288]
Account before claiming proceeds

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/de177f5c-15c2-4149-8836-caecca67fdc2)

Details of amount to claim

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/0afa101a-c434-4224-8e11-2f8d00a94498)

Balances after claiming

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f3e6964a-557c-47e6-b12c-f9d3cf790a06)

Shouldn't my P/L be $405.90?

**Comment by bthaile** [comment]
issue is that fees were not calculated correctly so after claiming user balance doesn't reflect real value claimed. Proceeds should have been added to user's available balance and frozen funds would be reduced so total funds would increase the amount of profit. 

Available Funds would increase by Proceeds.
Total Funds would increase by amount of Profit.
Frozen funds would reduce by Proceeds - Profit.

**Comment by matt-bullock** [comment]
P/L only updates after manual refresh.

Shouldn't my P/L be 878.35?

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/85609b4e-b6b7-494c-adc9-23d2aac048ee)

**Comment by bthaile** [comment]
The total balance is the same before and after refresh. Thats interesting. Also how did frozen funds go up after a refresh. After claiming frozen funds goes down because the original position funds gets released to users wallet.  
Something else is going on.

**Comment by bthaile** [comment]
@matt-bullock 

Frozen funds is correct. 
initial value: 1728.00 after claiming it's 1618.00. reduced by 110. 
100 DAI because that is the cost of getting into the position.
10 DAI because the market got finalized (when proceeds are claimed) and the validity bond was returned. Did this account create the market?

There looks to be an issue with Trading Balance:
before claiming it's 6499.70.
profit is 940.00 + 10 DAI (validity bond) mentioned above is 7449.7. But the screen shot says 7509.60, there is 59.9 DAI unaccounted for. 

If this account created the market it would get trading fees when the market is finalized. This could account for the 59.9 (there would be transaction fees in this well)

**Comment by joeykrug** [comment]
status?

**Comment by bthaile** [comment]
@matt-bullock have you been able to test this after my feedback?

**Comment by matt-bullock** [comment]
Just tested and the figures for P/L seems slightly off. Does the total account value, available trading balance and total frozen funds all add up correctly to you? @bthaile 

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/1aea9597-b108-4179-83fe-13c5543537a1)

**Comment by Chwy5** [comment]
I am having some weird funkiness with this still:

see starting balances:
![3-29balance.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/4c37600a-20d7-40fd-9ceb-1628627831db)

See amount to be claimed:
![3-29cpamount.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/0b6e7e25-6b5b-4d5e-95be-1458732e8612)

See balances after claiming:
![3-29postbalance.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/c6f1536c-42f9-43c4-b28c-749c49755bff)

I think there is a rounding issue going on with Realized PnL s/b 9.8 and not $10
My estimate Tx fee was $2.38 instead the actual was 32.888

**Comment by Chwy5** [comment]
This is still not adding up properly

See starting balances before claiming
![4-1beginningbalance.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/9125b80d-8af7-4f32-8be4-407d6a859096)

See claim proceeds modal
![4-1claimproceedsmodall.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/e7af4a63-aa84-4b19-9f78-8cbed487bdbb)

See final Balances (the only number that is close to correct is the Available funds- it's off by a nickel)
![4-1endingbalance-claim.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/586d890d-097f-4537-bc49-60e36bbca97b)

My Available funds increased 129.63 which is (9968.3-6838.67) which = the 155.49 Proceeds - 25.805 (tx fee)

No idea why my profit increases $10

I got back $163.1 In FF, I would only expect to get back the $155.49

And My total funds I would only expect to be lower by the Tx fee of $25.805 and it is lower by $33.47

**Comment by Chwy5** [comment]
this is all done -closing
