### ISSUE TITLE
Mobile side nav - add funds button is wrong 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6290]
Add funds button should be green. [figma](https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=12854%3A298319)

The build: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/3bae7baf-1888-49d9-a4c7-b8f5c99f923b)

The design: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/838c034c-1c38-4ca0-8001-5c342cd83a8c)

**Comment by Chwy5** [comment]
there is a ticket for this already - closing
