### ISSUE TITLE
Cancelling a transaction in the metamask prompt causes an error message modal in the UI

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6291]
This is what shows on local 

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/db6c668d-dea8-445a-8021-b2ae8996a29c)

This is what shows on Kovan

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/29cd608c-327f-4883-b35e-7db866b43381)

**Comment by Chwy5** [comment]
believe to be fixed....havent seen this happen in 2 weeks - closing for now
