### ISSUE TITLE
when disputing an outcome my disputing REP amount shown in the balance is always one transaction behind

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6323]
Image below should illustrate what I mean

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/49d34dcd-e719-49e1-a50c-8d9e9455a6f1)

**Comment by bthaile** [comment]
![2020-03-04 09 04 43](https://user-images.githubusercontent.com/3970376/75892678-5609a780-5df7-11ea-94ca-38b4a41340d5.gif)

screen capture got split into 2 gifs

![2020-03-04 09 05 04](https://user-images.githubusercontent.com/3970376/75892651-4e4a0300-5df7-11ea-9418-90e81595a71b.gif)


notice that user's disputing REP amount updated after disputing markets page refreshed.

**Comment by bthaile** [comment]
can you re-test, maybe the scenario you are seeing is different

**Comment by matt-bullock** [comment]
This is working correctly now. closing
