### ISSUE TITLE
Error should say Percentage rather than price on invalid outcome of scalar

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6324]
If we're referring to that input as percentage then the error message should be consistent 

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/a6b3440d-4458-409b-aed0-1a9f6eba9fc9)

**Comment by Chwy5** [comment]
Doesn't that need to be a whole number since it is a %

**Comment by matt-bullock** [comment]
Yeah I created a separate ticket for that #6326

**Comment by matt-bullock** [comment]
Message is now showing enter a valid percentage. closing
