### ISSUE TITLE
Invalid scalar market - error message in screenshot should say multiple of 1

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6326]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/93f9a546-29fc-47ea-a1d2-ca312c1526f1)

**Comment by Chwy5** [comment]
@matt-bullock not sure that is correct for scalars.... @bthaile

**Comment by Chwy5** [comment]
fixed closing
