### ISSUE TITLE
Load user's open orders

### ISSUE THREAD

**Issue by priecint** [AugurProject/augur#633]

**Comment by priecint** [comment]
Related https://github.com/AugurProject/augur-ui-react-components/issues/29

**Comment by priecint** [comment]
@tinybike, @joeykrug Please, what's the best way to get user's open orders for market (outcome)? One way is to filter values from getOrderBook by `owner` field. Any better way?

**Comment by joeykrug** [comment]
You should be able to filter by owner _and_ market 
event log_add_tx(market:indexed, sender:indexed, type, price, amount, outcome, tradeid)

Jack can explain more / may have a better way in augur js already setup i think

**Comment by tinybike** [comment]
@joeykrug The logs I'm getting from the `log_add_tx` event (and the `log_cancel` event) only have 2 topics, for example:
```javascript
{
    address: '0x8d28df956673fa4a8bc30cd0b3cb657445bc820e',
    blockHash: '0x8c3fa0f2a092adf52702b8ebda332c12311f32a9d7dbeca3fd7ad3237a1b143a',
    blockNumber: '0x11964c',
    data: '0x000000000000000000000000ae1ba9370f9c3d64894ed9a101079fd17bf1044800000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000001d7dd185ffffff8d00000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000002ccb7a4c7d0c9a0de5c08c459ce78642b23fdbd9df707781a9f4c24f9c1205bfd',
    logIndex: '0x1',
    topics: [
        '0x8dbed7bffe37a9907a92186110f23d8104f5967a71fb059f3b907ca9001fd160',
        '0xbbc704ce88ff685a56a6a8e708cec54f981d750d8fe83a53d8c4ffb2d4bf4ddd'
    ],
    transactionHash: '0xa1796f1e7bd1290ba695908a2633a5164deb83c1431c5106c51fb186e79c257e',
    transactionIndex: '0x3'
}
```
The first topic is the event signature `sha3("log_add_tx(int256,int256,int256,int256,int256,int256,int256)")`, the second is the market ID.  The sender's address `0xae1ba9370f9c3d64894ed9a101079fd17bf10448` is the first entry in the (serialized) data array.  Not sure why it's not being indexed but seems like it's not.

**Comment by tinybike** [comment]
Added in 1f7878e798d989774d80f25d8b8b1c372ed99ecf
