### ISSUE TITLE
Error message doesn't clear after switching outcomes in initial liquidity 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6332]
If I get an error message in initial liquidity like below

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/52ed8d28-40f2-46c6-a3e1-f308ac24361e)

and then switch outcomes, the error message doesn't go away. See below:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/21861be5-895f-4f24-8c7f-91c3ac9a2cd2)

Once I clear the input it does go away so this is only a minor nuisance

**Comment by Chwy5** [comment]
fixed -closing
