### ISSUE TITLE
FIREFOX: remove up/down arrows from inputs

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6333]
Also from initial liquidity and anywhere else they might appear

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f5277315-6daf-4516-9589-6a51951080af)

**Comment by JohnDanz** [comment]
Pretty sure you can't do that in firefox.

**Comment by JohnDanz** [comment]
I lied, fixing.

**Comment by matt-bullock** [comment]
not seeing these anymore. closing
