### ISSUE TITLE
FIREFOX: centre align expand/collapse buttons in outcomes and charts

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6334]
They still work but it looks broken 

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/bbaf4d73-8d71-4363-9fe4-7ddfd0a2c7d8)

**Comment by Chwy5** [comment]
Delete your local storage and this...

deleted augur-42 database as well as all the 0x databases from the storage tab.

Then it should work

**Comment by Chwy5** [comment]
fixed - closing
