### ISSUE TITLE
Order form breaks if user enters an order, puts in an order expiration and then tries to edit the limit price

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6335]
See in the screenshot below my max cost is still at $3 and the buy button is deactivated 

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/83400fd0-9831-497a-b1fb-cab13a44bd94)

**Comment by bthaile** [comment]
@matt-bullock  what are the steps to reproduce?

I can put in 
quantity 10
price 0.8
set an expiration date of 1 day
then change total order value to 3

I get the correct behavior

![image](https://user-images.githubusercontent.com/3970376/74982242-5cf8e900-53f9-11ea-82ba-1eae0d08bd83.png)

**Comment by matt-bullock** [comment]
tried to reproduce the steps but it looks fixed now. closing
