### ISSUE TITLE
Transaction history: need a way to show the show amount per page dropdown - currently it's getting cut off

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6340]
I would suggest the dropdown menu shows above rather than below but only on this dropdown. Or increase the spacing below in that modal to accommodate the menu. Whichever is easiest 

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/23f75d9a-b830-4e5f-9ddb-4df6f5f8b113)

**Comment by Chwy5** [comment]
fixed - closing
