### ISSUE TITLE
Clicking the view icon in transaction history doesn't work

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6341]
only clicking the text works, despite the whole button showing to be clickable

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/6938ab8c-e2d3-4fb3-a785-9dd6876c48e4)

**Comment by Chwy5** [comment]
It appears to work for open orders, fills and market creation....I think the issue is we are displaying the "view" button for transactions that do not require it....like cancel....this needs to be confirmed

**Comment by matt-bullock** [comment]
It's only a minor issue where this part of the button isn't clickable on transaction history modal 

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/ab9b7c56-9b2b-4f02-b1e9-ca2818a57aa2)
