### ISSUE TITLE
Transactions history: the table headers should scroll horizontally with the rest of the table

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6342]
Currently they don't:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/dd513926-66c7-44bc-b48c-4d7d2a554e2f)

And on firefox the horizontal scroll on the table isn't working at all

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/17c98532-aec7-4d3c-85ca-86adac05c759)

**Comment by phoebemirman** [comment]
is it ok if the header scrolls with the content when doing vertical scroll? (so it gets hidden)

don't think we can have one without the other without unnecessary complications

@Chwy5 @matt-bullock

**Comment by Chwy5** [comment]
Yes thats fine

**Comment by Chwy5** [comment]
fixed - closing
