### ISSUE TITLE
transaction history: sort by quantity not working (this works, just a big delay to update)

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6343]
Price is working but not quantity 

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/de8f2595-49df-4707-93e1-83dff1fc365e)

**Comment by Chwy5** [comment]
This needs to be fixed post launch....after further testing it does seem to work displaying lowest to highest, but there is a big delay before it readjusts....needs to show both ways and be much faster

**Comment by Chwy5** [comment]
fixed- closing
