### ISSUE TITLE
See Chwy's comments below: Transaction history: 2 market hover states showing up sometimes. See gif:

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6344]
![Kapture 2020-02-20 at 16.51.41.gif](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f9721eef-182d-4af4-92e2-ea0a82199f55)

**Comment by Chwy5** [comment]
I just retested and the hovers showing up for me are the incorrect hovers.  Maybe bc I sorted by quantity , But whe I am on pg 2 of my Transaction history and hover over one of my football markets it is showing me 2 hovers for 2 totally different markets

**Comment by Chwy5** [comment]
looks better - closing
