### ISSUE TITLE
Correct templated market scalar precision

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6346]
This seems to be an issue with all sports scalar templates Change the precision from 1 to .01 (2 decimal places out)....this should help fix the "Price must be a multiple of 1 issue" associated with rounding

Sports needed to update:

American Football
Baseball
Basketball
Hockey
Olympics

**Comment by bthaile** [comment]
based on reading the description, I don't think we should do this.

**Comment by Chwy5** [comment]
fixed closing
