### ISSUE TITLE
Signup: mac OS safari bug - portis - stuck in a loop 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6349]
Sign up isn't working on safari tech preview: 

- sign up for an account with portis
- enter email and password
- you'll then get stuck on the screen below (it just keeps spinning) 
- clicking 'continue' in the portis modal opens the pop up to sign up again
- clicking the 'x' shows this error (see below) 

Console screen shot below. 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/516659f7-74fe-467a-8a57-3fdfede52667)

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/fa0e15a8-c5f5-4ae6-a66d-6d28606f5c77)

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/bddc6884-ec61-4358-a9c6-c2ca2404173c)

**Comment by andrewdamelio** [comment]
~~@cillianhunter0 Are you able to load the markets, before trying to signin?~~

**Comment by andrewdamelio** [comment]
closing. moved to #6389
