### ISSUE TITLE
Signup: macOS Safari & Brave bug - torus 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6350]
Clicking login or sign up with torus shows the error below. 

I'm not sure if this is a bug or if safari tech preview and brave don't have cookies enabled by default (i didn't turn them off)? 

Console screenshot below. 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/436ed092-3816-4e84-824d-a373a456769c)

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/7d1a1b5a-6d9e-414c-84a6-a5cc3ed4985f)

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/105dfa5f-512e-4c87-ae3a-5dbfd7dbd14e)

**Comment by cillianhunter0** [comment]
fyi this was originally tested in safari but i'm seeing the same behaviour in brave.

**Comment by andrewdamelio** [comment]
closing. moved to #6389
