### ISSUE TITLE
Learn More links for Torus on boarding have the wrong links

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6362]
The What is Dai learn more links in torus on boarding are linking to the wrong spot

**Comment by phoebemirman** [comment]
whats the right spot? @Chwy5

**Comment by Chwy5** [comment]
@petervecchiarelli please provide the link to this

**Comment by petervecchiarelli** [comment]
https://augur.gitbook.io/help-center/prediction-markets/crypto-glossary#what-is-dai

**Comment by Chwy5** [comment]
goes to the correct spot - closing
