### ISSUE TITLE
When computer goes into sleep mode causes augur to not work properly upon awkening

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#637]
So I wanted to test the connection issue i had from yesterday morning, (leaving computer on all night in sleep mode)....I only had Augur app modal opened all night, I hit 'open in browser" button to launch a new trading pg and went to do a tx which goes through on etherscan, updates my eth balance, but gets stuck in pending state in notifications...(-was a cancelling an open order)only Grays out in My positions (and upon a refresh does not disappear) in fact gray area went solid again, so i would be able to reclick cancel even though i did already and had eth deducted.  

This can be a big problem for traders in the future as most serious traders like me would barely ever turn their computers off, for fear of missing a big trade over night.........

Refresh doesnt fix the issues....nor does signing out of augur or MM....only solution has been to disconnect from augur app and reconnect
Upon reconnecting - pending goes to confirmed and the transaction is removed from my positions

https://electronjs.org/docs/api/power-monitor

**Comment by adrake33** [comment]
Chwy's computer goes to sleep after 3 hrs. Balanced power plan
