### ISSUE TITLE
Exiting the test trade tutorial is cut off 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6374]
There is a bar at the top of the page that allows users to exit the flow. It's currently cut off in the build. 

Needs to be pushed down so users can read the text and exit. 

Same problem in chrome and brave 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/af49d13f-27a2-45eb-9723-bb73b9c8fd33)

Also noticed at the bottom of the page the overlay is not reaching the bottom of the page: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/3006f43b-f4fc-4c59-be37-7bda265b68ed)

**Comment by andrewdamelio** [comment]
@cillianhunter0 is this still an issue?
