### ISSUE TITLE
Firefox: torus - popups blocked 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6379]
Torus' popups are being blocked. I'm not sure if this can be fixed. But Portis doesn't seem to have this problem with their popups. 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/e86d9bc9-62cb-4443-88f4-7fd4617c54bd)

**Comment by pgebheim** [comment]
They've added a nice message for how to disable the popup blocking for the site.
