### ISSUE TITLE
24hr % change doesnt look to be calculating correctly in My active market in Acct summary pg

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6381]
see screenshot....

![2-2124hr.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/a8544e19-e616-40e7-88c8-ed113d0fafb1)

2nd issue is cosmetic and needs to be aligned on the right side of that section over the other numbers (not on the left of the box)

updated but still off...

![2-2124b.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/2a849f74-9e91-43ec-950d-2f9e11e8f8a9)

**Comment by Chwy5** [comment]
![Screen Shot 2020-02-24 at 12.10.49 PM.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/89194498-ba89-46f9-b6a3-89591963e814)

still seems off for me

**Comment by pgebheim** [comment]
@bthaile status? Did this close w/ 6416?

**Comment by Chwy5** [comment]
looks fixed
