### ISSUE TITLE
Check Matt's last comment on adding message. Scalar market order book for Invalid needs to display as % and not total order value

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6382]
Currently the order book shows total order value in it for the invalid outcome, It needs to display as %.

**Comment by bthaile** [comment]
we need to think it all the way though. 
Is outcome list going to display percentages for best bid/ask?
is this going to be site wide/ Can we make changes in SDK?

**Comment by Chwy5** [comment]
best bid / best ask last price and the order book and in my fills/open orders/fills

should be made on the sdk level

**Comment by joeykrug** [comment]
sdk should make it site wide imo

**Comment by pgebheim** [comment]
@bthaile -- we can give this to @robert-e-davidson3 or @justinbarry to do the getter changes quick.

Will also need to switch the formatting so will need to do the different number formatter UI side.

**Comment by Chwy5** [comment]
@matt-bullock need some design on this.....this is for a scalar market only...order book will trade in % and not total order value

@robert-e-davidson3 need to make changes to the SDK

**Comment by Chwy5** [comment]
Go to football template and create a scalar
enter to buy 1 share of invalid at 5% (shows on book as 4.71)....then go and enter a sell order to sell 1 invalid at 5% I am not getting consuming own order notification in the order ticket....

Also we need some text to explain why 5% is 4.71%

**Comment by Chwy5** [comment]
@matt-bullock we need a message box that take user to a learn more to explain why this works

**Comment by matt-bullock** [comment]
Design for order ticket message

https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=8218%3A266108

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/d9e5f3ae-4299-40f6-9385-11032e75e178)

**Comment by Chwy5** [comment]
I am not seeing this message trigger when I add an order for invalid that should trigger it....

Wasy way to recreate....NFL scalar market add to buy 1 share of invalid at 5% (shows as 4.71) message should trigger

**Comment by Chwy5** [comment]
added-closing
