### ISSUE TITLE
Portis/Torus issues with Brave/Safari (3rd party cookies)

### ISSUE THREAD

**Issue by andrewdamelio** [AugurProject/augur#6389]
## ISSUE relates to the below items
- Signup: mac OS safari bug - portis - stuck in a loop #6349 
- Signup: macOS Safari & Brave bug - torus #6350
- Signup & login with portis - not working in Brave macOS #6354

I closed the above issues to consolidate here

## ISSUE Brave

**Requirement:** 
In order to use Portis or Torus with Safari, currently the users needs to turn off Shield in Brave.

**Shields DOWN for this site**

<img width="222" src="https://user-images.githubusercontent.com/1683736/75063901-dfde7a00-54b3-11ea-8f34-9e90e0376186.png">

If you login with **Portis** you will see the below. [as of PR #6387]
<img width="333" src="https://user-images.githubusercontent.com/1683736/75064242-888cd980-54b4-11ea-8e9f-f3e39bc81e08.png">

If you login with **Torus** you will see the below.
<img width="333" src="https://user-images.githubusercontent.com/1683736/75064234-8460bc00-54b4-11ea-8c2c-bbad1f56208c.png" />

--------------

## ISSUE Safari
**Requirement**
In order to use Portis or Torus with Safari, currently the users needs to uncheck **Prevent Cross-site tracking enabled**
<img width="333" src="https://user-images.githubusercontent.com/1683736/75063948-f97fc180-54b3-11ea-851f-c2bebc4492dd.png">

Currently if a user tries to login with **Portis** we don't show the 3rd party cookie error. This is an issue I need to bring up with Portis. [#6349]

Currently if a user tries to login with **Torus** they will see the below.

<img width="333" src="https://user-images.githubusercontent.com/1683736/75064489-11a41080-54b5-11ea-9bce-6abcd0e73bd9.png">

## SUGGESTED FIXES

1) On Safari/Brave we disable Portis/Torus and only show Fortmatic
2) On Safari/Brave we should a caution/help icon besides login method with a tooltip and explain how to make browser compatible
3) On Safari/Brave we show a extra modal (Login, or on page load) that explains what they need to do to make browser compatible with Augur

**Comment by cillianhunter0** [comment]
options continued: 

4) If we can detect whether cookies are not enabled then show a message or modal that explains how to proceed

**Comment by cillianhunter0** [comment]
[Figma](https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=2045%3A1)

We're going with solution 4. 

If user is using Brave or Safari and tries to login/signup with portis or torus: 
- We will determine if they have cookies enabled
- If they don't have cookies enabled we will display a modal that explains they need to enabled cookies and display a "learn more" link with instructions on how to do this (link below)
- If they have cookies enabled the flow will proceed as normal 

Learn more link: 
https://www.whatismybrowser.com/guides/how-to-enable-cookies/?utm_source=whatismybrowsercom&utm_medium=internal&utm_campaign=breadcrumbs

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/7b1a858e-ee78-47c4-a3b9-8f53e4dbec94)
