### ISSUE TITLE
Bug: Buy/Sell text in notifications and alerts should match action the user took.

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#6392]
**Describe the bug**
When placing a BUY or SELL order, or when filling a BUY or SELL order, the notification toast and bell alert show the wrong direction.

**To Reproduce**
1. Go to any market
2. Make a BUY order
3. Check bell alert, it will say "Selling N and 0.X" in the alert.

**Expected behavior**
The direction should match what the user did.

If owner of order creates an ask order to put on the book then get filled, alert/toast should say
`"Selling N at X"` in the alert

If user creates a bid order to take an order on the book then the alert/toast should say
`"Buying N at X"` in the alert

**Comment by Chwy5** [comment]
Still looks incorrect....look at top toast message says sell and look at my position shows Long

![Screen Shot 2020-02-25 at 12.24.02 PM.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/053e51fd-3a99-4211-af3b-7e61a0252bc0)

**Comment by Chwy5** [comment]
fixed - closing
