### ISSUE TITLE
MC: designated reporter "someone else" label styling issue 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6402]
The "someone else:" label has no padding applied above or below. See [figma](https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=3962%3A115348) for correct padding. 

Build: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/1df172ab-bfd2-4e45-9de5-5d2c47dd2ac6)

**Comment by matt-bullock** [comment]
This is a duplicate. closing
