### ISSUE TITLE
Changes to navigation - Desktop only, mobile remains the same

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6405]
Remove add funds button from nav.

Market, Account Summary and Portfolio are now always the primary text colour. Only the blue underline is used to show they're active. This would mean there is no longer any  hover state.

Disputing, Reporting and Create Market are changed to 12px medium and are to become text secondary colour in their inactive states. In their active states the text becomes primary text colour and added blue underline. Again any hover state is no longer required - to be consistent with the menu items on the left. 

There is an inconsistency between the inactive states on the left side and those on the right side but this has been requested so that the items on the right are deemphasised.

Logged out state: Only show markets

Design: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=635%3A29484

Examples:

Markets active:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e08ddb24-3032-492f-a7cd-62f6ec8d0cd5)

Disputing active:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/3a414cbb-8ccf-43e3-933c-4a10e11c021d)

Logged out:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/963cf488-406d-4ca7-9d46-8c0ea960074e)

**Comment by phoebemirman** [comment]
@cillianhunter0 what about the migrate button?
![Screen Shot 2020-02-25 at 11.50.08 AM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/79488e1e-f2ef-46fb-9213-6db5dfdaad3b)

**Comment by cillianhunter0** [comment]
@phoebemirman let's put it to the left of the reporting link: 
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=14904%3A10205

**Comment by Chwy5** [comment]
This looks good but need to test migreate button appearing....if that is good please close

**Comment by matt-bullock** [comment]
Migrate REP button looks good on desktop

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/ee4a77e9-3807-4ec2-8364-5ef2a4c3347b)

@phoebemirman Mobile: can you line the migrate rep button up on the left with the other items

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/b74bb18e-293d-4a61-97fa-9c08e26a0237)

**Comment by matt-bullock** [comment]
looks good. closing
