### ISSUE TITLE
Placing Multi-Trade

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#641]
Still placing after 10+min. some bug here.

To reproduce just attempt a trade --- I'm in opera

**Comment by tinybike** [comment]
Yeah, it shouldn't take that long. Anything useful in the browser console? Also if you have them, can you post how much you tried to trade / on which market? Am probably going to need to drill into augur.js to debug and the more info I have to start with the better!

**Comment by joeykrug** [comment]
Now it seems to be working maybe.

Object {type: "CLEAR_TRADE_IN_PROGRESS", marketID: "0xc978674051154097d6604eecaff525a3316afb9d3d828d3f6980293e192e80d2"}

onTradeHash "0xfa9b175f16263448c22f8f2a6b860b97f597701c15f0185af4db13357a0450c1"

[multiTrade] trade: buy: onSent: Object {txHash: "0x5d7cdf87ab107f7455bc75eabd9bea7a4aa9d1a3bc9131ecb522cbd771f93885", callReturn: "0x000000000000000000000000000000000000000000000000000000000000

Object {type: "UPDATE_OUTCOME_PRICE", marketID: "0xc978674051154097d6604eecaff525a3316afb9d3d828d3f6980293e192e80d2", outcomeID: "5", price: 0.7552894060965627}

[multiTrade] trade: buy: onSuccess: Object {blockHash: "0x233024704d3987ce3636df74a320d179ef175752bdc4a0c9da1bced7ddefa010", blockNumber: "0x11c3d6", from: "0xd76c63db4f1cb072c2c6f7df6374df06f7685a64", gas: "0x2fd618", gasPrice: "0x4a817c800"…}

[multiTrade] trade: buy: onSent: Object {txHash: "0x2ac72fc661c605ce4c8009319cded6b73deef1012b98d7faa1de7421534f3499", callReturn: "0x0000000000000000000000000000000000000000000000000000000000000000"}

[multiTrade] trade: buy: onSuccess: Object {blockHash: "0x1f9c071829633004d15eb69f6cb147990028f6ace2107607e5381989beb46a25", blockNumber: "0x11c3d8", from: "0xd76c63db4f1cb072c2c6f7df6374df06f7685a64", gas: "0x2fd618", gasPrice: "0x4a817c800"…}


Issue with that is why is my buy call thing returning 0?

It does take away my money now, but i have 0 positions, so prob. doesn't work.

**Comment by joeykrug** [comment]
the trade function can't even return 0 hehe

**Comment by tinybike** [comment]
That is weird -- is the `callReturn` field in the `buy` `onSuccess` callback also 0?

**Comment by tinybike** [comment]
Closing b/c `multiTrade` is no longer a thing.
