### ISSUE TITLE
Market Orders

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#642]
Market order shouldn't place a bid but just consume what's on the book.

Not implemented yet but a suggestion ^

**Comment by tyche78** [comment]
I was just about to create an issue about the need for simplified buying/selling, but saw that it could be fused with this one. The current UI for placing trades is great for traders, not so much for the average user... I am myself a bit confused so imagine the reaction from the average guy (what do all these freaking numbers mean? I just want to bet on the presidential election!). 

I think there should be a simplified UI displayed by default with only market orders, and nice, big BUY/SELL buttons with percentage display and a neat green/red color. Then you could switch to the full "order book trading", if you want to.

**Comment by tinybike** [comment]
Moved to CH
