### ISSUE TITLE
Adjust net qty value calculation

### ISSUE THREAD

**Issue by nuevoalex** [AugurProject/augur#642]
The current net qty calculation is incorrect and produces values that are not helpful or sensible.

The way net qty for outcomes within a market should actually be calculated is as follows:

```
Short Position = exactly one outcome (x) owned == 0 ? min(owned of all outcomes but x) : 0;

Net Qty for outcome n = outcome n owned > 0 ? outcome n owned - Short Position : Short Position
```
Essentially when a user has a synthetic short position, of which it is only possibly to ever have 1 of, net qty for that short positions outcome is -(smallest owned position of other outcomes) and the net qty for every other outcome is the amount owned - (smallest owned position of other outcomes)

Right now this comes from AN so we can do this calculation from there still, but worth noting this and net qty could all theoretically come from chain data.

**Comment by pgebheim** [comment]
Done with PL merge
