### ISSUE TITLE
MC: update placeholder copy for designated reporter

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6423]
Update the placeholder copy in the 'someone else' option of designated reporter. 

From: 
"Enter wallet address"

To: 
"Enter Augur account address" 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/05e3524b-f7f9-439b-b288-82d6f7b4d0b4)

**Comment by Chwy5** [comment]
Closing not needed
