### ISSUE TITLE
ML: Additional markets banner should only apply to the market status tab you are viewing 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6428]
On the market list page we display a banner at the bottom of the list of markets if there are additional markets outside of any applied filters. 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/f177253b-e2dd-4869-9859-9c03c720df38)

If I have one of the market status tabs selected e.g. "Open", currently we are including any markets in "in-reporting" and "resolved" in that banner as additional markets. They should not be included. 

Changes: 
- [ ] Do not include the market status tabs "open/inreporting/resolved" as filters. 
- [ ] Only count markets **within** the tab I have selected e.g. "Open" AND outside of any filters I have applied as 'additional markets'

**Comment by Chwy5** [comment]
needs to be done post launch

**Comment by joeykrug** [comment]
needs to be done before, this is ***SUPER*** confusing and terrible UX w/o it fixed

**Comment by Chwy5** [comment]
closing
