### ISSUE TITLE
Add Positions / Open Orders section to Portfolio

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#643]
I want to see my:

- Positions
- Open orders
- Past trades

See UI Ron posted in UI channel for examples for this.

I should also be able to see how many shares I own of a given outcome directly on the market page [useful for selling etc.].  In old UI this was blah shares held.  Also would be useful to know how many outstanding shares there are in a market [shares issued for one outcome which is available on chain * numOutcomes].

**Comment by thinkloop** [comment]
There should be a comprehensive portfolio page that summarizes a user's entire net worth throughout the system

- This includes, at a minimum:

    - *positions in markets*: qty shares in each outcome, net gain/loss in each outcome, total value, total cost, total fees paid, total gas paid (if possible)

    - *open orders in markets*: qty shares in each outcome, bid/ask price, total gas paid (if possible)

    - *market-creator earnings*: total fees collected, total volume, total num trades, avg size trade, total open volume (whale watching reserved for another phase)

    - *summary of everything*: total value, net gain/loss, total fees + gas paid

**Comment by tinybike** [comment]
AURC screenshot again for reference:

![pasted image at 2016_07_11 02_37 am](https://cloud.githubusercontent.com/assets/2637020/16723277/d53bd8d2-4700-11e6-9cc8-45fa40b3c469.png)

**Comment by tinybike** [comment]
Combined #410
