### ISSUE TITLE
UI will sometimes not get SDK events after txn is confirmed

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6431]
I do a trade (sell 10 shares into an existing bid on the order book), 

My trade shows in open orders and spins processing.....
The order book decreases
My Available balance and Total order Value decrease

But my FF doesnt increase and I dont get a bell or toast message

**Comment by joeykrug** [comment]
status?

**Comment by bthaile** [comment]
@Chwy5 have you noticed this issue when not having wallet issues?

I do think there is a rare case when sdk doesn't send events to UI. I’ve only seen it once in the past few days. Couldn't repro again.

**Comment by bthaile** [comment]
I think the rare case the SDK didn't send events was do to it growing very large and sdk bogged down. Since that issue has been resolved, I don't think this is an issue anymore.

**Comment by Chwy5** [comment]
I havent seen this happen in a while

**Comment by pgebheim** [comment]
I'm gonna close this -- this hasn't happened in a while / the cases where we thought it was happening were other things.
