### ISSUE TITLE
OCHL labels on candlesticks look too dark

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6453]
Build:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/3e454c75-b681-4d2f-9b75-44b3b2013f2d)

OCHL labels should be text secondary colour.

Can you also remove the space between label and number

Design:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/4b1391f9-276a-4f49-80b6-0aeef653368f)

https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=1256%3A2999

**Comment by Chwy5** [comment]
fix post launch
