### ISSUE TITLE
Firefox bug on landing page banner 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6454]
The learn more button is HUGE! 

This is happening in Firefox on Windows and MacOS 

EDIT: 
- This appears to be impacting all buttons of the same type, see more screenshots below

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/a8cc9a8d-7a33-48c6-97ba-bcad5ec1bb96)

onboarding modal
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/8bc704ad-f519-42c4-843d-47dbaa54d4b4)

add funds
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/499a7172-6296-4797-825b-5707d61a4203)

**Comment by matt-bullock** [comment]
No longer seeing this
