### ISSUE TITLE
Torus signup in Chrome on windows - popup blocked 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6456]
Trying to sign up using torus on chrome on windows. 

The torus popup is blocked by chrome. 

If can change the setting to proceed but I think this should be fixable @andrewdamelio ?

**Comment by Chwy5** [comment]
hmm.... i dont get this on mine

can look for a work around post launch

**Comment by Chwy5** [comment]
should be looked into post

**Comment by pgebheim** [comment]
There's instructions for popup blockers if this happens.
