### ISSUE TITLE
Login - copy in modal is wrong 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6457]
When choosing one of the three login types, portis, torus, fortmatic the copy we display in the loading modal is confusing, it says: 
"Connecting to our partners at Portis to create your secure account."
this makes sense for signup not login. 

Let's update the login version of the loading modal to show: 
"Connecting to our partners at Portis to log you in to your secure account."

**Comment by joeykrug** [comment]
https://github.com/AugurProject/augur/commit/b0ca8ea9b72b7ec581f02c0b2aa2e0d07ee44c3d

took 30 seconds, why was this issue + discussion made and happened when it couldve been fixed in 30 s.?
