### ISSUE TITLE
Error when trying to use signup

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6458]
Tested on firefox on windows. 

I'm getting this error if i click the login or signup button too quickly: 

"Something went wrong
API must be initialised before use." 

It seems to appear if i click it before the markets have loaded. I'm not sure what it means or what i should do. 

@andrewdamelio what's triggering that? we can improve that copy, i'm just not sure what's going on.

**Comment by Chwy5** [comment]
not seeing this - closing
