### ISSUE TITLE
Test trade bug on Brave on Windows 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6460]
The exit the trade bar at the top of the page is cut off. 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/92298437-fb0f-4b76-a5a3-16931f73e66e)

**Comment by pgebheim** [comment]
@phoebemirman did you get this one verified as working?

**Comment by phoebemirman** [comment]
I haven’t been able to test because i don’t have windows. But fixed recent
issues with test trade. Is it still happening?

**Comment by pgebheim** [comment]
I'll try it now!

**Comment by pgebheim** [comment]
![image](https://user-images.githubusercontent.com/86010/80986078-ea3abf80-8de4-11ea-8825-a512b23093ec.png)
