### ISSUE TITLE
Add processing state to dispute cards after user confirms the transaction in the dispute/support form

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6461]
Required for both supporting and disputing buttons as feedback to let the user know the transaction is processing.

Button should be disabled and be at 50% opacity.

Button design: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=8223%3A4544

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/8aa2010d-3658-4b37-8413-a7e8ca867d11)

**Comment by Chwy5** [comment]
fixed -closing
