### ISSUE TITLE
MultiSig Error - Refreshing shouldn't break stuff / fix other multisig errors

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#6465]
Idea:
  - Store the most recently signed nonce in IDB in the ContractDependenciesGnosis, so that multiple tabs can share a signing nonce.
  - On error, this will need to be reset to the earliest nonce still queued for delivery.
  - On startup, ask the contract AND the relayer for the current nonce.
    - Contract via the normal contract call
    - Relayer, find the highest nonce on /transactions endpoint, then +1

### Updates from deepdive (Andrew)

It seems like despite efforts to manage the nonces (for single TAB, multi TAB) using the gnosis relayer TX endpoint + the gnosis contract,  the issue around incorrect nonces still seems to happen.

#### Ghost/Missing TX's error 

I've seen the below issue happen before with brand new wallets, as well as wallets that have some usage.

I asked the transactions endpoint for my TX count it returns 1 where the gnosis contract returns 0.
```
https://gnosis.kovan.augur.net/api/v1/safes/0xed576A195730deE063E113A68108f91db7131B5b/transactions/

https://kovan.etherscan.io/address/0xed576A195730deE063E113A68108f91db7131B5b

```
So this is a case where my wallet appears dead as its seems impossible to get out of this situation via the relayer, since providing a nonce of 0 will return a `SafeMultisigTxExists: Tx with nonce=0 for safe=0xed576A195730deE063E113A68108f91db7131B5b already exists in DB. Skipping TX.`  error and providing any other nonce will return an Invalid Owner error.

In these cases i'm not sure how we should proceed.  

I've been able to fix this by throwing the UI into relayer down mode, and forcing the next TX to be sent directly, which seems to fix things.

Seems like we may need to update the relayer to relax some rules around sending TX's with future nonces to handle our UI's sending queues.

**Comment by andrewdamelio** [comment]
@pgebheim updated ticket with my recently findings

**Comment by andrewdamelio** [comment]
closing since GSN updates will address this
