### ISSUE TITLE
Add additional filters to UI

### ISSUE THREAD

**Issue by kevinday** [AugurProject/augur#647]
@tinybike mentioned that we should add the additional filter types to the UI. The types that augur.js supports can be found here:
https://github.com/AugurProject/augur.js/blob/master/src/constants.js#L34

Currently the UI is only listening to 4 events:
https://github.com/AugurProject/augur/blob/3b4c04d2e0d090a53d0dca3c0271980161a3df19/src/services/augurjs.js#L198

I will defer to @thinkloop or @tinybike for what the UI needs to do with these events.

**Comment by tinybike** [comment]
Added in bc2ce0699212ea19bd059be8cd0891ff9fbcc46b
