### ISSUE TITLE
trading tutorial not opening at smaller desktop sizes

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6481]
![Kapture 2020-02-27 at 11.55.40.gif](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/8664a036-fa58-407a-8f8e-582688f3cf70)

**Comment by phoebemirman** [comment]
the tutorial is not available at tablet and mobile sizes, so i hid the button in those cases.

**Comment by matt-bullock** [comment]
@phoebemirman I'm still seeing the button at smaller sizes.. where clicking it does nothing 

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/76034684-3c1c-4e7a-9306-7f839381a435)

**Comment by phoebemirman** [comment]
what screen size is that?

**Comment by Chwy5** [comment]
I dont see it on Ipad pro or mobile

![4-18ip.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/3075db79-0c21-49e1-91b2-69dbbe0bf5d8)

**Comment by phoebemirman** [comment]
Yea it is supposed to be hidden there.

**Comment by matt-bullock** [comment]
Not seeing issues anymore. closing
