### ISSUE TITLE
Outcomes should truncate with ellipsis if they don't fit

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6485]
Can we also add a hover state to show the full outcome - tooltip style

This is how it currently cuts off in the build

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/16f5b19d-435d-4f6e-b460-ae3cd7bb72e6)

**Comment by joeykrug** [comment]
It should show full name w/ hover too

**Comment by Chwy5** [comment]
fixed - closing
