### ISSUE TITLE
REP migration update 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6486]
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=14936%3A224

IF user has V1 REP in GS, THEN show option 1
IF user has V1 REP in wallet, THEN show option 2
IF user has V1 REP in GS AND WALLET, THEN show option 1, when complete, THEN show option 2 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/2252fc21-7f91-4098-9926-1729c5df5beb)

**Comment by cillianhunter0** [comment]
Spotted an issue that's confusing. 

When you have v1 rep in your GS, the tooltip says: 
"You have V1 REP in your wallet. Migrate it to V2 REP to use it in Augur V2."
You don't, it's in your 'augur account address' etc. 

We can reduce the confusion here by having two versions of this: 

1: IF user has v1 rep in their GS (or IF user has v1 rep in both GS and wallet) 
"You have V1 REP in your Augur account address. Migrate it to V2 REP to use it in Augur V2."

2: IF user has v1 rep in their wallet 
"You have V1 REP in your wallet. Migrate it to V2 REP to use it in Augur V2."

**Comment by cillianhunter0** [comment]
@andrewdamelio is there any way i can test the modal with legacy v1 rep in my MM wallet? Not sure how i can send legacy rep from GS to my wallet?

**Comment by cillianhunter0** [comment]
Confirmation state of button is broken: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/d0dd1bcd-3e19-49cb-bcd3-c29bed8b3fd4)

Typo in the version of the modal when v1 rep is in wallet: 
first word of second paragraph "then" -> "When"

**Comment by cillianhunter0** [comment]
Failed state of button is broken: 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/5f9795f8-6c60-4cc2-a7d8-f67bc7d7b496)

Confirm state of button is still broken in chrome. (you can remove the X from this button if it will fix the problem, as it's not needed in this case. this doesn't apply to the fail state) 
and
It disappears too quickly. The confirmed state should show for 3 seconds before being removed.
![Kapture 2020-03-04 at 11.09.54.gif](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/b1a4f3f8-c43c-4b2f-b8ee-b74148ed036f)

**Comment by cillianhunter0** [comment]
All issues above are fixed. 

I spotted an issue that's impacting the whole page at ipad resolution (between 768 to ~800).

Open the page at 768px width, when the migrate REP button appears it breaks the layout, see the left side of the page flowing outside of the browser window:

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/05cad230-65f7-4774-9e88-630e053e8398)

**Comment by JohnDanz** [comment]
for the comment mentioned above by Chwy, I would think the best way to handle this is to reduce the space to the left of the migrate button. the fillSpace LI should most likely be refactored/removed and instead we can apply a `margin-right: auto` to the 3rd LI (portfolio) so that we have a bit more flexibility here. I would also look at why we have such strict left/right padding on each LI so as to crunch up things like `account summary` and `create market` when ideally they don't break into 2 lines if there is still space to be used.

**Comment by bthaile** [comment]
@andrewdamelio  see John's comment.
