### ISSUE TITLE
MC: dropdown menus with long strings have some bugs 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6498]
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/efbd84ec-3ef5-4d31-8d8f-47c0bc7a92af)
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/45d79f0b-012d-4c07-bbbe-16bd9f9ca902)

[Figma](https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=8219%3A265580)

When a dropdown has a value with a lot of characters there are two issues: 
1) the dropdown menu itself runs off the screen
2) when the user selects the value with a lot of characters, the dropdown input itself runs off the screen

We should always have a max width applied to both so this can't happen. 

Here's how we can fix the situation: 
- apply max widths to dropdown inputs and the menu 
- if one of the values is super long allow it to break on to two lines
- if the super long value is selected, truncate the text with ... so it doesn't force the input to run off the screen, i.e. it should maintain a max width 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/7d2c488e-efd6-42d6-aa77-7b5f23aa49b5)

**Comment by Chwy5** [comment]
fix post
