### ISSUE TITLE
Add referral link to account dropdown 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6499]
Add referral link as a row to the account dropdown. 

Desktop [figma](https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=1808%3A5290)
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/694d00e8-c671-4690-b4dd-c38fa80c4a4f)

Mobile [figma](https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=1819%3A507)
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/02d4ac75-be35-4ec5-9a27-a4790a839031)

Tooltip and copy link interactions [figma](https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=455%3A7436): 
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/428b92da-521d-4799-b437-2ab15527c7aa)

**Comment by Chwy5** [comment]
I dont see this added
