### ISSUE TITLE
URLs needed for migrate rep modal - HC links 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6501]
We need two HC links for the rep migration modals 
1) migrating v1 to v2 rep
2) general learn more about augur account address

two modals: 

1
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/c9de081d-42ef-4759-9c3a-b2642dfeea40)

2
![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/53446438-8cda-4b7d-ac3d-578dd59ed187)

**Comment by Chwy5** [comment]
waiting for copy from @petervecchiarelli

**Comment by andrewdamelio** [comment]
@petervecchiarelli any updates? Can you ping me when the URL's are ready! thanks

**Comment by matt-bullock** [comment]
links are in. closing
