### ISSUE TITLE
Augur-node error on startup (isInvalid binding error)

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#652]
Error when starting against local dev chain.

`Undefined binding(s) detected when compiling FIRST query: selectpayoutIdfrompayoutswheremarketId= ? andisInvalid= ? limit ?`

**Comment by adrake33** [comment]
@epheph Can you please look into this?

**Comment by epheph** [comment]
Yea, justin and i talked about this one, i'll take care of it. It's due to the contract change

**Comment by epheph** [comment]
I started work on this, but then realized a LOT more is broken. However, it seems that this never got merged: #346 . This looks to take care of a lot of new v2 contract changes

**Comment by adrake33** [comment]
Closing since #346 got merged
