### ISSUE TITLE
Some markets not showing their resolved state cards when in the resolved markets section

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6531]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/63a1174d-0e27-459d-8f31-7ce852fdebae)

**Comment by phoebemirman** [comment]
fixed here https://github.com/AugurProject/augur/pull/6690

**Comment by bconfortin** [comment]
@phoebemirman Thanks. Asked Matt about 1 hour ago how to reproduce because I wasn't able to, but I guess he has already stopped working for the day (timezones).

**Comment by matt-bullock** [comment]
looks fixed. closing
