### ISSUE TITLE
Missing warning message - user about to consume own order in the order ticket 

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6537]
If a user is about to trade with themselves ( hit or lift their own existing order) we show a warning message in the order ticket.....this is now missing

**Comment by phoebemirman** [comment]
<img width="355" alt="Screen Shot 2020-03-03 at 10 31 36 AM" src="https://user-images.githubusercontent.com/6775839/75807570-745d9d80-5d3a-11ea-821d-c97605cfd51d.png">

i'm seeing this. what market was it not working for you @Chwy5 ?

**Comment by Chwy5** [comment]
I see it in some markets....but this market I have a bid in Invalid and when i click on the order in the order book nothing happens.....This is a multiple choice market....could it have something to do with that?

https://v2.augur.net/#!/market?id=0x09277F8964794BA562Af53712a4B3486980e74CA

**Comment by phoebemirman** [comment]
haven't been able to repro but will keep eye for it

**Comment by phoebemirman** [comment]
seems this was covered here https://github.com/AugurProject/augur/issues/6761
