### ISSUE TITLE
UI bug when scrolling the side nav on mobile 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6544]
Login, open the side nav, open the account dropdown, then scroll down. 

The background behind the "x" and (?) tooltip isn't fixed and the content below scrolls underneath them. 

The top row should be a solid sticky bar that content scrolls behind. 

![Kapture 2020-03-03 at 17.33.57.gif](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/d30d48dd-e4d2-4533-ab9e-d07fa07be77c)

**Comment by Chwy5** [comment]
need to be fixed post launch

**Comment by joeykrug** [comment]
game breaking looks terrible, needs fixing

**Comment by matt-bullock** [comment]
looks good now. closing
