### ISSUE TITLE
bug on dispute card when reporting on invalid scalar / only two outcomes

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#6546]
see less/more arrow
![Screen Shot 2020-03-03 at 10.17.51 AM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/6e93c468-fe26-4262-a128-e6718ccfc037)

when you click arrow:
<img width="1118" alt="Screen Shot 2020-03-03 at 10 19 04 AM" src="https://user-images.githubusercontent.com/6775839/75806414-74f53480-5d38-11ea-996d-ce56c773d630.png">

**Comment by matt-bullock** [comment]
looks fixed
