### ISSUE TITLE
(x) is missing from open orders on both the trading and portfolio pg

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6547]
It appears the (x) to cancel orders has shrunk...needs to be fixed so user knows they can cancel open orders

![3-3x.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/4d53f736-7225-4803-9119-f102cd61a918)

**Comment by matt-bullock** [comment]
Close button is how it should be now. closing
