### ISSUE TITLE
Mobile order book issue - offer side is auto scrolling to highest offer

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6564]
In order to recreate, go to this market and you'll see the first time you come here the offer side loads as it should and scrolls as normal

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/9056d502-1454-413a-934b-0f04a90f7dda)

After scrolling, leave the page by clicking on market info tab or viewing the trades for another outcome and then returning to the first outcome. You'll find the offer side has either scrolled up to show the highest offer or will not scroll but then loads in showing the highest offer like so:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/2ed100b4-1036-488b-9ab8-2ead3df107c0)

**Comment by Chwy5** [comment]
This needs to show the Best offer (lowest offer available to be taken)

**Comment by matt-bullock** [comment]
I'm testing outcome London in [this market](https://v2.augur.net/#!/market?id=0x09277F8964794BA562Af53712a4B3486980e74CA) on my mobile using chrome. It loads in showing the best offer but after a split second it is scrolling up to show the highest offer @JohnDanz

**Comment by matt-bullock** [comment]
Unable to load larger order books on my phone currently. Need to wait for something to get fixed before I can test

**Comment by matt-bullock** [comment]
fixed now. Closing
