### ISSUE TITLE
betting/sports - Icon Check

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#6577]
https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet---Design-System?node-id=0%3A5

![Screen Shot 2020-03-04 at 11.39.34 AM.png](https://images.zenhubusercontent.com/57155267bf93871ccd99a48b/751fc31e-82e2-4c1a-ae72-8c436f8cabdd)

Confirm we have all of these icons already and if not add them. Make sure not to include a width/height attribute or any fill/stroke colors. These values should be applied with CSS to ensure we can change them per UI/dark/light backgrounds as needed.

**Comment by rubyweb3** [comment]
Close?
