### ISSUE TITLE
Tooltip for failed tags needs correct copy

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6592]
As it's currently using the copy when in the processing state.

Let me know if we don't have copy for this and we can quickly put something together

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/c6d3dd3e-2487-4f6d-97a4-e1df15a8e95c)

**Comment by bthaile** [comment]
That is the tooltip for the processing indicator. we don't have one specifically for failed. looking at the code there should not be a tooltip if failed.

**Comment by bthaile** [comment]
![image](https://user-images.githubusercontent.com/3970376/83524542-5e7e8680-a4a9-11ea-953b-828c6d7303dd.png)


I don't see a tooltip and we have a new failed format for portfolio.

**Comment by matt-bullock** [comment]
No longer relevant. Closing
