### ISSUE TITLE
Changes to market page when invalid is selected on a scalar market + open order and filled orders for invalid in portfolio

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6596]
**Market page changes is only when having the invalid outcome active on scalar markets**

---

**Outcomes list**

Best bid and best ask change from total order value to showing the percentage + show a percentage sign after them

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/09bf0387-4136-4c24-91bd-fad1b5322947)

---

**Order Book**

Add (%) next to price

Price should show the percentage value rather than total order value

Spread should show the percentage inc. percentage symbol

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f0979573-d6dc-4339-ae1c-eb1906939863)

---

**Trade History**

Add (%) next to price

Price should show the percentage value rather than total order value

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/51e0a985-7010-4177-a2a6-4be080709ea5)

---

**Open orders and Filled orders (changes to both market page and portfolio)**

Change the price from total order value to the percentage - only on the invalid orders

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/6e3e60a1-048c-4d01-8d90-195c5f8be229)

**Comment by Chwy5** [comment]
fixed -closing
