### ISSUE TITLE
Buy order appears as SOLD in My fills 

### ISSUE THREAD

**Issue by cillianhunter0** [AugurProject/augur#6599]
I placed 2 x buy orders, they filled and toast/bell message are accurate. 

But they appeared as SOLD in My Fills 

![image.png](https://images.zenhubusercontent.com/5c7591d7eec15745ffae99b1/f2c7b267-a7ea-466c-9cc5-55d5fcb9cb62)

**Comment by Chwy5** [comment]
fixed - c;losing
