### ISSUE TITLE
Sports Betting - Update Modal Styles

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#6601]
https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet---Design-System?node-id=17%3A12

Update/check that all in use modals are styled correctly. This could be a shorter task than I've estimated but be thorough. Also in the process, identify modals that are no longer in use or are extremely rarely used/are very similar to another type of modal. This way we can clean up some older components.

**Comment by rubyweb3** [comment]
Close?
