### ISSUE TITLE
Sports Betting - Update Open/resolved labels

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#6605]
https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet---Design-System?node-id=17%3A12

![Screen Shot 2020-03-05 at 12.14.28 PM.png](https://images.zenhubusercontent.com/57155267bf93871ccd99a48b/e44c8b91-7729-4edd-bdcd-d4254fdb888c)

Update the open/resolved labels to match the new design, (in reporting/disputing are a separate ticket).

**Comment by rubyweb3** [comment]
Close?
