### ISSUE TITLE
Sports Betting - Positive alert bars

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#6607]
https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet---Design-System?node-id=17%3A12

![Screen Shot 2020-03-05 at 12.17.31 PM.png](https://images.zenhubusercontent.com/57155267bf93871ccd99a48b/78423284-f0b7-4861-8b6c-4c0e30163ed7)

Not actually sure if we currently show these or not, if we don't then create a CSS class that can be applied to the warning/error bars that are referred to in another ticket assigned to you.

**Comment by rubyweb3** [comment]
It's implemented in https://github.com/AugurProject/augur/commit/1c12d5055f3d784a4ef7a082a10b6696cf3eb5fd

![Screen Shot 2020-04-28 at 11 46 00 AM](https://user-images.githubusercontent.com/58647954/80445044-e111a480-8945-11ea-8c64-852c6771f31e.png)
