### ISSUE TITLE
UI Redesign - Create Market

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#663]
Main goals and user story: A user wants to create a market on Augur that is well specified, while understanding how to create one such that they don't lose money from making a poor decision but also while maximizing visibility of their market by appropriately wording it, choosing categories + tags + fees + making it valid, and knowing to add liquidity at fair prices to encourage trading.

Problem: not always noticeable which button or field you are on
Solution: Make sure the focus state for the buttons is noticeable #524

Problem: users aren't adding initial liquidity
Solution: Encourage users to add initial liquidity and explain why it's important #524

Problem: users sometimes refresh the page or get disconnected or exit augur and not all their initial liquidity goes through
Solution: #582

Problem: small design nits
Solution #364 

Problem: user can't see total amount of eth when creating a market:
Solution: #522

Problem: users don't understand what all the words mean in market creation:
Solution: #411 

Problem: while categories have autocomplete, tags don't
Solution: #527 

Problem: users are accidentally doing "category,category,category" instead of "category" and "tag", "tag" etc and possibly choosing unpopular tags for their market.
Solution: #526

**Comment by joeykrug** [comment]
Needs max market length stuff for v2, referral stuff

2) Market creation should show what # your market would rank in the default sort based on the liquidity you're adding
3) When adding liquidity to a market, if you have sell orders for all outcomes, it should buy complete sets first for min(quantity of asks on outcomes list) so it uses less $$$ for the same liquidity

@cillianhunter0 @matt-bullock @Chwy5
