### ISSUE TITLE
Sports Betting - New Market Cards

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#6659]
https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet---Design-System?node-id=136%3A0

![Screen Shot 2020-03-09 at 12.25.06 PM.png](https://images.zenhubusercontent.com/57155267bf93871ccd99a48b/255bf91e-2a77-418f-bd3e-e34d94eeecf4)

![Screen Shot 2020-03-09 at 12.25.29 PM.png](https://images.zenhubusercontent.com/57155267bf93871ccd99a48b/74dcc4ac-ac60-4228-84cb-21179ffbc85a)

![Screen Shot 2020-03-09 at 12.25.56 PM.png](https://images.zenhubusercontent.com/57155267bf93871ccd99a48b/e03f5f7f-e967-43f3-9096-714b6f36fd52)

For now these will use dummy data and be mocks essentially... might not link to actual markets etc.

**Comment by pgebheim** [comment]
Making an epic 'cause this will contain a bunch of different things related to market cards changes,

**Comment by JohnDanz** [comment]
This has proven to be useless/noise going to close.
