### ISSUE TITLE
Bell message doesnt match tx

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6684]
There was 3 bids on the book:

.3 for 10
.25 for 10 
.2 for 10

I sold all 30 at once....I only get a filled bell notification for one of the 3 trades

![3-10bell.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/bdae4868-9833-4b00-8a00-cc34456d0153)

**Comment by Chwy5** [comment]
still having the same issue.....

to replicate In Account 1 add 3 Open orders:
Buy 10 at 35
Buy 10 at 30
Buy 10 at 25

Go to second acct....Click on the bottom order in the order book (sell 10 at 25)....the order ticket should filter in selling 30 at 25.....then execute the trade to sell all 30 shares....the bell notification is only showing the last 10 lot of the 30 lots (3 10 lots)

![3-12p.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/3620f55d-04da-4f17-bcf3-5c593a4064de)

**Comment by phoebemirman** [comment]
the PR wasn't merged actually got stuck in CI. Sorry about that

**Comment by Chwy5** [comment]
fixed - closing
