### ISSUE TITLE
when on disputing page and dispute time runs up, market card does not update and sticks around

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#6687]
<img width="1108" alt="Screen Shot 2020-03-10 at 12 50 31 PM" src="https://user-images.githubusercontent.com/6775839/76353344-c91a8e80-62cd-11ea-99d1-39300676f34e.png">

**Comment by matt-bullock** [comment]
@phoebemirman I have to manually push time to test this as using fake time docker doesn't move time until pushed. It disappears from the disputing page when I do this but I'm not sure what would happen if the time was automatically ticking over. Presumably the card would disappear from the disputing page?

I'm closing unless you think this needs any further testing
