### ISSUE TITLE
markets in awaiting finalization are missing winning outcome

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#6688]
<img width="1221" alt="Screen Shot 2020-03-10 at 12 56 14 PM" src="https://user-images.githubusercontent.com/6775839/76353785-9755f780-62ce-11ea-939b-de39ee6a0c57.png">

**Comment by matt-bullock** [comment]
@phoebemirman I'm having issues with local and can't reproduced getting a market into awaiting finalisation. It just finalises automatically before I can claim proceeds - which I believe should trigger finalisation.

Can you post a screenshot if you're able to reproduce and I'll get this closed

**Comment by phoebemirman** [comment]
this is one
![Screen Shot 2020-03-13 at 10.07.44 AM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/766c8e73-067a-4391-8d2f-cf616471901c)
