### ISSUE TITLE
Template fixes - Sports Season Updates

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6693]
Need to remove now that the seasons are cancelled:

NFL (multiple Choice and Yes/No Awards) remove the 2019-20 from dropdown

NBA Templates are missing 2019-20 from the year range selector on bottom 2 templates in Yes/No, bottom 3 templates in Multiple choice and the NBA scalar

Looks to be similar issue with Hockey too...missing 2019-20 range on year picker templates

**Comment by Chwy5** [comment]
moving to blocked/feedback needed...do not do until we confirm seasons are fully cancelled and not being restarted

**Comment by bthaile** [comment]
NBA templates years has been fixed

![image](https://user-images.githubusercontent.com/3970376/82685001-22316780-9c19-11ea-998e-ba6472355ea8.png)


hockey has been fixed
![image](https://user-images.githubusercontent.com/3970376/82685099-4725da80-9c19-11ea-8ed0-547c69281e16.png)
