### ISSUE TITLE
Pre-Launch Testing

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#6699]
- [x] Make sure to test the wallet that JUST has dai
- [x] Test trading
- [x] Warp Sync
- [x] Reporting
- [x] Affiliate Fees
- [x] Hosted SDK
- [x] IPFS Stable Loader
- [x] Forking
- [x] Google Translate - https://github.com/AugurProject/augur/issues/8240
- [x] Eth Nodes
   - [x] Cloudflare WORKS
   - [x] All Wallets
   - [x] Slockit (current fails to fetch old blocks on Kovan)
- [x] Test multiple reporting staking scenarios to make sure everything is working there.
- [ ] Test failures from pruning (where could the UI break?) - https://github.com/AugurProject/augur/issues/8241

**Comment by pgebheim** [comment]
Adding this to launch milestone so we run through it all again
