### ISSUE TITLE
Create Market: Replace "trading fee" with "taker fee" and re-define "maker fee" to be independent

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur#670]
Currently we have:

`trading fee`: % of total value of trade (ie 2%)
`maker fee`: % of `trading fee` (ie 50%)

We are simplifying this paradigm so that a `taker fee` and `maker fee` can be specified more independently of each other, and dropping the concept of `trading fee` from the ui. In the market creation process, the fee inputs should be:

`taker fee`: % of total trade value (ie 2%)
`maker fee`: % of total trade value *but not higher that 50% of taker fee* (ie 1%)

The only limitation is that the maker fee cannot exceed half of the taker fee. Ex: if taker fee is 3% maker fee can be between 0 and 1.5%.

These fees will also be passed into augurjs for the createMarket functionality, so this issue is dependent on this one: https://github.com/AugurProject/augur.js/issues/85

And the related UI work: https://github.com/AugurProject/augur-ui-react-components/issues/36

**Comment by stephensprinkle** [comment]
PRs #675 + AURC [#42](https://github.com/AugurProject/augur-ui-react-components/pull/42) resolve this issue -- closing.
