### ISSUE TITLE
Trust this dapp fix

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#6700]
- wallet approvals thing trust this dapp get working so user doesn't need to auto approve more than once every time they use augur - Andy

**Comment by andrewdamelio** [comment]
To test cookie/trust this dapp i created an IPFS instance of v2 [here](https://ipfs.infura.io/ipfs/QmNgv7XTwJy7L9wpRzFnC3dZBrf2pBQCh19X9gtSA3mvZk/) embedded in a iframe to test if wallet providers (Portis, Fortmatic and Portis) leak cookies between sessions. 

To Test:
1) Head over to v2.augur.net and loign with a wallet provider
2) Once you are logged-in close the tab
3) Open a new tab and navigate to https://ipfs.infura.io/ipfs/QmNgv7XTwJy7L9wpRzFnC3dZBrf2pBQCh19X9gtSA3mvZk/
4) Login with the saame provider --- YOU should be prompted to LOGIN AGAIN

Results: 

Portis:
NOPE - keeps sessions 😢 

Fortmatic
Yup -- forces you to login again 😄 

Torus
Yup -- forces you to login again 😄

**Comment by pgebheim** [comment]
The only thing left to do with this unless we get some support from Portis is to decide to pull the integration until it works.

**Comment by pgebheim** [comment]
Tom from Portis says they can add a setting to now persist sessions for the augur key. Moving to rc2 to continue following up.

**Comment by andrewdamelio** [comment]
tested the Portis setting on their staging. Works as expected, i was requested to re-login when navigating between sessions.

**Comment by pgebheim** [comment]
Ok, this is gonna stay open until we Portis has deployed. Moving into RC3 for confirmation.

**Comment by pgebheim** [comment]
@andrewdamelio -- did portis deploy this change yet?

**Comment by pgebheim** [comment]
![image](https://user-images.githubusercontent.com/86010/82973162-8fcbf380-9f8b-11ea-9d43-2aeb455f3061.png)

Portis deployed!
