### ISSUE TITLE
Add Copy to learn more for gsn: add screen to onboarding that introduces the idea of charging a one off initial fee to initialize the users account and join the network

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6708]
Add this copy to "learn more":

Augur runs on a peer-to-peer network which requires micro-fees to be paid in a digital currency called Eth for actions such as making trades.

In order to facilitate the ability for you to both trade and pay for transactions using only one currency, DAI ($), a small one-time fee will be automatically paid on your behalf when joining Augur. This fee is not collected by Augur.

--------------------------------------------------------------------------------------------------------------

This should come after the Add Dai to your account screen

Desktop:

https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=2113%3A26

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/1b501751-0bc1-4f26-b002-5d4bb4c3890c)

Mobile:

https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=2117%3A302

**Comment by matt-bullock** [comment]
looks good. We need to add a link to the learn more. @petervecchiarelli do you have place in the help section this can link to? Feel free to suggest any edits to the copy in this onboarding screen

**Comment by petervecchiarelli** [comment]
can someone give me figma access or show me what before/after steps are for more context?

**Comment by matt-bullock** [comment]
@petervecchiarelli you can see the before and after steps in the signup flow

**Comment by petervecchiarelli** [comment]
Can link here: https://augur.gitbook.io/help-center/trading-ui-1/signing-up#gas-station-network

How about something like this:

Augur runs on a peer-to-peer network which requires micro-fees to be paid in a digital currency called Eth for actions such as making trades. 

In order to facilitate the ability for you to both trade and pay for transactions using only one currency, DAI ($), a small one-time fee will be automatically paid on your behalf when joining Augur. This fee is not collected by Augur.

**Comment by matt-bullock** [comment]
Just waiting for copy to be added to the help section. @petervecchiarelli please close when done

Add this copy to "learn more":

Augur runs on a peer-to-peer network which requires micro-fees to be paid in a digital currency called Eth for actions such as making trades.

In order to facilitate the ability for you to both trade and pay for transactions using only one currency, DAI ($), a small one-time fee will be automatically paid on your behalf when joining Augur. This fee is not collected by Augur.

**Comment by petervecchiarelli** [comment]
copy added, closing.
