### ISSUE TITLE
Design - Price Oracle

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#671]

**Comment by pgebheim** [comment]
@nuevoalex - Poke!

Could you mark this and related tickets closed / won't fix or whatever needs to happen?

**Comment by nuevoalex** [comment]
@pgebheim  Since we're doing the auction I suppose this issue is to create a design for the auction in the UI?

**Comment by pgebheim** [comment]
Ah good call!

@Chwy5 -- @cillianhunter0  -- Do you wanna keep these Design tickets in github or is that not part of your process yet?

**Comment by Chwy5** [comment]
Doesnt need to be in GH yet...Im adding it to our sheet for timeline review

**Comment by pgebheim** [comment]
Ok, closing -- we can make tickets for this when its design that make sense.
