### ISSUE TITLE
Filled order toast and bell alerts not making sense

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6728]
bottom message is me placing an open order of 50 @ .6.

Chwy then took 20 of this order.

The following two messages are what I saw after Chwy took the order

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/6738d6ed-9562-42d1-8331-62c0295042d2)

**Comment by Chwy5** [comment]
looks fixed closing
