### ISSUE TITLE
Average price is showing different values for Position vs Filled orders

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6737]
Could be SDK calaculates one spot and UI is calculating the other

See screenshot

 i am seeing 2 different prices (not sure if it is a rounding issue)...bottom right are my 3 fills (avg price s/b 30)
![3-12price.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/0bf4fb52-2260-4e53-bfbb-1945ca549c09)

**Comment by Chwy5** [comment]
Still seeing this Occur....To replicate In Acct 1 add buy orders of:
Buy 10 @.25
Buy 10 @ .24
Buy 10 @.22

In different acct sell all 3 trades at once:

![3-21ap.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/382fba97-9eed-434e-9ddd-f85296fc963d)

**Comment by nuevoalex** [comment]
Couldn't repro on a local instance. This is actually a different issue than what I addressed FWIW. The contract issue was that the price was actually  incorrect. This appears to be a rounding discrepancy in two different parts of the UI. That said as I mentioned I couldn't repro and it didn't seem like these two values should ever differ, but I don't know my way around the UI as we as @bthaile who could maybe take a look.

**Comment by Chwy5** [comment]
still off, see screenshot

![3-30avg.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/d4594280-135c-4712-a291-fea19f746dff)

**Comment by Chwy5** [comment]
fixed - closing
