### ISSUE TITLE
Fix formatNumber regression

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur#674]
A few commits ago we were using `toLocaleString` to format numbers:

```
o.formatted = o.formattedValue.toLocaleString(undefined, { minimumFractionDigits: decimals, maximumFractionDigits: decimals });
o.rounded = o.roundedValue.toLocaleString(undefined, { minimumFractionDigits: decimalsRounded, maximumFractionDigits: decimalsRounded });
o.minimized = o.formattedValue.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: decimals });
```

This did many nice things:

- add thousands separator: ie `1,000,000`
- round numbers between a range of decimal places, so that it leaves out 0's. For example if you had the number `1.00`, and `minimumFractionDigits` was `0`, the number would be formatted to `1`, dropping the unnecessary zeros.
- show locale specific formatting like using a comma instead of a period for decimals, etc

It turned out that performance of toLocaleString was terrible, and causing serious lockups, so it was replaced with `toFixed`. However this replacement lost a lot of the formatting we want. This issue is about reimplementing that formatting using basic string manipulation.

Specifically:

- `o.formatted`: add thousands comma separator
- `o.rounded`: add thousands comma separator
- `o.minimized`: add thousands comma separator, remove trailing zeros in decimals

Please add detailed tests as part of this issue to ensure that formatting regressions don't happen in the future.

We will be ignoring internationalization for the time being.

**Comment by stephensprinkle** [comment]
PR #680 resolves this issue -- closing.
