### ISSUE TITLE
Countdown timers to change every second instead of blocks of 4-5seconds

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6744]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/3f6ac78d-c45d-45bb-826a-d9703f5cf6d0)

**Comment by Chwy5** [comment]
Need to smooth out timer.....not use block time

**Comment by Chwy5** [comment]
Timing is still all off.....the order disappeared from the order book and other outcome table around 58 seconds - the order showing in open orders....still looked to be jumping in 7 second intervals instead of by seconds

**Comment by bthaile** [comment]
this is what I see

![timer-open-order](https://user-images.githubusercontent.com/3970376/76671081-4b22e580-6562-11ea-85ac-127372cf0101.gif)

The order gets removed from the orderbook before it expires. It gets removed from the open orders section in UI when it actually expires. That was the plan, so the user can see it fully expire and not wonder what happen to it.

**Comment by Chwy5** [comment]
fixed looks much better closing
