### ISSUE TITLE
forking market cards visually messed up

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#6748]
![Screen Shot 2020-03-13 at 11.35.57 AM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/4eef75b7-ea9e-4f31-a6f0-f9904334f87d)

<img width="1258" alt="Screen Shot 2020-03-13 at 11 35 41 AM" src="https://user-images.githubusercontent.com/6775839/76650259-71736180-651f-11ea-89fe-2f9ff06f49ef.png">

Same for the dispute card. Total dispute needs to be shortened to K for thousands, M (?) for millions
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/621fa8bb-0f13-4083-9ca2-6616b8b0b91d)

**Comment by matt-bullock** [comment]
looks better. closing
