### ISSUE TITLE
forking modal is visually off

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#6749]
![Screen Shot 2020-03-13 at 11.35.08 AM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/cd382a84-7fa2-4b66-9f4a-d31332c76857)![Screen Shot 2020-03-13 at 11.34.26 AM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/03c8b558-1b31-4d4b-8090-ee2f61ba5d2c)

**Comment by matt-bullock** [comment]
fixed. closing
