### ISSUE TITLE
Add Reporting Begins to sports templates based off of estimated start time

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6765]
No longer allow inputs of reporting begins on certain sports templates....This time will be preset based off of the event start time

**Comment by bthaile** [comment]
I need to know the number of hours added to estimated start time per sport.

**Comment by Chwy5** [comment]
Will get you them soon....calculating longest games/matches ever played for each sport

**Comment by Chwy5** [comment]
NFL 8 hrs
NCAA FB 6 hrs
MLB 9 hrs
NBA 6 hrs
NCAA BB 6 hrs
WNBA 6 hrs
NHL  6 hrs
soccer 6 hrs
Mens Tennis 9 hrs
Women's Tennis 6 hrs

**Comment by Chwy5** [comment]
Some weird behavior....

If I enter the date and time (but not the time zone) into est start time....the event expiration only updates to 2 hrs ahead
And If I hit next at the bottom I can create the market with the unupdated wrong info in the reporting begins

**Comment by Chwy5** [comment]
closing
