### ISSUE TITLE
New Notification: Liquidity Spread

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#6778]
When market creator's market doesn't pass the default spread filter show a notification.

**Comment by Chwy5** [comment]
Needs to say....

The liquidity provided has been depleted and your market no longer is passing the liquidity spread filter.  Add more to have your market seen.
(add more button which would take them to the market) (also needs a don't show me this again for this market - button)

**Comment by matt-bullock** [comment]
Design for this is here

https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=15137%3A34030

**Comment by Chwy5** [comment]
2 Things:

I just created a market with pre-liquidity and see this notification already,,,,dont think I should get it yet

Also the check box need to be changed (probably make the Dont' show me again be a button)....bc I check to dismiss it but then what? how does it go away

**Comment by bthaile** [comment]
we chatted/kick around ideas. the idea is to check the checkbox then click the `add liquidity` button then the notification would go away.

**Comment by bthaile** [comment]
Need @matt-bullock  to update design

**Comment by Chwy5** [comment]
So the problem with clicking the checkbox and making the user hit the add liquidity button is, If I am the market creator and I added all the liquidity I wish to add.....the events outcome looks inevitable, etc....I would click the checkbox and NOT hit the add liquidity button....so there is no way for me to remove this.....and this will happen extremely often...probably every market

So we have 2 options:
1) Remove the checkbox and make the "Dont show me this again" clickable (once clicked we remove it)
2) Add an (x) to dismiss the notification

**Comment by Chwy5** [comment]
not doing - closing
