### ISSUE TITLE
SDK Optimization: Minimize Contract Calls

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#6792]
We make a lot of read-only contract calls because it's easy in local dev or test environments but it doesn't scale well. We need to find and remove these calls wherever we can.

First we should try to get information from the SDK's database. Where that isn't possible, memoize.

- [ ] 3 net_version calls during sdk/ui initialization
- [x] Remove calls to contracts.isKnownUniverse_ and replace with DB call.

**Comment by pgebheim** [comment]
@robert-e-davidson3 -- Do you have examples of this? Let's add them to the description.

**Comment by robert-e-davidson3** [comment]
- [ ] We call `augur.isKnownUniverse_` each time we get the markets list:

```@Getter('getMarketsParams')
  static async getMarkets(
    augur: Augur,
    db: DB,
    params: t.TypeOf<typeof Markets.getMarketsParams>
  ): Promise<MarketList> {
    // Validate params & set defaults
    if (!(await augur.contracts.augur.isKnownUniverse_(params.universe))) {
      throw new Error('Unknown universe: ' + params.universe);
    }```

This can be a db call.

**Comment by pgebheim** [comment]
@robert-e-davidson3 Good one! Added to the list in the description.
