### ISSUE TITLE
Being shown I am consuming my own order where I dont have a position or order on an outcome

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6796]
Create Cat Market (4 + Invalid) (I have no fills so no positions)
Add open Orders:
Short Outcome A
Long Outcome B
Long Outcome C

Go to add Sell (to add Open Order) to Outcome D - getting message that I am consuming my own order (Message doesnt trigger IF I make it a buy open order)

See screenshot

![3-17b.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/4bc9af94-6182-4ed1-803b-4d921803e950)

**Comment by bthaile** [comment]
this one should have gotten fixed with sdk changes to calculate self trade.

**Comment by Chwy5** [comment]
fixed - closing
