### ISSUE TITLE
Rep dispute amount needed is missing numbers in dispute round on outcome cards

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#6799]
![Screen Shot 2020-03-17 at 10.44.35 AM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/bb4bf0e7-1d17-4cb2-a2fe-49a18b3bbda1)

see "/ rep"

<img width="711" alt="Screen Shot 2020-03-17 at 10 55 45 AM" src="https://user-images.githubusercontent.com/6775839/76886343-e6a3a700-683d-11ea-9f86-521c3743996e.png">

**Comment by matt-bullock** [comment]
fixed. closing
