### ISSUE TITLE
Consider prettying up the Stable load screen and error message

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#6803]
Something we discussed. Just wanted to get this on paper.

**Comment by pgebheim** [comment]
We should discuss this tomorrow since the stable loader screen would ideally not change after launch as that would change its warp hash.

**Comment by matt-bullock** [comment]
Designs are here

https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=15471%3A0

![image](https://user-images.githubusercontent.com/39496225/81205123-896cdc00-8fca-11ea-85ab-f084023c11ec.png)

**Comment by bconfortin** [comment]
Hey @matt-bullock 
Not sure if we can do loading bars since it's really difficult to track the loading status from 0% to 100%.

What do you think of these loop loading animations? <https://loading.io/css/>
Do you think we can add those instead?

**Comment by matt-bullock** [comment]
@bconfortin Can we use the loader here https://tobiasahlin.com/spinkit/ - it's the 8th one along

![image](https://user-images.githubusercontent.com/39496225/81392291-bf22d980-911e-11ea-85d8-0b01968bdc60.png)

I've added the design for it here https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=15483%3A0

and mobile https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=15483%3A18

**Comment by pgebheim** [comment]
@bconfortin Status on this?

**Comment by bconfortin** [comment]
Just need to add the new logo

Em sex, 29 de mai de 2020 13:50, Paul Gebheim <notifications@github.com>
escreveu:

**Comment by pgebheim** [comment]
Great -- gonna close this and add that task to the #7052 issue
