### ISSUE TITLE
During Disputing outcomes should never show a negative stake

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#6805]
![Screen Shot 2020-03-17 at 1.14.44 PM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/fe4934fa-6d1c-4504-9fef-ea356f1c296f)![Screen Shot 2020-03-17 at 1.14.51 PM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/19c70dcf-1af2-4282-980d-dfc67e391b06)![Screen Shot 2020-03-17 at 1.15.07 PM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/8d91efcd-2409-47f7-849d-5b4dd47f1751)

had 13 rounds of disputing then one of the outcomes got a negative stake

**Comment by andrewdamelio** [comment]
was unable to reproduce. 
- tested self deputing back and forth, for many markets, max filling and min selected depute amounts
