### ISSUE TITLE
Create performance testing kit

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#6813]
- [x] 1000 orders per second (in one market and 100/s across 10 markets)
 - [x] 100s of markets on the site
 - [x] test with user accounts that've traded in 100s of markets
 - [x] and with accounts that've done 1000s of trades and have 100+ open positions

**Comment by robert-e-davidson3** [comment]
Related to https://github.com/AugurProject/augur/issues/6701

**Comment by pgebheim** [comment]
All requirements above are possible when #6714 merges.
