### ISSUE TITLE
Investigate Light Node Bulk Sync Missing Data

### ISSUE THREAD

**Issue by nuevoalex** [AugurProject/augur#683]
We got another instance of the token balance decrease error:

```
Could not find balance for token decrease
token: 0x92cbc0c7d0e70960959b45e6c2b5c581ecadda75
owner: 0xc685d2570be91660f3cce01b6f89a4b7ae526d4d
```

This occurred when bulk syncing with a light node after not syncing for about a week.

While it may be a red herring its worth noting that just before the error was encountered a bad connection error occurred with the error message:

```
aborted
eth_call returned no data (0x)
Controller Match Lookup Error: ... no suitable peers available
```

Inspecting the corrupted database there appear to be no logs for block `6847654` which is where the token owner first received their balance.

**Comment by nuevoalex** [comment]
While unable to reproduce this there are some major fixes in more recent versions of Geth specific to light node bugs. We're going to try upgrading our packaged binary as well as implementing some other light node improvements and see if this reoccurs for users after.

**Comment by epheph** [comment]
Which geth version was involved here?

**Comment by nuevoalex** [comment]
This seems to have been resolved since the last data corruption fix went in which was light node agnostic
