### ISSUE TITLE
Relayer reports Failed Transactions but Tx did not fail

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6835]
Have had this occur in 2 different times:

1) Created a a market in market creation that failed....Hit resubmit button and two markets were created

2)  Tried to trade multiple orders at once (sweep the order book).....If I click on the 3rd order on the book deep to sell 3 trades at once and hit place sell order....I got a box in the middle of the screen that says something went wrong....but 2 mins later I get fills in my toast messages and the order book clears and shows up in trade history.

**Comment by bthaile** [comment]
I think this issue is do to a GSN bug. @nuevoalex is working with GSN to get the bug sorted. Let me know if I'm not correct.

**Comment by pgebheim** [comment]
Closed with #7055
