### ISSUE TITLE
Mobile UI side bar issues

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#684]
Side nav menus are cut off on mobile devices. i think this change happened recently when the active state highlighting was changed. 

Also, Joey noticed that the mobile side bar doesn't always close when clicking off of it. Seems to be happening while page is loading, especially on the reporting pages. (This may not be mobile specific, though -- needs more investigation.)

![image](https://user-images.githubusercontent.com/6775839/49902515-fe110a80-fe18-11e8-9f37-f2ccaffd9c3c.png)

**Comment by adrake33** [comment]
Assigning this to @phoebemirman @JohnDanz & @bthaile. Whoever has bandwidth to work on it can do so.
