### ISSUE TITLE
Move conditional account funding out of augur.js and into augur

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur#684]
Currently there is azure-specific code inside augur.js `fund()` that funds new accounts differently based on the environment: `if (process.env.BUILD_AZURE)`. What it is doing, is instead of using the faucet to fund the base ether, it is simply moving eth from a special funding address to the newly registered address. 

This issue aims to generalize this using the new `fundNewAccountFromAddress` param in env.json: https://github.com/AugurProject/augur/issues/683

To implement:

1. In augur.js separate `fund()` fn to two new fns:
   - `fundNewAccountFromFaucet(registeredAddress, branch, onSent, onSuccess, onFailed)`
   - `fundNewAccountFromAddress(fromAddress, amount, registeredAddress, branch, onSent, onSuccess, onFailed)` 

2. In augur/augurjs.js make a `fundNewAccount()` fn that reads `env.fundNewAccountFromAddress`

3. If `fundNewAccountFromAddress` is undefined, use the `fundNewAccountFromFaucet` funding function

4. If `fundNewAccountFromAddress` is defined, use `fundNewAccountFromAddress(env.fundNewAccountFromAddress.address, env.fundNewAccountFromAddress.amount, ...)`

**Comment by JohnDanz** [comment]
This is complete mostly on branch 684-accountFunding.
