### ISSUE TITLE
Augur Dev-Node-Geth needs higher gas limit (10k)

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#6848]
<img width="949" alt="Screen Shot 2020-03-19 at 4 47 59 PM" src="https://user-images.githubusercontent.com/6775839/77124927-7b0a3700-6a01-11ea-856e-6676c4a492e6.png">

<img width="903" alt="Screen Shot 2020-03-19 at 4 48 59 PM" src="https://user-images.githubusercontent.com/6775839/77124948-8cebda00-6a01-11ea-957e-e8b85156d94b.png">

**Comment by nuevoalex** [comment]
This _may_ be the first time where the `gas exceeds required allowance` is the actual cause of the problem. Creating a new universe takes an enormous amount of gas. Our docker is outdated using 7.5 mil as the block limit though. It should be 10 mil which would be well above the limit.

That said we can test by manually forking then running these as well.

**Comment by robert-e-davidson3** [comment]
Closing because I upped our geth gas limit to 10 million.
