### ISSUE TITLE
custom category doesn't retain dropdown value

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#6851]
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/cfeb7186-7835-481f-958f-9c4c92a37ca9)

notice the category value selected by user isn't retained, it's cut off

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/ef43c944-c271-42b1-a567-d53307306e8d)

**Comment by Chwy5** [comment]
this still doesnt appear to work for me....I try to create a custom market and when I choose categories I select sports, football (soccer) and for Sub category i choose custom and select one from the drop down....when I go forward nothing is there for subcategory

**Comment by phoebemirman** [comment]
it works for me on master but seems v2 hasn't been updated yet

**Comment by Chwy5** [comment]
fixed - closing
