### ISSUE TITLE
Brave on android: try to login with portis and getting cookies are disabled message despite cookies being enabled 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6852]
Turns out it's because I didn't have 3rd party cookies / tracking enabled. This could only be located via the brave shied toggle. We probably need more specific instructions for this in the modal as it took me a while to figure out how to solve this. The learn more doesn't provide any solutions for Brave.

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/bed96d7a-1928-4229-98d0-8cfcb36288fc)

**Comment by andrewdamelio** [comment]
@matt-bullock i can't fine any good online resources that cover all browsers (including Brave)

brave users i would assume know about the lock in terms of website issues and when to turn it off.
Do you think it makes sense to close this ticket and instead have our own help center provide this information? Then we can just link to our own help desk article.

**Comment by matt-bullock** [comment]
Yeah let's close this. I'll make a note about it
