### ISSUE TITLE
User should be able to use app before 0x wasm bundle is loaded

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#6871]
To accomplish this:

- [ ] Switch to the 0x-mesh-browser-lite module 
- [ ] Include the wasm bundle we want in the augur src tree && make sure webpack copies it into build
- [ ] After warp sync is done / when bulk sync starts, also load the browser mesh by using WebAssembly.instantiateStreaming(...); This should already be doable just by doing this in createBrowserMesh from browser-mesh.ts -- after it is loaded, instantiate like normal

**Comment by albrow** [comment]
@pgebheim I would recommend _not_ bundling the Wasm bytecode for Mesh via Webpack and instead serving it separately. In my experience Webpack still doesn't handle Wasm well (especially with large binaries) and bundling it this way may remove some of the performance benefits.

**Comment by pgebheim** [comment]
@albrow -- Yes, that is how I am doing it now. The .wasm is just copied with a webpack copy rule from the `@0x/mesh-browser` package (installed as a devDep) into the build output directory. Other than that webpack doesn't touch it as of PR #6912.

FWIW this *greatly* speeds up the loading of the page.
