### ISSUE TITLE
Persistent login support ("remember me" checkbox)

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur#688]
When a user logins the first time, they will provide their 800! char secure login id and password. For a better experience, we should remember it (in localstorage), and pre-populate it the next time they login (similar to google), displaying their nice name, with an ability to change it:

```
secure login id: Baz [XDSA....TRED] (not you?)
password:
```

**Comment by tinybike** [comment]
Note: "remember me" functionality was implemented in augur.js in https://github.com/AugurProject/augur.js/blob/c33b342d9eb37479b20946d8aaf0c284efc18f97/src/client/accounts.js#L237-L243 and https://github.com/AugurProject/augur.js/blob/c33b342d9eb37479b20946d8aaf0c284efc18f97/src/client/db.js#L83-L103.  This code should be movable more-or-less as-is to the augur repo.
