### ISSUE TITLE
Add 'liquidity depleted' tag to markets under my created markets

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6883]
This is to be shown when the market fails the liquidity spread filter check

On hover the tooltip will say:

No longer passing the Liquidity spread filter, add more liquidity to have your market seen.

https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=2517%3A1241

**Comment by Chwy5** [comment]
added - closing
