### ISSUE TITLE
Saved template draft has sub category missing and is disabled so can't add it or advance

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#6884]
<img width="866" alt="Screen Shot 2020-03-23 at 11 53 48 AM" src="https://user-images.githubusercontent.com/6775839/77352810-071ba780-6cfd-11ea-86e8-9e0bcab5e80e.png">

1. Create a crypto template - set a 3rd category
2. Save draft on initial liquidity step
3. Go back to draft
4. Sub Cat is missing and disabled

**Comment by phoebemirman** [comment]
not reproducing

**Comment by Chwy5** [comment]
this is fixed
