### ISSUE TITLE
category not clearing when deleting custom

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#6886]
![Screen Shot 2020-03-23 at 12.42.38 PM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/a64e5a08-5972-451c-8481-73dc4ecd83ce)

results in

<img width="816" alt="Screen Shot 2020-03-23 at 12 42 17 PM" src="https://user-images.githubusercontent.com/6775839/77356640-f0c51a00-6d03-11ea-9656-ecdbce358384.png">

**Comment by matt-bullock** [comment]
fixed. closing
