### ISSUE TITLE
Trading: Implement augur portion of trading by integration tradeActions from augur.js

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur#689]
Augur.js is making a `tradeActions()` function that will calculate the logic for what transactions need to be executed to complete a trade. For example, if a user requests `10` shares @ `0.50` but only `5` are currently available on the book, `tradeActions` will return a structure like this:

```
[{
   action: BUY,
   shares: 5,
   avgPrice: 0.50,
   cost: 2.50 (without fee)
   fee: takerFee * 2.50
   gas: 0.00003eth
},
{
   action: BID,
   shares: 5,
   avgPrice: 0.50,
   cost: 2.50 (without fee)
   fee: makerFee * 2.50
   gas: 0.00003eth
}]
```

This issue is about taking the provided structure, and converting them into augur transactions that will be run and monitored through the transaction subsystem. Each item in the array, will be transformed into its own augur-transaction, and managed independently of the other. Some transactions may end up failing, while others may complete, they are independent.

**Comment by tinybike** [comment]
Added in 1738c8ed13852ac92e14c12cb4aab9e176e721ad
