### ISSUE TITLE
Adjust mobile top/side bars to fit better on small screens

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#689]
We need to adjust the X on the expanded side menu:
<img width="737" alt="screen shot 2018-12-13 at 9 57 03 am" src="https://user-images.githubusercontent.com/10524630/49952023-e2613f00-fec0-11e8-98f4-4ac8340a2404.png">

we also need to always show the notifications, should probably move the blocks behind to the sidebar on mobile:

<img width="408" alt="screen shot 2018-12-13 at 10 06 38 am" src="https://user-images.githubusercontent.com/10524630/49952088-fefd7700-fec0-11e8-824b-cac1eb3fb87c.png">

If we move the gas, we need to design a modal or something like that to pop up because currently it's a dropdown which won't work well. See how we do Gas Price Edit.

**Comment by joeykrug** [comment]
In new designs + in UI too
