### ISSUE TITLE
GSN wallet initialisation: Make the buy sell button active as soon as initialization is confirmed.

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6892]
Not wait for the user to close the message

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/4e1c49b8-0554-4030-888d-915886fa806a)

**Comment by matt-bullock** [comment]
I'm no longer seeing the processing or confirmed states

![Kapture 2020-03-26 at 12.58.43.gif](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/662a5be3-f23c-44c1-8609-eb9648377980)

Getting this error after trying to place the order. Not sure if the two are linked

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e556666c-0493-4bf4-923b-56c0b777a870)

**Comment by andrewdamelio** [comment]
@matt-bullock give this another test now on Kovan -- let me know if its working as expected.

**Comment by matt-bullock** [comment]
@andrewdamelio need to wait for v2 to be up and running again

**Comment by matt-bullock** [comment]
@andrewdamelio it's working ok on Local, does that mean it's good to close?

**Comment by matt-bullock** [comment]
Closing this as it's working how it should
