### ISSUE TITLE
Balances are not adding up correctly when creating a market

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6893]
My Starting Available balance, Frozen, Funds and Total Balance do not look accurate when I create a new market with adding pre-liquidity, based on the info in the market rvw step of market creation:

Starting balance and Totals expected to be deducted shown in market rvw step of market creation
![3-24starting balance.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/b4123e40-b41c-42ed-a2c8-17b90fc6d4b2)

Actual after market is created (only FF updated as expected)
![3-24lastbalance.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/bfef813b-54fd-480d-bb98-2573abbd946d)

Expected Balances s/b:
Available Funds:  1352.91 - 179 - 85.04 = 1088.87
Frozen Funds: 514.2 + 179 = 693.2
Total Funds: 1867.11 - 85.04 = 1782.07

**Comment by bthaile** [comment]
in the above screenshots did you create the orders?

with out the exact transaction cost, the numbers will be very difficult to compute. I'll add console log to print out actual transaction relayer payment

**Comment by Chwy5** [comment]
yes created orders

**Comment by Chwy5** [comment]
this works.....need to look up actual transaction payment from console (true amount being used), the estimate on V2 for tx fee is overestimating
