### ISSUE TITLE
Remove NaN from uniswap input. Should be 0

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6896]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/134f8914-3390-4c27-a2c7-19c23e4170ff)

**Comment by matt-bullock** [comment]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e0a625fa-9bf7-48ee-b797-0380908cb247)

@andrewdamelio I'm still seeing this when clearing the input

**Comment by andrewdamelio** [comment]
@matt-bullock could you please list the exact steps you do to create this issue?

**Comment by matt-bullock** [comment]
![image](https://user-images.githubusercontent.com/39496225/77645458-0a17d180-6f63-11ea-9abd-0a9ebdc539f6.png)
Click the input and press delete. Or put in a number then delete that number.
You'll see this:
![image](https://user-images.githubusercontent.com/39496225/77645613-49462280-6f63-11ea-82cf-52ca926728ef.png)

**Comment by matt-bullock** [comment]
All good now. closing
