### ISSUE TITLE
Outcome is cutting off in Portfolio Positions section

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6900]
If the outcome is longer than what we display, need ellipse and hover to show full outcome name

![3-24a.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/d3cf2f29-8349-434a-bd45-3940d88d6e14)

Also looks to be cutting off too soon in this section,,,all the other sections of the portfolio page show the full outcome name

**Comment by Chwy5** [comment]
the tooltip is now cutting off...see screenshot...

![3-26tip.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/13465fb8-2504-4313-8848-2b55611caf33)

**Comment by phoebemirman** [comment]
seems @bthaile fixed this. here https://github.com/AugurProject/augur/pull/6962

**Comment by Chwy5** [comment]
looks fixed - closing
