### ISSUE TITLE
Category tier system update in templates that use "Event"

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6903]
In our current templates the 3rd Category sort should be the Event:

For example: [Wimbledon} Men's tennis; Andre Agassi vs Pete Sampres
1) Sports
2) Tennis
3) Wimbledon

**Comment by phoebemirman** [comment]
this was added for the first tennis template

**Comment by Chwy5** [comment]
Can we do it for the Multiple Choice ones as well.....make the "Event" the 3rd category

**Comment by phoebemirman** [comment]
sure

**Comment by Chwy5** [comment]
Can we do this for Golf and Horse Racing as well?

**Comment by Chwy5** [comment]
fixed - closing
