### ISSUE TITLE
Add "My Reports" section to Portfolio page

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#692]
The Portfolio page should have a "My Reports" section that displays events that the user has reported on along with relevant info about each event:
- The event's outcome (if determined), from `augur.getOutcome(event)`
- The user's report on the event, from `augur.getReport(branch, period, event, sender)`
- The amount of fees (eth/cash) earned on this event, from `0.5*augur.getFees(market)*augur.getRepBalance(account) / augur.getEventWeight(branch, period, event)` (note: this item cannot be computed without `augur.getEventWeight`, which will be available after the next augur-core master/develop merge, which should be Very Soon Now)
- When the event expired, from `augur.getExpiration(event)` (or this can be simply looked up via the usual marketInfo object, if this is already in-memory)

Extra columns that would be super extra awesome to include (which are not in the mock) are:
- A breakdown of Rep awarded/penalized per event, from the `penalize` event logs, can be fetched via `augur.rpc.getLogs({fromBlock: eventExpirationBlock, address: augur.contracts.Consensus, topics: [abi.format_int256(account)]}, callback)` (can also set up an augur.js wrapper)
- The % of Rep that reported the consensus outcome (e.g., instead of just showing that the outcome was "No", show that 88% of Rep tokens reported "No"), from `augur.proportionCorrect(event)`

Here is a [mock](http://augur.link/mocks/myreports.svg), which shows this section as a tab:

![myreports-bg](https://cloud.githubusercontent.com/assets/2637020/16721660/d83a8b38-46f5-11e6-90b6-d2165bebd1e4.png)

Notes:
- The green checkmark symbol in the My Report column indicates that the user's report matched the consensus answer
- The orange exclamation points indicate that the event has an outcome assigned, but it can be challenged (put up for readjudication).  If a user challenges the event's outcome, then this should change to a different symbol (a red gavel, maybe?) indicating that readjudication is in-progress.

**Comment by tinybike** [comment]
Addendum: this issue (and its associated estimate) does not include the UI for readjudication.

**Comment by stephensprinkle** [comment]
Updated Task List:
- [ ] Selectors for my-reports
- [ ] Tests for my-reports
--- 
- [ ] Inclusion of tests for portfolio actions
- [ ] inclusion of test for portfolio reducers
- [ ] Fix to broken tests on previous master merge
