### ISSUE TITLE
Betting intro text visible in mobile

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#6948]
**Describe the bug**
![SmartSelect_20200326-132733_Brave](https://user-images.githubusercontent.com/86010/77693951-75af6e00-6f66-11ea-82bd-d13c71be29f8.jpg)

**To Reproduce**
1. Load site

**Screenshots**

**Desktop (please complete the following information):**
 - Android, Brave (chromium latest)

**Comment by Chwy5** [comment]
looks fixed - closing
