### ISSUE TITLE
Duplicate Market when showing 1 failed

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6964]
In Market creation sometime a market shows failed to create.  If I hit the resubmit button in the ui it appears to create twice.  

Possibly got created the first time and the Failed message in the ui is wrong

This doesnt happen all the time a market failed to create...but we need to figure this out, bc user gets charged bonds and tx fees for 2 of the same markets getting created

![3-27yes.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/e693e8ae-5a64-45a1-a73b-1f4980abd866)

![3-27duplicate.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/1af9d592-f02d-4991-a2cc-fceb674a0f88)

**Comment by nuevoalex** [comment]
Was fixed by @pgebheim I believe

**Comment by pgebheim** [comment]
Yes fixed yesterday with #7055
