### ISSUE TITLE
Add a button to activate comments 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#6965]
May need different wording

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/7841fd69-4c90-4a2f-af4c-a052d01a8e7f)

https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=3939%3A4

**Comment by pgebheim** [comment]
Closed with #7002
