### ISSUE TITLE
need env available in augur.js loadLoginAccount

### ISSUE THREAD

**Issue by kevinday** [AugurProject/augur#697]
I'm adding a switch to env.json to optionally disable auto-login and need env passed in from the UI in the function `loadLoginAccount` in augurjs.js (similarly to how it is being sent to `connect` in augurjs.js.

**Comment by JohnDanz** [comment]
Is this still needed? Wouldn't auto login be handled by the user by selecting the remember me checkbox on login?

Since we don't automatically log you in anymore when you register, i would assume this isn't needed.

**Comment by kevinday** [comment]
Maybe things have changed since we talked about this last but what I'm hoping to disable is auto-login for local unlocked accounts, which I thought Jack wanted to keep. From slack, 
```
if you eliminate auto-login, you'll need to make a button or something that lets people login with a local unlocked account

[4:53]  
possibly at the register/login prompt, if an unlocked account is detected, add a button to that screen that lets the user log in with it
```
@tinybike can you confirm you still want this feature? If so, I will need env available in the function i mentioned so I can disable it for private chains, since it doesn't make sense to auto-login to the unlocked account in that case.

**Comment by kevinday** [comment]
Hey @JohnDanz, mentioned this in slack but this isn't doing quite what we need. Since you are importing env.json, the values in env.json get fixed at build time. We need users to be able to use env.json to configure their build after it's built.

I tink @thinkloop did this for the connect stuff by doing a `GET` of `/env.json`, which fetches at run time the env.json that's in the build directory. https://github.com/AugurProject/augur/blob/d54e5433d07c4cce86a3d898c04fe9db04ba8900/src/modules/app/actions/init-augur.js#L49

**Comment by JohnDanz** [comment]
Fixed this in my latest merge
