### ISSUE TITLE
Bug trying to go back after you save a template

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6979]
I created a crypto yes/no market...entered the deatils into the template and saved it.  Then hit the back button on the bottom left of the screen

![3-27cry.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/b89d0e75-a8a4-454b-843c-a98f751ab884)

**Comment by phoebemirman** [comment]
only seeing this on v2

**Comment by Chwy5** [comment]
fixed - closing
