### ISSUE TITLE
'are you sure you want to leave?" modal doesn't show up when draft has been saved and then edited again

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#6987]

**Comment by Chwy5** [comment]
still not seeing this
To reproduce I need to be on pg 2 of the market creation (liquidity provision pg), then hit back twice....never get the modal

**Comment by phoebemirman** [comment]
it works for me, did you save the draft already?

**Comment by Chwy5** [comment]
looks good  now - closing
