### ISSUE TITLE
% in Positions section shows wrong value in resolved state

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#6996]
To reproduce Short an Outcome  For example short Yes at 0.5) when market gets reported, Make "No" the winning outcome (so your short "Yes" position wins.)
 Total returns looks correct, but the realized % is wrong

Last price currently doesnt change....should make that the correct value per outcome:

So If No is the winning outcome, No would show at 1.0 and all other outcomes would show at 0 in last price

**Comment by bthaile** [comment]
when market is awaiting finalization loser positions won't show correct percentage lost.
when market is finalized the percentages will be correct. 
when winners claim. loser's frozen funds will reduce, indicating their loss.

**Comment by Chwy5** [comment]
this appears fixed
