### ISSUE TITLE
Claim Stake and Fees Bug - amounts dont match

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7017]
see screenshot....

![3-29claimsf.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/6c08887f-b63b-4fc6-9a08-5d26b3fa8c8d)

**Comment by bthaile** [comment]
I'm suspicious of the failed transaction. Was there multiple things to claim and one failed so the aggregated REP total didn't update?

**Comment by Chwy5** [comment]
No....I hit the claim button that was there (not the claim all underneath) and the tx failed

**Comment by Chwy5** [comment]
not seeing this happen closing for now, will keep an eye out for it...cant reroduce
