### ISSUE TITLE
Initialize account coming up after I already created open orders

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7024]
1. Switched accounts from account that had initialized GSN wallet to an account had also been initialized
2. Created open orders which you can see in the bell, 
3. Then went to create more orders but the initialize account button appeared

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/4b614be4-64d4-4ae9-bbf7-8c225efa1b85)

**Comment by Chwy5** [comment]
Confirm this is just a kovan, switching accts bug and not a real issue

**Comment by andrewdamelio** [comment]
@Chwy5 does this still need attention or is this closable?

**Comment by Chwy5** [comment]
not seeing this closing
