### ISSUE TITLE
Scalar markets: processing tag showing on multiple outcomes

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7027]
Added stake to 10 degrees and it showed the processing states on both 10 degrees and 'dispute current tentative winner with new value'

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/7fe0e804-78d9-4f94-9de5-aab912487094)

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/cde8e8b1-8c10-4ecd-8197-a0c2902ce92f)

**Comment by Chwy5** [comment]
Also seeing similar behavior on processing/confirmed tags in the notification section

**Comment by Chwy5** [comment]
fixed - closing
