### ISSUE TITLE
dont' allow scam order in the UI orderbook

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#7031]
Filter out bad price for yes no / categorical markets. the screenshot is of a categorical market with bad priced orders. it pollutes the orderbook.

![image](https://user-images.githubusercontent.com/3970376/78041025-d7d8ec00-7335-11ea-8e54-390af6ee65a3.png)

used flash script to create scalar orders on a categorical market

**Comment by poyo-poyo** [comment]
huh? what is this? i don't understand what you're showing in the diagram..

**Comment by pgebheim** [comment]
Fixed -- UI wasn't filtering orders that were coming in streaming.
