### ISSUE TITLE
Resolved to awaiting finalization

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7033]
For Resolved markets that are awaiting finalization change label from resolved to Awaiting finalization

**Comment by Chwy5** [comment]
still not seeing this in

**Comment by Chwy5** [comment]
I see this in, but after I claim, should  it go from awaiting Finalization to Resolved?

**Comment by bthaile** [comment]
It should go from awaiting finalization to resolved. 
I’ve not seen it go the other way.

**Comment by Chwy5** [comment]
added - closing
