### ISSUE TITLE
fills not showing up in market page

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#7040]
fills in portfolio:
![Screen Shot 2020-03-31 at 12.14.47 PM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/7588eb9f-b79d-4ed7-964c-0bfa25b73795)

market page:
![Screen Shot 2020-03-31 at 12.14.40 PM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/29b35ca6-8442-466c-a7da-a47074e12447)

market on kovan: 
Week 10: Which NFL Team will win: Denver Broncos vs. Pittsburgh Steelers?
Estimated scheduled start time: Mar 31, 2020 11:00 AM (PDT)
0xD80C49977C5a5F51CaD969fa1236f8566f2247ca

**Comment by Chwy5** [comment]
fixed
