### ISSUE TITLE
Claim Proceeds Total in Modal doesnt update if you claim an individual market

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7049]
@bthaile this is probably what happened with the claim stake and fees (probably got claimed through the market pg) and the modal didnt update

In this modal I had 3 markets to claim on.... I claimed 1 market individually(not through the claim all button), after it processed that market disappeared, but the total on the bottom didnt update 

(It does update if you leave the modal and come back or just view the balance in notifications)

![4-1claimproceedsmodallnoutupdating.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/d24f02eb-76c0-4ecf-858b-34e7d19d7de2)

**Comment by bthaile** [comment]
this got fixed in one of the P/L PRs

**Comment by Chwy5** [comment]
fixed - closing
