### ISSUE TITLE
extra long resolution source messes up trading ui

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#705]
<img width="1377" alt="screen shot 2018-12-14 at 11 08 44 am" src="https://user-images.githubusercontent.com/6775839/50022342-b31a0300-ff90-11e8-8633-4760f24ccf10.png">

should this wrap with hyphenation? or scroll vertically?

**Comment by adrake33** [comment]
@sharkcrayon @matt-bullock What is your preference on how this should wrap?

**Comment by matt-bullock** [comment]
It should wrap here. There is a max width set to the component in the new design.

If someone was to put a massively long link that looks a mess, is it possible to identify this and put ellipses at the end of the first line?

**Comment by adrake33** [comment]
We could detect such links and shorten them with an ellipsis, but users will want to be able to see the full resolution source, so we should still have a way to allow users to expand it and see the full address.

**Comment by matt-bullock** [comment]
In that case ditch the ellipses idea on links and instead always have them wrap.

**Comment by adrake33** [comment]
Closing this since the max-width in the new design should cause it to wrap.
