### ISSUE TITLE
Bell message showing wrong winning outcome and value

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7050]
this is a resolved market (was not finalized) "yes" was the winning outcome, which I purchased. Once I hit claim it shows claim winnings on the wrong outcome (with the wrong amount)

![4-1wrongclaiminfo.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/c9d9f57f-d4a9-47ab-96e7-f7f3bce22dce)

**Comment by Chwy5** [comment]
fixed - closing

**Comment by pgebheim** [comment]
(new one #7226)
