### ISSUE TITLE
design something to tell users which markdown is available for additional details

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#706]
available:
- horizontal rules
- headers
- bold
- italics
- unordered/ordered lists
- newlines (just hit return)

here is how to use them:
https://guides.github.com/features/mastering-markdown/
http://jonschlinkert.github.io/remarkable/demo/

**Comment by adrake33** [comment]
Good point @phoebemirman! We'll need to add something in the Create Market flow that explains the Markdown support added in https://github.com/AugurProject/augur/issues/448

**Comment by Chwy5** [comment]
closing
