### ISSUE TITLE
bug in withdraw form - says no funds but account has dai

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#7065]
![Screen Shot 2020-04-01 at 3.26.41 PM.png](https://images.zenhubusercontent.com/574e216bbf93871ccd9be5fb/be8d97c2-eda1-4460-b225-c0069653cdf1)

to repro: 
set as eth, have 0 eth, type in 10, switch to dai

**Comment by Chwy5** [comment]
fixed -closing
