### ISSUE TITLE
TypeError thrown when creating / loading markets

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#707]
Tried to create a new binary market and the UI throws two errors:
```
load-markets-info.js:17: ERROR loadMarketsInfo() Object {error: "0x", message: "no response or bad input"}
load-markets-info.js:17: ERROR loadMarketsInfo() TypeError: marketIDs.forEach is not a function
```
So far I have only observed this while creating a market.

**Comment by tinybike** [comment]
Seems to happen every time I create a market (have only tried binary markets so far).  Only happens once.  After the initial error(s), the create market + generate order book process continues.

**Comment by stephensprinkle** [comment]
PR #717 resolves this bug -- closing.
