### ISSUE TITLE
Flash Script: Verify Test Deploy

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#7071]
To save time running manual tests, it'd be great to have a flash script that determines certain facts about an environment, to verify that a test deploy worked.

- [ ]  Are the markets there?
- [ ]  Is warpsync initialized?
- [ ]  Is the eth exchange funded?

(list incomplete)

**Comment by pgebheim** [comment]
instead we just made the deploy scripts do these things :-D
