### ISSUE TITLE
Getting a COMPLETE ALL REQUIRED FIELDS message on the fees and liquidity page of MC, when there are no fields required to complete

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7076]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/1b73e9e7-a7d7-463d-b555-f7bf78a741ce)

**Comment by Chwy5** [comment]
seeing this as well for only the sports templates....
click sports
click American football (or any sport) hit next
click MC, next
Select a template and after hitting next this message appears

****Going to a different style template which works and then coming back to sports fixes this....
not easily repeatable, but has happened on 2 separate occasions today

![4-2nfl.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/5bb0f4db-a414-4c74-88fe-f93a40a2f926)

**Comment by phoebemirman** [comment]
not able to repro

**Comment by Chwy5** [comment]
havent seen it happen...closing for now
