### ISSUE TITLE
MC: navigation broken, blows up

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#7079]
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/0ed2e939-448a-4688-9964-cadc8e6ed498)

Not totally sure the repro steps. There is state lost when navigating back and forth from picking a template and in market creation form and back. 

I noticed the pre-state was the `save` form button was missing on first page of market creation form. went to next page then back and it blow up. got the error above.

**Comment by phoebemirman** [comment]
not able to repro

**Comment by Chwy5** [comment]
fixed - closing
