### ISSUE TITLE
Trading Page: Market Header

### ISSUE THREAD

**Issue by sharkcrayon** [AugurProject/augur#708]
Design Prototype: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=342%3A34455

Add the new market header. It is this section of the trading page:

![image](https://user-images.githubusercontent.com/4355755/50024951-35aabe80-ffa1-11e8-9db2-ae80b902dba4.png)
(Details in the screenshot above may differ from the design. Use the design as final guidance.)

Top section (market state, topics, watchlist):

- [x] Add the Open/In Reporting/Resolved in the top left, along with corresponding color underlines.
- [x] List the market topics to the right of the market state. Topics have a hover state, and when clicked, should go to the Market List page with the filter for that particular topic applied.
- [x] Add the "Add to Watchlist" button on the far right. It has a hover state and a selected state. Clicking it should add the market to the user's favorites list. It should stay all the way to the right of the browser as the width grows.

Bottom section (three columns):

- [x] The bottom section should be broken up into three columns. The first column (with title and additional details) should have a max-width as reflected by the design. It and the column to the right of it (with Volume and other market stats) should be aligned to the left, and the column on the far right (with the market date) should be aligned to the right, so that on bigger screens a gap appears between the second column and the third. (`display: flex; justify-content: flex-start` on the parent and supposedly `margin-left: auto` on the third column according to [this](https://stackoverflow.com/questions/23621650/how-to-justify-a-single-flexbox-item-override-justify-content))
- [x] When the screen shrinks, the left column that should shrink when there is no more room left in between the second and third columns. The market stats and end date columns should have a min-width, while this left column shrinks as necessary.

Left column:

- [x] Add the title and resolution source.
- [x] Add the additional details. This should display at a min height, and expand to show the full additional details when clicked. "More" should turn to "Less" when expanded. [Mock is here](https://www.figma.com/proto/bZh7tOiLm6Ls9Hl4RL6qMC5X/Market-Trading-Page?node-id=1204%3A121227&viewport=-12321%2C7493%2C1&scaling=min-zoom&redirected=1)

Middle column:

- [x] List the five market stats (this does not include the created/end date). 

Right column:

- [x] Show the created and end date with the progress bar. The progress bar should show the percentage of time elapsed since the market was created compared to its end date.

Hide Market Info:

- Ignore this for now and do not include the "Hide Market Info" button. We will add this functionality after the trading page is live.

Market States:

- [x] When the market is in reporting, show the "Submit a Report" button as appropriate. (Only designated reporters should see it when it is in Designated Reporting, and everyone should see it when it's in Open Reporting.)
- [x] When the market has received a report and is not yet available for dispute, show just the Tentative Winning Outcome without the dispute button.
- [x] When the market is available for dispute, show the dispute button to the right of the Tentative Winning Outcome.
- [x] When the market is resolved, show the Finalize button. When the market is finalized, show the Winning Outcome. (See discussion on #692 for whether the Finalize button should always be shown, or shown only to users with winning positions)

**Comment by adrake33** [comment]
@sharkcrayon Is the corresponding color red for Resolved status? I only see green for Open and Yellow for In Reporting in the 2 mocks that are linked.

**Comment by adrake33** [comment]
Never mind, I used the arrow keys to cycle through the other mocks and saw that it is red.  What does the hover state look like for the market topics and "Add to Watchlist" button?

**Comment by adrake33** [comment]
Also, should the Finalize button show on the page (relates to #692)?

**Comment by sharkcrayon** [comment]
I commented on #692. I'm torn between each approach, but I'm leaning toward just always showing the button for simplicity's sake. Whatever we decide there should be reflected in this task as well when the Finalize button work is done.

**Comment by sharkcrayon** [comment]
@matt-bullock Can you add mocks to the Framer prototype for the topic hover state and the "Add to Watchlist" button?

**Comment by adrake33** [comment]
@sharkcrayon @matt-bullock Why do these 2 headers look different? Is one an older design?

![screen_shot_2018-12-17_at_12 48 55_pm](https://user-images.githubusercontent.com/11491365/50108432-10f55780-01ea-11e9-950f-8c36da878d5d.png)

![screen_shot_2018-12-17_at_12 49 02_pm](https://user-images.githubusercontent.com/11491365/50108448-1ce11980-01ea-11e9-84bb-d80f07819e21.png)

**Comment by bthaile** [comment]
`in reporting` mock
https://www.figma.com/proto/bZh7tOiLm6Ls9Hl4RL6qMC5X/Market-Trading-Page?node-id=1204%3A121229&viewport=-12321%2C7493%2C1&scaling=min-zoom&redirected=1

**Comment by bthaile** [comment]
`in reporting`
https://www.figma.com/proto/bZh7tOiLm6Ls9Hl4RL6qMC5X/Market-Trading-Page?node-id=1204%3A121229&viewport=-12321%2C7493%2C1&scaling=min-zoom&redirected=1

**Comment by sharkcrayon** [comment]
@adrake33 See the linked design at the top of the task for the design that should be used.
