### ISSUE TITLE
User should be able to cash out eth + dai - see chwys notes at the bottom for what still needs to be completed

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#7081]

**Comment by pgebheim** [comment]
First piece of this goes to Alex to make middleware/external contract to do this.

The second piece will be hooking up a button in the UI which does it. @bthaile 

@Chwy5 We could decide to do this work later if you think it's fine to assume that people can figure it out using their normal wallet (since it is possible to withdraw all your dai + eth), but for now I put this as High + Needed for V2 and scheduled for #6966

**Comment by Chwy5** [comment]
Yeah we should do this now, the UX is a little confusing
1)We should remove the gsn wallet number from the dropdown and just say Wallet (can still get the acct number through add funds)
2) We should add Eth Reserve (?) in the Account Menu
3) Add tooltip copy: Augur will reserve $(N) of your funds in order to pay these fees, but your total balance(Available Dai + Eth Reserves)  can be cashed out at any time.

**Comment by pgebheim** [comment]
Ah yeah that's nicer wording

**Comment by pgebheim** [comment]
![image](https://user-images.githubusercontent.com/86010/78394396-6e104a80-75a0-11ea-8065-dcac509b9af2.png)

Not totally sure how we should present this to the user -- but ostensibly somewhere on this screen.

**Comment by matt-bullock** [comment]
Add the ETH reserve to the account dropdown like so. Copy in Chwy's message above goes into the tooltip

https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=1808%3A5290

![image](https://user-images.githubusercontent.com/39496225/78578652-1982fe80-7830-11ea-9f0e-04293e8ec8e3.png)
---

Add cash out button to transactions section of account summary

https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=2704%3A981

![image](https://user-images.githubusercontent.com/39496225/78580078-2f91be80-7832-11ea-97b0-8f245acd09b0.png)


---

This opens the cashout modal (a reduced down version of the withdraw funds modal)

https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=2149%3A0

![image](https://user-images.githubusercontent.com/39496225/78580016-17ba3a80-7832-11ea-8789-a16785a39ca5.png)

**Comment by Chwy5** [comment]
We still need to do
1) Remove the Account Number and replace it with The users email address or phone number they used to sign up or if using MM/Web3 put MetaMask/Web3 Under Account **[DONE]**
2) The location of the cashout button is not in the correct spot on V2- needs to be moved **[DONE]**
3) the calculations arent accurate [see #7248]

**Comment by Chwy5** [comment]
This still appears off to me.....This is on my portis acct:

![4-14acct-portis.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/0fd47a90-f794-46ab-a62c-1d8e2451256f)

![4-14cashout.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/503257ef-af88-4d5a-9fea-ba7e7d5782e3)

**Comment by andrewdamelio** [comment]
@Chwy5 that will be address in https://github.com/AugurProject/augur/issues/7248  -- Tom just got a PR in

For this ticket, i just scoped it for the below, are they ok?
- Remove the Account Number and replace it with The users email address or phone number they used to sign up or if using MM/Web3 put MetaMask/Web3 Under Account [DONE]
- The location of the cashout button is not in the correct spot on V2- needs to be moved [DONE]

**Comment by Chwy5** [comment]
fixed - closing
