### ISSUE TITLE
User should be able to see ETH balance as part of their account summary / total funds

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#7082]
- [x] In the top bar, the "Total Funds" section should NOT include ETH held in the signer (for fees), but on hover it should have a tooltip (with the circle+question mark @Chwy5 ) that says "Your total funds does not include those funds Reserved for fees".
- [x] In the account menu, add in the ETH balance of the Signer as a row, with the label "ETH (Reserved) -- with the (?) + tooltip. The tooltip should use the final text that is displayed during the modal in #7084 

This issue is currently blocked by #7084 -- but once the final text has been decided we can remove that blocker.

**Comment by Chwy5** [comment]
looks good - closing
