### ISSUE TITLE
Improve the trade panel's mouseover toggle between buy and sell

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#709]
The current behavior (where you over over the "buy" text and a "sell" option appears) seems unintuitive to me.  My suggestion: convert it to a normal select/options drop-down menu, which people will immediately know what to do with.

**Comment by stephensprinkle** [comment]
Is this still relevant in light of the recent changes by @thinkloop?

**Comment by tinybike** [comment]
No, it shouldn't be; closing.
