### ISSUE TITLE
Enable ability to add pre-filled stake when a market is in slow dispute

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7093]
Assuming we want to allow this, the ability to do so is currently missing from the form and market card

Screenshots from the build:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/a8205785-2b8c-4b7b-b2a7-b4519e925da9)

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/3b8bd05e-a162-4f83-b1d5-574647ac7dad)

**Comment by bthaile** [comment]
Talked to Alex, user's can't add pre-filled when market is in slow disputing
