### ISSUE TITLE
consider adding a "read more" cut off to marker creation process so people can see how their additional details will be shown on market page

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#710]
but reporting/dispute also show it normal.

could go either of these places: 

![image](https://user-images.githubusercontent.com/6775839/50031865-a524ac00-ffa9-11e8-9427-f97632776cc0.png)

![image](https://user-images.githubusercontent.com/6775839/50032584-d3a28700-ffa9-11e8-98ba-43163c86acd0.png)

@bthaile thinks it should be done

**Comment by adrake33** [comment]
So the idea here is it would be something the user could click on to expand/collapse the preview if it's really long?

**Comment by phoebemirman** [comment]
yea. this is done in the trading view so might be good to use that same component. and then market creators will be able to preview more closely how traders are going to see the details they set.

but also /reporting and /disputing it is full length

**Comment by adrake33** [comment]
Adding it to the create market flow & reporting/disputing sounds good to me. What do you think @sharkcrayon @matt-bullock?

**Comment by matt-bullock** [comment]
It's a good idea but I'd like to leave it until we work on the redesign of this section. Need to have a discussion about how truthful this marker would be when the additional details on a market page is seen on different devices/browsers/operating systems as they will all render type differently, possibly affecting how much type is cut off

**Comment by bthaile** [comment]
I think an exact view of both the market trading header and the market card would help market creators see exactly how their market will look once created. Then there isnt any surprises after they pay the gas and stake the various bonds.

**Comment by matt-bullock** [comment]
Yep I was thinking the same for the redesign
