### ISSUE TITLE
Need to add Bell message for reporting on Warp sync market

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7101]
I reported on the Warp Sync market but did not get a bell alert for my confirmation...we need to add like we have for any other market that gets reported on

**Comment by Chwy5** [comment]
@matt-bullock please provide copy for what we use on regular market being reported on

**Comment by matt-bullock** [comment]
It'll follow this structure

![image](https://user-images.githubusercontent.com/39496225/78568277-27318780-7822-11ea-94d7-1ec9aa4013fd.png)

**Comment by matt-bullock** [comment]
Not seeing the warp sync market on local so can't test. @phoebemirman can you post a screenshot of the message

**Comment by matt-bullock** [comment]
done. closing
