### ISSUE TITLE
MC: Scalar market pre-liquidity doesn't pass liquidity ranking

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#7106]
Used Scalar baseball template and set bids to 12.5 and asks to 12.7 with roughly 2000 DAI on each side and liquidity ranking said failed. After creation with liquidity it passed default liquidity filter. 

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/38b774ac-37f5-4f2a-a5bd-1a30198591da)

![image](https://user-images.githubusercontent.com/3970376/78450330-72da0a80-7643-11ea-85be-224319653ab6.png)

**Comment by Chwy5** [comment]
not passing for me....

I am 1000 by 800 up on a football template (0-17) range

![4-6sc.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/9e18f567-a4f5-4926-8177-3c41d3444b37)

**Comment by Chwy5** [comment]
fixed - closing
