### ISSUE TITLE
Claim Proceeds Modal needs tooltip 

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7107]
We need to add tooltip explaining where that number comes from, this tooltip is on claim market proceeds modal. 

tooltip:
"This number is the return of Frozen Funds for any position(s) held in this market + any PnL accrued in this market"

**Comment by matt-bullock** [comment]
Tootip can go immediately after 'Proceeds after market fees'

**Comment by matt-bullock** [comment]
looks good. closing
