### ISSUE TITLE
Spike: Read in logs for creating orders & placing trades & run them through log processors

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#711]

**Comment by adrake33** [comment]
@pgebheim can provide more guidance on this.

**Comment by adrake33** [comment]
Reassigning this to @robert-e-davidson3 since he's doing this for universe creation & market creation.

**Comment by robert-e-davidson3** [comment]
I'm pretty sure this is a dupe of #714.

**Comment by robert-e-davidson3** [comment]
#714 turned out to be too much work for a single ticket. Instead, the infrastructure was built so that tickets like this one can be done much more easily. So I'm reopening this ticket for this specific work.

**Comment by justinbarry** [comment]
No need to support this. Better infrastructure exists for V2 using ganache and contract calls.
