### ISSUE TITLE
User can't switch to winning universe after fork is finalized

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#7110]
- use flash forking script to get into a fork.
 - use flash migrate rep script to migrate 100,000 REP to an outcome
 - push time 90 days
 - use flash to finalize the forking market.
 - migrate a few markets, they'll go on winning universe

![Screen Shot 2020-04-05 at 10.09.06 AM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/17e3bb30-dbbb-406b-b446-911f02e444a8)

![Screen Shot 2020-04-05 at 10.09.31 AM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/42455dfe-ee8c-4ee3-8e8c-c67e74001367)

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/c1c1f2ef-2f18-4384-a922-3e2bb69240d1)

**Comment by pgebheim** [comment]
Phoebe actually repro'd that this works now, so #4205 is indeed the real issue.
