### ISSUE TITLE
Augur Node Blockchain Testing Mechanism

### ISSUE THREAD

**Issue by nuevoalex** [AugurProject/augur#714]
Currently the Augur Node getter tests are all based off of mock DB data which is seeded directly into the databases. The tests for log processing generally use a combination of seeded data and directly processed JSON.

In order to more accurately (and we hope more painlessly) test the functionality of Augur Node we believe it would be preferable to instead provide some mechanism where test data (for both log processing and getter test) is defined and validated as sequential logs like it would come from a real blockchain.

The actual mechanism for specifying this data and how the test suite uses/modifies it is up for discussion currently.

**Comment by robert-e-davidson3** [comment]
The infrastructure is in place and some tests are converted. I'm closing this ticket. New tickets should be opened for converting additional tests.
