### ISSUE TITLE
categories should sit on the same line as shield, share and favourite icons

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7148]
These should get pushed below when there is not enough room due to a scalar or in-reporting tag being there. But generally in open markets, categories should sit on the top line where possible

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e71e9b95-33c8-4239-8e5b-7e5966c6a92c)

Design:

https://www.figma.com/file/Do4qnkCNM8P7lwBmCdYZCS4X/Market-Cards?node-id=189%3A97

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/4592ac60-c098-4653-9453-6c88028b7db5)

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/2cbedc59-f8a0-44f1-97b0-d959dc60a5be)

**Comment by Chwy5** [comment]
fixed - closing
