### ISSUE TITLE
npm install  Failed! Error!

### ISSUE THREAD

**Issue by bingjiw** [AugurProject/augur#715]
![augur error 1](https://cloud.githubusercontent.com/assets/20619102/17087289/47a35fb0-5239-11e6-9d17-4a1b77d36062.png)
![augur error 2](https://cloud.githubusercontent.com/assets/20619102/17087287/46fa643c-5239-11e6-8415-c52a6ace6e40.png)
![augur error 3](https://cloud.githubusercontent.com/assets/20619102/17087288/47356f46-5239-11e6-97d0-5a2ae607067b.png)

**Comment by tinybike** [comment]
I'm not sure our build process works / is supposed to work on Windows.  @thinkloop, have you tried building on Windows, by any chance?  (We're going to have a binary executable for Windows before launch.)

**Comment by thinkloop** [comment]
I have not tried building on Windows yet. Is the binary executable for
augur or augurjs? We have a build folder with everything already built for
augur if that helps.

**Comment by tinybike** [comment]
The build folder isn't git tracked though!  I think the executable would be for augur.  (We don't have one yet, but it'd be nice to provide one sometime prior to V1 launch.)

**Comment by thinkloop** [comment]
Ah, that should be going up soon in place of the azure one. What would an
executable do?

**Comment by tinybike** [comment]
Execute! :grinning:

**Comment by tinybike** [comment]
Executable would have the build/ stuff + the webserver stuff bundled together into an augur.exe file.  Double-click to run it and it does exactly the same thing that `npm start` does if you built it locally.

To get fancy, we could even use react-native or Electron to make it a real standalone app.  That would be post-launch though...

**Comment by joeykrug** [comment]
has to do w/ python not being in path on windows: https://www.robertkehoe.com/2015/03/fix-node-gyp-rebuild-error-on-windows/

not a bug on our end
