### ISSUE TITLE
Forking market card needs updating to the forking cards design

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7150]
Build:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/b2dd6fb1-0612-42fc-844f-9fb79e8b216c)

Design:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/c1801249-feb2-4d75-acac-82e76ab4e9a8)

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/304f340e-14e3-4825-8ac5-22bc313b27f6)

https://www.figma.com/file/aAzKHh4cA6OT2t7WFv2BQ7fB/Reporting-and-Disputing?node-id=4031%3A2449

Add forking tag

Remove dispute bond progress bars and amounts

Remove tentative winner title

Change dispute buttons to migrate rep to this outcome's universe buttons

Change time left to dispute to time left in fork window

**Comment by matt-bullock** [comment]
@phoebemirman Cards looks looks. Only thing I noticed that the condensed view button should say to 'Migrate REP to an Outcome's Universe' rather than 'to this'

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/69cbc898-c581-4e0f-b05d-78c18eb0f9e9)

**Comment by pgebheim** [comment]
@phoebemirman -- May as well just fix this typo and close the ticket during RC2

**Comment by matt-bullock** [comment]
looks good. closing
