### ISSUE TITLE
Resolved markets during or after a fork shouldn't have the blue message as they can't be migrated

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7151]
Unless I'm mistaken?

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/21a0bd91-36fb-46ed-81db-cb95c7953d8e)

**Comment by bconfortin** [comment]
You are correct in saying that a finalized market should not have that message.
However, I believe those markets were not finalized. They were awaiting finalization and, therefore, should be migrated to the new universe. From what I saw, finalized markets don't show up in a fork's market list.

I did spot an error in the migration logic where it would not migrate markets awaiting finalization. Fixed that here #7214

**Comment by bthaile** [comment]
it looks good to me. pushing this to design review

**Comment by matt-bullock** [comment]
Ok that would make sense. Tested again and indeed it does only happen to markets awaiting finalisation . Closing
