### ISSUE TITLE
Updates to migrating market message - buttons needs processing state + add additional copy 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7154]
Add processing state to button

Add this secondary text to message: This market will be migrated to the winning universe and will no longer be viewable in the current universe.

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/d631fb40-32cf-465d-ac05-687181a9c355)

**Comment by matt-bullock** [comment]
This message isn't showing up anymore after a fork has finalised. Please check and send back when working again

**Comment by phoebemirman** [comment]
seems like the forking market hasn't been finalized

**Comment by matt-bullock** [comment]
Looks good. Closing
