### ISSUE TITLE
Unable to report / migrate market or dispute when a market is in dispute after a fork

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7155]
Report and migrate market button (which is probably not the correct term here) doesn't do anything and the dispute buttons are disabled 

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/9707848e-9198-4e1f-a095-584298845d52)

**Comment by phoebemirman** [comment]
these markets shouldn't be showing up there. should be in child universe

**Comment by matt-bullock** [comment]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/d1253f42-4e1d-414e-b0c7-89156d5a0a81)

Seeing this message. I have REP in the current universe and REP in the winning universe. I should be able to migrate markets

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/04d15fa6-dde9-4d42-a554-96e57270a1dc)

Also check the spelling of UNIVERSE in that market card message 

To reproduce migrate all your REP to a universe. That universe will win. Then push time past the fork

**Comment by phoebemirman** [comment]
seems like the forking market hasn't been finalized

**Comment by matt-bullock** [comment]
Works now. We need a way in the UI to finalise the forking market
