### ISSUE TITLE
Mobile Bug- Trade history - if empty add null state

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7160]
When On a market on mobile if i click the Trade History button (next to Orderbook) it does not bring me to tjhe trade history section...still shows me the order book

![4-7mobiletrhis.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/de5921a7-765e-4f03-b23d-f6d65f789b3c)

**Comment by phoebemirman** [comment]
that is trade history. but looks like that one is empty

**Comment by Chwy5** [comment]
So if it is empty we need to add a null state

**Comment by Chwy5** [comment]
Fixed closing
