### ISSUE TITLE
Prune algo update

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#7162]
Current status
===

The prune algo queries the MarketFinalized logs for any that have a time stamp before the `PRUNE_HORIZON` which is currently 30 days previous to the current block's timestamp leaving just the most recent ShareTokenBalance logs.

The problem
===

We need some data for the UI to display that the user has funds to claim. This could be in the form of share tokens, disputing stake, or market creator / affiliate fees.

Solution
===
1. Make the prune delete all data of past-cutoff markets including share balance logs.
2. Provide a utility contract for taking an account and some list of markets which will it will scan and return data on what the user has to claim from them.
3. In the UI provide a basic UI to "recover old funds" or some such wording which will generate market ids and in chunks call this utility function to see what can be claimed.
4. UI presents basic info on claimable funds retrieved in (3) and button(s) to claim them.

**Comment by pgebheim** [comment]
@justinbarry I'm moving the due date for this to be may 15. If it can get in rc1 that's fine.

**Comment by pgebheim** [comment]
Issue closed with #7216
