### ISSUE TITLE
Changes to organisation of trading page on mobile

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7174]
1. Change 'Trade' tab to 'Charts'

2. Move order book and trade history component to the market info page and move the price history chart to the charts page. 

So the order of market info page is: Market title and info component - outcomes - order book and trade history component - order ticket - comments

Order of charts page: Price history chart - candle sticks and depth chart component - comments

No change to order/positions page

Clickable prototype: https://www.figma.com/proto/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=218%3A23083&viewport=-576%2C-173%2C0.6305556893348694&scaling=scale-down

Designs: https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=2357%3A2571

**Comment by Chwy5** [comment]
Looks much better - closing
