### ISSUE TITLE
Allow more space for the back to markets button on mobile

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7175]
The hit area is currently too small 

Build:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/2199116b-763a-43c2-aaee-b9e719d2ec2d)

See design:

Back button should have 32x48px hit area

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/063e009f-bc46-4240-9451-3157e5d488eb)

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/2dfff849-9b80-4f80-96a0-5fd679ed3ef9)

https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=2357%3A2571

**Comment by Chwy5** [comment]
still seeing this....needs more space

![4-9space.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/457c8cb7-8244-4a80-83e8-48860d8ced0e)

**Comment by Chwy5** [comment]
looks fixed - closing
