### ISSUE TITLE
Trading Page: Create New Layout

### ISSUE THREAD

**Issue by sharkcrayon** [AugurProject/augur#718]
Design Prototype: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=342%3A34455

Create the layout blocks for the part of the trading page below the market header. This is the part of the page I'm referring to (including Open Orders/Filled Orders/Positions, which is cut off in the screenshot):

![image](https://user-images.githubusercontent.com/4355755/50088687-f490f500-01c0-11e9-964e-92cb09f97efa.png)

(Details in the screenshot above may differ from the design. Use the design as final guidance.)

This task is about creating the placeholder blocks for the individual pieces of the page (order form, outcome list, etc) so that developers can work on the individual pieces simultaneously without worrying about the overall layout of the page.

Style Changes

- [x] Change the site-wide background color to match the Trading page background color

Top-Level Layout

- [x] At the top-most level, this page consists of two columns. The left column contains the order form, outcome list, charts, and open orders. The right hand column contains the order book and trade history. The right-hand column should have a set width and the left-hand column should fluidly take up the remaining space. As the page grows and shrinks the left-hand column should adapt.
- [x] The left and right hand columns should always grow to one another's height. Putting `display: flex` on the parent should do this automatically. (Do not set static heights to enforce this, as the content will grow and shrink in height)

Right Hand Column

- [x] Put placeholder divs for the order book and trading history modules. Use the background color shown in the mock. They should share the height 50/50 (with the appropriate gap in between). Feel free to put static min-heights on these so the placeholder layout doesn't collapse. We'll move those min-heights to the individual modules later when they are built.

Left Hand Column

- [x] The left hand column consists of two rows. The top row contains the order form, outcome list, and charts. The bottom row consists of the open orders module. Create this layout and add the open orders module placeholder. I don't think you'll need to put a min-height on this, because if flex is used properly it should grow in height to the space available.
- [x] The top row consists of two columns. The left column is the order form and the right column is the outcome list and charts. Add the order form placeholder with a static min-height. The order form should have a set width with the outcome list/charts fluidly taking up the remaining space. The outcomes list/charts width should grow and shrink as the page width grows and shrinks.
- [x] The right column within the top row should be fluidly split between the outcome list and the charts. When the outcome list is taller the charts will shrink, and when the outcome list is shorter the charts will grow. The combination of the two will always be as tall as the order form. If you put `display: flex` on the row div this should happen naturally. Put a min-height on the outcomes list to double check this.

**Comment by phoebemirman** [comment]
done on new-trading-page-layout branch in augur-ui repo
