### ISSUE TITLE
Transactions Sub-System does properly fail on generate order book failure response

### ISSUE THREAD

**Issue by stephensprinkle** [AugurProject/augur#718]
The transaction responses observed were as follows:

Account ID: 0x8a3e28436f62d2ae618737df168a9a253e21c599
'fake' ETH: 9,905
testnet ETH: 2.33

Market ID: 0x50b37d64a7a5b1e9375a8a6831cfc36a134eb8cfe75109c55eb13da3fdb340e5

Market created successfully, but during order book generation, an error was returned (below), which ultimately stalls the generate order book method.  
The UI should reflect this error state, but it looks as though an onSuccess of case: ORDER_BOOK_ORDER_COMPLETE is coming in after the error case and is causing the UI to not properly reflect the failure state of the Order Book and instead stall on the ORDER_BOOK_ORDER_COMPLETE case.

```
  message: "not enough money or shares"
  status: "failed"
```

```
  message: "Bid for 20 shares of outcome 'No' at 0.45 ETH created."
  status: "order creation complete"
```

**Comment by joeykrug** [comment]
What's satus of this stephensprinkle & tinybike?

**Comment by tinybike** [comment]
generateOrderBook on the backburner for now (per Ron's advice), altho I think this particular issue was fixed.
