### ISSUE TITLE
Hide migrate REP button if the user has missed the cutoff to migrate.

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#7205]
<img width="1217" alt="Screen Shot 2020-04-09 at 10 56 42 AM" src="https://user-images.githubusercontent.com/6775839/78925797-deabe100-7a50-11ea-8403-d708cb4b59af.png">

after finalizing the button goes away
so not supposed to have been able to press migrate button in first place

**Comment by Chwy5** [comment]
closed - not a bug

**Comment by bthaile** [comment]
suppose to fail, it's use it or lose it.

**Comment by pgebheim** [comment]
This is by design -- if you don't migrate during the fokring period you will lose your rep (use it or lose it)

**Comment by phoebemirman** [comment]
seems like we should hide the button in that case

**Comment by pgebheim** [comment]
Yes! I'll rename the ticket.

**Comment by Chwy5** [comment]
OK so for now we want to Hide Migrate Rep button when fork Finalizes

For post v2 launch:

Need to add finalize button when forking window has passed
Copy "The migration period has ended and you can no longer migrate rep into this universe"
*With a link to use it for lose it forking docs

**Comment by phoebemirman** [comment]
we already hide the button when the market is finalized. the issue is when it is in awaiting finalization. should it be hidden then?

**Comment by pgebheim** [comment]
When someone migrates REP it will finalize the forking market, so that button should stay visible. So we're good with how it is now!
