### ISSUE TITLE
Trading Page: Module Tabs

### ISSUE THREAD

**Issue by sharkcrayon** [AugurProject/augur#721]
When #718 is done:

Design Prototype: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=342%3A34455

This is referring to the tabs within individual modules, like Price History, Candlestick, and Market Depth shown here:

![image](https://user-images.githubusercontent.com/4355755/50092293-ed6ee480-01ca-11e9-8bc5-8ebc6df68568.png)
(Details in the screenshot above may differ from the design. Use the design as final guidance.)

Add this to the trading page in a page-wide, reusable way.

- [ ] Using the chart module referenced above, add tab styles, including hover and selected state.
- [x] Add the functionality to switch tabs and corresponding content. Switching tabs should of course be localized enough that switching tabs in one module doesn't switch it in another.

**Comment by phoebemirman** [comment]
need the hover state for tabs
