### ISSUE TITLE
Trading Page: Price History Chart

### ISSUE THREAD

**Issue by sharkcrayon** [AugurProject/augur#722]
When #721 is done:

Design Prototype: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=342%3A34455

This task refers to this section:

![image](https://user-images.githubusercontent.com/4355755/50092727-180d6d00-01cc-11e9-9661-59cc6ba5386e.png)

Add the Price History chart.

- [ ] Apply the new styles.
- [ ] When no outcome is selected all graphed lines should be of equal weight.
- [ ] When an outcome is selected, the graphed line corresponding to that outcome should be heavier (see mock for exact weight).

**Comment by bthaile** [comment]
going to use highcharts for this chart.

**Comment by pgebheim** [comment]
Is this totally complete now?

**Comment by bthaile** [comment]
Yes this is comple
