### ISSUE TITLE
disputing market card is confused with Scalar outcome price of 0.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#7221]
issue is that outcome id 0 is Invalid, but for scalars with price range that includes 0, this is a problem. Need to show price of 0 as regular outcome value and keep Invalid pink.

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/5d93299e-aa14-4826-b698-a7f64f88f3ce)

**Comment by Chwy5** [comment]
fixed - closing
