### ISSUE TITLE
Bell message missing value for claim winnings

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7226]
Just claimed roughly $250 from claim proceeds....$115 was profit

The message also shows the wrong winning outcome

The bell message only shows a dash and not the value...

![4-10cl.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/adc44bd4-8850-4b5d-94ca-2779b88fde3d)

**Comment by phoebemirman** [comment]
this is alert data:
![4-10st](https://user-images.githubusercontent.com/6775839/79008959-54788100-7b13-11ea-9af7-9a2229ab7cea.jpg)

market position in portfolio:
![image](https://user-images.githubusercontent.com/6775839/79009729-12503f00-7b15-11ea-8027-fbc15616681d.png)

**Comment by Chwy5** [comment]
This Is Fixed -closing
