### ISSUE TITLE
Confirmed button showing on claim stakes and fee modal before claiming the reporting stake: See images

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7231]
Opened from notification:

Confirmed button already showing

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/a25c20a8-3230-4927-9f85-b9138d60aca4)

Clicking it makes it go away:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/88cc6917-e552-471a-8ff1-1f4a37a3c2aa)

I had a winning position on the same market that I had winning REP. I claimed proceeds first
This is my bell history:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/cfa1a5fd-cb1e-47cc-918b-0d2a2f845b75)

Note: maybe claiming on proceeds indirectly causes claiming stake and fees to show confirmed

**Comment by bthaile** [comment]
pulling out marketIds is incorrect. Look at `getUserAccountData` method in Users.ts

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/527afb5a-845a-49f6-b2a3-66a3fe73a4b1)


![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/16845fd2-6b4b-4605-a53d-f6c5e208ed2c)

**Comment by phoebemirman** [comment]
it could also be from switching accounts

**Comment by Chwy5** [comment]
not seeing this....closing
