### ISSUE TITLE
Trading Page: Trade History

### ISSUE THREAD

**Issue by sharkcrayon** [AugurProject/augur#724]
When #718 is done:

Design Prototype: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=342%3A34455

This task is referring to this section:

![image](https://user-images.githubusercontent.com/4355755/50097512-55c3c300-01d7-11e9-91bd-a098e7a60057.png)
(Details in the screenshot above may differ from the design. Use the design as final guidance.)

Add the trading history.

- [x] Do not include the expand icon to the right of the Trade History title. This will be built after the trading page is live.
- [x] Remove the static min height set on the trade history placeholder div (if there is one).
- [x] List the trade history, grouped by day. At the top of each day should be the total volume for that day (in shares) on the left and the date on the right.
- [x] As the user scrolls in the trade history, the date group headers (total volume for that day and the date) should be sticky. [Example](https://gedd.ski/post/position-sticky/) I believe this is doable entirely with CSS but make sure to check browser support.
- [x] Dates with no trades should be skipped (do not show the group headers).
- [x] There should be a min-height on the trading history that is equal to the min-height on the order book (check what was done there). If the browser window is tall enough to allow more than the min height of the trading history and order book, those two modules should share the vertical space in their column 50/50. (This may automatically happen already with the way the trading page layout was coded.)

**Comment by sharkcrayon** [comment]
Conversations with @adrake33 make us think that the Volume totals in the date group headers need to be added up on the frontend rather than AN since it's particular to the user's timezone.

**Comment by bthaile** [comment]
If a new endpoint for market trading history is created the data needed is:
sorted by timestamp desc
```
marketId:[ {
amount,
price,
timestamp,
outcome,
orderType,
}]
```
UI will group by day, it's dependent on user local time.

if we expect to use this endpoint for users filled orders and users trading history then add
```
filler,
creator,
tradeGroupId
```

**Comment by sharkcrayon-augur** [comment]
Talked with Chwy about something related this morning. It sounds like the candlestick period and open/close times will be based on UTC, so it probably makes sense to base what is considered a "day" in the trading history on UTC as well.

**Comment by adrake33** [comment]
@sharkcrayon-augur Was just talking to @bthaile about this. This can be taken into account when the UI side does the volume calculations. We could potentially have Augur Node return the volume calculations instead, but it's probably better to just do these calculations on the UI side so we don't have to make multiple calls to Augur Node.

**Comment by bthaile** [comment]
decided to use market trading history already in UI to format for market trading history and to populate filled orders in market trading page.

**Comment by bthaile** [comment]
Current status: There is a change needed for parent/child min height. Also, I need to do the "sticky" date and num of shares header, if the number of trades is longer than container.

**Comment by bthaile** [comment]
Thanks @phoebemirman, day header is now sticky. Looks like this task it complete.
