### ISSUE TITLE
Firefox wont load markets

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7244]
still seeing this message and cant get markets to load on Firefox

![4-11ff.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/eaa0a80d-638c-48e8-aa2c-926a2ded2bed)

**Comment by pgebheim** [comment]
btw putting this in RC2 as it's a bug not a feature.

**Comment by nuevoalex** [comment]
@Chwy5 Try deleting your storage. If that fixes the issue this can be closed.

**Comment by Chwy5** [comment]
Yeah tried that....The markets dont filter in, the categories just spin and I still get the same...Uncaught exception: object in the console

**Comment by pgebheim** [comment]
It worked for me, deleted augur-42 database as well as all the 0x databases from the storage tab.

Paul
paul@augur.net

________________________________

**Comment by Chwy5** [comment]
Ohh those were under Indexed DB for me....I had deleted local storage underneath that....delted those and now i have markets...thanks
