### ISSUE TITLE
Cashout balance doesnt match balance shown in Account Summary

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7248]
I would expect my "Cashout" balance to be my dai + dai balance of my eth reserve

![4-11casoutblance.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/9ddded77-15b2-46c3-a2dc-ce9b9e38cb6c)

![4-11acctsumbalance.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/d9d3e820-3046-474a-aa86-89372c420cfe)

specify the amount of ETH to convert up to the ETH reserve amount.  Even if user has more ETH than reserve amount only go up to ETH reserve amount.

**Comment by pgebheim** [comment]
@nuevoalex can this method specify how much eth to cash out so we can pass in the current reserve amount?

**Comment by nuevoalex** [comment]
Ah yea we should allow that for the case where the signer has excess ETH they want to keep. Can do

**Comment by Chwy5** [comment]
Calculating based off of:

Available funds + FF funds for any Open Orders + eth Reserve (dai conversion)

This is working correctly
