### ISSUE TITLE
Trading Page: Open Orders

### ISSUE THREAD

**Issue by sharkcrayon** [AugurProject/augur#725]
When #721 is done:

Design Prototype: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=342%3A34455

This task is referring to this section:

![image](https://user-images.githubusercontent.com/4355755/50105527-27031800-01ea-11e9-978c-95e77b271ada.png)
(Details in the screenshot above may differ from the design. Use the design as final guidance.)

Add the Open Orders section.

- [x] Incorporate the code from #721 for the tabs.
- [x] Add null state for when the user has no open orders. 
- [x] You should not need to set a height or a min-height on this module; it show already grow or shrink to the space available based on how the layout was coded. If there are more orders than space available to display, it should scroll internally (vertically).
- [x] Open Orders should list all outcomes the user has an open order for, no matter what outcome is selected.
- [x] All columns should grow or shrink as the browser width grows and shrinks. The outcome names should truncate into ellipses if needed. The numbers should never get cut off or wrap.
- [x] Adjust table to use new styles.
- [x] Add the "Type" column to show whether an order is Buy or Sell.
- [x] Add the color bar on the left of each order to show whether it is a buy or sell.
- [x] Show "Pending" tag when the user has signed a tx for opening an order but that tx hasn't been confirmed on chain yet. This is not clickable and has no hover state.
- [ ] Show the Complete Sets bar if the user has complete sets.
- [ ] Show the Orphaned Order bar if the user has an orphaned order.
- Ignore the "Cancel All Open Orders" button. We'll add this after the trading page is live.

**Comment by phoebemirman** [comment]
@matt-bullock 

need hover states for cancel button, tab modules, and the design for orphaned orders.

**Comment by sharkcrayon-augur** [comment]
@phoebemirman Hover states for the tab modules and cancel button are available in Figma now.

Still waiting on the design for orphaned orders.

**Comment by phoebemirman** [comment]
i've added the hover states

**Comment by sharkcrayon-augur** [comment]
👍 Perfect. I've updated the task to reflect that orphaned orders and complete sets still needs to be done (currently blocked by design).
