### ISSUE TITLE
Remove warp sync processing/reporting on mobile

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#7259]
- Keep loading from warp checkpoint
- Do not generate checkpoints on mobile

This should be implemented by turning off a config in `init-augur` and the rest of the changes should check that config.

**Comment by pgebheim** [comment]
@justinbarry -- categorized and assigned to you

**Comment by pgebheim** [comment]
@robert-e-davidson3  Can help with this config today justin unless you did it?

**Comment by justinbarry** [comment]
I started on Friday. The point of this is to prevent the IPFS from spinning up. If so, it is a little bit trickier that I thought. We need to break out the DB/checkpoint gathering stuff out of the warp controller.

**Comment by pgebheim** [comment]
Main goal would be to not pin so that those clients don't serve the data
