### ISSUE TITLE
Transaction Error while cancelling multiple (4) open orders

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#7264]
![image](https://user-images.githubusercontent.com/86010/79164435-ea234300-7d95-11ea-980b-360a15ec8c8f.png)

This was chwy's example -- this is a scalar market. Could be bug in the cancel (on contract) or the sdk passing too many cancels in for cancel in one group.

Then:
  - Cancel 1 works
  - Cancel 1 works again
  - Cancel 2 remaining in bulk works.

**Comment by Chwy5** [comment]
yes

**Comment by bthaile** [comment]
not able to repro this. I successfully deleted 4 orders.  I successfully cancelled 10 open orders. it showed failed but recovered.

**Comment by Chwy5** [comment]
working for me - closing
