### ISSUE TITLE
Decide on ETH Reserve amount for launch

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#7265]

**Comment by pgebheim** [comment]
@Chwy5 -- So your vote here is to not require more than $5 USD worth of Eth?

**Comment by Chwy5** [comment]
sorry just saw this...cheaper the better...keep under $5

**Comment by bthaile** [comment]
How much ETH reserve do we want the user to have? Enough for 3 trades? or just 2 trades?

**Comment by nuevoalex** [comment]
2 trades ideally. The issue is that is also really dependent on gas price. $5 will not pay for a single trade with 30 gwei gas prices. $10 may cover 1.

**Comment by pgebheim** [comment]
Idea:

Round to nearest $5 such that two trades are possible at current gas price unless it's over $10 total on which case account for 1.

Paul

**Comment by nuevoalex** [comment]
The UI will have to then handle the ETH reserve goal potentially changing. (e.g If they have $5 and the ETH reserve goal changes to $8 it will have to inform them its going to convert some additional DAI into their ETH reserve).

If thats acceptable I can make it function that way in the middleware so someone can do the UI part.

**Comment by bthaile** [comment]
we tell the user in the trading form that the trade will replenish their fee reserve and give them a DAI value that will be used. 

The UI does have standard gasPrice, if the UI knew how much gas to keep in reserve it could do the calculation and change the min desired ETH reserve value. 

floating Fee reserve does make the UI tricky. We need to discuss if the user needs to 'ok' the new fee reserve, so they are informed. 
Could have a message saying `Average gas price has risen, keep lower fees? $5 increase in fee reserve is needed`

**Comment by nuevoalex** [comment]
We decided to forgo any UX complexity and just go with a fixed .04 ETH reserve
