### ISSUE TITLE
Make Uniswap slippage constant configurable with a config, use 0.5% for mainnet, 10% for testing

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#7266]
Currently this value is set to 10% for the auto-uniswaping of during contract contract calls to maintain a ETH balance in the signer.

@andrewdamelio -- what do you have it set to in the UI?

@epheph @MicahZoltu -- any thoughts here are on reasonable slippage from your experience?

**Comment by MicahZoltu** [comment]
0% is the only reasonable automatic slippage amount.  Users should be able to configure it and a reasonable UI default for a liquid market may be something like 0.5%, but definitely needs to be user-configurable.

**Whatever slippage you set is nearly guaranteed to be eaten by front runners!** Uniswap front-running bots will take *all* excess slippage basically *every single transaction*, so setting slippage to 10% means "give away 10% for free to front runners".

**Comment by MicahZoltu** [comment]
Discussed [in Discord](https://discordapp.com/channels/378030344374583298/378030681630179328/703262436891033741).  I misunderstood what you all were doing originally, but the **TL;DR** of the discussion was I recommend 0.5% or less.  I can see an argument for 1% at launch, and lowering it over time as the ETH:DAI liquidity pool on Uniswap v2 fills up, but I personally think that is doing a disservice to your users by giving away 1% of their money to front-runners.

**Comment by MicahZoltu** [comment]
Data: 0.5% slippage on Uniswap v1 right now means net 93 ETH (~17,000 DAI) movement in the pool between transaction signing and transaction mining.

**Comment by pgebheim** [comment]
@robert-e-davidson3 I think you can just update the ui to use the constant after you add it... ill see if I can point you to the code.

**Comment by pgebheim** [comment]
![image](https://user-images.githubusercontent.com/86010/80754311-a8a7cd00-8ae3-11ea-857d-ddc504446ef0.png)
this happens in `contractCalls.ts` and uses the same constant as the middleware.

**Comment by robert-e-davidson3** [comment]
more changes incoming

**Comment by MicahZoltu** [comment]
This issue's title implies the rate should be 0.5%, but the PR that closes this issue appears to set the value to 5%.  This is a 10x difference and 5% is giving away a lot of free money to bots for no reason IMO.
