### ISSUE TITLE
Users should be able to claim / interact with balances after 60-day pruning window.

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#7267]
- After 60 days check
  - Affiliate Fees
  - Shares for Proceeds
  - Reports
  - Disputes
  - API: "I think I disputed" and pass in an offset through the contract

This will work by having the Contract generate the market address for an offset (nonce) and can then check if the user has any disputes, shares, etc. This will be a slow process and will need some custom ui,

**Comment by pgebheim** [comment]
We're gonna need to do some product work here to figure out how we do this.

**Comment by matt-bullock** [comment]
Spoke to Chwy about this and recommend putting them in the transaction area of the account summary.

They should probably only appear when the user has an archived balance to claim. Rest of the time this section doesn't need to show

Design: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7833%3A196490

Recommended tooltip copy: Market data gets removed after 60 days post finalization. After this you can claim any outstanding balances here.

![image](https://user-images.githubusercontent.com/39496225/79473193-1690c680-8005-11ea-9320-2aae16e3ab30.png)
