### ISSUE TITLE
clicking on position quantity doesn't pop order form

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#7269]
clicking on position quantity doesn't pop order form,

user has a short position on YesNo market and clicking on position quantity doesn't populate order form quantity.

![Screen Shot 2020-04-13 at 6 07 43 PM](https://user-images.githubusercontent.com/3970376/79169318-bfdf7e80-7db1-11ea-9833-88a1d2bf7b88.png)

**Comment by Chwy5** [comment]
fixed - closing
