### ISSUE TITLE
User gets wrong modal when MM is pointed at wrong network

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#7280]
user has MM enabled but is not logged in.

user gets this modal but should get network mismatch modal.

![image](https://user-images.githubusercontent.com/3970376/79262859-89f4d580-7e57-11ea-83c3-bb7204726ece.png)

**Comment by matt-bullock** [comment]
Looks to be an unneeded comma here between network and please

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/ea2c662d-ec1c-4d74-b6ac-e8c6fe5690d9)

**Comment by matt-bullock** [comment]
done. closing
