### ISSUE TITLE
Clear and reinitialize db tables upon redeploy

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#7288]
Problem
===

Old databases with data for the previous deployment are causing trouble for testers on test nets.

Solution
===

On app startup grab the timestamp (or tx hash?) of the UniverseCreated log of the current universe and compare with the one in the currently connected DB. If different reset the database and refresh from the current deploy using the standard syncing mechanisms.

**Comment by pgebheim** [comment]
I like this, I think it can wait into an improvement post launch.
