### ISSUE TITLE
Update Photos on trading page

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7295]
Need to update the photos on the market list pg when a user first comes to the site

https://www.figma.com/file/7VxpJHS8FP20XvpEpsN4MU/Product-Landing-Pages?node-id=52%3A1043

![image](https://user-images.githubusercontent.com/3970376/81417380-b925fc00-9110-11ea-94e8-354704d37dfe.png)

**Comment by matt-bullock** [comment]
@bconfortin can you update the copy please:

**The world’s most accessible, no-limit betting exchange** 

Bet how much you want, on sports, finance, world events and more.

**Comment by matt-bullock** [comment]
@bconfortin we updated the images to improve the clarity. Could you update these in build.

When the screen is wider could the text area grow to the right like so:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/4dbd2a2f-6970-417e-b290-e7f2f4410809)

The breakpoints are in the design as a rough guide. Let me know if you have any questions on this

**Comment by Chwy5** [comment]
looks better - closing
