### ISSUE TITLE
Last price updates only after hitting F5/reload button

### ISSUE THREAD

**Issue by mzdici** [AugurProject/augur#730]
Created an account (funded successfully via faucet) and placed several (successful) trades on https://augur-dev.firebaseapp.com

I noticed that filled bids and asks disappear immediately from the order panel, but the "last price" on the left column does not automatically update to reflect the recent price action. Neither does the corresponding percentage in the market list. 

You have to hit F5 or reload to actually see the change.

**Comment by tinybike** [comment]
Fixed in 5dc4c6e8f52ff2927aa9d7c1dbda28c205fb0a79
