### ISSUE TITLE
Automate Contract Mock Generation & Fix Mock Tests

### ISSUE THREAD

**Issue by nuevoalex** [AugurProject/augur#730]
Right now the augur-core python tests have a suite of mock-based unit tests that are set to not run as they are currently broken and fixing them will likely be an onerous process.

Part of the reason this is the case is because the Mock contracts are managed by hand. It should be a relatively simple process for our test suite to manage the generation of these mocks by using the ABI from our contracts.

Once this generation is in place it would be nice to fix or alter the mock tests so they pass and we can turn them back on then in the future perhaps even expand them if we see value in that.

**Comment by robert-e-davidson3** [comment]
Note: make sure this code is python3-compatible.
