### ISSUE TITLE
Warp Sync Market Finalize Notification

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7305]
We need to add a notification for the warp sync market

Anyone can click it, Saying "Get free REP here"

Whenever the market is in Awaiting Finalization
it should put that notification in everyone's list

load warp sync market on login

**Comment by matt-bullock** [comment]
Anyway to bring up the warp sync market on local?

**Comment by matt-bullock** [comment]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/db0ae62f-a233-4e3e-9dfc-ad0792b3930a)

Worked perfectly and REP went to my signing wallet. closing
