### ISSUE TITLE
Charts broken

### ISSUE THREAD

**Issue by mzdici** [AugurProject/augur#731]
- All data points are timed "January 1". 

- Completely broken display in multi outcomes (https://augur-dev.firebaseapp.com/m/Which_political_partys_candidate_will_win_the_2016_US_Presidential_Election_0x3dc3d2eab74ea5b8fea409c5fbb8240a6fa88b3387c26ebcb467911cb8653027)

- Clicking on a data input field of trade panel refreshes the chart each time

**Comment by stephensprinkle** [comment]
AURC PR [#82](https://github.com/AugurProject/augur-ui-react-components/pull/82) + Augur PR [#736](https://github.com/AugurProject/augur/pull/736)
