### ISSUE TITLE
Trading Page: Filled Orders

### ISSUE THREAD

**Issue by sharkcrayon** [AugurProject/augur#731]
Design Prototype: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=342%3A34455

This task is referring to this section:

![image](https://user-images.githubusercontent.com/4355755/50170270-c557b200-02ac-11e9-9c4a-896753098391.png)
(Details in the screenshot above may differ from the design. Use the design as final guidance.)

Add the Filled Orders section.

- [x] Add null state for when the user has no filled orders.
- [x] List filled orders. These are grouped by the original open orders, and can be expanded to show the orders that fill the original order. For example, if I placed an open order to buy 10 shares of SF, someone came along and sold me 2 shares of SF, and a second person came along and sold me 6 shares of SF, the order listed in this table would be the original order for 10 shares, and would expand to show the two fills of 2 and 6 shares.
- [x] Only orders that have been partially or fully filled are listed here. Orders that are still entirely open (not filled at all) are not.
- [x] The Fill Date column shows the date of the most recent fill.
- [x] The Quantity column is the total quantity of the original order.
- [x] When clicked on, an order row should expand to show the specific fills. Most recent fills should be listed at the top.
- [x] The Filled column within the expanded area shows how many shares were filled.
- [x] The View Transaction Details links to the etherscan tx.

**Comment by bthaile** [comment]
Could extend `getMarketPriceHistory` to include data needed for Market trade history and filled orders. or just create a new endpoint to return all trading activity for a market, including `filler` and `creator`.

see https://github.com/AugurProject/augur/issues/724
on data needed for market trading history.
