### ISSUE TITLE
Sports Book market page header

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#7319]
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet---UI?node-id=2702%3A1201

![Screen Shot 2020-04-16 at 11.28.42 AM.png](https://images.zenhubusercontent.com/57155267bf93871ccd99a48b/b8dd59eb-2252-40b0-b6b2-604bc964173d)

Update/create the sportsbook market page header section

**Comment by Chwy5** [comment]
The wrong header and coupons are in the SB....ones added were for the exchange

**Comment by yanelbottini** [comment]
<img width="1377" alt="Screen Shot 2020-08-03 at 07 48 36" src="https://user-images.githubusercontent.com/49915900/89175253-c579f380-d55d-11ea-8760-4eb0c3466aab.png">

- Breadcrumb categories are smaller than original design. Color is different. 
- Could we improve alignment for Help icon? Right now seems it's not centered. 
- Missing comment icon (top right corner)
- Could we improve margin between Label (Estimated time..., matched, fee) and content? It should be 4px:

<img width="715" alt="Screen Shot 2020-08-03 at 07 53 04" src="https://user-images.githubusercontent.com/49915900/89175631-7f715f80-d55e-11ea-9d34-adbc8b60f24a.png">
