### ISSUE TITLE
Trading Page: Positions

### ISSUE THREAD

**Issue by sharkcrayon** [AugurProject/augur#732]
Design Prototype: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=342%3A34455

This task is referring to this section:

![image](https://user-images.githubusercontent.com/4355755/50178807-bc71db00-02c2-11e9-9f28-a4b719ab4860.png)
(Details in the screenshot above may differ from the design. Use the design as final guidance.)

Add the Positions section.

- [x] Add null state for when the user has no positions.
- [x] List Positions with updated styles.
- [x] Add the Type column.
- [x] When a position is short, Quantity should show the net position number. When quantity is long, Quantity should show the normal quantity number. Check with Aaron and Alex on this logic to make sure you're implementing it correctly.
- [ ] Show the "Claim Proceeds" button if the market is finalized and the user holds a winning position.

**Comment by sharkcrayon-augur** [comment]
@phoebemirman What needs to be done on this one still? Is it waiting for PR review, or do you need some more info on how something is supposed to work?

**Comment by phoebemirman** [comment]
Just the last checkmark is outstanding but I am planning on doing that today.
