### ISSUE TITLE
Placed bid of 200 shares, actual bid on the book is 122

### ISSUE THREAD

**Issue by mzdici** [AugurProject/augur#732]
https://augur-dev.firebaseapp.com/m/Which_political_partys_candidate_will_win_the_2016_US_Presidential_Election_0x3dc3d2eab74ea5b8fea409c5fbb8240a6fa88b3387c26ebcb467911cb8653027

- No preexisting ask for this price level, so bid should not have get filled at all 
- BID 200 shares @ 0.60ETH, actual BID appearing on the panel is 122.4 shares @ 0.60ETH. 
- BID order was fully executed for 200 shares, per "transactions" page
- Could be (very unlikely) that someone filled that order partially in the small time interval, so not sure if bug

**Comment by tinybike** [comment]
AFAICT this is working as of 3447942296fe8b498d89d2f3e78b7226e9e960ec.  Closing, but please re-open if this happens again.
