### ISSUE TITLE
Sportsbook Market Outcomes Table

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#7320]
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet---UI?node-id=2702%3A1201

![Screen Shot 2020-04-16 at 11.31.27 AM.png](https://images.zenhubusercontent.com/57155267bf93871ccd99a48b/0cafb23d-c5ce-4d19-b31e-31f5ef076659)

Should be able to re-use the outcomes table created for market cards here -- just need to edit the styles a bit on this page.

The fingers crossed should only appear for markets that are active and not being reported/resolved. Once resolved/reporting that should be hidden.

**Comment by Chwy5** [comment]
duplicate ticket - closing this one
