### ISSUE TITLE
sportsbook market page comments

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#7328]
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet---UI?node-id=4469%3A208368

![Screen Shot 2020-04-16 at 12.37.01 PM.png](https://images.zenhubusercontent.com/57155267bf93871ccd99a48b/837ed6e2-cf60-4d51-99a4-d5c1b9f8d116)

Review/confirm/add 3box comments section to market page and ensure the styling is correct to the mock for sportsbook

**Comment by yanelbottini** [comment]
@bconfortin @JohnDanz we can't see the 3box's comment box on the build. Is it there?

**Comment by bconfortin** [comment]
@yanelbottini I activated 3box's comments on Friday. You should be able to see it now.

**Comment by matt-bullock** [comment]
@bconfortin I had to approve 8 torus popups to activate.

I'm having to activate comments on every market, even when I'd previously just activated. Can this be fixed to only require one activation across all markets?
