### ISSUE TITLE
My Created Markets Bug

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7336]
After creating a market and approving pre-liquidity I see a line in My Created Markets that says in reporting liquidity depleted.  (Also the All and Open show extra numbers in there)....see screenshot (only had created one market in fresh account)....Refreshing makes it go away

![4-16my.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/2279ec56-52e0-4d3e-b74e-6f954b0cb435)

got this after creating my second market in that account

![4-16a.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/95ea452f-4149-46dc-b763-91cd2d579275)

**Comment by bthaile** [comment]
When a user creates a market, UI adds a placeholder so `processing ...` can be shown.
This placeholder isn't being removed, so it's still shown after market has been created.
not sure why this is happening after recent deployment. 
looks like the transaction hashes aren't matching up so the UI doesn't have the data needed to remove the placeholder. Need to look more into it.

**Comment by Chwy5** [comment]
not seeing this anymore- closing
