### ISSUE TITLE
Affiliate fees will be directly sent to affiliate during trading

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#7338]
In order to accomplish reasonable ux, fees will be sent to the affiliate during trading instead of accounting for them on chain and requiring claim calls.

This makes the feature cheaper for everyone, allows the UI to move forward with no ux changes, and doesn't have any attack surfaces not already present through scam markets.

Alex to do in RC2

**Comment by nuevoalex** [comment]
For extra clarity there will still be validity checks on the fees going through _after_ finalization. This means that there is no reliable way to rely on these fees as someone attempting to find an unexpected advantage in creating invalid markets.

**Comment by pgebheim** [comment]
closed with #7341
