### ISSUE TITLE
Add 'Statistics' button to the the Finance sub category of market creation 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7347]
Icon design: https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=3392%3A0

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f7609647-ff85-42e1-8ab5-5272d0e895e8)

**Comment by Chwy5** [comment]
added-closing
