### ISSUE TITLE
Sports Betting - My Bets - Header

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#7350]
Header area includes: 

![Header.png](https://images.zenhubusercontent.com/5cc988ee77bc5b0505df9320/9cbcf12b-0e7e-4431-973a-f4119b35c3ae)

- Title
- Optional legend: “To view your unmatched… Go to trading” . Legend should only be visible when the registered user has unmatched bets. 
- “Claim All” notification should only be visible when user has winnings to claim. 
- Filtering / Sorting options:

When user is viewing by **Event**, options are:

![Header - view by event.png](https://images.zenhubusercontent.com/5cc988ee77bc5b0505df9320/27fd4883-914b-4310-a58e-c99b9e9a063d)

[Go to Figma File](https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=3571%3A219)

- Filter by market status: All / Open / In Settlement / Resolved.
- View “Games” or “Futures” markets. 
- Search

When user is viewing by **Outcome**, options are: 

![Header - view by outcomes.png](https://images.zenhubusercontent.com/5cc988ee77bc5b0505df9320/5113f528-4a65-44ff-ae03-ff4074b08407)

[Go to Figma File](https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=3608%3A287)

- Filter by bet date: Last 30 days / Last 7 days / Last 24 hours.
- View “Active” or “Resolved” markets: Active market is a market that is Open or In Settlement.

**Comment by Chwy5** [comment]
Optional legend: “To view your unmatched… Go to trading” . Legend should only be visible when the registered user has unmatched bets. 

This is showing all the time....should only show when if a user has an unmatched bet
