### ISSUE TITLE
Make processing state buttons faster

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7365]
After a transaction is confirmed, the processing state button shows confirmed.  But it takes a very long time for this to go away.  Need to improve the speed of dismissal

-- note:
Need to standardize handling pending transactions. need to add transaction hash to pending queue entries. so that transaction can be looked up if status hasn't been updated in 10 blocks.

**Comment by bthaile** [comment]
Is there a specific transaction you are testing? The speed varies, slowest is trading

**Comment by Chwy5** [comment]
Notice it in a few places, but trading and cancelling an order stand out....Takes like 15-20 seconds for the confirmed button to disappear....if we can get this to 2 seconds would make it feel much more snappy

**Comment by bthaile** [comment]
Issue is that UI is waiting for SDK to send event in order to update user values like positions and PL. UI can't do that until SDK has processed the block data.

**Comment by bthaile** [comment]
Need to standardize handling pending transactions. need to add transaction hash to pending queue entries. so that transaction can be looked up if status hasn't been updated in 10 blocks.

**Comment by pgebheim** [comment]
This issue appears to be exacerbated by the blocks being cached by alchemy. On mainnet this discrepancy wont happen to this extent.
