### ISSUE TITLE
Unrealized PnL not updating

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7380]
My unrealized Pnl isnt updating on the trading pg or in portfolio pg....I am long at .55...someone else traded .57's (last price)...my unrealized pnl didnt update

![4-20unrealized.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/48b7f74e-298d-4b78-987e-752f4c19af98)

![4-20unrealized2.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/e354baf3-ef10-4aa3-9be6-515f4dd835d7)

**Comment by bthaile** [comment]
I suspect that this is the issue where UI mesh client crashes and UI isn't getting any order events so it doesn't know to update.

**Comment by Chwy5** [comment]
not seeing this anymore - closing
