### ISSUE TITLE
Sports Betting - My Account - My Created Markets Disabled on SportsBook

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#7398]
User can't create markets from Sportsbook UI. So, button won't be available on the UI:

![Screen Shot 2020-04-21 at 09.01.30.png](https://images.zenhubusercontent.com/5cc988ee77bc5b0505df9320/203f59e1-9662-4d53-b7cd-7209d5a94edd)

Empty state for the box:

![Screen Shot 2020-04-21 at 09.02.22.png](https://images.zenhubusercontent.com/5cc988ee77bc5b0505df9320/23d0c98f-b80f-46bf-9e37-7be6902d639b)

[Figma link](https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=3606%3A1015)

**Comment by Chwy5** [comment]
done - closing
