### ISSUE TITLE
Sports Betting - My Account - Search on Boxes

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#7401]
This is the expected behavior for search feature on the My account boxes: 

![Screen Shot 2020-04-21 at 09.25.45.png](https://images.zenhubusercontent.com/5cc988ee77bc5b0505df9320/9307bca0-35f9-422e-bbee-5accbd58c2b9)

[Figma link](https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet-Design-System?node-id=1227%3A0)

**Comment by yanelbottini** [comment]
Please update close icon so it match Betting UI:

<img width="224" alt="Screen Shot 2020-08-12 at 08 49 45" src="https://user-images.githubusercontent.com/49915900/90011917-d1aa3300-dc78-11ea-9103-fcb028a58d8d.png">

**Figma Reference:**
https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet-Design-System?node-id=1227%3A0

**Comment by yanelbottini** [comment]
- Icon doesn't match design:
<img width="336" alt="Screen Shot 2020-08-18 at 17 32 41" src="https://user-images.githubusercontent.com/49915900/90562627-e6a32c80-e178-11ea-80c5-9f62e9d034b8.png">

- Please, delete "Go to trading" on empty search results for My Created Markets
<img width="522" alt="Screen Shot 2020-08-18 at 17 33 06" src="https://user-images.githubusercontent.com/49915900/90562653-ed31a400-e178-11ea-87aa-753a29f45e53.png">

**Comment by matt-bullock** [comment]
looks good. closing
