### ISSUE TITLE
Sports Betting - My Account - Page Layout Responsive

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#7403]
Mobile layout:

[Figma link](https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=4153%3A196694)

Responsive references:

[Figma link](https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=3272%3A1612)

**Comment by JohnDanz** [comment]
https://github.com/AugurProject/augur/issues/8873

**Comment by yanelbottini** [comment]
In general looks fine. Some comments:

- I'm seeing a double scroll bar on tablet breakpoint:

<img width="672" alt="Screen Shot 2020-09-16 at 09 56 05" src="https://user-images.githubusercontent.com/49915900/93340761-a9779c00-f803-11ea-96fe-e3d7c9e3361d.png">

- Can we check if notifications are showing up on mobile? Because right now seems empty to me, but I'm seeing the notifications on desktop.

![WhatsApp Image 2020-09-16 at 10 00 35 (2)](https://user-images.githubusercontent.com/49915900/93341567-a6c97680-f804-11ea-9d69-25f97ffae46e.jpeg)
<img width="521" alt="Screen Shot 2020-09-16 at 10 09 39" src="https://user-images.githubusercontent.com/49915900/93341645-c19beb00-f804-11ea-8115-947309d0be7a.png">

- Can we reduce the size we use to show page title and tabs on mobile?

<img width="875" alt="Screen Shot 2020-09-16 at 10 13 24" src="https://user-images.githubusercontent.com/49915900/93342083-46870480-f805-11ea-91a5-772d08044845.png">

- Filter icon seems different (First one design, second dev)

<img width="155" alt="Screen Shot 2020-09-16 at 10 16 56" src="https://user-images.githubusercontent.com/49915900/93342476-c57c3d00-f805-11ea-8580-f42b21399767.png">

<img width="237" alt="Screen Shot 2020-09-16 at 10 17 13" src="https://user-images.githubusercontent.com/49915900/93342515-cf9e3b80-f805-11ea-918d-1aa19af7b55e.png">


- Please, update to match design

<img width="1139" alt="Screen Shot 2020-09-16 at 10 16 04" src="https://user-images.githubusercontent.com/49915900/93342405-b1384000-f805-11ea-8729-3e5b7093c5ce.png">

Figma reference: https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=4153%3A196592

**Comment by yanelbottini** [comment]
- Dropdown styles are incorrect. The ones applied to My created markets are ok.
<img width="450" alt="Screen Shot 2020-10-07 at 17 29 58" src="https://user-images.githubusercontent.com/49915900/95384339-d9760480-08c2-11eb-9232-1901a3e1ce86.png">

- Missing buttons:
<img width="456" alt="Screen Shot 2020-10-07 at 17 30 00" src="https://user-images.githubusercontent.com/49915900/95384345-db3fc800-08c2-11eb-9448-2858ad1b3fba.png">

- Footer should be fixed to bottom:
<img width="495" alt="Screen Shot 2020-10-07 at 17 30 19" src="https://user-images.githubusercontent.com/49915900/95384347-dbd85e80-08c2-11eb-957c-e6a77a12106e.png">

- Gray bkg should continue. Missing Apply filter button. 
<img width="486" alt="Screen Shot 2020-10-07 at 17 30 31" src="https://user-images.githubusercontent.com/49915900/95384350-dc70f500-08c2-11eb-96b4-d80ba876df8a.png">

**Comment by bconfortin** [comment]
@yanelbottini 

> Missing Apply filter button.

When I created those filters, I made them generic so we could use the same component anywhere in the UI. Since it's generic, it's hard to keep track of which filters were applied, that's why the filters are applying automatically when clicked instead of when we click an "Apply filters" button.

I still need to figure out the best strategy for that, so I am going to ask you create a separate ticket since it's going to demand some work.

Or we can leave it without the button since the filter process in this case is very fast and performant, as opposed to the Market List page, where we fetch a lot of data every time we click the "Apply filters" button.

**Comment by yanelbottini** [comment]
Hi @bconfortin Ok. I'll check with Chwy and Matt to see what they think.

I've found some other stuff on mobile:

- There seems to be a white space between notifications? 
- All buttons should be like the first one (Full-width)

![WhatsApp Image 2020-10-14 at 06 18 42 (5)](https://user-images.githubusercontent.com/49915900/95971326-72d37800-0de7-11eb-81ff-08d247ee3a25.jpeg)

- The box containing Active markets doesn't follow the same approach than the rest of them. I mean: On notifications I only have 2 notifications and the box is as tall as those 2 notifications. While on Active Markets is full height. 

![WhatsApp Image 2020-10-14 at 06 18 42](https://user-images.githubusercontent.com/49915900/95971554-c04fe500-0de7-11eb-90aa-6ea67053f9c9.jpeg)

**Comment by yanelbottini** [comment]
Looks fine. Wonder if we can unify the style for this 2 empty states. One has a box, while the other doesn't. Let's do whatever is simpler, but double check that all the sections within My Account (Favorites, Active Markets, Created Markets, Favs, Notifications) use the same pattern:

![e118d2e3-b4dc-417b-a0e1-551b85e2521f](https://user-images.githubusercontent.com/49915900/96267588-5c235180-0f9e-11eb-85aa-94cf543163ad.jpg)

![fff38225-5f60-4c24-9567-3a1322478e02](https://user-images.githubusercontent.com/49915900/96267584-5af22480-0f9e-11eb-9db2-50d6bf1d36d2.jpg)

Can we delete the line break between "Only... To view" so it fits in  3 lines? 

<img width="383" alt="Screen Shot 2020-10-16 at 10 59 20" src="https://user-images.githubusercontent.com/49915900/96267827-a99fbe80-0f9e-11eb-9929-9f318b9b7b93.png">
