### ISSUE TITLE
Add events for mesh browser crash and peers count

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#7404]
1. If mesh browser client crashes emit event out event that UI can use. 
2. When mesh browser client connects / disconnects to peers emit event with number of connected peers.

**Comment by pgebheim** [comment]
For (1) we need to emit errors from `browser-mesh.ts` in the error handler.
https://github.com/AugurProject/augur/blob/master/packages/augur-ui/src/services/browser-mesh.ts#L67

For (2) we will need to poll using the `getStatsAsync()` call on the browser mesh instance. This returns peer counts and other info that we could use to debug. We can add this information to the NewBlock event so the UI can just react.
