### ISSUE TITLE
Docker setup without wiping out local db on each run

### ISSUE THREAD

**Issue by afterether** [AugurProject/augur#7407]
I noticed that scripts that create Docker containers are using '-rm' flag and thus, upon stopping augur process, all docker containers are removed and the local data entered in the system is wiped out.

Can we add two separate processes for this?, like:
1. Initialize local db (single time setup)
2. A script that would run all required docker containers without doing the initialization step again.

TIA

**Comment by pgebheim** [comment]
That's done this way on purpose for dev since you most commonly need to run things and then restart it all only if there's contract changes or if you want to throw away the state.

The option to save it would require bind mounts for the dockers to save their chain data locally which is a pretty wonky set up because the goal is to be able to quickly spin up with a pre-defined contract state.

the -rm flag doesn't actually matter here since its the data the needs to be persisted.

If you want things to stick around I recommend you start a geth instance and then deploy to it manually:

```bash
# Terminal 1
% yarn docker:geth -v ./local/path:/geth/chain # Start a geth node, volume mounting the chain state into the local path ./local/path

# Terminal 2
% yarn flash docker-all --dev --do-not-run-geth # Will deploy contracts to the existing geth node
```

I think we should add this formula to the complex dev usage docs

**Comment by afterether** [comment]
> 
> # Terminal 2
> % yarn flash docker:all --dev --do-not-run-geth # Will deploy contracts to the existing geth node
> ```
@pgebheim 
thanks, are you sure this is the command? I am getting "usage" output, it seems that `--dev` is not available flag for `flash`

**Comment by pgebheim** [comment]
Sorry typo, updated original comment

```
yarn flash docker-all --dev --do-not-run-geth
```

**Comment by afterether** [comment]
thanks, the contracts were deployed correctly, but it seems that this geth image is using network id `12346` , while the UI is set to network `103` 

@pgebheim 
I wonder where is the UI takes the network ID from ? is it in some config file?

```
niko@desk :~/eth$ curl -H "Content-Type: application/json"  -X POST --data '{"jsonrpc":"2.0","method":"net_version","params":[],"id":67}' http://[::]:8545
{"jsonrpc":"2.0","id":67,"result":"12346"}
niko@desk :~/eth$
```
![metamask_error](https://user-images.githubusercontent.com/33187946/79898045-33941380-83d0-11ea-83de-a8c67d384a1b.png)

**Comment by pgebheim** [comment]
Correct -- You will need to delete the database for 0x and Augur the browser when switching networks.

**Comment by pgebheim** [comment]
oh we cache the network id here as well:
packages/augur-artifacts/src/environments/local.json

That should be over-written when you run `flash docker-all` but perhaps there's an issue there.

@robert-e-davidson3 Am I correct above?

Minimally, you will need to restart the ui dev server.

**Comment by afterether** [comment]
@pgebheim 

I have changed the file ./src/modules/common/constants.ts in the `augur-ui` and it works:

```
// network name to id map
export const NETWORK_IDS = {
  Mainnet: '1',
  Ropsten: '3',
  Rinkeby: '4',
  Kovan: '42',
  Private1: '101',
  Private2: '102',
  Private3: '12346',
  Private4: '104',
};

```
in IndexDB I can see a folder "augur-12346" now.

but it is still wiping out data upon docker restart, so I am looking how to fix this.

**Comment by pgebheim** [comment]
You shouldn't edit that constant, but we should instead add another that has that network id.
