### ISSUE TITLE
Full passphrase support in newest Trezor firmwares (1.9.0 and 2.3.0)

### ISSUE THREAD

**Issue by tsusanka** [AugurProject/augur#7421]
We have done some modifications regarding how passphrase is communicated between Trezor and the host.

Please upgrade the [trezor-connect](https://www.npmjs.com/package/trezor-connect) dependency of your application to latest (8.1.1 atm), otherwise your users won't be able to enter passphrase on the device (on Trezor T).

Thanks!

**Comment by pgebheim** [comment]
The V2 UI doesn't support direct trezor login -- will will remove these lib dependencies.
