### ISSUE TITLE
Add status for current service

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7425]
[Figma](https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=4079%3A0)

**When service is good:** display green dot next to order book header

**When service is experiencing a delay:** add yellow dot next to order book header. On hover tooltip should say 'Degraded service'

**When service is broken and requires restart:** add red dot next to order book header. On hover tooltip should say 'Something went wrong, please refresh your page'. In addition to this a banner is shown at the top of all app pages. Refer to the figma design for placement across different breakpoints.

**Comment by Chwy5** [comment]
Yellow and green work

 Need to get into a bad state to test red

**Comment by Chwy5** [comment]
got it by letting my computer go into sleep mode and restarting...got the red and the message.

Closing
