### ISSUE TITLE
Make sure all links have the correct url

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7426]
If unsure of where any of the links should go to, ask Matt or Peter

**Comment by andrewdamelio** [comment]
Went through all the links and they all seem to be ok, except for one i listed below under Issues.
cc @matt-bullock 

@petervecchiarelli  Would you be able to verify the ones i tested below? I provided a screenshot to the hyperlink + the URL it links to.

### Issues
1) Betting UI link
<img src="https://user-images.githubusercontent.com/1683736/80034303-32401500-84bc-11ea-909f-e38c2fd9c34c.png" width="325" />

https://www.augur.net

### Tested

<img src="https://user-images.githubusercontent.com/1683736/80034324-3c621380-84bc-11ea-90a9-240142bdf42a.png" width="333" />

https://metamask.zendesk.com/hc/en-us/articles/360020394612-How-to-connect-a-Trezor-or-Ledger-Hardware-Wallet%22

<img src="https://user-images.githubusercontent.com/1683736/80034351-4ab02f80-84bc-11ea-82cb-bd65b193e14f.png" width="333" />

https://help.augur.net/prediction-markets/crypto-glossary#what-is-dai

<img src="https://user-images.githubusercontent.com/1683736/80034362-51d73d80-84bc-11ea-96f1-ddd8843e0e3d.png" width="333" />

https://help.augur.net/getting-started/adding-funds

<img src="https://user-images.githubusercontent.com/1683736/80034389-5b60a580-84bc-11ea-9061-5a5d2d8be366.png" width="333" />

https://help.augur.net/getting-started/signing-up#gas-station-network

<img src="https://user-images.githubusercontent.com/1683736/80034436-6ddadf00-84bc-11ea-94e4-d3608b26cd99.png" width="333" />

https://help.augur.net/trading/trading-faq#how-do-i-short-an-outcome

<img src="https://user-images.githubusercontent.com/1683736/80034474-77fcdd80-84bc-11ea-92c8-fd94718c0b39.png" width="333" />

https://help.augur.net/trading/trading-faq#what-does-invalid-mean

<img src="https://user-images.githubusercontent.com/1683736/80034223-16d50a00-84bc-11ea-94fc-9e5bae30b411.png" width="333" />

https://help.augur.net/trading/trading-faq#what-does-invalid-mean

<img src="https://user-images.githubusercontent.com/1683736/80033422-ae395d80-84ba-11ea-8de7-93e3b1f7d4b1.png" width="333" />

https://help.augur.net/trading/trading-faq#what-does-invalid-mean

<img src="https://user-images.githubusercontent.com/1683736/80033972-9c0bef00-84bb-11ea-883f-069a7f8efe1e.png" width="333" />

<img src="https://user-images.githubusercontent.com/1683736/80033980-9f9f7600-84bb-11ea-8626-07c6229b462b.png" width="333" />

https://help.augur.net/disputing-explained

<img src="https://user-images.githubusercontent.com/1683736/80034015-acbc6500-84bb-11ea-87b3-de7b68e000f6.png" width="333" />

https://help.augur.net/getting-started/adding-funds

<img src="https://user-images.githubusercontent.com/1683736/80034044-b776fa00-84bb-11ea-8d43-d0b214fdecf8.png" width="333" />

https://help.augur.net/getting-started/signing-up#gas-station-network

<img src="https://user-images.githubusercontent.com/1683736/80034080-c65dac80-84bb-11ea-876e-05abbaebf42d.png" width="333" />

https://help.augur.net/getting-started/adding-funds

<img src="https://user-images.githubusercontent.com/1683736/80034114-decdc700-84bb-11ea-9c38-251c1c3b96fe.png" width="333" />

https://help.augur.net/reporting-or-disputing-faq#what-are-participation-tokens

**Comment by petervecchiarelli** [comment]
@andrewdamelio 

**Under Issues:**

- The Betting UI one should link to augur.net, I believe.

**Under Tested**

- For, What is DAI? You can use: https://help.augur.net/prediction-markets/augur-faq#what-is-dai

- For Learn more about your address: https://help.augur.net/prediction-markets/augur-faq#what-is-my-account-address

Rest look good!

**Comment by matt-bullock** [comment]
This was actually meant for the website (see the project label) but it sounds like this task needed doing for the app anyway so no loss. I'll create another ticket for the website. @andrewdamelio can you update the links Peter added, then send it back and I'll close.
