### ISSUE TITLE
NFL Draft Templates

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7431]
(Multiple Choice):

1)  [year] NFL Draft: Who will be the [1st] overall pick?
Estimated scheduled start time:
                                                  *[1st/2nd/3rd]
Must Include Other(Field) as an outcome

2) [year] NFL Draft: Who Will be the first [Position] selected?
Estimated scheduled start time:
*Position= [Quarterback, Wide Receiver, Running Back, Offensive Player, Defensive Player]

Must Include Other(Field) as an outcome

3) [year] NFL Draft: The First draft pick by the {Team}?
Estimated scheduled start time:

Must Include Other(Field) as an outcome

4)  [year] NFL Draft(O/U):  [#].5 Total [Position] drafted in Round 1
Estimated scheduled start time:
*Position= Quarterbacks, Wide Receivers, Running Backs, Defensive Players, Offensive Players

Over [#].5 
Under [#].5

5)  [year] NFL Draft(O/U):  When will [Input Players Name} be selected? Over/Under, Pick [#].5 
Estimated scheduled start time:

Over [#].5 Pick
Under [#].5 Pick

Added Resolution Rules For markets 1-3:

-Outcomes are determined by the player selected at the time of the "Pick".  Trades which occur after a player is selected do not impact the results.  For example, to determine the winner of the first pick in the draft...If a player was selected with the first pick in the draft and was then traded to the team with the 3rd pick.  The original player selected first would be the winning outcome.
-If the winning outcome is a player not listed in the market outcome, the market should resolve as "Other (Field)"
-If the event in the market question is not determined for any reason, by event resolution, this market should resolve as "Invalid".

Added Resolution Rules For markets 4&5:

-Outcomes are determined by the player selected at the time of the "Pick".  Trades which occur after a player is selected do not impact the results.  For example, If a QB was selected in the first round and was later traded for another player in the 2nd round.  The QB would count towards the first round total.
-If the event in the market question is not determined for any reason, by event resolution, this market should resolve as "Invalid".

**Comment by Chwy5** [comment]
Templates 1 through 3 are missing the Estimated Schedule start time:

Template 3 has the wrong Market Question...it should be:

[year] NFL Draft: The First draft pick by the {Team}?
Estimated scheduled start time:

Must Include Other(Field) as an outcome

We still need to tie the resolution time to the est. scheduled start time

**Comment by bthaile** [comment]
I can add the est date time. How many hours after the est date time should be the event expiration?

Template 3, I changed the question. Wasnt sure what was meant by `[year] NFL Draft: The First draft pick by the {Team}?` what is {Team}. Wanted to chat about that.

**Comment by Chwy5** [comment]
Template 5 For NFL and NBA is not correct in the wording should say "When Will...." (ours says what round)

5) [year] NFL Draft(O/U): When will [Input Players Name} be selected? Over/Under, Pick [#].5
Estimated scheduled start time:

Also NBA (Only) Template 2 and 3 the hours for resolution are currently 48hrs we need to change them to 8 hrs

**Comment by Chwy5** [comment]
fixed - closing
