### ISSUE TITLE
A smarter chaos monkey

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#7441]
Goal
===

 Create a bunch of bots that will simulate *some* of the properties of
  a real market. Runs on markets, etc. They will all run in the same thread and
  drink from the same datastore.
 
Personas
====
  A persona defines a particular traders strategy.
 
  A trade strategy culminations of the following decisions:
  1. Percentage of funds to put at stake. This might be a proxy for how risky a
  2. Which markets to trade in.
  3. How aggressive to be within a given market.
  4. Time of day range the user is active
 
  Types of persona.
  1. Aggressive
  2. Taker only
  3. Maker only
  4. Only focused on one market
  5. Thrify
  6. Normal distribution
  7. Uniform Distribution
  8. Focused on markets with certain keywords/categories.
 
  Disputing/ Reporting
  TBD.

**Comment by justinbarry** [comment]
Ref #7317

**Comment by pgebheim** [comment]
Putting this into v2 post for more testing unless we need to get some scenarios planned up for testing.
