### ISSUE TITLE
Financial template Bug

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7446]
Dax index market appears to be letting me create a resolution time before I should be able to

Dax closes at 530pm CET

I am getting this message (Cet is 6hrs ahead of EDT)
![4-23time.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/6449b572-481e-4c69-a61c-9c229eaa8aae)

**Comment by bthaile** [comment]
The template configuration for DAX is 
UTC +2
1:30PM

I can change it to 
UTC +2 
5:30PM

We use UTC +2 because of daylight savings time.

**Comment by Chwy5** [comment]
fixed - closing
