### ISSUE TITLE
Replace Subscription class on Augur instance with an EventEmitter

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#7447]
We have a couple of places where we chain Subscriptions -- and I am pretty sure they're not needed.

Augur has `events`, and controller has its own member `events` which uses the Augur `events` as a parent, but then I don't believe it is ever used.

The one thing that we may need the custom class for is `emitAfter` which alex wrote for... something. But that could honestly have been done with:

```
augur.events.once('theEventICareAbout', () => augur.events.emit('theEventIWantToGoLater'));
```

**Comment by pgebheim** [comment]
Tempted to fix this because currently there's a bug where if we don't emit with a payload it doesn't actually get sent -- and I think there may be some errors because of it.

**Comment by justinbarry** [comment]
@pgebheim This seems to work. Do you think something more nefarious is at play? And do you have an example of something that wasn't firing?


https://github.com/AugurProject/augur/blob/GH-7447-Replace-Subscription-class-on-Augur-instance-with-an-EventEmitter/packages/augur-sdk/src/subscriptions.test.ts

**Comment by pgebheim** [comment]
I did this
