### ISSUE TITLE
Empty 'Market' field in TokenTransferred event and TokenBalanceChanged event

### ISSUE THREAD

**Issue by afterether** [AugurProject/augur#7453]
I am parsing the event logs for Augur contracts (working with local testnet currently)

I have detected that in the Event TokenTransferred, the field 'Market' is empty (0x00000000000000000....000)

![empty_market_address](https://user-images.githubusercontent.com/33187946/80161179-27a57e80-8595-11ea-9eae-fa9657bbb798.png)

In Augur.sol the event is defined as:

`event TokensTransferred(address indexed universe, address token, address indexed from, address indexed to, uint256 value, TokenType tokenType, address market);`

This is event is fired by this function;

```
    function logTokensTransferred(address _universe, address _token, address _from, address _to, uint256 _amount, TokenType _tokenType, address _market, uint256 _fromBalance, uint256 _toBalance, uint256 _outcome) private returns (bool) {
        emit TokensTransferred(_universe, _token, _from, _to, _amount, _tokenType, _market);
        emit TokenBalanceChanged(_universe, _from, _token, _tokenType, _market, _fromBalance, _outcome);
        emit TokenBalanceChanged(_universe, _to, _token, _tokenType, _market, _toBalance, _outcome);
        return true;
    }

```

And this function is called with these parameters:

```
niko@desk :~/eth/dev/augur/packages/augur-core/source/contracts$ grep logTokensTransferred *
Augur.sol:        logTokensTransferred(address(_universe), msg.sender, _from, _to, _value, TokenType.ReputationToken, address(0), _fromBalance, _toBalance, 0);
Augur.sol:        logTokensTransferred(address(_universe), msg.sender, _from, _to, _value, TokenType.DisputeCrowdsourcer, address(_disputeCrowdsourcer.getMarket()), _fromBalance, _toBalance, 0);
Augur.sol:        logTokensTransferred(address(_universe), msg.sender, _from, _to, _value, TokenType.ParticipationToken, address(0), _fromBalance, _toBalance, 0);
Augur.sol:    function logTokensTransferred(address _universe, address _token, address _from, address _to, uint256 _amount, TokenType _tokenType, address _market, uint256 _fromBalance, uint256 _toBalance, uint256 _outcome) private returns (bool) {
niko@desk :~/eth/dev/augur/packages/augur-core/source/contracts$ 
```
it's the 7th parameter, and these are the values for it:

- address(0)
- address(_disputeCrowdsourcer.getMarket())
- address(0)

So, why are you hardcoding the market to 0? Can we have the real market address here so all the pieces of data match perfectly in the event chain of a transaction? 

And since the same function emit two events (`TokenTransferred` and `TokenBalanceChanged`) we have this inconsistency for two events. But as `TokenBalanceChanged` is emitted twice, we have 3 inconsistent events in total.

**Comment by pgebheim** [comment]
Reputation and ParticipationTokens don't belong to a specific market (as shares do) -- and so there's no market associated with their action. This isn't really an inconsistency it is just that different token types have different pieces of information that matter. By sharing a log type we're able to more quickly query all the logs relating to transfers for an address (which speeds up UI load times).
