### ISSUE TITLE
(Links unavaiable until release) Website: Add correct urls to all links

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7457]
Ask Peter or me if unsure of any

**Comment by matt-bullock** [comment]
Still a bunch of links missing from the developers page:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/dab9ab15-df8c-4d1a-80f8-da46909da974)

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/c99f89ea-6c83-4cbe-8091-ac8e45d412ed)

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/6ae70ef5-83d9-4b65-ba7f-66ae96d1fc15)

This seems broken
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/c0462ed5-8d67-4a53-8e74-0af61cd9c434)

**Comment by bconfortin** [comment]
Do you have the links for these two?
Contract ABI And Addresses - ?
Smart contract docs in github - ?

**Comment by Chwy5** [comment]
What is the status on this?

**Comment by bconfortin** [comment]
I believe we'll only be able to update those before the release. See #7507
