### ISSUE TITLE
Technical Dept incurred in the course of building portfolio

### ISSUE THREAD

**Issue by stephensprinkle** [AugurProject/augur#747]
- [ ] Tests for my-reports  
- [ ] Inclusion of tests for portfolio actions
- [ ] inclusion of test for portfolio reducers
- [ ] Fix to broken tests on previous master merge
- [ ] Object format congruence of portfolio summary values 

== Feature Additions ==
- [ ]  All rows link to respective markets

**Comment by joeykrug** [comment]
What's status of this stephensprinkle?

**Comment by stephensprinkle** [comment]
I’ve got a story tracking this over in CH — https://app.clubhouse.io/augur/story/163/get-some-tech-debt-off-the-books

It’s reprioritized currently until the re-skin is finished up.

**Comment by joeykrug** [comment]
k closing and can maintain on CH
