### ISSUE TITLE
When filtering by all liquidity spreads, user should not see banner for potential invalid

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#7481]
This message isn't true -- in this case users just see markets with bad spreads, but the invalid filter would still hide markets that appear invalid via the invalid orders filter.

![image](https://user-images.githubusercontent.com/86010/80392066-81db6380-8863-11ea-9eff-06ff37d988be.png)

**Comment by pgebheim** [comment]
@andrewdamelio -- we need to confirm this (don't do until status is set to confirmed)

**Comment by andrewdamelio** [comment]
@pgebheim To clarify, for this ticket should we just remove this notice for liquidity spread OR update the text to something else?

@Chwy5 Was there a reason we created this notice/text initially?

**Comment by Chwy5** [comment]
Not that I recall.....I think we used it before we added the invalid spread filter

**Comment by pgebheim** [comment]
@andrewdamelio We should not show the banner in this case.
