### ISSUE TITLE
Invalid pass no matter what

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#750]
1) create an account
2) sign in
3) sign out
4) sign in, it'll stay on login screen, say invalid username/password, but actually log you in on the top right... confusing

![snip](https://cloud.githubusercontent.com/assets/5925937/17987123/1c154d06-6ad3-11e6-8880-d74ce3ffdbab.PNG)

**Comment by JohnDanz** [comment]
This will/should be fixed with the updated registration flow which i plan to have a PR for by today, just doing my final testing on all browsers etc.

**Comment by joeykrug** [comment]
doesnt happen anymore
