### ISSUE TITLE
Notes from meetup together

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#751]
List of the issues we ran into during the demos in SF last week:
- top 0.000 eth and Portfolio (0.000 eth) on top left confusing to me
- need to be able to adjust the charts, need to adjust dates and stuff, also need candlesticks
- creation date is in the past [jan 17, 1970] for some markets
- metadata for market below the description is a messy/ugly layout [needs to be cleaner]
- don't want the tx page to take me away when i trade, want to stay on the market but have a tx dropdown pane with info
- add ability to favorite markets on individual market pages
- confirmation screen for trades is needed so i don't screwup as a trader
- if no order on book default limit order shouldn't be 1
- upon a limit order entering 0 in the box doesn't actually zero it out [it'll trade for the last price when i hit submit]
- what is my profit at the last trade price?
- what is my profit potential at resolution min or max
- what is my current cost of open positions (need to know to understand what has to happen to make money or how much I'm willing to lose)

**Comment by tinybike** [comment]
These bullet points have either been moved to CH or resolved
