### ISSUE TITLE
Mobile: Changes to menu and top bar (see chwys comment at bottom about logged out state)

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7513]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/fc2b9ba2-6d00-421c-8582-ce530b2ef440)

**Top bar:** [Design](https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=15345%3A271577)

- remove logo
- Remove funds
- Add account dropdown
___

**Account dropdown should look like this when active:** [Design](https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=15345%3A279990)

___

**Menu** [Design](https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=15345%3A270241)

- Add funds to top
- Update add funds button design
- Will need to add logo but hold off until we update logos everywhere
- Same as above for the app switcher

**Comment by matt-bullock** [comment]
**Reduce the header bar to 48px height** [Design](https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=15345%3A271577)

Only for header bar,  not inside the hamburger menu as this still requires the height

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/1611bac2-ac2b-4764-882f-0cf2c56b4ac5)


**Logged out state** [Design](https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=11719%3A90)

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/3b7a4225-0625-402f-aacd-c04f18fd7adb)

**Comment by matt-bullock** [comment]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/0d72aba1-6ef1-4e2b-b5fe-f392eb8c8336)

[Design](https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=425%3A51)

Bell should sit no more than roughly 50% from the right of the screen. This means limiting the amount of characters displayed under account - whether this is the users email or wallet provider

**Comment by Chwy5** [comment]
Issue with the logged out state- for both mobile and destop....should look like this...
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=11719%3A90

currently looks like ![4-30log.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/bcfb2049-1d97-420b-9a8e-029aa63e363c)

**Comment by matt-bullock** [comment]
The spacing has also changed in the build. Can you follow the guides below for this spacing in the account component (in red)

![image](https://user-images.githubusercontent.com/39496225/80722890-2da0df80-8b00-11ea-8e87-534ecd5c6bda.png)

**Comment by Chwy5** [comment]
fixed closing
