### ISSUE TITLE
iOS/Safari OOM

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#7517]
Currently happens in iPad OS with 2018 iPad, as well as iPad mini running iOS 13.3.x

This occurs in browser mesh -- currently looks like its happen on `new Mesh`

![image](https://user-images.githubusercontent.com/86010/80529487-626c3580-894c-11ea-83c2-2a1c63d22cba.png)

**Comment by robert-e-davidson3** [comment]
I switched to using the SDK server. The OOM error did not occur but it still tried to use the 0x rpc instead of browser mesh when trading, despite it being disabled.

**Comment by robert-e-davidson3** [comment]
We aren't getting the event we need from the sdk server.
```
  // Delay loading of the browser mesh until we're finished syncing
  client.events.once(SubscriptionEventName.BulkSyncComplete, () => {
```
This never triggers.

**Comment by pgebheim** [comment]
Ah this actually makes sense since the SDK server would already be bulk sync complete at the time a client connects to it. This fact means that we need to abstract events a bit to make UI work with the sdk server.

Ostensibly we could make it be that the connector emits this on connection?

**Comment by robert-e-davidson3** [comment]
I'm not sure why we delay the loading of the browser mesh until syncing is done. Is it actually necessary? If it is, do we need to wait for the SDK server to finish syncing as well, or could we add a conditional to immediately load the browser mesh if sdk is enabled? I'm going to give that last one a try.

**Comment by robert-e-davidson3** [comment]
Doesn't help. I also tried `client.events.once(SubscriptionEventName.SDKReady, () => {`but no dice, even though the console shows an SDKReady event was fired... though it does so just before printing "Subscribing to Augur events".

**Comment by pgebheim** [comment]
Oh in the node where we talk to a remote SDK server we don't want to load mesh. In that node the SDK server is receiving orders from a mesh rpc server and forwarding them to clients.

My debugging suggestion should have been just removing all syncing completely and seeing if 0x will startup without that overhead.

Basically is the whole app eating too much memory or is it just some wasm limit.

**Comment by robert-e-davidson3** [comment]
I set it so when we create the (in-browser) sdk server, its `sync` function does nothing. Then I loaded then app and manually emitted the bulk sync event. This caused an apparent recursion failure:

<img width="2097" alt="Screenshot 2020-04-29 14 12 38" src="https://user-images.githubusercontent.com/45945043/80647610-9d8d6800-8a23-11ea-82fc-a728928a6aaa.png">

**Comment by pgebheim** [comment]
@robert-e-davidson3 -- ah that didn't CAUSE that issue, that's a safari bug and happens ~50% of the time on desktop (using non-developer preview version of safari).

See these lovely results:
https://duckduckgo.com/?q=safari+13+wasm&t=lm&ia=web

That error should have been caught and you should see a "Restarting Mesh" however. It is possible that the change to load the Wasm binary asynchronously broke that error handling though! Think you can try to narrow that down a bit? Wondering if that happens during the loadMesh call or the `new Mesh`

**Comment by robert-e-davidson3** [comment]
I wrote this then didn't press Comment so it's a little outdated now... but that explains why I can't repro it anymore.

ALSO the apparently recursion bug could be a 0x problem where they try to manipulate too much data at once: https://github.com/eligrey/Blob.js/issues/6

---

Using the UI dev setup pointed to kovan with default config, I no longer see Out Of Memory errors. The browser mesh still fails to load but instead I get `Error: timed out waiting for BrowserFS to load`.

After a while, safari asked me to increase the allocated size for the (local dev) augur website, up to 1.1GB. I said Allow. This didn't seem to have any effect on behavior however.

I retried v2.augur.net (the production build) and it works fine: I was able to make an order. Safari also asked me to increase v2.augur.net's allocated size to 1.1GB to I clicked Allow there too... but then it asked for 1.3GB. This kept rising indefinitely... I stopped at 2.9GB.

**Comment by pgebheim** [comment]
That error is actually from the wasm loader manipulating too much data -- not at the level 0x is writing.

Now the other thing:
Something is definitely wrong if data is growing like that...  What tables end up with that data?

**Comment by robert-e-davidson3** [comment]
I couldn't find the data in the tables. Augur was around 6MB. I didn't see any likely suspects in local storage either.

**Comment by robert-e-davidson3** [comment]
More contradictory data: In the iPad settings for Safari under Website Data, it shows augur.net at 80.3MB and my local dev address at 266MB. Nowhere near the current 10.6GB it's requesting.

I deleted those websites then looked at the storage in the safari dev console. It deleted the augur databases but not the 0x mesh databases. None of them are very large however.

**Comment by robert-e-davidson3** [comment]
When I disallowed a storage size increase, I got these errors:

<img width="2095" alt="Screen Shot 2020-05-01 at 13 19 54" src="https://user-images.githubusercontent.com/45945043/80838689-757e4000-8bae-11ea-9c0f-b31432105901.png">

iOS settings shows augur at <100MB

**Comment by robert-e-davidson3** [comment]
safari on ipad does not have `navigator.storage` so I can't use the convenient method for finding how much storage has actually been requested.

**Comment by robert-e-davidson3** [comment]
Latest observations:
1. After getting requests for storage increases every few seconds, one of those requests resulted in getting 3.2k OrderEvent logs in the console.
2. For the next few minutes there were no storage increase requests.
3. Then the app refreshed itself, breaking the iOS-MacOS devtools connection so I couldn't see why that happened.
4. Now the 0x mesh is undefined.
5. I refreshed the webpage and now the 0x mesh is defined but the console is full of an Out Of Memory error from the 0x mesh. Every minute(?) an error message is logged complaining that the Go program (0x mesh) already exited.

I sent the OOM log to Paul to pass along to the 0x people.

**Comment by robert-e-davidson3** [comment]
Chwy was able to repro the same symptoms but he doesn't have access to the dev console so it's not confirmed. However that still tells us that augur does not work consistently on iPads in general, not just my iPad.
