### ISSUE TITLE
Website: update bug bounty information on developers page

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7533]
Once I have the up to date info I can update the design and assign to a dev

Also need to update licenses in footer:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/c2e69932-cfa0-4dbc-9b6c-6ca4ffe9b20e)

**Comment by bconfortin** [comment]
@matt-bullock Do you have the updated info/design?

**Comment by matt-bullock** [comment]
@tomkysar Could you get us the updated info for this page
