### ISSUE TITLE
Comments: Remove placeholder text when comments input is active

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7537]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f6c8e639-666a-4d5a-9b66-abd8043b9866)

Should disappear once user clicks inside input

**Comment by bconfortin** [comment]
Are you sure? That is not the default behavior of placeholders. See the example bellow:
<https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_placeholder>

It goes away only after you type the first character.

**Comment by matt-bullock** [comment]
We can keep it. I guess I'm used to material design where the placeholder moves out the way once the field is active. I kept thinking the input wasn't active and tapping again
 
https://kstatic.googleusercontent.com/files/e1b29d8e4b672404d302169b82d43b55a9987c114cd8d47be9dff66fe6436f82a1c3b4a016d0a609e9b78c07fe24f841d5d599bfdc56897e30dfae7814b900fd

Can you do one thing that'll help: move the circular avatar to the left a little so it lines up with the curve of the input. That way it creates more space between the avatar and placeholder text (and I can better see the cursor flashing).

This is how it currently looks:

![image](https://user-images.githubusercontent.com/39496225/80694619-0aad0600-8ad5-11ea-9126-59a20efb56fa.png)

Should look like:

![image](https://user-images.githubusercontent.com/39496225/80694828-565faf80-8ad5-11ea-82dd-1f12e6247c44.png)


You have this all correct on desktop but looks off on mobile
