### ISSUE TITLE
Mobile: Add logout button to account dropdown, remove from slideout menu + add dark background between overlay and page

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7569]
[Design](https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=15402%3A1949)

Overlay background:

background: #0E0E0F;
opacity: 0.9;

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/4fe3ce63-cfce-4bc9-bc2f-1352b578832f)

**Comment by Chwy5** [comment]
Not seeing the background darkened out

**Comment by Chwy5** [comment]
fixed - closing
