### ISSUE TITLE
Replace placeholder copy in the dispute window component 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7575]
@petervecchiarelli Can you adapt some copy from the help centre for this. Shouldn't be more than 2/3 lines and may need a learn more link. 

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f2200182-4253-4b66-9aed-4d22c6d87fb8)

**Comment by petervecchiarelli** [comment]
"The dispute window is a week-long cycle. Reporting fees from settled shares are deposited into the next upcoming window.

At the end of the dispute window, those fees are allocated to REP holders who exchange their REP for participation tokens. When the disputing window ends, users can redeem their participation tokens for a proportional amount of the fees generated."

**Comment by Chwy5** [comment]
Lets not put this in the text holder spot (bc it is a little lengthy) - lets add it to the disputing guide on that pg

**Comment by Chwy5** [comment]
added - closing
