### ISSUE TITLE
Move help icon to bottom left of menu. This will now open the help items in a modal

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7578]
[Figma](https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=15345%3A270241
)

Modal:

[Figma](https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=15394%3A279637)

All I've done here is move the items into a modal. Not changed anything about the design to keep things simple for dev. If there is an issue let me know

**Reasons for dong this:**

Containing the account dropdown within the menu is causing scrolling issues (can't scroll to the bottom). This approach won't work when we introduce the app switcher

**Comment by phoebemirman** [comment]
where does the icon go here cause of the logout button?
<img width="412" alt="Screen Shot 2020-05-01 at 2 02 25 PM" src="https://user-images.githubusercontent.com/6775839/80841525-7619d500-8bb4-11ea-9dad-78a17d6a2244.png">

**Comment by bthaile** [comment]
Logout button has moved to bottom of account dropdown

![image](https://user-images.githubusercontent.com/3970376/80847511-95752a00-8bd5-11ea-990c-33d88a0bc34c.png)

looks like only a few mobile designs got updated in figma

**Comment by Chwy5** [comment]
Still not seeing this
