### ISSUE TITLE
Mobile: Stop the user being able to scroll the page beneath when an overlay is open

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7579]
For example scrolling the slide out menu results in the page beneath scrolling

**Comment by matt-bullock** [comment]
I'm not seeing this fixed anywhere

**Comment by bconfortin** [comment]
When the side menu is open, you can't scroll the page behind anymore. That also fixes the global chat that you could scroll the page behind as well.

Have you tried those?
Can you tell me where you are seeing this, other than the slide out menu?

**Comment by matt-bullock** [comment]
@bconfortin any modals but those are less of a concern. Is it easy to fix?

**Comment by matt-bullock** [comment]
There are still some spots this is happening but I'm closing as they're low priority
