### ISSUE TITLE
Remove 3box

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7591]
Global chat Fails to load when signing on with formatic just stays stuck in loading global chat

![5-1a.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/3e548b57-b675-4088-967d-927e42b84d44)

Also having issues signing on while logged into v2 with MM...I get the portis error

![5-1c.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/70883553-b221-4b53-9103-8c88638dea9a)

**Comment by pgebheim** [comment]
@bconfortin moving this particular bug out of V2 -- if we bring 3box comments back we'll need to evaluate.

**Comment by pgebheim** [comment]
also see #7500

**Comment by bconfortin** [comment]
Removed 3box from both UI's
