### ISSUE TITLE
Candlesticks timestamp

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#760]
Hovering on a candlestick doesn't show me the time that that candlestick is for, it should, see Poloniex as an example

**Comment by justinbarry** [comment]
@joeykrug Is this addressed sufficiently in the redesign?

![image](https://user-images.githubusercontent.com/328965/51640116-80f8ab00-1f17-11e9-90dc-edea2834ef3c.png)

**Comment by adrake33** [comment]
Closing since this is addressed in the redesign
