### ISSUE TITLE
Big delay between when market is created and sign to approve orders box appears

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7602]
About a 1 minute delay (no idea what is going on during this time)

![5-1create.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/63ac7d35-cfd4-49fe-80ce-9508dd6ca7e4)

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/2cb56c1c-4783-4c89-ba49-20856c74afb0)

**Comment by pgebheim** [comment]
@bthaile -- Could this be related to the fact that currently due to caching on Kovan the responses to txn are slower than necessary?

**Comment by nuevoalex** [comment]
I looked at this a bit. Took ~10-15 sec for me on Kovan. This is due to the delayed block updates form the provider. On mainnet this won't be such an issue since if the caching is the same cadence we'll get a new block about the same time as the tx confirmation.
