### ISSUE TITLE
Ipfs pinning augur

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#761]
The augur ui should by default pin itself on IPFS using IPFS js (client side js version of IPFS, which supports pinning files), this way the latest version always stays up on IPFS, whereas right now that's not necessarily the case

**Comment by justinbarry** [comment]
See: https://js.ipfs.io/

**Comment by pgebheim** [comment]
Think I figured it out:

Strategy 1: Load the dir from IPFS and re-add it to your js-ipfs -- https://gist.github.com/pgebheim/001b1e0fcd172989ff769397aa31786f

Strategy 2: Figure what what assets you wanna pin from the HTML that was loaded (e.g. enumerate script tags / any images that we know about...) and then pin them using
```
ipfs.addUrl('/the-asset')

Strategy 1 will give ALL assets for sure, but will require actually connecting to and resolving files using the ipfs dht. Strategy 2 will be easy to get HTML, Scripts, CSS -- but fonts images etc are hard to get because the URL refs dont exist in the html directly (just through CSS).

**Comment by pgebheim** [comment]
Attaching to #3525
