### ISSUE TITLE
Mobile: Background behind menu overlay should prevent user from tapping on elements behind overlay

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7617]
Some users are accustomed to closing mobile menus by clicking the area off to the right or sliding the menu back. On Augur clicking the area to the right to close it means you can click items underneath, so whenever I do this I find myself opening a market by mistake. The overlay background should disable this.

If this isn't an easy task we could make the menu full width. Whatever is easiest to fix the problem. Let me know

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/2e3e52a9-fc57-438e-8a42-cf9197b594a1)

**Comment by Chwy5** [comment]
still seeing this.....if it is easier...you can make the hamburger pullout pg go the width of the pg,

**Comment by matt-bullock** [comment]
Much better. Closing

**Comment by matt-bullock** [comment]
Reopening this because it's still an issue across the rest of the app. Only appears fixed when on the market list page

**Comment by Chwy5** [comment]
looks fixed everywhere-closing
