### ISSUE TITLE
Toast message is too big-bug

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7637]
See screenshot (not supposed to be this long

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/26a465af-a018-4666-908c-672a2bd65feb)

Don't let the toast be wider than regular alerts

**Comment by Chwy5** [comment]
not able to see any toast messages now when trading

**Comment by matt-bullock** [comment]
this looks fixed. closing
