### ISSUE TITLE
Support modern Web3 enabled browsers.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#7673]
https://github.com/AugurProject/augur/blob/272c11959b8f1094196b4f888565afaa4402025d/packages/augur-ui/src/modules/auth/actions/login-with-injected-web3.ts#L106-L107

`window.web3.currentProvider` is considered deprecated now and dapps should target `window.ethereum` instead as their connection to the browser's client.  Ethers fully supports `window.ethereum` I believe, so the fix here should just be as simple as:
```typescript
new Web3Provider(windowRef.ethereum)
```
There are a [handful of other places](https://github.com/AugurProject/augur/search?q=web3.currentProvider&unscoped_q=web3.currentProvider) where `window.web3` and `web3.currentProvider` are referenced but the fix should mostly be the same.  For the network version check, you should be using `eth_chainId` (https://eips.ethereum.org/EIPS/eip-695), or just ask `ethers` for it (Ethers supports 695).

It would not be unreasonable to fallback to `window.web3` in case you want to support legacy browsers, in which case the code would look something like:
```typescript
new Web3Provider('ethereum' in window ? window.ethereum : window.web3.currentProvider)
```
As long as you have an `isGlobalWeb3` check prior to that line, it should be safe as if `isGlobalWeb3` returns true, then you either have `window.ethereum` or you have `window.web3.currentProvider`.

**Comment by pgebheim** [comment]
Thanks micah!
@andrewdamelio -- adding to this milestone, lemme know if there's an issue that comes up that needs more time.

**Comment by MicahZoltu** [comment]
It appears that at least one spot was missed:
https://github.com/AugurProject/augur/blob/9bba43dc7931c5ccca2205d4867ed3ccf6e543ca/packages/augur-ui/src/modules/auth/actions/login-with-injected-web3.ts#L37-L39

This will throw if `windowRef.web3` is undefined.

**Comment by MicahZoltu** [comment]
https://github.com/AugurProject/augur/blob/9bba43dc7931c5ccca2205d4867ed3ccf6e543ca/packages/augur-ui/src/modules/auth/actions/login-with-injected-web3.ts#L104 will also throw if `window.web3` is undefined.

**Comment by andrewdamelio** [comment]
@MicahZoltu ah I thought i added a ```.?``` 
i did just didn't commit :( -- will fix today 

I'll tag you on the PR if you got a second later today to check
