### ISSUE TITLE
Trade history getting cut off at bottom for desktop

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7675]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/65dc7917-d08b-48a4-add1-6dbbad8be276)

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/7a6c80b6-3a18-4f66-8874-67d53128ad9d)

**Comment by Chwy5** [comment]
the trade history scrolls...there were trades under that

just tested

closing

**Comment by matt-bullock** [comment]
This has caused a new problem - it looks like it's getting cropped off at the bottom of the page. The bottom of trade history should line up with the bottom of order ticket and orders

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/234a5368-e7ea-402c-b6e3-e3c565cd4024)

**Comment by andrewdamelio** [comment]
@matt-bullock could you please provide browser type, market id and screen resolution for the above screenshot

**Comment by matt-bullock** [comment]
@andrewdamelio https://v2.augur.net/#!/market?id=0x057BDc6949450a897769F8c1597c84cf28Ff6CD1

Chrome on mac. 1034px browser height

**Comment by matt-bullock** [comment]
@andrewdamelio still looks off on chrome

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/9ec2a225-9311-407d-8933-449377fce2b8)

**Comment by matt-bullock** [comment]
Still seeing it

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/4d56b69c-41dc-4b51-849d-6058b544dc96)

**Comment by andrewdamelio** [comment]
@matt-bullock i made the global chat button have some opacity also as we discussed 
<img width="439" src="https://user-images.githubusercontent.com/1683736/84151342-38209400-aa31-11ea-8a96-8aec72696243.png">

**Comment by matt-bullock** [comment]
Looks much better. closing
