### ISSUE TITLE
Loading a market page directly takes minutes to load orders

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7681]
When I send a link on the market to someone and they go open that market, there are no orders right away), the market trading pg seems to freeze and unfreeze and it takes multiple minutes to have the orders load.  

No user will wait that long to see this, we need to make it faster

**Comment by pgebheim** [comment]
This is going to be impacted by a couple things.

1) The 0x mesh isn't started until hot loading is done -- perhaps some optimization can be done here
2) The current issues we are having with 0x mesh in general means that fetching orders is slow
3) When you are fetching thousands of orders just loading all the orders seems slow.

Of these (1) is the best bet of where to start first. Perhaps we can start the 0x browser mesh sooner?

For 2,3 0x is actively investigating.

**Comment by pgebheim** [comment]
We've now done 1 and 2. We're chatting to 0x about how more options to continue to speed this up.

**Comment by pgebheim** [comment]
Gonna make specific issues for this speedup
