### ISSUE TITLE
Update Ghost blogging platform styling and logo to fit new brand

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7684]
Will need to update just before launch. May need to get on a call to discuss any styling

**Comment by petervecchiarelli** [comment]
@matt-bullock Not going to be using Substack post-launch. Could use finalization of branding update for Ghost, the blogging platform, though.

**Comment by matt-bullock** [comment]
Ok, will update this ticket

**Comment by Chwy5** [comment]
What is the status on this?

**Comment by petervecchiarelli** [comment]
@bconfortin The problem with Ghost rn is formatting for things like page breaks and bullet points from Ghost CMS editor breaks on the page

<img width="884" alt="CleanShot 2020-06-23 at 10 08 56@2x" src="https://user-images.githubusercontent.com/40179975/86623274-2372e580-bf76-11ea-9efe-1c9c633c5f8c.png">

<img width="1030" alt="CleanShot 2020-06-23 at 10 06 54@2x" src="https://user-images.githubusercontent.com/40179975/86623280-25d53f80-bf76-11ea-9101-8a5e76fae506.png">

**Comment by matt-bullock** [comment]
Looks good. closing
