### ISSUE TITLE
Twitter post template

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7690]
Need a design for this.

Can live here https://www.figma.com/file/31ISKCwagskMIE8pHM1FNH/Social-Media-Icons?node-id=24%3A2098

**Comment by bthaile** [comment]
@matt-bullock  we need a design. the figma link is empty. moving this to New Issues

**Comment by matt-bullock** [comment]
This is a design only ticket - it won't need any dev work.
