### ISSUE TITLE
Augur Account Address should say User Account Address in the add funds modal

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7701]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/d63eb215-39cb-4a4a-9b39-b42131964129)

**Comment by Chwy5** [comment]
mine still says augur account address

**Comment by bthaile** [comment]
![image](https://user-images.githubusercontent.com/3970376/81576012-541b1200-936d-11ea-98fe-3d400c0e1d64.png)

**Comment by matt-bullock** [comment]
looks changed. closing
