### ISSUE TITLE
Credit card amount error bug

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7702]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/b2f009a8-c76b-435a-a2a1-3b1c548ed0cb)

**Comment by bthaile** [comment]
When user is logged in using Portis can they buy crypto with credit card?
The current code doesn't set a min / max value, reason for the above error
`Sorry, amount must be between $0 and $0`

**Comment by matt-bullock** [comment]
fixed. closing
