### ISSUE TITLE
Add activate account button to the end of market creation if user hasn't done this

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7705]
https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=4206%3A138199

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/70eda872-2fce-47e5-8699-be48abef238a)

**Comment by Chwy5** [comment]
added - closing
