### ISSUE TITLE
Firefox market display bug on mobile

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7707]
On Firefox on mobile go to a market that has many resolution details. Click on the arrow to expand the resolution details

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/bfd5ffd9-d200-4cb7-8f4e-af2cf4d9cba0)

**Comment by matt-bullock** [comment]
still looks broken to me

**Comment by Chwy5** [comment]
now fixed- closing

**Comment by bconfortin** [comment]
For some reason this was still broken on Firefox for iPhone but not Firefox for Android. Turns out it was just cached, even after I cleared it and reinstalled Firefox on the iPhone. Seems fixed now, will let you guys test.

**Comment by matt-bullock** [comment]
Unable to load markets @chwy can you test

**Comment by Chwy5** [comment]
i dont have an iphone works on the emulator
