### ISSUE TITLE
Improvements to onboarding flow

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7708]
**Changes to screens**

[Desktop Design](https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=195%3A2195)  | [Mobile Design](https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=474%3A8733)

[MOBILE PROTOTYPE](https://www.figma.com/proto/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=2256%3A0&viewport=1003%2C-1479%2C0.44618603587150574&scaling=scale-down)

[DESKTOP PROTOTYPE](https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=2281%3A2841)

- [x] 1. Create log in
_Account created should be changed to Log-in created_
_Add additional copy to this screen saying two more steps required_

- [x]  2. Add funds
 _Copy update_
_If user has dai in their wallet then we detect this and give them to the option to transfer their dai to their Augur account address. Clicking Transfer my dai button brings the user immediately to the transfer section of add funds modal_

- [x] 3. Activate Account
_3 different screens depending on the amount of dai user added to their account - see the figma flow_
_Add activate account button in this step of modal screen  - if the user has dai in their GSN account or ETH in their signing wallet_

- [x] If user skips account activation and arrives at the final screen, they will be able to navigate back (they may have just skipped through the steps. If user completes account activation, then the user can't go back (no reason for them to)

- [x]  **Visualise steps at the top of bottom of modal. Steps fill when user has done what's required in each step**

- [x]  **Make steps at bottom of modal navigable**
[Design](https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=2213%3A346)

- [ ]  On mobile we show left and right buttons

---

- [x]  **Add dai button**  [Desktop](https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=15485%3A35081)  |  [Mobile](https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=15485%3A35187)
Should appear in the top bar is user doesn't have dai in their gsn wallet or eth in their signing account.
Will launch to this part of the onboarding flow.

---

- [x] **Complete account activation button** [desktop](https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=15485%3A30551)  |  [Mobile](https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=15485%3A32967)
Should appear on the top bar if user has dai in their gsn wallet or eth in their signing account but hasn't activated their account'
Will launch to this part of the onboarding flow.

---

- [x] **Complete account activation button in other areas such as order ticket and market creation should launch this section of the onboarding**

**Comment by andrewdamelio** [comment]
@matt-bullock for the below item, can you link me to where they should show up in Figma? thanks!

> Complete account activation button in other areas such as order ticket and market creation should launch this section of the onboarding

@andrewdamelio The components have already been built. These activate account buttons in the order ticket and market creation should open the activate account part of the onboarding, exactly the same as what clicking the activate my account button in the top bar does

 ![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/a21e96e9-290e-490c-b608-de0f9d1ae0f2)
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/9cbd7d8c-ccfb-44bb-8156-39f077b4f9ee)

**Comment by matt-bullock** [comment]
~~- [ ] Make mentions of **ETH reserve** bold~~

---

- [x] Can these not shift around on hover - it's shifting the circles to the left and right

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/96fccae4-0eaa-4c7c-899f-b13858fa47e2)

---

- [x] Left align this text

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/fe87088a-f9f4-4004-91d7-cace178b6dbd)

---

- [x] Dropdown looks weird in the transfer my dai modal (not sure what's going on with the miniature looking menu. This should be disabled 

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/acdc3a91-e12c-4005-84cf-a7968ba6f328)

---

- [x] After transferring my dai to my trading account, the transfer my dai modal disappears and I'm taken out of the onboarding flow which doesn't feel good. I suggest adding the processing and confirmed buttons to the transfer my Dai modal and closing this takes the user to the next step in the onboarding flow:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/19b883ae-fa0a-4fe9-8595-51dd4e7cb11f)

---

- [x] After successfully activating the account it feels like something more should happen. Is it possible to add the confirmed button after processing. This sits for a couple of seconds before automatically moving onto the next screen. Also clicking it within those couple of seconds can move the user to the next screen

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e0e545d9-8cad-4e80-86d7-12021ae2b221)

**Comment by matt-bullock** [comment]
- [x] Can you add some horizontal padding to the mobile modal and the left and right buttons don't need to be so huge - see the figma design

 

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/b7dd5d0d-1cbe-4505-bd41-245377b9c40e)

**Comment by matt-bullock** [comment]
- [x] Will need to remove the bell on mobile until account activation is complete, otherwise the button looks off.

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/a266b47e-2517-45c2-bed3-ac240ee74322)


Design:
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/6f26144d-b590-43b6-9821-659ac5f99b60)
