### ISSUE TITLE
Can't enter trades for Scalar markets

### ISSUE THREAD

**Issue by nuliknol** [AugurProject/augur#7709]
I am testing the template market Unemployment Rate provided by default and the problem I have is that it doesn't accept my BUY/SELL quantities. Since the UI doesn't provide any error message I don't understand what is wrong. It doesn't matter what quantities do I put, the "PLACE SELL" (or BUY) button is in Gray color.
I already have made orders in the past on this market (Trade History on the right), so I am not getting why it suddenly stopped working.
Attaching screenshots.

Could you please provide the reason of why the "PLACE SELL ORDER" is gray, or enable the button, but show a message onClick explaining what is wrong?

(this is using today's sources)
![scalar_markets_bug1](https://user-images.githubusercontent.com/1125368/81424254-466e4e00-911b-11ea-8a0e-cb5ddbf96a36.png)
![scalar_markets_bug2](https://user-images.githubusercontent.com/1125368/81424278-4e2df280-911b-11ea-92c1-64d63550a6c0.png)

**Comment by nuliknol** [comment]
I am also seeing lots of these ... not sure if it is related
![console_log](https://user-images.githubusercontent.com/1125368/81424787-1a070180-911c-11ea-9a02-a1cd9340e5b3.png)

**Comment by pgebheim** [comment]
@nuliknol -- is this still happening? I'm able to enter these here. Feel free to re-open if you get it again.
