### ISSUE TITLE
Spike: Research whether to use webtorrent or IPFS

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#771]

**Comment by joeykrug** [comment]
IPFS-js is useful for 2 reasons, 1 it can be used to pin the UI itself in the browser from other instances of the UI that are running and 2 for the warp sync stuff, it uses a DHT to find peers and not tracker servers like webtorrent

**Comment by bthaile** [comment]
We are going to work with IPFS, I'm not a fan of bit-torrent now that Tron has a stake in it.

https://www.engadget.com/2018/07/25/blockchain-company-tron-buys-bittorrent/

**Comment by joeykrug** [comment]
https://github.com/ipfs/js-ipfs/pull/856#issuecomment-453783261 rock on, let's do it & use ipfs
