### ISSUE TITLE
Improve landing page ranking

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#772]
#### Landing Page Changes: 
- Change "Get Started" button text to something like "Bet on Prediction Markets"
- Add explainer video back to the site, it was engaging + helpful
- Pages need better titles / header info
- Make sure people understand wth augur is from reading the site
- Use keywords in headers and alt image tags
- augur.net reference error fetch is undefined, don't use fetch, replace it with something else
- js load speeds for main site
- Improve score on [Google Pagespeeds](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Ftry.augur.net%2F) --->  [example list of things](https://gist.github.com/tomkysar/4beb750c84f8dc91ae8f615fddae4ec2) 

#### New Content:
- Create a "Prediction Markets Explainer" Medium post and add that content to landing page
- [The old site](https://web.archive.org/web/20160310113115/http://www.augur.net:80/) did do some of these things, for a reference + to get ideas + content. It mentioned the words prediction market a lot more.  Had way more links, images, interactive content, etc. CTAs were good too.
- Review landing page content + add way more content (target 2500 words, currently at 500 but sites with ~2500 are the average for #1 rank on Google)
- Get some blog posts out explaining things like prediction markets and for other keywords and get them highly ranked
- Regularly publish blog posts like 2-4 a month, both about informational stuff  *and* about engineering stuff
- Make landing page have link to UI + download side by side instead of get started, take the dev site info from existing get started page and put it at the bottom of current main page, take the rest of any useful content from get started page and put on main page

#### Metrics / SEO: 
- Get referral + social bounce rate down from 100% to sub 50%
- Get in top 5 rankings for a bunch of the keywords that are useful
- Research other things competitive to augur + what keywords they rank for (PMs, betting sites, etc.) and improve seo for those keywords

#### Augur UI Changes: 
- On the UI the market pages have titles cut off, Primary Keyword - Secondary Keyword | Brand is optimal title no more than 60 chars
- Markets should have meta keywords, same for category pages
- description for everything is the same, needs to be different / < 300 chars, each market = own description
- keywords for stuff should appear in headers and title tags, e.g. category/page/keywords
- No h2’s, we should use / add em
- h1s for market pages
- Google isn’t indexing in reporting or resolved markets on the markets page itself due to each url not being a link (ie the dropdown buttons to select reporting or resolved markets on the markets page don’t change url at the top / aren’t links)
- have a query param ?disclaimer=open when it’s opened and ?disclaimer=accepted when someone goes through it to detect fall off due to confusion of the explainer
-  if there’s a dumb stupid simple way to get the UI to add a query param when a user presses every button (and then on next button press the param changes and so on) and for entering data into an input box and uses the element's classname as the default we should do it. https://itnext.io/writing-customizable-styled-react-components-51d38ed20461
- category pages don’t update site title w/ category, they should
- Need sitemaps
- js load speeds for ui
- ui Does the homepage have at least one paragraph? if not add something
- site:search for ui to test indexing
- Is there a way to just have the UI check a reference somewhere of what the latest UI version is (maintained in an Augur repo e.g. github) and then load it automatically (but support passing params to use a different ipfs ui hash) while still supporting url params for nodes and links for the react stuff once it loads the actual UI by passing it all through
 - Need canonical tags on ui that are injected using helmet js for each page including the first word after the #! + market id if there is one but no other parameters
- Need a way to not pass node urls as params, bundle them w/ UI, and have optional params for nodes

**Comment by ghost** [comment]
Split out into #901, #902, #903.
