### ISSUE TITLE
On Registration using Firefox - error "invalid key length 32"

### ISSUE THREAD

**Issue by unimercio** [AugurProject/augur#772]
While trying to register on the app https://app.augur.net/markets
Using Firefox on Mac,  I get this error:

![screen shot 2016-09-13 at 11 06 48 am](https://cloud.githubusercontent.com/assets/362412/18479379/bd396e00-79a2-11e6-9ae3-c4a642bf3f16.png)

**Comment by unimercio** [comment]
Works fine on Chrome

**Comment by joeykrug** [comment]
Doesn't occur in new UI at https://augur-dev.firebaseapp.com/
