### ISSUE TITLE
Unrealized P/L not set when market is AwaitingFinalization

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#7722]
When calculating a user's profit & loss during a successfully reported-on but NOT finalized market, we want to add their upcoming `realizedPL` to their current `unrealizedPL`. This way a user can see how much they will gain or lose as soon as someone finalizes the market.

Currently there is no special rule for markets awaiting finalization.

ALSO: It may be desirable to do this for markets in `CrowdsourcingDispute`, since that state is entered immediately after the initial report is submitted.

**Comment by bthaile** [comment]
I’ll check if something got broken, but last price traded is Suppose to be set artificially when market is in awaiting finalization. 

Yes no and categorical markets outcomes get set to max or min depending on the winning outcome. Scalar price is set based on winning outcome. As if the market has actually finalized. The difference is awaiting finalization gives unrealized PL and finalized gives realized PL from the getProfitLoss getter. 

I tested in the UI and getProfitLoss getter is working. When user has a position in market awaiting finalization they see unrealized PL based on tentative winning outcome.
