### ISSUE TITLE
Future Template Ideas

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7726]
** MMA (this is the sport to list)
    UFC (is the organization like Basketball and NBA/WNBA/NCAA)- Organization should be shown before each market question
    Bellator

Multiple Choice Markets
#1)
[Fighter A] vs [Fighter B] `(Moneyline)`: Who will win?
Estimated Event Start time

Outcome 1) Fighter A
Outcome 2) Fighter B
Outcome 3) Draw

#2)
[Fighter A] vs [Fighter B] O/U: [#}.5 Rounds
Estimated Event Start time

Outcome 1) Over #.5 Rounds
Outcome 2) Under #.5 Rounds

#3)
[Fighter A] vs [Fighter B]: Method of victory?
Estimated Event Start time

Outcome 1) [Fighter A] by KO/TKO
Outcome 2) [Fighter A] by Submission
Outcome 3) [Fighter A] by Points
Outcome 4) [Fighter B] by KO/TKO
Outcome 5) [Fighter B] by Submission
Outcome 6) [Fighter B] by Points
Outcome 7) Draw

#4) 
[Fighter A] vs [Fighter B]: How will the fight end?
Estimated Event Start time

Outcome 1) KO/TKO
Outcome 2) Submission
Outcome 3) Points

#5)
[Fighter A] vs [Fighter B]: What round will the fight end?
Estimated Event Start time

Outcome 1)  Round 1
Outcome 2)  Round 2
Outcome 3)  Round 3

**Boxing

Multiple Choice Markets
#1)
[Fighter A] vs [Fighter B] `(Moneyline)`: Who will win?
Estimated Event Start time

Outcome 1) Fighter A
Outcome 2) Fighter B
Outcome 3) Draw

#2)
[Fighter A] vs [Fighter B] O/U: [#}.5 Rounds
Estimated Event Start time

Outcome 1) Over #.5 Rounds
Outcome 2) Under #.5 Rounds

#3) 
[Fighter A] vs [Fighter B]: Method of victory?
Estimated Event Start time

Outcome 1) [Fighter A] by KO
Outcome 2) [Fighter A] by TKO
Outcome 3) [Fighter A] by Points
Outcome 4) [Fighter B] by KO
Outcome 5) [Fighter B] by TKO
Outcome 6) [Fighter B] by Points
Outcome 7) Draw

#4) 
[Fighter A] vs [Fighter B]: How will the fight end?
Estimated Event Start time

Outcome 1) KO
Outcome 2) TKO
Outcome 3) Points
Outcome 4) Draw

#5)
[Fighter A] vs [Fighter B]: What round will the fight end?
Estimated Event Start time

Outcome 1)  Rounds 1 -3
Outcome 2)  Rounds 4-6
Outcome 3)  Rounds 7-9 
Outcome 4) Rounds 10-12
Outcome 5) Goes the Distance

**Car Racing
NASCAR (LIke NBA/WNBA/NCAA)
Formula 1

Multiple Choice

#1)
(NASCAR or Formula 1) {Event Name}; [Racer A] vs. [Racer B]: Who will finish better?
Estimated Event Start time (need to have event expiration based off of event start time)

Outcome 1) Racer A
Outcome 2) Racer B
Outcome 3) Event Cancelled

#2)
NASCAR - [Event Name} Winner
Estimated Event Start time

Outcome should include Racers Names
Must include: Other (Field)
Must Include: Postponed/Event Cancelled

#3)
[Year} NASCAR CUP Series Championship Winner

Must include:  Other (Field)

**Comment by bthaile** [comment]
```
[Fighter A] vs [Fighter B]: What round will the fight end?
Estimated Event Start time

Outcome 1) Round 1
Outcome 2) Round 2
Outcome 3) Round 3
```
issue is main card events will have 5 rounds. pre-lims will have 3 rounds.
what to do?
