### ISSUE TITLE
Open Order Preset Cancellation limit

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7727]
When a user creates an open order default expiration should be preset to when the Event Resolution for that market begins

If a market has reached the In Reporting State any New orders placed should have a preset order cancellation limit at 1 week

Market creation and order form
 - add advanced to pre-liquidity
 - default order expiration to market event expiation 
 - use local time with local timezone (EDT), ...

**Comment by Chwy5** [comment]
everything working correctly, but still not seeing local time zone in order seeing utc version instead

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/3c82f3ff-bbff-436a-aa7b-47c3d2b3df36)

**Comment by bthaile** [comment]
I forgot to use the timezone abbr instead of utc format. Push this ticket back to ui dev incoming and I’ll make that change

**Comment by Chwy5** [comment]
Seeing some funkiness with this....

If I fill in the order ticket and add an open order to the orderbook and then do nothing for a while.  IF i come back later and enter the order book again (it still shows the time under order expiration, when I did my first trade

If I clear it out and reenter the order ticket it didnt show me any date...I could still hit the place buy order button and my order went through with the correct expiration time

**Comment by bthaile** [comment]
If the market is still open then the expiration will stay the same as market event expiration. 

if market is in-reporting the order form will show order exp of 1 week. If you leave and come back the time will update to be 1 week in future.

**Comment by Chwy5** [comment]
In market creation...the pre-liq order doesnt match the event expiration time

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/bf8a12b2-8297-43f5-aabe-4dba7f7fe38f)

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/93ee4590-e1e1-4aba-8b1a-85ba533160af)

**Comment by Chwy5** [comment]
Still off....

If I create a market for later today(for expiration) the pre-liq order shows 7 days.

I also tried 3 days in the future and the time is off (see screenshots

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/1c9d65e1-b471-4484-bf5b-ab4b9baf2a68)

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/7e07a17d-4c2b-4bff-aade-f1d16924aec4)

**Comment by Chwy5** [comment]
fixed -closing
