### ISSUE TITLE
Multiple transaction notification issue

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7738]
If I click on an existing order on the orderbook or outcome table For example if there is a .20 bid for 90 shares and that filters into the order ticket for me to sell, I get a message this will take 9 txs.  It does this for any quantity...it currently is displaying 1 tx per quantity of 10

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/5622290f-b66a-4e78-aee8-cdd04bb3a237)

**Comment by andrewdamelio** [comment]
@bthaile any idea whats going on here?

**Comment by bthaile** [comment]
I fixed this. issue was numFills was used instead of numFills / max orders per trade. moving to product review

**Comment by Chwy5** [comment]
fixed - closing
