### ISSUE TITLE
Eth Reserve Top off messaging - See designs in comment

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7745]
1. Add the dai equivalent of eth reserve balance to the current tooltip....like "Your total funds does not include the Eth reserve balance of $7.94"

2. Inform the user when their ETH reserves get topped-off.
 - [x] bell alert
 - [x] order form ETH reserve top-off

3. Edit copy in ETH reserve tooltip in account
 - [x] tooltip
> Augur runs on a peer-to-peer network which requires transaction fees that are paid in ETH. These fees go entirely to the network and Augur doesn’t collect any of these fees.
> 
> If your account balance exceeds $40, a portion of this equivilant to 0.04ETH will be held in your ETH reserve to cover transaction fees resulting in cheaper transaction fees.
> 
> So long as your available account balance remains over $40 Dai, your ETH reserve will replenish automatically.
> 
> Your ETH reserve can be easily cashed out at anytime using the withdraw button in the transactions section of your account summary.

4. - [x] Total Funds tooltip

**Comment by matt-bullock** [comment]
[Design for order form message](https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=2221%3A847)

![image](https://user-images.githubusercontent.com/39496225/81833739-600afd80-9540-11ea-88d2-a483e2edccfe.png)


[Bell & Toast message](https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=2223%3A44)

![image](https://user-images.githubusercontent.com/39496225/81833911-96e11380-9540-11ea-8445-87705ee19942.png)

**Comment by Chwy5** [comment]
In the 3rd paragraph of the tooltip "As long as your available account balance remains over $40 Dai, your ETH reserve will automatically be replenish."

need to add an "ed" onto the end of replenish....should be replenished

**Comment by matt-bullock** [comment]
Checked. Closing
