### ISSUE TITLE
Create minimal reporo case for safari bugzilla re: universe count issue

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#7750]
Currently, some safari clients (latest ios version) are getting incorrect count results for the count of universe documents by key.

Discussion on discord.

Try and create a minimal repro case using only IDB primitives so this can be filed as a bug report.

**Comment by robert-e-davidson3** [comment]
This code reproduces the bug on @bconfortin's machine but not mine:
```
let db = await AugurSDK.connector._api.db;
await db.UniverseCreated.where({childUniverse: state.universe.id}).count()
```
(run each line separately in the browser console)

This code is intended to reproduce dexie's behavior using only indexeddb directly but fails to reproduce the bug on bruno's machine:
```
<html>
<script>

  (function() {
    'use strict';

    var storeName = "bar";

    var db = new Promise(function(resolve) {
      var request = window.indexedDB.open("foo");
      request.onsuccess = function (event) {
        resolve(event.target.result);
      };
      request.onupgradeneeded = function(event) {
        var db = event.target.result;
        db.createObjectStore(storeName, { keyPath: "id" });
      }
    });

    db.then(function(db) {
      return new Promise(function(resolve) {
        var tx = db.transaction([storeName], "readwrite")
        .objectStore(storeName)
        .add({ "id": "baz" })

        tx.onsuccess = function() {
          console.log("tx succeeded")
          resolve(db);
        };
        tx.onerror = function() {
          console.error("tx failed")
          resolve(db); // TODO happens when re-running script
        }
      });
    }).then(function(db) {
      var tx = db.transaction([storeName], "readonly")
        .objectStore(storeName)
        .count();

      console.log(tx)

      tx.onsuccess = function (event) {
        console.log(event);
        console.log(`Count: ${event.target.result}`)
      };
    });

  }());

</script>
<body>
</body>
</html>
```

**Comment by bconfortin** [comment]
There is just one database in Robert's test, not four.

Robert's Test using Safari
![Captura de Tela 2020-05-14 às 21 59 12](https://user-images.githubusercontent.com/10351013/82000382-8e670680-962e-11ea-8205-d6f930a5ec7e.png)

V2 using Safari
![Captura de Tela 2020-05-14 às 21 59 32](https://user-images.githubusercontent.com/10351013/82000383-8f983380-962e-11ea-8db2-71940b2653d0.png)

**Comment by robert-e-davidson3** [comment]
I only ever see a count of 1 but I still see the duplicate databases. This suggests they're unrelated issues.

**Comment by robert-e-davidson3** [comment]
dupe issue is seen elsewhere too: https://github.com/jakearchibald/idb/issues/72

**Comment by pgebheim** [comment]
We were unable to create a repro case of this issue....
