### ISSUE TITLE
Firefox mobile: search loading is visually broken

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7766]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/66f6a24b-5d18-49a2-988d-7a031cb924b4)

It don't know why it shows a loading icon in the search when the markets are initially loading, as you're not performing a search, but that's another story. Markets aren't loading on mobile so I can't test how this looks when performing a search but if I try to tap inside the input when markets are loading, this happens

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/385af466-4313-4e98-8e34-3302eaf73f6e)

So need to check this isn't happening when markets have loaded and user tries to perform a search

**Comment by bconfortin** [comment]
@matt-bullock Were you testing this on your phone or the emulator?
On the phone it's working as intended for me, both Android and iOS. The emulator, however, I'm seeing what you're seeing.

**Comment by matt-bullock** [comment]
@bconfortin screenshots above are from my android phone - in firefox

**Comment by bconfortin** [comment]
@matt-bullock We currently don't have an easy way to identify if a market is loading because of the search input, a filter that was applied or a category that was selected. It's just something like "markets are loading, show the loading icons".

**Comment by matt-bullock** [comment]
loading issue fixed. Still seeing the select issue but can't tell if this is still a problem when loaded because markets won't load on my device. I'll close the issue and check again when FF mobile is working
