### ISSUE TITLE
Firefox mobile: opening a market is scrolling immediately to the order ticket

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7767]
Shouldn't do this.

I'm having to test using the dev console as markets won't load on my device but I imagine if it's an issue here it's probably going to be the same on mobile

This is where it auto scrolls to when entering a market:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f0bd35f2-7083-4cf2-91d6-d60168e2ab5a)

**Comment by Chwy5** [comment]
fixed-closing
