### ISSUE TITLE
Realized Loss for positions worth 0

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#777]
After the market resolves, ui needs to solve if a user has a losing position or position worth 0.  Currently a user with a losing position has no need to finalize a market b/c all it does it charge them eth to do so.

**Comment by adrake33** [comment]
@joeykrug To clarify this ticket, it sounds like we need think of a way to show a user's position under their closed history in the event that their position is less than or equal to 0, since they won't finalize the market due to it being a waste of ETH.  Is that correct?

**Comment by joeykrug** [comment]
They won't claim their shares if they're worth 0, not that they won't finalize the market. So, if shares are worth 0 we should just mark them as realized at 0 imo

**Comment by adrake33** [comment]
@pgebheim Can you confirm if this is fixed by your PR for P/L?  Alex said it should be.

**Comment by pgebheim** [comment]
Oh I missed this -- will need to check if this happens.

**Comment by pgebheim** [comment]
Yes! The value goes to zero in `outcome_value_timeseries` so the unrealized heads to zero and nothing is put into realized.

**Comment by pgebheim** [comment]
Closing
