### ISSUE TITLE
UI locks up Firefox Android.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#779]
Loading the following page on Android Firefox completely locks up the browser, it eventually tells me the page has stopped responding: https://ipfs.augur.casino/ipfs/QmYznPLieFvWGNDrS839mQrGLuuWNxhSrg29TrXgog52ed/?ethereum_node_http=https%3a%2f%2feth-mainnet.alchemyapi.io%2fjsonrpc%2f7sE1TzCIRIQA3NJPD5wg7YRiVjhxuWAE&augur_node=wss%3a%2f%2faugur-node.augur.casino#/reporting-dispute-markets

Note: this issue may be transient since there are a large number of markets in reporting this week.  Recommend trying to repro now.

Firefox desktop is also a bit sluggish, though not nearly as bad as mobile.

**Comment by bthaile** [comment]
I've noticed that reporting dispute markets does locks up, we do need to figure out what is causing the freeze. To repro you can use Chrome on mainnet and just go to reporting then go to dispute, you will see a 10-15 second freeze. I assume its worst in Firefox on Android.

**Comment by adrake33** [comment]
Since we're on a tight schedule for getting the trading page redesign done, let's stick to just investigating this issue to see what's causing it (since this is an ideal time to do so), and we can work on a fix for this after the redesign is launched.

**Comment by SebastianMetzger** [comment]
I have the same issue under Windows 10, Chome 71.0.3578.98 (Official Build) (64-bit) and Metamask as a wallet (If that matters)

**Comment by bthaile** [comment]
Issue is 
https://github.com/AugurProject/augur-ui/blob/daa620dab83caba7b635aa411e0ac7515440e12f/src/modules/reports/actions/load-disputing.js#L28

and line 44,

We get the market information from augur-node which takes time. 

Also, we want the dispute information so we can sort by dispute round and amount staked. The container runs `src/modules/reports/selectors/select-dispute-markets.js` to sort the markets.

We need to not load market information but need to only add the marketId and it's reportingState and pass them to the component to get the market information and sort. By doing this we'll only grab the information for the visible markets (up to 20, in dispute and coming up dispute). We've done an effort like this before, seems we got away from understanding that users will directly navigate to the dispute page.

This will take a bit of effort. I think it's definitely needed to be done soon.
