### ISSUE TITLE
On Page Load using Firefox - Non Responsive Script

### ISSUE THREAD

**Issue by unimercio** [AugurProject/augur#779]
![screen shot 2016-09-21 at 5 18 07 pm](https://cloud.githubusercontent.com/assets/362412/18729738/f39d068a-8020-11e6-93db-239f2a6d72aa.png)

![screen shot 2016-09-21 at 5 19 06 pm](https://cloud.githubusercontent.com/assets/362412/18729782/23a16b0a-8021-11e6-9a18-dd612102b595.png)

**Comment by unimercio** [comment]
Works fine on Chrome

**Comment by joeykrug** [comment]
Also doesn't occur in new ui at https://augur-dev.firebaseapp.com/
