### ISSUE TITLE
Ballots count doesn't match decisions to be made

### ISSUE THREAD

**Issue by atroche** [AugurProject/augur#78]
![augur](https://cloud.githubusercontent.com/assets/29839/8227677/9a579738-15ec-11e5-8b04-14425f1cbf2c.jpg)

When I first load the page, ballots has the number 0 next to it. But after a little while, it updates to 8. But when I click on it, there don't appear to be any ballots. I'm on 37b0d45e993e8c1afc7d7d04161d9e2a4526c7fc.

**Comment by niran** [comment]
Good catch. This is a side effect of a change I made to hide the ballot when the contracts would reject its submission. We probably need to hide the badge in this scenario as well. Thanks for the report!

**Comment by tinybike** [comment]
I think this had the same bug that was causing AugurProject/augur.js#40, and I haven't observed this bug since it was fixed.  Closing for now.
