### ISSUE TITLE
outstanding returns needs to be reorganized so it is separated by outcome

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#780]
there is a new feature for the trading page where users are show which positions have claimable proceeds: 

<img width="514" alt="screen shot 2019-01-03 at 10 42 50 am" src="https://user-images.githubusercontent.com/6775839/50655234-58971580-0f44-11e9-9c99-b5e49fd7cafe.png">

claimable proceeds needs to be returned from getWinningBalance organized by outcome and claimTradingProceeds needs to be position specific, and also keep the previous functionality of claiming all proceeds.

**Comment by bthaile** [comment]
claimTradingProceeds takes market and share holder, all the winning shares will be traded in. There is no reason to have a claim proceeds per position, only one for the whole market. 

I think we need to re-think this design.

**Comment by joeykrug** [comment]
> There is no reason to have a claim proceeds per position, only one for the whole market.

Correct

**Comment by adrake33** [comment]
@bthaile Can you please coordinate with @epheph and @phoebemirman and update this ticket with the new design once you've discussed this more?

**Comment by sharkcrayon-augur** [comment]
I agree with Tom. We were originally thinking that only one position would be a winning position, but after talking with Phoebe it seems this is not correct in some places.

@matt-bullock We should consider dropping that "claim proceeds" button on the position row and perhaps move it to where the other market action buttons (Report/Finalize/etc) go.

**Comment by matt-bullock** [comment]
![image](https://user-images.githubusercontent.com/39496225/50701468-35588d00-104e-11e9-9ea8-2f7508833c62.png)
I've removed that column as it's not needed in positions

Moved the claim proceeds button to the market header:
![image](https://user-images.githubusercontent.com/39496225/50701530-6933b280-104e-11e9-8e8a-212f32b782e1.png)

**Comment by sharkcrayon-augur** [comment]
👍 Perfect!

**Comment by bthaile** [comment]
Just a thought. User will have to click on the claim proceeds button in order to go to the confirmation modal. 

There they will determine if its worth it to claim or if they want to wait for lower gas prices. 

Do we want to put how much ETH they will be claiming? Or is the button good enough and the user can go to positions page to get the amount of ETH to be claimed?

**Comment by sharkcrayon-augur** [comment]
@bthaile What is the confirmation modal? Is it something we show, or is like a MM popup? If it's the first, we can show that info there, but if it's the second we'll need to think about how to address this (since people using hardware wallets and Edge won't get a similar popup).

**Comment by bthaile** [comment]
This confirmation modal. 

![screen shot 2019-01-05 at 12 48 57 pm](https://user-images.githubusercontent.com/3970376/50727949-5372cb80-10e8-11e9-9437-013478f60a29.png)

**Comment by bthaile** [comment]
added this feature to feature branch to market trading page.
