### ISSUE TITLE
Claim proceeds modal est fee doesnt match 

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7808]
The individual Est tx fees dont match up with the claim all est tx fee....shows cheaper to do indivually (dont think this is correct), should be cheaper to do all i would think.

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/302f0dc4-2261-4d75-b74b-154dd418e911)

**Comment by bthaile** [comment]
Need to do gas estimations for individual claim proceeds, can't relay on hardcoded values they won't cover all the fee cases.

**Comment by Chwy5** [comment]
looks better - closing
