### ISSUE TITLE
warp sync files need consistent hash across all operating systems

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#781]
we need to figure out how to consistently hash augur db so that hashes match every X blocks on win, mac and linux. This will give greater confidence in the community for importing warp sync files.

one suggestion: sqlite utility for db hash
https://www.sqlite.org/src/artifact?ci=trunk&filename=tool/dbhash.c

**Comment by brianosaurus** [comment]
I'm thinking a KMAC signature for message integrity and we'll have to trust the IPFS hash for retrieval.

**Comment by pgebheim** [comment]
Nice to have, not for v2.
