### ISSUE TITLE
Add new sub categories to sports in market creation

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7811]
Boxing, Car Racing and MMA

Icons can be found here:

https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=4216%3A64

**Comment by bthaile** [comment]
@Chwy5 Do we have templates for these new categories. We need to add templates before we can do the Viz stuff.

**Comment by Chwy5** [comment]
Yes Ticket #7726 (they still need reporting rules), but everything else is there

**Comment by Chwy5** [comment]
added
