### ISSUE TITLE
Add toggle between shares and eth for Volume

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#782]
On redesign candlestick charts at the top of the pg...user should be able to toggle between shares/eth to see volume calculation.

Please see candlestick screenshot attached
![shares-eth-volume](https://user-images.githubusercontent.com/41301809/50660054-78423400-0f6c-11e9-8316-0f0c45df9615.jpg)

**Comment by adrake33** [comment]
The design for this has not been created/signed off on. Once it has, this can be implemented.

**Comment by matt-bullock** [comment]
There's an updated design in the figma file (charts and graphs artboard on desktop page) demonstrating how to switch between eth and shares when showing the volume. The hover colour for volume bar is linked to the colour of the volume total to help users see the connection. once Chwy has reviewed it we can get sign off.

**Comment by Chwy5** [comment]
Reviewed and it looks good.

**Comment by justinbarry** [comment]
It would appear we do not have the volume in eth readily available. Will need to add that to augur-node.

**Comment by Chwy5** [comment]
The 24hr volume and total Volume on the top of the trading pg is shown in Eth? Where does that come from? Or that needs to be added to AN also?
![1-4voleth](https://user-images.githubusercontent.com/41301809/50702601-62da1200-101f-11e9-8711-ae1392789fdf.jpg)

**Comment by adrake33** [comment]
@Chwy5 Isn't that total volume over all time? The dates in the chart can be changed, so I think we'll need the volume for whatever range is chosen?

**Comment by Chwy5** [comment]
Yeah total is all time, 24 hr is 24hr range......yeah would need it for range being selected

**Comment by adrake33** [comment]
Let's hold off on this until after all the other tasks that are required for the redesign launch are completed. If we have time before Jan 17th (when we want to be code complete), we can work on it. Otherwise, we should postpone this until after the launch.

**Comment by justinbarry** [comment]
Volume in eth added to augur-node here: https://github.com/AugurProject/augur-node/pull/801

**Comment by pgebheim** [comment]
@bthaile -- this one goes to you too with the new chart impl?

**Comment by bthaile** [comment]
Yes, it need to be added to the chart

**Comment by ryanberckmans** [comment]
Tom is implementing this as part of our transition from D3 to highcharts.

**Comment by pgebheim** [comment]
Is this also fully complete?

**Comment by bthaile** [comment]
Yes, complete
