### ISSUE TITLE
Estimated TX Fee - Eth Reserve

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7821]
We need to show when the Est tx fee is being paid by the eth reserve

We will show dai value of it

2 cases:

1) User doesnt have eth reserve and is under the $40 cutoff we just say:
 est tx fee........$xyz

2) User has eth reserve, we say
est tx fee (paid by ETH reserve).......$xyz

**Comment by matt-bullock** [comment]
Checked. closing
