### ISSUE TITLE
Ease automation of IPFS pinning for community

### ISSUE THREAD

**Issue by LukeWheeldon** [AugurProject/augur#7827]
**Is your feature request related to a problem? Please describe.**
It would be beneficial if Augur users having both an IPFS node and extra bandwidth (hosted nodes), would not only pin the current version but also make sure it is kept up to date as new ones are released.

**Describe the solution you'd like**
Store current IPFS hash in a JSON file accessible on augur.net

**Describe alternatives you've considered**
Alternatively, the HTML of augur.net/ipfs-redirect could be parsed but this is would probably be more prone to eventually breaking as the page gets updated.

**Additional context**
This is inspired by a tweet [1] detailing a simple method to make sure one's node is always pinning the most recent version (helped by a cron job), such as:
curl -s https://polkadot.js.org/apps/ipfs/pin.json | jq -jr .IpfsHash | xargs -0 -I CID ipfs pin add --progress CID

[1] https://twitter.com/chevdor/status/1263117917706760194

**Comment by pgebheim** [comment]
Hey Luke!

In v2 the UI will auto-pin itself to IPFS in the browser, and new releases will have the IPFS hash posted to the Github Release to ease finding it for people wanting to load the UI or to pin the hashes.

Example, here is a pre-release tag for Augur2 from a long time ago:
![image](https://user-images.githubusercontent.com/86010/82492626-5b43cd80-9a9b-11ea-9236-5917034c880c.png)

The highlighted file is the IPFS hash, it is easily discoverable using the public github API by listing all files in the release and finding the one with the `.ipfs` suffix.

Using this knowledge you can accomplish the above with the following snippet in a unix shell with access to `curl`, `jq`, and `ipfs`

```
curl https://api.github.com/repos/AugurProject/augur/releases | jq '.[0].assets[] | select(.name|test(".*ipfs$")) | .name | sub(".ipfs";"")' | xargs -0 -I CID ipfs pin add --progress CID
```
