### ISSUE TITLE
Add colour to transaction fee shown in order ticket +underline for tooltip + unprofitable trade message

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7839]
Yellow (#F1E700) by default to draw attention to the tx fee because it's not included in the profit and loss. 

This becomes red (#F12B00) when the tx fee is more than the profit + add unprofitable trade message

https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=4213%3A10373

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/1dd07a56-c079-42c2-8a69-97391fcb59de)

Display tooltip when user hovers over number. May need to increase the hit area on mobile

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/a1e6fb12-c6b3-49ee-b37f-5c6f748f71ef)

**Comment by Chwy5** [comment]
added - closing
