### ISSUE TITLE
Firefox mobile: header and close button not showing on categories and filters menu

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7840]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/9481ddd8-d59c-4456-ad18-d2ed08d2e262)

Should see this

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/6d4e2626-7e06-41ab-ae40-69165b674e0b)

**Comment by bconfortin** [comment]
@matt-bullock Not able to reproduce. Used chrome and firefox in both Android and iOS. Also tried a small screen on chrome and firefox in my Macbook.

Can you please test that again?

Android Firefox
![Screenshot_20200527-112359_Firefox Beta.jpg](https://images.zenhubusercontent.com/5d7fcf516b3dcf00019b60cd/3c8198f3-0387-48af-a23e-0b368bcf48dd)

Android Chrome
![Screenshot_20200527-112446_Chrome.jpg](https://images.zenhubusercontent.com/5d7fcf516b3dcf00019b60cd/95b901fb-5341-466c-930b-cf59976f449e)

iOS Firefox
![IMG_5052.PNG](https://images.zenhubusercontent.com/5d7fcf516b3dcf00019b60cd/c81dba3e-91da-438f-a604-dab8537682b2)

iOS Chrome
![IMG_5051.PNG](https://images.zenhubusercontent.com/5d7fcf516b3dcf00019b60cd/e9d12a46-4cc1-4a29-9cff-96ac9eead8be)

**Comment by bconfortin** [comment]
@matt-bullock Should be working now. I had to remove the fixed header from the mobile menu because it is a bug specific to the browser and how it handles transition (sliding menu) and position (fixed header). The Firefox Beta app on Android doesn't have this bug so maybe we can make the header fixed again in the future.

**Comment by matt-bullock** [comment]
I think that's fine to not have it fixed. I didn't notice the difference. Nice work getting that fixed
