### ISSUE TITLE
Cant take multiple orders already existing on the order book

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7843]
orders were in the orderbook already and I tried to take them...instead it placed my order as a bid and crossed the book...The trade doesnt fail in the console, it's just not taking the orders and my order goes on the book as a bid and crosses the book(see below)
(I dont get a failed trade message in the open orders button)

*If i place a bid to take the orders individually they trade, but do not, when i try to take multiple

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/abb259c9-81b6-484b-86cc-4909ceab336a)

**Comment by bthaile** [comment]
Not able to repro locally. 
sweeped asks (3 order) all orders were taken and user got a position. 

moving to need feedback, need to keep an eye out to see if this scenario is reproducible.
