### ISSUE TITLE
Trying to cancel an open order fails

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7844]
This occurs when I try to sweep 2 existing offers on the order book...my bid does not take them and instead it lands on the order book as a crossed book.....When I try to cancel my bid the trade fails...

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/16a10ddd-16c6-4fbd-b399-1805ebb95067)

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/32c881be-1266-4509-a773-dd33692b3903)

**Comment by Chwy5** [comment]
![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/a939ea63-6eea-49d2-86b5-4fa7571edc7e)

**Comment by bthaile** [comment]
cancelling looks to be working on Alex's most recent PR. moving this to UI Dev Outgoing and will move to Product Review once Alex's PR gets merged and deployed.

**Comment by Chwy5** [comment]
looks fixed - closing
