### ISSUE TITLE
Boxing Template Fix

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7849]
1) For template (O/U) rds outcomes
- Limit the number that can be input in the input box for rounds to 1-11

2) For template (O/U) rds outcomes
-Change Draw to "No Contest"

3) Change all the Draw outcomes to Draw/No Contest

4) For the What round will fight end? template.....Add in "No Contest" as an outcome

5) For How will the fight end? Change Draw to "No Contest"

6) BUG - For Method of Victory template- Outcomes displaying incorrectly

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/6ea920f5-df23-414f-9364-89c2571d83dc)

**Comment by Chwy5** [comment]
the dropdown for rounds...the numbers arent in order...
![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/92cd231b-214a-49e6-b9ef-082fdae6a6db)

**Comment by bthaile** [comment]
Ok, kick it back to me. Theres a flag I need to set.

**Comment by Chwy5** [comment]
fixed - closing
