### ISSUE TITLE
transferring modal confusing: transferring modal goes away when user transfers

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#7862]
confusing when user wants to transfer tokens from signing wallet to trading account. The modal goes away and user has no idea of anything is going on. Recommend keeping the modal up and showing processing button, also allow the user to close the modal manually. 

![2020-05-26 16.07.41.gif](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/7c9c4d83-7096-4295-93a0-2c776af3bb00)

**Comment by matt-bullock** [comment]
Could show the processing button then confirmed button state!. Then user can manually close the modal. It's not the smoothest but the best we can do without adding additional work
