### ISSUE TITLE
Trading Page: Market Depth Chart

### ISSUE THREAD

**Issue by sharkcrayon-augur** [AugurProject/augur#787]
Design Prototype: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=342%3A34455

This task is referring to this section:
![image](https://user-images.githubusercontent.com/46331128/50664289-c9045d80-0f69-11e9-9f06-5f96f9ddc846.png)

Add the Market Depth Chart:
- [x] The midpoint will now be anchored in the center of the chart.
- Leave out the plus and minus to the left and right of the midpoint. We'll be adding zoom functionality after the trading page is live.
- [x] The range of the chart should be determined by the largest value of the midpoint to the min or max. For example, if the midpoint is 0.3000 on a binary market, the value from the midpoint to the max is largest (0.7000). This should be reflected on the left side of the midpoint, making the total range displayed -0.4000 - 1.0000. The section of the graph from -0.4000 to 0.0000 will be blank, since that does not exist on a binary market. Check the design prototype for a mock.
- [x] Remove the "Qty, Price, Depth" labels and values from the top of the current chart.
- [x] Style the new hover state, showing Price, Volume, and Cost (the total ETH cost of filling all those orders, if the user were to click) to the left or right of the mouse as appropriate.
- [x] Adjust the line, shading, and label/tick styles to match the new mock. The shading should be vertical, from the top down.

**Comment by adrake33** [comment]
As per https://app.zenhub.com/workspaces/augur-5bfed3424b5806bc2bf8d173/issues/augurproject/augur/793, there may also be some styling/formatting changes needed for this chart on mobile, so please verify how the chart looks on mobile and make any necessary changes.

**Comment by JohnDanz** [comment]
This can now be found in new-trading-page-layout, and soon sneakpeak next time there is a push to it
