### ISSUE TITLE
http redirects for invalid parameters

### ISSUE THREAD

**Issue by sebs** [AugurProject/augur#787]
I have observed, when trying to change the url to http://, the redirect keeps all the parameters. 

Then I tried changing the protocol and some variables. The redirect is done, and the variable is validated and marked as error in the app. So far so good.

I think, the redirect should not take place at all and the app should validate the parameters beforehand and then not redirecting. 

Reproduce: 

Click a  detail page, change url to: 

https://app.augur.net/?page="0%2" if you are "ducktyping" this, I assume a division by zero and a very unexpected exception. 

Actual: Unknown state, application not responding. 

Expected: redirect is not executed.
[See Unvalidated Redirects and Forwards Cheat Sheet](https://www.owasp.org/index.php/Unvalidated_Redirects_and_Forwards_Cheat_Sheet)

**Comment by joeykrug** [comment]
won't happen w/ ipfs hosting so closing
