### ISSUE TITLE
Add checkbox to automatically top up fee reserve. Add to order ticket and account dropdown

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#7896]
Checked as default

[Order ticket design](https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=4220%3A13)

[Account dropdown design](https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=1808%3A5290)

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/33f4fb31-3bb3-47d1-a14f-a8f5030c3e3f)

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/9f2242ff-f9a1-42b0-9e90-56b6d3e246ef)

**Comment by pgebheim** [comment]
tag @JohnDanz

**Comment by Chwy5** [comment]
added - closing
