### ISSUE TITLE
bell in the header on mobile is off

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7909]
bell needs to move down in the header....issue may have something to do with size of the username

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/eab90fe8-ad49-4fd9-9277-cb1f58985833)

**Comment by matt-bullock** [comment]
looks fixed. closing

**Comment by Chwy5** [comment]
I am still seeing this....try a long account

I am using chrome on an android phone Galaxy s10

It corrects if i turn the phone sideways, but gets screwed up when i hold it normal (up and down)

**Comment by Chwy5** [comment]
fixed - was caused from a caching issue
