### ISSUE TITLE
my fills is incorrect when making trades at same price

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#7915]
scenario:
user gets into a position at 100 0.6 on outcome A. 
then closes position at 100 0.6.

The transactions are grouped together as `bought` they should be separate, a bought and a sell

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/d8d8abe3-cec2-44b2-9db4-07ffe7ff22d8)

**Comment by Chwy5** [comment]
fixed-closing
