### ISSUE TITLE
Scalar market - blows up

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7926]
clicking on the best bid in the outcome table and the order book is not filtering in the order ticket on a scalar for me
its not working on any market type....all it does is switch the Buy Shares from being underlined (in the order ticket) to sell shares (but doesn t filter in any fields (quantity, price Total order value) and then it switches back to buy shares a second later

Now after clearing out app cache...I am getting different behavior on a scalar market....If I click on the order (on the outcome table or book)...I get the messaging about what a scalar market is...if i hit OK and close it and do it again, that modal pops up again

If I click the dont show me this again box and then go click the order i get the same behavior described above and the site blows up

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/503012f2-632a-48fc-a323-a07567c532ea)

**Comment by bthaile** [comment]
looks like 0x mesh issue, assigning to @pgebheim

**Comment by pgebheim** [comment]
Very odd... lemme ask around about this.

**Comment by Chwy5** [comment]
fixed with caching issue
