### ISSUE TITLE
Mobile Trading Format & Styles

### ISSUE THREAD

**Issue by sharkcrayon-augur** [AugurProject/augur#793]
Design Prototype: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=342%3A34455

See the "Mobile - Almost Ready" page in the prototype. Mobile designs are mostly done, though a couple pieces here and there are still in flux. As a general guidelines, styles _within_ components, especially charts, should match what's done on Desktop. The few exceptions will be outlined below. When in doubt, ask Matt.

Tasks:

General: 
- [x] Create three tabs on mobile: Market Info, Trade, Orders. The user be able to click on a tab to change the trading "subpage", but should also be able to swipe left and right to change the subpage. If swiping is too hard or timely to implement, this can be postponed to after the trading page is live.

Market Info subpage:
- [x] Info from the Market Header will be displayed on the Market Info tab. Format and style this information as reflected in the design.
- [x] The outcome list will live on the Market Info tab. This is similarly formatted to what is available on desktop, with the exception that the outcome name is in a row above the outcome details. There is also a right-hand chevron on the far right of each row. An outcome row should be clickable and should transition the user to the Trade tab, with info for that particular outcome displaying.
- [ ] The Price History chart will live on the Market Info tab. You should not have to change any styles internal to this module (they should reflect what's shown on Desktop).

Trade subpage:
- [x] Add the "Select Outcome" select element. If an outcome was already clicked on the Market Info page, that selection should be reflected here. When the select element is clicked, a modal displaying the outcome list should appear (see mock). 
- [ ] The Candlestick and Market Depth charts will live on the Trade subpage. There may be some style and formatting changes needed internal to the Candlestick module for mobile to make everything fit (this is still in design at the moment).
- [x] Show the Order Book and Trade history below the charts. Styles internal to these modules should reflect what's done on Desktop. Both should be internally scrollable (just like on Desktop).

Orders subpage:
- [x] Open Orders, Filled Orders, and Positions will live on the Orders subpage.
- [x] Minimal formatting changes are needed for Open Orders, including some column labels wrapping to two lines and the outcome name on each open order living in its own row above the order details. Clicking on the vertical ellipses on the right of each row should highlight that order and bring up an option to cancel the order. The "Cancel All Open Orders" has a new style for mobile compared to Desktop.
- [x] Filled Orders has similar minimal formatting changes for mobile, including within the expanded details section.
- [x] Make the same changes for Positions, as reflected in the mocks.

General:
- [x] Add the "Buy / Sell" button. This will be present on every trading "subpage", and it should be fixed to the bottom of the screen (position: fixed) so it is always visible no matter the scroll position. Make sure there is enough padding at the bottom of each trading subpage so the user can scroll all the way to the bottom and not have the button overlapping content.
- [ ] When clicked on, the "Buy / Sell" button should bring up an order form modal.
- [ ] At the top of the modal, the user can toggle between buying and selling. It would be nice to animate the position of the toggle "pill", but not necessary if this takes too much time.
- [ ] The currently selected outcome should be displayed in the outcome select element, if one is already selected. Just like the other outcome select element, if clicked this should bring up the outcome list modal.
- [ ] A short version of the order book is displayed under the select element. Styles should match whatever is done on the other mobile version of the order book; the only difference is the number of orders immediately visible. The order book should be internally scrollable. Clicking on an order in the order book should populate the form below.
- [ ] Add the order form. This should contain the same elements and fields as is used on Desktop. The "Place Sell Order" / "Place Buy Order" button should live at the bottom of the form, and is not fixed to the bottom of the browser.

**Comment by phoebemirman** [comment]
i merged into the new trading page layout an initial mobile pass. without interactions, charts and order form.
