### ISSUE TITLE
Search returns poor results

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7934]
Example 1: When searching for short non-enlish words, e.g. "MMA"
When I type in MMA, into the search bar it returns a bunch of other markets not related to MMA

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/9873256c-6f67-406c-961a-45c91598c914)

Example 2: When searching for a category
search term `Augur` which is a new sub category for crypto. non related markets come up for the term

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/c0fbc82b-972d-48cb-bf28-b0124cf0d11f)

**Comment by pgebheim** [comment]
I think we'll need to do a pass of search tuning after launch. Gonna move this to 2.1 -- generally search gets a little weird with non-english short words.
