### ISSUE TITLE
Create hacks so Googlebot can load UI

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#7942]

**Comment by justinbarry** [comment]
Steps as I see them:
- [ ] Test if a plain html file will parse in the google bot seo tool. If so, continue.

Congratulations! We are in a position to use SSR react to solve our little issue.

- [ ] Use [ReactDOM server](https://reactjs.org/docs/react-dom-server.html) to generate markup.
- [ ] The app will need to use [ReactDOM.hydrate(](https://reactjs.org/docs/react-dom.html#hydrate) to take advantage of this markup in production.
- [ ] Add flash command to generate flat html file.
- [ ] As part of the webpack build conditionally load *all* javascript based on whether or not we are currently being run in google bot.

**Comment by justinbarry** [comment]
@pgebheim Can we close this when the hot load branch merges?
