### ISSUE TITLE
Landing Page Banners

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#7954]
We have updated the landing page for both Betting Exchange and SportsBook to include multiple banners:

*Please take into consideration that banners are still in progress, but page layout won't change*

On desktop breakpoint, we have a main banner (That corresponds to the site the user is looking at and invites to Sign Up), and 2 side banners that link through our other apps. 

On Mobile, Tablet and Tiny Desktop, the 3 banners lives together on a carrousel: 

[Figma reference](https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=2423%3A0)

**Comment by matt-bullock** [comment]
@bconfortin The side banners looks good. The top banner is missing the gradient overlay and the dots graphic. Let me know if you need help with exporting this image. Font weight looks off.

Should also get the mobile carousel set up with all the images. We'll get you the side images at the right sizes to work in the carousel.

**Comment by yanelbottini** [comment]
Hi @bconfortin, thanks for the updates. Here is the link where you can grab the final banner design for the TOP banner:

**https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7396%3A216185**

We need to buy the side banner photo. I'll let you know when we do it. 
For mobile, we plan to have a carousel set up with all the images. We'll get you the side images at the right sizes to work in the carousel.

**Comment by yanelbottini** [comment]
@matt-bullock 
I've moved this ticket to design review cause I've already prepared the different banner variations for the different breakpoints. You can find them here:
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7687%3A276585

We need to buy the iStockPhoto for Betting Exchange banner. I would like to have the photo to prepare the final assets and send this ticket back to Bruno. 

https://www.istockphoto.com/es/foto/aislado-hombre-de-jugador-de-f%C3%BAtbol-americano-gm868560768-145172673

WDYT?

**Comment by yanelbottini** [comment]
@bconfortin 
I've updated the banners with the missing picture (The one with the football player) and I've also prepared the different variations according to the different breakpoints. 

You can check the banners here:
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7789%3A278705

**Comment by Chwy5** [comment]
Sent back...still needs to be corrected
