### ISSUE TITLE
Refresh issue for FF creating a new market

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7967]
I just created a market and only my available fund dropped...the bond didnt get frozen in FF

waited 5 mins and still no update....If I log out and back in it appears

**Comment by bthaile** [comment]
not able to repro the issue. 
I did see a lag in sdk event so the UI showed placeholder market title for 20-30 seconds. once the event came in UI updated correctly. 

lets keep an eye on this for a while to see if the issue is consistent. moving to blocked/feedback needed.
