### ISSUE TITLE
Trades in TX History are always from the filler perspective

### ISSUE THREAD

**Issue by nuevoalex** [AugurProject/augur#797]
Trades in TX History are always from the filler perspective. They show up for the order creator however they display with text that is only accurate to the filler.

For example If I make an order to buy at .2 the UI will show that I _Sold_ at .2

**Comment by pgebheim** [comment]
@Chwy5 @joeykrug 

We need a decision here as to what should be displayed (on the current trading history) in the meantime before v2.

Do you agree with what @nuevoalex wrote, chwy?? Or do you think something else should be displayed.

**Comment by Chwy5** [comment]
No-  Filled orders need to show each user the way they know doing a trade.....
If the Maker enters buying 10 shares at 0.2 and I sell them 3 shares.....the Maker should know buying 3 at .2 and I should know selling 3 at .2

**Comment by Chwy5** [comment]
This is very important that it is clear this way, b/c we are going to have an export for record keeping as well (for accounting purposes)....hopefully through a .csv export and this needs to be easy to understand what the user did with their trades
