### ISSUE TITLE
Support Outcome button blanks webpage with errors

### ISSUE THREAD

**Issue by nuliknol** [AugurProject/augur#7973]
Clicking on "Support or Dispute Outcome" in Augur UI , using local testnet ends up showing blank screen. Some weird errors related to React Framework appear in the console log.

I recorded a video of bug reproduction for details.
https://drive.google.com/file/d/1lGqPqjwu0b2mBLFDDuAHhAeJefBpiAXP/view?usp=sharing

This is using sources as of today's morning.

**Comment by bthaile** [comment]
@nuliknol  we recently uploaded new contracts on kovan. 

Try pulling newest code
clear application data and hard refreshing

or are you running on fully local system? with local ethereum node?

**Comment by pgebheim** [comment]
Did you run this against the Kovan deploy or did you re-deploy locally or use the pop dockers?

**Comment by nuliknol** [comment]
@bthaile 
no, this is local testnet, you can see the config file there in javascript console, the addresses are not belonging to Kovan

**Comment by nuliknol** [comment]
@pgebheim I am using `yarn dockerall -f` and supply my own timestamp for testing purposes increasing timestamp by week on every time I run it.

**Comment by nuliknol** [comment]
this bugs actually happens after the second time I submit the Report, right after I submit the first report. And to clean this bug, I must go to browse another pages, then go back to market page again, and then the bug goes away, I can submit a Report, and when I click on it the second time, I get this error. So, navigating to another pages clears this bug. Weird stuff.

**Comment by nuliknol** [comment]
More screenshot on sudden blanking of the UI when clicking Report button. It happens on first click. React tells there is a possible memory leak, and also some errors with file locking are reported.  This bug is reproducible all the time on my machine and apparently it happens because I click on the button "Report" while there are still processes loading (like frozen funds, the chart, etc). If I wait 20 seconds, and then click "Report" the page isn't blanked.
![reporting_button_errors_shot1](https://user-images.githubusercontent.com/1125368/84455563-3f0ef880-ac23-11ea-857d-04632eb37da5.png)
![reporting_button_errors_shot2](https://user-images.githubusercontent.com/1125368/84455570-41715280-ac23-11ea-9bad-5e1ea3f44a8c.png)
![reporting_button_errors_shot3](https://user-images.githubusercontent.com/1125368/84455578-446c4300-ac23-11ea-8d97-779a0de4174c.png)
![reporting_button_errors_shot4](https://user-images.githubusercontent.com/1125368/84455582-46360680-ac23-11ea-9e73-195e688d7b5e.png)


I am using sources as of today.
@bthaile
