### ISSUE TITLE
Wrong color shield on twitter/instagram templates

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#7992]
I am getting a green shield, should be yellow as I need to input the twitter handle
it is missing the underline of the twitter handle

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/5bf69ef0-6691-461a-8bc3-3e1b5f8c7716)

**Comment by bthaile** [comment]
this has been fixed. moving to Product Review

on v2.augur.net
![image](https://user-images.githubusercontent.com/3970376/84206553-003b4000-aa75-11ea-878f-e35f546d15d3.png)

**Comment by Chwy5** [comment]
fixed -closing
