### ISSUE TITLE
Withdraw all funds and transfer testing scenarios

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#7996]
Scenarios:

#### Tries to withdraw all funds
1. user transfers 40 DAI into trading account. 
  no ETH in signing wallet ✅ 
 - note: Withdraw all funds estimate gas fails so modal does a transfer, tx is successful but leaves around 20% of the DAI in wallet and 0.01ETH shows up in signing wallet. Second tx for withdraw all funds only leaves a fraction of a DAI in trading account 

2. user transfers 100 DAI (has to be over 40 DAI) into trading account. 
 no ETH in signing wallet ✅ 

#### Tries to withdraw all funds
1. user has only ever had 40 DAI in their trading account 
  no ETH in signing wallet ✅ some value left in trading account
2. user has maintained DAI balance over 40 DAI.  
  user has fee reserve in signing wallet  ✅ **[working]** tested this scenaio, `withdrawAllFundsAsDai` transaction was successful. no DAI was left in trading account 

3. user has fee reserve but current DAI balance is 40 DAI. 
  just needs to be 40 DAI or less ✅  there is some value left in user's trading account. 

### New account no ETH, no account activation:
1. user transfers 40 DAI into trading account. 
  no ETH in signing wallet ✅ 

2. user transfers 100 DAI (has to be over 40 DAI) into trading account. 
 no ETH in signing wallet ✅ transferred 74 DAI left 1.20 in trading account. 

### Trading account has been activated
1. user has only ever had 40 DAI in their trading account 
  no ETH in signing wallet **[WORKING - was able to transfer out all my DAI]** ✅
2. user has maintained DAI balance over 40 DAI.  
  user has fee reserve in signing wallet ✅ 
3. user has fee reserve but current DAI balance is 40 DAI. 
  just needs to be 40 DAI or less **[WORKING - was able to transfer out all my DAI]** ✅

## Transfer DAI, REP tokens from signing wallet to trading account
1. user has no ETH in signing wallet, this should show error ✅ 
2. user has less ETH for gas cost than needed to transfer, this should show error ✅ 
3. user has enough ETH to pay gas costs. ✅

**Comment by bthaile** [comment]
transfer will trigger a Fee reserve top off if they transfer less than 90% of their DAI.

**Comment by matt-bullock** [comment]
tested most user cases and works as described
