### ISSUE TITLE
Prod build version of dev.augur.net

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#800]
We need a prod build deployed and put behind cloudflare caching.

Can still hit rinkeby. 

Call it: dev-prod.augur.net (or something better if you can come up with it)!

**Comment by petong** [comment]
created a cluster that is reachable via try.augur.net. a new docker image is built using the --production flag for yarn so the .js is minified.

https://github.com/AugurProject/augur-ui/commit/9367c348ae178653b419705c3467f98565eb0616
