### ISSUE TITLE
SDK Server does not tell UI that a 0x order is done processing

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#8003]
Using the SDK server and 0x RPC (0x mesh is off), create a new order. The UI order will show up in the UI as `PROCESSING ...`. 

Bugs:
1. If you navigate to another page then back to the market page, the order will show up in the orderbook. It should show up without needing to navigate away.
2. The order will only stop being tagged as `PROCESSING ...` if you refresh the page.

**Comment by robert-e-davidson3** [comment]
I added logging to `packages/augur-ui/src/modules/events/actions/log-handlers.ts`'s order-related functions then re-ran this test. None of them fired.

**Comment by pgebheim** [comment]
Hmm. Ok this is a good find let's talk through it tomorrow.

Paul

**Comment by robert-e-davidson3** [comment]
merged in a while ago
