### ISSUE TITLE
Several Report Filings on same Report

### ISSUE THREAD

**Issue by drkthng** [AugurProject/augur#802]
**Repro:**
Firefox 49.0.2 (Win 7)
Go To Report Page (ex: https://app.augur.net/?page=m&m=Who_will_win_the_MLB_World_Series_0xf856191babed561fdaa720620e09422f36fed36ec0c69a0d597faa4ae912d778)
Activate Radio Button of choice (Cubs)
Click Submit Report once
*Click Submit Report button several times
Go To Transaction Overview Page

**Expectation:**
a) Reports gets submitted
b) User gets visual confirmation that his choice has been submitted

**Actual:**
After Clicking Report "nothing" changes. After investigating the site, one can see that "Transaction Working" Count has increased by 1.
User gets no other visual cue.
Clicking the Button several times, the "Transaction Working" Count increases every time.

Going to Transaction Overview page, there are several entries listed for the given report (number equals number of clicks on the button) 
see Screenshot
![severalcommitreports](https://cloud.githubusercontent.com/assets/3247479/20055708/c02398fa-a4e2-11e6-97d1-055028d8c1b3.png)

**Comment by tinybike** [comment]
Resolved in Reporting updates.
