### ISSUE TITLE
"Exchange does not exist" error in local testnet config

### ISSUE THREAD

**Issue by nuliknol** [AugurProject/augur#8024]
I am getting continous errors of this type:

```
Uncaught (in promise) Error: Exchange does not exist
    at Uniswap.getExchangeRate (Uniswap.js:95)
    at async getRepRate (contractCalls.ts:341)
    at async eval (get-repToDai-rate.ts:9)


```

Steps to reproduce:
- Install local test net configuration:
           yarn docker:all
           yarn workspace @augurproject/ui dev
- Point the browser to the UI (localhost:8080)
- Click "Complete account activation"
- Click "Add Dai"
- Click "Transfer"

At this point the error starts to appear every few seconds
![exchange_does_not_exist_error](https://user-images.githubusercontent.com/1125368/84422275-64c7dd80-abe2-11ea-842c-cb702d3466bd.png)

**Comment by robert-e-davidson3** [comment]
This should be fixed from https://github.com/AugurProject/augur/pull/8293. Will verify in the UI once we redeploy to testnet.
