### ISSUE TITLE
Missing Open Order

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8030]
Missing order.....I added an open order for Invalid Market...it hit up in my open orders and I got a toast message for it (also FF updated correctly), but it does not appear on the outcome table or the order book...

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/0101a2f9-36b7-41df-8b85-ff78b2c68ba4)

**Comment by bthaile** [comment]
not able to repro. I created an order on Invalid and it showed up in the orderbook.
<https://v2.augur.net/#!/market?id=0x0F827E8fA13cc8F21a077275CFD964313Fd76f1E>

**Comment by bthaile** [comment]
bid at 0.25, market got marked Invalid
![image](https://user-images.githubusercontent.com/3970376/84503739-634cf280-ac80-11ea-99c4-423995b12720.png)

**Comment by Chwy5** [comment]
haven seen this again -closing for now
