### ISSUE TITLE
Finalizing Warp Sync Market doesnt update my rep balance

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8031]
I finalized the warp sync market through a notification, said I would get .0606 rep for doing it.....My Rep Balance in the "Your Overview Section" of Acct Summary pg didnt update (refreshing doesnt fix)

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/0f39a4c9-ec11-4c53-83c7-8b9cc65c5ef0)

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/3727a294-cc99-476b-bdd0-84853fcd7362)

**Comment by bthaile** [comment]
REP is in signing wallet not Trading account. decision was made because bots will prob be doing this transaction. @Chwy5 can you verify the REP is in your signing wallet?

**Comment by Chwy5** [comment]
confirmed -closing
