### ISSUE TITLE
Disabled state of the small buttons on market cards doesn't look correct

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#8032]
These look more active than disabled 

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/909f6ebe-6c83-4ddb-8c15-daf726c3e78e)

This is how it the disabled state should look

[Link to button](https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=15616%3A9197) - Refer to the button 'Small / Disabled'

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/db6a5b74-26d5-4105-964b-34223537ce8e)

**Comment by matt-bullock** [comment]
@bconfortin can you check the opacity is 0.25. It doesn't looked faded enough. Messaged you the details

**Comment by Chwy5** [comment]
fixed closing
