### ISSUE TITLE
add validation for year in templated market

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#8033]
## Estimated scheduled start time
 - [x] - fail template validation if market creation time is after estimated start time

## market question date time

 - [x] - fail template validation if endTime is before question date time
 - [x] - fail template validation if creationTime is after question date time

**Comment by Chwy5** [comment]
this looks to work from the ui side....I cant move forward during market creation....but this needs to be tested through an api

**Comment by bthaile** [comment]
@bconfortin  I'd like you to test these validations

There is 3 approaches to choose from:

1. updating and manually running a test
<packages/augur-test/src/tests/templates/validations.test.ts>
2. creating templated markets that have dates in the market question using flash scripts. See examples in <packages/augur-tools/src/flash/data/canned-markets.ts> 
you can see how methods  are called in scripts <packages/augur-tools/src/flash/scripts.ts> 

`yarn flash create-canned-template-markets`

3. create unit tests that will be run. look at <packages/augur-test/src/tests/api/Betting.test.ts> as an example.

**Comment by bthaile** [comment]
@Chwy5 the market creation form uses same validation for year as post market creation. I think that is a good way to test it.

**Comment by Chwy5** [comment]
looks good....closing
