### ISSUE TITLE
Gas price mobile modal issue

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#8040]
On mobile only:

Two issues:
 * If user opens Advanced it won't close the advanced section. It remains open even if the user toggles the `advanced` button. Only the Arrow changes to pointing up or down. 
So if the user changes to a custom gas Price they can't not save the value. 

 * They can not scroll down to hit the apply button. 

![826B43CD-6939-484F-AADD-63AB2AF20FAE](https://user-images.githubusercontent.com/3970376/84602479-5df0d300-ae4d-11ea-884a-a630dd7930a9.png)

**Comment by Chwy5** [comment]
fixed closing
