### ISSUE TITLE
Submit Orders button is broken

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#805]
Under My Markets ...when getting yellow message (see screenshot) that user has unsigned orders pending for market initial liquidity.....The submit orders button doesnt work.

![1-8cat5a](https://user-images.githubusercontent.com/41301809/50850800-f45fc180-1348-11e9-9488-8ff7a3c9bc61.jpg)

![1-8cat5b](https://user-images.githubusercontent.com/41301809/50850818-02154700-1349-11e9-9530-c8811e287dcf.jpg)

**Comment by Chwy5** [comment]
![1-8json2](https://user-images.githubusercontent.com/41301809/50852540-cf218200-134d-11e9-8a5a-7cbb4e49c4a9.jpg)

I get this error in the console when i hit the submit orders button

**Comment by adrake33** [comment]
John and I are having trouble reproducing this. Closing for now.
