### ISSUE TITLE
Soccer template changes

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8050]
1) Under Men's Leagues Add new template:
Men's [League] [year/year] Champion           **With the exception of MLS that will only use [Year] if selected

2) Under Customized for e existing templates
     A) Remove Football (soccer) from 3 existing templates 
     B) Add Drop down in it's place
     C) IF Women's is selected (Only option is) World Cup
     D) If Men's is selected the drop down can contain:
               a.  World Cup
               b.  UEFA Champions League
               c.  UEFA Europa League
               d.  Copa America
                e.  AFC Asian Cup
                f.  AFC Champions League
                g.  CONCACAF Gold Cup
                h.  CONCACAF Champions League
                i.   Friendlies

3)  Add new template:
[Men's/Women's] [Event] [year/year] Winner
     A) IF Women's is selected (Only option is) FIFA World Cup (Year option format is single year)
     B) If Men's is selected the drop down can contain:
               a.  FIFA World Cup (Single year format) - starting in 2022, 2026, 2030
               b.  UEFA Champions League (year/year) repeats annually
               c.  UEFA Europa League (year/year) repeats annually
               d.  Copa America (Single year format )- starting in 2021, 2024, 2028
                e.  AFC Asian Cup (Single year format )- starting in 2023, 2027, 2031
                f.  AFC Champions League (Single year format) repeats annually 
                g.  CONCACAF Gold Cup  (Single year format) repeats every other yr 2021, 2023, 2025
                h.  CONCACAF Champions League (Single year format) repeats annually

**Comment by Chwy5** [comment]
Resolution Rules For League or Event Winner:

If winner is not listed as a market outcome, market should resolve as 'Other (Field)'

If the season is officially cancelled and the league/event in the market not is played, this market should resolve as 'Invalid'

If the league or Governing Organization suspends play and starts up again at a later date, and the winner of the event in the market is determined before the Market’s Event Expiration begins, this market is still valid and should be settled accordingly.

If the league or Governing Organization suspends play and starts up again at a later date, and the winner of the event in the market is determined after the Market’s Event Expiration begins, this market should resolve as 'Invalid'.

**Comment by bthaile** [comment]
```
{
  text: `If winner is not listed as a market outcome, market should resolve as 'Other (Field)'.`,
},
{
  text: `If the season is officially cancelled and the league/event in the market question is not played, this market should resolve as 'Invalid'.`,
},
{
  text: `If the league or Governing Organization suspends play and starts up again at a later date, and the winner of the event in the market is determined before the Market’s Event Expiration begins, this market is still valid and should be settled accordingly.`,
},
{
  text: `If the league or Governing Organization suspends play and starts up again at a later date, and the winner of the event in the market is determined after the Market’s Event Expiration begins, this market should resolve as 'Invalid'.`,
},
```

**Comment by Chwy5** [comment]
added -closing
