### ISSUE TITLE
iPad: Total funds tootip broken of Firefox when using an iPad Size

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8059]
Total funds tooltip doesnt open when clicking on Firefox when using an ipad size...this occurs exactly at size 768...if i make 770 it works

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/e7dd75af-d336-4343-9687-75d5be768a34)

**Comment by pgebheim** [comment]
Problem here is touch simulation:

With it on, clicking on the tooltip thing wont show the tooltip as it should.
![image](https://user-images.githubusercontent.com/86010/87085591-fc6e1b00-c1e4-11ea-8111-e7a6c711fe12.png)

With it off, hovering does show:
![image](https://user-images.githubusercontent.com/86010/87085651-13147200-c1e5-11ea-8723-5685efdb369f.png)

**Comment by bconfortin** [comment]
This is working as intended. Check Paul's suggestion above.

On the responsive emulator
![working.png](https://images.zenhubusercontent.com/5d7fcf516b3dcf00019b60cd/1f4cfbd5-c693-45af-956a-51f1dd187715)


On a resized screen (with responsive emulator turned off)
![without simulation mode.png](https://images.zenhubusercontent.com/5d7fcf516b3dcf00019b60cd/134c66f1-f37a-43de-ab5f-f396404ab539)

**Comment by matt-bullock** [comment]
Working for me. closing
