### ISSUE TITLE
Search in UI returns rows unrelated to keyword

### ISSUE THREAD

**Issue by nuliknol** [AugurProject/augur#8063]
This is on Kovan's network.
URL: https://v2.augur.net/

When I search for markets that contain "Augur" the results shown are unrelated to "Augur" keyword.
Screenshot attached for more info
![search_shows_any_row](https://user-images.githubusercontent.com/1125368/84828836-4f8ced80-afec-11ea-8f21-1474dbe177b8.png)

**Comment by pgebheim** [comment]
This is a duplicate of #7593 -- we definitely need to see what we can do about search as there seem to be lots of little cases where things are just wrong.
