### ISSUE TITLE
Pre-liquidity orders don't cause bell alert

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8068]
I created a new market and added pre-liquidity (passed the spread filter)....My market gets created (and I get a toast message to confirm this) I sign my pre-liquidity orders.....they do show up in open orders, but I do NOT get a toast/bell message for them and my newly created market still shows liquidity depleted.

liquidity depleted goes away after refreshing......but i still get no bell messages for those orders being created

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/3a40136b-20ab-4569-9553-8c12cef82ec8)

**Comment by bthaile** [comment]
The liquidity label is based on a property that is calculated in the sdk, it gets re-calculated (it’s an Resource intensive calculation) every minute or so. Therefore the label will go away a minute or so after orders have been created.

**Comment by matt-bullock** [comment]
Seeing it in the bell now
