### ISSUE TITLE
Portis sign in mobile Bug

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8069]
Trying to sign onto portis on mobile.... First it just spins for ever.....after 30 seconds the sign box appears....then I am getting another sign box asking me to connect accounts to augur. Afte I agree and hit it, I get another one saying to continue on augur login to portis....even though i am signed in now......
![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/b60f2f9c-b41e-450a-8165-dc6b1f7ffff2)

If I hit continue it just takes me back to the screen saying Augur would like to connect your account

**Comment by andrewdamelio** [comment]
@Chwy5 a few questions.

- Is this a constant issue? Like does it happen every time you try and use Portis?
- Does this only happen to you on mobile? Does trying to login with the same account on desktop work?

**Comment by Chwy5** [comment]
Yes constant issue. Happens on Mobile and desktop emulator - mobile size (think i spelled that right)

I can login using normal desktop

This morning it just spins using mobile (and emulator)....clicking continue button doesnt do anything for me

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/5e728ee9-d3ec-4af1-844f-4a1ed91af4c6)

**Comment by Chwy5** [comment]
If I go to desktop it works, bc after i click the continue button it brings up this modal to login(which it doesn t bring up on mobile)....

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/43420e5c-60fa-4d8a-abb4-d73459a30b6f)

**Comment by andrewdamelio** [comment]
closing since we are removing Portis
