### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by nuliknol** [AugurProject/augur#8086]
I am getting this error when I switch Outcomes in the popup-up while entering different orders one after another. To continue I need to reload the page and sometimes the reload doesn't work so I restart the browser.
Don't have the reproduction steps as it happens randomly.

![something_went_wrong](https://user-images.githubusercontent.com/1125368/85067559-81ca5680-b176-11ea-99ce-aa3a436384a8.png)

Error code text:

```
0x add order validation failure: {"orderHash":"0x49ce439d444596731d8930c7df38b851551f028e5b3340fccd3d7a2dccaadb4a","signedOrder":{"chainId":102,"exchangeAddress":"0x2e90e3c430c1470d62587c8983755d717f46f617","makerAddress":"0x4b55c101a480256a4b127a7fcbd13fed0dd56eef","makerAssetData":"0x94cfcdd7000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000001c000000000000000000000000000000000000000000000000000000000000002200000000000000000000000000000000000000000000000000000000000000124a7cb5fb70000000000000000000000006749e370e7b1955ffa924f4f75f5f12653c7512c000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000001c8e74ad31921c1e271b18e5dfb37148ea526e6ae0000000000000000000d0101000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024f47261b00000000000000000000000005f3341ea5989ad3129e325027b8d908b63709a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e4a7cb5fb70000000000000000000000008470f1aac60a08d2282616f19a4c52718847b847000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","makerFeeAssetData":"0x","makerAssetAmount":"1000000000000000000","makerFee":"0","takerAddress":"0x0000000000000000000000000000000000000000","takerAssetData":"0xa7cb5fb70000000000000000000000006749e370e7b1955ffa924f4f75f5f12653c7512c000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","takerFeeAssetData":"0x","takerAssetAmount":"1000000000000000000","takerFee":"0","senderAddress":"0x0000000000000000000000000000000000000000","feeRecipientAddress":"0x0000000000000000000000000000000000000000","expirationTimeSeconds":"1592265660","salt":"1592510997150","signature":"0xf261a70d45f59b8a7bc3cdbffe5e498313eba3ebf87607e2631825e0a82094a669423295b1c6a1eb13f9b4aece1317e7bceb1efd5c101a668d431b01df714a001c07"},"kind":"ZEROEX_VALIDATION","status":{"code":"OrderExpired","message":"order expired according to latest block timestamp"}}
```

The setup is local testnet :

```
yarn docker:all
yarn workspace @augurproject/ui dev

```
![something_went_wrong2](https://user-images.githubusercontent.com/1125368/85068054-55fba080-b177-11ea-8fb9-cfa810bc104a.png)

**Comment by nuliknol** [comment]
@pgebheim 

After some code updates (made few days ago, or maybe today), I get very frequently the "no blocks were stored" when continuously creating SELL orders while changing Outcomes in Categorical markets:

![no_blocks_were_stored](https://user-images.githubusercontent.com/1125368/85586337-765bad00-b606-11ea-9905-159360d62b0d.png)

![no_blocks_transaction_failure](https://user-images.githubusercontent.com/1125368/85586421-883d5000-b606-11ea-8613-404a95386d3b.png)

This test was on Kovan network, so obviously thera are blocks there. Actually, the first transaction went through, but when I changed the Outcome in the popup, this error appeared upon submitting the order.

**Comment by pgebheim** [comment]
I need console log output to help with this. Could you post it? You're almost certainly spewing errors, probably writing to the database.

If you can send me that and then clear the app state and try again that would be appreciated.

The update on Monday includes backwards incompatible db changes.

**Comment by nuliknol** [comment]
@pgebheim 

the bug is still there , here is the video on how it is occurring.


[something_went_wrong.zip](https://github.com/AugurProject/augur/files/4848135/something_went_wrong.zip)

**Comment by nuliknol** [comment]
Here is another screenshot of this error (with sources as of today), but using Firefox. Here I am seeing a clear error in building 0xMesh order object:

![0x_mesh_order_build_error](https://user-images.githubusercontent.com/1125368/87335077-52083780-c505-11ea-8f30-891ecb93c358.png)

This error showed up after creating 2nd order. First order went ok, second order failed.
My guess would be that the problem is in the encoding of Market Data.

@pgebheim

**Comment by pgebheim** [comment]
This order is already expired when you're making it. Do you have an expiration time set explicitly?

**Comment by pgebheim** [comment]
@nuevoalex Would be good try to see if this is reproducible. @bthaile -- Do you think this could be the result of the UI setting the expiration timestamp wrong in some case that's happening only on this localhost? I've never seen this one before....

**Comment by nuliknol** [comment]
> This order is already expired when you're making it. Do you have an expiration time set explicitly?

@pgebheim  @nuevoalex 
no, but there is a little detail , I am running the local testnet setup using this command:

`yarn docker:all -f`

so, the time is always constant, however if it is constant, the order shouldn't be expiring. 
As for expiration date, I am not moving it, so it is set as default when data on the form is entered. 
Or maybe it is a timezone issue? I am in GMT-6

**Comment by pgebheim** [comment]
Something weird is going on here for sure, but as far as I can tell its related to this local dev / fake-time case -- I'm going to move it out of the v2-release and have someone take a look with slightly lower priority.

Are you saying you never moved the fake time?
