### ISSUE TITLE
Add  Est Tx Fee line to order ticket for Open Orders/Post Only

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8087]
1) always show Est Tx Fee (paid by Fee reserve) and show $0.00 for Open Orders

2) Add 'Post Only' to Order ticket dropdown

trigger error message if Post only order will fill any part of an order in the UI

*Post-Only Orders serve to strictly ensure that your Limit Orders will be placed into the order book.  By selecting this option, the UI will automatically fail to match the order or place it on the orderbook, if it detects that it will be executed immediately upon the order placement.

**Comment by Chwy5** [comment]
Post Only  is allowing me to trade...cant allow me to trade and needs to trigger a message

**Comment by bthaile** [comment]
![image](https://user-images.githubusercontent.com/3970376/85438643-c9bff380-b551-11ea-891f-90add3fdecee.png)

**Comment by Chwy5** [comment]
added -closing
