### ISSUE TITLE
ProfitLossChanged event is not reported under certain conditions

### ISSUE THREAD

**Issue by nuliknol** [AugurProject/augur#8092]
Problem: Augur fails to report **realized** profits for trading activity under certain conditions. The `ProfitLossChanged` event isn't emitted when wallet contract makes profits.

Steps to reproduce:

Use fixed time local testnet config

```
yarn docker:all -f
yarn workspace @augurproject/ui dev
```

1. Create market from Scratch (custom market)
2. Pick "Multiple Choice" (Categorical)

Market description: What city is the safest to live in Mexico?
Enter 3 outcomes: Puebla, Durango, Merida
	
Do not create initial market liquidity.

Fill all the other fields with some values and create market

MarketCreated event will look like this:

```
MarketCreated {
    Universe: 0x82a37C54267b1e9D94C37895Fe26EC232aA55030
    EndTime: 1591315260
    ExtraInfo: {"categories":["Medical","Covid-19",""],"description":"What city is the safest to live in Mexico?","longDescription":"I decide the outcom
e","_scalarDenomination":"","offsetName":null,"template":null}
    Market: 0xC8e74AD31921C1e271b18E5dfB37148eA526E6aE
    MarketCreator: 0xD13915703c36e894A45B5242742f6CE3c83eD501
    DesignatedReporter: 0xD13915703c36e894A45B5242742f6CE3c83eD501
    FeePerCashInAttoCash: 19900000000000000
    Prices: 0,1000000000000000000
    MarketType: 1
    NumTicks: 100
    Outcomes: Puebla,Durango,Merida
    NoShowBond: 349680582682291667
    Timestamp: 1591171544
}
```

Use 2 accounts for testing.

On the First account, create SELL ORDERS in this order:

Account 1: Sells 100 shares of outcome Merida for $0.38 (SELL ORDER)
Account 1: Sells 100 shares of outcome Durango for $0.62 (SELL ORDER)
Account 1: Sells 100 shares of outcome Puebla for $0.43 (SELL ORDER)

Login to the Second account, and fill the ORDERS in the same order they were created:

Account 2: Fills order for 100 shares of Merida (BUY ORDER)
Account 2: Fills order for 100 shares of Durango (BUY ORDER)
Account 2: Fills order for 100 shares of Puebla (BUY ORDER)

Now , switch to Account 1, you will see that you already have profits, but market has not yet finalized.

![portfolio](https://user-images.githubusercontent.com/1125368/85083061-3e7fe000-b196-11ea-92d6-4e6ca5562ca1.png)

![account_summary](https://user-images.githubusercontent.com/1125368/85083072-4475c100-b196-11ea-9296-2461a44c73f4.png)

Here are all the ProfitLoss events I am receiving during this test:
```

ProfitLossChanged {
    Universe: 0x82a37C54267b1e9D94C37895Fe26EC232aA55030
    Market: 0xC8e74AD31921C1e271b18E5dfB37148eA526E6aE
    Account: 0xf1b8E0f676e1b3449241eF70Af3e165579e88Cb8
    Outcome: 3
    NetPosition: 1000000000000000000
    AvgPrice: 38000000000000000000
    RealizedProfit: 0
    FrozenFunds: 38000000000000000000000000000000000000
    RealizedCost: 0
    Timestamp: 1591171544
}

ProfitLossChanged {
    Universe: 0x82a37C54267b1e9D94C37895Fe26EC232aA55030
    Market: 0xC8e74AD31921C1e271b18E5dfB37148eA526E6aE
    Account: 0x4B55c101A480256A4b127A7FCBD13fED0DD56EeF
    Outcome: 3
    NetPosition: -1000000000000000000
    AvgPrice: 38000000000000000000
    RealizedProfit: 0
    FrozenFunds: 62000000000000000000000000000000000000
    RealizedCost: 0
    Timestamp: 1591171544
}
ProfitLossChanged {
    Universe: 0x82a37C54267b1e9D94C37895Fe26EC232aA55030
    Market: 0xC8e74AD31921C1e271b18E5dfB37148eA526E6aE
    Account: 0xf1b8E0f676e1b3449241eF70Af3e165579e88Cb8
    Outcome: 2
    NetPosition: 1000000000000000000
    AvgPrice: 62000000000000000000
    RealizedProfit: 0
    FrozenFunds: 62000000000000000000000000000000000000
    RealizedCost: 0
    Timestamp: 1591171544
}
ProfitLossChanged {
    Universe: 0x82a37C54267b1e9D94C37895Fe26EC232aA55030
    Market: 0xC8e74AD31921C1e271b18E5dfB37148eA526E6aE
    Account: 0x4B55c101A480256A4b127A7FCBD13fED0DD56EeF
    Outcome: 2
    NetPosition: -1000000000000000000
    AvgPrice: 62000000000000000000
    RealizedProfit: 0
    FrozenFunds: -62000000000000000000000000000000000000
    RealizedCost: 0
    Timestamp: 1591171544
}
ProfitLossChanged {
    Universe: 0x82a37C54267b1e9D94C37895Fe26EC232aA55030
    Market: 0xC8e74AD31921C1e271b18E5dfB37148eA526E6aE
    Account: 0xf1b8E0f676e1b3449241eF70Af3e165579e88Cb8
    Outcome: 1
    NetPosition: 1000000000000000000
    AvgPrice: 43000000000000000000
    RealizedProfit: 0
    FrozenFunds: 43000000000000000000000000000000000000
    RealizedCost: 0
    Timestamp: 1591171544
}
ProfitLossChanged {
    Universe: 0x82a37C54267b1e9D94C37895Fe26EC232aA55030
    Market: 0xC8e74AD31921C1e271b18E5dfB37148eA526E6aE
    Account: 0x4B55c101A480256A4b127A7FCBD13fED0DD56EeF
    Outcome: 1
    NetPosition: -1000000000000000000
    AvgPrice: 43000000000000000000
    RealizedProfit: 0
    FrozenFunds: -43000000000000000000000000000000000000
    RealizedCost: 0
    Timestamp: 1591171544
}
```

So, at this point my (wallet) account already booked ($43.00 DAI) profits, but the events I have recevied never have `RealizedProfit` field greater than zero. All `RealizedProfit` fields in all 6 events I am receiving have value `= 0`.

I have ran this test to the end , until Market gets `Reported` and `Finalized` but the Profit loss for these $43 bucks never comes in. And it never comes because it was already booked, but `ProfitLossChanged` events emitted by the contracts don't notify I made *REALIZED* profits. They notify Frozen Funds only.

I think this bug is kind of making `ProfitLossChanged` event unreliable to track profits made in Augur system, so I hope this can be fixed. And by the way, the event neither comes when the Account books a loss , however this is easily detected because outcome value is different from winning outcome, but anyway , it would be nice to have `ProfitLossChanged` event more precise than it currently is (also for the losses, not only for the profits).

**Comment by pgebheim** [comment]
In this case you have an aggregate open position as a result of your three initial sells. Because you placed all 3 initial open orders together before any are filled, you are escrowing cash to cover each of those trades.

Then this resulting position shows the unrealized profit and loss being calculated as the last trade price minus average price to enter the position.

Those profits wouldn't be realized until Account 1 closes the position, in which case their realized profits would be calculated based on actual sale price. Once the market has finalized, any shares you own can be turned in for Cash -- with winning shares being redeemed at 1.

When you do this (via the claim proceeds flow) you should see the realized profit reflected in your PL. Also, losing shares are automatically counted as 0 even if you never redeem.

**Comment by nuliknol** [comment]
> In this case you have an aggregate open position as a result of your three initial sells. Because you placed all 3 initial open orders together before any are filled, you are escrowing cash to cover each of those trades.
> 
> Then this resulting position shows the unrealized profit and loss being calculated as the last trade price minus average price to enter the position.
> 
After all the 3 orders were filled, the Account 1 has **REALIZED** profits already. I have made `balance_of()` call to the contract and it reports 1043 DAIs, so at this moment, I can withdraw these funds without waiting for Market to finalize
![withdrawal](https://user-images.githubusercontent.com/1125368/85136783-c2bd7c00-b205-11ea-90ae-f23705e4d832.png)
![funds_gone](https://user-images.githubusercontent.com/1125368/85136798-cb15b700-b205-11ea-8249-b6dcf40b745e.png)

on first trade (filled) the balance of the wallet goes to 938 DAI
on second trade the balance of the wallet goes to 1000 DAI
on third trade the balance of the wallet goes to 1043 DAI

And then I can withdraw all the funds _without waiting for Market to finalize_.
And my point is: I am not getting ProfitLossChanged event when this happens, that's the bug, not that I booked profits before market finalization.

> Those profits wouldn't be realized until Account 1 closes the position, in which case their realized profits would be calculated based on actual sale price. Once the market has finalized, any shares you own can be turned in for Cash -- with winning shares being redeemed at 1.
> 
No, this is not the case, Account 1 has **realized** profits right after the last order is filled.

> When you do this (via the claim proceeds flow) you should see the realized profit reflected in your PL. Also, losing shares are automatically counted as 0 even if you never redeem.

Account 1 doesn't show "Claim" proceeds button because the system gave me profits already.

![no_claim_proceeds_button](https://user-images.githubusercontent.com/1125368/85137037-2d6eb780-b206-11ea-8f9c-aff6896e9aff.png)
![portfolio_with_profits](https://user-images.githubusercontent.com/1125368/85137044-2fd11180-b206-11ea-9c70-c8629ee3d7ea.png)

**Comment by nuliknol** [comment]
@pgebheim

**Comment by nuliknol** [comment]
@pgebheim 

I have reproduced this test case on Kovan network. More bugs where found, the new bug is that the UI doesn't show my 3 trades, but it shows only 2 trades, like the third trade never happened.

Market: https://v2.augur.net/#!/market?id=0xeFc2d6dB438C02BcD739d5479d19434c347bbA3B

After I created the 3 orders:

```
Account 1: Sells 100 shares of outcome Merida for $0.38 (SELL ORDER)
Account 1: Sells 100 shares of outcome Durango for $0.62 (SELL ORDER)
Account 1: Sells 100 shares of outcome Puebla for $0.43 (SELL ORDER)
```

And Filled the 3 orders:

```
Account 2: Fills order for 100 shares of Merida (BUY ORDER)
Account 2: Fills order for 100 shares of Durango (BUY ORDER)
Account 2: Fills order for 100 shares of Puebla (BUY ORDER)
```

I got $43 in profits on Account 1:

![booked_profits_account_summary](https://user-images.githubusercontent.com/1125368/85584220-8e323180-b604-11ea-95ed-2a026e1e2888.png)

The new bug is that only 2 orders are shown:
![acct_summary_open_positions](https://user-images.githubusercontent.com/1125368/85584344-adc95a00-b604-11ea-9f29-a25837916bb8.png)

here is the ALL positions tab:
![acct_summary_all_positions](https://user-images.githubusercontent.com/1125368/85584415-be79d000-b604-11ea-8e72-feb0d066301d.png)

On the Account 2, the FILLER account, this is what I see:
![filler_account_acct_summary](https://user-images.githubusercontent.com/1125368/85584564-e0735280-b604-11ea-9448-d79dbcced037.png)

![filler_account_frozen_funds](https://user-images.githubusercontent.com/1125368/85584582-e406d980-b604-11ea-8884-0596181d4e06.png)


These are the ProfitLossChanged events I am receiving:

```
INFO: 14:37:29 ProfitLossChanged event found (block=19242444) :
ProfitLossChanged {
        Universe: 0x919274CE3Ba5a0D0f11071Bb9fb402AE5c23381B
        Market: 0xeFc2d6dB438C02BcD739d5479d19434c347bbA3B
        Account: 0xfd8317dBD028b27E035D050545D66C8a103e1a1c
        Outcome: 2
        NetPosition: 1000000000000000000
        AvgPrice: 62000000000000000000
        RealizedProfit: 0
        FrozenFunds: 62000000000000000000000000000000000000
        RealizedCost: 0
        Timestamp: 1593009440
}

INFO: 14:37:29 ProfitLossChanged event found (block=19242444) :
ProfitLossChanged {
        Universe: 0x919274CE3Ba5a0D0f11071Bb9fb402AE5c23381B
        Market: 0xeFc2d6dB438C02BcD739d5479d19434c347bbA3B
        Account: 0x562e66b3d200566589Ee3F55F05b027340e27978
        Outcome: 2
        NetPosition: -1000000000000000000
        AvgPrice: 62000000000000000000
        RealizedProfit: 0
        FrozenFunds: -62000000000000000000000000000000000000
        RealizedCost: 0
        Timestamp: 1593009440
}
INFO: 14:36:34 ProfitLossChanged event found (block=19242436) :
ProfitLossChanged {
        Universe: 0x919274CE3Ba5a0D0f11071Bb9fb402AE5c23381B
        Market: 0xeFc2d6dB438C02BcD739d5479d19434c347bbA3B
        Account: 0xfd8317dBD028b27E035D050545D66C8a103e1a1c
        Outcome: 3
        NetPosition: 1000000000000000000
        AvgPrice: 38000000000000000000
        RealizedProfit: 0
        FrozenFunds: 38000000000000000000000000000000000000
        RealizedCost: 0
        Timestamp: 1593009388
}
INFO: 14:36:34 ProfitLossChanged event found (block=19242436) :
ProfitLossChanged {
        Universe: 0x919274CE3Ba5a0D0f11071Bb9fb402AE5c23381B
        Market: 0xeFc2d6dB438C02BcD739d5479d19434c347bbA3B
        Account: 0x562e66b3d200566589Ee3F55F05b027340e27978
        Outcome: 3
        NetPosition: -1000000000000000000
        AvgPrice: 38000000000000000000
        RealizedProfit: 0
        FrozenFunds: 62000000000000000000000000000000000000
        RealizedCost: 0
        Timestamp: 1593009388
}
INFO: 14:39:35 ProfitLossChanged event found (block=19242463) :
ProfitLossChanged {
        Universe: 0x919274CE3Ba5a0D0f11071Bb9fb402AE5c23381B
        Market: 0xeFc2d6dB438C02BcD739d5479d19434c347bbA3B
        Account: 0xfd8317dBD028b27E035D050545D66C8a103e1a1c
        Outcome: 1
        NetPosition: 1000000000000000000
        AvgPrice: 43000000000000000000
        RealizedProfit: 0
        FrozenFunds: 43000000000000000000000000000000000000
        RealizedCost: 0
        Timestamp: 1593009568
}
INFO: 14:39:35 ProfitLossChanged event found (block=19242463) :
ProfitLossChanged {
        Universe: 0x919274CE3Ba5a0D0f11071Bb9fb402AE5c23381B
        Market: 0xeFc2d6dB438C02BcD739d5479d19434c347bbA3B
        Account: 0x562e66b3d200566589Ee3F55F05b027340e27978
        Outcome: 1
        NetPosition: -1000000000000000000
        AvgPrice: 43000000000000000000
        RealizedProfit: 0
        FrozenFunds: -43000000000000000000000000000000000000
        RealizedCost: 0
        Timestamp: 1593009568
}
```
Now, just to remind what is the bug here: **_the bug is that RealizedProfit = 0, which is incorrect, there must be +$43 DAIs of profit in some of these event records_**.


Etherscan Transactions:
Order 1: https://kovan.etherscan.io/tx/0xeea0a06b343a3adf129ad31419e9a8061a16cf6677502f79695575c68a3c587c#eventlog
Order 2: https://kovan.etherscan.io/tx/0xa5c5b96d7cf5fd77acae5a24c3a243d05f8ec90eb7666a4002e25a50cfd2295c#eventlog
Order 3: https://kovan.etherscan.io/tx/0x623cd708954c4f7754fca2b3fa7bd187cfbb411a116b0815ab675f71592e09f3#eventlog

Account 1 (CREATOR)
EOA: 0xB00084262F130F389D2F524bEE88fb96089065D1
Wallet Contract: 0x562e66b3d200566589Ee3F55F05b027340e27978

Account 2 (FILLER)
EOA: 0x1b2E85De21C7CF4bD1787c6Ac4bd505e83b62Ba5
Wallet Contract: 0xfd8317dBD028b27E035D050545D66C8a103e1a1c

Order Hashes:
Order 1: 88cf905e1cfb99704fb66078f067dbbf90bb46b65e0f151e9778eca1cae77105
Order 2: 7e20f9f5dc30359d8c84e33e9e66c99feb5699187561fba91298234bcf7634dd
Order 3: 7e9eb1222a4eeee06c1caacb8d5b58c91f1e20a87728a612dd7dc5b8323bfec3

**Comment by pgebheim** [comment]
@nuliknol -- We are changing the way we are computing and handling profit and loss when moving to an AMM based share approach. Closing this now.
