### ISSUE TITLE
Augur V2 fully local deployment

### ISSUE THREAD

**Issue by Troublor** [AugurProject/augur#8105]
Hi, recently I would like to fully deploy Augur locally, including smart contracts (on geth private chain), augur-node and augur-ui, in order to inspect the source code. I noticed that there is a tutorial [here](https://github.com/AugurProject/augur-ui/blob/master/docs/dev-local-node.md) about "running everything locally". However I tried that tutorial and found it is for Augur V1 instead of V2. 
So my question is: how can I "run everything of Augur V2 locally"? 

Thanks in advance.

**Comment by bthaile** [comment]
There is a docker with the contracts deployed already. Pull down the augur mono repo <https://github.com/AugurProject/augur>

yarn
yarn build

To start docker `yarn flash docker-all`

flash is a utility we use to rum a lot of convenient scripts. Then you have a local geth node with augur v2 contracts already deployed. There are already a few custom markets created. 

if you want to run the UI to see, run this command in another shell in the augur code directory. `yarn workspace @augurproject/ui dev`

**Comment by Troublor** [comment]
Thanks for response. Is there a way to deploy contracts by myself?

**Comment by Troublor** [comment]
@bthaile Is Augur V2 still using augur-node as centralised database to store data? I didn't see it in the [AugurProject/augur/packages](https://github.com/AugurProject/augur/tree/master/packages)
