### ISSUE TITLE
Create initial V2 AN repo

### ISSUE THREAD

**Issue by nuevoalex** [AugurProject/augur#811]
Create a functional spike repo with the appropriate scaffolding such that other developers can then jump in and implement specific functionality.

The result of this work should be a process which handles DB migration, ingests logs from chain, and responds to query requests (both via WS and through a clean function API from the context of being run in process). The table implementations, log processors, and getters will be incomplete from a total V2 perspective.

**Comment by adrake33** [comment]
Closing this since it was done by Alex's PR, which has been merged.
