### ISSUE TITLE
Transfer funds no longer works

### ISSUE THREAD

**Issue by nuliknol** [AugurProject/augur#8118]
There was an update on the code over the weekend which broke "Transfer funds" functionality. It was working fine on Friday. Here is the screenshot of the error I am seeing when pushing "Send" button:
![transfer_funds_error](https://user-images.githubusercontent.com/1125368/85332925-64f79100-b49e-11ea-924a-36cd41e4086a.png)

**Comment by pgebheim** [comment]
Thanks! Fixing in 8121

We moved all sorts of symbols around so webpack code splitting could work right. If you notice any other issues like this is probably a broken import path in the ui if you'd like to PR (or feel free to just file a ticket).
