### ISSUE TITLE
transaction modal display bug

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#8127]
participation tokens value isn't displayed correctly. It's amount of fees gotten from claiming participation tokens
value should be `151.140431426602343212`

![Screen Shot 2020-06-22 at 8.12.00 PM.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/7cf5755f-c24c-458c-bd63-406c4596b753)

**Comment by Chwy5** [comment]
closing
