### ISSUE TITLE
transaction modal can't search

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#8128]
trying to filter on action results in errors. 

![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/2d85e03e-7c03-4ea9-96bf-dbbeef918624)

to repro
have trades, claim proceeds, claim rep and fees, created markets and try to look them up in transaction modal using the filter

**Comment by Chwy5** [comment]
works - closing
