### ISSUE TITLE
display issue in transactions

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#813]
### Summary
Steps to repro:
1. Make trade on scalar market.
2. Go to Transactions page. 
3. Note that in the display, the outcome id is displayed instead of the price of the scalar market trade.

Screenshot below

![screen shot 2019-01-09 at 9 55 47 am](https://user-images.githubusercontent.com/3970376/50911104-c6d05200-13f4-11e9-9f3d-22e599ca7aa3.png)

better verbiage is:
`SOLD 0.1000 SHARES AT 40.0000 ETH`

issue in add-transactions.js method doesn't know about scalars. 
```
function formatTransactionFillMessage(txType, amount, price, numTxs, outcome) {
  return `${txType === BUY ? "bought" : "sold"} ${amount} Share${
    amount === 1 ? "" : "s"
  } of ${outcome} at ${numTxs > 1 ? "an average price of " : ""}${price}`;
}

```

same issue in notifications:

![screen shot 2019-01-09 at 9 55 33 am](https://user-images.githubusercontent.com/3970376/50911111-c9cb4280-13f4-11e9-82d6-1debbc7956eb.png)

**Comment by Chwy5** [comment]
Should probably say sell .1 shares at @ 40.000 or Sell .1 long shares at 40.0000.....needs different wording, but we didn't sell a share of 1
