### ISSUE TITLE
"Unable To Register At This Time"

### ISSUE THREAD

**Issue by seemqueues** [AugurProject/augur#814]
I have tried registering four different times with four different usernames and each time I get this error, even though Airbitz application clearly accepts my user name because it suddenly becomes unavailable the next time. If I try logging in with my user name, it tells me "Failed to login with PIN."

I have tried using Chrome and I get the errors. I tried using Microsoft Edge, but it loads indefinitely and never goes anywhere.

**Comment by tinybike** [comment]
@paullinator any idea what's going on here?

**Comment by paullinator** [comment]
Yes. We had one last breaking API change which required a server side change. We have it fixed on augur.airbitz.co and will be submitting a pull request this weekend to fix the augur code base.
