### ISSUE TITLE
Users frozen funds breakdown modal

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#8142]
Add an underline to the frozen funds amount figure to indicate it's clickable

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/e6e72c78-cd8c-4628-8001-960dce1b4e67)

This will open the frozen funds modal 

Design for modal (both desktop and mobile):

https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=15832%3A16312

**Comment by matt-bullock** [comment]
On mobile. The modal goes bigger than my phone screen. Needs to add some spacing between top and bottom.

The top and header and footer components look twice the size they should be.

~~Cut market titles off after 2 lines and add ...~~

updated: Cut market titles off after `1` line and add ...

**Comment by pgebheim** [comment]
![image](https://user-images.githubusercontent.com/86010/86024826-53544300-b9e2-11ea-9d74-fa9b6a0aecac.png)
