### ISSUE TITLE
Have report link default to dispute

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#815]
Change default landing page for Reports nav:

in `src/modules/app/components/app/app.jsx` change

```
      {
        title: "Reporting",
        iconName: "nav-reporting-icon",
        icon: NavReportingIcon,
        mobileClick: () =>
          this.setState({ mobileMenuState: mobileMenuStates.FIRSTMENU_OPEN }),
        route: REPORTING_REPORT_MARKETS
      },
```

to route to `REPORTING_DISPUTE_MARKETS`

and change to order of Reporting nav to be
`Dispute`
`Next Dispute`
`Reports`
`Resolved`

Also:
Split out markets in dispute and upcoming dispute.
Remove upcoming reports from Reports page.

This will reduce data per page and speed up loading and help navigation to what users are interested in.

**Comment by pgebheim** [comment]
V2 Reporting entirely different.
