### ISSUE TITLE
Disclaimer should show on first load of market page + Market Creation pg 

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8154]
Sometime the disclaimer pops up randomly when i sign on for the first time.....

I just got it going to add an open order on a market i created, I had already added open orders in other markers and did other txs in this acct (like claiming fees)...

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/d8d35e66-a15e-451c-aded-61684e96a01f)

**Comment by pgebheim** [comment]
Changing this a bit so it should just always occur the first time a market page is loaded.

**Comment by Chwy5** [comment]
Needed for market creation pg too

**Comment by Chwy5** [comment]
fixed - closing
