### ISSUE TITLE
Allow swapping USDC/USDT into Trading Account

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#8155]
A lot of people hold USDC/USDT who may want to trade on Augur. Users should be able to deposit USDC/USDT and have the system automatically swap it for DAI (staying within reasonable slippage etc etc). @matt-bullock Has put together some designs for this.

@Chwy5 @matt-bullock -- are those designs ready for @andrewdamelio to take a look?

Requirements:
- [x] Users with USDC or USDT should be presented with option to deposit it during onboarding (like we do for DAI)
- [x] Users should be given the option to swap USDC/USDT in add funds modal
- [x] Users holding USDC or USDT should be given the option to deposit it from account modal [ if this works design wise ].
- [x] First implementation can be on top of Uniswap [https://github.com/AugurProject/augur/pull/8293]
- [ ] Second implementation should work on top of 1inch.exchange to give users the best possible slippage on larger deposits. We will need to intelligently figure out the costs of this, if possible.

**Comment by matt-bullock** [comment]
Designs are here https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=2547%3A11814

**Comment by Chwy5** [comment]
added - closing
