### ISSUE TITLE
Transaction Modal missing open orders -bug

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8157]
To reproduce (need multiple pg worth of items

create open orders and other transactions to fill up multiple pages.

1) goto Account Summary page and open Transactions modal
2) Click pg 2, watch all tx update
3) change All to Open in Actions dropdown, click search

doesnt show any open orders even though I have....

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/976acc89-ce74-4cf2-aded-7fe3c50d4bc5)

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/77868c18-6433-42c0-baf7-e7d72e3d6c7f)

**Comment by bconfortin** [comment]
Confirmed. It's not setting the page to 1 when doing a search, even if it seems like it's in page 1.

**Comment by Chwy5** [comment]
fixed -closing
