### ISSUE TITLE
Markets available for dispute are not appearing in the dispute UI

### ISSUE THREAD

**Issue by nuevoalex** [AugurProject/augur#8162]
Markets which are available for disputing do not appear in the "Markets In Dispute" page anymore.

![dispute_1](https://user-images.githubusercontent.com/3839700/85623460-4d92e200-b61d-11ea-9037-196175cad20b.png)

One oddity is that if I have dispute stake in a market and check the box to "only" show markets in my portfolio the non warp-sync one does appear:

![dispute_2](https://user-images.githubusercontent.com/3839700/85623516-626f7580-b61d-11ea-98b1-d33cce117362.png)

**Comment by matt-bullock** [comment]
showing up now. closing
