### ISSUE TITLE
Display The Potential Total P/L if an Outcome Occurs

### ISSUE THREAD

**Issue by stephensprinkle** [AugurProject/augur#817]
Once a user places a trade, that position is displayed on the market page.

Currently absent from the data presented in this table is the maximum possible profit or loss of a specific position (based on purchase price(s)).

Please add two columns:
Potential Profit
Potential Loss

These values should update with state and match the styling of the existing table.

![max-p-l](https://cloud.githubusercontent.com/assets/287003/21233862/0a52711a-c2ae-11e6-81ce-9c07046bd50b.png)

A good jumping off point to help point you in the right direction would be to start here: https://github.com/AugurProject/augur/blob/master/src/modules/market/components/market-positions.jsx

All the relevant selectors + state you’ll need to manipulate should be referenced within the above component, as well as within the `market-positions-row` file.

**Comment by tinybike** [comment]
Moved to CH
