### ISSUE TITLE
(On local branch) Logo Updates + web app manifest (to be done just prior to release)

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#8175]
- [x] Web app manifest https://www.figma.com/file/31ISKCwagskMIE8pHM1FNH/Social-Media-Icons?node-id=2%3A89

- [x] Favicon https://www.figma.com/file/31ISKCwagskMIE8pHM1FNH/Social-Media-Icons?node-id=77%3A0

- [x] Logo in topbar https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=15828%3A805

- [x] Logo in REP section of Your overview in account summary https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=15746%3A151709

- [x] Logo in mobile menu https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=15671%3A0

**Comment by bconfortin** [comment]
Changes are complete in my local branch, `bruno/logo-8175`.

**Comment by matt-bullock** [comment]
@bconfortin have you updated the web app manifest? I'm still seeing the incorrect one. Should be using this:

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/f0bd1be3-8e7d-4852-b79c-e39f19fd1a00)
