### ISSUE TITLE
Market Creation Form Hangs on Keypresses

### ISSUE THREAD

**Issue by nuevoalex** [AugurProject/augur#8177]
When typing normally in the market creation textareas the UI will hang. This is because there is an onChanged handler for the form which calls "updateNewMarket" which takes ~200msec per call.

We should either make this not so expensive or call "updateNewMarket" much less frequently

**Comment by Chwy5** [comment]
It is also effecting the dropdowns in the market creation....big delay

**Comment by Chwy5** [comment]
seems much faster now
