### ISSUE TITLE
Trading page redesign: Candlestick charts

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#820]

**Comment by justinbarry** [comment]
See: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign

Note: Please look at master component for specific styling/ux direction. The instances in the full page mockups are not exact.

**Comment by adrake33** [comment]
As per https://app.zenhub.com/workspaces/augur-5bfed3424b5806bc2bf8d173/issues/augurproject/augur/793, there may also be some styling/formatting changes needed for this chart on mobile, so please verify how the chart looks on mobile and make any necessary changes.

**Comment by bthaile** [comment]
This is done
