### ISSUE TITLE
Financial template Event expiration bug

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8200]
For all financial templates, wrong event expiration time appears
shows incorrect on market trading pg as well

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/65312df9-cbc6-45cb-bccf-64d4d100b278)

**Comment by Chwy5** [comment]
looks good for me, want @matt-bullock

**Comment by matt-bullock** [comment]
These look correct to me now on the market page. Still seeing conversion errors in the market creation which Tom's working on a fix for
