### ISSUE TITLE
Global Chat not working

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8203]
I cant get my message on the global chat board....is it missing an enter button

Is this by design it works if I hit enter on my keyboard

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/5b56a47e-ae7d-4382-bfbd-932b200f2ec7)

**Comment by pgebheim** [comment]
![image](https://user-images.githubusercontent.com/86010/86025359-f0af7700-b9e2-11ea-8f23-4710082c7ccc.png)

working for me here.

**Comment by pgebheim** [comment]
oh yes, it's by design :-D
