### ISSUE TITLE
The outcome_value_timeseries table should potentially be initialized on market creation for that market

### ISSUE THREAD

**Issue by nuevoalex** [AugurProject/augur#823]
Currently until an outcome is traded on there is no value for it in the outcome values timeseries table. 
Instead on market creation the value of each outcome could be assumed to be 1/numOutcomes.

We should decide if we want such a change.

**Comment by joeykrug** [comment]
Is this for pricing? I would value them at `-` until a trade takes place

**Comment by joeykrug** [comment]
was this done?
