### ISSUE TITLE
Test: Google Translate

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#8240]
@bconfortin -- Can you try google translate to verify its still working?
- [x] Does google translate appear on the page when your browser is set to Brazil / Portuguese?
- [x] Does it properly find the text of the market title / description / outcomes to translate?

**Comment by bconfortin** [comment]
It works. When I enter v2, this popup shows up, asking if I want to translate.
Note: it's translating Augur's logo. With a SVG logo, that won't happen.

![Captura de Tela 2020-06-30 às 15 46 22](https://user-images.githubusercontent.com/10351013/86164936-f2636280-bae8-11ea-812f-0f0205400e03.png)

**Comment by pgebheim** [comment]
Amazing thanks @bconfortin
