### ISSUE TITLE
Update copy of logged out hero banner

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#8242]
https://www.figma.com/file/Do4qnkCNM8P7lwBmCdYZCS4X/Market-List-Page?node-id=3829%3A31715

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/5de6b0d9-e34c-4ec6-9fd7-639d01a99e04)

**Comment by Chwy5** [comment]
fixed - closing
