### ISSUE TITLE
User should be able to build Augur and get it pinned to IPFS with a single script

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#8250]
This can be a shell script or make file that runs yarn commands + ipfs commands. All pre-requisites should be checked within the script.

## Goal 1: Source build -> Pinned Augur with optional DNS link

The goal is someone just downloading the monorepo source .zip file can run `make ipfs-publish` and it will do the necessary things to work. Caveat -- any needed dependencies should be errors that this process spits out. The output of this command should be an IPFS link that the user has pinned.

## Goal 2: Simplify Docker
Secondly, we should check our current build process, remove all unneeded docker images and just supply one docker image with is: Augur source + all dependencies needed to build it.

This would allow someone to do the following 
```docker run augurproject/augur --entrypoint='./ipfs-publish```
with the proper environment set and it would 

(more coming)

**Comment by robert-e-davidson3** [comment]
Goal 1 is accomplished.

**Comment by robert-e-davidson3** [comment]
I don't see us doing more work on this. @Chwy5 or @pgebheim reopen if I am wrong.
