### ISSUE TITLE
Additional crypto template list

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8252]
@matt-bullock need additional graphics for boxes

SEE Grouping in Design chat

Under `Crypto` category:
BTC, ETH, REP
MKR, COMP, BAL
ZRX, LINK, OTHER(Additional)

rest under `Additional`

![image](https://user-images.githubusercontent.com/3970376/86359315-7414d680-bc36-11ea-8528-822d2fa6a173.png)

**Comment by matt-bullock** [comment]
All icon SVGs can be found here under 'Crypto'
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=15700%3A50

**Comment by Chwy5** [comment]
added -closing
