### ISSUE TITLE
Liquidity message clarification 

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#8254]
Change `good` to `sizeable` and highlight it

![image](https://user-images.githubusercontent.com/3970376/86171227-0788c300-bae2-11ea-8ce6-afab8271753d.png)

**Comment by bthaile** [comment]
we don't have a highlight specific word in that text component. How about a better message that changes if user has liquidity but it's not sizeable. 
![image](https://user-images.githubusercontent.com/3970376/86241080-eb2f6980-bb67-11ea-9621-95a5f1ab5044.png)

**Comment by Chwy5** [comment]
k - closing
