### ISSUE TITLE
Trading Page: Order Ticket

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#826]
Desktop Prototype: https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=342%3A34455
Mobile Prototype (under m_orderType/buy & m_orderType/sell): https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=1496%3A6663

This task is referring to the section for buying & selling shares:
![Screen Shot 2019-01-11 at 8.48.57 AM.png](https://images.zenhubusercontent.com/5bff29dc5cb43a45a18add9f/06976c15-9b10-4fe5-880e-b0c851be2e30)

Desktop:
- [x] Empty, Active State, & Logged Out states should be implemented as per the orderTicket section of the design spec.
- [x] Quantity, Limit Price (Scalar)/Outcome (Categorical), & Total Order Value should show units in a new section to the right of the textbox.
- [x] Tooltip should be added to the New Position section. (Final verbiage provided by chwy below.) The mocks also show a tooltip in the Close Position section, but chwy said this is not needed and should not be implemented.
- [x] Insufficient Funds error should be shown as per spec when user does not have enough ETH to complete trade.
- [x] For Categorical Markets, Outcome dropdown should be added to Order Ticket section.
- [x] The New Position section should show how many shares the user will be long or short (and at what cost) by placing this trade, as well as their max profit/loss.
- [x] The Close Position section should be displayed if placing this trade will result in an existing position being closed.

Mobile:
- [x] When clicked on, the "Buy / Sell" button should bring up an order form modal.
- [x] At the top of the modal, the user can toggle between buying and selling. It would be nice to animate the position of the toggle "pill", but not necessary if this takes too much time.
- [x] The currently selected outcome should be displayed in the outcome select element, if one is already selected. Just like the other outcome select element, if clicked this should bring up the outcome list modal.
- [x] A short version of the order book is displayed under the select element. Styles should match whatever is done on the other mobile version of the order book; the only difference is the number of orders immediately visible. The order book should be internally scrollable. Clicking on an order in the order book should populate the form below.
- [x] Add the order form. This should contain the same elements and fields as is used on Desktop. The "Place Sell Order" / "Place Buy Order" button should live at the bottom of the form, and is not fixed to the bottom of the browser.

**Comment by adrake33** [comment]
The tooltip text is still pending. @matt-bullock is still waiting to hear from @Chwy5  what this should be. Please confirm with Matt/chwy that the tooltip text has been finalized before creating a PR for this.

**Comment by Chwy5** [comment]
For Binary and Categorical markets use what was in the mock ups....(Depends on if buying or selling)

"This means you believe (outcome) has a (higher, lower) than (limit price converted to %) chance of happening"

For scalar markets use (depending if buying or selling):

"This means you believe the result will be (less, greater) than (purchase price)(denomination)"

**Comment by bthaile** [comment]
error state

![screen shot 2019-01-11 at 12 35 40 pm](https://user-images.githubusercontent.com/3970376/51052805-6f211a80-159d-11e9-94a3-56f3968f350d.png)

**Comment by bthaile** [comment]
tooltip change in trading--confirm.jsx
user believes Yes will not happening by % (profit %) 
***Higher if you are buying and Lower if you are selling

```
Going long binary “You believe this event has a greater than % chance to occur”
Going short binary “You believe this event has a less than % chance of occurring”
(cats) **For cats can do similar but instead of this event it’s {outcome name}
(scalar) you believe the outcome of this event will be higher or lower than {number} denomination
```

**Comment by joeykrug** [comment]
What's status of this?

**Comment by bthaile** [comment]
Just needs to be verified by chwy.

**Comment by Chwy5** [comment]
Confirmed changes...closing ticket
