### ISSUE TITLE
MarketCreated fails to roll back when blockchain reorg happens

### ISSUE THREAD

**Issue by Troublor** [AugurProject/augur#8260]
**Describe the bug**

When market creation succeeds (market create transaction has been mined), some useful data is stored in Rollback datastore of IndexedDB. But if user refreshes the page, all data in Rollback datastore is lost, which induces a bug that the market creation cannot be rolled back when blockchain reorganisation happens. 

**To Reproduce**
1. start Augur development environment by running geth node at localhost. 
2. create a market in Augur-ui and send transaction to blockchain. 
3. mine blocks to make the transaction succeed.
4. The market should be successfully created now. Refresh the web page. (Rollback datastore contains nothing after refresh)
5. use another geth node to make block reorganise, and the previous transaction is reverted back to txpool.
6. The created market is not rolled back and stays in IndexedDB although it is already invalid.

**Expected behavior**
The data in Rollback datastore of IndexedDB should be persistent when the page is refreshed. 

**Screenshots**
![Screenshot 2020-07-01 at 17 18 59](https://user-images.githubusercontent.com/14846504/86226940-f5c91d80-bbbe-11ea-9c1d-6c341817d1eb.png)
![Screenshot 2020-07-01 at 17 17 35](https://user-images.githubusercontent.com/14846504/86226807-c3b7bb80-bbbe-11ea-8069-7831878585f1.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome

**Comment by nuevoalex** [comment]
Hey @Troublor ! Thanks for the report.

I confirmed this is an issue. The mistake is really that we do a bulk sync operation to the most current block provided when initially starting up which won't repopulate the rollback data.

That said I think rather than slow down initial processing we may as well just keep the Rollback table like you suggest since it gets pruned regularly anyway and doesn't really store that much.

**Comment by pgebheim** [comment]
@nuevoalex Can you confirm we roll back enough blocks on initial sync as well? I have a memory of seeing somewhere in the code where we actually don't roll back on initial sync to account for reorgs at the point of shut down. I.e. the code is there to do it but we roll back 0 blocks.

**Comment by nuevoalex** [comment]
@pgebheim IIR that was an issue where we would actually delete the entire DB in anticipation of a warp sync file so we'd roll back correctly then have nothing to rollback.
