### ISSUE TITLE
Markets wont load

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8262]
Markets wont load when i come to V2, seeing these errors (could be a sleep mode issue)

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/0c7b9eb8-2bfb-40c7-a1e4-2842aed34bc2)

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/3c746084-3a66-491d-8ba6-09140e48b40d)

**Comment by pgebheim** [comment]
Alex's patch that landed last night needs a delete of augur-* IndexedDB

**Comment by Chwy5** [comment]
closing
