### ISSUE TITLE
Get Echidna working with Augur Contracts

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#8289]
- [ ] Make contracts build with truffle
- [ ] Run contracts through echidna

**Comment by pgebheim** [comment]
This is a dead end because of the truffle build -- @robert-e-davidson3 I've moved this out of 2.0 and wanna leave it open can you connect it to the truffle issue you file?

**Comment by robert-e-davidson3** [comment]
Possibly impossible with truffle today. I get a JSON error that someone has associated with contract size.

In `packages/augur-core`, run `yarn node --max-old-space-size=12288 ./src/tools/truffle-compile.js`.

Draft PR with changes I made: [https://github.com/AugurProject/augur/pull/8392](https://github.com/AugurProject/augur/pull/8392)

- I'm getting this error: [https://ethereum.stackexchange.com/questions/78113/solc-compiler-related-error-in-nodejs](https://ethereum.stackexchange.com/questions/78113/solc-compiler-related-error-in-nodejs)

    ```
    * Line 1, Column 1
      Syntax error: value, object or array expected.
    * Line 1, Column 2
      Extra non-whitespace after JSON value.

    Compilation failed. See above.
    Truffle v5.1.33 (core: 5.1.33)
    Node v10.21.0```
    ```

- We also have to rename some contracts: [https://github.com/trufflesuite/truffle/issues/387](https://github.com/trufflesuite/truffle/issues/387)

    ```
    robertdavidson@MacBook-Pro-3 augur-core % find . -name '*.sol'|xargs egrep '^contract '|awk '{print $2}'|wc -l
         291
    robertdavidson@MacBook-Pro-3 augur-core % find . -name '*.sol'|xargs egrep '^contract '|awk '{print $2}'|sort -u|wc -l
         269
    ```

**Comment by robert-e-davidson3** [comment]
https://github.com/trufflesuite/truffle/issues/3164

**Comment by robert-e-davidson3** [comment]
I doubt this is worth the effort since it seems to be a truffle bug in handing immense solidity codebases. We may be the only team that hits this issue. But I'll leave it open in case we want to find a workaround.
