### ISSUE TITLE
Category Stats Data Isn't Refreshing Cache

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8295]
I created an Augur (rep/usd) price crypto market, which I see on the market list pg....but data doesnt show up in templates....possible caching issue?

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/5379d69d-1a47-48c4-b1b0-1cd2cff23d10)

**Comment by Chwy5** [comment]
still not updating for me....

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/89924587-e5c3-4910-b06f-b94753576416)

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/fd19a04c-265a-44b3-9d09-b2f5db69bc91)

**Comment by Chwy5** [comment]
Still not seeing this....

I see 0 markets for compund in the crypto list....but i see the compound market on the market list pg i created

market?id=0x06c9d0F87CD66Bd29f047941570F4a6bedBd93A0

**Comment by bthaile** [comment]
I've not been able to repro this bug.  Recent change fixes category counts on market list page but shouldn't effected category stats getter.

v2.augur.net has different values for categoryStats and market listing category counts.

![image](https://user-images.githubusercontent.com/3970376/86847037-5948c480-c071-11ea-9480-837a6e374aec.png)


![image](https://user-images.githubusercontent.com/3970376/86847056-5d74e200-c071-11ea-96e9-900045d2f6dc.png)


will continue to investigate

**Comment by matt-bullock** [comment]
tested and is working now
