### ISSUE TITLE
React complains about memory leak

### ISSUE THREAD

**Issue by nuliknol** [AugurProject/augur#8297]
While filling orders I have got a memory leak warning from React.
Local testnet setup, with sources pulled about 2 hours ago.
The error on the left side of the screen (the popup) is a different error (with a separate Github issue), not related to this bug I am reporting. I am only reporting memory leak, but I did start taking screenshots from the beginning of everything.

The error is:
```
webpack:////home/niko/eth/dev/augur/node_modules/react-dom/cjs/react-dom.development.js?:545 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Media (created by AccountView)
    in AccountView (created by Connect(AccountView))
    in Connect(AccountView) (created by Route)
    in Route (created by withRouter(Connect(AccountView)))
    in withRouter(Connect(AccountView)) (created by Route)
warningWithoutStack @ webpack:////home/niko/eth/dev/augur/node_modules/react-dom/cjs/react-dom.development.js?:545

```

```
react-dom.development.js:545 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in Candlestick (created by Media)
    in ModulePane (created by Media)
    in div (created by ModuleTabs)
    in div (created by ModuleTabs)
    in ModuleTabs (created by Media)
    in Media (created by MarketChartsPane)
    in MarketChartsPane (created by Connect(MarketChartsPane))
    in Connect(MarketChartsPane) (created by Route)
    in Route (created by withRouter(Connect(MarketChartsPane)))
    in withRouter(Connect(MarketChartsPane)) (created by Media)
    in div (created by Media)
    in div (created by Media)
```

This is a single screenshot made from many subshots, since I have a long console.log

![memory_leak_shot1](https://user-images.githubusercontent.com/1125368/86479485-e1e20080-bd11-11ea-9fb7-839ad6749997.png)
![memory_leak_shot2](https://user-images.githubusercontent.com/1125368/86479503-ec9c9580-bd11-11ea-99d9-0252d5117283.png)
![memory_leak_shot3](https://user-images.githubusercontent.com/1125368/86479515-f0301c80-bd11-11ea-8139-e7814db31c91.png)
![memory_leak_shot4](https://user-images.githubusercontent.com/1125368/86479522-f32b0d00-bd11-11ea-99d1-b9224d9e3691.png)

**Comment by pgebheim** [comment]
@bthaile -- Looks like perhaps this error coming back from MM provider got the ui out of sync and thus the component was never rendered?
