### ISSUE TITLE
Reporting Only UI

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8306]
1) Disable Trading Button
2) Pop up Message Modal
3) If Go to market pop up disclaimer (should be getting changed already)
4) If person goes to Scalar:
     A)  Pop up message modal upon arriving
     B)  Disclaimer, when entering scalar market
     C)  Scalar modal

**Comment by bthaile** [comment]
Need to copy kovan.json contents to new reporting.json instead of default.json

**Comment by Chwy5** [comment]
I am getting a formatic Pop up box (see screenshot)

should I be getting this here?

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/7259a037-bc8c-4e95-8756-8fe6fbda4d08)

**Comment by Chwy5** [comment]
closing - working properly
