### ISSUE TITLE
The Preview window shows a Market Trading Fee of 199%  instead of 2.00%

### ISSUE THREAD

**Issue by motteman** [AugurProject/augur#8310]
The Preview Window shows a Market Trading Fee of 199%  instead of 2.00%

I created a binary market with the recommended 2% market trading fee.

The preview window shows a Market trading fee of 199%.
Once approved, the Market Details and the summary of the market show the correct percentages.

Desktop: MacOS Catalina 10.15.5

<img width="1329" alt="Screenshot 2020-07-04 15 32 11" src="https://user-images.githubusercontent.com/8846514/86520702-f0f9a900-be0c-11ea-88f0-906478ca4877.png">
<img width="726" alt="Screenshot 2020-07-04 15 32 16" src="https://user-images.githubusercontent.com/8846514/86520705-f5be5d00-be0c-11ea-8236-7aeaaa8487b4.png">
<img width="1000" alt="Screenshot 2020-07-04 15 38 06" src="https://user-images.githubusercontent.com/8846514/86520706-f5be5d00-be0c-11ea-9a6b-2607822eced9.png">

**Comment by pgebheim** [comment]
@bthaile Displaying 199% instead of 1.99% and also not including the reporting fee in this view.

**Comment by Chwy5** [comment]
fixed - closing
