### ISSUE TITLE
Orders/trades failing using formatic

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8318]
![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/f63bbf87-b5be-4d3e-a1e8-669046f02a07)

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/b7b025bc-c5f0-4d93-a668-737e03d66fed)

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/0669a8d4-8574-4e85-8436-ba78a6f0a3d4)

**Comment by bthaile** [comment]
I'm not able to login with formatic. I don't get a code sent to my phone.
Tested with MM and tor.us was able to trade and create orders. 
can you re-test

**Comment by Chwy5** [comment]
@andrewdamelio saw it too and was reaching out to formatic

**Comment by andrewdamelio** [comment]
looks like Fortmatic was updating their provider stuff on the backend causing this outage.

I'm in the process of create some Ghost Inspector tests (Using Fortmatic) so we can catch these issues in the wild quicker.

**Comment by Chwy5** [comment]
fixed - closing
