### ISSUE TITLE
Reskin: Connect a Wallet

### ISSUE THREAD

**Issue by sharkcrayon-augur** [AugurProject/augur#832]
Design: https://www.figma.com/file/c7Yck1ciNsfd0HydNvM4OGRj/Old-Design---ReSkin?node-id=0%3A3321

View the "Create/Connect Account" page within the above design file. One of the connect dropdowns has been restyled to provide guidance.

- [ ] Update the general dropdown styles, including hover states and the logout dropdown item.
- [ ] Update error message styling for failed connection attempts. (Matt may need to provide design for this if he hasn't already)
- [ ] Update derivation path selection styling if needed.

![image](https://user-images.githubusercontent.com/46331128/51058057-caa2d680-15a4-11e9-926b-17c791734fb6.png)

**Comment by joeykrug** [comment]
Don't lose the current ordering of edge first + explainer sentence about username + pass
