### ISSUE TITLE
min quanity 10 for Scalar pre-liq order entry bug

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8325]
Creating a scalar crypto market for OMG (Range 0-3) I shouldnt get a quantity multiples box

![image](https://user-images.githubusercontent.com/3970376/86814543-2be72100-c047-11ea-9232-a01b6b27a6a4.png)

**Comment by bthaile** [comment]
`I shouldnt get a quantity multiples box` not sure what that means and your images aren't showing up in description

looks like that is the "feature" for min quantity of 10. so no bug.

**Comment by Chwy5** [comment]
It only seems to trigger if the range is 0-less than 10

**Comment by Chwy5** [comment]
not a bug closing
