### ISSUE TITLE
Trade history is missing

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8327]
![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/dad9abd7-0506-4159-aed0-b588aa2e7dde)

**Comment by Chwy5** [comment]
I needed to manually refresh the pg after 5 mins to get the trade history to appear

**Comment by bthaile** [comment]
@Chwy5  need a scenario. not enough information to do anything

**Comment by Chwy5** [comment]
Screenshots not working...shouldve showed it

Do an actual trade.....after it is completed the trade history(under the order book) on the market pg does not update....I need to refresh the pg for it to show up

**Comment by bthaile** [comment]
verified that UI is calling getter but the same payload is returned. so market trade history doesn't show the new trade.  I told Alex about it.

Looks to be a caching issue.

**Comment by Chwy5** [comment]
Trade history still not working....My fills is 

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/7d12fd0b-a193-4c55-8cee-6c79477164c8)

**Comment by matt-bullock** [comment]
Seeing issues with this. Lots of delay between order being confirmed and appearing in the trade history. One order wasn't showing up after a few minutes so I left the market and came back and much of my previous trade history had vanished. You can see from my bell alerts that there should be a lot more trades on Jul 10

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/4e8569d7-9f7b-4b9c-bddf-2ebd689eb2fd)

**Comment by matt-bullock** [comment]
Tested and working correctly now
