### ISSUE TITLE
Crossed Orderbook not trading

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8328]
There is a crossed orderbook made from 2 speperate accts

I am in a 3rd acct and can trade both sides of the book...but Accts 1 and 2 shouldve traded

Dot is green, refreshing doesnt fix block behind is 4

![image.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/68ddbaaa-9100-46cf-a028-572d2afc0815)

**Comment by bthaile** [comment]
@pgebheim are we going to going to do anything to address this issue?

**Comment by bthaile** [comment]
approach:
1. filter cross order
 a) smallest size
 b) filter oldest

2. allow Post Only orders, if open order would not cross the book.

**Comment by Chwy5** [comment]
working-closing
