### ISSUE TITLE
Go program has already exited

### ISSUE THREAD

**Issue by nuliknol** [AugurProject/augur#8334]
This error ocurrs at random, I can't find any pattern for reproduction. Shown after creating an order (new order, not filling existing order)

![go_program_exited](https://user-images.githubusercontent.com/1125368/86698712-294be380-bfd5-11ea-97f3-5c39968e22a5.png)

No errors on console either. Maybe adding error code in the sources would help tracking.
The config used is for Local test net, sources as of today.

**Comment by pgebheim** [comment]
@justinbarry -- see if you can repro this?

**Comment by justinbarry** [comment]
Can do.

**Comment by nuliknol** [comment]
With today's sources I can see this new error in console log

![go_program_exited](https://user-images.githubusercontent.com/1125368/87333456-bfff2f80-c502-11ea-9be7-37de4b94fb6a.png)

@justinbarry 
@pgebheim

**Comment by justinbarry** [comment]
My first guess is a memory thing but @albrow might have more insight.

**Comment by albrow** [comment]
"Go program has already exited" is usually just a symptom of a different underlying problem. Can you enable Mesh logging and share the log output?

**Comment by justinbarry** [comment]
@nuliknol We just upgraded to a new version of 0x mesh this week. Please reopen if this re-occurs.
