### ISSUE TITLE
Reskin: Create Market Form

### ISSUE THREAD

**Issue by sharkcrayon-augur** [AugurProject/augur#834]
Design: https://www.figma.com/file/c7Yck1ciNsfd0HydNvM4OGRj/Old-Design---ReSkin?node-id=0%3A3321

View the "Create Market" page within the above design file.

Much of this will probably come for free from the other site-wide style changes that have already been made.

- [ ] Adjust styles for the market card if needed. (Ignore the huge space at the bottom of the market card below the volume, fee, and end date stats - this is currently a mistake in the design.)
- [ ] Active button states should be the bright blue that Matt has been using around the rest of the site.
- [ ] Review the form for any further font style, color, etc changes that are needed.

**Comment by joeykrug** [comment]
When doing this, let's go ahead and add in a tooltip or info that states that if a resolution source is used, the url needs to be specific and ideally the market has extra details which say something about how to use that source. It's important to use a source that is specific and has consistent results no matter where it is accessed from that is the same across timezones

**Comment by adrake33** [comment]
The tooltip text for this could say something like: "A market's resolution source should be a specific URL that provides consistent results across all timezones. Ideally, the market description should provide details for how to use this source."

**Comment by joeykrug** [comment]
Sounds good

**Comment by joeykrug** [comment]
Another thing to add while doing this that'll solve a bunch of issues, when someone creates a categorical market, add a note that they should cover all potential outcomes, and possibly add an "other" outcome

**Comment by adrake33** [comment]
Yeah, that's a good idea. Let's add this as a paragraph above the Potential Outcome textboxes: 

```To reduce ambiguity, categorical markets should cover all possible outcomes. This can be done by including an outcome such as "Other."```
