### ISSUE TITLE
ProfitLossChanged event is reporting incorrect values

### ISSUE THREAD

**Issue by nuliknol** [AugurProject/augur#8364]
**Bug**: 
ProfitLossChanged event emitted by ProfitLoss contract is sending incorrect values for `RealizedProfit` and `RealizedCost` fields at certain conditions.

**Steps to reproduce**:

Using two accounts create the the following sequence of orders.

Example Account Addresses we used:

Account 1
EOA: 0xB00084262F130F389D2F524bEE88fb96089065D1
Wallet contract: 0x87b0C7224eCeA9F0367183576Ce4405346AB5Cff

Account 2
EOA: 0x1b2E85De21C7CF4bD1787c6Ac4bd505e83b62Ba5
Wallet contract: 0x2011AEdc2a23AA4863C1eBF7aEe890Cce945e135

Steps:
```
Step 1.

Account 1: Creates SELL order of Yes for 100 shares at 0.30
Account 2: Fills Account's 1 order (BUY 100 Yes shares at 0.30)

Step 2.

Account 2: Creates SELL order of Yes for 100 shares at 0.61
Account 1: Fills Acount's 2 order (BUY 100 Yes shares at 0.61)

Step 3.

Account 1: Creates SELL order of Yes for 100 shares at 0.45
Account 2: Fills Account's 1 order (BUY 100 Yes shares at 0.45)
```

For easier verification this test case was reproduced on Kovan's network, with the following market:
https://v2.augur.net/#!/market?id=0x79414c49dcEEeDB33bd6C48C69cb8e9eC24bC586

**Problem**:
First two orders report correct values in `ProfitLossChanged` event, but at the third order, the values are duplicated from previous order, therefore reporting incorrect profit/loss values for `RealizedProfit` and `RealizedCost` fields.

**Supporting information**:
Here is the data of the events in text format, after parsing Ethereum event logs:
Events are received in this order:

First order:
```
INFO: 23:50:53 ProfitLossChanged event found (block=19469330) :
ProfitLossChanged {
        Universe: 0xF821ec5a7bC0cFf05dBE10C741a19CF673b1cF4B
        Market: 0x79414c49dcEEeDB33bd6C48C69cb8e9eC24bC586
        Account: 0x87b0C7224eCeA9F0367183576Ce4405346AB5Cff
        Outcome: 2
        NetPosition: -1000000000000000000
        AvgPrice: 30000000000000000000
        RealizedProfit: 0
        FrozenFunds: 70000000000000000000000000000000000000
        RealizedCost: 0
        Timestamp: 1594165840
}
INFO: 23:50:53 ProfitLossChanged event found (block=19469330) :
ProfitLossChanged {
        Universe: 0xF821ec5a7bC0cFf05dBE10C741a19CF673b1cF4B
        Market: 0x79414c49dcEEeDB33bd6C48C69cb8e9eC24bC586
        Account: 0x2011AEdc2a23AA4863C1eBF7aEe890Cce945e135
        Outcome: 2
        NetPosition: 1000000000000000000
        AvgPrice: 30000000000000000000
        RealizedProfit: 0
        FrozenFunds: 30000000000000000000000000000000000000
        RealizedCost: 0
        Timestamp: 1594165840
}
```
Second order:
```
INFO: 23:53:13 ProfitLossChanged event found (block=19469359) :
ProfitLossChanged {
        Universe: 0xF821ec5a7bC0cFf05dBE10C741a19CF673b1cF4B
        Market: 0x79414c49dcEEeDB33bd6C48C69cb8e9eC24bC586
        Account: 0x2011AEdc2a23AA4863C1eBF7aEe890Cce945e135
        Outcome: 2
        NetPosition: 0
        AvgPrice: 0
        RealizedProfit: 30216100000000000000000000000000000000
        FrozenFunds: 0
        RealizedCost: 30000000000000000000000000000000000000
        Timestamp: 1594165988
}
INFO: 23:53:13 ProfitLossChanged event found (block=19469359) :
ProfitLossChanged {
        Universe: 0xF821ec5a7bC0cFf05dBE10C741a19CF673b1cF4B
        Market: 0x79414c49dcEEeDB33bd6C48C69cb8e9eC24bC586
        Account: 0x87b0C7224eCeA9F0367183576Ce4405346AB5Cff
        Outcome: 2
        NetPosition: 0
        AvgPrice: 0
        RealizedProfit: -32226100000000000000000000000000000000
        FrozenFunds: 0
        RealizedCost: 70000000000000000000000000000000000000
        Timestamp: 1594165988
}
```

Third order:
```
INFO: 00:03:00 ProfitLossChanged event found (block=19469476) :
ProfitLossChanged {
        Universe: 0xF821ec5a7bC0cFf05dBE10C741a19CF673b1cF4B
        Market: 0x79414c49dcEEeDB33bd6C48C69cb8e9eC24bC586
        Account: 0x87b0C7224eCeA9F0367183576Ce4405346AB5Cff
        Outcome: 2
        NetPosition: -1000000000000000000
        AvgPrice: 45000000000000000000
        RealizedProfit: -32226100000000000000000000000000000000
        FrozenFunds: 55000000000000000000000000000000000000
        RealizedCost: 70000000000000000000000000000000000000
        Timestamp: 1594166572
}
INFO: 00:03:00 ProfitLossChanged event found (block=19469476) :
ProfitLossChanged {
        Universe: 0xF821ec5a7bC0cFf05dBE10C741a19CF673b1cF4B
        Market: 0x79414c49dcEEeDB33bd6C48C69cb8e9eC24bC586
        Account: 0x2011AEdc2a23AA4863C1eBF7aEe890Cce945e135
        Outcome: 2
        NetPosition: 1000000000000000000
        AvgPrice: 45000000000000000000
        RealizedProfit: 30216100000000000000000000000000000000
        FrozenFunds: 45000000000000000000000000000000000000
        RealizedCost: 30000000000000000000000000000000000000
        Timestamp: 1594166572
}
```
The problem is that on Second order (right after the order is processed) both Accounts don't have any open positions (their positions were closed because they sold shares against each other), and when the third order comes in, a complete set of shares is created and the funds become frozen, but at the same time there is a report of Realized Profit. The error is that at this point there can't be any profit because the Accounts just opened positions at this transaction.

Here are the screenshots of EtherScan illustrating the events, and showing the errors
![etherescan_profit_loss_event_first_order](https://user-images.githubusercontent.com/1125368/86862368-adae6d00-c08e-11ea-9938-3d1665558b6c.png)
![etherescan_profit_loss_event_second_order](https://user-images.githubusercontent.com/1125368/86862381-b1da8a80-c08e-11ea-8da1-a34bef087331.png)
![etherescan_profit_loss_event_third_order](https://user-images.githubusercontent.com/1125368/86862385-b3a44e00-c08e-11ea-8089-6ccdd5fc97e5.png)

Links to Etherscan:
Order 1: https://kovan.etherscan.io/tx/0x17617f13f3229876eb612829649bcee4cd182bd87853d4a0c6881879031aff6c#eventlog
Order 2: https://kovan.etherscan.io/tx/0x0ebe1201c5f3c052b9cdb9de041c5c1e5e884fb0155ebe81ba22f194b445dc2c#eventlog
Order 3:  https://kovan.etherscan.io/tx/0x1c3bc9990e55962a3bdb49a7f59a6fe203a445eb28c832cdc42bb1f5b126acfe#eventlog

The existence of this problem, makes ProfitLossChanged event unreliable for tracking the changes in User's accounts so (in order to decide how to solve it for our own project) we would like to know if this is going to be fixed before July 28 (Augur's contract deployment date) ?

Thank you very much in advance.

**Comment by pgebheim** [comment]
Your profit and loss is calculated across all trades of an outcome in a market. It's not an *instantaneous* metric, its aggregate. So in this case the account opens a position but it still has a realized profit from their previous closed position for that outcome. In your example this is clearly shown, since Account 1 and 2 both maintain their previous RealizedProfit values on the 3rd trade while the other values in the log change (notably, frozenFunds)

This is by design because of how the reference UI needs to efficiently show profit and loss over time. In order to do this without fetching *all data* for a user, UIs need to be able to simply look at a range of logs and plot it, this is what the ProfitLossChanged events are designed to handle.
