### ISSUE TITLE
Page gets stuck when disputing

### ISSUE THREAD

**Issue by Troublor** [AugurProject/augur#8393]
**Describe the bug**
The web page got stuck when trying to dispute other outcomes for markets in dispute phase. 

**To Reproduce**
1. Go to `DISPUTING` page
(I use the default market `High temperature (in degrees Fahrenheit) on Sat Jul 04 2020 at the San Francisco International Airport` for testing)
2. Click on `dispute Tentative Winner`
3. Scroll down to `Other Outcomes`
4. Enter a number in the `degree` text input
5. See the page gets stuck
6. after some time, console shows a lot of errors 

**Expected behavior**
Shouldn't get stuck and no errors

**Screenshots**
![Screenshot 2020-07-09 at 12 22 22](https://user-images.githubusercontent.com/14846504/86996710-e8271f80-c1de-11ea-94bb-1985ce7d729e.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version [e.g. 83]

**Comment by bthaile** [comment]
not sure if that is a bad build. can you repro against v2.augur.net?

**Comment by pgebheim** [comment]
@Troublor -- Do you have any other info? The error you're seeing is coming from `augur-test` which shouldn't even be included in the UI build -- that's unit tests. Could you describe how your local build worked?

**Comment by bthaile** [comment]
![2020-07-09 17 20 44](https://user-images.githubusercontent.com/3970376/87096565-bf1b8480-c208-11ea-8b24-db6b8d29bd7b.gif)

I didn't capture the `processing ....` the transaction was successful. 

![image](https://user-images.githubusercontent.com/3970376/87096586-ca6eb000-c208-11ea-86f5-49eac6dcdcb1.png)

The disputing form is really sluggish. There is def room for improvement but it worked.

**Comment by Troublor** [comment]
I checked that this issue doesn't exist on v2.augur.net. I also pulled the latest commit [`8bf07fb7df`](https://github.com/AugurProject/augur/tree/8bf07fb7df3698aa379116a50f865763f5c358bf) from `dev` branch. But I couldn't create a market that expires immediately (e.g. in 3 minutes), so I can't test this issue again by now. 

I notice that code in the `dev` branch changes drastically recently. And the version deployed on v2.augur.net is not the latest. **Which version is deployed on v2.augur.net?** I think rather than testing the latest code, I can focus on the version deployed on testnet.

**Comment by pgebheim** [comment]
v2.augur.net is now deployed from the `v2` branch. The dev branch is 2.1+ and includes the work in progress for the betting and sportsbook uis. We split it off so the team could continue mainline work without destabilizing the launch RC.

Try pulling from v2.

Re: sluggishness @bthaile @JohnDanz shouldn't that form sluggishness be fixed on dev?

**Comment by bthaile** [comment]
@Troublor the market creation endTime bug was fixed yesterday. It's been deployed to v2.augur.net give it another try. `v2` branch.


I'd say `dev` branch is in pre-alpha state. I wouldn't point anyone at it for development, yet.

**Comment by Troublor** [comment]
@bthaile Thanks for the information.
