### ISSUE TITLE
Frozen Funds isn't displayed

### ISSUE THREAD

**Issue by nuliknol** [AugurProject/augur#8419]
Using 'dev' branch as of today's morning I get this error: the amount of frozen funds isn't displayed because possibly there an error in retrieving this value.
I can confirm Profit Loss events were received and they sum up to 101 DAIs. (evidence omitted)

![frozen_funds_is_not_displayed](https://user-images.githubusercontent.com/1125368/87189040-8ab1d200-c2b5-11ea-9bec-a186f00cf76a.png)

I have 3 open positions on this screenshot.
This test is done using local testnet config.

**Comment by pgebheim** [comment]
Use the v2 branch if you want to be integrating with the version being stabilized.

The dev branch is very unstable and hundreds of commits ahead of v2.

**Comment by nuliknol** [comment]
ok, now I am using v2

![using_v2](https://user-images.githubusercontent.com/1125368/87210554-90221300-c2db-11ea-846b-797dea8911d4.png)

but still getting the same error:
![portfolio_screen_ff_mismatch](https://user-images.githubusercontent.com/1125368/87210574-ad56e180-c2db-11ea-810f-6ad52304eddd.png)

I can guarantee it is $45 in frozen funds becase I am getting ProfitLossChanged events correctly in my database:
![profit_loss_events](https://user-images.githubusercontent.com/1125368/87210608-d5464500-c2db-11ea-9388-5edd54208a37.png)

**Comment by nuliknol** [comment]
@pgebheim

**Comment by nuliknol** [comment]
btw, there is no error in the console, except for the Metamask, but it is not related
