### ISSUE TITLE
Reskin: Portfolio My Markets page

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#842]
Portfolio: My Markets Design: https://www.figma.com/file/c7Yck1ciNsfd0HydNvM4OGRj/Old-Design---ReSkin?node-id=0%3A5344

- [ ] Update line in graph to be blue.
- [ ] Update Initial Liquidity section as per spec on Desktop & Mobile.
- [ ] Update fonts/formatting, buttons, categories/tags as per spec on Desktop & Mobile.

**Comment by phoebemirman** [comment]
also need to update claim button
