### ISSUE TITLE
Fix local integration test running in augur-core

### ISSUE THREAD

**Issue by nuevoalex** [AugurProject/augur#843]
Ethers does not work nicely with testrpc / ganache-cli. Its possible the ethers-cli package will work better but in general these should be altered to work again to help with development and testing locally.

**Comment by pgebheim** [comment]
@nuevoalex @robert-e-davidson3 -- is this still not working?

**Comment by robert-e-davidson3** [comment]
Talked to @nuevoalex about this. It's not important enough to do.

My suspicion is that this isn't still a problem since the middleware tests work fine against ganache.
