### ISSUE TITLE
Design Epic To Track

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#844]

**Comment by Chwy5** [comment]
1. Wire-frames - AS pg
2. Wire-frames Portfolio pg
3. Design - AS pg
4. Design - Portfolio pg
5. Design finish Market Cards
6. Wire-frames Reporting
7. Wire-frames Dep/WD
8. Design Reporting
9. Design Dep/WD
10. wire-frames - Market creation
11. Design Market creation
12. Design sort/searching-tags
