### ISSUE TITLE
Design QA - Market list Title, Sort by dropdown & Search Area

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#8447]
**POPULAR MARKET TITLE**
Size is smaller at dev.augur.net: Should be 24px (H3)

**SORT BY DROPDOWN**
- Style needs to be improved
- Options are incorrect. Should be: 
-- Estimated Start Time
-- Ending Soon 
-- Highest Liquidity

![Screen Shot 2020-07-14 at 09.36.27.png](https://images.zenhubusercontent.com/5cc988ee77bc5b0505df9320/c5a4091d-9d33-49b0-aa45-b00daf6e3d29)

![Screen Shot 2020-07-14 at 09.37.05.png](https://images.zenhubusercontent.com/5cc988ee77bc5b0505df9320/99c58270-e39d-488b-9b4f-9f16f9022d62)

**Figma reference:**
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7272%3A75

**SEARCH**
- While on Focus or active, the input border should be darker (Like it is during the hover state).
- Text is not vertically centered.
- Icons are different from original design 

**Reference (Design at bottom)**
![Screen Shot 2020-07-14 at 09.47.39.png](https://images.zenhubusercontent.com/5cc988ee77bc5b0505df9320/e89e63bb-0e54-47ec-bd0e-c8554055dc05)

**Figma Reference:**
https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet-Design-System?node-id=561%3A4371

**Comment by yanelbottini** [comment]
Issues were solved, please could we improve alignment of text inside search box. Right now doesn't seem to be vertically aligned:

<img width="934" alt="Screen Shot 2020-08-25 at 10 30 15" src="https://user-images.githubusercontent.com/49915900/91180387-0dec8300-e6be-11ea-9a18-ae2c884ff6e7.png">

**Comment by matt-bullock** [comment]
looks ok to me. closing
