### ISSUE TITLE
Design QA - Banners on Sportsbook landing page

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#8449]
We need to update the banner design to match the following approach:
- We have a top banner (that invite the user to sign up)
- We have side banners that redirect the user to our other products (Trading / Betting Exchange)

![Screen Shot 2020-07-14 at 10.25.21.png](https://images.zenhubusercontent.com/5cc988ee77bc5b0505df9320/8da84f2e-c40f-4e1a-b56f-2abf144555fd)

**Figma reference:**
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=6732%3A219660

**Comment by Chwy5** [comment]
updated - closing
