### ISSUE TITLE
some dispute rounds are not showing on market card

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#846]
on mainnet market card dispute round numbers not showing.

![screen shot 2019-01-12 at 7 50 38 pm](https://user-images.githubusercontent.com/3970376/51080552-6155bd00-16a3-11e9-98c0-12cabed392d5.png)

no errors in web console. Loading the dispute round number isn't consistent. When they don't only the first 5-6 don't show the rest on the page show.

**Comment by joeykrug** [comment]
I've seen this issue too

**Comment by bthaile** [comment]
issue is:

if user goes to market-list page and views  markets "in reporting", the market is loaded but not the dispute info. 
Then user goes to dispute markets page the previously loaded markets in dispute are listed but their dispute info isn't loaded. 
basically I missed loading market ids list and filtering markets in dispute that have been already loaded. 

Need to filter markets collection after getting callbacks from load markets if not loaded and getDisputeInfo.

**Comment by joeykrug** [comment]
Looks like tentative outcomes are missing there too

**Comment by bthaile** [comment]
Yea there were already loaded markets that getDisputeInfo wasnt called. Its fixed in my new PR, based on my testing against rinkeby.
