### ISSUE TITLE
UI doesn't start for specific Metamask account

### ISSUE THREAD

**Issue by gabbello** [AugurProject/augur#847]
I'm using ipfs.augur.casino and if i connect a specific metamask account (on which I have various transactions) I always get: "Sorry, something went wrong! Try reloading this page or returning home.". I've attached also browser console error log here.
If I use a different metamask account (without transactions) all is good.
I'm currently trying to set locally the env. as well (it will take ages until it will synch :( ), but I'm expecting simillar behaviour. Also, note that this metmask account was working fine (both locally and with augur.casino UI 4,5 months ago when I last used it.
[ipfs.augur.casino-1547388544310.log](https://github.com/AugurProject/augur/files/2753189/ipfs.augur.casino-1547388544310.log)

**Comment by pgebheim** [comment]
Sounds to me like something is happening when we try to fetch that account balance or somesuch that is causing a JS error. This is the gist of the error:

main.62984b861ed65a9345d5.js:1 Error: [BigNumber Error] Not a number: undefined
    at main.62984b861ed65a9345d5.js:12
    at new P (main.62984b861ed65a9345d5.js:12)
    at new P (main.62984b861ed65a9345d5.js:12)
    at a (main.62984b861ed65a9345d5.js:1)
    at main.62984b861ed65a9345d5.js:63
    at Array.reduce (<anonymous>)
    at T (main.62984b861ed65a9345d5.js:63)
    at u.max (main.62984b861ed65a9345d5.js:63)
    at main.62984b861ed65a9345d5.js:100
    at main.62984b861ed65a9345d5.js:43
main.62984b861ed65a9345d5.js:79 TypeError: Cannot read property 'plus' of undefined
    at main.62984b861ed65a9345d5.js:63
    at Array.reduce (<anonymous>)
    at T (main.62984b861ed65a9345d5.js:63)
    at u.max (main.62984b861ed65a9345d5.js:63)
    at main.62984b861ed65a9345d5.js:100
    at main.62984b861ed65a9345d5.js:43

**Comment by adrake33** [comment]
@JohnDanz Can you please spend a little bit of time investigating this to see if you're able to reproduce it? If it's not easy to reproduce, we can try investigating it more once the trading page redesign is done.

**Comment by gabbello** [comment]
Thanks for looking into this. As an update with a local installation everything seems to be working fine.

**Comment by JohnDanz** [comment]
I'm having trouble reproducing this issue (as mentioned above) Will keep an eye out to see if we can't track it down in the future, as @adrake33 mentioned

**Comment by gabbello** [comment]
Somehow simillar behaviour reported here: https://www.reddit.com/r/Augur/comments/agajmw/i_keep_getting_this_error_on_the_augur_web_app/?utm_source=reddit-android

BTW, I was also using Ubuntu (16.04) and chrome

**Comment by joeykrug** [comment]
Wow multiple people with the same issue. Seems new

**Comment by adrake33** [comment]
Yeah, this will need more investigation. Unfortunately, we still don't know how to reliably reproduce it.

@JohnDanz Can you ask around on Discord to see who else is seeing this and try to get more details as to how to repro it?

**Comment by gabbello** [comment]
I'm on discord and also I can still replicate the problem on ipfs.augur.casino if needed.

**Comment by joeykrug** [comment]
The reddit post says to reproduce: use metamask, buy positions, log out then log back in

**Comment by pgebheim** [comment]
New code hasn't yet been merged, or deployed to an app, nor has
augur.casino been updated.

Should be able to test later today.

**Comment by adrake33** [comment]
@gabbello Can you please check this again using version 1.10.0 (https://github.com/AugurProject/augur-app/releases/tag/v1.10.0) and let us know if you are still seeing this issue with your account?

**Comment by adrake33** [comment]
Closing this issue since it seems to be resolved.
