### ISSUE TITLE
Convert button not working - needs error message

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8476]
Click add funds modal
Click Convert
Input amount into Eth to dai....dai value doesnt update

**Comment by bthaile** [comment]
not sure what is going on. is it a long lag then update?

![2020-07-15 14 07 39](https://user-images.githubusercontent.com/3970376/87585418-adbcf700-c6a4-11ea-9a9b-b321238b9e4a.gif)

**Comment by bthaile** [comment]
Need error messages to tell user they don't have enough ETH to convert.

![2020-07-15 14 09 52](https://user-images.githubusercontent.com/3970376/87585631-fbd1fa80-c6a4-11ea-8660-93bd0df57fd0.gif)

**Comment by Chwy5** [comment]
Added - closing
