### ISSUE TITLE
migrate REP button doesn't go away

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#8477]
migrate REP button doesn't get removed after user migrates their legacy REP.

side effect of removing getBalance calls each block.

**Comment by bthaile** [comment]
not able to repro issue of migrate button sticking around

![2020-07-16 05 34 21](https://user-images.githubusercontent.com/3970376/87661380-1e582800-c726-11ea-82ec-448a246fdeb2.gif)

**Comment by Chwy5** [comment]
It closes if I hit the x or the close button didnt know if the modal would disappear automatically after the migration occurred

**Comment by Chwy5** [comment]
closing
