### ISSUE TITLE
Account Summary Pg Design

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#848]
"Your Overview" Section which shows: Users Acct value, ability to see 24 hr, 1 wk, 1 month value and % change.

Users Number of Positions, Number of Open Orders, Number of positions in reporting, Number of resolved positions, Users amount of Rep staked.

A notifications section for things like - Market can be finalized, orphaned orders, claim proceeds, you have open orders on finalized market, Complete sets (for now- removed for V2), etc. (all in 1 spot so user doesnt have to search through markets anymore).

List of all users open markets showing 24 hr % change - this will NOT expand to see outcomes as this is only a performance glance (w/button to take you to positions section on Acct overview pg to see specific positions).

Favorite (or watchlist section)

"Platform Status": # of Active users, Vol (24 hr), Trades (24 hr), Can show lifetime + OI as well, Avg block time (or move the block number here - like a system health), # of overall Markets, Total Money at Stake

**Comment by joeykrug** [comment]
This just sounds like the user’s account pages but all in one page as an overview. So it would maybe make sense to do them first

**Comment by Chwy5** [comment]
Just about done with the wire frames for the Account pg (want to show you them Monday), Matt and I will move onto this next

**Comment by pgebheim** [comment]
@chwy -- can this be closed?

**Comment by Chwy5** [comment]
Closing
