### ISSUE TITLE
UI blanks with error if MM `enable()` is denied

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#8487]
on occasion MM doesn't return chainId so UI can't determine if user is on correct network. In the case `enable()` is called to prompt the user to enable MM and the UI gets the chainId it's connected to. 

Need to handle case when user denies the `enable()` and fall back on torus provider

**Comment by Chwy5** [comment]
Works - closing

**Comment by bthaile** [comment]
According to Robert these steps still show perpetual loading cards:

1. Log into MM and pick the right network. Otherwise, you get a network mismatch error even when MM is locked.
2. Lock MM
3. Go to a market page directly, like http://localhost:8080/#!/market?id=0x1757c6b275a527774E68CD76894df3d9a4B7a065
4. MM will popup asking to unlock. Close that popup.
5. Wait for eternity like it says Market Loading without ever loading the market.
I assume it's just waiting forever for MM to give a response that will never come.

**Comment by Chwy5** [comment]
Still works for me... @robert are you seeing the "1" by the fox for MM after you close the MM signing box?  If you were to open that and sign the UI loads....or if you refresh the pg, the ui loads

**Comment by robert-e-davidson3** [comment]
Works for me now too. Closing.
