### ISSUE TITLE
Portfolio Pg Design

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#849]
1) Positions - Showing Market title with 24hr % change - this can be expanded open to show all individual outcome for that market - w/ value and 24% change on each outcome (risk assessment).

2) My Markets - list of all open Markets created by the user. (change to Markets Created Markets)

3) Reporting - User's markets they can report on. (will be its own separate pg)

4) Open Orders - will be preset by most recently traded first (will need ability to sort, search if user prefers to group by specific market).

5) Filled Orders - same sorting,searching needed as open orders

**Comment by joeykrug** [comment]
Done
