### ISSUE TITLE
Design QA - Sign Up

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#8493]
**Styles are not accurate:**

- Betting doesn't use border on modals 
-  Sign Up / Sign in button style is incorrect.
- Size is different. 
- Login created icon color incorrect. 
- Missing space:
![Screen Shot 2020-07-16 at 09.23.22.png](https://images.zenhubusercontent.com/5cc988ee77bc5b0505df9320/f700a2d6-ad80-4cc5-b8f6-7d297fdf7fef)

![Screen Shot 2020-07-16 at 09.18.38.png](https://images.zenhubusercontent.com/5cc988ee77bc5b0505df9320/4710f3d8-2c3c-4081-b98e-e1ed5b69d7b9)

**Steps**

- Please double check steps, cause we don't use the dots approach on Betting:

![Screen Shot 2020-07-16 at 09.25.59.png](https://images.zenhubusercontent.com/5cc988ee77bc5b0505df9320/f3afeee5-2581-4a8c-a012-48e0eca192dd)

**Buttons**

- Text size is incorrect:

![Screen Shot 2020-07-16 at 09.29.59.png](https://images.zenhubusercontent.com/5cc988ee77bc5b0505df9320/e64137ea-0167-49d4-9fc6-d969105ce0e2)

**Comment by Chwy5** [comment]
this is getting reworked closing this one...will need redesign and new ticket later
