### ISSUE TITLE
Show warp sync in designated reporting section when in DR reporting state

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#8508]
Warp Sync market should show up in the Designated Reporting section with report button enabled. 
It's currently not show up.

**Comment by pgebheim** [comment]
I think I'm okay coming in an update and not being there at 2.0

**Comment by Chwy5** [comment]
![image](https://user-images.githubusercontent.com/41301809/88181408-caa17f00-cbfc-11ea-80f7-9fd593bd1074.png)

This is working- closing this ticket
