### ISSUE TITLE
Incorrect Escrowed eth Value -displayed

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#851]
@Chwy5 commented on [Mon Jan 14 2019](https://github.com/AugurProject/augur-core/issues/761)

Open Orders showed 17 eth escrowed for an order.  I cancelled the order but only recieved 15.3 eth back in my total balance.  Etherscan TX confirms 15.3 eth. The order was already partially traded on (so 15.3 was actually correct).  The problem is the open orders still displayed 17 eth escrowed. Should have updated to 15.3 (see third order down on screenshot)

![1-14scalar-cancel.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/30e8552d-bfd6-4062-8816-a44facae2a84)

 etherscan tx     0x7af0bcfbfb53d06a769d8fc12a2e3455ec16843de81757d04b6518b26ab9c3ab

occurred in augur app 1.9.0

**Comment by adrake33** [comment]
Assigning this to @JohnDanz  for now. @Chwy5 will try to reproduce this tomorrow morning and see if refreshing the page causes the correct escrowed ETH to show. If so, John can take a look. Otherwise, if it seems like a calculation issue, this can be reassigned to @pgebheim.

**Comment by Chwy5** [comment]
After retesting -Refreshing does NOT cause the escrowed eth to show up.  the escrowed eth is not updating correctly after a partial trade of the original trade occurs.

See 2 attached screenshots - 1st is Acct 1 balance (escrowed eth) after placing buy 10 shares at .5 on the order book); 2nd is Balance and non updated escrowed eth after Acct 2 sells 1 share of Acct  1's 10 share bid....shows Acct 1 balance of 9, but escrowed eth remains 5

![1-15testacctA.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/e684a1ad-2fa7-42d0-860a-878587b1c3ec)

![1-15testacctB.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/83530abd-c3ce-49ca-94a6-3b9c32d5bc68)

**Comment by pgebheim** [comment]
Oh I mis-remembered!

On this one the escrowed eth wasn't UPDATED.

@nuevoalex is this related to the issue you're working on re escrowed amounts and profit/loss?

**Comment by nuevoalex** [comment]
I'm not working on this one currently, working on the net qty updates

**Comment by epheph** [comment]
Fixed in https://github.com/AugurProject/augur-node/pull/806
