### ISSUE TITLE
Cancel Order Failing

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8520]
I created an open order 5 mins ago.  Trying to cancel ( I sign my MM signer)...cancel fails

![image](https://user-images.githubusercontent.com/41301809/87797856-44122980-c819-11ea-8625-92c720284088.png)

**Comment by nuevoalex** [comment]
I suspect this is a case of the protocol fee being higher than what was permitted. I was only able to repro once and in that case my gas price was massive and potentially higher than what was used to calculate the max protocol fee. Will make a patch to increase that allowance and see if that works.

**Comment by Chwy5** [comment]
@nuevoalex I thought you changed this...can this be closed?

**Comment by pgebheim** [comment]
This is all gas estimation stuff that's fixed with removing GSN + adjusting the gas estimates to account for variance.
