### ISSUE TITLE
Design QA - Market Cards Hover States

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#8536]
![Screen Shot 2020-07-20 at 06.47.49.png](https://images.zenhubusercontent.com/5cc988ee77bc5b0505df9320/46cbfd95-c878-4ac2-9237-bdb5465d696d)

Please, use the above image as reference for hover states for market cards:

- Favorite: Please update hover state color.
- Outcome: When hovering the outcome please use Border gray (#D1D1D9) at 20% opacity.
- Odds: When hovering an odd box please use Bet For at 40% opacity.
- Related Market: When hovering a related market, please highlight border.

Figma reference:
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7384%3A886

**Comment by Chwy5** [comment]
not needed - made different changes - closing
