### ISSUE TITLE
Market OI fee displays infinity

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8543]
Caused by hotloading

![image](https://user-images.githubusercontent.com/41301809/87943798-8c755580-ca6c-11ea-9f0f-f725ce723cda.png)

**Comment by bthaile** [comment]
Infinity is coming from hotloading UpdateMarket event

![image](https://user-images.githubusercontent.com/3970376/87944086-8da28480-ca64-11ea-9dd3-a5b58d8992bd.png)

**Comment by bthaile** [comment]
augur-lite hotloading isn't processing the hex correctly.

![image](https://user-images.githubusercontent.com/3970376/87944639-45d02d00-ca65-11ea-8f9f-63acd0937cb1.png)

**Comment by bthaile** [comment]
![image](https://user-images.githubusercontent.com/3970376/87944793-76b06200-ca65-11ea-893c-0407d142a00f.png)
