### ISSUE TITLE
Missing postion and Fills

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8550]
using MM on a yes/No market...I sold 10 shares of invalid...I have a toast message fill and trade history shows it, but doesnt show in my position or my fills on the trading pg or in portfolio

![image](https://user-images.githubusercontent.com/41301809/87955427-bda95200-ca7b-11ea-91cc-b1fa6f1b2e3e.png)

**Comment by bthaile** [comment]
Are there any errors in web console for when get user data sdk getter is called?

**Comment by bthaile** [comment]
I think this failure caused data not to show up in Fills section of market trading page.

![image](https://user-images.githubusercontent.com/3970376/87998398-61672200-cabd-11ea-99a5-58ffbd2055a5.png)
