### ISSUE TITLE
Missing Consuming Own Order message

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8556]
there is no "consuming own order" message appearing if I click on my own order from the outcome table

It appears if i manually input it into the order ticket or click on the order book

2nd Scenario....Add a better bid (or Offer) to an existing side of the book....then click on the order book, like you would sweep it....Even though one of those orders is my own the message doesnt appear

**Comment by bthaile** [comment]
I think issue here is outcome table and orderbook not sending data to orderform. 

order form needs to be cleared then populated with data from orderbook/outcome table.

**Comment by bthaile** [comment]
Not able to repro this issue.
