### ISSUE TITLE
Invalid number value for feePerCashInAttoCash on Scalar Market creation

### ISSUE THREAD

**Issue by nuliknol** [AugurProject/augur#8560]
Using sources as of today's morning and with local testnet setup with real time I am getting this error on an attempt to create a scalar market:

![cant_create_scalar_market](https://user-images.githubusercontent.com/1125368/87993424-1397ed00-cab0-11ea-9215-2b5d6b3f62f6.png)

The error message is clear, but I can't see what parameters did I put because there is no way to check it once you hit submit button. 

The template I used  for this test was: Custom

**Comment by nuliknol** [comment]
I made a second attempt , using the same values I used in previous attempt, but now recording the screenshots. Creating Scalar market doesn't seem to work. Must have happened in some commit last week.
![market_parameters](https://user-images.githubusercontent.com/1125368/87994228-0d0a7500-cab2-11ea-962b-c8c6bb78fb7a.png)
![market_comission](https://user-images.githubusercontent.com/1125368/87994236-1267bf80-cab2-11ea-8775-800bfe92ce9d.png)
![market_preview](https://user-images.githubusercontent.com/1125368/87994243-14ca1980-cab2-11ea-85c0-e9142f90fecd.png)
![market_creation_error](https://user-images.githubusercontent.com/1125368/87994249-185da080-cab2-11ea-8dd7-2d9901ba3fca.png)

however, this time I am getting another error "gas required exceeds allowance"
![market_creation_error_2](https://user-images.githubusercontent.com/1125368/87994411-74282980-cab2-11ea-9bf5-ba7379ba6235.png)

**Comment by pgebheim** [comment]
@Chwy5 tried making a scalar today?

**Comment by nuliknol** [comment]
Actually, after more debugging,I can see that the error happens in the Market Preview page. The problem is that gas can't be estimated properly:

![scalar_market_preview](https://user-images.githubusercontent.com/1125368/88232161-fcd1d180-cc3a-11ea-9636-444633cc3d27.png)

**Comment by nuliknol** [comment]
I just created a scalar market from template, so this problem is only happeing for Custom Scalar markets

@Chwy5

**Comment by nuliknol** [comment]
@pgebheim 
this is isn't a problem with the UI, because I have tested it with UI of 9 July (2 weeks old) and I am getting the same error. So , this is a configuration problem of local test net.
![market_creation_error](https://user-images.githubusercontent.com/1125368/88320990-13803300-cce4-11ea-8754-468daaa3edcb.png)

**Comment by nuliknol** [comment]
Just tested the same config on Kovan and I also get the same error there. Well, maybe not the same error, but I am pretty sure this is the same problem.

![create_scalar_market_on_kovan_error](https://user-images.githubusercontent.com/1125368/88405153-76c99e00-cd94-11ea-808b-3eaf90f156db.png)

**Comment by namankumar** [comment]
hi @nuliknol, I'm working on Augur's product direction and wanted to get feedback on your overall Augur experience so we can make it more satisfying. 

Would you be open for a quick chat? I'm in the discord as naman or we can set up a call as well. 

Thanks so much!
