### ISSUE TITLE
Missing Fee reserve message for replenishment in order ticket

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8573]
MY eth balance is low, so my fees are high, but I am not getting the message letting me know to fill eth reserve (the one with the checkbox)

![image](https://user-images.githubusercontent.com/41301809/88093168-a0e64a80-cb5f-11ea-9ec2-df23e2a6deef.png)

**Comment by bthaile** [comment]
Prob not getting it because there is an error/warning for unprofitable trade. It would prob show if there wasnt the unprofitable trade error/warning

Oops, I’m thinking about the notice. Does the checkbox show in account dropdown?

**Comment by bthaile** [comment]
There is a check of user's signing wallet ETH. If the balances is 20% or more than fee reserve ETH target amount then the checkbox to replenish isn't shown. 20% over 0.04 ETH is `0.048` ETH. so as long as your signing wallet ETH balance is over that the checkbox won't show up. 

We can change that calc if we need to.

**Comment by bthaile** [comment]
I think we are good on this ticket. UI is behaving as coded. We'll need to figure out the fee reserve. 0.04 is 3x too low when gas prices are around 70 gwei. recommend closing this.
