### ISSUE TITLE
Add Portfolio Value and Available Funds

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#858]
we should consider using "frozen funds"....this will make it easier for a user to track their trading success....For example a user starts with 50k worth of dai....Market 1 they escrow $4200, market 2 they escrow $3550, market 3 they escrow $2200....currently we would show them having an eth balance of 40050....say they made $50 profit on market 2 after it resolved and claimed proceeds...we currently show them having a balance of $43650(the user doesnt really know if they are up or down $ by seeing this number).........If we showed a Portfolio Balance and available trading funds instead the user would see $50050 for Portfolio Balance and $43650 for Available Funds....makes it a lot more clear that they user is up money from their starting balance.

**Comment by adrake33** [comment]
@joeykrug @matt-bullock  chwy's idea for this in the UI was to always show Total Value and have a hover that would show available trading balance (or visa versa). What are your thoughts on this?

**Comment by joeykrug** [comment]
Sounds good

**Comment by matt-bullock** [comment]
Any preference?
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/6348a8ac-676f-4051-a9e0-93b54206b545)
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/84ccb51c-17d9-4855-a32c-0eaa3ddec376)

Is portfolio balance the best term here?

**Comment by adrake33** [comment]
@matt-bullock Personally, I prefer the top one. I think the term Portfolio Balance is probably ok unless someone else has a term that they think would make more sense to traders.

What do you think, @joeykrug @Chwy5?

**Comment by Chwy5** [comment]
hopefully it isnt too long, But I like the terms Total Portfolio Value and Available Funds

**Comment by adrake33** [comment]
Total Portfolio Value seems a little clearer to me, and it's not much longer than Portfolio Balance. I like that as well.

**Comment by joeykrug** [comment]
I've seen trading UIs just use Portfolio Value and Available Funds before, but I don't care either way here. Top is better.

**Comment by adrake33** [comment]
Ok, if Portfolio Value is the more commonly used convention, let's go with that.

**Comment by adrake33** [comment]
Since we decided to leave sprint tasks unassigned and let the devs choose which tasks they want to work on next, I'll unassign everyone from this ticket so one of the devs will pick it up.

**Comment by matt-bullock** [comment]
![image](https://user-images.githubusercontent.com/39496225/51320267-983f2080-1a5f-11e9-8846-ebca2a27449a.png)


This component sits in the buttons component board on the desktop design page

**Comment by JohnDanz** [comment]
@Chwy5 should we also update the accounts page to show the portfolio balance instead of just showing available balance as it does currently?

![image](https://user-images.githubusercontent.com/10524630/51920361-d9fa9000-23aa-11e9-90db-e2abf403d667.png)

these values shown here is what im talking about

**Comment by Chwy5** [comment]
For now put available balance over it and we'll address in the redesign

**Comment by pgebheim** [comment]
This was closed by PR and that automation didn't catch it.
