### ISSUE TITLE
Update images and copy on home page hero

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#8582]
https://www.figma.com/file/buzGz2v44DfkUQf112KlcO/Landing-Page-Complete-Design?node-id=1430%3A2974

Only using 3 screens rather than 4. Images in each screen have been updated

**Comment by matt-bullock** [comment]
Images look good but the copy still needs updating to what you see in the designs @bconfortin

**Comment by matt-bullock** [comment]
@bconfortin the copy still doesn't look updated. Has it been pushed yet?

**Comment by bconfortin** [comment]
Just updated it.

**Comment by matt-bullock** [comment]
looks good
