### ISSUE TITLE
Grammar & Content Review: v2 App

### ISSUE THREAD

**Issue by tomkysar** [AugurProject/augur#8612]
Passthrough of the Augur v2 app for grammar and content feedback/thoughts

Reoccurring thing is inconsistently capitalizing the names of fees and variables within Augur - if it's capitalized, that'd be referring to it as a proper noun, however we *don't* do it everywhere consistently if thats the case..pretty sure easiest thing is not capitalizing any of it. If you're trying to emphasis those words, we could consider bolding them or something instead. Either way, need to be consistent with however its done, but think it looks a bit wonky with the capitalization randomly throughout (and would need to properly reference it that way throughout elsewhere as well when referring to it by name specifically vs. generalized).

re: DAI, are we trying to account for referencing it as the name vs. the currency in locations? I know the _name_ itself is "Dai", but we reference it as "DAI" in like 90%+ of the UI, I think argument to be made for consistency sake and just always refer to it as the currency/ticker, and not the name itself? Feedback on this comes from this line of thinking, that a user will always recognize 'DAI'. Has this been discussed prior and a reason was landed to call it Dai in places? I don't know if this was done intentionally, but if so, then we use "Dai" in places followed by "ETH" - would it not follow a similar naming convention for ETH then and be called Ether?

### **Account Activation Modal:** 

a) Screens 2, 3, 4: Grammar, capitalization of DAI - **"DAI" capitalized** 

b) Screens 3, 4: Grammar - **"Fee reserve" has "Fee" capitalized in the middle of sentences.**

c) Screen 4: Wording - "This goes entirely to the network and Augur doesn’t collect any of these fees." ---> **"This goes entirely to the network and its participants, the Augur protocol doesn’t collect any fees."**

d) Screen 4: Fix - "There will be a $14.58 fee to activate your account." --> **This needs to be changed I'm pretty sure, I don't know how you best communicate it (ex: how we actually calculate that fee - but $14.58 is not static, this is a dynamically changing amount, no?)**

e) Screen 3, 4: Grammar - "equivalent to 0.04ETH" - **should be in  ( ), ex: "xyzxyzxyz (equivalent to 0.04 ETH)" and a space.** 

f)  Screen 4: Grammar - "So long as" --> **"As long as"**

g) Screen 5: Wording - "pretend" --> **"test"**

### **Add Funds Overlay:** 

a) "Add Dai ($) using a Coinbase account" --> **Grammar, capitalization of DAI** 

b) "Buy the cryptocurrency Dai ($)" --> **Grammar, capitalization of DAI** 

c) "Send the Dai ($) to your trading account" --> **Grammar, capitalization of DAI** 

d) "Learn how to buy Dai ($) and send it to your trading account." --> **Grammar, capitalization of DAI** 

e) "Buy Dai ($) using an app or exchange (see our list of popular ways to buy Dai ($))" --> **Grammar, capitalization of DAI, remove the ( ) -  "Buy DAI ($) using an app or exchange - see our list of popular ways to buy DAI ($)"** 

f) "Transfer the Dai ($) to your trading account" --> **Grammar, capitalization of DAI** 

### **Demo / Walkthrough Guide Layover:** 

Just rewrote these / edited the sentences with grammar fixes, a lot of this stuff is broken, inconsistent or bad grammar, took a stab at it:

1/12: "First, lets start by looking over the market details. Be sure to check that the question isn't subjective or ambiguous, and that the Resolution Source abides by the community guidelines and, if a Resolution Source is used, the source's URL or full name is in the Market Question." --> **"First, let's start by looking over the market details. Be sure to check that the question isn't subjective or ambiguous, and that the resolution source abides by the community guidelines. If a resolution source is used, the source's URL or full name will be in the market question."** 

3/12 : "To learn more about selling shares, or going 'short,' see our guide." --> **"To learn more about selling shares, or going 'short,' see the trading guide."**

4/12: "To learn why invalid is an outcome, see our guide." --> **"To learn more about invalid outcomes, see the invalid market guide."**

5/12: "Enter the amount of shares you wish to buy. Remember each share is priced between $0.01 - $0.99" --> **period at the end.** 

6/12: "The Limit Price is the price you’re willing to buy or sell per share. " --> **"The limit price is the price you’re willing to buy or sell per share."**

6/12: "For example predicting that there is a 40% chance of this outcome occurring, you would buy $0.40 per share. If your prediction is right, you stand to make a profit of $0.60 per share." --> **"For example, to predict that there is a 40% chance of this outcome occurring you would buy shares at $0.40. If your prediction is correct, you will make a profit of $0.60 per share."** 

7/12: "This shows the amount of money required to make this trade. You can change this value to control the total cost of your order, and the quantity will adjust to compensate for the new total order value. So if you want to bet $40, enter 40 in here." --> **"This is the total cost required for you to make this trade. You can change this value to control the total cost of your order and the quantity will adjust to compensate for the new total order value. If you want to bet $40, enter 40 in here."**

8/12: "Alternatively, you can select an available order from the order book to automatically fill into your order ticket. The orders in red are sell orders (offers); the quantities shown are available to buy at the listed prices. The orders in green (bids) are orders from users who wish to buy shares. The quantities show how much you can sell to them at the listed prices." --> " **"Alternatively, you can select an available order from the order book to automatically fill your order ticket. Orders in red are sell orders (offers), the quantities shown are available to buy at the listed prices. Orders in green are buy orders (bids), and the quantities shown are available to sell into at the listed prices."**

10/12: "As you can see our order just disappeared from open orders because it was filled. Click next to see it in my fills." --> "**As you can see, our order just disappeared from open orders because it was filled. Click next to see it in my fills."**

11/12: "'My Fills' are where you can track all filled or partially-filled orders." --> **"The my fills tab is where you can track all filled or partially-filled orders."**

12/12: "Tracks your overall exposure in the current market. This includes your overall position, the average price you put on that position, potential profit and loss (unrealized P/L) and any realized gains or losses (realized P/L)." --> **"The positions tab tracks your overall exposure in the current market. This includes your overall position, the average price you have on that position, potential profit and loss (unrealized P/L) and any realized gains or losses (realized P/L)."**

Final complete screen: "Now you're all set! You can view this walkthrough at any time from the help menu (question mark icon on the top right). Additionally, our Knowledge Center is there to help you with more in depth guidance" --> **"Now you're all set! You can view this walkthrough along with a more in depth knowledge center at any time in the help menu, located at the top right of your screen by selecting the question mark icon."**

### **Individual Market Page:** 

a) Market OI Fee tooltip --> **Grammar, Market OI Fee, Market Creator Fee, and Reporting Fee**

b) Event Expiration tooltip --> **Consistency, used as a title, it should be capitalized. "Event Expiration:" not "Event expiration"**

### **Global Chat:**

a) "Disclaimer: The comment section is for entertainment purposes only. Augur does not monitor or assess the accuracy of comments. Traders should seek out independent information before making any investment decision." --> **"This chat is an unmoderated public forum. Please seek independent information and do your own research before making any trading decisions."**

### **Account Summary:**

a) Transactions History layover: "Augur only saves the data for 60 days after a market is finalized" --> **"The export tool only shows transactions for 60 days after the markets finalization."**

### **Dispute Page:**

a) "You can earn a proportional share of the profits from this dispute window." --> **"You can earn a proportional share of the reporting fees from this dispute window."**

b) Grammar: "Redeem your past Participation Tokens and any returns from your share of the Reporting Fees." **--> "Redeem your past participation tokens and any returns from your share of the reporting fees."**

### **Reporting Page:** 

a) Consistency w/ dispute page & update: "Need help? View our Reporting Quick Guide" **-->  "Need help? Reporting Quick Guide"**

b) Grammar --> "Check your Upcoming Designated Reporting to see Markets that will soon be available to Report on." --> **"Check your upcoming designated reporting section to see markets that will soon be available to report on." --> This also shows for both the designated reporting & upcoming designated reporting filler placeholder when there is nothing available, it should not be in the upcoming one referencing itself?**

### **Market Creation:**

a) "Templates simplify the creation of new markets and reduce errors in the market making process." --> **"Templates simplify the creation of new markets and reduce errors in the market creation process."**

b) **In the create custom market screen, there are capitalized references throughout - Market Question, Resolution Details, etc --> should not be capitalized unless we're going to refer to these universally as proper nouns (which I don't think we are), saving time and not copy/pasting each one in here but you should see the in the bulleted lists**

**Comment by sebinsua** [comment]
https://github.com/AugurProject/augur/blob/0fe46b3e8bfa39ec7b4214a4fe67acc5adb0e275/packages/augur-ui/src/modules/common/constants.ts#L1344 <- This should be `completely`.
