### ISSUE TITLE
Missing Transactions

### ISSUE THREAD

**Issue by blacktemplar** [AugurProject/augur#862]
I just tried a view things in the test app and bought 60 shares from outcome G of "Categorical Reporting Test Market (Cycle 4): correct answer is G", they were split in 5 shares per Ask, then I got 6 new Transactions which are also finished, but I should have 12 Transactions (for each Ask a 5 shares). Now I see that there are still 6 open Asks for outcome G and if I want to buy them it displays the following:

Trade Currently In-Progress
You may trade once your previous trade has completed

So somehow this trade is still pending, but I don't see any open transactions in my transactions view. This is a little bit confusing, at least for me.

**Comment by stephensprinkle** [comment]
@blacktemplar — Thanks for the issue report (and apologies on the significant delay in responding).  

I’ve noted your issue + will specifically test for this against our new version of the UI (`v3` branch, now the default branch for augur as well).  

Closing.
