### ISSUE TITLE
Upgrade geth & parity docker images

### ISSUE THREAD

**Issue by epheph** [AugurProject/augur#863]
Both geth and parity are running on ancient implementations. Upgrade to parity 2.2.7 and geth 1.8.20

**Comment by epheph** [comment]
These have been upgraded in git, but need to be released through the core release process

**Comment by pgebheim** [comment]
@epheph -- I think we can hand this over to @petong

**Comment by epheph** [comment]
Yes, everything should be good to go with the next release. Although I suppose we should do it again-again to activate constantinople ?

**Comment by pgebheim** [comment]
@petong is this actually done?
