### ISSUE TITLE
Market creation preview: Open order quantities aren't matching the order book

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#8655]
Orderbook is correct in this image

![image](https://user-images.githubusercontent.com/39496225/88546678-04b7ba00-d01d-11ea-899e-455e01856888.png)

**Comment by Chwy5** [comment]
@matt-bullock did u ever see this again?

**Comment by matt-bullock** [comment]
I didn't see it again but only tested a couple of times since. Just tried again on staging but market creation keeps blowing up

**Comment by matt-bullock** [comment]
Still not behaving right

![image](https://user-images.githubusercontent.com/39496225/89314725-4d552000-d67a-11ea-96e5-2213d7781add.png)

**Comment by bthaile** [comment]
Yes No looks good for me. 


![image](https://user-images.githubusercontent.com/3970376/89341931-a7001f00-d667-11ea-913c-f828d9730a04.png)

**Comment by bthaile** [comment]
Categorical looks good for me as well.

![image](https://user-images.githubusercontent.com/3970376/89342154-fd6d5d80-d667-11ea-9066-5c4a7c3d29ca.png)



Need more information. seems there is something I need to do to get in your state. Can chat about it, when you get a chance.

**Comment by bthaile** [comment]
did you add and delete orders from pre-liquidity? I tried adding and deleting orders and everything looks good for me.

Need more info

**Comment by matt-bullock** [comment]
Just tried again and still seeing the issue. No, not deleting orders.

Steps:
1. Add buy order on outcome for 10 @ .4
2. Add buy order on same outcome at 100 @ .4

![image](https://user-images.githubusercontent.com/39496225/89389853-41af3b00-d706-11ea-974c-c36e378bdd93.png)
![image](https://user-images.githubusercontent.com/39496225/89390100-8b982100-d706-11ea-94b0-6efc74ebbb70.png)

**Comment by matt-bullock** [comment]
@bthaile did you try the steps above?

**Comment by bthaile** [comment]
I don't see any steps.

**Comment by bthaile** [comment]
I see one issue here  👇 
![Screen Shot 2020-08-06 at 07 48 26](https://user-images.githubusercontent.com/3970376/89533611-4c76d800-d7b9-11ea-8444-64d6f0a75804.png)

**Comment by bthaile** [comment]
I see two display issues are these what you are talking about? I think super minor if these are the only issues.
![Screen Shot 2020-08-06 at 07 48 26](https://user-images.githubusercontent.com/3970376/89533722-74663b80-d7b9-11ea-8f2c-6384fb1dbb14.png)

**Comment by matt-bullock** [comment]
Yes only a display issue but is concerning for users

**Comment by Chwy5** [comment]
lowered to pri 3...edge case ui only
