### ISSUE TITLE
Orders don't complete: Stay in OPEN ORDERS

### ISSUE THREAD

**Issue by mhmmdkemal** [AugurProject/augur#8702]
**Describe the bug**

- I have set up Augur using the private geth, which is open to anyone sharing the same network as me. I used the command `yarn flash docker-all` then running the `yarn workspace @augurproject/ui dev` command. 
- I have two browsers and two different MetaMask accounts for each browser to allow me to create markets and trade. I have open markets created but when I try to buy and sell, they stay in `OPEN ORDERS` and do not allow me to trade between the two accounts. 
- I think this might be some kind of bug because in Discord, I asked and the solution proposed was to run `yarn flash liquidity` but that does not solve the issue. 

**To Reproduce**
1. Have a private geth running
2. Have a market created 
3. Two browsers (Firefox and chrome) and separate MetaMask account for each. 
4. See error: Does not let you trade and just stays in `OPEN ORDERS`

**Expected behavior**
It should let you buy and sell shares between the two accounts that were created. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5003576/88718193-95f76100-d0ef-11ea-8a57-bc95244eb437.png)
![image](https://user-images.githubusercontent.com/5003576/88718329-d1922b00-d0ef-11ea-9369-33c1f27b6a57.png)
![image](https://user-images.githubusercontent.com/5003576/88718405-ebcc0900-d0ef-11ea-9adc-24c693a1ffa7.png)

**Desktop (please complete the following information):**
 - MacBook Pro 
 - OS: iOS - Catalina
 - Browser: Chrome & FirFox

**Additional context**

**Comment by bthaile** [comment]
not following totally. making sure the prices match, when est tx is not 0.00 the sdk found an order that will match and trade. 

sometimes, trades will fail because orders locally dont actually exist because they either got cancelled or expired.

**Comment by bthaile** [comment]
@mhmmdkemal pull down v2 branch and test again. There has been major changes. Reopen this ticket if problem still occurs.
