### ISSUE TITLE
Sports Betting - Cashout

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#8703]
Please, use the following link to review cashout flow:
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7617%3A0

- Cashout is the action of closing a position while a market is open.
- Cashout can be executed from Betslip or My Bet Section (Same flow)

<img width="240" alt="Screen Shot 2020-07-28 at 17 58 01" src="https://user-images.githubusercontent.com/49915900/88720842-e674bb80-d0fb-11ea-8896-1e2fcc8778a0.png">
Color indicates whether the action has a positive or negative result.

<img width="379" alt="Screen Shot 2020-07-28 at 17 59 16" src="https://user-images.githubusercontent.com/49915900/88720961-115f0f80-d0fc-11ea-84ab-c5d38508eb45.png">
Cashout could be disabled if there is no order on Trading UI / Betting exchange matching the user one.

**Comment by matt-bullock** [comment]
![image](https://user-images.githubusercontent.com/39496225/91079516-6d0db180-e644-11ea-8e19-4fa7fded041d.png)

Odds isn't displaying correctly.

Cash out amount should be in green or red, depending if the user is profiting or losing money

After clicking cash out it the button gets stuck on processing

**Comment by phoebemirman** [comment]
i'm not seeing the cash out button get stuck. do you have reproduction steps that aren't the happy path?

**Comment by matt-bullock** [comment]
fixed. closing
