### ISSUE TITLE
ETH Reserve being used when DAI balance in Trading Wallet doesn't have sufficient DAI to fund it

### ISSUE THREAD

**Issue by nuevoalex** [AugurProject/augur#8708]
The client attempts to create an ETH reserve of .16 ETH (worth ~$50) present) if the trading wallet balance is above 40 DAI.

The Transaction itself costs between 15-30 DAI.

This means if the trading wallet contains an amount between roughly 40-80 it is likely to fail because the trading wallet will not have sufficient DAI in order to complete the transaction.

FIX: The client should globally disable trying to create an ETH reserve when the trading wallet balance is less than .16ETH worth of DAI + some excess buffer amount that represents a maximum expected TX fee (for now lets assume 6mil gas). This would disable the ETH reserve for trading wallet balances less than ~$100 currently.

Algo:

```
const desired_eth_reserve = 0.16 - signing_wallet_eth_balance;
const desired_eth_reserve_in_dai = to_dai(eth_reserve);
const total_estimated_max_ = 6000000 * gasPrice; // Estimate of a very large tx with current gas price
const total_dai_worst_case = total_estimated_max + desired_eth_reserve_in_dai ;
const use_eth_reserve = trading_wallet_dai_balance > total_dai_worst_case;
```

**Comment by pgebheim** [comment]
Fixed in 8720
