### ISSUE TITLE
Volume not showing up in candlesticks

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#8712]
<img width="694" alt="Screen Shot 2020-07-28 at 5 11 52 PM" src="https://user-images.githubusercontent.com/5925937/88745183-39e80900-d0fe-11ea-9a5d-14b29b98f0fe.png">

See above

**Comment by Chwy5** [comment]
looks like it is in the top right box

**Comment by joeykrug** [comment]
oh wow, that's incredibly confusing

**Comment by Chwy5** [comment]
I am not sure that is correct, would be a coincidence that the volume was equal to the the price
