### ISSUE TITLE
Exchange rate varying when transfer funds screen is open for amount of dai available in wallet

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#8718]
![2020-07-28 20 28 33](https://user-images.githubusercontent.com/5925937/88748252-6bb09e00-d105-11ea-9905-3175400ab809.gif)

**Comment by bthaile** [comment]
Is this still an issue? I'm not seeing it on mainnet. I don't have any open orders though.

**Comment by joeykrug** [comment]
i don't see it

**Comment by Chwy5** [comment]
Not seeing this - closing
