### ISSUE TITLE
User Reports: Bugs / Errors

### ISSUE THREAD

**Issue by tomkysar** [AugurProject/augur#8719]
Please post your errors, issues, bugs or etc in this thread. Please be as specific as possible, including:

- The core issue
- Wallet you're using
- Browser you're using
- Screenshots / additional information

**Comment by wdishman7** [comment]
Using Fortmatic on Chrome.

Two things: 1) Sent in Dai from Coinbase and it’s not showing up in my account. 2) tried to send ETH via Coinbase and am showing that it was received but not ending up in my account.
![B3CD3F5F-99F4-4B74-A28F-4349837A91C3](https://user-images.githubusercontent.com/68934083/88749197-ca374580-d120-11ea-8a21-b6d9fa148b9e.jpeg)

**Comment by MicahZoltu** [comment]
User Report:
> one random issue: if you copy the referral code link and there's an existing referral code, then it'll place the "&r=referral_code" in the URL twice. If you then copy it again, it'll put it there a 3rd time.

**Comment by Chwy5** [comment]
URL  twice added to new ticket....above stuff closing
