### ISSUE TITLE
Unable to convert ETH to DAI

### ISSUE THREAD

**Issue by rmurrish** [AugurProject/augur#8729]
**Describe the bug**
Unable to convert a balance of ETH to DAI, following the instructions under "convert" at https://help.augur.net/getting-started/adding-funds

**To Reproduce**
1. New account
2. Add ETH
3. Follow instructions to convert ETH to DAI: https://help.augur.net/getting-started/adding-funds
4. Nothing happens, UI doesn't update on button press, etc. 

**Expected behavior**
I expected confirmation, modal to close, ETH and DAI balances to update.

**Screenshots**

**Desktop (please complete the following information):**
 - Latest Chrome on Chrome OS 

**Smartphone (please complete the following information):**
 - Chrome on Android

**Additional context**

**Comment by Chwy5** [comment]
We have an existing ticket for this and closing this out
