### ISSUE TITLE
Sports betting.

### ISSUE THREAD

**Issue by harshvardhan-shah** [AugurProject/augur#8750]
In the section of Sports, there are only few of the sports mentioned. Mainly played in Europe and America. I was creating market under sports category but I couldn't found Cricket in the list of Sports.

I would like you to add Cricket, which has the HUGE betting base across the world.

And right now, international cricket is resumed, it would be great time to add cricket into the Sports section.

**Comment by matt-bullock** [comment]
I remember there was a reason we weren't able to add cricket as a template. @Chwy5 can you remember why?
