### ISSUE TITLE
Change copy within approval notices

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#8785]
![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/5bc87ebc-47a4-4e44-a56a-396fd2b86c7b)

Change this to:

**Approval required to create market**
Approval requires one signing. Once confirmed, click create.

---

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/6a25c097-fe89-42fb-9aa7-7cc9c41c3585)

Change this to:

**Approval required to trade**
Approval requires 4 signings. Once confirmed you can place your order.

---

Also required for pre-liquidity notice

---

![image](https://user-images.githubusercontent.com/39496225/89053278-431fe280-d357-11ea-99c7-1f0e8fa34d37.png)

Change this to:

**Approval required to create orders**
Approval requires 4 signings. Once confirmed you can submit your orders.

**Comment by Chwy5** [comment]
added -closing
