### ISSUE TITLE
Unclear instructions on augur.net

### ISSUE THREAD

**Issue by ShawnKimble** [AugurProject/augur#88]
It is not clear from augur.net if a 32 bit windows OS is supported by Geth, or if only 64 bit.  It would be helpful to know the user requirements.

Additionally the formatting of the command line startup instructions are difficult to decipher.  Cleaning up the formatting in the html page of what is text and what is command line data would be helpful.

**Comment by tinybike** [comment]
Thanks for the feedback.  I have tested geth a bit on 32-bit Linux (Ubuntu), and it seemed to work fine.  I have not tried it on Windows, though.

Agree re: the startup instructions.  Our blog has an extraordinarily limited set of features, and as far as I can tell does not allow preformatted text for code.  I think we should move the install instructions to their own mini-site -- Wordpress, probably -- and clean up the formatting.

**Comment by scottzer0** [comment]
There's built-in and clear install instructions if you run client.augur.net with an ethereum client running.
![screenshot 2015-07-05 09 14 45](https://cloud.githubusercontent.com/assets/934818/8512528/96c4c7be-22fb-11e5-8927-9dc96f613c7c.png)
![screenshot 2015-07-05 09 15 07](https://cloud.githubusercontent.com/assets/934818/8512529/9aaa09a2-22fb-11e5-90eb-75f69af6d138.png)

**Comment by ShawnKimble** [comment]
Thanks, I'll check it out

Shawn
