### ISSUE TITLE
Add trading form to mobile trading ui

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#881]
design:
<img width="729" alt="screen shot 2019-01-18 at 1 26 16 pm" src="https://user-images.githubusercontent.com/6775839/51413714-ae62e480-1b24-11e9-93fc-a7206b923e8a.png">

https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=1496%3A6663

also charts need to be put on mobile trading page ui

**Comment by joeykrug** [comment]
On mobile trading page the candlesticks timestamps /dates text on the x axis are all bunched up
