### ISSUE TITLE
Node parameters issue

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#882]
There needs to be a way to have the UI still allow optional node parameters, but to also work with no node url parameters and have the same default ones from augur app bundled with the UI

**Comment by nuevoalex** [comment]
By default the UI will use localhost:8545 for the ethereum node and localhost:9001 for the augur node. We can make the UI for production builds default to an alchemy endpoint for the ethereum node but what does this entail for the augur node endpoint?

**Comment by joeykrug** [comment]
It should have fallbacks, so by default try localhost, if that doesn't work, try any injected web3, if that doesn't work, try the hosted ones used on the ipfs site

**Comment by nuevoalex** [comment]
To be clear you're saying the augur node endpoint, when not specified through url params, should attempt localhost:9001 and then attempt to use augur.casino's hosted augur node?

**Comment by adrake33** [comment]
Summary from Discord: Let's just attempt to use localhost:9001 first and then switch to augur.casino's hosted augur node.

**Comment by andrewdamelio** [comment]
Some initial questions.

- Does this change reflect using hosted fallbacks for both the ethereum and augur nodes or just the augur node? 
**YES**

- Currently when we are unable to connect to a local augur and/or ethereum node we show a modal that allows the user to provide node addresses.  This change would remove this modal as the fallback, is that correct?
**YES**


<img height="125" src="https://user-images.githubusercontent.com/1683736/52790146-cfd7c300-3033-11e9-8f36-15005093bdd8.png">
