### ISSUE TITLE
Show Min/Max Fee Estimates

### ISSUE THREAD

**Issue by tomkysar** [AugurProject/augur#8821]
On order ticket, show minimum and maximum fee estimates, vs. just showing estimated maximum, ex: 
"Est Transaction Fee.........$6.45 to $9.87" or something along those lines.

- [x] Use the average of the Min/Max when calculating the "Unprofitable Trade" notice
- [x] Use the average of the Min/Max for the estimate in the Gas dialog

**Comment by nuevoalex** [comment]
Can be found in augur-sdk-lite/src/constants.ts: NORMAL_FILL

**Comment by Chwy5** [comment]
added - closing
