### ISSUE TITLE
Firefox displaying network mismatch even though MM is connected to Mainnet

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8825]
@MicahZoltu  reports Firefox Issue:

Latest UI in Firefox keeps telling me there is a network mismatch yet MetaMask is connected to mainnet.
MetaMask is connected to the wrong Ethereum network. Please set the MetaMask network to: undefined.
In the console I see:
Uncaught (in promise) Error: API must be initialized before use.
I also see:
web3 updated, network changed to 1
The network mismatch modal has no way to close it, I can only refresh.
No markets every load in Firefox w/ MetaMask either when loading from insecure context (localhost subdomain).
I don't see any failed requests in the network tab.
I see a Torus error in console.
I see some miscellaneous warnings in console but nothing that looks critical.
I see one error in console which doesn't sound critical but maybe is causing the initialization to generally fail.
The Notification permission may only be requested in a secure context.
I do see this warning which maybe is related:
asm.js type error: expecting argument type declaration for 'e' of the form 'arg = arg|0' or 'arg = +arg' or 'arg = fround(arg)'

**Comment by MicahZoltu** [comment]
Two other users in #general have reported that the app doesn't work in Firefox.  It is unknown if they are using localhost IPFS or hosted IPFS.

**Comment by MicahZoltu** [comment]
Firefox connected via CloudFlare gateway:
* When I connect, complains about wrong MM network despite being connected to mainnet.
* Error in console: `Uncaught TypeError: o is undefined`
* Error in console: `Uncaught TypeError: getStore().commit is not a function`
* Error in console: `Uncaught (in promise) Error: API must be initialized before use.`

**Comment by Chwy5** [comment]
Not seeing this in testing now
