### ISSUE TITLE
Display affiliate fee

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#8833]
https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=3037%3A0

![image](https://user-images.githubusercontent.com/39496225/89206397-8d080300-d5b9-11ea-94b9-81ebbb9aa984.png)

![image](https://user-images.githubusercontent.com/39496225/89206717-f9830200-d5b9-11ea-9133-f2ed4909c5c2.png)

**Comment by Chwy5** [comment]
added and fixed closing
