### ISSUE TITLE
Total Cost $/Total cost shares shows incorrect data with existing short position

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8834]
I sell 30 of outcome A so I have a short position of 30 @0.26
![image](https://user-images.githubusercontent.com/41301809/89206762-b90a9080-d587-11ea-880a-8b51df483aef.png)

I add an open order to sell 150 shares of outcome B @0.8

My Open orders shows shows a total cost of 24.000 and total cost for shares of 30
![image](https://user-images.githubusercontent.com/41301809/89206817-ccb5f700-d587-11ea-9a8b-be6002dcbd82.png)

**Comment by bthaile** [comment]
need to think how to differentiate if user is short other outcome or long the order outcome. Need to discuss. not working until algo is figured out.

**Comment by Chwy5** [comment]
fixed - closing
