### ISSUE TITLE
Custom market caution tag updated design 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#8836]
[link to tag design](https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=15546%3A767)

![image](https://user-images.githubusercontent.com/39496225/89210506-803add80-d5c0-11ea-9812-727630d14a60.png)

---

[Link to tag in context](https://www.figma.com/file/Do4qnkCNM8P7lwBmCdYZCS4X/Market-List-Page?node-id=4067%3A3912
)

![image](https://user-images.githubusercontent.com/39496225/89210288-26d2ae80-d5c0-11ea-8415-4aed7dc2eb0a.png)

**Comment by matt-bullock** [comment]
not seeing the updated version. Still see this:
![image](https://user-images.githubusercontent.com/39496225/89626583-eada6a80-d899-11ea-89e6-f4520f21a634.png)

**Comment by Chwy5** [comment]
Changed - closing
