### ISSUE TITLE
Add funds improvements

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#8837]
- [x] In the add funds conversion modal we should say something like “Have USDC, USDT, or ETH and looking to get a large quantity of DAI at lower slippage? Try https://1inch.exchange”
- [x] add usdt usdc dai <> eth uniswap to funds conversion modal

**Comment by pgebheim** [comment]
Related to: #8155

**Comment by Chwy5** [comment]
This is till an issue...bc we dont show approval which may now be required for this....Made new tickets for that and processing button issue added to 2.1.10 - closing this
