### ISSUE TITLE
candlesticks volume for a market, doesn’t match with market’s total volume

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#8839]
-  ~~add up all candlesticks volume for a market, doesn’t match with market’s total volume (not all of it is included in the candles for some reason), so there is some issue here~~ https://github.com/AugurProject/augur/issues/5731
-   ~~show liquidity score for markets on cards if available~~ https://github.com/AugurProject/augur/issues/8947
-  ~~Time Period based volume wrong on Augur Stats~~ https://github.com/AugurProject/augur/issues/5731
- [x] display the affiliate fee percentage in the UI per market

**Comment by pgebheim** [comment]
Related to #5731

**Comment by Chwy5** [comment]
show liquidity score for markets on cards if available - this number will ne converted into a % or a ranking (and if so Overall market ranking or ranking within its category)...it is some long number with a bunch of 0s.....Would need to design all this out.... This should be pushed t a later release - Created ticket 8947

**Comment by bthaile** [comment]
looks like candlestick charts match market trade history volume per outcome. 
I think market total volume is showing high. 

SDK processes `MarketVolumeChanged` logs which get added to the database. per outcome they do not match just adding up the outcome trading history

example, here is the volume returned from getMarketsInfo getter
outcome volume is 
outcome 1: 122.50
outcome 2: 172.32
outcome 3: 50.00

here is the trading volume by adding up market trades in market history:
outcome 1: calc trade volume is 102.5, 20dai off.
outcome 2: calc trade volume is 109.52, 62.80 dai off.
outcome 3: calc trade volume is 20, 30 dai off.


existing ticket for market volume not calculated corrected
<https://github.com/AugurProject/augur/issues/5731>
we can close this ticket
