### ISSUE TITLE
Word wrapping on trading page is broken on mobile

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#884]
Micah was seeing the following in Firefox on Android:

![Screenshot_20190119-073347__01.jpg](https://images.zenhubusercontent.com/5bff29dc5cb43a45a18add9f/891e21d3-ccf7-42ab-a85d-6dfe8cd9e28b)

Text is also cut off in mobile on Chrome:

![Screen Shot 2019-01-18 at 3.56.06 PM.png](https://images.zenhubusercontent.com/5bff29dc5cb43a45a18add9f/f04a1799-dcc5-4d4e-ab0e-15fb064ec5a1)

**Comment by pgebheim** [comment]
Was fixed sometime in the last year (verified in v1 ui, also @bconfortin recently did wrapping work in the v2 UI)
