### ISSUE TITLE
Trading issues

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#8840]
- [x] open order not disappearing from order book when a user gets filled while offline / has tab closed
- [x] open order not disappearing from open orders if a user exits after getting bell alert filled but before UI removes the open order
- [x] self trade fill not working right in UI, UI says failed but really succeeded

**Comment by Chwy5** [comment]
open order not disappearing from order book when a user gets filled while offline / has tab closed - fixed
open order not disappearing from open orders if a user exits after getting bell alert filled but before UI removes the open order - fixed
self trade fill not working right in UI, UI says failed but really succeeded - goes through for me
