### ISSUE TITLE
Order transaction failed on chain with "Cost of purchasing ETH to cover protocol Fee on the exchange was too high"

### ISSUE THREAD

**Issue by enolan** [AugurProject/augur#8841]
**Describe the bug**
I tried to enter an order to buy shares on the 0xE38f69f1ECbe8009a0F2baA44000E5bA9982948b market and the Augur app created a transaction which failed. [Here](https://etherscan.io/tx/0x2a2b6ffc73144c7fa3b5f4767eb166b27385c2b117d4f8e05407a9f039f5de6e)'s the Etherscan tx. I don't understand why it needs to purchase ETH in the first place, I have plenty in my account.

**To Reproduce**
1. Go to https://bafybeiertdulpp4dhkn66owmoqbf7piah2iokaqswnud4csjz66jnq627y.ipfs.dweb.link/#!/market?id=0xE38f69f1ECbe8009a0F2baA44000E5bA9982948b
2. Try to sell shares to the two currently open buy orders for yes.

**Expected behavior**
The transaction should succeed and I should end up with a bunch of no shares.

**Desktop (please complete the following information):**
 - OS: NixOS Linux
 - Browser: Firefox
 - Version: 77.0.1

**Comment by pgebheim** [comment]
The likely cause of this issue is that the transaction was estimated with a lower gas price with which it was submitted.

If there's not enough ETH the contract will attempt to swap DAI for ETH in order to cover the fee.

Were you using Metamask or one of the other wallets?

**Comment by enolan** [comment]
I was using Metamask.

**Comment by pgebheim** [comment]
Related to #8843

**Comment by pgebheim** [comment]
This should actually be fixed by #8845 -- there was a mistake in the gas calculation code.

**Comment by bthaile** [comment]
@enolan can you verify with newest release and re-open is it's still an issue

**Comment by enolan** [comment]
I have been able to successfully take orders on the latest release, though
I did stop changing the tx fee in Metamask.
