### ISSUE TITLE
Use max(eth_gasPrice, recommended) Gas when submitting transactions

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#8843]
- [x] should use max(eth_gasPrice, recommended) in UI as default vs solely one from provider otherwise will be too slow

Split this into two parts
#8841 - Upon first trade there should be a popup modal that says if you want to set your gas price to something different than the default, you should do so in account settings at the top right if you want to (with an image of it) and *not* to do so in your wallet otherwise it’ll cause your trade to fail.

**Comment by Chwy5** [comment]
@matt-bullock need modal

**Comment by pgebheim** [comment]
This is merged into 2.1.9
