### ISSUE TITLE
Cannot browse Augur in Brave without signing in

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#8859]
**Describe the bug**
When I try to browse an Augur market via a link in Brave (with local IPFS enabled, not sure if this matters), it prompts me to sign-in to my wallet.  If I don't sign-in' the following modal remains on screen and I cannot dismiss it.

**To Reproduce**
1. Navigate to https://bafybeicepxmifdzubuxyaxkwonadmdvlzpl6ys3bq3zxu6ys6odiz7e5fu.ipfs.cf-ipfs.com/#!/market?id=0xB5346FdaEAA9741Ca81FD428736cbd2BEE73a03D in Brave browser.
2. If prompted, say yes to enable Crypto Wallet for the site.
3. Notice that it pops up a window asking for your Brave Crypto Wallet password.
4. Close the password prompt.
5. Notice that the UI is just spinning waiting for sign-in.

**Expected behavior**
I expected the UI to not prompt me to sign-in until I clicked Connect.

**Screenshots**
![image](https://user-images.githubusercontent.com/886059/89244309-bcaa2000-d638-11ea-9d83-d872764ca986.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 79.0

**Additional context**
The real issue here is that Augur is trying to connect to MetaMask before I click the Connect button.  I don't know what triggered this behavior, but it should *always* wait for me to click Connect button in the UI before popping up an un-dismisable modal.

**Comment by Chwy5** [comment]
reopen if still seeing this
