### ISSUE TITLE
REPv2 often showing as REPV2. Should be consistent across UI

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#8868]
Example:

![image](https://user-images.githubusercontent.com/39496225/89270615-de58d680-d63b-11ea-8882-dc1286f921d2.png)

How it should look for consistency:

![image](https://user-images.githubusercontent.com/39496225/89271138-971f1580-d63c-11ea-8fc9-53d08d432cfd.png)

**Comment by bthaile** [comment]
I didn't find any REPV2. they might have already been fixed

**Comment by matt-bullock** [comment]
Account

![image](https://user-images.githubusercontent.com/39496225/89626246-638cf700-d899-11ea-8b9e-bcd13041e844.png)


Cards
![image](https://user-images.githubusercontent.com/39496225/89626315-7c95a800-d899-11ea-9ef6-8751ced79179.png)


Reporting
![image](https://user-images.githubusercontent.com/39496225/89626347-920ad200-d899-11ea-9b17-ad445d26860f.png)

**Comment by bthaile** [comment]
css is upper casing that text, reason we didn't find it in code.
