### ISSUE TITLE
New Trading Pg Burndown

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#887]
- [x] Price History Chart -displaying incorrect starting pt @justinbarry 
- [x] Price History Chart x-axis points sometimes overlaps each other @justinbarry 
- [x] Adjust number of x axis pts @justinbarry 
- [x] Market depth chart – math for total cost is incorrect – when clicking on pt on the bid side of market depth chart cost does not match Max loss in order ticket (see 1-21 binary price on bid side .2 volume 6 eth- cost shows 4.6 eth….max loss is 4.8 eth)
- [x] On Markets depth chart overlay – numbers and wording not lining up correctly….cost is at the very bottom- needs better spacing
- [x] Market depth chart - when volume is very small line blends in with x-axis (see screenshot)
![1-22mdc](https://user-images.githubusercontent.com/41301809/51562516-0026aa00-1e58-11e9-8f3a-55aef20d8712.jpg)

- [x] Dashes and dotting on Charts needs to be same size throughout pg
- [x] Order Ticket – won’t allow me to plug in Total Order value @bthaile 
- [x] When I currently have a long position and click on buy shares and add my quantity – the message on the order ticket for close position says “short” (though the profit shown looks to be correct- on retesting different ways info not always correct) @bthaile 
- [x] When I add quantity and price in the order ticket starting on "buy" in the order ticket and then switching selecting “sell” shares (the info in the order ticket remains) – In new Position The word Long just changes color, but should change words from Long to short. **Max Profit** and **Max Loss** doesn’t Update- still shows same value when buy was plugged in. Same issue occurs when starting from Sell shares and then clicking buy shares @bthaile 
- [x] Very long delay for "Total Order Value" to filter in after adding price and quantity to the order ticket @bthaile 
- [x] "Filled Orders" section needs to display users trading history - all their filled orders for that market (including taker orders) currently only displays maker filled orders
- [x] Open orders and filled orders must update together....If user A adds an order to buy 10 shares onto the order book and User B sells them 2. User A's open orders should now show 8 and Filled orders should show 2.  As User A continues to get their open order filled, filled orders and No of fills needs to update
- [x] Order ticket tooltip needs to have an (i) instead of a (?) @bthaile 
- [x] Scalar tooltip message needs to be updated @bthaile 
- [x] When viewing “connect a wallet to place an order” order ticket should be slightly visible in the background
- [x] Type size should match design so you don’t get ‘order’ widowed on the one line @phoebemirman 
- [x] Order ticket "Place Buy order" button can be  the green color it looks when quantity and price is entered(same as order book green) to start....balance out coloring on empty trading pg
- [x] PnL stuff
- [x] Fix Depth Chart hovers getting cut off
- [x] Change Buy/Sell order types to Bought/Sold @phoebemirman 
- [x] Total Order Value lags when switching between Buy Shares/Sell Shares tabs

- [x] Have consistent chart height, charts shouldn't push order form longer. @phoebemirman

**Comment by phoebemirman** [comment]
> Order ticket "Place Buy order" button can be the green color it looks when quantity and price is entered(same as order book green) to start....balance out coloring on empty trading pg

we need to consider what the order form will look like after the button is pressed and that users might want to be able to create multiple orders without signing the first one. 

we could also probably do with a message in the order form to remind them to "sign their transaction" because the mm pop up can get lost behind their window

@matt-bullock

**Comment by Chwy5** [comment]
>we need to consider what the order form will look like after the button is pressed and that users might want to be able to create multiple orders without signing the first one..............
Users Can't create multiple orders on the trading pg (with the exception of sweeping one side of the orderbook).....The only area where users will be able to create multiple orders at once in the future will be in the Market Creation - pre-liquidity section

**Comment by bthaile** [comment]
it's possible to create multiple order currently from market trading page. 
here is how:

populate order form, click buy|sell button.
when Meta Mask pops up ignore it.
populate order form again, click buy|sell button.
when Meta Mask pops up ignore it.
...
this can be done so that many many order transactions are queued up in Meta Mask. 
then click to get meta mask drop down in web browser top bar and click send for each of the transactions.

**Comment by Chwy5** [comment]
Unless I am misunderstanding this sounds like a Meta Mask issue and not an order ticket issue,

**Comment by bthaile** [comment]
I was just explaining how a user could make bulk orders.
