### ISSUE TITLE
Design QA - Add Migrate V1 to V2 REP button

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#8871]
Please, add "Migrate V1 to V2 REP" button on menu. It should only be visible for users that have REP to migrate.

<img width="1478" alt="Screen Shot 2020-08-04 at 07 45 09" src="https://user-images.githubusercontent.com/49915900/89285289-78158900-d626-11ea-9e50-90e3ac82f9e3.png">

<img width="397" alt="Screen Shot 2020-08-04 at 07 45 39" src="https://user-images.githubusercontent.com/49915900/89285315-82378780-d626-11ea-9edd-3d2a81114d05.png">

**Figma links:**

Desktop:
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=4404%3A1803

Mobile:
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=5287%3A613

**Comment by yanelbottini** [comment]
Visuals is ok, but not sure if functionality is working: 
I don't have REP to migrate, but I see the button. 
@Chwy5 Would you mind checking it?

**Comment by Chwy5** [comment]
This button is only supposed to appear if a user has v1 rep to migrate and I am seeing it when I do not have any to

**Comment by Chwy5** [comment]
Also not displaying correctly on mobile

**Comment by Chwy5** [comment]
This button no longer appears after i get legacy rep - so cant test this yet

**Comment by Chwy5** [comment]
Added-Fixed - closing
