### ISSUE TITLE
Design QA - My Account Empty States

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#8873]
**Your funds:**

- View transaction button has a different style (Both font and icon look different)
- "Get Rep or Add liquidity" button -> We need to delete it from Sportsbook
- Withdrawal button is not centered-aligned.

<img width="498" alt="Screen Shot 2020-08-05 at 07 41 51" src="https://user-images.githubusercontent.com/49915900/89403732-2ab11e80-d6ef-11ea-9cda-1ca112c4dcc4.png">

*Figma reference*
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7717%3A423

**Favorites:**

- Star icon is different
- Actions (Search, Status, Sort by) should be disabled as there is no content.
- Dropdown style is not accurate (Specially the dotted line) 
- Please improve spacing between elements (16px between icon, no space between text) 

<img width="963" alt="Screen Shot 2020-08-04 at 08 37 10" src="https://user-images.githubusercontent.com/49915900/89289516-bd898480-d62d-11ea-93a0-cab208436e30.png">

*Figma reference*
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7717%3A446

**My created Markets:**

- Actions (Search, Status, Sort by) should be disabled as there is no content.
- Dropdown style is not accurate (Specially the dotted line)
- Please improve spacing between elements (16px between icon, texts and buttons, no space between text) 
- Users can't create markets from Sportsbook, so content is different.  

<img width="898" alt="Screen Shot 2020-08-04 at 08 28 52" src="https://user-images.githubusercontent.com/49915900/89288759-8bc3ee00-d62c-11ea-87b8-f7e80b8f8703.png">

Figma reference:
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7718%3A12

**My active Markets:**

- Search should be disabled.
-24h should not appear as there is no info to calculate.
- Please improve spacing between elements (16px between icon, no space between text) 

<img width="941" alt="Screen Shot 2020-08-04 at 08 32 55" src="https://user-images.githubusercontent.com/49915900/89289134-1d336000-d62d-11ea-9375-3a53940209b1.png">

*Figma reference:*
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7717%3A555

**Notifications:**

- Please improve spacing between elements (16px between icon, no space between text) 

<img width="936" alt="Screen Shot 2020-08-04 at 08 34 28" src="https://user-images.githubusercontent.com/49915900/89289294-608dce80-d62d-11ea-97b7-a1187dfe3111.png">

*Figma reference:*
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7717%3A579

**Comment by JohnDanz** [comment]
https://github.com/AugurProject/augur/issues/7403

**Comment by yanelbottini** [comment]
Please, remove "Get Rep or..." from Sportsbook:

![unknown](https://user-images.githubusercontent.com/49915900/90253015-defd2400-de16-11ea-9ea6-fa69de3c01ba.png)

Missing Hover state for "View Transactions"... Should be underline as the other links that have same style.

**Comment by yanelbottini** [comment]
Please, disable Search while there are no items to show inside Favorites, My created markets, My active markets. 
Also, filtering options are missing disabled style (They should be grayed out)

<img width="950" alt="Screen Shot 2020-08-18 at 17 38 35" src="https://user-images.githubusercontent.com/49915900/90563094-abedc400-e179-11ea-9d78-380613350459.png">

**Comment by JohnDanz** [comment]
updated the icons on a PR but going to wait on Bruno's update to these components before I apply the changes to places other than my created markets (where everything is properly disabled correctly when empty). Mainly because it will only make Bruno's work harder if I attempt to change things now.

**Comment by matt-bullock** [comment]
They're still not greyed out when disabled. Make sure to use the greyed out state when disabled. See here https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7717%3A446

Applies to both favorites and my created markets

**Comment by matt-bullock** [comment]
looks good
