### ISSUE TITLE
Transaction fee modal to appear on first trade

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#8877]
[Desktop design](https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=2638%3A12676) 
[Mobile design](https://www.figma.com/file/RMXc7jUWiC6amxz9Q2JK5L/Onboarding-and-Wallet-UX?node-id=2638%3A12860)

![image](https://user-images.githubusercontent.com/39496225/89388832-dc0e7f00-d704-11ea-841d-f9a2024ef1ed.png)

**Comment by matt-bullock** [comment]
Current UX on staging is messy

Place order button should be disabled until approval signings have been made. 

Once approval signings have been made, the place order button can be activated. Then when place order button is clicked the modal can show.

--

Not sure if you've finished this or are just testing for the UX but most the design specs are off and you'll want to export that image at a higher res so it's not so blurry. Lets get get the end result in sync with design for a consistent product experience.


![image](https://user-images.githubusercontent.com/39496225/89388316-22afa980-d704-11ea-85e0-d83580a5dd7f.png)

**Comment by bthaile** [comment]
I thought there was a new design for order ticket. this needs to be closed

**Comment by matt-bullock** [comment]
yep, closing
