### ISSUE TITLE
Trader should be able to understand Invalid outcome tooltip

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#8884]
To make this more understandable: Use the normal tooltip with the once piece of information trades care about and tell them to click for more.

1. tooltip: 
"Invalid outcome pays $1.00 per share if the market resolves as Invalid. Click here to learn what makes a market Invalid"

use market's max price value instead of 1.00
for scalars use `resolves at xxx denomination`

2. Invalid rules put Augur Markets on top of invalid rules. 
3. change Augur Markets in Invalid Outcome text, change
to "Invalid outcome pays $1.00 per share for Yes/No and Categorical markets if the market resolves as Invalid. Scalar markets pay out the upper bound. A lower price indicates a lower probability of the market resolving as invalid."

**Comment by Chwy5** [comment]
If we chagne the tooltip how is anyone supposed to know what makes up invalid.....I wouldnt change this...
