### ISSUE TITLE
Augur App should warn in auto-update when a full resync is needed

### ISSUE THREAD

**Issue by nuevoalex** [AugurProject/augur#889]
When using Augur App and an auto-update is available it would be good to warn the user when the DB version of Augur Node they're using is less than the DB version for the Augur Node included in the updated version.

For example we are currently at version 3 in Augur Node, however the next release will need to do a full resync and will move to version 4.

Augur App should recognize this is the case and in the auto-update dialog warn that this update will require fully resyncing the database so users who wish to delay this may do so in an informed way.

**Comment by pgebheim** [comment]
@justinbarry be do you know how to do this in short order?

**Comment by justinbarry** [comment]
@pgebheim Somewhere here: https://github.com/AugurProject/augur-app/blob/master/src/main/check-for-updates.js#L35

**Comment by bthaile** [comment]
There is two cases to cover.

1. users skip over releases that are market as needing resync. We need to be able to detect and inform them that the update will need resync. 

2. user manually downloads version and they don't have an existing database of current version, we'll need to inform them they will have to do a full resync. This is less critical but they might be surprised and come ask questions.

#1, for auto-updater, we assume only the newest version will be downloaded. We need to send over the database version in the update information and check user's augur-1-`dbVersion`.db files in their data dir and see if they will have to resync if they update. Down the road NEWEST_DB_VERSION can be updated via build process (not sure how).

#2, proposal is to add static method to augurNode controller to return db version. Then we can check if the user has a version of augur-1-`dbVersion`.db in their db directory and inform them they need to do a full resync. This handles case.
