### ISSUE TITLE
need to optimize portfolio positions page.

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#890]
portfolio position page can lag while markets are getting loaded if user has many positions.

create many many many position on markets in various reporting states.

we are calling loadUserMarkets in load-markets.js
```
  augur.markets.getMarkets(
    { universe: universe.id, creator: loginAccount.address },
```
this gets all marketIds than we call `loadMarketsInfoIfNotLoaded` on all those marketIds which can take a long while to load and the user has to wait.

We need to refactor (like the reporting disputes page)

**Comment by bthaile** [comment]
This effort is extends across open / in dispute / resolved market collections and each have their own pagination. It'll take some time. The heavy traders will greatly appreciate it.

**Comment by bthaile** [comment]
since the portfolio page is going to be refactored we can close this. @adrake33

**Comment by bthaile** [comment]
Actually need to talk to Matt see how far out the position design is. This task could be released before the work on new positions redesign page is started. @adrake33

**Comment by adrake33** [comment]
Ah, yeah that's a fair point. Reopening this for now.

**Comment by bthaile** [comment]
closing, this isn't needed because of redesign
