### ISSUE TITLE
Design QA - Chat Style

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#8906]
Please update color style for chat. It should be white.

<img width="357" alt="Screen Shot 2020-08-05 at 08 52 52" src="https://user-images.githubusercontent.com/49915900/89409838-11ad6b00-d6f9-11ea-8d52-fa5ec037435c.png">

<img width="984" alt="Screen Shot 2020-08-05 at 08 53 06" src="https://user-images.githubusercontent.com/49915900/89409857-196d0f80-d6f9-11ea-85de-bef23a8dbb98.png">

Figma Reference:
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7396%3A92658

https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7396%3A92603

**Comment by matt-bullock** [comment]
![image](https://user-images.githubusercontent.com/39496225/95317087-f693de80-0894-11eb-9058-c13b2abeb479.png)


Still seeing the old style after clearing cache. Has update been pushed? @bconfortin

**Comment by bconfortin** [comment]
For some reason the tests are running for over 20 hours. It should've completed in like 15 minutes. I'll see what's up. @matt-bullock

**Comment by yanelbottini** [comment]
@bconfortin @matt-bullock 
I see it white now, as we planned for the Betting UI, but there are 2 things that could be improved:

- The color used for the press-state doesn't make sense here:
<img width="134" alt="Screen Shot 2020-10-07 at 17 10 06" src="https://user-images.githubusercontent.com/49915900/95382467-12f94080-08c0-11eb-9acf-385132f7d0a3.png">

Can we keep it as the hover?

- This hover state (bkg-opacity change) doesn't make sense here either. Can we just underline the "Global Chat" words?
![hover-global-chat](https://user-images.githubusercontent.com/49915900/95382645-56ec4580-08c0-11eb-8c2c-4bc00de346ca.gif)

**Comment by yanelbottini** [comment]
Ok!
