### ISSUE TITLE
Default to UTC for reporting.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#891]
**Is your feature request related to a problem? Please describe.**
Humans often assume that everyone in the world views time from the same point of view as they do.  They then proceed to create a market without specifying a time zone and this leads to confusion during trading, reporting and universe selection.

**Describe the solution you'd like**
Add a market creation/trading/dispute/universe selection tip of some kind that indicates that if a time zone isn't provided, then UTC should be assumed.

**Describe alternatives you've considered**
There has also been talk of using UTC+14 or UTC-12 (which IIRC are the two extreme time zones) but I think that UTC is simpler and already an existing standard.

**Comment by MicahZoltu** [comment]
Related to #538

**Comment by adrake33** [comment]
@joeykrug @Chwy5 @bthaile @matt-bullock Can you please discuss this and come up with a plan for how timezones should be implemented/displayed throughout Augur?

**Comment by joeykrug** [comment]
People should be able to select their own timezone in a settings menu on the account dropdown or page. Or on the dashboard. By default it should use the time zone their machine / browser is using.

It should allow 00 / UTC time and all the +-, so from UTC-12 to UTC+14 is the range. +0 is UTC time.

If no time zone is provided then default to 0 UTC

That's my first idea ^

**Comment by bthaile** [comment]
We need a site wide timezone selector and default to UTC. Might as well start a user setting section. We can add more settings as we design it out.

**Comment by adrake33** [comment]
As per Paul's recommendation, I created https://github.com/AugurProject/augur/issues/893 as an epic for timezone-related tasks.

 We also have https://github.com/AugurProject/augur/issues/538 for the design of the timezone setting. @matt-bullock Would you be able to create some mocks for a Settings section on desktop & mobile?

**Comment by MicahZoltu** [comment]
To clarify, the thing I'm interested in fixing is how people deal with dates/times that are entered into one of the text entry boxes.  This is a separate (but related) problem to how we deal with timestamps that the UI is aware of as time stamps.  For example, when someone creates the market, "Will X happen by the end of 2018?" the UI doesn't understand that `end of 2018` is a timestamp and thus cannot affix a time zone to it.  We need a way for traders and reporters to come to agreement on what timezone `end of 2018` is in.  The end time for the market may be January 3rd, 2019 but the market still needs clarity on the "end of 2018" bit.

For _this_ problem my recommendation would be to add a new Guideline, along with the other guidelines, that specifies that "if the question or description contains a date or time without a time zone, then UTC should be assumed."

**Comment by bthaile** [comment]
Could add something to market creation where we capture market makers timezone and value they used, of course endTime timestamp would be saved in UTC. 

Basically adding timezone dropdrown next to time in marke creation UI. Pretty easy to capture and parse in augur-node then make available to UI. 

Would that be a solution to your above problem statement?

**Comment by MicahZoltu** [comment]
That would solve the problem, but I worry that it makes the UX _harder_ for traders and reporters and I'm generally against favoring market creators over traders and reporters.  Humans really struggle with manual time zone conversions, and having everything in UTC at least makes it so traders and reporters only have to deal with _one_ other time zone besides their own.

Another option would be to allow market creators to do some kind of string templating so they can have a market like:
> Will X happen by the end of {YYYY: 2018}?
In theory something (contracts?  UI? AN?) would parse that and include a time zone so that the it could be recognized as a timestamp.  We could then have a guideline like, "If the question or details contains any timestamps that are not Augur-aware timestamps, then the market is INVALID.  This way we can ensure that any timestamps embedded within strings are properly time zoned.

**Comment by bthaile** [comment]
Side note: I like the idea of a list of market making templates. Templates that fit most common types of markets where makers can pick a solid template and fill in the details. 

Specific Timezone or UTC could be in their face and explained from the reports prespective. Also could chang endTime to ‘reporting begins’ I liked that suggestion from #issues channel.

**Comment by adrake33** [comment]
Market templates would be useful, but would take longer to implement. For this particular issue, let's just add another guideline as Micah suggested.

**Comment by adrake33** [comment]
We should still have a larger discussion about how to implement timezones going forward, but this would provide clarification to users in the shorter term.

**Comment by JohnDanz** [comment]
<img width="1057" alt="screen shot 2019-01-29 at 12 05 00 pm" src="https://user-images.githubusercontent.com/10524630/51930468-4469fb00-23c0-11e9-811c-c7450f786dee.png">

Is this something like what we are thinking for now? (2nd sentence before the bullet points is the new one)

**Comment by MicahZoltu** [comment]
Works for me.  Though, I would change it to just `UTC` and not `UTC-0` personally, but either will achieve the goal I think.

**Comment by MicahZoltu** [comment]
Maybe turn `UTC` into a link to https://en.wikipedia.org/wiki/Coordinated_Universal_Time in case anyone isn't familiar with it (seems unlikely, but links are cheap in HTML)?

**Comment by JohnDanz** [comment]
Yeah I was on the fence with `utc-0` vs `utc` and I was also thinking about a link, the reason I went with the -0 is we show in the end time the UTC-6 for example so i was trying to use the same format

**Comment by MicahZoltu** [comment]
If you wanted to get technical you could do `UTC±00:00`.  Also, do we really do UTC+1/UTC-1 rather than UTC+01:00 or UTC-01:00?  There are time zones that have half an hour, what happens if someone uses the website with such a time zone set?

**Comment by MicahZoltu** [comment]
Just tested, UI does `UTC+9.5` in that case.

**Comment by MicahZoltu** [comment]
> An offset of zero, in addition to having the special representation "Z", can also be stated numerically as "+00:00", "+0000", or "+00". However, it is not permitted to state it numerically with a negative sign, as "−00:00", "−0000", or "−00".

I'll once again vote for just plain ol' `UTC`.  ;)

**Comment by JohnDanz** [comment]
<img width="739" alt="screen shot 2019-01-29 at 12 55 05 pm" src="https://user-images.githubusercontent.com/10524630/51932635-2226ac00-23c5-11e9-886f-15122d210d70.png">

UTC it is, `UTC` itself is a link to https://en.wikipedia.org/wiki/Coordinated_Universal_Time

**Comment by Chwy5** [comment]
Yeah - looks good
