### ISSUE TITLE
Error when hotloading with metamask

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#8911]
This happens rarely if metamask is locked but user was signed in before.

I think this might be because useMM is set during the hotloading "createDefaultProvider."

Perhaps we can try and if we can that error we use the fallback?

**Comment by andrewdamelio** [comment]
@pgebheim I figured out finally how to reproduce this on my end... any idea where in the hot-loading logic we would be emitting this error?
 
cc @justinbarry 
![image](https://user-images.githubusercontent.com/1683736/90176190-97bf5680-dd76-11ea-9eed-95069ecd7cd9.png)

**Comment by andrewdamelio** [comment]
tracked it down to a web extension issue --- looking for a workaround/fix 

https://stackoverflow.com/questions/11811554/chrome-extension-port-error-could-not-establish-connection-receiving-end-does
