### ISSUE TITLE
Potential Bug with Reporting on Scalar Markest

### ISSUE THREAD

**Issue by P-Benesch** [AugurProject/augur#8916]
**Describe the bug**
There's a scalar market in open reporting right now entitled "What will the next Augur Warp Sync hash be?"  I think the proper outcome should be "invalid" (I hate to say it, but it's true).  However, when I try to report on this market, the interface only allows me to provide the correct value for the hash rate - "invalid" is not a potential option for reporting.  I think it must be a bug in the UI.

**To Reproduce**
1. Go to 'Reporting'
2. Scroll to 'Open Reporting'
3. Click on the "Report" button for the market entitled 'What will the next Augur Warp Sync hash be'
4. See error ("invalid" is not a potential reporting option)

**Expected behavior**
When I clicked report, I expected "invalid" to be an option alongside the potential hash value for the correct outcome.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 84.0.4147.105

**Additional context**

**Comment by pgebheim** [comment]
Could you post a screenshot? Currently on a fresh client I see this -- which is expected it it hasn't yet finished computing the hash.

![SmartSelect_20200805-132549_MetaMask](https://user-images.githubusercontent.com/86010/89460675-85fb0500-d71f-11ea-91e4-09fcf361fca8.jpg)

**Comment by P-Benesch** [comment]
Breaking up this email into two parts, since my last attempt got bounced back for being too large

> Begin forwarded message:
> 
> From: Peter Benesch <beneschpeter@gmail.com>
> Subject: Re: [AugurProject/augur] Potential Bug with Reporting on Scalar Markest (#8916)
> Date: August 5, 2020 at 4:37:50 PM EDT
> To: AugurProject/augur <reply@reply.github.com>
> Cc: AugurProject/augur <augur@noreply.github.com>, Author <author@noreply.github.com>
> 
> Weird, I don’t see that and I’ve been checking in on this market for a few days now (and I’ve never seen that).
> 
> Here’s what I see (same thing I’ve always seen):
> 
> 
> 
> [End email 1, continued in email 2]
>

**Comment by P-Benesch** [comment]
Email 2 (really part 2 of the prior email) below:

> And then when you scroll down:
> 
> 
> 
> Should I just report something (to demonstrate that I can)? I clicked confirm once and it sent me to a MetaMask confirmation for the transaction, so I think it would go through. If that would be helpful let me know (I can eat the transaction fee).
>

**Comment by P-Benesch** [comment]
Weird, I don’t see that and I’ve been checking in on this market for a few days now (and I’ve never seen that).

The first attached is what I see, and the second attached is what I see when I scroll down.

Should I just report something (to demonstrate that I can)? I clicked confirm once and it sent me to a MetaMask confirmation for the transaction, so I think it would go through. If that would be helpful let me know (I can eat the transaction fee).
<img width="1680" alt="Screen Shot 2020-08-05 at 4 32 25 PM" src="https://user-images.githubusercontent.com/47550171/89467332-61b11f80-d743-11ea-8342-3fbb388eb3c4.png">
<img width="1680" alt="Screen Shot 2020-08-05 at 4 35 52 PM" src="https://user-images.githubusercontent.com/47550171/89467370-71306880-d743-11ea-80e2-add6010a0ea5.png">

**Comment by P-Benesch** [comment]
By way of update - since my last post, someone reported on this market (entering the correct hash rate).  I tried to go in and dispute this outcome because (as I noted before) I believe this market is invalid, but when I click "dispute" and scroll down, "invalid" is not one of the "other outcomes" that I can select. I took another screenshot to show this:

<img width="1680" alt="Screen Shot 2020-08-05 at 8 15 10 PM" src="https://user-images.githubusercontent.com/47550171/89476422-a3989080-d758-11ea-85cf-0c8433f7128b.png">
