### ISSUE TITLE
Gas cost estimates wrong

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#8919]
Inflated everywhere, including places you wouldn't think they'd be like open reporting. UI says $15, MM says $10 for instance

**Comment by bthaile** [comment]
566,620 gas for initial report (DR) What is the gas price is the UI set to?
378,444 gas for open reporting. on kovan reporting form looks correct, actually might be showing a little low. 

More information is needed. what is `MM`?

**Comment by joeykrug** [comment]
metamask said 700k gas for open reporting report and $10, UI said $15 estimate for it, idk why, just try a few actions, UI always gives larger estimate than metamask and MM usually more correct

**Comment by Chwy5** [comment]
Handling gas estimates in simplified
