### ISSUE TITLE
notifications bog down

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#892]
UI really slows down when there are lots and lots of notifications. We need to investigate b/c we want heavy traders to have a speedy experience moving around the site. 

reported by DM

*So today I learned why my Augur app was always so slow. It was my notifications building up (I’ve done a lot of trades on Rinkeby). As soon as I hit “Dismiss All” the app magically became super fast. :rofl:
Maybe something worth looking into*

**Comment by phoebemirman** [comment]
i'm not seeing this happen. tested on dev with 40 notifications

**Comment by adrake33** [comment]
Closing this since it wasn't reproducible. @bthaile thinks the real issue might be the Portfolio Positions page.
