### ISSUE TITLE
Refresh sort by button

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#8926]
Once markets have hotloaded they may be out of sort by order. Adding this button gives the user the ability to refresh the markets by the current sort by settings/

### Design: https://www.figma.com/file/Do4qnkCNM8P7lwBmCdYZCS4X/Market-List-Page?node-id=4161%3A4844

![image](https://user-images.githubusercontent.com/39496225/89524341-ad67d580-d7e4-11ea-9a53-67d3092109a5.png)

![image](https://user-images.githubusercontent.com/39496225/89524280-945f2480-d7e4-11ea-8ae9-d559cc66c65b.png)

### Add tooltip on hover

![image](https://user-images.githubusercontent.com/39496225/89524488-f3249e00-d7e4-11ea-9d97-2d8c79ffb20a.png)

I'm not sure how instant this refresh will be. Do we need a progress indicator? The refresh button could turn into one

**Comment by Chwy5** [comment]
This is added, but not sure this is working correctly.  Isnt the list supposed to update correctly after hotloading?

**Comment by Chwy5** [comment]
added- working closing
