### ISSUE TITLE
Market hidden by spread filter even though it has an outcome with a spread of $0.10

### ISSUE THREAD

**Issue by enolan** [AugurProject/augur#8939]
**Describe the bug**
The market "Will Derek Chauvin be convicted of second-degree murder?" (0xb4E12A9283e9281d7445Bcb94EB801C4257261b0) has a bid of 0.15 & an ask of 0.25. However, it doesn't show up in the markets list if the liquidity spread filter is turned on.

**To Reproduce**
1. Go to the "Popular Markets" list and set the liquidity spread filter to "All"
2. Scroll down and find the market in question
3. Click it and verify the state of the order book is as I said
4. Go back and set the liquidity spread filter to "Less Than 20%"
4. Scroll through the markets and see it's not there anymore.

**Expected behavior**
The market should show up with the filter turned on. Unless it's the display of bid/ask and the order book that's wrong, in which case that should be fixed instead.

**Desktop (please complete the following information):**
 - OS: NixOS 20.03
 - Browser: Firefox & Chromium
 - Version: 77.0.1 & 84.0.4147.105 respectively

**Comment by Chwy5** [comment]
spread filter takes into account cost of doing tx
