### ISSUE TITLE
Make y-axis of Market Depth Chart, toggle-able to user to chose in shares or Eth 

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#894]
Have dropdown selection to allow user to views Market depth chart y-axis in shares or in eth.  Currently set to shares. Eth total cost can be viewed in hover modal.  Can be similar to what we are going to do for volume in candlestick chart

**Comment by pgebheim** [comment]
@JohnDanz Are you gonna complete this this sprint? Is this needed before release @bthaile @Chwy5 ?

**Comment by joeykrug** [comment]
already shows total dai anyways, closing
