### ISSUE TITLE
Show Liquidity score on Market Cards

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#8947]
Either as % or Ranking

Should be overall Market score imo as opposed to Category ranking

@matt-bullock need to design this out

**Comment by matt-bullock** [comment]
If you wanted to add this you would need to reduce the white numbers shown here to 10px medium font size and reduce the spacing between to 8px. See image:

![image](https://user-images.githubusercontent.com/39496225/90627582-70580600-e21c-11ea-9790-164d138b2393.png)

https://www.figma.com/file/Do4qnkCNM8P7lwBmCdYZCS4X/Market-List-Page?node-id=3783%3A10834

Recommend not adding to mobile to prevent the card becoming cluttered

**Comment by Chwy5** [comment]
closing
