### ISSUE TITLE
Finalize button is mislabeled as "View".

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur#8963]
**Describe the bug**
In the notifications section, the Finalize Warp Sync Market has a view button that should be labeled Finalize.

**To Reproduce**
1. Wait for the warp sync market to show up in notifications.
2. Put yourself in the shoes of a newbie.
3. Try to finalize by clicking on the bold market title.
4. Search futilely on the trading page for a finalize button.
5. Go back to the notifications list and look for a finalize button.
6. Fail to find one.
7. Hopelessly click view button, expecting it to take you to the same place as the market title took you.
8. Be surprised that it pops up a finalization prompt, rather than viewing the market.

**Expected behavior**
It should be obvious what I need to do to finalize the market.

**Screenshots**
![image](https://user-images.githubusercontent.com/886059/89700085-f0998400-d95d-11ea-87b2-9d6c7df3b3a7.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 79

**Additional context**
I have never finalized any other market, so maybe this bug extends to other markets as well.

**Comment by pgebheim** [comment]
Ah, all the notifications use the same view button.

**Comment by MicahZoltu** [comment]
Ah, I see.  "View" views the notification, while the text may contain links to other parts of the UI *besides* what the notification was for?

**Comment by MicahZoltu** [comment]
Can we hyperlink the word `finalize` in the notification text perhaps?

**Comment by pgebheim** [comment]
I actually think the button should say finalize if possible
