### ISSUE TITLE
augur hasn't been published to the ubuntu store

### ISSUE THREAD

**Issue by elopio** [AugurProject/augur#897]
Hello!

A few months ago my PR to enable continuous delivery from travis to the store, #821, was closed because it was making the .travis.yml too complicated. So, taking that and some other comments we got, we worked on a build and CD service that we hope will make the experience very very easy.

Please take a look at https://build.snapcraft.io/
It should help you setting everything up, and then you can let it deliver your latest software to all the ubuntu users out there, with no effort. It's in beta, so I would appreciate very much any comments you can give us.

pura vida.

**Comment by elopio** [comment]
Now that I'm maintaining the solidity project in the ubuntu store, I feel confident that I can maintain augur there too. If you don't want to set it up in build.snapcraft.io, I can take care of the continuous delivery. But the augur name was registered by @tinybike in the store. I would need to take ownership of that name (which I can do from the store), or I would need him to add me as a collaborator.

Please let me know if this is alright for you, and which way would you prefer to handle the augur name.

pura vida

**Comment by stephensprinkle** [comment]
Hi @elopio — 

We would like to have an automated build that deploys to the Ubuntu store (as well as others), but for now our efforts are being focused on wrapping up the new version of the UI.

I think snapcraft is very interesting, but I’ve not personally spent enough time to properly evaluate it.  

I’m opening a task to circle back once our backlog is cleared to look into this.  

Closing for now.

**Comment by stephensprinkle** [comment]
Tracking this here: https://app.clubhouse.io/augur/story/4457/investigate-setting-up-an-automated-build-w-snapcraft

**Comment by elopio** [comment]
Ok, let me know if I can help whenever you are ready.

pura vida.
