### ISSUE TITLE
List all Notification types needed in Account Summary and design all the required flows for these 

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#897]
Unsigned Orders: You have unsigned orders pending for the following market’s initial liquidity:.. Please review and submit or cancel these orders. 

Open Order in Resolved Market

Sell Complete Sets

Forking

Orphaned Orders
 
Market is entering another dispute round..?

Reporting for your market is soon to expire...?

**Comment by Chwy5** [comment]
Broken up into individual issues - closing this
