### ISSUE TITLE
Design QA - Back Icon Hover State

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#8984]
We need to include a hover state for the Back icons that are applied on both sidebar with categories and breadcrumb:

<img width="104" alt="default" src="https://user-images.githubusercontent.com/49915900/89917082-c6023200-dbce-11ea-8bb7-18b9275df3a9.png">
<img width="119" alt="hover" src="https://user-images.githubusercontent.com/49915900/89917088-c7335f00-dbce-11ea-86cc-8886f04ccfa2.png">

Square border should be #0E0E21

**Figma reference:**
https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet-Design-System?node-id=55%3A316

**Comment by matt-bullock** [comment]
looks good
