### ISSUE TITLE
Design QA - Slight misalignment when moving through Categories

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#8985]
When you enter to a sub-category, there a is a slight vertical misalignment. 
I have overlapped 2 images (a category and a sub-category) so you can see what I mean:

Sports and square with numbers are not aligned. 

<img width="516" alt="Screen Shot 2020-08-11 at 12 36 29" src="https://user-images.githubusercontent.com/49915900/89917816-a28bb700-dbcf-11ea-89f9-05ee3ed2c708.png">

**Comment by matt-bullock** [comment]
Looks good to me. @yanelbottini is this what you meant?

**Comment by yanelbottini** [comment]
Looks good!
