### ISSUE TITLE
Design QA - Please increase Account menu so refer a friend link is completely visible.

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#8992]
Increasing width in 20px should be enough to make the full link visible.  

<img width="347" alt="Screen Shot 2020-08-11 at 20 17 51" src="https://user-images.githubusercontent.com/49915900/89958219-bfe07580-dc0f-11ea-997d-1754dd308b4d.png">

**Comment by phoebemirman** [comment]
adding an ellipse. urls are too long and meaningless to show them in full

**Comment by yanelbottini** [comment]
ok!
