### ISSUE TITLE
Design QA - Modal Styles

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#8993]
Modal styles are not accurate:

![unknown](https://user-images.githubusercontent.com/49915900/90006627-a111cb80-dc6f-11ea-9a7b-a2fce30dd8d7.png)

- Background color is incorrect
- Background overlay should be dark, not white as it is now.
- Error message is not visible (Should follow same style than other error messages across UI)
- Double check font size and table style.

<img width="822" alt="Screen Shot 2020-08-12 at 07 51 06" src="https://user-images.githubusercontent.com/49915900/90007152-97d52e80-dc70-11ea-8b48-2a40b320dcaa.png">

**Figma Reference:**
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7396%3A90753

**Comment by yanelbottini** [comment]
Modal general style is correct, but table looks different:

- Please, double check line dividing header from rows (seems shorter)
- Header font looks thinner. 
- Rows should be taller. 
- Sell / Buy style is not accurate
- Buttons styles are not accurate

<img width="1138" alt="Screen Shot 2020-08-19 at 10 44 23" src="https://user-images.githubusercontent.com/49915900/90642607-fb2f0580-e208-11ea-9c69-9bc9c15103af.png">

**Figma reference:**
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7396%3A90753

**Comment by phoebemirman** [comment]
back/lay shouldn't show in sportsbook according to @Chwy5

**Comment by yanelbottini** [comment]
@phoebemirman @Chwy5 
It's correct that we don't have Back / Lay on sportsbook, but in this case, the modal is appearing because the user is the market creator, so he can add back / lay orders. That's why we need that label on the modal.

**Comment by yanelbottini** [comment]
Missing hover states for Delete and Cancel Buttons.
They should follow the Design system reference:

**https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet-Design-System?node-id=540%3A67
https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet-Design-System?node-id=540%3A67**

**Comment by yanelbottini** [comment]
Beautiful. Looks nice!
