### ISSUE TITLE
Design QA - Missing indication that ID was copied

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#8995]
Right now there is no indication that the Market ID was copied: 

<img width="312" alt="Screen Shot 2020-08-12 at 08 05 41" src="https://user-images.githubusercontent.com/49915900/90008415-a7ee0d80-dc72-11ea-9d0b-b6c3cdfe95c3.png">

Once the user clicks "Copy Market ID", could we update the text to say: "Copied!"

**Comment by yanelbottini** [comment]
Looks fine inside the market detail page, but It's not working fine on the market cards:

- Not showing the "Copied" status
- Not copying the full URL, just the #

![copy-issue](https://user-images.githubusercontent.com/49915900/94069049-5cc52f80-fdc6-11ea-9dc6-c753d01fec04.gif)

**Comment by JohnDanz** [comment]
mark cards aren't supposed to copy the full URL, it's just the author id or the market id -- that's by design.

I'll check the market details copy

**Comment by matt-bullock** [comment]
I think this should copy the full URL. In trading design we have this (although it probably was never built)
![image](https://user-images.githubusercontent.com/39496225/94285194-abec9b00-ff53-11ea-8855-370e1b0dfa14.png)

No reasons for the sportsbook to have complexity like author id or market id.

@yanelbottini  we need hover states for this menu. Can you add to here thanks

**Comment by yanelbottini** [comment]
Hi, this is the hover state created for this type of component:
**https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet-Design-System?node-id=55%3A316**
