### ISSUE TITLE
Design QA - Unify pages width

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#8996]
All pages on SportsBook and Betting Exchange should have the same width:

![width](https://user-images.githubusercontent.com/49915900/90009142-e932ed00-dc73-11ea-9204-9f59674a8fac.gif)

Also, there should be a max-width applied to the site. Right now if I see it on a 3000px resolution it goes like this:

<img width="827" alt="Screen Shot 2020-08-12 at 08 13 28" src="https://user-images.githubusercontent.com/49915900/90009242-1b444f00-dc74-11ea-806c-a2075e76987c.png">

Please, reference to Responsive page on Figma to see how it should behave on big resolutions:
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7654%3A270124

**Comment by JohnDanz** [comment]
@yanelbottini we had this in, but i've reverted it as it didn't come out the way I think we intend. need some more time to review this as we haven't finished up responsive work on some of these pages so it breaks them when forced to be small and after reviewing it the width of the market cards on the markets page for example are a full 100 px less wide than the mocks, so we need to just rethink how we plan to apply this.

**Comment by yanelbottini** [comment]
@JohnDanz Thanks for the update. No pb, let me know when ready!

**Comment by yanelbottini** [comment]
Still seeing different width: 

![page-width](https://user-images.githubusercontent.com/49915900/95915907-3ae41a80-0d7e-11eb-9198-9b03e94bab25.gif)

**Comment by matt-bullock** [comment]
looks good to me
