### ISSUE TITLE
Design QA - Error message width

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#8999]
Error message box should have same width than site. Rigth now seems bigger:

<img width="1571" alt="Screen Shot 2020-08-12 at 08 29 03" src="https://user-images.githubusercontent.com/49915900/90010257-f3ee8180-dc75-11ea-8cee-69a20ddd1dd3.png">

**Comment by phoebemirman** [comment]
looks right to me
<img width="907" alt="Screen Shot 2020-09-23 at 7 42 47 AM" src="https://user-images.githubusercontent.com/6775839/94028091-6a4fca80-fd70-11ea-9184-27be88665e65.png">

**Comment by yanelbottini** [comment]
- Still using the dropdown component from Trading:

<img width="283" alt="Screen Shot 2020-09-23 at 18 04 38" src="https://user-images.githubusercontent.com/49915900/94069607-453a7680-fdc7-11ea-998e-f0be73248a65.png">

**Comment by matt-bullock** [comment]
same. closing
