### ISSUE TITLE
SEO Updates: Content 

### ISSUE THREAD

**Issue by ghost** [AugurProject/augur#901]
## General Content:

- Create a "Prediction Markets Explainer" on site post and add to the main landing page. 
- Review landing page content + add way more content (target 2500 words, currently at 500 but sites with ~2500 are the average for #1 rank on Google)
- Get some blog posts out explaining things like prediction markets and for other keywords and get them highly ranked. 
- Regularly publish blog posts like 2-4 a month, both about informational stuff  *and* about engineering stuff. 

## Dev Content: 

- Get a bi-weekly development blog post written by an engineer. We've had this planned for a while, someone needs to step up and write the initial one. Should have at minimum, two a month. cc: @pgebheim

**Comment by ghost** [comment]
Content writer is submitting initial draft of PM overview post to me on this upcoming Sunday. Will have him work on additional topics as well. 

- "What are Prediction Markets?" // "Prediction Markets Explainer" 
- "What is the Oracle Problem?"
- "How to use Augur" 

We need to kick off development blog posts. An engineer should draft even a 500-1,000 word post about some engineering topic, and hand it off to me - I will bake it into Augur.net appropriately.

**Comment by pgebheim** [comment]
@tomkysar -- Can we start getting Ben to do these? how can I support?

**Comment by joeykrug** [comment]
Ongoing
