### ISSUE TITLE
Bell alerts replication Bug

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#9011]
I placed this order one time, but shows the same bell/toast multiple xs

![image](https://user-images.githubusercontent.com/41301809/90134710-96bf0280-dd3f-11ea-913b-f1c116e27dcc.png)

**Comment by Chwy5** [comment]
fixed - closing

**Comment by Chwy5** [comment]
This is happening again

**Comment by phoebemirman** [comment]
Waiting until @andrewdamelio is done with his updates to take a look at this

**Comment by phoebemirman** [comment]
not seeing this. are you still seeing this @Chwy5 ?

**Comment by Chwy5** [comment]
no - closing
