### ISSUE TITLE
SEO Updates: Augur UI

### ISSUE THREAD

**Issue by ghost** [AugurProject/augur#902]
## General: 

* [ ] ~~Test Google indexing after making these changes (+1 or 2 days later) by searching **"site:IPFS_ROOT_URL"** and see how markets and etc are being indexed, ensure descriptions, tags, titles and etc are reflecting these changes.~~ Test how google bot indexes by using the chrome devtools (Ctrl+P, network conditions; set user-agent to google bot), test against ipfs as well (v2-ipfs.augur.net points to the ipfs hash; try against cloudflare-ipfs.com)
* [x] Implement and deploy a sitemap that tells Google how to navigate all the URL paths the Augur webapp. 
* [x] Add meta tags that make the app mobile native when saved to mobile homescreen, and add the pop-over notification for mobile users to download the page to their homescreen for a native app experience. (@tk will take care of this and submit a PR).
* [x] Use / add the term "Prediction Markets" wherever you can, while still looking native, clean, and appropriate. Don't try to fit a round peg into a square hole, but use the term as frequently as possible as long as it makes sense. 
* [x] Review loading speed times for the in-app Javascript, figure out how to make it load faster (check with Google Pagespeed tester). 
* [x] See if its possible to add a paragraph of content (~500 words) to the homepage of the Augur UI. Maybe a pop-up prior to the disclaimer with a TL;DR of Augur and how it works, or a quick paragraph about how to get started. They dismiss this popup, get shown the disclaimer, then are free to use the app. Flexible on this, but ideally we have a paragraph of some content on the landing UI page. 
* [x] Figure out a method for not passing node parameters in the URL - but bundle them within the UI somehow, and have additional optional parameters for nodes. 
* [x] Use HelmetJS for any meta title, description, tags, etc updates -- probably the best method for doing this all. 
* [x] Reorganize and add missing headers (h1…h6) in all pages.

## Stable Loader
**The stable loader exists -- why would we want to pass in another IPFS hash? I think we really just need to validate that the stable loader page works**

* [x] Wrapper for the UI to check a reference of what the latest UI version is (ex: on Github somewhere) and have it load automatically (but support passing parameters to use a different IPFS hash), while still supporting URL parameters for nodes and links for the react stuff once it loads the actual UI by passing it all through. 

## Markets Page (markets' list):

* [x] Update page title (50–60 characters - " | Augur" adds 8 characters). Should be something like: _”Prediction markets for sports, politics, crypto and more | Augur”_
* [x] Update page description (155–160 characters). Could be something that talks about the most popular markets of the year like winner of the elections, of a famous sport’s game or the price of a popular cryptocurrency at the end of a timeframe
* [x] Update meta tags for Facebook Open Graph (title 60-90 characters and description around 200 characters) and Twitter Cards (title 70 characters and description around 200 characters).
* [x] Use headers (h1, h2, h3) to identify the page and for the markets’ title.

## Market Page: 

* [x] Add meta canonical link tags: including the first word after the #! and market ID if there is one, but no other parameters. As clean as possible. 
* [x] Update page titles (50–60 characters - " | Augur" adds 8 characters): _"Primary Keyword - Secondary Keyword | Brand"_ - Truncate primary keyword / market title so the entire title is sub 60 characters. **(ex: "Will the price of Ethereum exceed $200 at the end of January 2019? - Cryptocurrency | Augur Prediction Markets")**
* [x] Update meta description (155–160 characters): currently, the market uses the default Augur page description in the header. This should be updated to reflect the description of the market. **(ex: "Will the price of Ethereum exceed $200 (USD) at the end of January 2019, UTC, according to last trade price average across the top five eth markets?”)**
* [x] Update meta tags for Facebook Open Graph (title 60-90 characters and description around 200 characters) and Twitter Cards (title 70 characters and description around 200 characters).
* [x] Use **h1, h2 and h3** tags for market title, market description, and market keywords. 
* [x] Add a URL parameter for the stage of reporting a market is in, so Google can index markets in reporting. **(ex: ".../market?id=0xf4f35c7909d6496779c390abbe71b5fc6353614c?=dispute")**

## Reporting Page: 

* [x] Update page title (50–60 characters - " | Augur" adds 8 characters): currently, the page title doesn't update when navigated on the account page. The title should update to reflect the page being viewed. **(ex: “Reporting - Short description of what reporting is | Augur")**
* [x] Update meta description (155–160 characters). Should be updated to reflect the description of the page. **(ex: "Report on active Augur markets - long description of what reporting is”)**
* [x] Update meta tags for Facebook Open Graph (title 60-90 characters and description around 200 characters) and Twitter Cards (title 70 characters and description around 200 characters).
* [x]  Use **h1, h2 and h3** tags for page title and page description.

## Disputing Page:

* [x] Update page title (50–60 characters - " | Augur" adds 8 characters): currently, the page title doesn't update when navigated on the account page. The title should update to reflect the page being viewed. **(ex: “Disputing - Short description of what disputing is | Augur")**
* [x] Update meta description (155–160 characters). Should be updated to reflect the description of the page. **(ex: "Dispute on active Augur markets - long description of what disputing is”)**
* [x] Update meta tags for Facebook Open Graph (title 60-90 characters and description around 200 characters) and Twitter Cards (title 70 characters and description around 200 characters).
* [x]  Use **h1, h2 and h3** tags for page title and page description.

## Create Market, Account Summary and Portfolio Pages: 
Not accessible unless you are logged in, so web crawlers do not have access to it. Users will still have access to this page, so we have to at least update their titles.

* [x] Update create market page title (50–60 characters - " | Augur" adds 8 characters).
* [x] Update account summary page title (50–60 characters - " | Augur" adds 8 characters).
* [x] Update portfolio page title (50–60 characters - " | Augur" adds 8 characters).

## Category Page: 
Doesn’t exist anymore.

**Comment by ghost** [comment]
Unclear on how the best way to address this all is, however I broke it down into as many specific changes that need to be made as possible. I am going to handle the landing page (#903), new content (#901) - however probably best I don't handle react stuff 🙃 

cc: @joeykrug @bthaile @justinbarry @adrake33 

Let me know if anything needs additional details or is unclear!

**Comment by joeykrug** [comment]
This seems very daunting, but it's not what it seems, I estimate 80% can be done in a week, so I'd say we do that then make separate issues for any tasks that end up being bigger ones

**Comment by adrake33** [comment]
We need to finish the Chrome 41 issue (https://app.zenhub.com/workspaces/augur-5bfed3424b5806bc2bf8d173/issues/augurproject/augur/854) first. We'll also need to discuss this ticket more to ask questions & discuss who's doing what before starting on it.

**Comment by joeykrug** [comment]
Probably 35 of these can be done with https://github.com/nfl/react-helmet

**Comment by justinbarry** [comment]
@joeykrug How we bundle the client might be increasing the load time.

<img width="493" alt="image" src="https://user-images.githubusercontent.com/328965/52439623-e2507a80-2ad0-11e9-8336-610ad0044405.png">

The bundles are defined here: https://github.com/AugurProject/augur-ui/blob/master/src/modules/routes/constants/components.js

**Comment by pgebheim** [comment]
We need to update this for current steps for v2 but still a good list of ideas of where to start.

**Comment by pgebheim** [comment]
@bconfortin -- I think for 


> Add meta tags that make the app mobile native when saved to mobile homescreen, and add the pop-over notification for mobile users to download the page to their homescreen for a native app experience. (@tk#1337 will take care of this and submit a PR).


@tomkysar means to add the following (correct me if im wrong)
```
<meta name="apple-mobile-web-app-capable" content="yes">
```

**Comment by pgebheim** [comment]
For 

> Add meta canonical link tags: including the first word after the #! and market ID if there is one, but no other parameters. As clean as possible.

I am assuming you want to make the link be like
```
<link rel="canonical" href="https://cloudflare-ipfs.com/ipfs/[[ the ipfs hash of the stable loader ]]/#!/market?id=0xdeadbeefdeadbeefdeadbeefdeadbeef" />
```

Question: Does this work if routes are generated dynamically via javascript?

@bconfortin -- does React-Helmet support changing this as routes change?

**Comment by bconfortin** [comment]
I believe we can use Helmet for that injection

Em qui, 27 de fev de 2020 às 19:11, Paul Gebheim <notifications@github.com>
escreveu:

**Comment by joeykrug** [comment]
that's right re canonical

**Comment by pgebheim** [comment]
@andrewdamelio @bconfortin  -- major issue with seo right now is that we dont get IDB support in google bot. In order to make the site work at all I think well need to use:
https://github.com/dumbmatter/fakeIndexedDB or something similar.

**Comment by pgebheim** [comment]
@andrewdamelio Has pointed out that google bot setting in chrome seems to render this properly.

I am trying the web console and currently it fails to render and it appears to only get as far as the ASM.js "Syntax Error" issue. If the useragent is google bot we should disable 0x mesh (at the config level) before calling createApi. Perhaps that will solve the issue and the we can see what happens next.

**Comment by pgebheim** [comment]
![image](https://user-images.githubusercontent.com/86010/78811559-e4d18d00-797e-11ea-9626-742c7248c2cd.png)
Currently google search console says it can't load the vendor bundle.

Perhaps this is a size issue?

**Comment by pgebheim** [comment]
Did more testing today. I believe the issue is currently the size of the vendor bundle. I'll look into splitting it to test whether Googlebot will manage to dowload it

**Comment by pgebheim** [comment]
the `<link rel='canonical' ...>` looks to have been added by React Helmet.

**Comment by pgebheim** [comment]
We're STILL wrestling with getting google bot to load the app. @robert-e-davidson3 had some ideas around a hack that would load / show the data without much of the SDK at all, so that could be shipped with the initial bundle and then get the whole SDK dynamically. Maybe this would make the page renderable by google bot?

**Comment by pgebheim** [comment]
Closing this mega-issue and making a specific issue for googlebot

**Comment by pgebheim** [comment]
Market page now loads -- finally making issue just for market list
