### ISSUE TITLE
Design QA - Transaction Fee Modal

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9032]
As you switch between the different options, boxes change size

![transaction-fee](https://user-images.githubusercontent.com/49915900/90396189-27f9e600-e06c-11ea-99f6-a8d7ae542458.gif)

- Please update modal style to match the rest of modals on Betting UI: No border line and incorrect close icon.
- Please check text-colors, because some seems to be taking colors from Trading UI.
- "Advance" button doesn't match Betting UI. Should follow this style:
https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet-Design-System?node-id=561%3A4371

**Comment by Chwy5** [comment]
This is still doing this.....

It stays the same size going from fast to slow (or slow to fast), but jumps around (looks like it increases the size of the whole modal) going from recommended to slow(or fast) or from Slow(or fast) to recommended

This is bc the red warning message increases from one line of info to 2- closing this
