### ISSUE TITLE
Design QA - Placing a bet, Wager field

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9044]
Right now when a user submit a bet on the Betslip, "Wager" field is populated with the max order amount available, but this behavior is incorrect: The user should enter the amount of $ he wants to bet, so it would be like this:

<img width="384" alt="Screen Shot 2020-08-18 at 07 12 42" src="https://user-images.githubusercontent.com/49915900/90501162-4ae6d180-e122-11ea-8851-959889e2683b.png">

**Comment by matt-bullock** [comment]
much better. closing
