### ISSUE TITLE
augur-app should support warp sync files generated by CLI augur-node

### ISSUE THREAD

**Issue by ryanberckmans** [AugurProject/augur#905]
Right now if you import a warp sync file that was generated by augur-node command line, the import will succeed, but augur app will fail silently in UI, and console shows fatal DB error "migrations missing".

The root cause is that augur-node CLI runs off a typescript source tree, and augur-app uses compiled augur-node and runs off javascript source tree.

The DB table `knex_migrations` has a log of the file names of migrations that have been applied to the DB. When augur-node is run from CLI, these file names end in `.ts`. For augur-app they end in `.js`.

Tom Haile and I designed a fix where an idempotent query is applied to the warp sync file when it's written to disk.

Applying the fix when warp sync is written, and not read, has the desirable property that warp sync files will have the same hash for `(block, augur node version)` regardless of how the warp sync file is generated.

Here is the query that needs to be run so that a warp sync file generated on augur-node cli is compatible with augur app import:

```
sqlite3 warp-sync.db "update knex_migrations set name = substr(name,1, length(name)-2) || 'js';"
```

**Comment by ryanberckmans** [comment]
Assigned to @bthaile per his request.

**Comment by bthaile** [comment]
Whats the best way to kick off this script from augur-node process? Because the warp sync file operation will need to know the script has finished and can continue to hash and rename the file.
