### ISSUE TITLE
Market missing after creating it - bug

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#9052]
I create a market and get bell message for it but doesnt show up in my created markets (in trading or SB)

![image](https://user-images.githubusercontent.com/41301809/90526836-dc643c80-e13e-11ea-9b66-2bddbdf527c4.png)

**Comment by Chwy5** [comment]
I do get the notification for "Sign to approve pre-liquidity orders) just my market doesnt appear in My created markets
![image](https://user-images.githubusercontent.com/41301809/90527673-cb67fb00-e13f-11ea-9e6c-b9cc5f88a9b0.png)


I also see my market in the Popular markets list

**Comment by JohnDanz** [comment]
![image](https://user-images.githubusercontent.com/10524630/90547215-c2335a00-e150-11ea-9d80-4af79696b345.png)
I'm seeing this working fine this morning, will keep an eye out for this though. potentially just a bad state for the example you found?

**Comment by Chwy5** [comment]
fixed -closing
