### ISSUE TITLE
My active markets - 24 hour change percentage to sit to the right of each market outcome, next to expand button

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9053]
Currently it sits over to the far left in the build. The % and value is mising...see screenshot

Currently looks like this
![image](https://user-images.githubusercontent.com/41301809/90918729-32411a80-e3b3-11ea-87db-8097359fe726.png)

should look like:
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=3606%3A1015

![image](https://user-images.githubusercontent.com/39496225/90527094-7349ec80-e171-11ea-8b67-dbdfa6e1c565.png)

**Comment by yanelbottini** [comment]
Position is fine!
