### ISSUE TITLE
My Created Markets should only show SB created Markets

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#9055]
![image](https://user-images.githubusercontent.com/41301809/90557425-755b7d80-e168-11ea-8ae6-0468a3a05c85.png)

**Comment by matt-bullock** [comment]
Not seeing any markets in my created markets. Created both sportsbook and non-sportsbook to test

**Comment by matt-bullock** [comment]
Only seeing sportsbook now which is correct. Closing
