### ISSUE TITLE
Migrate Rep button not appearing after hitting legacy rep 

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#9057]
Be on trading pg...hit legacy rep button ( I am not getting a toast confirmation or the migrate rep button doesnt appear, but in the console it says success for faucet tx when i do it

**Comment by JohnDanz** [comment]
I might ignore the faucet toast -- it's only for development anyway so I don't wanna add code for something that isn't even important for the real live product if it doesn't really matter to much. if it's simple sure, but I'm not gonna focus too hard on that. as for why the migrate button doesn't appear, that's a bug and will fix.

**Comment by JohnDanz** [comment]
yeah no notification for getting the legacy rep (just metamask) but the button will now appear/disappear immediately when you gain or lose legacy rep and there is a notification when you successfully get the latest version of REP after migrating.

**Comment by matt-bullock** [comment]
Button is appearing now so I'll close
