### ISSUE TITLE
Design QA - Missing Dropdown Style on My Account section

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9059]
All the dropdown menues (when showing options) don't have the proper style:

<img width="529" alt="Screen Shot 2020-08-18 at 17 28 18" src="https://user-images.githubusercontent.com/49915900/90562208-38978280-e178-11ea-804c-5c3ef58f5da2.png">

**Figma reference:**

Example
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=8024%3A279519

Full reference of the component status (Hover, selected, etc)
https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet-Design-System?node-id=561%3A4371

**Comment by yanelbottini** [comment]
Almost there. Can we align texts?
It's happening across most dropdowns:

<img width="859" alt="Screen Shot 2020-09-25 at 16 57 06" src="https://user-images.githubusercontent.com/49915900/94310558-3501d300-ff50-11ea-936f-d7d3abeba611.png">

**Comment by matt-bullock** [comment]
text looks aligned now
