### ISSUE TITLE
Migrate Rep Button on SB not too visable

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#9064]
Need to make it darker...

![image](https://user-images.githubusercontent.com/41301809/90634246-67a00980-e1f5-11ea-9809-22cb8b056196.png)

**Comment by yanelbottini** [comment]
@Chwy5 @matt-bullock 
I don't have REP to migrate. Maybe you can help me with this one?

**Comment by bconfortin** [comment]
@yanelbottini In the Trading UI, go to the Account Summary page and click on the button that says "Legacy Rep Faucet"

**Comment by yanelbottini** [comment]
Thanks @bconfortin!
Issue is ok, but can we please center-align this block of text. The one that says: "Est. Tx Fee .... $0.23"
 
<img width="409" alt="Screen Shot 2020-10-08 at 06 01 00" src="https://user-images.githubusercontent.com/49915900/95437681-a7e55380-092b-11eb-8fb1-f54627fef1ea.png">

**Comment by Chwy5** [comment]
yes - closing
