### ISSUE TITLE
New onboarding flow

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9068]
**Flows**
That have been worked through (these may change depending on what is is technically possible)
https://www.figma.com/file/mhImzKiTrvaMpSm1lQ5KcL/New-Onboarding-Flow?node-id=0%3A1

**Screens and components**
(these are all the screens used throughput the various flows and their different interaction states)
https://www.figma.com/file/mhImzKiTrvaMpSm1lQ5KcL/New-Onboarding-Flow?node-id=71%3A20259

**Prototype showing some of the interactions within the flows**
https://www.figma.com/proto/mhImzKiTrvaMpSm1lQ5KcL/New-Onboarding-Flow?node-id=30%3A2749&viewport=1173%2C-926%2C0.20209833979606628&scaling=min-zoom

Reach out to me if anything doesn't seem right / has been missed

**Comment by andrewdamelio** [comment]
this is testable on `https://staging.augur.net/#!/markets` @matt-bullock
