### ISSUE TITLE
Design QA - Alerts

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9077]
- "Clear All" style is incorrect (Left design, right dev)

<img width="836" alt="Screen Shot 2020-08-20 at 09 29 01" src="https://user-images.githubusercontent.com/49915900/90770076-a1d9db80-e2c7-11ea-9301-b653f006ff41.png">

- Missing Hover states on boxes and close icon
- Close icon is different
- Missing Hover state on View Ethernet link (Should be underline)

<img width="1303" alt="Screen Shot 2020-08-20 at 09 29 55" src="https://user-images.githubusercontent.com/49915900/90770484-3a705b80-e2c8-11ea-820f-7144b9dff7d6.png">

**Figma reference:**
https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet-Design-System?node-id=283%3A145

**Comment by matt-bullock** [comment]
only looks like the close button is missing its hover state

**Comment by matt-bullock** [comment]
looks good
