### ISSUE TITLE
Notification not disappearing after they have been done (refresh bug)

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#9079]
I claimed my Rep from the"Claim stake and Fees" got a bell message and my balance updated, but after the action button said confirmed...the notification didnt go away...It goes away if I refresh the pg

![image](https://user-images.githubusercontent.com/41301809/90777052-eb76f600-e2c8-11ea-91c0-5fe86f012711.png)

**Comment by matt-bullock** [comment]
This is working now but there was a slight lag. Seems to be an issue throughout a lot of dev. Closing this ticket
