### ISSUE TITLE
Local TestNet setup won't start for v2 branch

### ISSUE THREAD

**Issue by nuliknol** [AugurProject/augur#9080]
running the following commands:

```
docker kill $(docker ps -a -q);
docker system prune -af
yarn clean
yarn
yarn build
yarn docker:all

```
Will produce the error :

` {"error_string":"Post http://geth:8545: dial tcp: lookup geth on 127.0.0.11:53: no such host","level":"error","msg":"blockwatch.Watcher error encountered","myPeerID":"16Uiu2HAkwRKndauCzvdKmdCEtytvUihzuvHvUNNdNFssgMf9zjV5","time":"2020-08-20T15:32:48Z"}
`
![local_testnet_setup_failure](https://user-images.githubusercontent.com/1125368/90793925-c76be280-e2d1-11ea-8d14-450629cbc75d.png)

Git branch: v2
Latest commit: 00b97bef1ed9676bb86eb36e5503746eb6bbf270 of 14 August

**Comment by robert-e-davidson3** [comment]
The network name changed for some reason (git plugin update maybe?). In the linked PR I moved everything to use the new network name. Along with some other fixes.

**Comment by nuliknol** [comment]
@robert-e-davidson3 thanks! However it is still not working there is a new issue I opened here: https://github.com/AugurProject/augur/issues/9162
Connecting to 127.0.0.1:60557 won't pull open orders though there exist some.
