### ISSUE TITLE
My Bets section - Wager & Odds displaying incorrectly

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#9087]
Looks like the Odds in the My bets section are rounding to the whole number

![image](https://user-images.githubusercontent.com/41301809/90887767-f2623f00-e382-11ea-9cdb-03e6e4259c2c.png)

In Active Bets (in betslip) shows Full odds (in decimal format)
![image](https://user-images.githubusercontent.com/41301809/90887670-cd6dcc00-e382-11ea-9cb4-d34c67329165.png)

**Comment by yanelbottini** [comment]
Beautiful! Looks nice.

**Comment by matt-bullock** [comment]
Still seeing the rounding to whole number issue in my bets

**Comment by matt-bullock** [comment]
Fixed. closing
