### ISSUE TITLE
Betslip should be sticky to follow the user down the page

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9092]
Reopening because issue has reappeared

**Comment by phoebemirman** [comment]
leaving in design review while we wait for new mocks for logged out view

**Comment by yanelbottini** [comment]
@phoebemirman We've prepared the mockup with the small banners:

https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7654%3A270124

**Comment by matt-bullock** [comment]
Betslip is sticky now

**Comment by matt-bullock** [comment]
Works great
