### ISSUE TITLE
Stop Orders

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#91]
Limit orders in UI if price > or < a number and maximum amount of money you're willing to spend for buy, max shares to sell for sell then enter limit orders in actual chain.

Talk to me when you wanna implement this and I'll explain

Also add stop orders.

**Comment by tinybike** [comment]
API support added in AugurProject/augur.js@47544f1e3e0f2b6d78cc12c356841e7689acd3f4.

**Comment by tinybike** [comment]
Stop orders added in e1d3550e509acbfac5d323b399168d03c21e3a00.  Moving Limit Orders to separate issue.
