### ISSUE TITLE
Processing button for migrate REP isn't very visible -see comment about checkmark below

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9101]
Appears after migrating REP. @yanelbottini we may need a design for this 

![image](https://user-images.githubusercontent.com/39496225/91071047-f965a780-e637-11ea-9271-2b8d84909996.png)

**Comment by yanelbottini** [comment]
I've updated the design to make the processing status more visible and consistent (Spinner should be animated):
<img width="652" alt="Screen Shot 2020-08-25 at 10 19 10" src="https://user-images.githubusercontent.com/49915900/91179180-8d795280-e6bc-11ea-9fbe-7dba21b1dd18.png">

**Figma reference:**
https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet-Design-System?node-id=283%3A145

**Comment by Chwy5** [comment]
The checkmark after it finishes isnt centered...it is showing up on the line closest to the question mark
