### ISSUE TITLE
Design QA - My Bets Tooltip over Outcome

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9114]
- This tooltip should appear when you hover the outcome. Right now the position doesn't seem right. 
- The tooltip shouldn't appear if there is enough room for the outcome name. So, I think in this particular case, I shouldn't see at all. 

![Kapture 2020-08-25 at 09 42 36](https://user-images.githubusercontent.com/49915900/91175671-89970180-e6b7-11ea-9ecb-72725b20e21c.gif)

**Comment by yanelbottini** [comment]
Looks fine on big resolutions, but it's not working fine on smaller ones:

![responsive-stats](https://user-images.githubusercontent.com/49915900/93830426-9b33e080-fc46-11ea-8d81-9cf89617d735.gif)

![Uploading Screen Shot 2020-09-21 at 20.14.29.png…]()

Figma reference:
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7654%3A268226

**Comment by matt-bullock** [comment]
seems with a 32 limit character count the tooltip won't show anyway
