### ISSUE TITLE
REP staked redeemed alert: figure isn't accurate.

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9124]
Should show 1.3496

![image](https://user-images.githubusercontent.com/39496225/91307652-8af72580-e7ae-11ea-979d-fd740cee5368.png)

**Comment by matt-bullock** [comment]
Still doesn't seem right. @phoebemirman can you do some testing on this to check it's working for you 

![image](https://user-images.githubusercontent.com/39496225/93588911-5c82f980-f9ac-11ea-8a58-c7f32f935da3.png)

**Comment by matt-bullock** [comment]
Why's it 0.0001 off?

![image](https://user-images.githubusercontent.com/39496225/93908157-99c5ef00-fcfe-11ea-8c13-82913c5c3a8a.png)

**Comment by phoebemirman** [comment]
probably rounding

**Comment by matt-bullock** [comment]
closing for now
