### ISSUE TITLE
Page elements shifting when expanding row in my active markets

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9137]
![Kapture 2020-08-27 at 16 34 14](https://user-images.githubusercontent.com/39496225/91456150-396c9a80-e883-11ea-9761-bf4b64ea42bb.gif)

**Comment by yanelbottini** [comment]
Seems to work fine

**Comment by matt-bullock** [comment]
Still seeing this

![Kapture 2020-10-14 at 14 02 11](https://user-images.githubusercontent.com/39496225/95986217-edbb8380-0e25-11eb-8ee6-198dc29a3947.gif)

**Comment by matt-bullock** [comment]
Still seeing this. Leave it as low priority for now as it's not a big deal but should be fixed eventually

**Comment by matt-bullock** [comment]
Page content is still jumping

![Kapture 2020-10-16 at 12 23 44](https://user-images.githubusercontent.com/39496225/96247542-8c70ed00-0faa-11eb-8d1a-1e61ad7b262a.gif)

**Comment by JohnDanz** [comment]
I think thats close enough for now... not really sure why that minor redraw is causing it to move at all but let's back burn this minor jitter for now. putting this back in to-do.

**Comment by JohnDanz** [comment]
Closing as this entire page will no longer exist shortly.
