### ISSUE TITLE
Wager should show decimal places in my bets like it does in active bets and Include $ sign

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9138]
![image](https://user-images.githubusercontent.com/39496225/91460471-1d1f2c80-e888-11ea-8b03-53763e6d4f03.png)

![image](https://user-images.githubusercontent.com/39496225/91460550-32945680-e888-11ea-8eb5-36431a622d9e.png)

**Comment by yanelbottini** [comment]
ok
