### ISSUE TITLE
In my bets wager and to win figures should start with dollar sign 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9139]
![image](https://user-images.githubusercontent.com/39496225/91461067-de3da680-e888-11ea-86ee-dc05067b6920.png)

**Comment by JohnDanz** [comment]
<img width="1516" alt="Screen Shot 2020-10-12 at 1 40 00 PM" src="https://user-images.githubusercontent.com/10524630/95779849-6f79a880-0c90-11eb-80be-638c9dcfe224.png">

This appears to be the case already, above screenshot is taken from Dev as of Monday Oct 12th, at 1:40 PM CDT
