### ISSUE TITLE
Design QA - Report on this market Modal

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9141]
Styles for the modal are different from design:

<img width="1656" alt="Screen Shot 2020-08-27 at 22 56 54" src="https://user-images.githubusercontent.com/49915900/91512657-d990e680-e8b8-11ea-89b9-d01c77a60be3.png">
<img width="1646" alt="Screen Shot 2020-08-27 at 22 57 10" src="https://user-images.githubusercontent.com/49915900/91512663-ddbd0400-e8b8-11ea-81e5-e05ecf8cd860.png">
<img width="1609" alt="Screen Shot 2020-08-27 at 22 57 26" src="https://user-images.githubusercontent.com/49915900/91512665-de559a80-e8b8-11ea-91c7-1449d1f0d8f2.png">

**Figma Reference:**
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=8355%3A280825

**Comment by matt-bullock** [comment]
@phoebemirman Figma link with interaction states https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7396%3A94023
![image](https://user-images.githubusercontent.com/39496225/93880635-15fc0a80-fcde-11ea-859d-33b3e0cf704d.png)

**Comment by yanelbottini** [comment]
- Different styles:
<img width="1425" alt="Screen Shot 2020-10-02 at 08 57 41" src="https://user-images.githubusercontent.com/49915900/94920936-aaf4c580-048d-11eb-897f-5e42e8205017.png">

- Tooltip is not aligned "?"
<img width="488" alt="Screen Shot 2020-10-02 at 09 00 21" src="https://user-images.githubusercontent.com/49915900/94921011-cb248480-048d-11eb-8e86-7ba2aec1254e.png">

- Outcomes are gray by default. Right now seems bigger than should be, and the text is not vertically-aligned. 
<img width="949" alt="Screen Shot 2020-10-02 at 09 04 17" src="https://user-images.githubusercontent.com/49915900/94921280-5c93f680-048e-11eb-9aab-22b4a266c130.png">

- Hover state is incorrect. Border should be dark gray. For full reference of this component, please check:
<img width="1562" alt="Screen Shot 2020-10-02 at 09 06 15" src="https://user-images.githubusercontent.com/49915900/94921344-8baa6800-048e-11eb-8d21-35f2caf272c1.png">
https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet-Design-System?node-id=561%3A4371

- Add space between Max / Clear buttons. 16px should be enough
<img width="424" alt="Screen Shot 2020-10-02 at 09 06 46" src="https://user-images.githubusercontent.com/49915900/94921440-b85e7f80-048e-11eb-9a9d-552b1c333208.png">

- The bottom margin should be bigger: 24px
<img width="810" alt="Screen Shot 2020-10-02 at 09 08 55" src="https://user-images.githubusercontent.com/49915900/94921605-05daec80-048f-11eb-9aaa-c69584c8efa1.png">

- After reporting, the tick should be right-aligned, as in other notifications. 
<img width="426" alt="Screen Shot 2020-10-02 at 09 10 34" src="https://user-images.githubusercontent.com/49915900/94921709-315dd700-048f-11eb-81e5-a3e88e82ff8f.png">

**Comment by matt-bullock** [comment]
Still need to fix the text styling here 

![image](https://user-images.githubusercontent.com/39496225/96004267-7a247100-0e3b-11eb-93b3-4a37ebcdc341.png)

Compare with design below:

- Labels should be caps
- space between resolution details label and text underneath need increasing
- Font style of dates

Figma link https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=8355%3A280825


![image](https://user-images.githubusercontent.com/39496225/96004334-8f999b00-0e3b-11eb-85f4-9cd8dfa72555.png)


---

Tick still not right aligned 

![image](https://user-images.githubusercontent.com/39496225/96004955-4ac23400-0e3c-11eb-851c-80313f4db983.png)

**Comment by matt-bullock** [comment]
looks good
