### ISSUE TITLE
Design QA - My bets page moving when switching between Daily and Futures markets

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9142]
![moving](https://user-images.githubusercontent.com/49915900/91513010-b0248a80-e8b9-11ea-9d91-8b6a06293ab5.gif)

**Comment by phoebemirman** [comment]
I;m not seeing this. is it still happening for you @yanelbottini ?

**Comment by yanelbottini** [comment]
Nop @phoebemirman I don't see it anymore! closing it.
