### ISSUE TITLE
Design QA - Add more liquidity modal

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9145]
Please, update the tag that says "Liquidity depleted" with this design:
<img width="1019" alt="Screen Shot 2020-08-31 at 09 25 52" src="https://user-images.githubusercontent.com/49915900/91719616-06b8ef80-eb6c-11ea-8a22-7f3fff87b4c9.png">

Once the user clicks on the "Add more liquidity" button, this modal appears:
<img width="503" alt="Screen Shot 2020-08-27 at 23 56 07" src="https://user-images.githubusercontent.com/49915900/91516055-edd8e180-e8c0-11ea-8dc3-2d5ffcb793ff.png">

https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=8129%3A112

**Comment by matt-bullock** [comment]
Outcomes shouldn't be all caps

![image](https://user-images.githubusercontent.com/39496225/93595150-8261cb80-f9b7-11ea-9542-c34af1c39a07.png)

Modal header text here doesn't look like design 

![image](https://user-images.githubusercontent.com/39496225/93595543-3e22fb00-f9b8-11ea-8c62-d355653e0d52.png)

Add liquidity button should always be present to the market creator, not only when liquidity is fully depleted

**Comment by yanelbottini** [comment]
- The style for the dropdown menu still is not right:

**Dev:**
<img width="304" alt="Screen Shot 2020-09-22 at 06 16 27" src="https://user-images.githubusercontent.com/49915900/93864398-38b8ff80-fc9b-11ea-89cb-b664b0e13d28.png">

**Design Example of a dropdown component:**
<img width="553" alt="Screen Shot 2020-09-22 at 06 22 21" src="https://user-images.githubusercontent.com/49915900/93864957-02c84b00-fc9c-11ea-8854-c4769df1a0c8.png">

**Figma reference:**
https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet-Design-System?node-id=561%3A4371

- If possible, I would suggest hiding the table header until user includes an order:
<img width="717" alt="Screen Shot 2020-09-22 at 06 16 30" src="https://user-images.githubusercontent.com/49915900/93864456-4ff7ed00-fc9b-11ea-8fed-18563b17475f.png">

- Typo: "limitations"
<img width="467" alt="Screen Shot 2020-09-22 at 06 18 46" src="https://user-images.githubusercontent.com/49915900/93864617-8cc3e400-fc9b-11ea-8408-7658d45b51cd.png">

**Comment by yanelbottini** [comment]
Still using the dropdown from Trading:

![Uploading Screen Shot 2020-09-23 at 18.04.38.png…]()

**Comment by matt-bullock** [comment]
looks good
