### ISSUE TITLE
Para ZeroXTrade check address balance can cover protocol fees

### ISSUE THREAD

**Issue by epheph** [AugurProject/augur#9146]
Re-gas'ing 0x transactions is extremely unfortunate. Combined with how much gas is used in ZeroXTrade, a quick check that the contract has enough ether to cover the protocol fees

https://github.com/AugurProject/augur/blob/e196efb4261f02200f59d52dc839c8691a04139e/packages/augur-core/src/contracts/para/ParaZeroXTrade.sol#L246-L250

```
if ( address(this).balance < _protocolFee * _orders.length) {
}
```

**Comment by epheph** [comment]
And while you're in there, check for `_orders.length == _signatures.length`in `trade` and also for the protocol fee * _orders.length in `cancelOrders`

**Comment by robert-e-davidson3** [comment]
Merged into `para_deploys` branch:

```
commit 7496fbbbed8f02e2fc7b7787c8ad00a51c89b1b0 (HEAD -> para_deploys, origin/para_deploys, robert/9146)
Author: robert <robert.davidson@forecastfoundation.org>
Date:   Tue Oct 20 22:00:38 2020 -0400

    prevent expensive bad 0x ops
```
