### ISSUE TITLE
Node#moveTo was deprecated. Use Container#append.

### ISSUE THREAD

**Issue by kenorb** [AugurProject/augur#915]
The following warning appears during build.

```
augur $ npm run build
== Building Augur ==
...
[11:28:39] Build Augur [started]
Node#moveTo was deprecated. Use Container#append.
```

Same warning when running via `yarn build`.

**Comment by stephensprinkle** [comment]
@kenorb — Thanks for the issue, I’ll take a look into this.  

I’ll open a bug in our Clubhouse and will update this issue once things are resolved.

**Comment by stephensprinkle** [comment]
Resolved in `v3` branch.
