### ISSUE TITLE
Design QA - Missing word: "24H Change"

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9152]
- Should said "24h Change"
- Icon should be thicker.
- No need of the ()

<img width="754" alt="Screen Shot 2020-08-31 at 07 33 35" src="https://user-images.githubusercontent.com/49915900/91711522-6a3b2100-eb5c-11ea-95a4-5f83187e087a.png">

**Comment by yanelbottini** [comment]
@phoebemirman Icon still looks thinner: Is it possible to improve it?

**Comment by matt-bullock** [comment]
Icon looks broken. Rest looks good

![image](https://user-images.githubusercontent.com/39496225/93594056-7412b000-f9b5-11ea-9cd7-21b0c66b5123.png)

**Comment by matt-bullock** [comment]
looks good now
