### ISSUE TITLE
Design QA - Claim Stake & fee Modal

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9153]
Please, update styles to match design

<img width="1108" alt="Screen Shot 2020-08-31 at 08 03 48" src="https://user-images.githubusercontent.com/49915900/91713776-cd2eb700-eb60-11ea-89b7-2158ad617b00.png">

I've also included the processing & confirm status behavior:

<img width="811" alt="Screen Shot 2020-08-31 at 08 09 25" src="https://user-images.githubusercontent.com/49915900/91714090-6362dd00-eb61-11ea-9679-5cff6aa62fba.png">

And an example of error message: Do you have a text for that? I'm not able to reproduce the behaviour. 
<img width="805" alt="Screen Shot 2020-08-31 at 08 13 23" src="https://user-images.githubusercontent.com/49915900/91714372-f26ff500-eb61-11ea-9606-4b56b6c66c26.png">

**Figma reference:**
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=8379%3A982

**Comment by matt-bullock** [comment]
looks good
