### ISSUE TITLE
Use Create2 for ERC20 Proxy ERC1155 Nexus

### ISSUE THREAD

**Issue by epheph** [AugurProject/augur#9158]
https://github.com/AugurProject/augur/pull/8975/files#diff-3556ba754fa876289155443c95ffdc41R29-R31

There is a storage mapping of tokenId->ERC20 address. these are one-to-one mappings that seem perfect for CREATE2 , especially considering the design is already deploy THEN initialize (ensuring deployment is consistent bytes)

You could avoid storing the mapping and just use address calculation. Others who want to interact with the system would not need to look up the address, just perform the calculation themselves (and see there is a contract that exists in that location)

**Comment by robert-e-davidson3** [comment]
Love it. https://github.com/AugurProject/augur/pull/8975/commits/7f422160f8a771ef3f96e1cdd76d4aaf83f7ceac
