### ISSUE TITLE
Finish AMM Exchange Work

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#9164]
- [x] Implement fee. Likely just making this adjustment everywhere: poolConstant = poolYes.mul(poolNo).mul(1000).div(997)
- [x] add method to exit a position based on shares
- [x] add convenience view methods to see what current rates are for swapping / entering a position

**Comment by robert-e-davidson3** [comment]
All of these points are done. More could come up so "finish" is a bit premature but I'll close based on the subtasks.
