### ISSUE TITLE
Design QA - Confirmed message on Notifications

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9165]
We should use this approach to show the status on the Notification box after an action is confirmed: The icon should dissappear after 1 or 2 seconds:

<img width="985" alt="Screen Shot 2020-09-01 at 08 55 50" src="https://user-images.githubusercontent.com/49915900/91848109-ffa7e500-ec30-11ea-92fc-dc3bb4f36e5d.png">

**Figma reference:**
https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet-Design-System?node-id=1227%3A0

**Comment by matt-bullock** [comment]
This appears but then after a few seconds the original notification message reappears with the action button. This then removes after a second or 2. Test it to see what I mean
