### ISSUE TITLE
Design QA - Not seeing winner on Resolved market

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9166]
This market is resolved, and I don't see the winner:

https://dev.augur.net/#!/market?id=0x6b92F153f470540E375497667099a26E7BC4231f&t=SPORTS&r=0xA7fEdB2c47359cfDc4A04E5783DcD857a21A975A

<img width="1123" alt="Screen Shot 2020-09-01 at 09 14 45" src="https://user-images.githubusercontent.com/49915900/91850524-13a11600-ec34-11ea-92f0-871b977dda0d.png">

This is an example showing how winner is highlighted: 
<img width="1465" alt="Screen Shot 2020-09-01 at 09 18 43" src="https://user-images.githubusercontent.com/49915900/91850609-316e7b00-ec34-11ea-94eb-2a87e095424a.png">

Also the "Estimated start time..." shouldn't be there.

**Figma reference:**
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=4473%3A70

**Comment by matt-bullock** [comment]
Winner is showing
