### ISSUE TITLE
Design QA - Processing, Fail and Confirm Status on Modals

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9171]
Can we use the following approach to show different status on tables that includes actions:

<img width="1064" alt="Screen Shot 2020-09-02 at 07 12 18" src="https://user-images.githubusercontent.com/49915900/91968885-b49ed800-eceb-11ea-96a7-31dad2b8e597.png">

Please notice, that while an action is being processed, or it's confirmed, the "Cancel" action should be disabled. 

**Figma reference:**
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=8399%3A0

**Comment by matt-bullock** [comment]
Cancel button shouldn't shift when button state is in processing

![image](https://user-images.githubusercontent.com/39496225/94791450-f351ac00-03d7-11eb-9d79-c553d93b042e.png)

---

Error message..? See Yanel's screenshot above. Can say 'Failed. **Retry**' if you want to recycle existing components.

![image](https://user-images.githubusercontent.com/39496225/94791547-19774c00-03d8-11eb-8e5f-f5b6a4d63381.png)

---

Not seeing a confirmed state - please add. I think it would be better if the rows don't disappear after submitting, that way the confirmed state stays until you close the modal

---

Can you fix the alignment of the columns

![image](https://user-images.githubusercontent.com/39496225/94792177-e1bcd400-03d8-11eb-8b81-5a058c21ec03.png)

**Comment by yanelbottini** [comment]
@matt-bullock @phoebemirman
To unify how we handle error messages, we are going to implement this approach:

<img width="166" alt="Screen_Shot_2020-09-30_at_2 16 57_PM" src="https://user-images.githubusercontent.com/49915900/94816032-9c48d880-03d1-11eb-94c9-30e30ac37b13.png">

But should say: "Failed. **Retry**"

**Comment by yanelbottini** [comment]
I'm closing this issue: Ok and loading status seem to works fine. I wasn't able to test the Error message, but in case it's wrong, we can re-open a new ticket.
