### ISSUE TITLE
Design QA - Search field should be right-aligned

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9172]
<img width="1406" alt="Screen Shot 2020-09-02 at 07 25 37" src="https://user-images.githubusercontent.com/49915900/91970193-a9e54280-eced-11ea-9df6-f2ba7e3e0948.png">

**Comment by phoebemirman** [comment]
looks fine to me 
<img width="1464" alt="Screen Shot 2020-09-08 at 1 23 46 PM" src="https://user-images.githubusercontent.com/6775839/92524216-90089b80-f1d6-11ea-8a1e-edaec43c928c.png">

**Comment by matt-bullock** [comment]
Yeah looks fixed
