### ISSUE TITLE
Design QA - Winnings amount not matching

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9184]
The amount displayed on the top right banner on My Bet section doesn't match the amount displayed on the notification modal:

<img width="1439" alt="Screen Shot 2020-09-04 at 08 14 31" src="https://user-images.githubusercontent.com/49915900/92233477-bcdf4a80-ee86-11ea-8aad-1ac61387656c.png">

**Comment by matt-bullock** [comment]
Top banner in my bets isn't showing despite having winnings to claim on 2 markets
