### ISSUE TITLE
Design QA - Missing "Claim XX.XX" button on the table to see the market where you have the winnings

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9185]
![claim-bets](https://user-images.githubusercontent.com/49915900/92233636-062f9a00-ee87-11ea-8ab7-46ca6415bb49.gif)

Should be like this:
<img width="1424" alt="Screen Shot 2020-09-04 at 08 24 15" src="https://user-images.githubusercontent.com/49915900/92234263-172cdb00-ee88-11ea-8625-faf1ed4a0182.png">

**Figma reference:**
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=4473%3A2123

**Comment by phoebemirman** [comment]
we have to update the api for this because we don't have winnings per outcome or claiming per outcome at this point

**Comment by yanelbottini** [comment]
@phoebemirman we have updated the design:

- The user won't be able to claim individual outcomes. 
- Instead of showing the button to claim, we show a message that says: "WON: $XX.XX". (Should not be clickable)
- In order to claim winnings, the user must use the top green banner. 

<img width="1419" alt="Screen Shot 2020-09-10 at 16 13 35" src="https://user-images.githubusercontent.com/49915900/92788793-9fc3e380-f380-11ea-8679-59f6a28e68ab.png">

**Figma reference:**
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=4473%3A2123

Let me know if it makes sense!

**Comment by matt-bullock** [comment]
working as it should be
