### ISSUE TITLE
[BUG] Top Y-Axis label is cut off on candlestick chart.

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#919]
### Summary
Top Y-Axis label is cut off on candlestick chart.

<img width="679" alt="screen shot 2019-01-30 at 11 02 29 am" src="https://user-images.githubusercontent.com/328965/52005554-d3d5e380-247e-11e9-9681-0e6756ce9858.png">

D3 has a mind of its own sometimes when selecting vertical ticks. This is the market in question: https://sneakpeak.augur.net/#!/market?id=0x75ec1f1a3356517908eccb5f6e4fac619c68ba99

**Comment by joeykrug** [comment]
non issue in @bthaile's charts
