### ISSUE TITLE
Refactoring Charts

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#9198]
refactor and update the Depth Chart and Candlestick charts to be more responsive like the updated price history chart is.

**Comment by yanelbottini** [comment]
- For Mega templates it's missing the possibility to switch between markets. On the design is like this:

<img width="1294" alt="Screen Shot 2020-09-16 at 09 26 13" src="https://user-images.githubusercontent.com/49915900/93336853-b0e87680-f7fe-11ea-8139-1bd34ff63d84.png">

- It has a dropdown to switch between moneyline, o/u, etc...

**Figma reference to components:**
https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet-Design-System?node-id=185%3A0

On small breakpoints, the design contemplated including the references below the chart. On the build is on the side. Is it possible to update it?

**Comment by JohnDanz** [comment]
Oh yeah, I didn't touch those, this was more setup for eventual updates for these types of things. I was planning on a different ticket for that.

**Comment by yanelbottini** [comment]
- Can we increase this distance? Make it 16px instead of 8px like it is now. Because seems too close. 

<img width="481" alt="Screen Shot 2020-09-23 at 17 41 49" src="https://user-images.githubusercontent.com/49915900/94067372-2686b080-fdc4-11ea-827d-401399244351.png">

**Comment by yanelbottini** [comment]
For Mega templates it's missing the possibility to switch between markets. On the design is like this:

<img width="1294" alt="93336853-b0e87680-f7fe-11ea-8139-1bd34ff63d84" src="https://user-images.githubusercontent.com/49915900/94589187-57029a80-025b-11eb-8777-e63ab603cfea.png">
