### ISSUE TITLE
[BUG] Candlestick chart flickers on mousemove 

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/augur#920]
### Problem: 

The svg <g> tag doesn't handle mouseover/mouseout properly causing an annoying flicker when the mouse moves within a candlestick bar.

We need to replace the <g> tag with an <svg> which will define a new coordinate system is defined. The 'candles' will need to be positioned properly inside the new svg tag and (this might be the hard part) the masks for the hollow green candles will need to be adjusted. 

Please reach out with any questions. It will be nice to have another set of eyes on this code.

**Comment by ryanberckmans** [comment]
This issue is obsolete because `Candlestick chart flickers on mousemove` is an implementation detail of our use of D3, and we're transitioning to highcharts.
