### ISSUE TITLE
Design QA - 24h number meaning

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9204]
The 24h change is showing a 2: That number should be a %. 

As it is showing a positive change, shouldn't one or the two markets below have a positive value?

<img width="527" alt="Screen Shot 2020-09-07 at 10 17 04" src="https://user-images.githubusercontent.com/49915900/92485870-d56e9e00-f1c1-11ea-829a-df4c5f75e6cd.png">

**Comment by Chwy5** [comment]
this shows the same way (incorrectly on the trading pg on dev) as well

**Comment by matt-bullock** [comment]
looks right
