### ISSUE TITLE
AMM Registry / Factory

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#9236]
Creates new AMM markets for para augurs and markets.

**Comment by pgebheim** [comment]
@robert-e-davidson3 -- the factory should also track AMMs that have been created so they're cheaper to look up (and convenient off chain)

**Comment by pgebheim** [comment]
Related to #9181

**Comment by robert-e-davidson3** [comment]
Done - in `para_deploys`.
