### ISSUE TITLE
Design QA - Footer should be full-width

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9243]
- Link underline styles are incorrect.
- Should be fullwidth.
- Footer is missing on small breakpoints.

<img width="637" alt="Screen Shot 2020-09-14 at 08 19 29" src="https://user-images.githubusercontent.com/49915900/93079777-0a1ba300-f663-11ea-8ca9-fc4601e5aa0b.png">

**Comment by yanelbottini** [comment]
@bconfortin Container is fine, but the style for the links is still incorrect (The underline)

**Comment by yanelbottini** [comment]
Missing hover states for the links, should behave as other dotted links:
 
<img width="435" alt="Screen Shot 2020-09-23 at 17 36 48" src="https://user-images.githubusercontent.com/49915900/94066822-639e7300-fdc3-11ea-917b-233892956757.png">

**Comment by matt-bullock** [comment]
looks good
