### ISSUE TITLE
Onboarding: Entering convert amount pushes content off screen

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9266]
Click input to replicate

+ make sure output doesn't show a weird formula 

![image](https://user-images.githubusercontent.com/39496225/93474395-93e39e80-f8f7-11ea-8dd9-bca6af2e7730.png)

**Comment by andrewdamelio** [comment]
@matt-bullock this is only an issue on Kovan since our conversions rates are messed for Kovan USDC/USDT. We can fix post onboarding wor
