### ISSUE TITLE
Balance not updating cancelling open orders in resolved market

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#9272]
f I am a market creator and have open orders on the sportsbook (offers) after the market finalizes, cancelling those open orders (works through the modal) but my balance never updates...refreshing doesnt fix either

**Comment by JohnDanz** [comment]
going to push this one week due to potentially being resolved by updates on the backend/pulling out the gsn.

**Comment by LeonChain** [comment]
I would like to help with the issues.
Is there anyone I can discuss for the work?

**Comment by matt-bullock** [comment]
looks correct
