### ISSUE TITLE
Allow withdraw Uniswap(UNI) from 2.0 contract's wallet

### ISSUE THREAD

**Issue by gabbello835** [AugurProject/augur#9279]
If someone used Augur 2.0 (up to 2.0.5 I think) in order to deposit to **_TRADING_ACCOUNT_** and swap DAI or REP, they might be entitled for the Unisawp Airdrop. 

This can be checked at: https://app.zerion.io/{_TRADING_ACCOUNT_ADDRESS}/overview

If you are eligible you will see "Eligible for Uniswap tokens:" text

This can then be claimed from https://app.uniswap.org:

- Go to the [...] in top right corner
- Claim UNI
- Insert _TRADING_ACCOUNT_ eth address.
- Sign with metamask or alternative wallet used.

The problem is that UNI will be credited to trading_account address instead own address so there is no way to control them further

**Solution:**

Either build a standalone UI for adding ability to transfer UNI to an address that user controls, or add this as an ability in the Withdraw section of Augur that existed for versions up to 2.0.5.

**Comment by pgebheim** [comment]
Posted the URL for this in #help yesterday -- thanks for the suggestion.
