### ISSUE TITLE
Wrong header banner on trading section 

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#9280]
Currently has the old banner...needs to be updated 
Shows this:
![image](https://user-images.githubusercontent.com/41301809/93778880-5c753a80-fbf4-11ea-8227-f2faa74df3be.png)

Should be:
![image](https://user-images.githubusercontent.com/41301809/93779018-7f075380-fbf4-11ea-9d7d-04acd18484dc.png)

**Comment by matt-bullock** [comment]
Still seeing the old one @JohnDanz has your update not been pushed yet?
