### ISSUE TITLE
Handle para-augur deployment through factories

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#9288]
In order to ensure that Para-Augur deploys are legitimate the deploys should be handled directly from a set of factories and a manager contract that can do all the necessary steps of deployment. This also allows us to tackle a few other issues in this area.

- [ ] Compute initial price using the Storage Proof method outlined https://medium.com/@epheph/using-uniswap-v2-oracle-with-storage-proofs-3530e699e1d3 so that initial price doesn't need to be trusted.
- [ ] For on-chain trading interval, use the Core REP Trading interval (10 DAI) and automatically set the Para Augur trading interval to be as close that as possible while being a multiple of 10. So e.g. Choose whichever of 1/1000, 1/100, 1/10, 1, 10, 100, 1000 makes the most sense as the adjustment to the trading interval.
- [ ] Create a deployer contract + set of factories that can deploy the para augur contract in stages.

**Comment by MicahZoltu** [comment]
Where can I read about how this solves the problem of governance over the para-augurs?

**Comment by pgebheim** [comment]
> Where can I read about how this solves the problem of governance over the para-augurs?

What this means is that no governance is needed to deploy the para augur because we get verifiable deploys, and don't need to trust any information from the deployer for the price of the tokens or the trading interval.

**Comment by MicahZoltu** [comment]
What prevents me from creating a scam token that only I have any of (mint 1 trillion of them to myself), fixing the price on Uniswap (to say $1 per token), and then depositing 1 trillion of them in a para-augur I deployed through the factory?
