### ISSUE TITLE
Issues when user has a bet on an invalid market

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9290]
I have a long position in this market. It recently failed the invalid filter check. It should have the high risk label in my bets section.

![image](https://user-images.githubusercontent.com/39496225/93888875-d7b81880-fce8-11ea-9437-385452ba1444.png)

When I go to the market page it's correct (we need to update the copy in the message to say: 'This Market has a high risk of being resolved as Invalid. You can go to Trading and try to sell out your current position.  **Go to Trading**)

![image](https://user-images.githubusercontent.com/39496225/93888994-f9b19b00-fce8-11ea-8151-9c5c31ee4395.png)

The market isn't being filtered out of the markets page:

![image](https://user-images.githubusercontent.com/39496225/93889512-8f4d2a80-fce9-11ea-87c7-61336e9ad45f.png)

I'm not receiving a notification that the market is failing the invalid filter

---

On another account I hold a SHORT position 

![image](https://user-images.githubusercontent.com/39496225/93889747-dd622e00-fce9-11ea-8495-c57a7eabe64d.png)

On this account I get a notification and the market is filtered out

![image](https://user-images.githubusercontent.com/39496225/93889812-ef43d100-fce9-11ea-9022-137968c51c3e.png)

**Comment by matt-bullock** [comment]
I'm receiving the notification and the market is being filtered out the market list page

 but not seeing the high risk label in my bets and the message copy isn't updated:

![image](https://user-images.githubusercontent.com/39496225/95586744-65ae3600-0a41-11eb-9ae2-95b30e129df1.png)

**Comment by yanelbottini** [comment]
- The High Risk tag is showing up on My Bets, but I'm noticing that that specific market is not showing its name (Spread, Moneyline...) like the ones below:

<img width="1347" alt="Screen Shot 2020-10-14 at 06 54 35" src="https://user-images.githubusercontent.com/49915900/95973521-276e9900-0dea-11eb-9857-cd0d668ddbab.png">

- When you enter to the market detail page, the High risk tag should have the same size (Heigh) than the Status one. 

<img width="635" alt="Screen Shot 2020-10-14 at 06 56 47" src="https://user-images.githubusercontent.com/49915900/95973813-816f5e80-0dea-11eb-8c68-6ae429f9009f.png">

**Comment by matt-bullock** [comment]
looks good
