### ISSUE TITLE
Design QA - Missing Hover state on "View all Bets" button

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9309]
<img width="345" alt="Screen Shot 2020-09-24 at 08 13 42" src="https://user-images.githubusercontent.com/49915900/94138085-e532e700-fe3d-11ea-87f8-ce10994bd8fc.png">

"View all bets" button should include hover state as indicated on the design system file (last example):

<img width="656" alt="Screen Shot 2020-09-24 at 08 12 53" src="https://user-images.githubusercontent.com/49915900/94138098-e95f0480-fe3d-11ea-8279-55dd63c575f4.png">

**Comment by matt-bullock** [comment]
looks good
