### ISSUE TITLE
Design QA - 768 Breakpoint

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9312]
There are some differences on the header area on 768 breakpoint:

<img width="1676" alt="Screen Shot 2020-09-24 at 08 50 38" src="https://user-images.githubusercontent.com/49915900/94141451-2083e480-fe43-11ea-8311-01ccba59fd90.png">

- Different menu size
- Missing access to Active Bets
- Missing title
- It's not "Filter by", it's "Sort by". Please, check size & icon.

**Figma reference:**
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7654%3A269058

**Comment by yanelbottini** [comment]
The Ticket button included on the top nav should show Active bets. Right now seems to be linked to Betslip:

![Active-bets](https://user-images.githubusercontent.com/49915900/97415586-340fe880-18e4-11eb-9a20-85ac5455b7e2.gif)

**Comment by matt-bullock** [comment]
ticket button is now fixed
