### ISSUE TITLE
Design QA - Fast dispute

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9313]
Fast dispute tag (I guess same issue is happening with other tags), moves position on smaller resolution:

![fast-dispute](https://user-images.githubusercontent.com/49915900/94142126-29c18100-fe44-11ea-93b5-6081166dc625.gif)

**Comment by Chwy5** [comment]
We shouldnt be showing Fast dispute or disputing....should be market is in Settlement

**Comment by phoebemirman** [comment]
not seeing this happen. i'm not seeing in dispute markets in bet slip list. please reopen if its seen again.
