### ISSUE TITLE
Design QA - My bets tablet (1024 to 1200 breakpoint)

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9314]
- Last column content is touching table border. 

<img width="504" alt="Screen Shot 2020-09-24 at 09 04 57" src="https://user-images.githubusercontent.com/49915900/94142752-24186b00-fe45-11ea-83ef-5b1cbf37e043.png">

Design:
<img width="1011" alt="Screen Shot 2020-09-24 at 09 06 56" src="https://user-images.githubusercontent.com/49915900/94142889-53c77300-fe45-11ea-8973-9c54e194a453.png">

**Comment by matt-bullock** [comment]
looks fixed
