### ISSUE TITLE
Design QA - Please, center align footer  on Mobile.

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9327]
- Please, center align footer on mobile.
- In this case, where content doesn't fill screen, footer should be at the bottom.

![4acfdbd6-0fd7-4465-960b-9e189b9bd9d7](https://user-images.githubusercontent.com/49915900/94423657-597fca00-015f-11eb-8edb-52743e98ec19.jpg)

**Comment by matt-bullock** [comment]
@yanelbottini is this right? Looks odd

**Comment by yanelbottini** [comment]
No, it's not looking right. I see in this way on Mobile:
![fd5204b4-5014-4da1-a4c9-d14e93dbb8bf](https://user-images.githubusercontent.com/49915900/94918773-9adae700-0489-11eb-8f01-30e58b31672c.jpg)

And on desktop a double scroll appears (Not sure if it's related to the footer)
<img width="622" alt="Screen Shot 2020-10-02 at 08 05 07" src="https://user-images.githubusercontent.com/49915900/94918812-b2b26b00-0489-11eb-8823-8324046398ac.png">
