### ISSUE TITLE
Design QA - Claim Winnings Modal

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9329]
We have updated Claim winning modal design:
<img width="838" alt="Screen Shot 2020-09-28 at 08 21 29" src="https://user-images.githubusercontent.com/49915900/94426289-b7161580-0163-11eb-9b8a-0420730cfbf0.png">

**Figma reference:**
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=8825%3A277309

**Comment by Chwy5** [comment]
We still might need to include the gas cost depending which network pays it at the bottom by total returns

**Comment by matt-bullock** [comment]
Total proceeds at the bottom should be changed to what's in the screenshot above

Is it correct that the 2 estimated tx fees don't add up at the bottom? Is doing the claim all cheaper than the total of doing the individual claims?

![image](https://user-images.githubusercontent.com/39496225/95442129-4c32be80-095b-11eb-813b-139936c6b40f.png)

**Comment by phoebemirman** [comment]
yes thats true

**Comment by matt-bullock** [comment]
Total is getting pushed off at the bottom @phoebemirman 

![image](https://user-images.githubusercontent.com/39496225/95570787-b31da980-0a27-11eb-94f1-939ba2f54b0f.png)

**Comment by matt-bullock** [comment]
Models with multiple markets to claim from won't open - just crashes to a white screen @phoebemirman

**Comment by matt-bullock** [comment]
Still crashing so can't check

**Comment by matt-bullock** [comment]
multiple markets issue is fixed.

Minor thing but could you line up the total returns with tx fee

![image](https://user-images.githubusercontent.com/39496225/96568063-cfdb9c00-12c7-11eb-8e1f-fbbed1f7e8e4.png)

**Comment by matt-bullock** [comment]
👍
