### ISSUE TITLE
Design QA - Bug on Market Creation process when switching between Trading and SP

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9354]
Use case:
- I created a market on Trading.
- I arrived to the review detail page.
- I clicked on "Sportsbook" to switch theme. A modal warning me that I would loss data if I leave screen appeared.
- I clicked "Cancel" inside the modal, and switched to Sportsbook theme:

![Screen_Shot_2020-09-30_at_17 24 51-1](https://user-images.githubusercontent.com/49915900/94812304-eed3c600-03cc-11eb-84d9-84dee8fa00b3.png)

**Comment by JohnDanz** [comment]
@chwy5 Shouldn't we simply disable sportsbook theme switching in trading? like why are we even allowing that?

**Comment by Chwy5** [comment]
@JohnDanz  Yes
