### ISSUE TITLE
Missing Message "Sign to approve orders" in market creation

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#9355]
On trading section

1) Create SB Market
2) Add Pre Liquidity
3) Hit create Market _- I Do not get the "Sign to approve orders message" in the My created markets section of portfolio pg

![image](https://user-images.githubusercontent.com/41301809/94808933-df9a4b80-03bf-11eb-8f20-0e5792bb6978.png)

**Comment by matt-bullock** [comment]
fixed. Another ticket was created for the market not showing up under the all tab of my created markets
