### ISSUE TITLE
Odds convertor is broken

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#9359]
I added an offer (in implied probability at 35%)....Values should look like this:
![image](https://user-images.githubusercontent.com/41301809/94826123-fc8d4980-03d4-11eb-9c88-89fc1f05d25e.png)

But this is what is being shown in the UI:
Fractional-
![image](https://user-images.githubusercontent.com/41301809/94826251-1d559f00-03d5-11eb-8946-fe7d2bda0ebe.png)

Decimal - looks correct

American - 
![image](https://user-images.githubusercontent.com/41301809/94826348-39f1d700-03d5-11eb-9966-fd144c586579.png)

0-100%
![image](https://user-images.githubusercontent.com/41301809/94826427-4d9d3d80-03d5-11eb-9f77-86ae9bafb7cf.png)

**Comment by matt-bullock** [comment]
correct now
