### ISSUE TITLE
Design QA - Claim Stake & Fees Confirm status

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9378]
The tick icon that appears while tx is confirmed should be right-aligned as it is the processing icon.
Please, double check to apply this positioning across all modals that use the same component.

![claim-status](https://user-images.githubusercontent.com/49915900/95023992-b2b39600-0656-11eb-9eb1-b743e54f08fd.gif)

**Comment by matt-bullock** [comment]
currently broken. Waiting for updated ux

**Comment by matt-bullock** [comment]
looks good
