### ISSUE TITLE
Filters not showing up at tablet size

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9384]
![image](https://user-images.githubusercontent.com/39496225/95183448-49529500-07c6-11eb-93ce-6f1c57c0744c.png)

**Comment by JohnDanz** [comment]
Aren't filters going away? or am I misinformed? That filter button/sort by button is eliminated last I talked to chwy and yanel and I removed it from dev on the market list. Do we have any meaningful filters for tablet/mobile?Futures/Games would appear on top, categories can be found in the top left burger menu when you are on that page.

@Chwy5 can you clarify there?

**Comment by Chwy5** [comment]
For markets list pg, we wont have filters, - closing this ticket we have additional one with "How it should work"
