### ISSUE TITLE
Betslip transition on tablet

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9390]
Prototype: https://framer.com/share/SportsBook-Mobile-Prototype-Tablet-betslip-transition--18CV0EqIa9wMyvRLjpT8

Code:

// On Tap - Navigation
type: "tween",
delay: 0,
duration: 0.3,
ease: [0.44, 0, 0.56, 1],

tapping any of the backdrop should close the betslip

**Comment by JohnDanz** [comment]
also touch up style for tablet/tiny breakpoints and the slide out effect to match mocks.

**Comment by matt-bullock** [comment]
Seeing this on my tablet

![image](https://user-images.githubusercontent.com/39496225/95991416-08ddc180-0e2d-11eb-9b1b-193bd5bfa320.png)

**Comment by matt-bullock** [comment]
- Can you fade in and out the background overlay 

 - Clicking background should close the betslip

- Clicking a bet should open the betslip
