### ISSUE TITLE
Uncaught TypeError: Cannot read property 'constructor' of null

### ISSUE THREAD

**Issue by carver** [AugurProject/augur#94]
When using client.augur.net on the main (Olympic) testnet.

Browser gets stuck at the loading screen with this at console:
```
//one of these:
Uncaught TypeError: Cannot read property 'constructor' of null
augur.run.augur.execute.augur.invoke @ app.js:7003
...
//followed by tons of these:
Uncaught TypeError: this.state.asset.cash.toFixed is not a function
render @ app.js:2147
...
```

Any suggestion on how to copy a full stack trace from chrome console without the rows smashing together?

**Comment by scottzer0** [comment]
i just fixed this.  mainly an issue with the new geth account management notions changing underneath me.  pushing coming soon.

**Comment by tinybike** [comment]
You should be able to use `Error().stack` to get a stringified stack trace.

**Comment by carver** [comment]
Sweet
