### ISSUE TITLE
some markets missing their estimated start times

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9404]
![image](https://user-images.githubusercontent.com/39496225/95345494-10481c80-08bb-11eb-8c61-395f093d096a.png)

**Comment by JohnDanz** [comment]
I'm unable to reproduce this, do we have any specific examples? @matt-bullock

**Comment by matt-bullock** [comment]
looks fixed

**Comment by matt-bullock** [comment]
Example was in the screenshot in the first comment. Made this exact market again and it's fixed

**Comment by matt-bullock** [comment]
Reopening this as the issue has come up again

**Comment by JohnDanz** [comment]
I have yet to be able to reproduce this. are you consistently seeing it on a specific market maybe? @matt-bullock

**Comment by matt-bullock** [comment]
Not seeing it either now. I'll close but lets keep an eye on it @JohnDanz
