### ISSUE TITLE
Bug with submitting all unsigned orders

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9405]
After confirming the modal doesn't close and gives the option to submit all again and allows me to sign again

![image](https://user-images.githubusercontent.com/39496225/95346735-708b8e00-08bc-11eb-9823-71c8e47238f5.png)

**Comment by phoebemirman** [comment]
@matt-bullock working on new design for this

**Comment by matt-bullock** [comment]
much better
