### ISSUE TITLE
Design QA - Please add arrow to My Create Markets so it's more clear that by clicking there, the Open Interest information will appear.

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9413]
<img width="509" alt="Screen Shot 2020-10-07 at 16 37 31" src="https://user-images.githubusercontent.com/49915900/95379283-92384580-08bb-11eb-8ed3-1826563d9ef7.png">

https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=8136%3A279410

**Comment by yanelbottini** [comment]
Hi @JohnDanz
Can we improve the arrow alignment so it has the same than the add liquidity?

<img width="571" alt="Screen Shot 2020-10-14 at 07 08 47" src="https://user-images.githubusercontent.com/49915900/95975165-335b5a80-0dec-11eb-9536-2bcbef70f599.png">

**Comment by matt-bullock** [comment]
Arrow should rotate on click like my active markets.

These also look like 2 different components that should be the same (one rotates and the other doesn't, one has a hover state and one arrow looks bigger)

![image](https://user-images.githubusercontent.com/39496225/96118453-d050ed00-0eeb-11eb-8b84-5ec9c5b7bc47.png)

**Comment by matt-bullock** [comment]
The arrow component is still missing the hover state on my active markets. Isn't this meant to share the same component as the expand button in my created markets?

**Comment by matt-bullock** [comment]
perfect
