### ISSUE TITLE
Remove gap between your overview and augur status 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9418]
![image](https://user-images.githubusercontent.com/39496225/95439856-7767de80-0958-11eb-951e-eba66bf30380.png)

**Comment by JohnDanz** [comment]
Proving to be much more difficult than it appears... need to re-think how we lay this page out I think to achieve the mock

**Comment by matt-bullock** [comment]
just nudge it up ;)

**Comment by yanelbottini** [comment]
Looks good
