### ISSUE TITLE
After creating a market it immediately disappears from the All tab

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9420]
![image](https://user-images.githubusercontent.com/39496225/95445801-b8afbc80-095f-11eb-95f0-2302a451b3d6.png)

I have to click open and then go back to all for it to appear

![image](https://user-images.githubusercontent.com/39496225/95445975-f9a7d100-095f-11eb-8a4e-e7716d6f8695.png)

**Comment by phoebemirman** [comment]
not seeing this

**Comment by matt-bullock** [comment]
fixed
