### ISSUE TITLE
Notifications: most recent should go to the top of the stack

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9441]
In the screenshot below the invalid filter notification is the most recent, yet it's not at the top

![image](https://user-images.githubusercontent.com/39496225/95585501-9f7e3d00-0a3f-11eb-965e-dd3425c41b1c.png)

**Comment by bconfortin** [comment]
@matt-bullock I've talked to the dev team and it's not possible to implement that without refactoring how our notifications work. They asked me to postpone this ticket.

**Comment by Chwy5** [comment]
This needs to be worked....We can Not have the most recent at the bottom as they will not be seen.  This used to work correctly

**Comment by matt-bullock** [comment]
looks fixed now
