### ISSUE TITLE
Design QA - Open Orders in resolved market

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9446]
Table is missing betting design:

<img width="871" alt="Screen Shot 2020-10-09 at 17 41 54" src="https://user-images.githubusercontent.com/49915900/95629650-bda36780-0a56-11eb-8eec-7bfb8e45c8d1.png">

This is an example of a modal with a similar type of info:

<img width="811" alt="Screen Shot 2020-10-09 at 17 43 44" src="https://user-images.githubusercontent.com/49915900/95629793-03603000-0a57-11eb-8daa-f2bfb99e33e6.png">

**Figma reference:**
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=7396%3A90753

**Comment by matt-bullock** [comment]
fixed
