### ISSUE TITLE
High risk notification: What info should be included on the notification bar?

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9448]
@Chwy5 can you help me with this text? 

<img width="1034" alt="Screen Shot 2020-10-09 at 17 46 51" src="https://user-images.githubusercontent.com/49915900/95630063-8a150d00-0a57-11eb-8cfb-d66faf15f45d.png">

**Comment by Chwy5** [comment]
@matt has ticket for this - closing this
