### ISSUE TITLE
Sort by not sorting correctly on popular markets

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9451]
The approach we propose to order the markets is the following:

- Popular markets should be ordered by the closest event Start time (Daily) or ending soon (Futures)

Once you enter to a category:

- Daily events should be ordered by the closest event Start time.
- Future events should be ordered by the closest ending time.

How it currently sorts on dev:

![image](https://user-images.githubusercontent.com/39496225/97327075-e5773580-1874-11eb-863e-d225ce8c26d1.png)
![image](https://user-images.githubusercontent.com/39496225/97327112-ee680700-1874-11eb-827f-9abbc10bfcf1.png)

**Comment by JohnDanz** [comment]
Going to do this ticket in 2 steps, first step being the visual removal of sort by and responsive updates to handle that. 2nd step will be setting up the sorting rules as described because I think we will ultimately need to shift some state around to achieve this and so it might be a bigger task.

**Comment by yanelbottini** [comment]
ok!

**Comment by matt-bullock** [comment]
@phoebemirman reopened this ticket and JD asked to assign to you

**Comment by matt-bullock** [comment]
looks correct now
