### ISSUE TITLE
Design QA - "View details" button on Market Cards

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9452]
The Politic market shown on the example should have the "View Market details" button as the NBA example below it.

<img width="761" alt="Screen Shot 2020-10-12 at 12 30 20" src="https://user-images.githubusercontent.com/49915900/95764352-b9f62780-0c86-11eb-82be-0f864137cfe5.png">

**Comment by JohnDanz** [comment]
~~I thought view market details was specifically for futures markets only? I didn't see any mocks with the view market details on anything except the futures style markets.~~

I take it back, that is a futures, adjusting now to show the link on any futures markets, regardless of the amount of outcomes.

**Comment by matt-bullock** [comment]
added
