### ISSUE TITLE
Design QA - Grouping markets on "My Bets"

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9454]
- Daily markets that belong to the same event should be grouped together:

<img width="1488" alt="Screen Shot 2020-10-12 at 12 57 37" src="https://user-images.githubusercontent.com/49915900/95767048-874e2e00-0c8a-11eb-9d86-f1b2d32b24a3.png">

- Future markets are not grouped (because it's not possible to group them as they could have different event expiration dates)

<img width="1491" alt="Screen Shot 2020-10-12 at 12 58 38" src="https://user-images.githubusercontent.com/49915900/95767134-ab117400-0c8a-11eb-84c0-12b89486c893.png">

Please notice how "High risk" should be handle for each case:

- For Daily event should be included near Market name
- For future markets should be included near Market status, at top of marketcard.

Expected behavior for Betslip / Active Bets:

- We don't group megatemplates events. 
- We just group the bets placed on the same market:

<img width="781" alt="Screen Shot 2020-10-13 at 10 25 23" src="https://user-images.githubusercontent.com/49915900/95866650-8ecf0f00-0d3e-11eb-963c-2865400c9015.png">

**Comment by matt-bullock** [comment]
![image](https://user-images.githubusercontent.com/39496225/96016827-857e9900-0e49-11eb-81bd-46d7a7a9826c.png)

The high risk market is missing the market type (Moneyline)
Should look like:

![image](https://user-images.githubusercontent.com/39496225/96016926-a0510d80-0e49-11eb-9334-f263964c4a92.png)

**Comment by matt-bullock** [comment]
closing as last issue is a duplicate
