### ISSUE TITLE
Create a new common button for the Redesigned UI

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#947]
This is the first issue to be tracked in the overall refactor effort discussed here: https://github.com/AugurProject/augur/issues/941

The goal will be to implement a common button component for the new redesigned buttons look and feel in away that is droppable into current designs without needing to individually style each button or creating new buttons and extending a pre-defined class.

For example, instead of our current method that looks like this:

```
<button
            className={classNames(Styles["TradingWrapper__button--submit"], {
              [Styles.long]: selectedNav === BUY,
              [Styles.short]: selectedNav === SELL,
              [Styles.disabled]: !s.trade || !s.trade.limitPrice
            })}
            onClick={e => {
              e.preventDefault();
              market.onSubmitPlaceTrade(
                s.trade,
                selectedOutcome.id,
                (err, tradeGroupID) => {
                  // onSent/onFailed CB
                  if (!err) {
                    this.clearOrderForm();
                  }
                },
                res => {
                  if (s.doNotCreateOrders && res.res !== res.sharesToFill)
                    handleFilledOnly(res.tradeInProgress);
                  // onComplete CB
                },
                s.doNotCreateOrders
              );
            }}
          >
            Place {selectedNav === BUY ? "Buy" : "Sell"} Order
          </button>
```

we would instead target a situation where we could do this:

```
{selectedNav === BUY ? 
  <BuyButton action={submitTradeAction} text="Place Buy Order" /> :
  <SellButton action={submitTradeAction} text="Place Sell Order />
}
```

This way it's easier to reuse these buttons. All the CSS would be contained within `BuyButton` or `SellButton` already. May also simply  have a: 
```
<OrderButton type={selectedNav} action={submitTradeAction} />
```
where type would dictate `BUY` or `SELL` and that would change the text.

**Comment by bthaile** [comment]
@JohnDanz Is this still in progress? If not move to backlog or close if done
