### ISSUE TITLE
If user has multiple markets to claim from in a modal but for whatever reason decides to only claim some of the individual markets, after closing the modal the VIEW button should reappear 

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9473]
Currently it gets stuck on the tick and the only way to get the view button to reappear is a hard refresh.

I suggest the tick disappears after a few seconds and the view button reappears allowing them to bring up the modal again

![image](https://user-images.githubusercontent.com/39496225/95988579-6243f180-0e29-11eb-8df3-f5d94b385db9.png)

**Comment by phoebemirman** [comment]
@matt-bullock working on new design for this

**Comment by phoebemirman** [comment]
https://www.figma.com/file/bZh7tOiLm6Ls9Hl4RL6qMC5X/Augur-Redesign?node-id=7110%3A283094

**Comment by matt-bullock** [comment]
Works well
