### ISSUE TITLE
Other should be the 3rd outcome not the 2nd here

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9475]
![image](https://user-images.githubusercontent.com/39496225/95999702-704c3f00-0e36-11eb-9d84-71dbd2a2692b.png)

**Comment by JohnDanz** [comment]
<img width="786" alt="Screen Shot 2020-10-15 at 3 01 18 PM" src="https://user-images.githubusercontent.com/10524630/96179930-49a20d00-0ef7-11eb-8a91-6ed417db13e5.png">
Fixed so it should only effect markets that have a "Draw" option and 4 outcomes.

**Comment by matt-bullock** [comment]
looks good
