### ISSUE TITLE
Recurring Market REP Price Feed

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#948]
https://docs.google.com/document/d/1hLHJ7TvetzIxjfnwGlCUNJ3iHX-VqpJuRkyOdUOXVFQ/edit

**Comment by pgebheim** [comment]
@nuevoalex -- We shoved this into backlog. Move it into Ready for Dev once you're ready to start thinking about doing it.

**Comment by nuevoalex** [comment]
👍 It's in the game theory evaluation stage now presuming this is specifically for the recurring market proposal

**Comment by nuevoalex** [comment]
Putting this on hold since it seems like we've come to a better state with the auction using much smaller targeted sale amounts (and therefore far far less maximum inflation risk)

**Comment by nuevoalex** [comment]
This is superceded by returning to the auction with lower mint numbers
