### ISSUE TITLE
Design QA - Transaction Fee Modal

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9499]
Please, match font color and style to improve readability:

<img width="1334" alt="Screen Shot 2020-10-16 at 09 58 28" src="https://user-images.githubusercontent.com/49915900/96260974-27130100-0f96-11eb-9e50-d934762f9aa3.png">

**Figma reference:**
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=9777%3A309884

**Comment by yanelbottini** [comment]
Comments on the image:

<img width="1430" alt="Screen Shot 2020-10-28 at 05 58 23" src="https://user-images.githubusercontent.com/49915900/97414349-a384d880-18e2-11eb-9e5e-dbe87e920785.png">

**Comment by matt-bullock** [comment]
looks fine
