### ISSUE TITLE
AN in Browser MVP: Use blockstream to retrieve new blocks after initial sync

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#951]
This will require Scott's PR to get merged into ethers.js first: ~~https://github.com/ethers-io/ethers.js/pull/412~~ (Now merged)

**Comment by pgebheim** [comment]
@justinbarry First order of business tomorrow can you break this into a couple smaller tasks so we can see what needs to be done?

First thoughts here are that we need to verify that we are on the newest version of Ethers which supports getBlockByHash, also make sure that that the ethers support works for Blockstream (Micah uses this), and then see about integrating it into the current codebase. The last piece may be relatively complex. So I recommend at least 2 issues, one for getting blockstream working with ethers, and another for integrating the code.

**Comment by justinbarry** [comment]
@pgebheim Sounds good! See #1088 #1089

**Comment by pgebheim** [comment]
Check this out!

We can turn this into an epic and include those issues. Sub-epics work in Zenhub so we can track this all together as a unit even though it spans sprints.

Neat huh? Also, I'm gonna update those issues, but please double check them and make sure they're in the right states.
