### ISSUE TITLE
Mobile: betslip button at bottom shouldn't show up if empty

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9549]
![image](https://user-images.githubusercontent.com/39496225/97309554-77297780-1862-11eb-90de-74994206ab86.png)

**Comment by matt-bullock** [comment]
@phoebemirman still seeing it. has it not merged yet?

![image](https://user-images.githubusercontent.com/39496225/97682507-711cdc00-1a98-11eb-8e13-04bdabf045e3.png)

**Comment by phoebemirman** [comment]
looks right for me. maybe try a refresh?
