### ISSUE TITLE
investigate balances

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#9563]
we have gotten reports that our balances don't always match. we should investigate where we are displaying balance, how we get that value, and if it's indeed accurate. if it is, we will need to work on messaging, if it's not, we need to fix the issue.

**Comment by Chwy5** [comment]
![image](https://user-images.githubusercontent.com/41301809/97441853-8dd1dc00-18ff-11eb-8533-86135dece28f.png)

**Comment by phoebemirman** [comment]
total account value is dai balance + total frozen funds
dai value shown in your account dropdown is just the dai balance

@Chwy5 should it be showing other things here?

**Comment by Chwy5** [comment]
The issue above is I had open orders which just gets clumped into total exposure....Will think how to handle this scenario and get back to you

**Comment by Chwy5** [comment]
removed AS pg, will not have discrepancy anymore...which was caused by FF from open order in trading, which isnt possible on sb
