### ISSUE TITLE
Mobile logged out state: top bar is missing sign up and login buttons.

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9569]
Design (don't include logo)

https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet-Design-System?node-id=283%3A145

![image](https://user-images.githubusercontent.com/39496225/97588767-21d59d80-19fd-11eb-9ea7-b455b9397468.png)

Dev:

![image](https://user-images.githubusercontent.com/39496225/97588989-50ec0f00-19fd-11eb-96d4-5bca3a2dd8dc.png)

**Comment by yanelbottini** [comment]
Connect and Signup Buttons are bigger than should be.

**Comment by yanelbottini** [comment]
Size seems fine, but could we improve alignment for those buttons?

<img width="607" alt="Screen Shot 2020-11-16 at 08 38 47" src="https://user-images.githubusercontent.com/49915900/99248463-3c728980-27e7-11eb-8cad-d1d97383df7d.png">

**Comment by matt-bullock** [comment]
looks good
