### ISSUE TITLE
Mobile pagination visually needs fixing + remove show filter

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9572]
This 

![image](https://user-images.githubusercontent.com/39496225/97593240-ca85fc00-1a01-11eb-9222-42ed2d6fca95.png)

Should look like this

![image](https://user-images.githubusercontent.com/39496225/97593207-c063fd80-1a01-11eb-9da7-b330ffce2673.png)

Design: https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=3909%3A17

**Comment by yanelbottini** [comment]
Looks fine mobile, but now seems broken on desktop:

<img width="817" alt="Screen Shot 2020-11-16 at 07 37 16" src="https://user-images.githubusercontent.com/49915900/99242897-9de22a80-27de-11eb-8d66-2ec16180463a.png">

**Comment by matt-bullock** [comment]
looks good
