### ISSUE TITLE
Mobile: Market page still needs work to better match design

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9576]
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=4106%3A189124

Just go over all the individual elements - sizes, spacing, layout etc and try to match. Then we can do a QA pass with more detail but currently it mostly should be obvious what needs fixing

**Comment by matt-bullock** [comment]
@JohnDanz Looks a lot better. I've gone through it and added notes in the image below. Should be good after these 

![image](https://user-images.githubusercontent.com/39496225/98373003-e4958f00-203e-11eb-8e95-1caea4fae4ac.png)

Another small thing: font size for outcomes is 12px rather than 14px

![image](https://user-images.githubusercontent.com/39496225/98373305-58d03280-203f-11eb-98d1-6d961ebd9f4d.png)

**Comment by JohnDanz** [comment]
I didn't change the name drop downs for charts or favorites (cuz it's going away). I didn't change dropdown because I wanted to talk to chwy about it to make sure since it might not be enough information to just say moneyline/over under etc. It's a quick change so will update in the future.

**Comment by matt-bullock** [comment]
Can you increase the line height of the paragraph text to 140% (19.6px) Not sure of the rem value. This will make it easier to read as it won't be so bunched up.

![image](https://user-images.githubusercontent.com/39496225/98665332-d3ed5d80-234b-11eb-9328-602dc7d176e7.png)


Can you reduce the space at the bottom of the page to 24px.

Did you ask Chwy about the chart switcher dropdown? As far as I'm aware we're running with what's in the design as I remember having a meeting about this when the decision was made.

Rest looks good

**Comment by matt-bullock** [comment]
Can you remove you dotted underline as it's not working when text goes onto 2 lines

![image](https://user-images.githubusercontent.com/39496225/98805083-5db62d00-2417-11eb-949c-4e8c4786be3c.png)

And move the dropdown arrow closer to the text - like the design

![image](https://user-images.githubusercontent.com/39496225/98805222-89d1ae00-2417-11eb-83b9-79d0b13472d0.png)


Then this page is in a good place

**Comment by matt-bullock** [comment]
@JohnDanz can we shift around the title, dropdown and time switcher at the top to make it work better. We made some edits in the design below.

https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet-Design-System?node-id=185%3A0

![image](https://user-images.githubusercontent.com/39496225/99069751-43af5280-25af-11eb-8d74-c5fcccc6ff6e.png)

**Comment by yanelbottini** [comment]
Looking at at this market: 
https://dev.augur.net/#!/market?id=0x0b3A1BFe0C13A450e0B4bd57412778B2dcab7216&t=SPORTS

The dropdown should be hide in this case, but the control is showing up empty:

![WhatsApp Image 2020-11-16 at 07 44 48](https://user-images.githubusercontent.com/49915900/99243920-1e555b00-27e0-11eb-9951-c7ff87613589.jpeg)

<img width="808" alt="Screen Shot 2020-11-16 at 07 47 48" src="https://user-images.githubusercontent.com/49915900/99244130-6d02f500-27e0-11eb-8000-8917b739927c.png">

Distance between market name and arrow should be 4px.

----

There is one Share icon that is not aligned:

![WhatsApp Image 2020-11-16 at 07 44 48 (1)](https://user-images.githubusercontent.com/49915900/99244160-7724f380-27e0-11eb-833c-de851fbd1bc5.jpeg)

**Comment by JohnDanz** [comment]
I don't think any of them are actually styling reasons. Assuming the screenshots are all from that market, the charts should have a dropdown as there is multiple markets. the problem here was switching from market name to sportsbook Title. futures don't have titles, so the values are blank. That's working as intended but we didn't think through all the permutations when switching from market title to sportsbook short title (money line, spread 3.5, etc) 

The market name is 4px away from the arrow, there's a blank space between Price History (which is just a static label and is on every single chart no matter what) Missing Title as explained in the above paragraph, then the arrow.

**Comment by matt-bullock** [comment]
@JohnDanz I'm not seeing the dropdown next to price history here 
![image](https://user-images.githubusercontent.com/39496225/99518308-ada17080-2990-11eb-8fb8-f9c08a68805f.png)

**Comment by JohnDanz** [comment]
@matt-bullock if there's only one market made, even though it's a combo market, it's going to hide the dropdown...cuz the only option is the one market.

**Comment by matt-bullock** [comment]
makes sense. Closing, but may later address a way to better show markets that haven't been created
