### ISSUE TITLE
Add total exposure breakdown modal

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9582]
@yanelbottini to supply sportsbook styling version

Same as frozen funds modal breakdown in trading

User clicks total exposure figure (underlined)

![image](https://user-images.githubusercontent.com/39496225/97619100-16479e00-1a20-11eb-9868-07441cc9089e.png)

Modal to open up like trading

![image](https://user-images.githubusercontent.com/39496225/97619265-4bec8700-1a20-11eb-8659-8ebbbee80a0e.png)

To show both data from trading and betting

![image](https://user-images.githubusercontent.com/39496225/97619378-73dbea80-1a20-11eb-92dc-f94524a83b90.png)

**Comment by yanelbottini** [comment]
@matt-bullock I've prepared the modal:

![Modal](https://user-images.githubusercontent.com/49915900/97694454-5ab75600-1a81-11eb-8a0a-0cc9b4ff7e7e.jpg)

**https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=10096%3A0**

**Comment by matt-bullock** [comment]
@phoebemirman Could you remove the custom market tag which appears to be replacing the market title and put back in the market title

![image](https://user-images.githubusercontent.com/39496225/97895456-18696f80-1d34-11eb-8133-925913184612.png)

**Comment by matt-bullock** [comment]
@phoebemirman can the button say 'Close' rather than 'Cancel'

Any idea why some market titles are missing? Are these just older markets that were broken from before?

![image](https://user-images.githubusercontent.com/39496225/98103829-e4a65b00-1e95-11eb-8a04-55c3fe040b19.png)
