### ISSUE TITLE
Transaction trade term wrong

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#959]
User reported the transaction page is showing sold when they bought shares. Need to verify transaction trades have correct verbiage from filler spective

**Comment by pgebheim** [comment]
Gonna do the DIP part of this task right now and see if I can add some more info.

**Comment by pgebheim** [comment]
I don't see anything obvious. I'm gonna add this to V2 Portfolio page epic so that we can check it out along with that re-design work.

@JohnDanz Maybe you can investigate when it comes to time?

**Comment by Chwy5** [comment]
addressed in new redesign
