### ISSUE TITLE
User withdraws ETH fails

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#960]
User's can withdraw all ETH in their account, which will silently fail because the UI doesn't take gas costs into account when verifying user has enough ETH to transfer.

**Comment by joeykrug** [comment]
How'd you figure out this? definitely critical ^^

**Comment by pgebheim** [comment]
Wait... withdraw their eth... where?

Augur has no custodial mechanics so whatever ETH they have is in their wallet. If you mean they can cancel all escrowed orders then the user would HAVE to have enough eth for the gas to submit that transaction (and MM or ledger or something would give an error -- not that we shouldn't ALSO give an error).

**Comment by pgebheim** [comment]
Oh I see this https://try.augur.net/#!/withdraw-funds where we actually just do a normal transaction to send from one account to another.

They're able to enter any amount of ETH or REP into that; and while I guess it would be nice if we had better UX around it, this seems low priority to me as its not like we have any control over those funds anymore than they do from MEW or anywhere else.

**Comment by pgebheim** [comment]
@joeykrug -- Lemme know if its still critical with that info.

We don't have a "Withdraw all" button or anything -- if it is we can move it into Ready for Dev and keep the label, else change to Priority: Medium and keep in backlog.

**Comment by bthaile** [comment]
User posted video of the issue in #issues channel.
