### ISSUE TITLE
Convert python2 to python3 in preparation for python3 deprecation.

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#962]
Python2 deprecates at the end of the year. [See the clock](https://pythonclock.org/). We have tests running in python2 that need to run in python3.

This task includes this subtasks:

1. Run the tests using python3 to determine the extent of the conversion needed. This allows an estimate to be made. It's possible that our code is already python3-compatible so no fixes are needed.
2. Fix the tests, if any fixes are needed. Consider [this tool](https://docs.python.org/2/library/2to3.html) to speed things up.

**Comment by pgebheim** [comment]
@robert-e-davidson3 -- Do you wanna Backlog this or take care of it now? If so, move it into Ready for Dev.

**Comment by pgebheim** [comment]
@petong does your branch that you mentioned that gets rid of py2 mean this is defunct?

**Comment by pgebheim** [comment]
This is still valid!
Tests still need to be converted.

**Comment by pgebheim** [comment]
@petong Sending this your way since you expressed interest in taking a stab at it.

**Comment by petong** [comment]
All the docker work to run on python3 is done. basic changes to python syntax is done, however pyethereum is now deprecated and we are moving to something like py-evm

**Comment by nuevoalex** [comment]
Conversion to py-evm is complete and the tests pass using python 3.6
