### ISSUE TITLE
Design QA - Mobile Menu

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9621]
<img width="805" alt="Screen Shot 2020-11-05 at 09 25 21" src="https://user-images.githubusercontent.com/49915900/98240868-d9603780-1f48-11eb-8986-c45225ed2d85.png">

- Missing Connect / Sign up button
- Lines are smaller than menu area
- Menu seems taller than should be
- Missing Augur Logo

<img width="405" alt="Screen Shot 2020-11-03 at 07 57 58" src="https://user-images.githubusercontent.com/49915900/97977727-67062080-1dab-11eb-8e9c-9c57959e71ac.png">

- Account menu seems broken. 

<img width="337" alt="Screen Shot 2020-11-03 at 07 56 54" src="https://user-images.githubusercontent.com/49915900/97977850-8ef58400-1dab-11eb-9f0c-a58fa2d2a337.png">

- Missing bkg overlay behind the Alert area.

**Comment by JohnDanz** [comment]
completed from another ticket.
