### ISSUE TITLE
Mobile iPhone menu is broken

### ISSUE THREAD

**Issue by bconfortin** [AugurProject/augur#9642]
Ok, when using iPhone, login and try to open the side menu. Sometimes it shows the links, sometimes it doesn't.

Possible scenario:
- The topbar is extending all the way to the bottom and overlaying everything

![image0](https://user-images.githubusercontent.com/10351013/98137576-e4f82380-1ea0-11eb-8e4b-aa546e826fea.png)

![image1](https://user-images.githubusercontent.com/10351013/98137578-e6295080-1ea0-11eb-8500-a1aa89845ee3.png)

**Comment by matt-bullock** [comment]
@bconfortin Assume you tested this on your phone as I wasn't able to reproduce in chrome and don't have an iphone
