### ISSUE TITLE
Mobile trading cards - user stake indicators broken

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9653]
Should stack horizontally with 4px between icons

This

![image](https://user-images.githubusercontent.com/39496225/98227809-09630700-1f58-11eb-9c6f-d6e78f79a284.png)

not this

![image](https://user-images.githubusercontent.com/39496225/98227738-f0f2ec80-1f57-11eb-8c6c-1b86fdd4b398.png)

**Comment by JohnDanz** [comment]
Fixed this in another PR, feel free to confirm.
