### ISSUE TITLE
Mobile: My Bets button is loading the betslip every other tap + my bets doesn't need loading transition

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9656]
I feel like clicking the my bets doesn't need a transition. Should just load in instantly like alerts. Can you also make this chnage please

![Kapture 2020-11-05 at 11 36 55](https://user-images.githubusercontent.com/39496225/98230358-54324e00-1f5b-11eb-88c5-fdbd368e62f2.gif)

**Comment by yanelbottini** [comment]
Seems fine, but now the back icon doesn't make sense (It did when the menu had the bottom transition). 

Can we replace it with a close icon?

<img width="594" alt="Screen Shot 2020-11-16 at 09 35 12" src="https://user-images.githubusercontent.com/49915900/99253168-0d601600-27ef-11eb-8e0d-e21418097035.png">

Should be:
<img width="413" alt="Screen Shot 2020-11-16 at 09 36 28" src="https://user-images.githubusercontent.com/49915900/99253269-3aacc400-27ef-11eb-9450-7687fb50a168.png">


**Reference:**
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=3909%3A2221

**Comment by matt-bullock** [comment]
@JohnDanz I'm still seeing the betslip load in every other click
