### ISSUE TITLE
bug modal needs to follow new modal style in redesign

### ISSUE THREAD

**Issue by phoebemirman** [AugurProject/augur#967]
<img width="1214" alt="screen shot 2019-02-04 at 2 53 41 pm" src="https://user-images.githubusercontent.com/6775839/52242872-b80e7b00-288c-11e9-83cf-89d4aaa2a9ab.png">

**Comment by pgebheim** [comment]
@phoebemirman Can you add this to one of the redesign epics and give it an estimate?

This doesn't seem like a bug to me, more like an improvement.
