### ISSUE TITLE
Design QA - Please update "View market details" style on market cards

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9680]
We have updated the style for the "View market details" button to differentiate it from the "More Wagers" one:

<img width="1470" alt="Screen Shot 2020-11-08 at 23 20 41" src="https://user-images.githubusercontent.com/49915900/98493376-0e0a1280-2219-11eb-949a-0b287d8c7f4c.png">

**Comment by matt-bullock** [comment]
**MORE WAGERS (1)** button should be all caps and **View market details** lower case

This rectangle needs to be a bit bigger - 40px height
![image](https://user-images.githubusercontent.com/39496225/98666844-e1a3e280-234d-11eb-9545-7c8a9fb6814b.png)

**Comment by matt-bullock** [comment]
looks good
