### ISSUE TITLE
Remove favorites button from sportsbook (From market cards and market detail pgs)

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9682]
As we're removing the account summary we'll need to remove the favourites. It's not a necessity as any markets the user has placed a bet on will show up in my bets.

@yanelbottini to supply updated designs here.

**Comment by yanelbottini** [comment]
Updated market cards without Favorite Icon:

**https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet-Design-System?node-id=1140%3A0**

Please notice that FAV icon should be also removed from Market detail page:
<img width="1084" alt="Screen Shot 2020-11-09 at 11 39 54" src="https://user-images.githubusercontent.com/49915900/98555118-4db81500-2280-11eb-8dca-7203eb65529a.png">

**Comment by matt-bullock** [comment]
removed
