### ISSUE TITLE
Move notifications to bell alerts dropdown

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9683]
As we're removing the account summary page where they currently live.

@yanelbottini to supply the design

**Comment by yanelbottini** [comment]
This is the design with the Bell window combining both Alerts & Notifications:

**Desktop:**
<img width="672" alt="Screen Shot 2020-11-09 at 11 02 38" src="https://user-images.githubusercontent.com/49915900/98550686-2d398c00-227b-11eb-901b-d0ce9b74c586.png">

**Mobile:**
<img width="428" alt="Screen Shot 2020-11-09 at 11 02 41" src="https://user-images.githubusercontent.com/49915900/98550698-30cd1300-227b-11eb-80b0-efa08ff9dd11.png">

Figma Reference:
https://www.figma.com/file/42QoTLQcbObu7esoTPjWRv/Augur-Bet-Design-System?node-id=283%3A145

----

"View all TX" access will be included on "My bets" section:

<img width="1507" alt="Screen Shot 2020-11-09 at 11 11 35" src="https://user-images.githubusercontent.com/49915900/98551708-5f97b900-227c-11eb-9e17-898f21364536.png">

**Comment by yanelbottini** [comment]
Can we update the style for notifications to match design:

<img width="976" alt="Screen Shot 2020-11-16 at 08 30 45" src="https://user-images.githubusercontent.com/49915900/99247689-0ed91080-27e6-11eb-9821-508018293241.png">

**Figma reference:**
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=10177%3A44943

**Comment by matt-bullock** [comment]
looks good
