### ISSUE TITLE
Scalar / Categorical Reporting

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#97]
In order to make things cheap for consensus, when this type of reporting gets implemented in UI I would like things to be passed as params as follows:

Let's say we're reporting on Apple price, min is 0 max is 250
Our example user reports 127

Now, don't pass me 127, instead we're going to convert it to a number between 0 and 1, here's now:

1) Take 127 (the value reported) and subtract the min (0), you now have 127 again
2) Do 127 / (max - min), so 127 / (250) which = 0.508.  Pass me .508 in fixed point.

Now let's do a categorical example:
Say there are 9 outcomes
1-9

If the user says it's outcome 4 do:
1) take 4-1 = 3
2) do 3/ (9-1) == 3/8 == 0.375.  Pass me .375 in fixed point.

Note: if someone reports "indeterminate" for a scalar or a categorical, pass .5 * 2^64, however if someone reports 0.50 as the actual outcome, i.e. the real result was 0.50, pass .5 * 2^64 + 1

**Comment by tinybike** [comment]
Folded into #259.
