### ISSUE TITLE
NCAA Football National Championship template broken in market creation

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#9710]
![image](https://user-images.githubusercontent.com/41301809/99094329-aa2d7400-25a1-11eb-9220-85db63ba55f4.png)

This appears even though I have all the fields filled in including adding 6 teams

**Comment by phoebemirman** [comment]
seems there is an extra input in inputs that isn't being used

**Comment by Chwy5** [comment]
fixed- closing
