### ISSUE TITLE
Claim Winnings isn't updating after claiming. Only disappears after manual refresh

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9714]
Still seeing this full amount despite claiming all

![image](https://user-images.githubusercontent.com/39496225/99106917-50e73400-25e5-11eb-9b3d-8d3db923d6ad.png)

**Comment by phoebemirman** [comment]
this is working for me. can you let me know if still happening?

**Comment by matt-bullock** [comment]
@phoebemirman It's working now. On thing though:

I did 'claim all' and the modal instantly disappeared after signing the tx. There was no feedback in the UI that it was processing and only about 20 seconds or so after metamask confirmed the tx did it go away.

Can you add a processing state and confirmed state to this button and then I think we're good

![image](https://user-images.githubusercontent.com/39496225/99524574-e8a7a200-2998-11eb-98c1-8264025e99d5.png)

**Comment by matt-bullock** [comment]
much better
