### ISSUE TITLE
JShint + Flow

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#972]
Two things that would help w/ code quality imo, adding:

flow.org + 

https://github.com/jshint/jshint

[came across them just browsing GitHub]

**Comment by tinybike** [comment]
Agree that static typing would be nice, although it'd be a lot of work to bolt it on to the UI at this point; up to @stephensprinkle whether Flow (and/or TS) is worth the time/effort.  The UI already uses a linter, eslint -- basically it's a more evolved, configurable version of jshint!

**Comment by stephensprinkle** [comment]
We also utilize `stylelint` for our stylesheets.

At this point, it’s not worth the effort to implement TS, but that suggestion is in the vein of broader implementation improvements I’m starting to plan for after Augur is live.

@joeykrug — if you’ve identified specific code quality issues, I’d love to know to slate them for cleanup.

**Comment by stephensprinkle** [comment]
Closing for now.

**Comment by joeykrug** [comment]
> At this point, it’s not of a sufficient priority to implement TS, but that suggestion is in the vein of broader implementation improvements I’m starting to plan for after Augur is live.

Reason I mentioned flow is it's easier to integrate and may not be as much work, you can add it in and do nothing if you like, then once in a while while developing add type annotations, or add them going forward, and it automatically / intelligently propagates through
