### ISSUE TITLE
Design QA - View Transactions modal

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9721]
There are some elements that are not property styled: 

**Figma reference:**
https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=4073%3A235

<img width="1403" alt="Screen Shot 2020-11-16 at 08 55 48" src="https://user-images.githubusercontent.com/49915900/99249888-8fe5d700-27e9-11eb-94c6-ab0650f4ca83.png">

<img width="1551" alt="Screen Shot 2020-11-16 at 08 55 27" src="https://user-images.githubusercontent.com/49915900/99249872-8bb9b980-27e9-11eb-90d2-bb609f7e6bfc.png">

**Comment by JohnDanz** [comment]
@Chwy5 I'm going to hide this button from the sportsbook ui. It turns out we will most likely not need this at all by the time sportsbook launches so we are going to not work on it unless it actually is going to be needed in which case we can fix it prior to launch.
