### ISSUE TITLE
AM/PM switcher not working

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#9723]
I changed the 24hr display in settings to AM/PM and doesnt update- still displays in 24hr setting

![image](https://user-images.githubusercontent.com/41301809/99261528-d7b92e00-27ea-11eb-9d1f-c1b357978491.png)

**Comment by JohnDanz** [comment]
As I recall this is because unlike the odds we haven't factored in the time everywhere. We are keeping track of the user's preference but doing nothing with that information. Really this is more of a "hey, go fully implement this feature we only half did" instead of a bug. Will update.

**Comment by matt-bullock** [comment]
Should we remove seconds from the 24hr format in estimated start time? The seconds aren't changing anyway and they're not in the am/pm format. Will help to cut down on noise

![image](https://user-images.githubusercontent.com/39496225/99514390-fdca0400-298b-11eb-807a-f9f490930e23.png)

**Comment by JohnDanz** [comment]
for sports only? cuz remember time is a global thing, are you suggesting removing seconds form 24 time on trading or specifically only on sportsbook? What if it is down to 30 seconds left, it will appear as 00 minutes left but not actually have started.

**Comment by matt-bullock** [comment]
done
