### ISSUE TITLE
Tennis doubles template missing 'Mixed' in dropdown

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9738]
[Men's/Women's/Mixed] Doubles Tennis [Year] [Event] (O/U), [Player/Player A] vs. [Player/Player B]: Total [games/sets] played in a match; Over/Under [Whole #].5?

![image](https://user-images.githubusercontent.com/39496225/99431036-653f6f80-290a-11eb-9336-548020174c30.png)

**Comment by Chwy5** [comment]
fixed closing
