### ISSUE TITLE
Off-chain references to erc777 will need to update named parameter from _owner to _tokenHolder

### ISSUE THREAD

**Issue by epheph** [AugurProject/augur#974]
On-chain, it doesn't make a difference, because contract interaction is positional, but things like create-market and other off-chain tools will need to use the new name when referencing erc777 contracts

**Comment by joeykrug** [comment]
what's this?? @nuevoalex

**Comment by nuevoalex** [comment]
Yea this is done already. No need for an issue either for any straglers as they would just break and we'd fix it.
