### ISSUE TITLE
error message doesnt go away during market creation

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#9750]
the error message stays if it is triggered and then corrected...even if user moves forward between steps

to recreate....chose a market with a dropdown for the year in the future like 2021 (can do with NCAA BB who will win championship market)...when setting expiration date set it for 2020...this will trigger this message.  Then go and change the date to 2021....this will allow u to move forward, but the message doesnt disappear

![image](https://user-images.githubusercontent.com/41301809/99546564-88a70080-2984-11eb-9aa1-a7c2f4db660d.png)

**Comment by matt-bullock** [comment]
fixed
