### ISSUE TITLE
Design QA - Please reduce font-size for for categories (All breakpoints)

### ISSUE THREAD

**Issue by yanelbottini** [AugurProject/augur#9763]
As we are using All Caps on categories, we need to reduce the font-size:

<img width="496" alt="Screen Shot 2020-11-19 at 08 18 36" src="https://user-images.githubusercontent.com/49915900/99661883-3ed11f80-2a43-11eb-8ee7-5bd18cf06459.png">
<img width="393" alt="Screen Shot 2020-11-19 at 08 18 25" src="https://user-images.githubusercontent.com/49915900/99661887-41cc1000-2a43-11eb-8f00-560cb7966734.png">

Figma reference Desktop:
**https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=4404%3A1803**

Figma reference Mobile:
**https://www.figma.com/file/wogMuUDylgOHgTEYhZ3jgp/Augur-Bet-UI?node-id=5287%3A613**

We also need to reduce the font-size for the category name on each category page:

From 24px to 20px on desktop
From 20px to 16px on mobile

<img width="419" alt="Screen Shot 2020-11-19 at 08 46 51" src="https://user-images.githubusercontent.com/49915900/99662265-c9198380-2a43-11eb-8355-54392c7f773f.png">

<img width="253" alt="Screen Shot 2020-11-19 at 08 47 06" src="https://user-images.githubusercontent.com/49915900/99662287-cfa7fb00-2a43-11eb-9567-3c9589207538.png">

**Comment by matt-bullock** [comment]
looks much better
