### ISSUE TITLE
When selecting a category should take user to correct type

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#9769]
For Example  If I click on the boxing category button it takes me to an empty pg under futures for Boxing.  All boxing templates are Daily...Should take me to the daily section under boxing

Rule should be, when clicking on a sports category to always take user (or display) Daily first, unless there are currently no daily markets at that moment for that sport, then can show Futures first

**Comment by matt-bullock** [comment]
When I click car racing it opens Futures, even though there are many daily markets. 

Same for american football & Hockey and probably the rest (site is running slow so haven't tested all)

**Comment by yanelbottini** [comment]
Seems fine now!
