### ISSUE TITLE
Portfolio Page Redesign: Augur Node

### ISSUE THREAD

**Issue by pgebheim** [AugurProject/augur#978]
- [ ] Add Current Value for each market to getUTP results

**Comment by bthaile** [comment]
`getUTP` I assume means get user's current ETH value on a market. This will populate user's portfolio `Current Value` so they can sort.

![screen shot 2019-02-13 at 1 10 07 pm](https://user-images.githubusercontent.com/3970376/52736947-bb8eba00-2f90-11e9-8ca8-8a06aac9a9c0.png)

**Comment by Chwy5** [comment]
already been handled by pnl changes to augur node
