### ISSUE TITLE
Mobile: Selecting a category and reopening the menu causes error

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9795]
this happens

![image](https://user-images.githubusercontent.com/39496225/100452754-0a500a00-30ba-11eb-9ec7-7341af5e68ea.png)

**Comment by JohnDanz** [comment]
Note from Matt: "so if I click a category; say NHL. So I'm seeing all the NHL markets. Then I reopen the menu - all the categories disappear"

**Comment by yanelbottini** [comment]
Seems fine now
