### ISSUE TITLE
Finalized Market Header doesn't show show winning outcome

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#981]
https://augur.casino/id=0x4ce1f159b8e2ed4f32684b16f933e2273f09513b
https://augur.casino/id=0xfd23e32d0902b3d1ae24986d34e1a59d10f87f2d

between these 2 finalized markets, one shows the winning outcome and the other doesn't. Both are finalized.

**Comment by pgebheim** [comment]
Won't Fix V1 Issue
