### ISSUE TITLE
Spike: Full-Text Search in Augur State

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#983]
FlexSearch seems like a good option to try vs a custom PouchDB setup: https://github.com/nextapps-de/flexsearch/blob/master/README.md

**Comment by pgebheim** [comment]
@justinbarry -- lets leave this until Friday, but I think this is the most likely issue to move into belligerent banana.

**Comment by pgebheim** [comment]
Goal:

We want to do attempt to implement full-text search of Market data using an existing Browser-compatible FTS library.
https://github.com/nextapps-de/flexsearch/blob/master/README.md

For this implementation we will need to handle the MarketCreated logs that are being parsed by one of the DB classes in Augur State, this can be done by subclasses the DB implementation for MarketCreated and adding the code to add market data to the FTS datastore.

Then we can make a getter to access this data and see if it works as expected and is performant enough to be our full solution.

What needs to be indexed?

Market Title
Market Description
Tags + Categories (as one field is fine as they will be unified in the UI we think).
Start Date
End Date
