### ISSUE TITLE
Frozen funds change

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur#988]
![ts-snippet](https://user-images.githubusercontent.com/5925937/52514949-0abc9f80-2bcb-11e9-9a2a-c97b49f70a17.jpg)

Like ^

**Comment by joeykrug** [comment]
https://gist.github.com/joeykrug/e9b23731bff59b456d348335da2cfc79 has info on it + what assertions to maintain. Make sure to write tests for the assertions (they may uncover a bug in the spec)

frozen_funds
available_funds
profits		
total_funds

Are the things we want

**Comment by nuevoalex** [comment]
The data used in the tests which includes expected frozen funds and avail funds data is here: https://docs.google.com/spreadsheets/d/1ItTonxo_kBS9BBEurD_dU2ju-CoTN549O8wrA5_74VY/edit#gid=108380513

**Comment by pgebheim** [comment]
@ryanberckmans -- Can you  move this into In Progress and add an Estimate?

**Comment by joeykrug** [comment]
The gist has been updated to have a accurate way of calculating these things that is also much simpler btw

**Comment by ryanberckmans** [comment]
Latest public API and algorithm based on conversation with Alex/chwy

## frozen funds public API

frozenFunds will be added as new field to getUserTradingPosition()'s TradingPosition. These TradingPositions are returned per-outcome and we will track frozen funds per outcome.

Front end uses it like `getUserTradingPositionResponse[i].frozenFunds`.

TBD - `frozenProfit`, `availableFunds`

## frozen funds algorithm

```
getMyFrozenFunds()
    for trade of trades
        frozenFunds[marketId][outcome] += numCreatorTokens // if I'm creator
        frozenFunds[marketId][outcome] -= numFillerTokens // if I'm creator
        frozenFunds[marketId][outcome] -= getMyTokensRecievedFromDestruction()
    for redemption of winning share redemptions
        frozenFunds -= tokens received from redemption
    return frozenFunds

getMyTokensRecievedFromDestruction()
    totalTokensFreedFromEscrow = min(numCreatorShares, numFillerShares) * marketDisplayRange
    return portion of totalTokensFreedFromEscrow that's mine based on trade details
```

**Comment by pgebheim** [comment]
@ryanberckmans Moving this into In Progress

**Comment by pgebheim** [comment]
@ryanberckmans Moving this into Sprint 2.

**Comment by pgebheim** [comment]
@ryanberckmans -- Can you make sure to move this into review once those tests are pushed up?
