### ISSUE TITLE
Market List Stats Section

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#9902]
The $0.00 states for volume and so on on the top of the markets list page looks weird. it doesn't fill the entire square it's in. I'm not sure if we have mock states available but we need to adjust that to look good no matter what the content size is.

**Comment by JohnDanz** [comment]
<img width="1606" alt="Screen Shot 2020-12-29 at 8 46 42 AM" src="https://user-images.githubusercontent.com/10524630/103291922-61dfdf00-49b2-11eb-9a56-7a7a224e0ba6.png">
see above

**Comment by JohnDanz** [comment]
<img width="1984" alt="Screen Shot 2021-01-04 at 9 43 06 AM" src="https://user-images.githubusercontent.com/10524630/103552266-415fcb00-4e71-11eb-9f19-3a193d0f2f39.png">
another example of the opposite problem. we should look to simplify numbers ($48.3k instead of $48,305 kind of thing)

**Comment by bconfortin** [comment]
Waiting on mocks

**Comment by Chwy5** [comment]
fixed -closing
