### ISSUE TITLE
update dropdowns

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur#9912]
<img width="720" alt="Screen Shot 2020-12-30 at 9 48 31 AM" src="https://user-images.githubusercontent.com/10524630/103364746-2e6d8500-4a84-11eb-8bf4-5dfd3f98ec56.png">

Our dropdowns need to have checkboxes for multi-select style drop downs and radio buttons for the others.
https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Simplified-UI?node-id=320%3A20417

currently we have just the dropdown text like so:

<img width="554" alt="Screen Shot 2020-12-30 at 9 49 32 AM" src="https://user-images.githubusercontent.com/10524630/103364822-5361f800-4a84-11eb-8577-55e2b623e056.png">

**Comment by bconfortin** [comment]
Scrapped for now.
Multi selection, Radio Icons and Checkbox Icons should only apply for mobile.

**Comment by Chwy5** [comment]
closing not needed
