### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#992]

**Comment by pgebheim** [comment]
@adrake33 -- Here's another item we should add to the docs to describe how the categories work in the UI.

Not sure we have a good place for this now but this sort of stuff (describing how creation Templates would work) needs to go somewhere.

https://github.com/AugurProject/augur/issues/2559#issuecomment-507404609

**Comment by adrake33** [comment]
Sounds good! Will add a section for this.
