### ISSUE TITLE
Graph checkbox fixes

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9930]
https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Simplified-UI?node-id=309%3A2852

![image](https://user-images.githubusercontent.com/39496225/103418652-e89de300-4b8f-11eb-8911-677d062eac5a.png)

- When active the outline should be the same colour as the fill, not grey

- Please add the hover state

**Comment by matt-bullock** [comment]
@JohnDanz sorry I should have been more clear but can you only add the hover state to the inactive state. It looks weird when added to the active state

**Comment by JohnDanz** [comment]
sure thing, will make the adjustment

**Comment by matt-bullock** [comment]
Can you remove the hover on active, no crazy on the grey border on the orange or green

![image](https://user-images.githubusercontent.com/39496225/104058833-a4948900-51f4-11eb-9ffd-e81fbf70e5b6.png)
