### ISSUE TITLE
Summary Ticket for LP tokens issues

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#9949]
current issues:
- LP token earned fees show negative when user adds liquidity.
- add (initial or additional) liquidity modal not showing the user will receive yes/no shares.
- user isn't getting a position after adding liquidity to non 50/50 amms
- initial liquidity on USDC market isn't showing LP token balance in estimate showing "0"
- add additional liquidity to ETH market, in modal estimates "0" LP tokens.

**Comment by bthaile** [comment]
now getting cashValue for add/remove liquidity transactions from graph. Need contract deployment to fix sender which is needed to calculate initial value and derive earned fees.

**Comment by Chwy5** [comment]
Remoed earned fess...rest is fixed - closing
