### ISSUE TITLE
null state for Positions and Liquidity tables

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#9951]
`No positions to show` as  position

1. have same null message for position and liquidity
`no data to show`

2. remove button for liquidity

![image](https://user-images.githubusercontent.com/3970376/103563851-19796300-4e83-11eb-9eb8-4859701290ad.png)

![image](https://user-images.githubusercontent.com/3970376/103563879-29914280-4e83-11eb-8ab4-43184b66e94a.png)

**Comment by matt-bullock** [comment]
Still seeing the button

![image](https://user-images.githubusercontent.com/39496225/103764982-bae7ec80-501c-11eb-8af3-094c0066c6f7.png)
