### ISSUE TITLE
Add tooltip to Average price in order ticket

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#9987]
For tooltip styling please see the design at the bottom of this frame https://www.figma.com/file/6y4nvjfeVZwzwKcoXB0neq/Simplified-UI?node-id=309%3A2852

We need write the copy for this so add a placeholder for now

![image](https://user-images.githubusercontent.com/39496225/103799474-6dcf3f00-504b-11eb-9ed7-58f6c2ce03da.png)

**Comment by matt-bullock** [comment]
not seeing this

**Comment by phoebemirman** [comment]
see new ticket here https://github.com/AugurProject/augur/issues/10028
