### ISSUE TITLE
(waiting on middleware) wire up add/remove estimations 

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#9997]
wire up estimations for when user fills in add liquidity form
1. sets fee
2. sets odds
3. user inputs amount of collateral they want to add.
call `getAmmLiquidity` in contract-calls to get estimation of shares to display in form

wire up estimation for add additional liquidity
1. user inputs amout of collateral they want to add
call `getAmmLiquidity` in contract-calls, ...

wire up estimation for remove liquidity. User indicates the percentage of liquidity they want to exit. 
call `getRemoveLiquidity` to get the breakdown to display in modal.

**Comment by Chwy5** [comment]
Add Liquidity Looks to be updating correctly for usdc but not for ETH

![image](https://user-images.githubusercontent.com/41301809/105356859-f4def400-5bc1-11eb-863c-c675cc66eaf7.png)
